### PR TITLE
LPS-169066 baseline

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started the review

**Comment by alessandromalves** [comment]
Hi @ealonso, I just found a possible regression in the [LocalFile.DatabasePartitioning#CanDeleteCompany](https://testray.liferay.com/reports/production/logs/2022-11/test-1-28/test-portal-acceptance-pullrequest(master)/5194/functional-tomcat90-mysql57-jdk8/23/11/jenkins-console.txt.gz?authuser=0) test.

`ERROR [liferay/scheduler_dispatch-6][ParallelDestination:59] Unable to process message {destinationName=liferay/scheduler_dispatch, response=null, responseDestinationName=null, responseId=null, payload=null, values={GROUP_NAME=com.liferay.blogs.web.internal.messaging.CheckEntryMessageListener, companyIds=[Ljava.lang.Long;@6148c4a7, companyId=43863, groupId=0, DESTINATION_NAME=liferay/scheduler_dispatch, JOB_STATE=com.liferay.portal.kernel.scheduler.JobState@23e4ebff, STORAGE_TYPE=MEMORY_CLUSTERED, JOB_NAME=com.liferay.blogs.web.internal.messaging.CheckEntryMessageListener}}`

Do you think this could be related to PR?

**Comment by ealonso** [comment]
hey @alessandromalves it shouldn’t be related

**Comment by ealonso** [comment]
ci:forward

**Comment by alessandromalves** [comment]
The failures are not related to this PR. See https://github.com/brianchandotcom/liferay-portal/pull/126664

**Pull request closed without merging**
