### PR TITLE
[TS] LPS-126209 

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

could you please check my fix and push it forward?

Moving the resource loading logic to the ContentLayout level will prevent loading portlet resources multiple times.

In the _getPortlets method we will add one portlet only one to the portlet list.

Thanks, Roland

https://issues.liferay.com/browse/LPS-126209

cc @ealonso @pavel-savinov

@ealonso 
I tested the https://issues.liferay.com/browse/LPS-104119 issue and the /o/site-navigation-menu-web/css/main.css resource was loaded 2 times.

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
