### PR TITLE
LPS-142917 menu item display page types tracker map

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-142917

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Pull request closed without merging**
