### PR TITLE
LPS-142961 Uses ResourceURLBuilder

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ealonso, the following error thrown when open Select Structure Field
image

{code}
2022-01-27 17:36:19.280 ERROR [http-nio-8080-exec-7][PortletRequestDispatcherImpl:304] Unable to dispatch request: java.lang.RuntimeException: Use method "setPortletResource" when setting value for "portletResource"
2022-01-27 17:36:19.281 ERROR [http-nio-8080-exec-7][PortletServlet:119] javax.portlet.PortletException: org.apache.jasper.JasperException: java.lang.RuntimeException: Use method "setPortletResource" when setting value for "portletResource"
javax.portlet.PortletException: org.apache.jasper.JasperException: java.lang.RuntimeException: Use method "setPortletResource" when setting value for "portletResource"
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.dispatch(PortletRequestDispatcherImpl.java:307) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:123) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:620) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:636) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doDispatch(MVCPortlet.java:506) ~[portal-kernel.jar:?]
	at com.liferay.asset.publisher.web.internal.portlet.AssetPublisherPortlet.doDispatch(AssetPublisherPortlet.java:397) ~[bundleFile:?]
	at javax.portlet.GenericPortlet.render(GenericPortlet.java:291) ~[portlet.jar:3.0.1]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:309) ~[portal-kernel.jar:?]
	at com.liferay.asset.publisher.web.internal.portlet.AssetPublisherPortlet.render(AssetPublisherPortlet.java:298) ~[bundleFile:?]
	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:127) ~[portal-impl.jar:?]
	at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:58) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:124) ~[portal-impl.jar:?]
	at com.liferay.asset.publisher.web.internal.portlet.filter.AssetPublisherRenderParametersPortletFilter.doFilter(AssetPublisherRenderParametersPortletFilter.java:69) ~[bundleFile:?]
	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:124) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:71) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115) ~[portal-kernel.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
{code}
**Steps to reproduce**

1. Add a web content structure with Text field
2. Add an Asset Publisher to widget page
3. Navigate to the configuration of AP
4. Select the Web Content Article and new Structure in source section
5. Filter by Field
6. Open the Select Structure Field modal

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @ealonso, there is a regression issue.
**Steps to reproduce**

1. Add a web content structure with a Text field
2. Add a dynamic collection for Web Content Article and new structure
3. Switch Filter by Field to yes
4. Open select structure field

**Expected Results:**
The select structure field modal should be rendered well.

**Actual Results:**
The select structure field modal is unavailable. Additionally, the following error is thrown
```
2022-02-09 01:28:13.285 ERROR [http-nio-8080-exec-10][PortletRequestDispatcherImpl:304] Unable to dispatch request: java.lang.UnsupportedOperationException: Requires 3.0 opt-in
2022-02-09 01:28:13.286 ERROR [http-nio-8080-exec-10][PortletServlet:119] javax.portlet.PortletException: org.apache.jasper.JasperException: java.lang.UnsupportedOperationException: Requires 3.0 opt-in
javax.portlet.PortletException: org.apache.jasper.JasperException: java.lang.UnsupportedOperationException: Requires 3.0 opt-in
        at com.liferay.portlet.internal.PortletRequestDispatcherImpl.dispatch(PortletRequestDispatcherImpl.java:307) ~[portal-impl.jar:?]
        at com.liferay.portlet.internal.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:123) ~[portal-impl.jar:?]
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:620) ~[portal-kernel.jar:?]
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:636) ~[portal-kernel.jar:?]
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doDispatch(MVCPortlet.java:506) ~[portal-kernel.jar:?]
        at com.liferay.asset.list.web.internal.portlet.AssetListPortlet.doDispatch(AssetListPortlet.java:126) ~[bundleFile:?]
        at javax.portlet.GenericPortlet.render(GenericPortlet.java:291) ~[portlet.jar:3.0.1]
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:309) ~[portal-kernel.jar:?]
        at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:127) ~[portal-impl.jar:?]
        at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:58) ~[portal-impl.jar:?]
        at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:124) ~[portal-impl.jar:?]
        at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:71) ~[portal-kernel.jar:?]
        at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115) ~[portal-kernel.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
        at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
        at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:63) ~[?:?]
        at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
```

**Pull request closed without merging**
