### PR TITLE
LPS-160439 Open sidebar only if product menu is not visible

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
Hi @sandrodw3! There is a regression issue, the page editor is not shown to users with update permission. Could you please have a look at? Thanks!

We have to create a new site role, it's explained on the video.

https://user-images.githubusercontent.com/72820234/186003146-ac867ea2-2f3e-4e77-ba92-26c2d61bbad1.mp4

**Comment by sandrodw3** [comment]
> Hi @sandrodw3! There is a regression issue, the page editor is not shown to users with update permission. Could you please have a look at? Thanks!
> 
> We have to create a new site role, it's explained on the video.
> 
>  Roles.-.Liferay.DXP.-.22.August.2022.mp4

Hey @ozysouza! I think it's not possible that issue is related to this PR 😅 can we create a separate ticket?

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/122031

**Comment by ozysouza** [comment]
ci:close

**Pull request closed without merging**
