### PR TITLE
LPS-118321 Avoid destroying editor twice

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by veroglez** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @veroglez, your last commit causes a regression issue. Can not edit inline content when change to other language.
See
Video

**Comment by p2kmgcl** [comment]
https://github.com/Tim-Cao/liferay-portal/pull/344

**Comment by p2kmgcl** [comment]
ci:close

**Pull request closed without merging**
