### PR TITLE
LPS 133940

### PR DESCRIPTION
**Pull request by victorg1991**
This is a follow-up pr after this brian message: https://github.com/brianchandotcom/liferay-portal/pull/103089#issuecomment-859696694

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
