### PR TITLE
LPS-142557 Collection Display for Objects does not display all instances, even when "Display All Collection Items" is checked 

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
It works great! Thanks!

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Fixed semantic versioning [here](https://github.com/liferay-echo/liferay-portal/pull/6540)

**Pull request closed without merging**
