### PR TITLE
[TS] LPS-176530 Web content assets are not anonymized when the user data is deleted

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
By deleting a user, the web content's asset entry is not anonymized. This is because the asset entry's `classPK` is the ID of the journal article **resource**, not the journal article.

Proposed Solution
========
It is overriding `BaseJournalArticleUADAnonymizer`'s `fetchAssetEntry` method so that it fetches the asset entry of the journal article's `ResourcePrimKey`. 

Steps to Verify
========
Please see the linked LPS for reproduction steps.
https://issues.liferay.com/browse/LPS-176530

Thank you and best regards,
István

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
The failures are not related to this PR. See https://github.com/brianchandotcom/liferay-portal/pull/130885

**Pull request closed without merging**
