### PR TITLE
LPS-125534 Avoid using a boolean trap

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Since the failure case is an unstable one not related to change in PR and in order to not clog up ci resources I pushed directly to BChan.
See https://github.com/brianchandotcom/liferay-portal/pull/97585

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
