### PR TITLE
LPS-149676 Improve accessibility for selected items in Miller Columns

### PR DESCRIPTION
**Pull request by BarbaraCabrera**

### CODE REVIEW

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:relevant

**Comment by BarbaraCabrera** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
Hi @BarbaraCabrera, can you please check if those errors are related to your PR? Thanks!

cc LiferayEchoBot

**Comment by veroglez** [comment]
👏 Looks really nice!!

**Comment by veroglez** [comment]
ci:forward

**Review by veroglez — APPROVED** [review]

**Pull request closed without merging**
