### PR TITLE
LPS 182526

### PR DESCRIPTION
**Pull request by robertoDiaz**
I've added this new option in notifications in order o avoid customers perceive it as a bug.
Right now, it isnot possible to see the new added elements of asset publisher in the notifications portlet.

Most of portlets use thjis option, so it seem reasonable to have this web notification also in this portlet.

It is triggered as current emails (once a day by default) so the configuration is the same.

Captura de pantalla 2023-04-24 a las 13 39 51

Captura de pantalla 2023-04-24 a las 13 40 31

I've also add a link to browse to the page containing the asset publisher.

cc: @ealonso , @jkappler , @dacoulsalr

https://issues.liferay.com/browse/LPS-182526

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Hi @liferay-echo,

Any update about this?

A customer is waiting for an answer about this (if this is included or discarded)

Thanks in advance!

**Comment by ealonso** [comment]
Hey @robertoDiaz,

You send this one 2 days ago, please give us a chance. 

It is not the only priority for us, if it is so important scalate it, pr wait for the normal workflow.

Regards,
Eudaldo

**Comment by robertoDiaz** [comment]
No problem @ealonso 

I only wanted to inform you about the origin of the issue (and to know if you discard it, just to tell the customer the fastest I can to handle their expectations).

 Thanks!

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
