### PR TITLE
[TS] LPS-134739 | Sites allows language paths as friendly URLs

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-134739
Thank you!

The validation of the implementation of the friendly URL conflicting with language key matches was based on the LayoutLocalServiceHelper.ValidateFriendlyURL. Similarly, we should not allow language keys or language paths as friendly URLs on sitegroups, just like we do not allow them on pages.

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The failure case is unrelated to changes in PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/103740

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
