### PR TITLE
LPS-194258 Adjust styles for the Locked Pages configuration

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-194258

cc: @veroglez Thanks!!! :heart:

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
I have sent together two LPS in order to prevent merge conflicts as the second LPS is moving the code to another module.
Please see: https://github.com/liferay-echo/liferay-portal/pull/13420

**Pull request closed without merging**
