### PR TITLE
[TS] LPP-47459 -> LPS-175068 Display Date in the web content structure is auto reset to blank

### PR DESCRIPTION
**Pull request by TaiPhamLR**
Motivation
=======
This work solves the problem reported in the ticket https://issues.liferay.com/browse/LPS-175068
cc: @locpham97

Proposed Solution
========
What we did to solve this problem.
we tweak `JournalPortlet.es.js` for condition checking `articleId`

Steps to Verify
========
1. Create a web content structure
2. Open "Edit Default Values" of the created structure
3. Update the display date to the specific date and submit.
4. Reopen "Edit default values"

Actual result: The display date is blank
Expected result: Display date changed

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
Hey @TaiPhamLR 

It seems that solution doesn't cover all the cases, if you do this:

1. Create a structure
2. Edit default values
3. Change name 
4. Publish
5. Edit default values again

At that point the display date should be left empty since no changes has been made

**Comment by victorg1991** [comment]
could you take a look please?

**Comment by locpham97** [comment]
Thanks for your helps.
I will update my solution against.
Thanks,
Loc

**Comment by locpham97** [comment]
Hi @victorg1991 ,
I updated my solution. Could you recheck it ?
Thanks, 
Loc

**Comment by victorg1991** [comment]
Thanks @locpham97  I have resent it here https://github.com/liferay-echo/liferay-portal/pull/11142

**Pull request closed without merging**
