### PR TITLE
[TS] LPS-127057

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This PR tries to solve a collision between urlTitles and friendlyURLEntries in Web Contents by ensuring that copied Web Content have their respective FriendlyURLEntries created at the time of being copied.

Could you please review it?

Thanks in advance

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Thanks for the changes @aszlopap and @dacousalr. Submitted to Brian [here](https://github.com/liferay-echo/liferay-portal/pull/4950)

**Comment by ruben-pulido** [comment]
ci:close

**Pull request closed without merging**
