### PR TITLE
LPS-167147 Getting Expando from SiteMenuNavigationItem evaluates to null

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-167147)

Navigation Menu Items can benefit from the Expando framework in order to use custom fields. Still, these are not available when rendering navigation menus and evaluate to null. This is because we are not using the correct class when rendering the items: we are using NavItem and not SiteNavigationMenuNavItem which is the one that fills the expando map correctly.

## Proposed solution

Instead of using NavItem in our template handler for navigation menu, use SiteNavigationMenuNavItem

## Change summary:

* Create an interface in API so that the template handler has access to it
* Modify existing class so that it implements the new interface
* Let template handler use the interface for the variable, instead of NavItem class
* Integration test for template rendering

## Test Scenario

* Navigate to Configuration - > Custom Fields in Control Panel
* Click on "Sites Navigation Menu Item" and create an entry and name it "Test Field"
* Select "Dropdown" and populate required Field Name and Values and click "Save"
* Go back to home and navigate to Site Builder -> Navigation Menus and create a menu (name it "Test Menu")
* Populate the menu with at least one item
* Go back to home and on the side menu navigate to Design -> Templates -> Widget Templates
* Create a "Menu Display Template"  named "Test ADT" with the following:

```
<#if entries?has_content>
  <#list entries as navigationEntry>
    <#assign expandoAttributes = navigationEntry.getExpandoAttributes() />
	${expandoAttributes["Test Field"]}
  </#list>
</#if>
```

* Navigate back to the home page and edit the home page. Add a Menu Display widget and configure it to use "Test Menu" and "Test ADT"
* Save and publish the page & view the homepage
* Display navigation menu custom field attribute values

## Notes

* A freemarker error will be thrown when the user isn't logged in, this is because of permission checking in expando, and also happens with layouts

 
expando

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:echo

**Comment by jkappler** [comment]
ci:test:echo

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:echo

**Review by lfbesada — APPROVED** [review]
Amazing as always ❤️

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:forward

**Comment by alessandromalves** [comment]
The failures are not related to this PR.

**Pull request closed without merging**
