### PR TITLE
LPS-135964

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-135964

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Thanks @rodrigopaulino, LGTM I've resent it here with a few minor changes: https://github.com/liferay-echo/liferay-portal/pull/5426 :) 

I am just wondering why the json format needed for this import is different than the api response, shouldn't be the same format?

**Comment by rodrigopaulino** [comment]
> Thanks @rodrigopaulino, LGTM I've resent it here with a few minor changes: #5426 :)
> 
> I am just wondering why the json format needed for this import is different than the api response, shouldn't be the same format?

Hey, @victorg1991. Thanks for reviewing.

When we create a Structure using Data Engine's taglib, we are not only choosing the fields that go into it, but the layout as well. Retrieving just the fields is not sufficient to create a Structure. We needed to append the layout to the json as well, otherwise the Structure would not be rendered. You can find an example of one valid json in the code by the name of "valid_data_definition.json".

Hope this clarifies.

**Pull request closed without merging**
