### PR TITLE
LPS-202251 New design for the list of structures in Configuration > Structures

### PR DESCRIPTION
**Pull request by jkappler**
To the reviewer: sending on top of LPS-202106, so please only review commits related to LPS-202251 

@p2kmgcl, @veroglez

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
It is very beautiful todo esto :smiling_face_with_tear:

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
