### PR TITLE
LPS-168190 Simplify

### PR DESCRIPTION
**Pull request by ealonso**
From: https://github.com/liferay-echo/liferay-portal/pull/10314

Hi Team,

Motivation
=======
[LPS-168190](https://issues.liferay.com/browse/LPS-168190)
Having a Web Content refer itself could cause infinite recursion in ddm templates.

Proposed Solution
========
By forwarding the referring article's resourcePrimKey to the Item Selector, we can disable selectablility for the referer article
I'm unsure if any extra CSS to differentiate this referer article would be needed or what would be suitable for it.

Steps to Verify
========
1. Create a Web Content Structure with a Web Content field
2. Create a Web Content from this Structure and save it
3. Edit this Web Content and press Select for the Web Content field

**Expected behaviour:** The current Web Content should not be selectable to eliminate the change of infinite loops
**Actual behaviour:** The current Web Content is selectable

References to existing code (if applies)
========
A similar solution was used for Related Assets in https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-browser-web/src/main/java/com/liferay/asset/browser/web/internal/display/context/AssetBrowserDisplayContext.java#L327

Alternative Solutions that were discarded
========
I've discarded filtering the results in the 
- business logic layer: because of performance reasons and manipulating the results would make the result list less maintainable.
- service layer: While Search could be filtered with the correct search context having an exclusion term added, The DisplayContext uses multiple Service calls, that would need an extra parameter to work. I've opted to avoid creating new service methods.

Cheers,
Balázs

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
Hi @ealonso @balazssk, there is a regression. Could you please have a look at?

1. Add a Web Content structure with Web Content field
2. Add a Web Content based on new Structure
3. Click on the Select button on Web Content field

The select button doesn't work and there is an error on the browser console

`0:2 TypeError: Failed to construct 'URL': Invalid URL
    at new Iframe (0:1:28022)
    at Ug (0:2:52386)
    at ui (0:2:69160)
    at Ol (0:2:106651)
    at fk (0:2:91302)
    at Zj (0:2:91227)
    at Lj (0:2:88576)
    at 0:2:47050
    at U.unstable_runWithPriority (0:2:121544)
    at fg (0:2:46759)`

**Comment by ealonso** [comment]
Hey @ozysouza @balazssk,

I'll take a look at it, since it is related with my changes

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
