### PR TITLE
[TS] LPS-156378 Inject corresponding portlet request and portlet attributes in case when they don't exist yet

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
RenderRequest is frequently used to create URLs through AssetRenderers. Fragments don't have access to a renderRequest, which hinders the transition of specialised templates from widget pages to content pages
[LPS-156378](https://issues.liferay.com/browse/LPS-156378)

Proposed Solution
========
Using the logic implemented in [LPS-123118](https://issues.liferay.com/browse/LPS-123118) for Content Display Objects we can generate a renderRequest for the ContentObjectFragment

Steps to Verify:
----------------

1. Go to Content & Data -> Web Content and switch to Structures tab
2. Create a new structure called "test structure" with a text field
3. Switch to "Templates" tab and create a new template linked to the structure "test structure" called "test template" and set the freemarker code to: `Hello ${renderRequest}`
5. Switch to "Web Content" tab, click "+" and choose the new structure
6. Add random content to the article and click Publish
7. Go to the homepage
8. Click the Edit icon to enter the page edit mode
9. From the "Fragments and Widgets" menu drag the "Content Display" fragment and drop it on the page
10. Configure the Fragment to display the article

Thanks,
Balázs

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @balazssk 
I would like to understand the need to have a renderRequest in a fragment entry. Is it needed just to get the JournalArticle URL? 
Please could you explain it?
Thanks in advance!
Regards

**Comment by balazssk** [comment]
Hi @lfbesada ,
Yes, the main concern here is reliable generation of localised JournalArticleURLs using [AssetRenderer#getURLViewInContext](https://github.com/balazssk/liferay-portal/blob/master/portal-kernel/src/com/liferay/asset/kernel/model/AssetRenderer.java#L161)
Given that renderRequest was part of template contexts of Journal Display Portlets, this might also be a backward compatibility help for migrating from widgets to fragments.

**Comment by lfbesada** [comment]
Hi @balazssk 
Thanks so much for the explanation.
The content-display fragment is not a portlet so it should not have a portlet request. Additionally, the article's localized URL is already accessible in the template using
field-name.getFriendlyURL() so this use case has an easy and better-performing work-around.
Because of that, I have to refuse this fix.
Regards

**Pull request closed without merging**
