### PR TITLE
LPS-179841 Replace ddmStructureKey document field pre-filtering by the classTypeId field

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-179841

@david-gutierrez-mesa @liulukiwi @tim-cao @alessandromalves @rafaellajordao

This PR removes the ddmStructureKey field from JournalArticle's document in the index. Therefore, at least, [this assertion](https://github.com/liferay/liferay-portal/blob/552b422030fce581ab8962f793ffba5649fb0a39/portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructureee/search/searchexperiences/Blueprints.testcase#L4155-L4158) can no longer be made. I don't know if we should delete it or replace it with another one, could you please take a look at it? Thanks in advance ❤️

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
