### PR TITLE
LPS-152839 AssetEntryItemSelectorView

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to task](https://issues.liferay.com/browse/LPS-152839)

Echo Team has been trying to improve its item selectors by replacing legacy views with the new item selector framework. One of these views relates to Asset Browser

## Proposed solution

Change Asset Browser Portlet so that it uses the new item selector framework, and adapt usages

## Change summary:

* Change ItemSelectorViewDescriptorRenderer to render the item selector view

## Test Scenarios (all)

* All tests scenarios should include ordering and viewing with either list, table or cards

## Test Scenario 1

* Create some web contents
* Add a new web content, and go to info panel in edit view
* Go to Related Assets Section and click on Select (select web content from the list)
* Select some web contents and press done
* The items should be available in related assets section

## Test Scenario 2

* Create some web contents
* Go to Collections and add a new manual collection
* Select "All types" and save
* Click on the select button and select web content from the list (for example)
* Select some web contents and press done
* The items should be added to the collection

## Test Scenario 3

* Create some web contents
* Create a new page and add a web content display to it
* Click on configuration, and select a web content to view
* Click on the web content
* The web content should be available in configuration

## Test Scenario 4

* Manual entries in Asset Publisher Widget should still work

## Notes

* Item selector has a bug where if a vertical or horizontal card with a custom row checker, it will throw a NPE, that's why the existing VerticalCard is used
* Legacy view for selecting assets is maintained, since it's needed in Asset Publisher Portlet, it will most likely be removed here: https://issues.liferay.com/browse/LPS-167394
* Sorting is included, but not filtering, see https://issues.liferay.com/browse/LPS-159228

Scenarios

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:echo

**Comment by ealonso** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/125730

**Pull request closed without merging**
