### PR TITLE
LPS-138102 - Fragments used in collection display are not given unique fragment ids

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @victorg1991

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1267401_404

**Comment by ruben-pulido** [comment]
ci:reevaluate:1267401_404

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/6048

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
