### PR TITLE
LPS-135812  Add permissions action

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-135812

LPS-135812 Add permissions action

LPS-135561 Standardize success delete message in templates portly

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/5231

**Pull request closed without merging**
