### PR TITLE
LPS-137272 Update test

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reevaluate:1317401_130

**Comment by liulukiwi** [comment]
HI @jkappler , the issue is same as https://github.com/liferay-echo/liferay-portal/pull/5502, and here's the steps you can check it in local if it is fixed:

1. Add a display page template Content Type selected for Category
2. Add a Collection Display to display page template
3. Select the Items with "This Category collection provider in Collection Display" 
4. Add a Heading to Collection Display and Map the Title field to editable field  and publish
5. Add a vocabulary
6. Add a category and select the display page template as specific display page template
7. Add a web content with the category
8. Add a blogs entry with the category
9. Go to created vocabulary and click View Display Page
10. Assert the assert are listed as web content title. blog entry title

**Comment by jkappler** [comment]
Hi @liulukiwi, thanks! Will try again today since it was ordered correctly when I tested it :(

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by liulukiwi** [comment]
ci:test:bundle

**Comment by jkappler** [comment]
@david-gutierrez-mesa, @liulukiwi, I changed poshi test. We are going to order by modified date DESC (so that the same results show in different languages)

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@ealonso

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:stop

**Comment by liulukiwi** [comment]
Pushed to BChan directly:
https://github.com/brianchandotcom/liferay-portal/pull/105658

**Pull request closed without merging**
