### PR TITLE
LPS-121885 Migrate v2 usages in layout/layout-portlets-web

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

**Test plan**:
- Navigate to **Site Builder** > **Widgets**
- Make sure you can filter and order Widgets

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
cc @ambrinchaudhary @markocikos @jonmak08

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
