### PR TITLE
LPS-193149: Add endpoints to Sites API

### PR DESCRIPTION
**Pull request by peerkar**
- Story: https://liferay.atlassian.net/browse/LPS-193149
- Related: https://liferay.slack.com/archives/CL9RTSZ52/p1692691856324109 

This PR adds to Sites API endpoints required by https://liferay.atlassian.net/browse/LPS-126745.

Changes in a nutshell:

- Site schema aligned with the headless-admin-user-impl Site schema
- Endpoints for:
   - List sites user has access to (excluding global and personal sites)
   - Get site by ERC
   - Get site by ID
   - Get site by friendlyURLPath

The logic and utils were for the most parts copied from headless-admin-user-impl 

The existing logic and endpoints of Sites API were not harmed.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Hi @peerkar 
The "apps:headless:headless-site:headless-site-test:compileTestIntegrationJava" failures seem related to the PR. 
Can you take a look?
Thanks!

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:stop

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by peerkar** [comment]
ci:reevaluate:1287401_7540

**Pull request closed without merging**
