### PR TITLE
[TS] LPS-122606

### PR DESCRIPTION
**Pull request by jonathanmccann**
The listener for the CSS class is created here - https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/modal/Modal.js#L408-L416

Please let me know if there are any issues or questions.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
LGTM! thanks @jonathanmccann 🚀

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
