### PR TITLE
LPS-161145 Reload the page instead of posting the form

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @victorg1991, the root cause is reverted https://github.com/brianchandotcom/liferay-portal/pull/122015
Is this PR still required or not?

**Comment by victorg1991** [comment]
If the root cause is reverted this is not needed @Tim-Cao :) Closing it

**Pull request closed without merging**
