### PR TITLE
[TS] LPS-152517 - asset queries fail in Oracle if ordering by title

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @liferay-echo team!

https://issues.liferay.com/browse/LPS-152517

This is a fix for an issue where, when using an Oracle DB, certain portlets (e.g. Most Viewed Asset and Highest Rated Asset) will fail to load. This is due to them attempting to order by an asset entry's title. In [LPS-132521](https://issues.liferay.com/browse/LPS-132521) the title field was changed to a CLOB. Since it is a known limitation that you cannot an Order By a CLOB, we need to cast it to the equivalent of a VarChar which is the solution seen here. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
