### PR TITLE
[TS] LPS-187161

### PR DESCRIPTION
**Pull request by dacousalr**
Motivation
=======
This is a PR that aims to fix the FriendlyURLException that is thrown when publishing to Live after locales having been changed in the following way:
- The original default locale is no longer available.
- The new default locale was not one of the original available locales.

Proposed Solution
========
The approach taken is to pick the original urlTitle if we are in the middle of publishing to Live.

Steps to Verify
========

1. Create a new site
2. Establish Catalan and Spanish as site languages making Catalan as the default Language
3. Enable local Staging
4. Create a new Web Content filling only the Catalan fields
5. Publish to Live
6. Change the locales to Spanish, French making French as the default language
7. Publish to Live selecting all the contents to publish

Expected behavior: The publishing result is successful.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
