### PR TITLE
[TS] LPS-144543 Collections cannot show tagged contents from other sites

### PR DESCRIPTION
**Pull request by joseluisbango**
Hi team @liferay-echo,

When setting the tags and categories we need to use the groups that have been configured, instead of the current group.

See [LPS-144543](https://issues.liferay.com/browse/LPS-144543) for details.

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by joseluisbango** [comment]
ci:test:sf

**Comment by joseluisbango** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Hi @joseluisbango,
Thank you very much for the fix, it works great!
Regards.

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
