### PR TITLE
LPS-112746 Fix test, moves className creation setUpClass method to avoid com.liferay.portal.kernel.exception.NoSuchClassNameException

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
cc: @jPince

**Comment by ealonso** [comment]
Hey @jpince @david-gutierrez-mesa @manoelcyreno,

After taking a look the code this broken tests since to be caused by some changes on Core Infra, maybe we need to change the relevant tests for core infra suite, What do you think?

Regards,
Eudaldo.

**Comment by jpince** [comment]
@ealonso it's actually https://github.com/liferay/liferay-portal/commit/5d4065166b77e21a5f6b053431580cc3beb5f9ae that's needed. It didn't sync to upstream until about 3 hours ago.

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Pull request closed without merging**
