### PR TITLE
[TS] LPS-164273 Remove AssetUtil.filterCategoryIds to prevent filtering out results

### PR DESCRIPTION
**Pull request by evibudai**
Hi Team,

https://issues.liferay.com/browse/LPS-164273
THIS TICKET IS MARKED AS BREAKING CHANGE

**Issue:**
Web contents were filtered out in the Asset publisher by their categories, for users who didn't have the role with the permission to see that category. 

**Solution:**
As discussed here: [PTR-3409](https://issues.liferay.com/browse/PTR-3409?focusedCommentId=2781690&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2781690) "Category permissions should not be used to drive the visibility of a given web content with that category assigned."
I implemented the solution suggested on [PTR-3396](https://issues.liferay.com/browse/PTR-3396?focusedCommentId=2777040&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2777040).

I tested this solution in my local environment on master and it worked as expected. Both the admin and the users (with different roles) could see the web contents.

Please review my PR!

Best regards,
Évi

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
@evibudai, could you please also add tests for it?

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by evibudai** [comment]
> @evibudai, could you please also add tests for it?

Yes, I'm working on it. Sorry for the delay. I was on PTO and coming back, I had to prioritize other tasks.

**Comment by ealonso** [comment]
Hey @evibudai,

Thanks you very much!! Those tests are really helpful.

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/10283

**Comment by jkappler** [comment]
Thanks a lot @evibudai!

**Pull request closed without merging**
