### PR TITLE
LPS-171484 Apply same logic to the other method

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, the following error thrown in server console, would you mind having a look at?
`2022-12-24 11:41:43.725 ERROR [Portal Dependency Manager Component Executor--1][DefaultJournalArticleLayoutDisplayPageProvider:56] bundle com.liferay.journal.web:5.0.113 (1162)[com.liferay.journal.web.internal.layout.display.page.DefaultJournalArticleLayoutDisplayPageProvider(10313)] : findField: Suitable but non-accessible field _assetHelper in class com.liferay.journal.web.internal.layout.display.page.JournalArticleLayoutDisplayPageProvider, subclass of component class com.liferay.journal.web.internal.layout.display.page.DefaultJournalArticleLayoutDisplayPageProvider`

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128108

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
