### PR TITLE
LPS-139352 It should not be necessary

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1317401_485

**Comment by Tim-Cao** [comment]
Hi @ealonso, no need to run. I'm going to send to Brian directly

**Comment by ealonso** [comment]
@Tim-Cao thanks!!

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/107291

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
