### PR TITLE
LPS-120941 Check permissions when executing shortcuts

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
~ASDOIAKSÑDJAHUIGNAMSDPOJAA ÑOSDK~

I mean, I'm going to rebase this onto master and check locally

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Rebase then resend. See https://github.com/liferay-echo/liferay-portal/pull/2364

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
