### PR TITLE
LPS-202505 Use custom drag preview for mouse DnD

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-202505

@sandrodw3
cc @veroglez

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by alessandromalves** [comment]
The related failures ([comparison with acceptance routine here](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1701188671511&testrayRunIdA=2465464541&testrayRunIdB=2466758846)) only needed a test fix. See https://github.com/liferay-echo/liferay-portal/pull/14543

**Comment by alessandromalves** [comment]
ci:close

**Pull request closed without merging**
