### PR TITLE
LPS-165392 | [HR_131,150] Make the pages have only one and descriptive h1 tag

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-165392

### CODE REVIEW

**Comment by ozysouza** [comment]
ci:forward

**Comment by ozysouza** [comment]
Hi @veroglez @rebsilva, there is a regression issue on Kaleo Forms Admin, I didn't understand how the changes are causing it, but 100% sure it's caused by the changes.

It is missing the created, update and review task on the fourth steps. Please see the video below

https://user-images.githubusercontent.com/72820234/196455062-e63c2055-735c-477f-af8f-ea5de0384cff.mp4

Expected:
Selection_003

**Comment by rebsilva** [comment]
Thank you for your review [ozysouza](https://github.com/ozysouza)! I will take a look at this now to see what's happening

**Comment by veroglez** [comment]
Hi @ozysouza @rebsilva! I found the issue and added a commit fixing it. @ozysouza could you check it and see if everything is ok? See https://github.com/liferay-echo/liferay-portal/pull/9970

**Comment by rebsilva** [comment]
@veroglez that's amazing!! Thank you so much for this! :tada: I'll keep a look at the new PR, let me you if I can do anything to help :blush: Thanks again!

**Pull request closed without merging**
