### PR TITLE
[TS] LPS-144086 | "View" button appeared in the Asset Publisher when using URL to reach it

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?

https://issues.liferay.com/browse/LPS-144086

Thank you!

----

I Inverted the logic of the viewSingleAsset parameter in the JSPs. From now in the parameter is by default true and set for false when necessary this way the canonical URLs will not show the "view >>" link and will reduce the appearance of the parameter in the URL as well.

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
Hi @bakayattila and @ealonso, no regression issues found according to [ci:test:echo](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1597525525&testrayRunId=1597526732)

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
