### PR TITLE
LPS-183734 Get current user if the creator doesn't exit anymore

### PR DESCRIPTION
**Pull request by georgel-pop-lr**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
Hey @georgel-pop-lr,
You should send this one to @liferay-lima.
Regards,
Eudaldo.

**Comment by ealonso** [comment]
Hey @georgel-pop-lr,

As I can see we are using:

```
PortalUtil.getValidUserId(getCompanyId(), getUserId())
```

In other places like JournalArticleImpl and KBArticleImpl.

Could you please update the logic to change FragmentCollectionImpl to use it instead of changing PortletFileRepositoryImpl?

**Comment by georgel-pop-lr** [comment]
> Hey @georgel-pop-lr,
> 
> As I can see we are using:
> 
> ```
> PortalUtil.getValidUserId(getCompanyId(), getUserId())
> ```
> 
> In other places like JournalArticleImpl and KBArticleImpl.
> 
> Could you please update the logic to change FragmentCollectionImpl to use it instead of changing PortletFileRepositoryImpl?

Done, my doubt is that is using guest user https://github.com/liferay/liferay-portal/blob/a28f39f8e80e02582bac1a98892c2d2f1767d461/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L6055

Is there no problem in doing that in an administration area?

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
