### PR TITLE
LPS-122483 Wrong persistence call, it should by companyId

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Since the failure task is semantic versioning for com.liferay.portal.kernel.security.permission and in order to not clog up ci resources I pushed directly to BChan.
See https://github.com/brianchandotcom/liferay-portal/pull/95225

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
