### PR TITLE
LPS-145940 Fix journal articles user inconsistencies

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-145940

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
