### PR TITLE
LPS 186577 Migrate SegmentsEditor collapses to ClayPanel

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
In order to generalize components we're trying to use as many Clay components in the portal as posible. This PR contains the code to replace the html displayed by the CriteriaSidebarCollapse.js with the ClayPanel component.
https://issues.liferay.com/browse/LPS-186577

### CODE REVIEW

**Comment by Stephy6** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
I would like to review this today :)

**Review by claraizquierdo — CHANGES_REQUESTED** [review]
Hi @Stephy6 ,

just a few comments:

- We can remove the styles of `.sidebar-collapse-groups` if it is not being used anymore.
- The margins in the panel content are bigger now. I would be great to keep them as similar as they were.
- When we search for a property, the badge indicating the number of results per panel has been lost
Captura de pantalla 2023-06-14 a las 15 33 24

**Comment by Stephy6** [comment]
> Hi @Stephy6 ,
> 
> just a few comments:
> 
> * We can remove the styles of `.sidebar-collapse-groups` if it is not being used anymore.
> * The margins in the panel content are bigger now. I would be great to keep them as similar as they were.
> * When we search for a property, the badge indicating the number of results per panel has been lost
>   Captura de pantalla 2023-06-14 a las 15 33 24

Understood, thank you @claraizquierdo

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by Stephy6** [comment]
ci:test:relevant

**Review by claraizquierdo — CHANGES_REQUESTED** [review]
Hi @Stephy6 ,

the problem with the badge has been solved but I still see these two issues:

- We can remove the styles of .sidebar-collapse-groups if it is not being used anymore.
- The margins in the panel content are bigger now. I would be great to keep them as similar as they were.

**Review by claraizquierdo — CHANGES_REQUESTED** [review]
Hi @Stephy6 , the styles now look much better :) The only strange thing is that now the sidebar has horizontal scroll:

Captura de pantalla 2023-06-21 a las 12 13 51

**Comment by ealonso** [comment]
Hey @sandrodw3 @Stephy6 @claraizquierdo,
Could you please let me know why we need custom css for a ClayComponent? It shouldn't be necessary, and if we need it, we should ask Clay Team to fix it, or at least take this behavior into account.

**Comment by Stephy6** [comment]
> Hey @sandrodw3 @Stephy6 @claraizquierdo, Could you please let me know why we need custom css for a ClayComponent? It shouldn't be necessary, and if we need it, we should ask Clay Team to fix it, or at least take this behavior into account.

Because the ClayPanel has its own elements inside, like the panel-header, the badge or the icon and the only way to change their styles are by css. It is necessary to keep the design as it was.

**Review by claraizquierdo — APPROVED** [review]
Hi @Stephy6 , everything is working fine 🎉 

As @ealonso said, I believe que can get rid of more CSS if we use the property displayType="unstyled" for ClayPanel. That is more work because you will need to adapt all the paddings and margins and I'm sure that the look and feel will change a little bit. So @sandrodw3 and @Stephy6 , what you prefer :)

**Comment by ealonso** [comment]
We can do it in a follow up pr

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by alessandromalves** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by sandrodw3** [comment]
@Stephy6 it seems frontend tests are failing, could you please fix them?

**Comment by sandrodw3** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/12584

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
