### PR TITLE
LPS-1351172 Delete unused classes

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:forward

**Comment by jkappler** [comment]
@Tim-Cao, unsure if the tests are bacause of the pull

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/5186

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
