### PR TITLE
LPS-171754 Success message is missing after copy OOTB fragment into Untitled Set

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-171754)

When copying a fragment to a collection, the success message is not shown in firefox, it works well in chrome and safari

## Change summary:

* Don't use multi session messages to render the success message, but a toast when the modal is closed

## Test Scenario

* Go to fragments
* Click on the kebab for a contributed fragment and select copy To
* Click save
* The fragment is copied and the success message is shown

copy

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
