### PR TITLE
[Request review] LPS-183716 Remove LayoutClassedModelUsageRecorder

### PR DESCRIPTION
**Pull request by JanisZhang**
Hi team,

We are working on a task to avoid using method reference (convert to field reference or sercveTracker/serviceTrackerList... instead). we found that there is no impl of `LayoutClassedModelUsageRecorder`, the only usage was removed by https://issues.liferay.com/browse/LPS-174322. This PR is for removing `LayoutClassedModelUsageRecorder` and its related usages.

Reference: https://liferay.slack.com/archives/CL9RTSZ52/p1683163970150079 

Please review and leave your comment.

Thanks,
Janis

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by JanisZhang** [comment]
ci:test

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @JanisZhang,

SemancticVersioning is failing, Could you please fix it and update the pr?

thanks!!

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
Hi @ealonso ,

Force-pushed.  Thanks!

**Comment by JanisZhang** [comment]
Hi @ealonso ,
Can I forward this one? :)

**Comment by ealonso** [comment]
Hey @JanisZhang 
You need to execute baseline also for layout-taglib

**Comment by JanisZhang** [comment]
ci:test:sf

**Comment by JanisZhang** [comment]
ci:test:relevant

**Comment by JanisZhang** [comment]
thanks!! @ealonso

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
