### PR TITLE
LPS-163433 Unnecessary calls to JournalArticle.getContent, when we really need DDMFormValues objects

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-163433

In [LPS-129058](https://issues.liferay.com/browse/LPS-129058) the JournalArticle xml was extracted to the DDM* database tables.

After that LPS changes, the JournalArticle.getContent now calls the DDM API to get the DDMFormValues object and generate the XML, see:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/model/impl/JournalArticleImpl.java#L226-L254

But we have several calls to JournalArticle.getContent that parses the content XML to generate the DDMFormValues so in the end we are doing unnecessary transformations:

- getContent: gets the DDMFormValues => Fields => and generates the XML calling journalConverter.getContent
- the method that calls getContent, needs the DDMFormValues or the Fields, so it parses the XML to generate them

To avoid this:

1. In https://github.com/liferay-echo/liferay-portal/commit/529ce6ea5cbb10c577ebb164d432b264bb63c467 I have created a new `JournalArticleImpl.getDDMFormValues()` method that calls the **DDMFieldLocalServiceUtil.getDDMFormValues** method
2. In https://github.com/liferay-echo/liferay-portal/commit/25f69a79da1462a5ad6df724154f22a60fba1d81 I have applied this method in all getContent calls where we really need the DDMFormValues object
3. I have added two commits to fix some test problems, see https://github.com/liferay-echo/liferay-portal/commit/a9331d7a8253a7ff55ec87f4f776fa16d264df2d and https://github.com/liferay-echo/liferay-portal/commit/f157d26c24bf87da1129a0798c9a3d48ea92b18d

Let me know if you have any question.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:echo

**Comment by ealonso** [comment]
Hey @jorgediaz-lr,

We are taking a look to tests failures in echo and in relevant routine, if everything is ok, we are going to forward your pr.

**Comment by jorgediaz-lr** [comment]
ok, thank you!

**Comment by david-gutierrez-mesa** [comment]
Send manually to https://github.com/brianchandotcom/liferay-portal/pull/123691

**Comment by david-gutierrez-mesa** [comment]
ci:close

**Pull request closed without merging**
