### PR TITLE
LPS-140916 Also put inside a div so that it doesn't break because of the tooltip in site admin

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
@robertoDiaz, @Tim-Cao

**Comment by jkappler** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
kudos @jkappler, @Tim-Cao and @liferay-echo 

❤️

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Poshi is required to update since changes introduced by https://github.com/liferay-echo/liferay-portal/pull/6431/commits/0cf73dd57cdc5c9d9017075450f304666d4ff731

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/6439

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
