### PR TITLE
[TS] LPS-124173 Add folderId parameter to the iteratorURL

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @liferay-echo 

could you please check my change and push it forward?

Thanks, Roland

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/3128

**Pull request closed without merging**
