### PR TITLE
[TS] LPS-126629 | Moving a menu item tree can potentially corrupt the order values at the level where the root menu item is inserted

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?

https://issues.liferay.com/browse/LPS-126629

Best,
Attila

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Thanks for the fixes @dacousalr @bakayattila!

Sent to Brian [here](https://github.com/liferay-echo/liferay-portal/pull/3519) with new tests that fail prior to the fix and succeed with the fixes.

**Comment by dacousalr** [comment]
Thanks so much to you, @ruben-pulido!

**Pull request closed without merging**
