### PR TITLE
LPS-146056 Hide Display Page panel in Depots

### PR DESCRIPTION
**Pull request by adolfopa**
https://issues.liferay.com/browse/LPS-146056

It is not possible to create Display Pages in Depots, so it doesn't
make sense to display the panel. Hide it both for depots and the
global scope.

The bug is reproducible in 7.3.x as well, so this needs to be
backported if you're ok with it.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:stop

**Comment by liulukiwi** [comment]
ci:forward

**Pull request closed without merging**
