### PR TITLE
LPS-122314 Missing permissions for LayoutPageTemplateEntry when upgrading from 6.2

### PR DESCRIPTION
**Pull request by Mikellorza**
https://liferay.atlassian.net/browse/LPS-122314

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
Hi @Mikellorza 
Could you please add an integration test for this?
Thanks in advance!
Regards

**Comment by Mikellorza** [comment]
@lfbesada  integration tests added

Thanks

**Comment by lfbesada** [comment]
Hi @Mikellorza :wave: 
I have some concerns about this implementation:
1. The upgrade process is recreating the permissions of all the templates, which should not be done for performance. The query should be adjusted to only return the identifiers of those that need to be added.
2. I have verified that the permissions of these roles on the templates can be modified and removed manually by the user. With a solution like the one you propose, How do we distingue the case of a template in which the permission was not added when it was created (because comes from 6.2 or below) from one template in which a user has expressly removed that permission? I'm afraid this solution would override that user's decision.
What do you think?

**Comment by lfbesada** [comment]
@Mikellorza 
Please see
1. The related PTR Chaparro comment: https://liferay.atlassian.net/browse/PTR-2111?focusedCommentId=1813211
2. The previous PR comments: https://github.com/dacousalr/liferay-portal/pull/291

**Pull request closed without merging**
