### PR TITLE
LPS-126254, LPS-126257, LPS-126280 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-126254
https://issues.liferay.com/browse/LPS-126257
https://issues.liferay.com/browse/LPS-126280

This is only for master.

@david-gutierrez-mesa
@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
See https://github.com/david-gutierrez-mesa/liferay-portal/pull/108

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
