### PR TITLE
[TS] LPS-117494

### PR DESCRIPTION
**Pull request by ChrisKian**
[**LPS-117494**](https://issues.liferay.com/browse/LPS-117494)

**Previous Pull Request**
https://github.com/ChrisKian/liferay-portal/pull/244

From @jesseyeh-liferay: 

> **Changelog**
> * Use indexer post-processor approach to unescape content as suggested in [PTR-1842](https://issues.liferay.com/browse/PTR-1842?focusedCommentId=2205410&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2205410)
> * Allow `&nbsp;` to be unescaped

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:forward

**Comment by lipusz** [comment]
Hey Guys, @ChrisKian  @jesseyeh-liferay @jkappler 

One question: wouldn't it have been simpler to modify the `doGetSummary` method of `JournalArticle`? :thinking:

**Comment by jkappler** [comment]
Hi @lipusz, please feel free to send us a pull request with your approach. We are always happy to improve/simplify what we have.

Thanks!

**Pull request closed without merging**
