### PR TITLE
[TS] LPS-158448 | Translated FriendlyURL incorrectly redirects to the Home page after changing the language

### PR DESCRIPTION
**Pull request by bakayattila**
hi Team,
Could you review this?

https://issues.liferay.com/browse/LPS-158448

Best,
Attila

------

Related PTR: [PTR-3192](https://issues.liferay.com/browse/PTR-3192)

When comparing the redirect URL with the target locale layout firendlyURL the second could never become true if the friendlyURL is actually translated. My modification uses the current locale for the isGroupFriendlyURL because the redirect URL contains the URL related to the current locale, not the target locale based on my tests.

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
LGTM! @bakayattila Thanks for the fix! Regards

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
