### PR TITLE
LPS-137335 HTML Fragment Editor Modal unisolate the modal so ace edit…

### PR DESCRIPTION
**Pull request by pat270**
…or styles still apply

https://issues.liferay.com/browse/LPS-137335

@victorg1991 This is a temp solution to fix this bug. I'll send another pr isolating the modal once https://github.com/liferay/clay/pull/4223 and https://github.com/liferay/clay/pull/4225 are released and brought in. Feel free to close this if a fix isn't needed immediately.

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
Thanks for the fix :) I think it is fine to merge this for now, there are a couple of test that depend on this so we can re-enable them

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
