### PR TITLE
LPS-147669 adding equals method needed for cache validation when result is empty

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1307401_2297

**Review by lfbesada — APPROVED** [review]
Hi @linolaoj 
Thanks for the PR, LGTM!
Regards

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
