### PR TITLE
LPS-188026 Move focus to the proper node when updating AI Creator modal

### PR DESCRIPTION
**Pull request by p2kmgcl**
The idea of this PR is to properly move the browser focus when the AI Creator modal is updated. The order of precedence is:

1. If there is a loading alert, move the focus to it.
2. Otherwise, if there is an error alert, move the focus to it.
3. Otherwise, if there is some result message, move the focus to it.
4. Otherwise, do nothing.

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
@victorg1991 ready :smile:

**Comment by victorg1991** [comment]
P'alante :clap:

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward:force

**Pull request closed without merging**
