### PR TITLE
LPS-135805 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-135805

This is only for master.

@veroglez

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @veroglez, the failure case is unrelated to changes in PR.

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The semantic verisoning issue is unrelated to changes in PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/104549

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
