### PR TITLE
LPS-125853 [Bug] Widget section doesn't appear when an AB testing is running in other experience

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

When the user has several experiences but one of them has an A/B Test, some sidebars hide (Fragments and Widgets and Page Design Options) because the user cannot change the page during an active A/B Test. To do this, we check the permission `LOCKED_SEGMENTS_EXPERIMENT`.

**Steps to reproduce it**

* Connect Liferay Portal DXP with Analytics Cloud (AC)
* Create a Page (cp)
* Create an Experience (exp1)
* Create an A/B Test for Default experience
* Click Edit to edit the page and change between Default and exp1 experience to see the bug

**Solution**

In the file `sidebarReducer.js` we specify that the default panel ID is `fragments-widgets`:

```
const DEFAULT_PANEL_ID = 'fragments-widgets';
```

In this case, the experience (the one with the A/B Test) doesn't have that panel available and it's not able to render the first one available (Page Structure).

The solution proposed is create a function that retrieves the `panel` and `sidebarPanelId` of the first available panel if the selected sidebar panel ID is not found.

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:forward

**Pull request closed without merging**
