### PR TITLE
LPS-115388 Uses company in ThemeDisplay

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
@john-co as I supposed I think we need to update some poshi tests here due to markup changes. Could you please take a look? Thx!

**Comment by john-co** [comment]
created task to update the global menu portlet path

**Comment by zhangyan0701** [comment]
@john-co Sorry, I didn't get a chance to look into this today, will do tomorrow.

**Comment by zhangyan0701** [comment]
Resent in [liferay-echo#1143](https://github.com/liferay-echo/liferay-portal/pull/1143)

**Pull request closed without merging**
