### PR TITLE
LPS-138156 fixes

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-138156

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @lfbesada, The Asset content type is available in display page template creation, Is that expected?
image

**Comment by lfbesada** [comment]
> Hi @lfbesada, The Asset content type is available in display page template creation, Is that expected?
> image

Hi Tim, thanks for the warning!🤗

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
