### PR TITLE
[TS] LPS-136871

### PR DESCRIPTION
**Pull request by jonathanmccann**
Currently, all available `classNameIds` will be retrieved and all associated templates would be exported and imported. After these changes only the classes selected by the user in the UI of the export/import screen will be exported or imported.

If there are any questions or concerns please let me know.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Hi @jonathanmccann ,
Good job, it's looks great! Thank you very much for the fix!
Regards

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
