### PR TITLE
LPS-121077 Slow performance of predictive search in Asset Publisher filters (in configuration) by Asset Category

### PR DESCRIPTION
**Pull request by sammonsjl**

### CODE REVIEW

**Comment by dbagrey** [comment]
ci:test

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
ci:close

**Comment by pavel-savinov** [comment]
Resent here https://github.com/liferay-echo/liferay-portal/pull/2703

**Pull request closed without merging**
