### PR TITLE
LPS-183533 Refactor className and classPK in SegmentsExperiment

### PR DESCRIPTION
**Pull request by YurenaC**
Motivation
=======
The APIs for Experience Personalization are using className and classPK for fragmentsEntityLinks, that later are layout and layout plid.

Product Team Echo is changing this, as it is a bit confusing.

COMMITS:
=======
- LPS-183533 ClassNameId and ClassPK, have always the same values, which is Layout.class.getName and Layout.plid, so, replace unnecessary columns with plid for SegmentsExperiment
- LPS-183533 Update custom sql queries
- LPS-183533 Adds upgrade process
- LPS-183533 Update queries in experiment finder
- LPS-183533 BuildService
- LPS-183533 Remove classPK usages and changing signatures in order to use plid instead
- LPS-183533 buildService
- LPS-183533 Tests Update
- LPS-183533 Removing unnecessary params and updating usages
- LPS-183533 Baseline
- LPS-183533 Removing classPK and classNameId usages in frontend side

### CODE REVIEW

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:forward

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:forward

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/12283

**Pull request closed without merging**
