### PR TITLE
LPS-198041 [Tests] Allow page to display input fragments in read-only mode

### PR DESCRIPTION
**Pull request by jkappler**
https://liferay.atlassian.net/browse/LPS-198041

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by lfbesada — APPROVED** [review]
:heart_eyes: Nice end-to-end integration test :clap:

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:stable

**Comment by liulukiwi** [comment]
Hi @jkappler , [pmd-jdk8/0/0](https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/292576//consoleText) failed for:
```
BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:15011: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-portal/build-test-batch.xml:7318: 1 PMD violation(s) were found.

PMD VIOLATION: /opt/dev/projects/github/liferay-portal/modules/apps/layout/layout-test/src/testIntegration/java/com/liferay/layout/taglib/test/RenderLayoutStructureTagTest.java:610 > Do not call Assert#fail improperly. (PMD Rule: AssertFailJUnitRule)
```
can you take a look? thanks!

**Comment by jkappler** [comment]
Thanks @liulukiwi!

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
