### PR TITLE
LPD-17017 Add test

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:echo

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:2535040444

**Comment by jkappler** [comment]
@victorg1991, failures don't seem related to the PR. Will try a normal fw again

**Comment by victorg1991** [comment]
fw to brian since the test failures are not related https://github.com/brianchandotcom/liferay-portal/pull/146972

**Pull request closed without merging**
