### PR TITLE
LPS-172876 Use underscore for directory names

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, there is a regression issue. Would you mind having a look at? The page editor cannot load.
**Step to reproduce**

1. Edit the Home page

**Actual Results**
The page editor cannot load.
The following error is thrown in browser console.

image

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
Hey @p2kmgcl, some regressions found. Steps to repdroduce:

1. Create a Content Page
2. On the Edit Mode Selector button, select "Content Editing"

Actual result:
On the left sidebar, the Page Content tab will not appear

https://user-images.githubusercontent.com/69062082/213277914-64054fea-9d31-4289-b38f-5f07e0928c57.mp4

Expected result:
On the left sidebar, the Page Content tab will appear

https://user-images.githubusercontent.com/69062082/213277954-2566803b-5594-4321-a5e0-9285ce16bbba.mp4

**Comment by alessandromalves** [comment]
1. Create a Content Page
2. Add a Heading fragment to page
4. Go to Page Content Tab on Sidebar
5. Click on the Edit Text button

Actual result:
The browser tab is open

https://user-images.githubusercontent.com/69062082/213285695-cacb4bee-d5c3-4b53-b3e3-d414f473d867.mp4

Expected result:
The Edit Text button is disabled

https://user-images.githubusercontent.com/69062082/213285782-9ed71022-dfb6-4ced-8ea1-5510e493e554.mp4

**Comment by p2kmgcl** [comment]
Thanks @alessandromalves! I just fixed that

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
