### PR TITLE
LPS 156964

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Error message when deleting an unpublished experience. Also problems deleting an experience with less fragments than the default.
[Link to story or ticket](https://issues.liferay.com/browse/LPS-156964)

Proposed Solution
========
Get the necessary fragmentEntryLinks when deleting an experience

Steps to Verify:
----------------
First scenario:
- Create an Experience
- Navigate to somewhere else in portal
- Delete the experience

Second scenario:
- Add a card fragment to the home page
- Create an experience
- Delete the card fragment for the experience and publish
- Go to the view mode of the home page and select the experience created in step 2
- Click on the edit icon to edit the experience
- Delete the experience

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
Thanks @claraizquierdo good job :)

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:reevaluate:1257401_5092

**Comment by ozysouza** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:forward

**Pull request closed without merging**
