### PR TITLE
LPS-137148 Hide fragments from item actions (topper)

### PR DESCRIPTION
**Pull request by sandrodw3**
Only commits from LPS-137148 need to be reviewed, as LPS-136712 and LPS-136709 are already merged 😛

### CODE REVIEW

**Comment by victorg1991** [comment]
Ready to be merged, @sandrodw3 is going to rebase and add a minor commit 👏

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
Hi @david-gutierrez-mesa, @liulukiwi 🙂
I'm not sure if the failing tests are related or not, I relaunched ci:forward. Could you please take a look in case they fail again? Thanks!

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
