### PR TITLE
[Technical Support] LPS-121041 Creating URL element on Navigation Menu with other language

### PR DESCRIPTION
**Pull request by rijema**
Click [here](https://issues.liferay.com/browse/LPS-121041) to see the LPS

### CODE REVIEW

**Comment by rijema** [comment]
ci:test:sf

**Comment by rijema** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
