### PR TITLE
LPS-166433, LPS-166436, LPS-166439, LPS-166440, LPS-166442, LPS-166443, LPS-166444 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-166433
https://issues.liferay.com/browse/LPS-166436
https://issues.liferay.com/browse/LPS-166439
https://issues.liferay.com/browse/LPS-166440
https://issues.liferay.com/browse/LPS-166442
https://issues.liferay.com/browse/LPS-166443
https://issues.liferay.com/browse/LPS-166444

This is only for master.

@david-gutierrez-mesa

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
