### PR TITLE
LPD-35649 Liferay Experience Selector Color is not visible

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
> [!NOTE]
> Not needed to test the styles

## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPD-35649)

### Changes

Adapt styles to see the text

## Steps to reproduce

1. Start a clean bundle of Liferay DXP QR 2024.Q2.2
2. Edit the home page on the default site and create a new experience named test
3. Publish the home page

image

### CODE REVIEW

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:stop

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
