### PR TITLE
LPS-125750 Upgrade LayoutTable classNameId to 0 from null

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

https://github.com/IstvanD/liferay-portal/pull/135
@MarcellGyopos

Thank you and best regards,
István

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
