### PR TITLE
LPS-175222 OOTB Fragments are missing on portal with Oracle

### PR DESCRIPTION
**Pull request by jkappler**
[Link to ticket](https://issues.liferay.com/browse/LPS-175222)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@shuyangzhou, same problem that we had last time with DB2 but with oracle with time around. Wasn't able to make it work, so I'm reverting the changes and try to come up with another solution

**Comment by jkappler** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Thanks! ❤️

**Comment by lucasperj** [comment]
@jkappler , tested with the revert **locally** and the errors with Oracle are now fixed. Thanks. 

cc/ @Tim-Cao

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
