### PR TITLE
LPS-119565 Fix proptypes

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:Close

**Comment by victorg1991** [comment]
ci:close

**Comment by victorg1991** [comment]
Excuse me sir case sensitive

**Comment by victorg1991** [comment]
Sent here https://github.com/liferay-echo/liferay-portal/pull/2038

**Pull request closed without merging**
