### PR TITLE
LPS-140434

### PR DESCRIPTION
**Pull request by ealonso**
Web_Content_-_Staging_site_-_Liferay

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ealonso, there is a regression issue found.
**Step to reproduce**

1. Add a new site then enable local live
2. Add two widget pages
3. Add a navigation menu
4. Add two page type items in navigation menu
5. Navigate to a widget page
6. Choose the navigation menu in Menu Display widget
7. Publish to live
8. Back to Navigation Menus admin in staging site
9. Edit the navigation menu
10. Delete one widget page
11. Publish to live
12. Navigate to the live site

*Expected Results*
The deleted item shouldn't be shown in Menu Display

*Actual Results*
The deleted item is still shown in Menu Display

**Comment by ealonso** [comment]
Hey @Tim-Cao,
Do you test it without my changes? I didn't change nothing related with Menus, I've only removed a warning message.

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ealonso, the <em> tags are shown on tooltip.
image
Would you mind having a look?

**Comment by jkappler** [comment]
see https://github.com/liferay-echo/liferay-portal/pull/11572

**Pull request closed without merging**
