### PR TITLE
LPS-185045 Add Javadoc to SegmentsEntryItemSelectorReturnType

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-185045

See: https://github.com/brianchandotcom/liferay-portal/pull/135050#issuecomment-1554206832  @brianchandotcom my bad, thanks for fixing it! Once fixed the typo I am adding the Javadoc here because I think it is useful to find easily the expected JSO.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
cc: @ealonso @Stephy6

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
