### PR TITLE
LPS-144158 Fragment viewport textAlign property is not exported

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-144158

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1287401_1355

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
