### PR TITLE
LPS-173474 Delete based on document fields

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,
Can you please review?

Motivation
=======
https://issues.liferay.com/browse/LPS-173474
Indexer can't delete the search document based on a null object

Proposed Solution
========
Use fields from the search document to avoid null looked-up objects

Steps to Verify
========
N/A

References to existing code (if applies)
========
This pattern is used in [JournalHelperImpl ](https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/internal/util/JournalHelperImpl.java#L258-L261) as well

Cheers,
Balázs

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Hi @balazssk 
Thanks for the fix!
LGTM 🎉 
Regards

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
Some tests aborted prior to running but the failures are not related to this PR. See https://github.com/brianchandotcom/liferay-portal/pull/129193

**Pull request closed without merging**
