### PR TITLE
LPS-167545 Fix control menu markup and move it to a java class

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
Hi @victorg1991, there are some regression issues to take care. Could you please have a look at?

1. The back Icon is missing throughout the Portal
2. The pencil icon is missong on content page at view mode
3. The Toggle Control button is missing on widget pages


https://user-images.githubusercontent.com/72820234/201160818-b3534391-b39e-40b3-879a-0b282d5dbcf5.mp4

**Comment by victorg1991** [comment]
Thanks @ozysouza I'll take a look :)

**Comment by victorg1991** [comment]
should be fixed now @ozysouza  :)

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/126125

**Comment by ozysouza** [comment]
ci:close

**Pull request closed without merging**
