### PR TITLE
LPS-150991

### PR DESCRIPTION
**Pull request by holatuwol**
## Motivation

https://issues.liferay.com/browse/LPS-150991
https://issues.liferay.com/browse/PTR-3050

## Proposed solution

Searching in the source code, we found several dozen instances where something called getStaticResourceURL and getContextPath, without also calling getPathProxy.

```bash
git ls-files -- '*.java' | xargs grep -Fl 'getStaticResourceURL' | xargs grep -Fl 'getContextPath()' | xargs grep -L 'getPathProxy()'
git ls-files -- '*.jsp*' | xargs grep -Fl 'getStaticResourceURL' | xargs grep -Fl 'getContextPath()' | xargs grep -L 'getPathProxy()'
```

I asked the TSE to open [PTR-3050](https://issues.liferay.com/browse/PTR-3050) in order to get a perspective on how to best fix the issue, and the conclusion was that we should fix all instances where we see the pattern appear, rather than fix the API itself to automatically account for potentially incomplete parameter values (as is done with ComboServlet).

After preparing the pull request https://github.com/liferay-core-infra/liferay-portal/pull/964, the core infrastructure team recommended that we split up the pull request by reviewer. According to the DXP Product Teams page, Echo is responsible for Asset Framework, Sites, and Page Administration, and so we're sending some of the changes here.

## Steps to verify

The TSE was not able to figure out how to reproduce the issue in all the instances where the pattern appears, but they were able to identify steps to reproduce for all of the issues fixed in this pull request. They have shared a Google Drive document describing what we need to access in the portal in order to see the issue introduced by that file having an erroneous pattern.

https://docs.google.com/document/d/1dmiP23za68PAbbvxp-GrTO_EkRQ6Di0Z1-cqlDZXNts/edit

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Hi @sontruongces @holatuwol 
SF is complaining that the commit messages don't start with LPS-
Can you fix it and resend?

Thanks!

**Pull request closed without merging**
