### PR TITLE
LPS-130706 Migrate asset categories selection modals

### PR DESCRIPTION
**Pull request by markocikos**
Hey @liferay-echo ,

JIRA ticket: https://issues.liferay.com/browse/LPS-130706

Forward from https://github.com/liferay-frontend/liferay-portal/pull/976 . This is the first of three `asset` PRs, that have been on hold for a while, waiting for GA release.

Notes:
- I renamed `ItemSelectorDetails` to `ItemSelectorAddCategory`, as it is very much specific to this case.
- I moved all code related to 'add category' feature from more general `SelectCategory` to `ItemSelectorAddCategory`. @jonmak08 When you modified content dashboard in https://github.com/liferay-tango/liferay-portal/pull/1129, there was no need for completely unrelated code to break. This way we will have better separation.
- We are adding a wrapper around buttons. This is to match Clay buttons markup.

Test case 1:
1. Categorization > Categories > create a Vocabulary
2. Test deleting a vocabulary (see gif)
after2

Test case 2:
1. Have a Vocabulary
2. Web Content > new Basic Web Content > 'Select' next to Vocabulary
3. Test selecting categories (see gif)
4. Test creating a new category (see gif)
after1

/cc @kresimir-coko

### CODE REVIEW

**Comment by p2kmgcl** [comment]
@markocikos I am trying test case 2 and I think there might be something wrong: after selecting some categories from the vocabulary, the do not appear in the text input (it is always empty).

I tried clean deploy and a fresh ant all, and the error keeps happening (and it is working on master).

Can you have a look, please?

**Comment by markocikos** [comment]
@p2kmgcl I added https://github.com/liferay-echo/liferay-portal/pull/4436/commits/29221bf9a9d55f4636929d4ec74d94f2bfe7cc66 with the fix. This is a revert of a SF change, after https://github.com/liferay-frontend/liferay-portal/pull/976#discussion_r617380920. @kresimir-coko is looking sus for industrial sabotage. But alas, shame on me for not retesting :disappointed:

**Comment by p2kmgcl** [comment]
:O I suspected that @kresimir-coko might have some kind of evil plan. You can't trust anyone :cry:

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by markocikos** [comment]
@p2kmgcl The failure in https://github.com/liferay-echo/liferay-portal/pull/4436#issuecomment-833355455 is on the feature of this PR, but I don't think this PR is causing it. It looks like the test is checking if the card is selected, without expanding and selecting it first. This PR does not touch the inner logic of tree selection, we are only handling callback from it differently.

Can your QA please check this?

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/4477

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
