### PR TITLE
LPS-180303 Fix horizontal scroll in Browser Tree

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
The user should be able to read the node names using the horizontal scroll.
[Link to story or ticket](https://issues.liferay.com/browse/LPS-180303)

Proposed Solution
========
Reverts commit 5b2df08510d69c26b32e5dac6056ba4f07eb4580 in which the bug was introduced.

Steps to Verify:
----------------

1. Go to Home page and click Edit
2. Add some fragments inside other fragments (for example, a grid inside a container and a heading inside the grid)
3. In the left side bar click on Browser option
4. Open all the nodes in the tree

Screenshots (optional):
-----------------------
The bug:

Captura de pantalla 2023-03-30 a las 13 26 38

Fixed:
Captura de pantalla 2023-03-30 a las 17 07 10

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
