### PR TITLE
LPS-132227 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-132227

This is only for master.

@veroglez
@p2kmgcl

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @veroglez, Could you investigate deeply? There are still some issues.
For mapping item selector:
1. The Change Item angle right button won't be shown if doesn't select the mapping field.
2. The empty dropdown list is shown when remove selected assets if select the mapping field.

For all item selector (exclude color selector):
1. The dropdown list is still shown when the select modal popups. Additionally, the dropdown list is still shown after select the item.

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
Hi @Tim-Cao, answering your questions:
For mapping Item Selector:
1. This is correct. If the content has not been mapped, the Change Item option will not display anything. The options will only be shown when the content has been mapped.
2. You're right, the dropdown menu should close when the item is removed. I will take a look at it 👀 
3. This is also correct. Until the content has been mapped (a Field is selected), the text is not updated.

For all item selector (exclude color selector):
1. This is not correct. Let me check it 👀 .

**Comment by p2kmgcl** [comment]
I am going to split this PR and send now just the code refactor (no UI or feature changes).
I will send later another PR with the rest of the code.

**Comment by p2kmgcl** [comment]
This is it https://github.com/liferay-echo/liferay-portal/pull/4727

I will create a separated task to make the UI changes

**Pull request closed without merging**
