### PR TITLE
LPS-159329 Move AppHooks inside context providers

### PR DESCRIPTION
**Pull request by p2kmgcl**
Backend review: check https://github.com/liferay-echo/liferay-portal/pull/9185/commits/4dad04f0ec4a8f7b115988bd0a10a938da2f768d

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
cc @jkappler

**Comment by p2kmgcl** [comment]
ci:test:relevant

I am so confident about this that I am running tests again

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. I will manually foward it.

**Comment by ozysouza** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/121399

**Comment by ozysouza** [comment]
ci:close

**Pull request closed without merging**
