### PR TITLE
LPS-127040 - Fail to upgrade content page within publication

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:reevaluate:1212004_7509

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:reevaluate

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:stop

**Comment by ruben-pulido** [comment]
https://github.com/liferay-echo/liferay-portal/pull/3638

**Pull request closed without merging**
