### PR TITLE
LPS-127986 Path data definition before posting

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @liferay-echo 

This is a quick fix so that copying structures works for Journal, but what we really need is a new API method in the DE services to clone a data definition.

/cc @jeyvison

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by jeyvison** [comment]
Hi @adolfopa ! Thanks for that. Yeah , for now we should go with the Command but i'll tlak with @luiz_jardim and we will we create a story so data engine can support that. Thanks a lot :)

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
