### PR TITLE
LPS-151303 Index the content of private pages

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-151303

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/7759

**Comment by ealonso** [comment]
ci:stop

**Pull request closed without merging**
