### PR TITLE
LPS-191805 Enable component according to the FF LPS-183727

### PR DESCRIPTION
**Pull request by Mikellorza**
subtask: https://liferay.atlassian.net/browse/LPS-191805

Description
------
The purpose of this PR is to Enable CustomAssetDisplayPageFriendlyURLResolver that is responsible for resolve object display pages. Some of teammates have been issues to resolve object display pages because they had not enabled the component CustomAssetDisplayPageFriendlyURLResolver using scr:enable com.liferay.asset.display.page.internal.portlet.CustomAssetDisplayPageFriendlyURLResolver, so, to avoid that problems I think and IMHO that is better to enable it according to the FF.

cc: @victorg1991

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
:D :clap:

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @Mikellorza and @jkappler, This PR is required to Poshi update. Let me know when it is ready.

**Comment by Tim-Cao** [comment]
Hi @Mikellorza, the poshi update is sent in this PR. https://github.com/liferay-echo/liferay-portal/pull/13048

**Comment by Mikellorza** [comment]
Hi @jkappler ,

As we talked yesterday the other approach was not good for the new ways of FF's, so, I have changed the class to return null for the methods and now it looks fine.

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
