### PR TITLE
LPS-146836 Unify the Saved notice of the Style Book and the Page Editor

### PR DESCRIPTION
**Pull request by BarbaraCabrera**

### CODE REVIEW

**Comment by sandrodw3** [comment]
When rebasing your master, you can do:
```
git pull upstream master --rebase
git push origin master
```
So you avoid the "Merge..." commit 🥰

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Hi @BarbaraCabrera, could you fix the sf issue?

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:relevant

**Review by veroglez — APPROVED** [review]

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reevaluate:1257401_1678

**Comment by ealonso** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward 😔

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7241

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
