### PR TITLE
[TS] LPS-146712 Add missing LayoutRevision records for content pages

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @liferay-echo ,

Since the fix for [LPS-125755](https://issues.liferay.com/browse/LPS-125755) has been implemented, LayoutRevision records are created for content pages, to show their status in each Site Page Variation (LayoutSetBranch). Before this fix, there were no LayoutRevision records and all content pages were displayed in all variations.
The issue comes up when we upgrade from an older version. Since there are no LayoutRevision records found, the page versioning logic creates one with "Incomplete" status, and thus, these layouts are not displayed anymore.
First, I tried to solve it with an upgrade step, but it turned out that there's no way to do this without updating multiple existing schema versions. For this reason, I implemented it with an "implicit" upgrade, embedded into the `_getLayoutRevision(..)` method. This way, we can make sure that all content pages will be fixed that haven't been opened yet.
Unfortunately, for the ones that have been opened already, we can't decide whether the "Incomplete" status is intended or not. Those layouts can only be recovered manually, if needed.

Please review my changes.

Thanks,
Vendel

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @vendeltoreki 
Thanks for the pull request! ❤️ 
I am afraid I don't figure out when you say: _"I tried to solve it with an upgrade step, but it turned out that there's no way to do this without updating multiple existing schema versions."_ 
Please, could you explain a bit more about the inconvenience to use an upgrade step? 
Thanks
Regards

**Comment by vendeltoreki** [comment]
Hi @lfbesada ,

Sorry for the late response. This was my first idea of the upgrade step implementation: https://github.com/liferay/liferay-portal/compare/master...vendeltoreki:LPS-146712-fix .
I tried to add the new upgrade step in master version into [LayoutServiceUpgrade](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-service/src/main/java/com/liferay/layout/internal/upgrade/LayoutServiceUpgrade.java) as `1.2.3`.
However, when I would backport this, to 7.3.x, [LayoutServiceUpgrade](https://github.com/liferay/liferay-portal-ee/blob/7.3.x/modules/apps/layout/layout-service/src/main/java/com/liferay/layout/internal/upgrade/LayoutServiceUpgrade.java) doesn't have 1.2.2 (which was introduced by [LPS-136644](https://issues.liferay.com/browse/LPS-136644)). My guess is that it's not really backportable to 7.3. If I added 1.2.2 as a dummy step here, then the real 1.2.2 would have never been executed, when someone upgrades from 7.3 to 7.4.
So the solution would be to "push" the steps up by 1 micro version:
```
master:
registry.register("1.2.1", "1.2.2", new DummyUpgradeStep());
registry.register("1.2.2", "1.2.3", new LayoutRevisionUpgradeProcess(...));
registry.register("1.2.3", "1.2.4", new LayoutSEOUpgradeProcess(_layoutLocalService));

7.3.x:
registry.register("1.2.0", "1.2.1", new UpgradeLayoutAsset(...));
registry.register("1.2.1", "1.2.2", new LayoutRevisionUpgradeProcess(...));

```

This way, in some cases, the already existing `LayoutSEOUpgradeProcess` would be executed twice (which should be ok, as upgrade steps should be able to run multiple times, without causing any trouble).

My problem is that the same thing has to be done on the 7.2 backport as well. Adding even more dummy steps just to have this one executed.

Also, this upgrade step is already a little bit late, since as I mentioned, it doesn't fix those Layouts, that have been opened at least once.

That's why I went with this "implicit upgrade" solution, that fixes this corner-case scenario.

It would have been more straightforward if `LayoutSEOUpgradeProcess` bumped a minor version instead of a micro version. Then we would have some space to insert new steps between the existing ones.

E.g.:
```
master:
registry.register("1.0.1", "1.0.2", new DummyUpgradeStep()); // for 7.2
...
registry.register("1.2.1", "1.2.2", new DummyUpgradeStep()); // for 7.3
registry.register("1.2.2", "1.3.0", new LayoutSEOUpgradeProcess(_layoutLocalService));
registry.register("1.3.0", "1.3.1", new LayoutRevisionUpgradeProcess(...)); // new step

7.3.x:
registry.register("1.0.1", "1.0.2", new DummyUpgradeStep()); // for 7.2
...
registry.register("1.2.0", "1.2.1", new UpgradeLayoutAsset(...));
registry.register("1.2.1", "1.2.2", new LayoutRevisionUpgradeProcess(...)); // new step

7.2.x:
registry.register("1.0.0", "1.0.1", new UpgradeLayoutAsset(...));
registry.register("1.0.1", "1.0.2", new LayoutRevisionUpgradeProcess(...)); // new step

```

**Comment by lfbesada** [comment]
Hi @vendeltoreki,
Thanks for the details.
We have been analyzing the problem you mention and we think that the appropriate solution, in this case, is to apply differentiated solutions. 
On the one hand, in master, the appropriate solution is the upgrade process that would solve all cases. Given the difficulty of the backport, for 7.3 and 7.2, an implicit upgrade could be applied like the one you propose in this PR, although perhaps you could try to optimize it by replacing the dynamic query with an Adhoc service method (thanks!!! @dacousalr ❤️ ).
I hope this helps you.
Could you please send us another solution based on an upgrade process?
Thanks!
Regards

**Pull request closed without merging**
