### PR TITLE
LPS-197807 Applying the Workflow permission logic in the Journal Article permisson to fix the view permission bug by the copied URL

### PR DESCRIPTION
**Pull request by vngoliveira**
Hi team!
I have this [LPP-50732](https://liferay.atlassian.net/browse/LPP-50732), but the root issue component, by our investigation, is in the Journal Article since it isn't considering the view permission of the user when he tries to access the URL.
We worked to propose a solution to you. Could you look at it and see if it is viable for the component?

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
Hey @vngoliveira,

Could you please fix the source formatting error?

**Comment by jkappler** [comment]
@vngoliveira, when sending, can you also update LPS status and follow the workflow? It's not verified. 

Thanks!

**Comment by vngoliveira** [comment]
ci:test:sf

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by vngoliveira** [comment]
ci:test:stable

**Comment by jkappler** [comment]
Hi @vngoliveira, will start to checking this PR today. I'm unsure about the solution, so it's going to take a while.

Thanks!

**Comment by jkappler** [comment]
Hi @vngoliveira, after checking this out, and talking to @lfbesada, the change is too risky. You are changing basically how the permission for web contents works across all the portal.

We would suggest handling this logic either in layout-type-controller-display-page were the permissions for the object are changed. Or change JournalArticleInfoItemPermissionProvider which could also be tricky, but less risky.

So overall, we cannot accept this solution. If you want to raise it up, you can also create a PTR of type solution guidance so that we can take a closer look.

Thanks!

**Pull request closed without merging**
