### PR TITLE
LPS-179670 Do not allow to drag a disabled element

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
This is the second PR of this bug because the bug was still reproducible
[Link to story or ticket](https://liferay.atlassian.net/browse/LPS-179670)

Proposed Solution
========
Do not allow to drag a disabled element and set enabled again when the action has finished

Steps to Verify:
----------------
1. Check the ticket video

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142792

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
