### PR TITLE
LPD-1625 Web Content and Documents Display Pages are not properly imported

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-1625

I'm sorry for such a big PR. I can't help it as the tests must be in the same PR.

If this PR passes Echo's review it must also be reviewed by The Content Management Team regarding changes to FileEntryInfoItemFormVariationsProvider and JournalArticleInfoItemFormVariationsProvider

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Some of the failed test are related so I am working on adap them

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:report:19037147

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
I have only rebased and added the baseline that was generated after the rebase

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
@lfbesada

**Pull request closed without merging**
