### PR TITLE
LPS-172332 Cannot predefined an expiration date for web content

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to task](https://issues.liferay.com/browse/LPS-172332)

There was a change recently where the display date is now no longer mandatory for default values of a given DDM Structure. Because of this, if a user unchecks the "never expire" option, it's not reflected when saving

## Change summary:

* Remove the constraint for forcing the expire and review dates to be disabled if no display date is selected
* Add integration tests

## Test Scenario

* Create a new structure
* Edit the default values
* Uncheck the option "never expire" and provide a date
* Save and edit again

expire

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
