### PR TITLE
LPS-172368 Reset Category

### PR DESCRIPTION
**Pull request by Marina-Gouveia**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
Hi @Marina-Gouveia, thanks again for sending the PR.

When I try to follow the steps in the ticket I get another error:  

`com.liferay.journal.exception.ArticleVersionException: Version 1.0 is not the same as 1.1 `

Can you please check the steps again? Also, checking the code when setting the service context, the categories shouldn't be removed unless the user sends them

```
if (assetCategoryIds != null) {
    serviceContext.setAssetCategoryIds(
    ArrayUtil.toArray(assetCategoryIds));
}
```

I'll leave it on hold for now.

Hope to hear from you.

Thanks!

**Comment by Marina-Gouveia** [comment]
I adjust the correct steps for reproducing, this error that you mentioned occurs when:
1. Creating web content 
2. Submit for publication 
3. Edit 
4. Save
 In this case two ids in the database are created, one version is 1 and another version is 1.1, but both use similar resourcePrimKey. But when:
1. Creating web content
2. Save
3. Edit
4. Submit for publication
Only one id is created, so this error does not occur. In case this is not the expected behavior,  do you think we should open another LPS for that?
About the flow when the categorization is defined on request, I noticed that the fix influences the behavior, so I'll correct it and send the PR again.

**Comment by jkappler** [comment]
ok @Marina-Gouveia, thanks, will wait for your changes

**Comment by Marina-Gouveia** [comment]
Hi @jkappler 
I made the necessary change.

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/10973

**Pull request closed without merging**
