### PR TITLE
LPS-191767 Adds service validation to prevent a user to modify a draft locked by another user

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-191767

Dear reviewer 👋 

Thanks in advance for your review ❤️ 

This PR implements that when a layout is locked by a user if another user tries to modify its structure data, its fragment links, or the segment's experiences then the service will throw a LockedLayoutException.

The lock acquire process isn't implemented yet so we need to use scripts to lock/unlock the draft. In addition, to be able to test it, the feature flag must be enabled:
`feature.flag.LPS-180328=true`

These scripts are useful to test this PR:

* Script to lock a draft by a user

[LockLayout.txt](https://github.com/liferay-echo/liferay-portal/files/12184835/LockLayout.txt)

* Script to see the status of a draft (locked/unlocked) with respect to all the users of the company

[isUnlockedLayout.txt](https://github.com/liferay-echo/liferay-portal/files/12184843/isUnlockedLayout.txt)

* Script to unlock a draft

[UnlockLayout.txt](https://github.com/liferay-echo/liferay-portal/files/12184851/UnlockLayout.txt)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @lfbesada, failed integration test has same error
```
com.liferay.portal.kernel.exception.ModelListenerException: com.liferay.portal.kernel.security.auth.PrincipalException: Principal is null  at com.liferay.layout.page.template.internal.model.listener.LayoutModelListener.onBeforeRemove(LayoutModelListener.java:138)
```
[com.liferay.segments.internal.model.listener.test.LayoutModelListenerTest](https://testray.liferay.com/home/-/testray/case_results/2396130560)
[com.liferay.fragment.contributor.test.FragmentCollectionContributorPropagationTest](https://testray.liferay.com/home/-/testray/case_results/2396129383)
[com.liferay.layout.service.test.LayoutLocalServiceTest](https://testray.liferay.com/home/-/testray/case_results/2396129870)

**Comment by lfbesada** [comment]
See: https://github.com/liferay-echo/liferay-portal/pull/13065

**Comment by lfbesada** [comment]
Hi @Tim-Cao 
Thank you very much for analyzing this ❤️ 
I have fixed those tests and resent a new PR but I think it is most likely that some more will fail because of the exact cause. I will be waiting for the test failures to adapt them.
Thank you!

**Pull request closed without merging**
