### PR TITLE
LPS-115224 Modify case to make it robust

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:stop

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
Since the failure case is caused by LPS-119174 and in order to not clog up ci resources I pushed directly to BChan.
See https://github.com/brianchandotcom/liferay-portal/pull/92912

**Pull request closed without merging**
