### PR TITLE
LPS-182361 Missing unit tests for 500 utility page

### PR DESCRIPTION
**Pull request by jkappler**
https://issues.liferay.com/browse/LPS-182361

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by lfbesada — APPROVED** [review]
Awesome 😍 Thanks a lot! I am sure this is going to save us a lot of bugs 👏

**Comment by lfbesada** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136457

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
