### PR TITLE
LPS-178747 Add aria-label to button

### PR DESCRIPTION
**Pull request by DiegoHu97**
This is a fix from this pull https://github.com/brianchandotcom/liferay-portal/pull/131990/commits

1. Go to Product Menu > Pages
2. Select kebab of Search Page or any Widget Page > Configure
3. Go to look and feel > Style Book section
Screenshot 2023-03-23 at 11 49 23

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
