### PR TITLE
[TECHNICAL SUPPORT] LPS-201821 The system tries to use a Deleted user's ID to convert a Widget Page to a Content Page.

### PR DESCRIPTION
**Pull request by markomihalovics**
### 📖  Content

- LPS-201821
  - Created the `LayoutCopyHelperImpl._addLayoutPageTemplateStructure` method. 
  - Handled the `NoSuchUserException` thrown in the `LayoutCopyHelperImpl._copyLayoutPageTemplateStructure` method by using the `userId` from the `sourceLayout` when the `userId` associated with the `targetLayout` is not found.
  - Code format in the `LayoutCopyHelperImpl`.
  - Processed the exception thrown by the `_addLayoutPageTemplateStructure` method to avoid the failure of `UnprocessedExceptionCheck`.

### 🧪  How To Test
- Start DXP
- Open the main menu on the top right
  - Go To: `Control Panel`
    - `Users`
      - `Users and Organizations`
        - Add a new User
        - Assign to them the Administrator Role
- Go To: `Users` page, click on the **kebab** menu beside the **new** User, and select "**Impersonate User**”.
- Now as the new User Go To: `DXP Site`
  - `Site Builder`
    - `Pages`
      - Add a **Widget Page**
- Click on the user profile icon on the upper right and select "**Be yourself again**".
- As yourself (admin user) Go To: `Control Panel`
  - `Users`
    - `Users and Organizations`
      - Beside the new user click on the kebab menu and select "**Deactivate**" to deactivate the new user.
      - Click on **Filter and Find** and select "**Inactive**" to see the inactive users then remove the new user by clicking the kebab menu beside it and selecting "**Delete**".
- Go To: `Site Builder`
  - `Pages`
    - Click on the kebab menu beside the widget page and select "**Convert to content page**".
**Checkpoint**: The page is opened in edit mode with the following note:
The page conversion is shown in the preview below. Make modifications needed before publishing the conversion, or discard the draft to leave the widget page in its original state.
- Publish the Page.

### ✅ Expected result
**The Page is successfully converted to a Content Page.**

🙏🏻  Thanks for the review in advance.

Regards,
Márkó

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
Hi @markomihalovics 

Thanks for the fix :heart: 

I have changed the solution to ensure that the user always exists as nothing guarantees that the target layout user still exists.

Please see: https://github.com/liferay-echo/liferay-portal/pull/14426

Regards

**Comment by markomihalovics** [comment]
Hi @lfbesada 

Thank you! 😇

**Pull request closed without merging**
