### PR TITLE
LPS-121881 Migrate v2 usages in journal-web

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

**Test plan for each of the jsps changed:** 

`select_article_translations.jsp`
1. Go to Web Content and add a web content article
2. Click on the three dots on "Delete translations" => modal is opened with the new management toolbar

`select_ddm_template.jsp`
1. Go to Web content and create or edit a web content article. 
2. On the right panel, in "Default Template" section, click on "select" button => modal is opened with the new management toolbar. 

`select_ddm_structure.jsp`
1. Go to Web Content > Templates and create or edit a template
2. On the right panel, in "Basic information" section, click on "select" button => modal is opened with the new management toolbar

Everything should work like before. 

/cc @julien @markocikos @jonmak08

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
