### PR TITLE
LPS-147705 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-147705

This is only for master.

@victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
thanks @Tim-Cao 😍

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
