### PR TITLE
LPS-121862 Migrate v2 usages in asset/asset-tags-admin-web

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

Creating, merging and deleting tags should work as expected.

**Test plan**:
- Navigate to **Categorization**>**Tags**
- Assert that you can create a tag
- Assert that you can delete the tag you created previously
- Assert that you can merge two or more tags correctly.

**Additional notes**
Originally reviewed [here](https://github.com/liferay-frontend/liferay-portal/pull/823)

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
LGTM! thanks @julien :D

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
