### PR TITLE
LPS-124407 Set appropriate language cookie

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Hi @shuyangzhou, could you please take a look if this solution makes more sense from the architectural point of view? It is just another approach to solve the LPS-119582 (the one we asked you about, with DummyRequest/Response).

@dacousalr, this solution doesn't include private(or any other, permission-dependent) pages, the only way I see to support those is to pass "doAsUserId" with admin privileges, but this opens a huge security hole. Let's keep this limitation in mind for now and discuss further if needed.

/cc @ealonso @JorgeFerrer

**Comment by shuyangzhou** [comment]
@pavel-savinov this is very odd and slow. What's the reason that the content generation can not be aggragated and exposed as a single backend service call?

**Comment by pavel-savinov** [comment]
@shuyangzhou we need HttpServletRequest/Response to render our fragments correctly. Are there any way to get Request/Response other than:
1) create dummys
2) get real request/response using the crawler 
?
Thanks in advance.

**Comment by ealonso** [comment]
This is not only to render fragments it is also required to render portlets

**Comment by shuyangzhou** [comment]
No, you can not fake a request and response for real. 

To me, this really sounds like a bad api separation. It is logically wrong for us to consume something we generated via http hitting ourselves. The logic sitting in the backend has access to all the info you need, it does not need a web layer to get involved. 

If the bad api separation is making this hard, then it is really your call to either improve the backend api to do this right, or just use the crawler to get over it. But this is really a bad example we never have had in the past, once we start this, people may start to follow. And this is not something good for maintaining.

Just expressing my concerns, ultimately it is your decision.

**Comment by JorgeFerrer** [comment]
Hey Shuyang,
I've read your arguments and I believe that they are absolutely right in general. 
I also believe that this is a valid exception because what we are trying to do here is provide a search experience por site pages which is as similar as possible to what users experience with Google (and other search engines). That can only be achieved if we index the whole page as it's rendered when invoked via HTTP. One possible optimization would be to invoke MainServlet directly, but then again you loose the filters and it's very tricky to simulate the request and response objects under all circumstances. So I'm not sure if it's a good idea.
After all, what we are deciding to do here, from a functional point of view, is just a simple crawler-like process that is invoked page per page, instead of making it crawl the site. We are doing this on purpose, because it's the behavior we want, not because there is some Java API limitation that prevents us from invoking it directly.
Finally, I'd like to highlight that this behavior is only desired when indexing pages, for everything else, we'll continue with the previous paradigm of indexing what's in the database.

I hope that clarifies things,
Jorge

**Comment by shuyangzhou** [comment]
@JorgeFerrer not to say you can not do it this way, just saying it is not a good way. It is the easiest way for now, but long term wise will cost more.

But anyway, if you decide to go with it, I am ok with it, just at least remove this striping https://github.com/liferay-echo/liferay-portal/pull/3162/commits/0528bcba2f20b6a033fe591882667a2461301db8#diff-2e899bffba2aae6b51eef9561eb05a05473ae2bdbecb08185bd9f009f4d78714R95 , it was just striped at https://github.com/liferay-echo/liferay-portal/pull/3162/commits/0528bcba2f20b6a033fe591882667a2461301db8#diff-2e899bffba2aae6b51eef9561eb05a05473ae2bdbecb08185bd9f009f4d78714R86 . This is already a very heavy solution, it should not waste more cpu time. And don't mix use XYZUtil and the injected osgi services, that makes no sense.

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by victorg1991** [comment]
sent rebased: https://github.com/liferay-echo/liferay-portal/pull/3221

**Pull request closed without merging**
