### PR TITLE
[TS] LPS-136518

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

Can you please review?
https://issues.liferay.com/browse/LPS-136518

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @balazssk ,

Thanks for the pull request!

There are some tests related to the display pages that are failing, it seems display pages are broken in your branch. Please, could you review it?

Thanks!

**Comment by balazssk** [comment]
Hi @lfbesada ,
Looks like there is some major issue in master with the SiteAdministrationPanel
image
I'm waiting for this to get fixed to check which are the true failures for this pull.

**Comment by balazssk** [comment]
must have been DB data issue, a fresh DB doesn't reproduce this

**Comment by balazssk** [comment]
Hi @lfbesada ,
I've rechecked some of the failed tests on a fresh bundle they did not fail.
Most of the issues on the failed tests were http 404 for resources, which URLs are theoretically valid. This makes me believe that the issue was not on URL generation part.
I'll rerun the tests to confirm this.

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @balazssk,
The failures seems to be related with your changes, Could you please take a look at it and resend?

**Pull request closed without merging**
