### PR TITLE
LPS-139962 Refactor grid resizing

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
Dear frontend reviewer, I'm still fixing frontend tests for this one. Just sent the PR in case some of you wants to start reviewing it and gain some time. I'll update it when tests are ready 😄

**Comment by sandrodw3** [comment]
Tests updated 🤟🏾

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:stable

**Comment by sandrodw3** [comment]
ci:test:relevant 🐸

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/6047

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
