### PR TITLE
LPS-190003 Display notification message

### PR DESCRIPTION
**Pull request by p2kmgcl**
Update for https://github.com/liferay-echo/liferay-portal/pull/12884

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
I have rebased it onto master and applied some changes (you can check the separated commits @sandrodw3). I still can't map a display page to the form, need to check how it works.

**Comment by jkappler** [comment]
@p2kmgcl, @Mikellorza was very kind and mentioned this: 

To enable it:
gogo shell -> scr:enable com.liferay.asset.display.page.internal.portlet.CustomAssetDisplayPageFriendlyURLResolver
portal.properties -> feature.flag.LPS-183727=true

**Comment by jkappler** [comment]
@p2kmgcl, @sandrodw3, from backend it was already reviewed by @lfbesada, and I did a recheck and all looks good ❤️ 

My only observation is that it's presenting an issue with layout. After selecting it in the item selector, the change is not applied. But it can be from another change not related to the PR

**Comment by sandrodw3** [comment]
Thanks a lot @p2kmgcl @jkappler @lfbesada ❤️ Sent fixing what Jurgen commented in https://github.com/liferay-echo/liferay-portal/pull/12982

**Pull request closed without merging**
