### PR TITLE
LPS-131307 Split and sort web content article dropdown menu

### PR DESCRIPTION
**Pull request by p2kmgcl**
In order to support grouping these web content article actions, I used the existing `DropdownItemListBuilder.addGroup()` Java API. However, I found that part of this API was not supported by the frontend DropdownMenu component (see two first commits https://github.com/liferay-echo/liferay-portal/pull/4433/commits/f2830a55abae844d74508cea493d3ff1a32df5d9 and https://github.com/liferay-echo/liferay-portal/pull/4433/commits/5b1494caffcc1f5ff9ac33c505b41faa9b4f71b5):

- Nesting items with data-* attributes.
- Allowing using `dropDownGroup.setSeparator(true)` in Java.

Moreover, I discovered that empty groups are not being filtered in Java (see my comment in the third commit https://github.com/liferay-echo/liferay-portal/pull/4433/commits/f0fef8dc0d66a3ba88b67da49c528a0a8bf54d76) and I added some filtering in the FrontEnd part. We might prefer doing this filtering on the BackEnd, but I didn't found a clean/easy way to do this (ex. I would expect the `DropdownItemListBuilder.build()` method to filter empty groups).

Last two commits (https://github.com/liferay-echo/liferay-portal/pull/4433/commits/09ac19fe021169df9e790ea60b5d1a967109e246 and https://github.com/liferay-echo/liferay-portal/pull/4433/commits/1e413e779c68b8ecf475d9889c586a17d51d7be1) are just the small adapt process supporting recursive actions in the propsTransformer and do the sorting and grouping in the `getActionDropdownItems()` method.

> My two cents about the `dropDownGroup.setSeparator(true)` API: it might be a bit confusing because I am not sure if expect the separator to be before of after each group. In my implementation I added it before, but could be any.

### CODE REVIEW

**Comment by p2kmgcl** [comment]
@julien can you have a look at the first three commits mentioned in the description? I am modifying the DropdownMenu component behavior as I showed you on the call, but I am not sure about the filtering process. I can link the PR on the infra channel if you prefer so.

**Comment by julien** [comment]
Hey @p2kmgcl, yes, no problem I can have a look at that (and of we still have doubts after that, then it seems like good idea to open a thread). Thanks

**Comment by jkappler** [comment]
Looks nice @p2kmgcl 💯 * 💯, amazing!

**Comment by julien** [comment]
@p2kmgcl I've check those three commits you mentioned, and more specifically [this one about filtering](https://github.com/liferay-echo/liferay-portal/pull/4433/commits/f0fef8dc0d66a3ba88b67da49c528a0a8bf54d76). I wanted to ask you what exactly aren't you sure about?

**Comment by p2kmgcl** [comment]
> @p2kmgcl I've check those three commits you mentioned, and more specifically [this one about filtering](https://github.com/liferay-echo/liferay-portal/pull/4433/commits/f0fef8dc0d66a3ba88b67da49c528a0a8bf54d76). I wanted to ask you what exactly aren't you sure about?

Well, it is not exactly about the code, but this:

> We might prefer doing this filtering on the BackEnd, but I didn't found a clean/easy way to do this (ex. I would expect the DropdownItemListBuilder.build() method to filter empty groups).

But I guess it is fine to do the filtering in JS :sweat_smile:

**Comment by julien** [comment]
@p2kmgcl ah I see ... 
To be honest with you, I don't know enough about the `DropdownItemListBuilder` to give you an immediate reply; but I can have a look at it. It's true that filtering on the backend might be better (just to avoid the overhead) and I wonder what @jkappler thinks about that.

**Comment by jkappler** [comment]
I think that it would be a good idea to check the DropdownItemListBuilder to cover some gaps that may exist, such as the one that @p2kmgcl mentioned. Maybe we should create a task for it? So that we have it documented

**Comment by julien** [comment]
@jkappler sounds like a good idea to me.

**Comment by p2kmgcl** [comment]
@julien I can just pass this PR and open a new ticket for you in order to check the DropdownItemListBuilder, is that fine?

**Comment by julien** [comment]
@p2kmgcl yes you can, sorry I should have been more precise.

**Comment by p2kmgcl** [comment]
You've been very helpful :smile:

thanks!

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
There it goes (cc @julien @jkappler) https://issues.liferay.com/browse/LPS-131600

@julien I set the "Clay Taglibs" component because it is using the `<clay:dropdown />` taglib, but feel free to change the component if there is more appropriate one.

**Comment by julien** [comment]
@p2kmgcl that's exactly what I would have chosen too. Thanks.

**Comment by p2kmgcl** [comment]
I just rebased and found a small typo in the filtering process

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, cannot move the web content to Recycle Bin via Move to Recycle Bin action.

**Comment by p2kmgcl** [comment]
Thanks! I'm having a look

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
