### PR TITLE
LPS-187518 Implement integration tests for Utility pages and Page Templates to cover update cases

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
[Link to ticket](https://issues.liferay.com/browse/LPS-187130)

### CODE REVIEW

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@BarbaraCabrera, nice! 😍

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
