### PR TITLE
LPS-185111 Enable changing Structure Key

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-185111

The first 5 commits of this pull request were reviewed and approved by the Forms Team here: https://github.com/liferay-forms/liferay-portal/pull/2125

I've only edited those commits to change the LPS in the commit messages and extract the autogenerated code that was in the first commit into a separate commit.

I've also added a commit to hide the new behavior under an FF since we'll be adding warnings and limitations and don't want it exposed until it's done. For details please see the full story: https://issues.liferay.com/browse/LPS-184255

cc: @kristofloneck @carolmariaabb @ealonso

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward:force

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/135199

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
