### PR TITLE
LPS-129297 Avoid keeping empty layout object

### PR DESCRIPTION
**Pull request by p2kmgcl**
Forwarded from https://github.com/liferay-echo/liferay-portal/pull/4042
(ci was giving problems)

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
