### PR TITLE
LPS-183600 Test creation for Link to Layout DDMFormFieldType

### PR DESCRIPTION
**Pull request by YurenaC**
Test related to changes made for [LPS-182339](https://issues.liferay.com/browse/LPS-182339)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Comment by david-gutierrez-mesa** [comment]
Send directly to BChan: https://github.com/brianchandotcom/liferay-portal/pull/134394

**Comment by david-gutierrez-mesa** [comment]
ci:close

**Pull request closed without merging**
