### PR TITLE
LPS-133715 Hide breadcrumb in public pages tab when configuring a Display Page for Web Contents

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-133715

Adds a property to LayoutItemSelectorCriterion to enable breadcrumb in layouts item selector. By default it is enabled and is specifically disable in web content display page selection.

This PR change part of the solution to https://issues.liferay.com/browse/LPS-127467 --> PR: https://github.com/liferay-lima/liferay-portal/pull/1640

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
@jkappler @lfbesada the last commit doesn't include the LPS-XXXXX, so the Source Format is going to fail

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:stop

**Pull request closed without merging**
