### PR TITLE
LPS-155513 Modify cases to adapt new behavior

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
Hi @victorg1991
First Regression issue, The Page Content panel is unavailable to the user with Update permission for asset.
**Step to reproduce**
Add a site role with Update permission for Web Content Article
image
Add a new user
Assign new user to default site
Assign new site role to new user
Sign in as new user
Navigate to the page editor of Home page via pencil icon

**Expected Results**
The Page Content panel should be available to new user

**Actual Results:**
The Page Content panel is unavailable to new user

**Comment by Tim-Cao** [comment]
Second regression issue, the Preview in new tab doesn't work with Selected experience at view mode.
**Steps to reproduce**
Add a Button to content page
Add a new experience
Add a Heading below the Button
Publish the content page
Navigate to the content page at view mode
Select the new experience
Navigate to the page editor via pencil icon
View the selected experience is new experience
Preview in a new tab

**Expected Results**
The displayed content should be in new experience

**Actual Results**
However, the display content is shown in default experience.

**Comment by victorg1991** [comment]
Thanks @Tim-Cao

**Comment by Tim-Cao** [comment]
Hi @victorg1991, I've added additional commit to fix an Poshi issue found by ci:test:echo run.
https://github.com/liferay-echo/liferay-portal/pull/9611
Would you mind cherry picking?

**Comment by victorg1991** [comment]
this is the good one @Tim-Cao

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/9617

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
