### PR TITLE
LPS-99703 Regen

### PR DESCRIPTION
**Pull request by JavierMoral**
This is a fix for [https://issues.liferay.com/browse/LPS-99703](https://issues.liferay.com/browse/LPS-99703).
Last version of the fix sent in [brianchandotcom#77977](https://github.com/brianchandotcom/liferay-portal/pull/77977) tried to leave the serialized JSON with the same fields it had in 7.0. This was done to avoid making changes in Screens but caused field duplication in serialized JSONs so it was reverted in https://github.com/brianchandotcom/liferay-portal/pull/78095.

The cause of this duplication was a technical limitation of the underlying serialization library Jodd JSON. So, as maintaining the same names was not possible in the end, missing fields (title, description) are now serialized using new names to avoid this duplication. I spoke with @victorg1991 and Screens will need to be updated in order to show this fields that were missing since 7.1. In the end only two fields changed their names:

- _title_ is now called _titleMapAsXML_
- _description_ is now called _descriptionMapAsXML_

### CODE REVIEW

**Comment by JavierMoral** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:stable

**Pull request closed without merging**
