### PR TITLE
[TS] LPS-162468 Update UI for displaying current sorting type

### PR DESCRIPTION
**Pull request by binhtran92**
**Motivation**: 
[LPP-46398](https://issues.liferay.com/browse/LPP-46398): Asset Publisher's filtering by category, and display order by descending Publish Date is not working properly

This PR is fixing the display of the sorting icon in the UI.

**Step to reproduce**: 

1. Start up a Liferay DXP 7.4 U26 instance connected to a MySQL database

2. Sign in as admin

3. In the default Liferay DXP site, go to the side menu > Categorization > Categories

4. Create a new vocabulary called "VocabTest"

5. Go into "VocabTest" and create a category called "webinar"

6. Create 5 Basic Web Content articles (e.g. TestArticle 1, TestArticle 2, ... TestArticle 5) with each of them having the "webinar" category assigned to it (i.e., In the Web Content editor, click on Categorization > VocabTest > Select – Select "webinar")

7. In the Liferay DXP site, add a widget page

8. In that new widget page, add an Asset publisher Widget

9. Click on tricolon icon for the Asset Publisher widget > Configuration, and under Asset Selection, configure it as follows:
      Asset Selection: Dynamic
      Source
      Asset Type: Web Content Article
      Web Content Article Structures: Any
      Filter
      Rules Contains All of the following Categories
      Categories: webinar
      Ordering
      Order by Publish Date And Then Title
      Make sure both arrows are set to Descending order
10. Go back to the Widget page, and assert that the ordering is ignored with the first article created being on top, instead of the latest article (which is what we'd expect of Descending order)

11. Edit the bottom article (i.e., TestArticle 5) and under Schedule change the Display date to around 5 minutes from now, then publish.

12. Wait around 5 minutes, and check the widget page containing our Asset Publisher. Note: If TestArticle 5 is not yet published, then wait a little longer.

**Actual Behavior**
"TestArticle 5" still remains at the bottom of the Asset Publisher, even though Asset Publisher is configured to show items in Descending order.

**Expected Behavior**
The future display date's article should now come on top as Article's display date gets converted into Publish Date in asset entry. Basically, order by descending is not working properly in Asset Publisher.

cc: @hongvo2308

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/9582

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Hey @binhtran92,

Could you please take a look at?

[LocalFile.AssetPublisherUseCase#FilterAndOrderAssetsByField](https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/232486//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_AssetPublisherUseCase_FilterAndOrderAssetsByField_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-09/test-1-31/test-portal-acceptance-pullrequest(master)/4979/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.AssetPublisherUseCase_FilterAndOrderAssetsByField/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-09/test-1-31/test-portal-acceptance-pullrequest(master)/4979/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.AssetPublisherUseCase_FilterAndOrderAssetsByField/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-09/test-1-31/test-portal-acceptance-pullrequest(master)/4979/functional-tomcat90-mysql57-jdk8/0/2/jenkins-console.txt.gz)
[LocalFile.AssetPublisherUseCase#FilterAssetsByCategoriesWithPagination](https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/232486//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_AssetPublisherUseCase_FilterAssetsByCategoriesWithPagination_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-09/test-1-31/test-portal-acceptance-pullrequest(master)/4979/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.AssetPublisherUseCase_FilterAssetsByCategoriesWithPagination/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-09/test-1-31/test-portal-acceptance-pullrequest(master)/4979/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.AssetPublisherUseCase_FilterAssetsByCategoriesWithPagination/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-09/test-1-31/test-portal-acceptance-pullrequest(master)/4979/functional-tomcat90-mysql57-jdk8/0/2/jenkins-console.txt.gz)

Tests results seems to be related with your code.

**Comment by hongvo2308** [comment]
Hi @ealonso 
Thank you for reviewing this ticket. Unfortunately, I could not view the log that you mentioned above. Could you please give me more detail on this one?
Thank you very much.

**Comment by hongvo2308** [comment]
ci:test:relevant

**Comment by hongvo2308** [comment]
Hi @ealonso 
I have updated the test case. Could you please double-check the test-relevant results? 
I am not sure why it produces so many more cases than before.
Thank you very much.

**Comment by ealonso** [comment]
Hey @hongvo2308, @binhtran92,

This pr have some conflicts, Could you please rebase and update the pr? After that I going to execute the tests again.

Thanks!!

**Comment by hongvo2308** [comment]
Hi @ealonso 
I have rebased this branch with the latest and updated this PR. Please review it again and leave your comments.
Thank you.

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123218

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
