### PR TITLE
LPS-121883 Modify macro to assert delete button is disabled

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @jonmak08 @Tim-Cao @ambrinchaudhary

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Ready to forward once test relevant finishes :)

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Rebased then resent

**Comment by Tim-Cao** [comment]
I've made some changes for the last commit then rebased and resent in https://github.com/liferay-echo/liferay-portal/pull/3974

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
