### PR TITLE
LPS-143395

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-143395

/cc @javalosjr96

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @mbowerman 

I will review this pull request again, there are details that have passed me by.

Regards

**Review by lfbesada — CHANGES_REQUESTED** [review]
Hi @mbowerman,

Thanks for the fix!

The fix works okay but it seemed to me that it could be solved in a simpler way.

What had been overlooked in my first review was that the filtering that is incorporated in this PR, is already done in the doSearch method. This filtering only applies if the actionId parameter is present but the userId parameter is not, see: https://github.com/liferay/liferay-portal/blob/7560bf39c7afc45788cd8210d98d806d24a1f440/portal-impl/src/com/liferay/portal/service /impl/GroupLocalServiceImpl.java#L4343-L4342

So I have supposed that it could work without adding more checks if we just added the actionId parameter without adding userId. I have modified the commit so that it only adds that parameter and I have verified that this solves the bug, in a simpler way and using the logic already implemented.

I have submitted a new PR with that modified commit, please see: https://github.com/liferay-echo/liferay-portal/pull/6643

Regards

**Comment by lfbesada** [comment]
See: https://github.com/liferay-echo/liferay-portal/pull/6643

**Pull request closed without merging**
