### PR TITLE
LPS-129077 Only use default template when creating a new article

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @victorg1991, there is a regression issue caused by your changes. Cannot publish the web content
*Step to reproduce:*
1. Add a web content based on Basic Web Content
2. Type title and content
3. Click Publish

*Expected Results:*
The web content should be published successfully.

*Actual Results:*
The publish process is pending. Additionally, the following error is thrown in browser console
BrowserConsole

**Comment by victorg1991** [comment]
Thanks @Tim-Cao I'm going to take a look :)

**Comment by victorg1991** [comment]
should be fixed now, I didn't have SPA enabled, that is whay I didn't see the problem 🤦

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
