### PR TITLE
[TS] LPS-132408

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team, could you please review this PR? This solution assumes the fact that articles and their respective display pages, either modern or classic, are located within the same group. Thanks in advance

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
