### PR TITLE
LPS-195551 Display page content is not displayed when its opened from notification through comment

### PR DESCRIPTION
**Pull request by jkappler**
**Motivation**
https://liferay.atlassian.net/browse/LPS-195551
Assets in the request are lost when a widget is refreshed.

**Proposed Solution**
Create a mechanism to get the layout asset entry if it's not a request attribute, so it's friendly url could be used

/cc @robertoDiaz, @SamZiemer

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward:force

**Pull request closed without merging**
