### PR TITLE
LPD-36041 Reverse Order Direction button does not work in [Site Builder > Pages]

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPD-36041)

## Changes

The button will never work because of the drag and drop (we can reorder the pages) and also because they are sorted by creation date.

## Test Scenario

1. Go to Site Builder > Pages
2. Create a test page
3. Check that the button doesn't appear now

image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:forguard

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:page-management-playwright

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
