### PR TITLE
LPS-121919 Migrate v2 usages in style-book/style-book-web

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @liferay-echo,

Attached is an update for http://issues.liferay.com/browse/LPS-121919.

**Test Plan:**

1. Login to Liferay.
2. Click the **Menu** Option.
3. Open the **Design** Panel and Click the **Style Books**.
4. Click the `+` to add a **Style Book**.
5. Click the **Publish** button
6. You can now **Delete**, **Export**, and **Make a Copy** of the created Style Book

style-book

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Review by julien — APPROVED** [review]

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
