### PR TITLE
LPS-139871 Migrate AUI from /site/site-admin-web/src/main/resources/META-INF/resources/site_settings/details.jsp to a js file

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
