### PR TITLE
LPS-134288 The associate display page template field is shown in global category editor

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/projects/LPS/issues/LPS-134288

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @lfbesada,

The pull looks ok, but I think we need to take into account depot. Please take a look to the code that we have for Journal

```java
public boolean isVisible(User user, JournalArticle article) {
Group group = null;

if ((article != null) && (article.getId() > 0)) {
	group = _groupLocalService.fetchGroup(article.getGroupId());
}
else {
	ServiceContext serviceContext =
		ServiceContextThreadLocal.getServiceContext();

	ThemeDisplay themeDisplay = serviceContext.getThemeDisplay();

	group = themeDisplay.getScopeGroup();
}

if ((group != null) && (group.isCompany() || group.isDepot())) {
	return false;
}

return true;
}
```

Also should be really nice if you check the behavior for DL and Blogs.

Regards,
Eudaldo

**Comment by ealonso** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hey @ealonso ,

I added depot site checks and I have been check DL and Blogs behavior on Global and Depot sites, it does not show display page selection. 

Please could you check it again?

Thanks!
Regards
Lourdes

**Comment by lfbesada** [comment]
ci:reevaluate:1257401_1681

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/4960

**Pull request closed without merging**
