### PR TITLE
LPS-200228 and LPS-200682 Don't allow changing the type/subtype of a DPT if some asset has it assigned

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-200228
https://liferay.atlassian.net/browse/LPS-200682

cc: @sandrodw3 :heart:

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by jkappler** [comment]
@lfbesada, @sandrodw3, backend looks good ❤️

**Comment by p2kmgcl** [comment]
FrontEnd looks fine, I am going to test it manually and remove the review label.

@lfbesada shouldn't we merge the two "buildLang" commits?

**Comment by lfbesada** [comment]
@p2kmgcl Thanks for catching it :heart: I have joined them. Regards

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward:force 🐉

**Pull request closed without merging**
