### PR TITLE
[7.4.x only] LPS-124006 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-124006

This is only for master.

@p2kmgcl
@sandrodw3

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, there is an regression issue caused by your changes.
Only happens when disable adaptive media for Image fragment.
The url of document is shown in Image field instead of title of document
Actual

**Comment by p2kmgcl** [comment]
I'm having a look

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/3173

**Pull request closed without merging**
