### PR TITLE
LPS-169505 - Delete Permission elipsis button and Permissions option from the configuration view

### PR DESCRIPTION
**Pull request by ruben-pulido**
Screenshots
========
Screen Shot 63

//cc @ealonso @veroglez

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @ruben-pulido,

I think the agreement for the feature flags is used the LPS of the Epic and it is LPS-119382.

**Comment by ruben-pulido** [comment]
Thanks! I will update all 3 PRs in the story.

**Comment by ruben-pulido** [comment]
Fixed

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Failures are not related, pushed to BChan directly at https://github.com/brianchandotcom/liferay-portal/pull/128105

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
