### PR TITLE
LPS-176670 Replace alert divs with clay:alert taglib in journal-web

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-176670)

## Test Scenario 1

* Create a site, with a public page
* Add an Asset Publisher to the page
* Configure the Asset Publisher
    1. Navigate to Display Settings > Set and Enable
    2. Check "Set as the Default Asset Publisher for This Page"
    3. Save
* Create a new web content article
    1. Fill in a title and content
    2. Under Display Page settings, change "Default Display Page" to "Specific Display Page"
    3. Select the added public page
    4. Publish
* Export Web Content as a LAR (from the Web Content admin portlet; do not include pages)
* Create a new site, and import the Web Content LAR
image

## Test Scenario 2

* Create a new web content.
    1. Under Default Template click on edit for basic web content.
    2. After fix the behaviour in this pr you can see now the alert.
image

## Test Scenario 3

* Create a new structure.
* Create a new web content based on this structure
* Export Web Content as a LAR 
* Create a new site, and import the Web Content LAR
* Go to Edit the structure
image

## Test Scenario 4
* Create a new web content.
* Create a content Page.
    1. Add a Content display and relate it to the web content
    2. In general change the Template to the Title.
* In other tab, expire the web content.
* Reload the content page in the edit view.
image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
