### PR TITLE
[TS] LPS-128069 - instance names are double escaped

### PR DESCRIPTION
**Pull request by wanderlast**
https://issues.liferay.com/browse/LPS-122234

Hi Echo team!

This handles an issue where instance names are being double-escaped when displayed in the applications menu. Since React [automatically escapes JSX](https://reactjs.org/docs/introducing-jsx.html#jsx-prevents-injection-attacks) the call to [virtualInstance's label](https://github.com/wanderlast/liferay-portal/blob/181de00d31d8a36db157b737ce71a8de4c736b84/modules/apps/product-navigation/product-navigation-applications-menu-web/src/main/resources/META-INF/resources/js/ApplicationsMenu.js#L68) should be safe, I've removed the explicit call to escape to prevent the name from being escaped twice.

Please let me know if I can clarify anything. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
LGTM Thanks @wanderlast :)

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
