### PR TITLE
LPS-119582 Rename and move to the appropriate package

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by jpince** [comment]
Hi guys, I see this error in the log for several integration tests in each run. It's probably different than the portal-dao-test failure, but at least you have some info in the meantime.
`com.liferay.portal.kernel.exception.NoSuchLayoutException: No Layout exists with the primary key 0`

**Comment by Tim-Cao** [comment]
Rebase then resend. See https://github.com/liferay-echo/liferay-portal/pull/2365

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
