### PR TITLE
LPS-144447 | ModifiedDate of fragments are not getting updated

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
One of our customers reported that the modification date is not updated on fragments. I checked the code and we used the statusDate for the fragments. It seems to be intentional that we used the statusDate, but I changed it to be more in line with the web content view where the card view displays the modification date. 

Could you review these changes?
https://issues.liferay.com/browse/LPS-144447
Thank you!

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
No regression issues found according to [ci:test:echo](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1594802074&testrayRunId=1594802128)

**Review by lfbesada — CHANGES_REQUESTED** [review]
Hi @bakayattila 

Thanks for the PR!

Although the approach is correct, I am afraid that the solution is incomplete.

On the one hand, it would be necessary to apply this modification to all the cards that can be shown in that view, which are all those that FragmentEntryVerticalCardFactory could return.  If this were not done, we could have cards in the list that show different fields in the same list. In that way, in addition to BasicFragmentEntryVerticalCard, should be modified InheritedFragmentEntryVerticalCard and BasicFragmentCompositionVerticalCard too.

On the other hand, the fragment's searchContainer should sort by the displayed fields, otherwise, the view would be disconcerting for the user. So the ordering of the creationDate column should be changed to the modifiedDate column.

Thanks in advance.

Have a great new year!

Regards

**Comment by bakayattila** [comment]
Hi @lfbesada,
Thanks, I will make the required changes to my solution.
Have a great new year!

**Comment by bakayattila** [comment]
Hi @lfbesada,

I made the requested changes. I modified the BasicFragmentCompositionVerticalCard and created the new ordering. I also changed the default order to the new one because we are displaying the modification date. I did not modify the InheritedFragmentEntryVerticalCard as there is no implementation for the subtitle there.
I also changed the display pattern of the subtitle to be more in line with the other parts of the portal and to avoid the confusion that the previous one made.

Could you review it?

Thanks in advance.

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
Hi @bakayattila, could you update the semantic version in fragment-api module?

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
Hi @Tim-Cao,
I added a baseline commit to the pull.
Best,
Attila

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by lfbesada** [comment]
Hi @bakayattila,
Thanks for the fix, it works great!
Please see: https://github.com/liferay-echo/liferay-portal/pull/6862
I only added a minor change to hide the sort by creation date. As this field is not shown in the list view so it seems a little weird to allow sorting by a non-visible field.
Thanks a lot!
Regards

**Pull request closed without merging**
