### PR TITLE
LPS-176518 Include the externalReferenceCode in the TaxonomyCategory for the /taxonomy-categories/ranked endpoint

### PR DESCRIPTION
**Pull request by ccorreagg**
This PR contains the code to fix this bug: https://issues.liferay.com/browse/LPS-176518

It is related to this LPP: https://issues.liferay.com/browse/LPP-48059

The `externalReferenceCode` field has been included into the Projection of the dynamicQuery that is being used to get the Taxonomy Categories. With that, the field is returned in the response of the query and it is returned properly.

The field has been included in the list of fields that must be validated in the ResourceTests.

---

**Before the PR:**

```
curl -X 'GET' \
    'http://localhost:8080/o/headless-admin-taxonomy/v1.0/taxonomy-categories/ranked' \
     -H 'accept: application/json' \
     -u 'test@liferay.com:test'
```

```
{
  "actions" : { },
  "facets" : [ ],
  "items" : [ {
    "[...]
    "externalReferenceCode" : "",
    [...]
  } ],
  [...]
}
```

**After the PR:**

```
curl -X 'GET' \
    'http://localhost:8080/o/headless-admin-taxonomy/v1.0/taxonomy-categories/ranked' \
     -H 'accept: application/json' \
     -u 'test@liferay.com:test'
```

```
{
  "actions" : { },
  "facets" : [ ],
  "items" : [ {
    "[...]
    "externalReferenceCode" : "42c581b7-1232-5d0a-fddb-25167743c8d3",
    [...]
  } ],
  [...]
}
```

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ccorreagg** [comment]
cc/ @victorg1991

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ccorreagg** [comment]
Hey @victorg1991 ,

I am removing the code from the test as some tests are failing because of that. I think the autogenerated test is not properly designed as the patch method test is failing :cry: 

Anyway, maybe ins ome point in the future we will review it to design the test better

**Comment by ccorreagg** [comment]
ci:test:sf

**Comment by ccorreagg** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
