### PR TITLE
LPS-178363 Cannot publish expired Web Content with Display Page whose latest version is in draft status

### PR DESCRIPTION
**Pull request by AlmirFe**
LPS link: [LPS-178363](https://issues.liferay.com/browse/LPS-178363)

Motivation
=======
This PR contains the solution for [LPS-178363](https://issues.liferay.com/browse/LPS-178363) which fixes the [LPP-48264](https://issues.liferay.com/browse/LPP-48264). 
Issue: If we try to publish an expired Web Content with Display Page whose latest version is in draft status, an exception will be thrown on [this line](https://github.com/liferay/liferay-portal/blob/5329fcdb461f56b6921a56252983255a7ab0076c/portal-kernel/src/com/liferay/exportimport/kernel/lar/BaseStagedModelDataHandler.java#L924) because the Staging process is publishing the draft version of the Display Page and  the draft status is not an exportable status. We noticed that the [AssetRenderer](https://github.com/liferay/liferay-portal/blob/61dcdd0157a413052accb27608505f9079fe00b0/modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/asset/model/JournalArticleAssetRendererFactory.java#L108-L150) function tries to get an article with STATUS_ANY if there is no an approved version.

Proposed Solution
========
I added [two ways](https://github.com/liferay/liferay-portal/blob/51aef9a11b8a43d2fe2e4e63af9192a4ced9acde/modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/asset/model/JournalArticleAssetRendererFactory.java#L125-L137) to try to get an article version with an exportable status (STATUS_EXPIRED, STATUS_SCHEDULED) before trying to get it with STATUS_ANY. So if there is any web content with exportable status, it will be got first.

Steps to Verify
========
1.Enable Local Staging
2.Create a Display Page for Basic Web Content
3.Create a Basic Web Content with this Display Page
4.Expire the Web Content
5.Edit the Web Content and save it as draft marking it as "Never Expire"
6.Publish to Live

- Expected behavior:
The Web Content with its Display Page are published successfully.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by AlmirFe** [comment]
ci:test

**Comment by dacousalr** [comment]
Hi @AlmirFe,

Thanks for sending this PR to the team.

I would only like to friendly remind you that PRs sent to Echo team should provide at least the information requested in the [Echo template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md).

In addition to that, I would like you to reorder the service calls to retrieve the Web Contents in scheduled status over the Web Contents in expired status.

Could you please review these points?

**Comment by AlmirFe** [comment]
Hi @dacousalr,
I've changed the description in this PR to follow the template.

**Comment by AlmirFe** [comment]
Hi @dacousalr,
I sent a new commit with this change.

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
Thanks for your help on this Herr @dacousalr!

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
