### PR TITLE
LPS-117536 Add ItemConfiguration

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:close

**Comment by p2kmgcl** [comment]
I am fixing this and adding some changes

**Comment by p2kmgcl** [comment]
ci:reopen

**Comment by p2kmgcl** [comment]
I checked this locally, this should be working

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:close

**Pull request closed without merging**
