### PR TITLE
LPS-199249 - urlTitle changes based on titleMap when calling updateArticle 

### PR DESCRIPTION
**Pull request by ruben-pulido**
https://liferay.atlassian.net/browse/LPS-199249 - urlTitle changes based on titleMap when calling updateArticle

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@georgel-pop-lr, please don't run relevant everytime, this is still in review :D

**Comment by ruben-pulido** [comment]
Helper methods in test removed here: https://github.com/liferay-echo/liferay-portal/pull/14063

**Pull request closed without merging**
