### PR TITLE
LPS-112819 Build lang

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@ealonso

**Comment by yichenroy** [comment]
ci:forward

Previous attempt encountered network issue (most likely from Github).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/758

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
