### PR TITLE
LPS-171977 - Page Tree loses selected page after navigating to it

### PR DESCRIPTION
**Pull request by ruben-pulido**
Screenshots
========

https://user-images.githubusercontent.com/17814626/210290414-8f178ce6-bf2c-4623-a7c0-520aa5785b05.mov

//cc @ealonso @sandrodw3

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
LGTM 🎉

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128316

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
