### PR TITLE
LPS-163681 Page tree select all

### PR DESCRIPTION
**Pull request by vendeltoreki**
* Resending https://github.com/liferay-echo/liferay-portal/pull/10901 , based on [comment](https://github.com/liferay-echo/liferay-portal/pull/10901#issuecomment-1398312121)
* Fixing other issues regarding page selection:
  * When not changing anything in the publish form, we should still select everything if the root node was checked: https://github.com/liferay-echo/liferay-portal/commit/7b59ee9a76cea3a581e4efe3d87ef7a645a530b0
  * Unchecking any node in the tree should also uncheck the root node: https://github.com/liferay-echo/liferay-portal/commit/d951f72a997334d6dedb6663b65fd68fa63b3e0b
  * Drafts are not required, they are not shown in the page tree https://github.com/liferay-echo/liferay-portal/commit/4deb643a05ad170b609e2c0c997a1d11c712603b

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
Hi @vendeltoreki
Thanks for the PR! I have asked Product Management whether we want to go forward with this solution, which uses the root node "Pages" to determine whether pages created later on should be included or whether we want to follow a similar approach as the one we are already using for determining whether fragments created later on should be available in a drop zone within a master page.

Captura de pantalla 2023-02-02 a las 15 47 08

Personally, I think the second approach makes it more clear to the end user what will happen with pages that are created at a later point.

I'll let you know the decision once it is made.

**Comment by vendeltoreki** [comment]
Thanks, @ruben-pulido . I agree that it makes sense to have a specific option for that.

**Comment by ruben-pulido** [comment]
Hi @vendeltoreki 
I got feedback from Design that including a separate checkbox is the preferred way to move forward.
I am closing this PR then.

**Pull request closed without merging**
