### PR TITLE
LPS-92616 Server Administration

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:forward

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/120437

**Pull request closed without merging**
