### PR TITLE
[TS] LPS-111292

### PR DESCRIPTION
**Pull request by dacousalr**
Hi @ealonso, could someone of the team review this PR? Thanks in advance

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @dacousalr,
Could you please send this one to headless team?

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
ci:stop

**Pull request closed without merging**
