### PR TITLE
[TS] LPS-146461 | Can't order structures alphabetically when selecting 'More' during web content creation

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?

https://issues.liferay.com/browse/LPS-146461

Thank you!

-----

Original pull request: #7109

Based on the [PTR](https://issues.liferay.com/browse/PTR-2856) and my discussion with  @ealonso I modified my original fix. In the current version, I modified the comparator in order to use the actual names over the XML for the comparison added two test cases for the comparator, and used the comparator in the structure view and at the add web content more structures menu.

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
ci:test:echo

**Comment by ealonso** [comment]
Hey @bakayattila,

Could you please resolve the conflict and update the pr?

Thanks,
Eudaldo

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
ci:test:echo

**Comment by ealonso** [comment]
Please see: https://github.com/liferay-forms/liferay-portal/pull/1431

**Pull request closed without merging**
