### PR TITLE
[TS] LPS-123387

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-123387

Script to test performance boost can be found on the LPS ticket.  Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Resent here with SF: https://github.com/liferay-echo/liferay-portal/pull/2880
@ChrisKian Could you please check that it is still what you expect to see? Thanks

**Pull request closed without merging**
