### PR TITLE
LPS-180469 Change criteria_builder components to functional components

### PR DESCRIPTION
**Pull request by BarbaraCabrera**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
Hey @BarbaraCabrera 😄 this looks super good overall! 🎉 I'm just leaving some improvements I think we should do:
- Default props can be added inline in the props definition in the function header
- Inside components, we usually prefer using arrow functions over regular functions, could you change them?
- We should pay attention to the contexts usage (previous `contextType` and `this.context`), I think we have to review that part
- Could we rename test files from `Component.es.js` to `Component.test.js`? So we follow the pattern we have in other modules 🎉

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
Hey @BarbaraCabrera, a regression found. The last letter of every User Segment created is deleted. Steps to repdroduce:

1. Go to Product Menu >> People >> Segments
2. Add a segment with any title

Expected result:
The title will appear as previously placed

Actual result:
The last letter of the title is removed

**Comment by sandrodw3** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
The related failures only needed a test fix. Resent here https://github.com/liferay-echo/liferay-portal/pull/11828

**Pull request closed without merging**
