### PR TITLE
LPS-169088 Implements the fragment Drop Zone id validation

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-169088

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by jkappler** [comment]
Looks great @lfbesada ❤️

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1297401_5510

**Comment by lfbesada** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Hey @lfbesada, I will monitor the CI, and if it fails again, I will review it and send it manually.

**Comment by alessandromalves** [comment]
The failures are not related to this PR. See https://github.com/brianchandotcom/liferay-portal/pull/126703

**Comment by alessandromalves** [comment]
Hey @lfbesada, it looks like you had some conflicts between commits and Brian's repository. Could you take a look?

**Comment by lfbesada** [comment]
Hi @alessandromalves 
Done!
Thanks a lot for your help! ❤️ 
I have only solved conflicts in the last commit that is auto-generated.
Regards

**Comment by alessandromalves** [comment]
ci:forward

**Comment by lfbesada** [comment]
@alessandromalves SF is failing in the Brian repo, I could add a commit to solve it but I am afraid that it could cause conflicts in the Brian repo.
Please let me know if I should add it.
Maybe is easier to keep here this PR and wait for the master repo sync.
Regards

**Comment by alessandromalves** [comment]
Hey @lfbesada, I believe the best way is to wait for Brian's sync. Thank you!

**Comment by lfbesada** [comment]
I have joined this PR with [this one](https://github.com/liferay-echo/liferay-portal/pull/10354) to avoid conflicts between them since they are very related.

**Pull request closed without merging**
