### PR TITLE
[TS] LPP-46181 > LPS 160071 HTML injection in Liferay URL parameter p_p_id vulnerable to content spoofing

### PR DESCRIPTION
**Pull request by chileces**
Motivation
=======
Dear Team,
Our customer finds out an issue that HTML injection in Liferay URL parameter p_p_id vulnerable to content spoofing.
This PR is to fix it. Please help to review this solution and give me feedback.

Proposed Solution
========

Escape the header title attribute from the httpServletRequest before append to the writer

Steps to Verify
========
see Ticket https://issues.liferay.com/browse/LPP-46181 > https://issues.liferay.com/browse/LPS-160071

References to existing code (if applies)
========
similar to the title field, span content also need to be escaped

modules/apps/product-navigation/product-navigation-control-menu-web/src/main/java/com/liferay/product/navigation/control/menu/web/internal/LayoutHeaderProductNavigationControlMenuEntry.java line 93

Thank you very much,
@chileces

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by chileces** [comment]
@lfbesada thanks for your feedback, this is the fix for the source format issue of the previous PR: https://github.com/liferay-echo/liferay-portal/pull/9291

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @chileces 
Thanks for the fix! 
I have been trying to reproduce the reported bug in the master branch and can't reproduce it.
I have interpreted that in step 2 the screen name to be used is "laura" instead of "chii".
Trying to reproduce the bug I see on the page what is trying to be injected but the text is not clickable.
Could you please check if it is happening on the current master?
In case it is reproducible, please adjust the steps described in the ticket so we can reproduce the issue without your fix, and then, we can check that your fix solves it.
Thank you!
Regards

**Comment by chileces** [comment]
hi @lfbesada 
if you created a user with Screename "chii", the url should be http://localhost:8080/user/chii/manage?p_p_id=%3Ca+style=color:red;font-size:100px;width:100%25;height:2000px;position:fixed;z-index:1000;Top:0;left:0;background:white;text-align:center;+href=//example.com%3ECLICK-HERE%3C/a%3E

if you create a user with Screnname "laura", the url should be http://localhost:8080/user/laura/manage?p_p_id=%3Ca+style=color:red;font-size:100px;width:100%25;height:2000px;position:fixed;z-index:1000;Top:0;left:0;background:white;text-align:center;+href=//example.com%3ECLICK-HERE%3C/a%3E

this url is trying to inject a phishing url & content to the user control panel, at header title params.
Can you try it again?

**Comment by lfbesada** [comment]
Hi @chileces 
I tried it again with the same result, the text is not clickable. 
Can you reproduce this issue on the master branch?
Thanks
Regards

**Comment by chileces** [comment]
[](url)

> Hi @chileces I tried it again with the same result, the text is not clickable.
> 
> My current result is: _**Actual Result**: The content "CLICK-HERE" shows on the page. ~Clicking on the link will redirect you to example.com.~_
> 
> Can you reproduce this issue on the master branch? Thanks Regards
i can reproduce it with the master, i  put the evidence video in the attachment of https://issues.liferay.com/browse/LPS-160071

**Comment by lfbesada** [comment]
Hi @chileces 
Looking carefully at your video I have seen that the URL you use in the video is not the same as the one you wrote in the description of the ticket. I guess that's why I can't reproduce it, the URL in the ticket is escaped and the one you use in your video isn't.
Please, double-check that the ticket URL is correct and then I will try to reproduce it again.
Thank you

**Comment by chileces** [comment]
> Hi @chileces Looking carefully at your video I have seen that the URL you use in the video is not the same as the one you wrote in the description of the ticket. I guess that's why I can't reproduce it, the URL in the ticket is escaped and the one you use in your video isn't. Please, double-check that the ticket URL is correct and then I will try to reproduce it again. Thank you

hello @lfbesada , I have a double check, i create LPS content exactly the same as the LPP ticket to fix this issue. This LPP ticket was created by a CSE with their confirmation from the customer to reproduce. Can you try to look at https://issues.liferay.com/browse/LPP-46181 and https://issues.liferay.com/browse/LPS-160071 again? , i think there is an issue with copy text when you trying to paste it to the browser. Your url in the gif file is different than in the Jira tickets

**Comment by lfbesada** [comment]
Hi @chileces 
I have added to the ticket description the correct URL to reproduce the issue, please, review step number 5.
I will review this pull request using that URL instead of the one described in step number 5.
Are you agree?
Thanks
Regards

**Comment by lfbesada** [comment]
See: https://github.com/liferay-echo/liferay-portal/pull/9335

**Pull request closed without merging**
