### PR TITLE
LPS-148426 Fix: Not able to publish Content Pages when adding certain portlets to the page

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-148426

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
@lfbesada

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:stop

**Pull request closed without merging**
