### PR TITLE
LPS-135373 Sort by name

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
@Tim-Cao, we are replacing featured content fragments with compositions, so some tests might break (that's why I also added the lable, jic)

@ealonso

**Comment by jkappler** [comment]
If no tests fail, I'm going to forward it

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @jkappler，there is an issue I would like to double confirm the Name, Vocabulary, Friendly URL mapping fields are missing when select a category in editable field. Could you have a look at?

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/5184

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
