### PR TITLE
LPS-129168 Uses locale to cache the common styles, since the label change for each language

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:reevaluate:1117401_8606

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
