### PR TITLE
LPS-177533 Add permission restriction to the collection display fragment on EDIT mode Part II

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-177533

Dear reviewer,
In this PR, only commits with LPS-177533 should be reviewed.
This is the second part of [this PR](https://github.com/liferay-echo/liferay-portal/pull/11322) and includes its LPS-173462 commits because they are required to compile. To test the functionality all the commits of that PR are necessary.
Thanks in advance ❤️

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/11376 and https://github.com/liferay-echo/liferay-portal/pull/11377

**Pull request closed without merging**
