### PR TITLE
LPS-191643 Replace save-button and save-and-continue-button classes in edit_ddm_template.jsp

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-191643)

## Test Scenario 1
1. Navigate to Web Content
2. Create a new Web Content Template
3. Check the behaviour of “save and continue” and “save” buttons

## Test Scenario 2
1. Navigate to Templates
2. Create a new Information Template o Widget Template
3. Check the behaviour of “save and continue” and “save” buttons

Pasted Graphic 1

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
Niiiiice 👏 LGTM :D

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139179

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
