### PR TITLE
LPS-147515 Add macro for categorization of web content

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/8220

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
