### PR TITLE
LPS-174422 Create default utility page when creating a site

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-174422)

The goal of thee task is to add a default utility page when a blank site is created, and also when an 404 utility page is created

## Change summary:

* Create a new provider for the structure of the default utility pages
* Modify blank site initializer to create the default 404 utility page
* Modify so that when a user creates an utility page, it will be structured as the default one
* Change the vertical card for the utility page so that it has "Provided by Liferay Label"

## Test Scenario

* Enable FF feature.flag.LPS-155184=true
* Create a new site based on blank
* Go to Site Builder > Pages
* Go to Utility Pages tab
* Default 404 utility page is created and it's labeled as "Provided by Liferay"
* Click on + to add a new utility page
* The created utility page will have the structure of the default one

## Not covered in this task

Screenshot 2023-02-07 at 12 28 44

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by lfbesada — APPROVED** [review]
❤️

**Comment by lfbesada** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
@alessandromalves, fixed failing baseline. Thanks @lfbesada for mentioning it ❤️

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130401

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
