### PR TITLE
LPS-192968 Create modal for managing existing entries

### PR DESCRIPTION
**Pull request by Mikellorza**
https://liferay.atlassian.net/browse/LPS-192968

Waiting to merge this other one: https://github.com/liferay-echo/liferay-portal/pull/13392

cc: @claraizquierdo

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/13464

**Pull request closed without merging**
