### PR TITLE
LPS-109413 bnd

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
@Tim-Cao / @liulukiwi can you please test this locally before we send it to master?

**Comment by david-gutierrez-mesa** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
[Can not add new structure after upgrade when UpgradeDDMStructure using data engine](https://issues.liferay.com/browse/LPS-124577)

**Comment by Tim-Cao** [comment]
See https://github.com/jeyvison/liferay-portal/pull/898

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
