### PR TITLE
LPS-195942 When you update the friendly url of a web content and you publish it to Live, new FriendlyUrlEntry and FriendlyUrlEntryLocalization table entries are created but older ones aren't deleted

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://liferay.atlassian.net/browse/LPS-195942

**Problem:**
In the web content functionality, when you update a friendly url and you publish it to Live, new FriendlyUrlEntry and FriendlyUrlEntryLocalization table entries are created but older ones aren't deleted.

**Current behavior in the Staging environment (or without Staging enabled)**
If you change the friendly url title in the staging enviroment, the older FriendlyUrlEntry and FriendlyUrlEntryLocalization records are deleted because web content functionality doesn’t implements friendly url history and this point of the JournalArticleLocalServiceImpl is deleting the old records:
https://github.com/liferay-echo/liferay-portal/blob/d7210e871573904fcf486a55af02f57f5a2d2c74/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L7156-L7165

**Current behavior in the Live environment**
When you publish from Staging to Live, the creation of FriendlyUrlEntry and FriendlyUrlEntryLocalization records are handled by the FriendlyURLEntryStagedModelDataHandler and the deletion code of JournalArticleLocalServiceImpl is ignored due to this check:
https://github.com/liferay-echo/liferay-portal/blob/d7210e871573904fcf486a55af02f57f5a2d2c74/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L7117-L7121

This check was added by https://liferay.atlassian.net/browse/LPS-95020

**Reproduction steps**
See https://liferay.atlassian.net/browse/LPS-195942 description

**Solution**
To solve the issue, I am moving the code that deletes the old FriendlyUrlEntry records to a model listener.

The echo SME @dacousalr has already review this approach in https://liferay.atlassian.net/browse/PTR-4313

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:stop

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by liulukiwi** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141989

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
