### PR TITLE
LPS-121220 Removes buildings site initializer since it is out to date and we don't want to keep it in portal, we are going to develop a new site initializer see https://issues.liferay.com/browse/LPS-120773

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Rebase then resend. See https://github.com/liferay-echo/liferay-portal/pull/2437

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
