### PR TITLE
LPS-129599 Remove selectEntityHandler usages as part of migration to openSelectionModal

### PR DESCRIPTION
**Pull request by kresimir-coko**
This is a part of https://issues.liferay.com/browse/LPS-129599.

The change relies on `openSelectionModal` that is already implemented and removes the now obsolete usage of `Liferay.Util.selectEntityHandler`.

Only a part because removal of `Liferay.Util.getOpener().Liferay.fire` is waiting for https://github.com/pei-jung/liferay-portal/pull/824. So I just sent a PR that fixes half of the task but perfectly functions on it's own.

I've tested the changes manually, and everything works!

### CODE REVIEW

**Comment by victorg1991** [comment]
LGTM :) Thanks!

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
