### PR TITLE
LPS-173170 Change site initializer extender so that it can include utility pages

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-173170)

The goal of these changes is to allow site initializers to also take into account utility pages

## Change summary:

* Add code to site initializer extender to read utility pages
* Move 404 page from masterclass to utility page
* Update test cases
* Add integration tests

## Test Scenario

* Enable FF feature.flag.LPS-162765=true
* Create a new site based on master class
* Go to Site Builder > Pages
* 404 page will not be available
* Go to Utility Pages tab
* 404 utility page is created

utility pages

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Review by lfbesada — APPROVED** [review]
🤩

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
