### PR TITLE
LPS-202833 Set 'Search Results' as title if there is a search or filters applied

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
@jkappler @veroglez The `_isFilterApplied` method will need to be adapted to take into account the new parameter names once https://github.com/liferay-echo/liferay-portal/pull/14545 is merged.
Alternatively, we can call the `isNavigationXXX` methods to encapsulate parameter names in only one method and not depend on them here.

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
@ruben-pulido, we will fix this after the PR is merged after all

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
