### PR TITLE
LPS-171957

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Review by jkappler — APPROVED** [review]
Looks great @ealonso 🙌!

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
Hi @ealonso, conflicting files
modules/apps/client-extension/client-extension-web/src/main/resources/META-INF/resources/admin/edit_client_extension_entry.jsp, would you mind resolving it? thx!

**Comment by ealonso** [comment]
Hey @liulukiwi,

I already fixed the rebase errors.

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Failures are not related, pushed to BChan directly at https://github.com/brianchandotcom/liferay-portal/pull/130056

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
