### PR TITLE
[TS] LPS-190044 Ensure friendly URL entries are deleted on the live site when publishing

### PR DESCRIPTION
**Pull request by jonathanmccann**
Motivation
=======
This change ensures the deletion of friendly URLs on the Live side when publishing changes. This fixes https://liferay.atlassian.net/browse/LPS-190044.

Proposed Solution
========
To solve this problem I introduced a new method that is highly similar to _deleteMissingLayoutFriendlyURLs - https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/exportimport/data/handler/LayoutStagedModelDataHandler.java#L1154C15-L1154C47

It fetches the currently friendly URLs on the Live side and compares them against the ones being published. If one exists but is not being published then it is removed.

Steps to Verify
========
Please see the steps on https://liferay.atlassian.net/browse/LPS-190044

Notes
========
This has already been reviewed by the Staging team here - https://github.com/liferay-staging/liferay-portal/pull/354

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
