### PR TITLE
LPD-24489 If there are pages but none are visible link to the page administration

### PR DESCRIPTION
**Pull request by lfbesada**
Follow-up PR to [LPD-24489](https://liferay.atlassian.net/browse/LPD-24489): Redirect site links from site admin to page admin when pages exist but none are published

[LPD-24489]: https://liferay.atlassian.net/browse/LPD-24489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
Hey @lfbesada,

Could be possible to create a test for it?

**Comment by ealonso** [comment]
@lfbesada FYI: https://github.com/liferay-echo/liferay-portal/pull/15987/commits/3d71861a2b0116c11cee090fa196691c53dd60bf

**Comment by lfbesada** [comment]
@ealonso Thanks for the review :heart: I have added some JUnit tests. Could you please take a look? Thank you!

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1377401_17534

**Comment by lfbesada** [comment]
ci:report:43669251

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
