### PR TITLE
LPS-135304 layout-content-page-editor-web isolate Browser Panel CSS

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-135304

This PR isolates Browser Panel CSS.

The CSS I'm using to test:
```html
<style>
html {
  font-size: 20px;
}

#senna_surface1 h1,
#senna_surface1 h2,
#senna_surface1 h3,
#senna_surface1 h4,
#senna_surface1 h5,
#senna_surface1 h6 {
  background-color: #282828;
  border: 4px solid #00ff66;
  color: #00ff66;
  font-family: Georgia;
  font-size: 50px;
  font-style: italic;
  font-variant: small-caps
  font-weight: bold;
  line-height: 100px;
  letter-spacing: 2px;
  margin: 10px 0;
  padding: 10px;
  text-align: center;
  text-shadow: 1px 1px 0 #fff;
  text-transform: uppercase;
  white-space: nowrap;
}

#senna_surface1 .btn {
  background-color: #282828;
  border: 4px solid #00ff66;
  color: #00ff66;
  font-family: Georgia;
  font-size: 50px;
  font-style: italic;
  font-variant: small-caps
  font-weight: bold;
  line-height: 100px;
  letter-spacing: 2px;
  margin: 10px 0;
  padding: 10px;
  text-align: center;
  text-shadow: 1px 1px 0 #fff;
  text-transform: uppercase;
  white-space: nowrap;
}

#senna_surface1 .btn:hover {
  background-color: #000;
  color: #ffcc00;
  letter-spacing: 4px;
  font-size: 40px;
}

#senna_surface1 a {
  background-color: #282828;
  border: 4px solid #00ff66;
  color: #00ff66;
  font-family: Georgia;
  font-size: 50px;
  font-style: italic;
  font-variant: small-caps
  font-weight: bold;
  line-height: 100px;
  letter-spacing: 2px;
  margin: 10px 0;
  padding: 10px;
  text-align: center;
  text-shadow: 1px 1px 0 #fff;
  text-transform: uppercase;
  white-space: nowrap;
}

#senna_surface1 a:hover {
  background-color: #000;
  color: #ffcc00;
  letter-spacing: 4px;
  font-size: 40px;
}
</style>
```

Screenshot
browser-panel

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
hey @pat270 Just checked the pr, the page content tab doesn't have correct styles:

Screenshot 2021-07-08 at 18 02 40

Apart from that, there is also some files without the .cadmin prefix, don't we need that prefix in all the files??

**Comment by pat270** [comment]
@victorg1991 Sorry I missed those. I'll update the pr with those. In regard to adding `cadmin` to other files, I've been trying to update them component to make it easier to review and catch bugs. The other files will be updated in the pulls for Page Editor Inline controls and Page Editor Toolbar.

**Comment by pat270** [comment]
@victorg1991 I updated the pull, hopefully I got everything related to the Sidebar. Let me know if I'm missing anything else. I was unsure about this one (https://github.com/liferay-echo/liferay-portal/blob/2018d026d7f9b4e683986736650b31c5036ba207/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/common/components/_ColorPalette.scss) couldn't find where it renders in the UI.

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @victorg1991, the failure case is unrelated to changes in this PR. Feel free to let me know if there is no changes required.

**Comment by p2kmgcl** [comment]
I looked at the PR and I found some issues:

- ClayButtonWithIcon is not property spaced
image
master

- InlineConfirm component (used when you try to delete a comment) is not being shown, it has zero opacity
image

- Also comment box (Editor component) doesn't increase size automatically
image

- Sidebar loading indicator is misaligned
image

**Comment by victorg1991** [comment]
I've just found another one here:

Screenshot 2021-07-09 at 17 00 29

This should cover the whole text

**Comment by victorg1991** [comment]
Hey @pat270 

It seems that some of the failures has nothing to do with the css of the page editor, for example this button:
image

Without any of your changes, the btn has padding left 0 and padding right 0, that comes from clay. But after your changes it has some padding that comes from the theme. So it seems we are changing specificity of some selectors.

The selector with more specificity before any of the changes (including the one you sent a couple of days ago):
Screenshot 2021-07-09 at 17 04 22

The selector with more specificity now:

Screenshot 2021-07-09 at 17 04 02

Is this something expected? Do we need to change the css even more that just adding the .cadmin stuff?

Apart from that, we cannot use the sass's parent selector anymore, right? or we can still use it in some cases?

**Comment by pat270** [comment]
@p2kmgcl @victorg1991

Thanks for the feedback! I don't think I ever said these visual errors were because of Page Editor CSS? This isolate CSS feature is some what of a massive undertaking. I'm working with 2 css frameworks, custom portal markup, and custom portal css. There will be bugs...bear with me.

Specificity is the core concept behind this version of style isolation. It allows us to pick and choose the components we want isolated using the same class names and markup. See [Confluence](https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/blog/2021/05/19/1557659937/Isolating+Admin+Components+From+CSS+Customizations+for+Site+Creators) (it's a little out of date) for details.

For the select item issue, it's a combination of Page Editor not following the Clay CSS markup for `input-group` and Clay CSS not supporting `btn-monospaced` for Bootstrap's `input-group` markup. The difference:

###### clay.css
```html
<div class="input-group input-group-sm">
  <div class="input-group-item">
    <input class="form-control" type="text" />
  </div>
  <div class="input-group-item input-group-shrink">
    <button class="btn btn-monospaced btn-secondary" type="button"></button>
  </div>
</div>
```

###### bootstrap.css
```html
<div class="input-group input-group-sm mb-3">
  <input type="text" class="form-control" />
  <button class="ml-2 btn btn-secondary btn-sm" type="button"></button>
</div>
```

To answer your question, yes we will need to change CSS and markup. Don't fret though, I will change whatever you want. You just need to let me know what issues I miss since I'm not fully familiar with this component.

**Comment by victorg1991** [comment]
@pat270 Thanks for the explanation. Got it :) I thought that the wrapper wouldn't affect existing css. I'm going to dig it a bit more to see if I can find anything else.

Regarding the parent selector, can you provide examples where it is safe to use it?

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by pat270** [comment]
@p2kmgcl @victorg1991 I should have fixed all the issues listed here. Hopefully all the tests pass!

@Tim-Cao Just giving a heads up, I changed some markup so it might break some tests.

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/5135

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/5135

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
