### PR TITLE
LPS-166701 Uses is Dialog instead of a custom jsp

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Hi @ealonso， there's an issue found: can not upload app in App Manager, could you take a look? thanks! here are the steps:
1. Go to App Manager
2. Click ellipsis menu > go to upload

Actual result:
Upload modal is blank and error in broswer console:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'loadingmask')
`

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/125357

**Pull request closed without merging**
