### PR TITLE
LPS-125197 Use the name of the group of the company instead of the language key

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Thanks @adolfopa!
 
Leaving on hold until GA1 is out. Afterwards we can forward it directly.

@ealonso, fyi

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/4330

**Pull request closed without merging**
