### PR TITLE
LPS-181478 Remove FF                     

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
https://issues.liferay.com/browse/LPS-181478

# Motivation
Removes the FF for the Structure Tree migration to the Clay TreeView and fixes some bugs founded while removing the FF.
[Link to task](https://issues.liferay.com/browse/LPS-151678)
[Link to subtask](https://issues.liferay.com/browse/LPS-181478)

# Proposed Solution
Remove the FF flag and the old code and styles. We have also fixed some bugs with the calculation of the expanded nodes and some styles that were not being applied correctly for mapped nodes.

## Steps to Verify:

1. Go to home page and click on edit
2. In the left sidebar click on Browser section
3. Open the tree nodes and check that all the actions work for each node (rename, hide/show, save composition duplicate, delete, drag and drop)
4. Use a page with a master page and check that everything works fine

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by david-gutierrez-mesa** [comment]
ci:test:echo

**Comment by david-gutierrez-mesa** [comment]
ci:forward

**Comment by david-gutierrez-mesa** [comment]
Test failing in ci:test:echo are not related

**Review by claraizquierdo — APPROVED** [review]

**Comment by david-gutierrez-mesa** [comment]
ci:test:relevant

**Comment by david-gutierrez-mesa** [comment]
Test failing in relevant are not related to changes

**Comment by david-gutierrez-mesa** [comment]
ci:forward:force

**Pull request closed without merging**
