### PR TITLE
LPS-129598 Migrate selection modals in fragment modules

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @liferay-echo,

Attached is an update for http://issues.liferay.com/browse/LPS-129598.

Test Plan:

1. Login to Liferay
2. Click on the **Product Navigation Menu**
3. Go to **Design** -> **Fragments**
4. Click the `+` to add a new fragment collection
5. Click the `+` on the fragment collection to add a new fragment
6. Click on the ellipsis of the new fragment
7. Select **Move**
fragment

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Review by kresimir-coko — APPROVED** [review]
LGTM

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
