### PR TITLE
LPS-121963 Replace vertical-card-v2 with vertcal-card

### PR DESCRIPTION
**Pull request by carloslancha**
Follow up on https://github.com/liferay-echo/liferay-portal/pull/2987/

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
