### PR TITLE
LPS-175961 | Master

### PR DESCRIPTION
**Pull request by MirnaGama**
***Steps to verify:***
 1. Under default DXP site go to Design > Templates
 2. Create a new Widget Template
 3. Set a title
 4. Try to insert any combination that generates a character outside the Latin1. 
_Example:_ the vowels I or E with a tilde (ĩ ; ẽ) or a consonant along with an acute accent

_Result:_ The editor template is locked and nothing can be done except exit the page

***Proposed Solution:***

When the layout editor is locked, an error is displayed in the console browser:

> Uncaught DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

I did some research and discovered that this is an base64 escaping related issue. To fix it, we need to first escape the string with encodeURIComponent before encoding it to base64.

https://issues.liferay.com/browse/LPS-175961

### CODE REVIEW

**Comment by MirnaGama** [comment]
ci:test

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by MirnaGama** [comment]
ci:stop

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @MirnaGama this is already fixed by https://github.com/brianchandotcom/liferay-portal/pull/130175 which is tracked in https://issues.liferay.com/browse/LPS-174420 :)

**Pull request closed without merging**
