### PR TITLE
LPS-129316 - Style changes

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
LGTM :) I've talked with Juan about where to add this fragments, and he thinks that we can keep them in a separate module until we decide the final place. So this is good to go once the tests pass

**Comment by victorg1991** [comment]
Thanks!

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
