### PR TITLE
LPS-184932 Fix InfoFieldType's attributes usages

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-184932

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@lfbesada 😍

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
Hi @lfbesada , there are 2 issues found in these pull and three integretion tests failed, can you take a look?
here are the steps to reproduce the bugs:
Issue 1:

1. Add a basic web content
2. Add a spanish translation to the title and content via translate

Actual result:
The content and description do not display.
image

Issue2:
1. Add a basic web content
2. Add a display template for web content article > basic web content
3. Configure the display page template
4. Go to open graph
5. Click the bolt
6. Try to select content,description

Actula result:
Only Title, Author name, Last Editor Name display, no Content and Description.
issue

And here are the three failed integration tests, you can click Jenkins log to see the details:
[com.liferay.translation.exporter.test.XLIFF12TranslationInfoItemFieldValuesExporterTest
](https://testray.liferay.com/home/-/testray/case_results/2322646705)
[com.liferay.translation.exporter.test.XLIFF20TranslationInfoItemFieldValuesExporterTest
](https://testray.liferay.com/home/-/testray/case_results/2322646710)
[com.liferay.knowledge.base.internal.info.item.provider.test.KBArticleInfoItemFormProviderTest
](https://testray.liferay.com/home/-/testray/case_results/2322646393
)

**Comment by lfbesada** [comment]
Hi @liulukiwi Thanks a lot for the analysis, it helps me so much ❤️ Regards

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
Hi @lfbesada , rebase failed, can you take a look? thank you!

**Comment by lfbesada** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Hi @lfbesada , another issue was found and com.liferay.knowledge.base.internal.info.item.provider.test.KBArticleInfoItemFormProviderTest is still failed:
```    [exec] com.liferay.knowledge.base.internal.info.item.provider.test.KBArticleInfoItemFormProviderTest > testGetInfoForm STARTED
     [exec] 
     [exec] com.liferay.knowledge.base.internal.info.item.provider.test.KBArticleInfoItemFormProviderTest > testGetInfoForm FAILED
     [exec]     java.lang.AssertionError: expected:<com.liferay.info.field.type.TextInfoFieldType@3db68d73> but was:<com.liferay.info.field.type.HTMLInfoFieldType@3f528aba>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:120)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:146)
     [exec]     	at com.liferay.knowledge.base.internal.info.item.provider.test.KBArticleInfoItemFormProviderTest.testGetInfoForm(KBArticleInfoItemFormProviderTest.java:118)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
     [exec] ```

Here are the steps to reproduce:
1. Add a display page template
2. Go to configure it
3. Go to SEO

Actual result:
There's no HTML Title and Description field.
![image](https://github.com/liferay-echo/liferay-portal/assets/4900382/195da261-509d-4421-a71f-562501387a83)

Expected result:
![image](https://github.com/liferay-echo/liferay-portal/assets/4900382/7335b30d-b74a-4606-8821-4600fe4ad5d1)

**Comment by lfbesada** [comment]
Hi @liulukiwi You are helping me a lot! Thank you so much 😍

**Comment by lfbesada** [comment]
> Besides, do you change "Add Feed" to "Add Content" on purpose? before it was: image
> 
> now it is: image

Hi @liulukiwi it was an undesired change that is already fixed. Thanks for catching it 😍

**Comment by lfbesada** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Hi @lfbesada , 
1. com.liferay.knowledge.base.internal.info.item.provider.test.KBArticleInfoItemFormProviderTest > testGetInfoForm still fails in this pull:
```
    [exec] com.liferay.knowledge.base.internal.info.item.provider.test.KBArticleInfoItemFormProviderTest > testGetInfoForm FAILED
     [exec]     java.lang.AssertionError: expected:<com.liferay.info.field.type.TextInfoFieldType@11f1b272> but was:<com.liferay.info.field.type.HTMLInfoFieldType@b0460d0>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:120)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:146)
     [exec]     	at com.liferay.knowledge.base.internal.info.item.provider.test.KBArticleInfoItemFormProviderTest.testGetInfoForm(KBArticleInfoItemFormProviderTest.java:118)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec]     	at java.lang.Thread.run(Thread.java:750)
     [exec] 
     [exec] 1 test completed, 1 failed
```
2. “Map Field” still doesn't change back to "Add Field" under SEO's HTML Title, Description, Open Graph's Title, Description, Image Alt Description

3. Please merge this text-fix to your pull:https://github.com/lfbesada/liferay-portal/pull/178/commits/2164fcfd42974293c0c66fd1ba304ff83bc97ba8.

Can you take a look at these issues? thanks!

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Hi @lfbesada ,my bad,don't need to add additional test fix for this pull, I resend it here:  https://github.com/liferay-echo/liferay-portal/pull/12275.

**Pull request closed without merging**
