### PR TITLE
LPS-181652 Can't see Knowledge Base Article Child when Parent Article still pending

### PR DESCRIPTION
**Pull request by manuelecastro**
Related issue: [LPS-181652](https://issues.liferay.com/browse/LPS-181652)

**Motivation:** when a user creates a child article where the parent doesn't have an approved status, it's not possible to see its content page. 

**Proposed solution:** This happens because when the `getParentKBArticle()` method is called, it requests the KBA by approved status only, so when the parent article isn't _approved_ it throws a `NoSuchArticleException`. To solve this problem, I proposed to change the status parameter from `WorkflowConstants.STATUS_APPROVED` to `WorkflowConstants.STATUS_ANY` so no that matter what the parent's status is, it will return the article.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by manuelecastro** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @manuelecastro,

Could you please send this one to @liferay-lima? They are the owners of KB

**Comment by manuelecastro** [comment]
Resent here: https://github.com/liferay-lima/liferay-portal/pull/4229

**Pull request closed without merging**
