### PR TITLE
LPS-129802 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-129802

This is only for master.

@p2kmgcl

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, could you have a look at the failure about **Execution failed for task ':apps:layout:layout-content-page-editor-web:packageRunTest'**

**Comment by sandrodw3** [comment]
Sent here with frontend tests fixed: https://github.com/liferay-echo/liferay-portal/pull/4138

**Pull request closed without merging**
