### PR TITLE
LRAC-14606

### PR DESCRIPTION
**Pull request by riccardo-ferrari**
Hi team!

See LRAC-14606 for more details on the issue we're fixing here.

TLDR: We were mixing `experienceIds` from the terminated test with the newly created one leading to errors in some corner case.

In this PR:

- When removing a test we make sure to reset the relevant `experienceId` to the DEFAULT one (that is always existing).
- We avoid associating the variant `experienceId` of a terminated test with the newly created one.

Thanks!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by riccardo-ferrari** [comment]
ci:test:sf

**Comment by riccardo-ferrari** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
