### PR TITLE
LPS-133940 Use the correct resourceName. For some cases it may be DDMTemplate, but for other is a composite name like DDMTemplate+JournalArticle

### PR DESCRIPTION
**Pull request by victorg1991**
Co-authored-by: Rubén Pulido <ruben.pulido@liferay.com>

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:stop

**Comment by ruben-pulido** [comment]
ci:close

**Pull request closed without merging**
