### PR TITLE
LPS-127007 Get the optionReference instead of the label

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:reevaluate:1162004_7788

**Comment by Tim-Cao** [comment]
ci:reevaluate:1162004_7788

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
