### PR TITLE
[TS] LPS-144732

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

I'm not sure a326a4983fcbe3df73515c9d7c1459436dcec3fb is the best solution, but I really want this logic to be extracted to one place for maintenance reasons.
Also I'm not quite sure if setting the default Locale of deleted-user to en_US is  correct in all cases, what do you think?

Can you please review?
https://issues.liferay.com/browse/LPS-144732

Thanks,
Balázs

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
checking the test failures

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @balazssk, Would you mind fixing semantic verisoning issue?

**Comment by balazssk** [comment]
Hi @Tim-Cao ,
Sure, I've rebased to the latest master and fixed the semver

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
Hi @ruben-pulido , @Tim-Cao ,
Can you please check this?
Thanks

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @balazssk,

IMHO, is better if we update the code to control if the user was deleted or not in **GetContentDashboardItemInfoMVCResourceCommand**, as I can see the problem is because the following method is returning null, so we are getting a NullPointerException.

```java
WebImage webImage = (WebImage)contentDashboardItem.getDisplayFieldValue(
	"authorProfileImage", locale);
``` 

So, you should send it to @liferay-tango, since they are the owners of content dashboard.

Regards,
Eudaldo.

**Comment by balazssk** [comment]
Hi @ealonso ,
Cheers for the feedback, I'll look through the web layer in more detail and will send the next version to the tango team.

**Pull request closed without merging**
