### PR TITLE
LPS-138557 Rely on themeDisplay to get current locale in order to avoid null request objects

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

I reviewed the tests that failed in https://github.com/liferay-echo/liferay-portal/pull/5716 and add a commit trying to mimic some similar protected getter methods within the same class.

Could you please review it?

Thanks in advance

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reevaluate:1297401_220

**Comment by dacousalr** [comment]
ci:reevaluate:1297401_220

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
