### PR TITLE
LPS-194405 and LPS-194258 Adjust styles for the Locked Pages configuration and moves the code to layout-locked-layouts-web module

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-194258
https://liferay.atlassian.net/browse/LPS-194405

cc: @veroglez

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward:force

**Comment by lfbesada** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
manual forward: https://github.com/brianchandotcom/liferay-portal/pull/139776

**Pull request closed without merging**
