### PR TITLE
LPS-185998 Remove unused custom sql in asset-list-service

### PR DESCRIPTION
**Pull request by YurenaC**
Motivation
=======
In order to take advantage of the cache used in the DSLQueries, we will be migrating several database queries used in finder classes to improve performance

[story](https://issues.liferay.com/browse/LPS-185998)

Commits:
=======
- LPS-185998 Remove unused custom query
- LPS-185998 Remove finder
- LPS-185998 BuildService

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136458

**Comment by YurenaC** [comment]
Thank you very much @Tim-Cao!

**Pull request closed without merging**
