### PR TITLE
LPS-145232 Prefix DDMStructure and vocabulary info fields

### PR DESCRIPTION
**Pull request by victorg1991**
This PR adds prefixes to the DDMStructure and vocabulary info fields. Also it makes sure that old non-prefixes values work fine in the page editor.

### Problematic
In version older than 7.4 it it is possible for info fields to collide. Since we didn't have any prefixes in the names, creating structure fields named `title` or `description` collided with the existing fields. This collision cause that some of the two problematic fields could not be mapped. In master it is almost impossible to 

### Solution
Solving the collision once it appears is impossible for us because we don't know which field of the two colliding we should pick. Instead of that we decided to focus on avoiding possible conflicts in the future. For doing so, we are namespacing all the fields that come from the ddmStructure and the vocabularies (all the other dynamic fields, like DDMTemplate or ExpandoFields are namespaced already). For keeping backwards compatibility what we have done is to duplicate the field values, with and without prefix.

#### Frontend
The fix for the page editor is a bit tricky, here we only have one thing, the `fieldId` (It may be the mappedField in Display pages, or the collectionFieldId inside collection display) which contains the key of the associated info field. If this value was set in a previous version (or simply a 7.4 portal version without this fix), the field key won't have the namespace. In this case, the only thing that we can do is to try to look for the field with the new namespaces. Remember that we won't be fixing collisions, so it should be only one field.

#### How to test this

AFAIK, this is only used in the Mapping feature in the Page Editor and in the Web content translation feature. **Are there more usages I'm not aware of**?

Since in master there is little chance of collision (for instance, an user may create a vocabulary called `title` or `description`) the best way to test this is downloading a 7.3 version and:

1. Create some custom WC structure and document types
2. Create some WC, Blogs and Document with the custom structures/document types
3. Translate the WC to some languages
4. Create some Pages and display pages, add fragments and mapped the content
5. Upgrade the database and run a portal with this changes deploys
6. Check that all pages and translations are equal to the ones in 7.3

Any comments are appreciated, and any better alternativas are more than welcome 🤝

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @victorg1991, there is a regression issue
**Steps to reproduce**
1. Add a Heading fragment to a content page
2. Click the editable field of Heading

**Expected Results**
The Mapping panel should be rendered well.

**Actual Results**
The Mapping panel is broken. Btw, the following error shown in browser console.
Actual

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by victorg1991** [comment]
Good catch @Tim-Cao

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
mentioning here @adolfopa and @AliciaGarciaGarcia since I added some changes in the translation module 😇

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@victorg1991 Why not extends the Info API? The `name` attribute of an info item serves two purposes right now: as a name and as an identifier. Why not add a new mandatory `id` attribute and enforce the restriction that these ids are globally unique (per form). That way, we could still preserve a meaningful name and we wouldn't need to add/remove the prefix in the updaters.

Also, this won't solve conflicts in case there are, for example, multiple DDM structures that provide fields for an info form. Why not derive the namespace used in the ID from the className/classPK or the source model (vocabulary or structure).

**Comment by ricardocousolr** [comment]
Hi @adolfopa! 

Would your approach work for `7.3.x` as well? Or just for `master`? I'm asking because a solution to this issue would solve the problem of a customer who's in 7.3.10. (See [PTR-2747](https://issues.liferay.com/browse/PTR-2747) for more context.)

**Comment by adolfopa** [comment]
It depends, but I'd say it is for master only. Including a mandatory "id" step in the build will be a breaking change.

**Comment by bakayattila** [comment]
Hi @adolfopa,
An approach that is backportable to 7.3.x would be better because most of the use cases are relevant for 7.3.x or people who upgraded from 7.3.x. For more information please check [PTR-2847](https://issues.liferay.com/browse/PTR-2847).

**Comment by victorg1991** [comment]
> @victorg1991 Why not extends the Info API? The name attribute of an info item serves two purposes right now: as a name and as an identifier. Why not add a new mandatory id attribute and enforce the restriction that these ids are globally unique (per form). That way, we could still preserve a meaningful name and we wouldn't need to add/remove the prefix in the updaters.

That sounds good but I believe we'll have problems backporting it 😢  In master the collision are very unlikely, so this solution must serve mainly for other versions. Would this work for translations? Or this approach isn't valid for that?

> Also, this won't solve conflicts in case there are, for example, multiple DDM structures that provide fields for an info form. Why not derive the namespace used in the ID from the className/classPK of the source model (vocabulary or structure).

In which case this may happen? a custom infoForm that takes takes fields for several structures?

**Comment by adolfopa** [comment]
> > @victorg1991 Why not extends the Info API? The name attribute of an info item serves two purposes right now: as a name and as an identifier. Why not add a new mandatory id attribute and enforce the restriction that these ids are globally unique (per form). That way, we could still preserve a meaningful name and we wouldn't need to add/remove the prefix in the updaters.
> That sounds good but I believe we'll have problems backporting it cry In master the collision are very unlikely, so this solution must serve mainly for other versions. Would this work for translations? Or this approach isn't valid for that?
> 

That could be worked around by making that builder method optional in the backport (keeping it mandatory in master). Not ideal, but at least we'd not be compromising master due to the needs of 7.3.x.

Also, I guess collisions are unlikely because of the way we're using the API. But we should keep in mind that this is a general API, and we cannot predict how it will be used in the future. I'd very much prefer to fix any collision issues once and for all, for our future selves sake :-)

> > Also, this won't solve conflicts in case there are, for example, multiple DDM structures that provide fields for an info form. Why not derive the namespace used in the ID from the className/classPK of the source model (vocabulary or structure).
> 
> In which case this may happen? a custom infoForm that takes takes fields for several structures?

The Info API allows it, there's nothing preventing it. DDM also allows linking multiple structures to the same item.

**Comment by adolfopa** [comment]
@victorg1991 I'm sorry, but this won't work for translations (even as a 7.3.x only solution). Duplicating fields will break translations; all fields will show up duplicated in the side by side forms and in the exported XLIFF files.

**Comment by victorg1991** [comment]
Another approach is evaluated here: https://github.com/liferay-echo/liferay-portal/pull/7570

**Pull request closed without merging**
