### PR TITLE
LPS-127294 Move top and bottom margin to topper

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:stop

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
cc @ruben-pulido

**Comment by sandrodw3** [comment]
ci:stop

**Comment by sandrodw3** [comment]
ci:stop

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
@sandrodw3 Please resend, 😄

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
