### PR TITLE
LPS-184922

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
We want to improve the process of importing fragments.
[Link to story or ticket](https://issues.liferay.com/browse/LPS-184922)

Proposed Solution
========
We have created a new modal for importing in React so that we can customize better its UX. We have also move the warning messages to the view.jsp so that they are visible after closing the modal.
There will be follow up PRs changing the alert messages and the importation of page templates.

Steps to Verify:
----------------
1. Add `feature.flag.LPS-174939=true` to your portal-ext.properties
2. Go to Design -> Fragments and in the three dots menu click on Import (everything should work the same in importing fragment sets and fragments)
3. Check that the modal width is 600px.
4. Check that there is a paragraph before the input with the text: “Select a Zip File containing one or multiple entries.”.
5. Check that the "Select file" label has been replaced with with "File".
6. The "Overwrite Existing Entries" label should not be bold.
7. The import button should be disabled until a zip file is selected.
8. Try importing fragments with no errors and with some errors. Check that the success, error and warning messages appear outside the modal and after the modal has been closed.
9. Check that everything works without the Feature Flag

Screenshoots:
----------------
Captura de pantalla 2023-05-18 a las 13 06 25

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by claraizquierdo** [comment]
ci:reevaluate:1257401_1099

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
Hi @claraizquierdo, [js-unit-jdk8/0/0](https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/511105//consoleText) fails for apps:fragment:fragment-web:packageRunTest FAILED, event.target.files.item is not a function, can you take a look? thanks!

**Comment by claraizquierdo** [comment]
> Hi @claraizquierdo, [js-unit-jdk8/0/0](https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/511105//consoleText) fails for apps:fragment:fragment-web:packageRunTest FAILED, event.target.files.item is not a function, can you take a look? thanks!

Thank you @liulukiwi , I've fixed the tests that were failing. Hope it passes now 🤞

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:reevaluate:1397401_4858

**Comment by claraizquierdo** [comment]
ci:reevaluate:1397401_4858

**Comment by liulukiwi** [comment]
Failures are not related, pushed to BChan directly at https://github.com/brianchandotcom/liferay-portal/pull/135272

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
