### PR TITLE
LPS-161255 Do not show favorites in search results

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:reevaluate:1317401_4894

**Comment by liulukiwi** [comment]
[com.liferay.portal.log.assertor.PortalLogAssertorTest.testScanXMLLog](https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208680//testReport/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog) not related, pushed to BChan directly: https://github.com/brianchandotcom/liferay-portal/pull/122743

**Pull request closed without merging**
