### PR TITLE
[TS] LPS-173683 moving check to higher level to fix the thrown error

### PR DESCRIPTION
**Pull request by GaborKomaromi**
Hi Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-173683
Thank you!
---------
**Reproduction Steps:**

1. Create a new site
2. In the settings, the new site under SITE URL → Public Pages add a virtual host under which the site can be used.
3. Add at least one page to the site
4. Deactivate the site
5. Go to [virtualhost]:8080/sitemap.xml
**Expected outcome:** There are no error messages in the log, and the HTTP status code returned on the network tab is 404.
**Actual outcome:** There is a NullpointerException error in the log, and the HTTP status code returned on the network tab is 500.

Solution:
I placed the check from [LPS-171955](https://issues.liferay.com/browse/LPS-171955) to a higher level to avoid empty file creation and matched it with the right exception.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by GaborKomaromi** [comment]
ci:test:relevant

**Comment by GaborKomaromi** [comment]
ci:test:sf

**Review by lfbesada — APPROVED** [review]
Hi @GaborKomaromi 
Thanks for the fix ❤️ 
LGTM
Regards

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
