### PR TITLE
LPS-206655

### PR DESCRIPTION
**Pull request by jonathanmccann**
https://liferay.atlassian.net/browse/LPS-206655

This change was previously made in https://liferay.atlassian.net/browse/LPS-125313 but then changed back in https://liferay.atlassian.net/browse/LPS-139326. As far as I can tell the change in LPS-139326 seems almost accidental but please let me know if there is a reason why it should be looking at the `dataType` instead.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
