### PR TITLE
LPS-171587 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-171587

This is only for master.

@ealonso

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by david-gutierrez-mesa** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, would you mind fix the semantic versioning for item-selector-criteria-api ?

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/10701

**Pull request closed without merging**
