### PR TITLE
LPS-138914 Rename parameter

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-138914

https://github.com/brianchandotcom/liferay-portal/pull/107057#issuecomment-918346652

cc: @victorg1991

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
