### PR TITLE
LPS-160326  fix occasional NPE after session extension or use of "remember me" login

### PR DESCRIPTION
**Pull request by olafk**
fix occasional NPE after session extension or use of "remember me" login

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by olafk** [comment]
ci:test:sf

**Comment by olafk** [comment]
ci:test:sf

**Comment by olafk** [comment]
I have no clue what that failing SF wants to tell me. Is it the change in the last line, that the github editor has brought into the commit? 
Could somebody take over?

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/9284

**Pull request closed without merging**
