### PR TITLE
LPD-24488 Move the logic of LayoutCopyHelper to the service layer

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-24488 

The safe closeable has been maintained despite being already in the services layer because a serious worsening of performance has been perceived when removing it, see: https://github.com/lfbesada/liferay-portal/pull/251

In this Slack thread, I try to understand why it happens: https://liferay.slack.com/archives/CLUBRGT42/p1716792444094989?thread_ts=1714374932.401359&cid=CLUBRGT42

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:echo

**Comment by lfbesada** [comment]
ci:report:2572230156

**Comment by lfbesada** [comment]
I am adding the On Hold label because some echo routine failures are because of JSONLayout.publishLayout macro is not publishing the page, I think it could be related but I am not sure yet

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:echo

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:report:2572290987

**Comment by lfbesada** [comment]
ci:report:2572300872

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:report:2572611468

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
