### PR TITLE
LPS-146807

### PR DESCRIPTION
**Pull request by mbowerman**
Original comments from @javalosjr96:

> Ticket:
> https://issues.liferay.com/browse/LPS-146807
> 
> Issue:
> Scheduled Articles continue to be displayed with scheduled filter when edited to be published
> 
> Cause:
> The WHERE clause for Journal Status in the SQL query `findA_ByG_U_F_L` was not filtering results correctly.
> 
> Fix:
> Use WHERE clause outside of other criteria for search. 
> 
> NOTE:
> I checked out a failed test on my branch, I ran the test locally and it passed.

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @mbowerman @javalosjr96,

Could you please add an integration test for it?

Regards,
Eudaldo

**Comment by javalosjr96** [comment]
@ealonso OK.

**Comment by mbowerman** [comment]
Hi @ealonso,

@javalosjr96 has written and integration test, and I've updated the pull request

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by lfbesada** [comment]
Hi @javalosjr96 @mbowerman 
Thanks for the PR!
I've been testing it locally and I'm afraid it doesn't work correctly, it breaks the "With Approved Versions" and "With Expired Versions" filters, as well as not achieving the desired behavior in the case of a combination of status Scheduled + Draft.
On the other hand, I have been discussing this bug with other developers and with product management and we have concluded that the scheduled filter currently works correctly. It has the same behavior that "With Approved Versions" and "With Expired Versions" so what is incorrect is its label. Therefore we will fix this bug by changing the copy from "Scheduled" to "With Scheduled Versions".
Please, if you want a filter that works the way you want, do not hesitate to open a feature request so that its incorporation can be analyzed.
Please see: https://github.com/liferay-echo/liferay-portal/pull/7230
Regards

**Pull request closed without merging**
