### PR TITLE
LPS-118554 Integration test for new JournalArticleInfoItemPermissionProvider verifying that we cannot view an article without the required permissions

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
Since failure task unrelated to the change in PR and in order to not clog up ci resources I pushed directly to BChan.
See brianchandotcom#92323

**Pull request closed without merging**
