### PR TITLE
LPS-147252, LPS-147253 & LPS-146976

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Hi @sandrodw3, the failure tests are unrelated to this PR. I've forwarded it manually. Feel free to close it if you have any doubt. Thanks!

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114307

**Comment by Tim-Cao** [comment]
ci:close

**Comment by lfbesada** [comment]
ci:reopen

**Comment by lfbesada** [comment]
This pull request is waiting for https://issues.liferay.com/browse/LPS-147251 and https://issues.liferay.com/browse/LPS-148717. It shouldn't be forwarded until this task were completed.

**Comment by Tim-Cao** [comment]
Sorry @lfbesada , I see

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
https://github.com/liferay-echo/liferay-portal/pull/7451

**Pull request closed without merging**
