### PR TITLE
LPS-196853 Fix focus lost when changing selection

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
The focus is lost when changing selection with the keyboard in the ContentFilter Picker. When a selection is made by pressing enter or space while an item is focused, the menu should close and the focus should move back to the trigger
[Link to ticket](https://liferay.atlassian.net/browse/LPS-196853)

Proposed Solution
========
The problem was that we were defining the custom trigger inside the component. We had to move it outside.

Steps to Verify:
----------------
1. Go to page editor
1. On the left sidebar click on "Page Content"
1. Navigate with the keyboard to the Content filter and select a type of content.
1. The focus should move back to the trigger after selecting a type of content

Screenshots (optional):
-----------------------

Captura de pantalla 2023-09-21 a las 14 03 08

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
