### PR TITLE
LPS-179466, LPS-180031, LPS-180032, LPS-180034, LPS-180035 Add test to view error message when get asset library vocabulary by non-exit erc

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-179466
https://issues.liferay.com/browse/LPS-180031
https://issues.liferay.com/browse/LPS-180032
https://issues.liferay.com/browse/LPS-180034
https://issues.liferay.com/browse/LPS-180035

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by ealonso** [comment]
@Tim-Cao very nice!! 👏🏾

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
