### PR TITLE
[TS] LPS-194654 Scheduled web content version gets the wrong author after getting Approved

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
When a Web Content Article's publication is scheduled, the displayed author will be the user who made the editing, while the Article is in the SCHEDULED status. After the scheduled publication, however, the displayed author will be that of the creator of the Article.
This behavior seems incorrect because if the Article is published right away without scheduling, the author will be the user who made the publishing. 

Proposed Solution
========
When an Acticle's scheduled publication is being performed, it will be updated with the statusByUserId of the article's creator. This should be the user who scheduled the Article instead.

Steps to Verify
========
Please see the linked LPS for the reproduction steps.
https://liferay.atlassian.net/browse/LPS-194654

Thank you and best regards,
István

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by lfbesada — APPROVED** [review]
Hi @IstvanD 
Thanks for the fix! It works like a charm :clap: 
LGTM :tada: 
Regards

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
