### PR TITLE
LPS-161719 Don't add the href if the item is not browsable

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by ozysouza** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @victorg1991, would you mind rebasing codes?

**Comment by victorg1991** [comment]
Sure @Tim-Cao

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
done @Tim-Cao

**Comment by ozysouza** [comment]
ci:reevaluate:1277401_4781

**Comment by ozysouza** [comment]
I've analyzed all integration tests that are current failing on ci:test:relevant. They are no related to this PR.

**Comment by ozysouza** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @victorg1991, do you think is rebase necessary for changes in this PR? since [semantic-versioning-jdk8/0/0](https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/96352//consoleText)
Please fix semantic versioning on https://github.com/liferay-echo/liferay-portal/pull/9508

**Comment by ealonso** [comment]
Hey @Tim-Cao,
It is not necessary, if the tests failures are not related we can manually forward it.
Regards,
Eudaldo

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122798

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
