### PR TITLE
LPS-128471 Check for HashMap and then for any other type, so that we also cover numbers, not only strings

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@victorg1991

**Comment by jkappler** [comment]
ci:forward

**Comment by jpince** [comment]
ci:stop since the first test run completed & pull was forwarded

@jkappler please avoid duplicate test runs. `ci:test:relevant` started one run, then immediately commenting `ci:test:forward` started a second run. See https://liferay.slack.com/archives/C19PWQ74J/p1614718785029800

**Comment by jkappler** [comment]
Hi @jpince, didn't noticed. Will pay more attention in the future. Thanks for the heads up

**Pull request closed without merging**
