### PR TITLE
LPS-121881 Migrate v2 usages in journal-web

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hi @liferay-echo team. This is a continuation of https://github.com/liferay-echo/liferay-portal/pull/3891, where I missed some management toolbars to migrate. 

The `<clay:management-toolbar-v2 />` tag has been replaced with the
`<clay:management-toolbar />` tag (which uses clay v3).

**Test plan for each of the jsps changed:**

1. Go to Control Menu > Content Data > Web Content
2. Web Content tab: `view.jsp`
3. Structures tab: `view_ddm_structures.jsp`
4. Templates tab: `view_ddm_templates.jsp`
5. Go back to Web Content tab, and select any item and click on "View History" on the kebab menu: `view_article_history.jsp`
6. Create more than 8 structures. On the Web Content tab click on + icon, and then on "Show more" button: `view_more_menu_items.jsp`
7. Enable Feeds (System settings > Web Content > admin > check "Show Feeds". Then go back to Control Menu > Content Data > Web Content and select the "Feeds" tab: `view_feeds.jsp`
8. Edit a page, insert and element and map it to a content: `select_articles.jsp`
image (2)

Let me know if you need any help with this.
Thank you!

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Review by julien — APPROVED** [review]
LGTM! Thanks @ambrinchaudhary

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:reevaluate:1027401_210

**Comment by p2kmgcl** [comment]
> **Jenkins Build:**[test-portal-acceptance-pullrequest(master)#210](https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/210/)
> **Jenkins Report:**[jenkins-report.html](https://test-1-2.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/210/jenkins-report.html)
> **Jenkins Suite:** relevant
> **Pull Request:**[liferay-echo#3995](https://github.com/liferay-echo/liferay-portal/pull/3995)
> **Spira Release:**[/Liferay DXP 7.4/Pull Request/ci:test:relevant](https://liferay.spiraservice.net/16/Release/2004.aspx)
> **Spira Release Build:**[master - ambrinchaudhary > liferay-echo - PR#3995 - 2021-03-11[08:27:12]](https://liferay.spiraservice.net/16/Build/101220.aspx)
> **Spira Jenkins Build:**[publish-spira-report#15052](https://test-1-8.liferay.com/job/publish-spira-report/15052/)

@ruben-pulido
Do you know if it finished? It looks like it got stuck, but I don't know which log should appear.

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
Hi @john-co, @zhangyan0701 and @calvinctvo, could you please help us to resolve the poshi failures if they are related to the changes we did in the management toolbar? 

Thank youo very much!

**Comment by zhangyan0701** [comment]
ci:test:bundle

**Comment by zhangyan0701** [comment]
Hi @ambrinchaudhary 

The failures should be related.

When mouse over the plus icon in Web Content, the tooltip that displays under the plus icon is same as the first menu item in the dropdown. So in the failed tests, it supposed to click the menu item but click the tooltip instead.

- **LocalFile.CPRolesCPWebcontent#AddFolderSiteRoleDefinePermission**
- **LocalFile.WebContentUI#AddFolder**
- **LocalFile.WebContentWithPermissions#AddAndViewStructureAndTemplateWithPermissions**

In these three tests, the tooltip of plus icon is "Folder".
folder

- **LocalFile.CPRolesCPWebcontent#AddWebContentSiteRoleDefinePermission**
In this test, the tooltip of plus icon is "Basic Web Content", the logged user doesn't have add folder permission, so the dropdown menu only have one item.
content

**Comment by jonmak08** [comment]
Hey @zhangyan0701 and @ambrinchaudhary,

The CI errors should be fixed by https://github.com/brianchandotcom/liferay-portal/pull/99844/commits/2abcbca16ffa05711fa1a74c7f5e9d18775b51a9 which is waiting @brianchandotcom to push in at https://github.com/brianchandotcom/liferay-portal/pull/99844.

When that goes in the tooltip message should be resolved.

Please let me know if you have any questions. Thanks!

**Comment by ambrinchaudhary** [comment]
> The CI errors should be fixed by [brianchandotcom@2abcbca](https://github.com/brianchandotcom/liferay-portal/commit/2abcbca16ffa05711fa1a74c7f5e9d18775b51a9) which is waiting @brianchandotcom to push in at [brianchandotcom#99844](https://github.com/brianchandotcom/liferay-portal/pull/99844).

Thank you @jonmak08, yeah, it seems that will be fixed with that pull. Once merged I will rebase and run tests again 🙏

**Comment by jbalsas** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/99844 has been merged and made it upstream, so going to trigger a retest.

This is the last MT that's pending migration. It would be great if we can get this in asap so we have the stabilization period to hash over any possible issues and also as a way to unblock removing the old implementation before we hit GA1.

@Tim-Cao, could you please stay on top of those issues to forward if possible? Seeing as @sandrodw3 already tried `ci:forward` once I'd hope it's okay.

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
First 2 errors seem unrelated:

> LIFERAY_ERROR: Unable to connect to a valid mail server. Please make sure one is properly configured: Couldn't connect to host, port: localhost, 25; timeout -1

Last 2 errors still showcase the "Folder" label in the Creation Menu instead of "New".

@jonmak08, could you take a look see if this still needs an additional fix on top of https://github.com/brianchandotcom/liferay-portal/pull/99844?

**Comment by jonmak08** [comment]
Closing in favor of https://github.com/liferay-echo/liferay-portal/pull/4024 since there was a change to the `creationMenu` (https://github.com/liferay-echo/liferay-portal/pull/4024/commits/24b22574ae78633ba6a01f253dc7545615c2b321) that was needed.

**Comment by jonmak08** [comment]
ci:close

**Pull request closed without merging**
