### PR TITLE
LPS-125952 It's not enough with a dummy upgrade since the AssetEntryUsage doesn't exist if we are upgrading from 7.0, so creating a new upgrade process to add the table and indexes

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @achaparro @jkappler @dacousalr

Could you please take a look at it? I think we need to backport it, since the AssetServiceUpgrade is not being execute if you come at least from 7.0, I don't know if we have the same problem from 7.1, 7.2 or 7.3

Regards,
Eudaldo.

**Comment by achaparro** [comment]
Hi @ealonso,

If you want customers coming from old versions where this module did not exist execute the whole list of upgrade processes. You need to add your module here:
com.liferay.portal.upgrade.v7_4_x.UpgradeModules

In that way, the release record will be created and initialized with 0.0.1. You can start the upgrades from that point.

Let me know if this clarifies it.

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/4139

**Pull request closed without merging**
