### PR TITLE
LPS-172983 Remove Feature Flag LPS-135863

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://issues.liferay.com/browse/LPS-172983)

**The PR is on hold because it needs to be tested.**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:echo

**Comment by DiegoHu97** [comment]
Updated @victorg1991 😄

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/11225

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
