### PR TITLE
LPS-162207 - When empty message is configured by the user it should be used in view mode instead of the default message

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @victorg1991

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
fyi @Tim-Cao

**Comment by ozysouza** [comment]
ci:reevaluate:1307401_4476

**Comment by ozysouza** [comment]
ci:forward

**Pull request closed without merging**
