### PR TITLE
LPS-178316 Use ddm structure id instead of ddm structure key when creating or updating a journal article

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-178316

cc: @ealonso

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
Hi @lfbesada, there is an issue related to remote service.
2023-03-19 14:23:19.773 ERROR [http-nio-8080-exec-5][JSONWebServiceServiceAction:126] No JSON web service action with path /journal.journalarticle/add-article and method POST for journal
Would you mind having a look at? Thanks

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/11482

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
