### PR TITLE
LPS-197569 When you create a webcontent using the headless API, the display date is not correct

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://liferay.atlassian.net/browse/LPS-197569

When you create a web content using the headless API and the Liferay user is configured with a timezone different to GMT/UTC, the display date of the created web content is not correct, it will created with a date some hours before or later than current one, depending on the configured time zone.

This behavior:
- Is not reproduced if you create the web content from the user interface, the dates will match
- Is also reproduced If you specify a custom publish date in the headless API, it will be always created with some hours offset than the specified, depending on the configured timezone.

**Root cause of the issue**

- The `JournalArticleLocalServiceImpl.addArticle` method converts the received displayDate from the user time zone to GMT before saving it to the database, see: https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L375-L377
- The headless API uses the dates in UTC time zone when calling the JournalArticleLocalServiceImpl.addArticle method.

**Steps to reproduce**

- See [LPS-197569](https://liferay.atlassian.net/browse/LPS-197569) description

**Implemented solution**

- To solve the issue I have changed the headless code that calls `JournalArticleLocalServiceImpl.addArticle` adding a conversion from UTC to the user's time zone.

[LPS-197569]: https://liferay.atlassian.net/browse/LPS-197569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
Hi @jorgediaz-lr
Thanks for the PR!

Although the implementation in the PR works, I believe we can simplify it and make it more efficient.

In the PR we are receiving the date in UTC, we then convert it to the user's timezone, and then within `JournalArticleLocalServiceImpl` it is converted back into a Date object.

We can avoid performing this double conversion by overloading the method `addArticle` in `JournalArticleLocalServiceImpl` so it receives `Date` objects for `expiration`, `display` and `review` dates, and refactoring the existing `addArticle` so after it computes the `Date` objects it calls the new version of the method.

This way the headless code can call the new version of the method directly, without having to perform any date conversions.

**Comment by ruben-pulido** [comment]
Setting it on hold until an agreement is reached on which solution to move forward with

**Comment by ealonso** [comment]
Hey @ruben-pulido @jorgediaz-lr, 

I've already implemented the necessary methods for Journal API, please see https://github.com/liferay-echo/liferay-portal/pull/13883. 

Is it enough? Do you need something else @jorgediaz-lr ?

So, if it necessary Could you please pick my commits and apply those to your pr.

Regards,
Eudaldo.

**Comment by jorgediaz-lr** [comment]
@ealonso yes, I can use them, but in my opinion:

1. The new API methods are not consistent, the new ones that receives the Date objects expects these Date objects to be created using the GMT timezone and the old ones receives the long parameters in User's timezone, so a customer that is using this API will get confused
2. You have added the Date methods in the **addArticle** but you didn't add them in other existing methods (for example **updateArticle**, _I don't need them to fix this issue, but they should be added in order to get a consistent API_)

Nevertheless if you don't think this is a problem, I will go ahead.

**Comment by jorgediaz-lr** [comment]
@ealonso your implemented code is not checking the null value for `displayDate`

**Comment by jorgediaz-lr** [comment]
Hi @ealonso @ruben-pulido 

The new API that you added in https://github.com/liferay-echo/liferay-portal/pull/13883 cannot be used from `com.liferay.headless.delivery.internal.resource.v1_0.StructuredContentResourceImpl` because in that class we are using the JournalArticleService, and you changed the JournalArticleLocalService

It would be also necessary to add some new updateArticle methods with the Date parameter as I think the same bug can be reproduced here: https://github.com/liferay-echo/liferay-portal/blob/1db8604f9c14d5466ac6bafb6514c6e21909a9ee/modules/apps/headless/headless-delivery/headless-delivery-impl/src/main/java/com/liferay/headless/delivery/internal/resource/v1_0/StructuredContentResourceImpl.java#L521-L548

Perhaps we should create a new LPS to handle all the changes of the JournalArticle services API and once the API can be used with Date objects, fix the bug.

**Comment by jorgediaz-lr** [comment]
New PR sent here: https://github.com/liferay-echo/liferay-portal/pull/13913

**Pull request closed without merging**
