### PR TITLE
LPS-193987 Add missing brackets, otherwise the first condition is not applied for both

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
@ealonso

**Comment by jkappler** [comment]
Thanks @victorg1991, works like a charm ❤️

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
