### PR TITLE
LPS-203827 Add translationProgress prop to show how many translated fields there are at the moment

### PR DESCRIPTION
**Pull request by veroglez**
Code that was missing to complete this story https://liferay.atlassian.net/browse/LPS-200663. It was reviewed here https://github.com/liferay-echo/liferay-portal/pull/14738

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/146103

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
