### PR TITLE
LPS-132227 buildLang

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
@Tim-Cao could you review this PR? We have moved the ItemSelector action buttons to a DropDown and I think we need to update poshi tests (same functionality, just moved the buttons)

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/4687

**Pull request closed without merging**
