### PR TITLE
LPS-126651 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LPS-126651 
@david-gutierrez-mesa 
@liulukiwi
@Tim-Cao
Hi all, Could you review my PR please? Thank you

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @calvinctvo , could you refer to my comments from https://github.com/liferay-echo/liferay-portal/pull/3501?

**Comment by calvinctvo** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/3542
View total diff https://github.com/liferay-echo/liferay-portal/compare/c1e40415bd3bed213fe682f26bd05e910dfb9cea...760d6f75023a8001fa0ed4ee5c4781ca7bdcaa66

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
