### PR TITLE
LPS-177285

### PR DESCRIPTION
**Pull request by ealonso**
Split Site Initializers and Site Templates into two sections

Select_Site_Template_-_Liferay

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
Since this modification will affect many testes, I am sending it along with the updates here https://github.com/liferay-echo/liferay-portal/pull/11317

**Comment by alessandromalves** [comment]
Hey @ealonso, we have some conflicts related to the master, could you look at it please?

**Comment by ealonso** [comment]
Hey @alessandromalves,
I've already update it

**Comment by alessandromalves** [comment]
With the changes of [LPS-177285](https://issues.liferay.com/browse/LPS-177285) many tests will be affected and will need an update on some of them. Resent here https://github.com/liferay-echo/liferay-portal/pull/11324

**Pull request closed without merging**
