### PR TITLE
LPS-121881

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @liferay-echo,

Attached is an update for http://issues.liferay.com/browse/LPS-121881.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
Test plan can be found at https://github.com/liferay-echo/liferay-portal/pull/3995#issue-590846871

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @jonmak08, the dropdown menu shouldn't be shown when there is only one item.
Actual

**Comment by jonmak08** [comment]
Hey @Tim-Cao,

I just tested what you posted and I was unable to get the drop down to appear for the user as you said.  Are the steps correct or is the CI test just failing because of another reason?

See my steps to reproduce below:
journal

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by ambrinchaudhary** [comment]
Just started reviewing :)

**Comment by ambrinchaudhary** [comment]
Fixed (🙏 ) in https://github.com/liferay-echo/liferay-portal/pull/4030

**Comment by ambrinchaudhary** [comment]
ci:close

**Pull request closed without merging**
