### PR TITLE
LPS-140626 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-140626

This is only for master.

@david-gutierrez-mesa

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by david-gutierrez-mesa** [comment]
LPS-140318 is stopped. Additionally, this PR has conflicts. Closing.

**Comment by david-gutierrez-mesa** [comment]
ci:close

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
