### PR TITLE
LPS-164268 buildLang

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ozysouza** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Whether this last attempt doesn't work I will manually send it.

**Comment by ozysouza** [comment]
we had some tests to update that I didn't realize at first seen. See https://github.com/liferay-echo/liferay-portal/pull/9801

**Pull request closed without merging**
