### PR TITLE
LPS-115951 - The Delete action is missing before publish

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @jkappler @sandrodw3

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:stop

**Comment by ruben-pulido** [comment]
ci:close

**Comment by ruben-pulido** [comment]
@Tim-Cao will resend with updated Poshi tests. Thanks @Tim-Cao!

**Comment by Tim-Cao** [comment]
Thanks @ruben-pulido See https://github.com/liferay-echo/liferay-portal/pull/1229

**Pull request closed without merging**
