### PR TITLE
LPS-195881 | Test Automation | Master

### PR DESCRIPTION
**Pull request by rafaellajordao**
# LPS-182024 - Product QA | Test Automation Creation

Hi! :)
This pr is corresponding to this ticket: [LPS-182024](https://liferay.atlassian.net/browse/LPS-182024) → [LPS-195881](https://liferay.atlassian.net/browse/LPS-195881)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
Hi @rafaellajordao, please move all cases into correct files according to https://liferay.slack.com/archives/GT42EHW03/p1699257079678569
Additionally, content page won't be locked if quit the page editor.
We have to open a new tab to impersonate user to unlock locked content pages.

**Comment by rafaellajordao** [comment]
Hey @Tim-Cao about this:
> Additionally, content page won't be locked if quit the page editor.
> We have to open a new tab to impersonate user to unlock locked content pages.

Could this be a bug? After testing, if I exit the page editor without clicking the back button, just using the Product Menu, the page remains Locked.
This point about Impersonate User is also not included in the test steps. [LPS-192942](https://liferay.atlassian.net/browse/LPS-192942)

[Untitled_ Nov 8 2023 10_04 AM.webm](https://github.com/liferay-echo/liferay-portal/assets/49991803/f5d42159-8ac3-4eda-a8b2-e4d310df73e9)

**Comment by Tim-Cao** [comment]
I think so. Would you mind asking in our channel t-dxp-echo-in? @rafaellajordao
There are steps called `Navigate to Locked Pages admin in a new tab` It is also editing concurrently.

**Comment by Tim-Cao** [comment]
@rafaellajordao See changes https://github.com/liferay-echo/liferay-portal/pull/14282

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
