### PR TITLE
LPS-204982 Create friendly url separator company configuration

### PR DESCRIPTION
**Pull request by Mikellorza**
Story: https://liferay.atlassian.net/browse/LPS-203352
subtask: https://liferay.atlassian.net/browse/LPS-204982

Description
------------
Create a friendly url separator configuration in order to configure some friendly url separators. This pr contains only the code to show this configuration and save it without validations and without integrate this configurations with the portal url resolvers.

### CODE REVIEW

**Comment by Mikellorza** [comment]
Hi @lfbesada ,

I have applied the changes that we talk.

Thanks!

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
@lfbesada everything is done!  It looks very nice!

thanks for effort mate

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:report:2487404273

**Comment by Tim-Cao** [comment]
ci:forward:force

**Pull request closed without merging**
