### PR TITLE
LPS-147525 Change the modal to have a width of 600px.

### PR DESCRIPTION
**Pull request by BarbaraCabrera**

### CODE REVIEW

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1317401_2284

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
LGTM! 🥳

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
