### PR TITLE
LPS-175402 Replace icons in product-navigation-site-administration

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://issues.liferay.com/browse/LPS-175402)

## Test Steps

1. Go to Control Panel -> System Settings 
2. In Content & Data section -> Navigation 
3. In left menu -> Applications Menu -> Disable Applications Menu
4. Go to Product menu -> see at the bottom of Control Menu, the Product Menu options
5. Assert the sites icon and collapse/expand icon
Screenshot 2023-02-15 at 11 51 15

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
