### PR TITLE
LPS-141756: Poshi Automation for Bug LPS-137055.

### PR DESCRIPTION
**Pull request by BarbaraCabrera**

### CODE REVIEW

**Comment by Tim-Cao** [comment]
Hi @BarbaraCabrera, your branch is deleted. Could you push it to your origin again? Thanks

**Comment by BarbaraCabrera** [comment]
Sorry @Tim-Cao, it's done now.

**Comment by Tim-Cao** [comment]
Hi @BarbaraCabrera, I made some changes here https://github.com/liferay-echo/liferay-portal/pull/7028 in case you don't have time to do more changes. There is only one thing I would like to mention. Generally, no need to append colon to ticket number in commit message. Good job!
.

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
