### PR TITLE
LPD-29128 - Add External Reference Code to Layout entity

### PR DESCRIPTION
**Pull request by ruben-pulido**
https://liferay.atlassian.net/browse/LPD-29128 - Add External Reference Code to Layout entity

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:reevaluate:1287401_9671

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:report:26404345

**Comment by ruben-pulido** [comment]
The only unique failure reported corresponds to:
`commerce/commerce-product-content-web/productDetails.spec.ts,https://testray.liferay.com/#/project/34754/routines/34756/build/26404345/case-result/26415498/history,Unique,COMMERCE-12167 User can see SKU updated on the product details page when values are selected from multiple options: productDetails.spec.ts:131:1 COMMERCE-12167 User can see SKU updated on the product details page when values are selected from multiple options`

which completes successfully locally:
image

**Comment by ruben-pulido** [comment]
[testray-results-26404345.csv](https://github.com/user-attachments/files/15986206/testray-results-26404345.csv)

**Comment by ruben-pulido** [comment]
ci:forward:force

**Pull request closed without merging**
