### PR TITLE
[TS] LPS-174480 | Content page live version disappears after publishing a translation from the translation feature

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-174480
Thank you!

-------

**Steps to reproduce:**
1. Create a content page
2. Put an HTML fragment on it, edit it and put 'EN' in it somewhere
3. Publish, then go to its context menu -> Translate
4. Put 'AR' in the HTML fragment on the right side, publish
5. Notice that the layout is in draft state
6. Try to open the page by its URL in incognito mode

**Current behavior:** Resource not found error and a 404 error in the browser console
**Expected behavior:** Page should be opened

Based on my tests and understanding, the live versions of the layouts are created at the same time as the draft versions. To avoid displaying empty pages, we do not show live layouts without a publised=live typesettings in their draft counterpart. The translation feature sets this published to false. This behavior results in the disappearance of the live layout, even though only the draft layout was changed. My solution simply removes the typesettings relevant part and only changes the draft layout into draft status.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
@bakayattila the same for this one, it should be reviewed by lima team, @liferay-lima

**Comment by jkappler** [comment]
@bakayattila, please see @ealonso comments, send to the correct team

**Pull request closed without merging**
