### PR TITLE
LPS-201067 Add locale to the layout name

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-201067)

## Steps
 
- Navigate to Site Builder > Pages
- Create a Content Page named “Test1”
- Publish the page.
- From the miller columns, open the page in edit mode bu cliking on the page name
- In the left column go to Page Design Options.
- Click on configure button to see more design options.
- Hover over the back button.
- Verify the tooltip is “Go to Test1”
- Click on the back button.
- Notice it redirects to the page in edit mode

https://github.com/liferay-echo/liferay-portal/assets/91208451/f6a2544a-f8ca-4eff-a738-cc6c28e6d974

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
@DiegoHu97 it was fixed as part of https://github.com/brianchandotcom/liferay-portal/pull/143666

**Pull request closed without merging**
