### PR TITLE
LPS-179425, LPS-179427, LPS-179428, LPS-179430, LPS-179431, LPS-179432, LPS-180033 Add test to assert error message when post asset library structured content folder with duplicated erc

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-179425
https://liferay.atlassian.net/browse/LPS-179427
https://liferay.atlassian.net/browse/LPS-179428
https://liferay.atlassian.net/browse/LPS-179430
https://liferay.atlassian.net/browse/LPS-179431
https://liferay.atlassian.net/browse/LPS-179432
https://liferay.atlassian.net/browse/LPS-180033

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
@Tim-Cao Great job! 👏 
I only added a minor SF, see: https://github.com/liferay-echo/liferay-portal/pull/12581 
Regards

**Pull request closed without merging**
