### PR TITLE
LPS-121883 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-121883

This is only for master.

@ealonso
@jonmak08

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Hi @julien and @ealonso, there is a regression issue caused by your changes.
The tooltip of plus icon is wrong. It should always **New** but it actually is **Public Page** or **Manual Collection**.
ToolTip

**Comment by jonmak08** [comment]
Hey @Tim-Cao and @ealonso,

I am testing a fix with the team at https://github.com/ambrinchaudhary/liferay-portal/pull/395 to see if we need to make any additional changes to resolve this issue or not.  I will keep you updated.

If you would like, we can close out this pull request and I can send a new one containing all the necessary changes together  if that is easier.  Otherwise we can keep this pull request open and I will send my changes to the taglib up first to resolve this issue then we can send these changes in afterwards.

Just let me know what your preference is.  Thanks!

**Comment by jonmak08** [comment]
On a side note for QA, I noticed this issue in a few other places in portal components, but it looks like those QA test did not change the issues.  I am not sure if @Tim-Cao, wants to inform QA or have them take a look at their tests in other instances where this issue exists.

**Comment by ealonso** [comment]
Closing this one, thanks you very much @jonmak08

**Pull request closed without merging**
