### PR TITLE
LPS-166547 Adds monospaced only when is necessary

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
cc: @victorg1991 @Tim-Cao @ozysouza

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by lfbesada** [comment]
Hi @Tim-Cao 
It works properly for me in this pull request. 

https://user-images.githubusercontent.com/84471361/199782747-b8631678-71f5-43ed-851e-5847f41bbe31.mov

**Comment by Tim-Cao** [comment]
Sorry @lfbesada and @ealonso, it's my mistake, I've updated our case then fix the rebase conflict here.
https://github.com/liferay-echo/liferay-portal/pull/10174

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
