### PR TITLE
LPS-133629-1

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-133629 select folder modal should not show product menu
https://issues.liferay.com/browse/LPS-133924 junit backend tests

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Hey @lfbesada,
Could you please take a look to the sf errors and resend?
Regards,
Eudaldo

**Comment by lfbesada** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/4900

**Pull request closed without merging**
