### PR TITLE
LPS-201926 Create some tests using @FeatureFlags annotation instead of branching logic using FeatureFlagManagerUtill.isEnabled

### PR DESCRIPTION
**Pull request by Mikellorza**
subtask: https://liferay.atlassian.net/browse/LPS-201926

Coming from this [PR](https://github.com/liferay-echo/liferay-portal/pull/14373). This PR have the same except the code  of the change of this class test/AssetPublisherHelperTest.java that I deleted because I am waiting for the fix from Drew about use the @FeatureFlag annotation with an osgi component.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
