### PR TITLE
LPS-192105

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ealonso, would you mind checking this failed integration tests?
[com.liferay.layout.page.template.service.test.LayoutPageTemplateEntryServiceTest](https://testray.liferay.com/home/-/testray/case_results/2409489026)

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by alessandromalves** [comment]
ci:test:relevant

**Comment by alessandromalves** [comment]
Hey @ealonso, there is a possible regression here:

[PortalLogAssertorTest-modules-integration-mysql57-jdk8/3/9](https://testray.liferay.com/home/-/testray/case_results/2412969984)

```
[junit] Testcase: testScanXMLLog(com.liferay.portal.log.assertor.PortalLogAssertorTest):	FAILED
    [junit] 
    [junit] Portal log assert failure, see above log for more information: 
    [junit] Unable to register portal instance {"mvccVersion": 1, "companyId": 20096, "userId": 0, "userName": "", "createDate": "Fri Aug 25 16:47:14 GMT 2023", "modifiedDate": "Fri Aug 25 16:47:14 GMT 2023", "webId": "liferay.com", "mx": "liferay.com", "homeURL": "", "logoId": 0, "maxUsers": 0, "active": true, "name": "Liferay", "legalName": "", "legalId": "", "legalType": "", "sicCode": "", "tickerSymbol": "", "industry": "", "type": "", "size": "", "indexNameCurrent": "", "indexNameNext": ""}
    [junit] java.lang.UnsupportedOperationException: This class is deprecate and replaced by com.liferay.asset.link.service.impl.AssetLinkLocalServiceImpl
    [junit] 	at com.liferay.portlet.asset.service.impl.AssetLinkLocalServiceImpl.updateLinks(AssetLinkLocalServiceImpl.java:309)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:498)
    [junit] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41)
    [junit] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60)
    [junit] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48)
    [junit] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40)
    [junit] 	at com.sun.proxy.$Proxy96.updateLinks(Unknown Source)
    [junit] 	at com.liferay.portlet.documentlibrary.service.impl.DLAppHelperLocalServiceImpl.updateAsset(DLAppHelperLocalServiceImpl.java:577)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:498)
    [junit] 	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:57)
```

**Pull request closed without merging**
