### PR TITLE
LPS-147705

### PR DESCRIPTION
**Pull request by ozysouza**
This issue is only for master.

https://issues.liferay.com/browse/LPS-147705

cc @victorg1991

### CODE REVIEW

**Comment by ozysouza** [comment]
ci:test:sf

**Comment by ozysouza** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ozysouza, there are some changes needed. cc @victorg1991

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See changes https://github.com/liferay-echo/liferay-portal/compare/27de41ccfdeb81fbe2c476069120828781e76631...6a069cee4159ce52442cac0586f198a3c67190b1
@ozysouza

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
