### PR TITLE
LPS-133629-2 Select folder when adding web content from widgets

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-133629 
- Select folder modal should not show product menu.
- Change the default value of the selectFolder parameter to be able to select the folder when adding web content from anywhere except web content management.

https://issues.liferay.com/browse/LPS-133924 junit backend tests

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/4930

**Pull request closed without merging**
