### PR TITLE
LPS-157075 SF - Extract common code to assert the faviconURL

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
cc: @victorg1991

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, there is a regression issue.
The following error is thrown when remove a virtual instance.
```
[beanshell] 2022-06-29 01:54:05.070 ERROR [http-nio-8080-exec-6][GroupImpl:542] null
[beanshell] com.liferay.portal.kernel.exception.NoSuchLayoutSetException: No LayoutSet exists with the key {groupId=45383, privateLayout=true}
[beanshell] 	at com.liferay.portal.service.persistence.impl.LayoutSetPersistenceImpl.findByG_P(LayoutSetPersistenceImpl.java:1210) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.service.impl.LayoutSetLocalServiceImpl.getLayoutSet(LayoutSetLocalServiceImpl.java:190) ~[portal-impl.jar:?]
[beanshell] 	at sun.reflect.GeneratedMethodAccessor226.invoke(Unknown Source) ~[?:?]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
[beanshell] 	at com.liferay.portal.service.impl.LayoutSetLocalServiceStagingAdvice$LayoutSetLocalServiceStagingInvocationHandler.invoke(LayoutSetLocalServiceStagingAdvice.java:120) ~[portal-impl.jar:?]
[beanshell] 	at com.sun.proxy.$Proxy122.getLayoutSet(Unknown Source) ~[?:?]
[beanshell] 	at sun.reflect.GeneratedMethodAccessor226.invoke(Unknown Source) ~[?:?]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
[beanshell] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
[beanshell] 	at com.sun.proxy.$Proxy122.getLayoutSet(Unknown Source) ~[?:?]
[beanshell] 	at com.liferay.portal.kernel.service.LayoutSetLocalServiceUtil.getLayoutSet(LayoutSetLocalServiceUtil.java:272) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.model.impl.GroupImpl.getPrivateLayoutSet(GroupImpl.java:538) [portal-impl.jar:?]
[beanshell] 	at com.liferay.layout.internal.model.listener.GroupModelListener.onBeforeRemove(GroupModelListener.java:36) [bundleFile:?]
[beanshell] 	at com.liferay.layout.internal.model.listener.GroupModelListener.onBeforeRemove(GroupModelListener.java:31) [bundleFile:?]
[beanshell] 	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.remove(BasePersistenceImpl.java:668) [portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.service.impl.GroupLocalServiceImpl.deleteGroup(GroupLocalServiceImpl.java:1112) [portal-impl.jar:?]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
[beanshell] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
[beanshell] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
[beanshell] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
``

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
