### PR TITLE
LPS-137811 Skip unwanted targetCollections

### PR DESCRIPTION
**Pull request by p2kmgcl**
Only last three commits, rest is rebased onto this https://github.com/brianchandotcom/liferay-portal/pull/106044

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:reevaluate:1297401_471

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
