### PR TITLE
LPS-122009 - properly replace structure ID when referring to fields in the orderBy fields

### PR DESCRIPTION
**Pull request by adolfopa**
Original PR description follows:

https://issues.liferay.com/browse/LPS-122009

From @wanderlast 

> This fix is theoretically pretty straight forward. When we reference a specific field in a DDM Form, we use the format the roughly looks like: ddm__keyword__38809__Decimal28wq. However, this is not actually ever changed when read from properties so the link is broken if the structure ID is ever changed.
> 
> This name is created in DDMIndexer's encodeName() method which lays out what the format entails. Essentially it will always start with "ddm__", fields are indexed as keywords so it will continue with "keyword", the structureID is appended, and then finally the name of the field.
> 
> The fix therefore simply reconstructs the name using the same pattern, substituting the new structureID in the place of the old one. I used substrings since the naming scheme appears to me to be consistent, but there is the possibility that this could break if we ever change the "ddm__keyword__" part of the naming scheme. However, since we use that explicitly in other areas (e.g. liferay-type-mappings.json, some of our test cases), I felt this was an acceptable compromise.
> 
> Please let me know if you have any questions about this. Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Resent here: https://github.com/liferay-echo/liferay-portal/pull/2863

**Pull request closed without merging**
