### PR TITLE
LPS-125157 Escape to prevent possible XSS in the add menu items

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
For the failure in apps:layout:layout-seo-web:compileTestJava, this is reported in LPS-125372. So I'll forward this pull to BChan dirrectly.

**Comment by liulukiwi** [comment]
resend:
https://github.com/brianchandotcom/liferay-portal/pull/97306

**Pull request closed without merging**
