### PR TITLE
LPS-176138 -Collections portlet is down

### PR DESCRIPTION
**Pull request by Mikellorza**
Fix : https://issues.liferay.com/browse/LPS-176138

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Comment by DiegoHu97** [comment]
Just started reviewing :)

**Pull request closed without merging**
