### PR TITLE
LPD-19864 Take ctCollectionId into account for v5_1_1/LayoutPageTemplateStructureUpgradeProcess 2

### PR DESCRIPTION
**Pull request by balazssk**
[LPD-19864](https://liferay.atlassian.net/browse/LPD-19864)
Original: https://github.com/liferay-echo/liferay-portal/pull/15332

Updated based on https://github.com/brianchandotcom/liferay-portal/pull/148061#issuecomment-1991072594 
referring https://github.com/liferay/liferay-portal/commit/88c5b68169cb1eff551c56ef128c450a0cafb3c2

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:report:2549257719

**Comment by lfbesada** [comment]
ci:report:2549265744

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
