### PR TITLE
LPS-171587 baseline

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, Would you mind confirming is this change expected? The display style of web contents on Select Related Assets modal was table but is list.
image

**Comment by ealonso** [comment]
Hey @Tim-Cao,

It is expected, I'm making consistent all views for selecting web content.

Regards,
Eudaldo.

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/10688

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
