### PR TITLE
LPS-152438 Remove LayoutSet 7.2.x deprecated methods

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-152438

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1257401_3717

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1357401_2072

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1267401_4035

**Comment by ozysouza** [comment]
The failures are not related to the PR. I'll try to forward once more.

**Comment by lfbesada** [comment]
ci:forward

**Comment by ozysouza** [comment]
I will forward this PR manually after this last attemp.

**Comment by ozysouza** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/120636

**Pull request closed without merging**
