### PR TITLE
LPS-183324 Removes ContentDashboardWebKeys and replace constants with class names

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
[Link to ticket](https://issues.liferay.com/browse/LPS-183324)

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by BarbaraCabrera** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:forward

**Pull request closed without merging**
