### PR TITLE
LPS-138905 Remove unused

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
https://media2.giphy.com/media/AAsj7jdrHjtp6/giphy.gif?cid=ecf05e473uop92atwpfixlclvbnlnkwtowykqnh9ybi3dmgx&rid=giphy.gif&ct=g

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The failure case is unrelated to this PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/106826

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
