### PR TITLE
LPS-112037 Adapt DisabledArea to work inside a given GlobalContext

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
cc @ealonso

**Comment by p2kmgcl** [comment]
:candle:

**Comment by ealonso** [comment]
👏

**Comment by sandrodw3** [comment]
ci:close

**Comment by sandrodw3** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/1390

**Pull request closed without merging**
