### PR TITLE
LPS-171484 | The categories in keywords meta tag are not localized

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-171484
Thank you!

------

The root cause of the issue is twofold. First, the assetHelperImple does not have an implementation where a localized version of the keywords can be requested. Second, the DPOP had a localized getKeywords method but the implementation never tried to get an actual localized value. First I implemented a localized version of the getKeywords in the AssetHelper and after that, I used it in the three DPOPs where I found an implemented getKeywords method. Now, these three DPOPs use the asset helper and all of them use the same logic to get the keywords.

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/10702

**Pull request closed without merging**
