### PR TITLE
LPS-131934 buildLang

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@ealonso, @robertoDiaz

**Comment by robertoDiaz** [comment]
@jkappler 

We use the other approach in the help message to avoid loose all the translations of the first part of the message.

It also could help us to backport this changes.

Anyway, 👍

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
