### PR TITLE
LPS-206127

### PR DESCRIPTION
**Pull request by JavierMoral**
Motivation
=======
Fix https://liferay.atlassian.net/browse/LPS-206127
When removing a fragment that has an embedded widget from a master page, orphaned portletPreferences are left in the database.

Proposed Solution
========
First I considered that the cause of the problem was the creation of these portletPreferences that are orphaned when removing the fragment but they are necessary when rendering the layouts.
After discarding that, I focused on deleting these preferences when removing the fragment from the master page.

Steps to Verify
========
1. Create a fragment MyFragment with the following HTML code. It has an embedded SearchBar widget

```
<div class="fragment_1">
	<lfr-widget-search-bar id="MySB"></lfr-widget-search-bar>
</div>
```
1. Create a Master Page: MyMasterPage
1. Add MyFragment
1. Create a page from MyMasterPage: MyPage
1. Click Publish
1. Find de plid. For instance, open the JS Console and execute themeDisplay.getPlid()

**Checkpoint:** 
`select * from portletpreferences p where plid = XX and p.portletid like '%com_liferay_portal_search_web_search_bar_portlet_SearchBarPortlet%' `
returns 1 row

1. Go to MyMasterPage
1. Remove MyFragment
1. Add MyFragment again
1. Publish Master
1. Go to MyPage
1. Check your database again:
` select * from portletpreferences p where plid = XX and p.portletid like '%com_liferay_portal_search_web_search_bar_portlet_SearchBarPortlet%'`

:+1: **Expected**
Only 1 row is returned. The orphan portletpreference record has been removed

:-1:  **Current**
2 rows are returned. The orphan portletpreference hasn’t been removed

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
@JavierMoral, baseline is failing kernel

**Comment by JavierMoral** [comment]
@jkappler I added some new commits that I hope fixes the issue. Thanks!

**Comment by jkappler** [comment]
ci:forward

**Comment by JavierMoral** [comment]
"Error response from daemon: mount ... no space left on device" something is wrong with CI...

**Comment by jkappler** [comment]
lets try again @JavierMoral, if not, will manual forward after checking that no failure is related

**Comment by jkappler** [comment]
ci:report:2494188396

**Comment by jkappler** [comment]
@JavierMoral, checking the tests, they don't seem related to the changes, so moving this forward

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
