### PR TITLE
[TS]LPS-196445 Change site configuration for instance configuration

### PR DESCRIPTION
**Pull request by henriquelimadotcom**
<h1>Motivation</h1>
When changing languages ​​in "site settings", a component of the instance was affected. However, this component, which is the "Terms of Use", must be changed in "instance settings". According to the component description itself

Ticket: https://liferay.atlassian.net/browse/LPS-196445

<h1>Proposed Solution</h1>
I made a change so that it takes data from the instance configuration instead of the site settings

<h1>Steps to Verify</h1>
1-Start Liferay

2-On Terms of Use or Password Reminder screen, check which Languages are available
→Default: We can select 12 or 13 languages (depending on the version used)

3-Go to Liferay DXP site’s [Configuration > Site Settings > Localization > Languages]

4-Select “Define a custom default language and additional available languages for this site.”

5-Move all languages except "English(United States)" from Current to Available and Save

6-Go to Control Panel > Users > Users and Organizations > "+"

7-Add New User

8-Sign-in by new user and check “Terms of Use” screen

@dacousalr

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
Hi @henriquelimadotcom, can you please follow the  [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) please? And explain why the change was made?

Also, please move the ticket to the corresponding status.

Thanks in advance!

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
thanks @henriquelimadotcom!

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
