### PR TITLE
LPS-118212 Undo is already implemented for CHANGE_MASTER_LAYOUT

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @veroglez, The fragment name is replaced by {0} in Undo History dropdown list, could you have a look at this issue?
See the following screenshot.
Actual

**Comment by veroglez** [comment]
@Tim-Cao I have fixed this here: https://github.com/liferay-echo/liferay-portal/pull/1744

**Comment by veroglez** [comment]
ci:close

**Pull request closed without merging**
