### PR TITLE
LPS-164648 If we are on a site template we should use the tokens of private layout set, since site templates only have private layout set

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forwardEudaldo

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
@ozysouza Could you please manually forward it? Everything seems to be fine, but the pr is not forwarded. 😞

**Comment by ozysouza** [comment]
> @ozysouza Could you please manually forward it? Everything seems to be fine, but the pr is not forwarded. disappointed

Sure! The PR is good to go.

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/124080

**Pull request closed without merging**
