### PR TITLE
LPS-123155 Add aria-* and data-* attributes to make markup more accessible

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
@Tim-Cao can you check if this is enough for poshi tests? :smile:

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/2839

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
