### PR TITLE
LPS-121142 Restore current permission checker after indexing a content page

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by inacionery** [comment]
Hey @ealonso 

Did you analyze the jenkins log? There are several errors related to the layout. Wouldn't they be related to that PR?

Thanks!

**Comment by ealonso** [comment]
Hey @pavel-savinov,

Could you please take a look to @inacionery comment? https://github.com/liferay-echo/liferay-portal/pull/2442#issuecomment-697304904

Regards,
Eudaldo.

**Comment by pavel-savinov** [comment]
Hi @inacionery, I see only one unique failure:
`   [exec] * What went wrong:
     [exec] Execution failed for task ':apps:portal:portal-dao-test:startTestableTomcat'.
     [exec] > Timeout while waiting for the application server`
And I know that there are many people experiencing startTestableTomcat problems on their PRs as well.
Other (common) failures are present on the other PRs. They are probably ours, but not related to this particular pull.

**Comment by inacionery** [comment]
Hey @pavel-savinov,

I was talking these failures:
`com.liferay.layout.type.controller.test.LayoutTypeURLTest > testGetRegularURLLayoutTypeURL FAILED
com.liferay.layout.uad.anonymizer.test.LayoutRevisionUADAnonymizerTest > testDeleteAll FAILED
com.liferay.layout.uad.anonymizer.test.LayoutRevisionUADAnonymizerTest > testDelete FAILED
com.liferay.layout.uad.anonymizer.test.LayoutRevisionUADAnonymizerTest > testAutoAnonymizeUserOnly FAILED
com.liferay.layout.uad.anonymizer.test.LayoutRevisionUADAnonymizerTest > testAutoAnonymizeStatusByUserOnly FAILED
com.liferay.layout.uad.anonymizer.test.LayoutRevisionUADAnonymizerTest > testAutoAnonymizeAll FAILED
com.liferay.layout.uad.anonymizer.test.LayoutRevisionUADAnonymizerTest > testAutoAnonymize FAILED
com.liferay.layout.uad.exporter.test.LayoutRevisionUADExporterTest > testExportByStatusByUserId FAILED
com.liferay.layout.uad.exporter.test.LayoutRevisionUADExporterTest > testExportAll FAILED
com.liferay.layout.uad.exporter.test.LayoutRevisionUADExporterTest > testExport FAILED`
that are in this log https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=3,label_exp=!master/457013//consoleText

I thought if they were the cause of the failure of this PR, but you are saying that they are common...

This fix is important, because it is fixing an error that is blocking our PRs.

Thanks!

**Comment by pavel-savinov** [comment]
@inacionery Got you. You're 100% right, we check & fix those tests, but they have nothing to do with this particular PR.
Furthermore, I've just run those tests with the PR locally, and they all pass.

**Comment by pavel-savinov** [comment]
@inacionery Anyway, I'll double-check those which are common and add a fix to this PR.

**Pull request closed without merging**
