### PR TITLE
LPS-114729 Parameterize the generic type

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by JorgeFerrer** [comment]
Resent after rebasing as https://github.com/liferay-echo/liferay-portal/pull/1094

**Pull request closed without merging**
