### PR TITLE
LPS-147384 Include fragmentCollection in getMostRecentLayout

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1277401_1795

**Comment by ealonso** [comment]
ci:reevaluate:1277401_1795

**Comment by ealonso** [comment]
ci:reevaluate:1277401_1795

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
