### PR TITLE
[TS] LPS-162351 |  Page configuration does not save after the default language of the site was changed

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?

https://issues.liferay.com/browse/LPS-162351

Best,
Attila

----------------------------------------------------------------------

**Reproduction steps:**

1. Go to Control Panel > Sites and create a new site and name it test
2. Within the site create a new content page called home
3. Go to Site settings > Localization and change the default language
4. Go back to the above created page and enter configuration 
5. With or Without changing any of the configuration try to Save

**Actual result:** Configuration page does not save with the following error.
**Expected behaviour:** Configuration save without error

After LPS-141974 If the user changes the default langue of a Site or instance, the content pages will not be editable in the page settings.
The reason for this is that when the _layoutSerivce.updateLayout is called in the [EditLayoutMVCActionCommand.java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/portlet/action/EditLayoutMVCActionCommand.java#L185-L193) for the draft version. The draft version will use the getFriendlyURLMap for the update call and the [getFrendlyURLMap](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/model/impl/LayoutImpl.java#L606-L634) will return the previous default firendlyURL if there is no translation for the language. I removed this part of the code because it contradicts LPS-141974 and the unique index on the friendlyURL.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ozysouza** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/123051

**Pull request closed without merging**
