### PR TITLE
LPS-137207 Remove ignore for testOrderByDDMNumberFieldRepeatable

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
https://issues.liferay.com/browse/LPS-137207

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
liferay/ci:test:relevant

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:forward

**Comment by david-gutierrez-mesa** [comment]
ci:forward

**Pull request closed without merging**
