### PR TITLE
LPS-190093 Adds support to editing info items on display pages

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, the form fragments cannot be shown on content page at view mode
**Step to reproduce**

1. Add a company scope object with a Text field
2. Add a Form Container to a content page
3. Map the Form Container to object
4. Publish the content page
5. Navigate to the content page at view mode

**Expected Results:**
The Text Input and Submit Button fragments are shown.

**Actual Results:**
They are not shown.

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
