### PR TITLE
Journal Article - Basic Info Summary Editor Configuration is not taken into account

### PR DESCRIPTION
**Pull request by jbalsas**
As part of the epic [Reduce variability in WYSIWYG Writing Experience](https://issues.liferay.com/browse/LPS-98577), we worked to [Replace AlloyEditor in the Summary field in Web Content](https://issues.liferay.com/browse/LPS-110011)

Doing so introduced a regression that caused the editor not to use its custom configuration but the default `toolbar_simple`configuration.

**Steps to Reproduce**
- Navigate to`Content & Data > Web Content > Add Basic Web Content`
- Check the Summary localized input on the sidebar panel

**Current Result:** The editor shows a Source button but no Link button

**Expected Result:** The editor should show the following buttons: `[bold, underline, italic, numbered list, bulleted list, link]`

**What was going on?**
The configuration wasn't specifically targetting AlloyEditor, but it was only generating valid configuation for that editor. As we are now using CKEditor, those settings were not being properly honoured.

Additionally, only `<a>` tags were allowed but no attribute, so in practice this editor did not support adding links since their href attributes would've been wiped out on save. This PR addresses this potential bug by adding `a[href]` to the allowedContent rule configuration.

Deploying this PR should make the Summary editor look like the following:

Screen Shot 2020-07-28 at 15 08 47

**Additional Considerations:**

One thing to take into consideration is that `Unlink` is a separate button. Adding it will make the toolbar break to 2 rows (Space being very limited here... :D). Not having it makes it so that the only way to remove links is to actually delete the text or use the contextual (right-click) menu. 

Screen Shot 2020-07-28 at 15 24 24

Screen Shot 2020-07-28 at 15 24 36

My suggestion would be to leave only the `Link` button and work to add the [linkballoon](https://ckeditor.com/docs/ckeditor4/latest/examples/balloontoolbar.html) behaviour so removing links is more obvious.

/cc @JorgeFerrer. I'll add this in an email to Tarik as well, since he's still NOT in GitHub 😂

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
LGTM
Thanks Chema!

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:stop

**Comment by pavel-savinov** [comment]
ci:close

**Comment by jbalsas** [comment]
Hey @pavel-savinov, just realized that `toJSONArray("['Link', Unlink]"));` should just be `toJSONArray("['Link']"));`

I added that for the screenshots and somehow committed by mistake 😭 . I'll resend asap

**Comment by jbalsas** [comment]
I just rebased and push-forced the branch... let me see if reopening will pick it up

**Comment by jbalsas** [comment]
ci:reopen

**Comment by jbalsas** [comment]
😢 

Screen Shot 2020-07-29 at 08 09 15

**Pull request closed without merging**
