### PR TITLE
LPS-137272 Update test

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@ealonso

**Comment by jkappler** [comment]
@liulukiwi, would you please help me out? Are the errors because of ordering?

Thanks!

**Comment by liulukiwi** [comment]
ci:test:bundle

**Comment by liulukiwi** [comment]
Hi @jkappler, the assets in display page are displayed by modified date but not displayed date, this is changed by this pr, is this expected?

**Comment by jkappler** [comment]
Thanks @liulukiwi, will fix this

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Pull request closed without merging**
