### PR TITLE
LRAC-14634 It is not possible to edit the page if the variant is published in the AB test

### PR DESCRIPTION
**Pull request by Mikellorza**
Add changes requested here: https://github.com/brianchandotcom/liferay-portal/pull/141626#issuecomment-1745001103

https://liferay.atlassian.net/browse/LRAC-14634

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Mikellorza** [comment]
Hey @ruben-pulido ,

I made some changes , please take a look when we have time.

Thanks

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
