### PR TITLE
LPS-155625 Give feedback to the user when they cannot save a fragment composition

### PR DESCRIPTION
**Pull request by DiegoHu97**

### CODE REVIEW

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Review by jkappler — CHANGES_REQUESTED** [review]
@DiegoHu97, since we don't use getMessage() when showing the error, we could leave this commit out right? https://github.com/liferay-echo/liferay-portal/pull/9148/commits/cfc67e030a6abc1a2d72e692064cfb01ac52daf0

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
awesome @DiegoHu97, thanks!

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1337401_2074

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
