### PR TITLE
LPS-102711 Site Settings Portlet

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Rebased!
See https://github.com/liferay-echo/liferay-portal/pull/4478

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
