### PR TITLE
[TS] LPS-190729 Add setLocaleTransformerListener and utilizing the @Refere…

### PR DESCRIPTION
**Pull request by gergelyszalay**
Hi Team,

May I ask if you could review my PR?

Opened the PR to fix: https://liferay.atlassian.net/browse/LPS-190729 
Caused by: https://liferay.atlassian.net/browse/LPS-165626
Solution guidance: https://liferay.atlassian.net/browse/PTR-4133

Root casue: 

https://github.com/liferay/liferay-portal/blob/2f26b1877faf8cf517f5d5c8477fcf3ebb70da29/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/model/impl/JournalArticleImpl.java#L97 getContentByLocale() method gives back all the values, not only the locale. The problem is _localeTransformerListener is null, because the LocaleTransformerListener not getting activated.

Solution: calling the JournalArticleImpl::setLocaleTransformerListener at https://github.com/liferay/liferay-portal/blob/7.4.13-u86/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L5881-L5890
and
inject service dependencies: Reference annotation  [JournalArticleLocalServiceImpl.java#L8067C2-L8068C73](https://github.com/liferay/liferay-portal/blob/7.4.13-u86/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L8067C2-L8068C73)

Tested it locally and it solves the issue.

Thank you in advance!

BR,
Gege

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by gergelyszalay** [comment]
ci:test

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @gergelyszalay 👋 
Thank you very much for the fix, it works great 🎉 
I have resent it to add minor source formatting fixes. Please see: https://github.com/liferay-echo/liferay-portal/pull/13133
Regards

**Pull request closed without merging**
