### PR TITLE
LPS-143668 Adapt tests and add accessibility for the autocomplete input

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
This is mine

**Comment by p2kmgcl** [comment]
This is not mine, is @sandrodw3's

**Comment by veroglez** [comment]
ci:forward

**Pull request closed without merging**
