### PR TITLE
LPS-200199 Do not process the image in every selection: Read the metadata instead. Also: some image types are not processed in ImageTool so it drives to errors.

### PR DESCRIPTION
**Pull request by robertoDiaz**
See: https://liferay.atlassian.net/browse/LPS-200199

**Steps to reproduce:**

1. Add a new content page
2. Add an image fragment to the page
3. Upload an SVG image to the fragment
4. Observe the logs

**Expected result**: No console errors appear.

**Actual result**:

`2023-10-26 17:55:01.330 ERROR [http-nio-8080-exec-5][PortletServlet:109] Unable to process portlet com_liferay_layout_content_page_editor_web_internal_portlet_ContentPageEditorPortlet: java.lang.RuntimeException: java.io.IOException: Unsupported image type
`

**Root cause** is this peace of code in `com.liferay.layout.content.page.editor.web.internal.portlet.action.GetAvailableImageConfigurationsMVCResourceCommand#doServeResource`:

```
() -> {
	Image image = ImageToolUtil.getImage(
		fileEntry.getContentStream());

	return image.getWidth();
}
```
Doing this you are regenerating the image in each file selection (it has poor performance and some image types could fail because are handled by different tools)

**Solution:**
Instead of that width could be read from the extracted metadata (as we do in other parts of the portal as `com.liferay.adaptive.media.image.internal.validator.AMImageValidatorImpl#_isFileVersionStoredMetadataSupported` or `com.liferay.layout.seo.web.internal.util.FileEntryMetadataOpenGraphTagsProvider#getFileEntryMetadataOpenGraphTagKeyValuePairs`)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by robertoDiaz** [comment]
ci:test:sf

**Review by lfbesada — APPROVED** [review]
Hi @robertoDiaz 
Thank you very much for the fix! It works like a charm :star_struck: 
LGTM :tada: 
Regards

**Comment by lfbesada** [comment]
ci:forward

**Comment by rafaellajordao** [comment]
### Hey! After analyzing the flaws in this [comparison](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=2448811647&testrayRunIdA=2449924383&statusB=2) I found some related to this PR:

It is failing because apparently when creating a Master Page Template with a CSS configuration, when we try to add a page with the Master Page created, the CSS values are changed.

> MenuDisplay#DefineItemColorStyles

In these cases, the image resolution is different from the original image expected by the test, is this expected?
> FragmentsWithImageResolutionInDisplayPageTemplate#ViewAutoImageResolutionForImageDirectlySelectedInCard
> FragmentsWithImageResolutionInDisplayPageTemplate#ViewAutoImageResolutionForBackgroundImageDirectlySelectedInContainer
> FragmentsWithImageResolutionInDisplayPageTemplate#ViewAutoImageResolutionForBackgroundImageDirectlySelectedInBannerCenter
> FragmentsWithImageResolution#ViewAutoImageResolutionForMappingBackgroundImageInContainer
> FragmentsWithImageResolution#ViewAutoImageResolutionForMappingBackgroundImageInBannerCenter
> FragmentsWithImageResolution#ViewAutoImageResolutionForBackgroundImageDirectlySelected

cc/ @lfbesada @robertoDiaz

**Comment by robertoDiaz** [comment]
@lfbesada @rafaellajordao 

How could it be reproduced?

**Comment by lfbesada** [comment]
> @lfbesada @rafaellajordao
> 
> How could it be reproduced?

Hi @robertoDiaz @rafaellajordao 
Manually I can't reproduce these failures, following the steps works OK for me.
@rafaellajordao Did you reproduce these failures manually? Could you please provide the image used for it and the detailed steps?
Thanks in advance!

**Comment by lfbesada** [comment]
Hi @rafaellajordao 

I have relaunched the tests because neither @robertoDiaz nor I can reproduce those changes manually.

Please could you help us with this?

It would help us to know if you tested them manually and, if so, the steps and images you used to reproduce them. In case you didn't test them manually it would help us to have the image that POSHI uses for the test.

Thank you very much, 

Regards

**Comment by rafaellajordao** [comment]
Hey! Sorry for the delay!

Regarding the first case I mentioned (MenuDisplay#DefineItemColorStyles), I checked again in the master and the same error is happening, I apologize for the mistake so I believe that this failure is not related to the PR.

In case the other tests failing are actually related to the changes, here are the steps for one of them (FragmentsWithImageResolutionInDisplayPageTemplate#ViewAutoImageResolutionForImageDirectlySelectedInCard):

1. Add a display page template with Web Content Article and Basic Web Content
2. Add a Card fragment to page
3. Click the image editable field of Card
4. Click the Select button of Image field > Documents and Media tab > Select the uploaded file
5. Upload an image with greater than 2000px width > Add
6. Assert the Auto is selected in Resolution field
7. Assert the Width and File Size of original image is shown in Image Source panel
8. Change to the Landscape Phone viewport
9. Assert the Auto is selected in Resolution field
10. Assert the Width is 1000px and File Size become smaller
11. Publish
12. Add a web content based on Basic Web Content
13. Select the display page template as Specific Display Page Template
14. Publish
15. Click the ellipsis button of web content > View Content
16. Assert it redirects to the display page template
17. Click the Simulation button on the control menu
18. Click the Desktop
19. Inspect the image editable field of Card
20. Properties tab > img.w-100
21. Assert the value of currentSrc contains /documents/
22. Click the Mobile
23. Inspect the image editable field of Card
24. Properties tab > img.w-100
25. Assert the value of currentSrc contains /Preview-1000x0/

This is the path to find the image used:
`~/dev/projects/liferay-portal/portal-web/test/functional/com/liferay/portalweb/dependencies/high_resolution_photo.jpg`

high_resolution_photo

@lfbesada @robertoDiaz

**Comment by robertoDiaz** [comment]
I (and @lfbesada) were analyzing this and we weren't able to reproduce this manually.

We've check the poshi report and the failure seems to be this one:
Captura de pantalla 2023-11-06 a las 12 02 22

Based in 
Captura de pantalla 2023-11-06 a las 12 05 29

When we manually do this test we found that:

Captura de pantalla 2023-11-06 a las 11 55 46

Wich is the expected value since https://github.com/liferay/liferay-portal/blob/076b077b7fce84709594e1bd6f6438191520f140/portal-web/test/functional/com/liferay/portalweb/dependencies/high_resolution_photo.jpg has 
Captura de pantalla 2023-11-06 a las 12 07 55

Taking this into account 5464px should be the expected width in all cases since it's the original image width.

Are we missing something??

Please, can test it manually (in current master and appliying this changes) and assert how it behaves in your end? Also share with us a video with the test.

Also, @rafaellajordao, try to prioritize this, since it comes from customers and they are waiting for this fix.

Best regards.

**Comment by jkappler** [comment]
Hi @rafaellajordao, since @liulukiwi cannot also reproduce as @robertoDiaz and @lfbesada, can we move this forward? A customer is expecting the fix.

Thanks in advance!

**Comment by lfbesada** [comment]
The same test is failing in others PR, for example: https://github.com/liferay-echo/liferay-portal/pull/14235#issuecomment-1798837782

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
