### PR TITLE
[TS] LPS-141200

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

could you please review my fix?

**Steps to reproduce**

1) Create a Content page, put an Asset publisher on it
2) Configure the AP, so it will be 'Full content' and the default AP
3) Create a web content, put 'EN-title-translated' in the title and content fields
4) Add a French translation, put 'FR-title-translated' in the title and content fields
5) Set the Content page as the display page then publish
6) Create another web content, put 'EN-title-not-translated' in the title and content fields
7) Add a French translation, don't change the title, put 'FR-title-not-translated' in the content field, publish
8) Set the Content page as the display page then publish
9) Create a Widget page, put an Asset Publisher and a Language selector on it
10) Change the language to French
11) Open the 'EN-title-translated' web content
12) You will see the French translation in both the title and content
13) Open the 'FR-title-not-translated' web content

**Current behavior:** You will see the 'EN-title-not-translated' content

**Expected behavior:** You should see the 'FR-title-not-translated' content

**Root cause:**
In case the title has no translation beside the default locale, then no titleMapAsXML parameter with the default locale translation  is sent to the backend for the translations. 
In the reproduction no titleMapAsXML_fr_FR=EN-title-not-translated is sent to the backend.

**Solution:**
On the backend we can retrive this information from the content. 

Thanks, Roland

https://issues.liferay.com/browse/LPS-141200

### CODE REVIEW

**Comment by jkappler** [comment]
Hi @rolandpakai, @istvangergely, sorry for the long delay in reviewing this. We have been checking the solution, and don't think that forcing the values to be in urlTitleMap would be the best.

We are trying other approaches, but have found some inconsistencies because we have this story: https://issues.liferay.com/browse/LPS-79610 in which we basically show the content based on the language of the URL (which is what's happening when clicking the title of the web content).

And the bug surfaced because of this fix https://issues.liferay.com/browse/LPS-125409. So if we rollback the changes, we would have to find another way to solve this.

As I mentioned, sorry for the delay, we are trying to come with a solution that can work for everyone without breaking or complicating things.

Thanks for the patience

**Comment by istvangergely** [comment]
Hi @jkappler,

Thanks a lot for your update! I understand the issue is complex and finding the right solution takes more time than expected.

We look forward to further news from you.

Best,
István

**Comment by jkappler** [comment]
Hi @istvangergely, @rolandpakai, we are still working on it. About why we are unsure about the proposed fix: we would forcibly add friendlyURLs for each translation, and that could be problematic en the future. So we would have for example:  EN-title-not-translated, EN-title-not-translated-1, EN-title-not-translated-2 and so on for each translated content.

Hope this makes sense. Again, thanks for the patience

**Comment by rolandpakai** [comment]
Hi @jkappler 

i would like to ask, do you have any update on your side?

Thanks, Roland

**Comment by jkappler** [comment]
Hi @rolandpakai, still taking a look at it. We know it's important and are dedicating time and resources to it.

cc:// @ealonso

**Comment by jkappler** [comment]
Please see https://github.com/liferay-echo/liferay-portal/pull/6390. @dacousalr already had fixed this for a client (and is better fix than mine). Still, we have the other case that cannot be solved at the moment, which is when available locales are set and you navigate to the display page of the content. 

Will see if this is a limitation of the product and depending on it will create a new LPS.

**Comment by rolandpakai** [comment]
Thank you @jkappler for your hard work on this issue.

**Pull request closed without merging**
