### PR TITLE
LPS-147083 Migrate Feeds Type To Asset Categories

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
LPS-147083 Migrate Feeds Type To Asset Categories

https://issues.liferay.com/browse/PTR-2846

https://issues.liferay.com/browse/PTR-3570

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by lfbesada — CHANGES_REQUESTED** [review]
Hi @georgel-pop-lr 

Thanks for the PR! ❤️ 

I can't review it as it doesn't work properly. This is because in the UpgradeProcess you are deleting the type_ column that doesn't exists in the table, so when I try to test it I get an error "Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'type_' in 'field list'"

Please could you fix it?

I have not made a complete review for this PR, but I have seen some details that I am commenting on here in case you also want to fix it before the complete review:

1. Integration tests should be added, at least, for the UpgradeProcess.
2. I think that in the UpgradeProcess it would be necessary to classify the articles with those types by the categories that you are creating, don't you think?
3. I think the naming could be improved a bit, for example, queryCategoryId could be queryAssetCategoryId, what do you think about it?
4. Since we are adding the ability to categorize feeds I don't understand why we make journalFeedAssetRendererFactory.isCategorizable() always false.

Could you please ask me for the revision once this branch can be tested?

Thanks! Regards

**Comment by lfbesada** [comment]
Hi @georgel-pop-lr 
Hello
I think I've seen what the problem is. The upgrade process is trying to read a column from the table that was removed in 2014 with this ticket: https://issues.liferay.com/browse/LPS-50764
In my opinion, the upgrade process for this ticket should only create the assets for the existing feeds. The upgrade process you want to do add that creates categories and classifies the feeds with them, in the case is necessary, it must be inserted at another point to attend only the previous versions that had this column.
I haven't found any reference to the need for an upgrade process like that in any of the related tickets and IMHO it's not needed in the master branch in any case.
Please, would it be possible to remove that from the upgrade process of this PR in order to only create the feed assets? 
If you think this upgrade process like that is necessary, please open a PTR to the Upgrades teams to discuss your need and the best way to address it.
Thanks!
Regards

**Comment by georgel-pop-lr** [comment]
> * Integration tests should be added, at least, for the UpgradeProcess.
> * I think that in the UpgradeProcess it would be necessary t

Hi @lfbesada,

The problem is that type_ column exists only if you migrate from 6.2, if you start a new DB it doesn't as it was removed. 

So maybe the best way is to check first if that column exists and follow with the upgrade step, otherwise do nothing.

I will push a new fix as soon as possible.

Regards.

**Comment by lfbesada** [comment]
Hi @georgel-pop-lr 
The column "type_" was removed https://issues.liferay.com/browse/LPS-50764. That ticket also adds the upgrade process com.liferay.journal.internal.upgrade.v0_0_3.JournalArticleTypeUpgradeProces.
I think that any upgrade process executed in steps later than 0.0.3 will not find the type column in the JournalFeed table. I may be wrong and perhaps the type_ column is never removed from previous versions in which case the approach you are suggesting will work. That is a special case, I suggest you ask for help from the Upgrades team to achieve what you want.
This story doesn't require that upgrade process, it only needs an upgrade process to create the JournalFeed assets. So the process to create those vocabularies should be addressed in another ticket and this PR should do only this: to create the JournalFeed assets.
Could you please change this PR upgrade process to remove the extra code?
Thanks in advance
Regards

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr The column "type_" was removed https://issues.liferay.com/browse/LPS-50764. That ticket also adds the upgrade process com.liferay.journal.internal.upgrade.v0_0_3.JournalArticleTypeUpgradeProces. I think that any upgrade process executed in steps later than 0.0.3 will not find the type column in the JournalFeed table. I may be wrong and perhaps the type_ column is never removed from previous versions in which case the approach you are suggesting will work. That is a special case, I suggest you ask for help from the Upgrades team to achieve what you want. This story doesn't require that upgrade process, it only needs an upgrade process to create the JournalFeed assets. So the process to create those vocabularies should be addressed in another ticket and this PR should do only this: to create the JournalFeed assets. Could you please change this PR upgrade process to remove the extra code? Thanks in advance Regards

Hi @lfbesada,

I think this upgrade step should go together with this change, as if you come from 6.2 in JournalFeed table you have a column named type_ that contains the category. This category is possible to not be migrated if it wasn't used in JournalArticle table. To make it simple, LPS-50764 is only migrating the type_ column inside JournalArticle table, but is not touching the one on JournalFeed.

If we don't include it now, then people would start adding this category and this information would be lost after AssetEntry is created, that's why I think it should go togheter. Maybe is a good idea to pass this PR to @liferay-uniform team once passed review here.

Now going back to the open points you added in your first comment:

1. Integration tests should be added, at least, for the UpgradeProcess.

Please give more details on what to test, take in consideration that this is a deprecated feature and is better to not spend more time on it then we already did.

2. I think that in the UpgradeProcess it would be necessary to classify the articles with those types by the categories that you are creating, don't you think?

If I understand this correctly, I think this is related to the explanation I gave before about migrating type_ collumn of JournalFeed. If I'm not right, please give more details on this, in order to answer it properly.

3. I think the naming could be improved a bit, for example, queryCategoryId could be queryAssetCategoryId, what do you think about it?

I changed the naming, please check.

4. Since we are adding the ability to categorize feeds I don't understand why we make journalFeedAssetRendererFactory.isCategorizable() always false.

I changed this as well, please check.

Another thing I found out after migrating, is an error occurs with migrating JournalFeed from 6.2 (with or without my changes), I remember this was working before when I send this pull so maybe is something new that was introduced on master. 

This is the error when saving a migrating feed:
image

Is happening on this line `_ddmStructureLinkLocalService.getUniqueStructureLink`: https://github.com/liferay/liferay-portal/blob/09b60d8504d8adf46af2c627fead109c7cd65f34/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalFeedLocalServiceImpl.java#L353

Thrown here: https://github.com/liferay/liferay-portal/blob/7da680b4391587a99b4b5dcfc0b5143d82e5cd0e/portal-impl/src/com/liferay/portal/spring/transaction/TransactionInterceptor.java#L72

As this happens with master code and is not related to my changes, not sure if I should open a new ticket for this or how should we handle it.

Regards.

**Comment by lfbesada** [comment]
Hi @georgel-pop-lr 

Thank you for updating this PR!

From my point of view, the related ticket is resolved without the need to create those categories and classify the JournalFeed assets with them. 

I also don't see any inconvenience to addressing the migration issue from 6.2 with a later UpgradeProcess as long as this PR does not remove the type_ column from JournalFeed if it exists.

Please, can you explain a little more about the need for this to be executed in the same UP that creates the assets?

As I said before, IMHO it should be addressed in another ticket, just after this one, and should be reviewed by the upgrades Team. 

I look forward to your comments

Regards

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr
> 
> Thank you for updating this PR!
> 
> From my point of view, the related ticket is resolved without the need to create those categories and classify the JournalFeed assets with them.
> 
> I also don't see any inconvenience to addressing the migration issue from 6.2 with a later UpgradeProcess as long as this PR does not remove the type_ column from JournalFeed if it exists.
> 
> Please, can you explain a little more about the need for this to be executed in the same UP that creates the assets?
> 
> As I said before, IMHO it should be addressed in another ticket, just after this one, and should be reviewed by the upgrades Team.
> 
> I look forward to your comments
> 
> Regards

Hi @lfbesada,

My fear is to separate this, and they go in different updates.

As I explained before, if you create the AssetEntry without his category, if they go in separate ones, you might need to delete the column type_ without adding it, being lost forever. That because a Feed it contains only one category or none and if they go in different updates you could delete something that a user already changed (added or removed the category) manually from the UI.

If you refer to the steps of the ticket not including this upgrade in the description, then I could change it.

But I really think they should go together.

Regards.

**Comment by achaparro** [comment]
Hi @georgel-pop-lr @lfbesada,

As you mentioned before, it is fine if you send the pull to @liferay-uniform after this.

I took a quick look at your conversation (really quick) and take into account that the method alterTableDropColumn already checks the existence of the column:
https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/dao/db/BaseDBProcess.java#L283

Thanks.

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr @lfbesada,
> 
> As you mentioned before, it is fine if you send the pull to @liferay-uniform after this.
> 
> I took a quick look at your conversation (really quick) and take into account that the method alterTableDropColumn already checks the existence of the column: https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/dao/db/BaseDBProcess.java#L283
> 
> Thanks.

Hi @achaparro,

Thanks for checking, I know that `alterTableDropColumn` it checks for the column. 

The problem was not when deleting the type_ collumn, but when I was selecting a database that doesn't contain this column (if the user is not coming from 6.2) there the fail was. 

That's why I added this check in the beginning of the upgrade: https://github.com/liferay-echo/liferay-portal/blob/f78bf69ab6c3d7fcf8f9b81c81967abe99a790ee/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/internal/upgrade/v4_4_4/JournalFeedTypeUpgradeProcess.java#L79

Once this pull passes @liferay-echo review, I will send it to your team.

Regards.

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
Hi @georgel-pop-lr @achaparro ,

Thanks for your comments ❤️ 

I'm working on this ticket adding some changes to this PR, both to the development itself and to the upgrade process.
I will add an integration test but it won't assert the migration from 6.2 because the type_ column won't exist.
It would help me a lot to have a 6.2 DB dump to be able to test manually the upgrade from 6.2. 

@georgel-pop-lr Could you please provide any? It would be great if we have in this DB all the cases:
- Feeds without type
- Feeds with a type that matches an article type
- Feeds with a type that doesn't match an article type
- Feeds with the "general" type 

Something I would like to understand, in the last commit a DummyUpgradeStep is being added. @georgel-pop-lr Could you please explain why this is necessary? See: https://github.com/liferay-echo/liferay-portal/pull/11095/commits/f78bf69ab6c3d7fcf8f9b81c81967abe99a790ee#diff-47bc0fd8f1195aaa3aab915e6dd5a7daf4f7ee1ab45c360ae35658d3b689d315R293-R294

Thanks in advance!

Regards

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr @achaparro ,
> 
> Thanks for your comments heart
> 
> I'm working on this ticket adding some changes to this PR, both to the development itself and to the upgrade process. I will add an integration test but it won't assert the migration from 6.2 because the type_ column won't exist. It would help me a lot to have a 6.2 DB dump to be able to test manually the upgrade from 6.2.
> 
> @georgel-pop-lr Could you please provide any? It would be great if we have in this DB all the cases:
> 
> * Feeds without type
> * Feeds with a type that matches an article type
> * Feeds with a type that doesn't match an article type
> * Feeds with the "general" type
> 
> Something I would like to understand, in the last commit a DummyUpgradeStep is being added. @georgel-pop-lr Could you please explain why this is necessary? See: [f78bf69#diff-47bc0fd8f1195aaa3aab915e6dd5a7daf4f7ee1ab45c360ae35658d3b689d315R293-R294](https://github.com/liferay-echo/liferay-portal/commit/f78bf69ab6c3d7fcf8f9b81c81967abe99a790ee#diff-47bc0fd8f1195aaa3aab915e6dd5a7daf4f7ee1ab45c360ae35658d3b689d315R293-R294)
> 
> Thanks in advance!
> 
> Regards

Hi @lfbesada,

I added https://issues.liferay.com/secure/attachment/487503/6.2_before_migration to the ticket. It contains all this cases. The database I use is Postgres 10

As I mentioned on https://github.com/liferay-echo/liferay-portal/pull/11095#issuecomment-1432823860 there is an error when saving the migrated feeds, not sure if it is affected only by the database I use.

For the dummy steps, as this needs to be migrated to 7.3 and 7.2 I added for each version a dummy step. I think this would be something that @liferay-upgrades needs to review.

Anything else needed, let me know and I will try to help.

Regards.

**Comment by lfbesada** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/11213

**Pull request closed without merging**
