### PR TITLE
LPS-199575 Allow Manual Membership Management option will be disabled by default to the default site

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-199575

@Mikellorza
cc @ealonso

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Mikellorza** [comment]
@Tim-Cao thanks for your changes

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @Mikellorza, could you have a look at failed integration tests?
[com.liferay.site.service.test.GroupServiceTest](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/799967/testReport/com.liferay.site.service.test/GroupServiceTest)

**Comment by Mikellorza** [comment]
@Tim-Cao taking a look ,

Thanks

**Comment by Mikellorza** [comment]
ci:close

**Comment by Mikellorza** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/14143

**Pull request closed without merging**
