### PR TITLE
LPS-167959 Moves user_group_action.jsp to clay:dropdown-actions

### PR DESCRIPTION
**Pull request by DiegoHu97**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Hey @DiegoHu97,

Could you please apply https://github.com/brianchandotcom/liferay-portal/pull/126220#issuecomment-1314660769 to your pr?

**Comment by DiegoHu97** [comment]
@ealonso updated 😄

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/10294

**Pull request closed without merging**
