### PR TITLE
LPS-127466 - Ensure correct image variation is rendered in view mode when mapping background image of container to an image in D&M or to an Image Field of Web Content

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @p2kmgcl

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:reevaluate:1212004_7534

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:reevaluate:1012004_6415

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
