### PR TITLE
LPS-134599 Adds also FragmentElementId to freemarker context (same ID that we use in the markup for the wrapper)

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
The failure cases are unrelated to changes in PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/103541

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
