### PR TITLE
[TS] LPS-128817

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-128817

Resent from https://github.com/brianchandotcom/liferay-portal/pull/99812 with [additional commit](https://github.com/liferay-echo/liferay-portal/commit/185a4f41fd56483c3a0e2a45c53112bbc658eac1) addressing [Brian's comment](https://github.com/brianchandotcom/liferay-portal/pull/99812#issuecomment-797076562).

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
@ChrisKian, resent here, just added some checks for possible NPEs

**Pull request closed without merging**
