### PR TITLE
LPS-163019 Validate the reference of the private page in the web content

### PR DESCRIPTION
**Pull request by antonio91dev**
check if any private virtual hosts have been defined before checking if it is the default site

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Hey @antonio91dev,

There is a SF error. Could you please fix it and resend this pr to @liferay-stating team? This logic is under export import module and should be reviewed by them.

Regards,
Eudaldo.

**Pull request closed without merging**
