### PR TITLE
LPS-168644 Folder capabilities should be supported by staging process

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to task](https://issues.liferay.com/browse/LPS-168644)

Through [Use simple repository browser tag for fragment resources](https://issues.liferay.com/browse/LPS-167491), we now allow users to add folders to fragment collections, thus we need to adapt existing code so that it matches the new feature.

## Change summary:

* Change how we create the folder for the fragment collection (use unique key instead of ID)
* Upgrade process
* Adds integration tests for existing and new features

## Test Scenario No. 1

* Enable feature flag: feature.flag.LPS-158675
* Go to fragments admin
* Create a new fragment collection
* Go to resources tab
* Add a new folder
* Inside the folder, add a new image
* Create a new fragment and use the resource (i.e. [resource:folderName/imageName])
* Add the fragment to a page and publish
* Enable staging and visit the page
* The fragment should be shown

staging

## Test Scenario No. 2

* Enable feature flag: feature.flag.LPS-158675
* Go to fragments admin
* Create a new fragment collection
* Go to resources tab
* Add a new folder
* Inside the folder, add a new image
* Create a new fragment and use the resource (i.e. [resource:folderName/imageName])
* Go to Export and publish the LAR
* Stop the portal and delete the database
* Start the portal and import the LAR
* Go to the resources tab in the fragment collection
* The folder structure should be shown

export

## Test Scenario No. 3

* Start a Liferay Portal 7.3
* Create a fragment collection and add resources
* Stop the portal and upgrade to 7.4
* Check that the resources are available for the collection

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
@adolfopa, thanks a lot for the help on this, your suggestion worked flawlessly!

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:stop

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/126447

**Pull request closed without merging**
