### PR TITLE
LPS-147579 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
cc: @laszlopap

**Comment by lfbesada** [comment]
ci:reevaluate:1367401_530

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113835

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
