### PR TITLE
LPS-159591 Revert "LPS-159515 Inline"

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-159591

Why should we revert this commit?

previousFormStyledLayoutStructureItem and formStyledLayoutStructureItem point to the same object, so when updating the item configuration, previousFormStyledLayoutStructureItem changes its values ​​always having the same as formStyledLayoutStructureItem so the condition of the bellow if clause is never met because we are comparing the same objects. The consequence of it is that the form content is never automatically updated.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1277401_4308

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
