### PR TITLE
LPS-143500 No needed, since we are updating with the same value

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
cc: @lfbesada

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, could you have a look at the following regression issue caused by this PR.
Cannot publish content page with draft changes via remote service
**Step to reproduce**
1. Add a new site
2. Add a content page without publish
3. Navigate to the view mode via Home link on Product Menu
4. Get the plid of published layout via  Liferay.ThemeDisplay.getPlid(); on browser console
5. Access to http://localhost:8080/api/jsonws?contextName=&signature=%2Flayout%2Fpublish-layout-1-long
6. Populate the plid then Invoke

**Expected Results**
The content page should be published

**Actual Results**
Nothing happens.

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
