### PR TITLE
[TS] LPS-135017 | Asset Publisher configuration: Tags shown twice if they come from different sites

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-135017
Thank you!

-----

I modified the AssetTagSelectorDisplayContext to not return a tag more than once. Currently, if we create the same tag in two sites and on one of the sites create a page with an asset publisher and configure the asset publisher scope to include the other site as well. In this case, if we want to filter by tags in the filter -> tag section the selector window will list both of the tags with the same value. As we do not show any other info about the tags except their name this duplication is confusing. Also in the previous use case selecting any of the tags or both makes no difference in the result of the filtering.

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Thanks for the fix @bakayattila 
Forwarding it to Brian

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
