### PR TITLE
[TS] LPS-174456 Form Container fragment is not showing correctly title from a picklist object field

### PR DESCRIPTION
**Pull request by jgarcialr**
Motivation
=======
This PR is aimed to solve [LPS-174456](https://issues.liferay.com/browse/LPS-174456), If you map an object with a picklist field into a form container, it doesn't show the title of the options, [Object Object] is shown.

Proposed Solution
========
When the option fields are created, check if the "option.textContent" is an object, and get the name of it.

Steps to Verify
========

1. Create a Picklist with some values.
2. Create an Object (A) with a picklist field (use the one form step 1), use this field as Title field and publish it.
3. Create an Obejct (B) with a text field and publish it.
4. Create "One to Many" relationship from A to B.
5. Create several items of Object A.
6. Create a content page, add the Form Container fragment and map it with object B.
7. Publish the page.
8. View the page and click on the dropdown menu that relates B with A.

Screenshots (if applies)
========
Images/animations that showcase the changes
image
image

Checklist (optional)
========

CODE:
- [X] I have considered breaking this PR into smaller PRs if the amount of changed code is too large
- [X] I have performed a self-review of my own code following Liferay's code conventions
- [X] I have checked other areas of the product for solutions to similar problems
- [ ] I have added tests that prove my fix is effective or that my feature works

COMMITS:
- [X] My commits organize changes in coherent units
- [X] There are no commits which should be combined into others
- [X] My commits are ordered in a way that ease understanding
- [X] My commit messages are well formatted and concisely describe what was changed and why it was changed

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
Hi @victorg1991 ,

It's the code ok? Is there any improvement that I can made to move this to master?

**Comment by victorg1991** [comment]
resent here :) https://github.com/liferay-echo/liferay-portal/pull/11038

**Pull request closed without merging**
