### PR TITLE
LPS-164257 Remove FF

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.

https://issues.liferay.com/browse/LPS-164257

Hi @Tim-Cao, could you please review my changes? Thanks!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ozysouza** [comment]
ci:test:sf

**Comment by ozysouza** [comment]
ci:test:relevant

**Comment by ozysouza** [comment]
Hi @veroglez, I've noticed that if we hovers the Border Color it shows the input value instead of the Border Color name, is it expected?

**Comment by Tim-Cao** [comment]
Btw, I found a bug here https://issues.liferay.com/browse/LPS-166012 Would you mind having a look at? @veroglez

**Comment by Tim-Cao** [comment]
Hi @veroglez, I fixed the Poshi side then test them here. https://github.com/liferay-echo/liferay-portal/pull/9973

**Comment by ozysouza** [comment]
ci:close

**Pull request closed without merging**
