### PR TITLE
LPS-118906 This is the only place were we cannot cleanly remove the attribute. So create a new infoDisplayObjectProvider from the new implementation and use it temporarily

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@pavel-savinov, @ealonso

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
Since the failure tasks unrelated to changes in PR and in order to not clog up ci resources I pushed directly to BChan.
See https://github.com/brianchandotcom/liferay-portal/pull/92877

**Pull request closed without merging**
