### PR TITLE
LPS-130642 We should be casting tag names to lower case

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-130642

In Liferay 6.2, when fetching and finding AssetTags by name and groupId we cast the name passed in from PortletPreferences to lower case. The method was changed from 6.2 in [LPS-52588](https://issues.liferay.com/browse/LPS-52588) to simplify some of the calls for asset tags. However the method AssetTagFinderImpl.doFindByG_N used prior to LPS-52588 [cast the name passed in to lower case](https://github.com/brianchandotcom/liferay-portal/pull/23223/commits/b02d2ac41e6345c66ab3bd96cbfe96aad5808d97#diff-0cca6d98caade78feb402775c9a8267db01974d99bd490cd563d83728ff081d8L350), the methods now used do not however.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @SamZiemer,

We shouldn't make changes in generated files like PersistenceImpl. Could you please make the changes in the correct file and resend?

Regards,
Eudaldo

**Comment by SamZiemer** [comment]
resent here https://github.com/liferay-echo/liferay-portal/pull/4265

**Pull request closed without merging**
