### PR TITLE
LPS-149718 - Investigate if limitation that causes loss of reference from page to fragment in global when importing LAR can be removed

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @jkappler @lfbesada

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
@bakayattila

**Comment by dacousalr** [comment]
Hi @ruben-pulido,

First, thank you for working on this issue.

I have taken a quick look at the current PR, and although it works for local Staging or local export/import, it might not work so well for remote Staging or for export/import between different environments since groupIds can also be different.

As an idea to make the solution functional for these four scenarios, I would suggest that the groupKey value should be added as well at export time.

What do you think?

**Comment by bakayattila** [comment]
Hi @dacousalr @ruben-pulido,
I Agree with Daniel that's why I recommended the loose reference which works based on the UUID which we do not change in export-import or in staging processes.

**Comment by ruben-pulido** [comment]
Thank you @dacousalr and @bakayattila for your feedback!

Do you see any advantages/disadvantages of any of the proposed approaches vs the other?
A) fragment-entry-key + group-key
B) FragmentEntry UUIDs

**Comment by ruben-pulido** [comment]
@dacousalr pointed out that if the FragmentEntry has been exported and imported into several sites, the fragment-entry-UUID would not suffice to uniquely identify the FragmentEntry that should be referenced during import.

For this reason, the tuple (group-key, fragment-entry-key) is preferred over fragment-entry-UUID.

This new [PR](https://github.com/liferay-echo/liferay-portal/pull/7590) contains the new logic using (group-key, fragment-entry-key)

**Pull request closed without merging**
