### PR TITLE
LPS-185583 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-185583

@jkappler

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward:force

**Comment by Tim-Cao** [comment]
Hi @jkappler, do we need to make some changes?

**Comment by Tim-Cao** [comment]
ci:forward:force

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
My mistake

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
