### PR TITLE
LPS-7046 Add reset button for custom screen configuration

### PR DESCRIPTION
**Pull request by jkappler**
This PR contains some LPD's:

1. https://liferay.atlassian.net/browse/LPD-7042
2. https://liferay.atlassian.net/browse/LPD-7045
3. https://liferay.atlassian.net/browse/LPD-7046
4. Fix about a use case of url separators validations: https://github.com/liferay-echo/liferay-portal/pull/15044/commits/0c9edb62e27833982f1514a0804b0356af13ef2b

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
@Mikellorza, @sandrodw3, with SF fixed ❤️

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/15132

**Pull request closed without merging**
