### PR TITLE
LPS-196400 & LPS-196401

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
@ealonso We fixed SF issue here: https://github.com/liferay/liferay-portal/commit/d369e7db29fc2acfe7def11affc9ee21ca18b5a7
We are waiting for the new SF version. Now you can ignore this SF issue.

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/140874

**Pull request closed without merging**
