### PR TITLE
LPS-130742 Migrate asset/input_asset_links

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @liferay-echo,

Attached is an update for http://issues.liferay.com/browse/LPS-130742.

**Test Plan:**

1. Login to Liferay
2. Click on the **Product Menu**
3. Go to **Content & Data** -> **Web Content**
4. Click the `+` to add a **Basic Web Content**
5. Scroll down the **Properties**  to the **Related Assets** section
6. Click the **Select** button and choose **Blogs Entry**
7. Publish the **Web Content**
8. Click on the **Product Menu**
9. Go to **Content & Data** -> **Blogs**
10. Click the `+` to add a **Blog Entry**
11. Scroll down to the **Related Assets** section
12. Click the **Select** button and choose **Basic Web Content**
13. Select the newly created **Web Content** in the modal window
asset

**Test Plan for Management Toolbar Update (https://github.com/liferay-frontend/liferay-portal/pull/989/commits/5f3965332e6bfef94ee25af4ec801cd542c72f11)**
14. Click on the **Product Menu**
15. Go to **Site Builder** -> **Pages**
16. Click the `+` to add a **Public Collection Page**
17. Click the `+` to add a **Manual Collection**

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
ci:reevaluate:1067401_8513

**Comment by jonmak08** [comment]
ci:reevaluate:1067401_8513

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
