### PR TITLE
LPS-184146 Replace clay:navigation-bar with clay:tabs in trash-web

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://issues.liferay.com/browse/LPS-184146)

## Steps

**Case 1**
1. Create a web content and remove it
2. Go to Product Menu > Recycle Bin 
3. Select the info icon upper right
Screenshot 2023-05-11 at 12 52 56

**Case 2**
1. Create a web content and remove it
2. Go to Product Menu > Recycle Bin 
3. Select the web content removed
4. Select the info icon upper right
Screenshot 2023-05-11 at 12 54 05

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Niiice @DiegoHu97 👏

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
