### PR TITLE
LPS-125922 Add external reference code to JournalArticle

### PR DESCRIPTION
**Pull request by javierdearcos**
Hello team,

In the APIs we need to get and manage entities by an external reference code so we need to add this new fields to all portal entities.

This issue come after a long discussion about reusing a existing field or creating a new one and the decision was creating a new one to be more confident that the new code does not interfere with any existing feature.

We have started with JournalArticle as it is one of the most important entities of the portal. We did not used the external-reference-code attribute in the service.xml to allow ServiceBuilder create the column for us becaus,e in the case of JournalArticle, we want the externalReferenceCode be the same accross all versions of a JournalArticle (like articleId).

I've overloaded the addArticle and updateArticle methods to include this new parameter. In the case of addArticle it will use the articleId if no externalReferenceCode is specified. In updateArticle it will use the old externalReferenceCode in case the externalReferenceCode parameter is empty.

I've also modified the datahandler for import/export, made the database upgrade process taking populating the new externalReferenceCode column with the articleId, and made some tests to be sure the code is working.

I know is not the best time for you, but please I beg you to take a look at this PR when you can and let me know if you require any change or there is something you don't understand.

@jkappler has helped me a lot in the process so I hope I don't cause you to much work on this

Thank you very much!

### CODE REVIEW

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by javierdearcos** [comment]
ci:test:relevant

**Comment by javierdearcos** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Thanks for the changes @javierdearcos! They look good. Sent to Brian [here](https://github.com/liferay-echo/liferay-portal/pull/3481)

**Comment by javierdearcos** [comment]
Thank you!

**Comment by ruben-pulido** [comment]
I am reopening this PR and forwarding it to Brian, since unrelated tests are failing in https://github.com/liferay-echo/liferay-portal/pull/3481

Once it is merged, I'll send the changes to Javadoc in https://github.com/liferay-echo/liferay-portal/pull/3481/commits/24a657d2c23171a5ca8cc697f6e9a7487f1dbaba separately

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by javierdearcos** [comment]
thank you! and sorry for missing the formatJavadoc... I'm not used to it and I totally forgot

**Comment by ruben-pulido** [comment]
No problem at all! That's what we have reviews for :)

**Pull request closed without merging**
