### PR TITLE
LPS-121913 Migrate v2 usages in site/site-my-sites-web

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

**Test plan**:
- Click the Avatar on the top right of the page
- Select *My Dashboard**
- Assert that you can view and filter your sites

### CODE REVIEW

**Comment by julien** [comment]
cc @ambrinchaudhary @markocikos @jonmak08

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
LGTM, thanks!! :D

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
