### PR TITLE
LPD-15582 Increase z-index when focusing the button.

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
We need to increase z-index to 5 as when the button is in focus it has a maximum z-index of 4, this should not affect structures as the button is disabled.
image (16)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
LGTM! :rocket:

**Comment by veroglez** [comment]
ci:forward

**Comment by georgel-pop-lr** [comment]
ci:forward:force

**Pull request closed without merging**
