### PR TITLE
LPS-118100 Render fragment entry link when switching editor language

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:sff

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Backend review done. LGTM

**Comment by ruben-pulido** [comment]
@p2kmgcl While doing the review, we did the following test:
- Made a copy of the Video fragment, and name it "Localizable Video"
- Added "localizable": true for the URL configuration field and published the fragment
- Dragged the "Localizable Video" fragment onto a new page, and assign it a different URL for EN and ES.

We noticed that when changing the Language in edit mode, the video is not refreshed. Can you give us a hand on how to fix this? Thank you! :)

**Comment by ruben-pulido** [comment]
We need an additional task for supporting Fragment Compositions & Export/Import

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:stop

**Pull request closed without merging**
