### PR TITLE
LPS-157851 Fetch articles by version first if present

### PR DESCRIPTION
**Pull request by SamZiemer**
Motivation
=======
https://issues.liferay.com/browse/LPS-157851 -  Review web content in context displays resource not found

Proposed Solution
========
Prior to this pull, we were not using the version parameter added to the URL, this pull checks if the version parameter exists, if so, fetches the article by that version.

Steps to Verify
========
1. Create a web content Structure with:
Text Field - name it Heading
Rich Text - name it Body
2. Create a web content Template, and link the Structure from step 1.
In this template, add the fields from the Structure, it should appear on the Elements tab.
Format it to look like this:
~~~
<h1>${Text80630212.getData()}</h1>
<br/>
${RichText01025676.getData()}
~~~
Your values will be different, the above is an example.

Save it

3. Create a Blank Page (Content Page)
4. Add an Asset Publisher widget
5. Configure the Asset Publisher widget -> Configuration -> check Set as the Default Asset Publisher for This Page.
Click on Save
6. Publish the Page
7. Create a web content using the Structure
Name it Structure 1 web content
For Heading, put {[Structure 1 web content}}
For Body, put {{Structure 1 web content body}}

Under Display Page Template (right-side bar), select Specific
For display page, select the page from Step 3.
8. Publish the web content
9 Go to Configuration -> Workflow
10. Change Web Content Article to use the Single Approver workflow.
Click on Save.
11.Go back to the web content from Step 8, and Edit it.
Add any text to Body, and click on Submit for Publication.
12. Click on your User profile picture -> My Workflow Tasks.
The Task may appear in either Assigned to Me or Assigned to My Roles. Click on it.
13. Under {{Preview of Web Content Article}}, you should see the preview and an eye icon. Click on the eye icon.
14. You should see the preview including the edit you made in Step 11. This is expected.
15. Click on {{View in Context}}
Result: You will see a resource not found error page.
Expected: You should see the edit from Step 11.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @SamZiemer 
Thanks for the fix!
I have added a few commits, please see: https://github.com/liferay-echo/liferay-portal/pull/8874
Regards

**Pull request closed without merging**
