### PR TITLE
LPS-171084 The same Utility Page cannot be copied more than once if it has a thumbnail

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-171084)

When we delete a Utility Page (UP from now on) and this UP has a thumbnail, the delete option has to delete also the thumbnail, but not only the file, but also the folder.

## Proposed solution

Instead of delete the file, delete the folder.

## Test Scenario

1. Activate Staging.
2. Go to Site Builder > Pages and go to the Utility Pages tab.
3. Create a new Utility Page.
4. Change the Thumbnail of the Utility Page using the dropdown menu.
5. Copy the Utility Page.
6. Delete de copy you have made.
7. Try to copy the Utility Page again.

## Notes

This also happens without staging activated.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by lfbesada — APPROVED** [review]
LGTM 🎉

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/10670

**Pull request closed without merging**
