### PR TITLE
LPS-128928 Integration tests

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-128928

Follow up PR of: brianchandotcom#110684
See: brianchandotcom#110684 (comment)

cc: @NemethNorbert @sandrodw3

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1297401_759

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @lfbesada, would you mind taking a look at the integration tests failure?

**Comment by lfbesada** [comment]
> Hi @lfbesada, would you mind taking a look at the integration tests failure?

Hi Tim,

I have run in my local 
AssetCategoryStagedModelDataHandlerTest and it works ok. I can't understand why it failing but it should be related to my changes because only fails in my PR. So I have changed the implementation to avoid changes that could impact others test classes. I have sent a follow up PR for this, please see: https://github.com/liferay-echo/liferay-portal/pull/6613

Thanks!

Regards

**Pull request closed without merging**
