### PR TITLE
LPD-17105 & LPD-17106 Toolbar For Small Resolutions

### PR DESCRIPTION
**Pull request by veroglez**
PR changes for small resolutions:
- Collapse all viewport buttons in a picker
- The undo, redo, history, toggle sidebars and discard draft actions become a dropdown

FF: `feature.flag.LPD-10988`

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:test:stable

**Comment by veroglez** [comment]
ci:test:stable

**Comment by veroglez** [comment]
ci:test:stable

**Comment by veroglez** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward:force

**Comment by veroglez** [comment]
ci:stop

**Comment by veroglez** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:forward:force

**Pull request closed without merging**
