### PR TITLE
LPS-206272 Integrate configured separators with the portal

### PR DESCRIPTION
**Pull request by Mikellorza**
subtask: https://liferay.atlassian.net/browse/LPS-206272

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@ealonso, as talked with @Mikellorza, the change for urlSeparatorJSONObjectString will be done in https://liferay.atlassian.net/browse/LPD-15434

**Comment by ealonso** [comment]
Hey @Mikellorza @jkappler,

There are some baseline errors that seems to be related.

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
I've just amended these baseline error, thanks @ealonso

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:report:2532263539

**Comment by ealonso** [comment]
Hey @Mikellorza,

There are failures related with your changes, please fix it:

- com.liferay.journal.transformer.test.JournalTransformerTest
- com.liferay.headless.delivery.resource.v1_0.test.StructuredContentResourceTest
- com.liferay.template.info.item.provider.test.TemplateInfoItemFieldSetProviderTest
- com.liferay.dynamic.data.mapping.info.item.provider.test.DDMFormValuesInfoFieldValuesProviderTest
- com.liferay.asset.display.page.internal.portlet.CustomAssetDisplayPageFriendlyURLResolverTest

**Comment by Mikellorza** [comment]
@ealonso ,

I fixed the issues about all test except com.liferay.headless.delivery.resource.v1_0.test.StructuredContentResourceTest because seems not be related, for that I have created a bug :https://liferay.atlassian.net/browse/LPD-15905

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
SF issues seem unrelated

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:forward:foce

**Comment by Mikellorza** [comment]
ci:forward:force

**Comment by Mikellorza** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:report:2533244483

**Comment by Mikellorza** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:report:2531335245

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:stop

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:report:2533351917

**Comment by Mikellorza** [comment]
ci:report:2533351917

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:report:2534398227

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
