### PR TITLE
[7.4-only] LPS-121975 Replace vertical-card-v2 with vertical-card

### PR DESCRIPTION
**Pull request by julien**
**Original PR:** https://github.com/liferay-frontend/liferay-portal/pull/522

Replacing old vertical-card and horizontal-card tag uses in trash-web.

Adding support for defaultEventHandler transformation so it can accept either items or actions.

Before
image

After
image

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @julien @carloslancha 
it seems that there is still an [usage of clay-vertical-card-v2 in trash-web](https://github.com/liferay/liferay-portal/blob/99da21b8d49773477021b0472afcf38f4a917e13/modules/apps/trash/trash-web/src/main/resources/META-INF/resources/view.jsp#L195-L197)

Is this something that will be done in another pr? Or is that specific card a bit problematic?

Apart from that the pr looks great, many thanks! 😍

**Comment by julien** [comment]
Hi @victorg1991 yes replacing vertical card will be done in another PR.
Nothing problematic.

**Comment by victorg1991** [comment]
@julien Got it, thanks! 
This is good to go then 🎉

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
it seems that the missing usage will be replaced in this pr too :P

**Comment by carloslancha** [comment]
@victorg1991 done!

**Comment by victorg1991** [comment]
Thanks, checking this out again :)

**Comment by victorg1991** [comment]
Looking good 👏 

Ready to merge, once again :p

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
