### PR TITLE
LPS-123886 - The selected value should be shown in selector input field instead of field reference

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @victorg1991, the failure case should become common failure next run.

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Since the failure case is common failure not related to change in PR and in order to not clog up ci resources I pushed directly to BChan.
See https://github.com/brianchandotcom/liferay-portal/pull/97064

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
ci:stop

**Pull request closed without merging**
