### PR TITLE
LPS-204954 Create upgrade process to mark Master Pages as private as per LPS-172534

### PR DESCRIPTION
**Pull request by jonathanmccann**
https://liferay.atlassian.net/browse/LPS-204954

Previously submitted under https://github.com/liferay-echo/liferay-portal/pull/14902 @ruben-pulido. Resending due to a few issues caught by @jorgediaz-lr.

The changes from the previous pull are:

1. Using a parameter to set the boolean for `privateLayout` instead of hard coded `0` and `1` due to differences in databases
2. Updating the layout's `layoutId` to avoid a potential conflict in the case of private pages existing in the site
3. Additionally updating the `LayoutFriendlyURL` table to reflect the change from public to private

If there are any questions or concerns please let me know.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
Hi @jonathanmccann.
Thanks for the catching the issues!
The PR has some conflicts, can you resolve them? 
Thanks!

**Comment by jonathanmccann** [comment]
@ruben-pulido Thanks, should be good now.

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
Hi @jonathanmccann 
I have opened a new PR adding an integration test for the upgrade process.
see: https://github.com/liferay-echo/liferay-portal/pull/14950

**Comment by jonathanmccann** [comment]
@ruben-pulido Great, thank you for writing that. I'll keep it in mind for future pulls.

**Pull request closed without merging**
