### PR TITLE
LPP-40918 Use the same logic that LayoutTypePortlet uses to see if the portlet is in the layout

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @IstvanD @holatuwol,

The commit name starts with LPP I think it should be LPS, Could you please take a look at it?

**Comment by IstvanD** [comment]
Hi @ealonso, I'm really sorry, my mistake :)
I have reworded and pushed the commit.

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/4237

**Pull request closed without merging**
