### PR TITLE
LPS-166776 Use closeOnClick to move the focus back to the trigger

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:reevaluate:1377401_5959

**Comment by ozysouza** [comment]
Hi @victorg1991, could you please have a look on the unit test? apps:layout:layout-content-page-editor-web:packageRunTest'

Seems to be the only related failure.

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/125449

**Pull request closed without merging**
