### PR TITLE
LPS-147517 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-147517

This is only for master.

@victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @victorg1991, No regression issues found during my exploratory testing.

**Comment by Tim-Cao** [comment]
Waiting for testing on Safari.
cc @david-gutierrez-mesa

**Comment by victorg1991** [comment]
resent here: https://github.com/liferay-echo/liferay-portal/pull/8116

**Pull request closed without merging**
