### PR TITLE
LPS-124613 Don't fail in case when index doesn't exist

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:stop

**Comment by brianwulbern** [comment]
Whoa, @pavel-savinov, I haven't seen this error before:
```
     [exec] (node:26284) UnhandledPromiseRejectionWarning: Error: Command /opt/dev/projects/github/liferay-portal/modules/node_modules/@liferay/npm-scripts/node_modules/.bin/liferay-npm-bundler --config /opt/dev/projects/github/liferay-portal/modules/apps/frontend-js/frontend-js-jquery-web/build/npmscripts/tmp/.npmbundlerrc killed by signal SIGTERM
     [exec]     at spawnSync (/opt/dev/projects/github/liferay-portal/modules/node_modules/@liferay/npm-scripts/src/utils/spawnSync.js:61:9)
     [exec]     at withTempFile (/opt/dev/projects/github/liferay-portal/modules/node_modules/@liferay/npm-scripts/src/utils/runBundler.js:20:4)
     [exec]     at withTempFile (/opt/dev/projects/github/liferay-portal/modules/node_modules/@liferay/npm-scripts/src/utils/withTempFile.js:23:3)
     [exec]     at runBundler (/opt/dev/projects/github/liferay-portal/modules/node_modules/@liferay/npm-scripts/src/utils/runBundler.js:16:2)
     [exec]     at module.exports (/opt/dev/projects/github/liferay-portal/modules/node_modules/@liferay/npm-scripts/src/scripts/build.js:108:2)
     [exec]     at Object.build (/opt/dev/projects/github/liferay-portal/modules/node_modules/@liferay/npm-scripts/src/index.js:17:30)
     [exec]     at module.exports (/opt/dev/projects/github/liferay-portal/modules/node_modules/@liferay/npm-scripts/src/index.js:94:23)
     [exec]     at main (/opt/dev/projects/github/liferay-portal/modules/node_modules/@liferay/npm-scripts/bin/liferay-npm-scripts.js:12:31)
     [exec]     at Object.<anonymous> (/opt/dev/projects/github/liferay-portal/modules/node_modules/@liferay/npm-scripts/bin/liferay-npm-scripts.js:15:1)
     [exec]     at Module._compile (internal/modules/cjs/loader.js:689:30)
     [exec] (node:26284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

Did you resend this change?

**Comment by jpince** [comment]
@brianwulbern see https://github.com/liferay-echo/liferay-portal/pull/3174 and https://github.com/brianchandotcom/liferay-portal/pull/96748, needs additional work from Pavel

**Pull request closed without merging**
