### PR TITLE
LPS-117921 Introduce Permissions Provider to facilitate replacing AssetRendererFactory for checking permissions

### PR DESCRIPTION
**Pull request by JorgeFerrer**
/cc @jkappler

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:forward

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/1719

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
