### PR TITLE
LPS-199722 Implement Import Export for page rules 

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-199722

This PR was reviewed  [here](https://github.com/liferay-echo/liferay-portal/pull/14100), I'm resending it because of[ this comment](https://github.com/brianchandotcom/liferay-portal/pull/142858#issuecomment-1783791917). That commit has been removed from this PR since it is not related, and this bug has been fixed in [this other PR](https://github.com/liferay-echo/liferay-portal/pull/14140)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:test:stable

**Comment by lfbesada** [comment]
ci:forward

**Comment by liulukiwi** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142978

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
