### PR TITLE
[TS] LPS-125088

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-125088

This issue resolves a regression from LPS-124715 by correctly fixing the solution by fixing a related issue which allows workflow task comments to appear in the Journal Article comments.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @ChrisKian,

Could you please send this one to @liferay-lima or @liferay-workflow?

Thanks!!

**Comment by ChrisKian** [comment]
Sorry about that @ealonso, forwarded to https://github.com/liferay-lima/liferay-portal/pull/1302

**Comment by ealonso** [comment]
No problem @ChrisKian

**Pull request closed without merging**
