### PR TITLE
LPS-121599 When updating a Layout friendly URL exceeding character length doesn't show message in error tooltip

### PR DESCRIPTION
**Pull request by jgarcialr**

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jgarcialr** [comment]
I'll be on PTO until 13th of October.
Any question regarding this ticket please, ask @crodriguezy

//cc @dacousalr, @crodriguezy

**Comment by crodriguezy** [comment]
Hi @liferay-echo, did you have the change to review this PR?

Thanks!

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/2550

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
