### PR TITLE
LPS-177331 Adds new ddmStructureId column in Journal Article

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-177331

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
@lfbesada rebase errors, since everything is ok and the tests are in green, I think you can rebase and send directly to Brian.

**Comment by lfbesada** [comment]
ci:forward:force

**Comment by lfbesada** [comment]
See: https://github.com/brianchandotcom/liferay-portal/pull/131481

**Pull request closed without merging**
