### PR TITLE
[TS] LPS-180210 Do not override the styles of all elements of the Modal with the cadmin class

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hi Team,

LPS: https://issues.liferay.com/browse/LPS-180210
It is a regression fix caused by https://issues.liferay.com/browse/LPS-175642

I removed the _cadmin_ class from the ClayModal component and applied to the ClayModal.Footer only, because this solution applies the expected button style described in LPS-175642 as well as it is not going to override the whole Modal that causes the issue in LPS-180210.

Could you please review it?
Thanks
cc. @victorg1991 @pat270

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @orsolyaDekany 
I just sent a pr with a similar fix a couple of hours ago: https://github.com/liferay-echo/liferay-portal/pull/11595 I isolated more things to delimit this a bit more, could you check it out to se if I've missed something?

Sorry about that :'(

**Comment by orsolyaDekany** [comment]
Hi @victorg1991 , your solution resolves the issue described in LPS-180210. Thanks!

**Pull request closed without merging**
