### PR TITLE
LPS-168575 Copy possible error messages and exceptions from /data_layout_builder/end.jsp, also do the following logic:

### PR DESCRIPTION
**Pull request by ealonso**
Original message:

Dear Team,

Could you please review this pull request?

Motivation
=======
If importing a Web Content Structure fails, the error message "Error: The structure was not successfully imported." isn't descriptive enough, as the failure could have many reasons. If information about the root cause can be extracted from the exception, at least some of it should be part of the error message presented to the user. 
https://issues.liferay.com/browse/LPS-168575

Proposed Solution
========
If the exception has a message, it is forwarded to the UI to be displayed.

Steps to Verify
========
Please consult the linked LPS for reproduction steps.

Thank you and best regards,
István

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/126362

**Pull request closed without merging**
