### PR TITLE
LPS-130815 Filter and Order should persist.

### PR DESCRIPTION
**Pull request by brianikim**
https://issues.liferay.com/browse/LPS-130815

Forwarded from https://github.com/drewbrokke/liferay-portal/pull/1345

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:sf

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/4329

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/4329

**Pull request closed without merging**
