### PR TITLE
LPS-189886 Styles in Asset Publisher configuration -> filter are broken

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
The motivation behind this PR is to fix some style issues in the Asset Publisher for the Edit View.

Proposed Solution
========
What I did to solve this problem is to add the necessary spacing between elements and also remove some unnecessary styling code from it.

Steps to Verify
========
1. Go to Edit view for a page
2. Add an Asset Publisher from the left sidebar Widget Section
3. Click on the Options ellipsis button -> Configuration
4. Select Dynamic for Asset Selection and then go to the Filter section

Screenshots
========
BEFORE
Screenshot 2023-07-17 at 11 06 01

AFTER
Screenshot 2023-07-17 at 11 07 51

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Stephy6** [comment]
In the case of the Tags Selector, the component is rendered by AssetTagsSelector.js from the asset-taglib module. This component adds the OTHER METADATA message (on the top of the input) and therefore I couldn't fix the position as well as I wanted. Could anyone take a look specifically at this?

**Comment by ealonso** [comment]
Hey @Stephy6,

What happen with Collections widget when you create a new dynamic collection?

**Comment by sandrodw3** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/12902

**Pull request closed without merging**
