### PR TITLE
LPS-122101 Don't use default stylebook entry for the control panel or in the preview mode

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by ealonso** [comment]
Hey @pavel-savinov,

What happen if we want to preview a web content? or If we want to use responsive functionality in a content page?

**Comment by ealonso** [comment]
cc: @david-gutierrez-mesa Could you please take a look at it? https://github.com/liferay-echo/liferay-portal/pull/2691#issuecomment-715105050

**Pull request closed without merging**
