### PR TITLE
LPS-186372 Tests for importing page definition + missing tests

### PR DESCRIPTION
**Pull request by jkappler**
https://issues.liferay.com/browse/LPS-186372

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
@ruben-pulido, applied changes requested by Brian here https://github.com/brianchandotcom/liferay-portal/pull/136135#issuecomment-1586226769, in the last commit

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Test that is failing is related to CommerceOrderType which is not related to these changes

**Comment by Tim-Cao** [comment]
ci:forward:force

**Comment by jkappler** [comment]
thanks @Tim-Cao 😍

**Pull request closed without merging**
