### PR TITLE
LPD-15726 Blank page is displayed after filtering for category in collection page

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
Blank page is displayed after filtering for category in collection page because in some cases a categorised User can make its way to the search results. Which can't be converted to the AssetList's type.
https://liferay.atlassian.net/browse/LPD-15726

Proposed Solution
========
By adding a classTypeId filter to the searchContext of the dynamicSearch triggered, we can rule out User typed results.

Cheers,
Balázs

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
@balazssk Marking it on-hold since, although the added test is failing (without the fix) I haven't been able to reproduce the issue (without the fix) following the steps in the associated ticket

**Comment by balazssk** [comment]
Hi @ruben-pulido ,
Steps should be reproducible on master now (used e5cd9b9d7fb5332ad7593caa307e433a35796070 )

**Comment by ruben-pulido** [comment]
Thanks for the heads up @balazssk 
It is now reproduceable and the fix works correctly. 
I added some changes here: https://github.com/liferay-echo/liferay-portal/pull/15163

**Pull request closed without merging**
