### PR TITLE
LPS-149984 buildLang

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:stop

**Comment by ozysouza** [comment]
Hi @p2kmgcl! There is one regression issue related to your changes, would you take a look at?

1. Add a content page
2. Add a new experience
3. Add a heading fragment to page
4. Change to default experience

You can also see the video bellow:

https://user-images.githubusercontent.com/72820234/166586444-63f59f03-61ae-4933-ad8f-1cdfe4cf0959.mp4

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by p2kmgcl** [comment]
Thanks @ozysouza! I will fix that!

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
> ci:forward

Hi @ealonso, if this forward doesn't work I'll sent this PR directly yo Brian since the failures are not related to the changes.

**Comment by ealonso** [comment]
Hey @ozysouza
Could you please do your magic? 🙏 
Thanks!!

**Comment by ozysouza** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/116955

**Comment by ozysouza** [comment]
ci:close

**Pull request closed without merging**
