### PR TITLE
[TS] LPS-159875 remove HtmlUtil.escape. It's already scaped by autoescape annotation

### PR DESCRIPTION
**Pull request by jgarcialr**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Hey @jgarcialr,

Could you please fix the sf error?

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
Hi @ealonso ,
Fixed SF error.

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
@jgarcialr for next time is better if you squash your commits, in that way is going to be more clear the code and easy to review

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
