### PR TITLE
[TS] LPS-145876  share friendly URL`s when Display page is available

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
/cc @dacousalr

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @georgel-pop-lr 
Thanks for the PR!
I'll wait to do the full review until the conflicts are fixed but I've been looking at the code. I wondering if you have considered using the [AssetDisplayPageUtil.hasAssetDisplayPage(groupId, assetEntry)](https://github.com/liferay/liferay-portal/blob/5db9d37799c156c48492183ca15ecf938b39a393/modules/apps/asset/asset-display-page-api/src/main/java/com/liferay/asset/display/page/util/AssetDisplayPageUtil.java#L59) method from AssetPublisherHelperImpl  instead of creating a new method in AssetRenderer?
Maybe I am missing something but I think it could be a cleaner and easy way to implement the desired behavior.
Thanks! Regards
cc @dacousalr

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr Thanks for the PR! I'll wait to do the full review until the conflicts are fixed but I've been looking at the code. I wondering if you have considered using the [AssetDisplayPageUtil.hasAssetDisplayPage(groupId, assetEntry)](https://github.com/liferay/liferay-portal/blob/5db9d37799c156c48492183ca15ecf938b39a393/modules/apps/asset/asset-display-page-api/src/main/java/com/liferay/asset/display/page/util/AssetDisplayPageUtil.java#L59) method from AssetPublisherHelperImpl instead of creating a new method in AssetRenderer? Maybe I am missing something but I think it could be a cleaner and easy way to implement the desired behavior. Thanks! Regards cc @dacousalr

Hi @lfbesada,

Actually, we use `AssetDisplayPageUtil.hasAssetDisplayPage(groupId, assetEntry)`, the only issue is that in case of journal you need to check also if the display page is an asset publisher page that has this Display Settings configuration marked (Set as the Default Asset Publisher for This Page) that's why we check for getLayoutUuid https://github.com/liferay-echo/liferay-portal/blob/9cbea0bcbccb3747acbcab686594e2b2a8206bff/modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/asset/model/JournalArticleAssetRenderer.java#L633 

And for DLFileEntryAssetRenderer.java, I got some help from @dacousalr who maybe can explain better why we choose to use these methods.

Regards.

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1257401_1657

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1257401_1658

**Pull request closed without merging**
