### PR TITLE
[TS] LPS-139493

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hello,

These changes are for https://issues.liferay.com/browse/LPS-139493 / https://issues.liferay.com/browse/PTR-2655.

On the PTR it was discussed to update the modified date of the pages and templates so that they would be picked up by the staging process as needing to be published. Unfortunately, it was not that simple as Changesets are used to determine what needs to be published.

This logic is taken mostly from JournalArticleStagingModelListener (https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/internal/model/listener/JournalArticleStagingModelListener.java#L101).

Whenever changes are propagated for a fragment entry link it adds an entry for the associated layout and, potentially, the page template if one exists. With these changeset entries added to the database the staging screen now correctly selects and displays the page template for publication.

I added the logic here instead of the FragmentEntryLinkStagingModelListener because the fragment could be propagated to some pages and templates but not others. If we performed the logic in the listener we would not know which ones should be updated.

There is a source formatting issue because of the use of LayoutPageTemplateEntryLocalServiceUtil. If I added this service as a reference then there would be an NPE thrown on start up. It might be because LayoutPageTemplateEntryLocalServiceImpl has a reference to FragmentEntryLinkLocalService (https://github.com/jonathanmccann/liferay-portal/blob/c9571c06d292c9e749ab94fd20c2eddbd7899c4a/modules/apps/layout/layout-page-template-service/src/main/java/com/liferay/layout/page/template/service/impl/LayoutPageTemplateEntryLocalServiceImpl.java#L1124). I figured that due to the tight timeline of the client this is good enough for the time being and can be revisited later for sending to Brian.

I tested this with Master Pages, Page Templates, Display Page Templates, and Content Pages. Within that I also tested propagating only to some pages and not others to confirm publishing did not push the changes to every page.

Please let me know if you see any issues with this approach or if there is a better way to resolve the issue.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @jonathanmccann Can you take a look at those sf failures? Thanks! :)

**Comment by jkappler** [comment]
Already taking a look @jonathanmccann

**Comment by jkappler** [comment]
@jonathanmccann, was playing around the idea of the PTR. Please check https://github.com/liferay-echo/liferay-portal/pull/5919. Changing the modified date of the page + page template entries work.

I changed also LayoutTypeControllerPortlet to pass the display context in the request (avoiding NPE when the service is not present).

Since we could not have the reference (because of circular dependency), I used the model listener, but avoided several scenarios so that the modified date from LayoutPageTemplateEntry wouldn't be changed all the time.

This is far from perfect, but don't want to risk any potential blockers since we have the release coming soon, so all the code is isolated. 

Let us know what you think please. (will cc you in the other PR)

Thanks!

**Pull request closed without merging**
