### PR TITLE
LPS-185999 Replace custom sql with DSLQuery in layout-service

### PR DESCRIPTION
**Pull request by YurenaC**
Motivation
=======
In order to take advantage of the cache used in the DSLQueries, we will be migrating several database queries used in finder classes to improve performance

COMMITS:
- LPS-185999 Add Test to check actual behavior
- LPS-185999 Migrate to DSLQuery
- LPS-185999 Remove old finder

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/12284

**Pull request closed without merging**
