### PR TITLE
LPS-125055 Test that crawlers indexes widget content

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Unable to connect to a valid mail server. Please make sure one is properly configured: Couldn't connect to host, port: localhost, 25; timeout -1, this is kind of setup or internet issue. , I will report this when I see this error twice. All the failures are not related to this pr, so I'll forward this pull to BChan dirrectly.

**Comment by liulukiwi** [comment]
resend:
https://github.com/brianchandotcom/liferay-portal/pull/97306

**Pull request closed without merging**
