### PR TITLE
LPS-169729 Uses the same editor for web content display and for web content mapping

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1377401_6563

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, the scheduled web content is not shown on Select modal of Web Content Display
**Step to reproduce**
1. Add a web content scheduled publish in the future.
2. Add a Web Content Display to a widget page
3. Open the select web content modal

**Expected Results**
The scheduled web content should be shown on modal.

**Actual Results**
The scheduled web content is not shown on modal.

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
