### PR TITLE
LPS-137577 Select multiple Categories when creating a navigation menus

### PR DESCRIPTION
**Pull request by lfbesada**
Previous PR: https://github.com/liferay-echo/liferay-portal/pull/6574

https://issues.liferay.com/browse/LPS-137577

https://issues.liferay.com/browse/LPS-142377
https://issues.liferay.com/browse/LPS-142378
https://issues.liferay.com/browse/LPS-142417
https://issues.liferay.com/browse/LPS-142508
https://issues.liferay.com/browse/LPS-143204
https://issues.liferay.com/browse/LPS-143222

@Tim-Cao 
@sandrodw3

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The failure case is unrelated to this PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/110731

**Comment by Tim-Cao** [comment]
ci:stop

**Pull request closed without merging**
