### PR TITLE
LPS-143868 Fixing dropdown language

### PR DESCRIPTION
**Pull request by lazhcsilva**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lazhcsilva** [comment]
ci:test:sf

**Comment by lazhcsilva** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
Hey @lazhcsilva!

I think we should fix this issue more properly. With the z-index solution you proposed, we are only moving the language dropdown bellow the toolbar, but it is still hidden when scrolling. Can you investigate this a bit more and send another PR?

Thanks!

screen-record-2022-07-15_09-21

**Pull request closed without merging**
