### PR TITLE
Lps 149277

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-149277

Refactored code to extract duplicated code across journal-web and journal-service.

A similar pattern is used here [JournalArticleSitemapURLProvider.visitArticles()](https://github.com/liferay/liferay-portal/blob/687d7dfd609b7727d307edba457477fa2b9de9f5/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/internal/layout/admin/util/JournalArticleSitemapURLProvider.java#L274-L295) but I couldn't think of a way to get it extracted due to the different ways the URL could be built.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Thanks for the PR @noornajj! 

Some minor comments:
- Can we use JournalHelper instead of JournalHelperUtil when we are in the context of a Component? (for example JournalArticleInfoItemFieldValuesProvider)

- Do we need to define Boolean privateLayout as "Boolean" instead of "boolean"? 

- I would sort the parameter in buildURLPattern alphabetically

**Comment by noornajj** [comment]
Thank you for the comments @ruben-pulido 
I will make the updates and resend. Should I keep the same PR and force push or send a new PR?

**Comment by ruben-pulido** [comment]
Thank you @noornajj. I prefer a new PR. You can reference this PR from the new one to keep the history

**Pull request closed without merging**
