### PR TITLE
LPS-147831 Change modal size

### PR DESCRIPTION
**Pull request by victorg1991**
The idea is to some exploratory testing of this PR

More info in the associated subtask: https://issues.liferay.com/browse/LPS-153443

Deploy journal-web

1. Navigate to Content & Data > Web Content
2. Create a new Folder
3. Create a new Basic Web Content
4. Click on the ellipsis icon to the right of the Web Content
5. Click on the "Move" option
6. Click on the "Select" button 

@david-gutierrez-mesa @liulukiwi @Tim-Cao @ozysouza

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:test:bundle

**Comment by Tim-Cao** [comment]
Hi @victorg1991, No regression issues found during my exploratory testing. However, there is an issue. Could you fix it?
The search icon is unused since the search results is shown along with typing. Could we remove it?
For example, The search field doesn't that icon in Configure Allowed Fragments modal.
image

**Comment by Tim-Cao** [comment]
Waiting for testing on Safari.
cc @david-gutierrez-mesa

**Comment by victorg1991** [comment]
Hey @Tim-Cao I think it is better to put this icon in the Allowed Fragment modal, since it is a pattern that we have in other places :)

**Comment by Tim-Cao** [comment]
However, that icon doesn't have any functionality on new modal.
@victorg1991

**Comment by victorg1991** [comment]
Yep, it is an icon not a button @Tim-Cao it is just hinting users that the input is for searching. It is present in the fragments sidebar and also in the template editor sidebar

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
@victorg1991
Shouldn't keep the consistent behavior with other places?
In many places, the icon is a button has a trigger function.
image

**Comment by victorg1991** [comment]
@Tim-Cao  When you have to reload the page to obtain the results it makes sense to be a button, in this case we are filtering as the user type so in this case the button won't do anything

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
