### PR TITLE
[7.4.x only] LPS-123582 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-123582

This is only for master.

@victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
sse: https://github.com/liferay-echo/liferay-portal/pull/2942

**Comment by Tim-Cao** [comment]
ci:stop

**Pull request closed without merging**
