### PR TITLE
LPS-164462

### PR DESCRIPTION
**Pull request by quanhuynhces**
Hi team,
This PR is for fixing [LPS-164462](https://issues.liferay.com/browse/LPS-164462)
The original issue [LPS-151745](https://issues.liferay.com/browse/LPS-151745) was resolved. However, some changes may cause this issue again so we create new LPS to fix this issue.
This is quote from @chileces
>This PR is to fix the regression in the previous PR https://github.com/liferay-core-infra/liferay-portal/pull/1900#issuecomment-1270763674
Solution:
When performing checks to allow access to a portlet id, we should not reuse the previous value in the HTTP servlet attribute, the checking result either true/false can be changed in the runtime and may cause a problem if it is unsynchronized
In reference to the [ControlPanelLayoutTypeAccessPolicy](https://github.com/chileces/liferay-portal/blob/700a0b5588e6ac8dea98684d46eb113a345d5d59/modules/apps/layout/layout-type-controller/layout-type-controller-control-panel/src/main/java/com/liferay/layout/type/controller/control/panel/internal/model/ControlPanelLayoutTypeAccessPolicy.java#L70), there is no caching, too.

Please review and leave your comment
Thanks,
Quan
cc @chileces

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/9933

**Comment by ruben-pulido** [comment]
Hi @quanhuynhces @chileces 
The bug was a regression caused by https://github.com/liferay/liferay-portal/commit/8f277e86
Reverting that changes fixes the issue

**Pull request closed without merging**
