### PR TITLE
LPS-152446 Users click to edit a page from the page management screen

### PR DESCRIPTION
**Pull request by jkappler**
https://issues.liferay.com/browse/LPS-152446

This PR redirects the user either to the view mode of the page or to the edit mode of the page based on permissions

To test this, we would need to create a new user that can access the pages admin widget, and has only view permissions. When the user clicks on the page, they should navigate to the view mode of the page.

If a user that has permissions would do this, they would navigate to the page editor so that they can work on the page

Screenshot 2022-06-06 at 14 38 24

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:echo

**Comment by jkappler** [comment]
@david-gutierrez-mesa, will set this on hold until the test finish running

**Comment by jkappler** [comment]
ci:rest:relevant

**Comment by jkappler** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
Hi @jkappler, according to ci:test:relevant, there is no regression issues found. Let's wait for ci:test:echo. I did the following manual testing in addition to four criterias

- When a user with edit permissions clicks a content page in page administration, the page editor is opened with the selected page ready to be edited

- When a user with edit permissions searches for a content page in pages administration, and then clicks on it in the results, the page editor is opened with the selected page ready to be edited

- When a user without edit permissions clicks a content page in page administration, the page is opened in view mode

- When a user without edit permissions searches for a content page in pages administration, and then clicks on it in the results, the page is opened in view mode

They are

- When a user with edit permissions clicks a content page in page administration of live site, the page is opened in view mode

- When a user without edit permissions clicks a content page in page administration of live site, the page is opened in view 

- When a user with edit permissions clicks a content page in page administration of staging site, the page is opened in view mode

- When a user without edit permissions clicks a content page in page administration of staging site, the page is opened in view mode

**Comment by jkappler** [comment]
Hi @Tim-Cao, yes, those are also necessary scenarios. I will also add them to the acceptance criteria.

Thanks a lot!!!!

**Comment by Tim-Cao** [comment]
Hi @jkappler, there is no regression issues found according to [ci:test:echo](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1654591117265&testrayRunIdA=1870409818&testrayRunIdB=1870559189)
Feel free to run forward

**Pull request closed without merging**
