### PR TITLE
LPS-193240 The third item in the breadcrumb is never displayed when browsing the recycle bin

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-193240)

## Test Scenario 1
1. Create a folder for web content (“Folder 1”)
2. Create second folder inside the previous one (“Folder 1.1”)
3. Create a web content or more folders inside the “Folder1.1”
4. Delete the “Folder 1” (with everything inside)
5. Go to the recycle bin and navigate through the folders until get to the item created in step3.

image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
