### PR TITLE
LPS-139068 Merge styles values in a jsonObject honoring inheritance

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant 🕯

**Comment by sandrodw3** [comment]
ci:forward 🐸

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
