### PR TITLE
LPS-148385 Asset Publisher documents don't appear in the Page Content tab

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Review by lfbesada — APPROVED** [review]
❤️

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
