### PR TITLE
LPS-121941 Execute all JournalArticleSearchTest and DLFileEntrySearchTest tests twice, setting enableLegacyDDMIndexFields to true and false values

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-121941

In TestOrderHelper we are currently testing the ddm sorting functionality. After LPS-103224 changes, it is necessary to test them twice, setting the DDMIndexerConfiguration.enableLegacyDDMIndexFields to true/false.

TestOrderHelper is used in two classes: JournalArticleSearchTest and DLFileEntrySearchTest 

**My changes:**
In that classes, I am adding a `setUpClass()` method that sets DDMIndexerConfiguration.enableLegacyDDMIndexFields configuration to false (_that is the default value for 7.3 and master branches_)
So we will test the default master behavior in all branches.

In order to test the legacy behavior, I have created two new classes **JournalArticleSearchLegacyDDMIndexFieldsTest** and **DLFileEntrySearchLegacyDDMIndexFieldsTest** that extend existing classes but their setUpClass() method that sets DDMIndexerConfiguration.enableLegacyDDMIndexFields configuration to true (_that is the default value for 7.0 to 7.2 branches_)

/cc @liferay-lima

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
sent to lima team for review here: https://github.com/liferay-lima/liferay-portal/pull/973

**Pull request closed without merging**
