### PR TITLE
LPS-173770 check if companyId matchs portlet's companyId in order to avoid creating Resource Permissions for non current company

### PR DESCRIPTION
**Pull request by jgarcialr**
Resent from https://github.com/liferay-core-infra/liferay-portal/pull/3173

This PR aims to solve [LPS-173770](https://issues.liferay.com/browse/LPS-173770): Adding a relationship between a company object and site object generates Duplicate entry for key 'IX_A9FF4B2C'
In the UserPersonalSitePermissions we iterate over every company and perform initPermissions even if the current companyId is not the same as the one of the portlet we are initializing.
This generates some inconsistencies while using data partitioning, per example when generating relationships between objects in a secondary virtual instance.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
