### PR TITLE
LPS-119887 Save the className also so that in can be used in the ItemSelectorField

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
fixing the test

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
