### PR TITLE
LPS-203611 and LPS-203689

### PR DESCRIPTION
**Pull request by jkappler**
https://liferay.atlassian.net/browse/LPS-203689
https://liferay.atlassian.net/browse/LPS-203611

The idea is to follow the same pattern that we use in master pages, that is, show a specific error of what is happening, but also show a generic error stating that one or more items could not be removed. This is for page templates and display pages. 

This has to be done following moving logic from checking if there are usages to model listeners. Attached some screenshots:

Screenshot 2023-12-13 at 08 48 53

Screenshot 2023-12-13 at 08 49 08

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/145227

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
