### PR TITLE
LRAC-14367

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, there is compile error
[com.liferay.segments.experiment.web.internal.processor.test.SegmentsExperimentSegmentsExperienceRequestProcessorTest](https://testray.liferay.com/home/-/testray/case_results/2411520844)

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Comment by alessandromalves** [comment]
Hey @ealonso, we had one integration test that failed here and that is not repeated in the master. I'm not entirely sure it was as expected, would you mind looking at this?

[com.liferay.segments.experiment.web.internal.portlet.action.test.GetDataMVCResourceCommandTest](https://testray.liferay.com/home/-/testray/case_results/2412147385)

```
 [exec] com.liferay.segments.experiment.web.internal.portlet.action.test.GetDataMVCResourceCommandTest > testGetProps STARTED
     [exec] 
     [exec] com.liferay.segments.experiment.web.internal.portlet.action.test.GetDataMVCResourceCommandTest > testGetProps FAILED
     [exec]     java.lang.NullPointerException
     [exec]     	at com.liferay.segments.experiment.web.internal.portlet.action.test.GetDataMVCResourceCommandTest.testGetProps(GetDataMVCResourceCommandTest.java:156)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
```

**Comment by ealonso** [comment]
ci:forward

**Comment by alessandromalves** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
