### PR TITLE
LPS-171382 Add Remove Thumbnail for Utility Pages

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-171382

cc: @BarbaraCabrera 

@AliciaGarciaGarcia This PR is changing the signature of a DLFileEntryLocalServiceImpl's method. Could you please review it in this repo in order to not waste up ci resources? Thanks in advance! ❤️

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by AliciaGarciaGarcia** [comment]
@lfbesada LGTM

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:stop

**Comment by liulukiwi** [comment]
Failures are not related, pushed to BChan directly at https://github.com/brianchandotcom/liferay-portal/pull/128220

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
