### PR TITLE
LPD-7046

### PR DESCRIPTION
**Pull request by Mikellorza**
https://liferay.atlassian.net/browse/LPD-7046

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Mikellorza** [comment]
ci:report:2535405492

**Comment by Mikellorza** [comment]
ci:reevaluate:1307401_8725

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:report: 2535862216

**Comment by Mikellorza** [comment]
The errors are not related with the PR.

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
