### PR TITLE
LPS-150394 | ci test only

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-150394

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:test

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
Hi @victorg1991, failure cases are unrelated to changes in this PR. There is conflict with Brian's master.

**Comment by Tim-Cao** [comment]
ci:test

**Comment by Tim-Cao** [comment]
Wait for another testing PR, then merge them.

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/9619

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
