### PR TITLE
[TS] LPS-201959

### PR DESCRIPTION
**Pull request by ericyanLr**
# Motivation

When a Display Page Template that includes a custom Fragment, is exported and then imported to a new site, the imported Display Page Template fails to show the proper title of the custom Fragment.

The root issue is that during the import process, the associated FragmentEntryLink fails to retrieve the associated FragmentEntry's fragmentEntryId during import. As a result, the reference is lost and the title is not properly shown.

**Ticket:** [LPS-201959](https://liferay.atlassian.net/browse/LPS-201959)

# Proposed Solution

Add the associated FragmentEntry as a dependency for exporting a FragmentEntryLink. This would make it so the FragmentEntry is able to be retrieved during the import of FragmentEntryLink, which would allow for the import to set the correct fragmentEntryId.

For additional details, please see: [PTR-4475](https://liferay.atlassian.net/browse/PTR-4475)

# Steps to Verify

1. Navigate to Control Panel > Sites
    1. Create Blank Site: TestSite
2. In TestSite
3. Navigate to Design > Fragments
    1. Add Fragment Set: TestFragmentSet
    2. Add Basic Fragment: TestFragment with the following HTML content:
		```
		<div class="fragment_1">
			abc
		</div>
		```
4. Navigate to Design > Page Templates
    1. Navigate to Display Page Templates
        1. Add Display Page Template:
            1. Name: TestDisplayPageTemplate
            2. Content Type: Web Content Article
            3. Sub Type: Basic Web Content
        2. In the editor for our created: TestDisplayPageTemplate
            1. Add our created TestFragment to the page
            2. In the left side menu, click Browser and confirm the fragment name displays as expected (TestFragment)
            3. Click Publish
5. Navigate to Content & Data > Web Content
    1. Click [+] to add a new Basic Web Content
        1. Title: TestContent
        2. Display Page: Specific
        3. Select TestDisplayPageTemplate
        4. Click Publish
6. Navigate to Publishing > Export
    1. Click [+] to export our created site
        1. Uncheck Utility Pages to work around a different bug
        2. Click Export
    2. Download our created lar file
7. Navigate to Control Panel > Sites
    1. Delete our created TestSite
    2. Create Blank Site: NewImportedTestSite
8. Navigate to Publishing > Import
    1. Click [+] to import our lar file
        1. Select our lar file
        2. Click Continue
        3. Click Import
9. Navigate to Design > Page Templates
    1. Navigate to Display Page Templates
        1. Click Edit for our imported TestDisplayPageTemplate
        2. In the left side menu, click Browser and confirm the fragment name displayed

**Expected Result**
The shown fragment name is TestFragment

**Actual Result**
The shown fragment name is the generic default name: Fragment

----

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
Thanks for this @ericyanLr ❤️!

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
