### PR TITLE
[TS] LPS-127637 Use article instead of articleDisplay to improve performance

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

I've found that in some cases articleDisplay can be substituted with article to increase performance in some edge cases when caching is disabled and JournalContentPortlet is embedded in another JournalContentPortlet.

Can you please review?
https://issues.liferay.com/browse/LPS-127637

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
Hi @liferay-echo ,
Can someone have a look at this please?
Thanks

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Hi @balazssk

Thanks for your changes. I have tested them locally following the steps you included in the LPS. With your changes deployed I still observe the OOM. Did you observe that the problem was not longer happening with your changes deployed?

**Comment by balazssk** [comment]
Hi @ruben-pulido ,
All the nested Web Content Displays render fine on my part.
Do you happen to have a stacktrace I could look through?

**Comment by ruben-pulido** [comment]
HI @balazssk 

Here is the stacktrace:

[LPS-127637-stacktrace.txt](https://github.com/liferay-echo/liferay-portal/files/5992028/LPS-127637-stacktrace.txt)

**Comment by balazssk** [comment]
Hmm, there are way more calls for RuntimeTag than I expected.
If I check for `RuntimeTag.java:396` there are 206 occurrences and `ERROR` only appears 4 times and out of that only 2 are for Heap space. Have you changed the template from 30 Web Content Displays to ~100? Or maybe you've set the outer Web Content to be displayed in one of the dynamically nested Web Content Displays and caused a recursion?

**Comment by ruben-pulido** [comment]
Hi @balazssk. Thanks for your fix and your analysis of the problem I was having. Your guess is correct!
I had set the outer Web Content to be displayed in one of the dynamically nested Web Content Displays causing a recursion.

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
