### PR TITLE
[TS] LPS-187648 | Unmapped fragment value not showing after publishing

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-187648
Thank you!

--------------

The root cause of the issue was that an empty "collectionFieldId":"" was left in the editableValues field after unmapping the previous mapping. As a result, the fragments showed the default value instead the edited value. I fixed the issue by removing the collectionFieldId from the JSON when the mapped option is unmapped.

**Reproduction Steps:**

1. Go to Content & Data --> Web Content and create basic web content.
2. Go to Site Builder --> Pages and add a content (blank) page, add to it a Collection Display fragment, and select the recent content collection provider.
3. Add a paragraph fragment to the collection display, click twice on the Paragraph fragment, switch the Mapping tab in the right-hand-site panel, and set the mapping to "Author", then publish the page.
Checkpoint: The modified paragraph appears on the page.
4. Click twice on the Paragraph fragment, switch the Mapping tab in the right hand-site-panel, and set the mapping to "Unmapped"
5. Double-click on the Paragraph fragment and set a random text, and publish the page.
6. Observe the paragraph fragment on page view.

**Expected Result:**  The edited paragraph should be displayed after publishing the page.
**Actual Result:** The edited paragraph is not viewed on the published page. instead, the default value is returned. The edited paragraph appears only when editing the page.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
Hi @bakayattila! thanks for sending the fix.

The main problem is when the unmapped option is selected, here https://github.com/liferay/liferay-portal/blob/e5341d48364c62e329d3c551ded58f3900e3c0b5/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/common/components/MappingSelector.js#LL230C28-L230C28. Right now `{collectionFieldId: ''}` is being sent, it should be enough to send `{}` and so there is no need to delete it later. Could you resend it? Thanks in advance.

**Comment by bakayattila** [comment]
Hi @veroglez,
I think I tried that and in that case, nothing happened the old mapping stayed selected even when unselected was chosen. That is why I chose the remove option instead. Shall I double-check it?

**Comment by veroglez** [comment]
@bakayattila yes, it should work that way. Right now we're passing it `{collectionFieldId: ''}` and then here https://github.com/liferay/liferay-portal/blob/e5341d48364c62e329d3c551ded58f3900e3c0b5/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/browser/components/page_structure/components/item_configuration_panels/MappingPanel.js#L54, you're deleting it. If we don't pass anything to it, `{}`, nothing needs to be deleted.

**Comment by veroglez** [comment]
Hi @bakayattila! I'll take care of this! 😃

**Comment by veroglez** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/12547

**Pull request closed without merging**
