### PR TITLE
LPS-146373 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-146373

This is only for master.

@victorg1991

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
I wonder if I could place ci:forward in the middle of a sentence

**Comment by p2kmgcl** [comment]
> I wonder if I could place ci:forward in the middle of a sentence

Nah, it only checks the beginning of it.

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by victorg1991** [comment]
resent here: https://github.com/liferay-echo/liferay-portal/pull/9201

**Pull request closed without merging**
