### PR TITLE
LPS-199202 Make a copy seems to be disabled in copied Master Pages and Display Pages but allows copying

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-199202) and [Link to ticket](https://liferay.atlassian.net/browse/LPS-199211) 

### Changes and recommendations 

Don't allow copy Master Pages or Display Pages when it's a draft.
You will need the Feature Flag LPS-197408 and the LPS-195263.

## Test scenario 1

1.Add feature.flag.LPS-195263=true to portal-ext.properties.
2. Add feature.flag.LPS-197408=true to portal-ext.properties.
3. Create a Master Page named “MP”
4. Publish the page.
5. Navigate to Page Templates > Master
6. Click the Ellipsis menu of the page you published.
7. Make a Copy should be deactivated. 
8. Master Page with permissions or Master Page options should not be displayed.
9. Redo steps from 3 to 8 for Display Pages.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Review by lfbesada — APPROVED** [review]
LGTM :tada: 
:kissing:

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
