### PR TITLE
LPD-17378 Create the necessary tests

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
@victorg1991, I found several issues related to the date field. 

When I select a date and remove the minutes, the validator does not consider this format as an error. 

https://github.com/liferay-echo/liferay-portal/assets/9701095/f02e26f3-4c12-49f6-b7a7-f4385835cbfb

And another thing is that when there is an invalid date and errors are displayed, when that date is corrected the above error summary is still displayed.

https://github.com/liferay-echo/liferay-portal/assets/9701095/2b52ec0e-98b2-42d5-b039-ff5d0a58914a

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward:force

**Pull request closed without merging**
