### PR TITLE
[TS] LPS-139647

### PR DESCRIPTION
**Pull request by dacousalr**
Motivation
=======
This PR solves https://issues.liferay.com/browse/LPS-139647 by implementing a missing upgrade that cleans the leftovers of LPS-138565.

Proposed Solution
========
The proposed solution is the creation of an upgrade step which cleans the orphan page template structures and layout page template structure rel entities.

This solution has taken into account the special case of Oracle databases and its limit of 1000 items within an IN clause.

Steps to Verify
========
1. Startup master without this solution
2. Execute the following script:
```
import com.liferay.portal.kernel.model.Group;
import com.liferay.portal.kernel.model.Layout;
import com.liferay.portal.kernel.model.LayoutConstants;
import com.liferay.portal.kernel.model.LayoutTypePortlet;
import com.liferay.portal.kernel.service.GroupLocalServiceUtil;
import com.liferay.portal.kernel.service.LayoutLocalServiceUtil;
import com.liferay.layout.page.template.service.LayoutPageTemplateStructureLocalServiceUtil;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.ServiceContextFactory;
import com.liferay.portal.util.PropsValues;

String siteName = "Guest";

try {
	ServiceContext serviceContext = ServiceContextFactory.getInstance(
		actionRequest);

	long userId = serviceContext.getUserId();

	long companyId = serviceContext.getCompanyId();

	Group group = GroupLocalServiceUtil.fetchGroup(companyId, siteName);

	long groupId = group.getGroupId();

	String layoutTemplateId = PropsValues.DEFAULT_LAYOUT_TEMPLATE_ID;

	for (int i = 0 ; i < 1005; i++) {
		Layout layout = LayoutLocalServiceUtil.addLayout(
		    userId, groupId, false, 0, "test_" + i, "",
		    "", LayoutConstants.TYPE_PORTLET, false, "",
		    serviceContext);

		LayoutTypePortlet layoutTypePortlet =
		    (LayoutTypePortlet)layout.getLayoutType();

		layoutTypePortlet.setLayoutTemplateId(
		    userId, layoutTemplateId);

		LayoutLocalServiceUtil.updateLayout(
		    groupId, false, layout.getLayoutId(),
		    layout.getTypeSettings());

		Layout layoutWithDraftStatus = LayoutLocalServiceUtil.addLayout(
		    userId, groupId, false, 0, "test2_" + i, "",
		    "", LayoutConstants.TYPE_PORTLET, false, "",
		    serviceContext);

		layoutTypePortlet = (LayoutTypePortlet)layoutWithDraftStatus.getLayoutType();

		layoutTypePortlet.setLayoutTemplateId(
		    userId, layoutTemplateId);

		LayoutLocalServiceUtil.updateLayout(
		    groupId, false, layoutWithDraftStatus.getLayoutId(),
		    layout.getTypeSettings());
		
		LayoutLocalServiceUtil.updateStatus(
		    userId, layoutWithDraftStatus.getPlid(), 2, serviceContext);
		
		LayoutPageTemplateStructureLocalServiceUtil.addLayoutPageTemplateStructure(
		    userId, groupId, layout.getPlid(), com.liferay.segments.constants.SegmentsExperienceConstants.ID_DEFAULT, "data_", serviceContext);

		LayoutPageTemplateStructureLocalServiceUtil.addLayoutPageTemplateStructure(
			userId, groupId, layoutWithDraftStatus.getPlid(), com.liferay.segments.constants.SegmentsExperienceConstants.ID_DEFAULT, "data2_", serviceContext);
	}

}
catch (Exception e) {
	println("Script failed: " + e);
}
```
3. Stop the server
4. Start the server.
5. Deploy the module Layout Page Template Service with the modifications contained in this PR
6. Wait for the end of the upgrade process
7. Check LayoutPageTemplateStructure and LayoutPageTemplateStructureRel tables

Expected behavior: There are no records pointing to Layouts of type Portlet

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dacousalr** [comment]
The latest unique failure does not seem related to this PR:

> LIFERAY_ERROR: HHH000315: Exception executing batch [java.sql.BatchUpdateException: Duplicate entry 'com.liferay.client.extension.model.ClientExtensionEntry' for key 'IX_B27A301F'], SQL: insert into ClassName_ (mvccVersion, value, classNameId) values (?, ?, ?)

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/9720

**Pull request closed without merging**
