### PR TITLE
LPS-99212 Only count DDMTemplates of JournalArticles when populating last publish date counts in the Journal context

### PR DESCRIPTION
**Pull request by devpedrotavares**
## Motivation
Fix the bug reported in [LPS-99212](https://liferay.atlassian.net/browse/LPS-99212) where DDMTemplates of Dynamic Data Lists are counted under Web Content in the staging summary.

## Proposed Solution
Creates a new method for populating DDMTemplate "last publish date" counts that considers just the DDMTemplates that are related to JournalArticle.

#### Enabling Dynamic Data Lists
- Open applications menu
- Go to Control panel > Configuration > Instance settings > Feature flags > Deprecation
- Enable feature flag for Dynamic Data Lists

#### Configuring staging
- Add the following lines to `portal-ext.properties`:

```
tunnel.servlet.hosts.allowed=127.0.0.1,SERVER_IP
axis.servlet.hosts.allowed=127.0.0.1,SERVER_IP
tunneling.servlet.shared.secret=6162636465666768696a6b6c6d6e6f70
tunneling.servlet.shared.secret.hex=true
```

- Go to Control Panel > Sites 
- Create a new blank site
- On the created site, go to Product Menu > Publishing > Staging
- Choose 'Remote Live'
- Use 127.0.0.1 for 'Remote Host/IP'
- Use 8080 for 'Remote Port'
- Fill in the other site's ID on 'Remote Site ID'
- Check 'Dynamic Data Lists' under 'Staged Content'
- Save it

#### Reproducing the bug
- On the created staging site, go to Product Menu > Content & Data > Dynamic Data Lists
- Click on the kebab menu at the top right corner and then click on 'Manage Data Definitions'
- Create a Data Definition
- On the created Data Definition, click on the kebab icon and then on 'Manage Templates'
- Add a new Form Template
- Go to Product Menu > Staging 
- Click on 'New' to add a new publish process
- Under 'Content', select 'From Last Publish Date' and click on 'Refresh Counts'

**Expected behavior:** Template for DDL is not show in any counts
**Actual behavior:** Template for DDL is shown under Web Content

## References to existing code
I believe the created method follows a somewhat similar approach to what is being done [here](https://github.com/liferay/liferay-portal/blob/8d7a2491ee556c16f336c3f8cfcf4e3d212d1a2d/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/internal/exportimport/data/handler/JournalPortletDataHandler.java#L758)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
Hi @devpedrotavares 
Thanks for the fix!
I am trying to review this PR but with the steps indicated in the ticket it is impossible to verify that the bug is in the current master and therefore I can't verify your solution.
By now, I have checked that DDL is deprecated so in the current master enable an FF is required to access. Also, I can't create a template because the DDL Template editor seems to be broken.
Can you please adjust the ticket description so I can reproduce the bug in the current master?
Thanks in advance!

**Comment by devpedrotavares** [comment]
Hi @lfbesada ,
I have updated this PR's description with the steps to verify. Please let me know if I've missed something.
Thank you!

**Comment by lfbesada** [comment]
Hi @devpedrotavares 

Thank you very much for updating the steps, that allowed me to find an easier way to reproduce it:

1. Enable DDL
2. Create a new site
3. Activate local staging for that site, check the Dynamic Data List option before activating it
4. On the created staging site, go to Product Menu > Content & Data > Dynamic Data Lists
5. Click on the kebab menu at the top right corner and then click on 'Manage Data Definitions'
6. Create a Data Definition
7. On the created Data Definition, click on the kebab icon and then on 'Manage Templates'
8. Add a new Display Template, since it is not possible to edit the template and it cannot be saved empty, follow these steps:
- Create a script.ftl file with the content <h1>Test</h1>
- Upload that file as a script when creating the template
9. Create a new web content template 
10. Create a new export process

Expected: Only one web content template should appear in the web content summary
Obtained: Two web content templates appear in the web content summary

Are you okay if I change the ticket to put these reproduction steps?

But the underlying problem is not that it appears in the summary but that it is published. You can check it by inspecting the DDMTemplate table in DB before and after the publishing process. 
- If unchecked the web content templates no template is published, either the web content template as the DDL display template
- If it is checked both templates are published.

So I think we can add these steps

11. Uncheck  the web content templates to exclude them from publish process
12. Publish to live

Expected: DDL display template should published
Obtained: DDL template is not published to live

I have tested your fix and it works correctly to prevent that template from being considered in the summary as a web content template, but it is still publishing to live DDL templates and it shouldn't.

I think that is what we need to solve in addition to what you have solved in the summary, I am working on adding changes to your fix to solve it.

Thank you for your patience

Regards

**Comment by lfbesada** [comment]
see:  https://github.com/liferay-echo/liferay-portal/pull/14787

**Comment by devpedrotavares** [comment]
I see, that makes sense. Thank you for your help, @lfbesada !

**Pull request closed without merging**
