### PR TITLE
LPS-105422 - FriendlyUrl resolver to calculate the alternate urls using the current logic for asset publisher

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Comes from https://github.com/liferay-echo/liferay-portal/pull/8821 

Based on https://github.com/liferay-echo/liferay-portal/pull/8821#issuecomment-1180059576 replaced LPS-150368 with the correct one, LPS-105422

/cc @lfbesada

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by lfbesada — CHANGES_REQUESTED** [review]
Hi @georgel-pop-lr 
Hello,
Thanks for the fix!
I have been testing the solution on my local env in four scenarios:
1. Company's default site **without** a virtual host for public pages. 👍 
2. Company's default site **with** a virtual host for public pages. 👍 
3. Company's non-default site **without** a virtual host for public pages. 👎 
4. Company's non-default site **with** a virtual host for public pages. 👍 

In my tests, this fix doesn't work properly in the third scenario. Could you please double-check?
Thanks

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr Hello, Thanks for the fix! I have been testing the solution on my local env in four scenarios:
> 
> 1. Company's default site **without** a virtual host for public pages. +1
> 2. Company's default site **with** a virtual host for public pages. +1
> 3. Company's non-default site **without** a virtual host for public pages. -1
> 4. Company's non-default site **with** a virtual host for public pages. +1
> 
> In my tests, this fix doesn't work properly in the third scenario. Could you please double-check? Thanks

Hi @lfbesada, 

Thanks for your intensive looking at this issue. I force pushed here the changes. 

Would you prefer for me to send a new pull, or we continue with this one?

Regards.

**Review by lfbesada — APPROVED** [review]
Thanks for the fix! ❤️  LGTM

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
Hi @georgel-pop-lr 
I am afraid the test failures are related to this pull request's changes.
Could you please fix those tests?
Thanks a lot!

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr I am afraid the test failures are related to this pull request's changes. Could you please fix those tests? Thanks a lot!

Hi @lfbesada,

Yes, we will check them.

Regards.

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
LGTM! Thanks!

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
