### PR TITLE
LPS-138404 Get parameters from original HttpServletRequest

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
easy, gg

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The failure is unrelated to this PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/106681

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
