### PR TITLE
LPS-168835 Replace liferay-ui:icon with clay:icon in fragment-web

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
[Link to ticket](https://issues.liferay.com/browse/LPS-168835)

## Test Scenario 1 - Contributed  Fragment Set 

* Navigate to Design - > Fragments.
* Check the lock icon in the fragment sets by default.
Screen Shot 2023-01-30 at 09 13 44

## Test Scenario 2 - Inherited  Fragment Set 

* Go to Global site and navigate to Design - > Fragments.
* Create a new Fragment Collection (set).
* Crate a new Site and go to Design - > Fragments.
* Check the icon for global fragments.
image

## Test Scenario 3 - System  Fragment Set 

* Download the .zip in the ticket.
* Place it in the deploy folder of your bundle.
* Refresh the portal for the new site (the one you created for the second scenario) and navigate to Design - > Fragments.
* Check the new Default Fragment set "coleccion 1" with the lock icon.

image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:relevant

**Review by sandrodw3 — COMMENTED** [review]
This is cool! I only left a little suggestion 😄

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:forward 🚀

**Pull request closed without merging**
