### PR TITLE
LPS-191769 Redirect to the blocked page view when a user tries to access to a locked display page template or collection page

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-191769

Dear reviewer 👋

Thanks in advance for your review ❤️

This PR implements the browse to the blocked page view when the user tries to access a locked draft of types display page template and collection page.

The lock acquire and release process is not implemented yet so we need to use scripts to lock and unlock the draft.

In addition, to be able to test it, the feature flag must be enabled:
feature.flag.LPS-180328=true

These scripts are useful to test this PR:

Script to lock a draft by a user
[LockLayout.txt](https://github.com/liferay-echo/liferay-portal/files/12240677/LockLayout.txt)

Script to see the status of a draft (locked/unlocked) with respect to all the users of the company
[isUnlockedLayout.txt](https://github.com/liferay-echo/liferay-portal/files/12240681/isUnlockedLayout.txt)

Script to unlock a draft
[UnlockLayout.txt](https://github.com/liferay-echo/liferay-portal/files/12240682/UnlockLayout.txt)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
