### PR TITLE
[TS] LPS-174851 - multiple wc structure fields are missing in information templates

### PR DESCRIPTION
**Pull request by wanderlast**
Hi Team Echo!

I'm sending this PR to address a client reported issue here: https://issues.liferay.com/browse/LPP-47761

In it they reported that they were unable to map the upload field in an information template, despite it being available for use in web content templates. I've added therefore the fields available for WC structures. Looking through the documentation available, I didn't find any reason for these fields to be excluded, but please let me know if this is something that is intentional and I'll pass it on to the client. Thanks!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @wanderlast,

Could you please send this one to BPM Team?

Thanks!!

**Comment by wanderlast** [comment]
Sorry about that! Will do.

**Pull request closed without merging**
