### PR TITLE
LPS-149718 - Investigate if limitation that causes loss of reference from page to fragment in global when importing LAR can be removed

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @jkappler @lfbesada

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
@dacousalr @bakayattila

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
