### PR TITLE
LPS-131407 Reorder selection options to prioritize collection

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:stop

**Comment by ealonso** [comment]
Hey @victorg1991,

It is not only changing the order, it is always changing the default value, in this case the default value should be AssetPublisherSelectionStyleConstants.TYPE_ASSET_LIST instead of AssetPublisherSelectionStyleConstants.TYPE_DYNAMIC

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @victorg1991, there is a regression.
The Asset Publisher should be always visible to users.
**Step to reproduce**

1. Add an Asset Publisher to widget page

**Expected Results**
image

**Actual Results**
image
Additionally, add an asset like web content
The web content is not shown in Asset Publisher.

**Comment by victorg1991** [comment]
Hey @Tim-Cao We are changing that. We want to promote the usage of collections. What this pr does is to to change the behaviour, before this, the default behaviour was dynamic, now it is collection. If there are some test that required the old behaviour, we need to open the configuration of the portlet and configure it back to dynamic.

Could you update the affected tests? :)

**Comment by Tim-Cao** [comment]
I will try my best. @victorg1991

**Comment by Tim-Cao** [comment]
Hi @victorg1991
There are more than hundreds of usages are required to update in Poshi. If add UI steps, the running time will have a jump increase. Could we ask dev to add a remote service to update the value of PortletPreferences?

**Comment by Tim-Cao** [comment]
@victorg1991 See https://github.com/liferay-echo/liferay-portal/pull/7356

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
