### PR TITLE
[TS] LPS-128928 AssetCategory association may be lost when content editor has limited permissions

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,
[LPS-128928](https://issues.liferay.com/browse/LPS-128928)
I made this PR to follow up on https://github.com/liferay-echo/liferay-portal/pull/4223

I decided to get the categories from the LocalService to get all the categories regardless of permission, than I provide the categories, where the user don't have permission as restrictedItems.

These restricted Items later are displayed in the asset-category selector as an additional field.
I also implemented the functionality to be able to remove these restricted items.

I think the UX requires some additional improvement to better reflect the fact, these items cannot be re-added, once they are removed by the user. Something like adding a warning color on the restricted items. Unfortunately I did not see any corresponding Lexicon Documentation with a similar scenario, neither I managed to add any css change to the rendered items trough `elementClasses`, so I decided to just send the solution as is to see if it is a valid solution at all.

Please review my changes,

Thanks

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
Hi @NemethNorbert
The semantic versioning test failure seems to be related with the changes.
Can you run baseline and resend?
Thanks!

**Comment by NemethNorbert** [comment]
https://github.com/liferay-echo/liferay-portal/pull/6486

**Pull request closed without merging**
