### PR TITLE
LPS-146965 Update test macro

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:stop

Stopping due to ci-infrastructure bug

**Pull request closed without merging**
