### PR TITLE
LPS-137502 Renames some widgets and a fragment

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-137502

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
@david-gutierrez-mesa the cause of the failure of the tests is that the "Navigation Menu" widget has been renamed to "Menu Display Widget" so those POSHI tests should be adapted. Could you please have a look at it?

Thanks!!!

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/6941

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
