### PR TITLE
LPS-150358 As a developer I would like to have an API to retrieve the resources in a Fragment Collection

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-150358 Adds new method to retrieve the resources of a collection externally
- LPS-150358 Build service
- LPS-150358 Add test

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
