### PR TITLE
LPS-159979 Favorites backend side

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-159979

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:reevaluate:1267401_4736

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1267401_4771

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1267401_4788

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Seen directly to https://github.com/brianchandotcom/liferay-portal/pull/122494

**Comment by david-gutierrez-mesa** [comment]
ci:close

**Pull request closed without merging**
