### PR TITLE
LPS-127642 [Bug: Experiences] Fragments and Widgets sidebar in the Page Editor disappear when editing an experience

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description of the bug**

Fragments and widgets sidebar panel is NOT available when editing an experience. The behavior is similar to an experience with an AB Test (`hasLockedSegmentsExperiment`) but in this case, the experience doesn't have any experiment running.

**How to test it**

- Create a page
- Create an experience (exp1)
- Select the exp1 in the experience list
- Edit the experience name (exp1 edited)

**Solution**

On experience edition, we were only taking the priority of the experience and merging it with the updated information. To fix this bug, I merged the whole experience with the updated experiences:

```
[experience.segmentsExperienceId]: {
	...experience,
	...updatedExperience,
}
```

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
LGTM thanks 👏

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
