### PR TITLE
LPS-181468 Expand nodes when they are active

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
This is a follow-up of https://github.com/liferay-echo/liferay-portal/pull/11712
When the user select a node in the page editor and activate it, the node should expand in the structure tree to that it is visible.
[Link to task](https://issues.liferay.com/browse/LPS-151678)
[Link to subtask](https://issues.liferay.com/browse/LPS-181468)

Proposed Solution
========
We control what nodes are expanded by passing the props expandedKeys and onExpandedChange and keeping the nodes currently expended in the component state.

Steps to Verify:
----------------

1. Set feature.flag.LPS-151678=true
2. Go to home page and click on edit
3. Click on any element of the page layout and check the the structure tree appears with the node element selected expanded.
4. Try expanding and closing other nodes and clicking in the page editor and check that everything works fine.
5. Set feature.flag.LPS-151678=false, restart the server and check the everything works as before

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
Hi @victorg1991, have a look at the changes I've made.

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:forward

**Review by victorg1991 — APPROVED** [review]

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
