### PR TITLE
LPS-194233 Get collection warning from backend

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
@ealonso I updated the backend changing the condition of the warning message:

```
  And this fragment is mapped to a Dynamic Collection
  Or it is configured with the Pagination as None
  And (
    the check Display All Collection Items is clicked
    And the jaja es broma Items to Display is above 200
  )
```

**Comment by p2kmgcl** [comment]
@sandrodw3 I updated the frontend with the changes we talked about:
- Warning text weight is now normal.
- Checkbox text is always black.

And I added an extra change:
- The help text is more or less the same than the warning message, so I am hiding it when the warning is being shown.

**Comment by ealonso** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/13430

**Pull request closed without merging**
