### PR TITLE
LPD-2060 The content page template is broken after upgrade from 7.1

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-2060

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:upgrade

**Comment by lfbesada** [comment]
I have added the OnHold tag to carefully review the upgrade tests before forwarding

**Comment by lfbesada** [comment]
cc: @ealonso

**Comment by lfbesada** [comment]
ci:report:2532677327

**Comment by lfbesada** [comment]
ci:report:2532722341

**Comment by lfbesada** [comment]
ci:reevaluate:1407401_8530

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:report:2533129525

**Comment by ealonso** [comment]
ci:forward:force

**Comment by achaparro** [comment]
ci:test:upgrade-performance

**Pull request closed without merging**
