### PR TITLE
LPS-84667-1 Problem creating AssetCategories through API when site default locale is different from instance's default locale

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-84667

Previous PR: https://github.com/liferay-echo/liferay-portal/pull/728

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Please see: https://github.com/liferay-echo/liferay-portal/pull/4901

**Pull request closed without merging**
