### PR TITLE
[TS] LPS-114855 At LAR/Staging import time, we can have a webcontent with expire or scheduled status, version != 1.0 but without AssetEntry, so it is necessary to check if it already exists.

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-114855

I have extracted addDraftAssetEntry calculation to a new method in order to make code more clear.

The bug is solved with last commit https://github.com/liferay-echo/liferay-portal/pull/885/commits/c417f2c510659af837034763195d601cab171c72 just checking if AssetEntry exists when version != 1.0

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Rebased and forwarded here: https://github.com/liferay-echo/liferay-portal/pull/926

**Pull request closed without merging**
