### PR TITLE
LPS-153903 Add Favicon to a page

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-154307
https://issues.liferay.com/browse/LPS-154505
https://issues.liferay.com/browse/LPS-154398
https://issues.liferay.com/browse/LPS-154655 
https://issues.liferay.com/browse/LPS-154656

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
