### PR TITLE
LPS-133571 Better control of redirects

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Rebase then resent
https://github.com/liferay-echo/liferay-portal/pull/4919

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
