### PR TITLE
LPS-122204 Edit the content present on the page using the most appropriate editing option

### PR DESCRIPTION
**Pull request by veroglez**
cc @jkappler

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
@veroglez, @p2kmgcl, please check https://github.com/liferay-echo/liferay-portal/pull/4769

**Pull request closed without merging**
