### PR TITLE
LPS-130936 Also trim when updating

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@brianikim, @ealonso

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @jkappler, cannot add a site based on Minium initializer.
1. Add a site based on Minium
2. Type name then Click Save

Expected Results:
The new site is created successfully.

Actual Results:
An unexpected error shown. Additionally, the following error thrown in server console
```
2021-05-07 05:06:45.668 ERROR [http-nio-8080-exec-2][MiniumSiteInitializer:267] java.lang.UnsupportedOperationException
java.lang.UnsupportedOperationException: null
        at java.util.Collections$SingletonMap.replace(Collections.java:4937) ~[?:1.8.0_221]
        at com.liferay.portal.service.impl.GroupLocalServiceImpl._normalizeGroupNames(GroupLocalServiceImpl.java:5210) ~[portal-impl.jar:?]
        at com.liferay.portal.service.impl.GroupLocalServiceImpl.addGroup(GroupLocalServiceImpl.java:275) ~[portal-impl.jar:?]
        at com.liferay.portal.service.impl.GroupLocalServiceImpl.addGroup(GroupLocalServiceImpl.java:493) ~[portal-impl.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
        at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
```

**Comment by jkappler** [comment]
thanks @Tim-Cao!

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
