### PR TITLE
LPS-165509 Experience selected in view mode is incorrect

### PR DESCRIPTION
**Pull request by jkappler**
Motivation
=======
[Link to ticket](https://issues.liferay.com/browse/LPS-165509)

Bug fixing: The selected experience in view mode after editing that page  where an experience is created but the page is not saved is not correct.

Proposed Solution
========
Check if the experience that is in the parameter is in fact an experience of the page, if not return the default one.

Steps to Verify
========

1. Go to Home page, edit the page and create one experience
2. Create a new page from the Home page clicking in the '+' icon in the menu display element
3. Create a new experience in the new page
4. Click in the '<' (back) icon to return to the home page

**Actual result:**
See the home page and experience selected in the experience selector is the experience created for the new page.

**Expected:**
See the home page and experience selected in the experience selector is the active experience for the home page.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
Found another bug that needs solving

**Comment by jkappler** [comment]
@YurenaC, the changes fixed the issue, but if you click on the pencil to edit the page, it will show a different experience. I'll push the commit once github normalizes

**Comment by jkappler** [comment]
ci:forward

**Review by lfbesada — APPROVED** [review]
LGTM ❤️

**Comment by jkappler** [comment]
> LGTM ❤️

:trollface:

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @jkappler, there is a regression issue. Cannot switch experience at view mode.
**Step to reproduce**

1. Add a content page
2. Add a new experience for Anyone
3. Publish the content page
4. Navigate to the content page
5. Try to switch to the new experience

*Actual Results*
The Default one is still shown in selector

**Comment by jkappler** [comment]
Thanks @Tim-Cao!

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @jkappler, the second regression issue is The content of new experience is not shown at view mode after switch to new experience.
**Step to reproduce**

1. Add a content page
2. Add a Heading to page
3. Add a new experience for Anyone
4. Add a Button below the Heading
5. Publish the page
6. Navigate to the content page at view mode
7. Switch to the new experience 

**Expected Results**
Both fragments should be shown.

**Actual Results**
Only the Heading is shown.

**Comment by jkappler** [comment]
@YurenaC, can you please help me taking a look at this ❤️?

**Comment by YurenaC** [comment]
Sure thing @jkappler

**Comment by jkappler** [comment]
continued here.... https://github.com/liferay-echo/liferay-portal/pull/11606

**Pull request closed without merging**
