### PR TITLE
[7.4.x-only] LPS-116774 & LPS-104151 & LPS-109123 Enable Data Engine by default on Web Content

### PR DESCRIPTION
**Pull request by liulukiwi**
forward

cc @ealonso @david-gutierrez-mesa

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:stop

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
