### PR TITLE
LPS-119214 [Info Framework] Override equals and hashCode methods in InfoItemReference class

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

Override equals and hashCode methods in InfoItemReference class, as this class is defined in the API and the developer maybe will need to compare standalone objects or uniquely identify them in a collection.

**Proposed solution**

Override method equals in InfoItemIdentifier so it can be used in the equals method of InfoItemReference.

**How to test it**

Unit tests has been provided with this pull.

### CODE REVIEW

**Comment by cgoncas** [comment]
Hey @ jkappler and @JorgeFerrer!!

If you could take a look to this pull, would be awesome :)

Thanks in advance

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Thanks @cgoncas!

**Comment by JorgeFerrer** [comment]
¡Gracias Cristina! Me ha parecido una pasada esta pull y todos sus tests 👏 👏 
Gracias Jürgen por revisarla y pasarla.

**Pull request closed without merging**
