### PR TITLE
LPS-188466 importing fragments with global scoped sitenavmenu fails

### PR DESCRIPTION
**Pull request by gergelyszalay**
moved this PR https://github.com/liferay/liferay-portal/pull/5514 to the echo team, as per the request of @ealonso.
Thanks

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Hi @gergelyszalay 
Thanks for the fix, it works great 👏 
LGTM 🎉 
Regards

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1397401_5692

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
