### PR TITLE
LPS-171583 Set the new configuration fields in a different fieldSet 

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-171583

This PR is only related to LPS-171583.
The LPS-171144's commits are needed for this but are already reviewed and waiting for the Brian review [here](https://github.com/brianchandotcom/liferay-portal/pull/127975)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1297401_5850

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128018

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
