### PR TITLE
LPD-27946 & LPD-27948 Exporting and Importing Layouts should also include their StyleBookEntry and LayoutPageTemplateEntry

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
@balazssk 

Could you please double check tests failures?

[modules-integration-mysql57-jdk8/0/0](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1020519//consoleText)
[com.liferay.layout.admin.web.internal.exportimport.data.handler.test.LayoutStagedModelDataHandlerTest](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1020519/testReport/com.liferay.layout.admin.web.internal.exportimport.data.handler.test/LayoutStagedModelDataHandlerTest) - [Failed 0 of last 24](https://testray.liferay.com/home/-/testray/case_results/2573625668/history)
[modules-integration-mysql57-jdk8/0/3](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1126798//consoleText)
[com.liferay.layout.page.template.internal.exportimport.data.handler.test.LayoutPageTemplateEntryStagedModelDataHandlerTest](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/1126798/testReport/com.liferay.layout.page.template.internal.exportimport.data.handler.test/LayoutPageTemplateEntryStagedModelDataHandlerTest) - [Failed 0 of last 24](https://testray.liferay.com/home/-/testray/case_results/2573625649/history)
[modules-integration-mysql57-jdk8/0/5](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/973047//consoleText)
[com.liferay.layout.exportimport.service.test.ExportImportLocalServiceTest](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/973047/testReport/com.liferay.layout.exportimport.service.test/ExportImportLocalServiceTest) - [Failed 0 of last 23](https://testray.liferay.com/home/-/testray/case_results/2573625724/history)

Thanks!!

**Comment by balazssk** [comment]
Checking

**Comment by ealonso** [comment]
@balazssk Thanks you very much for the fixes, I've already incorporate your commits

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
