### PR TITLE
LPS-129702 - Remove usage of Liferay.Util.selectEntityHandler in trash

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by jonmak08** [comment]
ci:test:relevant

**Pull request closed without merging**
