### PR TITLE
LPS-180470 Change inputs components to functional components

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://issues.liferay.com/browse/LPS-180470)

## Steps 

1. Go to Product Menu > People > Segments
2. Create a Segment
3. Add the following inputs for each case:

**SelectEntityInput.js**
Users Section > Site
entity

**StringInput.js**
Users Section > Email Address 
Screenshot 2023-04-11 at 15 38 50

**BooleanInput.js**
Session section > Sign in
boolean

**CollectionInput.js**
Session Section > Coockies
collection

**DecimalInput.js**
Session Section > Device Screen Resolution Height
decimal

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
Hey @DiegoHu97, it seems that frontend tests are failing, could you please take a look?

**Comment by DiegoHu97** [comment]
@sandrodw3  Udpated 😄

**Comment by sandrodw3** [comment]
Hey @DiegoHu97 LGTM 😄 nice work! Just a small improvement, could we use `ClayInput` in the components that are rendering `input`? Or is there any reason why we can't?

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
@sandrodw3 Updated!

**Comment by sandrodw3** [comment]
Closing this as it has been merged in https://github.com/liferay-echo/liferay-portal/pull/11735 to solve conflicts

**Pull request closed without merging**
