### PR TITLE
LPS-190842 Remove no needed translations in labels and titles for clay:button, clay:link, clay:label and clay:checkbox in Echo modules

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/PS-LPS-190842)

## Proposed solution

Remove all no needed translations for clay:button, clay:link, clay:label and clay:checkbox in Echo Modules

## Notes

This changes don't modify the behaviours 

## Test Scenario 1

1. Go to the Home Page
2. Start editing the Home Page
3. Check this buttons tittles:

Pasted Graphic

## Test Scenario 2

1. Go to Instance Settings > Segments 
2. Disable Segmentation
3. Create a new Manual collection
4. Check the link in the warning

Pasted Graphic 1

## Test Scenario 3

1. Create a new Manual collection
2. Create a Widget Page and add an Asset Publisher
3. Select a collection
4. Check the label that says “no variations”

Pasted Graphic 2

## Test Scenario 4

1. Go to Instance Settings > Segments > Segments Service
2. Look at the checkbox for Enable Segmentation.

image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:forward

**Comment by alessandromalves** [comment]
The failures are not related to this PR [(comparison with acceptance routine here)](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1693334678599&testrayRunIdA=2414574057&testrayRunIdB=2414721336). See https://github.com/brianchandotcom/liferay-portal/pull/139914

**Pull request closed without merging**
