### PR TITLE
[TS] LPS-131903

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-131903

The solution prevents the edit icon from appearing altogether, and I don't believe there is any lost functionality by not showing this page.  The only possibility is Experiences are no longer selectable/createable, but since the layout is locked, there isn't anything new the user can create on the new experiences.  Further, Experiences cannot be created from the site template, so it's not like we are unable to select relevant Experiences now.

Lastly, I checked the fragment comment feature, and it seems comments do not propagate from the site template, so this also isn't an issue.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:stop

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @ChrisKian,

I've send the first part of the fix in a separated pr https://github.com/liferay-echo/liferay-portal/pull/4522, since the other part is related with permissions and site templates.

For the second part, you should talk with the Staging Team (they are the owners of site templates) or better open a new PTR, since you are changing the behavior of the product hiding the permissions and I don't know if it is going to have any other consequences or if the permissions are there on purpose.

Regards,
Eudaldo.

**Pull request closed without merging**
