### PR TITLE
LPS-147972 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-147972

@victorg1991

The page is frozen after select page in ckeditor

**Steps to reproduce**

1. Add a web content in default site
2. Type text in content field
3. Select the text
4. Click the link icon
5. Browser Server > Pages
6. Select the page

**Expected Results:**
The page is selected.

**Actual Results:**
The page is frozen.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
Btw, would you mind run **ci:test:acceptance-functional** after you have all fix?
@victorg1991

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by victorg1991** [comment]
ci:test:acceptance-functional

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional

**Comment by victorg1991** [comment]
resent here: https://github.com/liferay-echo/liferay-portal/pull/8180

**Pull request closed without merging**
