### PR TITLE
LPS-147705 Show modal when deleting a navigation menu

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Probably a bunch of poshi test to update :(

**Comment by ozysouza** [comment]
Hi @victorg1991, please see https://github.com/liferay-echo/liferay-portal/pull/8001

**Comment by ozysouza** [comment]
ci:close

**Pull request closed without merging**
