### PR TITLE
[TS] LPS-135330 Additional commit: Add test case

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @liferay-echo ,

I'm adding an integration test for [LPS-135330](https://issues.liferay.com/browse/LPS-135330), as requested on previous pull: https://github.com/brianchandotcom/liferay-portal/pull/105178#issuecomment-894179055

Thanks,
Vendel

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
