### PR TITLE
LPS-200753, LPS-200958, LPS-200981 & LPS-200990: Replace AUI() usages 

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket LPS-200753](https://liferay.atlassian.net/browse/LPS-200753)
[Link to ticket LPS-200958](https://liferay.atlassian.net/browse/LPS-200958)
[Link to ticket LPS-200981](https://liferay.atlassian.net/browse/LPS-200981)
[Link to ticket LPS-200990](https://liferay.atlassian.net/browse/LPS-200990)

## Steps 

**Case 1: commerce-notification-web**

- Go to Control Menu > Commerce > Channels 
- Create a Channel > In the channel edition > Go to Notification Templates tab
- Create a Notification Template and fill the following inputs: Name, Description, From Address, From Name, CC and BCC
- Then select a Type in Type input > notice the window URL changes but the inputs values remain the same as before

**NOTE: there is a bug, the input From Name does not save the value, it is unrelated with my changes, I have reported the bug already**

https://github.com/liferay-echo/liferay-portal/assets/91208451/df208c35-631e-4695-9685-d218203905fc

**Case 2: commerce-cart-taglib**

- Go to Control Panel > Sites > Create a Speedwell site 
- In Speedwell site > Go to Catalog page and add an item 
- Go to My Cart page > In Quantity input, change the value and click update button
- See the total price list changes 

https://github.com/liferay-echo/liferay-portal/assets/91208451/012838e6-2b94-4d3e-9b94-8e94b8f67ae9

**Case 3: commerce-order-content-web**
**NOTE: I know where is the content, but I have not been able to show it in the UI, but the changes are easy, so it should work as before, I think there is no need to test it**

- Go to Control Panel > Sites > Create a Minium site 
- Go to the Minium Home page > add an item to the cart
- In the left navbar > Click on pending orders
- View the order that is pending
- Below is the comments div hidden called _id="<portlet:namespace />transitionComments"_

**Case 4: commerce-pricing-web**

**Case 4.1: details.jsp**
- Go to Control Panel > Sites > Create a Minium site 
- Go to Control Menu > Commerce > Pricing > Discounts 
- Create a discount > In Type if you change the input value, the inputs bellow should change
- In Apply To, you have to change it's value, save the discount and in the discounts view in target column should appear the value

https://github.com/liferay-echo/liferay-portal/assets/91208451/ac906c86-5af9-482e-bd96-c715df3de23a

**Case 4.2: details.jsp**
This case I have not been able to find it, but the code is the same as **details.jsp** so it should work as well, I think it's not needed to test it

**Case 5: commerce-checkout-web**
- Go to Control Panel > Sites > Create a Minium site
- In the Home page > upper side > click on Account > create a new account 
- In the left nav bar > select Catalog
- Add some items to the cart
- In the left nav bar > click on Account Management > edit the account
- Go to Addresses and and an address
- In the left nav bar > click Pending Orders 
- View the pending order and click checkout 
- When clicking on "Add Address Line", address 2 and 3 inputs should appear 
- When changing "CHOOSE SHIPPING ADDRESS" input, if we choose an address it should fill the inputs and disable them, and if we choose Add a New Address, the inputs should enable and be reseted.

https://github.com/liferay-echo/liferay-portal/assets/91208451/5db07545-2be0-453d-82be-fb2da50ae53a

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Review by p2kmgcl — APPROVED** [review]

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
Sorry, I just noticed that commerce should review this before sending the PR

**Review by andrea-ale-sbarra — APPROVED** [review]
LGTM.
Thank you!

**Comment by DiegoHu97** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
