### PR TITLE
LPD-17669 Instead of deleting all fragments perform an update action

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-17669

@ealonso

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:upgrade

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by ealonso — APPROVED** [review]

**Comment by lfbesada** [comment]
ci:report:2542422646

**Comment by lfbesada** [comment]
At least this error is related to the UpgradeProcess added here:

`
Caused by: org.postgresql.util.PSQLException: ERROR: column "fragmententrylink" of relation "fragmententrylink" does not exist
  Position: 30
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676) ~[postgresql.jar:42.4.3]
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366) ~[postgresql.jar:42.4.3]
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356) ~[postgresql.jar:42.4.3]
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496) ~[postgresql.jar:42.4.3]
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413) ~[postgresql.jar:42.4.3]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333) ~[postgresql.jar:42.4.3]
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319) ~[postgresql.jar:42.4.3]
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295) ~[postgresql.jar:42.4.3]
	at org.postgresql.jdbc.PgStatement.executeUpdate(PgStatement.java:268) ~[postgresql.jar:42.4.3]
	at com.zaxxer.hikari.pool.ProxyStatement.executeUpdate(ProxyStatement.java:119) ~[hikaricp.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyStatement.executeUpdate(HikariProxyStatement.java) ~[hikaricp.jar:?]
	at com.liferay.portal.dao.db.BaseDB.runSQL(BaseDB.java:554) ~[portal-impl.jar:?]
	at com.liferay.portal.dao.db.BaseDB.runSQL(BaseDB.java:520) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.dao.db.BaseDBProcess.runSQL(BaseDBProcess.java:103) ~[portal-kernel.jar:?]
	at com.liferay.fragment.internal.upgrade.v2_10_3.FragmentEntryLinkUpgradeProcess.doUpgrade(FragmentEntryLinkUpgradeProcess.java:18) ~[?:?]
	at com.liferay.portal.kernel.upgrade.UpgradeProcess.lambda$upgrade$0(UpgradeProcess.java:122) ~[portal-kernel.jar:?]
	at com.liferay.portal.db.partition.util.DBPartitionUtil.forEachCompanyId(DBPartitionUtil.java:178) ~[portal-impl.jar:?]
	at com.liferay.portal.dao.db.BaseDB.process(BaseDB.java:465) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.dao.db.BaseDBProcess.process(BaseDBProcess.java:378) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:107) ~[portal-kernel.jar:?]`

See: https://testray.liferay.com/reports/production/logs/2024-02/test-1-39/test-portal-acceptance-pullrequest(master)/9504/functional-upgrade-tomcat90-postgresql153-jdk8/0/18/liferay-log.txt.gz?authuser=0

**Comment by lfbesada** [comment]
ci:report:2542434605

**Comment by lfbesada** [comment]
ci:test:upgrade

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:report:2542604464

**Comment by lfbesada** [comment]
ci:report:2542535442

**Comment by lfbesada** [comment]
ci:report:2542540501

**Comment by lfbesada** [comment]
At least this test failure seems to be related: https://testray.liferay.com/home/-/testray/case_results/2542536903

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:test:upgrade

**Comment by lfbesada** [comment]
ci:report:2543254332

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
