### PR TITLE
LPS-129677, LPS-132403, LPS-132684, LPS-134207, LPS-134897, LPS-135312 | master

### PR DESCRIPTION
**Pull request by veroglez**
**The last 4 commits have to be reviewed as they refer to this task https://issues.liferay.com/browse/LPS-129677**

https://issues.liferay.com/browse/LPS-129677
https://issues.liferay.com/browse/LPS-132403
https://issues.liferay.com/browse/LPS-132684
https://issues.liferay.com/browse/LPS-134207
https://issues.liferay.com/browse/LPS-134897
https://issues.liferay.com/browse/LPS-135312

This is only for master.

@Tim-Cao

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
Hi @veroglez and @victorg1991, the PR will cause this regression https://issues.liferay.com/browse/LPS-135294
If you would like to allow it in GA3, I could forward this PR to Brian.

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/5258

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
