### PR TITLE
LPS-205209 - Create Headless REST API for deleting a site

### PR DESCRIPTION
**Pull request by ruben-pulido**
https://liferay.atlassian.net/browse/LPS-205209 - Create Headless REST API for deleting a site

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@ruben-pulido 🚀

**Comment by jkappler** [comment]
@ruben-pulido, seems there are buildRest issues

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
