### PR TITLE
LPS-142377 Adds FF to enable multiple selections of categories on adding site navigation menu items

### PR DESCRIPTION
**Pull request by lfbesada**
Just adds the configuration, doesn't apply it.

https://issues.liferay.com/browse/LPS-142377

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1037401_9918

**Comment by jkappler** [comment]
Just started reviewing :)

**Pull request closed without merging**
