### PR TITLE
LPS-175810 Enable keyboard dnd

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Hi @BarbaraCabrera, LPS-176865 is not existed, can you check about it? thanks

**Comment by BarbaraCabrera** [comment]
> Hi @BarbaraCabrera, [LPS-176865](https://issues.liferay.com/browse/LPS-176865) is not existed, can you check about it? thanks

Hi @liulukiwi ! 
This LPS is from a subtask that existed before in a story that has now become a bug whose actual LPS is [LPS-175810](https://issues.liferay.com/browse/LPS-175810). I can't make changes because this PR is from @sandrodw3 and is not submitted from my repo, if he could modify it that would be great. Thanks for the feedback! 😄

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
Please resend @BarbaraCabrera @sandrodw3

**Pull request closed without merging**
