### PR TITLE
[TS] LPP-49065>LPS-185695 Display timing of duplicate message of friendly URL is strange when web content is added via widget

### PR DESCRIPTION
**Pull request by locpham97**
Hi Team
Please review this PR and leave your comment.
Thanks,
Loc
# Motivation
This PR is for fixing [LPS-185695](https://issues.liferay.com/browse/LPS-185695)
# Issue
The Asset Publisher widget does not have the Toast to display the warning from MultiSessionMessage. 
When sending the MultiSessionMessage, only the Web Content can receive it and display it. 
That is why when adding WC by Asset Publisher Widget, there is no warning until we access Web Content.
# Proposed Solution
Add the Toast to display a warning in the Asset Publisher which is similar to the Toast in Web Content. Then add the key to distinguish when the WC is created by Asset Publisher Widget or in the Web Content to display the warning in the correct time and place.
cc:@ces-quanhuynh

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ces-quanhuynh** [comment]
ci:test:sf

**Comment by ces-quanhuynh** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @locpham97 @ces-quanhuynh 
Thanks for your PR, and sorry for the delay in the review.
I'm working on a generic solution. My goal is to fix this bug and several others related to warning and success messages after performing operations with content on different types of pages.
I leave this PR open to reference the new PR here when I submit it.
Thank you for your patience, I hope to be able to send it soon.
Regards

**Comment by lfbesada** [comment]
See: https://github.com/liferay-echo/liferay-portal/pull/12380

**Pull request closed without merging**
