### PR TITLE
[7.4-only] LPS-121957 Migrate v2 usages of clay:vertical-card in asset-browser-web

### PR DESCRIPTION
**Pull request by julien**
**Original PR and review**: https://github.com/liferay-frontend/liferay-portal/pull/501

In this change, we replace <clay:vertical-card-v2 />(clay 2.x: Metal+soy) with
<clay:vertical-card /> (clay 3.x: React)

**Test plan**

- Fetch this branch
- Deploy the asset-browser-web and frontend-taglib-clay modules
- Navigate to  **Site Builder** > **Collections**
- Create a new collection
- When selecting an item, in the modal window, change the display style
to "Cards"

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
It looks great! 🥳

**Comment by veroglez** [comment]
ci:forward

**Pull request closed without merging**
