### PR TITLE
[TS] LPS-146461 | Can't order structures alphabetically when selecting 'More' during web content creation

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?

https://issues.liferay.com/browse/LPS-146461

Thank you!

------

I'm not sure if it's a bug but I think it would improve the overall consistency in to the portal. I also asked a question related to two other management toolbar here: https://liferay.slack.com/archives/CL9RTSZ52/p1643635823196989

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @bakayattila,

It is not going to work at all since the name for a structure is a xml in the database. Something like this:

```xml
<?xml version='1.0' encoding='UTF-8'?><root available-locales="en_US" default-locale="en_US"><Name language-id="en_US">Text structure</Name></root>
```

So, if you want to do that, we need to change the database model to have another entity with the localization, something like JournalArticleLocalization and we need to update the queries.

Could you please talk with bravo team about it? Since they are the owners of DDM APIs, and we are using it for journal structures.

Regards,
Eudaldo.

**Comment by ealonso** [comment]
Hey @bakayattila,

Also, Could you please create a PTR for it? we need to analyze other options , like getting all structures and order them.

Regards,
Eudaldo.

**Comment by bakayattila** [comment]
Hi  @ealonso,
I already created a PTR for the topic here: 
https://issues.liferay.com/browse/PTR-2856

**Pull request closed without merging**
