### PR TITLE
LRQA-57973 Quarantine Site Templates tests

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
cc: @jkappler @ruben-pulido

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
ci:stop

**Comment by ruben-pulido** [comment]
ci:stop

**Comment by ruben-pulido** [comment]
ci:close

**Comment by ruben-pulido** [comment]
Fixed wrong LPS number in commit messages here: https://github.com/liferay-echo/liferay-portal/pull/302

**Pull request closed without merging**
