### PR TITLE
LPS-102711 Adds new source formatter suppresion for JavaAPISignatureCheck and SiteSettingsConfigurationScreenContributor

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, there is an issue, Do you mind fix in this PR?
The success message is missing when create a new site.

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/4457

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
