### PR TITLE
LPS-153225 Get the default preferences directly from the Layout to avoid creating unnecessary new LayoutRevision's and their related portlet preferences

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

When investigating [PTR-2962](https://issues.liferay.com/browse/PTR-2962), I discovered [LPS-153225](https://issues.liferay.com/browse/LPS-153225), which affects at least Master and 7.3.x.

Could you please review it and confirm that the chosen fix approach is the right one for this issue?

Thanks in advance!

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Review by lfbesada — COMMENTED** [review]
Hi @dacousalr,
Thanks for the PR!
I have checked the [bug reported](https://issues.liferay.com/browse/LPS-153225) and for me works as expected with the current master branch.
Could you please double-check if you can reproduce it in master?
Maybe I am missing something 🤔 
Thanks!
Regards

**Comment by lfbesada** [comment]
@dacousalr this is my test recording, please let me know if I am doing something wrong, thanks!
ezgif com-gif-maker

**Comment by lfbesada** [comment]
Hi @dacousalr,
Have you had the chance to verify if you reproduce the bug in master?
Is there something wrong with the steps I am doing?
Thanks
Regards

**Comment by lfbesada** [comment]
I wasn't able to reproduce it because of my local configuration in portal-ext:

configuration.override.com.liferay.asset.publisher.web.internal.configuration.AssetPublisherSelectionStyleConfiguration_defaultSelectionStyle="dynamic"

Once removed I have reproduced the issue.

**Review by lfbesada — APPROVED** [review]
@dacousalr Thanks for the fix!

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
