### PR TITLE
LPS-114419 Cannot discard draft when there is an experience in a content page

### PR DESCRIPTION
**Pull request by darquesdev**
@ealonso @jkappler

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:close

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
https://github.com/darquesdev/liferay-portal/pull/154

**Pull request closed without merging**
