### PR TITLE
LPS-155843 add conditional to compare if default locale is different to site default

### PR DESCRIPTION
**Pull request by murilostodolni**
Related ticket: https://issues.liferay.com/browse/LPS-155843

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by murilostodolni** [comment]
ci:test:sf

**Comment by murilostodolni** [comment]
ci:test:relevant

**Comment by crodriguezy** [comment]
Hello @liferay-echo , just to let you know, this is a blocker for the customer, they are unable to create any content. It's present on u29+ and we asked for help in https://issues.liferay.com/browse/PTR-3184.

I've also tried to fix it by modifying the way we are getting default locale in LocaleUtil: https://github.com/crodriguezy/liferay-portal/pull/282. That change apparently also fixes the case, but since the code implied haven't been modified in a long time and this class is globally used across the portal, I'm not sure if it could easily lead to regressions. 
Please let me know if you find this more apropiate and I'll send it to the team.

Thanks

**Comment by jkappler** [comment]
hi all, we are taking a look at it. Thanks for the patience

**Comment by jkappler** [comment]
@murilostodolni, @crodriguezy, I traced the root cause to https://issues.liferay.com/browse/LPS-153217 

So to advance, reverting those commits would solve the clients issue. Will try to check it out tomorrow and find a solution for both issues

**Comment by jkappler** [comment]
@murilostodolni, @crodriguezy, please see: https://github.com/liferay-echo/liferay-portal/pull/8833

**Comment by crodriguezy** [comment]
Hi @jkappler , thanks a lot for taking care of this! :)

**Pull request closed without merging**
