### PR TITLE
LPS-151110 - Test upgrade from 7.2 and adapt it if necessary

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @sandrodw3

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hey @ruben-pulido,
In order to easy testing, could you please attach to the ticket the 7.2 SQL dump used to assert it? Thank you very much! ❤️ 
Regards

**Review by lfbesada — APPROVED** [review]

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
