### PR TITLE
LPS-125197 Use AL vocabularies in connected sites

### PR DESCRIPTION
**Pull request by adolfopa**
Hey Team!

This PR allows connected sites to see and use AL vocabularies. Note that this doesn't have a feature flag, so you may want to wait for the release before forwarding this.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Hi @adolfopa, thanks for sending us the pull :D

We'll wait until after the release to merge it as you mentioned.

Thanks again

**Comment by adolfopa** [comment]
Thanks @jkappler !

Even if you wait, can you review it now? That way, if you see anything weird, we can fix it now that it is fresh in our minds. In two weeks I won't remember anything about this ;-)

Thanks!

**Comment by adolfopa** [comment]
ci:reevaluate:1137401_5639

**Comment by adolfopa** [comment]
ci:reevaluate:1137401_5639

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Resent here: https://github.com/liferay-echo/liferay-portal/pull/4093

**Pull request closed without merging**
