### PR TITLE
LPS-138164 Use object's group at least it be a company group.

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-138164

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/5794

**Pull request closed without merging**
