### PR TITLE
LPS-169645 Escape string

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
Hi @ealonso, there is a regression issue. Could you please have a look at?

After map some fragment to content field of Web Content, it displays the tag.

https://user-images.githubusercontent.com/72820234/204043656-1946e9a1-1522-4b5e-b335-dd41d47f620f.mp4

**Comment by ealonso** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Hey @ealonso, the above mentioned failure is still happening, regarding a mapped fragment showing tag. https://github.com/liferay-echo/liferay-portal/pull/10445#issuecomment-1327800559
image

**Comment by alessandromalves** [comment]
Hey @ealonso, the [above mentioned failure](https://github.com/liferay-echo/liferay-portal/pull/10445#issuecomment-1327800559) is still happening, regarding a mapped fragment showing tag. Could you please have a look at?
image

**Comment by lfbesada** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/10492

**Pull request closed without merging**
