### PR TITLE
LPS-175108 Replace icons in product-navigation-product-menu-web

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://issues.liferay.com/browse/LPS-175108)

## Test Steps

1. Go to Control Panel -> System Settings 
2. In Content & Data section -> Navigation 
3. In left menu -> Applications Menu -> Disable Applications Menu
4. Go to Product menu -> see at the left side the Control Menu together with Product Menu
5. Collapse/expand the categories to see the icons
6. **NOTE: you have to reduce the window size of your browser to see the CLOSING button, because the button disappears with window sizes smaller than "md" sizes.**
Screenshot 2023-02-08 at 19 08 27

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:stable

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130039

**Pull request closed without merging**
