### PR TITLE
LPS-186419 Add button classes and clean CSS in control menu

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-186419)

Due to a previous task ([LPS-176251](https://issues.liferay.com/browse/LPS-176251)), we observed that the use of the css class control-menu-icon was not necessary since the same result could be obtained using the existing monoespaced and small classes for the buttons. 
## Proposed solution

Instead of using control-menu-icon, use monoespaced and small button classes.

### Test Scenario 1

* Navigate to Applications menu > Applications > Workflow > Metrics. * Check the focus visible state for the kebab menu.

Pasted Graphic 2

### Test Scenario 2

* Navigate to Applications menu > Applications > Workflow > Metrics. * Click on one process and check the focus visible state for the back button.

Pasted Graphic 3

### Test Scenario 3

* Navigate to product menu.
* Check all the icons in control menu: 

Liferay DXP

### Test Scenario 4

* Navigate to Applications menu > Control Panel > Configuration > Instance Settings.
* Go to Digital Signature.
* Check the back button.

Digital Signature Configuration

### Test Scenario 5

* Navigate to Applications menu > Applications > Workflow > Metrics.
* Go to Settings (click on the kebab menu in the control-menu bar).
* Reindex All for Workflow Metrics Indexes and check the loading icon next to the user.

Pasted Graphic 7

### Test Scenario 6

* Navigate to Applications menu > Control Panel > Sites > Site Template.
* Create a new site template and click on it once created.
* Check the propagation button.

site template

### Test Scenario 7

* Navigate to Content & Data > Forms.
* Create a new form.
* In that view, check the back button.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
ci:forward:force

**Comment by alessandromalves** [comment]
The failures are not related to this PR. [(see comparison with acceptance routine).](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2347984406&testrayRunIdA=2345438605&statusB=3)

**Pull request closed without merging**
