### PR TITLE
LPS-203029 reseting page number after altering filter

### PR DESCRIPTION
**Pull request by linolaoj**
Motivation
=======
[Widget Collection Filter not filtering after paginating](https://liferay.atlassian.net/browse/LPS-203029)

Proposed Solution
========
Reseting the page parameter from the URL When the filter is applied.

Steps to Verify
========

  1- Access Site Menu > Categorization > Categories > Create a Vocabulary and 2 Categories.

  2-  Go to Content & Data > Web Content > Create at least 10 Basic Web Content, with at least one category selected. (I defined Content 1 to Category-2 and all others with Category-1)

  3- Go to Site Builder > Collection > Create a Dynamic Collection and choose Basic Web Content as the source.

  4-  In a Page add the following:

       4.1-  Collection Display

            Collection: Choose the collection created previously

            Style Display: Bordered List

            List Item Style: Title

            Pagination: Numeric

            Maximum Number of Items per Page: 5

        4.2- Collection Filter

            Target Collection: choose the collection created.

            Filter: Category

            Source: Select the Vocabulary

   5- Publish the Page

   6- Access pagination, page 2.

* Actual Behavior

    In pagination 2, when attempting to filter by Category-2, for example, "No Results Found" is displayed.

* Expected Behavior

    The search filter should work in all paginations.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @linolaoj this solutions seem to work but is a bit brittle, if any other component would added any param that start with page_number it will be cleared too.

I think we should get somehow the exact name of the attribute, can you investigate if we can obtain that in the filters code?

Let me know if you need help with that :) 

Tahnks

**Comment by linolaoj** [comment]
Hi @victorg1991, thank you for taking a look at this. The code of the parameter `page_number` is the `containerKey` that is present in the table `AssetListEntryUsage`. In the context of the file [CollectionFilterRegister.js](https://github.com/liferay-echo/liferay-portal/pull/14578/commits/f6ec1f9d57b1beb3a4c2596fa8c0e5d2507d2606#diff-2cbe8ece4d0352273ce3f904e6f5c7bafa55d8f0abb903ed9178dd0705b99cee) I see that we have the `fragmentEntryLinkId`. I checked in the class `FragmentCollectionFilterCategoryDisplayContext` but could not find a way to get the `containerKey` from the FragmentEntry or the FragmentEntryLink. Is there a way that I can get the `containerKey` that I'm missing?

**Comment by victorg1991** [comment]
Hey @linolaoj Sorry for the delay. You can access the configuration values for that. There is a configuration field named "targetCollections" which contains the collections that are associated with the filter. You can access that value with the `getFieldValue` present in the display contexts of the filter. Then you can pass that value to the filter react component and then to the utility that control the filter (the one you changed in this pr) with that we can know the exact name of the parameter we have to remove :) 

Let me know if you need further help

**Comment by linolaoj** [comment]
Hi @victorg1991 , I've pushed the https://github.com/liferay-echo/liferay-portal/pull/14578/commits/4a00ca6752d2ebf40c59addcbb91b46bc1d938b3 to remove only the parameter related to the collection. Let me know if any other change is needed.
Thanks!

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Thanks @linolaoj I have resent the pr here: https://github.com/liferay-echo/liferay-portal/pull/14704

**Pull request closed without merging**
