### PR TITLE
LPS-135527 Frontend tests for display collection pagination

### PR DESCRIPTION
**Pull request by veroglez**
**Only the last 4 commits have to be reviewed**, the rest of commits belong to this [PR](https://github.com/liferay-echo/liferay-portal/pull/5359)

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
