### PR TITLE
LPS-129677, LPS-132403, LPS-132684, LPS-134207, LPS-134897 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-129677
https://issues.liferay.com/browse/LPS-132403
https://issues.liferay.com/browse/LPS-132684
https://issues.liferay.com/browse/LPS-134207
https://issues.liferay.com/browse/LPS-134897

This is only for master.

@veroglez

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by veroglez** [comment]
see https://github.com/liferay-echo/liferay-portal/pull/5098

**Pull request closed without merging**
