### PR TITLE
LPS-123101 buildLang

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
@Tim-Cao this probably needs some poshi renaming too (like https://github.com/liferay-echo/liferay-portal/pull/2856)

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/2937

**Comment by Tim-Cao** [comment]
ci:close

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/2948

**Pull request closed without merging**
