### PR TITLE
LPS-118408 and LPS-119754 Final Visual/Layout Improvements for Application Menu and Open/Close menu on keyboard shortcut

### PR DESCRIPTION
**Pull request by carloslancha**
https://issues.liferay.com/browse/LPS-118408 and https://issues.liferay.com/browse/LPS-119754

Original PRs: 
https://github.com/liferay-frontend/liferay-portal/pull/309
https://github.com/liferay-frontend/liferay-portal/pull/322

Done:
- Open / Close the menu on CMD + SHIFT + M press
- Changed "Sites" for "Environments" at the menu top area
- Added Virtual Instance section inside Environments area.
- Removed "Powered by Liferay"

TODO:
- In the bottom left corner of the apps menu it should appear the DXP Logo + Liferay DXP in DXP version or the CE Liferay Logo + Liferay for CE version. JS component is prepared to render it as it should be but backend (`ApplicationsMenuDisplayContext.java`) needs to be updated to pass the correct values for `liferayLogoURL` and `liferayName`.

image

### CODE REVIEW

**Comment by carloslancha** [comment]
hey @liferay-echo these are the final touches to the application menu. There's some work that needs to be done described in the TODO section of the description. Could you please take care of it? Thx!!

cc @jbalsas @diegonvs

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
I'll try to change a little the markup so we don't need to update the poshi tests, I'll push the changes here

**Comment by carloslancha** [comment]
@ealonso pushed the needed change, this should fix the poshi errors. Let's see 😅

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
Let's try again

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @carloslancha,

There is a problem with :apps:product-navigation:product-navigation-applications-menu-web:packageRunTest, Could you please take a look at it?

It seems some frontend tests are broken and need some updates.

**Comment by carloslancha** [comment]
@ealonso I'm taking a look, yep

**Comment by carloslancha** [comment]
ci:stop

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
@ealonso tests should be fixed now. I'll keep an eye on this during the afternoon anyway.

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
