### PR TITLE
[TS] LPS-200487 Sites are not browsable for Guests in Breadcrumb portlet

### PR DESCRIPTION
**Pull request by dcarrillolf**
Motivation
=======
Sites are not browsable for non-admin users in Breadcrumb portlet, even the user has permission to access the group. It occurs when site has Membership type != "Open".
- https://liferay.atlassian.net/browse/LPS-200487

Proposed Solution
========
Switching from Group Configuration to Group's Default Layout Permissions

Steps to Verify
========
Steps to reproduce:
1. Start Liferay, create a new site “Test”, and select select “private” or “protected” membership for this site.
2. Add a homepage with a breadcrumb portlet (“horizontal” template, default config).
3. Check “Show current Site” is enabled
4. Logout and reload this page with the Guest user

**Current behavior**: Site “Test” does not have href attribute (breadcrumbEntry.isBrowsable() = false)
**Expected behavior**: The link is enabled and can be used since Guest users have access to the homepage of this site.

Alternative Solutions that were discarded
========
Do not consider any kind of permission since current site may be browsable. In this case, the user will click on the breadcrumb and find a missing permission error..

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
@dcarrillolf it is not correct, the status should be in review and assigned to echo jira user. Also, you should add the link to the pr.

**Comment by ealonso** [comment]
Waiting for PTR

**Comment by jkappler** [comment]
@dcarrillolf, closing the PR based on the answer that we have given in the PTR

**Pull request closed without merging**
