### PR TITLE
LPS-142557 - Collection Display for Objects does not display all instances, even when "Display All Collection Items" is checked

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @Tim-Cao

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:echo

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ruben-pulido, no regression issues found according to [ci:test:echo](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1640129978373&testrayRunIdA=1593133440&testrayRunIdB=1593239417)
LGTM!

**Comment by Tim-Cao** [comment]
The failure case is unrelated to this PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/111464

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:close

**Comment by ruben-pulido** [comment]
Thanks a lot @Tim-Cao!

**Pull request closed without merging**
