### PR TITLE
LRAC-9857 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRAC-9857

This is only for master.

@jkappler

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Poshi cases are already fixed according to [ci:test:echo](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1638345428261&testrayRunIdA=1585708351&testrayRunIdB=1585670590)

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
