### PR TITLE
[TS] LPS-153713 Use the common pattern in filters to avoid NPE

### PR DESCRIPTION
**Pull request by bakayattila**
hi Team,
Could you review this?

https://issues.liferay.com/browse/LPS-154740

Best,
Attila

----

When this property is turned on I found that there is a second request in the use case explained on the LPS that will be stuck resulting in the following not returning a servletContext.
 ```
ServletContext servletContext  = (ServletContext)httpServletRequest.getAttribute(WebKeys.CTX);
``` 
because the current request will not contain the servletContext. After checking other Filters I found that the usual pattern to get the servletContext in filters is to get it through the filterConfig. I tested the use case and after using the common pattern the issue is resolved.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @bakayattila I think that code belongs to the core infra team, would you mind sending this pr to them? Thanks!

**Comment by bakayattila** [comment]
ci:close

**Pull request closed without merging**
