### PR TITLE
LPS-147234 Update the ContentImagesUpgradeProcess could identify the fileEntry in the dynamic element data

### PR DESCRIPTION
**Pull request by achaparro**
Hi,

This is an specific case only for 7.1GA1. In that version we generate journal articles with the following content for an image field:
```
<?xml version="1.0"?>

<root available-locales="en_US" default-locale="en_US">
	<dynamic-element name="Imageaj4l" type="image" index-type="text" instance-id="jqma">
		<dynamic-content language-id="en_US"><![CDATA[{"groupId":"20135","name":"Screenshot from 2022-02-18 17-31-59.png","alt":"","title":"Screenshot from 2022-02-18 17-31-59.png","type":"journal","uuid":"e9e8d300-adb1-3235-9114-7a8118017cd5","fileEntryId":"35670","resourcePrimKey":"35665"}]]></dynamic-content>
	</dynamic-element>
</root>
```

And during the upgrade _ContentImagesUpgradeProcess_ we are not able to process it because the _fileEntryId_ is not provided in the dynamic element fields, only in the JSON field.

The final format after the upgrade is:
```
<?xml version="1.0"?>

<root available-locales="en_US" default-locale="en_US">
	<dynamic-element name="Imageaj4l" type="image" index-type="text" instance-id="jqma">
		<dynamic-content language-id="en_US" fileEntryId="35670"><![CDATA[{"groupId":"20135","name":"Screenshot from 2022-02-18 17-31-59.png","alt":"","title":"Screenshot from 2022-02-18 17-31-59.png","type":"journal","uuid":"e9e8d300-adb1-3235-9114-7a8118017cd5","fileEntryId":"35670","resourcePrimKey":"35665"}]]></dynamic-content>
	</dynamic-element>
</root>
```

More info in:
https://github.com/liferay-upgrades/liferay-portal/pull/258#issue-1139449413

Thank you.

cc/ @binhtran92 @hongvo2308

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1297401_1823

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
