### PR TITLE
LPS-147088 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-147088

This is only for master.

@dacousalr

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Hi @dacousalr Thanks for the fix! It works great! Regards

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
