### PR TITLE
LPS-130377 Update _privateLayout by checking if any public or private pages are created

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-130377

The issue here was that the Add New Page button was only giving the option to create public pages when only private pages were created.
To fix this issue, _privateLayout is updated by checking whether any public pages or private pages have been created.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/4233

**Pull request closed without merging**
