### PR TITLE
[TS] LPS-126055 HtmlUtil.escapeJS the title parameter

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

could you please check my fix and push it forward?

Thanks, Roland

https://issues.liferay.com/browse/LPS-126055

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @rolandpakai,
Could you please send this one to User & Management System Team?
Regards,
Eudaldo

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
Hey @rolandpakai,
Sorry about that, I read Portlet Permissions and I didn't check where is the class.

**Pull request closed without merging**
