### PR TITLE
LPS-201547 Check tag cloud and tag navigation filter behavior

### PR DESCRIPTION
**Pull request by Mikellorza**
subtask: https://liferay.atlassian.net/browse/LPS-201547

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @Mikellorza, would you mind checking this failed test?
[com.liferay.batch.engine.internal.test.BatchEngineImportTaskExecutorTest](https://testray.liferay.com/home/-/testray/case_results/2460282335?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2460265916%26testrayRunId%3D2460280406%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

**Comment by Mikellorza** [comment]
sure @Tim-Cao , I am going to test it right now

**Comment by Tim-Cao** [comment]
Hi @Mikellorza, is tag-popularity changes expected? 
Expected
image

Actual
image

**Comment by jkappler** [comment]
ci:stop

**Comment by Mikellorza** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
Fix works on my local. Thanks @Mikellorza

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @Mikellorza, could you check this failed test? Thanks
[com.liferay.asset.link.exportimport.test.AssetLinkExportImportTest](https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/833950/testReport/com.liferay.asset.link.exportimport.test/AssetLinkExportImportTest)

**Comment by Mikellorza** [comment]
Hi @Tim-Cao ,

I've just checked it and all tests are passing.

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by alessandromalves** [comment]
The failures are not related to this PR [(comparison with acceptance routine here)](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1700503844752&testrayRunIdA=2462023878&testrayRunIdB=2462082302). See https://github.com/brianchandotcom/liferay-portal/pull/144077

**Comment by alessandromalves** [comment]
ci:close

**Pull request closed without merging**
