### PR TITLE
LPS-188163

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:for

**Comment by ealonso** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Hey @ealonso, a regression found ([see comparison with acceptance routine](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1687550332412&testrayRunIdA=2359554513&testrayRunIdB=2359888041)). Steps to repdroduce:

1. Go to Product Menu >> Design >> Page Templates >> Masters tab
2. Add a custom master
3. Go to Product Menu >> Site Builder >> Pages
4. Add a content page based on custom master
5. On the left sidebar, go to  Page Design Options >> More Page Design Options
6. Edit Master
7. Publish Master

Expected result:
User will be redirected to the content page.

https://github.com/liferay-echo/liferay-portal/assets/69062082/3b3c1309-3066-4801-9255-24c611f820ef


Actual result:
User is being redirected to More Page Design Options

https://github.com/liferay-echo/liferay-portal/assets/69062082/aaa3753c-b887-44a8-b579-df3b182f5488

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
