### PR TITLE
LPS-150759 Rely on super method

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
Hey @rolandpakai,

Yes your commit is not the problem, I'm taking a look at it.

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
