### PR TITLE
[TS] LPS-141980 Use the same tag filtering for Tags Widget Templates as for the default portlet rendering

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @liferay-echo Team,

I've implemented a fix of [LPS-141980](https://issues.liferay.com/browse/LPS-141980) to eliminate the differences between the default Tag Cloud/Tags Navigation portlet rendering and when the "Color by Popularity" widget template is used. I tried to replicate the same behavior as `_buildTagsNavigation()` in: https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-taglib/src/main/resources/META-INF/resources/asset_tags_navigation/page.jsp .

Please review my changes.

Thanks,
Vendel

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1317401_1040

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Hi @vendeltoreki, we are still talking about the PTR (internally), and after checking your solution we are a bit unsure about the performance issues that this could cause. Mostly since we are retrieving all tags, and then for each one their count.

Is there any other way that we could resolve this issue? 

Thanks!

**Comment by vendeltoreki** [comment]
Hi @jkappler ,

Thanks for looking into this PR. This fix was only supposed to remove the discrepancy between the two rendering methods of the tags portlet. It tried to replicate the same thing that we already execute in: https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-taglib/src/main/resources/META-INF/resources/asset_tags_navigation/page.jsp .

What I found is that we execute the same query twice anyways on one single rendering. Once in [view.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-tags-navigation-web/src/main/resources/META-INF/resources/view.jsp#L26) and once again in [page.jsp](https://github.com/liferay/liferay-portal/blob/f6b43a66e2d979fda74c1f02d28f101c7f1def84/modules/apps/asset/asset-taglib/src/main/resources/META-INF/resources/asset_tags_navigation/page.jsp#L70). The only difference is, that `view.jsp` did not do the same post-filtering that `page.jsp` already did.

To solve this the right way, I would wait for the result of your analysis on the PTR and build a complete solution based on that.

My first idea is to move all this logic from these JSPs into a java class. Probably AssetTagService would be the right one, but that would require probably new methods and a kernel change. This would automatically solve the case of [LPS-141980](https://issues.liferay.com/browse/LPS-141980), as both can use the same method.
To get rid of the extra asset count queries, we could use a join in the first query, as Daniel suggested on the PTR.
As for executing the same query twice, I don't really have any good idea in mind. We could probably restructure the `asset-tags-navigation` taglib to work with template rendering.

It's probably best to put this PR on hold until these are resolved.

Thanks,
Vendel

**Comment by vendeltoreki** [comment]
Closing this PR, resending on https://github.com/liferay-echo/liferay-portal/pull/6442

**Pull request closed without merging**
