### PR TITLE
LPS-159413 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-159413

This is only for master.

@sandrodw3
cc @ozysouza

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @sandrodw3, Would you mind having a look at the following issue.
When publish a content page where the Form Container only have Submit Button and Captcha fragments, the warning message is  **Fragment Mapping Missing**
However, there are no mappable input fragments existing.
image

**Comment by Tim-Cao** [comment]
Hi @sandrodw3, would you mind having a look at the second issue?
When publish a content page where the Form Container has mapped Text Input and Submit Button fragments and the Form Container with Preview Success State, the warning message Submit Button Missing is shown.
image

**Comment by sandrodw3** [comment]
https://github.com/liferay-echo/liferay-portal/pull/9278

**Pull request closed without merging**
