### PR TITLE
LPS-169776 Two select buttons appear in AP widget configuration after asset library scope is added

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-169776)

Recently Echo Team has been working in migrating icon-menus to dropdown-items. Which leads to certain issues...

## Change summary:

* Change so that the buttons to select assets are shown horizontaly, just like with the icon-menu
* Label the buttons correctly

## Test Scenario

* Add a new site
* Add an asset library and connect it to the site
* Add an Asset Publisher to the site
* Configure it and select manual selection
* Two buttons should be shown horizontally and with the correct label

Screenshot 2022-11-28 at 12 06 32

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
