### PR TITLE
LPS-153896 Add Test LayoutAssetRenderer testGetURLViewInContext

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-153896

Adds the test requested in https://github.com/brianchandotcom/liferay-portal/pull/117740#issuecomment-1132680591

/cc @hongvo2308

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
