### PR TITLE
LPS-182037 Refactor LocalizedDropdown

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://issues.liferay.com/browse/LPS-182037)

## Steps 

1. Go to Product Menu > People > Segments
2. Create a Segment
3. Open language flag to see the dropdown
Screenshot 2023-04-20 at 17 08 42

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:stop

**Comment by sandrodw3** [comment]
LGTM! Great job @DiegoHu97 😄

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:stop

**Pull request closed without merging**
