### PR TITLE
 LPS-132737 product-navigation-simulation-device width and height inputs should only show on the custom tab

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-132737

- product-navigation-simulation-web sidebar close button should be styled and line up vertically with panel collapse icons

custom-device-hidden
custom-device-show

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
