### PR TITLE
LPD-27549 Guest user is not redirected to the login page if default page visibility is restricted

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-27549

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:test:stable

**Comment by lfbesada** [comment]
ci:report:10512455

**Comment by lfbesada** [comment]
Manually forwarded https://github.com/brianchandotcom/liferay-portal/pull/151017

**Pull request closed without merging**
