### PR TITLE
[TS] LPS-185891 When moving a Web Content, users can view folders for which they don't have permissions

### PR DESCRIPTION
**Pull request by joseluisbango**
Hi @liferay-echo,

When moving a Web Content, users can view folders for which they don't have permissions. See [LPS-185891](https://issues.liferay.com/browse/LPS-185891) for details.

Instead of using the `JournalFolderLocalServiceUtil`, we can use `JournalFolderServiceUtil`. This way, user's permissions are checked when querying the database (if Inline Permission Check is enabled).

Could you review this change?

Thanks!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by joseluisbango** [comment]
ci:test:sf

**Comment by joseluisbango** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
