### PR TITLE
LPS-203837 Duplicated web content urlTItle is wrong

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you review this fix?
https://liferay.atlassian.net/browse/LPS-203837 
best,
Attila

--------

The root cause of the issue is that the FriendlyURLNormalizerUtil NormalizeWithPeriodsAndSlashes method removes all the language special characters like Japanese symbols. As we allow acented characters in friendlyURLs it is better to use the normalaziewithEncoding method here.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by lfbesada — APPROVED** [review]
Hi @bakayattila 
Thanks for the fix, it works like a charm :star_struck: 
LGTM :tada: 
Regards

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
