### PR TITLE
LPS-125485 Use DDM structure name in the default language wheen current isn't available

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by ealonso** [comment]
cc: @jeyvison

**Comment by jeyvison** [comment]
@ealonso @pavel-savinov LGTM :)

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Since the failure case is an unstable one not related to change in PR and in order to not clog up ci resources I pushed directly to BChan.
See https://github.com/brianchandotcom/liferay-portal/pull/97587

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
