### PR TITLE
LPS-142720 Remove feature flag

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @veroglez, there is a regression, The Saved information is missing after modify the non-color styles. Could you have a look?

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7347

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
