### PR TITLE
LPS-178959 Review and clean main.scss

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://issues.liferay.com/browse/LPS-178959)

## Steps 

1. Configure Page audit by following these steps https://liferay.atlassian.net/wiki/spaces/ENGTANGO/pages/1586299258/How+to+test+the+Page+Audit+panel+in+localhost and https://liferay.atlassian.net/wiki/spaces/ENGTANGO/pages/1638401188/How+to+fake+page+audit+to+show+all+failures+at+the+same+time
2. Then go to page audit and launch it

Screenshot 2023-04-19 at 16 38 41

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Review by p2kmgcl — CHANGES_REQUESTED** [review]

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
@p2kmgcl Updated! Thanks for the feedback ❤️

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:forward

**Review by p2kmgcl — APPROVED** [review]

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
