### PR TITLE
LPS-135156 Performance degradation with custom navigation pages menu if there are child pages

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-135156

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:reevaluate:1317401_405

**Comment by Tim-Cao** [comment]
The failure task is unrelated to this PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/107110

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
