### PR TITLE
LPS-181056 add treepath to retrieve values from children folders

### PR DESCRIPTION
**Pull request by jgarcialr**
Motivation
=======
This PR aims to solve the case where filtering by structureId from the web content administration only search in the current folder, instead of this folders and their children, [LPS-181056](https://issues.liferay.com/browse/LPS-181056)

Proposed Solution
========
Modify the methods in the finder to take into account the treepath and the folderId instead of only using the folderId.
The new aproximation uses 
`folderId = X or treepath like %/folderId/% `
instead of just 
`folderId = X`
If folderId = 0, treepath is /, as currently stored in the database

Steps to Verify
========

1. Start master
2. Go to Web Content
3. Create a Basic Web Content named "Outer Content" in Home level directory
4. Create a folder named "Subfolder 1"
5. Open "Subfolder 1", create Basic Web Content named "Inner Content Depth 1" AND create folder named "Subfolder 2"
6. Open "Subfolder 2", create Basic Web Content named "Inner Content Depth 2"
7. Go to Home (top level directory in Web Content)
8. Filter by Structure and select Basic Web Content

Expected Results :
    Show Basic Web Content in Home folder, Subfolder 1, and Subfolder 2 ("Outer Content", "Inner Content Depth 1", and "Inner Content Depth 2")

Actual Results :
    Only shows Basic Web Content in Home folder "Outer Content"

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jgarcialr** [comment]
ci:test:sf

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @jgarcialr 
Thanks for the pull request!
I have been talking with Product Management and they said this ticket hasn't been confirmed as a bug yet. So, please, keep this solution and resent it in case the expected behavior becomes confirmed.
Regards

**Pull request closed without merging**
