### PR TITLE
LPS-175787 Fail to deploy fragements to specific virtual instance when enable db partitioning

### PR DESCRIPTION
**Pull request by jkappler**
https://issues.liferay.com/browse/LPS-175787
https://issues.liferay.com/browse/LPS-166100
https://issues.liferay.com/browse/LPS-177954

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by david-gutierrez-mesa** [comment]
ci:test:echo-db-partition

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:echo-db-partition

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:forward

**Review by ruben-pulido — APPROVED** [review]

**Comment by ealonso** [comment]
ci:reevaluate:1277401_7289

**Comment by ealonso** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
