### PR TITLE
LPS-158538 Intermediate backward compatible nodes of FieldSet type should be skipped

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
[LPS-158538](https://issues.liferay.com/browse/LPS-158538)
Given 
1. a Parent Structure with a Nested Field
2. a Child Structure of Parent Structure
3. a Template for Child Structure
4. and a Web Content of the Child Structure

When this an upgrade is performed from 7.3 to master
Then the values of the Parent Structure's Fields can't be reached by the old template

Proposed Solution
========
By skipping the intermediate nodes that are FieldSets, we insert the original nested fields top level Fields into the `backwardsCompatibilityTemplateNodes`

Steps to Verify
========
1. Start up a 7.3 bundle
1. Create a structure with a text field (e.g. Text) and embed another text field inside it (e.g. Nested Text).
1. Create another structure and set the previously created structure as it's parent
1. Add a text field to the new structure as well
1. Create a template for the child structure to display both the parent structure's fields and it's own field, eg:
```
   #if (Text26j5.getData())??>
   	${Text26j5.getData()}
   	<#if (Text26j5.Text1c4v.getData())??>
   	    ${Text26j5.Text1c4v.getData()}
       </#if>
   </#if>
   <#if (Text1ef0.getData())??>
   	${Text1ef0.getData()}
   </#if>
```
1. Create a web content from the child structure and fill all the fields
1. Display the web content on a page
1. Upgrade the portal to master
1. Start up the master bundle
1. Check the page where the web content is placed

**Expected behaviour:** All field values are displayed from the Web Content
**Actual behaviour:** Only the child structure's own field is displayed from the Web Content

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1327401_4833

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
