### PR TITLE
LPS-164258 Show label if the color picker is used in the configuration

### PR DESCRIPTION
**Pull request by sandrodw3**
cc @p2kmgcl

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1347401_2880

**Comment by sandrodw3** [comment]
ci:forward please

**Comment by liulukiwi** [comment]
Failure is not realted, pushed to BChan at: https://github.com/brianchandotcom/liferay-portal/pull/123856

**Pull request closed without merging**
