### PR TITLE
LPS-192264 Inline errors

### PR DESCRIPTION
**Pull request by p2kmgcl**
**How to test this**:

- Enable `LPS-182728` feature flag.
- Create some Object with required fields (you can import [this sample Object](https://raw.githubusercontent.com/p2kmgcl/chachi-shell/master/liferay/api/resources/allthethings-object.json)).
- Add a form container to some content page and map it to the Object.
- Send the form with some invalid field, for example:
  - View the page.
  - Run `document.querySelectorAll('[required]').forEach(e => e.removeAttribute('required'))`
  - Send the form without filling any field.

**Before**:
image

> I didn't know that the previous message was "The Date is required", and I love it :cupid: 

**After**:
image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
> Thank you for submitting this PR. 👏

@liferay-echo you're welcome

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
I think I forgot to add the feature flag definition :cry:

**Comment by p2kmgcl** [comment]
Done :partying_face:

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Comment by alessandromalves** [comment]
ci:forward:force

**Comment by alessandromalves** [comment]
The failures are not related to this PR [(see comparison with acceptance routine)](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1690912503085&testrayRunIdA=2397854597&testrayRunIdB=2398055519). See https://github.com/brianchandotcom/liferay-portal/pull/137555

**Comment by alessandromalves** [comment]
The failures are not related to this PR [(see comparison with acceptance routine)](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1690912503085&testrayRunIdA=2397854597&testrayRunIdB=2398055519). See https://github.com/brianchandotcom/liferay-portal/pull/138679

**Pull request closed without merging**
