### PR TITLE
LPS-133675 Include javascript property when updating layout set setti…

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-133675

Tests passed here: https://github.com/SamZiemer/liferay-portal/pull/810#issuecomment-855156583

Notes from @noornajj
>The issue here was that the JavaScript in a site template was not being propagated to the sites.
To fix this, I added the javascript property to the default array in updateLayoutSetSettingsProperties method.

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Thanks for the fix @noornajj and @SamZiemer

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
