### PR TITLE
LPS-152792 fix commit message 

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-152792

See: https://github.com/brianchandotcom/liferay-portal/pull/116986#issuecomment-1118684274

cc: @Tim-Cao 🥰

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:close

**Comment by ozysouza** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/117072

**Pull request closed without merging**
