### PR TITLE
LPS-191767 Adds service validation to prevent a user to modify a draft locked by another use

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-191767

cc: @liulukiwi

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @lfbesada, cannot pubish content page with draft to live
**Steps to reproduce**

1. Add a new site
2. Enable the local live
3. Add a Heading fragment to a content page then publish in staging site
4. Add a Button fragement below the Heading without publish in staging site
5. Navigate to the Staging admin
6. Publish changes to live

Actual Results:
The publich progress failed due to the following error
```
2023-08-03 10:51:26.926 ERROR [liferay/background_task-4][LoggerExportImportLifecycleListener:390] Staged model {class: com.liferay.segments.model.SegmentsExperience, groupId: 34141, uuid: 3cb9ddb6-755d-4f90-763d-b363041f2aec} import failed
com.liferay.portal.kernel.exception.NoSuchLayoutException: No Layout exists with the primary key 26
	at com.liferay.portal.service.persistence.impl.LayoutPersistenceImpl.findByPrimaryKey(LayoutPersistenceImpl.java:19764) ~[portal-impl.jar:?]
	at com.liferay.portal.service.persistence.impl.LayoutPersistenceImpl.findByPrimaryKey(LayoutPersistenceImpl.java:19780) ~[portal-impl.jar:?]
	at com.liferay.portal.service.impl.LayoutLocalServiceImpl.getLayout(LayoutLocalServiceImpl.java:1277) ~[portal-impl.jar:?]
	at sun.reflect.GeneratedMethodAccessor1538.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at com.liferay.staging.internal.service.LayoutLocalServiceStagingAdvice$LayoutLocalServiceStagingInvocationHandler._invoke(LayoutLocalServiceStagingAdvice.java:862) ~[?:?]
	at com.liferay.staging.internal.service.LayoutLocalServiceStagingAdvice$LayoutLocalServiceStagingInvocationHandler.invoke(LayoutLocalServiceStagingAdvice.java:701) ~[?:?]
	at com.sun.proxy.$Proxy456.getLayout(Unknown Source) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor1538.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:57) ~[portal-kernel.jar:?]
	at com.sun.proxy.$Proxy1130.getLayout(Unknown Source) ~[?:?]
	at com.liferay.portal.kernel.service.LayoutLocalServiceWrapper.getLayout(LayoutLocalServiceWrapper.java:824) ~[portal-kernel.jar:?]
	at sun.reflect.GeneratedMethodAccessor1538.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:57) ~[portal-kernel.jar:?]
	at com.sun.proxy.$Proxy1134.getLayout(Unknown Source) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor1538.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40) ~[portal-impl.jar:?]
	at com.sun.proxy.$Proxy112.getLayout(Unknown Source) ~[?:?]
	at com.liferay.segments.service.impl.SegmentsExperienceLocalServiceImpl._checkUnlockedLayout(SegmentsExperienceLocalServiceImpl.java:551) ~[?:?]
	at com.liferay.segments.service.impl.SegmentsExperienceLocalServiceImpl.addSegmentsExperience(SegmentsExperienceLocalServiceImpl.java:117) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48) ~[portal-impl.jar:?]
```

**Comment by lfbesada** [comment]
@Tim-Cao Thank you very much for catching it!!! ❤️ 
I have fixed this issue and some other integration tests that were failing because of these PR changes. Let's see now 🤞 
Regards

**Comment by lfbesada** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Hey @lfbesada, we have some integration tests failing only in this PR [(comparison with acceptance routine here).](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1691167171820&testrayRunIdA=2399969137&testrayRunIdB=2400104969) Would you mind taking a look at them?

[com.liferay.account.internal.model.listener.test.CompanyModelListenerTest](https://testray.liferay.com/home/-/testray/case_results/2400108602)
```
[exec] com.liferay.account.internal.model.listener.test.CompanyModelListenerTest > testCleanUpAccountEntries FAILED
     [exec]     com.liferay.portal.kernel.exception.ModelListenerException: com.liferay.portal.kernel.security.auth.PrincipalException: Principal is null
     [exec]     	at com.liferay.layout.page.template.internal.model.listener.LayoutModelListener.onBeforeRemove(LayoutModelListener.java:138)
     [exec]     	at com.liferay.layout.page.template.internal.model.listener.LayoutModelListener.onBeforeRemove(LayoutModelListener.java:47)
     [exec]     	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.remove(BasePersistenceImpl.java:669)
     [exec]     	at com.liferay.portal.service.impl.LayoutLocalServiceImpl.deleteLayout(LayoutLocalServiceImpl.java:870)
     [exec]     	at com.liferay.staging.internal.service.LayoutLocalServiceStagingAdvice.doDeleteLayout(LayoutLocalServiceStagingAdvice.java:444)
     [exec]     	at com.liferay.staging.internal.service.LayoutLocalServiceStagingAdvice.deleteLayout(LayoutLocalServiceStagingAdvice.java:103)
```


[com.liferay.content.dashboard.web.internal.portlet.test.ContentDashboardAdminPortletTest](https://testray.liferay.com/home/-/testray/case_results/2400109331)
```
[exec] com.liferay.content.dashboard.web.internal.portlet.test.ContentDashboardAdminPortletTest > testGetSearchContainer FAILED
     [exec]     java.lang.AssertionError: expected:<3> but was:<0>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:633)
     [exec]     	at com.liferay.content.dashboard.web.internal.portlet.test.ContentDashboardAdminPortletTest.testGetSearchContainer(ContentDashboardAdminPortletTest.java:285)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```


```

```

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
I have cherry-picked [this commit](https://github.com/brianchandotcom/liferay-portal/commit/3cfe94341cbe091ac918a3fcc99a40e0851acccb) from Brian's repo in order to pass CI

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1397401_6555

**Comment by lfbesada** [comment]
ci:test:stable

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/138927

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
