### PR TITLE
LPS-130057

### PR DESCRIPTION
**Pull request by ealonso**
Hey @ricardocousolr,

I made another solution for LPS-130057, it is based on your code but using the status field, since it is more common in portal.

Also, I changed the place where we are adding the attribute in the search context to filter the layout, instead of adding the filtering parameter on search portlet, I made the changes on layout portlets. So, by default we are returning the approved layouts and we are setting the status in the places we want to search for other statuses, those are layouts admin and product menu.

Could you please take a look at it?

Please let me know if you have any question.

Regards,
Eudaldo

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ricardocousolr** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ricardocousolr** [comment]
Hi @ealonso, 
The solution works well in my manual tests but some of the automatic ones in the package `com.liferay.layout.search.test` of module `layout-test` don't pass anymore. This happened to me when I was first preparing my pr so I'll reuse my solutions here. I'll let you know if I find any problems.

**Comment by ricardocousolr** [comment]
See #4601

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/4601

**Pull request closed without merging**
