### PR TITLE
LPS-133709 As a Navigation Menu creator I would like to access my Menus (and menu pages) from the page tree

### PR DESCRIPTION
**Pull request by lfbesada**
Previous PR:
https://github.com/liferay-echo/liferay-portal/pull/5000
https://github.com/liferay-echo/liferay-portal/pull/5026

cc: @victorg1991 @jkappler

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by victorg1991** [comment]
pls

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
