### PR TITLE
LPS-130416 Take into account that the href can be localized

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @ealonso, there is a regression issue. Could you have a look at?
image
The value of href is Object Object after add a manual link to editable field.

**Comment by ealonso** [comment]
@p2kmgcl Could you please take a look to https://github.com/liferay-echo/liferay-portal/pull/5386#issuecomment-891707551?

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/5404

**Pull request closed without merging**
