### PR TITLE
LPS-118277

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-118277

Resend of https://github.com/liferay-echo/liferay-portal/pull/1803

From: @huynguyen-codeengine

> I have added one line of code to remove the form validation errors of the field after user remove field on UI in order to submit the form

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Hey @holatuwol,

Could you please send this one to Dynamic Data Mapping Team?

Regards,
Eudaldo

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
