### PR TITLE
LPS-117838 Order the vocabularies by group and localized title

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
hey @liferay-echo 

I've talk with @dacousalr about this and we've agreed that this changes do make sense.

If you need more info about the implementation, please contact us.

Best Regards!!

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/2054

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
