### PR TITLE
LPS-120501 Set _self as default link target

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by veroglez** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @veroglez, When leave the target as self by default, the a tag doesn't have the attribute target="_self" in view mode. Is that intended?
Actual

**Comment by p2kmgcl** [comment]
Hey @Tim-Cao,
It is intended, because having no attribute and having target="_self" produces the same result (self is the default browser behavior)

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/2236

**Pull request closed without merging**
