### PR TITLE
LPS-121910 Migrate v2 usages in site/site-browser-web

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

**Test plan**:
- Navigate to **Configuration** > **Site Settings**
- Scroll down and search for the **Parent Site** section
- Click on the **Select Button**
- Assert that you can filter and choose a parent site

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
cc @ambrinchaudhary @markocikos @jonmak08

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
