### PR TITLE
LPS-138557 Reserve locale variable for the current portal locale and add articleLocale variable to store the current journal article's locale analogously to articleGroupId variable

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

The original fix for LPS-108651 caused some regression bugs like LPS-125409, whose fix, which was absolutely correct, made LPS-108651 reproducible again, so I created LPS-138557 to propose another fix approach.

Looking into the place where this code was introduced in [LEP-5809](https://issues.liferay.com/browse/LEP-5809), the original intention was to provide some localized error messages so the variable locale was put in place. However, the value of locale variable was tied to the JournalArticle's locale instead of storing the current portal locale. Those values are usually the same expect for when the JournalArticle is rendered in a classic Display Page. I would like to friendly remember that the use of classic Display Pages was introduced much later in [LPS-15961](https://issues.liferay.com/browse/LPS-15951).

Following the naming of articleGroupId, I decided to add a new variable, articleLocale, to store the specific JournalArticle's locale so that value can still be available.

Could you please review this change?

Please, let me know if you need more information about this.

Thanks in advance

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @dacousalr,

Could you please take a look to the broken tests? I think those are related

**Comment by dacousalr** [comment]
Yes, you are right, @ealonso,

I will review them and resend a new PR

**Pull request closed without merging**
