### PR TITLE
LPS-147253 LPS-147252 Limit number of items in edit mode and set new default values

### PR DESCRIPTION
**Pull request by lfbesada**
Follow up: https://github.com/liferay-echo/liferay-portal/pull/7360

@sandrodw3 @ruben-pulido

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
@Tim-Cao @david-gutierrez-mesa
I am afraid the failed test should be adjusted.
With [this commit](https://github.com/liferay-echo/liferay-portal/pull/7383/commits/57fc1ce1a729778a6a36b55346c3c3cfe3ef35af) we are changing the default pagination type from None to Numeric (that is not working now, the views should be adjusted too) and increasing the number of items per page from 5 to 20.

@sandrodw3 It seems like the view is not taking into account the default pagination type and it is setting None when is set as Numeric. Could you please take a look?

Thanks!

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @lfbesada, would you mind double checking, the Previous and Next Button are shown in Collection Display when selected pagination is None.
image

**Comment by lfbesada** [comment]
Hi @Tim-Cao, I am not able to reproduce it, I attach a gif with my steps. Please can you detail the steps to reproduce it?
Thanks!
Pagination-improvment

**Comment by Tim-Cao** [comment]
Sorry @lfbesada, I cannot reproduce after rebase on top of master.

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7397

**Pull request closed without merging**
