### PR TITLE
LPS-134566

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-134566

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
Added a semantic versioning commit

**Comment by ealonso** [comment]
Hey @mbowerman,

Is there any reason to not to use themeDisplay.getDoAsUserId() instead of adding a new parameter in the taglib?

Regards,
Eudaldo.

**Comment by mbowerman** [comment]
Hi @ealonso,

The new param in the taglib `doAsUser` isn't meant to specify the value of the `doAsUserId`. It is a boolean param meant to specify whether we should propagate the `themeDisplay.getDoAsUserId()` value when computing the Layout's URL.

When searching for a Layout from the Layout Item Selection menu, we typically *don't* want to propagate the `themeDisplay.getDoAsUserId()` value, since the Layout Item Selection menu is used for things like finding the Layout URL to link the text of an article to, or finding the Layout URL to use for a "Link to Layout" Layout. In these cases we don't want to propagate the `doAsUserId` parameter, because (1) the current user isn't navigating to that URL, they are just linking something to it, and (2) the URL is most likely going to be published and visible to other users, so we do not want to include the `doAsUserId` parameter.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/5014

**Pull request closed without merging**
