### PR TITLE
LPS-134072 Translate Welcome to Liferay and replace the json in the page definition. We do this for all available languages. If the locale is not present, it will use the default language

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Thanks for the heads up @Tim-Cao!

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
The failure tasks are unrelated to changes in PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/103601

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
