### PR TITLE
LPS-166370 Add paragraph tag to paragraph fragment

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-166370

When adding a paragraph tag to a page, the text is not in a paragraph tag by default. I added the paragraph tag to fix this.

Please let me know if there are any questions or comments about this.
Thank you!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Hello @veroglez,

Truly appreciate your explanation on why this was not a bug.
Can I trouble you with the customer's response to this decision and clarification if this is a bug?

> "I understand a rename would make it more understandable.
> But there is still a bug that needs to be fixed: If you add the widget to the page, it has font Normal selected by default.
> 
> If you select the text and select Normal (same value, you're not changing anything) the appearance of the screen changes.
> 
> It happens because by selecting the Normal, it will add the <p> markup which will include specific styles and change the appearance of the screen.
> Selecting a value that is already selected can not cause changes in the appearance.
> 
> The expected solution: When the user adds a paragraph to the screen, since Normal font is selected by default, the <p> markup should be added by default"

Video can be found here paragraph.mkv: https://issues.liferay.com/browse/LPP-46805

**Pull request closed without merging**
