### PR TITLE
LPD-29128

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:reevaluate:1367401_6368

**Comment by ruben-pulido** [comment]
The integration test added for the upgrade process is failing for some databases:
e.g. https://testray.liferay.com/#/project/34754/routines/34756/build/26007601/case-result/26048367
and needs to be adapted

**Comment by ruben-pulido** [comment]
Upgrade test fixed here: https://github.com/liferay-echo/liferay-portal/pull/15869

**Pull request closed without merging**
