### PR TITLE
LPS-153935 Disable button in edit mode

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1387401_544

**Comment by ealonso** [comment]
ci:reevaluate:1387401_544

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:close

**Comment by ozysouza** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/117672

**Pull request closed without merging**
