### PR TITLE
LPS-193855 Revert click interaction on collections

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
The motivation behind this PR is to remove the selectItem interaction for collections in the Page Content tab from the Page Editor.
https://liferay.atlassian.net/browse/LPS-193855

Proposed Solution
========
What I did to solve this problem is to use editableId variable to discard collections since they doesn't contain it and also remove opacity for the collection item in the list.

Steps to Verify
========
1. Create a collection
2. Go to Page Content tab in the page editor
3. Check that the the Collection content is not clickable but it still contains the ellipsis button
4. Check that the inline-text elements still working fine

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
Hey @Stephy6 I think we should revert the whole https://github.com/liferay-echo/liferay-portal/pull/13255

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by sandrodw3** [comment]
https://github.com/liferay-echo/liferay-portal/pull/13497

**Pull request closed without merging**
