### PR TITLE
LPS-179287 Remove unused journal search services

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-179287

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by jkappler** [comment]
LGTM as always @lfbesada 😍

**Comment by jkappler** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
@lfbesada No nos quiere el ci hoy, esta en el meeting, 😂

**Comment by ealonso** [comment]
ci:forward:force

**Comment by lfbesada** [comment]
@ealonso pues no, y "me pone muy nervioso" 🤣

**Pull request closed without merging**
