### PR TITLE
LPS-150872 Remove not needed icons

### PR DESCRIPTION
**Pull request by DiegoHu97**

### CODE REVIEW

**Comment by victorg1991** [comment]
It seems this have some conflicts with master, could you fix it @DiegoHu97 ? 😇

**Comment by victorg1991** [comment]
Thanks @DiegoHu97 !

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
