### PR TITLE
LPS-117778 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-117778

This is only for master.

@p2kmgcl

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
@p2kmgcl **Show structure panel when an item is selected** caused a regression issue. See the following video.
Expected
Actual

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/1701

**Comment by p2kmgcl** [comment]
ci:close

**Pull request closed without merging**
