### PR TITLE
LPS-172103 Adapt classes to handle files

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by alessandromalves** [comment]
Hey @victorg1991, two tests failed, could you please check?

1. integration test failure
[com.liferay.fragment.internal.struts.test.RenderFragmentEntryStrutsActionTest](https://testray.liferay.com/home/-/testray/case_results/2165004746?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2165002323%26testrayRunId%3D2165003911%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)

2. [LocalFile.FragmentsAdmin#EditFragment](https://testray.liferay.com/home/-/testray/case_results/2165004039?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2165002323%26testrayRunId%3D2165003911%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
   1. Go to Product Menu >> Design >> Fragments  
   2. Add Fragment Set
   3. Copy a Basic Component to the new Fragment Set
   4. Edit the fragment
   5. Make some changes with the fragment

Actual result:
The changes are not shown in the fragment

https://user-images.githubusercontent.com/69062082/213300698-d913ff0c-ac0f-49d5-93ba-75409416b4bd.mp4

Expected result:
The changes are shown in the fragment

https://user-images.githubusercontent.com/69062082/213300724-46d73f83-c4db-4499-80ca-4c59db651543.mp4

**Comment by victorg1991** [comment]
Hey @alessandromalves Many thanks for the analysis 👏 

I've fixed the problem and pushed the changes, should be fine now :)

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
