### PR TITLE
LPS-178943 Replace liferay-ui:icon with clay taglib

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://issues.liferay.com/browse/LPS-178943)

## Steps 
**Scenario 1**

1. Go to Product Menu > People > Segments
2. Create a Segment
3. See three dots kebab al right side of the segment created 
Screenshot 2023-04-04 at 14 06 10

**Scenario 2**

1. Connect to analytics cloud
2. Go to Product Menu > People > Segments
3. Create a Segment
4. See source column 
Screenshot 2023-04-04 at 14 06 00

**Scenario 3**

1. Go to Control Menu > Control Panel > Instance Settings
2. Content and Data > Segments 
3. Go to Segments Service 
4. Change settings and save
5. Upper right side will appear a kebab 
Screenshot 2023-04-04 at 14 27 06

### CODE REVIEW

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
@DiegoHu97 Great job 👏 
LGTM 🎉 
Regards

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Review by p2kmgcl — APPROVED** [review]
Awesome @DiegoHu97! :heart:

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
