### PR TITLE
LPS-139510 add template bug

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-139510

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
@lfbesada SF error, Could you please fix it and resend?

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/5923

**Pull request closed without merging**
