### PR TITLE
LPS-135554 Make the condition more clear

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The semantic verisoning issue is unrelated to changes in PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/104440

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
