### PR TITLE
LPS-149322 when updating the number of columns on desktop from UI reset default values in landscape mobile

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-149322

cc:// @veroglez

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1317401_2604

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Pull request closed without merging**
