### PR TITLE
LPS-177546 - Test Scenarios Coverage | Backend

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @jkappler @lfbesada @david-gutierrez-mesa

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:reevaluate:1317401_7450

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
