### PR TITLE
LPS-102711 Keep the old translations

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1147401_8144

**Comment by Tim-Cao** [comment]
Flaky issue. It’s unrelated to changes in PR.

**Comment by Tim-Cao** [comment]
Due to the failure case is a flaky issue and save ci resource, I'm sending this PR to BChan directly.
https://github.com/brianchandotcom/liferay-portal/pull/101320

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
