### PR TITLE
LPD-6865 6874 6875 6869 6870 6871 test

### PR DESCRIPTION
**Pull request by istvansajtos**
Previous PR: https://github.com/brianchandotcom/liferay-portal/pull/149016

Hi Echo Team,

Please review my changes which add integration tests for the login related utility pages. A few notes that you may find useful:

- The first 3 commits were organized based on [Brian's suggestions](https://github.com/brianchandotcom/liferay-portal/pull/149016#issuecomment-2046565945).
- The last commit was organized based on the guidance of @jkappler.

Thank you,
Istvan

cc @nikolettabuza

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by istvansajtos** [comment]
ci:test:sf

**Comment by istvansajtos** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
