### PR TITLE
[7.4-only] LPS-121973 Migrate v2 usages of clay:vertical-card in site-navigation-directory-web

### PR DESCRIPTION
**Pull request by julien**
cc @carloslancha @markocikos

### CODE REVIEW

**Review by carloslancha — APPROVED** [review]

**Comment by victorg1991** [comment]
This seems slighty different (left old, right new) Screenshot 2020-11-24 at 15 40 42

Looking at the clay code it seems that those classes can be passed to the components in the `imgProps` prop of the Card component, but in the portal this is not supported, as seen [here](https://github.com/liferay/liferay-portal/blob/dae2e90221f684b6b1ffba1161e9daba344a4c42/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/resources/META-INF/resources/cards/VerticalCard.js#L96)

It seems that we are not allowing to pass `aspectRatioCssClasses` as before. is this something missing or are we removing this feature?

@carloslancha @julien :)

**Comment by carloslancha** [comment]
@julien is this a use case of that fushHorizontal stuff?

**Comment by julien** [comment]
@carloslancha yes that could be it ... although `flushHorizontal` and `flushVertical` make the image "spread" across the whole card, i.e. like in [this demo](https://storybook.clayui.com/?path=/story/components-claycard--cardwithfile-w-image) - select the "Knobs" tab and check the "Horizontal Flush" and "Vertical Flush" check boxes

**Comment by carloslancha** [comment]
>@carloslancha yes that could be it ... although flushHorizontal and flushVertical make the image "spread" across the whole card, i.e. like in this demo - select the "Knobs" tab and check the "Horizontal Flush" and "Vertical Flush" check boxes

Is that what you expect @victorg1991 ?

**Comment by victorg1991** [comment]
> Is that what you expect @victorg1991 ?
I would expect to be able to apply these classes to the card component: https://github.com/victorg1991/liferay-portal/blob/df2b4d23b96a1edab6901e9c7fb36697d3bf35aa/modules/apps/site-navigation/site-navigation-directory-web/src/main/java/com/liferay/site/navigation/directory/web/internal/servlet/taglib/clay/GroupVerticalCard.java#L38-L41

**Comment by victorg1991** [comment]
@carloslancha  not sure if it the same as the flushHorizontal stuff 🤔

**Comment by victorg1991** [comment]
sent here: https://github.com/liferay-echo/liferay-portal/pull/3018 seems that isFlushVertical does the trick. Thanks!!

**Pull request closed without merging**
