### PR TITLE
LPS-171421 Page titles to be read by screen readers

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://issues.liferay.com/browse/LPS-171421)

## Steps

1. Go to Product Menu > Pages 
2. Create a Content Page and edit it without saving changes
3. See asterisk button in the upper left side 
Screenshot 2023-03-10 at 10 33 36

**Actual Result with Screen Reader:**
- The asterisk is not announced by SR
- Added title to announce Page is in Draft
Screenshot 2023-03-10 at 10 49 35

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
The reported failures will only require a fix at the tests

**Comment by alessandromalves** [comment]
The failures are not related to this PR. See https://github.com/brianchandotcom/liferay-portal/pull/131497

**Pull request closed without merging**
