### PR TITLE
LPS-140076 Move the color handling to the ColorPalette component, we are no longer using the cssClass, so just return the rgbValue when a color is selected

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @victorg1991, NPE thrown when configure color via colorpalete
```
2022-01-27 16:07:06.371 ERROR [http-nio-8080-exec-4][PortletServlet:119] javax.portlet.PortletException: java.lang.NullPointerException
javax.portlet.PortletException: java.lang.NullPointerException
	at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCActionCommand.processAction(BaseMVCActionCommand.java:65) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.callActionMethod(MVCPortlet.java:402) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.LiferayPortlet.processAction(LiferayPortlet.java:88) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.processAction(MVCPortlet.java:256) ~[portal-kernel.jar:?]
	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:77) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:50) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115) ~[portal-kernel.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:63) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
	at com.liferay.portlet.internal.InvokerPortletImpl.invoke(InvokerPortletImpl.java:570) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.InvokerPortletImpl.invokeAction(InvokerPortletImpl.java:610) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.InvokerPortletImpl.processAction(InvokerPortletImpl.java:287) ~[portal-impl.jar:?]
	at com.liferay.portal.monitoring.internal.portlet.MonitoringInvokerPortlet.processAction(MonitoringInvokerPortlet.java:195) ~[?:?]
	at com.liferay.portlet.internal.PortletContainerImpl._processAction(PortletContainerImpl.java:517) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletContainerImpl.lambda$processAction$0(PortletContainerImpl.java:148) ~[portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletContainerImpl._preserveGroupIds(PortletContainerImpl.java:421) [portal-impl.jar:?]
	at com.liferay.portlet.internal.PortletContainerImpl.processAction(PortletContainerImpl.java:141) [portal-impl.jar:?]
	at com.liferay.portlet.SecurityPortletContainerWrapper.processAction(SecurityPortletContainerWrapper.java:92) [portal-impl.jar:?]
	at com.liferay.portlet.RestrictPortletContainerWrapper.processAction(RestrictPortletContainerWrapper.java:72) [portal-impl.jar:?]
	at com.liferay.portal.kernel.portlet.PortletContainerUtil.processAction(PortletContainerUtil.java:117) [portal-kernel.jar:?]
	at com.liferay.portal.action.LayoutAction.processLayout(LayoutAction.java:368) [portal-impl.jar:?]
	at com.liferay.portal.action.LayoutAction.execute(LayoutAction.java:174) [portal-impl.jar:?]
	at com.liferay.portal.struts.PortalRequestProcessor._process(PortalRequestProcessor.java:395) [portal-impl.jar:?]
	at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:151) [portal-impl.jar:?]
	at com.liferay.portal.internal.servlet.MainServlet.doPost(MainServlet.java:208) [portal-impl.jar:?]
```
image
**Step to reproduce**

1. Add a new fragment using colorPalette example codes
2. Add the new fragment to content page
3. Configure the color

**Comment by victorg1991** [comment]
Thanks @Tim-Cao Let's see now

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
