### PR TITLE
LPS-169842 Replace liferay liferay-ui:icon-menu with clay:dropdown-menu in portlet_header.jsp

### PR DESCRIPTION
**Pull request by DiegoHu97**

### CODE REVIEW

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/10515

**Pull request closed without merging**
