### PR TITLE
LPS-198912 Unify behavior for web content titles when copying

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-198912)

## Test scenario 1

1. Create a Web Content
2. Copy the same WC a few times and check the names

https://github.com/liferay-echo/liferay-portal/assets/93203423/c08c5601-a864-47ac-9cc5-4ad300550a8c

### CODE REVIEW

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Review by lfbesada — APPROVED** [review]
very nice :heart_eyes:

**Comment by lfbesada** [comment]
ci:forward

**Comment by BarbaraCabrera** [comment]
ci:test:stable

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142430

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
