### PR TITLE
LPS-140302 Fix: Site initializer fails to process fragments in pages when virtual instance is created with Portal Instance API

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-141140

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1327401_2830

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
