### PR TITLE
LPS-148997 Fix false positives in tests due to orphan ResourcePermission - Echo team - LPS-145396 Subtask

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
In parent LPS-145396 I am going to add some changes in DataGuardTestRule to detect orphan ResourcePermission records, avoiding the bug in the future.

In this LPS I am fixing some false positives in tests for Echo team code.

The false positives are caused because we call LocalServiceBaseImpl delete methods instead of calling the LocalServiceImpl ones.

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
ci:forward

**Pull request closed without merging**
