### PR TITLE
LPS-142720 | master 

### PR DESCRIPTION
**Pull request by veroglez**
https://issues.liferay.com/browse/LPS-142720

This is only for master.

@Tim-Cao

### CODE REVIEW

**Comment by veroglez** [comment]
Hi @Tim-Cao! I have added a new commit solving the problem you found. Can you give a second check that everything works correctly?

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @veroglez, could you double check an issue?
The defined color of fragment doesn’t work.
Add a Heading fragment
Change the Text Color to Success
The Text Color doesn’t change

**Comment by veroglez** [comment]
Hi @Tim-Cao, I already added the fix for the issue you found about the fragment color not working

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7363

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
