### PR TITLE
LPS-135294 Adapt tests

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @victorg1991, there is a regression issue, The user with Update Layout Content permissions cannot change the mapping content.
Step to reproduce
Add a web content
Add a content page
Add a Heading fragment
Map the Title field to editable field
Change to Content Editing mode

Expected: The Mapping panel should be shown.
Actual: The Mapping panel is missing.
image

**Comment by Tim-Cao** [comment]
Hi @victorg1991, the device viewport buttons are missing in non-desktop device viewport.
image

**Comment by victorg1991** [comment]
Should be fine now

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
