### PR TITLE
LPD-17364 Collection Displays can reference Exporting site's content

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
Collection Displays can reference Exporting site's content when there is a navigation menu referencing the page the Collection Display is on.
https://liferay.atlassian.net/browse/LPD-17364

Proposed Solution
========
Make the ContentProcessor to import the referred AssetListEntry if it hasn't already been imported so that it can replace its classPK

Steps to Verify
========
1. Create a site “Source”
2. Create dynamic collection “Test Collection” displaying “Web Content Article” and sub type “Basic Web Content”
3. Create Basic Web Content with title and content -> “TEST-1”
4. Create a Navigation Menu “Test menu”
5. Create a new Collection Page ”Home”:
6. When creating the page, check Add ‘Home” to the menu 'Test menu’
7. Select the "Test Collection" collection
8. Add a heading fragment and map the heading to the Title field
9. Publish and view the page, you should see “TEST-1”
10. Export the site through Publishing -> Export
11. Create a new Blank site “Target” and import the lar from previous step (Publishing -> Import)
12. Access to the home page and check the “TEST-1” content
13. Modify the “TEST-1” content’s title in the original site (“Source”) to “TEST-2”
14. Reload “Target” homepage

**Expected behaviour:** TEST-1 is displayed as the content in this site was not changed.
**Actual behaviour:** The page displays “TEST-2” from the “Source” site.

Cheers,
Balázs

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
