### PR TITLE
LPS-178332 Remove feature flag -> Utility Pages application: error pages, terms and conditions

### PR DESCRIPTION
**Pull request by jkappler**
https://issues.liferay.com/browse/LPS-178332

Remove FF from the code and tests

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
@Tim-Cao, @david-gutierrez-mesa, unsure if I removed the code correctly in the poshi tests, can you please take a look? Thanks!

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by david-gutierrez-mesa** [comment]
LGTM @jkappler

**Comment by ealonso** [comment]
Hey @jkappler,
There is a conflict, Could you please fix it? I think the tests failures are unrelated with this pr, so we can send it directly to Brian once we fix the conflict.

**Comment by Tim-Cao** [comment]
Hi @jkappler, the failure case is related to this PR, but not a regression issue. We could forward this one, then they will fix the broken tests.

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131632

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
