### PR TITLE
LPS-180473 Change shared and title_editor components to functional components

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://issues.liferay.com/browse/LPS-180473)

## Steps 

1. Go to Product Menu > People > Segments
2. Create a Segment
3. Click on the language flag (case 1)
4. Edit segment name (case 2)

Screenshot 2023-04-13 at 10 22 26

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
@sandrodw3 Updated!

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
Closing this as it has been merged in https://github.com/liferay-echo/liferay-portal/pull/11735 to solve conflicts

**Pull request closed without merging**
