### PR TITLE
LPS-147440 Migrate "Welcome" Site Initializer to use Extender

### PR DESCRIPTION
**Pull request by jkappler**
Dear Team ❤️ 

with this PR the site initializer for the welcome pages uses the new framework. There are two ways to test this.

1. After deploying the modules, start a Liferay Instance with a clean DB. The Home Page should be shown correctly
2. When creating a new site, you can now select the Liferay Site Initializer Welcome as template

Screenshot 2022-05-19 at 09 38 23

Please let me know what you think.

Thanks!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:reopen

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
