### PR TITLE
LPS-172659 Hide layouts tree icon if the user doesn't have permissions

### PR DESCRIPTION
**Pull request by victorg1991**
Not sure about whether we should use `MANAGE_LAYOUTS` permissions or other, that one seemed good enough. Also I thought about unifying the case where we want to disable the pages tree and the case where it should be hidden, but It makes sense to keep both. The disabled state show the user that the button will be enabled eventually where as hiding it doesn't give any clue to the user

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @victorg1991, cannot search in Page Tree
Step to reproduce

1. Navigate to the Page Tree in guest site
2. Type Home in search bar

The page tree become blank
The following error is thrown in browser console.
```
0:2 Uncaught TypeError: Cannot read properties of undefined (reading 'getAttribute')
    at getId (0:2:4393)
    at 0:2:2116
    at Ui (0:2:79067)
    at lk (0:2:103491)
    at U.unstable_runWithPriority (0:2:121544)
    at fg (0:2:46759)
    at Sj (0:2:103254)
    at Lj (0:2:88499)
    at 0:2:47050
    at U.unstable_runWithPriority (0:2:121544)
```

**Comment by Tim-Cao** [comment]
@victorg1991 Sorry, this also happens on master.

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137801

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
