### PR TITLE
LPS-119128 Change order of the upgrade process since UpgradeSQLServer reads a column that is created in UpgradeSchema. There shouldn't be a problem changing the order since it was release at the same time.

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@ealonso

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:test:stable

**Pull request closed without merging**
