### PR TITLE
LPS-126821, et al. | Master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-126821
https://issues.liferay.com/browse/LPS-126850
https://issues.liferay.com/browse/LPS-126844
https://issues.liferay.com/browse/LPS-126855
https://issues.liferay.com/browse/LPS-126852
https://issues.liferay.com/browse/LPS-126853
https://issues.liferay.com/browse/LPS-126825
https://issues.liferay.com/browse/LPS-126857
https://issues.liferay.com/browse/LPS-126834
https://issues.liferay.com/browse/LPS-126849
https://issues.liferay.com/browse/LPS-126833
https://issues.liferay.com/browse/LPS-126908
https://issues.liferay.com/browse/LPS-126909
https://issues.liferay.com/browse/LPS-126906
https://issues.liferay.com/browse/LPS-126890
https://issues.liferay.com/browse/LPS-126797
https://issues.liferay.com/browse/LPS-126792
https://issues.liferay.com/browse/LPS-126904
https://issues.liferay.com/browse/LPS-126906
https://issues.liferay.com/browse/LPS-127171
https://issues.liferay.com/browse/LPS-127160
https://issues.liferay.com/browse/LPS-127161
https://issues.liferay.com/browse/LPS-126897
https://issues.liferay.com/browse/LPS-126825
https://issues.liferay.com/browse/LPS-126806
https://issues.liferay.com/browse/LPS-126822
https://issues.liferay.com/browse/LPS-126853
https://issues.liferay.com/browse/LPS-126823
https://issues.liferay.com/browse/LPS-126893
https://issues.liferay.com/browse/LPS-126894
https://issues.liferay.com/browse/LPS-126254
https://issues.liferay.com/browse/LPS-126257
https://issues.liferay.com/browse/LPS-126393
https://issues.liferay.com/browse/LPS-126280
https://issues.liferay.com/browse/LRQA-64740

This is only for master.

@david-gutierrez-mesa
@austinchiang
@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
ci:test:sf

**Comment by austinchiang** [comment]
ci:forward

**Comment by austinchiang** [comment]
ci:stop

**Comment by austinchiang** [comment]
Since this pull was already merged by BChan we can close it. But i'll run `ci:test:relevant` just to have some closure on the results

**Comment by austinchiang** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @austinchiang, the failure cases are not related to our changes. Either bug or test fix.

**Comment by austinchiang** [comment]
ci:close

**Pull request closed without merging**
