### PR TITLE
LPS-167465 Add the isEmbeddedPersonalApplication method to the Layout and use it instead of multiple private and protected methods

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-167465

See: https://github.com/brianchandotcom/liferay-portal/pull/125970#issuecomment-1308866696

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Whether this last attemp also fails I will manually send it.

**Comment by ozysouza** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/126071

**Pull request closed without merging**
