### PR TITLE
LPS-162044 Prepare frontend to send data to server

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:stop

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:forward

**Comment by ozysouza** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/122827

**Pull request closed without merging**
