### PR TITLE
LPS-136127 Move discard action

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
rebased and fixed the conflicts

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @victorg1991, there is a regression issue. Coudl you have a loot at?
The user shouldn't be allowed to delete the pages inherited from site template.
The expected behavior looks like following video.
Expected
The actual behavior is
image

**Comment by victorg1991** [comment]
Thanks tim, checking :)

**Comment by victorg1991** [comment]
should be fixed now @Tim-Cao

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @victorg1991, according to [ci:test:echo](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1627484775512&testrayRunIdA=1549949658&testrayRunIdB=1549997616) results, no regression issue found.

**Comment by Tim-Cao** [comment]
The failure case is unrelated to this PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/104868

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
