### PR TITLE
LPS-147323 Update properties panel styles

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Labeling this as on hold because some of the changes are not under FF

**Comment by p2kmgcl** [comment]
Looks awesome. I am going to try that CSS loading on a slower computer :evil-parrot:

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7227

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
