### PR TITLE
LPS-145232 Search field in the frontend first by key and then by name

### PR DESCRIPTION
**Pull request by victorg1991**
I'm opening this here for feedback about the things that affect echo team. There is still pending work for adapting translations to these changes.

### Related tickets
- https://issues.liferay.com/browse/LPS-145232
- https://issues.liferay.com/browse/PTR-2847

### What's the goal of this PR

This PR adds a mandatory builder step in `InfoField` class that require to add an uniqueId. Also in `InfoItemFieldValues` it takes into account the name and it search first by id and then by name. This way stored info field names will still work. Also in the page editor we take into account old names to show the mapping selector and the mapping information correctly for pages created before this change.

### Some questions

- Should we make the builder step optional? This is a breaking change. It will force implementors to take into account, so in my opinion it is fine to make this breaking change, but I believe is debatable.
- Do you think current uniqueId are unique enough? I have used the model class simple name which I think it is enough but I want to hear more opinions about that :P

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Sent to adolfo for review here: https://github.com/adolfopa/liferay-portal/pull/1464

**Pull request closed without merging**
