### PR TITLE
LPS-121078 Remove not needed propType

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by jpince** [comment]
A lot of these failures like this:
```
     [exec] com.liferay.layout.uad.anonymizer.test.LayoutRevisionUADAnonymizerTest > testAutoAnonymize FAILED
     [exec]     com.liferay.portal.kernel.exception.NoSuchLayoutException: No Layout exists with the primary key 0
```

**Comment by jpince** [comment]
I verified the UAD test failures are also occurring in upstream. This was the only one that was unique (not failing in upstream):
```
     [exec] com.liferay.layout.type.controller.test.LayoutTypeURLTest > testGetRegularURLLayoutTypeURL FAILED
     [exec]     com.liferay.portal.kernel.exception.LayoutTypeException
     [exec]     	at com.liferay.portal.service.impl.LayoutLocalServiceHelper.validateFirstLayout(LayoutLocalServiceHelper.java:328)
     [exec]     	at com.liferay.portal.service.impl.LayoutLocalServiceHelper.validate(LayoutLocalServiceHelper.java:279)
     [exec]     	at com.liferay.portal.service.impl.LayoutLocalServiceImpl.addLayout(LayoutLocalServiceImpl.java:308)
     [exec]     	at com.liferay.portal.service.impl.LayoutLocalServiceImpl.addLayout(LayoutLocalServiceImpl.java:552)
     [exec]     	at com.liferay.portal.service.impl.LayoutLocalServiceImpl.addLayout(LayoutLocalServiceImpl.java:617)
     [exec]     	at com.liferay.portal.service.impl.LayoutLocalServiceImpl.addLayout(LayoutLocalServiceImpl.java:760)
     [exec]     	at com.liferay.portal.service.impl.LayoutLocalServiceImpl.addLayout(LayoutLocalServiceImpl.java:822)
```

I asked Brian Chan to pull this branch so we can move forward with building. Please send a follow-up pull request

**Comment by victorg1991** [comment]
@jpince That erro doesn't seem related to this change so this is good to go :)

**Comment by brianchandotcom** [comment]
I manually merged this as @jpince asked me to.

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
