### PR TITLE
LPS-154986 Hide theme configuration if a custom layout is selected

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
@Tim-Cao I have fixed the regression from https://github.com/liferay-echo/liferay-portal/pull/8290 but I think I am missing some poshi commits. Please tell me if I have to cherry-pick something else :pray:

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, there is another regression.
Edit Master shouldn't be avaiable to Blank.
image

**Comment by p2kmgcl** [comment]
don!

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/8371

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
