### PR TITLE
LPS-187076 Try again to fix navigation menus dnd

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
Alt Text

**Comment by p2kmgcl** [comment]
@sandrodw3 I have only added one more commit to create an invisible layer that makes the drop target huge during dnd, something like this:

image

I don't remember if we discussed more things about the dnd process :sweat_smile:

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by alessandromalves** [comment]
The failures are not related to this PR. See https://github.com/brianchandotcom/liferay-portal/pull/137110

**Comment by alessandromalves** [comment]
ci:close

**Pull request closed without merging**
