### PR TITLE
LPS-114731 Separate into interface and base class

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Since failure cases related to ci issue and in order to not clog up ci resources I pushed directly to BChan.
See https://github.com/brianchandotcom/liferay-portal/pull/92277

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
