### PR TITLE
LPS-195366 Add Copy Action for the Display Pages

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-195366)

## Proposed solution

Add Copy Action for the Display Pages.

## Test Scenario 

1. Go to Page Templates > Display Page Templates.
2. Create a new Display Page Template. 
3. Go to the kebab menu and click on copy.
4. Check that the behaviour for the copy action is correct. 

https://github.com/liferay-echo/liferay-portal/assets/93203423/449ef7a4-ebf4-4d0e-afda-f01ed21fefe7

### CODE REVIEW

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:stable

**Comment by ealonso** [comment]
ci:test:stable

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140437

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
