### PR TITLE
LPS-172007 Replace liferay-ui:icon

### PR DESCRIPTION
**Pull request by veroglez**
https://issues.liferay.com/browse/LPS-172007
https://issues.liferay.com/browse/LPS-172008
https://issues.liferay.com/browse/LPS-172010
https://issues.liferay.com/browse/LPS-172011
https://issues.liferay.com/browse/LPS-171952
https://issues.liferay.com/browse/LPS-171971
https://issues.liferay.com/browse/LPS-171974
https://issues.liferay.com/browse/LPS-172006

cc @victorg1991 @ealonso @BarbaraCabrera

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128394

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
