### PR TITLE
LPS-179120 Only ‘Success:’ displays after changing default language in category

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
[Link to ticket](https://issues.liferay.com/browse/LPS-179120)

## Test Scenario
- Go to Configuration > Site Settings > Localization
- Change default language to Spanish
- Add a vocabulary
- Add a category, name it cat1
Note: Check the success message when creating the category.
image

- Edit the category.
Note: Check the success message when update the category.
image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Looks awesome @BarbaraCabrera! ❤️

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
