### PR TITLE
LPS-153830 Get the higher UPDATE permission and toggle this one instead of always using UPDATE

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:reevaluate:135null_1576

**Comment by ozysouza** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
Hey @ozysouza I am going to merge this pr with other related task :)

**Comment by victorg1991** [comment]
I have sent it here: https://github.com/liferay-echo/liferay-portal/pull/8137

**Comment by ozysouza** [comment]
> Hey @ozysouza I am going to merge this pr with other related task :)

Nice then! :partying_face:

**Pull request closed without merging**
