### PR TITLE
LPS-119582 - Reindexing all index searches loses all the content from Content Pages

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @pavel-savinov

After the changes in this PR:
- Searching behaves consistently after a Content Page is published and after Reindex takes place.
- Content of widgets is not longer indexed when the page is published as part of the Page (we assume that widgets are in nature dynamic, and the content rendered by the widget when the page is published or after a reindex, does not necessarily match the content that would be rendered when the search takes place, which could result in confusing behaviour)

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:stop

**Comment by ruben-pulido** [comment]
https://github.com/liferay-echo/liferay-portal/pull/2271

**Pull request closed without merging**
