### PR TITLE
LPS-166547 Adds necessary cssClass

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
@Tim-Cao Fixed both regressions, we are still facing the problem described by @ozysouza, but for that one I need the frontend people to fix it.

Also, I've already fix the typo @ethib137

Could you please guys take a look to poshi failures?

Thanks!!

**Comment by ozysouza** [comment]
ci:test:sf

**Comment by ozysouza** [comment]
ci:test:relevant

**Comment by ozysouza** [comment]
ci:test:echo

**Comment by ozysouza** [comment]
There are some poshi tests to fix. I've already sent a message to Tim explaining the failures.

Also, once the devs are taking care of the regression issue on content page, the ellipsis icon seems to be misaligned too.
Selection_012

**Comment by victorg1991** [comment]
Resent here with the content pages issue fixed: https://github.com/liferay-echo/liferay-portal/pull/10124 I cannot reproduce the misalignement of the icon though

**Pull request closed without merging**
