### PR TITLE
LPS-134358

### PR DESCRIPTION
**Pull request by victorg1991**
## What is included in this PR
Allow users to nest a collection display within a collection display

## How to test this:
- Deploy the configuration file attached in https://issues.liferay.com/browse/LPS-134361
- Create a couple of collections and try to nest those
- For the nested collection the item selector to choose a collection should include the related collection providers, which allow to select a related collection for the item of the outer collection being rendered.

## What is out of this PR
Drag and drop will work fine both in page structure and the page editor itself. The only problem is that you cannout move an item from inside the collection to the outside, but this will be tackled in another subtask

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by sandrodw3** [comment]
Watchmaker job 👌🏽😄

**Comment by sandrodw3** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
