### PR TITLE
LPS-179500 Add description to breadcrumb template setting

### PR DESCRIPTION
**Pull request by Mikellorza**
[Link to the story](https://issues.liferay.com/browse/LPS-179500)

Motivation
=======
Add description to breadcrumb template setting.

Proposed Solution
========
Create a description for the setting.

Steps to Verify:
----------------
 Go to System Settings > Breadcrumbs > Breadcrumb Template to see the description.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:close

**Pull request closed without merging**
