### PR TITLE
[TS] lps-200683

### PR DESCRIPTION
**Pull request by crodriguezy**
Hello team, this commit fixes the case described in https://liferay.atlassian.net/browse/LPS-200683, observed by a customer within their prod environment, so it's quite urgent for them:

1. Define Check Interval value to 1 in _System Properties -> Web Content -> Virtual Instance Scope -> Web Content -> Check Interval_
2. Create a display page template for basic web contents
3. Add a new basic web content 'test':

> - Select the dpt created previously
> - Select the display date to 2 minutes later.

5. Wait until the article is approved.
6. Check article's friendly URL. In my case: localhost:8080/web/guest/w/test

**Expected result:** the page is shown

**Current result:** a not found 404 page is shown.

*If you publish manually the article or you click on the preview option from the dpt section, the above URL shows the article correctly.

Since AssetDisplayPageEntry table shows a plid = 0 for the entry related to the article even after it being approved, I considered that updating its assetDisplayPageEntry (if any), just like it's done when adding a draft or publishing it directly, could be an option. I'm not sure this is the best or most efficient way  to achieve the expected result, so please let me know if you need me to rethink this.

Thanks in advance :)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
Hi @crodriguezy, thanks for sending us the PR, already taking a look.

I'm just concerned that the proposed fix won't solve the root problem, since all web contents that have passed that point will still be inconsistent.

The best would be to change the logic in AssetDisplayPageEntryLocalServiceImpl when retrieving the plid, to make it consistent, and add an upgrade process to fix all the entries in the table.

I will try to send this today since as you mentioned, it's urgent for them.

Regards.

**Comment by crodriguezy** [comment]
Thank you very much @jkappler , that makes much more sense than my proposed solution. 
Let me know if I can be of any help :)

**Comment by jkappler** [comment]
@crodriguezy, please see https://github.com/liferay-echo/liferay-portal/pull/14213 and let me know if you have any doubts about it

**Pull request closed without merging**
