### PR TITLE
LPS-194235 Fix backURL

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Only two unique failures were found by the CI ([comparison with acceptance routine here](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1692810341054&testrayRunIdA=2410970934&testrayRunIdB=2411250456)) and were not reproducible locally. The others are not related to this PR. See https://github.com/brianchandotcom/liferay-portal/pull/139625

**Comment by alessandromalves** [comment]
ci:close

**Pull request closed without merging**
