### PR TITLE
LPS-159619 Change dropzone message

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-159619 add language key
- LPS-159619 buildLang
- LPS-159619 change message usages
- LPS-159619 update Poshi tests
- LPS-159619 Update usages

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@Tim-Cao, form container maintains the label as we mentioned "Place fragments here", while we change the root message to "Place fragments or widgets here"

**Comment by jkappler** [comment]
@DiegoHu97 👏

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
