### PR TITLE
LPS-195024 Convert old AUI to new js in product_navigation_control_menu.js

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-195024

@DiegoHu97
cc @liulukiwi

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Hi @DiegoHu97, Could you help us to find which js file could indicate the buttons are loaded completely?
Before this change, /o/frontend-js-aui-web/liferay/menu_toggle.js could indicate. The current poshi changes will make poshi tests unstable. I added on-hold label until we fix the unstable issue. Otherwise, the changes will block other PRs.

**Comment by DiegoHu97** [comment]
Hey @Tim-Cao, I don't understand your question very well. I haven't changed menu_toggle.js, if that was the js that indicates the component loaded, you can still use menu_toggle.js for that, isn't it?

**Comment by Tim-Cao** [comment]
Hi @DiegoHu97,
The /o/frontend-js-aui-web/liferay/menu_toggle.js is gone with your changes.
**Step to reproduce**

1. Sign In
2. Navigate to the Home page
3. Inspect the page element
4. Search menu_toggle.js

Would you mind checking?

**Comment by DiegoHu97** [comment]
@Tim-Cao I'm taking a look to it, thanks!

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:help

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional

**Comment by Tim-Cao** [comment]
Current solution didn't work

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by victorg1991** [comment]
resent here: https://github.com/liferay-echo/liferay-portal/pull/13889

**Pull request closed without merging**
