### PR TITLE
LPS-184966 | Apply Styling to "Copy To" page in Docuents and Media for Folders

### PR DESCRIPTION
**Pull request by jaimelr10**
**Description:** Apply styling to the page for copying a folder in documents and media

**Jira Ticket:** https://issues.liferay.com/browse/LPS-184966

### CODE REVIEW

**Review by lfbesada — APPROVED** [review]
Hi @jaimelr10 
Thanks for the pull request!
The backend part LGTM!
Regards

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Ey @jaimelr10 just a minor comment to take advantage of the pr an remove usages of aui taglibs :D

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
