### PR TITLE
[TS] LPS-128092 | Sort order does not persist in the web content history

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?

I modified the previous implementation to be more in line with the pattern from AssetBrowserDisplayContext.getOrderByType().

Also, the setValue call in the PortalPreferencesImpl uses the retryableStore method which will store the portal preferences in the DB.

Thank you!

brianchandotcom#99014
#3787

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
ci:stop

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
