### PR TITLE
LPS-111657 - Container layout that allows saving custom made fragment compositions visually

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @jkappler @p2kmgcl

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:stop

**Comment by ruben-pulido** [comment]
https://github.com/liferay-echo/liferay-portal/pull/1397

**Comment by ruben-pulido** [comment]
ci:close

**Pull request closed without merging**
