### PR TITLE
LPS-149490 Add icons to Style Book, Fragment, Page Template and Style Books

### PR DESCRIPTION
**Pull request by DiegoHu97**
Removed rename icons

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @victorg1991, Would you mind double check why change the download icon to upload icon for Export action?
It doesn't make sense. I also doubt the figma might be wrong 
image
They conflict with common sense.
Shouldn't use download icon for Export action?
image

**Comment by DiegoHu97** [comment]
Hello @Tim-Cao, we have spoken to the designers and they have told us that this icon is fine. It seems reasonable to me, because at the portal level, if you export something, you export it out of the portal. Also, if we leave the "download" button, it would conflict with the new icon associated with the "import".

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
I see. Thanks @DiegoHu97

**Comment by Tim-Cao** [comment]
Hi @DiegoHu97, shouldn't change the Icon#EXPORT until all usages are replace by new icon.
For example, this one still use previous icon but invoke Icon#EXPORT
image

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7576

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
