### PR TITLE
LPS-179486 Reorganize content for layout sets configuration

### PR DESCRIPTION
**Pull request by sandrodw3**
## Description

- Changes are applied in layout sets configuration (Site Builder > Control Menu three dots menu > Configuration

image

- We have reorganized the content of this view so it looks like this:

image
image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
The related failures will only need a test fix. See https://github.com/liferay-echo/liferay-portal/pull/11805

**Pull request closed without merging**
