### PR TITLE
LPS-114119 Moves to display context

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
ci:stop

**Comment by pavel-savinov** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
Just estarted reviuing (:

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/1223

**Comment by p2kmgcl** [comment]
ci:close

**Pull request closed without merging**
