### PR TITLE
LPS-148422 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LPS-148422

This is only for master.

@ealonso
@veroglez
@david-gutierrez-mesa 
@Tim-Cao

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
