### PR TITLE
LPS-150260 Add icons to Tags's drop-down

### PR DESCRIPTION
**Pull request by DiegoHu97**

### CODE REVIEW

**Comment by victorg1991** [comment]
👏

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Let's see now with a magical rebase 🤔

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Both poshi failure cases are unrelated to changes
@ealonso
@victorg1991
@DiegoHu97

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115239

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/115239

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
