### PR TITLE
LPS-181931 - Use externalReferenceCode instead of assetCategoryIds when referencing categories

### PR DESCRIPTION
**Pull request by ruben-pulido**
Steps to Verify
========

```
curl -s -X POST http://localhost:8080/o/headless-delivery/v1.0/sites/20119/site-pages -d @site-page-taxonomyCategoryBriefs.json -H 'X-Liferay-Accept-All-Languages: true' -H 'Content-Type: application/json' -u test@liferay.com:test
```

where site-page-taxonomyCategoryBriefs.json is a file with the following content:

```
{
  "title": "My Page",
  "taxonomyCategoryBriefs": [
    {
      "taxonomyCategoryReference": {
        "externalReferenceCode": "8240a11d-7784-ae49-047c-96607f109196"
      }
    },
    {
      "taxonomyCategoryReference": {
        "externalReferenceCode": "c2558ef8-ec64-3af2-343d-886d218eddf4",
        "siteKey": "20096"
      }
    },
    {
      "taxonomyCategoryReference": {
        "externalReferenceCode": "f1a6d2ea-9a36-2450-2d89-14b1288e4c11",
        "siteKey": "Asset Library 1"
      }
    }
  ]
}
```

creates a new page associating the specified categories (provided they exist).

Each taxonomyCategoryBrief now also includes a taxonomyCategoryReference as follows:

```
  "taxonomyCategoryBriefs": [
    {
      "taxonomyCategoryId": 44162,
      "taxonomyCategoryName": "Guest Site Category One",
      "taxonomyCategoryName_i18n": {
        "en-US": "Guest Site Category One"
      },
      "taxonomyCategoryReference": {
        "externalReferenceCode": "8240a11d-7784-ae49-047c-96607f109196",
        "siteKey": "Guest"
      }
    },
    {
      "taxonomyCategoryId": 44170,
      "taxonomyCategoryName": "Topic Category One",
      "taxonomyCategoryName_i18n": {
        "en-US": "Topic Category One"
      },
      "taxonomyCategoryReference": {
        "externalReferenceCode": "c2558ef8-ec64-3af2-343d-886d218eddf4",
        "siteKey": "20096"
      }
    },
    {
      "taxonomyCategoryId": 44180,
      "taxonomyCategoryName": "Asset Library 1 Category 1",
      "taxonomyCategoryName_i18n": {
        "en-US": "Asset Library 1 Category 1"
      },
      "taxonomyCategoryReference": {
        "externalReferenceCode": "f1a6d2ea-9a36-2450-2d89-14b1288e4c11",
        "siteKey": "Asset Library 1"
      }
    }
  ],
```

//cc @jkappler @ealonso

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
@jkappler I've simplified the logic, deprecated taxonomyCategoryIds and taken into account the feature flag when returning TaxonomyCategoryReference here https://github.com/liferay-echo/liferay-portal/pull/12031

**Pull request closed without merging**
