### PR TITLE
[TS] LPS-149557

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This is a fix for a scenario of embedded portlets via <lfr-widget-*> tags in fragment-based pages under Staging with Page Versioning enabled.

When the PortletFragmentEntryProcessor processes the portlet preferences of this kind of portlets, it updates the layout's portlet preferences with the default ones if needed, but when Page Versioning is enabled Layout Revisions are returned and their related portlet preferences have to be updated with the layout's portlet preferences.

Could you please review it?

Please, let me know if you need further clarifications.

Thanks!

https://issues.liferay.com/browse/LPS-149557

\cc @noornajj

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @dacousalr @noornajj
I am trying to reproduce the behavior reported in the related ticket and I don't see that behavior. In my tests on the master branch, it seems to work properly without applying the fix.  
I think there is some step I am not doing properly, maybe I misunderstand the described steps.
Could you please check this video with my test in the master branch?
It would be great if you head me up about what I am doing wrong.
Thanks a lot!
Regards

https://user-images.githubusercontent.com/84471361/163128328-2ce8ea81-b303-4957-9492-f0cededa715e.mov

**Comment by noornajj** [comment]
@lfbesada I was not able to reproduce on latest master either. Looks like the issue was fixed in between finding the solution and sending this PR

**Comment by lfbesada** [comment]
Hi @noornajj 
Thanks for the feedback!
I am going to close the PR and the bug because is no longer reproducible.
Thanks!
Regards

**Pull request closed without merging**
