### PR TITLE
LPS-145046 - Add fragment collection option to item selector

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @p2kmgcl @victorg1991

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ruben-pulido, the same issue happens with previous one https://github.com/liferay-echo/liferay-portal/pull/7016#issuecomment-1019878753

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/7046

**Pull request closed without merging**
