### PR TITLE
LPS-169017 Cannot import LAR file with circular dependencies

### PR DESCRIPTION
**Pull request by moltam89**
Hey guys,

I created example steps on [LPS-169017](https://issues.liferay.com/browse/LPS-169017), however I think there should be a lot of ways to trigger this problem, even with widget pages.

Importing the attached LAR results in a "circular reference" problem, the import process looks something like this:
Import journal -> child1 -> child1  draft -> **parent** -> parent draft -> journal -> child2 -> child2 draft -> **parent**.
At this point, the parent page hasn't been saved yet, and a NullPointer is thrown.

The fix is a lot simpler than the reproduction steps, we can get the parent layout from the layouts map, which already contains the correct values.

Let me know if you have any questions.

Best,
Tamas

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
