### PR TITLE
LPS-186128 Use same state for handling open in search results

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by claraizquierdo — CHANGES_REQUESTED** [review]
We should keep which tabs where open and close before the serach instead of leaving all of them opened.

**Review by claraizquierdo — APPROVED** [review]
Great job @sandrodw3 ! More elegant and functional :)

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward:force

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/135711

**Pull request closed without merging**
