### PR TITLE
LPD-31288 Adapt collections for multi-selection

### PR DESCRIPTION
**Pull request by veroglez**
Collections have been adapted to have several active elements.

The following has also been fixed:
- When deleting an item, its previous sibling is selected, if it doesn't have one, its parent is selected.
- When adding an item to a collection, the first item is always selected
- When deleting the last item within a collection, the content display is selected
- Avoid calling selectItem() when clicking on any button on the topper

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by sandrodw3 — COMMENTED** [review]
Hey @veroglez nice work! :clap:

I left a suggestion regarding the function of first commit, and also as I told you, I tried to find a way to avoid adding a new hook, I sent it to you [here](https://github.com/veroglez/liferay-portal/pull/148). Please let me know what you think 😄

**Comment by sandrodw3** [comment]
ci:test:page-management

**Comment by sandrodw3** [comment]
:candle:

**Comment by ealonso** [comment]
ci:test:page-management

**Comment by veroglez** [comment]
ci:test:page-management

**Comment by veroglez** [comment]
ci:test:page-management

**Comment by veroglez** [comment]
ci:stop

**Comment by veroglez** [comment]
ci:test:page-management

**Comment by veroglez** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:forward:force

**Pull request closed without merging**
