### PR TITLE
LPS-163785 Check GUEST view permission before using LayoutCrawler

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
[LPS-163785](https://issues.liferay.com/browse/LPS-163785)
Given a public Content Page
When its GUEST view permission is removed
Its content is no longer indexed via the LayoutCrawler

Proposed Solution
========
Extend the condition of using the LayoutCrawler to exclude Layouts with no GUEST view permission so that the return statement at the end of the LayoutCrawler block will not trigger for un-crawlable public pages.

Steps to Verify
========
1. Add a content page with the title "Testpage" and add a paragraph fragment
2. Add the text "lorem ipsum" to the paragraph and publish the page
3. Search for the text "lorem"
4. The page "Testpage" is found
5. Edit the permissions of the "Testpage" and remove the view permission for the Guest role
6. Edit the "Testpage" and make any change so you can publish it again (e.g adding a space to the paragraph fragment)
7. Publish the page
8. Search for the text "lorem"

Expected behaviour: The page can be found
Actual behaviour: The page is not found

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by ozysouza** [comment]
ci:forward

**Pull request closed without merging**
