### PR TITLE
LPS-200659 Substitute AUI code in upload_multiple_file_entries.jsp

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-199683)

## Changes

Remove not needed AUI() and replace code with JS for edit_folder.jsp and upload_multiple_file_entries.jsp

## Test Scenario 1

1. Go to Content and Data > Documents and Media
2. Upload multiple files
3. Check the behaviour

https://github.com/liferay-echo/liferay-portal/assets/93203423/46497cb3-0ef9-46cd-a22e-bc24cec35b4c

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
Not sure if we should forward this to lima or directly to Brian, I am asking...

**Comment by p2kmgcl** [comment]
Alright I've sent the PR to lima channel so they can have a look

**Comment by p2kmgcl** [comment]
https://github.com/liferay-lima/liferay-portal/pull/4871

**Pull request closed without merging**
