### PR TITLE
LPS-202233 Change Configuration view for KB

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-202233)

## Changes

Change the configuration for Knowledge Base because it should be open in a new page instead of a modal.

> [!NOTE]
> **You need to activate the LPS-197692 FF.**

## Test Scenario 1

1. Go to Knowledge Base
2. Click on the kebab menu in the top right
3. Navigate to the sections to check the behaviour and styles

image

cc:// @BarbaraCabrera

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
@sandrodw3, looks good from backend side, pending your review

**Comment by sandrodw3** [comment]
LGTM 😄

**Comment by jkappler** [comment]
https://github.com/liferay-lima/liferay-portal/pull/5012

**Pull request closed without merging**
