### PR TITLE
[TS] LSP-121651

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @liferay-echo

could you please check my fix?

More details here: https://issues.liferay.com/browse/PTR-1968

Thanks, Roland

https://issues.liferay.com/browse/LPS-121651

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
Looks perfect. Thanks @rolandpakai!

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
