### PR TITLE
Lps 130127

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-130127

Notes from @Noornajj : 

> The issue here is that asset publisher can be filtered by a custom user category that doesn't exist when that category exists under a different vocabulary.
> I fixed this issue by adding a condition to check the vocabulary of the asset category matches that of the user attribute being filtered by. The asset category will only be added to the search query when true.
> 
> **NOTE/INQUIRY:** this fix will result in the behavior acting as if the the custom attribute field is empty. It will not filter the asset entries and will return all results. Is this what the expected behavior for asset publisher should be? Or should the results returned be NONE?
> Please confirm this for me.

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
