### PR TITLE
LPS-167056 The Menu button name and roles are not being announcing correctly

### PR DESCRIPTION
**Pull request by veroglez**
Dear frontend,

One of the requirements for this bug is to add the attribute `aria-modal="true"` to the ClayModal. We can't add it on our own, so I asked Clay about [this](https://github.com/liferay/clay/issues/5199). Just to keep it in mind when reviewing the code.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
