### PR TITLE
LPS-155513 Apply width 100% so the panel always fits sidebar width

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
@ozysouza We are deciding whether to pass this FF or wait a bit. So you can start fixing the tests but not forwarding it for the moment :) 

Many thanks!

**Comment by ozysouza** [comment]
> @ozysouza We are deciding whether to pass this FF or wait a bit. So you can start fixing the tests but not forwarding it for the moment :)
> 
> Many thanks!

Okay @victorg1991! I will let you know once it's done.

**Comment by victorg1991** [comment]
@ozysouza Mateo just confirmed me that we an go ahead with this PR so once the tests are fixed we can forward it :)

**Comment by ozysouza** [comment]
@victorg1991, there is a wrong behavior on Page Content sidebar, when clicking to edit some text the user is redirected to Browser sidebar instead of keeping on Page Content. Should it be fix on this PR or should I create another ticker for it?

https://user-images.githubusercontent.com/72820234/189726221-dddde3e8-63fa-4edf-91f6-5197a557b530.mp4

**Comment by victorg1991** [comment]
should be fixed now @ozysouza :)

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @victorg1991, there is another regression issue found. The Page Content panel is unavailable in Content Editing mode.
The user is allowed to edit the inline content or mapped assets Page Content panel at Content Editing mode, would you mind having a look at?

**Comment by victorg1991** [comment]
Sure thing :)

**Comment by victorg1991** [comment]
I fixed that Mr @Tim-Cao  :)

**Comment by Tim-Cao** [comment]
Thanks @victorg1991

**Comment by Tim-Cao** [comment]
Preview in a new tab doesn't work with Preview Draft page.

**Steps to reproduce**
Add a Heading to content page
Add a new experience
Modify the inline text
Navigate to the Pages admin
Navigate to the Preview Draft page
Select the new experience
Navigate to the page editor via pencil icon
View the selected experience is new experience
Preview in a new tab

**Expected Results**
The displayed content should be in new experience

**Actual Results**
However, the display content is shown in default experience.

**Comment by Tim-Cao** [comment]
Hi @victorg1991, I fixed the rest broken cases with Oziel's commits here. https://github.com/liferay-echo/liferay-portal/pull/9599
I have confidence 99% cases should be fixed.

**Comment by victorg1991** [comment]
Thanks @Tim-Cao I'll create a pr with everything

Many thanks to you @ozysouza too :)

**Comment by victorg1991** [comment]
everything together here: https://github.com/liferay-echo/liferay-portal/pull/9600

**Pull request closed without merging**
