### PR TITLE
LPS-186001 Replace custom sql with DSLQuery in segments-service

### PR DESCRIPTION
**Pull request by YurenaC**
Motivation
=======
In order to take advantage of the cache used in the DSLQueries, we will be migrating several database queries used in finder classes to improve performance

Commits:
=======
- LPS-186001 Migrate to DSLQuery
- LPS-186001 Remove old finder
- LPS-186001 BuildService

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by jkappler** [comment]
semantic versioning seems to be failing

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:stable

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
