### PR TITLE
LPD-17379 | Global Information Template not showing on Display Page Template

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you review this fix?
https://liferay.atlassian.net/browse/LPD-17379
best,
Attila

-----

**Steps to reproduce**

1. Create a Web Content Structure on the global site
2. Create an Information Template for the newly created Web Content Structure on the global site
3. Go to the Default Site
4. Create a Display Page Template for the global Web Content Structure
5. Place a "paragraph" Element on the site and try to map the content with the global Information Template

**Expected Result:** I can select the global Information Template
**Actual Results:** The global Information Template does not show up in the list

The root cause of the issue is that the scope of the structure is not considered at all when the infoItemProviders provides the [templates](https://github.com/liferay/liferay-portal-ee/blob/master/modules/apps/template/template-service/src/main/java/com/liferay/template/internal/info/item/provider/TemplateInfoItemFieldSetProviderImpl.java#L127-L132). My solution is simply to retrieve the structure and search for tempalteEntires in the structure original group as well.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:report:2537189546

**Comment by ealonso** [comment]
ci:forwad:force

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
