### PR TITLE
LPS-112495 Test related assets info list provider

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
https://issues.liferay.com/browse/LPS-112495
Tests for: https://issues.liferay.com/browse/LPS-110191

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by david-gutierrez-mesa** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
