### PR TITLE
LPS-142517 buildLang

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1327401_3387

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, the new feature flag doesn't work according to Poshi report. Would you mind having a look at?

**Comment by ealonso** [comment]
Hey @Tim-Cao,

Could you please let me know why it is not working?

Regards,
Eudaldo

**Comment by Tim-Cao** [comment]
ci:test:bundle

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7746

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
