### PR TITLE
[TS] LPS-161719 | Links to inactive sites in the Breadcrumb Portlet direct to 404 Not Found error

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?

https://issues.liferay.com/browse/LPS-161719

Best,
Attila

------

**Reproduction Steps:**

1. Open the menu on the top right --> Control Panel --> Sites --> Sites and add a blank Site, then add a page to it.
2. Go to Control Panel --> Sites and add a child Site to the created Site by clicking the 3 dot menu beside the parent Site and selecting "Add Child Site".
3. Add a widget page to the child site and add to it Breadcrumb Portlet by clicking on "+" from the top right panel.
4. Go to Control Panel --> Sites and click on the 3 dot menu beside the parent Site and select "Deactivate" to deactivate the parent Site.
5. Go to the Child Site and click on the inactive parent Site link in the Breadcrumb Portlet.

**Actual Result:** A 404 Not Found is displayed because the parent Site is inactive.
**Expected Result:** Inactive Sites should be displayed in the Breadcrumb portlet but not as links.

 Based on https://issues.liferay.com/browse/PTR-3297 I consider it as a bug and fixed it by only adding the URL to the breadcrumb entries if the group is active.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @bakayattila Thanks!!
I have resent it here: https://github.com/liferay-echo/liferay-portal/pull/9508 with a couple of additions :) (nothing really big it was working fine)

**Pull request closed without merging**
