### PR TITLE
LPS-144550 Articles on the default display page do not appear in the sitemap

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-144550

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
We need to cover the case where `xml.sitemap.index.enabled=false` in portal properties
https://github.com/lfbesada/liferay-portal/pull/48

**Comment by lfbesada** [comment]
See: https://github.com/liferay-echo/liferay-portal/pull/6852

**Pull request closed without merging**
