### PR TITLE
LPD-27609 Object attachment field malfunction when cancelling file selection

### PR DESCRIPTION
**Pull request by veroglez**
https://liferay.atlassian.net/browse/LPD-27609

This pull does not include tests since it is not possible to simulate in playwright that the user opens a file browser and presses cancel. This is because the file explorer is native to the operating system and the behavior cannot be simulated in Playwright.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
