### PR TITLE
LPS-191805 Remove unnecessary steps

### PR DESCRIPTION
**Pull request by Tim-Cao**
@Mikellorza

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
Hey @Tim-Cao ,

I have to rethink the solution because is it not valid for the new FF's. But, for sure the solution goes thought enable componente.

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @Mikellorza, Would you mind sending Poshi update together with remove feature flag PR next time? Thanks

**Comment by Mikellorza** [comment]
@Tim-Cao [this](https://liferay.atlassian.net/browse/LPS-191804) was not a remove FF. Only I tried to delete the step to enable the osgi component and associate it to the FF, to avoid forget it and avoid enable it each time when developers restart the server. From now on, only It is necessary to enable the FF and that is all. Next time I will do it.

Thanks!

**Pull request closed without merging**
