### PR TITLE
LPD-23900 Use the correct condition to generate layoutSetFriendlyURL

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you review this fix?
https://liferay.atlassian.net/browse/LPD-23900
best,
Attila

-------

The root cause of the issue is that this condition is not passable. The first half contradicts the statement here:
[PortalImpl.java#L2896-L2897](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/util/PortalImpl.java#L2896-L2897) It's stated to only use the virtual host when the current layoutSet equals the given layoutSet. Yet the code does the exact opposite.
The second condition can only be true if the contextPath is the default ROOT in which case there is no additional contextPath. In any other case, that statement will fail. The themeDisplay.getURLPortal() is only set in one place of the portal: 
[ServicePreAction.java#L1790](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/events/ServicePreAction.java#L1790) As the themeDIsplay.getURLPortal already contains the contextPath even if the original condition would pass that would result in a duplicated context path in the URL. I think the two variables were put in the wrong order here by mistake.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
Hi @bakayattila Thanks for the PR :heart: Could you please add an integration test for this use case? Thanks a lot! Kind regards

**Comment by bakayattila** [comment]
Hi @lfbesada
I will add one or two tests to this pull tomorrow.

**Comment by lfbesada** [comment]
@bakayattila I think this should be fixed by keeping the logic as it was but doing portalURL = portalURL + getPathContext()
Have you tried that solution?

**Comment by bakayattila** [comment]
@lfbesada I have to disagree.  if we add the pathContext to the solution we have to change the logic anyway because it would cause a duplicated pathContext after the if statement in the URL.

**Comment by lfbesada** [comment]
@bakayattila Sorry, I explained myself wrong, I meant to initialize portal URL taking into account the path context, it mean:

```
String portalURL = getPortalURL(
				virtualHostname, themeDisplay.getServerPort(),
				themeDisplay.isSecure()) + _pathContext;
```


And then, inside the if, set initially layoutSetFriendlyURL as portal URL, it is mean:
`
layoutSetFriendlyURL = portalURL;
`

**Comment by bakayattila** [comment]
So we should simplify the logic like this and remove the second condition from the if statement?

	
```
String portalURL = getPortalURL(virtualHostname, themeDisplay.getServerPort(),themeDisplay.isSecure()) + _pathContext;

Layout curLayout = themeDisplay.getLayout();

LayoutSet curLayoutSet = curLayout.getLayoutSet();

long curLayoutSetId = curLayoutSet.getLayoutSetId();

if ((layoutSet.getLayoutSetId() == curLayoutSetId)) {

    String layoutSetFriendlyURL = portalURL;
```

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
Hi @lfbesada I'm done with the changes could you review it?

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
@bakayattila Thank you very much for the tests, very nice :star_struck: I have added some commits to add several unit tests to cover other use cases, please see: https://github.com/liferay-echo/liferay-portal/pull/15579

**Pull request closed without merging**
