### PR TITLE
LPS-113883 Modify case to adapt the current behavior

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
:candle:

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:stable

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:stable

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
sent directly to Brian: https://github.com/brianchandotcom/liferay-portal/pull/90236

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
