### PR TITLE
LPS-166626 Add item title to JSP preview file for non pop_up states

### PR DESCRIPTION
**Pull request by beltranrengifo**
[Story](https://issues.liferay.com/browse/LPS-161020)
[Figma](https://www.figma.com/file/ZpecwjhViyZGsP8hWxqOSe/LPS-134694-UX-Improvements-in-info-panels-of-content-dashboard?node-id=1080%3A358437)

## Motivation

We are implementing a new preview action for web contents versions in the info panel of the Content Dashboard.
This new preview action opens a new tab instead of a modal.
This new tab need some UI modifications, as showed in the Figma file linked above:
- A title
- A separator

## Solution proposed

Only for **non pop_up window states**, the template will render the title and the separator

## How to verify

- Create a web content, edit it once or twice just to generate versions
- Visit the Content Dashboard
- Open the info panel for the web content by clicking the info icon or using the item kebab menu
- Once in the info panel, click on versions tab
- Use the kebab menu for any version and click on preview action

**Expected**: new browser tab opens with a preview

Current preview implementations should work as before.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Hey @beltranrengifo,

One question, What happen is the article have a display page associated? Usually in web content admin we are using it to preview the web content, since it should be considered as web content preview, in your solution you are not using it, or Are you planing incorporate it in following prs?

Regards,
Eudaldo.

**Comment by beltranrengifo** [comment]
> Hey @beltranrengifo,
> 
> One question, What happen is the article have a display page associated? Usually in web content admin we are using it to preview the web content, since it should be considered as web content preview, in your solution you are not using it, or Are you planing incorporate it in following prs?
> 
> Regards, Eudaldo.

hi @ealonso !

that's a good question, AFAIK the web content with a DPT associated will behave the same. In the preview action of the Content Dashboard will open a new tab, but in the rest of usages will behave as it is now.
That's something we discussed yesterday because it goes beyond the scope of this story, so yes, we'll add any needed modifications in upcoming stories.

@cgoncas plz correct me if I'm wrong, I have no much context about this DPT

**Comment by ealonso** [comment]
ci:forward

**Comment by cgoncas** [comment]
> 
> 
> > Hey @beltranrengifo,
> 
> > 
> 
> > One question, What happen is the article have a display page associated? Usually in web content admin we are using it to preview the web content, since it should be considered as web content preview, in your solution you are not using it, or Are you planing incorporate it in following prs?
> 
> > 
> 
> > Regards, Eudaldo.
> 
> 
> 
> hi @ealonso !
> 
> 
> 
> that's a good question, AFAIK the web content with a DPT associated will behave the same. In the preview action of the Content Dashboard will open a new tab, but in the rest of usages will behave as it is now.
> 
> That's something we discussed yesterday because it goes beyond the scope of this story, so yes, we'll add any needed modifications in upcoming stories.
> 
> 
> 
> @cgoncas plz correct me if I'm wrong, I have no much context about this DPT

I will add a comment to the story so Carol can review how DTP are previewed and if she thinks we need to change something we will do it in another story.

thanks

**Comment by ozysouza** [comment]
ci:stop

**Comment by ozysouza** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/125817

**Pull request closed without merging**
