### PR TITLE
LPS-200303 Cannot see previous published content after submit for workflow on content page as guest

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-200303

Previous PR: https://github.com/liferay-echo/liferay-portal/pull/14248

cc: @ealonso I just removed [this commit](https://github.com/liferay-echo/liferay-portal/pull/14248/commits/4e103f59e9bf6389b1cca9e9a6952b933fde15cc) to solve conflicts because of this was handled by [this](https://github.com/liferay/liferay-portal/commit/f05b0155045d2eada7dcaf2cd543ea8e2469a9a6) commit

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @lfbesada, the draft label is missing when the content page is pending to approve.
Expected
image
Actual
image

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
Hi @ealonso @Tim-Cao 

I added the latest commit to maintain the current behavior of showing both labels draft and pending when a page is pending approval.

IMHO that is not the correct behavior, in addition to the published one, there is only one page that is published too, in draft or pending, it is never in both states at the same time. So, from my point of view, it should only have the label of the state that corresponds to it.

IMHO if it is pending it should only show the draft tag if it has never been published so that the user can know that there is no published version.

But we can discuss it later on, let's keep the current behavior.

Regards

**Comment by lfbesada** [comment]
ci:reevaluate:1347401_5165

**Comment by Tim-Cao** [comment]
Hi @lfbesada, there is another regression issue, The reviewer cannot preview after submit for workflow.
**Steps to reproduce**

1. Add a new site
2. Add a Button fragment to a content page then publish
3. Enable single approver for Content Page
4. Add a new user
5. Assign to the new site
6. Assign the site administrator to new user
7. Impersonate new user
8. Make some changes on content page then submit for workflow
9. Back to Test Test
10. Navigate to the Pages admin
11. Click the ellipisis button of page

There should be a Preview action.
image

**Comment by Tim-Cao** [comment]
@lfbesada, another regression issue is user without permissions is still able to edit the page after submit for workflow
**Step to reproduce**

1. Add a new site
2. Add a Button fragment to a content page then publish
3. Enable single approver for Content Page
4. Add a new user
5. Assign to the new site
6. Add a new site role with following permissions
7. Assign new site role to new user
8. Impersonate new user
9. Navigate to the content page at view mode
10. Make some changes on content page then submit for workflow

The pencil icon should be invisible to new user

image

**Comment by lfbesada** [comment]
In addition to the issues that @Tim-Cao found (thanks! :heart: ), I have found some additional ones. So I am going to close this and I will resend once fixed it.
Regards

**Pull request closed without merging**
