### PR TITLE
LPS-128399 Add StyleBook to LayoutPageTemplatesImporterImpl

### PR DESCRIPTION
**Pull request by p2kmgcl**
I don't like that we are using the internal StyleBookEntryKey as id when exporting. But life is life.

Checked with @jkappler :heart:, but please check that I didn't break anything.

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
@p2kmgcl It looks like we need to rerun `gw buildREST` and make sure the changes are committed since the [test](https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/331267/) above detects changes when running  `gw buildREST`

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
T.T I did run `gw buildREST`, I promise, I am going to try again

**Comment by p2kmgcl** [comment]
Peek 2021-03-11 16-49

It doesn't work (no new changes). @ruben-pulido @jkappler can either of you try running it? Maybe I am missing something

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
@p2kmgcl > https://github.com/liferay-echo/liferay-portal/pull/4000

**Pull request closed without merging**
