### PR TITLE
LPS-135101 Stay in the same page if not display page exists for the item

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@ealonso

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1197401_8546

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
