### PR TITLE
LPS-143500 Draft page is published when creating page template from it

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-143500

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/6660

**Pull request closed without merging**
