### PR TITLE
LPS-153676 Integration Tests

### PR DESCRIPTION
**Pull request by mbowerman**
Hi Echo Team,

I've added two integration tests for this case, per Brian's request [here](https://github.com/brianchandotcom/liferay-portal/pull/117622#issuecomment-1129899434).

The first one `testCompanyScopedPortletOnPortletLayoutHasCorrectAttributes`, takes place on a Widget Page, and this test would have still passed prior to the fix for [LPS-153676](https://issues.liferay.com/browse/LPS-153676). That said, I still think there's value in adding this test.

The second one `testCompanyScopedPortletOnContentLayoutHasCorrectAttributes`, takes place on a Content Page. This test may be more "controversial" because we don't seem to have good testing utilities available for adding portlets to Content Pages. So instead what I've done is added PortletPreferences for the Content Page directly, rather than adding an actual Portlet to the Content Page. This mimics the conditions that caused the bug to occur. I've put it in its own commit so that it can be easily reverted if need be.

Let me know if you have any questions about this.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by lfbesada — COMMENTED** [review]
Hi @mbowerman 
Thanks for the test!
I agree that is hard a lot to get a published content layout with a portlet added properly because there is needed some logic from the page editor. I tried to mitigate it by extracting code to a test-util class to expose an easier way to do it. 
I am going to send a follow-up pull request with your commit and add these utils to use in your test.
Thanks a lot!

**Comment by lfbesada** [comment]
Please see https://github.com/liferay-echo/liferay-portal/pull/8161

**Pull request closed without merging**
