### PR TITLE
LPS-157986 Prevent send form from staging group

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-157986

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1387401_2195

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
