### PR TITLE
LPD-6870 Interactive utility pages may need to be public layouts

### PR DESCRIPTION
**Pull request by stian-sigvartsen**
Hi @lfbesada . As we discussed on Slack, this is needed for the Login functionality because of the portlet interactions.

Motivation
=======
The Login functionality utility pages require interactions with portlets unlike simpler 404/500 utility pages that only display content.

Proposed Solution
========
Set the privateLayout parameter according to the utility page type. In the future maybe you can refactor this into a SPI.

Steps to Verify
========
N/A

References to existing code (if applies)
========
N/A

Screenshots (if applies)
========
N/A

Alternative Solutions that were discarded (if applies)
========
We attempted to use the same approach as with `TermsOfUseStrutsAction` but this falls short when interacting with the LoginPortlet. Because the `PortletURLFactory` will not generate portlet URLs that use the `StrutsAction` path.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
Hey @stian-sigvartsen,

It is not a good solution, also I saw that you merged some code without our suppervision, I would like to have some time to review the code that was already merged, and propose a good solution. One thing that can help is a pr with all logic, just to check all behavior.

Regards,
Eudaldo

**Comment by stian-sigvartsen** [comment]
Hey @ealonso . Thanks for your feedback. I did not think we merged anything relating to the UP framework without your team's supervision. Can you please highlight the change so we can learn?

**Comment by ealonso** [comment]
https://github.com/liferay/liferay-portal/commit/0ecad93f2753c00b8afc04e884b3ccf5bff1d11b

**Comment by ealonso** [comment]
Could you please send me a pr with all the logic that you have?

**Comment by stian-sigvartsen** [comment]
Hi @ealonso . Here is the login utility page functionality liferay-appsec/liferay-portal/pull/1686
I notice that after my rebased (10 days diff), this approach renders the UP without any theme content. I guess there has been a change upstream on your side.

**Pull request closed without merging**
