### PR TITLE
LPS-183054 Fix menu right position

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

could you please check my fix?

**Steps to reproduce:**

1. Start the bundle and log in as admin
2. Edit the Home page and create a composition as follows
3. Add a Container Fragment to the page
4. In the Container add a Dropdown fragment
5. In the drop zone of the Dropdown fragment add a Paragraph fragment
6. At the Advanced tab of the Container add the CSS classes: "d-flex" and "justify-content-end"
7. Click on the Dropdown

**Expected result**: paragraph content is fully visible

**Fix**: Set the menu.style.right to 0px in case the toggleRect.right is equals with the window.innerWidth

Thanks, Roland

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Review by claraizquierdo — COMMENTED** [review]
Hi @rolandpakai ,

thank you for submitting your PR. We have been having a look at your solution and it only works if the dropdown button in the right limit of the screen. If we give it a margin right of 1em it does not work 😢 

Captura de pantalla 2023-05-03 a las 17 34 37

There is a workaround for solving this issue that is assigning this CSS to the fragment:
Captura de pantalla 2023-05-03 a las 16 07 11

We are discussing with the product managers if it would make sense to add and option in the dropdown fragment to select the alignment of the dropdown so that the users don't need to add this CSS. I will keep you inform.

**Comment by rolandpakai** [comment]
Thank you @claraizquierdo for checking the my solution,
I will looking for your update.

Thanks, Roland

**Comment by claraizquierdo** [comment]
Hi @rolandpakai, thank you for your patience. We have developed a more extended solution (see https://github.com/liferay-echo/liferay-portal/pull/11957). Anyway, if you think it could be interesting to have an configuration option for this fragment to select the alignment of the menu you can open a feature request and we will tackle it when we have time :)

**Comment by rolandpakai** [comment]
Thank you @claraizquierdo  for the "more extended solution" :)

**Pull request closed without merging**
