### PR TITLE
LRQA-60158 Simplify case

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
Random failure (it works on my local)

**Pull request closed without merging**
