### PR TITLE
LPS-165966 Use openToast for the screen reader to read the alert. Also focus the clay alert to make it easy for the user to use the actions

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:forward

**Comment by BarbaraCabrera** [comment]
anigif_enhanced-10573-1609870853-33

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
