### PR TITLE
LPS-125534 Passing preserveValue as true to let the translation values appear

### PR DESCRIPTION
**Pull request by mateussgn**

### CODE REVIEW

**Comment by victorg1991** [comment]
Hey @mateussgn I can still reproduce the issue after deploying your changes

Can you double check it?

Thanks

**Comment by mateussgn** [comment]
Of course, I'll check it again. Thanks for reviewing!

**Comment by mateussgn** [comment]
Hey @victorg1991, I've deployed the changes and then I hard reloaded the page with an empty cache, it worked fine and I couldn't reproduce the issue.

**Comment by victorg1991** [comment]
hey @mateussgn 

I've tried again and It worked now, not sure what happened this morning 🤔  sorry about it

**Comment by mateussgn** [comment]
No problem. If you need something more just slack me. Thank you!

**Comment by victorg1991** [comment]
Resent here! https://github.com/liferay-echo/liferay-portal/pull/3403 :) I've tried to simplify a bit the code of that file

Thanks!!

**Pull request closed without merging**
