### PR TITLE
LPS-135959 FE Tests for ImportDataDefinitionModal

### PR DESCRIPTION
**Pull request by eli-rlima**
Hi reviewer!

This PR adds the FE units tests for the `ImportDataDefinitionModal.js`.  

The related tickets: 

- [LPS-135957](https://issues.liferay.com/browse/LPS-135957) 
- [LPS-135959](https://issues.liferay.com/browse/LPS-135959) 

The context of this ticket is related with the follow past PR's: 

- #5336 
- #5377 

Thanks for your review time.

### CODE REVIEW

**Comment by eli-rlima** [comment]
ci:test:sf

**Comment by eli-rlima** [comment]
ci:test:relevant

**Comment by eli-rlima** [comment]
ci:test:relevant

**Comment by eli-rlima** [comment]
ci:test:relevant

**Comment by eli-rlima** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @eli-rlima 

First of all, thanks for the detailed description! This helps a lot when reviewing the code 👏 

One thing I noticed here is that all the test depend on the first one, this is usually a bad practice since test should be as isolated as possible, if one fail, it shouldn't make the other fails too. Apart from that, jest has a mode that run tests in parallel, which will fail if we depend on the first test.

In order to remove this dependency, I think we should make a function to render the modal and just render it in every test.

In this case it may seem a bit weird, since we rely on Liferay.component to open the modal, but we can do something like this:

```javascript
jest.useFakeTimers();

const renderModal = () => {
       // grab open function from the Liferay.component call
	let open;
	Liferay.component = jest.fn((_component, {open: openFn}) => {
		open = openFn;
	});

	const container = render(<ImportDataDefinitionModal />);
       
        // open the modal, we use runAllTimers since clay modal has some delay to open, this way we make suer the modal is fully visible when we execute the tests
	act(() => {
		open();

		jest.runAllTimers();
	});

	return container;
};
```

and then a test may looke like this:

```javascript
it('renders the title modal', async () => {
		const {queryByText} = renderModal();

		const infoAlert = queryByText(
			'the-import-process-will-run-in-the-background-and-may-take-a-few-minutes'
		);

		expect(infoAlert).toBeInTheDocument();
	});
```

What do you think? :)

**Comment by eli-rlima** [comment]
Hi, @victorg1991!

Thanks for your review, was insightful for me! I did changes somethings in your initial idea. 
I achieved uses the simple render in each test as usually is done, using your suggest. 

I took advantage and did some refactoring. 

Thanks so much :)

**Comment by eli-rlima** [comment]
ci:test:sf

**Comment by eli-rlima** [comment]
ci:test:relevant

**Comment by eli-rlima** [comment]
ci:stop

**Comment by eli-rlima** [comment]
ci:test:sf

**Comment by eli-rlima** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
LGTM :) Looking good! I think we may get rid of all the `waitElement` calls with the `jest.runAllTimers()` to render the modal instantly, but I think leaving it like that is fine for now! 👏 

Thanks!!

**Comment by victorg1991** [comment]
ci:forward

**Comment by LuisMesquita** [comment]
Leaving here for futures references, but may you can consider [writing fewer longer tests](https://kentcdodds.com/blog/write-fewer-longer-tests)

**Pull request closed without merging**
