### PR TITLE
LPS-111937 Use Exception to catch JSON syntax errors when dealing with display page templates

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@ealonso, @ruben-pulido

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/296

**Pull request closed without merging**
