### PR TITLE
 LPS-197678 Add rename option for folders

### PR DESCRIPTION
**Pull request by jkappler**
Motivation
=======
Rename should be an available option for recently created folders for Diplay Page Templates

Proposed Solution
========
Implement the rename option

Steps to Verify
========
1. Go to Design > Page Templates > Display Page Templates Tab
2. Create a new Folder
3. Use the Kebab menu to display available actions for that folder
4. Select Rename, choose a different name and ensure is persisted.
 
Screenshots (if applies)
========
RenameActionForDPTFolders

Commits
========
- LPS-197678 Add rename option in dropdown item
- LPS-197678 Add update ActionCommand for displayPageTemplateCollections
- LPS-197678 Add renamePageTemplateCollectionModal to show a popup when rename option selected for DisplayPageTemplateSollections

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
