### PR TITLE
LPS-197569 When you create or update a webcontent or a blog using the headless API, the display date is not correct

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://liferay.atlassian.net/browse/LPS-197569

When you create or update a web content or a blog using the headless API and the Liferay user is configured with a timezone different to GMT/UTC, the display date of the created web content is not correct, it will created with a date some hours before or later than current one, depending on the configured time zone.

This behavior is not reproduced if you create/update the web content or blog from the user interface, the dates will match
This behavior is reproduced If you specify a custom publish date in the headless API, it will be always created with some hours offset than the specified, depending on the configured timezone.

**Root cause of the issue**

The JournalArticleLocalServiceImpl.addArticle method converts the received displayDate from the user time zone to GMT before saving it to the database, [see code here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L375-L377) and the BlogEntryLocalServiceImpl.addEntry method converts the received displayDate from the user time zone to GMT before saving it to the database, [see code here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L375-L377) 

But the headless API uses the dates in UTC time zone when calling the JournalArticleLocalServiceImpl.addArticle or BlogEntryLocalServiceImpl.addEntry methods, the received Date object from the HTTP request is handled in the headless code using the [LocalDateTimeUtil](https://github.com/jorgediaz-lr/liferay-portal/blob/master/modules/apps/portal-vulcan/portal-vulcan-api/src/main/java/com/liferay/portal/vulcan/util/LocalDateTimeUtil.java) class and broken into its parts.

**Solution**

To solve this issue, as it was suggested in the previous PR https://github.com/liferay-echo/liferay-portal/pull/13852 I have:

1. Created new addArticle/updateArticle methods with Date parameters in JournalArticleLocalService and JournalArticleService (see 991efd313ce272fe51cc76ca10999874be5f09bc)
2. Exposed in BlogEntryService the existing addEntry/updateEntry methods with Date parameters from BlogEntryLocalService (see 790b614a2b52d2adf370b310ae53ff5679239ea1)
3. Removed all the headless code related to LocalDateTimeUtil class used by web content and blogs headless APIs, and just call the new methods with the Date parameters (see 08b1da1660c6822386eeb38f2dc1b57bfe40483f , d5e6fc8d1456bebd0f58da2dbe15cfb53d2cc578 and 8359243ad1ef414f25e21950a2c9f56b37802335)
4. I have also applied the new addArticle/updateArticle methods of JournalArticleLocalService to everywhere (see 0e4d975c62a5cbd2494ed309a076e48987fa2440) this removes lots of duplicated code that is just converting Date format to int values.

This PR affects to Echo team (_modules/apps/journal_, _modules/apps/headless_), Lima team (_modules/apps/blogs_, _modules/apps/headless_) and Headless team (_modules/apps/portal-vulcan_) code. I am sending the PR to Echo because the customer reported the bug creating a web content and because most of the changed code is from Echo.

/cc @liferay-lima @liferay-headless

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @jorgediaz-lr,

Thanks you very much for it!!!

**Comment by 4lejandrito** [comment]
Hi @jorgediaz-lr! We can't remove that class because REST Builder is using it [here](https://github.com/liferay/liferay-portal/blob/29732d7552d5272e837d4bf301e6e3ff8ab1de31/modules/util/portal-tools-rest-builder/src/main/resources/com/liferay/portal/tools/rest/builder/dependencies/base_resource_impl.ftl#L68). It is not as simple as removing it from there too because that code will be present in customer's generated code and will break if they upgrade to the new version.

Can you remove that commit from this PR and send another PR just with it to `liferay-headless/liferay-portal`? We can take it from there and remove it if possible (but I think it will not be possible).

**Comment by jorgediaz-lr** [comment]
Hi @4lejandrito 

About https://github.com/liferay/liferay-portal/blob/29732d7552d5272e837d4bf301e6e3ff8ab1de31/modules/util/portal-tools-rest-builder/src/main/resources/com/liferay/portal/tools/rest/builder/dependencies/base_resource_impl.ftl#L68 usage, we could also remove it, because we are adding a import but the class is not being used anywhere in the Liferay code (except on the classes were I am already removing it), you can just execute `git grep -l LocalDateTimeUtil` and you will  see that the only file occurrences are:
```
modules/apps/headless/headless-admin-content/headless-admin-content-impl/src/main/java/com/liferay/headless/admin/content/internal/resource/v1_0/StructuredContentResourceImpl.java
modules/apps/headless/headless-delivery/headless-delivery-impl/src/main/java/com/liferay/headless/delivery/internal/resource/v1_0/BlogPostingResourceImpl.javamodules/apps/headless/headless-delivery/headless-delivery-impl/src/main/java/com/liferay/headless/delivery/internal/resource/v1_0/StructuredContentResourceImpl.java
modules/apps/portal-vulcan/portal-vulcan-api/src/main/java/com/liferay/portal/vulcan/util/LocalDateTimeUtil.java
modules/util/portal-tools-rest-builder/src/main/resources/com/liferay/portal/tools/rest/builder/dependencies/base_resource_impl.ftl
```


About:

>  _that code will be present in customer's generated code and will break if they upgrade to the new version._

It is true a customer could use the `LocalDateTimeUtil` class, but in my opinion, I think it is very unlikely as it only contains two methods to convert from Date to LocalDateTime that is not documented anywhere.

Nevertheless, I have just removed that commit from this PR right now.

**Comment by 4lejandrito** [comment]
Hi @jorgediaz-lr the problem is the `import`. Customers will have that import, and if they upgrade Liferay without rerunning REST Builder the code will not compile becasue the import will not be found.

**Comment by jorgediaz-lr** [comment]
Hi @ruben-pulido

We have to deliver a hotfix to our customer.

Do you think I can send a SDH hotfix with this code or it is better to wait until you review it and it is merged to master?

Thank you

cc @liferay-lima

**Comment by ruben-pulido** [comment]
Hi @jorgediaz-lr

Thanks a lot for the changes!

You can send a hotfix with this code.

I have added integration tests for Structured Content and Blog Posting verifying the bug is no longer reproducible with the fix [here](https://github.com/liferay-echo/liferay-portal/pull/13932)

I am closing this PR and will forward the new one to Brian.

**Comment by ruben-pulido** [comment]
@jorgediaz-lr 
The [semver commit ](https://github.com/liferay-echo/liferay-portal/pull/13913/commits/48cb991d718692fcc01554318a51d7a0b923d5e8) should also be removed. 
I have removed it from the [PR](https://github.com/liferay-echo/liferay-portal/pull/13932), but you probably want to avoid including it in the fix for the customer.

**Comment by jorgediaz-lr** [comment]
Hi @ruben-pulido , It is true, I forgot to remove the semver commit.

Thanks for reviewing the PR I will create the customer hotfix.

**Pull request closed without merging**
