### PR TITLE
LPD-18358

### PR DESCRIPTION
**Pull request by JavierMoral**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by JavierMoral** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:report:2546317585

**Review by lfbesada — APPROVED** [review]
LGTM :tada: 
@JavierMoral Thanks :heart:

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1297401_9390

**Comment by lfbesada** [comment]
ci:report:2546543334

**Comment by lfbesada** [comment]
ci:report:2546744439

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
