### PR TITLE
LPS-147252, LPS-147253, LPS-146976 | master

### PR DESCRIPTION
**Pull request by sandrodw3**
cc @Tim-Cao @ruben-pulido @lfbesada

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:relevant 🤡

**Comment by Tim-Cao** [comment]
Hi @sandrodw3 and @lfbesada , the manual testing passed according to acceptance criteria. I've updated an Poshi issue. QA  review is done.
cc @david-gutierrez-mesa

**Comment by lfbesada** [comment]
I am not able to add the On Hold label but this PR should wait by the upgrade process and for the implementation of taking into account in the import that the input could have the old fields instead of the new ones.

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
The failed test seems to be related. I will review it.

**Comment by sandrodw3** [comment]
https://github.com/liferay-echo/liferay-portal/pull/7433

**Pull request closed without merging**
