### PR TITLE
[TS] LPS-160990

### PR DESCRIPTION
**Pull request by jcampoy**
https://issues.liferay.com/browse/LPS-160990

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jcampoy** [comment]
FYI @lfbesada !!

**Comment by jcampoy** [comment]
ci:test:sf

**Comment by jcampoy** [comment]
ci:test:relevant

**Comment by jcampoy** [comment]
ci:test:sf

**Comment by jcampoy** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Hi @jcampoy 
Thanks for the fix! ❤️ 
LGTM!
Regards

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. It can be manually forward if this last attempt doesn't work.

**Comment by ozysouza** [comment]
Plese see https://github.com/brianchandotcom/liferay-portal/pull/122013

**Pull request closed without merging**
