### PR TITLE
LPS-173428 Adds 404 utility page to site initializer welcome

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-173428)

The goal of these changes is to add a 404 utility page to welcome site initializer

## Change summary:

* Add 404 utility page to welcome site initializer

## Test Scenario

* Enable FF feature.flag.LPS-162765=true
* Create a new site based on team extranet
* Go to Site Builder > Pages
* Go to Utility Pages tab
* 404 utility page is created

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
