### PR TITLE
LPS-112352 Initially hide FloatingToolbar to avoid flickering

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:close

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/480

**Pull request closed without merging**
