### PR TITLE
LPS-198911 Update screen reader feedback

### PR DESCRIPTION
**Pull request by p2kmgcl**
I've updated the screen reader messages. Still need a review from PEDS (will request it on slack).

To test this:
1. Enable `LPS-196420` feature flag.
2. Deploy `layout-content-page-editor-web` module.
3. Edit some content page and reorder items in this dialog:

[Screencast from 2023-10-24 18-07-06.webm](https://github.com/liferay-echo/liferay-portal/assets/800645/17865588-7fd5-480b-a0c4-2a6fc3aba338)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
