### PR TITLE
[TS] LPS-125070

### PR DESCRIPTION
**Pull request by jonathanmccann**
This solution was based on the discussion had on https://issues.liferay.com/browse/PTR-2145.

I'm not sure about the naming convention or whether adding a brand new ThreadLocal is the right choice. Please let me know if it should be done differently or feel free to refactor it as you see fit.

If there are any questions please let me know. Thank you for reviewing these changes.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
