### PR TITLE
[TS] LPS-126637 | Deleting a single menu item does not reorder all its sibling menu items

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?

https://issues.liferay.com/browse/LPS-126637

Best,
Attila

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Hi @bakayattila @dacousalr Thanks for the fix and the test.
Forwarded to Brian

**Comment by ruben-pulido** [comment]
ci:foward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
