### PR TITLE
[TS] LPS-132376 Second addendum

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team, this extra commit tries to meet our SF needs while keeping the fix functional after the last commit. Could you please review it? Thanks in advance

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
ci:reevaluate:1257401_441

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1257401_507

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
