### PR TITLE
LPS-146308 Avoid creating an array that represent the collection.

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
Hi @victorg1991, no regression issues found according to [ci:test:echo](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1604763719&testrayRunIdA=1604826337&testrayTeamId=1310700641&statusB=3)

**Comment by victorg1991** [comment]
Thanks @Tim-Cao ! :)

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
