### PR TITLE
LPS-150297 When a widget is removed from a content page the associated portlet preference is not removed

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-150297

Previous PR: https://github.com/liferay-echo/liferay-portal/pull/7703

See: https://github.com/brianchandotcom/liferay-portal/pull/115908#issuecomment-1093381735

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
