### PR TITLE
LPD-16327 Define a value so that it is not taken from the label

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
Portlet Look and Feel configuration can't save Text Styles -> Alignment = center
https://liferay.atlassian.net/browse/LPD-16327

Proposed Solution
the label value of this aui:option was changed to better reflect a localisation requirement. But if a value attribute is not defined this new label center[alignment] is used as the value. So, let's add a value attribute.
In regards of upgrade steps, I can create one, but I feel that anyone still using widget pages and meeting this issue would have immediately reported it. What do you think, should we add an upgrade step?

Steps to Verify
In Site Builder > Pages > Create a new Widget Page
Add an Asset Publisher to the new page
Click on the widget's three dot menu > Select Look and Feel Configuration
Click on "Text Styles" tab > Click down menu for “Alignment”
Click on "Center"
Click Save
Expected behaviour: The Center value stays in the modal
Actual Results: The Center value disappears in the modal

Cheers,
Balázs

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:report:2533536551

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
