### PR TITLE
LPS-130440 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-130440

This is only for master.

@jkappler

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @jkappler, as I mentioned, the selected display page template is not assigned to asset successfully.

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Resent here fixing the issue that you found @Tim-Cao! https://github.com/liferay-echo/liferay-portal/pull/4389

**Pull request closed without merging**
