### PR TITLE
LPS-144254 Convert comments link to button

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, would you like to check js test failure?

**Comment by p2kmgcl** [comment]
@Tim-Cao fixed!

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
