### PR TITLE
LPS-199434 Fix preview icons in fragment editor

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Fragment Editor used to contain icons for “Desktop”, “Tablet”, “Portrait Phone” and “Full Size”.
[Link to story or ticket](https://liferay.atlassian.net/browse/LPS-199434)

Steps to Verify:
----------------
1. Go to Design -> Fragments
2. Click on create a new fragment
3. In the fragment editor check that preview icons (desktop, tablet, portrait phone and full size) are visible.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142488

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
