### PR TITLE
LPS-114791 Removes com.liferay.dynamic.data.mapping.kernel dependencies

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Comment by jpince** [comment]
@ealonso can you please look into your own teams' test failures before retesting? These same test failures are blocking [Tango](https://github.com/cgoncas/liferay-portal/pull/510) and [Hugo](https://github.com/hhuijser/liferay-portal/pull/4345#issuecomment-637500543). It looks like the same tests will also fail in the retest for this pull https://github.com/liferay-echo/liferay-portal/pull/857#issuecomment-637724478. Blind retesting uses up CI resources and slows everyone down.

cc/ @liulukiwi @manoelcyreno

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
I'm analysing LocalFile.AdaptiveMedia#AddAMIWithHighDensityResolution.

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
