### PR TITLE
LPS-167255 Update js logic

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ozysouza** [comment]
Seems like there is a test failing on ExperienceToolbarSection.test.js. The other failures are unrelated.

**Comment by ozysouza** [comment]
I've just seen the same js-unit test failing on antoher PR. I'm not sure if it's related to this one :/

**Comment by ozysouza** [comment]
After second thought the failures seems to be unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/125627

**Pull request closed without merging**
