### PR TITLE
LPS-201523 Change back button title when editing a Collection

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-201523)

## Steps 

**edit_asset_list_entry_dynamic.jsp and edit_asset_list_entry_manual.jsp**

These two clases are the common classes to retrieve the "backURLTitle"

**AddAssetListEntryMVCActionCommand.java: this one is to set the "backURLTitle" when adding a Collection, we can add a Collection in two different ways**

**Case 1: From Collections - AssetListManagementToolbarDisplayContext.java**

- Go to Site Builder > Collections > Create a Manual Collection and see the back button title 
Screenshot 2023-11-14 at 12 26 22

**Case 2: From Collection Pages - SelectCollectionManagementToolbarDisplayContext.java**

- Go to Site Builder > Pages > Add a Collection Page > Choose or create a manual collection > see the title of back button 
Screenshot 2023-11-14 at 12 28 37

**AssetListDisplayContext.java**

- Go to Site Builder > Collections > Create a Manual Collection > Go to Collections tab to see the list of Collections
- Click on the collection name > see the back button title 
Screenshot 2023-11-14 at 12 32 56

**AssetListEntryActionDropdownItemsProvider.java**

- Go to Site Builder > Collections > Create a Manual Collection > Go to Collections tab to see the list of Collections
- Click on the collection ellipsis > edit > see the back button title 
Screenshot 2023-11-14 at 12 35 24

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143829

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
