### PR TITLE
LPS-135490 Add modal for creating information templates 2

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-135490

cc: @victorg1991

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Pull request closed without merging**
