### PR TITLE
LPS-157578: Change last modified user after modifcation

### PR DESCRIPTION
**Pull request by kristofloneck**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by kristofloneck** [comment]
ci:test

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
Hi @kristofloneck 
Thanks for the fix!
I have resent it to add a minor change, please see: https://github.com/liferay-echo/liferay-portal/pull/8846
Regards

**Pull request closed without merging**
