### PR TITLE
LPS-110227

### PR DESCRIPTION
**Pull request by marcosvictor22**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by marcosvictor22** [comment]
@david-gutierrez-mesa

**Comment by marcosvictor22** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Hi @marcosvictor22, please fix sf issue

**Comment by ealonso** [comment]
Hey @marcosvictor22,

Please fix the sf error and resend

**Pull request closed without merging**
