### PR TITLE
LPD-24277 Add a LayoutService method to get the first layout checking permissions

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-24277

I have asked the Content Management team [here](https://liferay.slack.com/archives/CLD39UKM5/p1714369594849429) to review [this commit](https://github.com/liferay-echo/liferay-portal/pull/15598/commits/3ea28e2839b8a355f302aaf5ffdb33f0c14724cd) because it is their component. That commit can be removed from this pull without implying any other changes.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
I set the On Hold label because we are waiting for Content Management team feedback

**Comment by lfbesada** [comment]
ci:report:2564380190

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:report:2564508735

**Pull request closed without merging**
