### PR TITLE
LPS-196356 Add permission checker by group when site is initialized

### PR DESCRIPTION
**Pull request by MirnaGama**
### **Motivation:**
[LPS-196356](https://liferay.atlassian.net/browse/LPS-196356) -> A user assigned to Site Administrator role cannot add child sites

### **Proposed Solution:**

I was investigating the class that renders the dropdown items for the site and it calls the method [hasAddChildSitePermission](https://github.com/liferay/liferay-portal/blob/master/modules/apps/site/site-admin-web/src/main/java/com/liferay/site/admin/web/internal/servlet/taglib/util/SiteActionDropdownItemsProvider.java#L93) to check the permission related to adding the child page. This method is from the SiteAdminDisplayContext class. It will check[ if the permission is contained in PortalPermissionUtil or GroupPermissionUtil](https://github.com/liferay/liferay-portal/blob/master/modules/apps/site/site-admin-web/src/main/java/com/liferay/site/admin/web/internal/display/context/SiteAdminDisplayContext.java#L297).

Furthermore I investigated the render class for the child page (SelectSiteInitializerMVCRenderCommand) since the permission error message appears there after we click the button. It has a similar verification, but [only checks inside the PortalPermission class](https://github.com/liferay/liferay-portal/blob/master/modules/apps/site/site-admin-web/src/main/java/com/liferay/site/admin/web/internal/portlet/action/SelectSiteInitializerMVCRenderCommand.java#L42).

After discussing with echo product team in this [PTR](https://liferay.atlassian.net/browse/PTR-4335), it was confirmed that the user with the Site Administrator role have this permission to create child sites by default.

> The user has permission because they have the action “Manage Subgroups“. So, if you check just a bit further, you will arrive to [AdvancedPermissionChecker](https://github.com/liferay/liferay-portal/blob/33dcc7116256d2c52b3a676d48e7ed3276320ed4/portal-impl/src/com/liferay/portal/security/permission/AdvancedPermissionChecker.java#L1390), and you will see that it specifically checks for Site Admin Role, granting permission to the user to see the action. 

> In any case, for the fix. What I personally would propose based on the findings is to also add the check for GroupPermission to the site initializer resource command.

### **Steps to Verify:**

1. Start the bundle and log in as admin
2. Control Panel > Users and Organisations, create a new user
3. Add the new user as a member of Liferay DXP site on the Membership tab
4. At the Roles tab, add the new user as Site administrator of Liferay DXP site
5. Control Panel > Roles, Select User role, Define permissions tab > Control Panel > Sites > Sites
6. Add 'Access in Control Panel' and 'View' APPLICATION PERMISSIONS
7. Impersonate the user and navigate to Control Panel > Sites
8. At the kebab menu of Liferay DXP site, click on Add child site

✅ _Expected result:_ the child site has been created successfully
❌ _Actual result:_ button is there, but when clicked, error message appears showing that there is no permission

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by MirnaGama** [comment]
ci:test

**Comment by MirnaGama** [comment]
ci:stop

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
thanks @MirnaGama ❤️

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141381

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
