### PR TITLE
LPS-174522

### PR DESCRIPTION
**Pull request by ealonso**
In some situations the value of ddmFormField is not in the first level. So, to avoid it, we are looking in all document for the field name since it should be unique.

For example:
1. Create a new structure in 7.3
2. Adds a fieldset with two fields
3. Create a web content
4. Edit the structure and remove the second field of the fieldset
5. Upgrade to master

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
