### PR TITLE
[TS] LPS-115024

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-115024

Although Site Template pages are technically private pages and thus should not have any Guest permissions, it is possible to create public pages in a site when creating from the site template.  This results in the Guest view permission always being revoked when creating a site from a site template, even though the permission is enabled by default.

Using _isSiteTemplate() logic from [LayoutsAdminManagementToolbarDisplayContext._isSiteTemplate()](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/display/context/LayoutsAdminManagementToolbarDisplayContext.java#L280).

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Hi @ChrisKian, sorry but we cannot review this PR, since it's not one of our components. Normally someone from staging should review this.

Best regards

**Comment by jkappler** [comment]
ci:close

**Comment by ChrisKian** [comment]
Thanks @jkappler, sent to https://github.com/vendeltoreki/liferay-portal/pull/71

**Pull request closed without merging**
