### PR TITLE
LPS-183029

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ruben-pulido** [comment]
ci:forward:force

**Comment by ealonso** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/134594

**Pull request closed without merging**
