### PR TITLE
LPS-198161 Do not import if the utility page with the same ERC exists and throw a warning

### PR DESCRIPTION
**Pull request by jkappler**
https://liferay.atlassian.net/browse/LPS-198161

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by alessandromalves** [comment]
Hey @jkappler, a regression found ([see comparison with acceptance routine](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1697059198156&testrayRunIdA=2438944747&testrayRunIdB=2439957473)). Steps to repdroduce:

1. Add a new site
2. Activate local live staging

Expected result:
The process is successfully completed

Actual result:
The process fails and there's been an error on the log
```
ERROR [liferay/background_task-10][LoggerExportImportLifecycleListener:390] Staged model {class: com.liferay.layout.utility.page.model.LayoutUtilityPageEntry, groupId: 32633, uuid: eecfb296-5454-a60c-c32e-5db528450398} import failed
com.liferay.layout.utility.page.exception.NoSuchLayoutUtilityPageEntryException: No LayoutUtilityPageEntry exists with the key {externalReferenceCode=LFR-404-ERROR, groupId=32705}
	at com.liferay.layout.utility.page.service.persistence.impl.LayoutUtilityPageEntryPersistenceImpl.findByERC_G(LayoutUtilityPageEntryPersistenceImpl.java:5205) ~[?:?]
	at com.liferay.layout.utility.page.service.base.LayoutUtilityPageEntryLocalServiceBaseImpl.getLayoutUtilityPageEntryByExternalReferenceCode(LayoutUtilityPageEntryLocalServiceBaseImpl.java:293) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40) ~[portal-impl.jar:?]
	at com.sun.proxy.$Proxy1140.getLayoutUtilityPageEntryByExternalReferenceCode(Unknown Source) ~[?:?]

```

**Comment by alessandromalves** [comment]
Also

```
com.liferay.layout.utility.page.internal.exportimport.data.handler.test.LayoutUtilityPageEntryStagedModelDataHandlerTest > testChangeDefaultLayoutUtilityPageEntry FAILED
[beanshell]      [exec]     com.liferay.exportimport.kernel.lar.PortletDataException: No LayoutUtilityPageEntry exists with the key {externalReferenceCode=rh1g50ga, groupId=32732}
[beanshell]      [exec]     	at com.liferay.exportimport.kernel.lar.BaseStagedModelDataHandler.importStagedModel(BaseStagedModelDataHandler.java:399)
[beanshell]      [exec]     	at com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil.importStagedModel(StagedModelDataHandlerUtil.java:380)
[beanshell]      [exec]     	at com.liferay.layout.utility.page.internal.exportimport.data.handler.test.LayoutUtilityPageEntryStagedModelDataHandlerTest._getImportedLayoutUtilityPageEntry(LayoutUtilityPageEntryStagedModelDataHandlerTest.java:230)
[beanshell]      [exec]     	at com.liferay.layout.utility.page.internal.exportimport.data.handler.test.LayoutUtilityPageEntryStagedModelDataHandlerTest.testChangeDefaultLayoutUtilityPageEntry(LayoutUtilityPageEntryStagedModelDataHandlerTest.java:62)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[beanshell]      [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[beanshell]      [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[beanshell]      [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
[beanshell]      [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:344)
[beanshell]      [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
[beanshell]      [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
[beanshell]      [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:90)
```

**Comment by jkappler** [comment]
thanks @alessandromalves, my bad, resent here: https://github.com/liferay-echo/liferay-portal/pull/13999

**Pull request closed without merging**
