### PR TITLE
LPS-131584 Use selected locale to format separator decimals for number field

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Use selected locale to format separator decimals for fields type ddm-number and ddm-decimal, always displays the decimal separator as point
For more details please check https://issues.liferay.com/browse/LPS-131584

Resend this PR https://github.com/liferay-forms/liferay-portal/pull/203 to Echo Team

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @georgel-pop-lr,

Could you please move the code to TemplateNode.getData? Like we are doing in other places, and test if everything is working fine.

Thanks,
Eudaldo

**Comment by georgel-pop-lr** [comment]
> Hey @georgel-pop-lr,
> 
> Could you please move the code to **TemplateNode.getData**? Like we are doing in for other types, and test if everything is working fine.
> 
> ```java
> public String getData() {
> String type = getType();
> 
> if (type.equals("ddm-journal-article")) {
> 	return _getLatestArticleData();
> }
> else if (type.equals("document_library") || type.equals("image")) {
> 	return _getFileEntryData();
> }
> else if (type.equals("geolocation")) {
> 	return _getGeolocationData();
> }
> 
> return (String)get("data");
> }
> ```
> 
> Thanks,
> Eudaldo

Hi @ealonso,

Okay I will check if works properly there.

Regards.

**Comment by ealonso** [comment]
Hey @georgel-pop-lr,

You can use **LocaleUtil.getMostRelevantLocale()**, since I think you need the user locale to show the number in the correct format, right?

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
> Hey @georgel-pop-lr,
> 
> You can use **LocaleUtil.getMostRelevantLocale()**, since I think you need the user locale to show the number in the correct format, right?

Hi @ealonso,

Thanks for the tip with the date, I did some relevant tests on my local  and everything seems to work just fine.

Let me know if you think that we could send this fix to our client.

Regards.

**Pull request closed without merging**
