### PR TITLE
LPS-124483 Only show site initializers that are available for the company

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@Tim-Cao, @ealonso, bug for showing Liferay DXP or Liferay Portal will not be fixed in this PR, it will be sent separately

**Comment by Tim-Cao** [comment]
Cool

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
