### PR TITLE
[TS] LPS-126209

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

could you please check my fix and push it forward?

The getPortletFooterPaths and getPortletHeaderPaths adds multiple times the resources to the DOM
https://github.com/liferay/liferay-portal/commit/364885718226ffef49b5d32548eef8a91cb39db8 

After removing th the liferay-util:html-top and liferay-util:html-bottom tags the content page still works in view mode and also in edit mode too.

Thanks, Roland

https://issues.liferay.com/browse/LPS-126209

cc @ealonso @pavel-savinov

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
@rolandpakai After taking a closer look at this issue, it seems that we need this code. Specifically for the Content Pages with widgets. Try to drag&drop Documents&Media widget on the content page and access the View mode - there is a "Processing actions..." label which must be hidden by the D&M portlet CSS which isn't being included.
Could you please take a look again?
Thanks!

**Comment by rolandpakai** [comment]
Hi @pavel-savinov 

thanks for reviwing my changes.
I resent the PR here: https://github.com/liferay-echo/liferay-portal/pull/3532

Thanks, Roland

**Pull request closed without merging**
