### PR TITLE
LPS-133292 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-133292

This is only for master.

@david-gutierrez-mesa
@jkappler

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
@Tim-Cao, check https://github.com/liferay-echo/liferay-portal/pull/4752

**Comment by jkappler** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
Thanks @jkappler

**Pull request closed without merging**
