### PR TITLE
LPS-139893

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-139893

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
See: https://github.com/liferay-echo/liferay-portal/pull/6004

**Pull request closed without merging**
