### PR TITLE
LPS-187534 The "featured image" link of a web content is not validated when it points to a wrong image from document library

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-187534

The "featured image" link (aka smallImageURL) is not validated when it points to a wrong image URL from the document library.

These image URLs from the document library are validated when you include them on the "content" section, but they are not validated on the "featured image" link.
On the other hand, the Staging functionality is also handling the URLs in both places when you export a LAR.

So the validations are not consistent depending on where are executed

To solve it, I am:

1. **Commit 69251b02a23b6db488a0e4078340b189ad31d41f:** Add an additional call to the `exportImportContentProcessor.validateContentReferences` method in JournalArticleModelValidator
2. **Commit 6c2930ef24296de84fc60fe3f83e3ad24879b7c0:** If the content variable only contains the URL, `((beginPos == 0) && (endPos == content.length())` it is not necessary to do the content.regionMatches logic that checks where the URL starts

Let me know if you have any question

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
Hi @ealonso 

It is necessary to add an additional commit to avoid a index out of bounds error, see new commit e94b7a9727c2aa45b84e1f1a9011e1934e1cfb4d

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
