### PR TITLE
LPS-128667 BuildLang

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
Hey @Tim-Cao! Could you help us with the poshi cases that are failing on this one? We have modified the placeholder for Item Selector and Image Selector, so I guess that's the main cause of the errors. Thanks! 🙂

**Comment by sandrodw3** [comment]
cc @veroglez

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/4004

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
