### PR TITLE
LPD-17934 BuildLang

### PR DESCRIPTION
**Pull request by veroglez**
This PR depends on https://github.com/liferay-echo/liferay-portal/pull/15205. 

Just review the commits with the LPD-17934 (d06423806c5ff59f0dbd01e909e19ebfb04debb0 - 0c064578dd9edce517e30546c85e660eef5a8189)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
ci:stop

**Comment by veroglez** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
