### PR TITLE
LPS-192659 Nested fields can lose value after upgrade to 7.4

### PR DESCRIPTION
**Pull request by Marina-Gouveia**
Related issue: [LPS-192659](https://liferay.atlassian.net/browse/LPS-192659)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
Hi @Marina-Gouveia 
Thanks for working on this! 
Could you please add an integration test to assert the current JournalArticleDDMFieldsUpgradeProcess behavior and the specific use case that you are fixing?
Thanks in advance!
Regards

**Comment by lfbesada** [comment]
Hi @Marina-Gouveia 
I am sorry, I have asked you for something I think is not viable. We cannot test that Upgrade Process correctly because it operates with a table's column that no longer exists.
Please forget my previous comment
I am sorry for the inconvenience.
Regards

**Comment by Marina-Gouveia** [comment]
Hi @lfbesada,
No problem!!
Regards.

**Review by lfbesada — APPROVED** [review]
Hi @Marina-Gouveia 
Thanks a lot for the fix!
LGTM
Regards

**Pull request closed without merging**
