### PR TITLE
LPS-120277 Simplify

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
@pavel-savinov

**Comment by jkappler** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
@Tim-Cao could you please take a look? It seems to be ok when doing it manually, but some POSHI tests are failing...

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @pavel-savinov  and @jkappler,
Could you confirm if _blank as default or _self as default?
https://github.com/liferay-echo/liferay-portal/pull/2759/commits/d12dab0b2e7ee9270461ca9eebb9cb62e5d62bc6#diff-a306623bb24ac3a4a80c505db84c25f16bd20c83fc3e4f97df0f135e972f7256R87
I double this line should be target = "_self";

**Comment by pavel-savinov** [comment]
Resent with changes here https://github.com/liferay-echo/liferay-portal/pull/2771

**Pull request closed without merging**
