### PR TITLE
LPS-196590 Test Scenarios Coverage | Test Creation

### PR DESCRIPTION
**Pull request by Mikellorza**
Waiting for the merge : [LPS-196591 Make available locked pages settings at site level #13771](https://github.com/liferay-echo/liferay-portal/pull/13771)

subtask: https://liferay.atlassian.net/browse/LPS-196590

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
Open a PR with the correct LPS, so, I proceed to close this one.

**Comment by Mikellorza** [comment]
https://github.com/liferay-echo/liferay-portal/pull/13795

**Comment by Mikellorza** [comment]
ci:close

**Pull request closed without merging**
