### PR TITLE
LPS-176664 Replace alert divs with clay:alert taglib in asset-list-web

### PR DESCRIPTION
**Pull request by BarbaraCabrera**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @BarbaraCabrera, there is a regression issue. Cannot filter by field
Steps to reproduce

1. Add a web content structure with a Select from List field
2. Add two options for Select from List field
3. Save
4. Add a dynamic collection for Web Content Article and new structure
5. Enable filter by field
6. Select the Select from List field and one option
7. Apply

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'classList')
    at ?browserId=chrome&minifierType=js&languageId=en_US&t=1687838239996&/o/js/resolved-module/asset-list-web@3.0.92/js/SelectStructureField.js:1:845
```
Shown in browser console

**Comment by sandrodw3** [comment]
ci:forward

**Comment by BarbaraCabrera** [comment]
ci:reevaluate:1267401_10164

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
