### PR TITLE
LPS-168383 Apply aria-current properly

### PR DESCRIPTION
**Pull request by sandrodw3**
This PR depends on https://github.com/liferay-frontend/liferay-portal/pull/3006, so I'm putting this on hold until it's merged.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Hi @sandrodw3 , compile failed for file:/home/liferay/portal/master/modules/apps/frontend-taglib/frontend-taglib/classes/META-INF/resources/screen_navigation/page.jsp(43,3) PWC6131: Attribute activeItemAriaCurrent invalid for tag navigation-bar according to TLD
, could you take a look? thanks!

**Comment by sandrodw3** [comment]
> Hi @sandrodw3 , compile failed for file:/home/liferay/portal/master/modules/apps/frontend-taglib/frontend-taglib/classes/META-INF/resources/screen_navigation/page.jsp(43,3) PWC6131: Attribute activeItemAriaCurrent invalid for tag navigation-bar according to TLD , could you take a look? thanks!

Thanks Fiona! Yeah, we actually have to wait for the other PR I mentioned to be merged, so putting this on hold, thanks!

**Comment by ealonso** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
