### PR TITLE
LPS-137569 Rename to className and classPK

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:reevaluate:1267401_16

**Comment by ealonso** [comment]
ci:reevaluate:1267401_16

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1267401_16

**Comment by ealonso** [comment]
ci:reevaluate:1307401_104

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1057401_8208

**Pull request closed without merging**
