### PR TITLE
LPS-138158 Set setShowDeltasDropDown to false to hide the deltas dropdown

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
