### PR TITLE
LPS-176663 Replace alert divs with clay:alert taglib in asset-categories-item-selector-web

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-176663)

## Test Scenarios

- Go to Site Builder > Collections > Create a Manual Collection (any type)
- Go to Site Builder > Pages > Create a Collection Page with the Manual Collection created
- Add a “Collection Filter” fragment
- Click on the fragment to enter Collection Filter options
- In Filter, choose Category 
- Then click in Source 
Screenshot 2023-07-04 at 10 37 46

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
