### PR TITLE
Lps 173201 master

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-173201

This is an updated fix for LPS-173201, The addition of the update command in the service context should be added only when the article is updated, rather than any time the workflow handler update status is called. (It is called both with adding articles and updating articles)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
ci:reevaluate:1377401_8188

**Comment by SamZiemer** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Hi @SamZiemer 
Thanks for the fix!
LGTM!
Regards

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
