### PR TITLE
LPS-198507 Two web content are created when the related display page is previewed during the creation of a new web content

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-198507)

### Changes

Update the articleId value

## Test scenario 1

1.  Create a Display Page.
2. Go to Web Content and try to add a web content.
3. Inside this edit mode, choose the DPT created before as the display page related.
4. Click on preview (you should have the name of the WC already because it will create a draft).
5. After seeing the preview, click on “save as a draft” and then publish.

https://github.com/liferay-echo/liferay-portal/assets/93203423/62b67a5d-0866-4732-adf6-2a24cb063d36

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:forward your dreams

**Comment by p2kmgcl** [comment]
This was a feature: enable creating web content twice as fast :cry:

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
