### PR TITLE
LPS-139952 Only join on ViewCountEntry once

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

There are 2 possible joins for ViewCountEntry, line 328 and line 357. If both joins are added to the final sql without an alias they produce the error `Not unique table/alias: 'ViewCountEntry'`. Because both of the joins are used to produce a ViewCountEntry.viewCount, it is enough to have one of them used.

Can you please review?
https://issues.liferay.com/browse/LPS-139952

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @balazssk,
Could you please add a test for it?
Regards,
Eudaldo.

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
Hi @ealonso ,
Sure, added https://github.com/liferay-echo/liferay-portal/pull/5990/commits/13d6ed1adb3615420e6794cb8337d3bd35055974

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Thanks you very much! @balazssk

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
