### PR TITLE
LPS-176893 | Master

### PR DESCRIPTION
**Pull request by MirnaGama**
**Motivation:** 
[LPS-176893 - Double clicking the accent key in the template editor using a browser with Windows crashes the entire page](https://issues.liferay.com/browse/LPS-176893)

When accidentally double-clicking the accent key, to try to write for example "á", it locks everything and does not allow anything else to be done.

**Steps to Verify**
1. Under default DXP site go to Design > Templates
2. Create a new Widget Template
3. Set a title
4. Double-click the "´´" or "``" accent key

**Results of Investigation**
I hosted my environment for testing purposes. Two machines with OS Windows and one with OS Linux were used. It was discovered that this issue _**is only reproducible when a user is using a browser with Windows**_. 

Using a debug fix, it was discovered that this is a javascript related issue. When the accent key is double-clicked, the [handleChange method in the CodeMirrorEditor.js](https://github.com/liferay/liferay-portal/blob/master/modules/apps/template/template-web/src/main/resources/META-INF/resources/js/ddm_template_editor/components/CodeMirrorEditor.js#L247) is called in loop as it tries to print two accent instead.

**Proposed Solution**
Use a debounce function in the handleChange to delay the character processing.

### CODE REVIEW

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @MirnaGama,
Could you please fix the SF issue and move the jira ticket to review?
Regards,
Eudaldo

**Comment by MirnaGama** [comment]
@ealonso Done ! 😀

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Resent here :)  https://github.com/liferay-echo/liferay-portal/pull/11296

**Comment by victorg1991** [comment]
Thanks @MirnaGama !!

**Pull request closed without merging**
