### PR TITLE
LRAC-14219 Remove the History Tab from the AB Testing Panel in DXP

### PR DESCRIPTION
**Pull request by interaminense**
JIRA Issue https://liferay.atlassian.net/browse/LRAC-14219

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Review by claraizquierdo — CHANGES_REQUESTED** [review]
Hi @interaminense 

Thank you for submitting your PR. The code seem to be working fine. The only thing that fails is the source format. Could you fix it and then we forward the PR? Thank you :)

**Review by claraizquierdo — APPROVED** [review]

**Comment by ealonso** [comment]
Hey @interaminense,
Could you please merge the SF commit with the one that need the changes? in that way the history is going to be easier to read.

**Comment by interaminense** [comment]
Done @ealonso!

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139067

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
