### PR TITLE
LPS-131984 

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@ealonso, only last 2 commits are from the LPS, the rest is in queue to be merged, but it's needed for the changes

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@ealonso, removed extract action commands since it caused failures. Will include them in a later pull since it's not related to this one

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/5298

**Pull request closed without merging**
