### PR TITLE
LPS-168834 Replace liferay-ui:icon with clay:icon in asset-taglib

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
[Link to ticket](https://issues.liferay.com/browse/LPS-168834)

## Test Scenario

* Navigate to Content & Data - > Web Content
* Create a New web content and publish it.
* Click on the add button to create another Web content and go to the Related Asset tag on the right menu. 
* Select the first web content as the related asset and then check the icon to delete the asset.
Screen Shot 2023-01-30 at 10 20 47

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:relevant

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
Hey @BarbaraCabrera, as this one is a link, maybe we can use `clay:link`? I think you can do something like this:

```
<clay:link
	aria-label='<%= LanguageUtil.get(request, "remove") %>'
	cssClass="modify-link"
	data-rowId="<%= assetLinkEntry.getEntryId() %>"
	data-title='<%= LanguageUtil.get(request, "remove") %>'
	href="javascript:void(0);"
	icon="times-circle"
/>
```

It should work, and that way we could remove the `liferay-util:buffer` on top 🎉 could you try?

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
