### PR TITLE
LPS-118027 Journal Article - Basic Info Summary Editor Configuration is not taken into account

### PR DESCRIPTION
**Pull request by jbalsas**
As part of the epic [Reduce variability in WYSIWYG Writing Experience](https://issues.liferay.com/browse/LPS-98577), we worked to [Replace AlloyEditor in the Summary field in Web Content](https://issues.liferay.com/browse/LPS-110011)

Doing so introduced a regression that caused the editor not to use its custom configuration but the default `toolbar_simple`configuration.

**Steps to Reproduce**
- Navigate to`Content & Data > Web Content > Add Basic Web Content`
- Check the Summary localized input on the sidebar panel

**Current Result:** The editor shows a Source button but no Link button

**Expected Result:** The editor should show the following buttons: `[bold, underline, italic, numbered list, bulleted list, link]`

**What was going on?**
The configuration wasn't specifically targetting AlloyEditor, but it was only generating valid configuation for that editor. As we are now using CKEditor, those settings were not being properly honoured.

Additionally, only `<a>` tags were allowed but no attribute, so in practice this editor did not support adding links since their href attributes would've been wiped out on save. This PR addresses this potential bug by adding `a[href]` to the allowedContent rule configuration.

Deploying this PR should make the Summary editor look like the following:

Screen Shot 2020-07-28 at 15 08 47

**Additional Considerations:**

One thing to take into consideration is that `Unlink` is a separate button. Adding it will make the toolbar break to 2 rows (Space being very limited here... :D). Not having it makes it so that the only way to remove links is to actually delete the text or use the contextual (right-click) menu. 

Screen Shot 2020-07-28 at 15 24 24

Screen Shot 2020-07-28 at 15 24 36

My suggestion would be to leave only the `Link` button and work to add the [linkballoon](https://ckeditor.com/docs/ckeditor4/latest/examples/balloontoolbar.html) behaviour so removing links is more obvious.

/cc @JorgeFerrer. I'll add this in an email to Tarik as well, since he's still NOT in GitHub 😂

### CODE REVIEW

**Comment by jbalsas** [comment]
This is a resend of https://github.com/liferay-echo/liferay-portal/pull/1675, because 🤷...

Same commit, force-pushed:
- Rebased to today's `master`
- Removed `Unlink` button that I added only for demo purposes but was not meant to be commited.

**Comment by JorgeFerrer** [comment]
I think your suggestion of not showing the "Unlink" button is reasonable, specially if we can have "Unlink" in the balloon. But even if we don't have time for that, I still believe it's better to miss the Unlink action than to have two rows.

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark:

OK to manual forward and skip retesting if no further changes.

The unique failure looks flaky network connection and similar to known flaky issue https://issues.liferay.com/browse/LRQA-58862

**Comment by jbalsas** [comment]
I've rebased and fixed SF...  hopefully

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
Totally unrelated, but going to retest to see if we can forward automatically instead of manually

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
@liferay-echo, this is green and should be good to forward if you approve. Please, let me know if you have any concerns about this! 🙏

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
ci:forward

**Pull request closed without merging**
