### PR TITLE
LPS-157995 Add actions when editing a page

### PR DESCRIPTION
**Pull request by jkappler**
When editing a content page, cog is replaced by a dropdown with actions

page actions

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:echo

**Comment by ozysouza** [comment]
Just start reviewing :)

**Comment by ozysouza** [comment]
Hi @jkappler, please see https://github.com/liferay-echo/liferay-portal/pull/8906
The other failures are not related to your PR.

**Comment by ozysouza** [comment]
ci:close

**Pull request closed without merging**
