### PR TITLE
LPS-149412 Remove logic to render dropdowns on first click and use new ClayDropDown prop instead

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward 🇮🇨

**Comment by sandrodw3** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114776

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
