### PR TITLE
LPS-139353 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-139353

This is only for master.

@ealonso
@victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by victorg1991** [comment]
Wait @ealonso we are missing some test fixed that I've sent here: https://github.com/liferay-echo/liferay-portal/pull/5886 :p

**Comment by victorg1991** [comment]
ci:stop

**Pull request closed without merging**
