### PR TITLE
LPS-160790 Extract ContentDashboardItemSearchClassMapperTracker to Info Framework

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-160790 Create InfoSearchClassMapper based on ContentDashboardItemSearchClassMapper
- LPS-160790 Create InfoSearchClassMapperTracker interface based on ContentDashboardItemSearchClassMapperTracker
- LPS-160790 Export package
- LPS-160790 Baseline
- LPS-160790 Create InfoSearchClassMapperTrackerImpl based on ContentDashboardItemSearchClassMapperTracker
- LPS-160790 Create FileEntryInfoSearchClassMapper based on FileEntryContentDashboardItemSearchClassMapper
- LPS-160790 Replace usages
- LPS-160790 No longer needed
- LPS-160790 Use new tracker
- LPS-160790 Baseline
- LPS-160790 Add display context to the request, so that we have all services available

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@lfbesada, still trying to send 😢

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:stop

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. I will manually forward it. Please see https://github.com/brianchandotcom/liferay-portal/pull/122005

**Pull request closed without merging**
