### PR TITLE
LPS-186000 Replace custom sql with DSLQuery in fragment-service

### PR DESCRIPTION
**Pull request by YurenaC**
[Story](https://liferay.atlassian.net/browse/LPS-186000)

COMMITS
--------------

- LPS-186000 Tests to check actual behaviour
- LPS-186000 Migrate FragmentEntry finders to DSLQuery
- LPS-186000 Replace finder SQL queries with DSLQueries within the finder implementation
- LPS-186000 Remove finder methods out of the finderImpl
- LPS-186000 BuildService

### CODE REVIEW

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/12795

**Pull request closed without merging**
