### PR TITLE
LPS-126678 Use scoped editorName instead of editor title

### PR DESCRIPTION
**Pull request by p2kmgcl**
@dacousalr could you have a look at [this change](https://github.com/liferay-echo/liferay-portal/pull/4915/commits/68d57dd6f04e6fb2f8bcffcc09ce2878b544241f)? I've seen it was added on https://issues.liferay.com/browse/LPS-109995, and I am not sure if it might cause a regression.

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
The change looks good and safe to me, @p2kmgcl!

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
