### PR TITLE
[TS] LPS-137055 Hide this option like how SetAsDefaultAssetPublisher is hidden

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

Given that 'Show only assets with [name] as its display page template' sets a layoutUuid filter to to the Asset Publisher's query, it is not needed if we can't set a page as Display Page Template using a default Asset Publisher (https://issues.liferay.com/browse/LPS-108269).

Another approach would be to improve how asset searching happens, but I wanted to validate the easier solution first.

Can you please review?
https://issues.liferay.com/browse/LPS-137055

Thanks,
Balázs

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
Hi @balazssk, lets go with this approach (also talked with @dacousalr about it). What we are going to do in any case is document this. From what I recall we also documented not being able to set the AP as default in display page templates.

Thanks as always

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:stop

**Comment by liulukiwi** [comment]
ci:forward

**Pull request closed without merging**
