### PR TITLE
LPS-133321 buildLang

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
Hey @Tim-Cao, this PR has the dropdown changes I mentioned some days ago. Tarik hasn't update the story definition yet (I hope he can make it soon) but Juan does have updated the design mockup, so please use it as reference: https://www.figma.com/file/cqD839xlWqaivw3Ohi5yFG/LPS-120606-Browse-content-used-on-a-Page?node-id=677%3A273091

As a general idea, we are going to have two buttons:
1. One with add/change options, which will open a dropdown if there are other mapped items
2. One with "remove item" option, and edit/permissions/usages options. These three only appear if the contentBrowsingEnabled feature flag has been enabled.

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
(I am also updating JS tests, will add a commit in some minutes)

**Comment by p2kmgcl** [comment]
JS tests updated :smile:

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/4762

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
