### PR TITLE
[TS] LPS-111332

### PR DESCRIPTION
**Pull request by dacousalr**
Hi @ealonso, this PR fixes a problem when changing between sites that have disjoint available languages. However, the code that fixes the issue is located in PortalImpl. Should I redirect this PR to Core Infra or could you handle its review? Thanks in advance

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @dacousalr,
Could you please send this one to the Core Infra Team?

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
ci:stop

**Pull request closed without merging**
