### PR TITLE
LPS-164647 - Adapt backend to return page tree in format required by clay tree view

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @sandrodw3 @lfbesada

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1257401_5077

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
@ruben-pulido I saw that you create a new LayoutActionProvider and it is only used in one place, why not creating an internal class, instead of a class into an api module?

**Comment by ruben-pulido** [comment]
> @ruben-pulido I saw that you create a new LayoutActionProvider and it is only used in one place, why not creating an internal class, instead of a class into an api module?

That's a good point! Feedback incorporated [here](https://github.com/liferay-echo/liferay-portal/pull/10046)

**Pull request closed without merging**
