### PR TITLE
[TS] LPS-180207 Title and description of web content are copied from inactive to default locale

### PR DESCRIPTION
**Pull request by ricardocousolr**
Motivation
=======
This issue ([LPS-180207](https://issues.liferay.com/browse/LPS-180207)) was reported by a customer. 

The wrong information might be shown for the default language title and description when a language is moved from current to available in Instance Settings (or elsewhere).

Proposed Solution
========
The problem arises because the method `LocaleUtil.fromLanguageId` by default will validate that the locale for that `languageId` exists and if it doesn't, it will use the default locale instead. So if there was a translation in a web content for a non-default language and we make that language unavailable, we might assign the title and description of the non-default language to the default language. (It may or not happen depending on the order of the locales in `journalArticleLocalizationList`.)

The proposed solution is to get the locale passing the arguments `validate = true` but `useDefault = false` in `LocalUtil.fromLanguageId`. If the result is `null` we don't add the information for that locale to the map.

Steps to Verify
========
Those in ([LPS-180207](https://issues.liferay.com/browse/LPS-180207)).

References to existing code
========

Checklist (optional)
========

CODE:
- [x] I have considered breaking this PR into smaller PRs if the amount of changed code is too large
- [x] I have performed a self-review of my own code following Liferay's code conventions
- [x] I have checked other areas of the product for solutions to similar problems
- [ ] I have added tests that prove my fix is effective or that my feature works

COMMITS:
- [x] My commits organize changes in coherent units
- [x] There are no commits which should be combined into others
- [x] My commits are ordered in a way that ease understanding
- [x] My commit messages are well formatted and concisely describe what was changed and why it was changed

PR TITLE & DESCRIPTION:
- [x] My PR title includes an issue number and a descriptive title
- [x] My PR description explains the motivation for this change
- [x] My PR description explains the proposed solution
- [x] My PR description includes the steps to verify the change
- [ ] My PR description includes references to other places where this solution is used (if applies)
- [ ] My PR description includes visual aids to understand what has changed (if applies)
- [ ] My PR description explains alternative approaches considered and why they were discarded (if applies)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
Hi @ricardocousolr 

I haven't reviewed the code, since it is currently assigned to @lfbesada, but the checkstyle failures are related with the changes.

```
     [java] 1: Method 'Validator.isNotNull' should only be used for type 'Long', 'Serializable' or 'String': ./modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java 2269 (Checkstyle:ValidatorIsNullCheck)
     [java] 2: Method 'Validator.isNotNull' should only be used for type 'Long', 'Serializable' or 'String': ./modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java 2984 (Checkstyle:ValidatorIsNullCheck)
```

Can you fix them? Thanks!

**Comment by ricardocousolr** [comment]
Hi @ruben-pulido!
I'll fix that and update the pr.

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ricardocousolr** [comment]
Hi @lfbesada,

I've just updated the pr with the correction requested by @ruben-pulido

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
@ricardocousolr Thanks for the fix ❤️ 
LGTM 🎉 
Regards

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
