### PR TITLE
LPS-181550

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, there is a regression issue for preview window in fragment editor.
**Steps to reproduce**

1. Add a basic fragment with the following codes
```
<div class="fragment_5">
Fragment Name
</div>
```
2. Publish the fragment
3. Edit the fragment
4. Make some changes
```
<div class="fragment_5">
Fragment Name 1
</div>
```
Actual Results
The preview window still shows the old content.

**Comment by Tim-Cao** [comment]
ci:forward:force

**Pull request closed without merging**
