### PR TITLE
LPS-143841 Give feedback when item does not have display page

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant 🦄

**Comment by veroglez** [comment]
LGTM! 🥳

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @lfbesada,

Why we are not using the following code?

```java
if (!AssetDisplayPageUtil.hasAssetDisplayPage(
				groupId, layoutDisplayPageObjectProvider.getClassNameId(),
				layoutDisplayPageObjectProvider.getClassPK(),
				layoutDisplayPageObjectProvider.getClassTypeId())) {

			return null;
		}
```

instead of

```java
_assetDisplayPageFriendlyURLProvider.getFriendlyURL(
						_portal.getClassName(classNameId), classPK,
						themeDisplay))
```

**Comment by ealonso** [comment]
Hey @lfbesada,

Also we should move 

```java

<react:component
				module="js/DisplayPageItemContextualSidebar"
				props='<%=
					HashMapBuilder.<String, Object>put(
						"chooseItemProps", displayPageTypeSiteNavigationMenuTypeDisplayContext.getChooseInfoItemButtonContext(request, liferayPortletResponse)
					).put(
						"defaultLanguageId", displayPageTypeSiteNavigationMenuTypeDisplayContext.getDefaultLanguageId()
					).put(
...
	).build()
				%>'
			/>

```
to the display context

**Comment by lfbesada** [comment]
Hey @ealonso,

Thanks for the tip! I didn't know about AssetDisplayPageUtil existed and that is just what I need there.

I will resend with that and move the creation of the DisplayPageItemContextualSidebar's props to the display context

Thanks!

**Comment by sandrodw3** [comment]
https://github.com/liferay-echo/liferay-portal/pull/7078

**Pull request closed without merging**
