### PR TITLE
LPS-160790 Extract ContentDashboardItemSearchClassMapperTracker to Info Framework

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-160790 Create InfoSearchClassMapper based on ContentDashboardItemSearchClassMapper
- LPS-160790 Create InfoSearchClassMapperTracker interface based on ContentDashboardItemSearchClassMapperTracker
- LPS-160790 Export package
- LPS-160790 Baseline
- LPS-160790 Create InfoSearchClassMapperTrackerImpl based on ContentDashboardItemSearchClassMapperTracker
- LPS-160790 Create FileEntryInfoSearchClassMapper based on FileEntryContentDashboardItemSearchClassMapper
- LPS-160790 Replace usages
- LPS-160790 No longer needed
- LPS-160790 Use new tracker
- LPS-160790 Add display context to the request, so that we have all services available

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:echo

**Comment by jkappler** [comment]
@david-gutierrez-mesa, @Tim-Cao, @liulukiwi, @ozysouza. Quite a big change, so that's why I'm mentioning you....

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:test:echo

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:echo

**Comment by liulukiwi** [comment]
ci:test:bundle

**Comment by liulukiwi** [comment]
Hi @jkappler , some integration tests fails for apps:content-dashboard:content-dashboard-web:compileJava, could you take a look?
`[exec] > Task :apps:content-dashboard:content-dashboard-web:processResources
     [exec] > Task :apps:content-dashboard:content-dashboard-web:classes
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DDMStructureContentDashboardItemSubtypeTest.java:52: error: cannot find symbol
     [exec] 		DDMStructureContentDashboardItemSubtype
     [exec] 		^
     [exec]   symbol:   class DDMStructureContentDashboardItemSubtype
     [exec]   location: class DDMStructureContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DDMStructureContentDashboardItemSubtypeTest.java:54: error: cannot find symbol
     [exec] 				new DDMStructureContentDashboardItemSubtype(
     [exec] 				    ^
     [exec]   symbol:   class DDMStructureContentDashboardItemSubtype
     [exec]   location: class DDMStructureContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DDMStructureContentDashboardItemSubtypeTest.java:87: error: cannot find symbol
     [exec] 		DDMStructureContentDashboardItemSubtype
     [exec] 		^
     [exec]   symbol:   class DDMStructureContentDashboardItemSubtype
     [exec]   location: class DDMStructureContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DDMStructureContentDashboardItemSubtypeTest.java:89: error: cannot find symbol
     [exec] 				new DDMStructureContentDashboardItemSubtype(
     [exec] 				    ^
     [exec]   symbol:   class DDMStructureContentDashboardItemSubtype
     [exec]   location: class DDMStructureContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DDMStructureContentDashboardItemSubtypeTest.java:91: error: cannot find symbol
     [exec] 		DDMStructureContentDashboardItemSubtype
     [exec] 		^
     [exec]   symbol:   class DDMStructureContentDashboardItemSubtype
     [exec]   location: class DDMStructureContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DDMStructureContentDashboardItemSubtypeTest.java:93: error: cannot find symbol
     [exec] 				new DDMStructureContentDashboardItemSubtype(
     [exec] 				    ^
     [exec]   symbol:   class DDMStructureContentDashboardItemSubtype
     [exec]   location: class DDMStructureContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DDMStructureContentDashboardItemSubtypeTest.java:105: error: cannot find symbol
     [exec] 		DDMStructureContentDashboardItemSubtype
     [exec] 		^
     [exec]   symbol:   class DDMStructureContentDashboardItemSubtype
     [exec]   location: class DDMStructureContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DDMStructureContentDashboardItemSubtypeTest.java:107: error: cannot find symbol
     [exec] 				new DDMStructureContentDashboardItemSubtype(
     [exec] 				    ^
     [exec]   symbol:   class DDMStructureContentDashboardItemSubtype
     [exec]   location: class DDMStructureContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DDMStructureContentDashboardItemSubtypeTest.java:112: error: cannot find symbol
     [exec] 		DDMStructureContentDashboardItemSubtype
     [exec] 		^
     [exec]   symbol:   class DDMStructureContentDashboardItemSubtype
     [exec]   location: class DDMStructureContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DDMStructureContentDashboardItemSubtypeTest.java:114: error: cannot find symbol
     [exec] 				new DDMStructureContentDashboardItemSubtype(
     [exec] 				    ^
     [exec]   symbol:   class DDMStructureContentDashboardItemSubtype
     [exec]   location: class DDMStructureContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DDMStructureContentDashboardItemSubtypeTest.java:126: error: cannot find symbol
     [exec] 		DDMStructureContentDashboardItemSubtype
     [exec] 		^
     [exec]   symbol:   class DDMStructureContentDashboardItemSubtype
     [exec]   location: class DDMStructureContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DDMStructureContentDashboardItemSubtypeTest.java:128: error: cannot find symbol
     [exec] 				new DDMStructureContentDashboardItemSubtype(
     [exec] 				    ^
     [exec]   symbol:   class DDMStructureContentDashboardItemSubtype
     [exec]   location: class DDMStructureContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DLFileEntryTypeContentDashboardItemSubtypeTest.java:53: error: cannot find symbol
     [exec] 		DLFileEntryTypeContentDashboardItemSubtype
     [exec] 		^
     [exec]   symbol:   class DLFileEntryTypeContentDashboardItemSubtype
     [exec]   location: class DLFileEntryTypeContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DLFileEntryTypeContentDashboardItemSubtypeTest.java:55: error: cannot find symbol
     [exec] 				new DLFileEntryTypeContentDashboardItemSubtype(
     [exec] 				    ^
     [exec]   symbol:   class DLFileEntryTypeContentDashboardItemSubtype
     [exec]   location: class DLFileEntryTypeContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DLFileEntryTypeContentDashboardItemSubtypeTest.java:89: error: cannot find symbol
     [exec] 		DLFileEntryTypeContentDashboardItemSubtype
     [exec] 		^
     [exec]   symbol:   class DLFileEntryTypeContentDashboardItemSubtype
     [exec]   location: class DLFileEntryTypeContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DLFileEntryTypeContentDashboardItemSubtypeTest.java:91: error: cannot find symbol
     [exec] 				new DLFileEntryTypeContentDashboardItemSubtype(
     [exec] 				    ^
     [exec]   symbol:   class DLFileEntryTypeContentDashboardItemSubtype
     [exec]   location: class DLFileEntryTypeContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DLFileEntryTypeContentDashboardItemSubtypeTest.java:93: error: cannot find symbol
     [exec] 		DLFileEntryTypeContentDashboardItemSubtype
     [exec] 		^
     [exec]   symbol:   class DLFileEntryTypeContentDashboardItemSubtype
     [exec]   location: class DLFileEntryTypeContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DLFileEntryTypeContentDashboardItemSubtypeTest.java:95: error: cannot find symbol
     [exec] 				new DLFileEntryTypeContentDashboardItemSubtype(
     [exec] 				    ^
     [exec]   symbol:   class DLFileEntryTypeContentDashboardItemSubtype
     [exec]   location: class DLFileEntryTypeContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DLFileEntryTypeContentDashboardItemSubtypeTest.java:108: error: cannot find symbol
     [exec] 		DLFileEntryTypeContentDashboardItemSubtype
     [exec] 		^
     [exec]   symbol:   class DLFileEntryTypeContentDashboardItemSubtype
     [exec]   location: class DLFileEntryTypeContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DLFileEntryTypeContentDashboardItemSubtypeTest.java:110: error: cannot find symbol
     [exec] 				new DLFileEntryTypeContentDashboardItemSubtype(
     [exec] 				    ^
     [exec]   symbol:   class DLFileEntryTypeContentDashboardItemSubtype
     [exec]   location: class DLFileEntryTypeContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DLFileEntryTypeContentDashboardItemSubtypeTest.java:116: error: cannot find symbol
     [exec] 		DLFileEntryTypeContentDashboardItemSubtype
     [exec] 		^
     [exec]   symbol:   class DLFileEntryTypeContentDashboardItemSubtype
     [exec]   location: class DLFileEntryTypeContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DLFileEntryTypeContentDashboardItemSubtypeTest.java:118: error: cannot find symbol
     [exec] 				new DLFileEntryTypeContentDashboardItemSubtype(
     [exec] 				    ^
     [exec]   symbol:   class DLFileEntryTypeContentDashboardItemSubtype
     [exec]   location: class DLFileEntryTypeContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DLFileEntryTypeContentDashboardItemSubtypeTest.java:131: error: cannot find symbol
     [exec] 		DLFileEntryTypeContentDashboardItemSubtype
     [exec] 		^
     [exec]   symbol:   class DLFileEntryTypeContentDashboardItemSubtype
     [exec]   location: class DLFileEntryTypeContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/DLFileEntryTypeContentDashboardItemSubtypeTest.java:133: error: cannot find symbol
     [exec] 				new DLFileEntryTypeContentDashboardItemSubtype(
     [exec] 				    ^
     [exec]   symbol:   class DLFileEntryTypeContentDashboardItemSubtype
     [exec]   location: class DLFileEntryTypeContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/BlogsEntryContentDashboardItemSubtypeTest.java:56: error: cannot find symbol
     [exec] 		BlogsEntryContentDashboardItemSubtype
     [exec] 		^
     [exec]   symbol:   class BlogsEntryContentDashboardItemSubtype
     [exec]   location: class BlogsEntryContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/BlogsEntryContentDashboardItemSubtypeTest.java:58: error: cannot find symbol
     [exec] 				new BlogsEntryContentDashboardItemSubtype();
     [exec] 				    ^
     [exec]   symbol:   class BlogsEntryContentDashboardItemSubtype
     [exec]   location: class BlogsEntryContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/BlogsEntryContentDashboardItemSubtypeTest.java:77: error: cannot find symbol
     [exec] 		BlogsEntryContentDashboardItemSubtype
     [exec] 		^
     [exec]   symbol:   class BlogsEntryContentDashboardItemSubtype
     [exec]   location: class BlogsEntryContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/BlogsEntryContentDashboardItemSubtypeTest.java:79: error: cannot find symbol
     [exec] 				new BlogsEntryContentDashboardItemSubtype();
     [exec] 				    ^
     [exec]   symbol:   class BlogsEntryContentDashboardItemSubtype
     [exec]   location: class BlogsEntryContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/BlogsEntryContentDashboardItemSubtypeTest.java:83: error: cannot find symbol
     [exec] 				new BlogsEntryContentDashboardItemSubtype()));
     [exec] 				    ^
     [exec]   symbol:   class BlogsEntryContentDashboardItemSubtype
     [exec]   location: class BlogsEntryContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/BlogsEntryContentDashboardItemSubtypeTest.java:88: error: cannot find symbol
     [exec] 		BlogsEntryContentDashboardItemSubtype
     [exec] 		^
     [exec]   symbol:   class BlogsEntryContentDashboardItemSubtype
     [exec]   location: class BlogsEntryContentDashboardItemSubtypeTest
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/content-dashboard/content-dashboard-web/src/test/java/com/liferay/content/dashboard/web/internal/item/type/BlogsEntryContentDashboardItemSubtypeTest.java:90: error: cannot find symbol
     [exec] 				new BlogsEntryContentDashboardItemSubtype();
     [exec] 				    ^
     [exec]   symbol:   class BlogsEntryContentDashboardItemSubtype
     [exec]   location: class BlogsEntryContentDashboardItemSubtypeTest
     [exec] 
     [exec] > Task :apps:content-dashboard:content-dashboard-web:compileTestJava
     [exec] Note: Some input files use or override a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] Note: Some input files use unchecked or unsafe operations.
     [exec] Note: Recompile with -Xlint:unchecked for details.
     [exec] 31 errors
     [exec] 
     [exec] > Task :apps:content-dashboard:content-dashboard-web:compileTestJava FAILED`

Except for this issue, there's no new issue found releted to this pull.

**Comment by jkappler** [comment]
Hi @liulukiwi, thanks for taking a look at it. It's not related to the PR, please see https://issues.liferay.com/browse/LPS-160634. I saw that it was failing in upstream so I helped out and sent a fix https://github.com/liferay-tango/liferay-portal/pull/2705

**Comment by jkappler** [comment]
Will send to Tango Team for final review

**Pull request closed without merging**
