### PR TITLE
LPD-15679 Display Page templates display default values when source is empty

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPD-15679)

### Changes

Return blank when the value is null.

## Test scenario 

1. Create structure with one Text field
2. Create a new display page template where Content Type is Web Content Ariticle and Subtype is your new structure
3. Add an html element to the Display Page Template and dynamically map the value to your Text field from your new structure
4. Mark new display page template as default
5. Create a new web content with the new structure and leave the text field blank
6. Edit the web content and in the Display Page Settings select "Preview"

https://github.com/liferay-echo/liferay-portal/assets/93203423/de86b5ff-699d-4023-a920-8eec903095d7

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
@BarbaraCabrera Could you please add a test for it?

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
