### PR TITLE
LPD-32919 Adapt usages

### PR DESCRIPTION
**Pull request by sandrodw3**
Hey @igor-franca, as I said in the previous PR, I'm suggesting a change so we keep the previous api we had in the function, with the params like `(page, text, options)`. I just moved the new `type` prop inside the `options`, and I also renamed `page` to `parent` because it can also be a `FrameLocator`. 

This way, the previous calls continue working the same way, and we only have to rename the function on the usages.

I also typed the `type` as `'success' | 'info' | 'warning' | 'danger'` so it's easier to use, and then inside the function I map it to the CSS class.

Could you tell me what you think?

Anyway, when sending this PR I think we should put a message in the Playwright channel letting the people know it, because as you said, it could cause conflicts.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by igor-franca** [comment]
Hey, @sandrodw3. Thanks for handling this, good changes!

**Comment by sandrodw3** [comment]
ci:test:playwright

**Comment by sandrodw3** [comment]
ci:test:playwright

**Comment by ealonso** [comment]
ci:test:playwright

**Comment by igor-franca** [comment]
ci:report:28508755

**Comment by sandrodw3** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/154755

**Pull request closed without merging**
