### PR TITLE
[TS] LPS-154364 - remove disabled class when toggling

### PR DESCRIPTION
**Pull request by wanderlast**
https://issues.liferay.com/browse/LPS-154364

Hi @liferay-echo!

This fix is meant to address an issue in the Look & Feel configuration menu. When one of the "Same For All" toggles is switched on and saved, the next time you re-open the menu all of the fields except the topmost field will be disabled. However, when toggling "Same For All" off, the fields keep their 'disabled' appearance (e.g. cursor is still a 'forbidden action' icon) despite technically being re-enabled (you can click into the fields and add values).

To address this, I've added a step to the toggling method where we remove the 'disabled' class from our classlist in the case of toggling disabled off. Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
Hey @wanderlast!

I've checked the solution, and it looks that only the select input classes are being update, but the text input does not check accordingly. Could you check that, please?

screen-record-2022-06-03_09-44

**Comment by wanderlast** [comment]
Hi @p2kmgcl,

Thanks for taking a look! I had it like that since that's the original behavior, but I've added logic now that should force the labels to reflect the status of the input fields.

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
Thanks for updating that @wanderlast :smile:

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
