### PR TITLE
LPS-147092 & LPS-147400

### PR DESCRIPTION
**Pull request by sandrodw3**
/cc @ealonso @ruben-pulido

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward 🎳

**Comment by ealonso** [comment]
ci:reevaluate:1307401_2106

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113538

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
