### PR TITLE
LPS-197568 Remove d-none attribute value so the link is shown and add url to lear Liferay

### PR DESCRIPTION
**Pull request by Stephy6**
https://liferay.atlassian.net/browse/LPS-187651

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
@Stephy6 you are using the LPS of the story, please change it to the subtask one

**Review by p2kmgcl — APPROVED** [review]

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
