### PR TITLE
LPS-140916 Add missing info to make this view consistent with sites admin

### PR DESCRIPTION
**Pull request by robertoDiaz**
What I've done here is show the same information in my sites portlet as seen in sites admin (users, user groups and organizations).

I've changed the 3 views to be consistent and show the same info in all the cases

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:stable

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
Hey @liferay-echo 

I've introduce some changes.

If you could help me with the functional test, I'll be very thankful :)

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/6424

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
