### PR TITLE
LPS-118863 Do not show App builder standalone apps in the recent sites menu

### PR DESCRIPTION
**Pull request by jeyvison**
Hello, Echo team! :) I hope this is the right place for this PR. I'm sending it to you because i had to create a new module( Brian's request) so i could use a web key. Let me know if you need me to change something and thanks a lot o/

### CODE REVIEW

**Comment by jeyvison** [comment]
ci:test:sf

**Comment by jeyvison** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @jeyvison,
I was trying to reproduce the issue, and I couldn't, Could you please let me know the steps to reproduce?
Thanks!!

**Comment by jeyvison** [comment]
Hi @ealonso , sure :) I just updated the ticket with the steps to reproduce. let me know if you need something else.

**Comment by jeyvison** [comment]
Closing the PR since the Bug is no longer reproducible :) Thanks a lot folks!

**Pull request closed without merging**
