### PR TITLE
LPS-154993 Pass segmentsExperienceId to be used in the fragmentEntryLink creation

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @victorg1991, there is a regression issue found by Poshi cases.
**Steps to reproduce**

1. Add a Heading fragment to a content page
2. Add a new experience for anyone
3. Publish the content page
4. Edit the content page
5. Switch the new experience
6. Click the body of Heading fragment

**Actual Results**
An unexpected error occurred while rendering this item.
image

**Comment by victorg1991** [comment]
should be fixed now, many thanks @Tim-Cao :)

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
