### PR TITLE
LPS-172129 Template Reserved El - Fix the order of parameters for articleId

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
ArticleId is no longer added to Web Content Templates as a reserved variable
https://issues.liferay.com/browse/LPS-172129

Proposed Solution
========
Fixing the parameter order

Steps to Verify
========
1. Add a new Web Content Structure with an html field
2. Add a Template to the Structure from the snippet
3. Create a new Web Content from the new Structure, use the new Template
4. Create a Widget page
5. Add the newly created Web Content to the Widget page

**Expected behaviour:** The variable 'reserved-article-id' should be available
**Actual behaviour:** The 'reserved-article-id' is not available

Snippet
=======
```
<ul>
<#list [
'reserved-article-asset-tag-names',
'reserved-article-author-comments',
'reserved-article-author-email-address',
'reserved-article-author-id',
'reserved-article-author-job-title',
'reserved-article-author-name',
'reserved-article-create-date',
'reserved-article-description',
'reserved-article-display-date',
'reserved-article-id',
'reserved-article-modified-date',
'reserved-article-small-image-url',
'reserved-article-title',
'reserved-article-url-title',
'reserved-article-version'] as theVar>
  <li>
	  <#if (.vars[theVar])??>
		  <@clay["icon"] symbol="check" />
		<#else>
		  <@clay["icon"] symbol="exclamation-full" />
		</#if>&nbsp; ${theVar}
</#list>
</ul>
```

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Hi @balazssk
Thanks for the fix 🎉 
Regards

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
