### PR TITLE
LPS-127548 Export ddm templates for configuration values

### PR DESCRIPTION
**Pull request by victorg1991**
This pr aims to be as simple as possible to make the backport of this issue smoth, a refactor of this class to cover al lthe case will be done in a separate task :)

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
