### PR TITLE
LPS-191767 Adds service validation to prevent a user to modify a draft locked by another user

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-191767

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:test:stable

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi QA Team 👋 , the relevant test execution is failing over and over and I don't guess what's going on. Please, can you help me to see what the problem is?
Thanks in advance!
Regards

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/13078

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @lfbesada
[com.liferay.dispatch.scheduler.test.SchedulerResponseManagerTest](https://testray.liferay.com/home/-/testray/case_results/2397212140)
[com.liferay.content.dashboard.web.internal.portlet.test.ContentDashboardAdminPortletGetPropsTest](https://testray.liferay.com/home/-/testray/case_results/2397212118)
[com.liferay.portal.company.log.web.internal.servlet.test.CompanyLogServletTest](https://testray.liferay.com/home/-/testray/case_results/2397213236)

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
resend it here: https://github.com/liferay-echo/liferay-portal/pull/13116

**Pull request closed without merging**
