### PR TITLE
[7.4.x-only] LPS-116774 & LPS-104151 & LPS-109123 Enable Data Engine by default on Web Content

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
@liulukiwi

**Comment by liulukiwi** [comment]
Resend it here:
https://github.com/liferay-echo/liferay-portal/pull/2768

**Comment by victorg1991** [comment]
ci:close

**Pull request closed without merging**
