### PR TITLE
LPS-168761 HR_446 Any action is not getting performed by pressing ctrl+Upward arrow+M

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @veroglez 

Is it possible to do something like we did in the hide sidebar button? 

https://github.com/liferay-echo/liferay-portal/blob/748079b6a4522d5ae29ee905d5f5d9984f82a56b/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/HideSidebarButton.js#L36-L56

In that case it has the tooltip and also it is read correctly in the screen reader

**Comment by victorg1991** [comment]
P'alante 👏

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
