### PR TITLE
LPS-130416 Update view mode to take into account the new format of localize href

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reevaluate:1257401_3472

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The failure case is unrelated to this PR. In order to save CI resource, I've sent this PR to BChan directly.
https://github.com/brianchandotcom/liferay-portal/pull/105231

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
