### PR TITLE
LPS-110707 Move DragPreview outside Layout content

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:close, Fix SF, 🤦

**Comment by ealonso** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:reopen

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/293

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
