### PR TITLE
LRAC-14634 It is not possible to edit the page if the variant is published in the AB test

### PR DESCRIPTION
**Pull request by Mikellorza**
https://liferay.atlassian.net/browse/LRAC-14634

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by manuferreira** [comment]
Hey, guys. I'm a QA from AC and while testing this PR with the new commits I found a new bug caused by these changes, I already spoke with Marcos Martins and Adriano Interaminense about this issue. While testing I discovered that if my AB test has data and I publish a variant (not the control)  and then go to AC and try to open the terminated (after I published the variant) I can't open the test, I get a blank screen on AC side.

**Comment by manuferreira** [comment]
ci:stop

**Comment by Mikellorza** [comment]
Hey @ruben-pulido ,

The PR is ready to review again. I made some changes and I tested it with the Riccardo's env and it seems that now all is working fine.

Thanks!

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
