### PR TITLE
LPS-131407 Change default preferences for Asset publisher like portlets | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-131407

This is only for master.

Setting this as on hold until https://issues.liferay.com/browse/LPS-148093 is resolved
@victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by victorg1991** [comment]
resent here:https://github.com/liferay-echo/liferay-portal/pull/7372

**Pull request closed without merging**
