### PR TITLE
LPS-198953 Fix bugs in page audit

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Repeated section on the PageSpeed Insights tab of Page Audit.
Some sections should appear collapsed
Repeated section on the PageSpeed Insights tab of Page Audit
[Link to story or ticket](https://liferay.atlassian.net/browse/LPS-198953)

Steps to Verify:
----------------

1. Go to a Page, example Home
2. Click on the Page Audit
3. Go to the PageSpeed Insights tab
4. Click on Configure, add you API Key and Save
5. Launch the Page Audit
6. Click on any of the elements
7. The detailed view of the element opens

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by p2kmgcl — APPROVED** [review]
Awesome 🤟

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142374

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
