### PR TITLE
LPS-169811 Complex data structure integration tests failures

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-169811)

Recently we added some integration tests because some clients complained about performance issues. These tests are failing because the contain references to existing documents in the portal

## Change summary:

* Change structure xml so that we can replace the references with an existing file entry
* Tests have been ignore because they take to long to run. Will be enabled once performance tuning is done

## Test Scenario

* No test scenario, since the tests are ignored

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
@ealonso

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@jkappler merged to master.

**Pull request closed without merging**
