### PR TITLE
LPS-131314 BuildLang

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Hi @ealonso, Let me try me best to update today since this is a huge UI change.

**Comment by Tim-Cao** [comment]
Hi @ealonso, there is an issue, could you fix it?
Following the same steps in https://issues.liferay.com/browse/LPS-129939

**Comment by Tim-Cao** [comment]
I think I finished poshi update.
See https://github.com/liferay-echo/liferay-portal/pull/4404

**Pull request closed without merging**
