### PR TITLE
LPS-114454 and LPS-114455: Implement FormProvider for JournalArticle and BlogsEntry

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/870

**Pull request closed without merging**
