### PR TITLE
LPS-190088 Change LPS of the Feature Flag for story LPS-186155

### PR DESCRIPTION
**Pull request by claraizquierdo**
We have used the wrong LPS for the feature flag in the story https://liferay.atlassian.net/browse/LPS-186155 and this PR fixes that.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
Hey clara :) code looks good to me. The commit message is missing the LPS number though, could you update that? Also I believe we should be updating the portal.properties file to update the FF there too, right?

Thanks!!

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137625

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
