### PR TITLE
Lps 118136

### PR DESCRIPTION
**Pull request by SamZiemer**
Notes from @Noornajj:

Test result: https://github.com/brianikim/liferay-portal/pull/106#issuecomment-668925047

> https://issues.liferay.com/browse/LPS-118136
> 
> The issues here were the following:
> 
> 1. validateModel in JournalArticleModelValidator was creating a temp file name for the featured image attached to the article and when that image was getting validated on allowed file extensions it was returning an error because the file extension was not added to the temp file name. To fix this bug, I create smallImageFile by calling FileUtil.createTempFile(String extension) instead of FileUtil.createTempFile(bytes[] bytes). This creates an empty file with the image's extension added to the name. Then I write out the image to the file.
> 2. When the image is deleted and modelValidate creates a temp file for the image, it tries to write out smallImageBytes but this is a null value. This results in a file exception error to occur and the model validator does not catch this exception. I fixed this by adding a condition before creating the temp file that smallImageBytes not be equal to null and also adding a check whether smallImageBytes is null in validateReferences() before throwing a NoSuchImageException.
> 3. The script was not sending descriptive exception error messages. I added two messages; one in validateReferences() for when the image does not exist, and one in validate() for when the file extension is not valid.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
resend here: https://github.com/liferay-echo/liferay-portal/pull/1839

**Pull request closed without merging**
