### PR TITLE
[TS] LPS-198057 Fix login button with called ckeditor invalid

### PR DESCRIPTION
**Pull request by henriquelimadotcom**
Ticket: https://liferay.atlassian.net/browse/LPS-198057
cc: @dacousalr 

<h1>Motivation</h1>
Make the login button work correctly
<h1>Proposed Solution</h1>
The proposed solution involved manipulating the WebKeys.AUI_SCRIPT_DATA attribute of the HttpServletRequest object to resolve an issue that affected the functionality of the login button. The change included creating a new empty ScriptData object before processing the FreeMarker model and then restoring the original value in the finally block, in order to avoid rendering unused Javascript code introduced by aui:script taglib in the OTB Rich Text Input fragment when this fragement is validated in the first request
<h1>Steps to Verify</h1>
Steps to reproduce:

Set the following properties in the [portal-ext.properties](http://portal-ext.properties/) file:

setup.wizard.enabled=false 
browser.launcher.url=

The setup.wizard.enabled=false setting is only required if we want to see the issue at the first startup. If this is not set, we need to go through the setup wizard and restart the portal to reproduce the issue.The browser.launcher.url= setting is required to reproduce the issue. 

Start the Liferay from Docker image

Open http://localhost:8080/ in Google Chrome

Expected result: user can log in when credentials typed in and clicked on the ‘Sign in’ button

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
@henriquelimadotcom, Could you please fix the source formmating issue?

**Comment by henriquelimadotcom** [comment]
ci:test:sf

**Comment by henriquelimadotcom** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
Hi @henriquelimadotcom 
Thanks for the fix! :heart: 
I've asserted that it works fine but I don't understand why that fix is added at the fragment validation. I'm concerned that it could cause other errors since it is applied to all fragments.
Please could you please help me understand why this solution has to be applied at this point instead of in the rendering of the affected view?
Thanks in advance!

**Comment by lfbesada** [comment]
see: https://github.com/liferay-appsec/liferay-portal/pull/1435

**Review by lfbesada — APPROVED** [review]
I did not understand the problem correctly before but @dacousalr has helped me understand it.
So the fix LGTM! 
I am sorry for the inconvenience!
Regards

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
Hey @henriquelimadotcom @lfbesada,
I cannot reproduce the issue following the description steps with a clean database in 4822744faf073f24e00e9069d11c51a208e43635.

Could you please help me with it?

**Comment by henriquelimadotcom** [comment]
hi @ealonso need haved this line in properties: navegador.launcher.url=

**Comment by ealonso** [comment]
Hey @henriquelimadotcom,

Do you mean browser.launcher.url=?

**Comment by ealonso** [comment]
Hey @henriquelimadotcom @lfbesada,

I think we need to find another solution for this issue, we shouldn't add it to FreeMarkerFragmentEntryValidator.java, IMHO we should find why we it is necessary and it is not being added.

For the moment, I'm going to close the pr while we find another solution.

Regards,
Eudaldo.

**Comment by ealonso** [comment]
Hey @henriquelimadotcom @lfbesada,

Finally I understood the problem, thanks you very much for the fix!! I'm going to forward it, and sorry for the late response.

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
Much better, I'm going to rewrite the commit message to reflect the real problem and why the fix is in FragmentValidator

**Comment by ealonso** [comment]
Please see: https://github.com/liferay-echo/liferay-portal/pull/14438

I kept your code, I only changed the commit message to make it more clear.

**Comment by pyoo47** [comment]
@henriquelimadotcom I had to abort the `relevant` test because it froze in CI

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:stop

**Pull request closed without merging**
