### PR TITLE
LPS-159619 Update wording of fragment dropzone

### PR DESCRIPTION
**Pull request by DiegoHu97**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
Hey @DiegoHu97,
There are some poshi errors, I think we need to update the poshi tests, also, there is an js error on test. Could you please take a look at it?

**Comment by DiegoHu97** [comment]
taking a look, thanks! @ealonso

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/9228

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
