### PR TITLE
LPS-175543 Extract AssetSearcher from portal-impl

### PR DESCRIPTION
**Pull request by Mikellorza**
Task: https://issues.liferay.com/browse/LPS-155403
Subtask: https://issues.liferay.com/browse/LPS-175543

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1267401_9166

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
ci:test:relevant

**Comment by alessandromalves** [comment]
The probable cause of test failures is an error related to a change in a poshi macro.
 https://github.com/brianchandotcom/liferay-portal/pull/134797 was sent to revert the changes. I'll run the CI again

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @Mikellorza, Cannot add asset into manual collection. Would you mind having a look at?
**Step to reproduce**
1. Add three blogs entries
2. Add a manual collection for Blogs Entry
3. Click the Select button

**Expected Results:**
Three blogs entry should be shown on Select Blogs Entry modal.

**Actual Results:**
The Select Blogs Entry modal is empty.
image

**Comment by jkappler** [comment]
Thanks @Tim-Cao! Will take a look

**Comment by Mikellorza** [comment]
@Tim-Cao  thanks

**Comment by jkappler** [comment]
Please see https://github.com/liferay-echo/liferay-portal/pull/12149

**Pull request closed without merging**
