### PR TITLE
[TS] LPS-151013

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

Fixed failures in https://github.com/liferay-echo/liferay-portal/pull/7785
- ImportFragmentEntriesStrutsActionTest.testImportZipFile
- RenderFragmentEntryStrutsActionTest.testRenderFragment

Please do note that altering the tests uncovered an additional bug: https://issues.liferay.com/browse/LPS-151311, testImportFragmentsSystemWide should fail in this case.

Can you please review?
https://issues.liferay.com/browse/LPS-151013

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @balazssk, could you please check if the test failure is related to your changes? Thanks! Regards

**Comment by ruben-pulido** [comment]
Thanks @balazssk 
I'm going to try to fix https://issues.liferay.com/browse/LPS-151311 and include both fixes in the same PR so we can avoid the test failure in FragmentsImporterTest.testImportFragmentsSystemWide

**Comment by balazssk** [comment]
cheers @ruben-pulido ,
Do you think I can make a hotfix out of the current solution for now?

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Hi @balazssk 

Thank you for the fix! Here is my feedback:

Since referencing resources is also supported in CSS, we need to apply similar logic to the css field, for the fix to be complete. Make sure to rename the parameter html in the _replaceResourceReferences method, so it is more generic.

In general, it is a good practice for tests NOT to share test data. That makes tests independent of each other, and easier to understand. The test data should be as simple as possible to verify the behaviour under test.
Therefore, I would discard the commits merging the test data.

Regarding naming, 'numberOfX' is used more frequently in the code base than 'xNumber' when referring to quantity (as opposed to position) as it is the case here.
Therefore I would rename resourceNumber to expectedNumberOfResources

As a general rule, we should not include in a PR changes that make active tests fail upstream. That would lead to normalizing tests failures upstream, which is a bad practice (and also the reason why only PRs which do not introduce any new test failures can be forwarded to Brian via ci:forward) We can use the @Ignore annotation to temporarily deactivate the test until the code is fixed, or the test is adapted.

Regarding LPS-151311, this is likely to be considered a limitation, and therefore we should not modify the test importing fragment collections systems wide to include resources as part of this PR. If that scenario ends up being supported, it should be tested as part of the PR for LPS-151311.

Thanks!

**Comment by balazssk** [comment]
Cheers @ruben-pulido ,
I'll get to it

**Pull request closed without merging**
