### PR TITLE
LPS-127271 Fix imports

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
Hi @victorg1991, there is another issue with your fix.
The modal is not rendered well when there is no page in site.
Actual
Additionally, the following warning will be thrown in server console
`2021-02-04 01:20:05.576 WARN  [http-nio-8080-exec-2][view_jsp:253] No item selector views found for layout`

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by ealonso** [comment]
ci:stop

**Comment by victorg1991** [comment]
taking a look

**Comment by victorg1991** [comment]
It seems that the failure is not related. I'm going to create a ticket to track it because I need to check the solution with design

Thanks!

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
