### PR TITLE
[TS] LPS-179558 | It is not possible to display web content on the live site when web contents are unstaged

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-179558
Thank you!

-------

**Steps to reproduce:**

1. Go to Publishing --> Staging --> enable local staging and uncheck "Web Content" from the Staged Content.
2. Go to the Live Site --> Content & Data --> Web Content and add basic web content.
3. On Staging Site go to Site Builder --> Pages and add a widget page.
4. Add an Asset Publisher to the page and configure it by Going to Asset Selection and check "Manual"
5. At the "Asset Entries" click on "Select" and choose "Basic Web Content"
6. On the Select Basic Web Content popup, select the web content and click on "Add".
**Expected Result:**  The web content should be added and displayed on the Asset Publisher.
**Actual Result:** the following message appears on the UI:
"The selected asset(s) have been removed from the list because they do not belong in the scope of this widget."
and the web content is not added and not displayed on AP.

The root cause of the issue is that when the selection is added under [addSelection ](https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-publisher-web/src/main/java/com/liferay/asset/publisher/web/internal/helper/AssetPublisherWebHelper.java#L187-L200)the assetEntryType is not specified. I think the reason for this is that the selection can hold any kind of asset in this use case so the selector can't identify the selection type. To solve this get the assetEntryType through the localService just to be safe I added the condition when the assetEntryType is blank. The assetEntryType is needed for the staging environment to decide whether or not the given type is staged.

Note: The customer has a go-live, so if my solution is insufficient and requires additional work, I would like to know whether or not it is sufficient as an SDH.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @bakayattila,

Please see https://github.com/liferay-echo/liferay-portal/pull/11781

**Pull request closed without merging**
