### PR TITLE
LPS-132502 Passing collection itemType as request attribute

### PR DESCRIPTION
**Pull request by lfbesada**
Passing collection itemType as request attribute to check permissions against the proper InfoItemPermissionProvider implementation.

https://issues.liferay.com/browse/LPS-132502

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1297401_161

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1267401_140

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
