### PR TITLE
LPS-193334 Adds a service method to get the Locked Layouts

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-193334

The two methods that this PR adds to LayoutLockManager are going to be used in the follow-up PR corresponding to [LPS-193333](https://liferay.atlassian.net/browse/LPS-193333)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/13350

**Pull request closed without merging**
