### PR TITLE
LPS-171486 Use the same preview that the one that we have in miller columns

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, there is a regression issue. Would you mind having a look at?
The preview with item doesn't work on Preview mode.
Step to reproduce

1. Add a new site
2. Add a web content
3. Add a display page template for Web Content Article and Basic Web Content
4. Add a Button fragment
5. Map the Title field to Button fragment
6. Select the web content as Preview with item
7. Open the dropdown menu of ellipsis button on control menu
8. Preview in a new tab

**Expected Results:**
The title should be shown on Button fragment

**Actual Results:**
The default inline text shown on Button fragment.

**Comment by lfbesada** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/10798

**Pull request closed without merging**
