### PR TITLE
[TS] LPS-123778

### PR DESCRIPTION
**Pull request by bakayattila**
hi Team,

Could you please review this pull request?
https://issues.liferay.com/browse/LPS-123778

Best,
Attila

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by victorg1991** [comment]
Checked by @jkappler and I and it worked fine, thanks!!

I've resent it here: https://github.com/liferay-echo/liferay-portal/pull/3244

**Pull request closed without merging**
