### PR TITLE
LPS-25034 Allow reading fragment.json > icon during import process so that the proper icon of fragments imported is shown using the generator

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @p2kmgcl @Tim-Cao

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The failure task is unrelated to this PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/110640

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
