### PR TITLE
[TS] LPS-147673

### PR DESCRIPTION
**Pull request by jonathanmccann**
This issue occurs after the changes from https://issues.liferay.com/browse/LPS-117934 due to the table class not being regenerated.

These changes were generated by running 'build-upgrade-table' on the 7.3.x branch and then brought forward to the master branch. This was done to avoid including master only changes.

If there are any concerns please let me know.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reevaluate:1267401_1840

**Comment by ealonso** [comment]
Hey @jonathanmccann,

Could you please fix the conflicts and resend?

Thanks!!

**Pull request closed without merging**
