### PR TITLE
LPD-33964 Reset custom styles to Clay Tree in Page Editor Browser

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPD-33964)

### Changes

Reset custom styles to Clay Tree in Page Editor Browser

## Test scenario 

1. Create a content page
2. Go to the page tree
3. Check the changes

Before changes:
image

After changes:
image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:page-managment

**Comment by BarbaraCabrera** [comment]
ci:test:page-management

**Comment by BarbaraCabrera** [comment]
ci:test:page-management

**Comment by BarbaraCabrera** [comment]
ci:test:page-management

**Comment by BarbaraCabrera** [comment]
ci:test:page-management

**Comment by BarbaraCabrera** [comment]
ci:test:page-management

**Comment by ealonso** [comment]
ci:test:page-management

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
Molt be :clap:

**Comment by ealonso** [comment]
ci:forward

**Comment by kenjiheigel** [comment]
ci:reevaluate:1257401_5909

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by kenjiheigel** [comment]
ci:reevaluate:1377401_17792

**Pull request closed without merging**
