### PR TITLE
LPS-189933 UnsupportedOperationException happens on com.liferay.headless.delivery.resource.v1_0.test.SitePageResourceTest.testGetSiteSitePagesPageWithFilterDateTimeEquals

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-189933

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137624

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
