### PR TITLE
[TS] LPS-168238 Site names' xml include incorrect locales configuration after upgrade if the site is configured to inherit locales from the instance

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-168238

The solution implemented in [LPS-146669](https://issues.liferay.com/browse/LPS-146669) is not correctly handling the site locales when they are inherited from the instance, it only works when the locale is not inherited

I have done following changes:

1. I have changed the SQL to include the companyId and the company default languageId. (_The company default languageId is retrieved from the default user of the company_)
2. By default, the site default language id and site locales are obtained from the instance
3. If **inheritLocales=false**, I am getting the site configuration from `typeSettingsUnicodeProperties`
4. If any data don't exist in the typeSettingsUnicodeProperties, as a fallback I am using the data obtained from the instance. (The [LPS-162783](https://issues.liferay.com/browse/LPS-162783) added as fallback a call to `LocaleUtil.getSiteDefault()` but that method always return en_US during upgrade process 😓

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
ci:forward

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/126337

**Pull request closed without merging**
