### PR TITLE
LPS-121886 Migrate v2 usages in layout/layout-set-prototype-web

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

Adding, sorting and deleting Site Templates should work as expected.

**Test plan**:
- From the global menu, select the **Control Panel** tab
- Navigate to **Site Templates**
- From the management toolbar, make sure you can create a Site Template
- From the management toolbar, make sure you can delete a Site Template
- From the management toolbar, make sure you can sort Site Templates

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
cc @ambrinchaudhary @markocikos @jonmak08

**Comment by victorg1991** [comment]
Hey @julien, `layout-set-prototype-web` doesn't belong to the echo team

You probably need to send this directly to @moltam89 :)

**Comment by julien** [comment]
Thanks for the heads up @victorg1991 
When I see "layout" I think of @liferay-echo :heart: 
Will resend

**Comment by julien** [comment]
ci:close

**Comment by julien** [comment]
Sent [here](https://github.com/moltam89/liferay-portal/pull/589)

**Pull request closed without merging**
