### PR TITLE
LPS-147138 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-147138

This is only for master.

Could you review this fix? The error won't be shown on my local.
@lfbesada
cc @david-gutierrez-mesa

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Please see: https://github.com/liferay-echo/liferay-portal/pull/7180

**Comment by lfbesada** [comment]
ci:stop

**Pull request closed without merging**
