### PR TITLE
[TS] LPS-132134

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @liferay-echo,

This is a fix related to site templates and the layoutUpdateable setting. When a site is created based off of a site template, the setting for whether layouts are allowed to be edited or not is passed down to the individual layouts of that site. However, when the setting is changed on the site template, the setting remains on widget page layouts and therefore a layout on a site can remain unable to be edited based off of the previous setting of the site template. This fix checks if a change was made to the setting, checks each layout on the site template to see if the setting is attached to that layout and then alters it on both the source layout as well as all layouts that have it as a source layout. Please let me know if you have any questions or concerns. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @wanderlast,

Could you please send this one to Staging Team? Since they are the owners of Site Templates.

Regards,
Eudaldo

**Comment by wanderlast** [comment]
Hi @ealonso,

Of course! Sorry about that.

**Pull request closed without merging**
