### PR TITLE
LPS-146826 Vocabulary Dynamic Menu Item remove FF

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-146826

@Tim-Cao I have removed the POSHI test line that references the feature flag, it seems to me that it was the proper way. Did I do it properly? Thanks in advance ❤️

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
That's it. LGTM! @lfbesada

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
Hi @lfbesada, feel free to forward

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
