### PR TITLE
[TS] LPS-135330 Content display fragment points to staging web content in live site

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @liferay-echo ,

I've implemented a fix for this staging related issue ([LPS-135330](https://issues.liferay.com/browse/LPS-135330), but also fixes the use-case of [LPS-125882](https://issues.liferay.com/browse/LPS-125882)). The problem is caused by a circular dependency between staged entities, which changes the order of import. Thus, the ID mapping of the JournalArticle will not be available in PortletDataContext, when the references in FragmentEntryLink are replaced.
My fix basically adds Layouts to the list of entity types that should be skipped prior to JournalArticle import: https://github.com/liferay-echo/liferay-portal/commit/cce01c9e3676958d030ff2bc03fb2cce83386185#diff-89c6f3ff2379bd22f157f28fa71fbc6fd2d985d8b0f5a64fb6663d03e54e566aR1283
And it starts importing them, once the JournalArticle record is created (or found for update) and its ID mapping is put in PortletDataContext.
As a final solution, we are investigating whether a 2-phase import for all entries would be possible ([LPS-136646](https://issues.liferay.com/browse/LPS-136646)).
However, that would require changes in the staging framework as well, so I'm changing only `JournalArticleStagedModelDataHandler` now.

Please review my changes.

Thanks,
Vendel

### CODE REVIEW

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
