### PR TITLE
LPS-195920 & LPS-196888 Migrate Selector to clay Picker and Order Display Templates

### PR DESCRIPTION
**Pull request by alessandromalves**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-195920)

## Steps 
- Create a New site Parent
- Inside Parent > Go Design > Templates > Widget templates > create some Asset Publisher Templates
- Create a New child site > Go Design > Templates > Widget templates > create some Asset Publisher Templates
- In the child site > Go Site Builder > Pages
- Create a Content Page 
- Add an Asset Publisher widget
- Go to the widget configuration > Display Settings tab
- See Display Template dropdown
asset

**NOTE: To see the ordered sites, in the child site created before, create another child site and add some widget templates, then create a content page and add an asset-publisher and go to the configuration.**

- I have changed also the Menu Display selector, I moved the aui:script to a new js file and adapted it to the new picker. In the case of site-navigation-breadcrumb, I have only adapted it to the new Picker.
**Menu display**
- Go Site Builder > Pages
- Create a Content Page and add a Menu Display widget
- Go to the widget configuration
menu

**Breadcrumb**
- Go Site Builder > Pages
- Create a Widget Page and add a breadcrumb widget
- Go to the widget configuration
bread

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by alessandromalves** [comment]
ci:forward

**Comment by liulukiwi** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142147

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
