### PR TITLE
LPS-179290 Stop propagation so the card does not activate when pressing the dropdown buttons

### PR DESCRIPTION
**Pull request by p2kmgcl**
Follow up of https://github.com/liferay-echo/liferay-portal/pull/11588

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
cc @victorg1991 

@Tim-Cao this should be ready to go

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward:force

**Pull request closed without merging**
