### PR TITLE
LPD-16325 Check if input labels are defined

### PR DESCRIPTION
**Pull request by georgel-pop-lr**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr! Reviewing the fix I have seen a strange behavior. When a language is selected, the page reloads automatically.
> 
>  Screen.Recording.2024-02-06.at.4.09.34.PM.mov 
> Investigating I have seen that the problem comes exactly from here
> 
> https://github.com/liferay-echo/liferay-portal/blob/eec70a72200c795a2f751b3cac78948855b8ba95/modules/apps/portlet-configuration/portlet-configuration-css-web/src/main/resources/META-INF/resources/view.jsp#L63
> 
> 
> It seems to be a js bug that prevents hidden inputs from changing their `disable` attribute (in this cases these hidden inputs don't have labels). Adding an optional chaining operator in the lines 72 and 77 in that way `input.labels?.length > 0` should be enough to fix this issue 🙂

It is strange as I don't have this behaviour on Chrome, it reloads onChange as we submit the form, then when selecting and setting a new language is not reloading any more.

I will push a commit with this change anyhow to fix this behaviour, as I'm not sure if it is browser related.

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
To test this fix depends on https://github.com/liferay-echo/liferay-portal/pull/15147

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
Hi @veroglez,

I tested your suggestions, and it works well, so I pushed all the changes.

Regards.

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
