### PR TITLE
LPS-198726 Remove input click interaction to open modal and replace placeholder to identify that no item is selected

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by sandrodw3 — COMMENTED** [review]
Hey @veroglez, some things I found:
- I think the selector in the Templates editor described in the ticket is still opening the modal on click, and has the wrong text, could you take a look?
- In the page editor, the inputs have `cursor: pointer`. Now that they are not interactive, should we remove that?

**Comment by veroglez** [comment]
@sandrodw3 yep! my bad! code updated

**Comment by sandrodw3** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @veroglez, could you check this failed js unit test
Execution failed for task ':apps:layout:layout-content-page-editor-web:packageRunTest'
[layout.layout-content-page-editor-web.test.page_editor.common.components.ItemSelector renders the placeholder correctly](https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/397351//testReport/layout.layout-content-page-editor-web.test.page_editor.common/components/ItemSelector_renders_the_placeholder_correctly)

**Comment by veroglez** [comment]
Hi @Tim-Cao! the error of the test is the following:

`TestingLibraryElementError: Cannot find an item with the placeholder text of: select-itemSelectorLabel`

To fix this issue we have changed the placeholder of the item selector, and now it's `no-x-selected` instead of `select-x`. Can you verify this and adapt the poshi test?

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/14037

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
