### PR TITLE
[TS] LPS-170287 Documents and Media - Wrong name is set when creating a folder with a lowercase

### PR DESCRIPTION
**Pull request by thienquach87**
Hi Team,

 Here is the PR for fixing https://issues.liferay.com/browse/LPS-170287. 
Please help to review and leave your comments.
This issue is because [LanguageUtil.get](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/HorizontalCardTag.java#L83-L84) function. 
In some cases, the title of HorizontalCardTag is one of keys in the resources of portal-language-lang, so the return value gotten from portal-language-lang is not right. 
Solution: Add condition to avoid using LanguageUtil.get() functoin in needed.

Thank you!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by thienquach87** [comment]
ci:test:sf

**Comment by thienquach87** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @thienquach87, this is not Echo Team related, can you please send this to Lima Team?

Thanks

**Pull request closed without merging**
