### PR TITLE
LPS-186309 Move and update OpenAI modal

### PR DESCRIPTION
**Pull request by p2kmgcl**
Hey there!

This PR is (almost) the frontend part that makes the OpenAI modal work. We have move the code to the new `ai-creator-openai-web` module, and will show the modal content inside an modal rendered on a JSP.

You might wonder why I am not using `ClayAlert` component and writing al the markup by myself :smiling_face_with_tear:. The default markup of `ClayAlert` has a `container` class that cannot be removed and it messes up when being rendered inside an iframe (the modal content) because it thinks that the screen size is smaller than usual.

If you want to test this manually, you might need to checkout [this other PR that includes everything](https://github.com/lfbesada/liferay-portal/pull/184) and follow these steps:

1. Enable the epic feature flag: `LPS-179483`
2. Go to instance settings > AI Creator.
3. Put an API key (some can be grabbed from our team vault) and press save.
4. Press the white empty button to open the modal.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
sf failed :grimacing:

**Comment by p2kmgcl** [comment]
Let's see now :crossed_fingers:

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by alessandromalves** [comment]
The failures are not related to this PR. See https://github.com/brianchandotcom/liferay-portal/pull/136274

**Pull request closed without merging**
