### PR TITLE
LPS-166857 baseline

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
cc: @BarbaraCabrera

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
Hi @ealonso, there are some failures that I could find so far. Could you please have a look at? I'm still analyzing the results once I finish all I'll let you know.

1. The picture on Home page is not selected by default when starting the portal up.

2. Cannot add a collection page
    - Add a Dynamic Collection
    - Add a collection page based on that collection
  `  
    2022-11-07 14:19:35.666 ERROR [http-nio-8080-exec-4][PortletServlet:117] null
javax.portlet.PortletException: java.lang.NullPointerException
	at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCActionCommand.processAction(BaseMVCActionCommand.java:65) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.callActionMethod(MVCPortlet.java:402) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.LiferayPortlet.processAction(LiferayPortlet.java:82) ~[portal-kernel.jar:?]
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.processAction(MVCPortlet.java:256) ~[portal-kernel.jar:?]
    `
    
   3. These integration tests are failing 
       - BundleSiteInitializerTest.testInitialize
       - DisplayPagesImporterTest.testImportDisplayPageTemplateCollection

**Comment by ozysouza** [comment]
4. There is a NPE when creating a site based on MasterClass and Team Extranet.

`2022-11-07 14:36:42.396 ERROR [http-nio-8080-exec-4][BundleSiteInitializer:544] null
java.lang.NullPointerException: null
	at com.liferay.layout.internal.importer.structure.util.CollectionLayoutStructureItemImporter._getCollectionJSONObject(CollectionLayoutStructureItemImporter.java:271) ~[?:?]
	at com.liferay.layout.internal.importer.structure.util.CollectionLayoutStructureItemImporter._getCollectionConfigAsJSONObject(CollectionLayoutStructureItemImporter.java:240) ~[?:?]
	at com.liferay.layout.internal.importer.structure.util.CollectionLayoutStructureItemImporter.addLayoutStructureItem(CollectionLayoutStructureItemImporter.java:88) ~[?:?]
	at com.liferay.layout.internal.importer.LayoutsImporterImpl._processPageElement(LayoutsImporterImpl.java:1134) ~[?:?]
	at com.liferay.layout.internal.importer.LayoutsImporterImpl._processPageElement(LayoutsImporterImpl.java:1170) ~[?:?]
	at `

**Pull request closed without merging**
