### PR TITLE
LPS-165824 buildLang

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:stop

**Comment by ozysouza** [comment]
@ealonso it seems to be not working yet :/

**Comment by ozysouza** [comment]
ci:forward

**Comment by ealonso** [comment]
@victorg1991 there are some conflicts, Could you please update it?

**Comment by victorg1991** [comment]
ci:forward

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/125198

**Comment by ozysouza** [comment]
ci:close

**Comment by ozysouza** [comment]
@victorg1991, I've close the PR that I sent to Brian because there are new conflicts to solve. Could you have a look?

**Comment by victorg1991** [comment]
manually forrwarded: https://github.com/brianchandotcom/liferay-portal/pull/125203

**Pull request closed without merging**
