### PR TITLE
LPS-192406 UI experience improvement in the Content Dashboard info panel

### PR DESCRIPTION
**Pull request by rafaellajordao**
# **Motivation**
The motivation behind this ticket is to improve Content Dashboard info panels UI experience.
https://liferay.atlassian.net/browse/LPS-164349
https://liferay.atlassian.net/browse/LPS-164348

# **Proposed Solution**
What I did to solve this problem is to change the Details key name to Properties in one of the info panels section and make that section expanded by default when the info panel is open. Also I moved the Categorization section to a new tab by using a new ClayTab.Item and ClayTab.Content when the item has linked vocabularies or tags.

# **Steps to Verify**
2. Create some tags and vocabularies.
3. Create a Display Page Template for web contents.
4. Create a web content and add the tag and vocabularies to it and also attach it to the DPT created.
5. Go to the Content Dashboard.
6. Hover over the web content created and click on the info button in the right side
7. When the info panel is opened, check that the item contains three tabs and all work correctly
8. Also, check the same with some item that hasn't has categories

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by rafaellajordao** [comment]
ci:forward

**Comment by rafaellajordao** [comment]
Resent based on https://github.com/liferay-echo/liferay-portal/pull/13135

**Comment by Tim-Cao** [comment]
Hi @Stephy6, could you have a look at the failed js unit test under apps:content-dashboard:content-dashboard-web

**Comment by Stephy6** [comment]
> Hi @Stephy6, could you have a look at the failed js unit test under apps:content-dashboard:content-dashboard-web

Yes I'm on it

**Comment by ealonso** [comment]
@Stephy6 should we close that one right?

**Comment by Stephy6** [comment]
> @Stephy6 should we close that one right?

Yes!

**Pull request closed without merging**
