### PR TITLE
LPS-141754, LPS-144703

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-141754
https://issues.liferay.com/browse/LPS-144703

See: https://github.com/brianchandotcom/liferay-portal/pull/111665#issuecomment-1003095160

cc: @Tim-Cao

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
