### PR TITLE
LPS-129360

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-129360

Note that this also reverts the "inline" source formatting commit from LPS-125475 ([reference](https://github.com/liferay-echo/liferay-portal/commit/d45cc9b487c920a78bad84a9a6664ca84f45bed6)), as the inlining of the code prevents the fix from working.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Hi @holatuwol! We'll hold the pull until GA1 is out.

Thanks for sending it to us

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/4425

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
