### PR TITLE
LPD-15718, LPD-17734, LPD-17759 Add a new SEO menu in Instance Settings to include specific Sites in the sitemap of Company

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-15718
https://liferay.atlassian.net/browse/LPD-17759
https://liferay.atlassian.net/browse/LPD-17734

Dear reviewer,

LPD-15718 was reviewed [here](https://github.com/liferay-echo/liferay-portal/pull/15158) so only LPD-17734 and LPD-17759 related commits should be reviewed.

The  LPD-17734 related commits are because of [this](https://github.com/brianchandotcom/liferay-portal/pull/147157#issuecomment-1939063922).

Thanks in advance!

cc: @veroglez Thanks! :heart:

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:stable

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:report:2539152956

**Comment by lfbesada** [comment]
ci:test:stable

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
