### PR TITLE
LPS-157053 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-157053

This is only for master.

@david-gutierrez-mesa
cc @magjed4289

Due to our case needs, I've added a new general json macro for add remote app here
https://github.com/liferay-echo/liferay-portal/commit/1a49753b94908690fc99baf3aae4b4db30f45f4d
I didn't add these two URL encoding lines since they are unnecessary.
```
		var urlModified = StringUtil.replace("${url}", ":", "%3A");
		var nameModified = StringUtil.replace("${name}", " ", "%20");
```

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
