### PR TITLE
[TS] LPS-145885

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/112638

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
