### PR TITLE
LPS-117758 Instead of calculating the field values in the display context, try to do it in the resolver so as to simplify logic

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:rest:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
@jorgeFerrer, I couldn't remove InfoDisplayObjectProvider from display_page.jsp because we still need it for permission checking until we can also extract that logic

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
