### PR TITLE
LPS-143207

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Hi @marianoalvarosaiz and @ruben-pulido, would you mind checking the integration test failures? Thanks

**Comment by marianoalvarosaiz** [comment]
Hi @lfbesada, @Tim-Cao, @ruben-pulido,
 I've rebased the pull and reexecute the tests and they have passed: https://github.com/marianoalvarosaiz/liferay-portal/pull/672

If you accept the pull I can forward mine (adding you in cc).

Kind regards.

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @marianoalvarosaiz and @lfbesada, no regression issues found according to [ci:test:echo](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1598983908&testrayRunId=1598983952)

**Comment by marianoalvarosaiz** [comment]
thanks @Tim-Cao

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Thanks for the PR @marianoalvarosaiz 
I just removed the deprecated method and forwarded to Brian
https://github.com/liferay-echo/liferay-portal/pull/6929

**Comment by marianoalvarosaiz** [comment]
Thanks @ruben-pulido

**Pull request closed without merging**
