### PR TITLE
LPS-205255 When content page workflow is enabled the "Publish" button of the UtilityPage turns to "Submit for Workflow"

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-205255

Dear reviewer :hand:  

To solve this bug the last three commits are not necessary. I have added them for consistency since it seemed ugly to me that the UtilityPages use the display context of the PageTemplates, but I can remove them without affecting the fix.
What do you think?

Thanks in advance!

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
I have rebased with the current master and added https://github.com/brianchandotcom/liferay-portal/pull/146045 to pass CI.

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
