### PR TITLE
LPS-124921 Apply the same approach for collection pages and collection display item selector

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
there's ```
[exec] com.liferay.document.library.web.exportimport.data.handler.test.DLPortletDataHandlerTest > testExportImportData STARTED
     [exec] 01:08:49,189 WARN  [com.liferay.document.library.test-executor-thread][JSONStorageAdapter:79] JSON storage adapter is deprecated, using default storage adapter
```, I will report this when I find it twice. All the failures are not related to this pr, so I'll forward this pull to BChan dirrectly.

**Comment by liulukiwi** [comment]
resend:
https://github.com/brianchandotcom/liferay-portal/pull/97306

**Pull request closed without merging**
