### PR TITLE
LPS-142160 Fix asset selection with pagination

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @sandrodw3, could you have a look at the integration test failure? Thanks

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@Tim-Cao, test shouldn't be related to the changes

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
