### PR TITLE
LPS-145619 Fix test warning

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by veroglez** [comment]
ci:stop

**Comment by veroglez** [comment]
ci:close

**Comment by veroglez** [comment]
see https://github.com/liferay-echo/liferay-portal/pull/7032

**Pull request closed without merging**
