### PR TITLE
LPS-115454 Also add ID to enableViewCountIncrement, for consistency

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
@jkappler It needs to be like this:

modules/apps/layout/layout-page-template-admin-web/src/main/resources/META-INF/resources/merge_alert.jsp:       String randomNamespace = PortalUtil.generateRandomKey(request, "portlet_layout_prototypes_merge_alert") + StringPool.UNDERLINE;

**Comment by brianchandotcom** [comment]
@jkappler type:

git grep "PortalUtil.generateRandomKey"

I don't want to generate the key twice. I want to generate and then prefix it.

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
