### PR TITLE
[TS] LPS-197922 NPE - Unable to process portlet com_liferay_layout_content_page_editor_web_internal_portlet_ContentPageEditorPortlet

### PR DESCRIPTION
**Pull request by jgarcialr**
https://liferay.atlassian.net/browse/LPS-197922

If you select manually a DLFolder into an asset publisher and publish it, it crashes content page editor as DLFolder doesn't have a layoutdisplaypageprovider registered.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
