### PR TITLE
LPS-184650 Element is deselected after create a variant in A/B Test

### PR DESCRIPTION
**Pull request by Mikellorza**
This PR fix the related bugs:

1. https://issues.liferay.com/browse/LPS-180874
2. https://issues.liferay.com/browse/LPS-184650

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:relevant

**Review by lfbesada — COMMENTED** [review]
Thanks for the fix! ❤️ 
I have added a few minors SF, see: https://github.com/liferay-echo/liferay-portal/pull/12387

**Pull request closed without merging**
