### PR TITLE
LPS-134150 Make sidebar fit only wrapper and not control menu

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:stop

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
