### PR TITLE
LPS-180181 Style Book and Master Pages panels have wrong padding

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
The card of the tabs within Page Design Options don't correspond with the desired design since they're not filling the space correctly.
[LPS-180181](https://issues.liferay.com/browse/LPS-180181)

Proposed Solution
========
Changing the padding of the tab panel.

Steps to Verify
========
1. Create a content page and edit it
2. Go to Page Design Options sidebar panel
3. Look at Style Book and Master Page cards and check that the card are filling the space correctly

How it looked before:
before

How it should look:
Screenshot 2023-03-29 at 14 27 21

Screenshot 2023-03-29 at 14 27 49

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:forward

**Review by sandrodw3 — APPROVED** [review]

**Comment by liulukiwi** [comment]
ci:test:stable

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
