### PR TITLE
LPS-175473

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, would you mind checking the failed integration test? Thanks
[ClientExtensionEntryRelStagedModelDataHandlerTest](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/245316/testReport/com.liferay.client.extension.internal.exportimport.data.handler.test/ClientExtensionEntryRelStagedModelDataHandlerTest)

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:stop

**Comment by liulukiwi** [comment]
Failures are not related, pushed to BChan directly at https://github.com/brianchandotcom/liferay-portal/pull/130973

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
