### PR TITLE
[TS] LPS-134453 Change the service the same way on the getTagsCount as well.

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-134453
Thank you!

We should use the same way to get the count of the tags otherwise the results will not match the numbers.

previouse pull: #5082

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
thanks @bakayattila!

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
