### PR TITLE
LPS-124941 Adjust path to the new value set in LPS-115709

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
LGTM :)

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
Thanks @dacousalr !

**Pull request closed without merging**
