### PR TITLE
LPS-156499 Add javax.portlet.version=3.0

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:echo

**Comment by ozysouza** [comment]
Hi @jkappler, the failures are not related to this PR. You can forward if it is already done.

**Comment by david-gutierrez-mesa** [comment]
ci:forward

**Pull request closed without merging**
