### PR TITLE
LPS-193301 Maintain previously selected file

### PR DESCRIPTION
**Pull request by claraizquierdo**
[Link to story or ticket](https://liferay.atlassian.net/browse/LPS-193301)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
LGTM! As I told you un slack, I would merge this one with the other impedi, to save CI resources 😂 but feel free to forward

**Comment by ealonso** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
