### PR TITLE
LPS-121914 Migrate v2 usages in site/site-taglib

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

Configuring an Asset Publisher scope should work as expected.

**Test plan**:
- Navigate to **Site Builder** > **Pages**
- Create a new **Public Page** based on the **Blank** template
- Enter a name for your page
- Drag and drop an **Asset Publisher** widget on your page
- In the Kebab Menu on the right of the Asset Publisher, select
**Configuration**
- In the modal window, search for the **Scope** section
- Click on the **Select** button and choose **Other Site or Asset
Library**
- In the modal window, make sure you can filter the available Sites
- Select a **Site**
- Click on **Save**

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
cc @ambrinchaudhary @markocikos @jonmak08

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
