### PR TITLE
LPS-128259 - As a Navigation Menu creator I would like to create a navigation menu item for item Display Page

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @jkappler

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The failure case is unrelated to changes in PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/103563

**Comment by Tim-Cao** [comment]
ci:close

**Comment by jkappler** [comment]
ci:stop

**Pull request closed without merging**
