### PR TITLE
LPS-137395 Do not allow dragging to disabled sections

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by liulukiwi** [comment]
send in https://github.com/brianchandotcom/liferay-portal/pull/106623

**Comment by liulukiwi** [comment]
LocalFile.PortalSmokeUpgrade#ViewPortalSmokeArchive621021 is known flaky issue.

**Pull request closed without merging**
