### PR TITLE
LPS-120553 Don't include resources or content when we are merging changes for site templates, see https://help.liferay.com/hc/en-us/articles/360017904332-Using-Site-Templates

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
Hey @moltam89, could you please take a look if this is something you expect? It seems to be, but just in case ;)
Thanks!

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by moltam89** [comment]
Hi @pavel-savinov ,

This looks good to me, thanks!

**Pull request closed without merging**
