### PR TITLE
LPS-159413 Improve form alerts when publishing

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-159413 Don't consider forms themselves
- LPS-159413 Rename to getFormErrorDescription
- LPS-159413 Add FormValidationContext
- LPS-159413 Add FormValidationModal
- LPS-159413 Refactor hook and rename it to useCheckFormsValidity
- LPS-159413 Use new hook and modal component
- LPS-159413 Unused
- LPS-159413 Move functions down
- LPS-159413 Move to utils
- LPS-159413 Add unmapped fragments check
- LPS-159413 Add unmapped required fields check
- LPS-159413 Adapt tests
- LPS-159413 buildLang

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by sandrodw3** [comment]
Thanks @jkappler 🥰

**Comment by sandrodw3** [comment]
ci:reevaluate

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by sandrodw3** [comment]
https://github.com/liferay-echo/liferay-portal/pull/9265

**Pull request closed without merging**
