### PR TITLE
LPD-19215 Use parameterized preparedStatements

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team, a followup for [LPD-19215](https://liferay.atlassian.net/browse/LPD-19215)
ref https://github.com/brianchandotcom/liferay-portal/pull/147835#issuecomment-1979097739

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
ci:test:upgrade

**Comment by lfbesada** [comment]
ci:report:2547086996

**Comment by lfbesada** [comment]
ci:report:2547078630

**Comment by lfbesada** [comment]
ci:report:2547074495

**Comment by lfbesada** [comment]
@balazssk Thanks! It works great! I added only a minor SF commit. Please see: https://github.com/liferay-echo/liferay-portal/pull/15317

**Pull request closed without merging**
