### PR TITLE
LPS-148446 Return the result of LayoutLocalServiceUtil.updateStatus

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, there is a regression.
The Discard Conversion Draft is missing when convert a widget page to content page before publish 
image

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1287401_2135

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
