### PR TITLE
[TS] LPS-161717

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team, could you please review this PR if you are ok with the chosen approach?

Thanks in advance!

* * *

Motivation
=======
[LPS-161717](https://issues.liferay.com/browse/LPS-161717) Asset Publisher's Subscriptions are not preserved after editing a Content page

When a content page is published, a copy from the draft is made to overwrite the previously published version. This is made mainly by deleting the existing fragments and create some new ones. This is done for all the fragments, even some of them have remained unchanged.

However, the deletion of fragments which contain portlets, leads to the deletion of their portlet preferences, and, consequently, this finally leads to the deletion of the subscriptions.

There is additional information in [PTR-3318](https://issues.liferay.com/browse/PTR-3318)

Proposed Solution
========
The proposed solution is to defer the deletion of the subscriptions to the end of the transaction. If, at that time, there are some portlet preferences linked to the portlet, then the former subscriptions are updated to the recreated portlet preferences. If there are no portlet preferences linked to the portlet, then the former subscriptions are effectively deleted.

Steps to Verify
========

1. Create a Content Page
2. Add an Asset Publisher
3. From the Asset Publisher's configuration, enable the subscribe button
4. Publish the Page
5. Click on subscribe
6. Edit the Page
7. Publish the Page

- Actual behaviour: You are not subscribed to the Asset Publisher
- Expected behaviour: You are subscribed to the Asset Publisher

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Please see: https://github.com/liferay-lima/liferay-portal/pull/3508

**Pull request closed without merging**
