### PR TITLE
LPS-161966 If Validator.isNull(masterLayoutUuid) then we should be resetting the Master Page to the default

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
[LPS-161966](https://issues.liferay.com/browse/LPS-161966)
A Site Template can't propagate one of it's Page switching to the Blank Master Page Template

Proposed Solution
========
Set the default Master Page Template's plid ( 0 ) if no Master Page uuid belongs to the imported Layout

Steps to Verify
========
1. Create a Site Template
2. Create a Master Page
3. Create a Page based on the Master Page
4. Create a Site from the Site Template
5. Go back to the Site Template
6. Edit the Page
7. Change the Page to use the Blank Master Page
8. Publish
9. Go to the Site
10. Check the Page

**Expected behaviour:** Page uses the Blank Master Page
**Actual behaviour:** Page uses the Site Template's Master Page

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
LGTM :) Thanks!!

**Comment by ozysouza** [comment]
ci:test:relevant

**Comment by ozysouza** [comment]
The failures are unrelated to this PR.

**Comment by ozysouza** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:reevaluate:1387401_3396

**Comment by ozysouza** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/122543

**Pull request closed without merging**
