### PR TITLE
LPS 143161

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-143161 Adds message to modal stating that the user will create the page based on the current experience
- LPS-143161 Adds language key
- LPS-143161 Build lang
- LPS-143161 Change label of button

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
