### PR TITLE
LPS-114136 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LPS-114136

cc @manoelcyreno @david-gutierrez-mesa 

@p2kmgcl, I adding the poshi cases change here, could you close https://github.com/liferay-echo/liferay-portal/pull/856?

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
resend: https://github.com/liferay-echo/liferay-portal/pull/898

**Pull request closed without merging**
