### PR TITLE
LPS-177203 Default utility page is lost when publishing twice the site in staging

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-177203)

This PR fixes several issues: 

* Default utility pages and display pages are lost on certain occasions when publishing to staging
* If calling the service, an inconsistency happens if we set the default utility page template to true

For the first issue, it depends on the order of the entries. For example, if we had an utility page with a numeric name set as default and we change the default to a non numeric name and publish, we would lose the default utility page in live. Same happens with utility pages.

We change this so as to only honour the default entry when we are not in staging mode

## Change summary:

* Check in staged model data handler for utility pages and page templates if we are in staging process or not before overriding the default entry
* Change local service for utility page to use the service that changes the default entry, and not set it directly
* Adds integration tests

## Test Scenario

* Follow the steps in the ticket, the naming of the entries is important to reproduce them

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:echo

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
