### PR TITLE
[TS] LPS-123406

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-123406

Limiting the amount of "recent" groups we retrieve from the DB will give us a performance boost in situations where there are hundred of entries.  This PR also includes other minor performance improvements.

@Preston-crary, I'm sending this PR directly to the echo  team, since it mostly deals with business logic and the performance boosts are more obvious.  Please let me know if you have questions/concerns with the solution though.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
@ChrisKian does this need an upgrade or will it fix itself by the user just navigating around?

**Comment by ChrisKian** [comment]
@Preston-Crary, the issue will resolve itself as soon as the  RecentGroupManager.addRecentGroup() method is called.  In my testing, this happens upon portal login and page navigation.

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
