### PR TITLE
[TS] LPS-161051 Web content preview is not displayed

### PR DESCRIPTION
**Pull request by tototrinh**
Hi guys,
Please help review this PR and leave your comments. Thanks.
Ticket:  https://issues.liferay.com/browse/LPS-161051.
The solution was implemented based on a discussion at https://issues.liferay.com/browse/PTR-3285.
cc @TaiPhamLR

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by tototrinh** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Thanks for the fix @tototrinh 
Forwarded to Brian [here](https://github.com/liferay-echo/liferay-portal/pull/9493)

**Pull request closed without merging**
