### PR TITLE
LPS-188405 Add new fields to the validation schema

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Comment by alessandromalves** [comment]
ci:forward:force

**Comment by alessandromalves** [comment]
The failures are not related to this PR ([see comparison with acceptance routine](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1687537562779&testrayRunIdA=2358261256&testrayRunIdB=2359822676)).

**Comment by victorg1991** [comment]
resent here: https://github.com/brianchandotcom/liferay-portal/pull/136847

**Pull request closed without merging**
