### PR TITLE
LPD-38268 Configuration should only always be translated in the user language

### PR DESCRIPTION
**Pull request by victorg1991**
There is already a test that covers this. This is how this got discovered

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
@victorg1991 tests failures are related with your changes, you need to initialize themeDisplay properly, I think it is just set the Locale

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
