### PR TITLE
LPS-132601 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-132601

This is only for master.

@jkappler

Since the content page is defined as draft when create it via  LayoutLocalServiceImpl.addLayout, cannot use serviceContext to setWorkflowAction to Approved.
I would like to add a new method to publish existing content page via JSON WS instead of UI to decrease running time for some specific cases.

### CODE REVIEW

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @jkappler, could you review my solution?
I validated on my local for the following four senarios
When create a draft content page, then publish it
When create a draft content page with elements, then publish it.
When make some changes in a published content page, then publish it.
Nothing happens when publish a widget page.

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
@Tim-Cao, please see https://github.com/liferay-echo/liferay-portal/pull/4734

**Comment by Tim-Cao** [comment]
Really really thanks @jkappler

**Pull request closed without merging**
