### PR TITLE
LPS-176666 Replace alert divs with clay:alert taglib in asset-taglib

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-176666)

## Test Scenario

* Navigate to Site Builder > Pages
* Create a new Widget Page.
* Add one category filter and one tag filter.

image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1397401_5699

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
