### PR TITLE
LPS-164655 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-164655

This is only for master.

@sandrodw3

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
The regression issue @sandrodw3 is taking a look

> When add a child content page via page tree, the parent page are expanded by default.
> However, when add a child widget page via page tree, the parent page is collapsed by default. It should be expanded.

**Comment by Tim-Cao** [comment]
Hi @sandrodw3, another regression issue, the _blank target for link to URL page doesn't work on page tree.
It should open on a new tab, it opens on current tab.
Would you mind having a look at?

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
https://github.com/liferay-echo/liferay-portal/pull/10286

**Pull request closed without merging**
