### PR TITLE
[TS] LPS-151013

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

Please do note that altering the tests uncovered an additional bug: https://issues.liferay.com/browse/LPS-151311, testImportFragmentsSystemWide should fail in this case.

Can you please review?
https://issues.liferay.com/browse/LPS-151013

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @balazssk 
Thanks for the fix! 
The test failures seem to be related to the pull request.
Could you please fix it?
Thanks!
Regards

**Comment by balazssk** [comment]
Hi @lfbesada ,
Sure, looks like the restructuring of the test data broke ImportFragmentEntriesStrutsActionTest.
I'm checking it

**Comment by balazssk** [comment]
Resent in https://github.com/liferay-echo/liferay-portal/pull/7826

**Pull request closed without merging**
