### PR TITLE
LPS-150394 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
@ealonso
@lfbesada
@sandrodw3

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Hi @sandrodw3, would you mind checking if the sf issue is related to this PR?

**Comment by sandrodw3** [comment]
Hey @Tim-Cao, I ran `formatSource` and it's adding this:

image

But that LPS (https://issues.liferay.com/browse/LPS-163118) is not related to us, as far as I think 🤷🏽‍♂️

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
https://github.com/liferay-echo/liferay-portal/pull/9687

**Pull request closed without merging**
