### PR TITLE
LPS-129297 Use layout title instead of full path

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
@p2kmgcl, all looks good, only the SF is missing (order of the attributes in the map)

**Comment by jkappler** [comment]
@p2kmgcl, there are errors thrown in the logs, could you please take a look at them?

**Comment by p2kmgcl** [comment]
That should be all :3

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
Mmmm ci looks a bit broken, I am going to resend this PR

**Comment by p2kmgcl** [comment]
ci:close

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/4054

**Pull request closed without merging**
