### PR TITLE
LPP-45812 | LPS-157509: Element placement on drop zones are not retained after fragment modification

### PR DESCRIPTION
**Pull request by quanhuynhces**
Hi @liferay-echo team!
This PR is for ticket [LPS-157509](https://issues.liferay.com/browse/LPS-157509)
Thien's solution has fix the issue which the CSE describes.
Please review and leave you comment
Thanks!
cc @thienquach87

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by thienquach87** [comment]
ci:test:sf

**Pull request closed without merging**
