### PR TITLE
LPS-184283

### PR DESCRIPTION
**Pull request by carolmariaabb**
Hi team, could you please review the changes related to the Web Content module? Thanks!

**Related Issue:** [LPS-184283](https://issues.liferay.com/browse/LPS-184283)

The idea of this PR is to fetch the `DDMFormValues` by `locale` in order to improve performance a little bit.

For more details, you can see this [PTR-3900](https://issues.liferay.com/browse/PTR-3900).

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by carolmariaabb** [comment]
ci:test:sf

**Comment by carolmariaabb** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
