### PR TITLE
LPS-174757 Replace aui:icon with clay:icon in configuration.jsp

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
[Link to ticket](https://issues.liferay.com/browse/LPS-174757)

## Test Scenario 

* Navigate to Site Builder > Pages and create two Widget pages.
* Navigate to Site Builder > Navigation menus.
* Create a menu for one of those pages.
* Go to the other page and add the Menu Display Widget.
* Check the configuration and choose the menu you created before. 
* Test the delete icon:

image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Review by sandrodw3 — APPROVED** [review]

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130402

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
