### PR TITLE
LPS-191641 Fix data attribute in dynamic_include/customization_settings.jsp

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-191641)

## Test Scenario 1

* Navigate to Site Builder > Pages and create a Widget page.
* In the configuration, go to General > Advanced and activate the customization settings.
* Save and go to View to see the behaviour of the icon for help in the top of the page.

Liferay DXP

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/138356

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
