### PR TITLE
[TS] LPS-119864

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-119864

The first commit resolves the issue, but the final three clean up the solution.  However, to prevent a minor version increase as well as having to update requirements, the final three commits can be dropped.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ChrisKian** [comment]
Hi @ealonso, is there any update for this PR?  Thanks!

**Comment by ealonso** [comment]
Hey @ChrisKian,
We are waiting for the release to send pulls to master that can cause regressions. Since this one is changing the behaviour of display dates in some modules, we prefer to wait for sending this one.
Regards,
Eudaldo.

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
@ChrisKian @ealonso Release is out, rebased and forwarded here https://github.com/liferay-echo/liferay-portal/pull/2659 Thanks.

**Comment by pavel-savinov** [comment]
ci:close

**Pull request closed without merging**
