### PR TITLE
LPS-161701 Grab the groupId from the request

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:reevaluate:1297401_4329

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/122452

**Pull request closed without merging**
