### PR TITLE
LPS-134566 No needed since _doAsUser is going to be always false

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @mbowerman

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
The failure cases are unrelated to changes in PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/103750

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
