### PR TITLE
LPS-126641 | master

### PR DESCRIPTION
**Pull request by brittneyq**
https://issues.liferay.com/browse/LPS-126641

Hi @david-gutierrez-mesa , @liulukiwi , @Tim-Cao can you please review this? Thank you!

### CODE REVIEW

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/3543
View total diff https://github.com/liferay-echo/liferay-portal/pull/3543/commits/f04e1240e3dab167c8e75756e2dbf04764a05ce9

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
