### PR TITLE
[TS] LPS-143852

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

A regression was found for LPS-136518, which in my opinion is more severe than the potential benefits of LPS-136518. 
With the 
- aim of keeping master as bug free as possible for 7.4 update releases
- the complexity of the underlying bug best described as /web/guest always being added in the default site's URLs (PortalImplLayoutFriendlyURLTest#testCompanyDefaultSiteVirtualHost failing)
I'm proposing to revert LPS-136518 and reopen it for further investigation.

Can you please review?
https://issues.liferay.com/browse/LPS-143852

Thanks,
Balázs

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
