### PR TITLE
[TS] LPS-189437 Fragment with url configuration type doesn't work after imported in a different site or environment

### PR DESCRIPTION
**Pull request by ricardocousolr**
Motivation
=======
The configuration type "url" for fragments was introduced in [LPS-164081](https://liferay.atlassian.net/browse/LPS-164081) and [LPS-164123](https://liferay.atlassian.net/browse/LPS-164123) (see [documentation](https://learn.liferay.com/w/dxp/site-building/developer-guide/reference/fragments/fragment-configuration-types-reference#url-configuration)).

This configuration allows to map an URL or an existing page to a part of a fragment. 

Unfortunately, exporting/importing a fragment like this is not aware of the corresponding new layout. So the imported fragment will point to the old layout in the source environment.

Proposed Solution
========
The export/import processing could have been automatic if the `editableValues` were defined under `EditableFragmentEntryProcessor` and the `layout` information were placed under `"config"` instead of a custom configuration name (e.g., `"myURL"` in the documentation linked above). 

The actual `editableValues` are defined under `FreeMarkerFragmentEntryProcessor`. 

To fix the problem I created a new `ExportImportContentProcessor` that is similar to :
- `EditableValuesLayoutMappingExportImportContentProcessor`: in that it expects a `"layout"` jsonObject with information to map to/from a layout.
- `BaseEditableValuesConfigurationExportImportContentProcessor`: in that it gets the available configurations from the `fragmentEntryLink` from which to get `fragmentConfigurationField.getName()`. 

Feel free to refactor if you think the code should be organized differently. 

Steps to Verify
========
See detailed steps in [LPS-189437](https://liferay.atlassian.net/browse/LPS-189437).

References to existing code (if applies)
========
- https://github.com/liferay-echo/liferay-portal/blob/master/modules/apps/fragment/fragment-service/src/main/java/com/liferay/fragment/internal/exportimport/content/processor/EditableValuesLayoutMappingExportImportContentProcessor.java
- https://github.com/liferay-echo/liferay-portal/blob/master/modules/apps/fragment/fragment-service/src/main/java/com/liferay/fragment/internal/exportimport/content/processor/BaseEditableValuesConfigurationExportImportContentProcessor.java

Checklist (optional)
========

CODE:
- [x] I have considered breaking this PR into smaller PRs if the amount of changed code is too large
- [x] I have performed a self-review of my own code following Liferay's code conventions
- [x] I have checked other areas of the product for solutions to similar problems
- [ ] I have added tests that prove my fix is effective or that my feature works

COMMITS:
- [x] My commits organize changes in coherent units
- [x] There are no commits which should be combined into others
- [x] My commits are ordered in a way that ease understanding
- [x] My commit messages are well formatted and concisely describe what was changed and why it was changed

PR TITLE & DESCRIPTION:
- [x] My PR title includes an issue number and a descriptive title
- [x] My PR description explains the motivation for this change
- [x] My PR description explains the proposed solution
- [x] My PR description includes the steps to verify the change
- [ ] My PR description includes references to other places where this solution is used (if applies)
- [ ] My PR description includes visual aids to understand what has changed (if applies)
- [ ] My PR description explains alternative approaches considered and why they were discarded (if applies)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1277401_9022

**Comment by ruben-pulido** [comment]
https://github.com/liferay-echo/liferay-portal/pull/12731

**Pull request closed without merging**
