### PR TITLE
LPS-189946 Reduce XML deserialization when rendering web content

### PR DESCRIPTION
**Pull request by holatuwol**
## Motivation

https://liferay.atlassian.net/browse/LPS-189946

In analyzing a customer's 7.4.13-u74 performance test, we found that the customer was experiencing issues due to garbage collection.

This change aims to reduce the number of objects that are created when viewing web content in order to make garbage collection tuning a little easier for our customer.

## Proposed solution

Some parts of the code (`getDocument` and `getDocumentByLocale`) have a code pattern where they retrieve an XML string from `JournalConverter`, only to deserialize that XML string back into a `Document`.

If we have `JournalConverter` return a `Document` directly, we can eliminate the unnecessary conversion, thus saving a little on object creation.

## Steps to verify

N/A, this is just a code optimization

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Review by lfbesada — APPROVED** [review]
Hi @holatuwol 

Thanks a lot for this 😍 




Regards

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
