### PR TITLE
LPS-174194 Empty taglib

### PR DESCRIPTION
**Pull request by p2kmgcl**
I simply have replaced the deprecated `liferay-ui:empty-result-message` with the incredible brand new...

:star2::star2::star2::star2::star2::star2::star2::star2::star2::star2::star2::star2::star2::star2::star2::star2::star2::star2::star2:
```liferay-frontend:empty-result-message```
:star2::star2::star2::star2::star2::star2::star2::star2::star2::star2::star2::star2::star2::star2::star2::star2::star2::star2::star2:

It has incredible feature like

# _Accessible titles_

image

Don't worry any more about those horrible inaccessible page titles. A `div`? What's that? You will forget about those tags with the new awesome taglib!

# _Custom icons_

image

Do you want to show a telescope? A rocket? Do whatever you want! Now we have the _unlimited power_ of five different icons that can be used.

# _Our clients_

"Since I moved to the new taglib, my kids are much happier and no one punches me in the face anymore." — Anonymous.

"Every night before going to bed I watch my favorite TV Shows together with my taglib." — Tim Berners Lee.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/11125

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
