### PR TITLE
LPS-194957: A Blueprint collection provider can return (structured) model classes

### PR DESCRIPTION
**Pull request by peerkar**
- **Background**:
   - Spike with links to depending customer cases: https://liferay.atlassian.net/browse/LPS-188797
- **Story**: https://liferay.atlassian.net/browse/LPS-194956
- **Task**: https://liferay.atlassian.net/browse/LPS-194957

### Description

The request for this feature comes from a customer case where Blueprint collection providers are in use. It has however identified as a significant limitation that the Blueprint collection provider can only return Asset Entries, but not model classes, which would then allow mapping the model fields conveniently to collection item fragments.

This PR extends the Blueprint collection provider functionality as follows:

1. **Multiple searchable types selected in a Blueprint** -> Like currently, a single collection provider returning asset entries is registered
2. **A single searchable type is selected in a Blueprint** -> 2 collection providers are registered. The first one returns Asset Entries as before. The second one (structured) returns model class instances. First only Journal Article will be supported, but  support for more models can be added later if requested. In selecting the Collection Provider in the dialog, the description of the provider displays, which model it returns.

###  About Detecting the DDM Structure from a Search Result
Detecting the subtype / DDM structure to be used for the articles of collection is challenging. This is a critical issue in making the whole initiative worth it as it would allow mapping structure fields to fragment fields in the collection display.
The challenge is, that for example in the case of JournalArticles,  a Blueprint can return articles of multiple DDM structures. How should the collection provider know what to use? The other problem is that Blueprints are dynamic: they can even return different results for different users. What DDM structures the Blueprint returns is not possible to detect with 100% certainty.

This PR simply fetches one search result and uses the first DDM structure of it. That means that the responsibility to add proper filters in the Blueprint is entirely on the Blueprint authors shoulders. This behaviour will be properly documented.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
Hey @peerkar,

It seems to be related with Search, Could you please send it to them? Or Do you want something from our part?

**Comment by peerkar** [comment]
ci:test:sf

**Comment by peerkar** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Hi @peerkar 

The PR looks good and works as described, so from my point of view can be forwarded to Brian. Should we forward this PR or do you want to forward the one that was opened in the search repo?

As a side note (in case it's useful for anybody else testing it) in addition to the feature flag corresponding to this story (feature.flag.LPS-193551) and additional feature flag (feature.flag.LPS-129412) needs to be enabled for the new Collection Provider to be listed when selecting a collection for the Collection Display

**Comment by ealonso** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
Closing this one after talking to @peerkar

**Pull request closed without merging**
