### PR TITLE
LPD-26032 Add test for view mode

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward:force

**Pull request closed without merging**
