### PR TITLE
LPS-166547 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-166547

This is only for master.

@ealonso
@victorg1991
cc @ozysouza

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ealonso, this issue still happens. Would you mind having a look at?
The info message is wrong in Web Content Display after move selected web content then empty trash.
**Step to reproduce**
1. Add a Web Content Display to a widget page
2. Add a web content
3. Select the web content in Web Content Display
4. Move the web content to Recycle Bin
5. Navigate to the widget page then view info message in Web Content Display
6. Navigate to the Recycle Bin
7. Click the ellipsis button on control menu then Empty Trash
8. Navigate to the widget page then view info message in Web Content Display
**Actual Results:**
The message is The web content article was moved to the Recycle Bin
**Expected Results:**
The message should be The selected web content no longer exists.

**Comment by Tim-Cao** [comment]
@ealonso
Another regression issue I found here.
The Restore action is missing in portlet dropdown list.
**Steps to reproduce**
# Add a Clay Sample portlet to a widget page
# Navigate the Look and Feel page of widget page
# Define a specific look and feel for this page.
# Switch Show Maximize/Minimize Application Links to yes then save
# Navigate the widget page
# Minimize the Clay Sample via topper bar
# Open the dropdown list of Clay Sample

**Expected Results:**
The Restore action should be shown instead of Minimize

**Actual Results**
The Restore action is missing.

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
Hey @Tim-Cao,

For the fist one it is working for me:

Widget_Page_-_Liferay_DXP

For the second one, we need to work on it.

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/10142

**Pull request closed without merging**
