### PR TITLE
LPS-142506 Keep the first single slash in friendly URLs

### PR DESCRIPTION
**Pull request by adolfopa**
This was caused by https://issues.liferay.com/browse/LPS-132908. @dacousalr @ealonso See
comments in the original PR; in general, it is not possible to keep prepending slashes and avoiding too extra slashes in URLs without changing the way URLs are generated. This cannot be fixed in the friendly URL service, URL generation will need to be changed.

I'll let you decide whether to revert the whole change, or merge this and cross fingers.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Merged. Thx.

**Comment by ealonso** [comment]
Already merged by Brian

**Pull request closed without merging**
