### PR TITLE
LPS-189301 Improve error messages for Open AI integration

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-189301

This PR changes the OpenAI error handling, so here the OpenAI Client Mock is adapted too and the documentation has been updated to reflect it: https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2413429012/How+to+use+the+OpenAI+mock+client

Summary of changes to the Mock

1. The "`OPENAI_API_INVALID_API_KEY`" key is removed since this error is no longer handled differently from the rest.
2. The "`OPENAI_API_{0}_RESPONSE_CODE`" key is modified, now it is "`OPENAI_API_{0}_ERROR_MESSAGE`" to allow {0} to be the error message that the API responds to. With the new implementation, the treatment is the same for any error code and the message that is received from the API should be displayed

cc: @Tim-Cao

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:forward palante

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, what's this `ci:forward palante` ?

**Comment by p2kmgcl** [comment]
> Hi @p2kmgcl, what's this ci:forward palante ?

:laughing: just a joke @Tim-Cao, "palante" is "para adelante" in Spanish, which is more or less "forward". I discovered that I can write anything after "ci:forward", and the CI just ignores it :smile:

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl and @lfbesada, I think js unit test is required to update.
[js-unit-jdk8/0/0](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/598766//consoleText)
Build completed with 1 failures.
Execution failed for task ':apps:ai-creator:ai-creator-openai-web:packageRunTest'
[ai-creator.ai-creator-openai-web.test.ai_creator_modal](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/598766/testReport/ai-creator.ai-creator-openai-web.test/ai_creator_modal)

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:test:stable

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
