### PR TITLE
LPS-181452 Copy page menu item isn't disabled for draft content page

### PR DESCRIPTION
**Pull request by Mikellorza**
Impedibug: https://issues.liferay.com/browse/LPS-181452

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/11795

**Pull request closed without merging**
