### PR TITLE
[TS] LPS-158040 - collections with web content are not being correctly filtered by field

### PR DESCRIPTION
**Pull request by wanderlast**
https://issues.liferay.com/browse/LPS-158040

Hi!

This is a PR to address an issue where collections were not being properly filtered when the content was web content. This is because the "ddmStructureFieldName" and "ddmStructureFieldValue" attributes are never properly set for non-DL content and therefore a boolean filter is never created. This PR remedies this by adding them to the assetentryquery.

Please let me know if you have any questions or concerns. Thanks!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by lfbesada — CHANGES_REQUESTED** [review]
Hi @wanderlast 
Thanks for the fix! 🤗 
I have identified the cause of the bug and have preferred to partially revert the commit that caused it in order to more easily trace its origin.
I have also implemented a slightly simpler solution.
Thank you very much!
Cheers

**Comment by lfbesada** [comment]
@wanderlast please see: https://github.com/liferay-echo/liferay-portal/pull/9202

**Pull request closed without merging**
