### PR TITLE
[TS] LPS-134704 - check against site template as well when setting workflow for web content folders

### PR DESCRIPTION
**Pull request by wanderlast**
Hi Echo team!

I'm sending this to you since it relates specifically to Journal folders, but if you feel like it's more appropriate elsewhere please just let me know. This adds a check to the layout set prototype group's setting in the case we can't find a setting for our own scope group since otherwise the setting is not carried over at all from the site template.

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Thanks for the fix @wanderlast

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
