### PR TITLE
LPS-133709 As a Navigation Menu creator I would like to access my Menus (and menu pages) from the page tree 

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-133709
https://issues.liferay.com/browse/LPS-134593
https://issues.liferay.com/browse/LPS-134751

cc: @victorg1991

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
resent here https://github.com/liferay-echo/liferay-portal/pull/5026

**Pull request closed without merging**
