### PR TITLE
LPS-163005 Do not send notifications for comments if the layout is being copied.

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Echo Team,

Can you help review this PR?

As mentioned in [PTR-3327](https://issues.liferay.com/browse/PTR-3327), this PR is solution 1.

**Notes from @noornajj:**

> https://issues.liferay.com/browse/LPS-163005
> 
> The issue here is that notifications for content page comments were be sent every time the page was published or a new experience was created. This was due to the layout being copied and therefore the comments being copied as well.
> 
> To fix the issue, I added a check in the notifySubscribers method to check whether the layout is being copied using the CopyLayoutThreadLocal variable.

I'll also leave a few observations I had, in case it helps.

Please let us know if you have any questions.
Thanks!

----

**Additional Observations**
The `_copyLayoutData` method may eventually call the method: `_copyPortletPreferences`. Not sure if this would eventually land here: [PortletPreferencesLocalServiceImpl.java#L1035-L1054](https://github.com/liferay/liferay-portal/blob/7.4.3.41-ga41/portal-impl/src/com/liferay/portal/service/impl/PortletPreferencesLocalServiceImpl.java#L1035-L1054), which has logic involving: `CopyLayoutThreadLocal`
```
if (CopyLayoutThreadLocal.isCopyLayout()) {
```

Not entirely related, but I noticed in the same `notifySubscribers` method, a threadlocal is used: `MailingListThreadLocal`, in [MBMessageLocalServiceImpl.java#L2384](https://github.com/liferay/liferay-portal/blob/7.4.3.41-ga41/modules/apps/message-boards/message-boards-service/src/main/java/com/liferay/message/boards/service/impl/MBMessageLocalServiceImpl.java#L2384)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @ericyanLr @noornajj,

As I can see in the comment they recommend you send this pr to @liferay-lima or let them know in the slack channel, please see https://issues.liferay.com/browse/PTR-3327?focusedCommentId=2758255&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2758255

Regarding the changes in [SegmentsExperienceUtil.java](https://github.com/liferay-echo/liferay-portal/pull/9632/files#diff-3ae92922c211e09c7a0fb8687ad99df4ec2dd15fc0dca51341576e9611ddf955), it LGTM

Could you please send this one to them?

Regards,
Eudaldo

**Review by adolfopa — APPROVED** [review]

**Comment by adolfopa** [comment]
ci:forward

**Pull request closed without merging**
