### PR TITLE
LPS-158711 Add rich text description to the Asset Category

### PR DESCRIPTION
**Pull request by BarbaraCabrera**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Great job 👏 
LGTM 🎉

**Comment by lfbesada** [comment]
Hi @Tim-Cao 
This PR is changing the category description field to use a WYSIWYG editor. I think this is the cause of [this test failing](https://testray.liferay.com/reports/production/logs/2022-08/test-1-28/test-portal-acceptance-pullrequest(master)/4059/functional-tomcat90-mysql57-jdk8/1/5/LocalFile.DisplayPageTemplatesForCategory_SelectSpecificDisplayPageTemplateInCategoryEditor/index.html.gz), I guess the selector should be adapted.
Could you please review it?
Thanks a lot! ❤️ 
Regards
cc @BarbaraCabrera

**Comment by Tim-Cao** [comment]
No problem @lfbesada

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/9405

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
