### PR TITLE
LPS-178945 Migrate SegmentsEntryBrowsePortletProvider to Item Selector

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-178945

cc: @ealonso @Stephy6 @Tim-Cao

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @lfbesada, the Selection is unavailable when select another segment entry in segment editor.
image

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1377401_11604

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
