### PR TITLE
LPS-166547 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-166547

This is only for master.

@ealonso
There are two regression issues found. Would you mind having a look at? Thanks
First, the ellipsis icon of inherited widget from master page is visible to users on FireFox latest and Chrome 100.
**Steps to reproduce**
1. Open a FireFox browser
2. Add an Asset Publisher to a master page
3. Add a content page based on master
4. Hover on the body of Asset Publisher

**Acutal Results**
1. The ellipsis button is visible
2. Click on the ellipsis button
3. The dropdown menu is shown but nothings happens when click any menu item.

**Expected Results**
The ellipsis icon is invisible to users when hover on Asset Publisher since it is inherited from master.

Second, the info message is wrong in Web Content Display after move selected web content then empty trash.
**Step to reproduce**
1. Add a Web Content Display to a widget page
2. Add a web content
3. Select the web content in Web Content Display
4. Move the web content to Recycle Bin
5. Navigate to the widget page then view info message in Web Content Display
6. Navigate to the Recycle Bin
7. Click the ellipsis button on control menu then Empty Trash
8. Navigate to the widget page then view info message in Web Content Display

***Actual Results:***
The message is The web content article was moved to the Recycle Bin

***Expected Results:***
The message should be The selected web content no longer exists.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
see https://github.com/liferay-echo/liferay-portal/pull/10118

**Pull request closed without merging**
