### PR TITLE
LPS-131852 Use "description" as UI name instead of "summary"

### PR DESCRIPTION
**Pull request by adolfopa**
Change the visible name to match the actual name, used both in the model and in the InfoItem field.

If you don't think this change is worth, please close the associated ticket as won't fix.

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/4666

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
