### PR TITLE
LPS-132744 Fix preview modal styles

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
Hey @pat270 I've updated some css in order to fix some styles issues

Apart from that, there is another modal in the page editor the AllowedFragment selector, this can be displayed creating a master page:

1- Go to Page templates -> master pages
2- Create a new master page
3- Click in the configure allowed fragment button

I've tried to fix it myself but I think we need to add cadmin stuff also to the tree view component (from frontend-js-components-web)

Check here that the collapse button are messed up (I'm adding/removing the cadmin class in the video):


https://user-images.githubusercontent.com/11654230/128166577-74822046-26a7-4e3c-a5f2-9acce83bb0e9.mov

Would you mind taking a look ? :) 

Thanks!!

**Comment by pat270** [comment]
Thanks @victorg1991, I'll send another pr for AllowedFragment selector.

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
