### PR TITLE
LPS-199579 Guest role vs. SignedIn=False role differences in Experiences visibility

### PR DESCRIPTION
**Pull request by Mikellorza**
See https://liferay.slack.com/archives/G03LYN0J8/p1698234880477949 to know more about the solution.

bug:  https://liferay.atlassian.net/browse/LPS-199579

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142799

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
