### PR TITLE
LPS-132209 Revert editable id change, this can lead to upgrade problems

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@Tim-Cao, would you please help us with this? Thanks!

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/4643

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
