### PR TITLE
LPS-144550 Articles on the default display page do not appear in the sitemap

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-144550

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
