### PR TITLE
LPS-167895 Make empty string a valid value

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-167895

For fragments, the default value would be displayed if the default locale is an empty string. To resolve this issue, I added a check to make sure the value is acceptable when it is an empty string. 

Mateo said this should be considered a breaking change.
https://issues.liferay.com/browse/PTR-3466?focusedCommentId=2797567&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2797567

Please let me know if there are any questions or comments about this.
Thank you.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @fortunatomaldonado,

The tests failures seems to be related with your pr, I've asked QA to take a look and let you know what is broken.

**Comment by Tim-Cao** [comment]
Hi @fortunatomaldonado, two regression issue caught by failure cases. The default value of fragment with editable field are changed, another is the default value of fragment with editable field are invisible at view mode.  Would you mind having a look at?
**Step to reproduce:**

1. Add a Heading fragment to a content page

**Expected Results**
The default value of Heading should be **Heading Example**

**Actual Results**
The default value of Heading is **Example Text**

**Step to reproduce:**

1. Add a Heading fragment to a content page
2. Publish the content page
3. Navigate to the view mode

**Expected Results**
The default value of Heading should be shown on page.

**Actual Results**
The default value of Heading is missing on page.

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Hello @ealonso,

I updated the fix and reran the tests. Let me know if this is fine or I should open a new PR.

I found that the current checks for locale value was not able to differentiate between the value being a blank string and it being Null. This lead to the case of other locales being set to the default value when the site locale being a blank string.

In order to resolve this, I checked to see if the locale being used had any value in the `jsonObject`. If not, then would check for the site locale and would return the default value if the site locale has not been registered or return the value.

Please let me know if there are any questions or comments about this.
Thank you!

**Comment by ruben-pulido** [comment]
Hi @fortunatomaldonado 

Thanks for the PR.

I have added a [comment](https://issues.liferay.com/browse/LPS-167895?focusedCommentId=2804987&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2804987) to the ticket in JIRA because in my opinion the reported behaviour works as expected in view mode, whereas the unexpected behaviour is actually happening in edit mode.

The fix will need to take that into account.

**Comment by ruben-pulido** [comment]
Hi again @fortunatomaldonado 

As I stated in the ticket I have to take back my previous statement. The expected behaviour is as you described it, as it was confirmed in the [PTR](https://issues.liferay.com/browse/PTR-3466)

I have simplified the fix in this new [PR](https://github.com/liferay-echo/liferay-portal/pull/10408)

**Pull request closed without merging**
