### PR TITLE
LPS-195017 Remove soy from dynamic-data-mapping modules

### PR DESCRIPTION
**Pull request by p2kmgcl**
Here I have removed unused soy files from dynamic-data-mapping-form-field type.

The only remaining usage lives in project-templates-form-field, and I have updated that to enforce using React for new projects. That way those templates cannot depend on Soy unless they are created for a previous portal release.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
cc @ealonso

**Comment by p2kmgcl** [comment]
ci:test:bundle

**Comment by p2kmgcl** [comment]
I am running ci:test:bundle because I am not sure if I broke something with these changes :sweat_smile:. It looks like everything was unused, but I want to be sure.

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
Waiting for https://github.com/liferay-echo/liferay-portal/pull/13888

**Comment by p2kmgcl** [comment]
Just rebased onto master, not sure how to test this :sweat_smile:

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/13914

**Pull request closed without merging**
