### PR TITLE
LPS-142147 | master

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-142147

### Steps to reproduce

1. Go to Global site > Categorization > Tags
2. Add a tag named "global"
3. Go to Content & Data > Web Content
4. Add a web content with "global" tag
5. Go to default site and edit the home page
6. Add a Tags Navigation widget
7. Open "Tags Navigation - Configuration > Scope" and change scope to Global
8. Add a Asset Publisher widget
9. Open "Asset Publisher - Configuration > Setup: Asset Selection: SCOPE" and change scope to Global
10. Publish the changes
11. Click "global" tag displayed on the Tags Navigation widget

**Actual result**: "Content with tag XXX" is not displayed above the Asset Publisher widget.
**Expected result**: "Content with tag XXX" is displayed above the Asset Publisher widget.

### Notes about the solution

Given that the issue is that the tag has no idea which sites were configured, it made the most sense to pass that along as a tag attribute from code that did know (in this case, asset publisher). For backwards compatibility, that attribute is optional.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Thanks for the changes @sontruongces and @holatuwol
Forwarding them to Brian

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
