### PR TITLE
LPS-117064, LPS-117066, LPS-117069, LPS-118298 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-117064
https://issues.liferay.com/browse/LPS-117066
https://issues.liferay.com/browse/LPS-117069
https://issues.liferay.com/browse/LPS-118298

This is only for master.

@sandrodw3
@pavel-savinov

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by Tim-Cao** [comment]
For poshi side
1. Make locators robust
2. Modify PageEditor.editLayoutContainer

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
See https://github.com/sandrodw3/liferay-portal/pull/371

**Pull request closed without merging**
