### PR TITLE
LPS-201622 When defining the search URL, take into account the DDMStructureId so that only results for it are shown

### PR DESCRIPTION
**Pull request by jkappler**
https://liferay.atlassian.net/browse/LPS-201622

How to test:

1. Enable: `LPS-194763` and `LPS-197692` feature flags.
2. Go to Web Content Admin and create 2 structures
3. Create a web content for each structure with a common keyword, for example Notebook 1 and NoteBook 2
4. Go inside of the configuration and select both structures as highlighted and save
5. Back in the main view, click on the vertical nav menu on any structure
6. Search for Notebook

Only the web content for that structure will be shown

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by lfbesada — APPROVED** [review]
:heart:

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1287401_8267

**Comment by lfbesada** [comment]
ci:test:stable

**Comment by Tim-Cao** [comment]
ci:forward:force

**Pull request closed without merging**
