### PR TITLE
LPS-171399 Unable to preview web content after enable repeatable of nested fields when upgrading from 7.3.10.sp1

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-171399

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @lfbesada, would you mind having a look at failed integration tests?

[com.liferay.journal.transformer.test.JournalTransformerTest](https://testray.liferay.com/home/-/testray/case_results/2148903891)
[com.liferay.journal.internal.transformer.JournalTransformerTest](https://testray.liferay.com/home/-/testray/case_results/2148903906)

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
