### PR TITLE
LPS-189578 Delete unused usageCount property

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-189578

cc: @sandrodw3 @ealonso

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by alessandromalves** [comment]
ci:forward:force

**Comment by alessandromalves** [comment]
The failures are not related to this PR [(see comparison with acceptance routine)](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1688738043722&testrayRunIdA=2372452216&testrayRunIdB=2374032341). See https://github.com/brianchandotcom/liferay-portal/pull/137555

**Pull request closed without merging**
