### PR TITLE
LPS-205266

### PR DESCRIPTION
**Pull request by jonathanmccann**
https://liferay.atlassian.net/browse/LPS-205266

After https://github.com/liferay/liferay-portal/commit/1961eeec57900e81fd58f6644b926ad2d48b4665 filtering based on Category or Tag became broken since `JournalDisplayContext._getArticlesSearchContainer` would no longer reach the point where the filters are added to the search query.

These changes add a new method to check whether or not a Category or Tag has been selected. If so, then it will filter the results based on these choices. I wasn't sure the best name for the method (`hasAssetFilter`) so please let me know if there is a better alternative. `JournalDisplayContext.isFilterApplied` exists but has more checks than needed for this use case thus the new method being created.

If there are any questions or concerns please let me know.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Mikellorza** [comment]
LGTM!!,

Thanks @jonathanmccann

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward:force

**Pull request closed without merging**
