### PR TITLE
LPS-140434

### PR DESCRIPTION
**Pull request by jkappler**
Web_Content_-_Staging_site_-_Liferay

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
@Tim-Cao

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/11574

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
