### PR TITLE
LPS-110011 Pass the portletId to Liferay.component

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
🕯

**Comment by victorg1991** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
