### PR TITLE
LPS-137917 Removes ignore

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:reevaluate:1267401_51

**Comment by Tim-Cao** [comment]
The failure cases are unrelated to this PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/106534

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
