### PR TITLE
[TECHNICAL-SUPPORT] LPS-116118 Unify lazy upgrade for 'layout-classed-model-usages-*' tags

### PR DESCRIPTION
**Pull request by vendeltoreki**
Dear @liferay-echo team,

`layout-classed-model-usages-admin` tag executes a "lazy upgrade" ([LPS-88698](https://issues.liferay.com/browse/LPS-88698)) in its doStartTag() method, while `layout-classed-model-usages-view` doesn't. I separated out a method into a utility class, so both can execute it and show the correct data.
This might not be the best solution, I just wanted to avoid code duplication.

Please review my changes.

Thanks,
Vendel

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
