### PR TITLE
[TECHNICAL SUPPORT] LPS-165205 Fragment CSS is included multiple times for the same Fragments from U32

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hello,

**Motivation**
[LPS-165205](https://issues.liferay.com/browse/LPS-165205),
The CSS is duplicated when we render multiple instances of the same Fragment. This issue was introduced in [LPS-157131](https://issues.liferay.com/browse/LPS-157131)

**Proposed Solution**
In order to not duplicate CSS when we render the same fragment multiple times, we have to create the key for the css from The FragmentEntryLinkId, which is the same across multiple instances of the same fragment.

**Steps to Verify**
Go to Design → Fragments and Create a new Fragment Set
Create a new Fragment with some CSS
Place it to the home page multiple times
Inspect it in DevTools
_**Actual behavior:**_
The styling is present with every fragment.

_**Expected behavior:**_
Prior to update 32 the styling tag was only present with the first fragment.

Please review my changes,

Thanks

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/124322

**Comment by ozysouza** [comment]
ci:close

**Pull request closed without merging**
