### PR TITLE
LPS-172571 Add permission restriction to Editable fields

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-172571

Dear Reviewer ❤️ 
In this PR are included the first two commits using LPS-173429. Those commits are from [this pull request ](https://github.com/liferay-echo/liferay-portal/pull/10908) but also are needed to pass successful integration tests in this PR.
Thanks!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1387401_5933

**Pull request closed without merging**
