### PR TITLE
LPS-112334 Update test

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@ealonso

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
Already merged on https://github.com/brianchandotcom/liferay-portal/pull/88677

**Pull request closed without merging**
