### PR TITLE
LPS-179206 The screen size button loses focus when pressed multiple times

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
[Link to ticket](https://issues.liferay.com/browse/LPS-179206)

## Test Scenario
- Go to Simulation panel > open it
- Navigate by keyboard
- Press the Mobile screen size button
- Press again the Mobile button (landscape mobile)

https://user-images.githubusercontent.com/93203423/227903104-5a54831d-4901-4c26-8162-969f26f382df.mov

### CODE REVIEW

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
