### PR TITLE
[TS] LPS-141893

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-141893

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Hi @ChrisKian, I'm still getting DuplicateFragmentEntryKeyException when publishing. Is there something else I should do? I have deployed both modules, and followed the steps in the tickets.

One SF that I did was to use the service instead of the util in the StagedModelRepository.

Will leave on hold for now

**Comment by ChrisKian** [comment]
Hey @jkappler,
Thanks for looking into this PR, hopefully we can figure out what's going on.

To confirm, when publishing the staging page to live (step 16 on [LPS-141893](https://issues.liferay.com/browse/LPS-141893)), which publication type are you using; simple or advanced?  Both types will work, but when using advanced publication, we must check the "Replicate Individual Deletions" option AND select any page(s) which are using the outdated fragment.

You can also enable WARN logging on `com.liferay.exportimport.internal.lar.DeletionSystemEventImporter` to see if there are any issues processing the FragmentEntryLink deletion(s) from the layout(s).

**Comment by ChrisKian** [comment]
Also, I notice a bug which appears with deletion events of assets from staging to live, but isn't fragment-specific.  I'll describe it so you don't see it as a regression coming from my fix:
1. Enable local-live staging
2. Create a fragment
3. Create a web content
4. Publish them both to Live
5. Delete both in staging
6. Publish both deletions to live (next to each asset type, `1 Deletions` appears in the Simple publication window).
7. Attempt to perform another simple publication
Expected: Nothing will appear under the "Changes Since Last Publish Process" section
Actual: Both a Fragment deletion and Web Content deletion will appear

**Comment by jkappler** [comment]
hi @ChrisKian, seems "Replicate Individual Deletions" is what I was missing (I was only testing advanced publication). I'll test again tomorrow and then send to the staging team so that they can check the export-import change.

 Thanks again!

**Comment by jkappler** [comment]
Please check https://github.com/liferay-staging/liferay-portal/pull/4 (conflict fixed)

**Comment by jkappler** [comment]
@ChrisKian, just extracted to a new method, thanks again

**Pull request closed without merging**
