### PR TITLE
LPS-136279 Adjust label position

### PR DESCRIPTION
**Pull request by p2kmgcl**
Needs: `feature.flag.LPS-143206=true`
Checkout story definition for more info https://issues.liferay.com/browse/LPS-136279 :rainbow:

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/8930

**Pull request closed without merging**
