### PR TITLE
LPS-196540 Change "AI-creator" button behavior

### PR DESCRIPTION
**Pull request by Stephy6**
- LPS-196540 Use data-title attribute as hover tooltip and old tooltip as onClick tooltip
- LPS-186540 Change png image to higher resolution
- LPS-196540 buildLang

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by p2kmgcl — APPROVED** [review]
ci:forward your dreams

**Comment by p2kmgcl** [comment]
ci:forward drawrof:ic

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
