### PR TITLE
[TS] LPS-150132

### PR DESCRIPTION
**Pull request by dacousalr**
@joseluisbango originally wrote:

> The result of mixing public and private pages in navigation menus is not consistent when staging is enabled. See [LPS-150132](https://issues.liferay.com/browse/LPS-150132) for details.
> 
> On the one hand, we have to add an extra condition to [this check](https://github.com/liferay/liferay-portal-ee/blob/7.4.x/modules/apps/site-navigation/site-navigation-menu-item-layout/src/main/java/com/liferay/site/navigation/menu/item/layout/internal/type/LayoutSiteNavigationMenuItemType.java#L102-L103) implemented in [LPS-125086](https://issues.liferay.com/browse/LPS-125086), otherwise the behaviour seems random to the user because a private and a public page can share the same "layoutId". However, a private page can never be checked in a publication of public pages (and vice versa).
> 
> On the other hand, if Page Versioning is enabled, some undesired records are created in the database when performing a publication of public pages and there are navigation menu items for private pages.
> When the execution calls [_getLayout() from LayoutSiteNavigationMenuItemType#exportData()](https://github.com/liferay/liferay-portal-ee/blob/7.4.x/modules/apps/site-navigation/site-navigation-menu-item-layout/src/main/java/com/liferay/site/navigation/menu/item/layout/internal/type/LayoutSiteNavigationMenuItemType.java#L99), you can see how a new row is added to "LayoutBranch" table for the private page in the staging site database, but pointing to the public "LayoutSetBranch". This is because it tries to get a mater branch [here](https://github.com/liferay/liferay-portal-ee/blob/7.4.x/portal-kernel/src/com/liferay/portal/kernel/model/LayoutStagingHandler.java#L224-L226) that doesn't exist, and it ends up creating a new one.
> Then, the execution of LayoutStagingHandler#_getLayoutRevision() continues, and a new public "LayoutRevision" for that private page [is added too](https://github.com/liferay/liferay-portal-ee/blob/7.4.x/portal-kernel/src/com/liferay/portal/kernel/model/LayoutStagingHandler.java#L234-L244) with INACTIVE status, so LayoutSiteNavigationMenuItemType#exportData() always returns false [here](https://github.com/liferay/liferay-portal-ee/blob/7.4.13-u16/modules/apps/site-navigation/site-navigation-menu-item-layout/src/main/java/com/liferay/site/navigation/menu/item/layout/internal/type/LayoutSiteNavigationMenuItemType.java#L113).
> 
> Please, let me know if you have any questions.
> 
> Thanks!

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Hi @joseluisbango @dacousalr 
Thanks for the fix! It works great! ❤️ 
Regards

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
