### PR TITLE
LPS-130145 Create infoItemPreviewSelectorURL

### PR DESCRIPTION
**Pull request by p2kmgcl**
Needs to activate "displayPageItemPreviewEnabled" feature flag, and only applies to Display Pages (see JIRA ticket).

Backend has been reviewed with @ealonso

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/4198

**Pull request closed without merging**
