### PR TITLE
LPS-117480 Ensure pagination includes the group groupId whose items are going to be paginated.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
looks good, thanks @marianoalvarosaiz!

@ealonso

**Pull request closed without merging**
