### PR TITLE
LPS-148919 Inline

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
cc: @lfbesada

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ealonso, the * symbol of draft content page is missing on control menu. Would you mind double checking?
image

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
