### PR TITLE
LPs-206029

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
----
Fix the following issue and don't break clients templates.

[Link to the issue](https://liferay.atlassian.net/browse/LPS-206029) 

Proposed Solution
----
Creates new class that represents SelectInfoFieldType for TemplateNode, in that way we can add two new methods, getKey and getLabel(Locale). For select types modify the template to generate the following code:

```
<#if (ObjectField_fruit.getKey())??>
	${ObjectField_fruit.getKey()}
</#if>
```

Now we have available in FreeMarker template the following methods to access label and key of select types:

```
<ul>
	<li>
		Data: ${ObjectField_fruit.getData()}
	</li>	
	<li>
		Key: ${ObjectField_fruit.getKey()}
	</li>
	<li>
		Label: ${ObjectField_fruit.getLabel(locale)}
	</li>
</ul>
```

Also add an error message for clients using getData method, in that way they can be aware of the new methods.

Steps to verify
----

1. Go to Control Panel → Picklists → Add a new picklist
2. Add some items
3. Go to Control Panel → Objects → Add a new custom object
4. Go to Fields tab → Add a Picklist field
5. Publish the Custom Object
6. Go to Control Panel → Notifications → Template → Add a new Email notification template
7. Change the editor type to FreeMarker template
8. Use the Picklist data in the FreeMarker template
9. Go to Control Panel → Objects →Edit the created custom object
10. Go to Actions tab  → Add a new action 
11. Add a new entry

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Thank you very much for this @ealonso 

I am afraid that this approach changes the behavior of the web content and document structure's fields in the Info Templates. 

I think the only way to get what we want without breaking other things is to somehow differentiate the picklist from the other selects.

Therefore I propose one of these two approaches:
- POC1: Add new attributes to the select info fields https://github.com/liferay-echo/liferay-portal/pull/15020
- POC2: Add new info field types to handle picklists https://github.com/liferay-echo/liferay-portal/pull/15024

What do you think?

Thanks!

**Comment by ealonso** [comment]
see https://github.com/liferay-echo/liferay-portal/pull/15033

**Pull request closed without merging**
