### PR TITLE
LPD-37740

### PR DESCRIPTION
**Pull request by JavierMoral**
This pull fixes https://liferay.atlassian.net/browse/LPD-37740 that has been reported in a fire priority ticket

In LayoutStagedModelDataHandler, every time we import another layout (for example the draft or parent layouts) we save the originalPlid like in https://github.com/liferay/liferay-portal/blob/b6575d807576538c658a56f826911896aed0fc87/modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/exportimport/data/handler/LayoutStagedModelDataHandler.java#L698-L706

I used this same pattern when importing the LayoutPageTemplateStructure as it could also result in the import of other layouts when the page has fragments with fields mapped to those layouts

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by JavierMoral** [comment]
ci:test:sf

**Comment by JavierMoral** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
