### PR TITLE
LPS-195640

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @claraizquierdo, the json object is shown on page when view collection items.
**Steps to reproduce**

1. Add three web contents
2. Add a manual collection then select them
3. Add a collection page based on manual collection then publish
4. Navigate to the Pages admin
5. View Collection Items of collection page

image

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
