### PR TITLE
LPS-167430 Set min-height for editable content

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-167430

The issue is that editable content do not have a `min-height` and so it can be difficult to get the menu kebab to display.
Here is an example of the difficultly.
https://user-images.githubusercontent.com/31672551/199601594-b1fd8ec6-e55e-4e72-afd8-cb2ff9cf707f.mp4

To fix this, I added `min-height: 40px` so that it can be more reasonable to get the menu kebab. 
Please let me know if there are any questions or comments about this.

Thank you!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @fortunatomaldonado I cannot reproduce it in content pages, could you review the reproduction steps?

This is what I got:
Screenshot 2022-11-03 at 10 33 01

**Comment by fortunatomaldonado** [comment]
Hello @victorg1991, I apologize I did not notice that there were two Search Results. We need to use the Commerce Search Result.
Please let me know if there are any other questions or comments about this.

Thank you!

**Comment by victorg1991** [comment]
Hey @fortunatomaldonado 

Thanks! I was able to reproduce it, we have a min-height already in place for the overlay in the topper. would you mind set this min-height to that value instead?

https://github.com/brianchandotcom/liferay-portal/blob/d35f84a6c73896735c207c6d12f1358f5b7aae1e/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/app/components/fragment-content/_FragmentContent.scss#L28

This way both overlay and topper have the same height :)

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Hello @victorg1991, I was able to make the change. Please let me know if there is anything else needed.
Thank you!

**Comment by victorg1991** [comment]
Thanks @fortunatomaldonado !

**Comment by victorg1991** [comment]
ci:forward

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/125781

**Pull request closed without merging**
