### PR TITLE
LPS-121909 Migrate v2 usages in site/site-admin-web

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

Creating, filtering and deleting sites should work as expected

**Test plan**:
- From the Global Menu, select the **Control Panel** tab
- Navigate to **Sites**
- Assert that you can create a **New Site** from the management toolbar
- Assert that you can delete a **Site** from the management toolbar
- Assert that you can create a nested Site in an existing Site
- Assert that you can delete a nested Site in an existing Site

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
cc @ambrinchaudhary @markocikos @jonmak08

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
