### PR TITLE
LPS-193455 Missing tab for Blogs and more label tab when is necessary 

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
The motivation behind this PR is to solve two impedibugs in the Content Dashboard sidebar about the Blogs tabs view and the tabs styles
https://liferay.atlassian.net/browse/LPS-193618
https://liferay.atlassian.net/browse/LPS-193544

Proposed Solution
========
What I did to solve this problem is to add a tab for when Blogs contains categorization and no tabs in the other case. For the styles improvement part I used a clay-dropdown for the cases there are all three tabs (Details, Versions and Categorization) so the spacing in the tabs ir correct.

Steps to Verify
========
1. Create a various Blogs and Web content with and without Categorization
2. Go the the Content Dashboard and open the sidebar panel for the elements created.
3. Check that the Details, Versions and Categorization are displayed correctly. For the cases we have all of the three, a More tab should be displayed which contains the Verions tab.

Screenshot 2023-08-17 at 15 24 04

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
Hey @sandrodw3 @Stephy6 there are some failures related with the changes on frontend tests. please fix it

**Comment by Stephy6** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
