### PR TITLE
LPS-161248 Apply workflow for hidden pages

### PR DESCRIPTION
**Pull request by ces-huynguyen**
LPS-161248 Apply workflow for hidden pages

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ces-huynguyen** [comment]
ci:test

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Vy-CES** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:reevaluate:1337401_2166

**Comment by ozysouza** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/122418

**Pull request closed without merging**
