### PR TITLE
LPS-127071 Reference CSS color classes for text color as well

### PR DESCRIPTION
**Pull request by achaparro**
Hi @liferay-echo,

Please @kevhlee  comments below to understand why we need to do this.

Regarding the changes, I would like to centralize the definition of the following variables:
https://github.com/liferay-echo/liferay-portal/pull/3745/commits/62bcf545c46786c19219c164c5f64c0f3606b116#diff-3b4aa1d70b459c024e6d2cc43276e21fde7b73d0c2154c7269953c093a0d8c98R179-R215

Which are used in several upgrade processes. However, I am not sure if we should use a util or helper class or any other kind of solution. Since you are the owner of the component, can you make a decision regarding this?

Thanks.

Notes from @kevhlee:

> Tickets
> https://issues.liferay.com/browse/LPS-127071
> 
> Notes
> The issue occurs because the upgrade does not update the backgroundColorCssClass values to the ones found in later versions. As a result, the color picker field in the side menu editor does not recognize the background color and RGB values are used. This issue occurs for text color (cssClass values) as well.
> 
> To resolve this issue, we need to use the CSS color classes found in frontend-token-definition.json in frontend-theme/frontend-theme-classic module:
> 
> https://github.com/liferay/liferay-portal/blob/7.3.5-ga6/modules/apps/frontend-theme/frontend-theme-classic/src/WEB-INF/frontend-token-definition.json
> The portal refers to the CSS color classes found in frontend-token-definition.json when rendering layouts, as seen in the following:
> 
> https://github.com/liferay/liferay-portal/blob/7.3.5-ga6/modules/apps/layout/layout-taglib/src/main/java/com/liferay/layout/taglib/internal/display/context/RenderLayoutStructureDisplayContext.java#L694-L712
> I used UpgradeFragmentEntryLinkEditableValues.java to determine which CSS color class to use from frontend-token-definition.json.
> 
> https://github.com/liferay/liferay-portal/blob/7.3.5-ga6/modules/apps/layout/layout-page-template-service/src/main/java/com/liferay/layout/page/template/internal/upgrade/v3_4_1/UpgradeFragmentEntryLinkEditableValues.java#L191-L213
> Let me know if you have any questions or if I need to revise my solution.

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @achaparro @kevhlee 

In 7.2 we used a color palette for changing colors, which worked using css classes. In 7.3 we replaced this component and now it uses a color picker that works with tokens (in case the theme doesn't have tokens we fallback to a color palette)

As color picker doesn't use classes we needed to do some kind of conversion. This conversion was done like that because we cannot be sure that the theme the page is using has tokens. So we ended up converting those classes to raw rgb colors so in the worst case the page style will be the same. If we do this conversion and the theme doesn't have those tokens the colors will be lost.

So having this into consideration I don't think we can merge it like this because it may affect other customers

Can you describe a bit more this case? it may be useful to find a solution for both problems. Is the customer using the classic theme for their pages? were they using the css classes (bg-primary, bg-secondary) to change the background color from the theme?

**Comment by kevhlee** [comment]
Hi @victorg1991, thanks for the feedback! You raise a good point. I assumed that the frontend tokens would always stay the same for themes.

So it seems the two problems you mentioned are the following at a high-level (correct me if I'm wrong):

1. Preserving customer style color data.
2. Making UI consistent and accurate.

I can understand why the colors are converted to RGB in 7.3 DXP. Also, there's probably not much that can be done about preserving the color CSS class. However, at its current state, the sidebar editor doesn't seem to handle displaying RGB colors. So, would the solution be to change the UI instead? Specifically, would the solution be to change the color picker so that when an RGB value is detected, it would display as something like `RGB(xxx, xxx, xxx)` as well as the color rather than as `Default`. Let me know your thoughts.

Also, to answer your questions about the customer's use case, the customer is using the classic theme. For the background color, they were using the default colors provided in 7.2 DXP (`bg-primary`, `bg-secondary`). Let me know if that answers your questions and if I need to elaborate further. For more context, you can look at the corresponding customer ticket: <https://issues.liferay.com/browse/LPP-39987>.

**Comment by kevhlee** [comment]
Hi @victorg1991,

Just to add more information about the customer's use case, it would be preferable if the usage of a CSS class for the background color can be preserved upon upgrade. This is so that the customer can customize the background color with their personal CSS code:

<https://issues.liferay.com/browse/LPP-39987?focusedCommentId=2375888&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2375888>

**Comment by victorg1991** [comment]
Hey @kevhlee 

> I can understand why the colors are converted to RGB in 7.3 DXP. Also, there's probably not much that can be done about preserving the use of a color CSS class from 7.2 to 7.3. However, at its current state, the sidebar editor doesn't seem to handle displaying RGB colors. So, would the solution be to change the UI instead? Specifically, would the solution be to change the color picker so that when an RGB value is detected, it would display as something like RGB(xxx, xxx, xxx) as well as the color rather than as Default. Let me know your thoughts.

That seems like a good idea! Do the customer care about this a lot, or they just mentioned it? It doesn't feel like a big deal (just to see if it is worth doing it)

> Just to add more information about the customer's use case, it would be preferable if the usage of a CSS class for the background color can be preserved upon upgrade. This is so that the customer can use their own CSS code to customize the background color. They find that, in 7.3, a newly-created fragment would list the class name for the color while an upgraded would not, causing an inconvenience for the customer. They also use both the classic theme and a custom theme.

In 7.3 there isn't css classes anymore, I guess they refer to css variables, in 7.3 when you select a color from the color picker a css variable is used in the container. Something like: `var(--primary)`. 

Regarding css clases being lost we fixed a bug a couple of months ago: https://issues.liferay.com/browse/LPS-124403. We are preserving the css classes in case they are custom one not the ones that we provide (they ones not present in the converter map). Maybe a possible workaround would be to update customer css classes to other names like instead of primary. maybe primary-1 or primary-custom. we can do this with a groovy script or a custom upgrade script, do you think that this may be a possible fix? If not, we'll need to find a way to keep both className and color value 🤔 

Thanks!

**Comment by kevhlee** [comment]
Hi @victorg1991,

> That seems like a good idea! Do the customer care about this a lot, or they just mentioned it? It doesn't feel like a big deal (just to see if it is worth doing it).

For the customer, it seems more important if there's a CSS variable/class they can reference in their custom CSS code. The sidebar editor could be dealt with as a separate issue.

> Maybe a possible workaround would be to update customer css classes to other names like instead of primary. maybe primary-1 or primary-custom. we can do this with a groovy script or a custom upgrade script, do you think that this may be a possible fix?

That might be feasible. I will talk with the CSE to see if the customer is able to accept this workaround. I'll also take a look at [LPS-124403](https://issues.liferay.com/browse/LPS-124403).

**Comment by victorg1991** [comment]
Closing this for now, I'm watching updates on https://issues.liferay.com/browse/LPP-39987 in case the workaround is not valid and we need to implement a fix for this. 

Thanks! :)

**Pull request closed without merging**
