### PR TITLE
LPS-143509 When creating a new site shows the categories selectors for the required vocabularies

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-143509

To solve this bug, in the creation of the site we have applied the same logic that is applied in the creation of pages when there are required vocabularies.

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/6801

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
