### PR TITLE
LPS-118321 The mapped collection items are same in the configuration panel of different cells

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
Hi @jkappler , there is a regression issue, Please review it.

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/1765

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/1765

**Comment by p2kmgcl** [comment]
ci:close

**Comment by p2kmgcl** [comment]
ci:close

**Comment by Tim-Cao** [comment]
See https://github.com/Tim-Cao/liferay-portal/pull/344

**Pull request closed without merging**
