### PR TITLE
LPS-172536 Replace onPreventCollectionSelect with onBeforeItemSelect

### PR DESCRIPTION
**Pull request by p2kmgcl**
This is rebased onto Brian's master, it's just the last commit.

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
Since @sandrodw3 already fixed that, I am going to apply the refactor in a technical debt ticket (https://issues.liferay.com/browse/LPS-172533), and closed the bug as duplicated.

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Pull request closed without merging**
