### PR TITLE
[TS] LPS-153827

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This is a followup of https://github.com/liferay-echo/liferay-portal/pull/8193.

The circular dependecy has been avoided by implementing the necessary logic into a new Service Wrapper.

Could you please review it?

Thanks in advance!

\cc @rolandpakai

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by lfbesada — CHANGES_REQUESTED** [review]
Hi @rolandpakai @dacousalr,
Thanks for the fix!
IMHO the proper approach is to reuse existing logic instead of copying it.
I will send a PR in that sense.
Regards

**Comment by lfbesada** [comment]
Please see https://github.com/liferay-echo/liferay-portal/pull/8266

**Pull request closed without merging**
