### PR TITLE
LPS-166857

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-166857

Previous PR: https://github.com/liferay-echo/liferay-portal/pull/10222

See: https://github.com/brianchandotcom/liferay-portal/pull/125968#issuecomment-1308864385

cc: @ealonso @BarbaraCabrera

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by lfbesada** [comment]
@ozysouza Thanks a lot for catching it! ❤️ 
I have added a commit to fix that test!

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ozysouza** [comment]
Hi @lfbesada, there is a conflic on the PR. Could you please have a look at?

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
🙏

**Comment by lfbesada** [comment]
🕯️ 🤞 🍀

**Comment by ozysouza** [comment]
I'll keep both eyes on the results

**Comment by lfbesada** [comment]
ci:reevaluate:1257401_5353

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/126132

**Pull request closed without merging**
