### PR TITLE
LPS-201205 Asset library tags are not displayed in asset tag selector  of filter and order from document library administration

### PR DESCRIPTION
**Pull request by Mikellorza**
bug : https://liferay.atlassian.net/browse/LPS-201205

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
@Mikellorza, better send this to Lima team, so that they can take a look.

Thanks

**Comment by Mikellorza** [comment]
ok @jkappler. I had just this doubt if i had to send it to them or not , because tag are ours and d&m is yours. Anyway closing this PR and sending it  to us.

Thanks Jurgen!

**Comment by Mikellorza** [comment]
ci:close

**Pull request closed without merging**
