### PR TITLE
LPS-184009 Apply new Document Processor to others Fragment Processors

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-184009

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1267401_9292

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1277401_8241

**Comment by lfbesada** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward:force

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
