### PR TITLE
LPS-165872 Better manage focused state

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:close

**Comment by p2kmgcl** [comment]
ci:reopen

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
I think we might need to update some poshi tests here, as the mouse/keyboard interactions have changed a little bit. @Tim-Cao are you able to have a look?

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, the placeholder *Choose an Option* is missing in Select From List fragment. Would you mind having a look at?
image

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl Another request, is that possible to add show to class?
Dropdown

**Comment by p2kmgcl** [comment]
Thanks so much for having a look. I am adding the placeholder and the show class, no problem :smile:

**Comment by p2kmgcl** [comment]
@Tim-Cao updated!

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, is that possible to change the id to **rvwb-select-from-list-input**?
SelectFromList
Like other form inputs fragments
Text

**Comment by p2kmgcl** [comment]
> Hi @p2kmgcl, is that possible to change the id to **rvwb-select-from-list-input**?

Sure, updating it a sec

**Comment by p2kmgcl** [comment]
> > Hi @p2kmgcl, is that possible to change the id to **rvwb-select-from-list-input**?
> 
> Sure, updating in a sec

:thinking: but do you know that "rvwb" is autogenerated, right?

**Comment by ealonso** [comment]
resend here: https://github.com/liferay-echo/liferay-portal/pull/10307

**Pull request closed without merging**
