### PR TITLE
LPS-141471 Removes unnecessary class

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
cc: @ruben-pulido

**Comment by Tim-Cao** [comment]
Hi @ealonso and @ruben-pulido, there is a regression issue. The latest changes are not shown in Preview page after enable workflow for Content Page.
**Steps to reproduce**
1. Add a new site
2. Add a published content page with a Heading fragment
3. Enable the Single Approver workflow for Content Page in site
4. Edit the inline text of Heading then Submit for Publication
5. Navigate to the Pages admin
6. Click the Preview action of page item

**Expected Results:**
The edited inline text should be shown in preview page.

**Actual Results:**
The default inline text is shown in preview page.

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
