### PR TITLE
LPS-121011 Adapt tests to check both messages

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Taking a look

**Comment by victorg1991** [comment]
Sent here: https://github.com/liferay-echo/liferay-portal/pull/2514

**Comment by victorg1991** [comment]
ci:close

**Pull request closed without merging**
