### PR TITLE
[TS] LPS-135873

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This PR addresses the need of stripping noscript blocks to avoid indexing non-visible content.

The solution has been moved to the general method since all its usages are calls from methods which needs to get a summary or a short descriptions from a given asset content.

Could you please review it?

Thanks in advance

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @dacousalr.
It should be reviewed by Core Infra team since you are modifying the HtmlImpl.java.
Regards,
Eudaldo

**Comment by ealonso** [comment]
ci:stop

**Comment by laszlopap** [comment]
Hi @dacousalr !

Could you please forward it to the core infra team?

Thanks!

**Pull request closed without merging**
