### PR TITLE
LPS-118919

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
LPS-118919 To keep the correct order use default locale to search for asset entry results.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
Hey @georgel-pop-lr @antonio-ortega,

Could you please take a look to the broken test? It seems to be related

Regards,
Eudaldo

**Comment by ealonso** [comment]
ci:close

**Comment by antonio-ortega** [comment]
Hi @ealonso ,

I think we need your help to understand what is the expected behavior in the case explained in LPS-118919.

When all the contents have a translation to the language we are displaying there is no doubt about asset publisher ordering, but what should happen when:
1. Only some of the contents have been translated
2. None of the contents have been translated
?

Since this is more a sort of "behavior clarification" question, we can raise a PTR to your team to clarify it. Just let us know if you prefer to take that way.

Thanks in advanced.

Regards.

**Comment by ealonso** [comment]
Hey @antonio-ortega 

Could you please open a new PTR?

Regards,
Eudaldo

**Comment by antonio-ortega** [comment]
Sure! https://issues.liferay.com/browse/PTR-1898

Thanks for your help!

**Pull request closed without merging**
