### PR TITLE
LPS-117902 Add test to check that if we add a new DDMStructure, it will be available as a variation for the classname of JournalArticle

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Since the failure is unrelated to changes in PR and in order to not clog up ci resources I pushed directly to BChan.
See https://github.com/brianchandotcom/liferay-portal/pull/92006

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
