### PR TITLE
LPS-112937 - WCD portlet header overlaps over first line of content

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @liferay-echo team!

This is addressing an apparently long-standing issue where the portlet header, when using the 'barebones' application decorator setting, will overlap over the first line of content. This prevents any admin user from interacting with the first line of content. I've switched the barebones portlet header positioning from absolute to relative to adjust for this while still hopefully maintaining usability across display resolutions, but please let me know if you have any concerns about this solution. Thanks!

As a note, I'm not sure why the LPS has the "7.2.x-ee only" tag -- this issue is still present and reproducible in Master.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
Hey @wanderlast!

Thanks for the PR. I am checking the result, and adding position relative there works, but it pushes the content down creating a blank space.

[Screencast from 2023-04-21 09-02-16.webm](https://user-images.githubusercontent.com/800645/233564398-91ff47a3-69df-4285-a6d4-3f06b13566dd.webm)

I have tried to add `width: auto` to that same class, and it looks like it fixes the problem, because the header only has the ellipsis button:

image

Could you check if that solution is valid, please?

**Comment by wanderlast** [comment]
Hi @p2kmgcl,

Thanks for taking a look at this! That looks good to me as well.

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/11845

**Pull request closed without merging**
