### PR TITLE
LPS-205423 AssetCategoryLocalServiceTest fails in certain databases

### PR DESCRIPTION
**Pull request by jkappler**
https://liferay.atlassian.net/browse/LPS-205423

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
Verified with ibmcom/db2:11.5.7.0

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:report:2488188266

**Comment by Tim-Cao** [comment]
ci:forward:force

**Pull request closed without merging**
