### PR TITLE
[TS] LPS-134554

### PR DESCRIPTION
**Pull request by jonathanmccann**
These changes display the title (in this case the name of the category by which the assets are grouped) in the Asset Publisher widget. This is the behavior previously in 7.0 and was seen after a client upgraded.

Please let me know if there is a reason the title was removed or if changes need to be made. Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1107401_4859

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
