### PR TITLE
LPS-138914 Make configurable available widget template languages

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-138914

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1057401_8215

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/5844

**Pull request closed without merging**
