### PR TITLE
LPS-206200 buildLang

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:report:2488260716

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @victorg1991, the buildService task failed at apps:journal:journal-service:buildService. Would you mind having a look at?
```
     [echo] --- a/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/http/JournalArticleServiceHttp.java
     [echo] +++ b/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/http/JournalArticleServiceHttp.java
     [echo] @@ -941,17 +941,20 @@ public class JournalArticleServiceHttp \{
     [echo]      \}
     [echo]    \}
     [echo]  
     [echo] -  public static int getArticlesByArticleIdCount(
     [echo] -    HttpPrincipal httpPrincipal, long groupId, String articleId,
     [echo] -    int status) \{
     [echo] +  public static java.util.List<com.liferay.journal.model.JournalArticle>
     [echo] +    getArticlesByArticleId(
     [echo] +      HttpPrincipal httpPrincipal, long groupId, String articleId,
     [echo] +      int start, int end,
     [echo] +      com.liferay.portal.kernel.util.OrderByComparator
     [echo] +        <com.liferay.journal.model.JournalArticle> orderByComparator) \{
     [echo]  
     [echo]      try \{
     [echo]        MethodKey methodKey = new MethodKey(
     [echo] -        JournalArticleServiceUtil.class, "getArticlesByArticleIdCount",
     [echo] -        _getArticlesByArticleIdCountParameterTypes21);
     [echo] +        JournalArticleServiceUtil.class, "getArticlesByArticleId",
     [echo] +        _getArticlesByArticleIdParameterTypes21);
     [echo]  
     [echo]        MethodHandler methodHandler = new MethodHandler(
     [echo] -        methodKey, groupId, articleId, status);
     [echo] +        methodKey, groupId, articleId, start, end, orderByComparator);
     [echo]  
     [echo]        Object returnObj = null;
     [echo]  
     [echo] @@ -963,7 +966,8 @@ public class JournalArticleServiceHttp \{
     [echo]            exception);
     [echo]        \}
     [echo]  
     [echo] -      return ((Integer)returnObj).intValue();
     [echo] +      return (java.util.List<com.liferay.journal.model.JournalArticle>)
     [echo] +        returnObj;
     [echo]      \}
     [echo]      catch (com.liferay.portal.kernel.exception.SystemException
     [echo]            systemException) \{
     [echo] @@ -974,20 +978,17 @@ public class JournalArticleServiceHttp \{
     [echo]      \}
```

**Comment by victorg1991** [comment]
Sure thing, many thanks @Tim-Cao for checking this :)

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:report:2488738858

**Comment by Tim-Cao** [comment]
ci:forward:force

**Pull request closed without merging**
