### PR TITLE
LPS-106212 - As a page administrator I can export one content page template as a well defined open format

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @jkappler

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/301

**Pull request closed without merging**
