### PR TITLE
LPS-136124 Load Liferay.Form on initialization 

### PR DESCRIPTION
**Pull request by alinedoleron**
Ticket: https://issues.liferay.com/browse/LPS-136124

### CODE REVIEW

**Comment by alinedoleron** [comment]
ci:test:sf

**Comment by alinedoleron** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @alinedoleron 
I've been analyzing this bug and I don't think this is the best solution for this.

If we see this particular code: https://github.com/liferay/liferay-portal/blob/777c01c82a917c4335c32e1179de2ce7bc64b9d1/modules/apps/portlet-configuration/portlet-configuration-web/src/main/resources/META-INF/resources/edit_configuration.jsp#L27-L33 that is the part where the configuration is rendered. In this case it is using DDM but in other case it is just using a jsp. Since only in some cases we need the form to be accessible I think we should move this code elsewhere

I'm preparing a PR for you to see another alternative :)

Thanks!!

**Comment by victorg1991** [comment]
sent this: https://github.com/liferay-forms/liferay-portal/pull/1477 :) 

Closing this for now in favor of the new one

**Pull request closed without merging**
