### PR TITLE
LPS-188078 Handle the possibility of the comment user being null (i.e. they were deleted at some point after they made the comment)

### PR DESCRIPTION
**Pull request by mbowerman**
Motivation
=======
If a comment was made on a fragment by a user who has since been deleted, then the entire page editor fails to load. This is a very poor user experience, as it is a scenario that is fairly likely to occur and it prevents the user from being able to edit the page at all if it happens.

Proposed Solution
========
Handle the possibility of the comment user being null in the CommentUtil#getCommentJSONObject class.

Steps to Verify
========
1. Start up Liferay and log in as the admin user.
2. Create a user and assign it the Site Administrator role for the default Liferay DXP Site.
3. Log in with the new user and edit the Home Page.
4. Add an HTML fragment onto the Home Page.
5. Leave a comment on the HTML fragment.
6. Log out and then log back in with the Admin user.
7. Deactivate and then delete the new user.
8. Go back to the Home page as the Admin user and edit it.

References to existing code (if applies)
========
Here is a place where a similar solution is applied: https://github.com/liferay/liferay-portal/blob/f6d10ea9c662b8d5408636c2805681d249dd0a1a/modules/apps/sharing/sharing-taglib/src/main/java/com/liferay/sharing/taglib/internal/util/CollaboratorsUtil.java#L127-L134

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Thanks @mbowerman!

**Comment by ealonso** [comment]
ci:stop

**Comment by jkappler** [comment]
The PR seems to be stuck, resending here as is @mbowerman: https://github.com/liferay-echo/liferay-portal/pull/12531

**Pull request closed without merging**
