### PR TITLE
LPS-200303

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by lfbesada — APPROVED** [review]
Beautiful as always :heart_eyes:

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
Hi @ealonso , pending label is missing for content page, can you take a look?
here are the steps:
1. Enable Single Approver for Content Page
2. Add a content page
3. Click Submit for Workflow
4. Go to page admin

Actual result:
Only draft label displays, there's no pending label.

Expected resylt:
Draft and pending label display.

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/14299

**Pull request closed without merging**
