### PR TITLE
Lps 128446

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-128446

The issue here is that getArticleDisplay is being called from JournalArticleLocalService when web contents are linked to display page templates. This method does not return scheduled web content displays which did not apply the user to preview the web content.
To fix the issue, I added a condition to the if statement that the view mode is not equal to "preview".

This PR is being resent with updated steps due to the issue not being reproducible based on this [comment](https://github.com/liferay-echo/liferay-portal/pull/3951#issuecomment-795026637)
I also added a screen recording of the reproduction steps to avoid confusion.

### CODE REVIEW

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Hi @noornajj 

Thanks for the fix and for clarifying the reproduction steps. With the additional information you have provided I have been able to reproduce the issue.

Sent to Brian [here](https://github.com/liferay-echo/liferay-portal/pull/3986)

**Comment by noornajj** [comment]
Thank you @ruben-pulido. 
Did you test your changes by any chance? Because while I was debugging, I noticed the viewMode that is passed into the method had a different value than "preview". That is why I created a new view mode variable.

**Comment by ruben-pulido** [comment]
Hi @noornajj 
You are totally right. My changes broke your fix. I did test them, but definitely not correctly. Sorry about that. I'll send a follow-up fix. Thanks for letting me know

**Comment by ruben-pulido** [comment]
Follow-up fix sent [here](https://github.com/liferay-echo/liferay-portal/pull/3994)

**Pull request closed without merging**
