### PR TITLE
LPS-180051

### PR DESCRIPTION
**Pull request by icgsbr**
### Jira Link
[LPS-180051](https://issues.liferay.com/browse/LPS-180051)

### What was done:
- Enabled collection creation on different language from the default one
- Fixed collection locale reference in order to fix the asset publisher view when in a language different from the default one

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by icgsbr** [comment]
ci:test:sf

**Comment by icgsbr** [comment]
ci:test:stable

**Comment by icgsbr** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @icgsbr 

If this behaviour is not reproducible in master, maybe we don't need to change anything in master. Is there a way to reproduce it in master?

**Comment by icgsbr** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
@icgsbr Would you mind updating the jira ticket? the description is a bit misleading :)

>  Can't test on branch
>  Can't test on master
>  The behavior was reproduced in LXC project.

**Comment by icgsbr** [comment]
> @icgsbr Would you mind updating the jira ticket? the description is a bit misleading :)
> 
> > Can't test on branch
> > Can't test on master
> > The behavior was reproduced in LXC project.

Of course! I'll do it right away! 😄

**Comment by icgsbr** [comment]
ci:test:relevant

**Comment by icgsbr** [comment]
ci:test:relevant

**Comment by icgsbr** [comment]
ci:test:relevant

**Comment by icgsbr** [comment]
ci:test:stable

**Comment by icgsbr** [comment]
ci:test:relevant

**Comment by icgsbr** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @icgsbr 
Thanks for the fix ❤️ 
The changes in the second commit look good to me but the first commit should be reviewed by the Forms Team as it is its component.
Could you please send this PR to them so they can review that commit?
For our side, we are OK with the second commit.
Thank you
Regards

**Pull request closed without merging**
