### PR TITLE
LPS-119736 Menu must be closed using the modal closing method to correctly handle the animation

### PR DESCRIPTION
**Pull request by jbalsas**
Manual forward of https://github.com/liferay-frontend/liferay-portal/pull/350

[Tests are green](https://github.com/liferay-frontend/liferay-portal/pull/350#issuecomment-685653421)
✔️ ci:test:stable - 21 out of 21 jobs passed
✔️ ci:test:relevant - 57 out of 57 jobs passed in 1 hour 56 minutes

This is a small issue detected while reviewing the last UX changes to Applications Menu.
---

https://issues.liferay.com/browse/LPS-119736

Applications Menu fading / sliding on close animation wasn't working when closing the menu with the keyboard shortcut (CMD + SHIFT + M).

Modal's hook `onClose` method needs to be used to close the menu to make this work.

Steps to reproduce:
- Go to Home
- Press `CMD` + `SHIFT` + `M`. The Menu should open sliding from top.
- Press `CMD` + `SHIFT` + `M`. The Menu should close sliding and fading to top.

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
Executed ci : forward on liferay-frontend#350

**Pull request closed without merging**
