### PR TITLE
LPS-157995 Add actions when editing a page

### PR DESCRIPTION
**Pull request by ozysouza**
This is only for master.
https://issues.liferay.com/browse/LPS-157995

Rebased from https://github.com/liferay-echo/liferay-portal/pull/8901

cc @jkappler

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ozysouza** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, would you mind having a look at the integration test failures?

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/8938

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
