### PR TITLE
LPS-185054 Change collection display content when selecting experience with the same segment

### PR DESCRIPTION
**Pull request by Mikellorza**
Story: https://issues.liferay.com/browse/LPS-183723
Subtask: https://issues.liferay.com/browse/LPS-185054

Description
---
Added logic to change the displayed content of a collection display when we are selecting an experience and that experience segment is the same as the selected experience.

Integration test are included.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
See: https://github.com/Mikellorza/liferay-portal/pull/20

**Pull request closed without merging**
