### PR TITLE
LPS-177162 Instead of reverse the collection just put the default locale in the first position

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-177162

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Failures are not related, pushed to BChan directly at https://github.com/brianchandotcom/liferay-portal/pull/131056

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
