### PR TITLE
LPS-141196 Change to use ResourceURLBuilder and pass the fragmentCollectionId as parameter

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Just wanted to thank @YurenaC since I didn't need to investigate about javax.portlet.version=3.0 issue 🤗

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
