### PR TITLE
[TS] [Urgent] LPS-201860 Menu Display Configuration Window frequently shows wrong information in Preview Pane

### PR DESCRIPTION
**Pull request by mbowerman**
Motivation
=======
When configuring a Menu Display widget, a Preview Pane is shown to allow the user to see what the menu will look like when rendered with the selected configuration. Unfortunately, however, the updated values are often not sent properly to the backend, so the Preview Pane renders the menu using the old values instead of the newly selected ones. This causes a misleading and confusing user experience for the user who is trying to configure the Menu Display widget.

See my comment [here](https://liferay.atlassian.net/browse/LPP-51699?focusedCommentId=2510314) and Minhchau's comment [here](https://liferay.atlassian.net/browse/LPP-51699?focusedCommentId=2510470) for further explanation about the root cause.

A similar bug, which Minhchau alluded to in his comment, was occurring where the default template was being used any time the form was updated except for the times that the template dropdown specifically was the thing that was updated. This was because `displayStyle` was gibberish, because it was using the _element_, rather than the _value_ of the element, as Minhchau mentioned in his comment.

Ticket : [LPS-201860](https://liferay.atlassian.net/browse/LPS-201860)

Proposed Solution
========
* Debounce the "resetPreview" method to ensure that it always gets called with the correct parameters having been set.
* Fix the problem where we were passing in the display style _element_, rather than the _value_, if option was null, by using the value of the element. Also rename the variables to be more accurate ("displayStyle" should refer to the element to be consistent with how the other variables were named. "displayStyleValue" can refer to the value).

Steps to Verify
========
1. Add a Navigation Menu named “Test Navigation Menu” (you can just leave it blank).
2. Create a Widget Page.
3. Add a Menu Display Widget to the Widget Page.
4. Open up the Configuration Menu for the Menu Display Widget.

**Checkpoint:** Observe that the Pages Hierarchy Navigation is selected and the Preview pane shows the Pages navigation.

5. Select the “Choose Menu” radio option, then press the Select button and select the “Test Navigation Menu”.

**Checkpoint:** Observe that the Preview pane now shows an empty window (since the Test Navigation Menu is empty).

6. Select the “Select Navigation” radio option again.

**Expected Result:** The Preview Pane would be updated to show the Pages navigation.
**Actual Result:** The Preview Pane stays blank.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
LGTM! Thanks!

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
