### PR TITLE
LPS-173884

### PR DESCRIPTION
**Pull request by robertoDiaz**
Hi guys!

in this pull I've applied error handling to JournalArticle Feeds when its link validation fails.

I've use the same pattern as used for DLFileEntries, layouts...

Currently the portal only shows a generic error, with my changes the error is more user friendly and points to the invalid url.

If you have any questions, please tell me! :)

See the screenshot with the fix:
Captura de Pantalla 2023-02-06 a las 13 30 30

and the current behavior:

Captura de Pantalla 2023-02-06 a las 13 33 22

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129889

**Comment by Tim-Cao** [comment]
ci:close

**Comment by jkappler** [comment]
thanks @Tim-Cao!

**Pull request closed without merging**
