### PR TITLE
LPS-165478 master

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team.

could you please review my fix?

Thanks, Roland

**Reproduction Steps:**

1. Set up the master bundle
2. Go to Content and Data --> Web Content --> Structures and create a structure with a "Select from list" field.
3. Go to web content and create web content from the structure and in the content select "Option" then publish.
4. Go to Design --> Page Templates --> Display Page Templates and add a DPT and add to it a Heading fragment.
5. Doubleclick on the fragment and from the right panel at the "Mapping" --> "Source" select "Specific Content" and select the web content under "Item" and at the "Field" find the content structure and select "Select from list".
6. Check the fragment heading.

**Actual Result:** The Option appears incorrectly rendered with characters like [" Option "]. There are no errors in the log and browser console.
**Expected Result:** The Option appears normally as it is.

In case creating a Template for the structure and mapping this template to the Fragment

<#if (SelectFromList54473153.getData())??>
    ${SelectFromList54473153.getData()}
</#if>
the rendering shows the Field reference (Option65398360) instead of the field value (Option)

**Fix**
The SELECT, RADIO and CHECKBOX_MULTIPLE types cases are implemented

https://issues.liferay.com/browse/LPS-165478

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by ruben-pulido** [comment]
Hi @rolandpakai 

The baseline error seems related to the changes. Can you fix it? Thanks!

**Comment by rolandpakai** [comment]
Hi @ruben-pulido 

i fixed the baseline.

Thanks, Roland

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1387401_4303

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
Resnet because of the Conflict: https://github.com/liferay-echo/liferay-portal/pull/9978

**Pull request closed without merging**
