### PR TITLE
[TS] LPS-176405 live groups web contents will appear in the item selector, if staging is not set for web contents

### PR DESCRIPTION
**Pull request by GaborKomaromi**
Hi Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-176405
Thank you!
-----
**Reproduction Steps:**

1. Go to Publishing --> Staging --> enable local staging and uncheck "Web Content" from the Staged Content.
2. Go to Content & Data --> Web Content and create basic web content.
3. Go to Site Builder --> Pages and create a widget page, then place a web content display portlet on it.
4. Click on the "Select web content to make it visible" link in the WCD and click "Select" in the Popup.

**Expected outcome:** The web content does not appear for selection.
**Actual outcome:** If web contents are not staged, the live group's web content should be displayed.

**Solution:**
This regression was caused by LPS-169729. If staging for web contents were disabled it was not taken into consideration, so I implemented a method where it checks that, and in this case, web contents from the live site will be visible.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by GaborKomaromi** [comment]
ci:test:sf

**Comment by GaborKomaromi** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Please see: https://github.com/liferay-staging/liferay-portal/pull/251

**Pull request closed without merging**
