### PR TITLE
LPD-16483 Add an empty view template to the Test Portlets

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-16483

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:report:2534337826

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
