### PR TITLE
LPS-183937 - New site with changed default locale loses name

### PR DESCRIPTION
**Pull request by ruben-pulido**
https://liferay.atlassian.net/browse/LPS-183937 - New site with changed default locale loses name

Resending, since original fix modified a generated file as pointed here (https://liferay.slack.com/archives/CLCD3DQLF/p1696523872380109?thread_ts=1696519664.317309&cid=CLCD3DQLF)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by liulukiwi** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141992

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
