### PR TITLE
[TS] Avoiding UI Error regarding AssetListEntrySegmentsEntryRel

### PR DESCRIPTION
**Pull request by rijema**
Hi team, using the customer database, when exporting their portal and trying to import, I faced some null values. This fix has the intention of solving most part/more of the empty queries verification we have through the Content Processor, avoiding UI errors such as this one reported by the customer. Let me know your thoughts about this. Thanks!

```
Se produjo un error inesperado con el proceso de publicación. Consulte la configuración de publicación y del portal.
The model.resource.com.liferay.asset.list.model.AssetListEntrySegmentsEntryRel cb1e39d2-e79b-3df7-a848-742be9fa22f1 could not be imported because of the following error: null.
```

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
Hi @rijema 
Thanks for the fix :heart: 
Please can you modify the ticket description so that it can be reproduced? Also, before sending us a PR the bug ticket should be verified on the master branch, and if this ticket isn't verified it is still on Open status.
Once the ticket is in the correct status (In Review) and the steps describe how to reproduce the bug, I will review the solution.
Thank you very much in advance!

**Comment by rijema** [comment]
Hi @lfbesada ! Thanks for your comment!! Of course, I will try to reproduce on master and share with you the results. In this case, do you want to close this PR ou should remain open? Thanks again. ☺️

**Comment by lfbesada** [comment]
Hi @rijema 
Thank you!
The fix looks very good, but I need to know what the error is so I can try it.
If it's okay with you, keep this PR and please let me know when it's all ready to review.
But if you prefer to send it again later, it is okay for me too. 
Regards

**Comment by rijema** [comment]
Hi @lfbesada !
First of all, I'm sorry. Due to local holidays and teammate's PTO in the end of last week I didn't have enough time to take a look on this properly. I'm closing this PR and when I create another one I will tag you. Thanks for commenting and letting me aware again. Have a great day!

**Pull request closed without merging**
