### PR TITLE
[TS ] LPP-47896 > LPS-175473 fix duplicate ERC for importedClientExtensionEntryRel

### PR DESCRIPTION
**Pull request by Vy-CES**
Hi team, this ticket has passed our internal review here: https://github.com/ces-huynguyen/liferay-portal/pull/106. Please help us to review the work and give us your feedback. Thank you in advance!

Please see [LPS-175473](https://issues.liferay.com/browse/LPS-175473) for reproducible steps.

## Root cause analysis.
When the imported clientextensionRel is referenced in multiple places, at the second time it is imported, it has the ERC not null but the clientextensionRelId is not different from the pre-existing clientextensionRel. Therefore a DuplicateClientExtensionEntryRelExternalReferenceCodeException will be thrown as Liferay think they are not identical [ClientExtensionEntryRelPersistenceImpl.java#L3951-L3961](https://github.com/liferay-echo/liferay-portal/blob/master/modules/apps/client-extension/client-extension-service/src/main/java/com/liferay/client/extension/service/persistence/impl/ClientExtensionEntryRelPersistenceImpl.java#L3951-L3961)

## Proposed solution.
In Data Mirror Strategy: the content will initially be imported as new within the target environment with new ids and updated references, but subsequent imports will retain the same ids:
- If there is an entry with the same unique ID (ERC) on the target Site, the new one replaces it.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Vy-CES** [comment]
ci:test:sf

**Comment by Vy-CES** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
