### PR TITLE
[TS] LPS-194116 Inconsistency in the column name from AssetVocabulary, when importing vocabularies replacing space with dash

### PR DESCRIPTION
**Pull request by dcarrillolf**
Motivation
=======
There are a naming inconsistency if the user creates a Vocabulary from the UI and importing the same Vocabulary by Import/export functionality. If the vocabulary has title "Hello World", the column "name" from the AssetVocabulary table willl have the following values:
- Created by UI: "hello world"
- Created by Export/Import: "hello-world"

Proposed Solution
========
Modified the StagedModelDataHandler to pass the default name as vocabularyTitleMap.get(LocaleUtil.getSiteDefault()), like the UI.

Steps to Verify
========
Steps to reproduce with MySQL:

1. Create a site A and create a "vocabulary A" (Categorization - Categories - Vocabularies - +)
2. Export the vocabulary with the Categories Export, it will generate export.lar
3. Create a site B and import the export.lar in the Categories Import
4. Check the database, the table assetvocabulary will have two Vocabularies, one with dash ("vocabulary-a") and the other one with space ("vocabulary a").

Alternative Solutions that were discarded (if applies)
========
- I could not find any existing AssetVocabularyLocalService method that could be use in this case since it requires externalReferenceCode, but maybe is another solution to implement a new local service method.
- Moreover, there is a _generateVocabularyName method that literally replaces spaces by dash, but is not used in all the cases when adding a new vocabulary.
`private String _generateVocabularyName(long groupId, String name) {
		String vocabularyName = _getVocabularyName(name);

		vocabularyName = StringUtil.replace(
			vocabularyName, CharPool.SPACE, CharPool.DASH);

### CODE REVIEW

**Comment by jkappler** [comment]
Hi @dcarrillolf, thanks for sending the PR, can you please first verify your commits? Otherwise the PR will be rejected when sending it to BChan. 

Afterwards we will gladly review it.

Thanks

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139660

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
