### PR TITLE
LPS-182581 InfoFramework localization issues

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-182581

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by lfbesada** [comment]
ci:forward:force

**Comment by lfbesada** [comment]
ci:forward:force

**Comment by lfbesada** [comment]
ci:forward:force

**Comment by lfbesada** [comment]
ci:forward:force

**Comment by lfbesada** [comment]
manually forwarded, see: https://github.com/brianchandotcom/liferay-portal/pull/133874

**Pull request closed without merging**
