### PR TITLE
LPS-159422 Use existing pageContents from addItem

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
😞

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
Hi @sandrodw3! There is a regression issue. Could you please have a look at?

1. Add a content page
2. Add a button fragment 
3. Go to Styles tab of button fragment and select Align Center
4. Duplicate the fragment
5. Delete the duplicated fragment
6. Click on the History icon
7. Click on Add Button menu item

There is an error on UI -> An unexpected error occurred

**Comment by ozysouza** [comment]
The failures on these integration tests are also related.

com.liferay.layout.content.page.editor.web.internal.portlet.action.test.UpdateFormItemConfigMVCActionCommandTest
com.liferay.layout.taglib.test.RenderLayoutStructureTagTest

**Comment by sandrodw3** [comment]
cc @p2kmgcl

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/9858

**Pull request closed without merging**
