### PR TITLE
LPS-148716 - Modal to save a fragment composition mentions "Collection" instead of "Fragment Set"

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
@ruben-pulido There is a rebase error

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
https://github.com/liferay-echo/liferay-portal/pull/7480

**Pull request closed without merging**
