### PR TITLE
LPS-162999 Avoid setting breadcrumbs as disabled area

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
Hey @Tim-Cao, @ozysouza,

I think there might be some tests that need update for this PR. Now we are not opening the sidebar automatically when some item is selected (it is an acceptance criteria of this story).

Also this PR is not hidden behind any feature flag (I asked Mateo and he is fine with that, as this is a small UI change).

**Comment by Tim-Cao** [comment]
```
Given a page I am editing,

When I close the left sidebar (containing the browser) and then I click on any fragment or component,

Then the left sidebar is not openend automatically anymore.
```
Is these, right? @p2kmgcl

**Comment by p2kmgcl** [comment]
> ```
> Given a page I am editing,
> 
> When I close the left sidebar (containing the browser) and then I click on any fragment or component,
> 
> Then the left sidebar is not openend automatically anymore.
> ```
> 
> Is these, right? @p2kmgcl

yep

**Comment by p2kmgcl** [comment]
> Hi @p2kmgcl, there is a regression issue found. When click the body of fragment and keep left sidebar open, it won't be redirects to the Browser panel.
It is against with show the Breadcrumb in Browser panel.
I don't think we have cases required to update. The close button is a new feature, there is only one case to test it is able to close the left sidebar panel.

You're right, I am updating that.

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
