### PR TITLE
[TS] LPS-114872 ServiceContext is null when it is executed by scheduled job AssetEntriesCheckerUtil.checkAssetEntries()

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-114872

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@yichenroy this passed all green but it never got sent to me, so I merged it manually.

@jorgediaz-lr @ealonso fyi

**Comment by brianchandotcom** [comment]
ci:close

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by yichenroy** [comment]
@brianchandotcom there was no `ci:forward` command used in this pull request so it wasn't forwarded.

**Pull request closed without merging**
