### PR TITLE
LPS-147088

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This is a fix for a regression bug caused by the last commit of LPS-146458.

As per Brian's [request](https://github.com/brianchandotcom/liferay-portal/pull/113103#issuecomment-1030914323), a Poshi test has been added to take into account the presence or absence of Workflow when displaying the available Status filters.

Could you please review it?

Thanks in advance!

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7192

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
