### PR TITLE
LPS-132227 Use DropdownWithItems

### PR DESCRIPTION
**Pull request by p2kmgcl**
cc @veroglez 

(This PR should have no UI changes, just a small refactor)

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/4731

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
