### PR TITLE
Lps 159512

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,
This is a follow up of https://github.com/liferay-echo/liferay-portal/pull/9159 with Test included.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Thanks @balazssk!

cc:// @lfbesada

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
