### PR TITLE
LPS-114885 Separate logic in two methods instead of relying on the existence of a property for determining if an article or a folder is about to be publish

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
@jonathanmccann

**Comment by jonathanmccann** [comment]
@victorg1991 Thanks for taking a look and cleaning it up.

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/901

**Pull request closed without merging**
