### PR TITLE
LPS-183651 Rename copy methods of ServiceImpl classes to follow source/target pattern

### PR DESCRIPTION
**Pull request by Mikellorza**
PR with SF requested from Brian in this PR: https://github.com/brianchandotcom/liferay-portal/pull/132924#issuecomment-1498812258

Task: https://issues.liferay.com/browse/LPS-181166
Subtask: https://issues.liferay.com/browse/LPS-183651

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:reevaluate:1377401_11277

**Comment by alessandromalves** [comment]
Unique failures were found by the CI that was not reproducible locally, and the others are not related to this PR. See https://github.com/brianchandotcom/liferay-portal/pull/134567

**Pull request closed without merging**
