### PR TITLE
LPS-119582 - Reindexing all index searches loses all the content from Content Pages

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @pavel-savinov

After the changes in this PR:

- Searching behaves consistently after a Content Page is published and after Reindex takes place.
- Content of widgets is not longer indexed when the page is published as part of the Page (we assume that widgets are in nature dynamic, and the content rendered by the widget when the page is published or after a reindex, does not necessarily match the content that would be rendered when the search takes place, which could result in confusing behaviour)

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ruben-pulido, your changes cause the following NPE error.
Add a page based on Blank
Add an Asset Publisher widget to page
Click Publish
`2020-09-11 00:43:57.358 ERROR [http-nio-8080-exec-2][PortletRequestDispatcherImpl:304] Unable to dispatch request: java.lang.NullPointerException
2020-09-11 00:43:57.361 ERROR [http-nio-8080-exec-2][PortletServlet:119] javax.portlet.PortletException: org.apache.jasper.JasperException: java.lang.NullPointerException
javax.portlet.PortletException: org.apache.jasper.JasperException: java.lang.NullPointerException
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.dispatch(PortletRequestDispatcherImpl.java:307)
	at com.liferay.portlet.internal.PortletRequestDispatcherImpl.include(PortletRequestDispatcherImpl.java:123)
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:571)
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:587)
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doView(MVCPortlet.java:177)
	at com.liferay.portal.kernel.portlet.LiferayPortlet.doDispatch(LiferayPortlet.java:295)
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doDispatch(MVCPortlet.java:466)
	at com.liferay.asset.publisher.web.internal.portlet.AssetPublisherPortlet.doDispatch(AssetPublisherPortlet.java:366)
	at javax.portlet.GenericPortlet.render(GenericPortlet.java:291)
	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:305)
	at com.liferay.asset.publisher.web.internal.portlet.AssetPublisherPortlet.render(AssetPublisherPortlet.java:268)
	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:127)
	at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:58)
	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:124)
	at com.liferay.asset.publisher.web.internal.portlet.filter.AssetPublisherRenderParametersPortletFilter.doFilter(AssetPublisherRenderParametersPortletFilter.java:69)
	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:124)
	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:71)
	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)`
[liferay.2020-09-11.log](https://github.com/liferay-echo/liferay-portal/files/5205321/liferay.2020-09-11.log)

**Comment by ruben-pulido** [comment]
Thanks for the analysis @Tim-Cao!
The issue should be fixed https://github.com/liferay-echo/liferay-portal/pull/2297

**Pull request closed without merging**
