### PR TITLE
LPS-121579 Compute column style for non-divisible column widths

### PR DESCRIPTION
**Pull request by veroglez**
If user chooses a number of columns that can't divide 12,
we compute the remaining of the division and add it to the
middle column

### CODE REVIEW

**Comment by veroglez** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
cc: @veroglez @p2kmgcl https://github.com/veroglez/liferay-portal/pull/59#discussion_r497310559

**Pull request closed without merging**
