### PR TITLE
LPS-152849 Add support for redirections to display pages

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:reevaluate:1297401_2864

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1277401_3268

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by lfbesada — COMMENTED** [review]
Hi @adolfopa 
Thanks a lot for the pull request! 😍 
From my point of view, it is an excellent SEO improvement and I am sure many customers will be happy with it.
I have been testing the PR and it works OK. 
I found just a problem: when redirecting it always prepends the public page prefix and the site-id. Even if the user is on the default company site and/or accessed using the site virtual host.
IMHO this issue could be easy to fix: as we just want to redirect the friendly URL we could do the redirect to an absolute URL using the part of the original request URL that precedes the original friendly URL and appending the desired friendly URL. In that way we will redirect to an absolute URL instead of a relative URL, ensuring that the part of the original request URL that we don't want to vary is preserved.
What I mean is something like I am proposing in [this commit](https://github.com/lfbesada/liferay-portal/pull/70/commits/318edb14427f26256bc7a283d1a0d78845211fab).
I have tested it in my local and it seems to work ok in different scenarios: On the default company site or any other site, with or without a localization prefix, and/or with or without a virtual host.
But maybe I am missing relevant scenarios because of poorly knowing the friendly-url components. What do you think about it?
Thanks!
Regards

**Comment by adolfopa** [comment]
@lfbesada I'm totally ok with your changes. I'll close this PR as done then; can you move forward the PR with your additional changes? Thanks!

**Pull request closed without merging**
