### PR TITLE
LPS-107216 Moves error inside the correct section

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Test fixed in https://github.com/liferay-echo/liferay-portal/pull/441

**Comment by david-gutierrez-mesa** [comment]
ci:close

**Pull request closed without merging**
