### PR TITLE
LPS-133735 Modify cases to view header title

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The failure case is a flaky issue. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/104721

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
