### PR TITLE
[TS] LPS-118034

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-118034

From @kevhlee:

> The issue is that the site hierarchy is used to check if a page menu item is selected instead of the menu hierarchy. Thus, I change the logic so that a page menu item is considered selected when one of the following is true:
> 
> - Does the theme display's layout (the current layout) match the given page item's layout?
> - Is one of the Page item's children selected (this includes descendants)?
> 
> Let me know if you have any questions or thoughts.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@ChrisKian, will send after GA5 is build

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
