### PR TITLE
LPS-122343 SF

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
@p2kmgcl Could you please take a look ant JS tests failures?

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Resent with tests fixed here https://github.com/liferay-echo/liferay-portal/pull/2738

**Pull request closed without merging**
