### PR TITLE
LPS-203214 Adds site sitemap configuration

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-203214

Previous PR: https://github.com/liferay-echo/liferay-portal/pull/14727

Resend because of: https://github.com/brianchandotcom/liferay-portal/pull/145383#issuecomment-1862036298

Screenshot from 2023-12-19 09-50-23

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:test:stable

**Comment by lfbesada** [comment]
> Hi @lfbesada, would you mind checking js unit failures? [apps:layout:layout-content-page-editor-web:packageRunTest](https://testray.liferay.com/home/-/testray/case_results/2476437861)

Hi @Tim-Cao

Thanks for looking this!
I have run on my local the tests and those tests are passing OK

image

In addition, this PR adds a new site setting configuration, it has nothing to do with the page editor so these failures can't be related to this PR changes.

Thanks!

**Comment by Tim-Cao** [comment]
Thanks @lfbesada

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/145428

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
