### PR TITLE
LPS-156173 and LPS-156864

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-156173 Add a new util class to handle the SegmentsExperience's related common methods
- LPS-156173 Move from LayoutStructureUtil to SegmentsExperienceUtil
- LPS-156173 Replace usages
- LPS-156173 Receive segmentsExperienceId as a parameter to break the dependency
- LPS-156173 Update usages
- LPS-156173 Move to layout-page-template-api to reuse
- LPS-156173 Add required dependency
- LPS-156173 Adds plid and segmentExperienceId to be able to retrieve LayoutStructure data when submit the form
- LPS-156173 Extract to var
- LPS-156173 Add required dependencies
- LPS-156173 Baseline layout-page-template-api
- LPS-156173 Baseline layout-taglib
- LPS-156864 Adds two methods. Once to retrieve the structure of the layout, and the other one for the specific form.
- LPS-156864 Adds new method that retrieves the link where the user will be forwarded if they have selected URL for the success message
- LPS-156864 Adds new method that retrieves the page where the user will be forwarded if they have selected Page for the success message
- LPS-156864 Adds new method that determines where the user should be forwarded based on the defined configuration
- LPS-156864 If we get the form ID in the session, it means that we must show the success message, so control it accordingly

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Perfect! Thanks! ❤️

**Comment by jkappler** [comment]
ci:test:relevant

**Pull request closed without merging**
