### PR TITLE
LPS-150394

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
cc: @Tim-Cao @sandrodw3

**Comment by ealonso** [comment]
@Tim-Cao @sandrodw3 

I've executed ci:forward by mistake, but it is not going to happen, 😂 or yes who knows

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @sandrodw3, it seems like no failure cases are related to this changes. Feel free to run ci:forward when you think this PR is ready to merge.

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
