### PR TITLE
LPS-123640 auto-scroll upon load when dragging a page

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

Could you please review this PR?

You can find some additional context in PTR-2069.

Thanks in advance

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
Hi @NemethNorbert (cc @dacousalr) 🙂 first of all, thanks a lot for your solution! I have some feedback:

It happened to me that when the autoscroll is done, if the new target element also has children, the autoscroll is triggered again. This can cause a permanent autoscroll til we target an element without children, and I think it could be a little bit confusing. I agree that for Safari it's much better that what we had before (basically it was impossible to do the scroll), but for the rest of browsers, I think the experience gets a little bit more confusing. I would consider applying the solution only to Safari.

Another thing I noticed is this solution allows users to scroll right while they are dragging, but as far as I could test, It's not possible to scroll left again, right?

In my opinion, the ideal solution would be to implement the scroll in Safari in the most similar way to what the other browsers do: when you are on the left or right edge of the container, it scrolls progressively.

What do you think, @NemethNorbert? 🙂

Thanks in advance!

**Comment by NemethNorbert** [comment]
I half-baked another solution
https://github.com/liferay-echo/liferay-portal/pull/3085

**Pull request closed without merging**
