### PR TITLE
LPS-205102 Add 'Permissions' option to the kebab menu under 'View Source' when editing a Web Content

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
To merge after: https://github.com/liferay-echo/liferay-portal/pull/14922#issuecomment-1878688072

## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-205102)

### Changes

Add "Permissions" option to the kebab menu under "View Source" when editing a Web Content when the FF is active.

>[!NOTE]
>You should activate the FF: LPS-198959

## Test scenario 1

1. Go to Content & Data > Web Content.
2. Create a Web Content.
3. Once created go to edit the WC and check the upper-right kebab menu.

## Results

image
image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
Feténs!

**Comment by victorg1991** [comment]
ci:forward:force

**Pull request closed without merging**
