### PR TITLE
LPS-171160 Fix the delete for the Utility Pages

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-171160)

When deleting a utility page, the layout associated with that utility page must also be deleted.

## Proposed solution

Modify the service to use the deleteLayoutUtilityPageEntry with the Layout Utility Page Entry instead of layoutUtilityPageEntryId.

## Test Scenario

1. Go to Design > Fragments and create a new set of fragments.
2. Select any fragment of the default ones and copy it to the New set created before.
3. Go to Site Builder > Pages and go to the Utility Pages tab.
4. Create a new Utility Page and add to it the fragment copied.
5. Publish it, and then delete the utility Page.
6. Go again to Design > Fragments.
7. Open the three dot menu of the fragment you copied and click on "View usages".

## Notes
Step by step video (before the fix):

https://user-images.githubusercontent.com/93203423/207637616-87d15ae6-d710-4089-a9dd-893df8dcbdcd.mov

Test after the fix:

https://user-images.githubusercontent.com/93203423/207637848-f7dd2ec4-b300-49cf-a4ae-c26250a227ba.mov

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Review by lfbesada — APPROVED** [review]
👏

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1327401_7405

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127773

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
