### PR TITLE
LPS-149350 Show common styles even if there are no filterable collections

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward :peepo-mad:

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114777

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
