### PR TITLE
LPS-206284 Apply master page plid when creating an utility page

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Same as [SelectLayoutMasterLayoutVerticalCard.java#L73](https://github.com/liferay/liferay-portal/blob/6ce0b9eb049e99a50285a324a3bd4afd76d340ab/modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/frontend/taglib/clay/servlet/taglib/SelectLayoutMasterLayoutVerticalCard.java#L73) 
or
[SelectDisplayPageMasterLayoutVerticalCard.java#L54
](https://github.com/liferay/liferay-portal/blob/a9c43c6469feeabf4b34ced92493c3cc337f64b1/modules/apps/layout/layout-page-template-admin-web/src/main/java/com/liferay/layout/page/template/admin/web/internal/frontend/taglib/clay/servlet/taglib/SelectDisplayPageMasterLayoutVerticalCard.java#L54)
[selectLayoutPageTemplateEntryDisplayContext.getMasterLayoutPlid()](https://github.com/liferay/liferay-portal/blob/3f610aea9cea2c660cc3aee4b2f0d836dcb66b2e/modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/display/context/SelectLayoutPageTemplateEntryDisplayContext.java#L225) is expecting to have the param masterLayoutPlid in the request

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Thanks! ❤️

**Comment by Tim-Cao** [comment]
ci:report:2488455241

**Comment by Tim-Cao** [comment]
ci:forward:force

**Pull request closed without merging**
