### PR TITLE
LPS-147390 buildLang

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by sandrodw3** [comment]
@Tim-Cao failures seem unrelated, right?

**Comment by victorg1991** [comment]
ci:test:relevant 🍊

**Comment by victorg1991** [comment]
ci:reevaluate:1277401_2041

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reevaluate:1307401_2360

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
