### PR TITLE
LPS-177552 Send vocabularyId

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @sandrodw3, would you mind checking this failure? Thanks
https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/406595//testReport/layout.layout-content-page-editor-web.test.page_editor/common/openItemSelector_uses_selectedItem_returnType_as_type

**Comment by sandrodw3** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
Merged to master and U67

**Pull request closed without merging**
