### PR TITLE
LPS-190564 Test to check that value references are added correctly in contentFields

### PR DESCRIPTION
**Pull request by YurenaC**
[Story](https://liferay.atlassian.net/browse/LPS-190564)

Test added to check that new modifications made in https://liferay.atlassian.net/browse/LPS-190222 reflect properly and no poshy test will be needed

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@YurenaC, I'm getting a lot of failures in StructuredContentResourceTest with your changes, can you please take a look?

**Comment by ealonso** [comment]
see https://github.com/liferay-echo/liferay-portal/pull/13124

**Pull request closed without merging**
