### PR TITLE
LPS-120702 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-120702

This is only for master.

@sandrodw3
@veroglez

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @sandrodw3, your changes cause the following regression issue. The group labels are missing.
GroupLabelMissing
HTML

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by veroglez** [comment]
Hi @Tim-Cao, this https://github.com/liferay-echo/liferay-portal/pull/2376 fixes the group labels

**Comment by veroglez** [comment]
ci:close

**Pull request closed without merging**
