### PR TITLE
[TECHNICAL SUPPORT] LPS-196034 Fragment displays error message when an editable field is created trough configuration

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

[LPS-196034](https://liferay.atlassian.net/browse/LPS-196034),

In case the Fragment is dynamically adding editable fields through configuration when originally there were no editable fields in the Fragment it causes an error.
My solution is to update editableValuesJSONObject with defaultEditableFragmentEntryProcessorJSONObject when we encounter this scenario. Please review my change.

Thanks,

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
Looking good @NemethNorbert :clap:

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward:force

**Pull request closed without merging**
