### PR TITLE
LPS-147394 Add support for Container HTML Tag

### PR DESCRIPTION
**Pull request by lfbesada**
@sandrodw3 
@victorg1991

### CODE REVIEW

**Comment by victorg1991** [comment]
Github doesn't allow me to remove the label for some reason. But this is good to go 👏

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
The test failures are related --> Adding label Changes Required :sad-smile:

**Comment by sandrodw3** [comment]
https://github.com/liferay-echo/liferay-portal/pull/7421

**Pull request closed without merging**
