### PR TITLE
LPS-183219 - Publications slow on Widget pages

### PR DESCRIPTION
**Pull request by david-truong**
**Motivation**
Attempting to resolve customer [issue](https://issues.liferay.com/browse/LPP-48769).

**Proposed Solution**
We discovered the issue was the add button in the toolbar for Web Content Display.  The toolbar will render all the structures available without any limits other than permission checking.  When the structures grew to a large amount, it became a performance issue, especially in a publication where there is limited caching.  In production, the problem is reduced after the initial hit but it is still a bit strange to render all structures available.  The proposed solution is to limit the total to 10 and have a link to the Web Content Admin screen if they do not see the template they wish to use.

**Steps to Verify**
Steps are listed in [LPP ticket](https://issues.liferay.com/browse/LPP-48769).

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by david-truong** [comment]
fixed rebase error

**Comment by david-truong** [comment]
@ealonso we noticed a similar problem with this line of code: https://github.com/liferay/liferay-portal/blob/530250f9edc7dc38571bf56b99e67275550b7d3e/modules/apps/journal/journal-web/src/main/java/com/liferay/journal/web/internal/display/context/JournalViewMoreMenuItemsDisplayContext.java#L91

Is it possible for us to only get the current page results instead of the full list each time?

**Comment by ealonso** [comment]
@david-truong please see: https://github.com/liferay-echo/liferay-portal/pull/12023.
I've modified a little bit your solution and apply it also to View More Menu Items

**Comment by david-truong** [comment]
Thank you!

**Pull request closed without merging**
