### PR TITLE
[TS] LPS-171901 - reindex journals related to an structure filtering by groupId

### PR DESCRIPTION
**Pull request by jvelalr**
Motivation
=======
This PR try to fix the problem mentioned in the ticket.
[Link to task](https://issues.liferay.com/browse/LPS-171901)

Whenever an structure is update, journal articles related to are re-indexed, but the indexer doesn't filter journals by groupId properly. It makes when an structure is update in an staging site, live journals articles are also re-indexed.

Proposed Solution
========
To modify the way ActionableDynamicQuery exectuted in the JournalArticleDDMStructureIndexer search for results filtering by groupId.

Steps to Verify
========
1. Create Site A
2. Create structure stA
3. Export site A
4. Create Site B
5. import site A into site B
6. Create a journal from site B with stA
7. Define com.liferay.portal.search.elasticsearch7 log level to ALL
8. Go to site A, edit the stA and save.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @jvelalr
Thank you very much for the fix! ❤️ 
The root problem that causes this bug is that the information in the article that allows us to determine its structure is the StructureKey but this is not a unique id. This causes that, if this key is duplicated, we will not be able to reliably know which structure the article corresponds to.
This is what happens when we import into a site a structure that comes from another site in the same installation, in this scenario, the structure created duplicates the StructureKey.
A solution like the one you propose is not viable since an article may be using structures from Global, from an asset library, or even from an ancestor site.
The definitive solution will imply a modification of the data that makes it possible to unambiguously identify which structure an article belongs to and vice versa (which articles belong to a structure).
There are other bugs with the same cause, for example, https://issues.liferay.com/browse/LPS-172451
Could you please create a Behavior Clarification PTR to address this issue?
Thank you very much!
Regards

**Comment by jvelalr** [comment]
Thanks you,
We create yesterday the [PTR-3619](https://issues.liferay.com/browse/PTR-3619)

Regards

**Pull request closed without merging**
