### PR TITLE
LPS-169146 The fragment inside fragment composition is not counted

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to task](https://issues.liferay.com/browse/LPS-169146)

Usage count for the fragment is not correctly reflected in the card. It shows the usage per layout, not the individual usage

## Change summary:

* Use method to retrieve individual usage count for the fragment, not by layout

## Test Scenario

* Create a fragment
* Add it several times to a page, and then to another page
* The label for usages should reflect the individual usages

## Additional notes

* Tests are not included in the PR, will be added most probably through poshi tests
* Changes also apply to global fragments, not site fragments

usages

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
Hi @jkappler! Could you please double-check the failures on the modules-compile? They are passing on upstream and failing on this PR. Could be related but I don't know how to test it :3

**Comment by jkappler** [comment]
they don't seem related @ozysouza, will run tests again. Thanks for checking!

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
