### PR TITLE
LPS-148426 Avoid potential NPEs (they can arise in site initializers since we don't have the preferences persisted at that moment)

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1337401_1286

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114360

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
