### PR TITLE
LPS-21174 Restricted Pages functional tests

### PR DESCRIPTION
**Pull request by veroglez**
Waiting for the following PRs:

- https://github.com/liferay-echo/liferay-portal/pull/15405
- https://github.com/brianchandotcom/liferay-portal/pull/148428

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
ci:test:playwright

**Comment by veroglez** [comment]
ci:test:playwright

**Comment by veroglez** [comment]
ci:test:playwright

**Comment by veroglez** [comment]
ci:stop

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/148556

**Pull request closed without merging**
