### PR TITLE
LPS-147252, LPS-147253, LPS-146976 | master

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-147252
https://issues.liferay.com/browse/LPS-147253
https://issues.liferay.com/browse/LPS-146976

@Tim-Cao could you please review that I have removed correctly the feature flag for testing? Thanks!

cc @david-gutierrez-mesa
cc @ruben-pulido
cc @sandrodw3

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @lfbesada, I will try to finish test scenarios and manual testing based on this PR today.

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7414

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
