### PR TITLE
LPS-161817 -  	Child content page of a Site created from a Site Template cannot be viewed or edited

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @lfbesada

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1337401_2169

**Comment by lfbesada** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:reevaluate:1347401_2705

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
The failures seems to be unrelated to this PR.

**Comment by ozysouza** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
@ozysouza - This should be safe to forward, it seems related to this error:
https://issues.liferay.com/browse/LPS-158474

**Comment by ozysouza** [comment]
> @ozysouza - This should be safe to forward, it seems related to this error: https://issues.liferay.com/browse/LPS-158474

Okay, Thanks @michaelhashimoto!

**Comment by ozysouza** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/122443

**Pull request closed without merging**
