### PR TITLE
[TS] LPS-182423 Keep the parentGroupId parameter

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
Site initialization does not keep the parentGroupId param from the initial request, so a Custom Site Template can't be used to create a child site.
https://issues.liferay.com/browse/LPS-182423

Proposed Solution
========
SelectSiteInitializerDisplayContext must keep the parentGroupId  for its portletURL, like how [SiteAdminManagementToolbarDisplayContext](https://github.com/liferay/liferay-portal/blob/master/modules/apps/site/site-admin-web/src/main/java/com/liferay/site/admin/web/internal/display/context/SiteAdminManagementToolbarDisplayContext.java#L125) defines it

Steps to Verify
========
1. Go to Control Panel > Sites > Site Templates
2. Create a Site Template
3. Go to Control Panel > Sites > Sites
4. Create a child site for the Liferay DXP site using the Site Template
5. Go to Control Panel > Sites > Sites

**Expected behavior:** Child site should be created as a child site for the Liferay DXP site
**Actual behavior:** Child site gets created on the same level as the Liferay DXP site

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
