### PR TITLE
LPS-191353 Browse to the generic error page if a user tries to discard a draft locked by another user

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-191353

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
I have cherry-picked [this commit](https://github.com/brianchandotcom/liferay-portal/commit/3cfe94341cbe091ac918a3fcc99a40e0851acccb) from Brian's repo in order to pass CI

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
