### PR TITLE
[TS] LPS-139659 Failed upgrade process for module com.liferay.layout.page.template.internal.upgrade.v2_1_0

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
LPS-139659 Use default user when the user does not exist like other places in the portal (check LPS-88730). I have decided not to log this because the customer does not need to know that an old object does not have a valid user right now and the new object is created properly with an existing user.

For reference, I used this as an example: https://github.com/brianchandotcom/liferay-portal/pull/67644

My commit is: https://github.com/liferay-echo/liferay-portal/pull/5952/commits/14499c6023fe8f2128020a0a21c9635994579462

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/5955

**Pull request closed without merging**
