### PR TITLE
[TS] LPS-136518

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

Can you please review?
https://issues.liferay.com/browse/LPS-136518

Thanks,
Balázs

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
hmm, com.liferay.document.library.info.display.contributor.test.FileEntryInfoDisplayContributorTest.testDisplayPageURL might be related failure, I'll investigate

**Review by lfbesada — CHANGES_REQUESTED** [review]
Hi @balazssk 

Thanks for the Pull Request!

I fear, as you mentioned, one of the failed tests seems related to PR, sure you have it in mind.

There is a merge conflict too. It has been a lot of coincidence, but just yesterday were merged changes that collide with yours, please, could you take a look at these commits?

https://github.com/liferay/liferay-portal/commit/a1f1792941144164eb5d941a2a7ba6ef8be9d312
https://github.com/liferay/liferay-portal/commit/2d2b5b7b78eb8b2d1366a8f2799b36819b227379
https://github.com/liferay/liferay-portal/commit/6b3bb805454ba6dd92e8f36a0d9132bfe8099c5f
https://github.com/liferay/liferay-portal/commit/eaf2cb6924bafe8b4770e5ec4383fd7c53292dcb

This is a solution to make the URLs of the display pages localize according to portal configuration. Could you merge these changes in your PR?

I have been testing the PR and, in the described bug use case, it works great! 

Unfortunately, it causes an error if the URL is localized, adding a double slash in the URL, for example: "http://localhost:8080/en//w/test". I think it could be caused by using the I18N_Path attribute and I think this could be solved by keeping the path calculation incorporating the changes in the above commits.

On the other hand, I am afraid that the logic of the localization should not be extracted from the provider. If the logic of the localization of the provider is extracted, others that use the provider would not localize properly their URLs, for example, AssetCategoryAssetDisplayPageFriendlyURLResolver, CProductAssetDisplayPageFriendlyURLResolver, etc.

Also, the provider must clone receiver themeDisplay before changing it, otherwise, ThemeDisplay changes could affect the invoker.

Maybe you could take into consideration to remain the localization logic in the provider and add to clonedThemeDisplay whatever needs to proper call to getCanonicalURL.

Thanks!

Regards

**Comment by balazssk** [comment]
Thanks for the feedback @lfbesada

**Pull request closed without merging**
