### PR TITLE
LPS-LPS-166045 | LPS-167518 - Improvements in collection view

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Add views to Collections](https://issues.liferay.com/browse/LPS-167518)
[Add usage information to list view](https://issues.liferay.com/browse/LPS-167634)

Echo Team has been trying to improve the user experience across all its features, being most recent one is Collections. This includes standardizing the view with other existing views, and improving the visibility of information to the user

## Change summary:

* Adapt collection view so that it also has a vertical cards and table view
* Adapt list and table view so that they now have the usages count for the collection
* Change icon for dynamic views so that it's a bolt instead of list
* Remove collection type and date from list view so that it resembles vertical card info

## Test Scenario

* Navigate to collection
* Add several collections (manual and dynamic)
* The user will be able to change view types (list, descriptive and card)

collections

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
Please see https://github.com/liferay-echo/liferay-portal/pull/10221

**Pull request closed without merging**
