### PR TITLE
[7.4.x only] LPS-123683 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-123683

This is only for master.

@victorg1991
@p2kmgcl

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, I just investigated deeply, there is another regression issue. When change the default site language without setting up localized site name. The following error is shown Site name is required for the default language.

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/3079

**Pull request closed without merging**
