### PR TITLE
LPS-132151

### PR DESCRIPTION
**Pull request by manuelRives**

### CODE REVIEW

**Comment by manuelRives** [comment]
ci:test:sf

**Comment by manuelRives** [comment]
ci:test:relevant

**Comment by manuelRives** [comment]
ci:test:stable

**Comment by ealonso** [comment]
Hey @manuelRives,

I think you need configure your github account since the commands "ci:test:sf" and "ci:test:relevant" are not working at all.

Regarding the commands you should use, it should be enough if you put only "ci:test:sf" and "ci:test:relevant", the other command is not necessary.

Regards,
Eudaldo.

**Comment by manuelRives** [comment]
Hi @ealonso,

Ok, I will check what is happening with those commands. Thanks by the advise!

Regards

**Comment by victorg1991** [comment]
Hey @manuelRives 

Would you mind opening a PTR for discussing about this solution? This way we can analyse the use cases that are failing with the current approach and our product manager can also chime in and agree on a possible solution :) 

Thanks!!

I'm closing this for now, but if we end up deciding that this is the best approach we can reopen this later

**Pull request closed without merging**
