### PR TITLE
LPS-154506 Respect empty values

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
https://github.com/liferay-echo/liferay-portal/pull/8767/files#diff-3b9eb87c26495eaf08a3994b33f2ceb16eac7f3825bc037d2bb570a865474276R247
@jkappler  Something missing?
https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/util/Validator.java#L914-L924

**Comment by jkappler** [comment]
Will check it out, thanks @Tim-Cao!

**Pull request closed without merging**
