### PR TITLE
LPS-146824 Remove Feature Flag for LPS-141410

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, there is a regression issue. Would you mind having a look at?
The Margin Left and Margin Right should be disabled when Container with Fixed Width. The new spacing styles don't have this status, even though the defined Margin Left and Margin Right won't apply to Container.

**Comment by Tim-Cao** [comment]
@p2kmgcl Poshi changes see https://github.com/liferay-echo/liferay-portal/pull/7709

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
