### PR TITLE
LPS-147083 Migrate Feeds Type To Asset Categories 

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-147083

Previous PR: https://github.com/brianchandotcom/liferay-portal/pull/130771

See: https://github.com/brianchandotcom/liferay-portal/pull/130771#issuecomment-1445036146

cc: @georgel-pop-lr @achaparro

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1397401_3274

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130912

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
