### PR TITLE
[TS] LPS-161717 Additional commit

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This an additional commit to put the service call in a transaction callback again.

Additional information can be found in LPS-161717's comments.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by dacousalr** [comment]
ci:stop

**Comment by dacousalr** [comment]
Force push to include the other calls into the transaction callback to be executed at the end of the main transaction as well.

**Comment by ozysouza** [comment]
Just started revewing :)

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/123625

**Pull request closed without merging**
