### PR TITLE
LPS-200384 Reduce screen movement when using the fragment

### PR DESCRIPTION
**Pull request by p2kmgcl**
Instead of using "block:center", we have updated it to nearest, which avoid scrolling if the element is already visible on the screen.

Moreover we now avoid scrolling when user interacts with the fragment using the mouse.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:forward

**Comment by liulukiwi** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143177

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
