### PR TITLE
[TS] LPS-148896 | Freemarker variables are not substituted in fragments with lfr-editable tags or data-lfr-editable-type attributes

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi team @liferay-echo,

This is a solution for [LPS-148896](https://issues.liferay.com/browse/LPS-148896). Please see reproducing steps there and linked PTR.

Please let me know if you have any questions. 

Regards.

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ricardocousolr** [comment]
Thanks @ruben-pulido !

**Pull request closed without merging**
