### PR TITLE
LPS-113883 - Duplicate Section element to create new Container element (backend)

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @p2kmgcl

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
I think this is failing because of the container "type" change, I'm going to run this test locally to be sure

**Comment by p2kmgcl** [comment]
Ok, this is the issue: https://github.com/liferay-echo/liferay-portal/pull/1062/commits/b7efbe0ebfdcdd754b4685538b139c5f2cef82a9#diff-a5d5ca5302220938bc22f4da9e462eedR228

We've changed the default value of container type from fixed to fluid, what apparently breaks some poshi test that are expecting "fixed" to be the default value. Maybe we should keep "fixed" as default until we can enable our feature flag :shrug:

**Comment by p2kmgcl** [comment]
I added this comment to the ff enable task on jira https://issues.liferay.com/browse/LPS-113886?focusedCommentId=2178187&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2178187

**Comment by p2kmgcl** [comment]
Hey @Tim-Cao, we are updating section default type to "fluid" and all default paddings to "0" instead of "3", could you update this poshi test? ContentPages#ChangeLayoutElementProperties

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/1085

**Comment by p2kmgcl** [comment]
ci:close

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/1120

**Pull request closed without merging**
