### PR TITLE
LPS-185235 Add warning message when the structure key changes

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-185235

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
cc: @sandrodw3 ❤️

**Comment by jkappler** [comment]
Looks good from my side @lfbesada 😍

**Comment by lfbesada** [comment]
@jkappler @claraizquierdo my first react component 😍 💪 I feel good 🎵 I feel front 🎵 

Thanks for the review ❤️

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
