### PR TITLE
LPS-164375 Take LayoutCrawlerClientConfiguration into account when deciding on hostName

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
[LPS-164375](https://issues.liferay.com/browse/LPS-164375)
In LayoutCrawlerImpl, by returning when inetAddress is null we disregard any potential configuration present in LayoutCrawlerClientConfiguration.

Proposed Solution
========
The original code only uses inetAddress to set hostNames. LayoutCrawlerClientConfiguration can also have a value for this, so we can use it when the configuration is enabled

Steps to Verify
========
Sadly, I'm not sure how to reproduce this, I've created this pull based on assuming intent of the original [LPS-152505](https://issues.liferay.com/browse/LPS-152505)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/9784

**Comment by balazssk** [comment]
Cheers @ealonso ,
Just found out that `@Nullable` caused the compile error as well

**Pull request closed without merging**
