### PR TITLE
LPS-143395 Added permission check for group search results

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-143395

/cc @javalosjr96 @mbowerman

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:forward

**Comment by javalosjr96** [comment]
Hi @lfbesada,
you need the userId in the parameters incase the customer has ComplexSQL queries enabled in the system properties.

**Comment by lfbesada** [comment]
> Hi @lfbesada, you need the userId in the parameters incase the customer has ComplexSQL queries enabled in the system properties.

Hi @javalosjr96,

Thanks for the tip! Please, could you tell me where can I enable this option?

Thanks!

Regards

**Comment by javalosjr96** [comment]
@lfbesada 
Add:
`groups.complex.sql.class.names=com.liferay.portal.kernel.model.User,com.liferay.portal.kernel.model.Organization,com.liferay.portal.kernel.model.UserGroup,com.liferay.portal.kernel.model.Company`

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
