### PR TITLE
[TS] LPS-131848

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-131848

When setting permissions at the web content level, Liferay's permission checking will assume the owner of the latest version has OWNER access when performing some permission checks.  This can lead to access the user shouldn't have, if they aren't the original owner.

Please let me know if you have any questions, thanks!

CCing @lipusz since this has some security implications

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @ChrisKian,

Could you please open a PTR for it? since you are changing the behavior that we have in portal for many versions and we need to take a look at it. It can fix the problem for your customer but it can cause problems in other customers and we need to discuss if it is the correct fix or not.

Regards,
Eudaldo

**Comment by ChrisKian** [comment]
Hi @ealonso,
I have added an additional commit to this PR as well as created [PTR-2430](https://issues.liferay.com/browse/PTR-2430) to investigate the implications of the changed behavior.

Please let me know if you have any questions, thanks!

**Comment by ealonso** [comment]
Closing this one, see the comments https://issues.liferay.com/browse/PTR-2430

**Pull request closed without merging**
