### PR TITLE
LPS-128044 isCopyLayout thead local values should be false by default, it should only be true when setting it explicitly

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
cc @ruben-pulido

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1127401_4304

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
