### PR TITLE
LPS-195038 View Metrics button in Content Dashboard should appear regardless of current site

### PR DESCRIPTION
**Pull request by jkappler**
https://liferay.atlassian.net/browse/LPS-195038

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Tests don't seem related to the changes. They are related to test bundle already exists

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
