### PR TITLE
[TS] LPS-141460

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This is a followup to fix the regression bug detected in LPS-142617.

Could you please review it?

Thanks in advance

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Hi @dacousalr,
It works great!
Thanks!
Regards

**Comment by dacousalr** [comment]
Thanks to you for your prompt review, @lfbesada!

**Comment by lfbesada** [comment]
ci:reevaluate:1097401_5178

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
