### PR TITLE
LPD-34442 Add copy action CopyItemsMVCActionCommand.java

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
For more details, please see epic https://liferay.atlassian.net/browse/LPD-25482

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by ealonso** [comment]
first part send here: https://github.com/liferay-echo/liferay-portal/pull/16174

**Comment by ealonso** [comment]
last part: https://github.com/liferay-echo/liferay-portal/pull/16182

**Pull request closed without merging**
