### PR TITLE
LPS-115369 Wrap journal template error to avoid overflow

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/1058

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
