### PR TITLE
LPS-85145 Always show product menu close icon

### PR DESCRIPTION
**Pull request by p2kmgcl**
As discussed in PEDS channel (see https://liferay.slack.com/archives/C049XG98GQL/p1671438056481869). We are going to replace existing "Skip to *" links with a real focus move when sidebar panels are opened.

Moreover, having a consistent close button fits Lexicon's design principles, so we are using it as a focus target then the sidebar is opened.

Because of the loading time of the sidebar (which is very inconsistent), checking if there is any close button in a 200ms interval, until a 3s timeout is reached. I chose this instead of a MutationObserver because it is simpler, and there are some cases where the sidebar content it is already loaded and the observer finds nothing.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
I'm gonna run tests to put some pressure on this :smirk:

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
https://www.youtube.com/watch?v=Y8i1Ddj1Sw8

**Comment by victorg1991** [comment]
resent here: https://github.com/liferay-echo/liferay-portal/pull/10687

**Pull request closed without merging**
