### PR TITLE
LPS-140784 style book preview fixes

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-140784

Solving https://github.com/brianchandotcom/liferay-portal/pull/109286#issuecomment-954915076

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/6312

**Pull request closed without merging**
