### PR TITLE
LPS-135483 Improve Collection Display fragment performance

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
Dear frontend friend:
- These changes are saving me around 50% of time when following the steps described in the ticket. Could you please give it a try and check if you also note that improvement? 🚀
- I removed the `toControlsId` from `selectPanels`, I think it's not necessary now, because panels should be the same for all collection items, could you have a look at it? 😄

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/5790

**Pull request closed without merging**
