### PR TITLE
LPS-111546 Rename Web Content MVC actions to follow the new pattern

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by jpince** [comment]
@vicnate5 a lot of errors like these. Known issue? 
```
[java] 2020-04-06 13:42:45.174 WARN  [main][UpgradeProcess:389] Attempting to upgrade table AssetCategory by recreating the table due to: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
...
[java] 2020-04-06 13:42:46.150 WARN  [main][UpgradeProcess:389] Attempting to upgrade table RatingsStats by recreating the table due to: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
...
[java] 2020-04-06 13:43:23.166 WARN  [main][UpgradeProcess:389] Attempting to upgrade table KaleoAction by recreating the table due to: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
```

And I'm not sure what actually failed the upgrade batch. Maybe this?
```
Error response from daemon: endpoint cloud-10-0-13-99.lax.liferay.com_mysql not found
```

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
@jpince Not a known issue, but seems to be not related, testing again.

**Comment by vicnate5** [comment]
@jpince Here is the ticket for the upgrade WARNs you brought up https://issues.liferay.com/browse/LPS-110703

**Pull request closed without merging**
