### PR TITLE
LPS-114622 Removes recent sites tab from my sites, keep the class for the moment

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @Tim-Cao @liulukiwi,

As part of the changes on Global Menu we decide to removes the Recent tab of, here is where the Recent tab is located:

Home_-_Liferay

Now we should use the Global Menu to do that.

Could you please take fix the broken tests?

Regards,
Eudaldo.

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
I will fix tests tomorrow.

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
