### PR TITLE
LPS-121955 Replace user-card-v2 with user-card in site-teams-web

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
cc @julien @markocikos

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Review by julien — APPROVED** [review]

**Comment by ealonso** [comment]
ci:forward

**Comment by victorg1991** [comment]
I think that this may be affected by: https://github.com/liferay-echo/liferay-portal/pull/2965#issuecomment-731988164

**Pull request closed without merging**
