### PR TITLE
LPS-125805 Deprecate old supported field types constants

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
Hi @ealonso, the failure cases in ci:test:echo are known issues not related to changes in PR.
See https://testray.liferay.com/home/-/testray/case_results/index?testrayTeamId=1310700641&testrayBuildId=1418274036&testrayRunId=1418274039&cur=1&delta=20
Could we move forward?

**Comment by Tim-Cao** [comment]
ci:test:sf

**Pull request closed without merging**
