### PR TITLE
 LPS-188311 Use clay:vertical-nav for configuration-admin-web #12913 

### PR DESCRIPTION
**Pull request by jkappler**
Motivation
=======
The motivation behind this ticket is to use the clay:vertical-nav tag in order to standarize the usage of vertical navigation elements.
https://liferay.atlassian.net/browse/LPS-188311

Proposed Solution
========
The proposed solution consists in creating a list of verticalNavItemList and pass it to the clay:vertical-nav tag besides of some style adjustments.

Steps to Verify
========
1. Go to ControlPanel -> System Settings -> Select one of the settings.
2. Check that the left vertical navigation panel looks and works fine.

Screenshot 2023-07-19 at 14 54 04

@Stephy6

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@Stephy6

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/12927

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
