### PR TITLE
LPS-139999 Add useControlledState

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/6042

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
