### PR TITLE
LPS-138306 Add data-tooltip-align bottom to button

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:reevaluate:1297401_130

**Comment by Tim-Cao** [comment]
The semantic versioning is unrelated to this PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/106540

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
