### PR TITLE
LPS-142961 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-142961

This is only for master.

@victorg1991
@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
Hey @Tim-Cao, Eudaldo is going to adapt the collections part too, thanks for the heads up!

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/7049

**Pull request closed without merging**
