### PR TITLE
LPS-159247

### PR DESCRIPTION
**Pull request by MirnaGama**
## Motivation:
Adding on the fly an existing category causes buttons to be duplicated
https://issues.liferay.com/browse/LPS-159247

## Steps to verify: 
 1. Create a new vocabulary voc1, and create a category cat1 in it.
 2. Put a Wiki widget on a page.
 3. Click on the Edit icon (pen) in the upper right part (so as if you would edit any given wiki page)
 4. In the Categorization section click on Select next to voc1.
 5. In the resulting popup, click the + button (to add on the fly a new category to that vocabulary)

 - Type in cat1 and click 'Save and Add New One' button. (so by accident you entered here the name of an already existing category)
 *Result*: The footer buttons are duplicated and initial modal buttons are displayed again
 
- Click 'Save and Add New One' or 'Save' button without filling the required input 
 *Result*: The footer buttons are duplicated and Modal Title is also reset

### Proposed Solution:
- Check if the SessionErrors object is empty so the edit/add page buttons are not displayed if an exception occurs 
- Reorganize the function that removes the "hide" attribute on the initial modal buttons so it can be triggered after the action is called
- Validation on ItemSelectorAddCategory to check if a required input is empty so the form can not be submitted

## Commits included:
- LPS-159247 Fixes initial modal buttons appearing when a footer button is clicked before the action is finished
- LPS-159247 Insert validation method on ItemSelectorAddCategory to check when a required field is empty so the form is not submitted
-  LPS-159247 Add another condition so the buttons from the edit category form do not appear in add category form modal
- LPS-159247 SF

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @MirnaGama 

Thanks for your PR! I've seen that is solves the issue, but unfortunately it also hides the buttons in the category administration so no new categories can be created :(

In any case I think we can simplify this solution a bit:

* For displaying the default buttons and hiding the custom ones, I think we can use the dispose method that is defined in the bottom of the file. This method is called when the view is destroyed, so in that case we should show the cancel/done buttons and hide the cancel/saveAndAdd/save. Can you try that? the required check should not be needed with that :) 
* In order to not show the buttons when there is a failure, the problem is that [we are checking the availability of the "itemSelectorEventName" parameter](https://github.com/liferay/liferay-portal/blob/4af8937052647e8f1913d3e8c8702f994252f4cb/modules/apps/asset/asset-categories-admin-web/src/main/java/com/liferay/asset/categories/admin/web/internal/display/context/AssetCategoriesDisplayContext.java#L752-L754) . Apart from that another thing that allow us to recognize this is with the window state, I think we can get the windowState and check if that is different from popup :) 

Let me know if you have further question or you need some extra help

Thanks!!

**Comment by MirnaGama** [comment]
Hi @victorg1991 !
It's done ! Please have a look, I'll be waiting for your feedback. :grinning:

Thanks in advance !

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
Hi @MirnaGama 🥰
Victor is out of office, so I'm taking care of this. I was testing your new changes and when creating a new category successfully from the widget, the buttons used to create categories become visible in the main view:

image

Could you please take a look?

**Comment by MirnaGama** [comment]
Hi @sandrodw3 
Thanks for pointing that out, now I believe it's working fine. I'll be waiting for your feedback 😀 

Thanks in advance !

**Comment by sandrodw3** [comment]
> Hi @sandrodw3 Thanks for pointing that out, now I believe it's working fine. I'll be waiting for your feedback 😀
> 
> Thanks in advance !

Hi @MirnaGama, thanks for your changes 🥰 @victorg1991 will take a look as he is back already.

**Comment by victorg1991** [comment]
Hey @MirnaGama This is working fine!! 👏 

Just a couple of thing I think we should take into account to make it perfect:

* Could you redo the commits to include only the latest changes? This would make the history cleaner, since the changes done in the first commits are removed in the latter ones
* Can you move the `LiferayWindowState.isPopUp(request)` to the `isItemSelector` method? This check is part of the logic that decide whether the view is rendered in an itemSelector 

After that, everything will be ready to go :)

Thanks!!

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by MirnaGama** [comment]
Hi guys ! @sandrodw3 , @victorg1991 
It's done, please have a look 😄 

Thanks in advance !

**Comment by victorg1991** [comment]
Nice, many thanks @MirnaGama 👏  This is ready to go

**Comment by victorg1991** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:forward

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Whether this last attempt doesn't work I will manually send it.

**Comment by ozysouza** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/122050

**Comment by ozysouza** [comment]
ci:close

**Pull request closed without merging**
