### PR TITLE
LPS-140253 Hide Private Pages

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @jkappler , Could you resolve the conflict? Thanks

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:test:bundle

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:bundle:norebase

**Comment by Tim-Cao** [comment]
ci:test:echo:norebase

**Comment by Tim-Cao** [comment]
No regression issues found according to [ci:test:echo](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1638167421519&testrayRunIdA=1584559116&testrayRunIdB=1584551417)

**Comment by jkappler** [comment]
thanks @Tim-Cao and @liulukiwi!

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
SF issue is not related to this PR.

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The sf failure is unrelated to this PR. I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/110480

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
