### PR TITLE
LPS-156832 Search Bar Suggestions shows HTML as plain text

### PR DESCRIPTION
**Pull request by thektan**
https://issues.liferay.com/browse/LPS-156832

## Motivation
In the Search Bar, we're rendering the page summary and the output would be something like `<strong>Page:</strong> <script>...</script>`. Attempting to render the `<strong>` tags would output: `Page: `.

## Proposed Solution
I escaped the page title in `layout-admin-web` `LayoutAssetRenderer#getSummary` method to be able to render the `<strong>` tags that `LayoutAssetRenderer#getSummary` was adding without rendering other potential tags in a page title. 29b52269fb3bc3ac5de16c8d935f275a5deca80b

Ran `ci:test:sf` and `ci:test:relevant` at https://github.com/liferay-search/liferay-portal/pull/476
[✔️ ci:test:sf - 1 out of 1 jobs passed in 4 minutes](https://github.com/liferay-search/liferay-portal/pull/476#issuecomment-1165041921)
[✔️ ci:test:stable - 27 out of 27 jobs passed
✔️ ci:test:relevant - 182 out of 188 jobs passed in 1 hour 26 minutes](https://github.com/liferay-search/liferay-portal/pull/476#issuecomment-1165102247)

## Screenshots
Here's a screenshot of our use case in the Search Bar where we're rendering the summary with the changes in the PR applied. 

175435902-3d69af9a-bda7-402c-81d7-1ab853051b6c

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
Hey @thektan 

I just checked and it seems that the getSummary has several implementations, so we should make sure that all of those are escaped, otherwise we can introduce some XSS vulnerabilities. For example here: https://github.com/liferay/liferay-portal/blob/f6b43a66e2d979fda74c1f02d28f101c7f1def84/modules/apps/bookmarks/bookmarks-web/src/main/java/com/liferay/bookmarks/web/internal/asset/model/BookmarksFolderAssetRenderer.java#L115

Not sure if those summary are going to show up in the search or only appear for pages, is possible to display that summary?

**Comment by thektan** [comment]
Thanks for taking a look at this @victorg1991! 

I had a conversation with @lipusz and they brought up how escaping should happen on the view layers instead of the asset renderer classes. This also made me realize how some places will already escape the summary so a double escape could happen. ([For example in asset-taglib](https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-taglib/src/main/resources/META-INF/resources/asset_display/preview.jsp#L56))

I can't think of a scenario where we'd be able to render these `<strong>` tags without rendering potential tags in a page title. I also couldn't find any other places where this `Page: ` pattern would be rendered, if you had any ideas where this could be displayed.

What are your thoughts on these possible solutions instead: 
1. Remove the `<strong>` tags from `LayoutAssetRenderer#getSummary`
2. Remove the entire `<strong>Page:</strong>` string (and if a place that was using it needed the `Page :` prefix, they could conditionally render `<strong>Page:</strong>`.

**Comment by thektan** [comment]
@victorg1991 
> Not sure if those summary are going to show up in the search or only appear for pages, is possible to display that summary?

Summaries will display for all asset types.

Here's a screenshot of a blog asset and page asset from master.

Screen Shot 2022-06-27 at 6 23 34 PM

**Comment by victorg1991** [comment]
> Thanks for taking a look at this @victorg1991!
> 
> I had a conversation with @lipusz and they brought up how escaping should happen on the view layers instead of the asset renderer classes. This also made me realize how some places will already escape the summary so a double escape could happen. ([For example in asset-taglib](https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-taglib/src/main/resources/META-INF/resources/asset_display/preview.jsp#L56))
> 
> I can't think of a scenario where we'd be able to render these <strong> tags without rendering potential tags in a page title. I also couldn't find any other places where this Page: pattern would be rendered, if you had any ideas where this could be displayed.
> 
> What are your thoughts on these possible solutions instead:
> 
> Remove the <strong> tags from LayoutAssetRenderer#getSummary
> Remove the entire <strong>Page:</strong> string (and if a place that was using it needed the Page : prefix, they could conditionally render <strong>Page:</strong>.

Thanks for the additional information!

Based on that I would go for the 1st option, since we leave the context "page" and removing the strong doesn't seems super bad, it only changes the appearance slightly :)

**Comment by thektan** [comment]
Thanks, @victorg1991! I agree with that as well. It's a more minimal change. 

I updated the PR which now only removes the `<strong>` tags.

**Comment by victorg1991** [comment]
Hey @thektan I believe we also need to remove the escaping right? As this should be done in the view :)

**Comment by thektan** [comment]
ci:test:sf

**Comment by thektan** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Thanks @thektan LGTM :)

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
