### PR TITLE
LPS-128603 buildLang

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/3925

**Pull request closed without merging**
