### PR TITLE
LPS-171156 Cannot select date fields with Date Editable Fragment in Collection Display

### PR DESCRIPTION
**Pull request by DiegoHu97**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1387401_5334

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Hi @DiegoHu97 ,  wrong date for mapped modified date, could you take a look?

Here are the steps:
1. Add a web content
2. Get its modified date via view history or database
3. Add a Collection Display to page and Select Recent Content Collection Providers
4. Add a Heading to Collection Display and Map Modified Date of collection items to editable field 

Actual result:
The time keeps at 12:00 AM, in my case, it displays 12/21/22 12:00 AM while the actual modified date is 12/21/22 7:11 AM.

**Comment by DiegoHu97** [comment]
@liulukiwi taking a look, thanks!

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
