### PR TITLE
LPS-118310 prompt the login if the guest does not have view permission for visiting an asset via its friendlyURL

### PR DESCRIPTION
**Pull request by jcampoy**

### CODE REVIEW

**Comment by jcampoy** [comment]
cc @marianoalvarosaiz

**Comment by jcampoy** [comment]
ci:test

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
ci:close

**Comment by pavel-savinov** [comment]
Forwarded to https://github.com/jkappler/liferay-portal/pull/881

**Pull request closed without merging**
