### PR TITLE
LPS-152792 fix commit message

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-152792

See: https://github.com/brianchandotcom/liferay-portal/pull/116986#issuecomment-1118684274

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @lfbesada, would you mind rebasing on master?

**Comment by lfbesada** [comment]
Hi @Tim-Cao 
Thanks for your help! 🥰 
I think that I can't rebase on master by now because the commit I am reverting with this pull is not in master yet 🤔 
This pull request is just reverting and recommitting the same commit just changing the message. Could it be the reason for the CI issue? This pull request actually doesn't have any change...
Regards

**Pull request closed without merging**
