### PR TITLE
[TS] LPS-195736 layout-impl: the mode should be search

### PR DESCRIPTION
**Pull request by joshuacords**
https://liferay.atlassian.net/browse/LPS-195736

Hi team,

The layout rendering is really too complicated for me to really understand, so check how this works carefully. From my debugging I found that the [_mode initialized here](https://github.com/liferay/liferay-portal/blob/6f2ea80810c5bf5fb239d35aaaed97e1f1589df4/modules/apps/layout/layout-taglib/src/main/java/com/liferay/layout/taglib/servlet/taglib/RenderLayoutStructureTag.java#L96-L98) controls whether or not [the fragment will be rendered here](https://github.com/liferay/liferay-portal/blob/beddd7cb0a41f5f9e1448d95c1a5f69e43668547/modules/apps/layout/layout-taglib/src/main/java/com/liferay/layout/taglib/servlet/taglib/renderer/LayoutStructureRenderer.java#L1171-L1177), and the mode is initially [set by the LayoutContentProviderImpl here](https://github.com/liferay/liferay-portal/blob/5ea6cab6b3f7368e241195e8cdcaf36602f3b804/modules/apps/layout/layout-impl/src/main/java/com/liferay/layout/internal/content/LayoutContentProviderImpl.java#L95-L99). If LayoutContentProvider.getLayoutContent is just used for indexing this should work fine, but if not I wouldn't know how else to change this behavior.

**Reproduction Steps**

1. Create a new fragment with the following code:`<lfr-drop-zone></lfr-drop-zone>`
2. Create a new page
3. Drag the fragment onto it
4. Drag an HTML fragment onto the fragment's drop zone
5. Set the content of the HTML field to xxxxxxxxxx
6. Click on the HTML fragment > right menu's Advanced tab > check Hide from Site Search Results
7. Publish the page
8. Search for xxxxxxxxxx

**Expected Behavior**
The page is NOT returned as a search result and "xxxxxxxxxx" is not displayed.

**Actual Behavior**
The page is returned as a search result and "xxxxxxxxxx" is displayed.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by joshuacords** [comment]
ci:test

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
Hey @joshuacords,
Please fix SF errors.

**Comment by joshuacords** [comment]
ci:test:sf

**Comment by joshuacords** [comment]
ci:test:relevant

**Comment by joshuacords** [comment]
Sorry about the SF error.

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
