### PR TITLE
LPS-123294 Enable Filter and Applied Filters fragments

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
Hi @ealonso, missing poshi commit

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
