### PR TITLE
LPS-146965 Update test macro

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1267401_1736

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1307401_2058

**Comment by ealonso** [comment]
ci:reevaluate:1307401_2058

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
