### PR TITLE
LPS-126682 Adjust toolbar height

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
@victorg1991 I think this is ready :3

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Perfect! LGTM :D

**Comment by victorg1991** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
tu si que failed

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
