### PR TITLE
LPS-173794 Add HTMLInfoFieldType

### PR DESCRIPTION
**Pull request by p2kmgcl**
As we want to distinguish between Text and Rich Text fields, I have created a new HTMLInfoFieldType that is mapped to Object's RichText and the Rich Text Input Fragment.

This will replace the TextInfoFieldType+HTML attribute, but that will be refactored in another task.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
When submitting a page with a form container mapped to an object definition with a rich text field, the object created is not showing the values entered in the input fragments. We probably need additional changes

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Failures are not related, pushed to BChan directly at https://github.com/brianchandotcom/liferay-portal/pull/130057

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
