### PR TITLE
LPS-102712 Keep the old portlet key to avoid upgrade process since we should update tables that have the old identifier with the new one, such as permissions

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @david-gutierrez-mesa @Tim-Cao  @liulukiwi,

Could you please take a look to the poshi failures? I think we need to update some macros.

**Comment by liulukiwi** [comment]
ci:test:bundle

**Comment by liulukiwi** [comment]
Hi @ealonso,

From the screenshot, it seems after adding a site, the site setting is missing, I'm waiting for the [built bundlle](https://github.com/liferay-echo/liferay-portal/pull/4306#issuecomment-824599943) to assert that.

**Comment by ealonso** [comment]
Hey @liulukiwi,

Sorry about that, I didn't explain the objective of this task. 

The idea of this task is replace the old portlet of settings for a new one, the new Site Settings portlets should looks like System Settings or Instance Settings. If you want to see the configuration of site settings you should click on Site Configuration.

https___testray_liferay_com_reports_production_logs_2021-04_test-1-25_test-portal-acceptance-pullrequest_master__50_lpkg-base-jdk8_0_0_LocalFile_PortalSmoke_Smoke_summary_html_gz

Please let me know if you have any other question.

Regards,
Eudaldo.

**Comment by liulukiwi** [comment]
Hi @ealonso ,

Could you cherry-pick these two commits? https://github.com/liulukiwi/liferay-portal/pull/351 One more thing, the site setting is now com_liferay_site_admin_web_portlet_SiteSettingsPortlet, you have to fix this then the relevant should pass.

site-setting

**Comment by ealonso** [comment]
resend: https://github.com/liferay-echo/liferay-portal/pull/4331

**Pull request closed without merging**
