### PR TITLE
LPS-142961 Show the selected field by default

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @victorg1991 and @ealonso, I've updated Poshi cases. However, the collection still keeps old behavior, Would you have a look at? If it is expected, please remove the last two commits from https://github.com/liferay-echo/liferay-portal/pull/7042

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
