### PR TITLE
LPS-176261 When update editable values, allow setting the display date back to blank

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Hi @victorg1991, sidebar in structure is missing when editing default value, can you take a look?

Steps to reproduce:
1. Go to add a web content structure
2. Edit Default Value

Actual result:
Sidebar is missing when editing default value.

Screenshot from 2023-02-22 17-22-18

**Comment by victorg1991** [comment]
Fixed that sorry @liulukiwi

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130686

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
