### PR TITLE
LPS-196125 Standardize the text to Make a Copy through the product

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
https://github.com/liferay-echo/liferay-portal/pull/13681#issue-1896308432

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:foward

**Comment by BarbaraCabrera** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140845

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
