### PR TITLE
[TS] LPS-114135

### PR DESCRIPTION
**Pull request by dacousalr**
Hi @p2kmgcl, Could you please review this PR? In order to avoid odd behaviors in the AlloyEditor of FragmentEntryLinks, it seems to be needed to remove the code that stops the event propagation introduced in https://github.com/liferay/liferay-portal/commit/927904c83202a1c0b20a218d6ff22cf534321cb1

### CODE REVIEW

**Comment by victorg1991** [comment]
Taking a look

**Comment by victorg1991** [comment]
Hey @dacousalr, I've review it and looks good to me 🎉, thanks! If you press arrow or down key in the editor it will move the selected fragment bottom or up, it seems the reason we block that events in the past, but it is not needed anymore

**Comment by victorg1991** [comment]
ci:forward

**Comment by dacousalr** [comment]
Thanks to you for your clarifications and your review, @victorg1991!

And thank you so much, @NemethNorbert! Good job!

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/754

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
