### PR TITLE
LPS-116856 classify new types depending the DDMFormFieldType

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
Hi @JorgeFerrer and @liferay-echo 

I added several InfoFieldTypes to filter and arrange the some of DDMFormFieldType and show/hide on translation pages.

Can you review it.

Thanks!!

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/1602

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
