### PR TITLE
LPS-124403 Add css class for the background color too in cases where it may be a class (if start with # is considered a hex value so it is not added)

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
