### PR TITLE
LPS-143198 Remove max-height

### PR DESCRIPTION
**Pull request by p2kmgcl**
To check this you need to create some web content structure with lots of elements so there is enough vertical scroll.

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
