### PR TITLE
LPD-22494 Duplicate entry in v3_4_1.LayoutFriendlyURLEntryUpgradeProcess#doUpgrade

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-22494

cc: @balazssk

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
ci:test:upgrade

**Comment by lfbesada** [comment]
ci:report:2558836511

**Comment by lfbesada** [comment]
ci:report:2558833196

**Comment by lfbesada** [comment]
ci:test:stable

**Comment by lfbesada** [comment]
ci:report:2559168459

**Comment by lfbesada** [comment]
ci:test:stable

**Comment by lfbesada** [comment]
ci:test:stable

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:report:2559388063

**Pull request closed without merging**
