### PR TITLE
LPS-197782 Add context title to back button in Fragment

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-197782)

## Steps 
**- Case 1**
- Go to Design > Fragments > Create a fragment set > edit the fragment set > see back button
Screenshot 2023-10-02 at 12 28 07

**- Case 2**
- Go to Design > Fragments > Create a fragment set 
- Create a fragment entry > Edit the fragment entry > see back button
Screenshot 2023-10-02 at 12 27 01

**- Case 3**
- Go to Design > Fragments > Create a fragment set 
- Create a fragment entry 
- Go to Site Builder > Pages > create a content page
- Add the fragment created to the page
- Go to Design > Fragments > select the kebab of the fragment created
- Go to view usages
Screenshot 2023-10-02 at 12 29 52

**- Case 4**
- Go to global site 
- Go to Design > Fragments > Create a fragment set 
- Create a fragment entry 
- Go back to the previous site
- Go to Site Builder > Pages > create a content page
- Add the fragment created in global site to the page > publish
- Go back to global site
- Go to Design > Fragments > select the kebab of the fragment created
- Go to view usages
Screenshot 2023-10-02 at 12 31 29

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
LGTM! 🎉

**Comment by BarbaraCabrera** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by BarbaraCabrera** [comment]
ci:forward

**Pull request closed without merging**
