### PR TITLE
LPS-121883 Migrate management toolbar v2 usages in layout/layout-admin-web

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Attached is an update for http://issues.liferay.com/browse/LPS-121883.  

**Test Plan:**
1.  Login to Liferay
2. Click on the **Control Menu**
3. Click on the **Page Tree** link
4. Click on the **Gear Icon**
5. Under the **Look And Feel** panel, click on the **Change Current Theme** button
6. See Management Toolbar in popup window
7. Go back to step 3 and now click on the `+` icon
8. Click on **Add Collection Page** from menu
9. See Management Toolbar
10. Go back to step 3 and now click on the **Public Pages** link in the page tree
11. See Management Toolbar
layout

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
LGTM! Thanks!

**Comment by victorg1991** [comment]
ci:forward

**Review by julien — APPROVED** [review]

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
ci:close

**Comment by jonmak08** [comment]
There is a CI error that i will fix

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/liferay-echo/liferay-portal/pull/4003

**Pull request closed without merging**
