### PR TITLE
LPS-137664 Validate collection filter configuration in service tracker

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reevaluate:1287401_645

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:reevaluate:1287401_645

**Comment by ealonso** [comment]
ci:reevaluate:1287401_645

**Comment by ealonso** [comment]
ci:reevaluate:1287401_645

**Comment by victorg1991** [comment]
ci:reevaluate:1287401_645

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
