### PR TITLE
[TS] LPS-130990

### PR DESCRIPTION
**Pull request by jonathanmccann**
These changes allow for https://issues.liferay.com/browse/LPS-117376 to continue working as expected due to the request being available when the template is processed. It also resolves https://issues.liferay.com/browse/LPS-130990 by resetting the request and response even in the case they are null.

Please let me know if there are any questions or if there are potential issues with these changes.

Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reevaluate:1107401_4654

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
