### PR TITLE
LPS-127955 Fix ImageSourcePanel-EditableLink conflict

### PR DESCRIPTION
**Pull request by p2kmgcl**
@ruben-pulido this should fix link-image conflicts

This is the editableValue shape that we have in portal:

```js
{
  "defaultValue": "data:image/png;base64,iVBORw0KGgoA=",
  "config": {
    /* Image description, this configuration can be translated but not mapped */
    "alt": {
      "es_ES": "Spanish image description",
      "en_US": "English image description"
    },

    /* Image size, this configuration cannot be translated nor mapped */
    "imageConfiguration": {
      "desktop": "Thumbnail-300x300"
    },

    /* Link href and target, these values appear here if they have been mapped  */
    "target": "_blank",
    "href": "https://google.mapped",

    /* It looks like backend services need this "flat" for link configuration */
    "mapperType": "link",

    /* Link href, this configuration can be translated and mapped */
    "es_ES": { href: "https://google.es", target: "_blank" },
    "en_US": { href: "https://google.us", target: "_blank" }
  },

  /* Editable content */
  "en_US": {
    "fileEntryId": "38684",
    "title": "samurai.jpg",
    "url": "/documents/20124/0/samurai.jpg/59d01c97-2563-4e81-a0d1-583876c799e8?t=1614673849293&download=true"
  },
  "es_ES": {
    "fileEntryId": "38695",
    "title": "tetris-minimal.jpg",
    "url": "/documents/20124/0/tetris-minimal.jpg/90f9dd03-9f69-b951-ea56-ae3908ade75a?t=1614673887980&download=true"
  }
}
```

In a near future, we should move editable link configuration to somewhere like `config > link > { href, target }`. Currently this information is embeded inside `editableValue > config`, which causes lots of headaches, and force us to take care of link-image configuration conflicts.

I would refactor editableValues into something like this:

```js
{
  /* Image description, this configuration can be translated but not mapped */
  "imageDescription": {
    "es_ES": "Spanish image description",
    "en_US": "English image description"
  },

  /* Image size, this configuration cannot be translated nor mapped */
  "imageSize": {
    "desktop": "Thumbnail-300x300"
  },

  /* Link target, this configuration cannot be translated nor mapped */
  "linkTarget": "_blank",

  /* Link href, this configuration can be translated and mapped */
  "linkHref": {
    "es_ES": "https://google.es",
    "en_US": "https://google.us"
  },

  /* Default value, cannot be translated nor mapped */
  "defaultValue": {
    url: "data:image/png;base64,iVBORw0KGgoA="
  },

  /* Editable content, can be translated or mapped */
  "content": {
      "en_US": {
        "fileEntryId": "38684",
        "title": "samurai.jpg",
        "url": "/documents/20124/0/samurai.jpg/59d01c97-2563-4e81-a0d1-583876c799e8?t=1614673849293&download=true"
      },
      "es_ES": {
        "fileEntryId": "38695",
        "title": "tetris-minimal.jpg",
        "url": "/documents/20124/0/tetris-minimal.jpg/90f9dd03-9f69-b951-ea56-ae3908ade75a?t=1614673887980&download=true"
      }
   }
}
```

```ts
type LanguageId = "en_US" | "es_ES";
type ViewportSize = "desktop" | "mobile";

type EditableValueRawEntry<T> = T;
type EditableValueTranslatedEntry<T> = Record<LanguageId, T>;
type EditableValueMappedEntry = { name: string };

type DefaultEditable<T> = {
  defaultValue: EditableValueRawEntry<T>,
  content: EditableValueTranslatedEntry<T> | EditableValueMappedEntry,
};

type LinkableEditable = {
  linkHref: EditableValueTranslatedEntry<string> | EditableValueMappedEntry,
  linkTarget: EditableValueRawEntry<string>,
};

type EditableImage = DefaultEditable<{ title: string, url: string }> &
  LinkableEditable & {
    imageDescription: EditableValueTranslatedEntry<string>,
    imageSize: EditableValueRawEntry<Record<ViewportSize, string>>,
  };
```

Which will allow us to add extra configuration in the future without modifying existing configuration panels. This will imply an upgrade process (or at least a lazy upgrade of all editables). For more information please check [my original post](http://www.cervantesvirtual.com/obra-visor/el-ingenioso-hidalgo-don-quijote-de-la-mancha-6/html/05f86699-4b53-4d9b-8ab8-b40ab63fb0b3_2.html#I_2_) at cervantesvirtual.com.

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, there is a regression issue caused by this PR.
Can not save fragment composition as fragment when it includes an Image fragment with inline image.
*Step to reproduce:*
# Add a page based on Blank
# Add a Container to page
# Add an Image fragment inside the Container
# Click the editable field of Image
# Image Source panel > Select > Documents and Media > Select an image > Add
# Assert the image is shown in Image fragment
# Click the body of Container
# Click the ellipsis button on topper bar of Container > Save Composition
# Type name and check Save Inline Content
# Click save

*Expected Results:*
The composition should be saved successfully.

*Actual Results:*
Error:An unexpected error occurred.

**Comment by p2kmgcl** [comment]
Thanks @Tim-Cao, I going to fix that

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
