### PR TITLE
LPS-146828 Take into account color css classes

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:bundle

**Comment by Tim-Cao** [comment]
Hi @victorg1991, there is a regression issue caught by Poshi case.
The Text Align of Heading doesn't change in preview mode.
**Steps to reproduce**

1. Add a Heading fragment to a content page
2. Switch to Tablet viewport
3. Change the Text Align to Center
4. Switch back to Desktop viewport
5. Open preview mode
6. Switch to Tablet viewport

**Expected Results:**
The Text Align should be Center.

**Actual Results:**
The Text Align is left.

**Comment by Tim-Cao** [comment]
Hi @victorg1991, there is another regression issue.
The fragment is empty when unhide via page structure at non-desktop viewport.
**Step to reproduce**

1. Add a new site 
2. Add a Heading fragment to a content page
3. Hide via page structure at desktop viewport
4. Switch to the Tablet viewport
5. Unhide via page structure

**Expected Results:**
The Heading fragment should be shown well.

**Actual Results:**
The Heading fragment is empty.
image

Note: Add a new site is required.

**Comment by Tim-Cao** [comment]
Hi @victorg1991, there is another regression issue.
The hidden fragment is still shown at non-desktop viewport on preview mode.
**Step to reproduce**

1. Add a new site
2. Add a Heading fragment to a content page
3. Switch to the Tablet viewport
4. Hide the Heading fragment
5. Open the preview mode
6. Switch to Tablet viewport

**Expected Results:**
The Heading fragment should be hidden.

**Actual Results:**
The Heading fragment is still shown.

**Comment by Tim-Cao** [comment]
Hi @victorg1991, there is another regression issue.
The Fragments and Widgets,Page Design Options should be hidden at Content Editing.
**Step to reproduce**

# Add a content page
# Switch to the Content Editing

**Expected Results:**
The Fragments and Widgets,Page Design Options should be hidden.

**Actual Results:**
The Fragments and Widgets,Page Design Options are still shown.

**Comment by Tim-Cao** [comment]
Resent https://github.com/liferay-echo/liferay-portal/pull/8525

**Comment by Tim-Cao** [comment]
Hi @victorg1991, another regression issue found.
The marketer without Update permission in Page section cannot drag fragment into Container.
**Step to reproduce**

1. Add a site role named marketer with Update Basic and Update Advanced Options permissions
2. Add a new user
3. Add a new site
4. Assign the new user to site
5. Assign the new site role to user
6. Add a content page in new site
7. Sign in as new user
8. Navigate to the page editor
9. Add a Container to page
10. Try to add a Heading fragment into Container

**Expected Results:**
The Heading fragment is shown in Container

**Actual Results:**
Unexpected error happens
image

**Pull request closed without merging**
