### PR TITLE
LPS-189594 - Show the error message of the Object Action on Preview Error toggle

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @sandrodw3 @victorg1991 @lfbesada

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
https://github.com/liferay-echo/liferay-portal/pull/12759

**Pull request closed without merging**
