### PR TITLE
[TS] LPS-128151

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This PR tries to fix the import over a site where a preexisting content page is updated by matching its Friendly URL with differentLayoutPageTemplateStructure UUIDs.

The solution checks if there is an existing LayoutPageTemplateStructure with the same plid (classPK). If so, do the update, if not it behaves as usual creating a new LayoutPageTemplateStructure entry.

Could you please review it?

Thanks in advance

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1137401_5474

**Comment by dacousalr** [comment]
ci:reevaluate:1137401_5474

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Hi @ruben-pulido,

I would like to know if there is something blocking with this PR or, by contrast, it would be safe to deliver.

Thanks in advance

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
