### PR TITLE
[TS] LPS-156240

### PR DESCRIPTION
**Pull request by jonathanmccann**
https://issues.liferay.com/browse/LPS-156240

The issue is that previously we were passing along the `JournalArticle`'s `id_` in order to update the associated `AssetEntry`. This resulted in the existing `AssetEntry` not being found and a new one being created. By passing in the `resourcePrimKey` the existing `AssetEntry` is found as expected.

This code has been the same since the block was introduced many years ago but every other call to `updateEntry` in this class uses the `resourcePrimKey`. That being said please let me know if there is a reason why the `id_` should be used in this case.

Thank you.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @jonathanmccann 

The code you want to change is correct, it should not be changed. It is adding a draft JournalArticle that is not the first version, so its AssetEntry  classPK should be the id

A JournalArticle can have more than one AssetEntry and only one of them will have the resourcePrimKey as classPK, the rest of them will have the id as classPK. Of those AssetEntries, will only be visible the one that corresponds to the published version. If there is no published version, none will be visible.

The visible AssetEntry, will have the JournalArticle resourcePrimKey as classPK, the rest of the AssetEntries will have the id as classPK.

When there is no visible AssetEntry because there is not any published version, then the first of the non-visible assetEntries will have the resourcePrimKey as classPK, the rest will have the id.

Here are some examples where an item has more than one AssetEntry:

1. Create an article publish it and then make a draft
2. Create an article, publish it, and then modify it scheduling it for different dates
3. Create an article and, before publishing it, change the publish date to the future so publishing is scheduled, then make a draft of that article --> you will have two asset entries and none are visible.

Regards

**Comment by jonathanmccann** [comment]
https://github.com/liferay-echo/liferay-portal/pull/8563

**Pull request closed without merging**
