### PR TITLE
LPS-127677 Disable submit buttons before submitting the form, an reenable then after

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:reevaluate:1277401_130

**Comment by Tim-Cao** [comment]
ci:reevaluate:1277401_130

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
