### PR TITLE
[TS] LPS-130051

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-130051

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @ChrisKian,
Could you please send this one to Core Infra Team or Staging Team?
Regards,
Eudaldo

**Comment by ChrisKian** [comment]
Sorry about that @ealonso, resent to https://github.com/vendeltoreki/liferay-portal/pull/189

**Pull request closed without merging**
