### PR TITLE
LPD-21153 Convert LPD-11070 to release feature flag

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-21153

On Hold because [this](https://liferay.atlassian.net/browse/LPD-16011) story must pass the product review and these two PRs must be merged:

- https://github.com/liferay-echo/liferay-portal/pull/15366
- https://github.com/liferay-echo/liferay-portal/pull/15401

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
cc: @JavierMoral

**Comment by lfbesada** [comment]
The SF failure will be fixed once https://github.com/liferay-echo/liferay-portal/pull/15393 merged

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
