### PR TITLE
LPS-122013 Only save fileEntryId if the adaptiveMedia config is enabled

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
