### PR TITLE
[7.4 only]LPS-121973 Use vertical flush to preserve the old appearance

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Review by carloslancha — COMMENTED** [review]
You can probably remove `getAspectRatioCssClasses`  method from the model

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
I'll put the pr on hold until we decide whether or not we are going to maintain the `getAspectRatioCssClasses()` functionality

**Comment by victorg1991** [comment]
It seems that flushHorizontal is not enough because the image is not scaled proportionaly but stretched

**Comment by julien** [comment]
cc @carloslancha @julien

**Comment by carloslancha** [comment]
@victorg1991  @julien this has been addressed in https://github.com/liferay/clay/pull/3815/files

To not stay blocked with this I created [this ticket](https://issues.liferay.com/browse/LPS-123984) so we can fix the issue once the migration is done. 

So we can continue with this one. Thx! :)

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
Let's send this then, thanks! :)

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
