### PR TITLE
LPS-131407 Set collections as default source in asset publisher

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-131407

Previous PR: https://github.com/liferay-echo/liferay-portal/pull/7378

@victorg1991 
@Tim-Cao

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Thanks @lfbesada, I will update Poshi cases today.

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7411

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
