### PR TITLE
[TS] LPS-152159

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by crodriguezy** [comment]
Hi team, this is the best way I could think of to solve case https://issues.liferay.com/browse/LPS-152159. Any suggestions or changes on how to fix it are welcome

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Hi @crodriguezy,

As part of this review, could you push a commit to add a debug trace inside the catch block?

Thanks!

**Comment by crodriguezy** [comment]
Done @dacousalr . Thanks for reviewing it!

**Comment by dacousalr** [comment]
Thanks to you, @crodriguezy!

Let us see what the team has to say after they finish their review.

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by lfbesada — COMMENTED** [review]
Hi @crodriguezy @dacousalr 
Thanks for the pull request! ❤️ 
It works great and I agree that the best approach is to check the group Manage Pages permission here in addition to the individual layout checks permissions that LayoutServiceUtil.getLayoutsCount.
Recently we have hidden the private pages under a Release Feature Flag for new installations. The intention is to advance in the advance the objective of unifying the private and public pages, so the same situation could happen using public pages if the permissions are restricted. That's the reason why I have added a few commits to apply your solution to the public page counts too.
Regards

**Comment by lfbesada** [comment]
See: https://github.com/liferay-echo/liferay-portal/pull/8043

**Pull request closed without merging**
