### PR TITLE
LPS-124283 Use localized config when possible

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @sandrodw3, the Banner Center is rendered wrong when add it to page editor.

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Pull request closed without merging**
