### PR TITLE
LPS-136545 Add search/clear icon to the search bar

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @victorg1991，there is a regression issue. Cannot select structure in template editor when the current site has a structure.
image
Add a new site
Add a structure with any field
Add a template
Click the plus icon of Structure field

**Comment by victorg1991** [comment]
should be fixed now, thanks @Tim-Cao

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
