### PR TITLE
LPS-166857

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-166857

Previous PR: https://github.com/liferay-echo/liferay-portal/pull/10222

See: https://github.com/brianchandotcom/liferay-portal/pull/125968#issuecomment-1308864385

cc: @ealonso @BarbaraCabrera

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/126214

**Pull request closed without merging**
