### PR TITLE
LPS-162588 Disallow shrinking ColorPicker buttons

### PR DESCRIPTION
**Pull request by p2kmgcl**
I just fixed a small part of the issue, but I couldn't reproduce the line break problem: https://issues.liferay.com/browse/LPS-162588?focusedCommentId=2757164&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2757164

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
