### PR TITLE
LPS-193342

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
Hi @ealonso, one baseline issue found, can you take a look? thanks!

```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/portal-background-task/portal-background-task-api] FAILED
     [exec]     java.lang.AssertionError: [Baseline Warning] Bundle Version Change Recommended: 7.7.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertFalse(Assert.java:64)
     [exec]         at com.liferay.semantic.versioning.SemanticVersioningTest.testSemanticVersioning(SemanticVersioningTest.java:73)
     [exec]         at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
     [exec]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
     [exec]         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
     [exec]         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
     [exec]         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
     [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
     [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
     [exec]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
     [exec]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
     [exec]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
     [exec] 
     [exec] 88 tests completed, 1 failed
     [exec]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
     [exec]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
     [exec]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
     [exec]         at org.junit.runners.Suite.runChild(Suite.java:128)
     [exec]         at org.junit.runners.Suite.runChild(Suite.java:27)
     [exec]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
     [exec]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
     [exec]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
     [exec]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
     [exec]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
     [exec]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
     [exec]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
     [exec]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
     [exec]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
     [exec]         at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
     [exec]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
     [exec]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
     [exec]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
     [exec]         at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
     [exec]         at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
     [exec]         at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
     [exec]         at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
     [exec]         at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
     [exec] 
```

**Comment by ealonso** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Many of the tests were as `Failed prior to running` but were not reproduced locally. And the other failures are not related to this PR ([comparison with acceptance routine here](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1692381123401&testrayRunIdA=2408641802&testrayRunIdB=2408841012)). See https://github.com/brianchandotcom/liferay-portal/pull/139435

**Comment by alessandromalves** [comment]
ci:close

**Pull request closed without merging**
