### PR TITLE
LPS-170765 Use toString before toLowercase to ensure that it is a string

### PR DESCRIPTION
**Pull request by mbowerman**
Original comment from @javalosjr96:

> Ticket:
> [LPS-170765](https://issues.liferay.com/browse/LPS-170765)
> 
> Issue:
> Some of the variables in the are not being parsed as Strings when the Styles menu is being rendered.  When t.toLowerCase is applied, the method throws an exception.
> 
> Solution:
> Parse as string before using toLowerCase.
> 
> Testing:
> Used steps from LPS to create database dump and upgrade.  Before fix, the Styles menu would not appear and an error is thrown in the console.  
> 
> After the fix, the Styles menu appears with all of the relevant data.  
>

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by javalosjr96** [comment]
@victorg1991 
Hi Victor,
how does the PR look?

**Comment by victorg1991** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
The failures are not related to this PR. See https://github.com/brianchandotcom/liferay-portal/pull/128833

**Pull request closed without merging**
