### PR TITLE
LPS-173462 and LPS-174473 Add permission restriction to the collection display fragment on EDIT mode

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-173462
https://issues.liferay.com/browse/LPS-174473

Previous PRs:
LPS-173462 --> https://github.com/liferay-echo/liferay-portal/pull/10990
LPS-174473 --> https://github.com/liferay-echo/liferay-portal/pull/11017

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Splitted in these PRs: https://github.com/liferay-echo/liferay-portal/pull/11322 and https://github.com/liferay-echo/liferay-portal/pull/11330

**Pull request closed without merging**
