### PR TITLE
LPS-169820 Using existing priority if any

### PR DESCRIPTION
**Pull request by 4lejandrito**
Fixes https://issues.liferay.com/browse/LPS-169820, coming from https://issues.liferay.com/browse/PTR-3508.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1277401_5978

**Comment by liulukiwi** [comment]
Pushed to BChan directly:
https://github.com/brianchandotcom/liferay-portal/pull/126979

**Pull request closed without merging**
