### PR TITLE
LPD-35585: Search Configuration param leaks between Experiences

### PR DESCRIPTION
**Pull request by gustavolimav**
Ticket: https://liferay.atlassian.net/browse/LPD-35585

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by gustavolimav** [comment]
Hey @ealonso, I needed to make a change in `modules/test/playwright/pages/layout-content-page-editor-web/PageEditorPage.ts`. Could someone from your team review it for me? The change was necessary because, when using the edited function, there were two 'saved' options appearing when the widget tab was opened. Thanks!

**Comment by sandrodw3** [comment]
ci:test:page-management-playwright

**Comment by sandrodw3** [comment]
Hey @gustavolimav the change in `PageEditorPage` looks good to me, thanks for letting us know 😄 just running our tests to confirm everythings works fine. Do you want to forward the PR here or we can close it once the tests pass?

**Comment by gustavolimav** [comment]
ci:test:sf

**Comment by gustavolimav** [comment]
Hey @sandrodw3, you can close once the tests pass.

**Pull request closed without merging**
