### PR TITLE
[TS] LPS-174627 | Content page loses portlet configuration after opening the translation feature

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-174627
Thank you!

----

**Steps to reproduce:**

1. Create a content page
2. Put an Asset Publisher on the page and configure it do 'Dynamic' and set Web content article as the source
3. Publish, then go to its context menu -> Translate
4. Put 'AR' in the HTML fragment on the right side, save as draft
5. Open the page

**Current behavior:** The asset publisher lost the selected dynamic configuration
**Expected behavior:** The asset publisher should keep the configuration

The root cause of the issue is that when we call the getHTML for a fragmentEntryLink for a widget the processors will create a new portletPreference while generating the HTML for the control panel which will belong to the Plid = 1. This portletPreference will be handled as a shared preference and will overrule the live version. As the modified part of the code only tries to collect editableTypes we can skip all fragmentEntrylinks with isTypePortlet() = true.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @bakayattila,

Could you please send this one to liferay-lima?

Thanks!!

**Comment by ealonso** [comment]
@bakayattila everything looks good to me, but I prefer another review from lima perspective, since they created that part of the code.

**Comment by jkappler** [comment]
Same as the other PR, please see @ealonso, comments

**Pull request closed without merging**
