### PR TITLE
LPS-116104 - Container in Collection with background color displays background color only for first element of the collection when viewing the page

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @victorg1991 @p2kmgcl

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
https://github.com/liferay-echo/liferay-portal/pull/1278

**Pull request closed without merging**
