### PR TITLE
LPS-126007 Add canDrag prop to DragAndDropContext, so we can set it from ColumnWithControls and prevent rows from being dragged when resizing

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:forward 🦄

**Comment by sandrodw3** [comment]
ci:forward 🚀

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward 🤷🏽‍♂️

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
