### PR TITLE
LPD-15505 Take into account the rest of the localizable fields in the translation status label

### PR DESCRIPTION
**Pull request by veroglez**
The label that shows the status of the translation has to take into account all **localizable fields**, both the Name and Metadata, as well as the Fields (ddm fields)

Screen Shot 2024-01-26 at 4 04 56 PM
Screen Shot 2024-01-26 at 4 10 51 PM

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:stop

**Comment by veroglez** [comment]
Send to https://github.com/liferay-frontend/liferay-portal/pull/3966 and https://github.com/liferay-forms/liferay-portal/pull/2465 to be reviewed for their respective teams

**Pull request closed without merging**
