### PR TITLE
LPS-137014 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-137014

This is only for master.

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
The tests results are related with the changes

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/5832

**Pull request closed without merging**
