### PR TITLE
LPS-131534 Content Pages with Page Versioning

### PR DESCRIPTION
**Pull request by moltam89**
Hi guys,

**This isn't the final code**, I'd just like to open a discussion about how Page Versioning could be implemented for Content Pages.

Right now in master when Page Versioning is enabled, only the Site Pages Variation option is available for Content Pages (without History and Page Variations) and changes made on different Variations affect each other.

With the current solution we should be able to create different versions of the pages and preserve the History, add new Page Variations, select a version for "Ready for Publish Process" and publish them to Live.
Please turn on Page Versioning before creating any content pages, during the initial publication there is an inverse publication from the Live to the Stage site, which is not implemented yet.

###  Highlights of the changes:

1. **History and Page Variation options are reenabled**

2. **Plid is swapped for layout revisionId in LayoutPageTemplateStructure and FragmentEntryLink services** (later Segments have to be considered)
In order to differentiate between the revisions, we need to connect the LayoutPageTemplateStructure and FragmentEntryLink entities to a revision. This is how it works for PortletPreferences, in PortletPreferencesLocalServiceImpl the plids are swapped to the revisionId.

3. **Draft pages are versioned too**
In the current solution for each published layout revision, there is a connected draft layout revision. (Publish meaining: Publishing a Content Page after editing, not Publishing to Live).
It seems necessary to me, as users can start editing previous versions via the History.  E.g. if there are 1.0-1.5 versions of a layout, someone can go back to 1.3 and start editing it. We need a draft revision for 1.3 where the changes are stored. 
It's a bit unambiguous what should happen when we are editing an older version, how we should preserve the history. When we publish version 1.3, a new version is created with the latest changes, and the 1.3 version of the published layout is copied back to the draft 1.3, so next time we go back to 1.3 in the History, we'll see that version.

4) **Changes for handling LayoutRevisions**
These changes are mostly needed because Widget Pages and Content Pages are different.

### Problems to consider:
1. There are quite a lot of problems with Page Versioning in general, even for Widget Pages which will also affect Content Pages once versioning is enabled for them.
Most of the entities are not prepared to handle a revisionId instead of a plid.
For example when we are adding a tag to a page, the plid is stored in the database. This way we cannot add separate tags for different layout revisions. The same applies for Portlet Permissions, Categories, Custom fields, SEO, Open graph, Custom Meta Tags, Layout Classed Model Usages and so on (probably all the places where we store the plid instead of the revisionId).

2. Developers have to remember that getPlid() calls can result in a revisionId. This is a problem for PortletPreferences as well, portletPreferences.getPlid() calls should be prepared for receiving revisionId. As far as i can see, there are only a few corner cases where this can cause a problem, but once LayoutPageTemplateStructures, FragmentEntryLinks and Segments will work the same way, it can cause quite a lot of problem.

Sorry for the long post, feel free to ping me with any questions.

Best,
Tamas

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:echo

**Comment by ealonso** [comment]
ci:test:echo

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
@moltam89

Could you please update the pr? I want to execute the tests, but I think we need to resolve the conflicts first, sorry about that 😞.

Also, just to avoid more conflicts, What do you think of sending the changes on portal-kernel to master? Since those changes are helper methods and should not affect anything else. 

Regards,
Eudaldo.

**Comment by moltam89** [comment]
Hi @ealonso ,

Please note that this is not a complete, final solution, tests will probably fail.

I just wanted to ask for your opinion about the concept (changing plid to revisionId, enabling versioning for draft pages) at an early phase of the development.

Best,
Tamas

cc @zsigmondrab

**Comment by ealonso** [comment]
Hey @moltam89,

I don't like the idea of changing plid to revisionId, I think it can be really dangerous since we are using it for all entities that we have on Content Pages, LayoutStructure, Segments, Usages, ...

Also having versioning for draft pages can be really difficult to understand for the clients, also for developers.

For that reason I asked in the LPS about the urgency of this story.

Regards,
Eudaldo

**Comment by moltam89** [comment]
Hi @ealonso ,

I understand your concerns.
I left a [comment](https://issues.liferay.com/browse/LPS-131534?focusedCommentId=2498587&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2498587) earlier on the LPS.

Best,
Tamas

**Comment by moltam89** [comment]
Resent here:
https://github.com/liferay-echo/liferay-portal/pull/5755

**Pull request closed without merging**
