### PR TITLE
LPS-125228 Use piping servlet response here to ensure correct rendering order for collection display elements

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Same Unable to connect to a valid mail server issue with https://github.com/liferay-echo/liferay-portal/pull/3316, this is reported in [LRQA-62217](https://issues.liferay.com/browse/LRQA-62217). All the failures are not related to this pr, so I'll forward this pull to BChan dirrectly.

**Comment by liulukiwi** [comment]
resend:
https://github.com/brianchandotcom/liferay-portal/pull/97306

**Pull request closed without merging**
