### PR TITLE
LPS-110925 Update modal usages in fragment-web

### PR DESCRIPTION
**Pull request by markocikos**
Hey @sandrodw3,

This is a followup on https://github.com/wincent/liferay-portal/pull/198, https://github.com/wincent/liferay-portal/pull/203 and  https://github.com/liferay-echo/liferay-portal/pull/156

Changes:
- Removed Babel inclusion generalization commit. As a consequence, I needed to revert `Modal.js` file name to `Modal.es.js`.

I did some testing on my origin, suspecting that Babel config change might be causing issues:
- https://github.com/markocikos/liferay-portal/pull/183: master
- https://github.com/markocikos/liferay-portal/pull/184: master + @jbalsas commit
- https://github.com/markocikos/liferay-portal/pull/185: master + @jbalsas commit + my generalization commit

The last one has a lot more unique errors than the first two. They are not the same as in #156, but it could be a general JS build error that causes all sorts of problem. CI run on this branch should confirm it. We still want to do the transpile inclusion changes, but we can split that of to a separate task.

/cc @wincent

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
@markocikos Cool! So let's see what CI has to say about this one, thanks!

**Comment by wincent** [comment]
> The last one has a lot more unique errors than the first two.

The trouble is, "unique failures" are an *almost useless* indicator of build quality in my opinion. The false positive rate is atrociously high, which massively reduces the utility of the signal. I mean, your `master` pull has "unique failures" in it, which doesn't make any sense at all. @john-co may be able to give some insight into how many (and which) of these "failures" are legit. 😢

**Comment by markocikos** [comment]
Unfortunately, this didn't help, the same upload errors are back. As my theory is proven wrong, I'll force push the exact same code as on https://github.com/liferay-echo/liferay-portal/pull/156. I am out of ideas how to proceed from here.

**Comment by sandrodw3** [comment]
Hey @markocikos, I'll reach our QAs to see if they can help us. If I'm not wrong, most of the tests that are failing are related to applying openModal to `fragment-web`, so if you want, maybe you can send the code that is not related to `fragment-web` and we will send the rest when we find a solution to the test failures. (cc @ealonso @david-gutierrez-mesa)

**Comment by sandrodw3** [comment]
ci:close

**Comment by markocikos** [comment]
See https://github.com/wincent/liferay-portal/pull/204

**Comment by wincent** [comment]
@john-co: even though this one is closed, it would be helpful if you could lend your insight as well.  This pull has been stuck in various forms for about 15 days now:

- https://github.com/wincent/liferay-portal/pull/192
- https://github.com/jbalsas/liferay-portal/pull/2154
- https://github.com/markocikos/liferay-portal/pull/182
- https://github.com/wincent/liferay-portal/pull/198
- https://github.com/wincent/liferay-portal/pull/203
- https://github.com/liferay-echo/liferay-portal/pull/156 and spin-offs:
  - https://github.com/markocikos/liferay-portal/pull/183
  - https://github.com/markocikos/liferay-portal/pull/184
  - https://github.com/markocikos/liferay-portal/pull/185
- https://github.com/wincent/liferay-portal/pull/204

(Just wanted to make that explicit because it is super easy to lose track due to The Liferay System™ of sending multiple versions of the same PR to different places.)

**Pull request closed without merging**
