### PR TITLE
LPS-121917 Migrate v2 usages in site-navigation/site-navigation-item-selector-web

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

Selecting Navigation Menus should work as expected.

**Test plan**:
- Navigate to **Site Builder** > **Navigation Menus**
- Create a new Navigation Menu
- Navigate to the **Home Page**
- Right click on the Home Page's Navigation Menu
- Select **Configuration**
- In the modal window, select the **Choose Menu** radio button
- Click on the **Select** button
- In the nested modal window, make sure you can filter and select a Navigation Menu

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
cc @ambrinchaudhary @markocikos @jonmak08

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
