### PR TITLE
LPD-22144 - Global Information Template not showing on Display Page Template for Custom objects

### PR DESCRIPTION
**Pull request by ruben-pulido**
Original PR Description from @bakayattila 

Hi Team,
Could you review this fix?
https://liferay.atlassian.net/browse/LPD-22144
best,
Attila

-----
The root cause of the issue is that the global scope is not considered when the information templates are collected. My solution is to get the current company's global group and add it to the localService scope.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ruben-pulido** [comment]
ci:forward:force

**Pull request closed without merging**
