### PR TITLE
LPS-138554 Use new TemplateSelectorTag everywhere and remove its "Manage Templates" link

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-138554

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
Hi!

The test that is failing is because this PR removed the link "Manage templates" in the template selector tag. I suppose that, in addition to the failed test, other tests on other components of the portal that do the same check will also fail. 

Please could you adapt this test and the others it may apply to reflect the new expected behavior?

Thank you!

**Comment by Tim-Cao** [comment]
Hi @lfbesada, Could you resolve the conflict first?

**Pull request closed without merging**
