### PR TITLE
LPS-128572 Don't show discard draft when there isn't a published version of the page

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @victorg1991, I have a doubt about this change, **Don't show discard draft when there isn't a published version of the page**
There is a regression issue here, how to discard the draft in a content page without publication?
Imagine that 
1. Add a content page
2. Make some changes in page editor
3. Refresh the page
4. Undo interactions is cleaned up
5. How to discard all draft?

**Comment by p2kmgcl** [comment]
This is not frontend and the PR works fine

**Comment by victorg1991** [comment]
Talked with Juan and we are going to rethink this

**Pull request closed without merging**
