### PR TITLE
LPS-163003 Asset publisher with dynamic selection won't display contents that have their latest version in scheduled status

### PR DESCRIPTION
**Pull request by JavierMoral**
Hi,
I send this pull in order to fix [LPS-163003](https://issues.liferay.com/browse/LPS-163003).
**Reproduction steps:**

- Add an asset publisher widget to a page and configure it with dynamic selection of assets.
- Create a basic web content and publish it.
- Edit this basic web content and set a display date set in the future.
- Publish this new version of the content that should remain in SCHEDULED status.
- In this point the web content should have two versions: 1.0 in APPROVED status and 1.1 in SCHEDULED status.

**Expected behavior:**

- When rendering the asset publisher, it shows the content.

**Actual behavior:**

- When rendering the asset publisher, it does not show the content created in the reproduction steps.

After the changes made in [LPS-141570](https://issues.liferay.com/browse/LPS-141570), asset publisher shows non-searchable contents. The boolean query used to get these results from the search indices queries documents which have field `headListable=true AND status=0`.
When a new version with SCHEDULED status is added to an existing content, it is indexed with the following field values in the search index: `head=false, headListable=true, status=7`.
This means that the asset publisher query will not get this last version because its status is not zero (APPROVED).
I changed JournalArticleModelPreFilterContributor to get documents that have `(headListable=true OR head=true) AND status=0`. This way if a content have a latest version in SCHEDULED status, it will get its last APPROVED version and it will be shown in asset publisher results.

In JournalArticleModelPreFilterContributor class I'm using a new attribute called "headOrShowNonIndexable". I could have used the existing head and headListable attributes both with value="true" to represent this use case but I thought that it could imply that an AND operation was being made like in `(headListable=true AND head=true)` when actually is an OR.
Thanks.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by JavierMoral** [comment]
ci:test:relevant

**Comment by JavierMoral** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ozysouza** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/123220

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
