### PR TITLE
LPS-25034 Allow reading fragment.json > icon during import process so that the proper icon of fragments imported is shown using the generator

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @p2kmgcl

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @ruben-pulido, there is a regression issue. The page editor is broken when drag the new fragment from Fragments and Widgets panel.
**Step to reproduce**
1. Add a new fragment collection
2. Add a new fragment with simple codes
```
<div class="fragment_1">
Fragment Name
</div>
```
3. Add a content page
4. Expand the new collection in sidebar panel
5. Drag the new fragment

**Expected Results**
The fragment card could be dragged.

**Actual Results:**
image

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/6569

**Pull request closed without merging**
