### PR TITLE
LPS-183195 Remove FF

### PR DESCRIPTION
**Pull request by victorg1991**
Setting this on hold for now since the epic already has a story in testing

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:reevaluate:1397401_4831

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/12148

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
