### PR TITLE
LPS-175160 The icon in the date field fragment inside the form container is not being rendered as expected

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
# Test Steps
1. Create and publish a custom object with a date field
2. Create a page
3. Add a form container
4. Map to the object
5. Save the page

image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by sandrodw3** [comment]
Too fast @ealonso 😂

**Comment by sandrodw3** [comment]
ci:stop

**Review by sandrodw3 — APPROVED** [review]

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
