### PR TITLE
[TS] LPS-92704 semantic versioning

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This solution tries to meet the sitemap constraints of less than 50000 links and less than 50 MB per XML file by implementing a sliding window.

More context information in https://issues.liferay.com/browse/PTR-1413

Could you please review it?

Thanks in advance

\cc @jkappler @ealonso

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/981

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
