### PR TITLE
LPS-204336 Default styles bg-white and text-secondary not applied in Form Container

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @veroglez, would you mind checking the failed test?
[com.liferay.layout.taglib.test.RenderLayoutStructureTagTest](https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/892374/testReport/com.liferay.layout.taglib.test/RenderLayoutStructureTagTest)

**Comment by veroglez** [comment]
> Hi @veroglez, would you mind checking the failed test? [com.liferay.layout.taglib.test.RenderLayoutStructureTagTest](https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/892374/testReport/com.liferay.layout.taglib.test/RenderLayoutStructureTagTest)

Fixed! Thanks for checking

**Comment by veroglez** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
