### PR TITLE
LPS-129702

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @liferay-echo,

Attached is an update for http://issues.liferay.com/browse/LPS-129702.

**Test Plan**:
1. Login to Liferay
2. Click on the **Product Menu**
3. Go to **Content & Data** -> **Web Content**
4. Click the `+`  to add a **Folder**
5. Click into the newly created folder
6. Click the `+`  to add a **Subfolder**
7. Click back to the parent **Home** folder
8. Click the `+`  to add another **Folder**
9. Delete the folder containing the **Subfolder**
10. Go to the **Recycle Bin** -> **Recycle Bin**
11. Click into the folder that was deleted
12. Click the **ellipsis** on the subfolder and select **Restore**
trash

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Review by kresimir-coko — APPROVED** [review]
LGTM

**Comment by victorg1991** [comment]
LGTM We can forward this as son as the relevant finishes :)

**Comment by ealonso** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Resend since the CI seems to be not working at all, see: https://github.com/liferay-echo/liferay-portal/pull/4184

**Pull request closed without merging**
