### PR TITLE
LPS-150420 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-150420

This is only for master.

@ozysouza

I've made some changes. However, you probably miss refactoring **LocalizationWithWebContent#ViewLocalizedFriendlyURLInWCD**, Would you mind modifying based on this PR? Thanks

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by ozysouza** [comment]
Hi @Tim-Cao, I didn't miss this test, I saw it but as it was done by you I'd better don't make any change. I will push a new PR with this change.

**Comment by ozysouza** [comment]
Please see https://github.com/liferay-echo/liferay-portal/pull/8265

**Comment by ozysouza** [comment]
ci:close

**Pull request closed without merging**
