### PR TITLE
LPS-172538 Asset publisher error if configure a collection without Guest permissions

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-172538

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @lfbesada, would you mind having a look at the integration test failure? Thanks
[com.liferay.asset.link.exportimport.test.AssetLinkExportImportTest](https://testray.liferay.com/home/-/testray/case_results/2157515265)

**Comment by lfbesada** [comment]
Hi @Tim-Cao 
Thanks for looking at it! ❤️ 
I can't reproduce the test failure on this branch. That test has no relation to my changes, IMHO its failure cannot be related.
I will run the tests on this branch again to see if the error is repeated.
Regards

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
The test failure is not related to the changes.

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128656

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
