### PR TITLE
LRQA-81043 Amazing new feature

### PR DESCRIPTION
**Pull request by Tim-Cao**
Please pull these awesome changes in!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
See https://github.com/Tim-Cao/liferay-portal/pull/738

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136454

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
See https://github.com/Tim-Cao/liferay-portal/pull/739

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
