### PR TITLE
LPS-124173 SF - Refactor

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @Tim-Cao,

Could you please help us to identify if it is a real failure?

Thanks!!

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
