### PR TITLE
LPS-172368 Reset Category

### PR DESCRIPTION
**Pull request by Marina-Gouveia**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
@Marina-Gouveia, also, your LPS is empty and without clear steps as to reproduce the ticket. I'm closing the PR for now, please resend after all is clear.

Thanks

**Comment by Marina-Gouveia** [comment]
ci:reopen

**Comment by Marina-Gouveia** [comment]
New PR: https://github.com/liferay-echo/liferay-portal/pull/10927

**Pull request closed without merging**
