### PR TITLE
LPS-134903 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-134903

This is only for master.

@victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
Many thanks @Tim-Cao !!

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
@Tim-Cao I think we might need to update more poshi tests

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @victorg1991, there is no scroll bar in Elements panel. Could you have a look at?

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
https://github.com/liferay-echo/liferay-portal/pull/5161

**Comment by victorg1991** [comment]
Fixed the scroll there :) Thanks!!

**Pull request closed without merging**
