### PR TITLE
LPS-128259 Change service ranking

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
com.liferay.portal.tools.ConfigurationEnvBuilderTest.testBuildContent fixed in https://github.com/liferay-echo/liferay-portal/pull/4966

**Pull request closed without merging**
