### PR TITLE
LPS-139074 Load disabled styles if needed

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
👏  didn't know about the dynamic import, looks cool

**Comment by victorg1991** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
> clap didn't know about the dynamic import, looks cool

@boton mentioned it once in the weekly, and I remembered :partying_face:

**Comment by boton** [comment]
My issue with import CSS via js is the unstyled moments until the CSS is loaded.
I'm not sure if I mentioned imported dynamically, I haven't tested yet 😄  but based on my own issue and your code seems to work

**Comment by ealonso** [comment]
ci:reevaluate:1277401_222

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1317401_435

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
