### PR TITLE
LPS-175383 Fix react FragmentEntryLinkModelListener initialization

### PR DESCRIPTION
**Pull request by izaera**
Please note that this is only a proposed solution. I'm no expert in the Fragments infrastructure, so it is possible that this breaks another thing.

Alternative solutions to this problems I evaluated with @victorg1991 and we discarded:

1. Create a new event listener interface in NPMRegistry so that the ModelListener knows when to trigger the initialization (discarded because we have had such listener interfaces in the past and ended up removing them because they were problematic from the POV of performance).
2. Implement an active wait (polling) in the activate method (this could work since the time elapsed between the ModelListener activation and the NPMRegistry processing should be short; however we don't know if it could lead to OSGi locks or delays)
3. Schedule future calls to check if it is possible to initialize (using a scheduler or something alike). This is equivalent to 1, so why making the solution more complex? :shrug: )

Again: please make sure that this works and doesn't break anything else :pray:

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
LGTM, but I prefer other backend to give some input here :D

**Comment by jkappler** [comment]
@izaera, @victorg1991, it's weird to use a model listener as a reference. Could we extract the ensureInitialize code and move it to a LifecycleListener?

**Comment by jkappler** [comment]
Basically moving the current code from activate/deactivate in the ModelListener to when the company is registered

**Comment by jkappler** [comment]
@izaera, @victorg1991, something like this (done quickly) https://github.com/jkappler/liferay-portal/pull/1097

**Comment by jkappler** [comment]
@izaera, @victorg1991, closing this for now since it would be best to not have a reference to the model listener as we talked about. Better go with another util/provider/helper class.

Thanks

**Comment by jkappler** [comment]
@izaera, @victorg1991, see https://github.com/liferay-echo/liferay-portal/pull/11156 as we talked.

Gracias majos

**Pull request closed without merging**
