### PR TITLE
Revert "LPS-180849 Only check for update permission on the published layout if the page is being edited"

### PR DESCRIPTION
**Pull request by jkappler**
This reverts commit 87b1932dd17438fa3969af084c40f11811e229cf.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
cc: @ruben-pulido

**Comment by jkappler** [comment]
@IstvanD, with the changes there are no permission checks and anyone can see the draft though view mode. If you check before the changes, a forbidden error was thrown.

Reverting this, and reopening the ticket

**Pull request closed without merging**
