### PR TITLE
LPS-205105 Expand only if it has children

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by NemethNorbert — CHANGES_REQUESTED** [review]
In order for the `onClick` method to be able to run the `toggle` method on the expand object, we have to pass it as a parameter inside `ClayTreeView.Item`'s `onClick` property.
 
 Also if we want to toggle the node, we have to load it's children as well. Right now it is only done if the user clicks on the arrow next to the treeItem to expand it. However once it is done the user is free to expand and close the TreeItem by clicking on the treeItem itself. One way we could solve it is to pass the `load` object as well to the `onClick` method, and we could call `load.loadMore(item,item.id)` conditionally inside the onClick method like:

if (item.hasChildren) {
	expand.toggle(item.id);
	if(!expand.has(item.id)) {
		load.loadMore(item.id, item)
	}
	expand.toggle(item.id)
}

**Comment by sandrodw3** [comment]
> In order for the `onClick` method to be able to run the `toggle` method on the expand object, we have to pass it as a parameter inside `ClayTreeView.Item`'s `onClick` property.
> 
> Also if we want to toggle the node, we have to load it's children as well. Right now it is only done if the user clicks on the arrow next to the treeItem to expand it. However once it is done the user is free to expand and close the TreeItem by clicking on the treeItem itself. One way we could solve it is to pass the `load` object as well to the `onClick` method, and we could call `load.loadMore(item,item.id)` conditionally inside the onClick method like:
> 
> if (item.hasChildren) { expand.toggle(item.id); if(!expand.has(item.id)) { load.loadMore(item.id, item) } expand.toggle(item.id) }

Hey @NemethNorbert thanks for catching that case! I fixed it 😄

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/146174

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
