### PR TITLE
LPS-160439 Add scroll to the browser panel when the two sidebars are preset

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1357401_2334

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @victorg1991, the page editor sidebar isn't open when access to page editor and product menu is closed.
Would you mind having a look at? Thanks

**Comment by Tim-Cao** [comment]
**Step to reproduce**
1. Navigate to the Pages admin
2. Close the Product Menu
3. Add a content page

**Expected Results**
The page editor sidebar should be open.

**Actual Results**
The page editor sidebar is closed.

**Comment by sandrodw3** [comment]
https://github.com/liferay-echo/liferay-portal/pull/9324

**Pull request closed without merging**
