### PR TITLE
[TS] LPS-171955 | Sitemap gets generated even after the site is deactivated

### PR DESCRIPTION
**Pull request by GaborKomaromi**
Hi Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-171955
Thank you!
---------
**Reproduction Steps:**

1. Create a new site
2. In the settings, the new site under SITE URL → Public Pages add a virtual host under which the site can be used.
3. Add at least one page to the site
4. Deactivate the site
5. Go to [virtualhost]:8080/sitemap.xml

**Expected outcome:** The sitemap cannot be generated or does not include pages referring to the site.
**Actual outcome:** The sitemap is generated and can be accessed.

The root cause is that before generating the sitemap.xml, it did not take in to consideration the active or deactive state of the group. It was an issue as through the sitemap the set virtualhost could be reached and the sitemap was generated. To fix this, I added a check before the sitemap generation.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
ci:test:sf

**Review by lfbesada — APPROVED** [review]
Hi @GaborKomaromi 
Thanks for the fix! LGTM 🤩 
Regards

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128321

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
