### PR TITLE
LPS-191536

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Hi @ealonso , one issue found in this pull, can't view content page with custom master,

here are the steps to reproduce:
scenario1:
1. Add a master page
2. Add a menu display to the header
3. Add a content page with the custom master
4. Go to view the content

Actual result:
The page is blank, npe occurs in server console:
```
2023-07-25 09:04:13.177 ERROR [http-nio-8080-exec-5][IncludeTag:128] Current URL /web/s1/mpc generates exception: java.lang.NullPointerException
java.lang.NullPointerException: null
	at com.liferay.portal.layoutconfiguration.util.velocity.TemplateProcessor.<init>(TemplateProcessor.java:80) ~[portal-impl.jar:?]
	at com.liferay.portal.layoutconfiguration.util.RuntimePageImpl.doProcessTemplate(RuntimePageImpl.java:175) ~[portal-impl.jar:?]
	at com.liferay.portal.layoutconfiguration.util.RuntimePageImpl.doDispatch(RuntimePageImpl.java:155) ~[portal-impl.jar:?]
	at com.liferay.portal.layoutconfiguration.util.RuntimePageImpl.processTemplate(RuntimePageImpl.java:99) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.layoutconfiguration.util.RuntimePageUtil.processTemplate(RuntimePageUtil.java:66) ~[portal-kernel.jar:?]
	at com.liferay.layout.taglib.servlet.taglib.renderer.LayoutStructureRenderer._renderDropZoneLayoutStructureItem(LayoutStructureRenderer.java:758) ~[bundleFile:?]
	at com.liferay.layout.taglib.servlet.taglib.renderer.LayoutStructureRenderer._renderLayoutStructure(LayoutStructureRenderer.java:1082) ~[bundleFile:?]
	at com.liferay.layout.taglib.servlet.taglib.renderer.LayoutStructureRenderer._renderLayoutStructure(LayoutStructureRenderer.java:1170) ~[bundleFile:?]
	at com.liferay.layout.taglib.servlet.taglib.renderer.LayoutStructureRenderer.render(LayoutStructureRenderer.java:124) ~[bundleFile:?]
	at com.liferay.layout.taglib.servlet.taglib.RenderLayoutStructureTag.processStartTag(RenderLayoutStructureTag.java:107) ~[bundleFile:?]
	at com.liferay.taglib.util.IncludeTag.doStartTag(IncludeTag.java:116) ~[bundleFile:?]
	at org.apache.jsp.render_005ffragment_005flayout.page_jsp._jspService(page_jsp.java:215) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111) ~[jasper.jar:9.0.75]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[servlet-api.jar:4.0.FR]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411) ~[jasper.jar:9.0.75]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473) ~[jasper.jar:9.0.75]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377) ~[jasper.jar:9.0.75]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[servlet-api.jar:4.0.FR]
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:328) ~[bundleFile:?]
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:340) ~[bundleFile:?]
```

scenario2:
1. Add a Materclass site
2. Go to the site from application menu

Actual result:
The page is blank, npe occurs in server console:
```
2023-07-25 08:59:59.521 ERROR [http-nio-8080-exec-5][IncludeTag:128] Current URL /web/mc generates exception: java.lang.NullPointerException
java.lang.NullPointerException: null
	at com.liferay.portal.layoutconfiguration.util.velocity.TemplateProcessor.<init>(TemplateProcessor.java:80) ~[portal-impl.jar:?]
	at com.liferay.portal.layoutconfiguration.util.RuntimePageImpl.doProcessTemplate(RuntimePageImpl.java:175) ~[portal-impl.jar:?]
	at com.liferay.portal.layoutconfiguration.util.RuntimePageImpl.doDispatch(RuntimePageImpl.java:155) ~[portal-impl.jar:?]
	at com.liferay.portal.layoutconfiguration.util.RuntimePageImpl.processTemplate(RuntimePageImpl.java:99) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.layoutconfiguration.util.RuntimePageUtil.processTemplate(RuntimePageUtil.java:66) ~[portal-kernel.jar:?]
	at com.liferay.layout.taglib.servlet.taglib.renderer.LayoutStructureRenderer._renderDropZoneLayoutStructureItem(LayoutStructureRenderer.java:758) ~[bundleFile:?]
	at com.liferay.layout.taglib.servlet.taglib.renderer.LayoutStructureRenderer._renderLayoutStructure(LayoutStructureRenderer.java:1082) ~[bundleFile:?]
	at com.liferay.layout.taglib.servlet.taglib.renderer.LayoutStructureRenderer._renderLayoutStructure(LayoutStructureRenderer.java:1170) ~[bundleFile:?]
	at com.liferay.layout.taglib.servlet.taglib.renderer.LayoutStructureRenderer.render(LayoutStructureRenderer.java:124) ~[bundleFile:?]
	at com.liferay.layout.taglib.servlet.taglib.RenderLayoutStructureTag.processStartTag(RenderLayoutStructureTag.java:107) ~[bundleFile:?]
	at com.liferay.taglib.util.IncludeTag.doStartTag(IncludeTag.java:116) ~[bundleFile:?]
	at org.apache.jsp.render_005ffragment_005flayout.page_jsp._jspService(page_jsp.java:215) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111) ~[jasper.jar:9.0.75]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[servlet-api.jar:4.0.FR]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411) ~[jasper.jar:9.0.75]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473) ~[jasper.jar:9.0.75]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377) ~[jasper.jar:9.0.75]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[servlet-api.jar:4.0.FR]
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:328) ~[bundleFile:?]
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:340) ~[bundleFile:?]
```

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
