### PR TITLE
LPS-150575 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-150575

This is only for master.

@DiegoHu97
cc @victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
updated this pr: https://github.com/liferay-echo/liferay-portal/pull/7810

**Pull request closed without merging**
