### PR TITLE
[TS] LPS-144692

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team Echo,

**Context**
Please see [LPS-144692](https://issues.liferay.com/browse/LPS-144692) for details.

To summarize, if a Web Content with a custom structure is being imported and the resulting imported custom structure does not have a matching structure key, references to Document Library images fail to be properly processed for the imported Web Content.

**Issue**
The issue has to do with how the JournalArticleExportImportContentProcessor fails to retrieve the proper DDMStructure, due to the non-matching DDM Structure Keys. This results in the referenced DL images not being processed.

The proposed fixed attempts to retrieve the updated DDM Structure Key if available.

**Additional Notes**
This PR consists of 2 sets of commits:
- Apply fix for JournalArticleExportImportContentProcessor
- Apply fix for AMJournalArticleExportImportContentProcessor

For the scenario described in LPS-144692, applying the fix for JournalArticleExportImportContentProcessor already resolves the issue. 

However, I also included the changes to AMJournalArticleExportImportContentProcessor, since it looks like the same issue would apply to that logic as well.

Feel free to let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
**Update**
Added additional commit to update unit test.

This should still maintain the original behavior: when the AMJournalArticleExportImportContentProcessor attempts to fetch a DDMStructure, null is returned.

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @ericyanLr,

Thanks for the fix, it works great!

I have resent the PR [here](https://github.com/liferay-echo/liferay-portal/pull/6900) I don't make any changes, I just solve the conflicts.

Thanks a lot!

Greetings

**Pull request closed without merging**
