### PR TITLE
LPS-113885 Add number to allowed defaultValue types

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
> AXIS_VARIABLE=0,label_exp=!master #396978
LocalFile.ContentPages#ChangeLayoutElementProperties - Poshi Report - Poshi Summary - Console Output
LocalFile.ContentPages#ViewRestrictionVisualFeedbackWhenDragSectionCardOverAnotherOne - Poshi Report - Poshi Summary - Console Output

I'm going to run these locally

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/905

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/931

**Pull request closed without merging**
