### PR TITLE
[TS] LPS-141980 Get the scoped asset counts for displaying tags with the "Color by Popularity" template

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @liferay-echo team,

I'm resending a previous PR ( https://github.com/liferay-echo/liferay-portal/pull/6341 ), with the modification suggested in the PTR.

I'm not completely sure whether this is the right solution, as I solved it by using `serviceLocator` in the FTL template. As I saw, it's still used in [some places](https://github.com/liferay/liferay-portal/search?l=FreeMarker&q=%22serviceLocator%22). Please let me know whether using a `TemplateContextContributor` would be a better solution in this case.

cc: @lfbesada , @jkappler 

Thanks,
Vendel

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @vendeltoreki,

Thanks for the PR! Looks great!

Regarding the use of the service locator, I think you are right and it would be best to avoid it. 

In this case, rather than using a TemplateContextContributor, since that service is only needed in the templates of this portlet, I think a better approach would be to overwrite in AssetTagsNavigationPortletDisplayTemplateHandler or AssetTagsCloudPortletDisplayTemplateHandler the getCustomContextObjects method to put that service in the context of all templates portlet.

https://github.com/liferay/liferay-portal/blob/2916989675f1a421b3f8d23464d4cd51e387ee24/portal-kernel/src/com/liferay/portal/kernel/template/BaseTemplateHandler.java#L43

Please could you update it accordingly with this?

Thanks!

Regards

Regards

**Comment by vendeltoreki** [comment]
Hi @lfbesada ,

I've added commit https://github.com/liferay-echo/liferay-portal/pull/6442/commits/f2322a5be1abd2766ce7e870a336d13eab09740e to remove `serviceLocator` from the template.

Thanks,
Vendel

**Review by lfbesada — APPROVED** [review]
Hi @vendeltoreki,
It works great!
Thank you!
Regards

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
