### PR TITLE
LPS-147705 Show modal when the user is trying to remove a fragment

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @Tim-Cao we have changed the confirmation message when deleting some entities, I think some test needs update, would you mind taking a look, please? Thank you😁

**Comment by Tim-Cao** [comment]
Sure. I will update them today.

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7936

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
