### PR TITLE
LPS-125552 Use window state pop_up so that only the content renders

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-125552

I wasn't sure if `p_p_state=pop_up` working the way it does with content pages is a bug, but it resolves the search issue. Please let me know if there are any questions.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Adding the on hold label as we wanted to do a google-like crawler. That includes indexing the page as a user would see it, that includes the theme too. I'm asking PMs to see if this is something that is convenient change :)

**Comment by holatuwol** [comment]
@victorg1991 : Did you receive a response from the product team?

**Comment by ealonso** [comment]
Hey @holatuwol,

Please see: https://issues.liferay.com/browse/LPS-125552?focusedCommentId=2350664&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2350664

**Pull request closed without merging**
