### PR TITLE
LPS-130624 Adapt tests

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @victorg1991, the collection items are not shown in Collection Display. Could you have a look?
*Step to reproduce:*
1. Add three web contents based on Basic Web Content
2. Add a dynamic collection with Web Content Article and All Subtypes
3. Add a content page
4. Add a Collection Display fragment
5. Select the dynamic collection

*Expected Results:*
The collection items should be shown in Collection Display

*Actual Results:*
The collection items are not shown in Collection Display
Actual

**Pull request closed without merging**
