### PR TITLE
LPS-142221 Fix stylebook preview cannot select the widget page templates

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-142221

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1287401_975

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
