### PR TITLE
LPS-113710, LPS-113962 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-113710
https://issues.liferay.com/browse/LPS-113962

This is only for master.

@p2kmgcl

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
@Tim-Cao maybe we need to update something else?

**Comment by Tim-Cao** [comment]
@ealonso These two cases are failed by a bug. The Collection Display fragment is can not be added.

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/810

**Comment by p2kmgcl** [comment]
ci:close

**Pull request closed without merging**
