### PR TITLE
LPS-126914

### PR DESCRIPTION
**Pull request by ChrisKian**
[LPS-126914](https://issues.liferay.com/browse/LPS-126914)

From @jesseyeh-liferay: 

> This fixes a regression in which Web Content fails to publish if it contains a link beginning with a non-URL scheme. To account for this, a URI is used in place of a URL, as the former is a superset of the latter.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
ci:forward

**Pull request closed without merging**
