### PR TITLE
LPD-15248 Move folder does not work in Web Content's Management Toolbar

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPD-15248)

## Steps 

- Go to Content & Data > Web Content
- Create some Web Contents and Folders
- In Web Contents view > Check the checkbox and select some items 
- See Toolbar upper > Click on move
- Choose a folder > See the content moves correctly to the desired folder

### CODE REVIEW

**Comment by veroglez** [comment]
Awesome :heart_eyes:

**Comment by veroglez** [comment]
ci:forward

**Comment by DiegoHu97** [comment]
ci:report:2530791398

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
