### PR TITLE
LPD-26920 Migrate quarantine test OpenGraphPreview.testcase

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

Analyzing and migrating the different quarantine tests within the platform. 
[Link to ticket](https://liferay.atlassian.net/browse/LPD-26648)

### Changes

Delete the poshi tests and try to replace them with backend ones.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
@BarbaraCabrera Good job :clap: I have added some SF commits, see: https://github.com/liferay-echo/liferay-portal/pull/15738

**Pull request closed without merging**
