### PR TITLE
LPS-130605 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
@p2kmgcl

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
Just a minute, I want to apply some of the changes that @victorg1991 suggested :sweat_smile:

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/4388

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/4408

**Pull request closed without merging**
