### PR TITLE
LPD-15150 Add integration tests for the url separator configuration

### PR DESCRIPTION
**Pull request by Mikellorza**
waiting to merge : https://github.com/brianchandotcom/liferay-portal/pull/146520

Description
--------
This pr contains the integration test to test the url separator save configuration process.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
Hey @Mikellorza,

I was taking a look to the tests and I have one question, why we are using a JSONObject in configuration instead of String[]?

I'm asking because you are returning a String when calling  **_friendlyURLSeparatorConfigurationManager.getFriendlyURLSeparators(_companyId)**, for me it is really confusing, since nothing said to me that I'm going to receive a JSON Object.

I was looking into the portal and I found this pattern:

```java
@Meta.AD(
		deflt = "${resource:com/liferay/account/dependencies/account_entry_invite_user_subject.tmpl}",
		description = "invitation-email-subject-description",
		name = "invitation-email-subject", required = false
	)
	public LocalizedValuesMap invitationEmailSubject();

```

Where we are returning a LocalizedValuesMap, maybe we need to find something similar for this case, What do you think?

cc: @ruben-pulido @lfbesada @jkappler

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
@Mikellorza failures seems to be related

**Comment by Mikellorza** [comment]
@ealonso  I fixed the issues that were due because some translation changes

**Comment by Mikellorza** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:2533327171

**Comment by Mikellorza** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:stable

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
