### PR TITLE
LPD-36690 Add playwright test

### PR DESCRIPTION
**Pull request by sandrodw3**
This PR is going to have conflicts with https://github.com/liferay-echo/liferay-portal/pull/16275, so as this one has less priority, I'm leaving it on hold until the other one is merged

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:test:page-management-playwright

**Comment by ealonso** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:stop

**Comment by sandrodw3** [comment]
This PR is going to have conflicts with https://github.com/liferay-echo/liferay-portal/pull/16275, so as this has less priority, I'm leaving it on hold until the other one is merged

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
