### PR TITLE
LPS-144389 UI improvements for the Simulator Device

### PR DESCRIPTION
**Pull request by veroglez**
https://issues.liferay.com/browse/LPS-144389

cc @beltranrengifo

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
No regression issues found according to [ci:test:echo](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1596867500&testrayRunId=1596867533)

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
