### PR TITLE
LPS-197200 When a widget page template is created the text of the back button tooltip is Go to Page

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-197200)

### Changes

Replace language key “pages” with “page-templates” 

## Test scenario 1 
1. Go to Design > Page Templates > Pages Templates
2. Create a page template set and a new widget page template
3. Check the back button

## Results

https://github.com/liferay-echo/liferay-portal/assets/93203423/95597ac6-c32d-4e89-a8c3-39f141dc0436

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141278

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
