### PR TITLE
LPD-19643 SignedIn segment expression not working for headless call

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
Session based segments aren't always evaluated correctly in Collection headless calls
[LPD-19643](https://liferay.atlassian.net/browse/LPD-19643)

Proposed Solution
========
Collections has its own code to map an httpRequest to a segmentsContext. This method could be replaced by the centralised requestContextMapper.map call, which has the more advanced logic to map far more information.
Based on this pattern, I've updated SegmentResource as well

Steps to Verify
========
Please check [LPD-19643](https://liferay.atlassian.net/browse/LPD-19643), sadly this is a very long scenario.

Cheers,
Balázs

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
sf isn't working locally :(

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
