### PR TITLE
LPS-138770 Ignore integration test

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
@david-gutierrez-mesa, @Tim-Cao, disabling components as I mentioned

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @jkappler  and @david-gutierrez-mesa, does this PR need to run ci:test:relevant? Could send to Brian directly after ci:test:sf passed? I'm afraid ci:foward won't pass today.

**Comment by jkappler** [comment]
Yes we can @Tim-Cao. Anything I can do to fix CI?

**Comment by Tim-Cao** [comment]
Hi @jkappler, I think nothing we could do. No need to run more time.

**Comment by Tim-Cao** [comment]
No need to run ci:test:relevant for this PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/106778

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
