### PR TITLE
LPS-138009 Show only the filters that are supported for all the selected collections

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
