### PR TITLE
LPS-180293 - Test Scenarios Coverage | Backend

### PR DESCRIPTION
**Pull request by ruben-pulido**
Based on https://github.com/brianchandotcom/liferay-portal/pull/132698#issuecomment-1497886527 error messages have been adapted after [discussion](https://liferay.slack.com/archives/C5E1CRLJY/p1681286367485629) with Headless Team

//cc @ealonso @4lejandrito

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
