### PR TITLE
LPD-15572 - Failed upgrade process for module com.liferay.layout.service from 7.0.10.6 to master

### PR DESCRIPTION
**Pull request by ruben-pulido**
https://liferay.atlassian.net/browse/LPD-15572 - Failed upgrade process for module com.liferay.layout.service from 7.0.10.6 to master

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by achaparro** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
Hi @ruben-pulido,

Your modifications make sense to me, I only have a question. The table LayoutPageTemplateEntry was created in the schema version 1.1.0, why did you choose the version 3.4.1 to wait for? I assume you need columns created after 1.1.0 and also the logic in 3.4.1 but I want to be sure about that. We must use the lower version that allows us to upgrade properly to avoid requiring other modules to wait longer than needed or create circular dependencies.

I am also executing the ci:test:upgrade suite to be sure this does not happen.

Thanks

PS: I have to work late today so I can check the results later

**Comment by ruben-pulido** [comment]
Hi @achaparro 

Thanks for taking a look at the upgrade code!

I had chosen version 3.4.1, since in that version the value of the data in the `classNameId` column is modified, and the UpgradeStep introduced (`com.liferay.layout.internal.upgrade.v1_4_2.LayoutUpgradeProcess`) uses that column to obtain the values it needs to update, so it was a "conservative" decision in terms of making sure that the data of the columns involved in the query would not be modified the `UpgradeStep` introduced had run.

However, performing a deeper analysis, I see that `com.liferay.layout.page.template.internal.upgrade.v3_4_1.LayoutPageTemplateEntryUpgradeProcess` modifies the data in the `classNameId` column, but only for those entries which had `classNameId` corresponding to `DLFileEntry`, whereas the `UpgradeStep` introduced affects only entries with `classNameId` corresponding to `Layout`.

Therefore I think it is safe to reduce the version we depend upon to 2.1.0, since that is the step in which the `plid` column is added to the `LayoutPageTemplateEntry` table, which is needed within the added `UpgradeStep`.

I am going to test this locally and will send shortly a new PR.

**Comment by ruben-pulido** [comment]
@achaparro 

Changes incorporated in https://github.com/liferay-echo/liferay-portal/pull/15086

Closing this PR.

Thanks a lot for you help!

**Pull request closed without merging**
