### PR TITLE
LPD-22610 Preserve the sitemap settings in the typesettings

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you review this fix?
https://liferay.atlassian.net/browse/LPD-22610
best,
Attila

-----

The root cause of the issue is that we override the typeSettings of the live page with the draft page and the sitemap relevant information is only stored in the live page typesetting. My solution is to preserve these settings if they exist.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
