### PR TITLE
LPS-168171 baseline

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by michaelhashimoto** [comment]
ci:reevaluate:1317401_5848

**Comment by ozysouza** [comment]
Hi @ealonso, there is a regression issue when selecting collection on Asset Publisher. Could you please have look at? 

1. Add a Dynamic Collection for Web Content Article and Basic Web Content
2. Add an Asset Publisher to widget page
3. Select Collection in Asset Collection
4. Select the Dynamic Collection

The Collection is not shown
The order of the tabs are changed, Collection Providers is coming first, it should be after Collections tab.

https://user-images.githubusercontent.com/72820234/201408446-f99635a7-e36a-49ff-b27f-1cdeca4306b4.mp4

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
Hi @ealonso, there is one related failure on the PR. Could you please have a look at? It's the below unit test.

`com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageEditorDisplayContextTest > testGetInfoItemClassNames FAILED
    java.lang.NoSuchMethodException: No method on null with name _getInfoItemClassNames and parameter types []
        at com.liferay.portal.kernel.test.ReflectionTestUtil.getMethod(ReflectionTestUtil.java:190)
        at com.liferay.portal.kernel.test.ReflectionTestUtil.invoke(ReflectionTestUtil.java:217)
        at com.liferay.layout.content.page.editor.web.internal.display.context.ContentPageEditorDisplayContextTest.testGetInfoItemClassNames(ContentPageEditorDisplayContextTest.java:91)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
`

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
Hey @ozysouza,

Thanks you very much!! you are helping me a lot with this pr, I've really appreciate it.

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/126312

**Pull request closed without merging**
