### PR TITLE
LPS-180062 Parent fields shouldn't be editable

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-180062)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:echo

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:reevaluate:1397401_3971

**Comment by Tim-Cao** [comment]
ci:forward:force

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132695

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
