### PR TITLE
LPS-184487 Extract DDMTemplateResourceParser from portal

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-184487 Create PortletDisplayTemplateUtil class and apply usage
- LPS-184487 Uses dynamic data mapping modules portlet display template classes
- LPS-184487 Moves DDMTemplateResourceParser to dynamic data mapping modules
- LPS-184487 Make it a component
- LPS-184487 Moves DDMTemplateResource to dynamic data mapping api module
- LPS-184487 Uses service methods instead of template manager
- LPS-184487 Removes unused DDMTemplateManager
- LPS-184487 Uses DDMTemplateConstants
- LPS-184487 Use references
- LPS-184487 Uses dynamic data mapping modules portlet display template classes
- LPS-184487 baseline

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Failures are not related, pushed to BChan directly at https://github.com/brianchandotcom/liferay-portal/pull/135273

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
