### PR TITLE
LPS-162123 Corrected language key translation.

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
FWD: https://github.com/fortunatomaldonado/liferay-portal/pull/49
https://issues.liferay.com/browse/LPS-162123

Hello,

I am not too sure how we handle incorrect translations, so I am sending here. 
Let me know if I should send it elsewhere or if we have a different method to go about this.

Thank you!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
Hey @fortunatomaldonado,
I'm not completely sure about what should be the process, Could you please add a question into slack about it? #product-delivery can be a good channel for it, by the way I'm going to forward it.

**Comment by ozysouza** [comment]
ci:forward

**Comment by fortunatomaldonado** [comment]
Hello @ozysouza and @ealonso,

I was able to find that there is no need to send PR. Crowdin was updated and the translation will be updated.
Information can be found here: https://liferay.slack.com/archives/CN3HAAXEU/p1666635050036539?thread_ts=1666634032.649069&cid=CN3HAAXEU

**Pull request closed without merging**
