### PR TITLE
LPS-104151 Removes feature flag and enable new data engine editor on web content

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:test:bundle

**Comment by austinchiang** [comment]
ci:test:bundle:norebase

**Comment by liulukiwi** [comment]
There's conflict issue, could you check about this? @ealonso

**Comment by ealonso** [comment]
Hey @liulukiwi,

We don't want to send it to Brian, we need to fix the Poshi errors first. And then when we finish the migration send it to Brian.

The idea is start working on Poshi updates while we are finishing the migration to have it prepare.

Regards,
Eudaldo.

cc: @manoelcyreno

**Comment by manoelcyreno** [comment]
@liulukiwi , this PR is related to change the DDM to Data Engine migration.
currently, we are in the test phase... One time that the things start to be stable, we will start the poshi migration, so for now, is something like Eudaldo told, we not want to send it to Brian.

**Comment by adolfopa** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by liulukiwi** [comment]
Hi @ealonso 

https://github.com/liferay-echo/liferay-portal/pull/567/commits/3d15a9f3b64e6a69d9e8f045d5c4caa3b3ab59b8
This commit makes property tab not available.
properties
 And there's also error in console:
`2020-07-10 09:10:24.825 ERROR [http-nio-8080-exec-5][render_portlet_jsp:131] null
javax.portlet.PortletException: Path /data_engine/basic_info_data_engine_editor.jsp is not accessible by portlet com_liferay_journal_web_portlet_JournalPortlet
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:568)
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.include(MVCPortlet.java:589)
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.doDispatch(MVCPortlet.java:463)
        at com.liferay.journal.web.internal.portlet.JournalPortlet.doDispatch(JournalPortlet.java:236)
        at javax.portlet.GenericPortlet.render(GenericPortlet.java:291)
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.render(MVCPortlet.java:305)
        at com.liferay.journal.web.internal.portlet.JournalPortlet.render(JournalPortlet.java:168)
        at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:127)
        at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:58)
        at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:124)
        at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:71)
        at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
        at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
        at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:62)
        at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120)
        at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48)
        at com.liferay.portlet.internal.InvokerPortletImpl.invoke(InvokerPortletImpl.java:571)
        at com.liferay.portlet.internal.InvokerPortletImpl.invokeRender(InvokerPortletImpl.java:661)
        at com.liferay.portlet.internal.InvokerPortletImpl.render(InvokerPortletImpl.java:344)`

**Comment by ealonso** [comment]
Hey @liulukiwi,

Sorry for the late response, but I miss this one 😞 .

I've just updated the pr fixing the error.

**Comment by ealonso** [comment]
Hey @manoelcyreno @liulukiwi 

Please see: https://github.com/liferay-echo/liferay-portal/pull/1518

**Pull request closed without merging**
