### PR TITLE
LPS-144629 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-144629

This is only for master.

@david-gutierrez-mesa
@john-co
cc @zhangyan0701
cc @victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional

**Comment by Tim-Cao** [comment]
All failure cases from ci:test:relevant are caused by https://issues.liferay.com/browse/LPS-147045

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:echo

**Comment by john-co** [comment]
ci:test:acceptance-functional

**Comment by john-co** [comment]
rerunning since https://issues.liferay.com/browse/LPS-147045 is no longer reproducible

**Comment by Tim-Cao** [comment]
No failure cases related the changes according to [ci:test:echo](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1644465831058&testrayRunIdA=1609424898&testrayRunIdB=1609571345)

**Comment by Tim-Cao** [comment]
Hi @john-co, @david-gutierrez-mesa and @victorg1991, poshi updates are finished.

**Comment by victorg1991** [comment]
resent here: https://github.com/liferay-echo/liferay-portal/pull/7237

**Pull request closed without merging**
