### PR TITLE
LPS-197303 Check new permission

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
sorry @victorg1991, my bad

**Comment by liulukiwi** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141371

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
