### PR TITLE
LPS-147517 Modify locators to make them reusable

### PR DESCRIPTION
**Pull request by victorg1991**
Deploy asset-taglib

1. Create a some categories and vocabularies
2. Create a couple of web contents one with category and one without it
3. Create a widget page
4. Add an asset  publisher and configure it to be dynamic
5. Add a category filter widget
6. Press the category that you have set in the web content
7. The page should be reload and the asset publisher should be filtered by that category

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:stop

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Tested on Safari and works as expected!

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
