### PR TITLE
LPD-20123 Improve PortalImpl.getBrowsableLayout method

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-20123

Dear reviewed :heart: 

The performance improvement could be asserted using the integration tests added in [LPD-20057](https://liferay.atlassian.net/browse/LPD-20057).

As a reference, [here](https://github.com/liferay-echo/liferay-portal/pull/15339#issue-2179238968) is the previous test results. 

- With default settings (DEPTH = 5, LEVEL_LENGTH = 5)

**Previous performance test results:**

image

**Current performance test results:**

image

- With a heavier hierarchy (DEPTH = 25, LEVEL_LENGTH = 25)

**Previous performance test results:**

image

**Current performance test results:**

image

Regards

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:report:2549217652

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:report:2549373182

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:report:2549419584

**Comment by brittneyq** [comment]
ci:report:2549419584

**Comment by lfbesada** [comment]
ci:forward:force

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
