### PR TITLE
LPS-142416 Remove feature flags

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-142416
This PR removes the feature flags that keep this epic hidden:
https://issues.liferay.com/browse/LPS-137494
By now, I won't run the CI because it will surely fail.
@Tim-Cao @david-gutierrez-mesa could you please adjust the tests to adapt them to the removal of the feature flags?
Thanks a lot!

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7245

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
