### PR TITLE
LPD-21140 - Site initializer adding same globalJS client extension entry in master page template configuration every time we run site initializer

### PR DESCRIPTION
**Pull request by ruben-pulido**
https://liferay.atlassian.net/browse/LPD-21140 - Site initializer adding same globalJS client extension entry in master page template configuration every time we run site initializer

Original PR description: https://github.com/liferay-echo/liferay-portal/pull/15399#issue-2201117690

**Additional Scenarios Reproduction Steps:**

The issue can be reproduced as well outside of Site Initializer.

**Steps Scenario 1:**

1. Deploy Liferay Sample Global JS CX
2. Go to Design > Page Templates > Master > and create a Master Page
3. Go to Page design options(Left side menu 3rd option) and click on setting gear icon
4. Now go to Customization section and click on Javascript tab
5. Add Liferay Sample Global JS 
6. Publish master page
7. Export master page
8. Import master page selecting “Overwrite Existing Items”

**Expected result:**
There is one entry for Liferay Sample Global JS and no additional CX entries will be added every time we run site import with “Overwrite Existing Items”

**Actual result:**
There are two entries for Liferay Sample Global JS and it will add same CX entry every time we run site import with “Overwrite Existing Items”

We should also account for the fact that the configuration of the CX relationship may have been changed on a subsequent import.

**Steps Scenario 2:**

1. Deploy Liferay Sample Global JS CX
2. Go to Design > Page Templates > Master > and create a Master Page
3. Go to Page design options(Left side menu 3rd option) and click on setting gear icon
4. Now go to Customization section and click on Javascript tab
5. Add Liferay Sample Global JS 
6. Change Load to async 
7. Publish master page
8. Export master page
9. Go to Page design options(Left side menu 3rd option) and click on setting gear icon
10. Now go to Customization section and click on Javascript tab
11. Change Load  to defer
12. Save
13. Publish master page
14. Import master page selecting “Overwrite Existing Items”

**Expected result:**
There is one entry for Liferay Sample Global JS with load "async" and no additional CX entries will be added every time we run site import with “Overwrite Existing Items”

**Actual result:**
There are two entries for Liferay Sample Global JS (one with load "defer" and one with load "async") and it will add same CX entry every time we run site import with “Overwrite Existing Items”

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
shouldn't [LayoutStagedModelDataHandler#_importClientExtensionEntryRels](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/exportimport/data/handler/LayoutStagedModelDataHandler.java#L2042) be removing the ClientExtensionEntryRel?

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:report:2554934546

**Comment by lfbesada** [comment]
ci:reevaluate:1317401_10652

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
