### PR TITLE
[7.4.x only] LPS-123094 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-123094

This is only for master.

@p2kmgcl

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, could you check again? The same issue happens with https://github.com/liferay-echo/liferay-portal/pull/2830

**Comment by p2kmgcl** [comment]
@Tim-Cao these are failing because of CSS class renaming (I think all of them):

https://testray.liferay.com/reports/production/logs/test-1-8/1605689472341/test-portal-acceptance-pullrequest(master)/6558/functional-tomcat90-mysql57-jdk8/0/14/LocalFile.WebContentTemplates_SaveChangesInExistingTemplateWhenDisableTemplateCreation/summary.html.gz

https://testray.liferay.com/reports/production/logs/test-1-8/1605689472341/test-portal-acceptance-pullrequest(master)/6558/functional-tomcat90-mysql57-jdk8/0/5/LocalFile.WebContentExportImport_AddCreatedStructureForImportedTemplate/summary.html.gz

https://testray.liferay.com/reports/production/logs/test-1-8/1605689472341/test-portal-acceptance-pullrequest(master)/6558/functional-tomcat90-mysql57-jdk8/0/5/LocalFile.WebContentExportImport_ImportAndUseGlobalStructureAndTemplate/summary.html.gz

https://testray.liferay.com/reports/production/logs/test-1-8/1605689472341/test-portal-acceptance-pullrequest(master)/6558/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.WebContentTemplates_AddTemplateWithStructure/summary.html.gz

https://testray.liferay.com/reports/production/logs/test-1-8/1605689472341/test-portal-acceptance-pullrequest(master)/6558/functional-tomcat90-mysql57-jdk8/0/6/LocalFile.WebContentWithCustomStructures_EditContentWithTitleAndAllFieldsNull/summary.html.gz

https://testray.liferay.com/reports/production/logs/test-1-8/1605689472341/test-portal-acceptance-pullrequest(master)/6558/functional-tomcat90-mysql57-jdk8/0/8/LocalFile.WebContentWithPermissions_AddAndViewStructureAndTemplateWithPermissions/summary.html.gz

**Comment by Tim-Cao** [comment]
@p2kmgcl 
The selected structure is not shown in field.
Actual

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/2944

**Pull request closed without merging**
