### PR TITLE
LPS-126178

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @liferay-echo,

Attached is an update for http://issues.liferay.com/browse/LPS-126178.

Without fix:
image

With fix:
image

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @jonmak08 thanks! I've sent a new pr here: https://github.com/liferay-echo/liferay-portal/pull/3777 
I've seen that this fix worked for this specific case but it was still failing for others, so I went ahead and try to fix all :)

**Pull request closed without merging**
