### PR TITLE
LPS-66138 Update the layout template to the default one if it doesn't exist when we are rendering the page

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by matthiasblaesing** [comment]
@ealonso not sure if this is the right place to comment, but I found a regression caused by this fix. We noticed, that since a few months our liferay system loses the configured layouts when the theme is hot-deployed.

We observe, that that the affected page show the default layout instead of the originally configured layout. Only pages which are configured for a non-standard layout are affected.

After I read the description here and had a look at the implementation I think this is what happens:

1. We push our updated theme to the "deploy" folder
2. The liferay autodeployer stops the old version of the theme
3. A user opens an affected page. Now the code added here kicks in: The layout is not present and thus the layout of the page is reset to the default layout.
4. The liferay autodeployer finishes the deployment and starts the theme again

The layout is still there, but the page is now broken by step 3. This was not a problem until this change, as between steps 2 and 4 liferay rendered a degraded version of the page for a very short time and after step four the page returned to the correct rendering. Now rendering is permanently broken.

So can you please revisit this?

**Comment by Emmaliu** [comment]
@matthiasblaesing https://issues.liferay.com/browse/LPS-169365 this should fix the behavior mentioned.

**Comment by matthiasblaesing** [comment]
@Emmaliu thank you for the notification, indeed I tested the fix changeset directly and found it fixed there and did a quick test of our installation and it seems the fix also works there. Thanks again.

**Pull request closed without merging**
