### PR TITLE
LPS-114072 Replace layout classes with new clay components in layout-admin-web

### PR DESCRIPTION
**Pull request by eduardoallegrini**
This is a simple code replacement of the layout classes with the new Clay Layout Component, you can see the previous local tests in https://github.com/liferay-frontend/liferay-portal/pull/53

Can you verify that the modules are rendering correctly and we aren't breaking anything?

### CODE REVIEW

**Comment by victorg1991** [comment]
We'd like to work until the release is out to merge this @eduardoallegrini is that ok?

**Comment by eduardoallegrini** [comment]
ok, thank you!

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
reviewing :)

**Comment by victorg1991** [comment]
resent here https://github.com/liferay-echo/liferay-portal/pull/1344

**Comment by victorg1991** [comment]
Good job :)

**Comment by victorg1991** [comment]
ci:close

**Pull request closed without merging**
