### PR TITLE
LPS-137397 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-137397

This is only for master.

@victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:reevaluate:1267401_52

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
