### PR TITLE
LPD-17673 Multiple DLFileEntry versions causes duplicate constraints during Asset Display Upgrade(3.0.0)

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-17673

cc: @javalosjr96

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:report:2538710363

**Comment by lfbesada** [comment]
ci:report:2538642192

**Comment by lfbesada** [comment]
ci:report:2538726049

**Comment by lfbesada** [comment]
ci:forward:force

**Comment by lfbesada** [comment]
There is no unique failures at  relevant test suite eirther the upgrade one, so I am forcing the forward.

**Pull request closed without merging**
