### PR TITLE
[TS] LPP-46108 > LPS-159985 JavaScript set in the site template is not properly propagated

### PR DESCRIPTION
**Pull request by locpham97**
Dear Team,
Could you review this?

https://issues.liferay.com/browse/LPS-159985

Thanks,
Loc
====================================================
**Steps to reproduce**
 1. Navigate to Control Panel > Site > Site Template
 2.  Add a site template
 3. Open site template created in step 2
 4. Navigate to Site Builder > Pages
 5. Choose + > Add Site Template Page > Full Page Application
 6. Paste the following code on the Advanced tab > JAVASCRIPT field and save
`$(function(){
    $(document).on('contextmenu',function(e){
        return false;
    });
    $document.on('dragover',function(e){
      return false ;
    });
    $document.on('drop',function(e){
      return false ;
    });
});`
 7. Navigate to Control Pane > Sites > Sites
 8. Create a site using the site template added in step 2
 9. Navigate to created site
 10. Open "Configure" on the default（Home）page

**Actual result**
 Some contents of JAVASCRIPT have been deleted.
**Expected result**
 The contents of JAVASCRIPT will be properly propagated.
 
 This is reviewed in https://github.com/liferay-staging/liferay-portal/pull/101
 cc:@chileces

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by locpham97** [comment]
ci:test:relevant

**Comment by locpham97** [comment]
ci:test:sf

**Comment by locpham97** [comment]
ci:test:stable

**Comment by locpham97** [comment]
ci:test

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1257401_4343

**Review by lfbesada — APPROVED** [review]
Hi @locpham97 
Thanks for the fix! 
Sorry for the late review, LGTM
Regards

**Comment by lfbesada** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:reevaluate:1307401_4424

**Comment by ozysouza** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:reevaluate:1297401_4356

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
