### PR TITLE
LPS-131994 Remove empty div if not needed

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
@p2kmgcl - Some of the builds were aborted in this pull request test. Please retest if results needed. Sorry for any inconvenience.

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
