### PR TITLE
LPD-8428 Migrate ContentPagesWithUndoRedo to Playwright

### PR DESCRIPTION
**Pull request by NemethNorbert**
Analyzation of the poshi test file:

`RedoInteractionStates`: It's testing the undo redo button work
`'UndoAllInteractionStates':` It's testing the same thing with the addition of wether undo or redo is disabled once there are no corresponding action
`UndoDeletedCollectionDisplay`, `UndoDeletedFragmentAndWidget`, `UndoDeletedFragmentComposition`: Testing Deleting Fragments and Redoing the action
`UndoDeletedFragmentWithCustomConfiguration`, `UndoDeletedFragmentWithInlineContent`, `UndoDeletedFragmentWithMappedContent`: These tests are redundant as fragment configuration, mapping and inline content are all saved in the same place, so testing one of them implies the other two will work as well
`UndoInteractionStatesHundredTimes`: Testing a hard cap, but we already have a unit test for it
`ViewUndoInteractionStatesClearedAfterRefreshPage`: Testing the Undo Interaction state after a page refresh

I created 3 tests in playwright to cover the above test cases:

`'View Undo interaction state is cleared after refreshing the page' `: Testing the Undo Interaction state after a page refresh
`'Undo and Redo buttons work as expected'`: Testing the Undo and Redo button disabled state with deleting a configured Tabs Fragment
`'Undo history works as expected'`: Testing the History dropdown list functionality and if the current history state is disabled by cahnging the configuration of a heading fragment

With the test `'Undo history works as expected'`, I run into some hydration issue, as while the fragment configuration change was happening the select field for the heading level remained ineractible.
I resolved it by asserting the configuration change every time the test changed it, however it feels like I hid an issue away from the test. What do you think?

cc @sandrodw3

Please review it

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by NemethNorbert** [comment]
Hey @sandrodw3,

Thank you for the detailed review and the requested changes. I force pushed them. I also made some additional assertions to make sure the tests always pass. Right now interactions that requires a rerender of a given fragment/widget does not disable all the operations. For example changing the Heading style of a fragments does not make the select field disabled while the operation is undergoing. To prevent flaky tests, I made assertions to validate the change we did, forcing playwright to wait for the UI to be operational again.

Please review this commit: [f084760](https://github.com/liferay-echo/liferay-portal/pull/15079/commits/f0847607a003b2474fd38f8e5afcd50492348c67)

**Comment by sandrodw3** [comment]
Awesome 😍

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
