### PR TITLE
Revert "LPS-127677 Disable submit buttons before submitting the form, an reenable then after"

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The failure task is unrelated to this PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/107021

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
