### PR TITLE
[TS] LPS-161362 | LayoutModelDocumentContributor creates new portletPreferences for private content pages

### PR DESCRIPTION
**Pull request by bakayattila**
hi Team,
Could you review this?

https://issues.liferay.com/browse/LPS-161362

Best,
Attila

--------

**Reproduction steps:**
1. Create a Private content page with an asset publisher on it
2. publish the page
3. Check the portletPreferences related to the asset publisher in the DB

**Expected result:** There are two portletPreferences for the asset publisher 
**Actual result:** There are three portletPreferences for the asset publisher one for the draft page, one for the live page, and one with plid = 0

The root cause of the issue is that the LayoutModelDocumentContributor uses a themeDisplay inherited from the system layout. Because of this the FragmentEntryRender portlet believes it should use an inheritedfromMaster portletPreferences and creates a new shared portletPreferences for the widget.
[FragmentPortletRendererImpl.java#L63-L67](https://github.com/liferay/liferay-portal/blob/master/modules/apps/fragment/fragment-impl/src/main/java/com/liferay/fragment/internal/renderer/FragmentPortletRendererImpl.java#L63-L67)
[RuntimeTag.java#L319-L330](https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/com/liferay/taglib/portletext/RuntimeTag.java#L319-L330) // this is where the inheritedFromMaster is used

To fix the issue I modified the themeDisplay in the request created for the contributor and changed the layout and the plid in the new request's themeDisplay to the one we actually try to index.

Additionally, I also added the layout to the request just to be safe with [PortletPreferencesFactoryImpl.getPortletPreferencesIds](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/PortletPreferencesFactoryImpl.java#L448-L455).

[PortletFragmentEntryProcessor.java#L423-L430](https://github.com/liferay/liferay-portal/blob/master/modules/apps/fragment/fragment-entry-processor/fragment-entry-processor-portlet/src/main/java/com/liferay/fragment/entry/processor/portlet/PortletFragmentEntryProcessor.java#L423-L430)

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1327401_5424

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@bakayattila @lfbesada merged to master, one change from me in 28caff603339b7cfbcfb188ffb86f9e1706d6eb5

**Pull request closed without merging**
