### PR TITLE
LPS-117757 Also take into account for update data definitions

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ealonso, the description of structure is not shown in Description column of structure entry.

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ealonso, The above issue can not be reproduced on HEAD.

**Comment by Tim-Cao** [comment]
Rebased then resent https://github.com/liferay-echo/liferay-portal/pull/3219

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
