### PR TITLE
LPS-179556 Unnecessary warning and error messages fix

### PR DESCRIPTION
**Pull request by YurenaC**
Motivation
=======
[Link to ticket](https://issues.liferay.com/browse/LPS-179556)

Bug fixing: The mentioned test throws different error and warning messages while executing. Those messages are expected but confuse the CI as they look as a test error. 

Proposed Solution
========
Catch those error messages produced by the test so it won't interferer with the CI own checks.

Steps to Verify
========

1. Run testAddInfoItemStrutsActionCaptchaException located in AddInfoItemStrutsActionValidationTest.

**Actual result:**
Several warning and one error message is shown in the server log.

**Expected:**
No warning or error messages are shown in the server log.

Commits
========
- LPS-179556 Catching unnecessary forced error log in captcha test
- LPS-179556 Adding content type to mockHttpServletRequest to avoid noisy and not needed warning messages

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
https://github.com/liferay-echo/liferay-portal/pull/11578

**Pull request closed without merging**
