### PR TITLE
LPS-117884 Introduce a more powerful framework for verification of InfoItemCapabilities, allowing each of them to do their own validation (rebased 2)

### PR DESCRIPTION
**Pull request by JorgeFerrer**
cc: @jkappler @csierra

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:forward

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/1743

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
