### PR TITLE
[TS] LPS-167839 | Can't add assets to collections after upgrade from 7.2

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-167839
Thank you!

-------

**Steps to reproduce:**

1. Start a 7.2 bundle
2. Create a manual collection in Site administration -> Content and data -> Content sets
3. You will see a 'Select' button where you can add assets to the collection
4. Shut down the server and upgrade it to 7.4 or master
5. Check the collection in Site builder -> Collections

**Expected behavior:** Select button should still be there
**Current behavior:** Select button is not available

Note:

To upgrade to master, just use the upgrade.database.auto.run=true property in your master bundle

The root cause of the issue is that on the older version we did not force the user to decide the type of the collection. As a result, the typesettings related to the asset list are empty for the migrated asset lists.
There is a fallback logic for the empty typesettings but because of the StringUtil.split in the code, we will never receive a null. I changed the code to see whether or not we got an empty string array as a result of the StringUtil.split and if we did I fallback to the _getDefaultClassNameIds.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
@bakayattila Thanks for the fix! 🎉

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
