### PR TITLE
LPS-178839 - Rely on Headless transaction rather than creating transaction on SiteResourceImpl

### PR DESCRIPTION
**Pull request by ruben-pulido**
TransactionContainerRequestFilter is already creating a transaction for POST requests so there is no need to crate a separate transaction on SiteResourceImpl.

A drawback is that transactions can be deactivated via HTTP Header X-Liferay-Transaction-Disabled, potentially leading to an inconsistent state.

We need to discuss if we are OK with this, and can therefore simplify the code.

//cc @ealonso @jkappler @lfbesada

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
