### PR TITLE
LPS-128816 Fix method call

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:reevaluate

**Comment by Tim-Cao** [comment]
ci:reevaluate:1077401_6859

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
