### PR TITLE
LPS-176242 Refuse exporting public pages while private export process

### PR DESCRIPTION
**Pull request by DaniSzimko**
[LPS-176242](https://issues.liferay.com/browse/LPS-176242)

forwarding from: https://github.com/liferay-staging/liferay-portal/pull/266

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
@DaniSzimko, can you please configure so that your commits are verified? Otherwise the PR will get rejected when sending to BChan

**Comment by DaniSzimko** [comment]
I signed the commit and force pushed it.
Thank you @jkappler

**Comment by lfbesada** [comment]
Hi @DaniSzimko 
Thanks for coming to us with this.
We are analyzing this bug and its cause in order to address it with a robust solution.
I'm afraid it will take a bit longer as it is a complex problem, but we are working on it.
Thank you for being so patient.
Regards

**Comment by jkappler** [comment]
@DaniSzimko, we went with your proposal, just did a small simplification

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/13507

**Pull request closed without merging**
