### PR TITLE
LPS-136106 Add info list basic table taglib

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
Related ticket: https://issues.liferay.com/browse/LPS-136106

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Hi @ealonso, @jkappler and @JorgeFerrer, could any of you take a look on this? You are the guys who knows the context. Thanks!

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by rodrigocunhaa** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
Hey guys, the test error doesn't seems to be related, it may be a flaky test as can be checked in his [history](https://testray.liferay.com/home/-/testray/case_results/1550677236/history?tab=result&hideFilterPin=true) on Testray.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/5383

**Pull request closed without merging**
