### PR TITLE
LPS-140916 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-140916

This is only for master.

@robertoDiaz
@ruben-pulido

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
@robertoDiaz, please see changes in https://github.com/liferay-echo/liferay-portal/pull/6431

**Pull request closed without merging**
