### PR TITLE
LPS-156019 Terms of use

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-156019 Adds new module for utility pages, the idea of this module if allow users override admin screens, like, term of use, 404 pages, ...
- LPS-156019 Copy terms_of_use.jsp from portal-web no logic changes
- LPS-156019 Removes terms_of_use struts paths
- LPS-156019 Apply changes
- LPS-156019 Register terms of use struts action
- LPS-156019 Uses reference
- LPS-156019 build.gradle
- LPS-156019 Render terms of use using the theme
- LPS-156019 It is not necessary
- LPS-156019 Removes no needed files
- LPS-156019 Not used
- LPS-156019 Instead of calling the jsp that was moved, copy the HTML for the view
- LPS-156019 Adds specific module. We will have more utility pages in the future, such as 404 or error pages
- LPS-156019 Not needed
- LPS-156019 We moved to a specific module, so it's no longer needed to have a separate directory. Remove also the default jsp since it's only used in one place

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by ealonso** [comment]
cc @lfbesada @ruben-pulido

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
