### PR TITLE
LPS-155827 Fix Poshi Automation | master

### PR DESCRIPTION
**Pull request by ozysouza**
https://issues.liferay.com/browse/LPS-155827

cc @david-gutierrez-mesa 
cc @Tim-Cao

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
Hi @ozysouza, keep it on hold, since there is a [regression issue](https://issues.liferay.com/browse/LPS-155861) caused by https://issues.liferay.com/browse/LPS-155252

**Comment by Tim-Cao** [comment]
Let me refactor our case @jkappler

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/8454

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
