### PR TITLE
LPS-133715 Hide breadcrumb in public pages tab when configuring a Display Page for Web Contents

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-133715

Adds a property to LayoutItemSelectorCriterion to enable breadcrumb in layouts item selector. By default it is enabled and is specifically disable in web content display page selection.

This PR change part of the solution to https://issues.liferay.com/browse/LPS-127467 --> PR: liferay-lima#1640

Old PR: https://github.com/liferay-echo/liferay-portal/pull/4819

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
