### PR TITLE
LPS-154986 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-154986

This is only for master.

@p2kmgcl
cc @victorg1991

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl and @victorg1991, there is a regression issue found by cases.
Would you mind having a look at?
The theme section is still shown after change to custom master
**Steps to reproduce**

1. Add a master page with some fragments
2. Add a content page based on Blank
3. Navigate to Look and Feel settings via Page Design Options
4. Change to custom master without save

Expected Results:
The theme section should be hidden.

Actual Results：
The theme section is still shown.

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, could you cherry-pick these commits on yours after resolve the regression issue and conflict issue? Thanks
https://github.com/liferay-echo/liferay-portal/compare/8607651c67c2edcb7aaec66070e91c245e0cf17d...ebf7b1753f685662998197255589a2ff57ac2e8a

**Comment by p2kmgcl** [comment]
:+1: sure

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/8354

**Pull request closed without merging**
