### PR TITLE
[TS] LPS-148543

### PR DESCRIPTION
**Pull request by jcampoy**
https://issues.liferay.com/browse/LPS-148543

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @jcampoy  This seems a bit risky to do 🤔  Since lfr-editable has been included in liferay since at least 3 major versions, This is probably to break some of the customer fragments. Couldn't the customer create a different fragment without lfr-editable?

**Comment by victorg1991** [comment]
Given that using data-lfr-editables solves this situations I don't think we should change the behaviour of the lfr-editable tag

**Comment by jcampoy** [comment]
hey @victorg1991 , I have already talked this subject with @ealonso and he agreed.

we are going to include important changes in the documentation when we deliver/release this change to customers, but with the current code we generate wrong html markup, and some gubernamental organizations and others working with blinds are reporting accessibility problems because of this markup. 

Let me know if you have any doubt.
BR.

**Comment by jcampoy** [comment]
@victorg1991  i have fixed the test, see https://github.com/liferay-echo/liferay-portal/pull/7429

**Pull request closed without merging**
