### PR TITLE
LPS-118272 Adapt tests

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @pavel-savinov , there is a regression issue, when add a widget to content page, the following browser error is thrown.
BrowserConsole

**Comment by sandrodw3** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/1852

**Pull request closed without merging**
