### PR TITLE
LPS-176193 Welcome Site initializer should create its images in specific folder

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-176193)

The proposal is to move the default images inside a folder called "Provided by Liferay" to align with the OOTB and also, so that the DM root folder doesn't look too wild and untidy to customers.

## Change summary:

* Move images to the Provided by Liferay folder and adapt page definition

## Test Scenario

* Start a vanilla bundle or create a new site based on Welcome Site Initializer
* Go to Documents and Media
* A folder "Provided by Liferay" should be present with several images
* Go to Home Page, the tree image should be shown
* Edit the default 404 utility page, the images should be shown

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@david-gutierrez-mesa, @liulukiwi, @Tim-Cao, @alessandromalves, moved the images to a specific folder (like the image). This might (maybe) break some tests. The only tree.png that I could find in poshi was related to DM, so not sure if they are using the image or not.

Thanks y'all    

Screenshot 2023-02-20 at 21 39 38

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
