### PR TITLE
LPS-138258-2 Render information templates

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-138258

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lfbesada** [comment]
ci:test:relevant

**Pull request closed without merging**
