### PR TITLE
LPD-22783 Add methods to Playwright to create vocabularies, categories and tags

### PR DESCRIPTION
**Pull request by veroglez**
In this PR, new methods are added to playwright to create vocabularies, categories and tags. They are also added to be able to create a Web Content directly with categories and tags.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
Hey @veroglez this looks amazing 😍 just two quick things:
- For the `categories` param, as its expecting the ids I think it would be more clear to name it `categoryIds`, what do you think?
- For the types you added in `categorization.d.ts`, instead of declaring them globally, we could just place them in the files they are being used. Or are you sure they will be used elsewhere?

**Comment by veroglez** [comment]
@sandrodw3

> For the categories param, as its expecting the ids I think it would be more clear to name it categoryIds, what do you think? 

Sounds good! I've updated the name of both `categories` and `tags`: `categoryIds` and `tagIds`.

> For the types you added in categorization.d.ts, instead of declaring them globally, we could just place them in the files they are being used. Or are you sure they will be used elsewhere?

yes, well seen! I've removed it and added the type to each file

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:playwright

**Comment by veroglez** [comment]
ci:test:playwright

**Comment by veroglez** [comment]
ci:forward:force

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:forward:force

**Pull request closed without merging**
