### PR TITLE
[TS] LPS-156240

### PR DESCRIPTION
**Pull request by jonathanmccann**
Previous - https://github.com/liferay-echo/liferay-portal/pull/8522

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
Hi @jonathanmccann 
Could you please explain your solution and how to verify it? We have a [PR template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md), it would be great if you used it.
Thank you very much!

**Comment by jonathanmccann** [comment]
@lfbesada Please let me know if there are any other questions or concerns.

**Motivation**

These changes are for https://issues.liferay.com/browse/LPS-156240 where editing a Journal Article within a publication causes it to no longer be displayed in an Asset Publisher in the main publication. This is causing significant issues for the client since they are unable to make modifications to their existing articles without destroying their production site.

**Proposed Solution**

Since this is a caching issue (as evidenced by clearing the database cache resolving the missing articles) we need to make sure we are working with the correct Asset Entry and Change Tracking Collection. This is done by fetching the Asset Entry and then updating it to ensure it has the correct `ctCollectionId`.

The current behavior is problematic because we are working with an Asset Entry with a `ctCollectionId` of `0` and then updating it's title and visibility but we should be modifying an entry whose `ctCollectionId` matches with the currently selected publication.

Although everything ends up correct in the end, the cache is populated with an incorrect value causing the issue.

**Steps to Verify**

1. Go to Menu - Applications - Publications and enable Publications
2. Create a new Basic Web Content named "Web Content 1"
3. Put an Asset Publisher on the home page and open the Configuration
4. Choose the _manual_ option under Asset Selection tab and select the newly created web content
5. Publish the page
6. Create a new Publication
7. Edit the previously created Web Content and change title to "Web Content 2"
8. Visit the home page as a guest
9. Assert there is no Journal Article displayed

**Alternative Solutions that were discarded**

https://github.com/liferay-echo/liferay-portal/pull/8522

**Comment by lfbesada** [comment]
Following the steps in the issue description, the bug does not reproduce in the current master. See: https://issues.liferay.com/browse/LPS-156240?focusedCommentId=2707917&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2707917

**Pull request closed without merging**
