### PR TITLE
LPD-4587 On displaying a Utility Page its SEO configuration must be applied

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-4587

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
I am going to run the test to advance detecting problems :candle:

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:report:2529941759

**Comment by lfbesada** [comment]
ci:report:2530178979

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:report:2530504804

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
