### PR TITLE
LPD-21288 Quarantine failing web content management tests

### PR DESCRIPTION
**Pull request by john-co**
**Description**
Quarantine failing release tests to reduce impact on release testing analysis. Please unquarantine the tests as each fix is implemented in their respective follow up tickets.

**JIRA Ticket**
https://liferay.atlassian.net/browse/LPD-21288

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by john-co** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Hey @john-co,

Echo is not the owner of all tests that you modified. Could you please split the pr and send it to the proper teams?

Analytics Cloud - @liferay-ac
* ABTesting.testcase
* ContentPerformance.testcase

Content Management - @liferay-content-management
* CategoriesUseCase.testcase
* WebContent.testcase
* WebContentDisplay.testcase

Echo - 
* ExperienceCreateExperience.testcase
* CollectionDisplay.testcase
* MastersPageTemplates.testcase
* WidgetTemplatesUseCase.testcase

Regards,
Eudaldo

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
