### PR TITLE
LPD-19864 Take ctCollectionId into account for v5_1_1/LayoutPageTemplateStructureUpgradeProcess

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
If a widget page was converted to a content page while the page is also present in a Publication the content page will lose its LayoutPageTemplateStructure when v5_1_1/LayoutPageTemplateStructureUpgradeProcess is executed.
[LPD-19864](https://liferay.atlassian.net/browse/LPD-19864)

Proposed Solution
========
Add ctCollectionId to the upgradeProcess' sqls

Steps to Verify
========
1. Launch 7.3 U17
2. Enable Publications
3. On Production, create a widget page
4. Create a new publications and visit the widget page that was created
5. Add an asset publisher widget
6. Do not merge the publication to production
7. Navigate to Production and view the widget page in Page Builder
8. Convert the Widget Page to a Content Page
9. Add a Heading to the Page and Publish
10. Check the page as a guest and view the heading added
11. Upgrade to master
12. Visit the page

**Expected behaviour:** Page shows the heading
**Actual behaviour:** The heading is not present and there is an NPE in the logs

Cheers,
Balázs

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
ci:test:upgrade

**Comment by javalosjr96** [comment]
Looks like CI bugged out.

**Comment by javalosjr96** [comment]
ci:test:upgrade

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:report:2548705511

**Comment by lfbesada** [comment]
ci:report:2548689392

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
