### PR TITLE
[TS] LPP-47473 > LPS-171297 Check Custom User Attribute with locale

### PR DESCRIPTION
**Pull request by sontruongces**
Dear team,

This PR is for ticket https://issues.liferay.com/browse/LPS-171297 that passed @TaiPhamLR's review. Please help us review it.

Thanks a lot.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
Hey @sontruongces @TaiPhamLR,

I have a question regarding your pr, Why are you using the user locale and not the current locale? Is there any reason behind it?

Also, Could you please fix the source formatting error?

Regards,
Eudaldo.

**Comment by sontruongces** [comment]
> Hey @sontruongces @TaiPhamLR,
> 
> I have a question regarding your pr, Why are you using the user locale and not the current locale? Is there any reason behind it?
> 
> Also, Could you please fix the source formatting error?
> 
> Regards, Eudaldo.

Hi @ealonso, At first I tried to use current locale by using **serviceContext.getLocale()**. But this API

`List<AssetCategory> assetCategories =
				_assetCategoryLocalService.search(
					companyGroup.getGroupId(), userCustomFieldValueString,
					new String[0], QueryUtil.ALL_POS, QueryUtil.ALL_POS);`

searching entries by using the '**name**'. While the '**name**' is saved in DB by using the value of default language. I assume your Instance Settings default language is English, so when you switch to JP by add /ja in the URL. The value of **userCustomFieldValueString** will be in Japanese. While the title of asset vocabulary is English. So API will return null.

And I see the better is use
`LocaleThreadLocal.getDefaultLocale()` instead of `user.getLocale();`. If you feel the same I will update the code

Sorry if my explanation is not clear enough. 

Please let me know thought.

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/10721

**Pull request closed without merging**
