### PR TITLE
LPS-167052 HR_29 SR is not announcing the exact descriptive name for the setting button

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:stop

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ozysouza** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/126359

**Pull request closed without merging**
