### PR TITLE
[TS] LPP-48211 -> LPS-178147 Fix category filter does not work when Documents and Media widget is not on first page

### PR DESCRIPTION
**Pull request by locpham97**
Hi team,
Please help me review this ticket.
This PR is for ticket: https://issues.liferay.com/browse/LPS-178147 (resolve issue [LPP-48211](https://issues.liferay.com/browse/LPP-48211)), this is passed reviewed in https://github.com/liferay-lima/liferay-portal/pull/4096. 
Thanks a lot,

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by locpham97** [comment]
Hi @lfbesada ,
Could you help me review this PR?
Thanks,
Loc

**Review by lfbesada — CHANGES_REQUESTED** [review]
Thanks for the PR.
I have been testing it locally and I have verified that it solves the bug reported in the Documents and Media widget but it causes errors in other portlets, in my case I have tested it with an Asset Publisher widget.
Please repeat the same test in your PR by adding to the same page an Asset Publisher configured to display documents, with pagination, and with 20-item paging. In that scenario, if you go to the last page of the two widgets and filter by a category,  you will see that the Documents and Media widget works fine but AP shows no results.
IMHO, your proposed solution is not the right way to go. I think that it should address how the Documents and Media widget processes the parameters and not change the parameters that receive because that will affect other widgets.
Regards

**Comment by locpham97** [comment]
Hi @lfbesada ,
The original Asset Publisher widget is not recognized by the categoryId. Follow to the debugging, the AP widget has a problem with the orginal widget category filter. With my fix, It helps the AP widget recognize the categoryId( not always false when choosing page in pagination). The cause error makes the AP shows no results is in here:https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-publisher-web/src/main/java/com/liferay/asset/publisher/web/internal/util/AssetPublisherHelperImpl.java#L1093-L1093. I will reopen this PR again could you help me recheck about this issue?
Thanks,
Loc

**Comment by lfbesada** [comment]
Hi @locpham97 When I test your fix, I the Asset Publisher did not paginate properly when filtering, but it works properly without your fix, although it was not filtering the pagination works. According to your tests, the Asset Publisher pagination works properly with your changes?

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by locpham97** [comment]
Hi @lfbesada ,
Follow to my fix, it helps the AP widget can get the right categoryId from the URL; however, the AP widget has an error when filtering by the categoryId. This error is not related to my fix.
Thanks,
Loc

**Comment by lfbesada** [comment]
Hi @locpham97 
As I told you before, according to my tests, your fix breaks the AssetPublisher pagination when filtering by category. Without your fix, the AP pagination is correct even though it doesn't filter.
Please send a solution that does not contain source formatting errors and does not introduce new errors. It would be nice if you follow the Echo Pull Request Template, it helps us to understand the context.
If you need help finding a solution, please create a ticket.
Regards

**Pull request closed without merging**
