### PR TITLE
LPS-185587 Identify the types of fragments during import

### PR DESCRIPTION
**Pull request by jkappler**
https://issues.liferay.com/browse/LPS-185588

@claraizquierdo ❤️

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
seems another baseline is needed

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
