### PR TITLE
LPS-178951 Removes unnecessary js logic from edit_segments_entry.jsp

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
[Link to ticket](https://issues.liferay.com/browse/LPS-178951)

## Test Scenario
* Go to People > Segments and create a new Segment.
* Edite the Segment, save it and check that the changes have been applied.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Review by claraizquierdo — CHANGES_REQUESTED** [review]
Hi @BarbaraCabrera ,
if you remove that code the segment edition fails when clicking the button save 😢  . I'm getting this error in the console:

Captura de pantalla 2023-04-05 a las 17 12 58

**Comment by BarbaraCabrera** [comment]
> Hi @BarbaraCabrera , if you remove that code the segment edition fails when clicking the button save 😢 . I'm getting this error in the console:
> 
> Captura de pantalla 2023-04-05 a las 17 12 58

Fixed, thanks!! @claraizquierdo 😄

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
CI fails are not relates to this pr, can you review it anyways? Thanks @claraizquierdo 😊

**Review by claraizquierdo — APPROVED** [review]
LGTM! 🎉

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
