### PR TITLE
LPS-112968 Add empty items to fix test failure

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
cc: @sandrodw3 @p2kmgcl se rompen los mismos tests todo el rato

**Pull request closed without merging**
