### PR TITLE
LPS-128667 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-128667

This is only for master.

@sandrodw3
@veroglez

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Hi @sandrodw3 and @veroglez, There is a suggestion, Could you modify Content Display to Content label in General tab?
There is a placeholder Select Content Display.
Actual
That could confuse user. If iplement, just modify https://github.com/liferay-echo/liferay-portal/pull/4004/commits/8a58f12e8eb1d94f3bd834a5561f8eedbb855d16
Thanks

**Comment by veroglez** [comment]
Hi @Tim-Cao! Yes, it makes sense to change what you say. I got this!

**Comment by veroglez** [comment]
@Tim-Cao I have made the changes you requested and have resent it here https://github.com/liferay-echo/liferay-portal/pull/4006

**Pull request closed without merging**
