### PR TITLE
LPS-157847 Remove default alt for OOTB fragment. This will allow keeping the alt empty

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/120133

**Comment by ealonso** [comment]
ci:stop

**Comment by victorg1991** [comment]
Hey @d80wrk it was only a sample alt, which served not purpose, so we removed it :) "responsive image" alt was useless in the 100% of the cases

**Pull request closed without merging**
