### PR TITLE
LPS-138102 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-138102

This is only for master.

@ruben-pulido

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1297401_394

**Comment by ruben-pulido** [comment]
Poshi tests should no longer fail on https://github.com/liferay-echo/liferay-portal/pull/6067

**Pull request closed without merging**
