### PR TITLE
LPS-150364 Move htmlTag to a more proper place in page definition 

### PR DESCRIPTION
**Pull request by lfbesada**
@sandrodw3 See: https://github.com/liferay-echo/liferay-portal/pull/7625#issuecomment-1083666904

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
