### PR TITLE
LPS-119617 show decoded url title to better user experience

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
ci:test:sf

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Hi @ealonso, can you review this solution, and decide what to do with it?


We were assigned with this bug (https://issues.liferay.com/browse/LPS-119617)
The problem comes with the ^ character (that it's a valid character)

We are storing the friendlyURL on 3 tables :

- Layout
- LayoutFriendlyURL
- FriendlyURLEntryLocalization

And now the url stored if different on all 3.

We are storing on LayoutFriendlyURL, when we normalize the url to add to FriendlyURLEntryLocalization, it's normalized so renormalize the url converts. The method is public so we must normalize the url because it can comes directly from the user.
So the result is : 
**^** > **%5E** > **-5e** (because the % )

The main idea is that if we normalize several times the same url, the result must be equals, but with this case it doesn't happens.

The problems appears when the fix for https://issues.liferay.com/browse/LPS-117484 comes, and with the fix, this bugs reappears.


Thanks

//@4lejandrito if you can adds more info, you are welcome.

**Comment by ealonso** [comment]
Hey @AliciaGarciaGarcia,
Could you please take a look to tests failures?
Regards,
Eudaldo.

**Comment by AliciaGarciaGarcia** [comment]
Hi @ealonso 

With the all the test fails, we analyzed the problem and decided to revert the changes made on the  https://issues.liferay.com/browse/LPS-117484 (https://issues.liferay.com/browse/LPS-119836 > https://github.com/liferay-lima/liferay-portal/pull/693)

Thanks for all!!

**Pull request closed without merging**
