### PR TITLE
LPS-91391 Add button role and tabIndex attributes to existing VerticalCards

### PR DESCRIPTION
**Pull request by p2kmgcl**
I tried replacing this elements with a clay:navigation-card taglib, but it just uses a div with a tab-index attribute, so it's easier (and a bit more accessible) to add those attributes by ourselves.

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
Wonderful 🌈 😄 I only found a case that probably should be working and I think it's not. When creating a Page Template and selecting a Master Page, should we be able to select that cards with the keyboard? The rest of the cases I tested are working amazingly 🐼

**Comment by p2kmgcl** [comment]
> Wonderful   I only found a case that probably should be working and I think it's not. When creating a Page Template and selecting a Master Page, should we be able to select that cards with the keyboard? The rest of the cases I tested are working amazingly

You're right, I am going to add that too :smile:

**Comment by p2kmgcl** [comment]
There it goes. I found the solution has nothing to do with the other module, but now it works better :smile:

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
