### PR TITLE
[TS] LPS-182522 Web Contents are not creating new copies when importing them

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
Importing journalArticles with "Copy as new" strategy will not create new articles if an articleId match exists in the importing site.
[LPS-182522](https://issues.liferay.com/browse/LPS-182522)

Proposed Solution
========
Create the new articles with different articleIds in order to "branch off" from the original journalArticle

Steps to Verify
========
1. Go to Content & Data > Web Content
2. Create a Basic Web Content
3. Go to the home page
4. Add a Web Content Display widget to the page and select the created Basic Web Content for it
5. Export the Web Content Display widget as a .LAR file
6. Import the .LAR file to the Web Content Display widget
7. Under "UPDATE DATA" select "Copy as New"
8. Go to Content & Data > Web Content

**Expected behviour:** There are 2 Web Contents
**Actual behaviour:** There is only 1 Web Content

cc @vendeltoreki

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
