### PR TITLE
LPS-188354 Use clay:vertical-nav tag for fragments and categories

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-188354

@Stephy6
@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @Stephy6, would you mind checking the sf issue? I cannot reproduce on my local.

**Comment by Stephy6** [comment]
Hey @ealonso , I'm not able to find the issue, could yo take a look al the SF errors?

**Comment by ealonso** [comment]
Hey @Stephy6 @Tim-Cao,
The sf failures seems to be related with a bug in source formatter tool, the same happen with https://github.com/liferay-echo/liferay-portal/pull/13118 and it is related with init.jsp file

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/138734

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
