### PR TITLE
LPS-155696 Input type fragments shouldn't be cacheable

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-155696

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1377401_2703

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
