### PR TITLE
[TS] LPS-131901, LPS-131902

### PR DESCRIPTION
**Pull request by ChrisKian**
From @jesseyeh-liferay:

> [LPS-131901](https://issues.liferay.com/browse/LPS-131901) updates Web Content notification links to go directly to the Web Content itself instead of the list of all Web Content. Similarly, [LPS-131902](https://issues.liferay.com/browse/LPS-131902) uses this new link and includes it in the e-mail template for Web Content reviews, mirroring the prose from [email_article_approval_requested_body](https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-api/src/main/resources/com/liferay/journal/dependencies/email_article_approval_requested_body.tmpl).

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @ChrisKian @jesseyeh-liferay,

What happen if you don't have permissions to edit the web content? I tend to think that it is not a bug and it is the expected behavior of the product, since it is working in that way from long time ago.

Regards,
Eudaldo.

**Comment by jesseyeh-liferay** [comment]
@ealonso That was my initial thought as well. However, it seems strange that we supply parameters in the URL identifying the Web Content of interest, but not navigate directly to it. Regardless, the current behavior seems inconsistent with other, similar notifications. For example, on master, if you:
1. Check Email Article Approval Requested Enabled in Control Panel > System Settings > Web Content > Service
1. Configure outgoing mail settings in Control Panel > Server Administration > Mail
1. Create a Basic Web Content

The e-mail notification that gets generated (using the [email_article_approval_requested_body template](https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-api/src/main/resources/com/liferay/journal/dependencies/email_article_approval_requested_body.tmpl)) contains a direct link to edit the specified Web Content. And if a user with this link does not have permission to edit the Web Content, a corresponding error message appears, preventing the user from making edits.

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/4584

**Pull request closed without merging**
