### PR TITLE
LPS-145408 Create a class of constants to centralize friendly url separators

### PR DESCRIPTION
**Pull request by guilhermedcamacho**
Hey guys, Brian asked me to create a class of constants to map all Friendly URL Separators there and then document /o/ as reserved (to avoid another developer use this by mistake).

Please see this [thread](https://liferay.slack.com/archives/CL9RTSZ52/p1638325668150400)

cc: @ealonso @jkappler

### CODE REVIEW

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:sf

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1297401_1355

**Review by lfbesada — APPROVED** [review]
Thanks!

**Pull request closed without merging**
