### PR TITLE
LPS-121276 - Add feature flag for new react component

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @p2kmgcl @sandrodw3 @ealonso

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
