### PR TITLE
LPS-137806 Auto SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by liulukiwi** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1307401_405

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
