### PR TITLE
LPS-The exported zip of utility page should use utility page name

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to task](https://issues.liferay.com/browse/LPS-172869)

Utility pages are exported with their external reference code in the filename. In case of fragments and page templates, we generated them by hand, in utility pages it's the UUID.

The goal of the task is to standardise this so that utility pages have the same type of external reference code as fragments and layout page templates

## Change summary:

* When we don't receive an ERC, we autogenerate them just like with fragments and page templates
* Integration tests

## Test Scenario

* Create a new utility page
* Export it - the name of the utility page should be present in the zip file name

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
❤️

**Pull request closed without merging**
