### PR TITLE
LPS-102711 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-102711

This is only for master.

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
See: https://github.com/liferay-echo/liferay-portal/pull/4460, it include the fix for baseline and integration tests

**Comment by Tim-Cao** [comment]
Hi @ealonso, Found a regression issue here. The open graph image is not shown in Preview window after clicking Save.
Steps to Reproduce
1. Add a new site based on Blank Site
2. Click the Pages > Open Graph
3. Click the Select button of Image field
4. Upload an image > Add
5. Assert the image is shown in preview window
6. Click Save

Expect Result:
The image is still shown in preview window.

Actual Result:
The preview window is empty.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
