### PR TITLE
LPS-122372 baseline

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
cc: @jkappler

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @ealonso, There is a regression issue caused by your changes.
*Step to reproduce:*
1. Add a display page template with Web Content Article and Basic Web Content
2. Add a Display Page Content fragment to display page template
3. Publish
4. Add a web content article based on Basic Web Content
5. Select the new display page template as Specific Display Page Template 
6. Publish
7. Click the ellipsis button of web content entry > View Content

*Expected Results:*
The /-/ should redirect to /w/, then content is shown in display page template.

*Actual Results:*
The /-/ doesn't redirect to /w/ and the page doesn't work like the following screenshot. Additonally, when access to /w/, the display page template display correctly.
Actual

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
