### PR TITLE
LPS-184119 Add missing maxLength attribute

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Review by claraizquierdo — APPROVED** [review]
It works perfectly!

**Comment by p2kmgcl** [comment]
mmm @lfbesada I just saw that LongTextInfoFieldType is using some attributes from TextInfoFieldType. I think we should fix that, I working on it.

(or maybe you just told me that on Slack :3)

**Comment by lfbesada** [comment]
@p2kmgcl In order to prevent a large PR I am sending this as it but I will send a follow PR to attend to your comment [here](https://github.com/liferay-echo/liferay-portal/pull/12088#issuecomment-1551483570) using another ticket: https://issues.liferay.com/browse/LPS-184932 
Thanks a lot for your suggestions 
See you in Slack 😘

**Comment by lfbesada** [comment]
ci:forward:force

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
