### PR TITLE
[TS] LPS-128928

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team, could you please review this PR in order to see if it is a good approach to fix the case related to a user with limited permissions editing asset configured with categories which are not allowed to see or de/select? Thanks in advance

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Hi @istvansajtos, we should find another way to solve the ticket.

One idea that @dacousalr mentioned is that it could behave like in related assets: You can deselect any category, but you wouldn't be able to add it again

Let us know if you have any questions regarding this. Will reassign the ticket to you.

Thanks!

**Comment by istvansajtos** [comment]
Thanks @jkappler! 

At the moment I have just one question: What do you think about giving out the recent changes as a temporary fix for the customer while I am working on the final solution. Do you see any risk?

**Comment by jkappler** [comment]
Hi @istvansajtos, the issue was with all the markup that was generated and the complexity. But as long as it's a temporary fix there shouldn't be a problem (if we can rollback easily)

**Comment by istvansajtos** [comment]
Thanks @jkappler ,

In the meantime, the final fix with the approach you suggested turned out to be an easy implementation. I will send you a PR after I tested it. Because of this the temporary fix doesn't make sense anymore.

**Comment by jkappler** [comment]
great, thanks @istvansajtos!

Still, kudos to @dacousalr who was the one to suggest it in the first place :D

**Comment by dacousalr** [comment]
Thanks to you for making me think about this fix twice, @jkappler!

I only regret not having come up with the other approach earlier.

**Pull request closed without merging**
