### PR TITLE
LPS-147896 Add support for container flex wrap

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
@sandrodw3 you have a wrong LPS number

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/7618

**Pull request closed without merging**
