### PR TITLE
LPS-121884 Migrate v2 usages in layout/layout-page-template-admin-web

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

**Test plan for each of the jsps:**

`view_master_layouts.jsp`
1. Design > Page Templates > Master tab

`view_display_pages.jsp`
1. Design > Page Templates > Display Page Templates

`view_layout_page_template_entries.jsp`
1. Design > Page templates => Page Templates tab
2. Create a collection

`select_layout_page_template_collections.jsp`
1. Design > Page templates => Page Templates tab
2. Delete a collection => modal is opened

`view_asset_display_page_usages.jsp`
1. Design > Page Templates > Display Page Templates
2. Create a display page template for a Web Content
3. Content & Data > Web Content > create a web content
4. On the sidebar expand section “display page template” > select specific display page
5. Select the one created before
6. Goo back to Design > Page Templates > Display Page Templates
7. In the created display page template, click on the three dots and select "View Usages"

`view_layout_prototypes.jsp`
1. Go to Site global
2. Design > Page templates > Page templates  tab  

cc @julien @jonmak08 @markocikos

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
I'll have a look to thee poshi failures on monday... sorry guys!

**Comment by ambrinchaudhary** [comment]
Hi  @calvinctvo @zhangyan0701 and @john-co: 

I have checked the first 4 poshi failures and my gut feeling is that the poshi tests needs update because some element classes have changed. On the screenshots I see everything is correct, also in my local instance everything works fine. 

**LocalFile.MastersPageTemplatesExportImport#CannotExportMastersPageTemplateWithoutPublishedVersion:** 
//button[*[name()='svg'][contains(@class,'icon-download')] and contains(@disabled,'disabled')]

Before markup: 
```
<button class="btn nav-link nav-link-monospaced btn-unstyled" aria-label="download" disabled="disabled" type="button" title="Export">
	<svg class="lexicon-icon lexicon-icon-download" focusable="false" role="presentation">
```
After markup: 
```
<button class="nav-link nav-link-monospaced btn btn-unstyled" type="button" disabled="" title="Export">
	<svg class="lexicon-icon lexicon-icon-download" role="presentation">
```

**LocalFile.DisplayPageTemplatesWithViewUsage#ViewAssetsOrderInViewUsagesOfDisplayPageTemplate**
//a[contains(@class,'order') and contains(@class,'active')]

Before markup: 
```
<a class=" nav-link nav-link-monospaced order-arrow-up-active"
	<svg class="lexicon-icon lexicon-icon-order-arrow" focusable="false" role="presentation">
```

After markup:
```
<a class="nav-link nav-link-monospaced link-unstyled”
	<svg class="lexicon-icon lexicon-icon-order-arrow" role="presentation">
```

**LocalFile.DisplayPagesUseCase#AssignToDefaultAndDeleteDisplayPageMappedSpecificDPT** and 
**LocalFile.DisplayPagesUseCase#UnassignAndDeleteDisplayPageMappedSpecificDPT**
//div[contains(@class,'dropdown-action')]//button[contains(@class,'dropdown-toggle')]

Could you please check and change them if necessary? thanks a lot.

**Comment by john-co** [comment]
ci:test:bundle

**Comment by calvinctvo** [comment]
Just start reviewing :)

**Comment by calvinctvo** [comment]
Hi @ambrinchaudhary , I've taken a look at the poshi failures and looks like they are related to this PR. I will need a bit more time to come up with fix for these tests. This could be done by tomorrow.

**Comment by zhangyan0701** [comment]
Just start reviewing :)

**Comment by zhangyan0701** [comment]
Analysis Results:
**1. [Test Fix]** 
LocalFile.MastersPageTemplatesExportImport#CannotExportMastersPageTemplateWithoutPublishedVersion
LocalFile.DisplayPageTemplatesWithViewUsage#ViewAssetsOrderInViewUsagesOfDisplayPageTemplate
LocalFile.DisplayPagesUseCase#AssignToDefaultAndDeleteDisplayPageMappedSpecificDPT
LocalFile.DisplayPagesUseCase#UnassignAndDeleteDisplayPageMappedSpecificDPT

I sent the fix in https://github.com/ambrinchaudhary/liferay-portal/pull/394. Could you cherry-pick my commits if you rerun relevant tests??

**2. [Flaky]**
LocalFile.Dropdown#DefineDisplayedBehaviorOfDropdownPanel

I was able to reproduce this locally, test passed. I think it should be a flaky.

**3. [Should be unrelated]**
LocalFile.PagesAdmin#SearchPages

I have no idea why this test failed, test failed as well when I running it locally, then I tried running the same test on upstream,  but also failed, so I don't think it related to this PR.

**4. Not sure if indented**
I noticed this but not sure if this is an indented change.

When click the Select All icon in Design > Page Templates, the blue border of it appears, but no check mark inside of it.
select all icon

But this is how it looks like on upstream:
select all master

Could you take a look at this? Which one should be the correct one?

**Comment by ambrinchaudhary** [comment]
Sent here: https://github.com/liferay-echo/liferay-portal/pull/3961

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
Thank you @zhangyan0701 for your fixes! I have cherry-picked you commits and trying to run ci:test:relevant again. 

About the point 4., I'm not sure either, I will check back wiith the team, but IIMHO, it would be intented because the blank master page is not selectable... Anyway... I guess this does not affect the poshi test, isn't it?

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
@zhangyan0701 so about the point 4), same issue appeared in https://github.com/liferay-echo/liferay-portal/pull/3869#issuecomment-789350296. As a conclusion, yes, it is intended because there are no selectable items. I agree that it could be better to disable the checkbox in this cases, but we will check this internally and implement it separately if we go for it. 

/cc @julien

**Comment by zhangyan0701** [comment]
>  I guess this does not affect the poshi test, isn't it?

It doesn't affect any test.

> yes, it is intended because there are no selectable items.

Got it, thanks for the confirmation!

**Pull request closed without merging**
