### PR TITLE
LPS-139573 Remove feature flag

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
https://issues.liferay.com/browse/LPS-139573

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Thanks @david-gutierrez-mesa! ❤️

**Comment by david-gutierrez-mesa** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
