### PR TITLE
LPS-168249 Allows editing the friendly URLs of the global's scoped Web Contents 

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-168249

Previous PR: https://github.com/liferay-echo/liferay-portal/pull/10380

cc: @joaovictoralvesmartins

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@lfbesada, all looks good as always ❤️. If you want to incorporate what we talked about in the tests feel free to do it, otherwise we can forward it

**Comment by lfbesada** [comment]
@jkappler Thanks for the tips! ❤️

**Review by jkappler — APPROVED** [review]
❤️

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1387401_4989

**Comment by lfbesada** [comment]
ci:forward

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/126856

**Pull request closed without merging**
