### PR TITLE
LPS-188278

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Hey @ealonso, a regression found ([see comparison with acceptance routine](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2358243427&testrayRunIdA=2356841461&statusB=3)). Steps to repdroduce:

1. Go to Product Menu >> Content & Date >> Blogs
2. Add a blog entry
3. Go to Product Menu >> Site Builder >> Pages
4. Add a Content Page
5. Add a Content Display to a content page
6. Select the blog entry in Content Display

Expected result:
The Content field will be shown

Actual result:
"The selected content is no longer available. Please select another." This text is being shown

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
