### PR TITLE
LPS-159512

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,
This is a follow up of https://github.com/liferay-echo/liferay-portal/pull/9209 [LPS-159512](https://issues.liferay.com/browse/LPS-159512)

Brian [asked](https://github.com/brianchandotcom/liferay-portal/pull/121335#issuecomment-1207517069) if I can Randomize the values in the test, and I don't see a reason why not.

Can you please review?
Thanks,
Balázs

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1267401_4417

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @balazssk, would you mind checking the failed integration test? Thanks

**Comment by balazssk** [comment]
Hi @Tim-Cao ,
The code change in this PR has already passed on https://github.com/liferay-echo/liferay-portal/pull/9209 and https://github.com/liferay-echo/liferay-portal/pull/9159
The only changes added were in the Test file in the second commit and
The first commit was already merged to master, can this user's master branch be rebased to that?

Also, neither
[com.liferay.layout.seo.web.internal.servlet.taglib.test.OpenGraphTopHeadDynamicIncludeTest.testIncludeLinkLayoutTranslatedLanguagesOpenGraphDisabled](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/181467//testReport/com.liferay.layout.seo.web.internal.servlet.taglib.test/OpenGraphTopHeadDynamicIncludeTest/testIncludeLinkLayoutTranslatedLanguagesOpenGraphDisabled)
nor https://testray.liferay.com/reports/production/logs/2022-08/test-1-35/test-portal-acceptance-pullrequest(master)/2298/functional-tomcat90-mysql57-jdk8/0/24/LocalFile.ContentPageTemplates_CanViewPaginationContentViaAP/index.html.gz involves LayoutClassedModelUsages

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ozysouza** [comment]
ci:forward

**Pull request closed without merging**
