### PR TITLE
[TS] LPS-135453

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hello,

The fix for this issue uses the isolated mode so that the position of the script is set to `inline`:

https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/com/liferay/taglib/util/PositionTagSupport.java#L81-L86

I did not encounter any issues after making these changes but please let me know if you see any regressions because of it.

If you do not wish to make a code change for this issue then we can instruct users to workaround it by updating their script calls to include the position:

`<@liferay_aui["script"] use="liferay-alert" position="inline">`

If you feel that is a better option than committing a change then we can let the client know and also open a documentation request.

Please let me know if there are any questions or issues.

Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1327401_342

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Hi @jonathanmccann  
While testing the fix, I have realized that the alert is no longer displayed when navigating to the page with the Asset Publisher.
This would break step 8. in the description of the bug:
" 8. Assert there is an alert message at the top of the screen "

This happens both when applying the fix, or when adding position="inline" to the @liferay_aui["script"] tag.

**Comment by jonathanmccann** [comment]
@ruben-pulido I'm sorry for the confusion. I put the red X there to denote it shouldn't happen but I've updated the description to be more clear. Since the Asset Publisher is only showing an abstract I don't believe the script should be executed at that point.

**Comment by ruben-pulido** [comment]
Thanks for the clarification @jonathanmccann.

@p2kmgcl  @victorg1991 @sandrodw3 @veroglez 
Do you believe it makes more sense to instruct users to include `position="inline"` in the scripts to avoid the issue or to merge the fix?

**Comment by p2kmgcl** [comment]
I am not sure about the solution, because maybe we are hiding some kind of rendering issue, @jonathanmccann have you checked how that JS is being included with/without the "isolated" option? Why is the script being executed twice only if it is not inline? It should be the same result :confused:

**Comment by victorg1991** [comment]
Yeah, the solution seems a bit risky since it changes the behaviour for all the templates. I think I rather add some recommendation into the documentation to warn users about this. Also, you can set the script as sandbox to avoid name clashing `sandbox="<%= true %>"` (Mentioning that for including in the recommendations also :))

**Comment by jonathanmccann** [comment]
I didn't pinpoint why the script is being included on the page an extra time. I'm not sure if it's worth the time or not if documenting the workaround is preferred.

**Comment by ruben-pulido** [comment]
Thanks for the response @jonathanmccann.
Let's close this PR and go ahead with the documentation.

**Pull request closed without merging**
