### PR TITLE
LPS-125755 Suppress the usage of the advice to avoid stale object problems

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @ealonso, Could you double check your codes again? 
```
LayoutService.addLayout(long groupId, boolean privateLayout, long parentLayoutId,
			String name, String title, String description, String type,
			boolean hidden, String friendlyURL, ServiceContext serviceContext)
```
When create a content page via the above method, the Main Variation is not enabled with your commits.
Actual

**Comment by ealonso** [comment]
What happen if you create a widget page?

**Comment by Tim-Cao** [comment]
> What happen if you create a widget page?

The same with content page.

**Comment by ealonso** [comment]
Perfect, Can we fix the test in some way? like adding a click in the button "Enable in Main Variation" and then clicking in the switch

**Comment by Tim-Cao** [comment]
@ealonso, I agree with you. The above is another issue not related to your PR. I will bypass this issue temporarily.

**Comment by ealonso** [comment]
Thanks you very much @Tim-Cao, I really appreciate it

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/3419

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
