### PR TITLE
LPS-187869

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
cc: @victorg1991 @ruben-pulido

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Hey @ealonso, a regression found ([see comparison with acceptance routine](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2358292850&testrayRunIdA=2358261256&statusB=3)). Steps to repdroduce:

1. Create a content Page
2. Add a grid fragment
3. Add a image fragment into the first module of Grid
4. Edit the inline image of Image
5. Save the fragment composition as fragment **with inline content**
6. Export the fragment collection
7. Import the fragment collection into a new site
8. Add an imported fragment composition to content page

Actual result:
The image added previously is not showing

https://github.com/liferay-echo/liferay-portal/assets/69062082/a8f6f25c-de5d-4c99-a1e1-967016dc216d


Expected result:
The previously added image will continue to appear

https://github.com/liferay-echo/liferay-portal/assets/69062082/ca2e338f-52c2-4f75-8059-9ad0ade8f734




 I also found some failures related to integration tests, could you please take a look at it?

[com.liferay.layout.page.template.admin.web.internal.portlet.action.test.ImportExportLayoutPageTemplateEntriesTest](https://testray.liferay.com/home/-/testray/case_results/2358295550)
`ImportExportLayoutPageTemplateEntriesTest > testImportExportLayoutPageTemplateEntryFragmentImageFieldImageMappedAndLinkMapped FAILED`

`ImportExportLayoutPageTemplateEntriesTest > testImportExportLayoutPageTemplateEntryFragmentImageFieldImageMappedAndLinkPage FAILED`

`ImportExportLayoutPageTemplateEntriesTest > testImportExportLayoutPageTemplateEntryFragmentImageFieldImageURLAndLinkURL FAILED`

`ImportExportLayoutPageTemplateEntriesTest > testImportExportLayoutPageTemplateEntryFragmentTextFieldFragmentAvailableMappedContentNotAvailable FAILED`

[com.liferay.layout.page.template.internal.importer.test.PageTemplatesImporterTest](https://testray.liferay.com/home/-/testray/case_results/2358295406)

`PageTemplatesImporterTest > testImportLayoutPageTemplateEntryHTMLFragment FAILED`

`PageTemplatesImporterTest > testImportLayoutPageTemplateEntryImageFragment`

**Comment by alessandromalves** [comment]
And when opening the Home page the `tree.png` is not being shown 

Screenshot

**Comment by ealonso** [comment]
@ruben-pulido @victorg1991 Could you please take a look?

**Comment by victorg1991** [comment]
resent here https://github.com/liferay-echo/liferay-portal/pull/12567

**Pull request closed without merging**
