### PR TITLE
LPS-134638 Behaviour has changed and we no longer track default display pages. So when no display page was exported with the items, delete the one if exists

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The failure case is unrelated to changes in PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/103637

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
