### PR TITLE
LRQA-80727 | Test Fix | Master

### PR DESCRIPTION
**Pull request by rafaellajordao**
# Element is not present in ContentDashboardAuditGraph#AuditGraphFlipAxes

Hi! :)
This pr is corresponding to this ticket: [LRQA-80727](https://issues.liferay.com/browse/LRQA-80727)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
See changes @rafaellajordao
https://github.com/liferay-echo/liferay-portal/pull/12127

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
