### PR TITLE
LPD-34747 - Link type lfr-editable field created in 7.2 looses the href when upgrading

### PR DESCRIPTION
**Pull request by ruben-pulido**
https://liferay.atlassian.net/browse/LPD-34747 - Link type lfr-editable field created in 7.2 looses the href when upgrading

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
Forwarding manually as unique failure is reported in other PRs (e.g: https://github.com/liferay-echo/liferay-portal/pull/16396#issuecomment-2410639669)

**Comment by ruben-pulido** [comment]
ci:forward:force

**Comment by ruben-pulido** [comment]
ci:stop

**Comment by ruben-pulido** [comment]
Manually forwarded here: https://github.com/brianchandotcom/liferay-portal/pull/155144

**Pull request closed without merging**
