### PR TITLE
LPS-124425 Use base class in other processors

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Adding a new commit :)

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
