### PR TITLE
LPS-182044 Fix fragmentComposition test

### PR DESCRIPTION
**Pull request by YurenaC**
[Story](https://liferay.atlassian.net/browse/LPS-192044)

A malfunction test was found during QA review.  Also, some errors related to a change in a JSON parser (fields with default value are not propagated anymore) were found and fix in a separate commit.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
