### PR TITLE
[TS] LPS-148543

### PR DESCRIPTION
**Pull request by jcampoy**
https://issues.liferay.com/browse/LPS-148543

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @jcampoy! 

We have been discussed this issue internally and we think that the best solution is to add a new configuration to allow user to control whether we use a `span` or a `div` to render the lfr-editable tag :)

**Comment by jcampoy** [comment]
i will try to implement that solution, thx!! @victorg1991

**Comment by victorg1991** [comment]
Thanks!!!

**Pull request closed without merging**
