### PR TITLE
[TS] LPS-112258

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team, item selectors in fragments should allow to select documents and pages as in Web Contents \cc @ealonso

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@vicnate5
```
junit.framework.AssertionFailedError: 
Duplicate entry 'com.liferay.portal.repository.portletrepository.PortletRepositor' for key 'IX_B27A301F'
```

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
