### PR TITLE
LPS-133767 - As a Category manager I want to bulk update the Display Page Templates for my categories

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @jkappler

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/4907

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
