### PR TITLE
LPS-111343 Use secondary display type

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
cc: @david-gutierrez-mesa

**Comment by david-gutierrez-mesa** [comment]
@victorg1991 please just ignore this test. More info here: https://issues.liferay.com/browse/LPS-111348

**Comment by victorg1991** [comment]
I think in this case we have to merge all the pr's we want to send and add the commit that ignores the test right, otherwise we cannot send more than one pr

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
