### PR TITLE
LPS-192693 Use global printPage function in print.jsp

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-192693)

## Steps
    1. Go to Site Builder > Pages > create a Content Page 
    2. Add a Wiki widget to the page > Publish 
    3. Go to the page view > Click on All Pages in wiki widget
    4. Select the kebab and select print option in dropdown 
   
Screenshot 2023-08-07 at 12 19 42

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/138928

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
