### PR TITLE
LPD-34913 Page preview API is not working

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-34913

This is covered by the test that discovered the issue: com.liferay.headless.admin.content.resource.v1_0.test.PageDefinitionResourceTest.testPostSitePageDefinitionPreview

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by lfbesada** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
