### PR TITLE
[TS] LPS-186686

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-186686

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Hey @ChrisKian,
I cannot reproduce the issue with the description steps in the jira ticket, Could you please help me with it?

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
Resent here: https://github.com/liferay-echo/liferay-portal/pull/12374

**Pull request closed without merging**
