### PR TITLE
LPS-172712 Asset Categories Selector is temporarily unavailable

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to task](https://issues.liferay.com/browse/LPS-172712)

This PR fixes the problem mentioned in the ticket, while at the same trying to not regress

[LPS-171805](https://issues.liferay.com/browse/LPS-171805)
[LPS-171737](https://issues.liferay.com/browse/LPS-171737)
[LPS-171689](https://issues.liferay.com/browse/LPS-171689)

The idea is to differ the check for the visibility of the vocabularies and do it only when creating the json structure for them. This will avoid affecting other elements of the component

## Change summary:

* Change the point where we check if we want to show the vocabularios or not

## Test Scenario 1 (related to this bug)

* Go to Content and Data > Blogs
* Create a new Blog
* Click on Topic
* No categories were found message should be shown

## Test Scenario 2 (related to LPS-171805)

* Go to Global Site
* Go to Content and Data > Documents and Media
* Click on File Upload 
* Click on Categorization -> Topic
* In the modal, a + button should be shown to add a new category to the vocabulary

## Test Scenario 3 (related to LPS-171737)

* Go to Categorization > Categories
* Create 2 vocabularies
* Add a category to one of the vocabularies
* Click on the kebab to move the category to the other vocabulary 
* In the modal, the empty vocabularies should be shown

## Test Scenario 4 (related to LPS-171689)

* Go to Site Builder > Collections
* Create a dynamic collection
* Change filter to categories and press "select"
* Only vocabularies with categories should be shown

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
🤩

**Comment by alessandromalves** [comment]
ci:forward

**Pull request closed without merging**
