### PR TITLE
LPS-205117 Remove fixes and sticky position when xs resolution

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
This might require FEI team approval as well.

The solution was based on Marcos Castro suggestions, for more details please check https://liferay.atlassian.net/browse/LPP-52174?focusedCommentId=2548058 

image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
> -breakpoint-down(xs) {
>         position: unset;

I have tried this but is always being applied:
image

What is working doing:
`.example {
    @include media-breakpoint-up(md) {
        position: sticky;
     }
}`

But clearly this goes beyond xs resolution.

Any suggestions are welcome.

**Comment by marcoscv-work** [comment]
media-breakpoint-up(md)  is perfect, thanks @georgel-pop-lr

**Comment by georgel-pop-lr** [comment]
Hi @victorg1991,

I committed new changes, could you please check them.

Regards.

**Comment by victorg1991** [comment]
Sent some changes here: https://github.com/liferay-echo/liferay-portal/pull/14974

**Pull request closed without merging**
