### PR TITLE
LPS-120935 - Internal categories are being shown by category navigation widgets

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @pavel-savinov

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Rebase then resend. See https://github.com/liferay-echo/liferay-portal/pull/2374

**Comment by Tim-Cao** [comment]
ci:close

**Comment by ruben-pulido** [comment]
Thanks for rebasing it @Tim-Cao!

**Comment by Tim-Cao** [comment]
You're welcome

**Pull request closed without merging**
