### PR TITLE
[7.4-only] LPS-121967 Migrate v2 usages of clay:vertical-card in portlet-configuration-web

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
cc @carloslancha @markocikos

**Comment by julien** [comment]
ci:test:relevant

**Review by carloslancha — APPROVED** [review]

**Comment by victorg1991** [comment]
I've seen a strange behaviour hereScreenshot 2020-11-24 at 13 19 40

I believe that this will be fixed in a newer version of clay, right? I've seen the fix here: https://github.com/liferay/clay/commit/dee67288b890b50440b220377992567d4f06adb4#diff-850786b8efe6f1e3fd8bc011f8056008f79ae4f0802e1282b964ec9e8626399c

**Comment by carloslancha** [comment]
Yup, that will be fixed with the next clay release so don't worry about it @victorg1991

**Comment by victorg1991** [comment]
Niice :D this is good to go then

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
