### PR TITLE
LPS-205566 Increase z-index of properties panel to 2 in order to not …

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
…overlap with image select button

Before:
image

After:
image

### CODE REVIEW

**Comment by veroglez** [comment]
Hi @georgel-pop-lr, this issue also happens when a structure is created, can we fix it there too? 

Screen Shot 2024-01-11 at 11 46 37 AM

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr, this issue also happens when a structure is created, can we fix it there too?
> 
> Screen Shot 2024-01-11 at 11 46 37 AM

Hi @veroglez,

What resolution did you use to test it?

In my case for the structures, it looks awful: 
image

Regards.

**Comment by veroglez** [comment]
> > Hi @georgel-pop-lr, this issue also happens when a structure is created, can we fix it there too?
> > Screen Shot 2024-01-11 at 11 46 37 AM
> 
> Hi @veroglez,
> 
> What resolution did you use to test it?
> 
> In my case for the structures, it looks awful: image
> 
> Regards.


@georgel-pop-lr I have tested it by resizing the browser. It seems that Chrome's device simulation is not a faithful one. I have tested from a real iPhone 14 device and it looks like this

**Comment by georgel-pop-lr** [comment]
> > > Hi @georgel-pop-lr, this issue also happens when a structure is created, can we fix it there too?
> > > Screen Shot 2024-01-11 at 11 46 37 AM
> > 
> > 
> > Hi @veroglez,
> > What resolution did you use to test it?
> > In my case for the structures, it looks awful: image
> > Regards.
> 
> @georgel-pop-lr I have tested it by resizing the browser. It seems that Chrome's device simulation is not very faithful. I have tested from a real iPhone 14 device and it looks like this
> 
> 

Hi @veroglez,

I tried to fix the structures as well like you suggested, but for some unknown reason is more difficult than it seems, is not working by only changing the z-index, not sure if something else is interfering here.

See this print screen: 
image

I tried to increase the z-index for multi-panel-sidebar-content class to a max of, 99999 but without any results.

This is the file that controls the z-index:
https://github.com/liferay/liferay-portal/blob/216e474b3e508ba4e6caab46a8faf02d14d55444/modules/apps/data-engine/data-engine-taglib/src/main/resources/META-INF/resources/data_layout_builder/js/components/sidebar/MultiPanelSidebar.scss#L10-L11

Also, I see this file is managed by Data engine team, maybe this is a bug they need to fix, not sure here...

So my guess is that we need to change the position of the elements in the DOM in order to fix it, maybe I'm wrong, but I see it  loads first the '_com_liferay_journal_web_portlet_JournalPortlet_header' which contains the fields and then the panel 'multi-panel-sidebar multi-panel-sidebar-light' that we need to increase the z-index. Theoretically this seems correct, but maybe we need to play with this order, but I'm not sure yet, I need to investigate more on this.

If you have any suggestion, they are more then welcome.

Regards.

**Comment by veroglez** [comment]
> So my guess is that we need to change the position of the elements in the DOM in order to fix it, maybe I'm wrong, but I see it loads first the '_com_liferay_journal_web_portlet_JournalPortlet_header' which contains the fields and then the panel 'multi-panel-sidebar multi-panel-sidebar-light' that we need to increase the z-index. Theoretically this seems correct, but maybe we need to play with this order, but I'm not sure yet, I need to investigate more on this.

It seems that the overlay continues because the parent element of the panel `.multi-panel-sidebar-content` is `.multi-panel-sidebar` and this has also a fixed position with z-index 0 by default. If we add z-index 1 to this element it seems to fix it 🙂 

**Before** adding z-index="1" to `multi-panel-sidebar` element:

Screen Shot 2024-01-12 at 5 25 47 PM

**After** adding z-index="1" to `multi-panel-sidebar` element:

Screen Shot 2024-01-12 at 5 26 17 PM

**Comment by georgel-pop-lr** [comment]
> multi-panel-sidebar

Hi @veroglez,

You are right, I was searching for z-index in the CSS properties, forgetting that an element would have a default value of 0. 

I have sent a fix, thanks for your hints!

Regards.

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by veroglez** [comment]
LGTM!! 👏

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:report:2488188266

**Comment by Tim-Cao** [comment]
ci:forward:force

**Pull request closed without merging**
