### PR TITLE
LPS-133699 Replace ClayDropDownWithDrilldown by ClayDropDownWithItems with Cascading menu

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
FrontEnd looks perfect :D

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
