### PR TITLE
LPS-179670 Fix possibility to add multiple "single-use" widgets to a page

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Fix the Ability to add multiple "single-use" widgets to a page
[Link to bug](https://liferay.atlassian.net/browse/LPS-179670)

Proposed Solution
========
We have created a new action for updating a widgets used property and fire it before the fetch for updating the fragment entry links.

Steps to Verify:
----------------
1. Check the ticket video

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
Hey @claraizquierdo I believe there is an easier way to do this. We can simple force the disabled state in the TabItem component while the request is being made. This way we don't need to create extra actions/reducers :)

**Comment by victorg1991** [comment]
niiice :clap:

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
