### PR TITLE
LPS-119655 Adds image field type since we are using Data Engine for structures

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/2928

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
