### PR TITLE
LPS-120304 Change onMouseOver and onMouseLeave events to the parent

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
Since the failure task unrelated to changes in PR and in order to not clog up ci resources I pushed directly to BChan.
See https://github.com/brianchandotcom/liferay-portal/pull/93717

**Pull request closed without merging**
