### PR TITLE
LPS-155229 Error saving a value in the color picker with keyboard navigation

### PR DESCRIPTION
**Pull request by veroglez**
…tocomplete is active

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1267401_3338

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:forward

**Pull request closed without merging**
