### PR TITLE
LPS-140136 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-140136

This is only for master.

@jkappler

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by david-gutierrez-mesa** [comment]
The tests failing in this PR are not related.

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
See liferay-echo#6052

**Pull request closed without merging**
