### PR TITLE
LPS-149232 Does the same steps that we follow in the user interface when we are converting a layout, it is generate preview and then publish the layout

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @ealonso, there is an issue caught by automation. Would you mind having a look at?
Cannot render the widget after bulk convert via groovy script.
**Steps to reproduce**

1. Add a new site named Test Site Name
2. Add a Web Content Display to a widget page
3. Bulk convert widget page to content page via the following groovy script
```
import com.liferay.layout.util.BulkLayoutConverter
import com.liferay.portal.kernel.module.util.SystemBundleUtil
import com.liferay.portal.kernel.util.ArrayUtil
import org.osgi.framework.ServiceReference
import org.osgi.framework.BundleContext

companyId = com.liferay.portal.kernel.util.PortalUtil.getCompanyId(actionRequest)
group = com.liferay.portal.kernel.service.GroupLocalServiceUtil.getGroup(companyId, "Test Site Name");
groupId = group.getGroupId();

BundleContext bundleContext = SystemBundleUtil.getBundleContext()

ServiceReference serviceReference = bundleContext.getServiceReference(BulkLayoutConverter.class.getName())

BulkLayoutConverter bulkLayoutConverter = bundleContext.getService(serviceReference);

bulkLayoutConverter.convertLayouts(groupId)
```
4. Navigate to the converted page editor

**Expected Results:**
The Web Content Display should be rendered well.

**Actual Results:**
Cannot render the Web Content Display
image

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
