### PR TITLE
LPS-202014 Add title to back button when importing display page templates

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-202014)

## Steps

- Go to Design > Page Templates > Display Page Templates
- Click on the ellipsis menu upper right
- Select import
- Import page is automatically open
- Hover over the back button
Screenshot 2023-11-17 at 13 01 32

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
Nice! 🎉

**Comment by BarbaraCabrera** [comment]
ci:forward

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward:force

**Pull request closed without merging**
