### PR TITLE
LPS-153827

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @liferay-echo

could you please review my fix?

In case of fragmant propagation (updateLatestChanges) the template strucutre is not updated.

I used the _updateLayoutPageTemplateStructure method from the DropZoneContentPageEditorListener.
I want ot use the

       @Reference
	private LayoutPageTemplateStructureLocalService
		_layoutPageTemplateStructureLocalService;
but after the deployement in the Gogo shell the
scr:info com.liferay.fragment.service.impl.FragmentEntryLinkLocalServiceImpl
returns LayoutPageTemplateStructureLocalService UNSATISFIED
and in the portal some menus (Pages, WebContent) and functionalities (edit Page) is not working.

So, therefore is used the ServiceReference for the _layoutPageTemplateStructureLocalService

https://issues.liferay.com/browse/LPS-153827

cc @lfbesada

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
Thanks @lfbesada 
I opened a ticket here: https://issues.liferay.com/browse/PTR-3093

**Pull request closed without merging**
