### PR TITLE
LPS-122798 - Remove Adaptive Media feature flag

### PR DESCRIPTION
**Pull request by ruben-pulido**
We are reverting the removal of the feature flag since there are additional stories under the epic.

//cc @ealonso @veroglez

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ruben-pulido, this failure case is a common failue.

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
Since the failure case is common failure not related to change in PR and in order to not clog up ci resources I pushed directly to BChan.
See https://github.com/brianchandotcom/liferay-portal/pull/97175

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
