### PR TITLE
LPS-152432 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-152432

This is only for master.

@brianwulbern
@chaowang-123

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by brianwulbern** [comment]
ci:test:stable

**Comment by brianwulbern** [comment]
@Tim-Cao LGTM.

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
