### PR TITLE
LPS-125034 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-125034

This is only for master.

@ruben-pulido

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ruben-pulido, Could you have a look at integration test failure?

**Comment by ruben-pulido** [comment]
There are some additional tests that still be to be adapted. I will send a new PR

**Pull request closed without merging**
