### PR TITLE
LPS-125684 - Update smallValue on PortletPreferenceValue

### PR DESCRIPTION
**Pull request by joseabelenda**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @achaparro,

It looks good to me, Could you please help us taking a quick look?

Thanks!!

**Comment by achaparro** [comment]
Hi @ealonso,

It looks good to me but @joseabelenda, can you change the first step to end on 1.0.1?:
https://github.com/liferay-echo/liferay-portal/pull/3427/files#diff-303994a6c9da627048013ded95262bbd1dce0b0b823a71a1f08033d94e454825R33

The step starting in 0.0.0 is reserved for its execution for new installations if we don't change it to:
`registry.register("0.0.0", "1.0.1", new DummyUpgradeStep());`

We will always execute the step 1.0.1 for new installations when it's not needed.

Thanks.

**Comment by joseabelenda** [comment]
Hi, @achaparro .

I've pushed the request change.
Thanks!

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Thanks @joseabelenda !

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
