### PR TITLE
LPS-195551

### PR DESCRIPTION
**Pull request by SamZiemer**
**Motivation**
https://liferay.atlassian.net/browse/LPS-195551
Assets in the request are lost when a widget is refreshed.

**Proposed Solution**
Create a mechanism to get the layout asset entry if it's not a request attribute, so it's friendly url could be used

@jkappler should have some context for this issue if we could assign it to him.

/cc @robertoDiaz

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by jkappler** [comment]
@SamZiemer, @robertoDiaz, can we organize the PR in commits, so that it's more tidy?

Thanks!

**Comment by jkappler** [comment]
@robertoDiaz, @SamZiemer, fix looks good 👌. Still as we already talked in slack, it would be better to keep this in the radar because we might get other related issues.

Thanks guys!

**Comment by robertoDiaz** [comment]
Hey @SamZiemer 
Please move the [PageCommentPortletLayoutAssetEntryProvider.java](https://github.com/liferay-echo/liferay-portal/pull/14268/commits/59f339b4c69e5470dbff06afbbdbd9bd7ff45881#diff-eb3c3b5a7fbe9c261413d7c17bc603517584d1367369d37a649eb5a6eb6a079a) creation to it's own commit (so we have one commit for the new infrastructure and one for it's implementation) and resend.

While it is merged in master, since there are not logical changes required, we could provide this as it is to the customer to solve their issue.

Thank you in advance.

**Comment by SamZiemer** [comment]
Hi @jkappler, I've updated this branch with more commits to break up the implementation. Please let me know if you need anything else.

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
