### PR TITLE
LPS-120935 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-120935

This is only for master.

@ealonso
@pavel-savinov

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/2391

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
