### PR TITLE
LPS-113654 Wait for a dispatch undo action to initiate the next. Otherwise we may end up dispatching several request at the same time and the server could potentially fail

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/686

**Pull request closed without merging**
