### PR TITLE
LPS-165736 Adding integration test for AssetEntriesCheckerHelper

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-165736

Previous PR: https://github.com/liferay-echo/liferay-portal/pull/10083

cc: @IstvanD

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@lfbesada AssetEntriesCheckerHelperTest is throwing a NPE, but it says it happens also in upstream 😭

**Comment by lfbesada** [comment]
@jkappler thanks for catching it! ❤️

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1277401_5654

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/125732

**Pull request closed without merging**
