### PR TITLE
LPS-166624 Not able to search page with workflow in new site

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to bug](https://issues.liferay.com/browse/LPS-166624)

There's a bug when after approving a content page, when searching for text in it, no results are found. This is because we check that the request and the response are present when generating the content

## Proposed solution

Always add the response to the request, this is done when completing the task

## Change summary:

* Check if the response is present in the httpServletRequest, if not, retrieve it from actionResponse and add it
* Add unit tests for the changes in action command
* Change methods for localisation so that we pass the service context instead of retrieving it from the ThreadLocal
* Adapt integration test for workflow handler

## How to test the changes

* Create a new site
* Enable workflow for content pages
* Create a new widget page called "Search" and add a "Search Result" widget to it
* Create a new content page, add something with text on it and submit for publication
* In publication tasks assign the page to you
* Approve the page
* Go to any page and search for text that was added to the content page

workflow

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by ozysouza** [comment]
ci:reevaluate:1387401_4557

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
Hi @jkappler , two integration tests(testContentLayoutTypeControllerPublishedPagePermissionUser, testContentLayoutTypeControllerPublishedPageGuestUser) fail in this pull, could you take a look? thanks!

```     [exec] com.liferay.layout.type.controller.content.internal.layout.type.controller.test.ContentLayoutTypeControllerTest > testContentLayoutTypeControllerPublishedPageGuestUser FAILED
     [exec]     java.lang.NullPointerException
     [exec]     	at com.liferay.portal.util.PortalImpl.getCanonicalURL(PortalImpl.java:1410)
     [exec]     	at com.liferay.portal.util.PortalImpl.getCanonicalURL(PortalImpl.java:1352)
     [exec]     	at com.liferay.portal.kernel.util.PortalUtil.getCanonicalURL(PortalUtil.java:468)
     [exec]     	at com.liferay.portal.kernel.service.ServiceContextFactory._getInstance(ServiceContextFactory.java:190)
     [exec]     	at com.liferay.portal.kernel.service.ServiceContextFactory.getInstance(ServiceContextFactory.java:62)
     [exec]     	at com.liferay.layout.type.controller.content.internal.layout.type.controller.ContentLayoutTypeController._updateLayoutContent(ContentLayoutTypeController.java:367)
     [exec]     	at com.liferay.layout.type.controller.content.internal.layout.type.controller.ContentLayoutTypeController.includeLayoutContent(ContentLayoutTypeController.java:146)
     [exec]     	at com.liferay.layout.type.controller.content.internal.layout.type.controller.test.ContentLayoutTypeControllerTest.testContentLayoutTypeControllerPublishedPageGuestUser(ContentLayoutTypeControllerTest.java:139)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
     [exec] 
     [exec] com.liferay.layout.type.controller.content.internal.layout.type.controller.test.ContentLayoutTypeControllerTest > testContentLayoutTypeControllerPublishedPagePermissionUser STARTED
     [exec] 
     [exec] com.liferay.layout.type.controller.content.internal.layout.type.controller.test.ContentLayoutTypeControllerTest > testContentLayoutTypeControllerPublishedPagePermissionUser FAILED
     [exec]     java.lang.NullPointerException
     [exec]     	at com.liferay.portal.util.PortalImpl.getCanonicalURL(PortalImpl.java:1410)
     [exec]     	at com.liferay.portal.util.PortalImpl.getCanonicalURL(PortalImpl.java:1352)
     [exec]     	at com.liferay.portal.kernel.util.PortalUtil.getCanonicalURL(PortalUtil.java:468)
     [exec]     	at com.liferay.portal.kernel.service.ServiceContextFactory._getInstance(ServiceContextFactory.java:190)
     [exec]     	at com.liferay.portal.kernel.service.ServiceContextFactory.getInstance(ServiceContextFactory.java:62)
     [exec]     	at com.liferay.layout.type.controller.content.internal.layout.type.controller.ContentLayoutTypeController._updateLayoutContent(ContentLayoutTypeController.java:367)
     [exec]     	at com.liferay.layout.type.controller.content.internal.layout.type.controller.ContentLayoutTypeController.includeLayoutContent(ContentLayoutTypeController.java:146)
     [exec]     	at com.liferay.layout.type.controller.content.internal.layout.type.controller.test.ContentLayoutTypeControllerTest.testContentLayoutTypeControllerPublishedPagePermissionUser(ContentLayoutTypeControllerTest.java:167)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$2.evaluate(AbstractTestRule.java:99)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$1.evaluate(TestExecutorRunnable.java:237)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at com.liferay.portal.kernel.test.rule.AbstractTestRule$1.evaluate(AbstractTestRule.java:59)
     [exec]     	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable._execute(TestExecutorRunnable.java:316)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable.run(TestExecutorRunnable.java:95)
     [exec]     	at java.lang.Thread.run(Thread.java:745)
     [exec] ```

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
Thanks @liulukiwi, will take a look

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ozysouza** [comment]
@jkappler the failures on last relevant are unrelated to this PR. It seems good to go

**Comment by ozysouza** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/125475

**Pull request closed without merging**
