### PR TITLE
[TS] LPS-200940 Add option to skip unwrapping the request

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
During Content Page indexing, [RuntimeTag](https://github.com/liferay/liferay-portal/blob/master/util-taglib/src/com/liferay/taglib/portletext/RuntimeTag.java#L187) unwraps the `companyHttpServletRequest` created in [LayoutServiceContextHelperImpl#_getHttpServletRequest](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-impl/src/main/java/com/liferay/layout/internal/util/LayoutServiceContextHelperImpl.java#L691) removing all the request overrides set up for index rendering.
This unwrapping was introduced as part of https://liferay.atlassian.net/browse/LPSA-39344
[LPS-200940](https://liferay.atlassian.net/browse/LPS-200940)

Proposed Solution
========
By adding the option to skip this request unwrapping we should be able render widgets sufficiently to create a search document from them.

Steps to Verify
========
1. Go to Content & Data > Web Content
2. Click the blue + to add a new Web Content
3. Add an easily recognisable text to its content, like “unique” and press Publish
4. Create a content page
5. Add a Web Content Display widget
6. Select the “unique” Web Content to be displayed in the widget
7. Press Publish
8. Use the page’s search bar to look for “unique”
9. 2 results should appear: the web content and the page
11. Go To Control Panel > Search
12. Switch to the Index actions tab
13. Looks for “Page (com.liferay.portal.kernel.model.Layout)”
14. Press the Reindex button next to it, accept the prompt
15. Return to the page and use the search bar to look for “unique”

**Expected behavior:** 2 results should appear: the web content and the page
**Actual behavior:** Only the web content appears

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
Hi @balazssk 

Thanks for the fix! :heart: 

From the Echo component's side, this fix is correct. But this change must also be tested by the Core Infra team since it introduces changes in RuntimeTag, which is its component.

Could you please send this PR through [the Core Infra repo](https://github.com/liferay-core-infra/liferay-portal/pulls) for review?

Thank you!

Regards

**Comment by balazssk** [comment]
Cheers @lfbesada ,
Will do

**Pull request closed without merging**
