### PR TITLE
LPS-137211 Calculate itemId before activating it. This will activate the first element when the item is inside a collection

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
The failed cases are reported in [LPS-137335](https://issues.liferay.com/browse/LPS-137335), not pr realted.

**Comment by liulukiwi** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
