### PR TITLE
LPS-142432 Adds an upgrade process to update the menu item type

### PR DESCRIPTION
**Pull request by lfbesada**
This pull request only adds the upgrade process without registering the upgrade step, since the step must be registered simultaneously with the removal of the feature flag.

https://issues.liferay.com/browse/LPS-142432

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relavant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @lfbesada, no need to run more ci:test:relevant. I will forward it manually when the ready for merge is added

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/6658

**Pull request closed without merging**
