### PR TITLE
LPS-206204 Adds the configure action to the card's dropdown items

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-206204

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:report:2488379380

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:report:2488567820

**Comment by Tim-Cao** [comment]
Hi @lfbesada, is this expected change?
image
The ellipsis button and New button are swapped.

**Comment by lfbesada** [comment]
Hi @Tim-Cao 

Thank you very much for reviewing this. :heart: 

I have reviewed these rebased on master 3710a8f0d816394652434e548cc8f65b80efc8a8 and I don't see it that way.

Screenshot from 2024-01-17 08-14-05



On the other hand, the only commit of this PR only adds an action in the UtilityPage cards, it can't produce that change on the Miller Columns.

Could you please check it again?

Thank you so much!

Regards

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
@Tim-Cao I am going to forward this since the report said all tests run and there is not unique failures.

Thanks for your help! :heart:

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
