### PR TITLE
[7.4.x only] LPS-123101 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-123101

This is only for master.

@p2kmgcl
@pavel-savinov

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:close

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/2948

**Pull request closed without merging**
