### PR TITLE
LPS-152089 baseline

### PR DESCRIPTION
**Pull request by lfbesada**
Previous PR: https://github.com/liferay-echo/liferay-portal/pull/7905

cc. @ealonso

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
Hi @lfbesada, would you mind check sf failure?

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
Hi @Tim-Cao,
Could you please help me with the SF issue? In my local, it works OK but I think that is because I am not working with DXP profile and the SF issue seems to be there. This PR doesn't change anything in DXP, but is rebased against the Brian repo, could it be the cause? 
Thanks a lot! ❤️ 
Regards

**Comment by lfbesada** [comment]
See: https://github.com/liferay-echo/liferay-portal/pull/7923

**Pull request closed without merging**
