### PR TITLE
LPS-121861 Migrate v2 usages in asset/asset-taglib

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

**Test plan**:

Since this tag is no longer used and was replaced with the
`<liferay-layout:layout-classed-model-usages-admin />` tag in
[https://github.com/liferay/liferay-portal/commit/1bb7fde](https://github.com/liferay/liferay-portal/commit/1bb7fdefbbf3b4d595252fc4134f481d8db075e7), you can:

- Edit [`view_asset_entry_usages.jsp`](https://github.com/liferay/liferay-portal/blob/c724841cf6f0b0baff32e5aa3fca17b799583427/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/view_asset_entry_usages.jsp)
- Replace `<liferay-layout:layout-classed-model-usages-admin />` 
  with `<liferay-asset:asset-entry-usages />`
- Follow the original test plan described [here](https://github.com/liferay-echo/liferay-portal/pull/3898#issue-584082311)

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
cc @ambrinchaudhary @markocikos @jonmak08

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
