### PR TITLE
[DE-Migration] LPS-128453 Fill the journal article field with the rest of the expected data

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant ticket: https://issues.liferay.com/browse/LPS-128453

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:echo:upgrade

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
Hey, @ealonso.

I've come across this bug which looks like there might be missing data (title, titleMap and classNameId) in journal article fields, when they are upgraded from 7.0/7.1 to master. Unfortunately, I couldn't include all the expected data related to this type of field during upgrade, because I've noticed that the UpgradeJournalArticleContent uses a converter service to adapt old content to the new format and we would need to run a bunch of extra queries in the database to get all the data expected by Data Engine's renderer. So, in order to avoid reinventing the wheel with this upgrade, I've chosen to fill the necessary data on runtime.
Please, let me know if you think we should handle this during upgrade and, if so, what would be the best approach to do that since we can't reference module's services in the upgrade?

Thanks in advance.

**Comment by Tim-Cao** [comment]
The failure cases from ci:test:echo are not related to this PR.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Resend: https://github.com/liferay-echo/liferay-portal/pull/3907

**Pull request closed without merging**
