### PR TITLE
[TS] LPS-153215

### PR DESCRIPTION
**Pull request by crodriguezy**
Hello team,

A previous attempt to fix https://issues.liferay.com/browse/LPS-153217 in the data engine side was tried here: https://github.com/liferay-forms/liferay-portal/pull/1716
But we concluded it was easier to add a simpler logic just in `JournalEditArticleDisplayContext.java`. This is why I'm forwarding this PR to you.

Thank you

### CODE REVIEW

**Comment by crodriguezy** [comment]
Sorry for the mistake in the title, it should be [TS] LPS-153217 not LPS-15321**5**

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @crodriguezy,

It is already happening on Document Library.

Steps to reproduce:

1. Add a new required Vocabulary for Asset Type: 'test'. Add a category to it.
2. Create a new Document Type with a Text field
3. Define a default value for text field, 'default text value'
Text_-_Liferay
4. Try to create a Document using the new document type adding some title and changing the text field default value to 'value'

Then you are going to see the same result that we have on Journal. That is:

Expected result: "Error: Please select at least one category for X_"_ and the text field keeps its current value 'value'.
Current result: "Error: Please select at least one category for X_"_ and the text field value changes to its default one 'default text value'.

@carolmariaabb What we should do in this case? Should we add the same code to DLDisplayContext? IMHO, it should be fixed in a common place.

Regards,
Eudaldo.

**Comment by crodriguezy** [comment]
Hi @ealonso ,

Since we have already discussed the solution with data-engine team and so it's getting a bit delayed (the customer has been waiting for the solution for too long now), I was wondering if we could merge this specific fix to master for Journal and, in case you decide to develop a common logic, replace it later.

Another option is to give it to the customer as a workaround only if you think it's safe.

Thanks

**Comment by crodriguezy** [comment]
Hey @ealonso . according to  @carolmariaabb 's comment, could this be moved forward? It's the priority for the customer.
I can open later the bug for DL and try to f ix it the same way as this one.

Thanks

**Comment by ealonso** [comment]
Please see: https://github.com/liferay-echo/liferay-portal/pull/8360

**Comment by matthiasblaesing** [comment]
I'm looking into LPS-172654 (translations are lost when editing WebContent and switching display template). Bisecting indicates, that this introduced the issue (bisect log is attached to the referenced issue). It would be great if one of you working on this could have a look at the refenced issue.

**Pull request closed without merging**
