### PR TITLE
LPS-135554 Adding null checks

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

This change was originally made in https://issues.liferay.com/browse/LPS-124229 but was left out during the migration in https://issues.liferay.com/browse/LPS-127772

Can you please review?
https://issues.liferay.com/browse/LPS-135554

Thanks,
Balázs

### CODE REVIEW

**Comment by victorg1991** [comment]
Hey @balazssk, thanks for the PR :) 

Can you add null check also in the other places where this variable is used across the file?

Also, instead of an if, you can use the optional chaining operator, which is shorter `ddmStructureFieldNameInput?.value`

Thanks :)

**Comment by balazssk** [comment]
Hi @victorg1991 ,
Thanks for the feedback, I've extended the check based on your suggestion and simplified it so that `?.` wouldn't be needed

**Comment by victorg1991** [comment]
Hey, thanks @balazssk, this looks super good :) 

I've just realised that the Source file is kind of duplicated in asset-list-web module, would you mind changing that also? Just to keep the files in sync 

Thanks!

**Comment by balazssk** [comment]
Hi @victorg1991 ,
Nice catch, I've investigated asset-list-web and found the following:

asset-list-web doesn't have the possibility of not rendering the subTypeFieldFilters like asset-publisher-web
https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-list-web/src/main/resources/META-INF/resources/asset_list/source.jsp#L305
https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-publisher-web/src/main/resources/META-INF/resources/configuration/source.jsp#L281
As those input fields are always part of the html rendered, LPS-135554 is not reproducible with asset-list-web.

**Comment by victorg1991** [comment]
Didn't realise that @balazssk then we the solution is perfectly fine :) I've added a minor comment and resend it here: https://github.com/liferay-echo/liferay-portal/pull/5209

**Comment by balazssk** [comment]
Cheers!

**Pull request closed without merging**
