### PR TITLE
LPS-111869 - Test Scenarios Coverage | Backend

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @pavel-savinov @jkappler

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
https://github.com/liferay-echo/liferay-portal/pull/373

**Pull request closed without merging**
