### PR TITLE
LPS-179703 Export interfaces for customizing fragment editable

### PR DESCRIPTION
**Pull request by Mikellorza**
[Link to the story](https://issues.liferay.com/browse/LPS-179703)

Motivation
=======
Extract interfaces EditableElementParser and EditableElementMapper for customizing fragments 

Proposed Solution
========
Extract interfaces to fragment-entry-processor-api

Steps to Verify:
========
After this change, the whole page will be render in the same way as before.

Notes
========
No test needed.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
