### PR TITLE
LPS-165519 Instead of removing the InfoItemReference after iterate the collection, restore the previous one

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-165519

@ealonso Thanks for the idea! ❤️

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ozysouza** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:test:bundle

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Whether this last forward doesn't work I will manually send it :)

**Comment by ozysouza** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/125900

**Pull request closed without merging**
