### PR TITLE
LPS-137268 Enable Template App

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-137268

This PR enables templates panel app and disables the widget pages panel app. 
Also, it enable TemplatePortlet export/import/staging and disable  export/import/staging of Widget pages portlet.
This change causes, at least, the failure of a lars Import POSHI test because it uses an old lar file, which should be updated to not contain references to widget templates. 
This is an example of a failed execution:

https://testray.liferay.com/reports/production/logs/2021-08/test-1-32/test-portal-acceptance-pullrequest(master)/182/functional-tomcat90-mysql57-jdk8/0/9/LocalFile.StagingUsecase_ImportLARsOnStagedSite/summary.html.gz

It could also be useful to launch more exhaustive tests on this PR

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:echo

**Comment by lfbesada** [comment]
ci:reevaluate:1307401_319

**Comment by lfbesada** [comment]
ci:reevaluate:1307401_319

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Looks good @lfbesada!

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1307401_319

**Comment by liulukiwi** [comment]
ci:test:bundle

**Comment by liulukiwi** [comment]
ci:reevaluate:1307401_319

**Comment by liulukiwi** [comment]
Hi @lfbesada ,
I resend it with test-fix: https://github.com/liferay-echo/liferay-portal/pull/5593

**Pull request closed without merging**
