### PR TITLE
LPS-161381 Added button outline borderless

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
FWD: https://github.com/fortunatomaldonado/liferay-portal/pull/42

Let me know if there are any questions or comments about this.

> [LPS-161381](https://issues.liferay.com/browse/LPS-161380) Added button outline borderless and secondary classes to cancel button.

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @SelenaAungst @fortunatomaldonado 

Thanks for submitting the PR. Although the PR works as it is I believe we should make some changes before merging this to master:

* The LPS of the commit is incorrect, I believe we should use this one: https://issues.liferay.com/browse/LPS-161380 in the commit LPS-161381 is used
* Instead of retrieving the node with the querySelector it is better to modify the `createButton` function to be able to pass the two classes we need here like `buttonClass: 'btn-outline-borderless btn-outline-secondary',`

Let me know if you have any doubt :) 

Thanks!

**Comment by SelenaAungst** [comment]
Hi @victorg1991,
Thanks for looking into this! 

I will correct the LPS number in the commit message and branch name then send an updated PR. 

As for modifying the `createButton` directly, I initially tried adding the two classes to the `buttonClass` for the button that way, but it did not allow for two classes to be added. I attempted this again today and it still shows the following error: `contains HTML space characters, which are not valid in tokens`. My solution to this issue was to add the class using the querySelector as seen in my commit here, but if there is a better/more efficient solution to this please let me know and I can implement that instead. 

I'll wait to send the updated PR so I can add whatever changes are necessary. Thanks again!

**Comment by victorg1991** [comment]
Hi @SelenaAungst  

> As for modifying the createButton directly, I initially tried adding the two classes to the buttonClass for the button that way, but it did not allow for two classes to be added. I attempted this again today and it still shows the following error: contains HTML space characters, which are not valid in tokens. My solution to this issue was to add the class using the querySelector as seen in my commit here, but if there is a better/more efficient solution to this please let me know and I can implement that instead.

This is why the function `add` that it is used here: https://github.com/liferay-echo/liferay-portal/blob/e292f8a825bc76d78660b328742c7b10dc759d94/modules/apps/asset/asset-categories-admin-web/src/main/resources/META-INF/resources/js/ItemSelectorAddCategory.js#L24 doesn't allow passing a class with spaces. This is why I suggested that you'd need to change the `createButton` function to be able to pass several classes to it :) 

Hope this helps

Thanks!

**Comment by SelenaAungst** [comment]
Hi @victorg1991,
My apologies, I misunderstood your original comment. Thank you for clarifying! I have sent a new PR (https://github.com/fortunatomaldonado/liferay-portal/pull/50) for this with both corrections added. Please let me know if anything else is needed for this.

**Comment by victorg1991** [comment]
Thanks @SelenaAungst 

I have send the PR here: https://github.com/liferay-echo/liferay-portal/pull/9647 :)

**Pull request closed without merging**
