### PR TITLE
LPS-124615 Fix alt resolution in ImageProcessor

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
I going to send this later with another change

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, there is a regression issue. Could you have a look at?
The default value **Responsive Image** of alt is missing.
Actual

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/3213

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
