### PR TITLE
LPS-123708 Don't use Senna here since it causes some portlets JS load to fail

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
@jbalsas It is not the first time we have to disable Senna for links because of the issues which seem to be really hard to diagnose. It gives no errors, just doesn't work. Could you please analyze the cases when we use "senna-off" data attribute if we consider Senna as something we want to keep? Thanks!

**Comment by jbalsas** [comment]
Hey @pavel-savinov, could you simply ignore this bug and let out team deal with it? We're making changes in how senna integrates in DXP, so some issues are to be expected. We need to see them and address them, so disabling senna will make it harder for us.

**Comment by jbalsas** [comment]
In this case, as hinted in the LPS, the issue was introduced by a change in our `runScriptsInElement` utility helper at https://github.com/liferay-frontend/liferay-portal/pull/484/files#diff-d58d4624ad80b48401b52d39f85483cc0d5917268adfb9a365149cba90fc9a3aR15 which for some reason makes the form register `script` in Calendar not to run. 

Would you mind letting @bryceosterhaus deal with this? Feel free to remove your component from the issue and set it to SPA since the diagnosis is clear.

Thanks!

**Pull request closed without merging**
