### PR TITLE
LPS-178791 Use consistent event handlers

### PR DESCRIPTION
**Pull request by p2kmgcl**
Motivation
=======
https://issues.liferay.com/browse/LPS-178791

Proposed Solution
========
Previously I was in favor of `on*` properties and `handle*` event handlers, but this was totally opinionated (there is no mention about this in the frontend guidelines). Some time ago I had a conversation about this with @sandrodw3 and we agreed that using `on*` for both properties and event handlers looks more consistent, and much easier to reason.

Checklist (optional):
========
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:forward:force

**Pull request closed without merging**
