### PR TITLE
LPS-182830 Add tests for ErrorMessage

### PR DESCRIPTION
**Pull request by p2kmgcl**
This is a resend because of a revert.
https://github.com/brianchandotcom/liferay-portal/pull/136668

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
