### PR TITLE
LPS-125093 Check key existence instead of the value because it can be a valid boolean false

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
The the first failure in apps:commerce:commerce-frontend-js:packageRunTest, I update this in https://issues.liferay.com/browse/COMMERCE-5409.
For the second failure in apps:layout:layout-seo-web:compileTestJava, this is reported in [LPS-125372](https://issues.liferay.com/browse/LPS-125372). So I'll forward this pull to BChan dirrectly.

**Comment by liulukiwi** [comment]
resend:
https://github.com/brianchandotcom/liferay-portal/pull/97306

**Pull request closed without merging**
