### PR TITLE
LPS-114283 Adapt tests

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
Do not merge this one until the backend part of this pr is reviewed

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by victorg1991** [comment]
rebased and sent here: https://github.com/liferay-echo/liferay-portal/pull/2611

**Pull request closed without merging**
