### PR TITLE
[TS] LPS-114206

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @jonathanmccann,
Since it is part of export-import, Could you please send this one to the staging team?
Regards,
Eudaldo.

**Comment by jonathanmccann** [comment]
ci:close

**Comment by jonathanmccann** [comment]
https://github.com/vendeltoreki/liferay-portal/pull/64

**Pull request closed without merging**
