### PR TITLE
LPS-116338 Add keyboard shortcuts for item actions

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:stable

**Comment by Tim-Cao** [comment]
Hi @sandrodw3 , Is it expected, the floating toolbar of fragment is missing when there is only configuration or style?
Container
Content Display

**Comment by sandrodw3** [comment]
Yep, that's expected! 🙂

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/1383

**Pull request closed without merging**
