### PR TITLE
LPS-138157 Fix category filter

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:stable

**Comment by Tim-Cao** [comment]
The failure cases are caused by https://issues.liferay.com/browse/LPS-138269. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/106382

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
