### PR TITLE
[7.4-only] LPS-121974 Migrate v2 usages of clay:vertical-card in style-book-web

### PR DESCRIPTION
**Pull request by julien**
cc @carloslancha @markocikos

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Review by carloslancha — APPROVED** [review]

**Comment by victorg1991** [comment]
This is good to go, thanks @julien @carloslancha 🎉

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
