### PR TITLE
LPS-151745

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-151745

### Steps to reproduce

1. Add the following property into the portal-ext.properties and startup the server
```java
layout.show.portlet.access.denied=false
```
1. Add Blogs widget into Home page and configure its Look and Feel to have a Border Width of 5
1. Revoke the VIEW permission for the Guest role
1. Logout

**Expected Behavior**: The portlet is not visible
**Actual Behavior**: The portlet is not visible, but you see a border where the portlet is meant to be

### Solution notes

The original pull request https://github.com/liferay-ts-reviewer/liferay-portal/pull/43 included all of the logic inside of `RenderLayoutStructureDisplayContext`, but I felt that moving the implementation details of how portlets are stored in the configuration made more sense in `FragmentStyledLayoutStructureItem`.

If you prefer the original solution, or if you feel there is a better place to add this permission check logic, please let me know.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
Hi @holatuwol,
Thanks for the pull request!
Could you please fix the source formatting issues?
Thanks
Regards

**Comment by lfbesada** [comment]
Hi @holatuwol 
Please, resend this PR once the source formatting issues are fixed.
Thanks

**Pull request closed without merging**
