### PR TITLE
LPD-29128 - Add External Reference Code to Layout entity

### PR DESCRIPTION
**Pull request by ruben-pulido**
https://liferay.atlassian.net/browse/LPD-29128 - Add External Reference Code to Layout entity

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:stable

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:report:25258132

**Comment by ruben-pulido** [comment]
ci:reevaluate:1377401_17214

**Comment by ruben-pulido** [comment]
ci:report:1377401

**Comment by lfbesada** [comment]
ci:report:25258132

**Comment by sandrodw3** [comment]
https://github.com/liferay-echo/liferay-portal/pull/15865

**Pull request closed without merging**
