### PR TITLE
LPS-115801 Mapping a generic image field of a Web Content to an image editable doesn't show the image

### PR DESCRIPTION
**Pull request by JorgeFerrer**
Resending after rebasing again

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:forward

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/1205

**Comment by JorgeFerrer** [comment]
Resent as https://github.com/liferay-echo/liferay-portal/pull/1205

**Pull request closed without merging**
