### PR TITLE
LPS-150065 Avoid NPE

### PR DESCRIPTION
**Pull request by jkappler**
Dear Team, asking a very very nice person to review this: @victorg1991 ❤️

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
pls resend

**Comment by victorg1991** [comment]
ci:forward

**Comment by jkappler** [comment]
Thank you @victorg1991 ❤️

**Pull request closed without merging**
