### PR TITLE
[TS] LPS-192814 - add new parameter to prevent adding all groupIds of a company to the URL

### PR DESCRIPTION
**Pull request by wanderlast**
Previous PR: https://github.com/liferay-echo/liferay-portal/pull/13180

Hi team, I've taken the comments you guys made into account and attempted to implement the alternate solution that was presented by @lfbesada on the LPS. Please let me know if there's anything else that needs editing or correcting. Thanks!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @wanderlast 
Thank you very much for the fix ❤️ 
I have added some SF commits.
Please see: https://github.com/liferay-echo/liferay-portal/pull/13238
Regards

**Pull request closed without merging**
