### PR TITLE
LPS-141589 The Content Flag fragment should not be interactive in edit mode

### PR DESCRIPTION
**Pull request by veroglez**
cc @lfbesada

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
Hi @veroglez 🥰

If we already have a `disabled` property, it's not easier to set it to `true` in backend if it's not view mode instead of sending `isViewMode` to the front and do it there?

**Comment by Tim-Cao** [comment]
Hi @veroglez, Could you check the failure test?

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
