### PR TITLE
LPS-163610 - Permissions are not checked when listing Vocabularies in AssetCategoriesSelectorTag

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @dacousalr

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ozysouza** [comment]
ci:reevaluate:1297401_4681

**Comment by ealonso** [comment]
ci:reevaluate:1297401_4681

**Comment by liulukiwi** [comment]
No unique failures after checking, push to BChan directly: https://github.com/brianchandotcom/liferay-portal/pull/123465

**Pull request closed without merging**
