### PR TITLE
LPS-152546 Update mapper and importer to take into account extra styles

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Hi @victorg1991 ❤️ 
LGTM 😍 
Thanks!

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
