### PR TITLE
LPS-200005 Define fixed width for the picker

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-200005)

## Steps 

- Go Site Builder > Pages
- Create a Content Page and add a Menu Display widget
- Go to the widget configuration

Screenshot 2023-10-25 at 14 17 20

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
Hey @veroglez @DiegoHu97,

I don't like this solution too much, What happens if clay decide to change in some moment the width by default around portal?

**Comment by veroglez** [comment]
I agree with you @ealonso, right now I don't understand why the width of the picker wants to be changed 😅. Diego and I will talk tomorrow with Mery about this.

**Comment by DiegoHu97** [comment]
Hi @ealonso,

**Comment by DiegoHu97** [comment]
Discarded the pr since we do not want to introduce custom styles

**Pull request closed without merging**
