### PR TITLE
[TECHNICAL SUPPORT] LPS-165736 Adding integration test for AssetEntriesCheckerHelper

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
This test exposes the issue reported in [LPS-165736](https://issues.liferay.com/browse/LPS-165736) and demonstrates its solution

Proposed Solution
========
Testing `AssetEntriesCheckerHelper_getAssetEntries` for two cases:

- the Asset Publisher portlet is not configured for manual selection
- the Asset Publisher portlet is configured for manual selection

Because the `AssetEntriesCheckerHelper` class doesn't really lends itself for testing, the `_assetEntriesCheckerHelper` object is instantiated and initialized through reflection.
https://github.com/IstvanD/liferay-portal/blob/f738c5d0c79e8e723ec25740f95987feafb1a0f7/modules/apps/asset/asset-publisher-test/src/testIntegration/java/com/liferay/asset/publisher/web/internal/messaging/helper/test/AssetEntriesCheckerHelperTest.java#L196-L247
Thanks to @lfbesada and @dacousalr for the idea! 👍 

Instead of calling `AssetTestUtil.addAssetEntry`, Asset Entries are added as BlogEntries. This is because `AssetEntriesCheckerHelper_getAssetEntries` performs a search in the index when the Asset Publisher portlet is not configured for manual selection. `AssetTestUtil.addAssetEntry` does not indexes the Asset Entries but `BlogsEntryLocalServiceUtil.addEntry` does. Please consult [AssetHelperTest](https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-test/src/testIntegration/java/com/liferay/asset/util/test/AssetHelperTest.java) for an example.

Steps to Verify
========
Please run the test in `modules/apps/asset/asset-publisher-test` with the command:
`gradlew testIntegration --tests *AssetEntriesCheckerHelperTest`

Thank you and best regards,
István

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1347401_3097

**Comment by lfbesada** [comment]
Hi @IstvanD 
Thanks for the pull request!
Great job getting the AssetEntriesCheckerHelper reference! 👏  
I have added some source format commits, please see: https://github.com/liferay-echo/liferay-portal/pull/10132
Regards

**Pull request closed without merging**
