### PR TITLE
LPS-152936 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-152936

This is only for master.

@victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:close

**Comment by ozysouza** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/117072

**Pull request closed without merging**
