### PR TITLE
LPS-124926 Make more robust ControlMenu bar, since when a ProductNavigationControlMenuEntry implementation fails, it takes down the whole ControlMenu bar

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ealonso, the failure case is a common failure in the previous run. I think the current run could pass.

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
