### PR TITLE
LPS-174801

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, would you mind resolving the conflict? Then I'll update the poshi side. Thanks

**Comment by ealonso** [comment]
Hey @Tim-Cao,

I've already fix the rebase errors.

**Comment by Tim-Cao** [comment]
Hi @ealonso, the Comments metadata is renamed to Comment on configuration of web content display, is that expected change?
image

**Comment by ealonso** [comment]
@Tim-Cao fixed

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130053

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
