### PR TITLE
LPS-142557 - Collection Display for Objects does not display all instances, even when "Display All Collection Items" is checked

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:echo

**Comment by ruben-pulido** [comment]
On hold until upstream is synchronized with Brian's remote

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/6768

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
