### PR TITLE
LPS-119053 Checking default language

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi guys,

Can you review this pull request, please?

You can find more information in [LPS-119053](https://issues.liferay.com/browse/LPS-119053).

The reason why the behavior is not as expected is because [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/internal/validation/JournalArticleModelValidator.java#L110-L129) we are throwing a LocaleException because the defaultLocale from the article's content (structure's default locale) is not among the available locales for the site.

My proposal is updating content's default locale to retrieve site's default locale in case the structure's default locale is not one of the available locales.

I was not completely sure about how to get the available locales for the site at that point without breaking anything else and I used this hacky way using GroupThreadLocal, but you might have a better idea about how to do it.

Thanks in advance.

Regards.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
resend: https://github.com/liferay-echo/liferay-portal/pull/1887

**Pull request closed without merging**
