### PR TITLE
LPS-131534 As a Content Publisher, I want to change to a specific site pages variation by using the Site Pages Variation selector

### PR DESCRIPTION
**Pull request by moltam89**
Hi guys,

This is the continuation of the previous [pull request](https://github.com/liferay-echo/liferay-portal/pull/5363) with the feature flag. I'm copying the description:

**This isn't the final code**, I'd just like to open a discussion about how Page Versioning could be implemented for Content Pages.

Right now in master when Page Versioning is enabled, only the Site Pages Variation option is available for Content Pages (without History and Page Variations) and changes made on different Variations affect each other.

With the current solution we should be able to create different versions of the pages and preserve the History, add new Page Variations, select a version for "Ready for Publish Process" and publish them to Live.
Please turn on Page Versioning before creating any content pages, during the initial publication there is an inverse publication from the Live to the Stage site, which is not implemented yet.

###  Highlights of the changes:

1. **History and Page Variation options are reenabled**

2. **Plid is swapped for layout revisionId in LayoutPageTemplateStructure and FragmentEntryLink services** (later Segments have to be considered)
In order to differentiate between the revisions, we need to connect the LayoutPageTemplateStructure and FragmentEntryLink entities to a revision. This is how it works for PortletPreferences, in PortletPreferencesLocalServiceImpl the plids are swapped to the revisionId.

3. **Draft pages are versioned too**
In the current solution for each published layout revision, there is a connected draft layout revision. (Publish meaining: Publishing a Content Page after editing, not Publishing to Live).
It seems necessary to me, as users can start editing previous versions via the History.  E.g. if there are 1.0-1.5 versions of a layout, someone can go back to 1.3 and start editing it. We need a draft revision for 1.3 where the changes are stored. 
It's a bit unambiguous what should happen when we are editing an older version, how we should preserve the history. When we publish version 1.3, a new version is created with the latest changes, and the 1.3 version of the published layout is copied back to the draft 1.3, so next time we go back to 1.3 in the History, we'll see that version.

4) **Changes for handling LayoutRevisions**
These changes are mostly needed because Widget Pages and Content Pages are different.

### Problems to consider:
1. There are quite a lot of problems with Page Versioning in general, even for Widget Pages which will also affect Content Pages once versioning is enabled for them.
Most of the entities are not prepared to handle a revisionId instead of a plid.
For example when we are adding a tag to a page, the plid is stored in the database. This way we cannot add separate tags for different layout revisions. The same applies for Portlet Permissions, Categories, Custom fields, SEO, Open graph, Custom Meta Tags, Layout Classed Model Usages and so on (probably all the places where we store the plid instead of the revisionId).

2. Developers have to remember that getPlid() calls can result in a revisionId. This is a problem for PortletPreferences as well, portletPreferences.getPlid() calls should be prepared for receiving revisionId. As far as i can see, there are only a few corner cases where this can cause a problem, but once LayoutPageTemplateStructures, FragmentEntryLinks and Segments will work the same way, it can cause quite a lot of problem.

Sorry for the long post, feel free to ping me with any questions.

Best,
Tamas

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test:sf

**Comment by moltam89** [comment]
ci:test:stable

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @moltam89,

We are working on a different solution here: https://issues.liferay.com/browse/LPS-142162, the idea is use the experiences as different page variation and have different experiences per site page variation.

I added a comment here https://issues.liferay.com/browse/LPS-142161?focusedCommentId=2580088&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2580088, to keep the pr tracked just in case we need it, so I'm going to close this one for now.

Regards,
Eudaldo.

**Pull request closed without merging**
