### PR TITLE
LPS-199249 Don't change urlTitle if already exists when calling updat…

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
…eArticle without a friendlyUrlMap

For steps please check https://liferay.atlassian.net/browse/LPS-199249

Note: Maybe we shouldn't call friendlyURLEntryLocalService.getUniqueUrlTitle method if we use urlTitle and not title...

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
Closing this, new pull: https://github.com/liferay-echo/liferay-portal/pull/14051

**Pull request closed without merging**
