### PR TITLE
LPS-146691 Fix: Information templates of other subtypes can be selected in the "Content Display" fragment

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-146691

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
