### PR TITLE
[7.4.x-only] LPS-116774 & LPS-104151 & LPS-109123 Enable Data Engine by default on Web Content

### PR DESCRIPTION
**Pull request by liulukiwi**
forward

cc @ealonso @david-gutierrez-mesa

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:test:bundle

**Comment by ealonso** [comment]
Hey @liulukiwi,

Do you have any update? Do you need help?

**Comment by liulukiwi** [comment]
Hi @ealonso,
Not for now. I'm going to fully work on this, just fix other task.

**Comment by liulukiwi** [comment]
ci:test:echo

**Comment by liulukiwi** [comment]
ci:test:bundle

**Comment by liulukiwi** [comment]
Bugs found in this pr (WIP):
https://issues.liferay.com/browse/LPS-119645
https://issues.liferay.com/browse/LPS-123072
https://issues.liferay.com/browse/LPS-123076
https://issues.liferay.com/browse/LPS-123091

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
ci:test:echo

**Comment by liulukiwi** [comment]
resend https://github.com/liferay-echo/liferay-portal/pull/2875

**Pull request closed without merging**
