### PR TITLE
LPS-198193 Remove Soy from data-engine

### PR DESCRIPTION
**Pull request by p2kmgcl**
This is a bunch of components that was actually not being used, just to maintain a compatibility layer with legacy Metal components.

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:stable

**Comment by ealonso** [comment]
ci:test:stable

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
