### PR TITLE
LPS-180293 - Test Scenarios Coverage | Backend

### PR DESCRIPTION
**Pull request by ruben-pulido**
Incorporates feedback from https://github.com/brianchandotcom/liferay-portal/pull/133654#issuecomment-1515981961

- modules/apps/headless/headless-site/headless-site-impl/src/main/java/com/liferay/headless/site/internal/jaxrs/exception/mapper/NoSuchGroupExceptionMapper.java is necessary, since it makes sure that the message returned uses the terms "site" and "site key" instead of "group" and "groupKey". It also hides companyId value which is otherwise returned by the Vulcan NoSuchModelExceptionMapper

- IllegalArgumentExceptionMapper has been moved to Vulcan.
@4lejandrito Can you review this [commit](https://github.com/liferay-echo/liferay-portal/pull/11842/commits/766d78befab27b2eeff226bc73ace0e43b8b72fc)?
 

//cc @ealonso @jkappler

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Pull request closed without merging**
