### PR TITLE
LPS-159512 Copy the LayoutClassedUsages to the draftLayout

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
[LPS-159512](https://issues.liferay.com/browse/LPS-159512)
When a Widget Page is converted into a Content Page, its LayoutClassedUsages are not copied to the draftLayout, so by publishing the draft, the original Page loses the LayoutClassedUsages.

Proposed Solution
========
Copy the LayoutClassedUsages to the draftLayout during conversion

Steps to Verify
========
1. Go to Site menu > Content & Data > Web content and create a web content
2. Name it "my web content" and add the text "usages" to it
3. Go to Site menu > Builder > Pages, create a new Widget page (named p1)
4. Place a Web Content Display on the widget page which displays the web content
5. Go to Home page and search for "usages"
6. Verify that when clicking on the result, it will open the web content on p1
7. Go to Site menu > Builder > Pages
8. From the kebab menu of p1, click "Convert to content page..."
9. Publish the page
10. Go to Home page and search for "usages"
11. Click on the Web Content search result (not the page)

*Expected behaviour:* Navigation happens to p1 where the web content is displayed in context
*Actual behaviour:* Navigation happens to the search page where the web content is displayed out of context

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
Hmm, actually it might be better to extract https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-impl/src/main/java/com/liferay/layout/internal/util/LayoutCopyHelperImpl.java#L936 from the IF, right?

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
Hi @lfbesada 
What do you think of https://github.com/liferay-echo/liferay-portal/pull/9159#issuecomment-1202419795 ?
I was under the impression that widget pages don't have LayoutClassedUsages, but maybe they do now?

**Review by lfbesada — CHANGES_REQUESTED** [review]
Hi @balazssk Thanks a lot for the fix!
I've been looking at the problem and proposed solution in this PR as well as your comment about whether it's a better approach to address it in LayoutCopyHelperImpl.
I think you're right that it's a better approach to remove _copyLayoutClassedModelUsages from the if, putting it right after it. This fix should work fine and be easier to maintain in the future.
Could you please implement that solution?
If it is more comfortable for you, force the push on this PR or open a new one, whichever you prefer.
Thank you very much!
Regards

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
