### PR TITLE
LPS-145253 Isolates Page Editor Create Page Template Modal

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-145253

Theme styles shouldn't apply to Page Editor Create Page Template Modal.

create-page-template

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
Thanks @pat270!

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
