### PR TITLE
[TS] LPS-201930

### PR DESCRIPTION
**Pull request by dacousalr**
Motivation
=======
This is a PR that aims to fix the lack of Master Page's styles in Widget pages which are configured with a non-default Master page.

Proposed Solution
========
This PR aims to fix LPS-201930 by relying on the layout structure of the master page related to a widget page.

Steps to Verify
========
1. Create a Master page template "master1".
2. Add a Container to "master1", above Drop Zone:
- Height: 50px
- Background color: any color (i.e. #FABADA)
3. Publish "master1" and mark it as default master page.
4. Add a Widget page "wp1" (using "master1" as master page).
5. Navigate to "wp1".

Actual behavior the container's styles are not visible.

References to existing code
========
Full Page Application pages, Panel pages and Embedded pages have been left out of this PR since other LPS tickets should be created first to address the adaptations to Master Pages of their corresponding Layout Type Controllers.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by dacousalr** [comment]
\cc @henriquelimadotcom

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @dacousalr, there is a regression issue. Cannot render fragments on Home page.
image

**Comment by dacousalr** [comment]
Thanks for catching this, @Tim-Cao!

I have sent a new PR in https://github.com/liferay-echo/liferay-portal/pull/14472

I have also opened [PTR-4537](https://liferay.atlassian.net/browse/PTR-4537).

**Pull request closed without merging**
