### PR TITLE
LPS-137267 Add feature flag to hide information templates

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-137267

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1257401_3571

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
