### PR TITLE
LPS-144473 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-144473

This is only for master.

@noornajj

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
Hi @noornajj, could you fix sf issue?

**Comment by dacousalr** [comment]
Hi @Tim-Cao,

I am afraid that this SF error is inevitable since the request object is needed to properly implement the logic and fix this issue.

In fact, the rest of the methods of this interface have the request object as parameter.

In the light of the justifications commented above, I would like to ask you to pass this PR as is, making an exception for this time.

**Comment by noornajj** [comment]
Ok, thank you @dacousalr and @Tim-Cao 
I will send a new PR

**Comment by noornajj** [comment]
New PR sent #6999

**Pull request closed without merging**
