### PR TITLE
LPS-169795 Create tags filter

### PR DESCRIPTION
**Pull request by lfbesada**
(The only FrontEnd change is here: https://github.com/liferay-echo/liferay-portal/pull/10528/commits/6c4cab5f1835512710d0ecc268c9b9ae6209962d#diff-ed5536ea32fef4b0a98d6063740534f9b43562486c53b3692fa3c32530ce4498)

This is an initial development for the story, adding a new "Tags" filter fragment. In order to test this:

1. Enable FragmentCollectionFilters component.
2. Deploy all modules.
3. Add some tags (in Product Menu > Categorization > Tags).
4. Upload some images to the document library and tag them.
5. Create a manual collection of Basic Documents (it can be empty).
6. Add a content page with:
   - A collection display fragment targeting the created collection.
   - A collection filter fragment targeting the created collection display and using _tags_ as filter type.

Things to check:
- [ ] The page can be published.
- [ ] If something is typed into the fragment and enter is pressed, the page reloads and a new URL parameter appears.
- [ ] The fragment preserves typed tags into the URL.
- [ ] When typing a tag, it suggest existing tags.
- [ ] Content is filtered depending on selected tags.

**Warning**: currently the page is reloaded whenever a tag is added/removed. This is intended as we need to reload the page to update results, but we should investigate if this behavior can be improved.

cc: @p2kmgcl

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1377401_7274

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1327401_7527

**Comment by liulukiwi** [comment]
Failures are not related, pushed to BChan directly at https://github.com/brianchandotcom/liferay-portal/pull/127970

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
