### PR TITLE
LPS-146203

### PR DESCRIPTION
**Pull request by mbowerman**
Hi Echo Team,

I'm sending this to you since it modifies Asset-related code. Let me know if I should send it to a different team instead.

https://issues.liferay.com/browse/LPS-146203

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
