### PR TITLE
LPS-139487

### PR DESCRIPTION
**Pull request by mbowerman**
Hi Echo Team,

Please see [PTR-2652](https://issues.liferay.com/browse/PTR-2652) for an explanation of why this is being treated as a bug.

https://issues.liferay.com/browse/LPS-139487

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Thanks for the fix @mbowerman. Forwarded to Brian [here](https://github.com/liferay-echo/liferay-portal/pull/5961)

**Pull request closed without merging**
