### PR TITLE
LPS-112879 AssertionError on AssetInfoCollectionProviderTest on SQL Server

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-112879)

The goal of these changes is to match the asset entry queries that come from highest rated and most viewed collection providers with those from the legacy widgets. 

## Change summary:

* Allow a second type of ordering for asset entry queries in collection providers
* Change second ordering for highest rated and most viewed collection providers
* Integration tests are already present

## Test Scenario in SQL Server and any other DB

* Add a web content
* Add a second web content
* Create a widget page and add a highest rating widget to the page
* Configure it so that it shows the rating
* Change the ratings of the web contents several times
* Add a new widget page with an asset publisher and configure it so that it uses the highest rating collection provider
* Order of the list should match the order in the first page everytime the rating changes

Note: Tested on MySQL and SQL Server

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
failures are not related to the changes

**Pull request closed without merging**
