### PR TITLE
LPS-184017 Adds exception mappers for layout title and friendly URLs

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-184017)

Adds exception mappers for bad title and friendly URLs for layout

## Change summary:

* Just add both mappers

## Test Scenario

* Enable FF for the endpoint: LPS-178052
* Try to create a page through with a bad title or friendlyURL (examples can be: title longer than 255 chars, friendlyURL with less than 2 chars, friendlyURL with invalid chars)
* Instead of an ugly exception thrown in the logs, a "nice" error is returned

## Notes

* If the typeSettings for sitemap are incorrect, an error (or several) is (are) thrown at service layer. But since we already capture the errors in the schema, there's no need to add mappers for it

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by ruben-pulido — CHANGES_REQUESTED** [review]

**Comment by jkappler** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
