### PR TITLE
LPS-130470,LPS-130545 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LPS-130545
https://issues.liferay.com/browse/LPS-130470

cc @david-gutierrez-mesa

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
force push doesn't refresh the commit, close

**Pull request closed without merging**
