### PR TITLE
LPS-167896 HR_197, HR_220 The label is announced as "Select Button" not "Select" buttons

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by alessandromalves** [comment]
ci:forward

**Pull request closed without merging**
