### PR TITLE
LPS-166547 baseline

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:reevaluate:1397401_1296

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
Hi @ealonso, could you please cherry-pick my commit on https://github.com/ealonso/liferay-portal/pull/3243? 

There is one regression issue with Widget Templates, pleasse see video below. I'm not sure if we should change the script due your changes or if it's really a regression.

https://user-images.githubusercontent.com/72820234/198100032-a855a870-bfe4-4195-b1ee-1f03de11a994.mp4

Script 

<#if entries?has_content>
	<@liferay_aui.row>
		<#list entries as entry>
			<@liferay_aui.col width=25>
				<div class="results-header">
					<h3>
						${entry.getUnambiguousTitle(entries, themeDisplay.getSiteGroupId(), themeDisplay.getLocale())}
					</h3>
				</div>

				<#assign categories = entry.getCategories() />

				<@displayCategories categories=categories />
			</@liferay_aui.col>
		</#list>
	</@liferay_aui.row>
</#if>

<#macro displayCategories
	categories
>
	<#if categories?has_content>
		<ul class="categories">
			<#list categories as category>
				<li>
					<#assign categoryURL = renderResponse.createRenderURL() />

					${categoryURL.setParameter("resetCur", "true")}
					${categoryURL.setParameter("categoryId", category.getCategoryId()?string)}

					<a href="${categoryURL}">${category.getName()}</a>

					<#if serviceLocator??>
						<#assign
							assetCategoryService = serviceLocator.findService("com.liferay.asset.kernel.service.AssetCategoryService")

							childCategories = assetCategoryService.getChildCategories(category.getCategoryId())
						/>

						<@displayCategories categories=childCategories />
					</#if>
				</li>
			</#list>
		</ul>
	</#if>
</#macro>

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/10064

**Pull request closed without merging**
