### PR TITLE
LPS-190112 Test Scenarios Coverage | Backend

### PR DESCRIPTION
**Pull request by ruben-pulido**
https://liferay.atlassian.net/browse/LPS-190112

//cc @Mikellorza

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ruben-pulido, would you mind checking this failure?

[com.liferay.layout.reports.web.internal.struts.test.GetLayoutReportsRenderTimesDataStrutsActionTest](https://testray.liferay.com/home/-/testray/case_results/2412471693)

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/13431

**Pull request closed without merging**
