### PR TITLE
LPD-1695 Don't allow to add a portlet to the page, that is already in the master page

### PR DESCRIPTION
**Pull request by jkappler**
https://liferay.atlassian.net/browse/LPD-1695

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
@jkappler What do you think about performing this check within FragmentEntryLocalServicImpl instead of within AddPortletMVCActionCommand?
That way the check would be performed not only when adding a portlet through the UI.

**Comment by ruben-pulido** [comment]
@jkappler We should also apply the validation when changing a a page / page templates master page, since this may lead to having multiple non-instantiable portlets

**Comment by jkappler** [comment]
@ruben-pulido, for changing the master page as we talked, I created another bug

https://liferay.atlassian.net/browse/LPD-17077

Still, will close this since there are more use cases that have to be covered

**Pull request closed without merging**
