### PR TITLE
[TS] LPS-121208

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team, could you please review this PR? Thanks in advance \cc @MarcellGyopos

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
Resent here https://github.com/liferay-echo/liferay-portal/pull/2568 Thanks!

**Comment by pavel-savinov** [comment]
ci:close

**Pull request closed without merging**
