### PR TITLE
LPS-119659 Makes ProductMenuApp take priority over other buttons since it should always show at the left.

### PR DESCRIPTION
**Pull request by jbalsas**
Setting entry.order=100 which is the same value as the ProductMenu entry that this replaces when the AppMenu is enabled so it positions in the same way.

Reported by @victorvalle: 

> I see in the screenshot something that is wrong, it should be
> Apps button + [Back] + selector
> Vertical bar shouldn’t be there

This is not reflected in any of the current designs, so this is a best estimate of what's needed.

Changing the entry order to `100` so it shows to the left. Doing so also makes the separator disappear since that only shows when the element is not the first one in a list.

**Before**

current

**After**

expected

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
