### PR TITLE
LPS-145876 baseline

### PR DESCRIPTION
**Pull request by ealonso**
Hey @georgel-pop-lr, @lfbesada, @dacousalr

I was taking a look to the solution proposed in https://github.com/liferay-echo/liferay-portal/pull/7209 and https://github.com/liferay-echo/liferay-portal/pull/7236 and I think we can simplify it just using the view url method with a few changes.

If you take a look to **getAssetViewURL** it is calling **getURLViewInContext** which is taking into account if the asset have a display page or not, also it is the url that we use in the title link, so, IMHO we should use the same url that we have here for social links.

The Link URL for Twitter with my changes if you have a Display Page is:

> https://twitter.com/intent/tweet?text=11+Proven+Health+Benefits+of+Chia+Seeds&tw_p=tweetbutton&url=http://localhost:8080/web/test-1/w/11-proven-health-benefits-of-chia-seeds

and without my changes:

> https://twitter.com/intent/tweet?text=11+Proven+Health+Benefits+of+Chia+Seeds&tw_p=tweetbutton&url=http://localhost:8080/web/test-1/1/-/asset_publisher/QwolNHKKMrZ5/content/11-proven-health-benefits-of-chia-seeds

Could you please take a look at it and check if it fix the problem that you described in https://issues.liferay.com/browse/LPS-145876 and let me know if it is ok for you?

Regards,
Eudaldo.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ealonso, the semantic versioning failure is not related to your changes. Could we forward this one?

**Comment by dacousalr** [comment]
Hey @ealonso,

Your solution is certainly simpler and much cleaner. This can be explained due to the fact that it assumes that the social URL should be:
1) The Display Page Friendly URL of the asset if any.
2) If there is not a Display Page associated, then the Asset Publisher Portlet Friendly URL should be shared.

It does not take into account the link behavior configured in the Asset Publisher (Full Content or View in Context) or the current URL actually visited.

This solution could lead to scenarios where the page editor has configured the Asset Publisher assets to be viewed as Full Content and therefore, to be accessed by their Portlet Friendly URL.

The user who visits the page and click in an asset configured with a modern Display Page would visit the URL:

http://localhost:8080/web/test-1/1/-/asset_publisher/QwolNHKKMrZ5/content/11-proven-health-benefits-of-chia-seeds

but it would share the URL:

https://twitter.com/intent/tweet?text=11+Proven+Health+Benefits+of+Chia+Seeds&tw_p=tweetbutton&url=http://localhost:8080/web/test-1/w/11-proven-health-benefits-of-chia-seeds

Although the content displayed by both URLs is similar it does not necessarily mean that it should be taken as equivalent since the editors might have tweaked its Display Page to look quite different from the aspect of the Full Content shown by the its Default Template if we think of Assets like Web Contents.

This scenario could be perceived as a kind of inconsistency. Hence the reason of presenting the previous approach (#7209 and #7236) that aims to share the visited URL as the social URL, although the related code can be more complex since it takes into account the Asset Publisher configuration, the Asset Publisher view which is rendering the asset and if it is rendering the asset through its Display Page URL or not.

I am afraid that, in the end, this is a matter of properly establishing the specifications around this feature when applied to the Asset Publisher, since both approaches would be acceptable according to their respective initial assumptions.

Best,
Daniel

**Comment by jkappler** [comment]
Marking on hold until @ealonso returns

**Comment by ealonso** [comment]
Hey @dacousalr,

I've updated the pr taking into account the viewInContext configuration c40acf9.

Could you please let me know if it enough or if we need to include something else?

Thanks!!

**Comment by dacousalr** [comment]
Hi @ealonso,

Firstly, thank you for your work on this fix.

After your last change, there would be the following missing case:
1) Create a page (P1)
2) Add an Asset Publisher widget to P1
3) Create another page (P2)
4) Add an Asset Publisher Portlet with the following configuration:
	- Asset Link Behavior: Full Content
	- Set as the Default Asset Publisher for This Page: Checked
5) Create a Web Content (WC1) with its Display Page pointing to P2
6) Go to P1
7) Click in WC1's link inside the Asset Publisher widget
8) Compare the social URL generated with the current URL

Expected result:
- Both URLs are the same or at least quite similar

Actual result:
- The social URL is of type Portlet Friendly URL while the current URL is of type Display Page URL

This logic that controls this scenario can be located in the other fix approach (#7236) at this [point](https://github.com/liferay-echo/liferay-portal/pull/7236/files#diff-9f33e39b8f454251070d9b90a12bea705b478fdcab7cf771665c43e312c7e60cR524-R552).

Please, let me know if further clarification is needed or if you have any comments.

Best,
Daniel

**Comment by ealonso** [comment]
Hey @dacousalr,

I've followed the steps described in the previous comment and I got the following urls

View URL

> http://localhost:8080/web/guest/-/12-proven-health-benefits-of-avocado?redirect=%2Fweb%2Fguest%2F5

Current URL after clicking in WC link

> http://localhost:8080/web/guest/-/12-proven-health-benefits-of-avocado?redirect=%2Fweb%2Fguest%2F5

Social URL

> https://twitter.com/intent/tweet?text=12+Proven+Health+Benefits+of+Avocado&tw_p=tweetbutton&url=http://localhost:8080/web/guest/-/12-proven-health-benefits-of-avocado

As you can see, the urls are the same, Do I missing something?

Regards,
Eudaldo.

**Comment by dacousalr** [comment]
Just started reviewing :)

**Comment by dacousalr** [comment]
Hi @ealonso,

It seems that we are obtaining different results. I got the following URLs:

ViewURL

> http://localhost:8080/web/guest/-/abcde?redirect=%2Fweb%2Fguest%2Fp1

Current URL after clicking in WC link:

> http://localhost:8080/web/guest/-/abcde?redirect=%2Fweb%2Fguest%2Fp1

Social URL

> https://twitter.com/intent/tweet?text=abcde&tw_p=tweetbutton&url=http://localhost:8080/web/guest/p2/-/asset_publisher/khmr/content/abcde?_com_liferay_asset_publisher_web_portlet_AssetPublisherPortlet_INSTANCE_khmr_assetEntryId=44187

LPS-145876_pr-7274

Be careful with step 6. The Web Content has to be accessed from page P1, not from page P2.

**Comment by ealonso** [comment]
Hey @dacousalr,

I've reproduced the steps again and I can see where is the problem, the problem is in P2 social links. I was thinking that you were referring P1 social links.

After understanding the problem and taking a closer look to it, IMHO, the social url to share should be the same always and it should not depend on the Asset Publisher where we are showing the content.

So, I've decided to removed the last commit from my pr that takes into account the view in context option.

What do you think? If you prefer we can create a PTR to discuss it.

Regards,
Eudaldo.

**Comment by dacousalr** [comment]
Hi @ealonso,

It seems that there are two distinct fix approaches, but I do not see clear arguments which makes one of them more preferable over the other, so I have opened [PTR-2905](https://issues.liferay.com/browse/PTR-2905) to discuss it.

Best,
Daniel

**Comment by georgel-pop-lr** [comment]
Hi @ealonso @dacousalr,

There is another case the client is complaining about and not sure how to handle it.

If they use this property, `locale.prepend.friendly.url.style=2` the friendly URL doesn't have `web/guest` but we still share it with web guest. 
image


Can we do something about this case without impacting too much the existing implementation?  

Regards.

**Comment by dacousalr** [comment]
Hi @georgel-pop-lr,

Firstly sorry for the delay in my response.

I think that that issue could be fixed by following the approach taken in LPS-135692.

In order to unblock this PR from being forwarded since it has been approved in PTR-2905, you could open a new LPS ticket to treat this case separately.

Would it make sense to you?

Best,
Daniel

**Comment by georgel-pop-lr** [comment]
> LPS-135692

Hi @dacousalr,

Thanks for your help, I will have a look.

Yes, is better to open a separate ticket, also the client said that on integration environment this is not reproduced, and maybe we don't have to fix it, this if production environment behaves as it should on their tests.

Regards.

**Comment by dacousalr** [comment]
Got it, @georgel-pop-lr!

@ealonso, I think that we are ready to try to forward this PR to Brian if possible

Best,
Daniel

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114447

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
