### PR TITLE
LPS-186272 Add warning icon

### PR DESCRIPTION
**Pull request by veroglez**
https://issues.liferay.com/browse/LPS-186272

This PR depends on https://github.com/liferay-echo/liferay-portal/pull/12120. Just review from bcc034dc02c002cb720593b866687f57a74ef8b5 to 8c869638e45ea025090eef854fe18f532aa838fb.

**Testing steps**

1. Create a new site template: 'temp1'
2. Create a new site from the template: 'site1'
3. Add a new page to 'site1', name it "ConflictPage"
4. Add a new page to 'temp1', also named "ConflictPage"
5. Both of the friendly URLs will be "/conflictpage", therefore, they will be colliding.
6. Go to "Site Builder > Pages", verify that a "!" warning sign appears next to the page name. Tooltip on the warning shows more detailed info.
7. Go to "Home > Page Tree", verify that a "!" warning sign appears next to the page name. Tooltip on the page name shows more detailed info.
8. These warnings should work from the template's ([LPS-174465](https://issues.liferay.com/browse/LPS-174465)) and the site's ([LPS-174471](https://issues.liferay.com/browse/LPS-174471)) side as well, just with different tooltip messages.

**Feature flag**
`feature.flag.LPS-174471=true`

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:sf

**Review by claraizquierdo — APPROVED** [review]
LGTM 🎉

**Comment by claraizquierdo** [comment]
Ei @veroglez , everything seems to be working but since the PR it depends on is not merged I don't know if I should forward this.

**Comment by veroglez** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/12333

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
