### PR TITLE
LPS-198977 Add context title to back button in fragment import and configuration

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-198977)

## Steps 
**- Case 1**
- Go to Design > Fragments > Next to fragment set > Click on ellipsis > Import File > See back button
import

**- Case 2**
- Go to Design > Fragments > Upper right click on ellipsis button > Configuration > See back button 
config

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
Nice! 🎉

**Comment by BarbaraCabrera** [comment]
ci:forward

**Comment by BarbaraCabrera** [comment]
ci:forward:force

**Comment by DiegoHu97** [comment]
ci:test:stable

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
