### PR TITLE
LPS-174420 Send the script as a file to avoid having to parse it as a base64

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:forward

**Comment by matthiasblaesing** [comment]
@victorg1991 thanks for taking care of this. I'm not that deep into the inner structure of liferay, but to me your optimized version looks sane and survives a local test (i.e. the testcase I described was correctly rendered).

**Comment by matthiasblaesing** [comment]
@victorg1991 I just noticed a problem. When using "Save and continue". Steps to reproduce:

- Create a new template
- Enter "X Template" as name, and "Test" as content
- Click on "Save and Continue"
- Wait a second
- Click on "Save and Continue"

You get an exception: [liferay.2023-02-07.log](https://github.com/liferay-echo/liferay-portal/files/10678529/liferay.2023-02-07.log)

This is reproducible for me.

**Comment by victorg1991** [comment]
Should be fixed now :)

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by matthiasblaesing** [comment]
@victorg1991 works for me. Thank you.

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @victorg1991, would you mind having a look at this failed integration test? [com.liferay.template.web.internal.portlet.action.test.UpdateTemplateEntryMVCActionCommandTest](https://testray.liferay.com/home/-/testray/case_results/2191969499)

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
The failures are not related to this PR. See https://github.com/brianchandotcom/liferay-portal/pull/130175

**Comment by dacousalr** [comment]
Just started reviewing :)

**Pull request closed without merging**
