### PR TITLE
LPS-202276 Show hidden layout structure items

### PR DESCRIPTION
**Pull request by victorg1991**
This PR makes layout rules works in the view and preview modes 

`feature.flag.LPS-169837=true`

To create rules:

- Create a content page
- Add some fragments (give them custom name to make them easily accessible from the rule builder)
- Go to Page Rules sidebar panel
- Add some conditions and actions
- Publish the page

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Review by ruben-pulido — CHANGES_REQUESTED** [review]

**Comment by victorg1991** [comment]
Updated @ruben-pulido :)

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
