### PR TITLE
LPS-137281 Update templates help to adequate to the new view

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-137281

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
Failures above are not related to this pull, send to BChan directly: https://github.com/brianchandotcom/liferay-portal/pull/105652

**Comment by liulukiwi** [comment]
Cases are failed for [LPS-136747](https://issues.liferay.com/browse/LPS-136747) , [LPS-137465](https://issues.liferay.com/browse/LPS-137465), [LPS-136151](https://issues.liferay.com/browse/LPS-136151),
com.liferay.journal.asset.test.JournalArticleAssetSearchTest and com.liferay.journal.asset.test.JournalArticleAssetSearchTest.testOrderByCreateDateDesc
are flaky issues, pass in other relevant suite, about No CommerceCurrency exists with the key, this has been reported in [COMMERCE-6391](https://issues.liferay.com/browse/COMMERCE-6391), will reopen it if catches it again.

**Pull request closed without merging**
