### PR TITLE
LPS-136434 Gracefully handle invalid FragmentCollection

### PR DESCRIPTION
**Pull request by dnebing**
This is for https://issues.liferay.com/browse/LPS-136434. A client keeps getting into situations where the FragmentCollection is invalid leading the an NPE which totally stops publishing from staging until the data is cleaned up. This change will report the fragment with the invalid FragmentCollection and return, and will not stop publishing from completing.

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/5381

**Pull request closed without merging**
