### PR TITLE
LPS-113710 Fix Collapse button related tests

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/794

**Comment by p2kmgcl** [comment]
ci:reopen

**Comment by p2kmgcl** [comment]
ci:test:stable

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:bundle

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/807

**Pull request closed without merging**
