### PR TITLE
LPS-145046 - Add fragment collection option to item selector

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @p2kmgcl @victorg1991

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ruben-pulido, similar regression issue found. The page is broken after enable local live.
**Steps to reproduce**

1. Add a new site based on Blank
2. Navigate to the Staging admin
3. Enable local live

Expected Results:
Local Live enbled successfully. No error thrown in console.

Actual Results:
The page is broken. The following error is thrown.
```
2022-01-26 05:39:16.480 ERROR [http-nio-8080-exec-2][BaseJSPPanelCategory:101] Unable to include /sites/site_administration_body.jsp
org.apache.jasper.JasperException: java.lang.UnsupportedOperationException: Requires 3.0 opt-in
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:440) ~[jasper.jar:9.0.56]
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473) ~[jasper.jar:9.0.56]
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377) ~[jasper.jar:9.0.56]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
        at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:364) ~[bundleFile:?]
        at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:376) ~[bundleFile:?]
        at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
        at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:63) ~[?:?]
        at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
        at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
```
image

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Pull request closed without merging**
