### PR TITLE
[TS] LPS-202937 | Previous versions of the resource files (CSS and JS) are not available during a long propagation

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you review this fix?
https://liferay.atlassian.net/browse/LPS-202937
best,
Attila

---------

This behavior was considered a bug based on this [PTR](https://liferay.atlassian.net/browse/PTR-4511).
This pull changed the previous behavior in a way that after every resource file is deleted the new version of this file is imported in. This way there is no moment where all the resources are missing. It also greatly reduces the chance of experiencing a case where a resource is not visible to the user.

### CODE REVIEW

**Comment by jkappler** [comment]
Hi @bakayattila, there are conflicts with the PR, can you please take a look at them? Thanks!

**Comment by bakayattila** [comment]
Hi @jkappler,
Sorry for the delay I had to retest it to make sure that the new folder-based import does not break my fix. I pushed the rebased fix with a slight modification to also respect the folder structre.

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
Hi @liferay-echo,
Could you check out the requested changes?
Thanks,
Attila

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:reevaluate:1397401_8692

**Pull request closed without merging**
