### PR TITLE
LPD-15889 | Unable to change Staging Friendly URL

### PR DESCRIPTION
**Pull request by jkappler**
Original comment:

Hi Team,
Could you review this fix?
https://liferay.atlassian.net/browse/LPD-15889
best,
Attila

------------------
The root cause of the issue was the _groupService.updateGroup method which caused a javax.persistence.OptimisticLockException error. My solution was simplifying and unifying the code by using the _groupLocalService.updateFriendlyURL method for both cases.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
Sorry @bakayattila, my bad, adding the method would have caused more logic

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:2533324435

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
Failure are not related to the changes

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
