### PR TITLE
[TS] LPS-168004

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-168004

Motivation:
Adding new attachments before the wiki is published results in "draft" attachments appearing on published wiki page.

Proposed Solution:
Only show attachments uploaded at last publish date or earlier.

Steps for reproduction:
1. Navigate to Menu > Configuration > Workflow.
2. Edit Wiki Page > Select Single Approver > Save.
3. Navigate to Home page > Add a Wiki widget to the page > Publish.
4. Edit the Wiki Front Page > Content: "test1" > Open Attachments tab > Select Files > Any file is ideal > Submit for Publication.

Expected results: The Wiki page does not show any changes > you have to approve the changes first.
Actual results: The attachments are already visible, however the changes are not approved yet.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ChrisKian** [comment]
ci:test

**Comment by jkappler** [comment]
Hi @ChrisKian, this is not Echo Team related, can you please send this to Lima Team?

Thanks

**Comment by ChrisKian** [comment]
Sorry about that @jkappler, I've forwarded the PR to https://github.com/liferay-lima/liferay-portal/pull/3792

**Pull request closed without merging**
