### PR TITLE
LPS-169503 - Add new dropdown options

### PR DESCRIPTION
**Pull request by ruben-pulido**
This PR contains the implementation for "Delete", "Copy" and "Permissions" actions

//cc @ealonso @veroglez @victorg1991 @lfbesada

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
I have updated the PR, since as @ealonso pointed out, the LPS that was used in the feature flag corresponded to the story and not the epic.

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Frontend changes from @sandrodw3 and fixed redirect after copying page [here](https://github.com/liferay-echo/liferay-portal/pull/10681)

**Pull request closed without merging**
