### PR TITLE
LPS-150575 Make sure a "null" is not added to the className

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:reevaluate:1377401_1722

**Comment by victorg1991** [comment]
ci:reevaluate:1377401_1722

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @DiegoHu97 and @victorg1991, there is an regression issue, Could you have a look at?
The ellipsis button is replaced by trash icon on Web Content Display topper after stop Liferay Journal Web module
**Step to reproduce**
1. Add a Web Content Display to a widget page
2. Use stop bundle ID to stop Liferay Journal Web via gogo shell
3. Back to widget page
4. Mouse over on Web Content Display

**Expected Results:**
The ellipsis icon should be shown in Web Content Display

**Actual Results:**
image

**Comment by Tim-Cao** [comment]
Sent Poshi updates here https://github.com/liferay-echo/liferay-portal/pull/7819

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
going to give it a new try because I doubt those test are related (I only changed UI stuff that is not tested in integration tests)

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
