### PR TITLE
LPS-124692 Test that localizable configuration fields have corresponding flag icon

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
For  [parallel] 00:46:02,484 ERROR [Portal Dependency Manager Component Executor--1][JDBCExceptionReporter:234] Duplicate entry '20100-com.liferay.commerce.discount.model.CommerceDiscount-4-com' for key 'IX_A9FF4B2C', I will report this when I see this error twice.

**Comment by liulukiwi** [comment]
All the failures are not related to this pr, so I'll forward this pull to BChan dirrectly.

**Comment by liulukiwi** [comment]
resend:
https://github.com/brianchandotcom/liferay-portal/pull/97306

**Pull request closed without merging**
