### PR TITLE
LPS-188388 Avoid accessing editable values on Fragments if empty

### PR DESCRIPTION
**Pull request by rijema**
**Motivation**
The customer opened a ticker reporting an issue related to editing an existing fragment, after setting the environment and testing different scenarios, I managed to identify that a specific value in the Fragment Content file related to the title of a editable field thad contained a unexpected value when the existing fragment was updated with a lfr-editable  property.

**Proposed Solution**
After debugging I could notice that the object editableValues had no value, so I introduced a condition to avoid checking an empty object and, consequently, stop generating an error.

**Steps to Verify**

Described also on [LPS-188388](https://liferay.atlassian.net/browse/LPS-188388)

Start your liferay-portal 

Access Control Panel > System Settings > Page Fragments > Enable Propagate Fragment Changes Automatically.

Navigate to the Global site and export the [collections-20230615170457241.zip](https://github.com/liferay-echo/liferay-portal/files/11827352/collections-20230615170457241.zip) fragment collection. (Also tested after creating manually with different contents)

Go to the Home page and add the fragments "Accordion" and "Item de Accordion" to the page > Publish the page.

Return to the Global site and modify the fragment "Accordion" with the following change:
`<h2 class="neo-accordion-title" data-lfr-editable-id="title" data-lfr-editable-type="text">Título do accordion</h2>
`

Open the Home Page and try to edit it.

Expected Behaviour:
The fragment changes propagate successfully, with no error on the page. Including when editing the Page Content.

Actual Behaviour:
An error message appears: "Error An unexpected error occured while rendering this item" is showed when editing the page. (Screenshot attached)

What to do next

**Suggestions for testing**
Please feel free to test without downloading the attached document.

**Screenshots** 
Screenshot from 2023-06-21 19-25-25
Current result

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by rijema** [comment]
ci:test:sf

**Comment by rijema** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
hey @rijema I've resent it here: https://github.com/liferay-echo/liferay-portal/pull/12548 :) 

Thanks for the pr

**Pull request closed without merging**
