### PR TITLE
LPS-135805 & LPS-135877 Rename for collection display pagination

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/5248

**Comment by victorg1991** [comment]
already sent here: https://github.com/liferay-echo/liferay-portal/pull/5248

**Pull request closed without merging**
