### PR TITLE
LPS-193304 Adapt import messages to singular and plural

### PR DESCRIPTION
**Pull request by claraizquierdo**
[Link to story or ticket](https://liferay.atlassian.net/browse/LPS-193304)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
Hey @claraizquierdo, this LGTM now 😄 just a few comments/improvements:
- I saw you changed the order of the language keys and then the buildLang commit fixed the order again. For next times, I think it's better if you initially commit the keys in the correct order
- The `collapseHeaderClassNames` prop is already available in `ClayPanel` 🥳 so we can already replace the ugly classes I introduced with a `p-0`
- Another improvement I think we can introduce is creating an `ImportResultsSection` component (or something like that) to avoid repeating almost the same logic three times

As accorded in Slack, we can forward this one and apply those improvements in the next PR.

**Comment by sandrodw3** [comment]
Closing this one as changes are included in https://github.com/liferay-echo/liferay-portal/pull/13266

**Pull request closed without merging**
