### PR TITLE
LPS-191352 Browse to the generic error page if a user tries to access a locked by another user draft

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-191352

Dear reviewer 👋 

Thanks in advance for your review ❤️ 

This PR implements that when a draft is locked by a user other users cannot access the page edit, instead they are redirected to a blocking page.

The lock acquire process isn't implemented yet so we need to use scripts to lock/unlock the draft. In addition, to be able to test it, the feature flag must be enabled:
`feature.flag.LPS-180328=true`

These scripts are useful to test this PR:

* Script to lock a draft by a user

[LockLayout.txt](https://github.com/liferay-echo/liferay-portal/files/12169318/LockLayout.txt)

* Script to see the status of a draft (locked/unlocked) with respect to all the users of the company

[isUnlockedLayout.txt](https://github.com/liferay-echo/liferay-portal/files/12169321/isUnlockedLayout.txt)

* Script to unlock a draft

[UnlockLayout.txt](https://github.com/liferay-echo/liferay-portal/files/12169322/UnlockLayout.txt)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
@jkappler Thank you very much for the feedback 😍 
I have changed the last commits to incorporate the changes.
Could you please review it?
Thank you so much! ❤️

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1387401_8390

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@lfbesada ❤️

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
