### PR TITLE
LPS-123587 Don't render dropdowns until they are open the first time

### PR DESCRIPTION
**Pull request by sandrodw3**
In order to test this, it would be cool if you can add, for example, 100 pages, so you have a column with a lot of items. I'm leaving here a groovy script to add a bunch of pages at a time:

[AddPages.groovy.zip](https://github.com/liferay-echo/liferay-portal/files/8153056/AddPages.groovy.zip)

🥰

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
Works fine :D the difference is quite notably 👏 

Just realized that the buttons in the miller columns doesn't have any title, can we update that? (not related to the pr but it seems like a quick thing to fix :) )

Accessibility wise, since we are hidden the button when clicked to show the dropdown's one, the focus is moved to the body, could we manually give the focus to the "real" button?

**Comment by sandrodw3** [comment]
> Works fine :D the difference is quite notably 👏
> 
> Just realized that the buttons in the miller columns doesn't have any title, can we update that? (not related to the pr but it seems like a quick thing to fix :) )
> 
> Accessibility wise, since we are hidden the button when clicked to show the dropdown's one, the focus is moved to the body, could we manually give the focus to the "real" button?

Um, good point, I'll do it 🥰
Thanks for the feedback!

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
