### PR TITLE
LPS-153160 Include Google Maps JavaScript API script only once

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

This fix solves the issue on 7.3.x because, on master, Geolocation, along with the other DDM fields is rendered with React.

I initially sent the pull to the liferay-forms team, but they said that they are not responsible for the map-google-maps module.
They suggested that perhaps it belongs to your team.
https://github.com/liferay-forms/liferay-portal-ee/pull/126#issuecomment-1122746781

Please let me know if that is not the case.

I cannot reach your liferay-portal-ee repo, so I'm sending this to liferay-portal.

Thank you and best regards,
István

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @IstvanD if this is 7.3.x only, you can send the pr to @dacousalr :)

**Comment by IstvanD** [comment]
Hi @victorg1991 got it! I'll then send it to him.

Regards,
István

**Comment by victorg1991** [comment]
@dacousalr if you need help reviewing this just let us know 😇

**Comment by lfbesada** [comment]
ci:stop

**Pull request closed without merging**
