### PR TITLE
LPS-120210

### PR DESCRIPTION
**Pull request by Commando18**

### CODE REVIEW

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by Commando18** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Hey @Commando18,
Could you please take a look at the test failure? It seems to be related with your changes.
Regards,
Eudaldo.

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by Commando18** [comment]
ci:test:sf

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
@Commando18, could you please take a look at the test that is failing? Adding resourceBundle in base class could break existing implementations that rely on locale and do not have resourceBundle

**Comment by Commando18** [comment]
ci:test:relevant

**Comment by Commando18** [comment]
ci:test:sf

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/2240

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
