### PR TITLE
LPS-114627 Adds new data-qa-id for Global Menu button like in product menu

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Since test failures are unrelated to this fix but caused by LRQA-58578 and in order to not clog up ci resources I pushed the commits directly to BChan brianchandotcom#89469

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
