### PR TITLE
LPS-173795 Rich text fragment

### PR DESCRIPTION
**Pull request by p2kmgcl**
The goal of this story is to create a new fragment input for rich text editing. This simple fragments uses CKEditor with the existing `liferay-editor:editor` taglib.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
I know that CKEditor is throwing some bugs at some points. I am going to list some changes that need to be applied to the taglib and try contributing them:

- CKEditor breaks sometimes when fragment is re-rendered. Taglib should check if the element is still on the page and dispose it if it has been removed.
- There is no "readonly" or "disabled" attribute.
- There should be both "label" and "placeholder" attributes.

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
