### PR TITLE
LPS-146275

### PR DESCRIPTION
**Pull request by mbowerman**
Hi Echo team,

I'm sending these two fixes together since they have similar root causes and I added to the same test method for each fix. Let me know if you prefer me to send them separately instead.

https://issues.liferay.com/browse/LPS-141011
https://issues.liferay.com/browse/LPS-146275

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @mbowerman 
Thanks for the pull request!
Regarding the bug: https://issues.liferay.com/browse/LPS-141011
Could you please clarify the steps to reproduce it? I have understood it because I have read the PTR but I think clarifying it by making the two bugs understandable independently would help in the verification process.
Thanks!

**Comment by mbowerman** [comment]
Hi @lfbesada,

Thanks for the review! Sorry for the confusion on the steps to reproduce. I have edited the description of [LPS-141011](https://issues.liferay.com/browse/LPS-141011) to clarify the steps to reproduce. For your convenience I have copied them below as well:

1. Start up Liferay DXP
2. Login as test@liferay.com
3. Go to Categorization > Categories
4. Create a new vocabulary called 'Test Vocabulary'
5. Edit the vocabulary's settings and add two associate asset types:
 -- All Asset Types - Not required.
 -- Web Content Article - Required.
6. Click 'Save'
7. Edit the 'Test Vocabulary' vocabulary again

**Expected Result:** The asset type settings would be showing as:
   -- All Asset Types - Not required.
   -- Web Content Article - Required.

 **Actual Result:** The asset type settings instead show as:
    -- All Asset Types - Not required.

(The "Web Content Article - Required" setting has been removed.)

**Review by lfbesada — APPROVED** [review]
@mbowerman Thanks for the fix, it works great!
Especially, thanks a lot for so detailed commit messages, it turns the review easier <g-emoji alias="heart" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2764.png" class="social-button-emoji">❤️</g-emoji>.
Regards

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
