### PR TITLE
LPS-120439 Set service rankings

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forwardd

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/Tim-Cao/liferay-portal/pull/470

**Comment by Tim-Cao** [comment]
ci:close

**Comment by liulukiwi** [comment]
resend in https://github.com/liferay-echo/liferay-portal/pull/2464

**Pull request closed without merging**
