### PR TITLE
LPS-165478 Fixing the InfoFramework rendering for SelectInfoFieldType Part I

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-165478

This is the first of two. This one is only fixing the issue, I will send another PR that will include the following:

* Fixing a typo in the method names of the class TemplateNodeTransformerTracker and hiding this interface because it is used only in the template-service module so it doesn't need to be exposed.
* Add some integration tests to ensure:

> * The proper conversion from DDM fields to info fields
> * The expected info field value format that depends on the object value's class
> * The expected rendering of info fields of type "select" using information tem

plates

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
