### PR TITLE
[TS] LPS-202901 User correct title

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
"Down" tooltip is displayed for an "angle-up" icon
[LPS-202901](https://liferay.atlassian.net/browse/LPS-202901)

Proposed Solution
========
Use "up" for title

Steps to Verify
========

1. Create 2 Web Contents
2. Create a Manual Collection for Web Contents
3. Add the 2 Web Contents to the Collection
4. Check the ^ icon for a tooltip

Expected behaviour: The tooltip is Up
Actual behaviour: The tooltip is Down

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
Thanks @balazssk :)

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
