### PR TITLE
LPS-141974

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-141974

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by javalosjr96** [comment]
@ruben-pulido 
I've figured out what the issue is, and I'll make the changes you requested.
Thanks for finding this issue.

**Comment by javalosjr96** [comment]
@ruben-pulido 
[PR#86](https://github.com/mbowerman/liferay-portal/pull/86)

**Pull request closed without merging**
