### PR TITLE
LPS 161452

### PR DESCRIPTION
**Pull request by robertoDiaz**
Hi, 

The main reason to open this PR is fix some performance issues we've detected when rendering articles.

In the past the content xml was stored in the database, but now this column has been removed.

Anyway some uses of the XML remain in the product, and, for example it is been used to calculate the language ids of the content.

Another problem is that is been cached. In the past it was almost free because we didn't had to parse or calculate it, but now we force the system calculate it every time we retrieve the article from the database.

Since that I've:

- Remove the document field cache 
- Remove some uses of the xml (that assume that this xml is cached)

If you have any question, do not hesitate in contact me.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
Hi @liferay-echo 

Any update about this?

The customer has a workaround but we want to provide a fix to solve the issue.

Thanks!

**Comment by ruben-pulido** [comment]
Thanks for the fix @robertoDiaz! Forwarding it to Brian

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
Thank you @ruben-pulido 

Maybe it could be interesting launch some performance test once it is in master.

**Comment by ealonso** [comment]
ci:forward

**Comment by robertoDiaz** [comment]
ci:reopen

**Pull request closed without merging**
