### PR TITLE
LPD-33656 and LPD-33657 Add an Upgrade Process to add the new portlet preferences and remove the feature flag

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-33656 
https://liferay.atlassian.net/browse/LPD-33657

Dear reviewer, 

I think that the helper methods for calculating and caching the external reference code of the preference scope, in the medium term, would be beneficial to move to BasePortletPreferencesUpgradeProcess as they will also be useful for widget preferences that do not have display templates.
However, I have left them in BaseUpgradePortletPreferences for now as they are only needed here currently. 

Thank you for the review! :heart:

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1307401_9945

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:upgrade

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:report:70210038

**Comment by lfbesada** [comment]
ci:report:70210038

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
