### PR TITLE
LPS-159886 [App Pages] Take into account that input fragment entries could be hidden by the master layout

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-159886

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
@lfbesada Usually we use "cannot-have" instead of "may-not-have"

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1377401_4069

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1327401_5195

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121494

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
