### PR TITLE
LPS-132737 Isolate Product Menu, Control Menu, Add Panel, Simulation Menu, Page Audit, Page Editor Toolbar CSS

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-132737

This PR isolates the CSS in Product Menu, Control Menu, Simulation Menu, Add Panel, and Page Audit. I wanted to send them as separate pulls to make it easier to review but these components are too intertwined together, changing one (e.g., Control Menu) breaks all the Menus.

The CSS I'm using to test my changes:

```html
<style>
html {
  font-size: 20px;
}

#senna_surface1 h1,
#senna_surface1 h2,
#senna_surface1 h3,
#senna_surface1 h4,
#senna_surface1 h5,
#senna_surface1 h6 {
  background-color: #282828;
  border: 4px solid #00ff66;
  color: #00ff66;
  font-family: Georgia;
  font-size: 50px;
  font-style: italic;
  font-variant: small-caps
  font-weight: bold;
  line-height: 100px;
  letter-spacing: 2px;
  margin: 10px 0;
  padding: 10px;
  text-align: center;
  text-shadow: 1px 1px 0 #fff;
  text-transform: uppercase;
  white-space: nowrap;
}

#senna_surface1 .btn {
  background-color: #282828;
  border: 4px solid #00ff66;
  color: #00ff66;
  font-family: Georgia;
  font-size: 50px;
  font-style: italic;
  font-variant: small-caps
  font-weight: bold;
  line-height: 100px;
  letter-spacing: 2px;
  margin: 10px 0;
  padding: 10px;
  text-align: center;
  text-shadow: 1px 1px 0 #fff;
  text-transform: uppercase;
  white-space: nowrap;
}

#senna_surface1 .btn:hover {
  background-color: #000;
  color: #ffcc00;
  letter-spacing: 4px;
  font-size: 40px;
}

#senna_surface1 a {
  background-color: #282828;
  border: 4px solid #00ff66;
  color: #00ff66;
  font-family: Georgia;
  font-size: 50px;
  font-style: italic;
  font-variant: small-caps
  font-weight: bold;
  line-height: 100px;
  letter-spacing: 2px;
  margin: 10px 0;
  padding: 10px;
  text-align: center;
  text-shadow: 1px 1px 0 #fff;
  text-transform: uppercase;
  white-space: nowrap;
}

#senna_surface1 a:hover {
  background-color: #000;
  color: #ffcc00;
  letter-spacing: 4px;
  font-size: 40px;
}
</style>
```

Product Menu Isolated
product-menu-isolated

Simulation Menu Isolated
simulation-menu-isolated

Add Panel Isolated
add-panel-isolated

Page Audit Isolated
page-audit-isolated

Page Editor Toolbar Isolated
page-editor-tlbr

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
@p2kmgcl @victorg1991 Is it possible to get this in for our next 7.4 release?

**Comment by victorg1991** [comment]
Checking this now @pat270 :)

**Comment by victorg1991** [comment]
Since the test are green and the pr has a lot of changes I think it is better to send this to brian right away. I've tested it a bit and found a couple of minor things:

Icon menu is now black

Screenshot 2021-07-13 at 17 53 28

Plus button was not present when the tree node didn't have children
Screenshot 2021-07-13 at 17 53 03

Do you want to track those as bugs or are you going to use the same LPS?

**Comment by pat270** [comment]
@victorg1991 Let's do same LPS. I'll send those fixes in.

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
hey @pat270 LocalFile.UIInfrastructureUsecase#RightToLeftSmoke failure seems legit, can you check it out?

**Comment by pat270** [comment]
@victorg1991 You're right. I think the cause is cadmin isn't being processed by our rtl css converting thing. Do you happen to know how I can add that?

**Comment by victorg1991** [comment]
Not sure about that, I'm checking frontend-css-web (which is getting converted) and it have this class: https://github.com/liferay/liferay-portal/blob/a7d01e03127bd1dcd09abe64c80462bb0a0796a1/modules/apps/frontend-css/frontend-css-web/src/main/java/com/liferay/frontend/css/web/internal/CSSPortalWebResources.java#L32-L68
Maybe adding something similar to the cadmin module makes the trick 🤔  @pat270

**Comment by pat270** [comment]
@victorg1991 I tried this and I get the regular version and the rtl version at the bottom of the page. I'm def doing something wrong. @izaera help please :pray:.

**Comment by izaera** [comment]
I've found the problem. I think I won't be able to fix it today (properly). Tomorrow it will be fixed (or worked around), for sure.

**Comment by victorg1991** [comment]
Many thanks @izaera ! :)

**Comment by izaera** [comment]
Resent as https://github.com/liferay-frontend/liferay-portal/pull/1254 (for CI and review of changed APIs)

**Comment by victorg1991** [comment]
Thanks! Closing this here since everything looked fine apart from the two issues I mentioned earlier :)

**Pull request closed without merging**
