### PR TITLE
LPS-153410 It is not possible to import a structure into an existing one

### PR DESCRIPTION
**Pull request by leticia-maciel**
Related Issue: https://issues.liferay.com/browse/LPS-153410

Reviewed on https://github.com/liferay-forms/liferay-portal/pull/1687

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by lfbesada — CHANGES_REQUESTED** [review]
Hi @leticia-maciel 
Thanks for the pull request! ❤️ 
It works great 👏 
Could you please do a couple of minor changes?
1. The commit ["LPS-153410 Add language keys"](https://github.com/liferay-echo/liferay-portal/pull/8140/commits/55744262789161aaebf771adfa3cc319e75e20f8) should be split into two commits. The autogenerated code by the buildLang command must be in a separate commit.
2. Following our design pattern, the alert message in the popup file selection should be "Stripe" type.
Thanks a lot!
Regards

**Comment by lfbesada** [comment]
@leticia-maciel see Stripe type warning example
Captura de pantalla 2022-05-19 a las 14 21 33

**Comment by victorg1991** [comment]
Hey @leticia-maciel this is working fine, I'd suggest a minor change on top of what Lourdes has said :) 

Given that we have 2 very similar modal (the other is ImportDataDefinitionModal) could we use the mechanism to open them?

The other modal is defining a Liferay.component: https://github.com/liferay/liferay-portal/blob/21078d8663ae2a8d264f611a68d0e17c4ef9a056/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/js/modals/ImportDataDefinitionModal.js#L51-L66

And it is opened obtaining the component and calling the open function as here: https://github.com/liferay/liferay-portal/blob/89032c37d40408bcca439a50c49139647eda1dbb/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/configuration/icon/import_data_definition.jsp#L50-L56

What do you think? :)

**Comment by leticia-maciel** [comment]
Hi @lfbesada and @victorg1991 ,

thanks for the suggestions!! I'll do the changes with no problem :grin: 

Should I close this PR and open another when the changes are ready or can I just push here?

Thanks again :wink:

**Comment by victorg1991** [comment]
@leticia-maciel as you prefer :) You can push the changes here

**Comment by leticia-maciel** [comment]
Hey @lfbesada @victorg1991 ,
I did the modification you asked! Can you check if everything is okay now?
Thanks :)

**Comment by lfbesada** [comment]
Hi @leticia-maciel 
Thanks a lot for your work! ❤️ 
From my side it's approved, @victorg1991, please forward this pull request once your review has passed.
Thanks
Regards

**Review by lfbesada — APPROVED** [review]

**Comment by victorg1991** [comment]
Hey @leticia-maciel good job! just made a minor spacing fixes and resent it here https://github.com/liferay-echo/liferay-portal/pull/8203 👏

**Pull request closed without merging**
