### PR TITLE
LPS-200877 Redirect to sign in URL when redirect is true

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-200877)

## Steps 

- Go to Control Panel / Security / SAML Admin
- Select SAML Role: Identity Provider, and type "samlidp" as Entity ID > Save
- Press the "Create Certificate" button and fill out all mandatory fields, and "Save" the certificate
- Tick the Enable checkbox, and press "Save", to activate the Identity Provider role
- Logout the portal
- Click Sign in button

https://github.com/liferay-echo/liferay-portal/assets/91208451/ae7b32b2-76e3-48ba-aa97-084cec574ccc

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by gaborlovasdotcom** [comment]
ci:test:security

**Comment by JoyceWang08211** [comment]
> ### ❌ ci:test:security - 305 out of 333 jobs passed in 1 hour 57 minutes
> Click here for more details.

The fix doesn't work on multiple [idps](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=2453378581&testrayComponentId=1310779464&testrayRunId=2453381429). I'll write down the reproduced steps later.

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/14236

**Pull request closed without merging**
