### PR TITLE
LPS-164280 Filter InfoForm implementations by using the InfoPermissionProvider to provide only those implementation that the user is allowed to VIEW

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-164280

Dear reviewer ❤️ 

This PR needs the LPS-164263 commits, those commits were merged in the Brian repo but the Liferay repo hasn't synchronized. That is the reason those commits are included here but just **the four** LPS-164280's commits should be reviewed.

Thanks in advance!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
ci:reevaluate:1327401_6031

**Comment by lfbesada** [comment]
ci:forward

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/123910

**Comment by ozysouza** [comment]
ci:close

**Pull request closed without merging**
