### PR TITLE
LPS-149491

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team!

Could you please review my fix?

This is a fix for the regression of https://issues.liferay.com/browse/LPS-145308
The regression is: https://issues.liferay.com/browse/LPS-149491

Thanks, Roland

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
Hi @rolandpakai 
Thanks for the fix! 
I was analyzing the regression bug and the original bug and I found that when you apply the first commit, the regression bug is fixed but the original bug in the master branch is not reproducible following the described steps.
Because of that, I think that the second commit is not needed so I sent a pull request just with the first commit. Please see: https://github.com/liferay-echo/liferay-portal/pull/7597
Please, if is my bad and you are able to reproduce it, could you please add a video in order to check if I am missing some steps?
Thanks a lot!
Regards.

**Comment by rolandpakai** [comment]
Hi @lfbesada 
indeed, reverting the LPS-145308 is fixing the original issue.

Thanks, Roland

**Comment by lfbesada** [comment]
Hi @rolandpakai

If I understood you properly, you agreed with me that once the commit was reversed in master the bug was not reproduced, is that right?

If that is the case, there is no fix to apply in master because there is no bug.

I looked trying to find how the bug was solved in master but I didn't find the commit that solved it. 

The case that you were catching in your commit, resourcePrimKey matching the article that holds the structure default values, is not reproducible in the master branch.

I am sorry not to be able to help.

Regards

**Pull request closed without merging**
