### PR TITLE
LPS-113161 Clear list on error

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
Just estarted reviuing

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/642

**Comment by p2kmgcl** [comment]
ci:close

**Pull request closed without merging**
