### PR TITLE
LPS-122372 Removes deprecated classes, since those are not usefull for third part developers

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Since one failure task is semantic versioning for com.liferay.portal.kernel.security.permission and the other failure case is a test fix here https://issues.liferay.com/browse/LRQA-62596. and in order to not clog up ci resources I pushed directly to BChan.
See https://github.com/brianchandotcom/liferay-portal/pull/95224

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
