### PR TITLE
LPS-167609 - Mouse hover information is not available for keyboard

### PR DESCRIPTION
**Pull request by ethib137**
https://issues.liferay.com/browse/LPS-167609

This PR adds the `lfr-portal-tooltip` class so that title is visible onHover, onFocus, and read by screen readers.

Screenshot 2023-03-15 at 11 31 48 AM

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
