### PR TITLE
LPS-133077 We need to use classPK too, otherwise all asset list will have the same classNameId

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @victorg1991, the Mapping panel of nested fragment is broken in Collection Display.
Actual

**Comment by p2kmgcl** [comment]
Having a look :eyes:

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/4730

**Pull request closed without merging**
