### PR TITLE
[7.4 ONLY] LPS-122017 Avoid getting empty object as image url

### PR DESCRIPTION
**Pull request by victorg1991**
This is 7.4 only code

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jpince** [comment]
`PortletTitleTest.testPortletTitles` Hey guys, this test is usually very consistent in identifying real issues. Please check your code if it fails again.

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
