### PR TITLE
LPS-137014

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1277401_318

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/5942

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reevaluate:1077401_7347

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/5956

**Pull request closed without merging**
