### PR TITLE
LPD-16488 | Search box doesn't work for private pages in display page for web content

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you review this fix?
https://liferay.atlassian.net/browse/LPD-16488 
best,
Attila

-------

There were two bugs in the code. The first root cause for the UI error was in the [FindLayoutsStrutsAction.java](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-taglib/src/main/java/com/liferay/layout/taglib/internal/struts/FindLayoutsStrutsAction.java#L70-L89). The issue was the out of bound request with requesting a list from 0 to 0,  0 not included. I fixed this issue by skipping the whole requesting and processing logic if the count is not bigger than zero. The other bug was in selectLayoutTags where the searchURL did not pass the privateLayout boolean to the findLayoutAction.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
Hi @bakayattila, checking the PR, you cannot select a private page. So I'm wondering if we should even show the private pages tab when selecting the display page
 
Screenshot 2024-02-05 at 13 09 45

**Comment by jkappler** [comment]
Thanks @bakayattila, missed this use case 😓

**Comment by jkappler** [comment]
ci:forward

**Comment by bakayattila** [comment]
It's my fault. It was not in the original steps. I only added the asset publisher out of habit 😄

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:report:2534992027

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
Failures are not related to the changes

**Pull request closed without merging**
