### PR TITLE
LPS-190825 Show customized field reference value instead of the default one

### PR DESCRIPTION
**Pull request by YurenaC**
Motivation
=======
An impedibug was raised when testing a relates story as when the user customizes the option labels available in the select sections in a web content, those new names are not shown properly. (Please for more info go to the original [Story](https://liferay.atlassian.net/browse/LPS-190825) ) 

Proposed Solution
========
In order to keep showing accurate information when a graphQL query is executed, information like the customized field reference value (label) and the original reference will be added to the response.

Steps to Verify
========

1. Add a web content structure with a Select from List field
2. Add two options with customized field reference for Select from List
3. Add a web content based on new structure
4. Get the id of structuredContent via getSiteStructuredContentsPage
5. Navigate to the  GraphQL GUI -> http://localhost:8080/o/api
6. Get the structuredContent with contentFieldValue

 ```

{
  structuredContent(structuredContentId: {structuredContentId}) {
    contentFields {
			contentFieldValue {
			  data
			  value
			}
    }
  }
}
```
7. Expected result as follows:
SelectExpectedResult

COMMITS:
-------------------
LPS-190825 Show customized field reference value instead of the default one

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward:force

**Pull request closed without merging**
