### PR TITLE
LPD-19215 Wrap containerKey value in quote

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
During upgrade, a LayoutClassedModelUsage can't be identified if the db is PostgreSQL.
[LPD-19215](https://liferay.atlassian.net/browse/LPD-19215)

Proposed Solution
========
Wrap containerKey value in quote to signal its type is String (varchar) to the DB

Steps to Verify
========
1. Start up a 7.4 u92 bundle
2. Create a web content
3. Create a page
4. Add a Heading fragment to the page
5. In the Heading fragment's element-text component map the created web content's title
6. Publish the page
7. Stop DXP and upgrade it to 2023.q4.4

**Expected behaviour:** The update finishes with no issues

**Actual behaviour:**
The upgrade fails with the attached error:
```org.postgresql.util.PSQLException: ERROR: operator does not exist: character varying = integer_  Hint: No operator matches the given name and argument types. You might need to add explicit type casts._```

Cheers,
Balázs

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by balazssk** [comment]
ci results are full of github and drive space errors, I'm restarting them

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
ci:test:upgrade

**Comment by balazssk** [comment]
Can't see any relevant issues with ci:test:upgrade

**Comment by achaparro** [comment]
ci:report:2546156937

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
