### PR TITLE
LPS-175543 Extract AssetSearcher from portal-impl

### PR DESCRIPTION
**Pull request by jkappler**
Task: https://issues.liferay.com/browse/LPS-155403
Subtask: https://issues.liferay.com/browse/LPS-175543

@lfbesada, @Mikellorza

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by alessandromalves** [comment]
Only two unique failures were found by the CI ([see comparison with acceptance master results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2316776549&testrayRunIdA=2316107771&statusB=3))  and were not reproducible locally. The others are not related to this PR. See https://github.com/brianchandotcom/liferay-portal/pull/135251

**Pull request closed without merging**
