### PR TITLE
LPS-200877 Simplify sign in process

### PR DESCRIPTION
**Pull request by p2kmgcl**
@DiegoHu97 Instead of maintaining multiple variables to handle the state logic, try to create a linear flow that is easier to follow. When user clicks the "sign in" button:

1. If we should redirect to other page, do it and stop the process.
2. Otherwise, start loading the modal content.
   a. Open the modal.
   b. Wait until the modal content has finished loading.
   c. Show the modal content.
3. If anything unexpected happens (no modal content, some error...), just redirect.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
cc @gaborlovasdotcom @JoyceWang08211 this should be ready to forward

**Comment by JoyceWang08211** [comment]
> ### ❌ ci:test:security - 287 out of 330 jobs passed in 2 hours 15 minutes
> Click here for more details.

No regression was found.

**Comment by JoyceWang08211** [comment]
ci:forward

**Pull request closed without merging**
