### PR TITLE
LPS-127939 Always use title defined by the panel app, unless undefined

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @liferay-echo 

I had to make a very small change to the panel app taglib logic. Please take a look to the second commit and forward this if you're ok with it.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
