### PR TITLE
LPS-196591 Make available locked pages settings at site level

### PR DESCRIPTION
**Pull request by Mikellorza**
story: https://liferay.atlassian.net/browse/LPS-194241
subtask: https://liferay.atlassian.net/browse/LPS-196591

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
Hi @jkappler ,

I made some changes about your proposal. Take a look when you have time.

Thanks for your review!

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
