### PR TITLE
LPS-135665 asset-categories-admin-web: group category actions and use dropdown-items

### PR DESCRIPTION
**Pull request by victorg1991**
These commit are already reviewed: 

LPS-135843 Extract functions to its own file
LPS-135843 Take into account action groups in cards components
LPS-135843 Take into account action groups in management toolbar
LPS-135843 If all the groups are empty just return null to avoid rend… 
LPS-135665 asset-list-web: group action in asset list dropdown
LPS-135665 asset-tags-admin-web: group actions in tags
LPS-135665 asset-categories-admin-web: group actions in categories ma… …
LPS-135665 asset-categories-admin-web: group vocabulary actions and u… …
LPS-135665 asset-categories-admin-web: group category actions and use… …

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @julien the first 4 commits are the one that implement the support for item groups in cards and management toolbar :) Let me know what do you think!

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by victorg1991** [comment]
waiting for julien review :)

**Review by julien — APPROVED** [review]

**Comment by victorg1991** [comment]
@markocikos This pr includes some changes from frontend-taglib-clay to support having dropdown actions of type group. This was previously done for dropdown in cbabc75a866b094c28d29cb4be99410193c6c3a0

Could you take a look?

Let me know what do you think :)

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/5272

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
