### PR TITLE
[TS] LPS-156013

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

We have detected an inconsistency in content page templates when they are published to Live regarding the privateLayout column of the Layout records related to this type of templates, which is changed from true (in Staging) to false (in Live).

This solution adds a specific attribute at export time to be read at import time and set the appropriate value for the privateLayout column.

Could you please review it?

Thanks in advance!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Hi @dacousalr 
Thanks for the fix!
Regards

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
