### PR TITLE
[TS] LPS-137532 Have search container return only the orphan portlets to be displayed

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi team,

Can you help review this PR?

**Notes from @noornajj:**

> https://issues.liferay.com/browse/LPS-137532
> 
> The issue here was that the orphan widgets page would not update with the correct number of entries when the number of entries per paged was less than the total number of entries.
>
> To fix this, I made sure the results in the orphanPortletsSearchContainer only holds the portlets to be displayed instead of all the portlets.

Feel free to let us know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
See: https://github.com/liferay-echo/liferay-portal/pull/5580

**Pull request closed without merging**
