### PR TITLE
LPS-111779 expose preview

### PR DESCRIPTION
**Pull request by nhpatt**
Hi @pavel-savinov!

Please review the changes, I'm not sure if the existing ObjectMapper is enough, if it is not, remove this commit https://github.com/liferay-echo/liferay-portal/commit/501842e9d1b07c2d4ab4431030b6f5b0e36d465f.

Brian likes to use auto generated OperationId, apart from that everything is perfect (but he can complain about  "/sites/{siteId}/page-definitions/preview", it's possible that he would like to change the preview for something else).

Nice work :)

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by nhpatt** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:close

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Pull request closed without merging**
