### PR TITLE
LPS-144629 Use the new ClayTreeView component

### PR DESCRIPTION
**Pull request by john-co**
Resent from https://github.com/liferay-lima/liferay-portal/pull/2715
cc/ @julien

----

In this change, we're migrating from our previous
[Treeview](https://github.com/liferay/liferay-portal/blob/c5a9a72d3a58a504233e4cc799652fc9f544ba5e/modules/apps/frontend-js/frontend-js-components-web/src/main/resources/META-INF/resources/treeview/Treeview.js) component to the new [ClayTreeView](https://github.com/liferay/clay/blob/d7340f875372ba7ac11752aedd70f4343100241b/packages/clay-core/src/tree-view/TreeView.tsx) component.

**Test plan:**

- Fetch this branch
- Deploy the journal-web OSGi module
- Navigate to Content & Data > Web Content
- Create a new Folder
- Create a new Basic Web Content
- Click on the ellipsis icon to the right of the Web Content
- Click on the "Move" option
- Click on the "Select" button
- In the modal window, choose a destination Folder

### CODE REVIEW

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:sf

**Comment by john-co** [comment]
ci:test:echo

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:relevant

**Comment by john-co** [comment]
ci:test:echo

**Comment by john-co** [comment]
ci:test:acceptance-functional

**Comment by john-co** [comment]
ci:stop

**Comment by john-co** [comment]
I was working on possible test fix but it got more complicated than I first thought b/c there's a macro that gets widely used `Portlet.expandTree`. I also believe there will be other failing tests besides the other two relevant tests that failed. I don't have much more time today and I'm doing EVP 1/2 days this week so I think it's better to pass this on to someone else to keep this moving.

cc/ @david-gutierrez-mesa @Tim-Cao would you be able to pick up the test fixes here? I believe the macro is mostly used in Echo and a couple usages in Document and Commerce components. Feel free to piggy back from my commits or scrap them. I also wanted to let you (echo-qa) know of this PR to review for any other regressions/test fixes. We want to involve product team QA's for review since FI is not as familiar with the product usecases and product team tests.

cc/ @zhangyan0701 could you help if needed on FI QA side? Consider asking Kevin too if he's able to work on things like this.

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @john-co, I've made some additional changes see https://github.com/liferay-echo/liferay-portal/pull/7164

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
