### PR TITLE
LPD-25498 Review & adapt tests using hard-coded test password

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you review this fix?
https://liferay.atlassian.net/browse/LPD-25498
best,
Attila

I reviewed the following files:
[CustomMetaTags.testcase](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-seo-web-test/src/testFunctional/tests/CustomMetaTags.testcase)
[DisplayPageTemplates.testcase](https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/layout/pagetemplate/displaypagetemplate/DisplayPageTemplates.testcase)
[ExperienceCreateExperienceWithStaging.testcase](https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/enduser/segmentation/ExperienceCreateExperienceWithStaging.testcase)
[LocalizationWithSites.testcase](https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/site/LocalizationWithSites.testcase)
[MySites.testcase](https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/site/mysites/MySites.testcase)
[NavigationMenus.testcase](https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/sitenavigation/navigationmenu/NavigationMenus.testcase)
[SiteMembershipsWithXSS.testcase](https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/site/SiteMembershipsWithXSS.testcase)
[SitesExportImport.testcase](https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/site/SitesExportImport.testcase)
[SitesUseCase.testcase](https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/site/SitesUseCase.testcase)
[CanonicalURL.testcase](https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/tests/enduser/wem/seo/CanonicalURL.testcase)

Only modified the hardcoded password for the admin user (test@liferay.com) I left the hardcoded value for the users created by the tests.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relelvant

**Comment by bakayattila** [comment]
ci:test:echo

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:echo

**Comment by ealonso** [comment]
ci:test:echo

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
