### PR TITLE
[TS] LPS-127732

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

I have done some tests and everything seems to work as expected.

Could you please review it?

Thanks in advance.

@NemethNorbert originally wrote:

> LPS-127732
> When we are changing styles the removeformat plugin is called to make sure we are only applying the style we want on the selection:
> liferay/alloy-editor@master/src/components/buttons/button-styles-list-item.jsx#L91-L103
> 
> First we intended to fix the reported issue, by enlarging the selection to the html element as well, when using removeformat. It resolves the issue when we are selecting the whole paragraph, however it doesn't when we only select a word or just part of the paragraph. This proposal was reviewed, we found its limitation and concluded:
> liferay-frontend#895 (comment)
> 
> Based on our findings, I concluded the issue here is we are defining the lead and small style changes as block level changes, however in reality they are inline level styles and they can also be applied trough the usage of html elements -> <small> and <big>
> This is what is used in ckeditor if you check
> ckeditor.com/docs/ckeditor4/latest/examples/removeformat.html
> 
> If we check ckeditor.com/docs/ckeditor4/latest/examples/removeformat.html
> we can see ckeditor defined small and big as inline styles and they also end up using their html tag equivalent -> <big> <small>
> I modified the configuration to apply these styles to our selection with a <span> html tag and made them inline level styles, as they should be.
> Because of this change, the block level and inline level styles are separated and does not have an effect on each other, unless the whole paragraph is selected. This behaviour is the same as in ckeditor and prevents confusion about the intended behaviour.

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Thanks @NemethNorbert and @dacousalr!

**Pull request closed without merging**
