### PR TITLE
LPD-28611 Change the expected result

### PR DESCRIPTION
**Pull request by veroglez**
https://liferay.atlassian.net/browse/LPD-28611

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:playwright

**Comment by veroglez** [comment]
ci:stop

**Comment by veroglez** [comment]
ci:test:playwright

**Comment by sandrodw3** [comment]
@veroglez what I meant was something like that:

```
const cards = await page.locator('.card').all();

for (const card of cards) {
	await expect(card.getByLabel('Select Template:')).toBeVisible();
}
```

This way you make sure all cards have the "Select Template" label

**Comment by veroglez** [comment]
ci:test:playwright

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
