### PR TITLE
LPS-115224 Support string textColor

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Just started reviewing

**Comment by Tim-Cao** [comment]
Hi @pavel-savinov, there is a regression issue. The Pages admin is broken.
Actual

**Comment by Tim-Cao** [comment]
The poshi issue is already fixed.
See https://github.com/liferay-echo/liferay-portal/pull/1916

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/1917

**Pull request closed without merging**
