### PR TITLE
LPS-156553 Default name and friendlyURL in site initializer extender

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-156553 There are cases where the locale is not informed or we simply want a specific default value that works independen
- LPS-156553 Adapt welcome site initializer
- LPS-156553 Adapt tests

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
