### PR TITLE
LPS-201702 Add FF LPS-196766  Filter and search improvements in Web Content

### PR DESCRIPTION
**Pull request by Mikellorza**
task: https://liferay.atlassian.net/browse/LPS-201702

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143834

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
