### PR TITLE
LPS-164875 Urgent Accessibility Issue cannot tab through page with editor

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-164875

I was able to find this issue and fix it in Page Templates, Templates, and Fragments.

For this issue, I decided to use Ctrl + M in order to disable the tab functionality in the editor and make it possible to change focus.
I decided to use this instead of Esc since in HTML Editor Modal in Page layout Esc will close modal. I also found that these keys are recognized as a way to change the tab behavior in editors.
https://stackoverflow.com/questions/30112415/what-is-accessibility-mode-for-ctrl-m

I also followed Evan's direction on how to handle the Screen Reader here: https://github.com/ethib137/liferay-portal/pull/62#issuecomment-1271455256

Let me know if there are any questions or comments about this.
Thank you!

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Hello @veroglez,

Thank you for taking a look at this and providing my next steps. I do have some questions.

Once the user enables `Tab` for the editor, should we have a way to disable it again? If so, which key presses should that be?

Also, for users not using a Screen Reader, this means I will have to display these instructions, `Press Ctrl + M..` somewhere by the editor correct? If so, how should I go about doing this?

Thank you again for all your help!

**Comment by veroglez** [comment]
Hi @fortunatomaldonado!

I'm so sorry for the long delay for the response. Don't worry about this, the Echo team will take care of this, since a specific design had to be made to solve this issue.

Thank you very much for your concern!

**Pull request closed without merging**
