### PR TITLE
LPS-191944 Handles dropzones propagation through locked layouts #13567 

### PR DESCRIPTION
**Pull request by jkappler**
https://liferay.atlassian.net/browse/LPS-191944

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Hi @jkappler , some integration testa are failed in this pull, can you take a look? thanks!

[com.liferay.layout.page.template.admin.web.internal.importer.test.LayoutsImporterTest
](https://testray.liferay.com/home/-/testray/case_results/2420295760/history)[com.liferay.layout.page.template.admin.web.internal.portlet.action.test.ExportMasterLayoutsMVCResourceCommandTest
](https://testray.liferay.com/home/-/testray/case_results/2420295803/history)com.liferay.layout.page.template.admin.web.internal.portlet.action.test.ExportImportMasterLayoutsTest
com.liferay.layout.page.template.admin.web.internal.portlet.action.test.ExportImportDisplayPagesTest
[com.liferay.layout.content.page.editor.web.internal.portlet.action.test.UpdateItemConfigMVCActionCommandTest
](https://testray.liferay.com/home/-/testray/case_results/2420295749/history)com.liferay.layout.content.page.editor.web.internal.portlet.action.test.UnmarkItemsForDeletionMVCActionCommandTest
com.liferay.layout.content.page.editor.web.internal.portlet.action.test.AddPortletMVCActionCommandTest
[com.liferay.layout.page.template.admin.web.internal.portlet.action.test.ExportLayoutPageTemplateEntriesMVCResourceCommandTest
](https://testray.liferay.com/home/-/testray/case_results/2420295796/history)com.liferay.layout.page.template.admin.web.internal.portlet.action.test.ExportDisplayPagesMVCResourceCommandTest
[com.liferay.layout.content.page.editor.web.internal.portlet.action.test.PublishLayoutMVCActionCommandTest
](https://testray.liferay.com/home/-/testray/case_results/2420295888/history)com.liferay.layout.content.page.editor.web.internal.portlet.action.test.AddItemMVCActionCommandTest

**Comment by jkappler** [comment]
Thanks @liulukiwi!

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
