### PR TITLE
LPS-203762 Themes whose portal_normal.ftl doesn't have an element with id 'content' can produce a noninformative NPE

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Reproducing Steps

1. Create a theme (using yo liferay-theme, for example)
2. Edit the file portal_normal.ftl to change the line `<section id="content">` to `<section id="content1">`.
3. Deploy the theme to a Liferay (with gulp deploy, for example).
4. Set the theme for the public pages in the default site.
5. Go to the URL http://localhost:8080/c/portal/status to force the execution of the class StatusStrutsAction.java.

> [!NOTE]
>This bug is also reproducible doing the changes in the classic theme instead of creating a new one.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
Hey @BarbaraCabrera,
Could you please look for getElementById("content")? We have more usages and I think we should also change those, Could you please double check it?

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @BarbaraCabrera, there is a regression issue. The preview in a new tab doesn't work.
Steps to reproduce
1. Add a new site
2. Add a Button fragment into a content page
3. Click the ellipsis button on control menu > Preview in a new tab

Expected Results
The preview page open in a new tab

Actual Results
The page editor open in a new tab again

**Pull request closed without merging**
