### PR TITLE
LPS-171029 Add tests for ItemConfiguration

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:stop

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1277401_6214

**Comment by Tim-Cao** [comment]
Hi @ealonso, I've contacted with @sandrodw3 via slack, there is a regression issue found.

**Comment by sandrodw3** [comment]
> Hi @ealonso, I've contacted with @sandrodw3 on slack, there is a regression issue found.

Hey @Tim-Cao, I'm not being able to reproduce the regression, could you give me some steps? Thanks!

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
