### PR TITLE
LPS-161812 Enable select favicon using extensions

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
Hi @victorg1991, would you mind checking the integration test failures?

**Comment by victorg1991** [comment]
Sure thing @Tim-Cao  :)

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ozysouza** [comment]
ci:reevaluate:1307401_4466

**Comment by ozysouza** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:reevaluate:1367401_1955

**Comment by ozysouza** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/122599

**Comment by ling-alan-huang** [comment]
@victorg1991 
Please see SF issue [here](https://github.com/ling-alan-huang/liferay-portal/pull/1318#issuecomment-1236283724), it's related to your changes [here](https://github.com/liferay/liferay-portal/commit/71966ae450fa226b0a5bd44ec86d986d9260f13b#diff-ef119629946c9b5876f3ddaf7e739fa3316781f38535fa10141db62509a5d684L746).

```
     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: Missing language key 'add-custom-field': ./modules/apps/expando/expando-web/src/main/java/com/liferay/expando/web/internal/display/context/ExpandoDisplayContext.java (SourceCheck:LanguageKeysCheck)

```

**Comment by ling-alan-huang** [comment]
see https://github.com/brianchandotcom/liferay-portal/pull/122616#issuecomment-1236429332

**Pull request closed without merging**
