### PR TITLE
LPS-205015 Add aria-label to restricted pages icon

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-205015)

## Steps

**Case 1: MillerColumnsItem.js: Pages in Miller Columns**

- Go to Site Builder > Pages > See Miller Columns

https://github.com/liferay-echo/liferay-portal/assets/91208451/1dae63e8-8a30-4133-aafc-c55118157d3b

**Case 2: SelectLayoutTree.js: Item Selector Page Tree**

- Go to Site Builder > Navigation Menus > Create a Nav Menu
- Select New > Page > See modal

https://github.com/liferay-echo/liferay-portal/assets/91208451/12261f0c-e077-4102-9ddc-fd80cb076110

**Case 3: PreviewSelector.js :preview pages in Style Book**

- Go to Design > Style Books > create one
- Select Pages in the preview selector > Click on pages dropdown

https://github.com/liferay-echo/liferay-portal/assets/91208451/0243c64c-4c59-4835-9c77-de336bb29e0c

**Case 4: PagesTree.js: Product Menu Page Tree**

- Click on Page Tree in Product Menu

https://github.com/liferay-echo/liferay-portal/assets/91208451/85004738-ab76-4696-9124-b1aeebff763b

**Case 5: Layout header**

- Edit a Content page 

https://github.com/liferay-echo/liferay-portal/assets/91208451/3e0d5b16-558d-4093-bef1-34c5bf1fe495

**Case 6: Staging Page Tree**

- Go to Publishing > Staging > Enable Staging
- Click on new > See tree

https://github.com/liferay-echo/liferay-portal/assets/91208451/22ea7199-672a-4e28-85f9-fd68389cda7a

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
@DiegoHu97 I was just passing by here, and I saw a little thing (I haven't reviewed the pull)  🙂. In the cases of _Miller Columns_ and _Layout Header_, when the focus reaches the name of the page, the screen reader should read "[Name], Restricted Page". To do this we can add a `<span class="sr-only">Restricted Page</span>` inside the element that contains the name. The `aria-label` in the icon is not needed.

**Comment by DiegoHu97** [comment]
@victorg1991 Updated with the changes that @veroglez told me, thanks for the advice ❤️

**Comment by DiegoHu97** [comment]
ci:report:2488359876

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:report:2488580810

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:report:2488617526

**Comment by Tim-Cao** [comment]
ci:forward:force

**Pull request closed without merging**
