### PR TITLE
LPS-135942

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-135942

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @rodrigopaulino,

I made some tests and it is not working at all, I've tried to export a structure and import it and it is not working. My structure looks like:

Edit_Custom_Structure_-_Liferay

I think in this case the problem is with the numeric field, since I'm facing problems with the **numericInputMask**

```
 "numericInputMask":{
               "en_US":"{""append"": "", ""appendType"": ""prefix"", ""symbols"": {""decimalSymbol"": ""."", ""thousandsSeparator"": ""none""}}"
            },
```

Could you please take a look at it? Is it a known issue? if the answer is yes, then I think we can forward it in fix the issue later.

Regards,
Eudaldo.

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
@ealonso, thanks for checking the whole functionality.

Looks like we have some bugs in our API that are appearing while testing this new feature. Old things that weren't on our radar, because we didn't use that part of the code very much. But it was a good thing that you found it and I already fixed it, otherwise QA would have trouble testing it.
I also agree with you in regards to moving forward with this PR and we can treat other specific cases like this in parallel so we don't block this, as it is a dependency of another task. Please let me know if something else appears, so I can report it in the story.

Once again, thanks for your review.

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
