### PR TITLE
LPS-168652 Replace liferay-ui:icon-menu with clay:dropdown-menu in asset_actions.jsp

### PR DESCRIPTION
**Pull request by BarbaraCabrera**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:relevant

**Comment by BarbaraCabrera** [comment]
ci:reevaluate:1357401_3074

**Comment by BarbaraCabrera** [comment]
ci:reevaluate:1357401_3074

**Comment by victorg1991** [comment]
Resent here: https://github.com/liferay-echo/liferay-portal/pull/10373 just a minor change in a language key, the rest was wonderful! 👏  good job! 😍

**Pull request closed without merging**
