### PR TITLE
LPS-141460 Remove autogeneration of URLs in Web Content translations deleting previous friendly URLs when not introduced or left in blank

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This PR tries to accomplish the conclusions reached in [PTR-2609](https://issues.liferay.com/browse/PTR-2609?focusedCommentId=2548745&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2548745):

1. Friendly URL fields are not auto-generated automatically
2. Friendly URL fields can be left blank. Those translations will take the URL from the default language. No warning will be shown.
3. In the cases where a repeated URL is detected, the system will complete the URL to ensure its uniqueness. The current alert after publishing will be shown.
4. It will also fix the problem that re-publication generates a new URL again.
5. The upgrade step that auto-generates all existing translations without friendlyURL when installing Fix Pack 2 will be removed.

Please, let me know if further information or clarification is needed for your review.

Thanks in advance

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
https://github.com/liferay-echo/liferay-portal/pull/6443

**Pull request closed without merging**
