### PR TITLE
LPS-180716 Basic endpoint for creating an empty published content page

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-180716)

This PR creates a very very basic endpoint for creating an empty published content page. It will only take the localized name and friendly URL and create it

## Change summary:

* Adds post endpoint for creating the page

## Pre-requisites

* Enable FF for the epic
* Endpoint to be used: http://localhost:8080/o/headless-delivery/v1.0/sites/{siteId}/site-pages

## JSON Body bost basic scenario

{
	"title": "layout1"
}

## Scenario 2

{
	"friendlyUrlPath": "/layout2",
	"title": "layout2"
}

## Scenario 3

{
	"title": "layout3",
	"title_i18n": {
        "en-US": "layout3",
        "es-ES": "layout3_ES"
    }
}

## Scenario 4

{
	"friendlyUrlPath": "/layout4",
	"friendlyUrlPath_i18n": {
		"en-US": "/layout4",
		"en-ES": "/layout4es"
	},
	"title": "layout4",
	"title_i18n": {
				"en-US": "layout4",
				"es-ES": "layout4_ES"
			}
}

## TODO

* Exception mappers
* Integration tests

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
Looks good!

Two things we can keep in mind for following PRs:

1) 
When the input is:
```

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Thanks a lot for the help @ruben-pulido ❤️!

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward:force

**Pull request closed without merging**
