### PR TITLE
[TS] LPS-132521 Change AssetEntry.title to CLOB

### PR DESCRIPTION
**Pull request by vendeltoreki**
Resending https://github.com/liferay-echo/liferay-portal/pull/4619 :
* Added a new upgrade step: https://github.com/liferay-echo/liferay-portal/commit/e86cd6474dd6bb687fb24b0925ad50cd64aa7911
* Fixed semantic versioning: https://github.com/liferay-echo/liferay-portal/commit/2c62a72dac960be52a78cd31c6d7df15669339e9

cc: @achaparro

### CODE REVIEW

**Comment by achaparro** [comment]
looks good to me :-)

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
