### PR TITLE
LPD-20690 Replace lock icons of pages when a page is restricted

### PR DESCRIPTION
**Pull request by Mikellorza**
subtask: https://liferay.atlassian.net/browse/LPD-20690

Description
-----------
Replace icon from lock to password-policies as you can see in the [story](https://liferay.atlassian.net/browse/LPD-15807) :

> We should replace the lock icon of pages (LPD-6798: Identify the public pages from the restricted ones when seeing or editing them) for the permissions icon

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
