### PR TITLE
LPS-130606 Use the method to check if the layout is draft

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
:candle:

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reevaluate:1127401_4930

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @victorg1991, the render error happens on the Mapping panel in display page template. Could you have a look at?
**Step to reproduce**
1. Add a display page template for Web Content Article and Basic Web Content
2. Add a Heading fragment to display page template
3. Click the body of Heading fragment
4. Click the editable field of Heading

Expected Results:
The Mapping panel is rended well.

Actual Results;
The render error happens.
Actual

**Comment by victorg1991** [comment]
Thanks @Tim-Cao :)

Added a fix, let's see now

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The failure cases are unrelated to changes in PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/103828

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
