### PR TITLE
LPS-155947

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-155947

I wasn't sure if the ancestor sites' tags should be included too, but based on the description of [LPS-131461](https://issues.liferay.com/browse/LPS-131461) I thought that ancestor sites' tags should not be included. So I only included hte direct parent groups' tags in the event that the current scope group was a Layout.

Also, is it even possible to add tags to a layout-scoped group? If it's not, we could modify this code to look something like this:
```
if (group.isLayout()) {
	group = group.getParentGroup();
}

_groupIds = new long[] {group.getGroupId()};
```
It didn't seem like it was possible for a layout-scoped group to have its own tags, but I wasn't 100% sure so I didn't feel comfortable writing the code this way.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
Hi @mbowerman,
Thank's for the fix!
The logic that the tags selector should apply when groupIds tag attribute is not informed is to use PortalUtil.getCurrentAndAncestorSiteGroupIds(
					themeDisplay.getScopeGroupId()) like is doing [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-taglib/src/main/java/com/liferay/asset/taglib/servlet/taglib/AssetTagsSelectorTag.java#L171-L193).
IMHO the cause of this bug is that if groupIds tag attribute is not informed then the parameter groupIds is not added to the tags browser's portletURL. In this case, the AssetBrowserPortlet applies its logic taking as groupId the scopeGroupId.
Just by doing that the portletURL parameter exists always, the bug is solved. Please see https://github.com/liferay-echo/liferay-portal/pull/8505
I have preferred this way to fix the bug because we are only changing how the tags browser behaves when it is used from the tags selector, without impacting in AssetBrowserPortlet logic, so other tags browser possible uses where maybe is expected to use just the scopeGroupId will be preserve. 
Regards

**Pull request closed without merging**
