### PR TITLE
LPS-84862 implement test for new endpoint

### PR DESCRIPTION
**Pull request by devpedrotavares**
Hey @liferay-echo! I sent this pull liferay-forms#2025 to BPM and they approved it. However, the changes involve the Journal component. Could you please take a look at it?

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by devpedrotavares** [comment]
ci:reevaluate:1327401_7283

**Comment by liulukiwi** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/127412

**Pull request closed without merging**
