### PR TITLE
LPS-204393 Removes LPS-197692 Feature Flag

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ealonso, no failures are related to changes. Could we forward this one?

**Comment by ealonso** [comment]
@Tim-Cao we need to wait for https://github.com/brianchandotcom/liferay-portal/pull/145518, and we need to close the related story first. For that reason is in on hold.

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/14796

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
