### PR TITLE
LPS-142416 Remove FF for categories multi-selection in site navigation menu

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-142416

@Tim-Cao

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1317401_2232

**Comment by Tim-Cao** [comment]
Hi @lfbesada, could you fix the conflict issue?

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
