### PR TITLE
LPS-115312 Check if we are not in single experience mode (editing AB Test variant)

### PR DESCRIPTION
**Pull request by dgarciasarai**
cc: @ealonso @victorg1991

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
cc: @darquesdev

**Comment by victorg1991** [comment]
Thanks 👏

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
