### PR TITLE
LPS-146828 Rename

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @victorg1991, there are two regression issues. Cannot edit the inline text of fragment in Content Editing or user only with Update Page Content permission.

**Steps to reproduce**
1. Add a Heading fragment to a content page
2. Switch to the Content Editing
3. Double click the body of Heading

**Comment by victorg1991** [comment]
Thanks @Tim-Cao It should be fixed now

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
