### PR TITLE
LPS-145232 We need to check the uniqueId to obtain the journal title and description fields

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:reevaluate:1377401_1607

**Comment by ealonso** [comment]
ci:reevaluate:1377401_1607

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1377401_1607

**Comment by ealonso** [comment]
ci:reevaluate:1377401_1607

**Comment by ealonso** [comment]
ci:reevaluate:1377401_1607

**Comment by ealonso** [comment]
ci:reevaluate:1377401_1607

**Comment by ealonso** [comment]
ci:reevaluate:1377401_1607

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @victorg1991, would you mind checking compile error? Thanks

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, please don't run ci:forward until @victorg1991 checking the failure.

**Comment by victorg1991** [comment]
resent here: https://github.com/liferay-echo/liferay-portal/pull/7803

**Pull request closed without merging**
