### PR TITLE
[TS] LPS-125070

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi @liferay-echo ,

Previous PR: https://github.com/liferay-echo/liferay-portal/pull/3336
BChan's latest comment: https://github.com/brianchandotcom/liferay-portal/pull/97406#issuecomment-754768429

> @jonathanmccann @ericyanLr it shouldn't be in com.liferay.asset.kernel.messaging
> 
> The reason is that NotifiedAssetEntryThreadLocal just happens to be used in messaging in one instance.. but it may be used in other places. It's not in essence messaging...
> 
> Please resend. Thx.

**Thoughts**
From Brian's comment, it sounds reasonable that `NotifiedAssetEntryThreadLocal` can be used in other places other than messaging.

With that in mind, we decided to add the class to **com.liferay.asset.kernel.util** instead of **com.liferay.asset.kernel.messaging**.

We also found an existing class: `com.liferay.document.library.kernel.util.DLAppHelperThreadLocal`, which seems similar and also resides within a `util` package.

Hopefully that makes sense, feel free to refactor it as you see fit.

Please let us know if you have any questions.
Thanks!

/cc @jonathanmccann

### CODE REVIEW

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
