### PR TITLE
LPS-197679 Show missing labels in DPT's infopanel and formatting 

### PR DESCRIPTION
**Pull request by YurenaC**
Just formatting changes as sf was confused due a `</div>` estrangelly placed 

See https://github.com/liferay-echo/liferay-portal/pull/13908

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by YurenaC** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:stop

**Comment by sandrodw3** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/13936

**Pull request closed without merging**
