### PR TITLE
LPS-129058 Move JournalArticle content to DDMField tables

### PR DESCRIPTION
**Pull request by Preston-Crary**
Please send to @shuyangzhou if you're fine with these changes and we'll check it for performance regressions.

### CODE REVIEW

**Comment by Preston-Crary** [comment]
ci:test:relevant

**Comment by Preston-Crary** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @Preston-Crary,

The pull looks good to me, I want to make some changes using the new tables instead of parsing a XML field, since it can improve the performance in some cases, but I think we can do it later in another task.

Do the performance testing includes the upgrade process?, If not, IMHO, we should include it since we have clients with a lot of web content and it can affects them.

I was waiting for the test results to send it to Shuyang, but CI seems to be overloaded, so feel free to send it directly to him.

Regards,
Eudaldo.

**Comment by Preston-Crary** [comment]
> The pull looks good to me, I want to make some changes using the new tables instead of parsing a XML field, since it can improve the performance in some cases, but I think we can do it later in another task.
I agree, I made several compromises to keep the pull as small as I can and it's still pretty big.  More APIs need to happen to remove the XML usages.

> Do the performance testing includes the upgrade process?
No, only run time performance.  Upgrade performance is checked less frequently, runtime is checked daily.

> I was waiting for the test results to send it to Shuyang
I ran relevant and fixed all the failures before sending.  I'll go ahead and forward it.  Let me know if you have other questions, thanks!

**Comment by Preston-Crary** [comment]
Please see https://github.com/shuyangzhou/liferay-portal/pull/9929

**Pull request closed without merging**
