### PR TITLE
LPS-143422 Auto

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
Hi @ealonso, no regression issues found according to [ci:test:echo](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1638756147979&testrayRunIdA=1587762028&testrayRunIdB=1587909300)

**Comment by Tim-Cao** [comment]
The failure tasks are unrelated to this PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/110766

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
