### PR TITLE
[TS] LPP-LPP-48211 > LPS-178147 Category Filter does not work when Documents and Media widget is not on first page

### PR DESCRIPTION
**Pull request by ces-quanhuynh**
Hi team,
This PR is for fixing https://issues.liferay.com/browse/LPS-178147
The [original PR](https://github.com/ces-quanhuynh/liferay-portal/pull/24) has passed my review.
Please review and leave your comment.
Thanks,
Quan
cc @locpham97

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Hi @locpham97 @ces-quanhuynh 
It works like a charm 😍 
Thanks a lot for the fix!
Regards

**Comment by lfbesada** [comment]
ci:forward

**Comment by david-gutierrez-mesa** [comment]
ci:forward:force

**Pull request closed without merging**
