### PR TITLE
LPD-31549 and LPD-31906 Expose ERC and Scope in objects attachment fields

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-31549
https://liferay.atlassian.net/browse/LPD-31906

Reviewed by the Headless Team [here](https://github.com/liferay-headless/liferay-portal/pull/2140#pullrequestreview-2230437478) and [here](https://github.com/liferay-headless/liferay-portal/pull/2142#issuecomment-2278177127)

cc: @4lejandrito

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:report:58754280

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:report:59212227

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
