### PR TITLE
LPS-135172

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-135172

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
Rebased here: https://github.com/liferay-echo/liferay-portal/pull/5167 let's see if the mighty ci works this time

**Pull request closed without merging**
