### PR TITLE
LPS-123847 - Support having multiple Collection selectors in a single page

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @jkappler @veroglez

Adds more functionality on top of brianchandotcom#96029

LPS-123388 - Render a select element
LPS-123847 - Support having multiple Collection selectors in a single page

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/3016

**Comment by ruben-pulido** [comment]
Rebased here: https://github.com/liferay-echo/liferay-portal/pull/3046

**Pull request closed without merging**
