### PR TITLE
LPS-136015 Revert commit LPS-135017 and implement a new solution

### PR DESCRIPTION
**Pull request by lfbesada**
The solution implemented for LPS-135017 introduced the bug described in LPS-136015. This PR reverses the given solution and implements a new one solution for LPS-135017.

Related issues:

https://issues.liferay.com/browse/LPS-135017
https://issues.liferay.com/browse/LPS-136015

cc: @bakayattila

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by david-gutierrez-mesa** [comment]
ci:stop

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
ci:stop

**Comment by david-gutierrez-mesa** [comment]
ci:stop

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Send directly to BChan since failing test are not related.

See: https://github.com/brianchandotcom/liferay-portal/pull/104676

**Pull request closed without merging**
