### PR TITLE
LPS-130915 Add Distinct to the selection of assets to ensure multuple…

### PR DESCRIPTION
**Pull request by SamZiemer**
https://issues.liferay.com/browse/LPS-130915

Added distinct to the query to ensure we only have 1 AssetDisplayPageEntry per asset.

/cc @achaparro, @jkappler

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
thanks @SamZiemer!

**Pull request closed without merging**
