### PR TITLE
LPS-167337 Receive KeyboardDND feedback

### PR DESCRIPTION
**Pull request by p2kmgcl**
This PR only includes adding items with DND (not moving them). In order to test, commits from this other PR are needed: https://github.com/liferay-echo/liferay-portal/pull/10128

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
Hey @p2kmgcl, this looks awesome 😍 great job! ❤️

I found some things that I think we should take a look at:
- Sometimes, when adding a field with keyboard, it's added two times. I think I'm being able to reproduce it consistently, we can take a look tomorrow
- I also found out we are not scrolling when navigating with keyboard. It's a bit weird when you move to a target that is not visible in the screen and it doesn't scroll. As we currently don't have refs or another way to identify field elements, I don't know how easy would be to implement it (the same we discussed about the drag preview). What do you think?
- Improvement for the future: if not too difficult, it would be cool to add also commands to move to end and start of the page, as you suggested in the page editor, I think it was a good idea 😄

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Pull request closed without merging**
