### PR TITLE
LPS-133735 Prevent the Page Tree and the Site Builder's Pages menu from being open at the same time

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,
[LPS-133735](https://issues.liferay.com/browse/LPS-133735),

My changes:
- The Page-Tree button is disabled while we are viewing the GroupPagesPortlet
- I kept the Page Administration link and I close the Page-tree with an onClick on the link
- I also check in layout-admin wether the Page-tree is open when it's loaded, if yes I close it from there.
This was needed to handle scenarios where the user is navigating back

Last PR: https://github.com/liferay-echo/liferay-portal/pull/5071

Please review my changes,

/cc @victorg1991

### CODE REVIEW

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @NemethNorbert,

Could you please take a look to the SF errors?

Regards,
Eudaldo

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
Hey @NemethNorbert The pr works fine, I find it a bit of overcomplicated, having to add that code to the millers columns 🤔 

What do you think about:  

- Adding a check [here](https://github.com/liferay/liferay-portal/blob/c9557cfde75e4b19b36d72032b3ff270a22721a1/modules/apps/product-navigation/product-navigation-site-administration/src/main/resources/META-INF/resources/sites/site_administration_body.jsp#L97-L105) and disable (adding the disable class for example) the button if we are in the miller columns.
- Instead of checking the productMenuState [here](https://github.com/liferay/liferay-portal/blob/0c62fe5b6faac28903fb99c4ee1b513a2a966930/modules/apps/product-navigation/product-navigation-product-menu-web/src/main/resources/META-INF/resources/portlet/view.jsp#L52-L62) check if we are in the miller columns and render the product menu always.

For checking that the user is in the miller columns we have to take into account that the `p_p_id` is `com_liferay_layout_admin_web_portlet_GroupPagesPortlet` and that we dont have a `mvcPath` nor a `mvcRenderCommand` param.

This way we can reduce all the code to two ifs, let me know if this makes sense to you :)

Thanks!

**Comment by NemethNorbert** [comment]
https://github.com/liferay-echo/liferay-portal/pull/5239

**Pull request closed without merging**
