### PR TITLE
LPS-149984 Create Feature Flag LPS-150277

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @ealonso and @p2kmgcl, the General tab of fragment is missing. Would you mind having a look at?
Thanks
image

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/7862

**Pull request closed without merging**
