### PR TITLE
LPS-130642 Revert changes since it should not be needed

### PR DESCRIPTION
**Pull request by ealonso**
Hey @SamZiemer,

Could you please take a look to my changes? I made a more generic fix, since if tags are no case sensitive we should take into account in all search methods.

If everything is fine for you I'm going to forward it.

Regards,
Eudaldo.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by SamZiemer** [comment]
Hi @ealonso, any update on this?

**Comment by ealonso** [comment]
Hey @SamZiemer,

Are you creating the tags on master? or are you creating the tags in older versions and upgrading to master?

Regards,
Eudaldo.

**Comment by ealonso** [comment]
Hey @SamZiemer,

Could you please take a look to the fix now? I've included the code in https://github.com/liferay-echo/liferay-portal/pull/4445, since it is related and I think this one fix the problem.

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/4448

**Pull request closed without merging**
