### PR TITLE
LPS-150394 Enable input fragments

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
Hi @sandrodw3, I'm afraid we need to refactor all Form Components cases for this PR. Let me know when you think it is time.

**Comment by sandrodw3** [comment]
Hey @Tim-Cao, I think it's just time for it, as we are removing the FF soon. I just rebased the PR with today's master and solved conflicts. Could you also take a look at the commits that remove the FF from poshi just to confirm they are ok? Thanks! 🥰

**Comment by Tim-Cao** [comment]
Hi @sandrodw3, this task is separately assigned to me, oziel and fiona.
My part is done here. https://github.com/liferay-echo/liferay-portal/pull/9619
You could cherry pick the Poshi commits except the last one for ci test.

**Comment by ozysouza** [comment]
Hi @sandrodw3! Could you please cherry-pick my commits on https://github.com/sandrodw3/liferay-portal/pull/496?
Thanks!

**Pull request closed without merging**
