### PR TITLE
LPS-172654: Changing display template for webcontent destroys translated content

### PR DESCRIPTION
**Pull request by matthiasblaesing**
The code in
    
com.liferay.dynamic.data.mapping.form.values.factory.internal.DDMFormValuesFactoryImpl
    
expects the parameter availableLocales to be present and represent the languages it needs to cover.
    
availableLocales is set for the normal submit process via _JournalPortlet#handleDDMFormValid in JournalPortlet.es.js. As that    code path is not executed for the template change, this needs to be handled in the template change submission code.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by matthiasblaesing** [comment]
The referenced issue holds steps to reproduce and a git bisect for the begin of the problem.

**Review by lfbesada — APPROVED** [review]
Hi @matthiasblaesing 
Thanks for the fix! ❤️ 
LGTM!
Regards

**Comment by lfbesada** [comment]
ci:forward

**Comment by matthiasblaesing** [comment]
@lfbesada thank you for the review. I still try to really grasp the automation running behind the liferay repositories, but looking at the other PRs, that were recently merged, the `ci:forward` request was followed by the bot shortly afterwards. It seems this did not happen here. Could you have another look?

**Comment by lfbesada** [comment]
ci:forward

**Comment by matthiasblaesing** [comment]
@lfbesada thank you for taking care of this.

**Pull request closed without merging**
