### PR TITLE
LPS-114178 Adapt test cases

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@ruben-pulido, @ealonso

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/757

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
