### PR TITLE
LPS-138163 Increase space between show more and clear buttons

### PR DESCRIPTION
**Pull request by p2kmgcl**
Just need review of this commit https://github.com/liferay-echo/liferay-portal/pull/5635/commits/53b7ee1883659053ab41da3e20465b973f7df002

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:stable

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1257401_5

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Rebase see https://github.com/liferay-echo/liferay-portal/pull/5649

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
