### PR TITLE
LPS-132797 site-admin-web: buildLang

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-132797

Hi, @liferay-echo.

Could you please review this new site setting we need for the conclusion of one of our stories? Basically, this is to configure the Places API key that will be used in a new Forms' field that leverages Google's Places Autocomplete JavaScript API.

Thanks in advance.

Also, you don't need to forward this. This will still pass the Data Engine's review. Once this passes your review, we'll take it from there.

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @rodrigopaulino,
It is not needed that you put the configuration screen on Site module, it should be on dynamic data form module.
Could you please change it? So, it is not necessary send it to us, if you move your code to your modules.
Regards,
Eudaldo

**Comment by rodrigopaulino** [comment]
I see. Since this is a site setting contributor, it can be anywhere. Makes sense. Thanks for pointing that out.
Also, thank you very much for reviewing this so quickly.

Kind regards.

**Comment by rodrigopaulino** [comment]
ci:stop

**Comment by rodrigopaulino** [comment]
ci:close

**Pull request closed without merging**
