### PR TITLE
LPS-141906 | master

### PR DESCRIPTION
**Pull request by ozysouza**
https://issues.liferay.com/browse/LPS-141906

@david-gutierrez-mesa 
@Tim-Cao

### CODE REVIEW

**Comment by ozysouza** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
The failure is a new issue might be a regression bug. Let me check with devs.
https://github.com/liferay/liferay-portal/compare/e7dee72a637379b138882b802e1dcc5fe311e3c1...214ee2e68be9acbc25df7a28c19de82a919f021c

**Comment by Tim-Cao** [comment]
After talk with @lfbesada, this behavior is hidden by FF file.

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
