### PR TITLE
LPS-155177 Validate typeOptions in fragment contributors and when importing fragments

### PR DESCRIPTION
**Pull request by jkappler**
https://issues.liferay.com/browse/LPS-155177

This PR adds JSON Schema validation for typeOptions when publishing fragments, importing them, and for contributed fragments.

To test this PR, we have to enable the FF first:

feature.flag.LPS-152938=true for the feature flag

Steps to test:

- Create a new fragment collection
- Add a new form fragment, and in configuration select some field types
- Publish the fragment
- Export the fragment, and then delete it
- Expand the zip file and locate fragment.json
- Check that typeOptions contains fieldTypes with the ones that were selected and change fieldTypes -> fieldTypes1 or something else
- Generate the zip file
- Import it in the UI

The interface will mention that there was an issue and the fragment will be imported as draft

Screenshot 2022-06-06 at 11 07 16

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
