### PR TITLE
LPD-32101 Move com.liferay.layout.internal.upgrade.v1_0_0.LayoutPermissionsUpgradeProcess to Core upgrades

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-32101

@achaparro I'm sending this PR for your review to see if the approach is correct, even though it doesn't pass the source formatter due to the use of ServiceUtil in an Upgrade class.

With the last commit, I have removed the use of GroupLocalServiceUtil, but removing the use of ResourceLocalServiceUtil will be much more complicated as it would require replicating all the internal logic of the service.

The test I added works correctly after moving the Upgrade and with the DB we have to test I think it will also work because the query does not return any results so it will never be executed.

But I don't see any use of services in the core upgrades, so I suspect that it's not just a matter of making an exception to the SF rule and that I need to replicate all this logic. Since this will not be trivial, before trying to make these changes, I wanted to ask for your first assessment of the approach and whether it will solve the query performance problem that originated this ticket.

Thanks in advance!

I'm leaving this PR on hold.

cc: @ealonso

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by achaparro** [comment]
you are right @lfbesada, we won't be able to use the service in these classes.

I will analyze if there is a way to achieve it somehow. If not, we will need to work on the index performance.

Thanks.

**Comment by lfbesada** [comment]
@achaparro Thanks for the feedback!

**Comment by achaparro** [comment]
Hi @lfbesada,

Moved it to Core in this PR:
https://github.com/brianchandotcom/liferay-portal/pull/156865

Cheers!

**Pull request closed without merging**
