### PR TITLE
LPS-110723, LPS-115224 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-110723
https://issues.liferay.com/browse/LPS-115224

This is only for master.

@pavel-savinov
@sandrodw3

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/1917

**Pull request closed without merging**
