### PR TITLE
LPS-136538

### PR DESCRIPTION
**Pull request by wanderlast**
https://issues.liferay.com/browse/LPS-136538

From @Odrakir1:

> The issue was solved calling another normalizer function instead of the one that wouldn't remove the friendly URL's accents.

Essentially, a user reported that friendlyURLs keep any accents that may be in the site's name. This apparently causes issues related to SEO.

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
This was discussed in [PTR-1974](https://issues.liferay.com/browse/PTR-1974). Due to there can be several ways of transliterating, being removing the diacritic accents one of them, the solution might be more complex than it might seem at first sight.

There is also a Feature Request about this in [LPS-78008](https://issues.liferay.com/browse/LPS-78008).

I am afraid that [LPS-136538](https://issues.liferay.com/browse/LPS-136538) should be marked as Won't Fix for now.

**Comment by lfbesada** [comment]
Hi @wanderlast @Odrakir1 

Thanks for the PR!

As @dacousalr said in his previous comment: 

https://github.com/liferay-echo/liferay-portal/pull/5524#issuecomment-900068345

I'm afraid this bug should be marked as Won't Fix.

Regards

**Pull request closed without merging**
