### PR TITLE
[TS] LPS-177127 Consistent search behavior should be present

### PR DESCRIPTION
**Pull request by ces-huynguyen**
Please review this ticket
cc: @tototrinh
Closed here https://github.com/liferay-core-infra/liferay-portal/pull/3742

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by yuhai** [comment]
Hi @ealonso, 

Sorry, the pr sent to the wrong team. Do you know which team is suitable to review it?

Thanks,
Hai

**Comment by ealonso** [comment]
Hey @yuhai,

One week ago it should be User & System Management, but today I don't know. We are trying to investigate which team should review it, once we know it, we are going to let you know.

Regards,
Eudaldo

**Comment by yuhai** [comment]
Hi @ealonso,

Thanks very much.

Regards,
Hai

**Comment by ces-huynguyen** [comment]
Hey @ealonso, 

Why is it not User & System Management today but it was a week ago? 

Thanks,
Huy

**Comment by ealonso** [comment]
Hey @ces-huynguyen,

Because the components were moved to other teams

**Comment by stian-sigvartsen** [comment]
@ealonso that's right. We had hoped to determine if this now falls under our components ownership but I think the decision cannot be made until tomorrow earliest unfortunately. In the meantime I have been gaining familiarity with code to help progress things faster.

cc @ces-huynguyen

**Comment by stian-sigvartsen** [comment]
Hi @ces-huynguyen . We discussed this more at our daily standup.
Please can you send this PR to the `liferay-appsec` user and we will review it (and coordinate the review if other teams also if necessary).

Thanks! :)

cc @ealonso

**Comment by stian-sigvartsen** [comment]
Hi @ces-huynguyen . Following on from the above we analyzed the behaviour which was fixed in LPS-78443 and found that it is simply caused by role descriptions being included in the search. So we would prefer to fix that within `RoleFinderImpl` under a future ticket instead of patching the search results in a secondary filtering.

So to fix the current ticket we will just remove that fix for now. Please see liferay-appsec/liferay-portal/pull/1034

**Comment by ces-huynguyen** [comment]
Thanks for your infor @stian-sigvartsen

**Pull request closed without merging**
