### PR TITLE
LPS-130552-III | master

### PR DESCRIPTION
**Pull request by ozysouza**
Splitted from [#6969](https://github.com/liferay-echo/liferay-portal/pull/6969)

https://issues.liferay.com/browse/LPS-130552
@Tim-Cao 
@david-gutierrez-mesa

### CODE REVIEW

**Comment by ozysouza** [comment]
ci:test:sf

**Comment by ozysouza** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ozysouza, see changes https://github.com/liferay-echo/liferay-portal/compare/8d3025f51e58fb8dccabd6b9e0e105221765f7ba...ed180233106096053cb26b66921677e806e2523a

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
