### PR TITLE
LPS-165485 - Selecting an option from the "Page Design" Select should keep focus on the button that opens the dropdown.

### PR DESCRIPTION
**Pull request by ethib137**
Motivation
=======
Selecting an option from the "Page Design" Select causes the focus to move the end of the page instead of staying.

https://issues.liferay.com/browse/LPS-165485

Proposed Solution
========
This dropdown's active state was being controlled by the page editor, but it doesn't need to be. The ClayDropdown can control it's own active state, and when it does it properly handles which element should be focused when an item is clicked.

Steps to Verify
========
1. Navigate to the page editor.
2. Press tab until the "Page Design" select is focused. 
3. Press 'Enter' or 'Space' to open the select.
4. Use the down arrow keys to move to an item.
5. Press 'Enter' to select an item.

Expected Result:
Focus stays on the Button that opens the select.

Actual Result:
Focus moves to the bottom of the page.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/124602

**Pull request closed without merging**
