### PR TITLE
[TECHNICAL-SUPPORT] LPS-120519 Join queries directly to JournalArticleLocalization

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @liferay-echo ,

Since a unique index already exists for the columns of the `group by` clause:
```
create unique index IX_97DC9F36 on JournalArticleLocalization (companyId, articlePK, title[$COLUMN_LENGTH:400$], languageId[$COLUMN_LENGTH:75$], ctCollectionId);
```
I've made an attempt to remove the `group by` and the sub-queries altogether, and join directly to `JournalArticleLocalization`.
This made the queries significantly faster, even when there are many (400000) JournalArticles in the DB.

Please review my changes.

Thanks,
Vendel

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Hi @vendeltoreki, thanks for the optimization! We'll wait after the release to send it

**Comment by jkappler** [comment]
Also @vendeltoreki, the code was added in LPS-73630. These were the tests I was referring to before, mostly to check that the issue hasn't regressed

Thanks!

**Comment by vendeltoreki** [comment]
Hi @jkappler ,

Thanks for the review! I have other tasks this week, so I'll try to add some tests next week.

**Comment by jkappler** [comment]
Hi @vendeltoreki, will close the PR and assign the ticket back to you.

Thanks again

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
