### PR TITLE
LPS-156889 The custom CSS defined in site template is not applied to the created site

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-156889 The earlier call to updateLayout causes the earlier values set on importedLayout to be lost
- LPS-156889 Update layout after importing the theme
- LPS-156889 Instead of updating the whole type settings, just update javascript if the original layout has it
- LPS-156889 No need to persist since it's being done after the method is called

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
