### PR TITLE
LPS-197156 Add Copy with permissions for Master Pages

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

Add options for copy with and without permissions in the dropdown for Master Pages and Display Pages

[Link to ticket](https://liferay.atlassian.net/browse/LPS-197156)
[Link to ticket](https://liferay.atlassian.net/browse/LPS-196851)

## Test scenario 1 
1. Create a new Master Page.
2. Change the permissions for this Master Page.
3. Make a Copy with permissions and a copy without them. Check that they are copied or not depending on the case.

https://github.com/liferay-echo/liferay-portal/assets/93203423/932986a5-82f0-45a3-a229-b591ab885002

## Test scenario 1 
1. Create a new Display Page.
2. Change the permissions for this Display Page.
3. Make a Copy with permissions and a copy without them. Check that they are copied or not depending on the case.

https://github.com/liferay-echo/liferay-portal/assets/93203423/c0e96ef8-b14b-44cd-9990-d0065ab9c490

### CODE REVIEW

**Comment by BarbaraCabrera** [comment]
ci:test:stable

**Comment by BarbaraCabrera** [comment]
ci:forward

**Comment by BarbaraCabrera** [comment]
ci:forward

**Comment by BarbaraCabrera** [comment]
ci:test:stable

**Comment by alessandromalves** [comment]
Hey @BarbaraCabrera, would you mind checking this compile issue? 
[apps:layout:layout-page-template-test:compileTestIntegrationJava](https://testray.liferay.com/home/-/testray/case_results/2437538417)

```
FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:layout:layout-page-template-test:compileTestIntegrationJava'.
     [exec] > Compilation failed; see the compiler error output for details.
     [exec] 
     [exec] * Try:
     [exec] > Run with --info or --debug option to get more log output.
     [exec] > Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:layout:layout-page-template-test:compileTestIntegrationJava'.
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:145)
     [exec] 	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:143)
     [exec] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:131)
     [exec] 	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
     [exec] 	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
```

**Comment by BarbaraCabrera** [comment]
ci:test:stable

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:stable

**Comment by alessandromalves** [comment]
ci:test:relevant

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by BarbaraCabrera** [comment]
elmo-fire

**Comment by alessandromalves** [comment]
ci:forward

**Comment by alessandromalves** [comment]
The failures are not related to this PR. See https://github.com/brianchandotcom/liferay-portal/pull/142052

**Comment by alessandromalves** [comment]
ci:close

**Pull request closed without merging**
