### PR TITLE
LPS-173665 New configuration for managing asset.categories.search.hierarchical property at instance level and using the UI

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-173665

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Thanks @lfbesada  ❤️ 

Also, I don't think tests will finish because of the change in portal kernel and portal impl. We might need to send directly to BChan

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
Hey @lfbesada, a unique failure has been found, related to 
[com.liferay.headless.delivery.resource.v1_0.test.MessageBoardThreadResourceTest](https://testray.liferay.com/home/-/testray/case_results/2180428445). Could you take a look at it?


[Full log here](https://testray.liferay.com/reports/production/logs/2023-01/test-1-26/test-portal-acceptance-pullrequest(master)/7300/modules-integration-mysql57-jdk8/2/1/jenkins-console.txt.gz?authuser=0)
```com.liferay.headless.delivery.resource.v1_0.test.MessageBoardThreadResourceTest > testGetMessageBoardSectionMessageBoardThreadsPageWithSortInteger FAILED
     [exec]     java.lang.NoSuchMethodException
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.BaseMessageBoardThreadResourceTestCase$BeanTestUtil.setProperty(BaseMessageBoardThreadResourceTestCase.java:3527)
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.BaseMessageBoardThreadResourceTestCase.lambda$testGetMessageBoardSectionMessageBoardThreadsPageWithSortInteger$2(BaseMessageBoardThreadResourceTestCase.java:483)
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.BaseMessageBoardThreadResourceTestCase.testGetMessageBoardSectionMessageBoardThreadsPageWithSort(BaseMessageBoardThreadResourceTestCase.java:563)
     [exec]     	at com.liferay.headless.delivery.resource.v1_0.test.BaseMessageBoardThreadResourceTestCase.testGetMessageBoardSectionMessageBoardThreadsPageWithSortInteger(BaseMessageBoardThreadResourceTestCase.java:480)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]     	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     	at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]     	at com.liferay.arquillian.extension.junit.bridge.server.TestExecutorRunnable$3.evaluate(TestExecutorRunnable.java:353)
     [exec]     	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
     [exec]     	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)

**Comment by lfbesada** [comment]
Hi @alessandromalves 
Thanks for taking a look at the test results.
The failed test is not related to the changes, it is failing at the current master branch. 
Regards

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/129438

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
