### PR TITLE
LPS-193727 Allow order showed items by different fields

### PR DESCRIPTION
**Pull request by jkappler**
Motivation
=======
Currently we allow users to create folders to organice their DPTs so looks natural allow then to order them by different fields as well the DPTs.

Proposed Solution
========
Different comparators are implemented an the order options are shown in the management toolbar. 

Steps to Verify
========
1. Go to Design > Page Templates > Display Page Templates Tab.
2. Create several new Folders
3. Create several new Display Page Template.
4. Order by (asc/desc) the three different fields available: name, creation date and modified date.

Commits
========
- LPS-193727 Create LayoutPageTemplateCollectionModifiedDateComparator
- LPS-193763 Create LayoutPageTemplateCollectionLayoutPageTemplateEntryModifiedDateComparator
- LPS-193763 Add LayoutPageTemplateCollectionLayoutPageTemplateEntryModifiedDateComparator to vailable orderBy options
- LPS-193763 Add new fields in response to be able to orderby
- LPS-193727 Add modified date option to orderBy
- LPS-193727 Add workaround to make orderBy dates work

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
