### PR TITLE
LPS-138584 build.gradle

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Tim-Cao** [comment]
Hi @ealonso, The Collection Provider is missing in Asset Publisher configuration, Could you have a look at?
image

**Comment by ealonso** [comment]
Hey @Tim-Cao,

I did it on purpose, now it is like the content pages, when you are going to select a collection you can also select collection providers. 

I think we need update the poshi tests.

Thanks!!

**Comment by Tim-Cao** [comment]
ci:test:bundle

**Comment by Tim-Cao** [comment]
Hi @ealonso, cannot select collection provider, Could you have a look at?
截屏2021-09-04 下午11 50 00

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/5726

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
