### PR TITLE
LPS-205028 Fix error message on form container when guest user tries to add object entry beyond their limit

### PR DESCRIPTION
**Pull request by thallescezar**
Motivation
=======
Problem this work solves including link to LPS ticket and any relevant context

Story LPS-192848 (https://liferay.atlassian.net/browse/LPS-192848) adds a timely limit of object entries that a guest user can add. To cover all the scenarios I need to treat object entry creation through a form container. To that, I've created a new exception that extends InfoFormValidationException and handled this exception on ObjectEntryInfoItemExceptionRequestHandler.

Proposed Solution
========
- Create a new ExceedsMaxEntries, an exception that extends from InfoFormValidationException.
- Update ObjectEntryInfoItemExceptionRequestHandler to check on ExceedsMaxEntries and handle it to show the right behavior on a form container in case of a guest user can't add anymore entries.

Steps to Verify
========

Feature Flag: LPS-192957

1. Go to Control Panel -> Objects, then create an ObjectDefinition
2. Add a Field to this ObjectDefinition and publish it.
3. Go to Control Panel -> Roles, select Guest, go to Define Permissions tab, search for the name of your object definition and select it. Then you need to mark all the checkboxes to grant access to guest user.
4. Go to Control Panel -> Instance Settings -> Object
5. Set "Maximum Number of Guest Object Entries per Object Definition" to 1. Click on update.
6. Now, go to Site Builder -> Pages and add a new Blank Page
7. Search for a form container, add it to your page and then choose your object definition to be related to form container. Publish the page.
8. Make logoff on portal.
9. As a guest user, select the page that you created on step 4.
10. Add a new object entry, then add a new one. You should see the correct error message in a toast.

References to existing code
========
I used as example the already mentioned ObjectEntryInfoItemExceptionRequestHandler and also InvalidCaptcha, that serves me as an example to create ExceedsMaxEntries.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
Hi @thallescezar, I'm trying to reproduce the issue fff775e599f3 but I'm not able to. As a guest user I can still create many objects and no exception is thrown, even when I change the configuration. I have followed the steps that you provided, but maybe I'm missing something? I'm testing with Oracle. 

Code looks great, just want to test it properly

Objects

**Comment by jkappler** [comment]
@thallescezar, maybe I'm missing a FF?

**Comment by thallescezar** [comment]
Hey @jkappler! Sorry about that. I totally forgot the FF. Here it is:

feature.flag.LPS-192957=true

I'm going to add that to the description.

**Comment by jkappler** [comment]
Works great @thallescezar! I'll forward it. Thanks!

**Comment by jkappler** [comment]
ci:forward

**Comment by thallescezar** [comment]
@jkappler This PR was missing the baseline. Just added the commit.

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward:force

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
