### PR TITLE
LPS-121259 Remove unused useControlledState

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
Rebase then resend. See https://github.com/liferay-echo/liferay-portal/pull/2474

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
