### PR TITLE
LPS-188726 Send all ids in same param

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @sandrodw3, the bulk move action always move all web contents no matter how many web contents selected.
Step to reproduce

1. Add three web contents
2. Add a web content folder
3. Select 1 web content
4. Click the bulk move icon

Expected results:
Only one web content be shown on Move Web Content page.

Actual Results:
All web contents are shown on Move Web Content page.

**Comment by sandrodw3** [comment]
Thanks @Tim-Cao! Fixed, trying to forward again 🚀

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by alessandromalves** [comment]
The failures are not related to this PR. See https://github.com/brianchandotcom/liferay-portal/pull/137096

**Pull request closed without merging**
