### PR TITLE
[TS] LPS-117865

### PR DESCRIPTION
**Pull request by ChrisKian**
Resent from https://github.com/ericyanLr/liferay-portal/pull/200

https://issues.liferay.com/browse/LPS-117865

Eric believed this PR should go to the WEM team since it only affects journal.

Followed guidence on PTR-1863. Please let me know if you have any questions, thanks!

CC @holatuwol, @ericyanLr, and @dacousalr

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
