### PR TITLE
[TS] LPS-168564 Sort the related assets list alphabetically

### PR DESCRIPTION
**Pull request by danielmijarra**
Hello @liferay-echo,
this pull fixes LPS-168564.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by danielmijarra** [comment]
ci:test:sf

**Comment by danielmijarra** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @danielmijarra,

A couple of things, first of all Could you please update the jira ticket? https://issues.liferay.com/browse/LPS-168564, it's still in open, and it should be verified and then move to In Review status, put the link to the pr and assign to the correct team.

After that, Could you please follow the pr template? [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md)

Regards,
Eudaldo

**Comment by jkappler** [comment]
@danielmijarra please see https://github.com/liferay-echo/liferay-portal/pull/10410

For the next time, please follow the etiquette here: https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md

And also the workflow for tickets as @ealonso mentioned.

Thanks

**Pull request closed without merging**
