### PR TITLE
LPS-125445 Send all the translated languages for an article. Otherwise, although the content was being sent correctly, all languages were being deleted because the availableLocales parameter was wrong

### PR DESCRIPTION
**Pull request by ambrinchaudhary**

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
@liferay-echo are the poshi failures related to this change?

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Resend here: https://github.com/liferay-echo/liferay-portal/pull/3435

**Pull request closed without merging**
