### PR TITLE
LPS-128090 Use Liferay.Language.direction instead of built languageDirection

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Review by victorg1991 — COMMENTED** [review]
I think we also need to remove it from the typing file: https://github.com/liferay/liferay-portal/blob/91b6a5f20154e5aca2c2eddfcad4b47babc8e9ea/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/types/config.d.ts#L133-L135 

Apart from that this is good to go :D 👏

**Comment by sandrodw3** [comment]
Done @victorg1991! Thanks 🙂

**Comment by victorg1991** [comment]
Perfect!

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
