### PR TITLE
LPS-198689 - Apply --control-menu-container-height css variable to echo components.

### PR DESCRIPTION
**Pull request by ethib137**
https://liferay.atlassian.net/browse/LPS-198694
https://liferay.atlassian.net/browse/LPS-198689
https://liferay.atlassian.net/browse/LPS-198687
https://liferay.atlassian.net/browse/LPS-198685
https://liferay.atlassian.net/browse/LPS-198683
https://liferay.atlassian.net/browse/LPS-198682

This PR is consistently applying the use of the --control-menu-container-height css variable to handle the offset for elements that have a fixed position.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
Thank @ethib137  :)

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by ethib137** [comment]
ci:reevaluate:1267401_11447

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
