### PR TITLE
LPS-192105

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:stable

**Comment by alessandromalves** [comment]
Hey @ealonso, there are some integration test files with initializationError. Would you mind taking a look at them please?

[com.liferay.journal.exportimport.data.handler.test.JournalExportImportTest](https://testray.liferay.com/home/-/testray/case_results/2397663995)

```com.liferay.journal.exportimport.data.handler.test.JournalExportImportTest > initializationError FAILED
     [exec]     java.lang.NoClassDefFoundError: com/liferay/asset/link/model/AssetLink
     [exec]         at java.lang.Class.getDeclaredMethods0(Native Method)
     [exec]         at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
     [exec]         at java.lang.Class.getDeclaredMethods(Class.java:1975)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.junit.Arquillian._scanTestMethods(Arquillian.java:152)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.junit.Arquillian.<init>(Arquillian.java:37)
     [exec]         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     [exec]         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     [exec]         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
```

[com.liferay.exportimport.test.PortletPreferencesExportImportTest](https://testray.liferay.com/home/-/testray/case_results/2397663453)
```
com.liferay.exportimport.test.PortletPreferencesExportImportTest > initializationError FAILED
     [exec]     java.lang.NoClassDefFoundError: com/liferay/asset/link/model/AssetLink
     [exec]         at java.lang.Class.getDeclaredMethods0(Native Method)
     [exec]         at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
     [exec]         at java.lang.Class.getDeclaredMethods(Class.java:1975)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.junit.Arquillian._scanTestMethods(Arquillian.java:152)
     [exec]         at com.liferay.arquillian.extension.junit.bridge.junit.Arquillian.<init>(Arquillian.java:37)
```

[com.liferay.layout.set.prototype.exportimport.test.LayoutSetPrototypeExportImportTest](https://testray.liferay.com/home/-/testray/case_results/2397664115)
```
```


[com.liferay.blogs.internal.exportimport.test.BlogsExportImportTest](https://testray.liferay.com/home/-/testray/case_results/2397662694)

```

```

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Pull request closed without merging**
