### PR TITLE
LPS-113882 Rename to section in tests until we make the change definitive

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:close
@sandrodw3 @p2kmgcl please review tests failures

**Pull request closed without merging**
