### PR TITLE
LPS-128603 Update itemSelector layout fields

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
cc @p2kmgcl 🐥

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @sandrodw3, there is a regression issue caused by your changes.
*Step to reproduce:*
1. Create a feature flag file named
com.liferay.fragment.renderer.menu.display.internal.configuration.FFFragmentRendererMenuDisplayConfiguration.config
with enabled="true"
2. Copy the file to bundle/osgi/configs
3. Add a new site
4. Add a public widget page
5. Add a private widget page
6. Add a master page
7. Add a Menu Display fragment above the Drop Zone
8. Assert the public page name is shown in Menu Display
9. Click the body of Menu Display
10. General tab
11. Click the plus icon of Source field
12. Click the Private Pages Hierarchy > Select This Level

*Expected Results:*
The private page name should be shown in Menu Display.

*Actual Results:*
The public page name is still shown in Menu Display.

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Pull request closed without merging**
