### PR TITLE
LPS-117123 Other upgrades have been backported so we have to move this to the lastest one for 7.2.x

### PR DESCRIPTION
**Pull request by achaparro**

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @liferay-echo,

Can you verify if the test is related? I don't think so but I just want to be sure.

Thanks.

cc/ @SamZiemer

**Comment by jkappler** [comment]
@achaparro, tests seem to be unrelated. Will review the PR first thing tomorrow

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by achaparro** [comment]
ci:close

**Comment by achaparro** [comment]
Hi @jkappler @ealonso,

We made a mistake with the upgrade processes order, we just need to:
- Create a dummy here:
registry.register("2.2.1", "2.2.2", new DummyUpgradeStep());
- Add the new one as micro upgrade process at the end.

@jkappler told me that you guys have another idea in mind. We will wait for it.

Thanks.

cc/ @SamZiemer

**Comment by achaparro** [comment]
Hey @ealonso, @jkappler,

Any updates on this fix? Do you want us to send the same pull request with the schema version fixed?

Thanks.

@SamZiemer

**Comment by ealonso** [comment]
Hey @jkappler,

Could you please take a look at it?

Sorry about it, I missed your comment, :(

**Comment by jkappler** [comment]
Hi @achaparro, as we talked, we are going to invert the logic for default <-> no page templates (working on it atm). Afterwards I'll create and upgrade process for it. That would invalidate the upgrade process that you sent to us. Still, the upgrade process would be for 7.2 right?

**Comment by jkappler** [comment]
after talking with @achaparro we'll go with another approach for master. So closing this pull

**Pull request closed without merging**
