### PR TITLE
LPS-121011 Adapt tests

### PR DESCRIPTION
**Pull request by dacousalr**

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
ci:stop

**Comment by dacousalr** [comment]
Continue in https://github.com/liferay-echo/liferay-portal/pull/2452

**Pull request closed without merging**
