### PR TITLE
LPS-186159 The feed is not able to configure after upgrading from 6.2

### PR DESCRIPTION
**Pull request by jkappler**
https://issues.liferay.com/browse/LPS-186159

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1407401_3071

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
