### PR TITLE
LPS-168306 Added title attribute to add and delete buttons.

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
FWD: https://github.com/fortunatomaldonado/liferay-portal/pull/61

Please let me know if there are any questions or comments about this.
Thank you!

> [LPS-168306](https://issues.liferay.com/browse/LPS-168306) Added title attribute to add and delete buttons.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
Hello @fortunatomaldonado! Thanks for your contribution!
Looking at your code, I think the user right now doesn't have much context of what he's doing if we only add the `Add` and `Delete` titles. Maybe, the most appropriate title would be something like `Add Condition` and `Remove Condition`. It would also be convenient to add the `aria-label` attribute to make sure any assistive technology reads it.

**Comment by fortunatomaldonado** [comment]
@veroglez, truly appreciate the feedback!
@SelenaAungst

**Comment by SelenaAungst** [comment]
Hi @veroglez,
I added these changes and made a new PR https://github.com/liferay-echo/liferay-portal/pull/10509.
Please let me know if anything else is needed for this, thank you!

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/10509

**Pull request closed without merging**
