### PR TITLE
LPS-153405 Poshi Automation for Bug | master

### PR DESCRIPTION
**Pull request by ozysouza**
https://issues.liferay.com/browse/LPS-153045

cc @david-gutierrez-mesa
cc @Tim-Cao

### CODE REVIEW

**Comment by Tim-Cao** [comment]
LGTM! @ozysouza

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ozysouza, could you correct the ticket number?

**Comment by ozysouza** [comment]
> Hi @ozysouza, could you correct the ticket number?

Hi @Tim-Cao, sorry about that I also created the wrong number in the branch. I'll rebase to the correct one.

**Comment by ozysouza** [comment]
Please see https://github.com/liferay-echo/liferay-portal/pull/8041

**Pull request closed without merging**
