### PR TITLE
LPS-136040

### PR DESCRIPTION
**Pull request by wanderlast**
From @Odrakir1:

> This issue was caused by a missing group id, in this case, the Global group id. The asset was being fetched by the Control Panel's group id only, adding the Global group id in the search solved the problem.
> 
> 
> 
> https://issues.liferay.com/browse/LPS-136040

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
Hey @wanderlast @Odrakir1, I think this is something that needs to be done from the outside when calling the taglib, the taglib has a groupIds parameter where you can set the groupIds that you want to search, there is no need to modify the taglib itself for this 

Specifically, from here: https://github.com/liferay/liferay-portal/blob/c76182ecaca677b3e9cd7f48e51507c0d5b20d50/modules/apps/account/account-admin-web/src/main/resources/META-INF/resources/account_entries_admin/account_entry/categorization.jsp#L36-L51

Apart from that, I've seen that there is a related issue: https://issues.liferay.com/browse/LPS-113946 which you may be careful not to bring back :) 

I hope this makes sense, after that you'll have to send this to the users team to review

Thanks!!

Feel free to reopen if you think it can't be donde from the outside for some reason :)

**Pull request closed without merging**
