### PR TITLE
LPS-160422 Move Add Container, Grid, Form and Collection Display fragments to backend

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-160422

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:forward

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. It can be manually forward if this last attempt doesn't work.

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @lfbesada, would you mind having a look at this integration test failure?
https://testray.liferay.com/home/-/testray/case_results/1952830933

**Comment by lfbesada** [comment]
Hi @Tim-Cao 

Thanks for looking in-depth at the tests failures ❤️ 

I have run several times this test in my local over this branch and it worked ok.

Seeing the history of this test it seems that was passed ok in this branch three times and one time it failed.

Failed test (the one you stand out): 
https://testray.liferay.com/home/-/testray/case_results/1952830933 

Success tests:
https://testray.liferay.com/home/-/testray/case_results/1952216265
https://testray.liferay.com/home/-/testray/case_results/1951779803
https://testray.liferay.com/home/-/testray/case_results/1951660679

IMHO the test failures on this PR are not related. 

What do you think about it?

Thanks!

**Comment by Tim-Cao** [comment]
Nice! Thanks @lfbesada

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/122026

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
