### PR TITLE
LPS-121916 Migrate v2 usages in site-navigation/site-navigation-admin-web

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

Creating, filtering or deleting Navigation Menus should work as
expected.

**Test plan**:
- Navigate to **Site Builder** > **Navigation Menus**
- Assert that you can create a new Navigation Menu using the management
toolbar
- Assert that you can filter various Navigation Menus
- Assert that you can delete one or more Navigation Menus

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
cc @ambrinchaudhary @markocikos @jonmak08

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
