### PR TITLE
LPS-133321 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-133321

This is only for master.

@p2kmgcl
@veroglez

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
see https://github.com/liferay-echo/liferay-portal/pull/4771

**Pull request closed without merging**
