### PR TITLE
LPS-130440 New language key for display page

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Hi @Tim-Cao, we made some changes to the display page selector, like this:

Screenshot 2021-04-26 at 12 54 40

So some tests might fail. If so, could you please help us out?

Thanks as always!

**Comment by jkappler** [comment]
@ealonso

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @jkappler, poshi side is already updated.
See https://github.com/liferay-echo/liferay-portal/pull/4362

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
