### PR TITLE
[TS] LPS-124704

### PR DESCRIPTION
**Pull request by wanderlast**
https://issues.liferay.com/browse/LPS-124704

AssetEntryId in the Asset Publisher must be escaped or else it's susceptible to reflected XSS.

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
