### PR TITLE
LPD-28401

### PR DESCRIPTION
**Pull request by lfbesada**
cc: @ealonso

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:report:23388841

**Comment by ealonso** [comment]
@lfbesada I think it is related com.liferay.friendly.url.web.internal.portlet.action.test.FriendlyURLSeparatorSaveCompanyConfigurationMVCActionCommandTest

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/15845

**Pull request closed without merging**
