### PR TITLE
[TS] LPS-204740 | Remove HTML escape to avoid JSON parse issues

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you review this fix?
https://liferay.atlassian.net/browse/LPS-204740
best,
Attila

------
The root cause of the issue is that the JSON characters are escaped and because of this, the JSON parse in the ddm_form.js can't parse the forwarded values.

**Steps to reproduce:**
1. Create a Structure and add a type Select from list with options: "2023, 2022, 2021" for example
2. Create a page
3. Add an asset publisher and filter by the structure and the field "select from list", click on the filter and select 2023
4. Click on save
5. Click on select for the filter by field

**Expected:** The popup shows the previously made selection
**Result:** Error in javascript the selection is not displayed.

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @bakayattila,

Could you please apply the same fix to collections? modules/apps/asset/asset-list-web/src/main/resources/META-INF/resources/asset_list/select_structure_field_item.jsp

**Comment by bakayattila** [comment]
> Hey @bakayattila,
> 
> Could you please apply the same fix to collections? modules/apps/asset/asset-list-web/src/main/resources/META-INF/resources/asset_list/select_structure_field_item.jsp

Yes, I will update the pull in a few sec. I will also quickly fix the SF issue.

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
Hi @ealonso,
Did the same for the asset lists as requested.

**Comment by bakayattila** [comment]
@ealonso,
SF command seems to keep putting back the html.escape with the following

> Task :apps:asset:asset-publisher-web:formatSource
C:\git\master\liferay-portal\modules\apps\asset\asset-publisher-web\src\main\resources\META-INF\resources\select_structure_field_item.jsp (SourceCheck:JSPXSSVulnerabilitiesCheck)

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Hey @bakayattila,

Source formatting still failing.

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
@ealonso,
Yes an SF rule was not okay with removing the HTML escape. Luckily it seems to be working with escapeJS instead of the regular escape.

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
