### PR TITLE
LPS-169811 Convert to Map, so we can remove recursion

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
Very nice @shuyangzhou @ealonso just 3d34292e90a591a026d1b7de966fc35fb78e4bd2 and 1e342d1d5c83d391e486fffe2e25c91352ec9b1b

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
Hey @ealonso, a regression found. Steps to repdroduce:
1. Go to Documents and Media >> Document Types tab
2.  Add a new document type with text area
3. Go to files tab and choose Multiple Files Upload option
4. Add least one document
5. On the document type area choose the Document Type you created

Expected result:
The text area appears there
Screenshot

Actual result:
The text area does not apppers there
Screenshot (1)

**Comment by ealonso** [comment]
Thanks you very much @alessandromalves

**Pull request closed without merging**
