### PR TITLE
[TS] LPS-129353 Regression: Fix invalid containerKey issue

### PR DESCRIPTION
**Pull request by vendeltoreki**
Dear @liferay-echo team,

Please review the fix for the regression [LPS-129353](https://issues.liferay.com/browse/LPS-129353) I caused by [LPS-128693](https://issues.liferay.com/browse/LPS-128693).

I added a condition to only try to parse the `containerKey` as `FragmentEntryLink` ID when the type of the container is actually a `FragmentEntryLink`.

cc: @jkappler , @jesseyeh-liferay

Thanks,
Vendel

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by vendeltoreki** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Thanks for the quick fix @vendeltoreki!

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
