### PR TITLE
LPS-149161 Don't allow ordering for relevance when having no keywords.

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
The current fix prevents the page from crashing when clearing the keywords field.
We will deal with the sorting part on a subsequent PR

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
