### PR TITLE
LPS-166635 | LPS-166636 Integration tests for New related assets collection provider - items with same category 

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

Related tickets
[Link to task](https://issues.liferay.com/browse/LPS-166636)
[Link to task](https://issues.liferay.com/browse/LPS-166635)

This PR contains two issues. One, hide the related collection provider under a FF, the other, the integration test for the component

## Change summary:

* Hide items with the same category collection provider behind FF for the epic
* Don't include the selected item in the list of results
* Add integration tests for the component

## How to test the changes, scenario 1

Note: fix for this is in https://github.com/liferay-echo/liferay-portal/pull/10039

* Start the portal with FF LPS-166036 disabled
* Create a new Display Page Template for Web Content
* Add a collection fragment to the page
* Click on the collection fragment to configure it
* Go to the related collection tabs
* Items with the same category collection provider should not be shown

## How to test the changes, scenario 2

* Start the portal with FF LPS-166036 enabled
* Create a new Display Page Template for Web Content
* Add a collection fragment to the page
* Click on the collection fragment to configure it
* Go to the related collection tabs
* Select Assets with the same category collection provider
* Add a heading to the collection fragment and map the title of the web content to it
* Publish the display page template and mark it as default
* Add a new vocabulary
* Add a category to the vocabulary
* Create a new web content and assign the category to it
* Create a second web content and assign the category to it
* Click on the kebab of the first web content and select "View Content"
* You will see the title of the second web in the list

related

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ozysouza** [comment]
Just waiting the CI post the results on the report to start reviewing :)

**Comment by jkappler** [comment]
@ozysouza, I will take a look, this 

[AssetEntriesWithSameAssetCategoryRelatedInfoItemCollectionProviderTest.testGetCollectionInfoPageWithSameAssetCategory](https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/299121//testReport/com.liferay.asset.internal.info.collection.provider.test/AssetEntriesWithSameAssetCategoryRelatedInfoItemCollectionProviderTest/testGetCollectionInfoPageWithSameAssetCategory) 

shouldn't fail

**Comment by ozysouza** [comment]
Thanks @jkappler!
  
  Would you mind also double-checking these below tests? The first a believe is a fluke but the second could be related.
  
  [SocialActivityServiceTest.testPagingFilterActivities](https://testray.liferay.com/home/-/testray/case_results/2017902350)
  [AssetListAssetEntryProviderTest.testNotCombineSegmentsOfDynamicCollection](https://testray.liferay.com/home/-/testray/case_results/2017900515)

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Hi @ozysouza, those have nothing to do with the PR

**Comment by jkappler** [comment]
ci:forward

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/125302

**Comment by jkappler** [comment]
thanks @ozysouza!

**Pull request closed without merging**
