### PR TITLE
LPS-110819, LPS-111435 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LPS-11089
https://issues.liferay.com/browse/LPS-111435

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
LocalFile.ContentPageConverter#ConvertWidgetPageWithNonStandardLayout isnot related to the changes here, should be fixed in LRQA-57536 and I'll add loading time for LocalFile.WidgetPagesUseCase#SitesPrivatePagesPermissions

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:stop

**Pull request closed without merging**
