### PR TITLE
LPS-135182 Isolate Page Editor Inline Controls

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-135182

Manually forwarded from https://github.com/liferay-frontend/liferay-portal/pull/1226

@liferay-echo This isolates the CSS (make it difficult to overwrite) for Page Editor Inline Controls.

The CSS I'm using to test:
```html
<style>
html {
  font-size: 20px;
}

#senna_surface1 h1,
#senna_surface1 h2,
#senna_surface1 h3,
#senna_surface1 h4,
#senna_surface1 h5,
#senna_surface1 h6 {
  background-color: #282828;
  border: 4px solid #00ff66;
  color: #00ff66;
  font-family: Georgia;
  font-size: 50px;
  font-style: italic;
  font-variant: small-caps
  font-weight: bold;
  line-height: 100px;
  letter-spacing: 2px;
  margin: 10px 0;
  padding: 10px;
  text-align: center;
  text-shadow: 1px 1px 0 #fff;
  text-transform: uppercase;
  white-space: nowrap;
}

#senna_surface1 .btn {
  background-color: #282828;
  border: 4px solid #00ff66;
  color: #00ff66;
  font-family: Georgia;
  font-size: 50px;
  font-style: italic;
  font-variant: small-caps
  font-weight: bold;
  line-height: 100px;
  letter-spacing: 2px;
  margin: 10px 0;
  padding: 10px;
  text-align: center;
  text-shadow: 1px 1px 0 #fff;
  text-transform: uppercase;
  white-space: nowrap;
}

#senna_surface1 .btn:hover {
  background-color: #000;
  color: #ffcc00;
  letter-spacing: 4px;
  font-size: 40px;
}

#senna_surface1 a {
  background-color: #282828;
  border: 4px solid #00ff66;
  color: #00ff66;
  font-family: Georgia;
  font-size: 50px;
  font-style: italic;
  font-variant: small-caps
  font-weight: bold;
  line-height: 100px;
  letter-spacing: 2px;
  margin: 10px 0;
  padding: 10px;
  text-align: center;
  text-shadow: 1px 1px 0 #fff;
  text-transform: uppercase;
  white-space: nowrap;
}

#senna_surface1 a:hover {
  background-color: #000;
  color: #ffcc00;
  letter-spacing: 4px;
  font-size: 40px;
}
</style>
```

Screenshot:
page-editor-controls

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
I think we might be missing [InlineConfirm.scss ](https://github.com/liferay/liferay-portal/blob/76446601f17237d712f15b9653baae9fa01339a5/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/common/components/_InlineConfirm.scss#L3-L26 )here, right'

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
Sending this for now. since it has a lot of changes that are prone to cause conflicts. All related visual issues can be added to  https://github.com/liferay-echo/liferay-portal/pull/5112

**Comment by victorg1991** [comment]
Thanks!

**Pull request closed without merging**
