### PR TITLE
LPS-200468 Test Scenarios Coverage | Backend 1.2

### PR DESCRIPTION
**Pull request by Mikellorza**
subtask: https://liferay.atlassian.net/browse/LPS-200468

waiting to merge : https://github.com/liferay-echo/liferay-portal/pull/14459

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Mikellorza** [comment]
Hi @lfbesada ,

As we talk in slack I have changed the way to assert arrays with more than one element to do not take into account the order. Take a look when you have time.

Thanks in advance!

**Comment by Mikellorza** [comment]
Hi @lfbesada ,

I have changed the way to check the tags regardless of database order since each database works different in terms of order, some are case sensitive or have different collate to order. I aded a new commit to reflect why of this change.

thanks

**Review by lfbesada — APPROVED** [review]
LGTM :tada:

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
