### PR TITLE
LPS-183937 - New site with changed default locale loses name

### PR DESCRIPTION
**Pull request by ruben-pulido**
https://liferay.atlassian.net/browse/LPS-183937

Implemented solution was agreed [here](https://liferay.slack.com/archives/G03LYN0J8/p1696327369765889?thread_ts=1696326072.945969&cid=G03LYN0J8)

@jkappler @ealonso

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Beatlray** [comment]
ci:forward:force

**Comment by david-gutierrez-mesa** [comment]
ci:forward:force

**Pull request closed without merging**
