### PR TITLE
LPD-17451 Auto SF

### PR DESCRIPTION
**Pull request by victorg1991**
Dear reviewer:

What this pr do:
* Hides toolbar when in smaller resolution
* Overlap toolbar in smaller resolution
* Remove fixed and sticky elements in smaller resolution

What this pr doesn't do:
* The height of the elements is a bit off, I have to sync all heights in a following pr

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forwar:force

**Comment by jkappler** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
