### PR TITLE
LPS-117884 Introduce a more powerful framework for verification of InfoItemCapabilities, allowing each of them to do their own validation

### PR DESCRIPTION
**Pull request by JorgeFerrer**
cc: @jkappler @csierra

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:forward

**Comment by JorgeFerrer** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by JorgeFerrer** [comment]
Resent after rebasing: https://github.com/liferay-echo/liferay-portal/pull/1738

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
ci:stop

**Pull request closed without merging**
