### PR TITLE
LPS-121878 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-121878

This is only for master.

@victorg1991
@julien

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
This was sent here before: https://github.com/liferay-echo/liferay-portal/pull/3869 in case anyone is interested in the converstion :D

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
