### PR TITLE
LPS-144089 Navigation Menu Preview

### PR DESCRIPTION
**Pull request by sandrodw3**
Hi @victorg1991 🥰

I applied the changes we were talking about yesterday:

- Added a loading state when the preview is not ready
- Added some padding to the iframe
- Increased modal body heght so big menus fits better
- Added capture: true to iframe's click listener
- Removed no needed useMemo for the preview url

Let me know what you think! Thanks!

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:forward 🙅🏽‍♂️

**Comment by sandrodw3** [comment]
@Tim-Cao could you please confirm if failures are related?

**Comment by ealonso** [comment]
ci:reevaluate:1327401_3627

**Comment by Tim-Cao** [comment]
Sure, I will do it today.

**Comment by Tim-Cao** [comment]
Hi @sandrodw3, there is a regression isssue. It redirects to Navigation Menus admin after save changes of navigation menu item.
**Step to reproduce**

1. Add a widget page
2. Add a site navigation menu
3. Add a page type item using the widget page
4. Use Custom Name for item

**Expected Results:**
It should stay in the navigation menu page after save.

**Actual Results:**
It redirects to Navigation Menus admin page after save.

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
