### PR TITLE
LPS-137747 Use method

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1327401_279

**Comment by victorg1991** [comment]
@rodrigopaulino JFYI I had to fix f9cd301712f7132017c37ef18dc88a44d20286c4 Probably a change introduced recently?

**Comment by victorg1991** [comment]
ci:forward

**Comment by rodrigopaulino** [comment]
Thanks for letting me know, @victorg1991

**Pull request closed without merging**
