### PR TITLE
LPS-156173 Validate the captcha only when is needed

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-156173

Previous PR (approach using configuration): https://github.com/liferay-echo/liferay-portal/pull/8588

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@lfbesada, https://github.com/liferay-echo/liferay-portal/pull/8632 but without captcha

**Comment by jkappler** [comment]
closing for now until we decide on how to handle captcha

**Pull request closed without merging**
