### PR TITLE
LPS-15717 Apply to sitemap the option to exclude Child Pages

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-15717

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:stable

**Comment by lfbesada** [comment]
ci:report:2538377952

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
