### PR TITLE
LPS-173582 When publishing web content folder, Link to Page fields are not be processed correctly

### PR DESCRIPTION
**Pull request by vendeltoreki**
**Notes:**
* Forwarding from: https://github.com/liferay-staging/liferay-portal/pull/220 .
* Made some [optimization](https://github.com/liferay-staging/liferay-portal/pull/220#issuecomment-1408303050)
* The change looks ok from staging perspective

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
Hey @vendeltoreki,

It is part of BPM Team, Could you please forward it to them?

Regards,
Eudaldo.

**Comment by jgarcialr** [comment]
Hey @ealonso ,

We will forward the PR to bpm team. I'll close this one.

Regards

**Comment by jgarcialr** [comment]
ci:close

**Pull request closed without merging**
