### PR TITLE
LPS-183218 Uses selPlid to get the layout and for calling service methods, since in some situations the privateLayout and layoutId are not matching with the selected layout

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Hey @ealonso, a regression found. Steps to repdroduce:

1. Go to Product Menu >> Design >>  Page Templates >> Master tab
2. Add Master Page
3. Go to Display Page Templates tab
4. Add Display Page Template based on the Master Page that you created
5. On the left side bar go to Page Design Options
6. Click on More Page Design Options
7. Change the Custom Masters Page Template to Blank 
8. Save

Expected result:
Configuration is saved and the success message will appear

Actual result:
The page is redirected to Page admin

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
