### PR TITLE
LPS-166942 Removes files

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
Hi @ealonso,

The changes of this PR affecting ADTs (FTL files) might not be automatically applied if the user comes from a previous Update.

I would suggest that we test the upgrade path from a previous Update and, if needed, add a specific Upgrade Step if posible.

**Pull request closed without merging**
