### PR TITLE
LPS-134139 - Remove Feature Flag to hide bulk assignment of display page templates for Categories

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:reevaluate:1077401_7278

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by ruben-pulido** [comment]
https://github.com/liferay-echo/liferay-portal/pull/5050

**Pull request closed without merging**
