### PR TITLE
LPS-144473 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-144473

This is only for master.

@noornajj

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
Hi @noornajj, there is a regression issue found by [ci:test:echo](https://testray.liferay.com/home/-/testray/case_results/1595411687)
The user only with journal article update permission cannot go to page editor since control menu is hidden to user without permissions.

**Step to reproduce**
1. Add a new user assigned a site role only with com.liferay.journal.model.JournalArticle Update permission
2. Assign the new user to default site
3. Add a web content
4. Add a Web Content Display to a content page
5. Display the web content in Web Content Display
6. Publish the content page
7. Sign in as new user
8. Navigate to the content page at view mode

**Expected Behavior**
The pencil icon should be shown in control menu. The user should be edit the web content via Page Content panel in page editor.

**Actual Behavior**
The control menu is hidden.

**Comment by lfbesada** [comment]
Hi @noornajj,

I'm closing this PR by causing the regression bug that @Tim-Cao detailed above. Once corrected, please resend it.

Thank you!

Regards

**Pull request closed without merging**
