### PR TITLE
LPS-166930 Include some margin to properly show focus shadow

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:reevaluate:1307401_5549

**Comment by veroglez** [comment]
ci:reevaluate:1307401_5549

**Comment by ealonso** [comment]
ci:reevaluate:1307401_5549

**Comment by ealonso** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
```[LocalFile.ProductMenu#ViewProductMenuStyles]```

I am going to run this locally, maybe something is failing because of the markup change.

**Comment by p2kmgcl** [comment]
It randomly fails on master too :cry:

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
Hey @p2kmgcl, I saw that the failures are related to changing an element in the code. Before it was as `div` and now as `li`

Before was:
before

After was:
after

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/10495

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
