### PR TITLE
LPS 145208

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-145208 Also take siteNavigationMenuName into account, not only siteNavigationMenuId
- LPS-145208 Copy also siteNavigationMenuName if the typeSettingsProperties contains it
- LPS-145208 Extract from specific method since we also want it available for lfr-widget tags

### CODE REVIEW

**Comment by jkappler** [comment]
@victorg1991 ❤️

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
image

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @jkappler and @victorg1991, the Welcome page is broken and the following error is thrown in console.
```
2022-01-18 06:57:31.307 ERROR [Portal Dependency Manager Component Executor--1][WelcomeSiteInitializer:118] com.liferay.portal.kernel.exception.PortalException: com.liferay.portal.kernel.exception.PortalException: java.lang.NullPointerException
com.liferay.portal.kernel.exception.PortalException: com.liferay.portal.kernel.exception.PortalException: java.lang.NullPointerException
        at com.liferay.site.welcome.site.initializer.internal.WelcomeSiteInitializer._addDefaultGuestPublicLayout(WelcomeSiteInitializer.java:217) ~[?:?]
        at com.liferay.site.welcome.site.initializer.internal.WelcomeSiteInitializer.initialize(WelcomeSiteInitializer.java:115) ~[?:?]
        at com.liferay.site.welcome.site.initializer.internal.instance.lifecycle.AddDefaultLayoutPortalInstanceLifecycleListener.portalInstanceRegistered(AddDefaultLayoutPortalInstanceLifecycleListener.java:61) ~[?:?]
        at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl.registerCompany(Por
```

**Steps to reproduce:**
1. Deploy changes to a clean bundle
2. Start the bundle

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
thanks @Tim-Cao!

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
