### PR TITLE
LPS-124423 Add staging process for fields of type collectionSelector

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@victorg1991, issues don't seems related to the PR, thanks majo

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
