### PR TITLE
LPS-163444 Add flex display options to Collection Display

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @sandrodw3,

What happen if you configure align, flexWrap and justify for a collection and then save a composition and then put it in a page?

**Comment by sandrodw3** [comment]
> Hey @sandrodw3,
> 
> What happen if you configure align, flexWrap and justify for a collection and then save a composition and then put it in a page?

It won't work becasue I have to update import/export 😂

**Comment by ealonso** [comment]
See: https://github.com/sandrodw3/liferay-portal/pull/498

**Pull request closed without merging**
