### PR TITLE
LPS-202908 ComparisonFailure in AssetTagNamesFacetedSearcherTest

### PR DESCRIPTION
**Pull request by Mikellorza**
impedibug: https://liferay.atlassian.net/browse/LPS-202908

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:stop

**Comment by Mikellorza** [comment]
ci:stop

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
