### PR TITLE
LPS-137645  Add styles to json test resource.

### PR DESCRIPTION
**Pull request by lfbesada**
To ensure we are testing that styles are saved properly.

https://issues.liferay.com/browse/LPS-137645

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1327401_256

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
