### PR TITLE
LPS-119582 Restore current permission checker after indexing a content page

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
@Tim-Cao @david-gutierrez-mesa Could you guys please check if this failure https://testray.liferay.com/reports/production/logs/test-1-11/1601458827726/test-portal-acceptance-pullrequest(master)/7718/functional-tomcat90-mysql57-jdk8/33/0/LocalFile.WidgetPagesUseCase_SitesPrivatePagesPermissions/index.html.gz is actually caused by this PR? Thanks!

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by vicnate5** [comment]
ci:test

**Comment by vicnate5** [comment]
Running bigger test suite on this change because it high risk.

**Comment by vicnate5** [comment]
ci:test:bundle

**Comment by vicnate5** [comment]
@pavel-savinov There is still some similar regressions on this PR

#### 1. https://issues.liferay.com/browse/LPS-121303
https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448461/AXIS_VARIABLE=52,label_exp=!master/testReport/junit/com.liferay.portal.log.assertor/PortalLogAssertorTest/testScanXMLLog/
#### 2. https://issues.liferay.com/browse/LPS-121206
Errors on this PR when attempting to create virtual instance with Database partitioning enabled:
```
WARN  [http-nio-8080-exec-9][PortalInstanceLifecycleListenerManagerImpl:146] Unable to register portal instance {mvccVersion=1, companyId=40984, accountId=40988, webId=www.able.com, mx=www.able.com, homeURL=, logoId=0, system=false, maxUsers=0, active=true}
com.liferay.portal.kernel.exception.PortalException: java.lang.RuntimeException: Unable to initialize dummy HTTP servlet request and HTTP servlet response
        at com.liferay.layout.internal.instance.lifecycle.AddDefaultLayoutPortalInstanceLifecycleListener.addDefaultGuestPublicLayoutByProperties(AddDefaultLayoutPortalInstanceLifecycleListener.java:117)
        at com.liferay.layout.internal.instance.lifecycle.AddDefaultLayoutPortalInstanceLifecycleListener.portalInstanceRegistered(AddDefaultLayoutPortalInstanceLifecycleListener.java:69)
        at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl.registerCompany(PortalInstanceLifecycleListenerManagerImpl.java:142)
        at com.liferay.portal.instance.lifecycle.internal.PortalInstanceLifecycleListenerManagerImpl.registerCompany(PortalInstanceLifecycleListenerManagerImpl.java:60)        at com.liferay.portal.service.impl.CompanyLocalServiceImpl.registerCompany(CompanyLocalServiceImpl.java:1349)
        at com.liferay.portal.service.impl.CompanyLocalServiceImpl$2.call(CompanyLocalServiceImpl.java:1929)
        at com.liferay.portal.service.impl.CompanyLocalServiceImpl$2.call(CompanyLocalServiceImpl.java:1925)
```
```
Caused by: java.lang.RuntimeException: Unable to initialize dummy HTTP servlet request and HTTP servlet response
        at com.liferay.layout.internal.search.spi.model.index.contributor.LayoutModelDocumentContributor.contribute(LayoutModelDocumentContributor.java:137)
        at com.liferay.layout.internal.search.spi.model.index.contributor.LayoutModelDocumentContributor.contribute(LayoutModelDocumentContributor.java:64)
        at com.liferay.portal.search.internal.indexer.IndexerDocumentBuilderImpl.lambda$getDocument$1(IndexerDocumentBuilderImpl.java:60)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at com.liferay.portal.search.internal.indexer.IndexerDocumentBuilderImpl.getDocument(IndexerDocumentBuilderImpl.java:58)
        at com.liferay.portal.search.internal.indexer.IndexerWriterImpl.reindex(IndexerWriterImpl.java:235)
        at com.liferay.portal.search.internal.indexer.DefaultIndexer.reindex(DefaultIndexer.java:272)
        at com.liferay.portal.search.internal.indexer.DefaultIndexer.reindex(DefaultIndexer.java:52)
        at com.liferay.portal.search.IndexableAdvice.afterReturning(IndexableAdvice.java:130)
        at com.liferay.portal.kernel.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:66)
        at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
        at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
        at com.sun.proxy.$Proxy100.updateStatus(Unknown Source)
        at com.liferay.layout.internal.instance.lifecycle.AddDefaultLayoutPortalInstanceLifecycleListener.addDefaultGuestPublicLayoutByProperties(AddDefaultLayoutPortalInstanceLifecycleListener.java:108)
        ... 195 more
Caused by: com.liferay.portal.kernel.events.ActionException: com.liferay.portal.kernel.security.auth.PrincipalException$MustBeAuthenticated: User 40990 must be authenticated
        at com.liferay.portal.events.ServicePreAction.run(ServicePreAction.java:152)
        at com.liferay.portal.kernel.events.Action.processLifecycleEvent(Action.java:34)
        at com.liferay.portal.events.EventsProcessorUtil.process(EventsProcessorUtil.java:87)
        at com.liferay.portal.events.EventsProcessorUtil.process(EventsProcessorUtil.java:59)
        at com.liferay.layout.internal.search.spi.model.index.contributor.LayoutModelDocumentContributor.contribute(LayoutModelDocumentContributor.java:131)
        ... 208 more
Caused by: com.liferay.portal.kernel.security.auth.PrincipalException$MustBeAuthenticated: User 40990 must be authenticated
        at com.liferay.portal.events.ServicePreAction._initThemeDisplay(ServicePreAction.java:1100)
        at com.liferay.portal.events.ServicePreAction.servicePre(ServicePreAction.java:168)
        at com.liferay.portal.events.ServicePreAction.run(ServicePreAction.java:149)
        ... 212 more
```
https://testray.liferay.com/reports/production/logs/test-1-8/1601912025391/test-portal-acceptance-pullrequest(master)/6361/functional-tomcat90-mysql57-jdk8/88/0/liferay-log.txt.gz

#### 3. There is also some unique Integration test failures:
1. https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448461/AXIS_VARIABLE=39,label_exp=!master/testReport/junit/com.liferay.portal.search.facet.faceted.searcher.test/FacetedSearcherTest/testSearchByKeywordsIgnoresInactiveSites/
2. https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448461/AXIS_VARIABLE=20,label_exp=!master/testReport/junit/com.liferay.exportimport.test/LayoutSetPrototypePropagationTest/testLayoutPropagationWhenLoadingLayoutsTreeWithLinkEnabled/
3. https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448461/AXIS_VARIABLE=10,label_exp=!master/testReport/junit/com.liferay.commerce.price.list.service.test/CommercePriceEntryLocalServiceTest/testAddCommercePriceEntry2/
4. https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448461/AXIS_VARIABLE=10,label_exp=!master/testReport/junit/com.liferay.commerce.pricing.service.test/CommercePriceModifierLocalServiceTest/testCreatePriceModifierWithInvalidTarget/

CC @david-gutierrez-mesa

**Pull request closed without merging**
