### PR TITLE
LPS-192586 Content Page search indexes are not carried over an upgrade

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-192586

This PR fixes [The contents of the pages created using a site initializer are not indexed](https://liferay.atlassian.net/browse/LPS-193856) @jkappler Could you please take care of following up on both tickets? Thanks in advance :heart:

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by evibudai** [comment]
Hi @lfbesada,
Could you please give an update about this PR? Thank you very much in advance!

**Comment by evibudai** [comment]
Hi @jkappler,
I already tagged Lourdes, but if I'm not mistaken, I should've pinged you. Could you please give an update about this PR?
Thank you!

**Comment by jkappler** [comment]
Hi @evibudai, the update of this PR is that it has an assignee and that it's in review. I will most likely be reviewed soon.

Thanks for reaching out to us.

**Comment by evibudai** [comment]
@jkappler thank you!

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
Hi @evibudai 
I have finished verifying the fix. The PR is ready to be forwarded to Brian

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
Conflicts solved in https://github.com/liferay-echo/liferay-portal/pull/13628

**Pull request closed without merging**
