### PR TITLE
[TS] LPS-123773

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

As discussed in PTR-2095, I sent this PR with the minimal modifications to use the alternative library where this bug is fixed.

Please, let me know if further clarifications are needed or if you prefer that this PR be sent to another team for review.

Thanks in advance

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @dacousalr,
I don't know if we should review this pull or it should be reviewed by other team

**Comment by dacousalr** [comment]
Closing here to continue in #3025

**Pull request closed without merging**
