### PR TITLE
LRAC-14417 LRAC-14380 LRAC-14381

### PR DESCRIPTION
**Pull request by interaminense**
JIRA issues: https://issues.liferay.com/browse/LRAC-14417 https://issues.liferay.com/browse/LRAC-14380 https://issues.liferay.com/browse/LRAC-14381

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:sf

**Comment by interaminense** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
LGTM now! Thanks @interaminense!

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:stable

**Comment by ealonso** [comment]
ci:test:stable

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
