### PR TITLE
LPS-130559 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-130559

This is only for master.

@david-gutierrez-mesa
@sandrodw3

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:stable

**Comment by sandrodw3** [comment]
Thanks @Tim-Cao 😄

**Comment by Tim-Cao** [comment]
Missing the feature flag file

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @sandrodw3, I found an issue, Cannot apply Border Color to Container. Could you check it? It seems like only reproduce on running Poshi cases. It could be workaround by browser cache on manual testing.
Step to reproduce
1. Add a Container to page
2. Add a Card inside the Container
3. Set the Border Color of Container as Danger

Expected Results:
The border-color: (var --danger) should be shown in Container element

Actual Results:
The border-color: (var --danger) is not shown in Container element

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:stable

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
The failure case is also caused by Border Width setting of Container. Need to go around more steps.

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:reevaluate:1087401_7254

**Comment by Tim-Cao** [comment]
WorkflowMetrics#ViewReports is a common failure
https://testray.liferay.com/home/-/testray/cases/1311689211

**Comment by Tim-Cao** [comment]
Due to saving CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/101001

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
