### PR TITLE
LPS-104151 Removes no needed sheet class

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
cc: @manoelcyreno @liulukiwi

**Comment by liulukiwi** [comment]
Hi @ealonso ,
Could you rebase this pull again? thank you in advance.

**Comment by ealonso** [comment]
@liulukiwi Already rebased

**Comment by liulukiwi** [comment]
Hi @ealonso,
Sorry for troubling you again. There'are new comflicting files, could you please rebase it again?

**Comment by ealonso** [comment]
@liulukiwi done

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/2761

**Pull request closed without merging**
