### PR TITLE
LPS-168794 Prefilter to add category filters to related assets collection providers - Backend tests

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-168794

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
Success CI [here](https://github.com/liferay-echo/liferay-portal/pull/11099#issuecomment-1425713315) but the forward isn't executed

**Comment by david-gutierrez-mesa** [comment]
manually forwarded since all tests passed. See https://github.com/brianchandotcom/liferay-portal/pull/130076

**Comment by david-gutierrez-mesa** [comment]
ci:close

**Pull request closed without merging**
