### PR TITLE
LPS-168501 Page configuration fields are blank when changing default language of the site

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-168501

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @lfbesada, there is a regression issue. Cannot save master selection for widget page template.
Step to reproduce
Add a new site
Add a page template set
Add a widget page template
Add a master page
Navigate to the configuration page of widget page template
Change to the new master page
Click Save

Actual Results
Then throw Please enter a valid name. error message

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
@Tim-Cao Thanks a lot for catching it ❤️

**Comment by lfbesada** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward:force

**Pull request closed without merging**
