### PR TITLE
[TS] LPS-119582

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

I have added some changes to address the Websphere case and the case where there is no user or the user is the default user by retrieving a company administrator user.

Please, let me know if you need further clarifications.

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Send for testing review here: https://github.com/vicnate5/liferay-portal/pull/1585

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Pull request closed without merging**
