### PR TITLE
[TS] LPS-157939 Add integration test

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Echo Team,

This is an additional commit to add a test for [LPS-157939](https://issues.liferay.com/browse/LPS-157939)

**Notes from @noornajj:**
> Created test was requested: https://github.com/brianchandotcom/liferay-portal/pull/120495#issuecomment-1187683951

Please let us know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @noornajj @ericyanLr
Thanks for the pull request! 
Please see: https://github.com/liferay-echo/liferay-portal/pull/9334
Regards

**Pull request closed without merging**
