### PR TITLE
LPS-137476 Class that registers DDMStructures as RelatedInfoCollection providers when portal starts and structures are added. We also take care of unregistering them

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:bundle

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/5579

**Pull request closed without merging**
