### PR TITLE
LPS-117535 - Allow changing the stylebook page using the sidebar panel

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @victorg1991

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:close

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/1703

**Pull request closed without merging**
