### PR TITLE
LPS-148025 Uses parameters instead of ServiceContext values.

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-148025

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
