### PR TITLE
LRAC-9857 Allow developers to flag no tracking attribute in the journal Taglib so AC will not track this taglib OOTB

### PR DESCRIPTION
**Pull request by jkappler**
This reverts commit f9fa01a86bd68298594f6b6715e11d2044027d5d.

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Hi @david-gutierrez-mesa, @Tim-Cao, this reverts the revert from a couple of weeks ago in https://issues.liferay.com/browse/LPS-142963

I cannot reproduce the first case with only this commit. For the second one, as @marcellustavares mentioned, we might need to change poshi test accordingly

**Comment by jkappler** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
Hi @jkappler, when access to page editor after restarting. The content of web content cannot be rendered. The following error thrown. Could you double check?
```
2021-11-30 21:00:02.881 ERROR [http-nio-8080-exec-7][FragmentRendererControllerImpl:126] Unable to render content of fragment entry 0:java.io.IOException: Unable to include /asset/full_content.jsp
```

**Pull request closed without merging**
