### PR TITLE
LPS-189245 Web Content and Documents Display Pages are not properly imported

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-189245

This PR is a sample to show how I think we can fix this bug. If this approach were appropriate I think new developments would be needed for:

1. Add integration tests
2. Add UpgradeProcess that detects and tries to fix display pages that may be wrong on installation
3. Put a specific error text when a DPT cannot be imported because its subtype is not site-assignable

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Pull request closed without merging**
