### PR TITLE
[TS] LPS-146712 Add missing LayoutRevision records for content pages

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @liferay-echo team,

I'm resending a previous pull: https://github.com/liferay-echo/liferay-portal/pull/7422

Based on comment: https://github.com/liferay-echo/liferay-portal/pull/7422#issuecomment-1075023444

I think it's worth rewriting the DynamicQuery in the backported solutions. However, in master version, an index already exists on the `Layout` table, that starts with `groupId` and and `type` columns: https://github.com/liferay/liferay-portal/blob/67c950481ea7312816c8c282d4ad76319c2c0f86/sql/indexes.sql#L264
This query would run efficiently by using this index.

cc: @lfbesada 

Thanks,
Vendel

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by vendeltoreki** [comment]
Hi @lfbesada ,

I've uploaded it to [LPS-146712](https://issues.liferay.com/browse/LPS-146712): [Dump20220223_dxp-8-7210.zip](https://issues.liferay.com/secure/attachment/446399/Dump20220223_dxp-8-7210.zip).

* It has 2 site page variations on **testsite2**: **Main Variation** and **SitePageVar1**.
* The widget page **wpage2** only exists on **SitePageVar1**.
* The content page **cpage1** existed on both (that was the only option in dxp-8-7210 portal version), so it will exist in both site page variations after the upgrade.

Regards,
Vendel

**Review by lfbesada — COMMENTED** [review]
Hi @vendeltoreki 
Thanks for the fix!
I have made some changes, please see: https://github.com/liferay-echo/liferay-portal/pull/7630
Thanks! ❤️ 
Regards

**Pull request closed without merging**
