### PR TITLE
LPS-142557 - Collection Display for Objects does not display all instances, even when "Display All Collection Items" is checked

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ruben-pulido, there is a regression issue caused by this PR. When add a collection page, the following NPE is thrown
```
     [exec] 2021-11-23 00:19:11.371 ERROR [http-nio-8080-exec-10][PortletServlet:119] javax.portlet.PortletException: java.lang.NullPointerException
     [exec] javax.portlet.PortletException: java.lang.NullPointerException
     [exec] 	at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCActionCommand.processAction(BaseMVCActionCommand.java:65) ~[portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.callActionMethod(MVCPortlet.java:402) ~[portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.portlet.LiferayPortlet.processAction(LiferayPortlet.java:88) ~[portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.processAction(MVCPortlet.java:256) ~[portal-kernel.jar:?]
     [exec] 	at com.liferay.layout.admin.web.internal.portlet.GroupPagesPortlet.processAction(GroupPagesPortlet.java:119) ~[bundleFile:?]
     [exec] 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:77) ~[portal-impl.jar:?]
     [exec] 	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:50) ~[portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115) ~[portal-kernel.jar:?]
     [exec] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
     [exec] 	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:63) ~[?:?]
     [exec] 	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
     [exec] 	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
     [exec] 	at com.liferay.portlet.internal.InvokerPortletImpl.invoke(InvokerPortletImpl.java:567) ~[portal-impl.jar:?]
     [exec] 	at com.liferay.portlet.internal.InvokerPortletImpl.invokeAction(InvokerPortletImpl.java:607) ~[portal-impl.jar:?]
     [exec] 	at com.liferay.portlet.internal.InvokerPortletImpl.processAction(InvokerPortletImpl.java:285) ~[portal-impl.jar:?]
     [exec] 	at com.liferay.portal.monitoring.internal.portlet.MonitoringInvokerPortlet.processAction(MonitoringInvokerPortlet.java:195) ~[?:?]
     [exec] 	at com.liferay.portlet.internal.PortletContainerImpl._processAction(PortletContainerImpl.java:517) ~[portal-impl.jar:?]
     [exec] 	at com.liferay.portlet.internal.PortletContainerImpl.lambda$processAction$0(PortletContainerImpl.java:148) ~[portal-impl.jar:?]
     [exec] 	at com.liferay.portlet.internal.PortletContainerImpl._preserveGroupIds(PortletContainerImpl.java:421) [portal-impl.jar:?]
     [exec] 	at com.liferay.portlet.internal.PortletContainerImpl.processAction(PortletContainerImpl.java:141) [portal-impl.jar:?]
     [exec] 	at com.liferay.portlet.SecurityPortletContainerWrapper.processAction(SecurityPortletContainerWrapper.java:92) [portal-impl.jar:?]
     [exec] 	at com.liferay.portlet.RestrictPortletContainerWrapper.processAction(RestrictPortletContainerWrapper.java:72) [portal-impl.jar:?]
     [exec] 	at com.liferay.portal.kernel.portlet.PortletContainerUtil.processAction(PortletContainerUtil.java:117) [portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.action.LayoutAction.processLayout(LayoutAction.java:368) [portal-impl.jar:?]
```

**Comment by ruben-pulido** [comment]
Thanks for proactively looking into this @Tim-Cao!

**Pull request closed without merging**
