### PR TITLE
LPS-200303 Cannot see previous published content after submit for workflow on content page as guest

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-200303

@ealonso 

I am convinced that what you proposed as a solution to this ticket at https://github.com/liferay-echo/liferay-portal/pull/14248 is something we should implement but, from my point of view:

1. We should implement an UpgradeProcess that changes the in-curse workflow instances to reference the draft layout instead of the published one, to eliminate from the code the possibility that a published layout is in workflow.
2. We should review a series of associated behaviors to assess how they should behave. For example, some of the behaviors discussed in https://github.com/liferay-echo/liferay-portal/pull/14248 and https://github.com/liferay-echo/liferay-portal/pull/14299

For these reasons, I am proposing to approach the layout workflow changes as a story and apply the changes that this PR incorporates as a solution for LPS-200303

Could you please analyze it?

Thanks in advance!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevan

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
I have rebased with the current master and added https://github.com/brianchandotcom/liferay-portal/pull/146045 to pass CI.

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/146102

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
