### PR TITLE
LPS-180874 Asset Publisher loses configuration when creating A/B test variant in nondefault language

### PR DESCRIPTION
**Pull request by Mikellorza**
Bug : https://issues.liferay.com/browse/LPS-180874

This bug is related to this another one: [LPS-178900](https://issues.liferay.com/browse/LPS-178900). We are keeping the same namespace as the source segment experience from we are creating the variant (Default segments experience or Control variant). So for that reason is causing that wrong portlet preferences are being created. So to fix it, we have to generate a new namespace also for the new variant because they are like a segments experience and a variant is totally independent of another but associated to a A/B test .

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Mikellorza** [comment]
ci:test

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
