### PR TITLE
LPS-137397 Adapt tests

### PR DESCRIPTION
**Pull request by victorg1991**
I want to give it a try to see if some test fail. I want to do some manual testing before this pr is ready to be reviewed

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
