### PR TITLE
LPS-145412 Unregister the current module and register a new one when the fragmentEntryLink is updated.

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @victorg1991 the backend looks good to me, thanks!!! I only will put off the backend review label because the frontend review is still pending. Regards

cc: @sandrodw3

**Comment by sandrodw3** [comment]
Checked functionality and it works perfectly 🥰

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
