### PR TITLE
LPS-159212 Remove unneeded aria-label

### PR DESCRIPTION
**Pull request by p2kmgcl**
Disclaimer: this PR does not represent a great performance improvement, just minor changes that I applied in https://github.com/liferay-echo/liferay-portal/pull/8146 while trying to move ControlContext to store.

I tried measuring the improvement of performance with these changes, but we are speaking about less than 1ms improvements in most cases (it might be a bit more with less powerful PCs).

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
