### PR TITLE
LPS-143509 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-143509

This is only for master.

@lfbesada
cc @ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
Hi @lfbesada, the style of validation error message is changed. Could you double check? The actual is
image
The expected should be
image

**Comment by Tim-Cao** [comment]
The same issue
image

**Comment by lfbesada** [comment]
Hi @Tim-Cao,

The entire popup modal changes, the indication is that it should be the same as the page creation one and that's right, for validation errors too. 

What does not seem correct to me, which also happens when adding a page, is that the name input does not mark an error when the error is a duplicate name.

When frontend will be reviewed I will discuss it with the reviewer.

Thanks!

**Comment by Tim-Cao** [comment]
@lfbesada , I don't think page creation modal has the following conflict styles. The highlight is green while the error message popup.
image
image

**Comment by lfbesada** [comment]
Hi @Tim-Cao 
It is the same issue as in the page creation modal when you enter as name a text with more than 255 characters. 

Captura de pantalla 2021-12-29 a las 8 08 55

All the frontend in this pull request have been copied from add page modal, as I told you, I will discuss it with the frontend reviewer, I think the fix should be applied to both.
Thanks!
Regards

**Comment by sandrodw3** [comment]
Sent a new PR with frontend adapted here: https://github.com/lfbesada/liferay-portal/pull/47.
Some backend work is still pending, so Lourdes will send the final PR when it's done.

@Tim-Cao, just for you to know, server errors will still apear in the toast, and not below the field (that's not possible with the implementation we have). But now the field will be marked as error instead of success.

**Comment by lfbesada** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/6850

**Pull request closed without merging**
