### PR TITLE
LPS-156296 Make sure that the editor is destroyed properly

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
Hey @victorg1991 🥰 I was testing this following the steps on the Jira ticket and I have a doubt: now I can publish after changing the link to blank, but when I edit the page again and inspect the link, it has type default again, instead of blank. Maybe it's not related to your changes, but just in case.

**Comment by victorg1991** [comment]
Should be fixed now @sandrodw3 I had to make sure that the content was saved :)

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
