### PR TITLE
[TS] LPS-159035 | Imported pages are not visible at Site Pages

### PR DESCRIPTION
**Pull request by bakayattila**
hi Team,
Could you review this?

https://issues.liferay.com/browse/LPS-159035

Best,
Attila

-------

**Reproduction steps:**
1. Create a site.
2. Create a public page on the site.
3. Create master page templates (Menu > Design > Page Template > Masters) until the layoutid of the master template becomes equal to the layoutid of the previously created page.
4. Create child pages for the previously created page and make sure that at least one of the pages are created from the master template whose layoutid is the same as the layoutid of the parent page.
5. Create a web content structure with a link to page field.
6. Create a template for the structure.
7. Create a web content from the structure and select the parent page for the Link to Page field.
8. Export the site.
9. Import the exported LAR into a new site.
 
**Expected behavior:** All of the child pages of the parent page are present on the UI. 
**Actual behavior:** Some of (or all of) the child pages are seemingly missing.

------

The root cause of the issue was the following based on my research. The parent layout was overwritten in the layouts map because the parent layout shared the same layoutID as the master template. Because of this, the import linked the child pages to the wrong parent. The layoutId forms a unique key if we combine it with the group id and private page stats but alone it is not enough for a unique key. I fixed it by re-ordering the import. First, try to import the parent layout if it's not a skip, and then try to fetch it. In this order, the layout can be fetched, and I don't have to use the layouts map to get the right layout. Based on my test the import works with this modification and the disappeared layouts will be imported properly.

[LayoutStagedModelDataHandler.java#L861](https://github.com/bakayattila/liferay-portal/blob/master/modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/exportimport/data/handler/LayoutStagedModelDataHandler.java#L861)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
