### PR TITLE
[TS] LPS-141980 Get the scoped asset counts for displaying tags with the "Color by Popularity" template

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @liferay-echo ,

Since the last PR has been rejected (https://github.com/brianchandotcom/liferay-portal/pull/110140#issuecomment-974148060), I came up with a new solution: created `DisplayContext` class for `AssetTagsNavigation` portlet as well. We have one already for the `AssetCategoriesNavigation` portlet: [AssetCategoriesNavigationDisplayContext](https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-categories-navigation-web/src/main/java/com/liferay/asset/categories/navigation/web/internal/display/context/AssetCategoriesNavigationDisplayContext.java)

Unfortunately, I could not inject the count values through [AssetTagsNavigationPortletDisplayTemplateHandler](https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-tags-navigation-web/src/main/java/com/liferay/asset/tags/navigation/web/internal/portlet/template/AssetTagsNavigationPortletDisplayTemplateHandler.java). The first problem is that I can't really access the parameters needed for executing the queries there, and the second is that it would contradict the 1st requirement: https://github.com/liferay-echo/liferay-portal/pull/6341#issuecomment-962981393 . As it would execute the count queries even if we don't use them in the template.

Hopefully this will satisfy both requirements:
* Don't query the asset counts of tags when we don't need them
* Keep only the necessary logic in the FTL (we can't really remove more logic, since the template should still be able to control how it filters the tags, see [PTR comment](https://issues.liferay.com/browse/PTR-2689?focusedCommentId=2555552&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2555552))

cc: @lfbesada , @jkappler 

Please review my changes.

Thanks,
Vendel

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Looks great! Thanks!

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
