### PR TITLE
[TS] LPS-129944 Not needed on configuration modal, let JournalContentPortlet handle this

### PR DESCRIPTION
**Pull request by balazssk**
Hit Team,
This is quite similar to https://issues.liferay.com/browse/LPS-127637 in the way that

- when the article's template has a dynamically included JournalContentPortlet
- and creating the articleDisplay on the configuration modal

the template rendering can get into an infinite loop .

Can you please review?
https://issues.liferay.com/browse/LPS-129944

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
