### PR TITLE
LPS-172635 Copied a Master with a thumbnail in the staging site cause a failure in the publishing process

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-172635)

The goal of these changes is standardise the way we save the preview file entries for all kind of layout page templates

## Change summary:

* Change service layer to use portly repository, just like we do in the action command when uploading a preview image
* Change action command so that we use references and not util classes
* Add integration tests

## Test Scenario

* Follow the steps in the ticket

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
will also apply to utility pages. Same fix

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
