### PR TITLE
LPS-135170 - Removes unnecessary check

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
cc: @ethib137

**Comment by ethib137** [comment]
Additionally, without these changes [here](https://github.com/liferay-echo/liferay-portal/pull/7467/commits/591f397e27ef5cd38c79d1e2cbb6964db0ed6d21) and [here](https://github.com/liferay-echo/liferay-portal/pull/7467/commits/97cef788e665587fe3790d293daad2bab7bccb00) to LayoutCopyHelperImpl.java portletPreferences are being added with incorrect values and are not being removed when the portlet is removed from the page.

**Comment by ealonso** [comment]
Hey @ethib137, the optimization that you added [here](https://github.com/liferay-echo/liferay-portal/pull/7467/commits/337e315c2e223ab988670e736f69ba55b2e4cf03) changes the behavior of the method, so I decided to not include it.

Imagine that you create two pages one public (public-1) and one private (private-1), in the private page you put the <portlet-x> and you go to look for the <portlet-x> you are going to get the private-1, but if you add another public page (public-2) with the <portlet-x> with your code you are going to get always private-1 instead of the original behavior that is get public-2

Regarding LayoutCopyHelperImpl, it should be handle in other LPS ticket

I added a comment https://github.com/liferay-echo/liferay-portal/pull/7467#issuecomment-1076358279, explaining why I did it.

**Comment by ethib137** [comment]
@ealonso gotcha... I see how it could be a feature that we always want to default to the public page if possible. Thanks.

 Regarding LayoutCopyHelperImpl, the way I fixed this issue depended on LayoutTypePortletImpl.getAllPortlets calling LayoutTypePortletImpl.getEmbeddedPortlets which eventually uses portletPreferences to find the portlet. Did your fix add different logic to find portlets on content pages? If it doesn't, this fix won't work until LayoutCopyHelperImpl is fixed since it handles adding and removing portletPreferences.

**Comment by ethib137** [comment]
Thanks @ealonso. 

Okay... so just clarify. This means that the current pull will NOT make it possible to find portlets on content pages. This still won't work until we add the fix in LayoutCopyHelperImpl.

We then need a new ticket for the portletPreference Issues in LayoutCopyHelperImpl which should include tests.

We also need a ticket for using the updated portalImpl in AssetCategoryAssetDisplayPageFriendlyURLResolver.java and CProductAssetDisplayPageFriendlyURLResolver.java. 

Does that sound right?

**Comment by ealonso** [comment]
@ethib137 

> Okay... so just clarify. This means that the current pull will NOT make it possible to find portlets on content pages. This still won't work until we add the fix in LayoutCopyHelperImpl.

Taking into account that everything is working fine in LayoutCopyHelperImpl. This pull should make it possible to find portlets on content pages, it's just your code with some extra optimization, if we can call my commits "optimization" 😂 .

> We then need a new ticket for the portletPreference Issues in LayoutCopyHelperImpl which should include tests.

Yes

> We also need a ticket for using the updated portalImpl in AssetCategoryAssetDisplayPageFriendlyURLResolver.java and CProductAssetDisplayPageFriendlyURLResolver.java.

Yes and it should be send to commerce team

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
