### PR TITLE
LPS-129642 & LPS-129641 Add a search input and a filter in the page content tab

### PR DESCRIPTION
**Pull request by veroglez**
This pull request is a continuation of https://github.com/liferay-echo/liferay-portal/pull/4205, therefore, only the **last three commits should be reviewed**

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
LGMT :D

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
