### PR TITLE
LPS 140253.1

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-140253 New Helper to check if we want to show private pages for a given site
- LPS-140253 New Util class with a service proxy so that we can check if the privates are visible for a given site
- LPS-140253 Apply usage
- LPS-140253 Build service
- LPS-140253 Baseline
- LPS-140253 Adds feature flag for disabling private pages
- LPS-140253 Only hide private pages if the feature flag is disabled

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
@ealonso

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
