### PR TITLE
[TS] LPS-117593

### PR DESCRIPTION
**Pull request by ChrisKian**
From @kevhlee:

> Relevant Tickets:
> 
> - [LPS-117593](<https://issues.liferay.com/browse/LPS-117593>)
> 
> The issue occurs because the "copy layout" action requires the portal namespace for its icon's cssClass, as seen [here](<https://github.com/kevhlee/liferay-portal/blob/LPS-117593/modules/apps/layout/layout-admin-web/src/main/resources/META-INF/resources/layout_action.jsp#L119>). I append the namespace to the cssClass to resolve the problem of the dialog window not appearing. The same issue occurs for the "view collection items" action for collection pages. Thus, I append the namespace to the "view collection items" icon's cssClass as well.
> 
> Additionally, there is another issue where the dialog window does not exit and redirect the user when the user tries to create a copy. As a result, I've added additional changes so that the user gets redirected. My solution is based on code [here](<https://github.com/kevhlee/liferay-portal/blob/LPS-117593/modules/apps/layout/layout-admin-web/src/main/resources/META-INF/resources/js/layout/actionHandlers.js#L18-L24>).

CC @wanderlast

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
@ChrisKian, @kevhlee, sent here: https://github.com/liferay-echo/liferay-portal/pull/1716

Thanks guys!

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
