### PR TITLE
[TS] LPS-186411 Cookies set by SegmentsExperimentSegmentsExperienceRequestProcessor can't be bulk removed

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
SegmentsExperimentSegmentsExperienceRequestProcessor can set multiple cookies with different paths. During logout, at best 1 URLCurrent can be identified from themeDisplay. (During a forced logout after a password change, themeDisplay is null, hence the "at best"). If there are cookies that do not match this path, they will not be present in the request, so those cookies will not be removeable.

Proposed Solution
========
By setting the Path of all cookies set by this class to the root, we will always have browsers send them in the request and we can remove them in the response. In order to do this, I suggest we create the cookies with the original name+plid names as unique names.

Steps to Verify
========
Sadly I don't have clear reproduction steps for this, but if one can store a cookie while a user is logged in with the name= "ab_test_variant_id", value="123" and path="/home" and log out you will see that the cookie remained.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Pull request closed without merging**
