### PR TITLE
LPS-158654 Adapt the width and height of the component to the sidebar

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
Hey @veroglez,

There is an issue with this solution, the width of the sidebar actually depends on width of scrollbars. In some OSs, they push content when there is some overflow, and the SpacingBox does not fit:

Screenshot from 2022-07-27 16-09-11

You can check this on Chrome on MacOS by manually [disabling overlay scrollbars](chrome://flags/#overlay-scrollbars):

Screenshot from 2022-07-27 16-08-08

**Pull request closed without merging**
