### PR TITLE
LPS-120957 Uses correct attribute

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ealonso, there probably be a regression issue in this PR. Could you have a look?
Add a web content article
Add a page based on Blank
Add a Button fragment to page
Click the editable field of Button
Link tab
Content Mapping
Select the web content article
Expected:
The Field field should be enabled
Actual:
The Field field is disabled

**Comment by ealonso** [comment]
Hey @Tim-Cao,
It is not possible, I'm fixing a pop-up in fragments admin, nothing related with web content or content pages. It seems to be a flaky test.
Regards,
Eudaldo.

**Comment by ealonso** [comment]
Hey @Tim-Cao,
Now we have another failure

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, the another failure is a new regression issue caused by https://github.com/liferay-echo/liferay-portal/pull/2329

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/2346

**Pull request closed without merging**
