### PR TITLE
LPS-134139 Remove feature flag and usages

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The failure case is unrelated to changes in PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/103830

**Comment by Tim-Cao** [comment]
ci:close

**Comment by jpince** [comment]
@Tim-Cao @david-gutierrez-mesa I saw Tim manually forwarded a number of pull requests with unrelated test failures. What is being done to follow up on those test failures so PRs don't need manual forwarding?

**Pull request closed without merging**
