### PR TITLE
LPS-176233 master

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

could you please review my fix?

**Steps to reproduce:**

1. Configure a MySQL 8.0.15 server (docker is the easiest way)
2. Generate 20000 articles (dummy factory needs a rebuild to the latest version)
3. Go to site administration -> Web Content and select 'Mine' or 'Recent' filters
**Expected behavior:** The page should load instantly
**Current behavior:** Page loads for 3 minutes

Thanks, Roland

**Root cause**
The ON (1 = 0) logic is slowing down the queries on MySQL 8.0.15

**Fix**
Remove the ON (1 = 0) logic from the queries and change the QueryPos parameters.

https://issues.liferay.com/browse/LPS-176233
More details: https://issues.liferay.com/browse/PTR-3663

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
The failures are not related to this PR. See https://github.com/brianchandotcom/liferay-portal/pull/130856

**Pull request closed without merging**
