### PR TITLE
LPS-119582 Don't index default layout in the lifecycle listener

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
ci:test

**Comment by vicnate5** [comment]
@pavel-savinov The DB partitioning test is **passing** now!

@david-gutierrez-mesa Still one regression I mentioned in https://github.com/vicnate5/liferay-portal/pull/1594#issuecomment-726289723, did you have a chance to look into this?

Links to the unique failing tests:
https://testray.liferay.com/home/-/testray/case_results/1345303303
https://testray.liferay.com/home/-/testray/case_results/1345303489

**Comment by pavel-savinov** [comment]
ci:test

**Comment by jordirodo** [comment]
ci:test:bundle

**Comment by joshuacords** [comment]
Hello @pavel-savinov and others working on this fix. There's a customer issue related to this issue: [LPP-39345](https://issues.liferay.com/browse/LPP-39345). I just downloaded the test bundle and did some testing on it and experienced some problematic behavior you should be aware of. 

These are the steps to reproduce the behavior:
1. Start bundle and Login
2. Create a new web content with Title: apple Content: apple
3. Create a new Content Page Title: Test content
4. Add a Web Content Display widget and select to display the created content
5. Go back to home page and search for "apple"
→OK: The content page and the web content are found
6. Do a full Reindex 
→ERROR: In logs
`Unable to index com.liferay.portal.kernel.model.Layout with primary key 8
java.lang.NullPointerException
	at com.liferay.layout.internal.search.spi.model.index.contributor.LayoutModelDocumentContributor.contribute(LayoutModelDocumentContributor.java:144)`
7. Search for "apple"
→NG: Content page is not found

I get similar results following the reproduction steps on [LPP-39345](https://issues.liferay.com/browse/LPP-39345) which adds the property `index.on.startup=true` to the portal-ext.properties before the same reproduction steps, and instead of doing a full reindex in step 6, restarts the portal.

Will these behaviors be addressed in this ticket?

/cc: @jordirodo

**Comment by joshuacords** [comment]
One additional note that is likely outside the scope of this ticket, the summaries for content pages returned during a search don't highlight the matching phrases. Note how the result for Test Content page contains what appears to be the Web Content Display's widget menus, while what we would like to see is some portion of the "My Apple WC" from the Web Content.
Apple Search Results
Apple Actual Content

**Comment by pavel-savinov** [comment]
Hey @joshuacords, yep, you're 100% correct. Even if we decide to proceed with this approach, we aren't going to index Widgets content since they are dynamic, depend on the user context and it doesn't make a lot of sense to index a particular snapshot.

**Comment by joshuacords** [comment]
Hi @pavel-savinov,
I assume you're talking about my "additional note" not being part of this ticket. I would also like to know your thoughts on https://github.com/liferay-echo/liferay-portal/pull/2938#issuecomment-733851274

 Thanks

**Comment by ealonso** [comment]
We implement another solution please see: https://github.com/liferay-echo/liferay-portal/pull/3143

**Comment by jkappler** [comment]
Just started reviewing :)

**Pull request closed without merging**
