### PR TITLE
LPS-167759 Resources Folder in export/import of fragments

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-167759)

We have changed so that we use the DM browser for fragment collection resources. This opened the pandora box to have also directories, so we have to adapt our code for this

## Change summary:

* Allow to display the complete file when adding resources to a fragment
* Export fragment collections with folders in resources
* Import fragment collections with folders in resources
* Copy resources with folders from one collection to another

## No included in the changes:

* Everything related to staging, will be done in another task

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@ealonso, @lfbesada, follow up for https://github.com/liferay-echo/liferay-portal/pull/10235 changing based on BChans comments

**Comment by jkappler** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:stop

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/126126

**Pull request closed without merging**
