### PR TITLE
LPS-125362 Update tests

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by yichenroy** [comment]
ci:reevaluate:1132004_5359

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
