### PR TITLE
LPD-26903 Removes classNameId cache for asset modules

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by achaparro** [comment]
Hi @ealonso,

From the logical point of view, the changes are good. Especially in the case where you only have a classNameId. [Our method](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/ClassNameLocalServiceImpl.java#L172) does not add much more that what you did, it is just a way to keep the constant in the class but if you do not need it, your solution is better.

When you have two or more classNameIds like in [here](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/ClassNameLocalServiceImpl.java#L172), [our method provides a cache only for your classNames](url). So, with your solution, the performance is slightly worse since you have to go to the map and create the array for all ids anytime the method is called. It is not really noticeable but if the class is widely used in the requests, can be optimal to use the mentioned method instead.

Just take this into consideration, we trust your judgment since you know these components better.

cc/ @marianoalvarosaiz

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
