### PR TITLE
LPS-206141 In Display Page Template changing display style of a Related Items Collection Provider in Collection Display fragment does not work

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,

[LPS-206141](https://liferay.atlassian.net/browse/LPS-206141)

Based on `showEmptyMessage` we either display an empty message warning inside `CollectionContent` or we use `<FlexContainer /> `or `<Grid />` to display the children. I modified the code so we display the `fakeCollection` in flex mode as well and use the same <EmptyCollectionGridMessage /> component on the top. This way the users can drag and drop fragments into the sample collection in every display style expect when they use an already defined template.

Please review my change.

Thanks,

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:report:2488390809

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/15003

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
