### PR TITLE
LPS-173331 Use div so it's valid HTML

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:forward

**Comment by alessandromalves** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Recalling CI once the results were not imported correctly

**Comment by alessandromalves** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1327401_7976

**Comment by sandrodw3** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
The failures are not related to this PR. See https://github.com/brianchandotcom/liferay-portal/pull/129128

**Pull request closed without merging**
