### PR TITLE
LPS-186596 and LPS-186280 Add AI-Creator button to web contents CKEditor and Creates AICreatorOpenAIPortlet

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-186280
https://issues.liferay.com/browse/LPS-186596

cc: @p2kmgcl ❤️

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
This PR is adding the AICreator toolbar in the wrong way, I will fix it and resend

**Pull request closed without merging**
