### PR TITLE
LPS-117778 Do not show page-structure if comments panel is open

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:test:stable

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
Since failure task unrelated to changes in PR and in order to not clog up ci resources I pushed directly to BChan.
See https://github.com/brianchandotcom/liferay-portal/pull/92017

**Pull request closed without merging**
