### PR TITLE
LPS-131037 We need to use the correct className if we are using FileEntry collections

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:reevaluate:1097401_4693

**Comment by victorg1991** [comment]
Checking those tests

**Comment by victorg1991** [comment]
Resent here: https://github.com/liferay-echo/liferay-portal/pull/4406 with the test fixes and the baseline updated

**Pull request closed without merging**
