### PR TITLE
LPS-153104 Adapt test

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @victorg1991, is **ci:test:echo** required? or Just forward this PR?

**Comment by victorg1991** [comment]
@Tim-Cao It is not, we can forward this :)

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
