### PR TITLE
LPS-156173 Partial revert 

### PR DESCRIPTION
**Pull request by lfbesada**
Reverting wrong changes added to a commit, see: https://github.com/brianchandotcom/liferay-portal/pull/119381#issuecomment-1165698570

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
cc: @jkappler

**Comment by lfbesada** [comment]
ci stop

**Comment by lfbesada** [comment]
ci:stop

**Pull request closed without merging**
