### PR TITLE
LPS-146715 Prevent creating items that are empty

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-146715

The asset publisher portlet is creating documents that have blank tags. These tags if add with other tags, prevent the document form being published. A solution for this is to prevent selectedItems form creating a label and value if the tagName is blank.

Let me know if there are any questions or comments about this.
Thank you.

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/7266

**Pull request closed without merging**
