### PR TITLE
LPS-136040

### PR DESCRIPTION
**Pull request by wanderlast**
From @Odrakir1:

> The previous behavior forced the Control Panel group id to be used, because it was stored before the getGroupIds() was called, using the same logic of the Categories Selector did the trick. But, in addition, the portlet URL's parameter "groupIds" was using that id which led the Selector fetch no tag.

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
