### PR TITLE
LPS-152839 AssetEntryItemSelectorView

### PR DESCRIPTION
**Pull request by BarbaraCabrera**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:relevant

**Comment by BarbaraCabrera** [comment]
Hi @david-gutierrez-mesa @Tim-Cao, reviewing the CI errors, I have seen that the bugs are in Poshi tests that could be related to the new views we have implemented. The view changes are expected, so I guess the Poshi tests would have to be modified. Could you take a look at it? thanks in advance!

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @BarbaraCabrera, the item selector cannot filter items with your changes, Is that expected?
**Steps to reproduce**
# Add a manual collection for All Types
# Open the Select Basic Web Content modal

*Actual Results:*
image

*Expected Results:*
image

**Comment by Tim-Cao** [comment]
Second issue, @BarbaraCabrera
The entry in modal is missing link. Is that expected?
**Steps to reproduce**
1. Add a web content
2. Add a Web Content Display to a widget page
3. Select the web content in Web Content Display

**Actual Results**
image

**Expected Results**
image

**Comment by BarbaraCabrera** [comment]
Hi @Tim-Cao, in the case of the first issue "the item selector cannot filter items" is an expected change since in this case it does not apply because you will always have only one single item to filter by. However, thank you very much for finding the errors, we will correct them and I will send the PR back to the repository with the modifications.

**Comment by Tim-Cao** [comment]
Sorry @BarbaraCabrera, I didn't understand in this case it does not apply because you will always have only one single item to filter by.
I don't agree with you.
image
The selector in collection is a multiple items selector.
If remove the Filter and Order, how to change the scope and filter items when lots of items exist?
image

**Pull request closed without merging**
