### PR TITLE
LPS-153000 Set property, otherwise we will have an inconsistency between DB and indexed content

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:close

**Comment by ozysouza** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/117072

**Pull request closed without merging**
