### PR TITLE
LPS-177297 Remove liferay-ui:tabs usages

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Great job guys 👏

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1407401_2519

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward:force

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/135200

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
