### PR TITLE
[7.4.x only] LPS-119655, LPS-123126, LRQA-63043, LRQA-63187 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-119655
https://issues.liferay.com/browse/LPS-123126
https://issues.liferay.com/browse/LRQA-63043
https://issues.liferay.com/browse/LRQA-63187

This is only for master.

@p2kmgcl
@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
