### PR TITLE
LRDOCS-11563 altered language keys

### PR DESCRIPTION
**Pull request by ericthmoritsuka**
Related issue: https://liferay.atlassian.net/browse/LRDOCS-11563

These were the steps I followed:

* In liferay-portal, go to  `liferay-portal/modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties`
look for the key you want to alter and alter it. If necessary, delete the key and add the new one (the file is in alphabetical order)
* Alter all the files where the key was used...
*Once it is done, `cd liferay-portal/modules/apps/portal-language/`
* Run `gw buildLang`
* Run `gw deploy`
* Redeploy the files you altered in step 3 as well

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
