### PR TITLE
LPS-176675 Substitute alert with <clay-alert> in .jsp

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
The motivation behind this ticket is to use clay utilities or clay classes in order to standardize the components in the portal.
[LPS-176675](https://liferay.atlassian.net/browse/LPS-176675)
[LPS-176676](https://liferay.atlassian.net/browse/LPS-176676)
[LPS-176677](https://liferay.atlassian.net/browse/LPS-176677)

Proposed Solution
========
The proposed solution consists in replace the <div alerts> elements with clay:alerts.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Stephy6** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by liulukiwi** [comment]
resend with test-fix: https://github.com/liferay-echo/liferay-portal/pull/12766

**Pull request closed without merging**
