### PR TITLE
LPS-117064 Use fragment entry link configuration as part of styles to maintain backwards compatibility

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
I pushed directly to BChan since all task passed and added a [NOT-FOR-GA5] label reference to https://github.com/brianchandotcom/liferay-portal/pull/92639
See https://github.com/brianchandotcom/liferay-portal/pull/92662

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
