### PR TITLE
LPS-131982 Prevent loss of data

### PR DESCRIPTION
**Pull request by balazssk**
Hi @liferay-echo ,

I've checked https://github.com/liferay/liferay-portal/commit/a379f36affd04f4f92baf6d32041c8ac1010729c for other possible errors like this, but I'm only sure about the change CopyLayoutMVCActionCommand. Can you please check the other cases when zero was set for masterLayoutPlid input parameter?
(like https://github.com/liferay/liferay-portal/commit/a379f36affd04f4f92baf6d32041c8ac1010729c#diff-259a6df63905e26e7c87c3f4abf7222604f31bd1822d568c59e200335f298ecbR739 )

Can you please review?
https://issues.liferay.com/browse/LPS-131982

Thanks,
Balázs

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
