### PR TITLE
master qa 134281

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
The failure case is unrelated to changes in PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/103635

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
