### PR TITLE
[TS] LPS-124622 master

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @liferay-echo

could you plese check my changes and push it forward?

Thanks, Roland

https://issues.liferay.com/browse/LPS-124622

Based on my tests adding the **col** and **col-4** classes breaks the responsivity

The col class is always added by the ColTag.processCssClasses method
the col-lg-4 col-sm-4 col-4 col-md-4 are added by the ResponsiveLayoutStructureUtil.getColumnCssClass method

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @rolandpakai I think this is not a bug, it is how it works by default. You can modify the number of modules that are displayed by role in the "styles" tab of the grid fragment

an example: 

Home_-_Liferay_and_Station

Isn't that exactly the behaviour that you want?

**Comment by duracell80** [comment]
Heads up here, I'll revisit this with help center when we finally get a 7.3 upgrade to work. It's not acceptable to have pages that don't work on mobile. When the user hasn't used the modules per row settings ... the columns (modules) should stack 100% width on phones at least.

Widget pages are more modern!!

**Comment by d80wrk** [comment]
Another year goes by, we are getting closer here, thank you for the efforts.

**Pull request closed without merging**
