### PR TITLE
LPS-184545 The Load More Result button is not present under childpages

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-184545)

Fix two scenarios, the first one is that the load more button doesn't appear during staging process, the other is that the button didn't have a correct behaviour in product menu

## Change summary:

* Change so that the total layout count is used when calculating is we want to show the load more button in the publish process
* Take into account the session key when calculating how to show the load more button in product menu

## Test Scenario No. 1

* Follow the steps in the ticket to reproduce
* At the end, the load more elements is displayed and upon clicking, the tree is expanded

## Test Scenario No. 2

* Start portal with layout.manage.pages.initial.children=5 as explained in the ticket
* Create a new Site
* Add a Home page
* Add several child pages to the home page (one more than the property at least)
* Go to the home page and open the product menu
* Click on Page Tree and expand home page (notice that only 5 childs are shown and a load more button is present)
* Click on load more, and the rest of the child pages are shown
* Click on the cog in pages tree to "configure pages"
* The tree should be expanded and load more button is not shown

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
