### PR TITLE
LPS-152633 Make sure that the fragmentEntry is the pubished version and not the draft

### PR DESCRIPTION
**Pull request by victorg1991**
**This issue is only reproducible with mysql 8.0**

In the fragmentEntry table we may have several entries with the same fragmentEntryKey value, but we have to make sure that the published version is the one we use, since the query doesn't always return the published version.

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
