### PR TITLE
LPS-182702 Add update config logic

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reevaluate:1347401_3987

**Comment by lfbesada** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/11927

**Pull request closed without merging**
