### PR TITLE
LPS-129360

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-129360

Note that this also reverts the "inline" source formatting commit from LPS-125475 ([reference](https://github.com/liferay-echo/liferay-portal/commit/d45cc9b487c920a78bad84a9a6664ca84f45bed6)), as the inlining of the code prevents the fix from working.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @holatuwol,

This test is failing in both ci: test: relevant tries LocalFile.DisplayPagesWithWebContent#ViewDisplayPageViaFriendlyURL, Could you please take a look at it?

Regards,
Eudaldo

**Comment by holatuwol** [comment]
Confirmed regression bug.

1. Create a display page template, set it as the default
2. Create a web content
3. Select the "View Content" link in the web content actions menu, confirm the page renders
4. Change the `/w/` in the URL to `/-/`

Expected behavior is that the page renders. Actual behavior is that we now get an error page.

**Pull request closed without merging**
