### PR TITLE
LPS-150368 - FriendlyUrl resolver to calculate the alternate urls using the current logic for asset publisher

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Already approved by team lima, see: https://github.com/liferay-lima/liferay-portal/pull/3206

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
Hi @georgel-pop-lr 
Thanks for the fix!
I have been testing the bug described in my local env, with the changes of this PR deployed. The behavior that I appreciate in both cases is the one described in the bug with "Actual behavior" so this PR doesn't seem to solve the bug.
Please, could you double-check the fix?
I attach a video with my test steps, I tested using es-ES instead of de-DE. Please, if I have made a mistake testing, could you show me it up?
Thanks, regards

https://user-images.githubusercontent.com/84471361/178211145-5b9298bc-6102-43ba-a178-1bfe1fe9a888.mp4

**Comment by georgel-pop-lr** [comment]
Opened with correct LPS-105422 https://github.com/liferay-echo/liferay-portal/pull/8875

**Pull request closed without merging**
