### PR TITLE
LPS-130069 It's not possible to scroll a structure when the mouse is on the left side of the builder

### PR DESCRIPTION
**Pull request by mateusgomes01**
Related Issue: https://issues.liferay.com/browse/LPS-130069

### CODE REVIEW

**Comment by victorg1991** [comment]
LGTM thanks @mateusgomes01 :)

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
