### PR TITLE
LPS-152956 Create Component UndoHistory

### PR DESCRIPTION
**Pull request by BarbaraCabrera**

### CODE REVIEW

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
Alt Text

**Review by veroglez — APPROVED** [review]

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
