### PR TITLE
LPS-121948 Migrate v2 usages of clay:horizontal-card in fragment/fragment-web

### PR DESCRIPTION
**Pull request by julien**
cc @carloslancha @markocikos

**before**

**after**
2020-11-26-144839_950x827_scrot

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Review by carloslancha — APPROVED** [review]
lnhtm 😉 ❤️

**Comment by victorg1991** [comment]
resent here: https://github.com/liferay-echo/liferay-portal/pull/3041 :) thanks!!

**Comment by victorg1991** [comment]
ci:stop

**Comment by julien** [comment]
thanks @victorg1991

**Pull request closed without merging**
