### PR TITLE
LPS-151411 Not needed, since the view.jsp is the default jsp of the portlet

### PR DESCRIPTION
**Pull request by victorg1991**
It seems that the RenderCommand was not needed, and removing it fixes the issue. I may be missing something though, let's see what the ci have to say

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
@jkappler fyi

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
