### PR TITLE
LPS-132227 Update tests labels

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, there are some issue I would like to confirm with you.
1. The item selector field label is changed to Item but Content in Mapping and Link panel
** Mapping in editable field, Mapping in background image of Container
2. There is no way to clear selected mapping assets
3. Which way should actions keep Change Item Remove Item or Change ${fieldLabel} Remove ${fieldLabel}

**Comment by veroglez** [comment]
Hi @Tim-Cao, answering your questions:

1. Yes, the Content label has been changed by Item label
2. Something has to be happening in your master because this dropdown should have a back button like this:
back_button
3. The second case, but in the case of Content field, it will be Item field

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/4697

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
