### PR TITLE
LPS-136518

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

Found that the source of the poshi test failures. Non-guest site's control panel should not remove the `web/group-name/` from the URL.

Can you please review?
https://issues.liferay.com/browse/LPS-136518

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1297401_380

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1337401_295

**Comment by lfbesada** [comment]
ci:reevaluate:1337401_301

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @balazssk 

Thanks for the PR!

I am afraid that the way you are trying to solve the issue is not the better approach. The /web and /group prefixes are configurable so they can be changed at will in the user installation, please look at: https://docs.liferay.com/portal/7.4-latest/propertiesdoc/portal.properties.html

layout.friendly.url.private.group.servlet.mapping=/group
layout.friendly.url.public.servlet.mapping=/web

In addition, there are other prefixes that should be taken into account and your approach would make difficult the incorporation of new prefixes in the future.

Could you please try another approach to the problem?

From my point of view, the right way is to construct the URL in another way instead of manipulating it. For example, as you did in the first PRs using getCanonicalURL, look at https://github.com/liferay-echo/liferay-portal/pull/5584 I think this approach just needed to adjust getCanonicalURL so that it would not fail if the themeDisplay is not complete properly or to make sure every needed attribute is set in themeDisplay from all the sites that call use the FriendlyURLResolver method.

Regards

**Pull request closed without merging**
