### PR TITLE
LPS-129182 Fix React fragments

### PR DESCRIPTION
**Pull request by izaera**
Please see the commit description for the full details.

I've tested this locally with the fragment provided in the LPS and it works.

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
wrong command xD

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:stop

**Comment by izaera** [comment]
I've set the PR to draft because it may need one change due to https://github.com/liferay/liferay-frontend-projects/issues/458.

**Comment by izaera** [comment]
If you need to push it to continue working just forward it and I will send a followup, but if it is not absolutely necessary I'd say wait for the new commit...

**Comment by victorg1991** [comment]
We decided to remove the other placeholder until the generator counterpart is done. This way we can fix the FP5 right away. resent here: https://github.com/liferay-echo/liferay-portal/pull/4068

**Pull request closed without merging**
