### PR TITLE
[TS] LPS-197128 Check property to display Javascript sections

### PR DESCRIPTION
**Pull request by balazssk**
[LPS-197128](https://liferay.atlassian.net/browse/LPS-197128)

Motivation
=======
It is no longer possible to utilise the method described in https://liferay.atlassian.net/browse/LPSA-74321 to hide the JS input fields on Layout and LayoutSet administration pages

Proposed Solution
========
Add an extra check in the respective jsp files to not render the fieldsets if the properties are false

Steps to Verify
========
Steps to Reproduce:
In the portal-ext.properties, add the following properties
```
field.enable.com.liferay.portal.kernel.model.Layout.javascript=false
field.enable.com.liferay.portal.kernel.model.LayoutSet.javascript=false
```
1. Start the bundle
2. Navigate to the Configure Page menu by clicking Site Builder > Pages > 3-dot icon next to any page > Configure
3. Select the Design submenu
4. Scroll down to Customization
5. Select the Javascript tab

**Expected result:** The javascript text area is gone
**Actual result:** The javascript text area is visible

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @balazssk, 

What happens if we add some js using the ui or headless or services, and then disable the property? Shouldn’t we take it into account?

**Comment by balazssk** [comment]
Hi @ealonso ,
I think I get what you are thinking about. The old solution had a flaw that if the JS was added to a page an admin could not purge it because the field was not present (without a bundle restart with enabled fields).

I could maybe approach this via a disabled input with an alert and a purge button and altering the [LayoutLocalServiceImpl.java#L3547-L3559](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/service/impl/LayoutLocalServiceImpl.java#L3547-L3559) logic to let empty JS override.

This of course will leave the option to add JS through groovy script or through LayoutPersistence

**Comment by victorg1991** [comment]
Hey @balazssk We have changed a bit the definition of the ticket, could you take a look? Basically we want to show a disabled input in the case that there are some JS already saved, but if there isn't any JS we just want to simply hide the input as you did here :)

**Comment by balazssk** [comment]
Cheers for the feedback and @victorg1991 ,
Would https://github.com/liferay-echo/liferay-portal/pull/13800/commits/bba355fb23b6a4d72cc5ef68784849b1af6c2be3 be good or should I refactor some of if the logic into layoutLookAndFeelDisplayContext?

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
