### PR TITLE
LPS-167535 Use new Picker component

### PR DESCRIPTION
**Pull request by sandrodw3**
This PR depends on https://github.com/liferay-frontend/liferay-portal/pull/2919, so we need it to be merged before forwarding this.

There's also another bug that is related (https://github.com/liferay/clay/issues/5271). We could merge this PR without it, but we may have some styles problems.

@liulukiwi is also taking a look to see if we have to adapt some poshi tests.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by liulukiwi** [comment]
ci:test:bundle

**Comment by liulukiwi** [comment]
ci:test:bundle

**Comment by liulukiwi** [comment]
ci:stop

**Comment by liulukiwi** [comment]
Hi @sandrodw3 , there's no testcase to change but I find user can not select page type with the commits in this pull, can you take a look? here are the steps:
# Enable Disable Private Pages from System Settings > Release Feature Flags
# Go back to site
# Go to page tree

Actual result:
There's no dropdown to select page type.
actualvsexpected

**Comment by sandrodw3** [comment]
> Hi @sandrodw3 , there's no testcase to change but I find user can not select page type with the commits in this pull, can you take a look? here are the steps:
> 
> 1. Enable Disable Private Pages from System Settings > Release Feature Flags
> 2. Go back to site
> 3. Go to page tree
> 
> Actual result: There's no dropdown to select page type. actualvsexpected

Hey @liulukiwi, as I told you via Slack, that's happening because we need https://github.com/liferay/clay/issues/5271. I sent you a PR with both PRs together so you can try 😄

**Comment by liulukiwi** [comment]
Hi @sandrodw3 , I run the testcases about page tree and they are able to pass with https://github.com/liferay/clay/issues/5271.

**Comment by sandrodw3** [comment]
> Hi @sandrodw3 , I run the testcases about page tree and they are able to pass with [liferay/clay#5271](https://github.com/liferay/clay/issues/5271).

Perfect! Thanks @liulukiwi 😄

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:stop

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/128225

**Pull request closed without merging**
