### PR TITLE
LPS-168734 Add role=alert to announce required fields when press enter

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-168734

The Screen Reader does not read the required messages when we try to submit the form by pressing `Enter`. I found that adding `role="alert"` made the screen reader read this out.

Please let me know if you have any questions or comments about this.
Thank you!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
Hey @fortunatomaldonado! Thanks for your fix 😄 I've taken advantage to refactor some code in this component and improve some things, final PR is here: https://github.com/liferay-echo/liferay-portal/pull/10478

**Pull request closed without merging**
