### PR TITLE
LPS-139866

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team

could you please review my fix?

**Steps to reproduce:**
_Case 1_

Create a layout template and embed a single instance portlet (e.g. Announcements) in one of the columns (or use the attached template).
Deploy the template.
Create a Widget page and configure the above template for it.
Note LPP-21087 Testing Upgrade #1: The Announcements portlet appears on the page immediately as it is embedded in the template.
Try to add the Announcements portlet to the page

_Case2_

Create a Web Content Structure with one field item
Create a template for the structure with an embedded portelt
<@liferay_portlet["runtime"]
portletName="com_liferay_announcements_web_portlet_AnnouncementsPortlet"
/>
Create a Web Content based on the structure
Create a Widget Page
Add the Web Content to the page
Try to add the Announcements portlet to the page
Actual behavior:
The Announcements (single instance) portlet can be added to the page again if it is embedded in the layout template.

**Expected behavior:**
The Announcements (single instance) portlet can not be added to the page again if it is embedded in the layout template.

**Solution**
The issue is a regression of LPS-127346

Thanks, Roland

https://issues.liferay.com/browse/LPS-139866

Documentation for Embedding Portlets in a Layout Template on 6.2 with processor.processPortlet:
https://help.liferay.com/hc/en-us/articles/360018180991-Embedding-Portlets-in-a-Layout-Template

Documentation for Embedding a Portlet by Portlet Name on 7.2 with @liferay_portlet["runtime"]
https://help.liferay.com/hc/en-us/articles/360028746512-Embedding-a-Portlet-by-Portlet-Name

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
