### PR TITLE
[TS] LPS-124622 Use md instead of cssClass for responsiveness

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @liferay-echo 

could you plese check my changes and push it forward?

Thanks, Roland

https://issues.liferay.com/browse/LPS-124622

Based on my tests adding the col and col-4 classes breaks the responsivity

The col class is always added by the ColTag.processCssClasses method
the  col-lg-4 col-sm-4 col-4 col-md-4 are added by the ResponsiveLayoutStructureUtil.getColumnCssClass method

With the following commit https://github.com/liferay/liferay-portal/commit/a0bd4a81ffbce485d17045389d1dcc575cdbb3e0
the code was refactored from <div class> to <clay:col md >

And with the following commit https://github.com/liferay/liferay-portal/commit/7e122d46f77e43ba486f3b82821b7ec77cc40ac1
the md attribute was replaced with the cssClass attribute.

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @rolandpakai,
Your commits break some tests, Could you please take a look at it?
Regards,
Eudaldo

**Comment by rolandpakai** [comment]
Resent: https://github.com/liferay-echo/liferay-portal/pull/3200

**Pull request closed without merging**
