### PR TITLE
LPS-175928 Quit text-truncate in subtitle for Web Content  in the content tab for Widget Pages and Content Pages

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
[Link to ticket](https://issues.liferay.com/browse/LPS-173139)

## Test Scenario 1

* Navigate to Content & Data > Web Content and create two of them with the names:
	- Company_Liferay_article_new_week_Monday_1 	
	- Company_Liferay_article_new_week_Monday_2
* Navigate to Site Builder > Pages and create one Widget page.
* Navigate to the page and click on the add button.
* Go to “Content” tab and check the subtitle.

image

## Test Scenario 2

* Navigate to Content & Data > Web Content and create one with the name:
	- Company_Liferay_article_new_week_Monday_1
* Navigate to Site Builder > Pages and create one Content page.
* Add one content display and select the web content.
* Check the subtitle in the page content tab.

image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Review by sandrodw3 — APPROVED** [review]

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1257401_6340

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
