### PR TITLE
[TS] LPS-129980 | When configuring a Page it is not highlighted on the Page Tree

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?
According to [PTR-2364](https://issues.liferay.com/browse/PTR-2364) I made selPlid a public render parameter again and fixed the regression issue under [LPS-88949](https://issues.liferay.com/browse/LPS-88949) with the GroupPagesRenderParametersPortletFilter.
The root cause of the regression was the selPLid being able to call on a layout that is not part of the current group.  The new filter will remove any selPlid param that is pointing to another group plid or a non-existing plid.
The last commit makes sure that when we open the pages from the control panel, we will always start on the default plid. This was required by the failure of the poshi tests from the previous pull.

https://issues.liferay.com/browse/LPS-129980
Thank you!

----
Previous pull request: #4321

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
hi @bakayattila, thanks for the PR, I just made some small changes (mostly SF) and resent here: https://github.com/liferay-echo/liferay-portal/pull/4437

**Pull request closed without merging**
