### PR TITLE
LPS-165753, LPS-165838 and LPS-166682 AlternateURLs Integration Tests and Fixes

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-165753

See: https://github.com/brianchandotcom/liferay-portal/pull/123960#issuecomment-1264334168

The Integration Tests had reveal the following bugs, the fixes are included in this PR.

https://issues.liferay.com/browse/LPS-165838
https://issues.liferay.com/browse/LPS-166682

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
A few test failures are related to this PR, I am taking a look...

**Comment by lfbesada** [comment]
@bakayattila this PR is related to https://issues.liferay.com/browse/LPS-164130 
Regards

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1297401_5224

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1277401_5586

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1397401_1352

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/125484

**Pull request closed without merging**
