### PR TITLE
Lps 129407

### PR DESCRIPTION
**Pull request by SamZiemer**
**Ticket:**
<https://issues.liferay.com/browse/LPS-129407>

Tests passed here: https://github.com/SamZiemer/liferay-portal/pull/796#issuecomment-809606996

Notes from @kevhlee
> When the "Select Roles" form is submitted, the action request passes back the IDs of the selected roles. The selected roles are used to determine what site roles to add and remove from the user being edited. However, the issue is that the portal treats the roles that are not included in the selected roles as roles to remove, including **the roles that the user being edited has**:
> 
> <https://github.com/liferay/liferay-portal/blob/7.3.6-ga7/modules/apps/site/site-memberships-web/src/main/java/com/liferay/site/memberships/web/internal/portlet/SiteMembershipsPortlet.java#L255-L268>
> 
> This can lead to the portal attempting to remove the wrong site roles from the user being edited, which can cause permission issues that break the Site Memberships portlet. 
> 
> My solution is to filter out the roles that the current user does not have permission to remove from users. I based my solution on the filtering that is performed when displaying the site roles in the Select Roles modal window:
> 
> <https://github.com/liferay/liferay-portal/blob/7.3.6-ga7/modules/apps/site/site-memberships-web/src/main/java/com/liferay/site/memberships/web/internal/display/context/UserRolesDisplayContext.java#L117-L118>
> 
> Let me know if you have any questions/thoughts.

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/4166

**Pull request closed without merging**
