### PR TITLE
[TS] LPP-48250 | LPS-178629 Adding and deleting a Fragment before publishing the page still count

### PR DESCRIPTION
**Pull request by thienquach87**
Here is the PR for fixing [LPP-48250](https://issues.liferay.com/browse/LPP-48250)([LPS-178629](https://issues.liferay.com/browse/LPS-178629)). The [original PR ](https://github.com/thienquach87/liferay-portal/pull/27)was passed my review
Please help review and leave your comments.

Thanks

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by thienquach87** [comment]
ci:test:sf

**Comment by thienquach87** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @thienquach87 @tototrinh,

Every things looks good. Waiting for tests results to forward it.

Thanks!!

**Comment by ealonso** [comment]
Hey @thienquach87 @tototrinh,
There is a SF error, I already fixed it and resend it here: https://github.com/liferay-echo/liferay-portal/pull/11429

**Comment by ealonso** [comment]
ci:stop

**Pull request closed without merging**
