### PR TITLE
LPS-119092

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @liferay-echo,

Attached is an update for http://issues.liferay.com/browse/LPS-119092.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@tim-cao, are these real failures?? Thanks!

**Comment by Tim-Cao** [comment]
Hi @victorg1991, please check your code, the personal menu icon is gone.

**Comment by ealonso** [comment]
Hey @jonmak08,
Could you please take a look at https://github.com/liferay-echo/liferay-portal/pull/1914#issuecomment-677434584? The tests failures seems to be related with your pull.

Also, Could you please send the following pull to User & Management Team?, they are the owners of this component.

Regards,
Eudaldo.

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
