### PR TITLE
LPS-171854 Wrong language key in custom date format documentation link

### PR DESCRIPTION
**Pull request by DiegoHu97**
Fix changes in this commit: https://github.com/brianchandotcom/liferay-portal/commit/ad61406fafe7924a440250f634e99c0dbb94d634

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
