### PR TITLE
[TECHNICAL SUPPORT] LPS-149018 Global information templates not available in sites

### PR DESCRIPTION
**Pull request by NemethNorbert**
Hey,
[LPS-149018](https://issues.liferay.com/browse/LPS-149018),
I created a collection and added the global site template entries to it as well.
Please review my changes

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @NemethNorbert,

Could you please apply the following changes to your pr?

1. Update service.xml to accept one or more groups adding **arrayable-operator="OR"** to the finder

```
<finder name="G_IICN_IIFVK" return-type="Collection">
   <finder-column arrayable-operator="OR" name="groupId"  />
   <finder-column name="infoItemClassName" />
   <finder-column name="infoItemFormVariationKey" />
</finder>
```
2. Creates a new method in ServiceImpl  that accepts **long[] groupIds**
3. Use the new method instead of addAll
4. To get the groupIds use PortalUtil.getCurrentAndAncestorSiteGroupIds

Regards,
Eudaldo

**Comment by ealonso** [comment]
Hey @NemethNorbert,

Could you please apply the following changes to your pr?

1. Update service.xml to accept one or more groups adding **arrayable-operator="OR"** to the finder

```
<finder name="G_IICN_IIFVK" return-type="Collection">
   <finder-column arrayable-operator="OR" name="groupId"  />
   <finder-column name="infoItemClassName" />
   <finder-column name="infoItemFormVariationKey" />
</finder>
```
2. Creates a new method in ServiceImpl  that accepts **long[] groupIds**
3. Use the new method instead of addAll
4. To get the groupIds use PortalUtil.getCurrentAndAncestorSiteGroupIds

Regards,
Eudaldo

**Comment by NemethNorbert** [comment]
ci:test:sf

**Comment by NemethNorbert** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @NemethNorbert,

Thanks you very much for the changes it looks really nice, 👏🏾 .

Regards,
Eudaldo

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
