### PR TITLE
LPS-120614 Remove unneeded fragment

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
(I'll have a look at this locally)

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/2316

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/2316

**Comment by p2kmgcl** [comment]
ci:close

**Pull request closed without merging**
