### PR TITLE
LPS-127643 Remove the friendlyURLEntires only when removing the last version

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
cc/ @dacousalr

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:stable

**Comment by robertoDiaz** [comment]
See my comment in the jira ticket

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
