### PR TITLE
LPS-135182 Isolate Page Editor Inline Controls

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-135182

Fixed conflicts with https://github.com/liferay-echo/liferay-portal/pull/5139. Original PR rejected by bchan https://github.com/brianchandotcom/liferay-portal/pull/104172.

### CODE REVIEW

**Comment by victorg1991** [comment]
hey @pat270 I think the changes that conflicts with this pr are not yet in master, they are only on the brian's repo. We need to wait a bit until it is synchronized

**Comment by pat270** [comment]
Ok, I used Brian's repo to rebase. Let me know if anything else is needed.

**Comment by victorg1991** [comment]
It is synchronized yet, I've resend it here: https://github.com/liferay-echo/liferay-portal/pull/5155

**Comment by victorg1991** [comment]
Thanks!

**Pull request closed without merging**
