### PR TITLE
LPS-125160 - The styles of fragments are missing in edit mode after upgrade

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @pavel-savinov @victorg1991 @Tim-Cao

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ruben-pulido, why use bottomSpacing instead of verticalSpacing for Separator? The Separator has Height custom style that is verticalSpacing on master. However, bottomSpacing is marginBottom common styles. Could you have a look at again?

**Comment by ruben-pulido** [comment]
Hi @Tim-Cao. I see verticalSpace was replaced by bottomSpacing in this [commit](https://github.com/liferay/liferay-portal/commit/149e0b4272ae71cbeb0fcc50b1f4c3fcba367473)

This [commit](https://github.com/liferay-echo/liferay-portal/pull/3372/commits/c843144a76d39e8f2317bfbf246a63a72759fb70) should take care of upgrading it propperly.

@victorg1991 Can you confirm?

**Comment by Tim-Cao** [comment]
Hi @ruben-pulido, you're right.

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/3376

**Pull request closed without merging**
