### PR TITLE
LPS-127285 Add upgrade step for adding missing columns in  StyleBookEntryVersion

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Just started reviewing :)

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:reevaluate:1147401_7990

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
