### PR TITLE
LPS-138554 Use new TemplateSelectorTag everywhere and remove its "Manage Templates" link

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-138554

Original pull request: https://github.com/liferay-echo/liferay-portal/pull/5771

Hi @Tim-Cao 

As I commented in the previous PR, the test that is failing is because this PR removed the link "Manage templates" in the template selector tag. I suppose that, in addition to the failed test, other tests on other components of the portal that do the same check will also fail.

Thank you a lot for your help!!!

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
ci:test:bundle

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/5791

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
