### PR TITLE
LPS-129536 not deleting preferences from portlet on content page

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/4143

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
