### PR TITLE
[TS] LPS-124622 master

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hello @victorg1991 ,
The original PR is in closed status by now leaving it without response from TS side (my colleague Roland, Pakai is on PTO), so I re-send the PR and would like to continue the discussion in this current PR. The original PR: https://github.com/liferay-echo/liferay-portal/pull/3200 

"I think this is not a bug, it is how it works by default. You can modify the number of modules that are displayed per viewport in the "styles" tab of the grid fragment"

I think what you mentioned is a feature where you can select the number of columns (modules) to display per viewport and you can even adjust the width of modules to create a more custom layout. 
Displaying the columns with this feature, is creating a layout that is not responsive at all when you shrink the screen size, for example to mobile screen. When you choose the 3 columns layout and you shrink the screen size, ideally the modules should be displayed on top of each other, so the user easily can read it. Currently, it does not seem user friendly and responsiveness is the reason why the customer opened an LPP. Responsiveness works on 7.2.x. Can you please let me know your opinion and comment on this?

LPS: https://issues.liferay.com/browse/LPS-124622
Thank you,
Orsolya

### CODE REVIEW

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:stable

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @orsolyaDekany 

Grid fragment is flexible enough to support all kind of responsive behaviour. It is true that by default the 3 columns shrink instead of displaying in top of each other. But this behaviour can be customised very easily. that is the example I gave to Roland in the other pr. This is why I think this change is not necessary, user can just get the same behaviour in several steps.

It is true too than in 7.2 the section fragment used to work that way, in order to fix that in the upgrade we have sent a fix: https://issues.liferay.com/browse/LPS-124609

I hope it makes sense

Thanks!

**Comment by orsolyaDekany** [comment]
Hi @victorg1991 ,
thank you for your comment and sending a fix. I close the PR and will follow up: https://issues.liferay.com/browse/LPS-124609
Thanks,
Orsolya

**Comment by duracell80** [comment]
Heads up here, when we finally get our upgrade to 7.3 working. I will have to push this through help center because it's too much effort to expect users to make the pages responsive to mobile viewports. This is something I should be able to have control over as a designer so that my users do not have to take this extra cognitive load on every page they create.

The solution is:
A toggle:
Off - The page acts like Widget Page Layouts do ... they stack on mobile automatically (100% width).
On - The breakpoint icons appear for mobile / tablet / desktop and the user can choose to customize at that point

It's not acceptable for the pages to fail to display on mobile correctly by default and it's too much cognitive load for users who do not have the knowledge of breakpoints like this. The average user isn't going to do this and our organization will have pages that don't render on mobile breakpoints. This is insane.

I will revisit this with help center some time in the future, maybe 6 to 12 months from now. Please don't mark this as won't fix. These columns need to stack horizontally at 100% width by default.

**Comment by d80wrk** [comment]
Getting there ... slowly. April 2022 it looks like finally the default will stay at 1 for mobile portrait and landscape.

There must be a UX team at Liferay that can analyze what is being released for usability?

**Pull request closed without merging**
