### PR TITLE
LPS-144253 Site navigation menu item display page type multi-selection integration tests

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-144253

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
