### PR TITLE
LPS-148908 Set portrait mobile and landscape mobile modules per row default values

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-148908

@veroglez 
In this PR we are trying a new way to set a feature flag. 

We are using a portal-ext property to enable or disabled the implemented behavior. This way to implement the feature flag is simpler and solves some inconveniences, for example:
1. Now we are able to share a unique feature flag between different modules
2. We don't need a component to hold the feature flag so we can use it in API modules.

This property is named with the prefix feature.flag and followed by the main LPS, in this case: feature.flag.LPS-119551.

The new behavior is only applied if the property is present and its value is true, in any other case, the old behavior is preserved.

We have found two ways to enable or disable the feature flag.

1. Set the property in portal-ext.properties and restart.
2. Using a groovy script to set the desired property value
```
import com.liferay.portal.util.PropsUtil;
import java.util.Properties;

java.util.Properties properties = new Properties();
properties.setProperty("feature.flag.LPS-119551","true");
PropsUtil.addProperties(properties);
```

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
