### PR TITLE
LPS-185583 Custom values are lost in display page templates configuration when editing it

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-185583)

Some configuration that should only be available for draft display pages is exposed for the published layout (SEO and OpenGraph). This PR deals with this situation

## Change summary:

* Remove configuration in display page card that was leading to the published display page
* Changed so that clicking on configuration when editing a display page will lead to the draft configuration and not published configuration
* Some changes in the JSPs of SEO and OpenGraph since there was a backURL issue
* Don't show screen navigation entries for SEO and OpenGraph for published display page templates to avoid future issues

## Test Scenario No. 1

* Start the portal
* Go to Design -> Page Templates -> Display Page Templates
* Create a new Display Page Template (for simplicity, we will create one for categories)
* Publish the empty display page
* Check the kebab actions of the cards, "Configure is not shown"

## Test Scenario No. 2

* Start the portal
* Go to Design -> Page Templates -> Display Page Templates
* Create a new Display Page Template (for simplicity, we will create one for categories)
* Click on the kebab on the top right of the page, and click "Configure"
* Click on SEO Settings and fill in the fields for title and description
* Save, press back and publish the display page template
* Click on the kebab and select "Mark as default"
* Go to Categorization -> Categories
* Create a new vocabulary
* Create a new category
* In the kebab for category, click on View Display Page
* Inspect the page and search for the values specified in the title and description, they should be present  

config

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @jkappler, did we discard the configure action for display page template entry?
If add some fragments into display page template, then publish, the configure action still disappear.


> Test Scenario No. 1
> Start the portal
> Go to Design -> Page Templates -> Display Page Templates
> Create a new Display Page Template (for simplicity, we will create one for categories)
> Publish the empty display page
> Check the kebab actions of the cards, "Configure is not shown"

**Comment by jkappler** [comment]
Hey @Tim-Cao, yes, we removed it from the card for display page template (only for the card and only for display page template).

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/12193

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
