### PR TITLE
LPS-202939 Missing "for" when FF is disabled

### PR DESCRIPTION
**Pull request by p2kmgcl**
https://liferay.slack.com/archives/G03LYN0J8/p1701247943158189?thread_ts=1700789563.537399&cid=G03LYN0J8

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/144621

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
