### PR TITLE
LPS-196687 & LPS-197314 Aria live

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by sandrodw3** [comment]
Works like a charm 😍 I love the `sendMessage` implementation :rainbow:

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:reevaluate:1287401_7751

**Comment by p2kmgcl** [comment]
ci:forward (last attempt, I might have cause some issue, but it looks totally unrelated to my changes)

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
