### PR TITLE
LPS-164507 baseline

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
Hi @ealonso! There are more than 3.000 tests failing to run, with this last force pushed have you fixed it? I was having a look at it

**Comment by ozysouza** [comment]
@ealonso, the error is while starting the portal, it's not starting up withe the follow error

`01-Oct-2022 22:17:14.280 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [158136] milliseconds
2022-10-01 22:17:15.050 ERROR [http-nio-8080-exec-1][BatchingBatch:134] HHH000315: Exception executing batch [java.sql.BatchUpdateException: Data truncation: Data too long for column 'content' at row 1], SQL: insert into LayoutLocalization (mvccVersion, companyId, content, languageId, plid, layoutLocalizationId) values (?, ?, ?, ?, ?, ?)
2022-10-01 22:17:15.051 ERROR [http-nio-8080-exec-1][SqlExceptionHelper:142] Data truncation: Data too long for column 'content' at row 1
2022-10-01 22:17:15.060 WARN  [http-nio-8080-exec-1][PortalImpl:6583] null
com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.PersistenceException: org.hibernate.exception.DataException: could not execute batch
	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.processException(BasePersistenceImpl.java:648) ~[portal-kernel.jar:?]
	at com.liferay.portal.service.persistence.impl.LayoutLocalizationPersistenceImpl.fetchByC_L_P(LayoutLocalizationPersistenceImpl.java:984) ~[portal-impl.jar:?]
	at com.liferay.portal.service.persistence.impl.LayoutLocalizationPersistenceImpl.fetchByC_L_P(LayoutLocalizationPersistenceImpl.java:885) ~[portal-impl.jar:?]
	at com.liferay.portal.service.impl.LayoutLocalServiceImpl.updateLayoutContent(LayoutLocalServiceImpl.java:2949) ~[portal-impl.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
	at com.liferay.portal.service.impl.LayoutLocalServiceStagingAdvice$LayoutLocalServiceStagingInvocationHandler._invoke(LayoutLocalServiceStagingAdvice.java:833) ~[portal-impl.jar:?]
	at com.liferay.portal.service.impl.LayoutLocalServiceStagingAdvice$LayoutLocalServiceStagingInvocationHandler.invoke(LayoutLocalServiceStagingAdvice.java:672) ~[portal-impl.jar:?]
	at com.sun.proxy.$Proxy110.updateLayoutContent(Unknown Source) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_221]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_221]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_221]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_221]
	at com.liferay.portal.kernel.bean.ClassLoaderBeanHandler.invoke(ClassLoaderBeanHandler.java:66) ~[portal-kernel.jar:?]
`

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
@ealonso, the portal is starting up but there is still an error on console which causes an Internal Server Error that is spreaded throughout the portal.
Selection_001


`2022-10-03 19:18:46.735 ERROR [http-nio-8080-exec-2][BatchingBatch:134] HHH000315: Exception executing batch [java.sql.BatchUpdateException: Duplicate entry '0-en_US' for key 'LayoutLocalization.IX_914937DB'], SQL: insert into LayoutLocalization (mvccVersion, companyId, content, languageId, plid, layoutLocalizationId) values (?, ?, ?, ?, ?, ?)
2022-10-03 19:18:46.736 ERROR [http-nio-8080-exec-2][SqlExceptionHelper:142] Duplicate entry '0-en_US' for key 'LayoutLocalization.IX_914937DB'
2022-10-03 19:18:46.744 WARN  [http-nio-8080-exec-2][PortalImpl:6583] null
org.springframework.dao.DataIntegrityViolationException: could not execute batch; SQL [insert into LayoutLocalization (mvccVersion, companyId, content, languageId, plid, layoutLocalizationId) values (?, ?, ?, ?, ?, ?)]; constraint [LayoutLocalization.IX_914937DB]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute batch
	at org.springframework.orm.hibernate5.SessionFactoryUtils.convertHibernateAccessException(SessionFactoryUtils.java:245) ~[spring-orm.jar:5.2.22.RELEASE]
	at org.springframework.orm.hibernate5.HibernateTransactionManager.convertHibernateAccessException(HibernateTransactionManager.java:804) ~[spring-orm.jar:5.2.22.RELEASE]
	at org.springframework.orm.hibernate5.HibernateTransactionManager.doCommit(HibernateTransactionManager.java:639) ~[spring-orm.jar:5.2.22.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743) ~[spring-tx.jar:5.2.22.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711) ~[spring-tx.jar:5.2.22.RELEASE]
	at com.liferay.portal.spring.transaction.DefaultTransactionExecutor.commit(DefaultTransactionExecutor.java:41) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:77) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
`

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ozysouza** [comment]
@ealonso, there is just one more regression issue.

1. Add a new site
2. Add a widget page called Search
3. Add a Search Results widget to widget page
4. Add a Button fragment to content page and publis it
5. Navigate to content page at view mode
6. in the Search Bar type somewhere and enter

The button fragment should be shown in the results

https://user-images.githubusercontent.com/72820234/193868227-83cb3832-9498-45ea-be9d-89890303cf11.mp4

**Pull request closed without merging**
