### PR TITLE
LPS-174019 PATCH web content resets Tags metadata field

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-174019 Reset Tags
- LPS-174019 Pass parameters ordered by name

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@Marina-Gouveia, seems your local git email is incorrect, should be marina.gouveia@liferay.com, not "marina.gouveia@liferay.com" (with the quotes).

I fixed this for this PR, but you probably want to fix this in your local PC 

Screenshot 2023-02-02 at 08 55 57

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Marina-Gouveia** [comment]
Hi @jkappler 
Thank's.

**Comment by liulukiwi** [comment]
Failures are not related, pushed to BChan directly at https://github.com/brianchandotcom/liferay-portal/pull/129656

**Pull request closed without merging**
