### PR TITLE
LPS-117533 Rename from pageType to layoutType

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
@ealonso

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @victorg1991 , Commits message should start with LPS- or LRQA- or LRCI.

**Pull request closed without merging**
