### PR TITLE
[TS] LPS-119667

### PR DESCRIPTION
**Pull request by cleydyr**

### CODE REVIEW

**Comment by cleydyr** [comment]
ci:test:sf

**Comment by cleydyr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
Resend: https://github.com/liferay-echo/liferay-portal/pull/2009

**Pull request closed without merging**
