### PR TITLE
LPS-155821 Update usages

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @victorg1991 @jkappler,

I think with this one we can remove the _getPortletId from [ContentPageEditorDisplayContext.java](https://github.com/liferay-echo/liferay-portal/pull/8529/files#diff-893a928c5365cddbf3553639a6afc15f90014ef581c62f32e9979975c96cacc5)

**Comment by jkappler** [comment]
It's being used, for example when we convert a widget page to a content page, otherwise it will show "Component" as title. Another option would be to change how we convert widgets and treat them like the widgets that we add to the page

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
