### PR TITLE
LPS-161694 master

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @liferay-echo 

could you please review my fix?
https://issues.liferay.com/browse/LPS-161694

**Steps to reproduce:**

As admin:

1.) Add a Organization Role "testrole" and define permissions as follows:
Categorization => Categories: Set all Permissions
Content & Data => Documents and Media: Set all permissions

2.) Add a second Organization Role "testaddon", set no permissions for this role

3.) Add a new user to the portal called "testuser"

4.) Add a new organization called "testorg" and create an organization site in this organization.

5.) Add "testuser" to "testorg" and assign "testrole" and "testaddon" at organization roles.

6.) Go to the settings of the organization site => Categorization => Categories and add 2 vocabularies, visible for site-members only, one called "viewable" and one "limited".

7.) Open the permissions-setting for the vocabulary "limited" and uncheck the checkbox in the viewable-column for the role "Site Member". 

8.) Save the settings and add a category to each vocabulary, viewable again by site-members only. You can name them "category1" and "category2".

9.) Finally, add a blank page to the site, so the user can navigate to it.

10.) Now impersonate the user "testuser" and navigate to the organization site (/web/testorg).

11.) Open the Categorization Menu and make sure you see both vocabularies (viewable and limited) with the corresponding categories in them.

12.) Then go to Content & Data => Documents and Media and add a new document via file upload. Scroll down and open the "Categorization" tab. You will only see the "viewable" vocabulary along with "Topic" and "Tags", although the user should see both vocabularies according to the role permissions set in "testrole".

**Result**: The user will now be able to see the vocabulary "limited" in the upload-screen.

This beahviour is not limited to uploads only. It also occurs when trying to edit existing assets.

**Expected behaviour:** the "View" Setting inherited from the role-settings should also allow users to see the vocabulary in asset-editing, especially as the users are able to see and edit the vocabularies at the Categorization menu.

**Fix**
I added the _visibilityTypes filter parameter to the getGroupVocabularies method 
and in the upload_multiple_file_entries_resources.jsp page i removed visibilityTypes attrib from the liferay-asset:asset-categories-selector to use the default AssetVocabularyConstants.VISIBILITY_TYPE_PUBLIC visibilityType

Thanks, Roland

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by ruben-pulido** [comment]
ci:reevaluate:1257401_4359

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1347401_2721

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
Hi @ruben-pulido 

thanks for reviewing this PR.
Could you please check my question on the LPS here: https://issues.liferay.com/browse/LPS-161694?focusedCommentId=2750890&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2750890

Thanks, Roland

**Comment by liulukiwi** [comment]
The obove 4 unique failures are not releated to this pull after checking, pushed to BChan directly: https://github.com/brianchandotcom/liferay-portal/pull/122747

**Pull request closed without merging**
