### PR TITLE
LPS-152611 baseline

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
I'll start reviewing once the last relevant results went out :)

**Comment by ozysouza** [comment]
Hi @ealonso, could you please have a look on this integration test? The failures is related.

`com.liferay.message.boards.social.test.MBMessageActivityInterpreterTest > testActivityInterpreter FAILED
    com.liferay.trash.exception.NoSuchEntryException: No TrashEntry exists with the key {classNameId=41219, classPK=43841}
    	at com.liferay.trash.service.persistence.impl.TrashEntryPersistenceImpl.findByC_C(TrashEntryPersistenceImpl.java:2288)
    	at com.liferay.trash.service.impl.TrashEntryLocalServiceImpl.getEntry(TrashEntryLocalServiceImpl.java:387)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
    	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
    	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
    	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
    	at com.sun.proxy.$Proxy1135.getEntry(Unknown Source)
    	at com.liferay.trash.internal.TrashHelperImpl.getViewContentURL(TrashHelperImpl.java:238)
    	at com.liferay.social.activity.test.util.BaseSocialActivityInterpreterTestCase._checkLinks(BaseSocialActivityInterpreterTestCase.java:236)
`

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:reevaluate:1277401_5859

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/126439

**Pull request closed without merging**
