### PR TITLE
LPS-131984 Change view to show description and asset types of the vocabulary

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
cc: @jkappler

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The semantic verisoning issue is unrelated to changes in PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/104708

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
