### PR TITLE
LPS-185695 and LPS-185774 Success and Warning widget messages in pages

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-185774
https://issues.liferay.com/browse/LPS-185695

Previous PR: https://github.com/liferay-echo/liferay-portal/pull/12380

Resent because of: https://github.com/brianchandotcom/liferay-portal/pull/136144#issuecomment-1586606480

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ling-alan-huang** [comment]
Hey @lfbesada The SF change looks good to me.

**Comment by jkappler** [comment]
Thanks @ling-alan-huang!

**Review by jkappler — APPROVED** [review]

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
