### PR TITLE
LPS-114729 Extend generic tracker to support services which support multiple implementations

### PR DESCRIPTION
**Pull request by JorgeFerrer**
@ealonso

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/1066

**Comment by ealonso** [comment]
ci:reopen

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
Resent: https://github.com/liferay-echo/liferay-portal/pull/1102

**Pull request closed without merging**
