### PR TITLE
LPS-196807 Older versions of Web Content are indexed with the newest version's values 

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-196807

This PR fixes https://liferay.atlassian.net/browse/LPS-198486 too. On already existing content, a reindex is needed to fix these issues.

After the Echo Team's review, [this commit](https://github.com/liferay-echo/liferay-portal/commit/6beface04d47019d5d27c90b2936b386729dc4bf) should be reviewed by the Search Team.

This PR ensures that the correct entryClassPK field value is added when a model with asset entries is indexed. 
Since now the no-latest article published versions are processed assuming that their assetEntry was the latest published one, and that is not correct.
From now on, for those articles that do not have any asset entry, its entryClassPK is going to be 0. So the AssetEntryDocumentContributor does not add fields for versions that do not have an entry, which fixes the original bug.
The same logic manages to fix LPS-198486 because AssetTagDocumentContributor and AssetCategoryDocumentContributor receive 0 as entryClassPK so they do not use the categories and tags published for the other versions.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
Ready to be sent to the Search Team @lfbesada

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
See: https://github.com/liferay-search/liferay-portal/pull/1114

**Pull request closed without merging**
