### PR TITLE
LPD-28943 Add integration tests for LPP-52844

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you review this fix?
https://liferay.atlassian.net/browse/LPD-28943
best,
Attila

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
Hi @bakayattila!

From what I can see, the tests added are not leading to the code changes that fixed the issue (https://github.com/liferay-echo/liferay-portal/pull/12677/files) to be executed, correct?

We would need tests that cover that logic, otherwise, if the logic breaks it will go unnoticed.
Can you add them?

I have also sent a PR simplifying the tests that were added here: https://github.com/liferay-echo/liferay-portal/pull/12677/files

Thank you!

**Comment by bakayattila** [comment]
Hi @ruben-pulido,
https://github.com/liferay-echo/liferay-portal/pull/15248/files 
This is the fix for the issue. LPS-186892 was the cause. The issue is resolved by adding default values when adding the collection to the layout. The test checks if the default value exists.

**Comment by bakayattila** [comment]
I'm still working on for a test case for LPS-186892 under https://liferay.atlassian.net/browse/LPD-28929

**Comment by ruben-pulido** [comment]
Thanks for the clarification @bakayattila! 

Now everything makes sense. I was confused by the fact that that Pull Requests for LPS-186892 are listed under LP-52844

image

Forwarding to Brian here: https://github.com/liferay-echo/liferay-portal/pull/15903

**Pull request closed without merging**
