### PR TITLE
LPS-194357 Page Editor ColorPicker does not work with manual input

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-194357)

## Proposed solution

Check if there is a color value and use the default value if there is not

## Test Scenario 1

1. Go to the Home Page
2. Start editing the Home Page
3. Select the “Welcome to Liferay” Heading
4. On the right side menu, select the Styles tab
5. Change the background color
    * Click into the input field, don’t use the “Select a color" button on the left of the input field, nor the “Value from Stylebook" button from the right
    * Replace #00000000 with #99FF99

## Result:

https://github.com/liferay-echo/liferay-portal/assets/93203423/0565016a-e153-4f8c-8861-5383f8f93982

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
