### PR TITLE
LPS-164576 Use "Private Page Index" if LayoutCrawler can't retrieve content

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
[LPS-164576](https://issues.liferay.com/browse/LPS-164576)
Ideally LayoutCrawler should be able to handle Public Page indexing, but should it fail because of any reasons (proxy settings, Crawler override settings being bad) the Private Page Indexing logic is not used as a fallback

Proposed Solution
========
Should the Crawler return an empty String for any locale, try the Private Page logic for that locale

Steps to Verify
========
1. Go to Instance Settings
2. Search for Crawler
3. Open Layout Crawler Client Configuration
4. Set Enabled=true and "Hostname or IP Address" = "invalid"
5. Press Save
6. Create a Page with a paragraph with the text "help"
7. Publish the page
8. Search for "help"

Expected behaviour: Page is found
Actual behaviour: Page is not found

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
test failure is because `language.getAvailableLocales` returns an unmodifiable Set

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/9829

**Pull request closed without merging**
