### PR TITLE
LPS-142966 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-142966

This is only for master.

@zhangyan0701
@vicnate5

Would you mind reviewing this changes @vicnate5?
Thanks

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by vicnate5** [comment]
@Tim-Cao This looks good. Good job searching the smaller (and more common) directory first. Have you run any tests on CI with this change? If not, can you run `acceptance-functional` to make sure the tests are working on CI before merging?

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional:nocompile

**Comment by Tim-Cao** [comment]
> @Tim-Cao This looks good. Good job searching the smaller (and more common) directory first. Have you run any tests on CI with this change? If not, can you run `acceptance-functional` to make sure the tests are working on CI before merging?

Make sense! Thanks

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional

**Comment by Tim-Cao** [comment]
Hi @vicnate5, the failure are not related to the changes in PR. LGTM!

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
