### PR TITLE
LPS-130057 Unpublished content pages can be found in search

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @ealonso, I've fixed the broken tests and added a new one. I've also rebased the pr because the change in packaginfo is not needed any more after the latest bump to 8.0.0. Please let me know if you have any comments.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@ricardocousolr, same errors

**Comment by ricardocousolr** [comment]
I'll review those persistent errors, @jkappler

**Comment by ricardocousolr** [comment]
Hi @ealonso, @jkappler,

To solve the test failure LocalFile.PagesAdmin#CheckAndViewCountViaManagementToolbar I chose one strategy (the 3 new commits) but there was an alternative approach in which one would modify the methods 
```
public int getLayoutsCount(
		long groupId, boolean privateLayout, String keywords,
		int[] statuses, String[] types)
``` 
and 
``` 
public List<Layout> getLayouts(
		long groupId, boolean privateLayout, String keywords,
		int[] statuses, String[] types, int start, int end,
		OrderByComparator<Layout> orderByComparator)
```
in the class `LayoutServiceImpl` to include the code
```
if (ArrayUtil.contains(statuses, WorkflowConstants.STATUS_ANY)) {
	return layoutService.getLayoutsCount(
		groupId, privateLayout, keywords, types);
}
```
inside `if (Validator.isNull(keywords)) {`. 

I don't know if this latter approach is better than the one I chose. In any case, the first two commits adding `where="system = [$FALSE$]"` should remain, right?

Please let me know if you have any questions.

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ricardocousolr** [comment]
ci:reevaluate:1037401_9658

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/4661

**Pull request closed without merging**
