### PR TITLE
[TS] LPS-158457 New Structure Field causes Freemarker errors in default Template

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Thank you and best regards,
István

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Dear Team,

The test failures are not related to the solution.

Best regards,
István

**Comment by ealonso** [comment]
Hey @IstvanD,

The problem described in the https://issues.liferay.com/browse/LPS-158457, is a cache problem, if you restart the server everything is working fine.

After debugging the code, I realized that the problem is in JournalArticleImpl:

```java
@Override
public Document getDocument() {
if (_document == null) {
	String content = getContent();

	if (content != null) {
		try {
			_document = SAXReaderUtil.read(getContent());
		}
		catch (DocumentException documentException) {
			if (_log.isWarnEnabled()) {
				_log.warn(documentException);
			}
		}
	}
}

return _document;
}

...

@CacheField(propagateToInterface = true)
private Document _document;

```
As you can see we are caching the _document. Then, when we are changing the ddm structure of the related journal article the cache is not invalidated and we are getting the same _document.

After removing the **if (_document == null) {** everything is working fine.

Could you please take it into consideration and update or resend the pr? We should find the way of invalidating the cache when we are changing the structure.

Thanks!!
Eudaldo

**Comment by IstvanD** [comment]
Hi @ealonso 

Thank you for the review.
I have sent a new pull request: https://github.com/liferay-echo/liferay-portal/pull/9031

**Pull request closed without merging**
