### PR TITLE
[TS] LPS-200487 Sites are not browsable for Guests in Breadcrumb portlet

### PR DESCRIPTION
**Pull request by dcarrillolf**
Motivation
=======
Sites are not browsable for non-admin users in Breadcrumb portlet, even the user has permission to access the group. It occurs when site has Membership type != "Open".
- https://liferay.atlassian.net/browse/LPS-200487
- Previous Pull Requests: 
   - https://github.com/liferay-echo/liferay-portal/pull/14159
   - https://github.com/liferay-echo/liferay-portal/pull/14221

Proposed Solution
========
- Replacing Default Layout permission to current Group check.
- Disable Group membership checking since it has no relantionship to layout browsability

Steps to Verify
========
Steps to reproduce:
1. Start Liferay, create a new site “Test”, and select select “private” or “protected” membership for this site.
2. Add a homepage with a breadcrumb portlet (“horizontal” template, default config).
3. Check “Show current Site” is enabled
4. Logout and reload this page with the Guest user

**Current behavior**: Site “Test” does not have href attribute (breadcrumbEntry.isBrowsable() = false)
**Expected behavior**: The link is enabled and can be used since Guest users have access to the homepage of this site.

It also affects in the opposite way: Open Membership with a Private home layout. In this case, a link with href is visible but 404 error is present when clicking on it.

Alternative Solutions that were discarded
========
1. Adding Layout Permission instead of adding it to current implementation. Discarded since it does not cover both use cases (open / private group membership).
2. Do not consider any kind of permission since current site may be browsable.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by dcarrillolf** [comment]
Considered Product Breaking Change by PTR-4485 (It is not API breaking change).

**Review by lfbesada — APPROVED** [review]
Hi @dcarrillolf 
Thanks for the fix, it works great!
LGTM
Regards

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1287401_8393

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
