### PR TITLE
Lps 149277

### PR DESCRIPTION
**Pull request by noornajj**
https://issues.liferay.com/browse/LPS-149277

Updated based on comment from [#8111](https://github.com/liferay-echo/liferay-portal/pull/8111#issuecomment-1128730531)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by noornajj** [comment]
ci:test:sf

**Comment by noornajj** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Thanks for the changes @noornajj!

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
