### PR TITLE
[TS] LPS-135349

### PR DESCRIPTION
**Pull request by jonathanmccann**
Similar to https://issues.liferay.com/browse/LPS-107358 this changes the default ordering for Structures and Templates so that the newly modified entries appear at the top of the list.

If there is a reason the ordering was meant to be ascending please let me know so that I can inform the client.

Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @Tim-Cao,
Could you please update the poshi test?
We change the order to make it consistent with other views and portlets, now the newly modified entries appear at the top of the list.
Regards,
Eudaldo.

**Comment by Tim-Cao** [comment]
Hi @ealonso, sure! See https://github.com/liferay-echo/liferay-portal/pull/5133

**Pull request closed without merging**
