### PR TITLE
LPS-121031 Filter last active item

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Since the failure task caused by startTestableTomcat and in order to not clog up ci resources I pushed directly to BChan.
See https://github.com/brianchandotcom/liferay-portal/pull/94361

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
