### PR TITLE
LPS-178453 Dispatch event when the panel is activated, so that other fragment can react

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by crodriguezy** [comment]
Hello team, do you think it is safe to provide a customer with this solution?
Thanks! :)

**Comment by p2kmgcl** [comment]
Hey @crodriguezy, I think it is safe, but let's wait for @victorg1991 opinion, he has investigated this more than me :sweat_smile:

**Comment by p2kmgcl** [comment]
@victorg1991 feel free to forward the PR whenever you check this :smile:

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
