### PR TITLE
LPS-112183 Update frontend tests

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
@ealonso semver
```
     [echo] * com.liferay.fragment.util.configuration            MINOR      1.2.0      1.2.0      1.3.0      VERSION INCREASE REQUIRED
     [echo] 	<   interface  com.liferay.fragment.util.configuration.FragmentEntryConfigurationParser
     [echo] 		+   method     getConfigurationJSONObject(java.lang.String,java.lang.String)
     [echo] 			+   access     abstract
     [echo] 			+   return     com.liferay.portal.kernel.json.JSONObject
     [echo] 		+   method     getFieldValue(java.lang.String,java.lang.String,java.lang.String)
     [echo] 			+   access     abstract
```

modules-int failures
```
Unable to validate fragment entry
com.liferay.fragment.exception.FragmentEntryContentException: There is no widget available for alias nav.
	at com.liferay.fragment.entry.processor.portlet.PortletFragmentEntryProcessor._validateFragmentEntryHTMLDocument(PortletFragmentEntryProcessor.java:546)
	at 
```
there are others, not sure if they're related

**Comment by ealonso** [comment]
Thanks @jpince.

Related with:

```Unable to validate fragment entry
com.liferay.fragment.exception.FragmentEntryContentException: There is no widget available for alias nav.
	at com.liferay.fragment.entry.processor.portlet.PortletFragmentEntryProcessor._validateFragmentEntryHTMLDocument(PortletFragmentEntryProcessor.java:546)
	at 

This was fixed by: https://github.com/brianchandotcom/liferay-portal/pull/87776

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Pull request closed without merging**
