### PR TITLE
LPS-121078 Remove unneeded variable

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by jpince** [comment]
Hey @p2kmgcl @victorg1991 @david-gutierrez-mesa, I already see this error in several tests:
`BUILD FAILED: Element is not present at "//div[contains(@class,'management-bar')]//span[contains(@class,'navbar-text')]"`

**Comment by victorg1991** [comment]
I'm taking a look

**Comment by victorg1991** [comment]
Those failures were legit, sending a new one fixing those

**Comment by victorg1991** [comment]
sent here: https://github.com/liferay-echo/liferay-portal/pull/2386

**Comment by victorg1991** [comment]
ci:close

**Pull request closed without merging**
