### PR TITLE
LPS-129860 Modify macro to add custom site for UI change

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ealonso, the Poshi side is not ready.

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/4340

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
