### PR TITLE
LPS-130416 Extract getEditableLinkValue

### PR DESCRIPTION
**Pull request by p2kmgcl**
Only needs to review last two commits

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
Hi @p2kmgcl! Nice refactor! A lot of ugly code simplified 😍

Just found some things, listing them here as some are not directly related to any piece of code:
- You have a typo in the LPS in your commits (146 instead of 416) 😛
- Just curiosity, why `getEditableLocalizableValue` and not `getEditableLocalizedValue`?
- I think links to URL are not being stored well: 
image

If you want me to help just tell me! 🥰

**Comment by p2kmgcl** [comment]
@sandrodw3 I just updated the PR, but I think that the link issue has to be updated in backend @ealonso (it's happening in view mode)

**Comment by Tim-Cao** [comment]
Sure. I will take care of failure cases tomorrow @sandrodw3

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @sandrodw3 and @ealonso, The Not Found is shown when click the link of fragment at view mode.
image

**Comment by Tim-Cao** [comment]
Hi @sandrodw3, there is no Poshi codes required to update.

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/5441

**Pull request closed without merging**
