### PR TITLE
[TS] LPS-162351 | Page configuration does not save after the default language of the site was changed

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?
Best,
Attila

--------

On this pull request I proved the integration test that was requested here:
https://github.com/brianchandotcom/liferay-portal/pull/123051#issuecomment-1246502199

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/9669

**Pull request closed without merging**
