### PR TITLE
LPS 140253.1

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-140253 New method to identify if private pages are enabled for a given site
- LPS-140253 Build service
- LPS-140253 Baseline

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@ealonso

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The failure task is unrelated to this PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/110630

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
