### PR TITLE
LPS-112037 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-112037

This is only for master.

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/1449

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/1450

**Pull request closed without merging**
