### PR TITLE
LPS-158810 Remove FF from properties

### PR DESCRIPTION
**Pull request by ozysouza**
https://issues.liferay.com/browse/LPS-158810

This is only for master.

@Tim-Cao, would you mind revewing the changes I made? We had one test failing on the last report related to this PR. If you agree with the changes would you manually forward to BChan? I believe the relevant will keep failing for the others unrelated failures. 

@victorg1991

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ozysouza** [comment]
ci:test:sf

**Comment by ozysouza** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/9092

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
