### PR TITLE
LPS-147396 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-147396

This is only for master.

@sandrodw3
cc @ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by sandrodw3** [comment]
https://github.com/liferay-echo/liferay-portal/pull/7621

**Pull request closed without merging**
