### PR TITLE
LPS-133579 build.gradle

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Tim-Cao** [comment]
ci:test:bundle

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @ealonso, Does we change multiple selection in one filter to Contains All Categories?

**Comment by ealonso** [comment]
Hey @Tim-Cao,

With this change I'm using the same code to filter manual and dynamic collections, to reuse the code, so we are going to have the same behavior on both type of collections. The idea is fix it on https://issues.liferay.com/browse/LPS-132736.

Regards,
Eudaldo.

**Comment by ealonso** [comment]
ci:reevaluate:1257401_703

**Comment by Tim-Cao** [comment]
However, the dynamic collection also doesn't work when choose multiple selection in one filter. Could you have a look at? @ealonso

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @Tim-Cao,

Could you please help me with the poshi failures? I don't know if it is a bug or a flaky test, 😞 

Regards,
Eudaldo

**Comment by Tim-Cao** [comment]
ci:test:bundle

**Comment by Tim-Cao** [comment]
@ealonso Sure

**Comment by Tim-Cao** [comment]
Hi @ealonso, there is a regression issue caused by your changes. Could you have a look at?
The collection items should always be ordered by descending modified date.
However, they are ordered by ascending modified date when filter by category

**Comment by ealonso** [comment]
Hey @ealonso,
Thanks you very much!!, 👏🏾 , I'll take a look

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
resend: https://github.com/liferay-echo/liferay-portal/pull/4809

**Pull request closed without merging**
