### PR TITLE
LPS-205117 Add button for closing the properties panel in smaller devices

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
Hey @georgel-pop-lr I'd like to know your opinion about this solution before moving forward :) could you take a look please?

**Comment by georgel-pop-lr** [comment]
> Hey @georgel-pop-lr I'd like to know your opinion about this solution before moving forward :) could you take a look please?

Hi @victorg1991 

I checked this and it looks good:
image

Regards.

**Comment by victorg1991** [comment]
Thanks!!

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:report:2487532067

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
