### PR TITLE
LPS-154760 | LPS-155070 - New properties column in Fragment Entries and Sticker changes in UI

### PR DESCRIPTION
**Pull request by jkappler**
https://issues.liferay.com/browse/LPS-154760
https://issues.liferay.com/browse/LPS-155070

This PR adds a new column called properties to the FragmentEntry table. It also includes taking it into account during export/import (from fragment admin UI), staging, and upgrade process.

It also includes changes in stickers and icons

Screenshot 2022-05-31 at 13 48 54

To check the contributed fragment input collection, a feature flag and the component should be enabled:

feature.flag.LPS-150277=true for the feature flag
scr:enable com.liferay.fragment.collection.contributor.inputs.InputsFragmentCollectionContributor for the component

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Review by lfbesada — APPROVED** [review]
❤️

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
