### PR TITLE
LPS-171421 Page Draft Accessibility

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
FWD: https://github.com/fortunatomaldonado/liferay-portal/pull/73

Hello, please let me know if there are any questions or comments about this.

> [LPS-171421](https://issues.liferay.com/browse/LPS-171421) Modified divs to allow SR to read page title and draft status. I added a new header for this that is only accessible by the screen reader so it reads the correct status if the page is a Draft.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
Hey @SelenaAungst @fortunatomaldonado 

I'm reviewing the bug and it seems that the description is a bit off, this label should not be focusable since it doesn't have any action associated, I do agree that the `*` should be hidden from the screen reader, and maybe adding a hidden label, but since it is not very clear I'm going to move the issue back to open to see if we can verify it again :)

Thanks and sorry for the inconvencience!

**Comment by victorg1991** [comment]
Hey @SelenaAungst and @fortunatomaldonado The bug is now ready again :) if you want to check this out

**Comment by SelenaAungst** [comment]
Hi @victorg1991,
It looks like this has been resolved elsewhere, but please let me know if there is anything else I can do!

**Pull request closed without merging**
