### PR TITLE
LPS-169953 Fix some behaviors for Utility Pages actions Part II

### PR DESCRIPTION
**Pull request by lfbesada**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-169953)

For utility pages there are behavioural actions that have been developed for the optimal functioning of them, such as edit, rename, mark as default... and they should work as expected. 

## Proposed solution

For each of the operational problems a solution is proposed. 

1. When the Utility pages in draft are still marked by default when they should not be, it is proposed to disable the option 
when the pages have not been published.
2. In the case of the alerts, what was happening was that the name was not being properly validated, so changes are proposed in the validate to take into account invalid characters or duplicate names.
3. For the case where the thumbnail is not copied, it is proposed to add a method that obtains the thumbnail and adds it when the utility page is copied inside the Local Service.
4. Finally, we had to improve the import of the Utility Pages so that when importing one, it warns the user if the import is correct, incorrect or if there are warnings, so the Page Templates are taken as a reference and the same adapted solution is implemented. 

 ## Change summary:

* Disable the option of mark by default when the pages have not been published.
* Validate invalid characters or duplicate names.
* Add a method that obtains the thumbnail and adds it when the utility page is copied inside the Local Service.
* Implement alerts for the import (success, warnings, unable).

## Test Scenario

- Activate FF for Utility Pages (LPS-162765)
- Navigate to Site Builder > Pages
- Go to Utility Pages tab and create some Utility Pages.

     ### Mark draft page as default.

1. Edit one Utility Page and let it in draft.
2. Go back, open the dropdown with the actions and try to select "Mark as Default".

     ### Rename.

1. Open the dropdown with the actions for one of the Utility and select "Rename".
2. Try to write a space as the name and click in save.
3. Try to write the name of a Utility that already exist and click in save.

     ### Copy thumbnail.

1. Open the dropdown with the actions for one of the Utility Pages and select "Copy".

     ### Import.

1. Open the dropdown with the actions for one of the Utility Pages and select "Export".
2. Open the upper menu and try to import  the exported Utility Page.
    - To obtain a success message let the "Overwrite Existing Utility Pages" checked.
    - To obtain an unable message uncheck the "Overwrite Existing Utility Pages".
    - To obtain a warning message
               a) Create a role
               b) Create a Utility Page
               c) Add any widget
               d) Open the menu and click on widget settings > change permissions of the new role
               e) Publish the Utility Page
                f) Export the Utility Page
               g) Delete the Utility Page
               h) Remove the permissions you added to the Role
                i) Import the Utility Page

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:forward

**Pull request closed without merging**
