### PR TITLE
LPD-16086 Don't compute the value for item selector and url fields

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
Thanks, @victorg1991, for having a second look, I like this approach better and solve the export file instead.

I think this is good to be merged.

**Comment by georgel-pop-lr** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:report:2533671564

**Pull request closed without merging**
