### PR TITLE
LPD-21554 - Some page names result in 404 friendly URLs

### PR DESCRIPTION
**Pull request by ruben-pulido**
Description from original PR: https://github.com/liferay-echo/liferay-portal/pull/15419

Motivation
=======
**Given** a page being created with a 2 letter locale code as its name
**When** that locale IS NOT available for the site
**Then** the locale code will be used as friendlyURL for the page

but,
**When** that locale IS available for the site
**Then** the `layoutId` will be used as friendlyURL for the page

Because URLs with locale codes are reserved for language changes and will not render pages. If the locale is not available, a 404 page will be displayed.

[LPD-21554](https://liferay.atlassian.net/browse/LPD-21554)

Proposed Solution
========
During page friendlyURL validation use all the supported locales to prevent the generation of a reserved friendlyURL

Steps to Verify
========
1. Create a Widget Page named `th`
2. Navigate to the home page
3. Click the `th` link in the navigation bar

**Expected behaviour:** The widget page opens
**Actual behaviour:** A 404 page opens

//@balazsk

### CODE REVIEW

**Comment by sandrodw3** [comment]
Hey @ruben-pulido this looks very good 🥰 but I think you can simplify it and save a lot of code by using my isolated site fixture. It creates a blank site for each test, and remove it at the end of the test (even if it fails), so you wouldn't need all the code to remove the layout and to get the group. What do you think? You can see it [here](https://github.com/liferay-echo/liferay-portal/blob/master/modules/test/playwright/tests/layout-content-page-editor-web/keyboard.spec.ts) for example

**Comment by ruben-pulido** [comment]
Hi @sandrodw3 
In order to reproduce the issue the page needs to be created in the guest site. That's the reason I didn't use the isolatedSiteTest feature

**Comment by sandrodw3** [comment]
ci:test:playwright

**Comment by sandrodw3** [comment]
Waiting for the test to pass in CI before forwarding 🚀

**Comment by ruben-pulido** [comment]
https://github.com/ruben-pulido/liferay-portal/pull/546

**Comment by ruben-pulido** [comment]
Rebased and fixed test here: https://github.com/liferay-echo/liferay-portal/pull/15448

**Pull request closed without merging**
