### PR TITLE
LPS-148836 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-148836

This is only for master.

@lfbesada
Thanks for your help!
I tested on my local. The FF file works and doesn't cause unit tests failure.
Would you mind double check? Thanks!

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Hi @Tim-Cao LGTM Thanks! :heart:

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/114433

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
