### PR TITLE
LPS-159738 Added empty alt attribute for accessibility.

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
FWD: https://github.com/fortunatomaldonado/liferay-portal/pull/39

Let me know if this should go elsewhere.
Thank you!

> [LPS-159738](https://issues.liferay.com/browse/LPS-159738) Added empty alt attribute for accessibility.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
Hi @fortunatomaldonado! Thanks for this 👏 👏 👏

**Comment by veroglez** [comment]
ci:forward

**Pull request closed without merging**
