### PR TITLE
[TS] LPS-131937 | Collection Display Fragment collection selector displays collections of Parent site at the Child Site Scope

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-131937
Thank you!

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/4579

**Pull request closed without merging**
