### PR TITLE
LPS-110925 Update modal usages in fragment-web

### PR DESCRIPTION
**Pull request by wincent**
Sending this over for you folks to verify. The code looks fine to me (reviewed over in https://github.com/wincent/liferay-portal/pull/198 and https://github.com/wincent/liferay-portal/pull/203), but in my testing I was getting some [weird modal behavior](https://github.com/wincent/liferay-portal/pull/198#issuecomment-610847351) where the modal wouldn't close and I ended up being able to nest modal inside modal inside modal... However, @markocikos [can't repro](https://github.com/wincent/liferay-portal/pull/198#issuecomment-610875585), and I am suspicious of my repo state (even though I did `git clean` and `ant all`).

### CODE REVIEW

**Comment by wincent** [comment]
ci:test:relevant

**Comment by wincent** [comment]
(Already ran `ci:test:sf` [over on my fork](https://github.com/wincent/liferay-portal/pull/203#issuecomment-610942504).)

**Comment by sandrodw3** [comment]
Thanks @wincent 🙂I'll take a look

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by markocikos** [comment]
@sandrodw3 There are two failures that may be related to this PR:
1. [LocalFile.FragmentsImporter#CannotImportNonZip](https://testray.liferay.com/reports/production/logs/test-1-18/1586362530872/test-portal-acceptance-pullrequest(master)/3202/functional-tomcat90-mysql57-jdk8/51/1/LocalFile.FragmentsImporter_CannotImportNonZip/summary.html.gz)
1. [LocalFile.ContentPages#AddContentPage](https://testray.liferay.com/reports/production/logs/test-1-18/1586362530872/test-portal-acceptance-pullrequest(master)/3202/functional-tomcat90-mysql57-jdk8/2/0/LocalFile.ContentPages_AddContentPage/summary.html.gz)

Both are the same error: file cannot be uploaded using import modal.

I just did a fresh `ant all` on this branch and I cannot reproduce this. I am getting this:

screen

As you can see in the screenshot, the test seems to be fine and finds the element.

Can you reproduce the issue?

/cc @wincent

**Comment by ealonso** [comment]
ci:stop

**Comment by markocikos** [comment]
Rebased and force-pushed, to rerun tests. No changes.

**Comment by markocikos** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
Hey @markocikos, taking a look at this one today 🙂

**Comment by sandrodw3** [comment]
@markocikos I rebased and rerun tests today and a bunch of them are still failing. Most of them with the same failure:

`Element is not present at "//input[contains(@id,'file') or contains(@id,'File')][@type='file'] | //input[@type='file']"`

I haven't been able to figure out why they are failing, as the markup inside the modal is not changing in this PR, so it should still find the input. I'll ping the QA guys to see if someone can help.

**Comment by markocikos** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/218

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
