### PR TITLE
LPS-147323 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-147323

This is only for master.

@victorg1991
cc @p2kmgcl

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Resend this here: https://github.com/liferay-echo/liferay-portal/pull/7233 @Tim-Cao I cherrypicked your commits too

**Pull request closed without merging**
