### PR TITLE
LPS-184418 Test Scenarios Coverage | Backend

### PR DESCRIPTION
**Pull request by Mikellorza**
Waiting to be merged this PR: https://github.com/liferay-echo/liferay-portal/pull/13553

Story: https://liferay.atlassian.net/browse/LPS-175120
Subtask: https://liferay.atlassian.net/browse/LPS-184418

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@Mikellorza, there seems to be an SF issue in ImportMVCResourceCommandTest.java (not related to UserLocalServiceUtil)

**Comment by jkappler** [comment]
Semantic version issue is related to the PR that needs to be merged first

**Comment by jkappler** [comment]
Fixed rebase issues here: https://github.com/liferay-echo/liferay-portal/pull/13594

**Pull request closed without merging**
