### PR TITLE
LPS-147252, LPS-147253, LPS-146976, LPS-147251 & LPS-148717 

### PR DESCRIPTION
**Pull request by lfbesada**
cc:// @david-gutierrez-mesa @Tim-Cao @ruben-pulido @sandrodw3 

This feature branch is ready for the QA round

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @Tim-Cao,
I have been taking a look at the failed Poshi tests and it seems that they fail because when they are looking for a checkbox with the label "Display All Collection Items". This feature changed some pagination options including that one. Instead of that checkbox, in a pagination option different to "None", you will find a checkbox with the label "Display All Pages".
Could you please review these tests?
Thanks a lot! ❤️ 
cc:// @sandrodw3 @ruben-pulido

**Comment by sandrodw3** [comment]
> Hi @Tim-Cao, I have been taking a look at the failed Poshi tests and it seems that they fail because when they are looking for a checkbox with the label "Display All Collection Items". This feature changed some pagination options including that one. Instead of that checkbox, in a pagination option different to "None", you will find a checkbox with the label "Display All Pages". Could you please review these tests? Thanks a lot! ❤️ cc:// @sandrodw3 @ruben-pulido

In addition to what @lfbesada said, the checkbox "Display All Collection Items" appears now when you have selected "None" in Pagination field. Another important note is that now the default value for Pagination field is "Numeric", instead of "None" 🥰

**Comment by Tim-Cao** [comment]
I will update them and test upgrade and import issue tomorrow. @lfbesada and @sandrodw3, if there are no issues, could I forward it? Is there any other review needed?

**Comment by sandrodw3** [comment]
> 

Yep! Feel free to forward it 🥰

**Comment by sandrodw3** [comment]
> I will update them and test upgrade and import issue tomorrow. @lfbesada and @sandrodw3, if there are no issues, could I forward it? Is there any other review needed?

Yep! Feel free to forward it 🥰

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7527

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
