### PR TITLE
LPS-156173 [App Pages] Validate captcha only when a captcha fragment is present 

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-156173

cc: @ealonso

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:reevaluate:1317401_3939

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
