### PR TITLE
LPS-113740 Moves method to MillerColumnsDisplayContext where it is used

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jpince** [comment]
@ealonso in the breadcrumb, it now says `Public Pages > Public Pages` instead of `Pages > Public Pages`
image
```
Error Message
java.lang.RuntimeException: Element is not present at "//ol[contains(@class,'breadcrumb')]//*[text()='Pages']"
```

**Comment by ealonso** [comment]
@jpince I'm working o n it

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jpince** [comment]
@ealonso test failure unrelated, can you just push directly to BChan?

**Comment by brianchandotcom** [comment]
@ealonso I merged this.

**Comment by jpince** [comment]
ci:close

**Pull request closed without merging**
