### PR TITLE
LPS-170210 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Hi @veroglez, could you resolve the conflict file of portal-impl/src/portal.properties
 at first? I'm checking the other failures.

**Comment by liulukiwi** [comment]
Failures are not related.

**Comment by ealonso** [comment]
Hey @liulukiwi 

I manual forwarded this one please see: https://github.com/brianchandotcom/liferay-portal/pull/127649

**Pull request closed without merging**
