### PR TITLE
LPS-133852 & LPS-133853 Allow searching for widget templates in add panel

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
resent here: https://github.com/liferay-echo/liferay-portal/pull/4837

**Pull request closed without merging**
