### PR TITLE
LPS-129802 Sort link options by priority

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
@Tim-Cao I think this is going to break some poshi tests, as we are changing some "link mapping" labels (see https://issues.liferay.com/browse/LPS-120198?focusedCommentId=2405097&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2405097)

**Comment by p2kmgcl** [comment]
I am removing this "priority" field so @victorg1991 can be happy

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/4132

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
