### PR TITLE
LPS-147972 Update usage for link to a page of this site

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:help

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/8190

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
Missing cherry-pick this one https://github.com/liferay-echo/liferay-portal/pull/8168/commits/10b7b745200a057340dc162967d6abc703b94c30

**Pull request closed without merging**
