### PR TITLE
LPS-198161 Do not import if the utility page with the same ERC exists and throw a warning

### PR DESCRIPTION
**Pull request by jkappler**
https://liferay.atlassian.net/browse/LPS-198161

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142186

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
