### PR TITLE
LPS-128826 Migrate v2 usages in asset/asset-list-web

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

Creating and deleting collections and viewing their usages should work as
expected.

**Test plan**:
- Navigate to **Site Builder** > **Collections**
- Click on the **+** button on the right and make sure you can
    - Create a manual collection
    - Create a dynamic collection
- Make sure you can delete a collection
- Navigate to **Content & Data** > **Blogs**
- Create a few blog entries and publish them
- Navigate to **Site Builder** > **Pages**
- Create a new (Content) Page
- Drag and Drop an Asset Publisher widget and configure it display
  your collection
- Make sure you can view their usages

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Resent here: https://github.com/liferay-echo/liferay-portal/pull/3969 PR was perfect, just wanted to fix a minor thing that was already present :p

**Comment by julien** [comment]
@victorg1991 thanks, and good move, these migration PRs are perfect for these kind of things.

**Pull request closed without merging**
