### PR TITLE
LPS-118702 Check HTTP servlet request since item selector taglib has parameter without namespace

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by jpince** [comment]
Failure in `FileEntryInfoDisplayContributorTest.testDisplayPageURL` is also in common with upstream:
https://testray.liferay.com/home/-/testray/cases/863800678

**Comment by jpince** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
@pavel-savinov I did it manually, but the fix doesn't smell right.

Weird that modules/apps/item-selector/item-selector-taglib/ has no namespace

May be THAT is the bug...

**Comment by jpince** [comment]
ci:close

**Comment by jpince** [comment]
Brian merged https://github.com/brianchandotcom/liferay-portal/commit/34c7d09d10fb7dbd3744da0074f214b46facf048

**Pull request closed without merging**
