### PR TITLE
LPS-145606 Use numeric condition because some DBs don't have boolean type

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
Test GroupFinderTest.testFindByC_C_N_DJoinByActionId fails with `Invalid column name 'true'.`
https://liferay.atlassian.net/browse/LPS-145606

Proposed Solution
========
By using a numeric condition, this query will work on DBs that don't have a boolean type

Steps to Verify
========
1. Setup Liferay with an Oracle or an MSSQL
2. Open a terminal
3. Navigate to `modules/apps/site/site-test`
4. Run `gw testIntegration --tests GroupFinderTest.testFindByC_C_N_DJoinByActionId`

**Expected behaviour:** The test passes successfully
**Actual behaviour:** The test fails with `Invalid column name 'true'.`

References to existing code
========
I do recall seeing similar WHERE clauses somewhere else, but couldn't find them anymore for a pattern to copy.

### CODE REVIEW

**Comment by balazssk** [comment]
fixed i`s`Admin, thanks Jürgen

**Comment by balazssk** [comment]
ci:test:sf

**Comment by jkappler** [comment]
@balazssk, works great, tested it also in PostgreSQL, MS SQLServer and Oracle

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward:force

**Pull request closed without merging**
