### PR TITLE
[TS] [Urgent] LPS-191314  Navigation does not work while embedding Documents and Media portlet via Widget Template

### PR DESCRIPTION
**Pull request by mbowerman**
Motivation
=======
When trying to render an embedded portlet in a Widget Template, the original request parameters do not get propagated to the embedded portlet request. This causes some embedded portlets not to work properly. For example, folder navigation in an embedded Documents and Media portlet does not work correctly, because it is dependent on the `folderId` parameter, which does not get propagated to the embedded Documents and Media portlet.

Ticket: [LPS-191314](https://liferay.atlassian.net/browse/LPS-191314)

Proposed Solution
========
Use the `themeDisplay`'s request, rather than the modified httpServletRequest, when rendering the template, so that the original parameters are preserved. See [PTR-4103](https://liferay.atlassian.net/browse/PTR-4103), and especially Eric's detailed comment [here](https://liferay.atlassian.net/browse/PTR-4103?focusedCommentId=2178136), for more details about this solution.

Steps to Verify
========
1. Start up Liferay and log in as the admin user.
2. Navigate to Site > Templates > Widget Template > Plus Sign > Asset Publisher Template 
3. Name it “Test Template, then add the following code to the template and click Save:
```
 <@liferay_portlet["runtime"] portletName="com_liferay_document_library_web_portlet_DLPortlet"/> 
```
4. Create a new Widget Page an add an Asset Publisher portlet to it.
5. Click the Asset Publisher portlet’s Kebab Menu > Configuration > Display Settings > Display Template > Select “Test Template” and click Save.
6. Attempt to navigate inside the default “Provided by Liferay” folder.

**Expected Result:** The UI would display the contents of the folder.
**Actual Result:** Nothing changes at all. The user is still inside the root folder.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
