### PR TITLE
LPS 188394 Consider ERC when mapping to info items

### PR DESCRIPTION
**Pull request by sandrodw3**
## Context
This PR adapts the mapping logic so we have into account that sometimes we will have `externalReferenceCode` instead of `classPK`

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:forward

**Comment by rafaellajordao** [comment]
Hey @sandrodw3 ! I found a regression bug during the failure analysis related to this PR, here are the steps to reproduce it:

1. Create a web content
2. Create a blog entry
3. Go to Product Menu > Site Builder > Collections
4. Add a Dynamic Collection with All Types
5. Add a Manual Collection with All Types
6. Go to Product Menu > Site Builder > Pages
7. Add a content page
8. Add two Collection Display fragments
9. Try to place for each of them one of the collections created in steps 4 and 5
10. **Notice that the collection is repeated for both fragments**

Actual result:
it is not possible to set different collections for each fraction of the collection display

[ActualResult_Jun23_LPS188394.webm](https://github.com/liferay-echo/liferay-portal/assets/49991803/bbb901a0-d5ab-416a-8520-5d930fe61898)

Can you take a look?

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
