### PR TITLE
LPS-165509 Experience Selector

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-165509 Check if the experience belongs to the page
- LPS-165509 Don't add the parameter if the experience doesn't belong to the layout

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/132675

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
