### PR TITLE
[TS] LPS-202245 URLs for Embedded Page type is not being encoded properly

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

Motivation
=======
When a Page is configured with the Embedded template, the URL of the embedded page in the iFrame will be encoded.
For example,  the `&` character will be encoded as `&amp;`

and an URL like `www.google.com?embedded=true&userid=test` will be turned into `www.google.com?embedded=true&amp;userid=test` .

This does not pose a problem for internal URLs like `/group/guest/{etc}` , but if external URLs are encoded, the pages won’t load properly.

Proposed Solution
========
Using `HtmlUtil.escapeJS` instead of `HtmlUtil.escapeHREF` as it is sufficient in preventing script execution.

Steps to Verify
========
Please see the linked LPS for the reproduction steps.
https://liferay.atlassian.net/browse/LPS-202245

Thank you and best regards,
István

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
Perfect, thanks!

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
