### PR TITLE
LPS-150023 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-150023

This is only for master.

@DiegoHu97
@victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Hi @DiegoHu97, there is a regression issue.
The user has view resource permission cannot view the web content structure
**Step to reproduce**
1. Add a regular role with the following permissions
image
image
2. Add a new user
3. Assign the regular role to new user
4. Assign the new user to a new site
5. Add a web content structure
6. Sign in as new user
7. Navigate to the Web Content admin

Expected Results:
The new structure is visible to new user.

Actual Results:
The new structure is invisible to new user.

cc @victorg1991

**Comment by victorg1991** [comment]
Many thanks @Tim-Cao !! We'll take a look

**Comment by victorg1991** [comment]
resent here: https://github.com/liferay-echo/liferay-portal/pull/7622

**Pull request closed without merging**
