### PR TITLE
LPS-118486 Check that add child page option is allowed

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
@jbalsas could you please take a look at https://github.com/liferay-echo/liferay-portal/pull/1801/commits/a0ee1ec1e353f1833bc91754f9b6e5993a079676 ? Shouldn't break anything and it helps when items weren't added due to the condition, but the category was created(like "primaryItems" empty, etc.).
Thanks!

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
LGTM @pavel-savinov!

sealofapproval

**Comment by pavel-savinov** [comment]
ci:forward

**Pull request closed without merging**
