### PR TITLE
LPS-178311 No success message appears after publish a 404 error utility page

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://issues.liferay.com/browse/LPS-178311)

## Steps

1.  Enable the utility page
2. Add a new site
3. Add a new 404 error utility page
4. Add a Heading fragment
5. Publish
Screenshot 2023-03-17 at 10 13 20

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@DiegoHu97, @ealonso, shouldn't it be "The utility page" was published correctly? Not "The page" was published correctly?

**Comment by jkappler** [comment]
Hi @DiegoHu97, message should be "The utility page was successfully published" not "added". I closed the PR in BChan's queue

**Comment by jkappler** [comment]
thanks @DiegoHu97! ❤️

**Comment by jkappler** [comment]
ci:forward

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
@jkappler Updated! (again) 😄

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
Thanks @DiegoHu97 🥳!!!!

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
