### PR TITLE
LPS-150364 Move htmlTag to a more proper place in page definition

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
Hi
I have sent a pull request to solve the compilation issue, see this commit, and added a couple of source format minor fixes.
The backend part LGTM Great job! 👏 
I have let the On_Hold label because in my local tests I have checked that the desired HTML tag was present in EDIT mode but I wasn't able to find it in VIEW mode. I always found a DIV, no matter what I set in the HTML tag field.
Maybe be I didn't check it properly, please, could you double-check it?
Thanks!

**Comment by lfbesada** [comment]
See: https://github.com/liferay-echo/liferay-portal/pull/7655

**Pull request closed without merging**
