### PR TITLE
LPS-160026 Fix message when dropping an input in a unmapped form container

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
Hey @ozysouza,
Could you please manually forward it? Everything seems to be working fine see https://github.com/liferay-echo/liferay-portal/pull/9239#issuecomment-1208558433

**Comment by victorg1991** [comment]
sent this here: https://github.com/brianchandotcom/liferay-portal/pull/121423

**Pull request closed without merging**
