### PR TITLE
LPS-129599 Migrate getOpener usage to openSelectionModal in journal-web

### PR DESCRIPTION
**Pull request by kresimir-coko**
Hi team, I'm sending this PR that is a part of our ongoing migration over at [LPS-129246](https://issues.liferay.com/browse/LPS-129246).

There are 2 remaining usages of `Liferay.Util.getOpener().Liferay.fire()` that I didn't figure out how to remove due to it not being tied to a Search Container (cc @markocikos) inside [select_articles.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/item/selector/select_articles.jsp#L415-L424) and [SelectFolder.es.js](https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-web/src/main/resources/META-INF/resources/js/SelectFolder.es.js#L50-L55). We're probably not gonna be migrating those 2 for the time being 🤷 

# 🧪 Test case
## `select_article_translations.jsp` + `ElementsDefaultPropsTransformer.js`
1. Create a web content based on basic web content
2. Fill the title in several languages & publish
3. In the kebab menu of the items choose “Delete Translation”

## `view_more_menu_items.jsp` + `ManagementToolbarPropsTransformer.js`
1. Create 8+ Web Content Structures
2. Click + to add a new Web Content
3. Click on "More" button

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test

**Comment by kresimir-coko** [comment]
I found another usage, so putting this as a draft until I migrate that one too.

**Comment by kresimir-coko** [comment]
@victorg1991 Hey it's me again, I force-pushed the changes in the same commit, rebased with master and reopened the PR, so you can start working on it. I'll add the 2nd usage to test cases in the description right now.

**Comment by victorg1991** [comment]
Hey @kresimir-coko 

I've tested your changes and everything looked good 👏 

I've taken the opportunity to fix some unrelated problems I found and to clean up a bit the select_articles.jsp

Resent here: https://github.com/liferay-echo/liferay-portal/pull/4394

Just one question, is getOpener going to be deprecated/removed? Is fine for now to leave the usage in the SelectFolder.js file? :)

**Comment by kresimir-coko** [comment]
AFAIK `getOpener` is not getting deprecated yet. We are trying to remove custom events as part of this Epic, as they're mostly connected to modals and mostly easy to remove. So there shouldn't be any fear of keeping the `getOpener` inside `SelectFolder.js`. Correct me if I'm wrong @markocikos

**Comment by markocikos** [comment]
> is getOpener going to be deprecated/removed? Is fine for now to leave the usage in the SelectFolder.js file? :)

We will eventually deprecate and replace it, along with all other AUI-based utilities. But, it's not going to be soon, for now it's ok to leave the usage.

**Comment by victorg1991** [comment]
Thanks for the answers! :)

**Pull request closed without merging**
