### PR TITLE
LPS-147669 adding equals method needed for cache validation when result is empty

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @linolaoj,

Could you please take a look to previous comment and resend?

Regards,
Eudaldo.

**Comment by linolaoj** [comment]
Hi @lfbesada, @ealonso, sorry for the delay, we had a local holiday of a few days.
Here is the new pull request:
https://github.com/liferay-echo/liferay-portal/pull/7385
Please let me know if any other change is needed.

**Pull request closed without merging**
