### PR TITLE
LPS-179802 Those should be executed in a transaction

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso , there is a regression issue found.
When publish the content page, the following error is thrown
```
ERROR [http-nio-8080-exec-1][PortletServlet:118] Unable to process portlet com_liferay_layout_content_page_editor_web_internal_portlet_ContentPageEditorPortlet: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.OptimisticLockException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.liferay.portal.model.impl.LayoutImpl#18]
[beanshell] javax.portlet.PortletException: com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: javax.persistence.OptimisticLockException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.liferay.portal.model.impl.LayoutImpl#18]
[beanshell] 	at com.liferay.portal.kernel.portlet.bridges.mvc.BaseTransactionalMVCActionCommand.doProcessAction(BaseTransactionalMVCActionCommand.java:56) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCActionCommand.processAction(BaseMVCActionCommand.java:57) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.callActionMethod(MVCPortlet.java:402) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.portlet.LiferayPortlet.processAction(LiferayPortlet.java:83) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.processAction(MVCPortlet.java:256) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:77) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:50) ~[portal-kernel.jar:?]
[beanshell] 	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:114) ~[portal-kernel.jar:?]
[beanshell] 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:779) ~[servlet-api.jar:4.0.FR]
[beanshell] 	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
[beanshell] 	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:63) ~[?:?]
[beanshell] 	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
[beanshell] 	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
[beanshell] 	at com.liferay.portlet.internal.InvokerPortletImpl.invoke(InvokerPortletImpl.java:576) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.internal.InvokerPortletImpl.invokeAction(InvokerPortletImpl.java:616) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.internal.InvokerPortletImpl.processAction(InvokerPortletImpl.java:293) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.monitoring.internal.portlet.MonitoringInvokerPortlet.processAction(MonitoringInvokerPortlet.java:195) ~[?:?]
[beanshell] 	at com.liferay.portlet.internal.PortletContainerImpl._processAction(PortletContainerImpl.java:514) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.internal.PortletContainerImpl.lambda$processAction$0(PortletContainerImpl.java:148) ~[portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.internal.PortletContainerImpl._preserveGroupIds(PortletContainerImpl.java:421) [portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.internal.PortletContainerImpl.processAction(PortletContainerImpl.java:141) [portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.SecurityPortletContainerWrapper.processAction(SecurityPortletContainerWrapper.java:82) [portal-impl.jar:?]
[beanshell] 	at com.liferay.portlet.RestrictPortletContainerWrapper.processAction(RestrictPortletContainerWrapper.java:72) [portal-impl.jar:?]
[beanshell] 	at com.liferay.portal.kernel.portlet.PortletContainerUtil.processAction(PortletContainerUtil.java:117) [portal-kernel.jar:?]
```

**Pull request closed without merging**
