### PR TITLE
LPS-202505 Use custom drag preview for mouse DnD

### PR DESCRIPTION
**Pull request by alessandromalves**
https://liferay.atlassian.net/browse/LPS-202505

cc.: @sandrodw3 @veroglez @Tim-Cao

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by alessandromalves** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Resent based on https://github.com/liferay-echo/liferay-portal/pull/14537

**Comment by alessandromalves** [comment]
ci:forward:force

**Comment by alessandromalves** [comment]
The failures are not related to this PR [(see comparison with acceptance routine)](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1701218378745&testrayRunIdA=2466327409&testrayRunIdB=2467104709). See https://github.com/brianchandotcom/liferay-portal/pull/144541

**Pull request closed without merging**
