### PR TITLE
LPS-168270 Usage count for collection for asset libraries

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-168270)

This PR fixes an impedibug found when checking the story to show the usage count of collection in an asset library

## Change summary:

* Add a new finder so that we can retrieve the usage count of collection for a company
* Show the usage count for company in asset library
* Don't show the action for usage count when in asset libraries

## Test Scenario

* Add an asset library
* Create a collection in it
* Connect it to a site
* Use the collection in a site, can be through a collection display
* Go back to the asset library
* Usage count should be reflected

usages

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:stop

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/126129

**Pull request closed without merging**
