### PR TITLE
LPS-120935 - Internal categories are being shown by category navigation widgets

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
https://github.com/liferay-echo/liferay-portal/pull/2394

**Pull request closed without merging**
