### PR TITLE
LPS-167504 - Select buttons in the Category and Tag Selectors are being announced with the same name.

### PR DESCRIPTION
**Pull request by ethib137**
https://issues.liferay.com/browse/LPS-167504

 **Steps to Reproduce:**
1. Turn on JAWS > Open the URL.
2. Navigate to the Site Menu > Content & Data > Web Content.
3. Click the "+" to add a new Basic Web Content.
4. Press tab until you reach the Categories section of the sidebar.
5. Tab through each Select button.
6. Observe the JAWS.

 **Expected Result:**
Each select button should have a unique descriptive name.
For example:
"Select topic button
Opens a dialog
To activate press enter".

 **Actual Result:**
There are multiple select buttons on the page with same announcement by SR: ("select button").
This will confuse the SR users.

 

**How to fix, recommendation:**

Add additional aria properties:
aria-controls={selectionModalId}
aria-expanded={selectionModalOpen}
aria-haspopup="dialog"
aria-label="select-x"

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @ethib137 Label changes looks good!

Regarding the other aria attributes I have been checking it, and also ask Marcos about it and it seems that only the `aria-haspopup="dialog"` may be needed. `aria-expanded` I'm not sure about how it fits because I didn't find any information about the usage with modals and we don't use it elsewhere in the portal. `aria-controls` may be interesting but in this case won't work properly since the modal is only present when clicking the button the id used in aria-controls won't exist at first

What do you think? I would leave the label and the aria-haspopup changes and remove the other ones :)

**Comment by victorg1991** [comment]
I can make the changes needed if you wish :)

**Comment by ethib137** [comment]
Hey @victorg1991 thanks for your review. I added both aria-controls and aria-expanded based on the info here: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-expanded

From my reading it appears that these attributes can be applied to dialogs and there's no mention of the dialog needing to be in the dom for the aria-controls to be added. The only reason I could see that we might not use aria-expanded for this case is that the button does not act as a toggle since the main page content is inaccessible while the modal is open.

Either way aria-expanded and aria-controls are not as critical to the screen reader function, so I don't think it's problematic to remove them.

If you'd still like to make the change, I'd be more than happy to have you make it for me. Thanks. 😄

**Comment by victorg1991** [comment]
Nice @ethib137 I'll do the changes! :)

**Comment by victorg1991** [comment]
resent here: https://github.com/liferay-echo/liferay-portal/pull/10268

**Pull request closed without merging**
