### PR TITLE
[TS] LPS-129012 Use page's currentURL instead of portlet's currentURL

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,
If we are on a page defined by an asset's friendlyURL, this redirection will not redirect to the asset's friendlyURL, but to the asset publisher's friendlyURL.

Can you please review?
https://issues.liferay.com/browse/LPS-129012

Thanks,
Balázs

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by balazssk** [comment]
sorry @ruben-pulido ,
Looks like I somehow added double ; at the end of line. Will resend.

**Pull request closed without merging**
