### PR TITLE
LPS-119924 Some fragments don't have default value, this is the case for example in the home page

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Please give me some mins. This PR probably cause a regression issue.

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
Hi @victorg1991 and @p2kmgcl, your changes cause the following regression issue.
Run ContentPageConverter#ConvertWidgetPageWithNestedApplicationsContainingWidgets on local
The converted page is still at conversion draft after publish
Run DisplayPagesWithWebContent#PreviewDraftWebContent  on local
The display page template is still at draft after publish
This issue can not be reproducible manually.

**Comment by p2kmgcl** [comment]
:cry: thanks @Tim-Cao for checking that. I'll have a look :)

**Comment by victorg1991** [comment]
Thanks @Tim-Cao

**Comment by victorg1991** [comment]
ci:close

**Pull request closed without merging**
