### PR TITLE
LPS-128329 Build lang

### PR DESCRIPTION
**Pull request by adolfopa**
Hey @liferay-echo 

Slashes cannot be allowed in friendly URLs, as the display page friendly URL resolver assumes that the second component of an URL is the version ID (see BaseAssetDisplayPageFriendlyURLResolver#_getVersionClassPK)

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by dacousalr** [comment]
The solution proposed in this PR entails a severe breaking change to how this works or allows since 7.1 onward.

**Comment by adolfopa** [comment]
@dacousalr The thing is that friendly URLs with slashes don't work at all (see reproduction steps in the ticket), so the breaking change is already there, as things that worked previously won't work anymore. Allowing slashes will only make that content detail inaccessible when linked from portlets (e.g. asset publisher).

In any case, I don't mind if Echo team decides to keep things as they are. Feel free to discard this PR or the issue.

**Comment by tdemnati-star** [comment]
Hi,
As agreed with Adolfo we believe that "/" should be supported. 
and Echo team could resolve the issue by finding another mechanism to display the page using the Friendly URL. 

@liferay-echo could you please handle that ?

cc @dacousalr 

Thanks

**Comment by victorg1991** [comment]
Closing since we need to find another solution for the bug

**Pull request closed without merging**
