### PR TITLE
LPS-159751 NPE when editing content page of a child site based on a site template

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Failure cases are unrelated to changes

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121535

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
