### PR TITLE
LPS-115307 Refactor Experiences dropdown

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

This pull request is a refactor of the markdown from `ExperienceSelector`:

* Use `ClayLayout` for the `ExperiencesSelectorHeader` (cc: @marcoscv-work)
* Use `ClayList` for the list of experiences (cc: @marcoscv-work)
* Fix permissions (cc: @sandrodw3)
* Remove unnecessary CSS classes
* Adjust spaces between elements
* Fix `ExperimentsLabel` PropTypes
* Flip rendering between `ExperimentsLabel` and `ViewportSizeSelector` (cc: @p2kmgcl)
* Recover active style from `ExperienceToolbarSection.scss` (for the active experience)

**Module**

```
~/liferay-portal/modules/apps/layout/layout-content-page-editor-web
```

**Screenshots**

* **Before:**

Screenshot 2020-07-14 at 09 33 47

* **After:**

Screenshot 2020-07-14 at 19 45 52

### CODE REVIEW

**Comment by dgarciasarai** [comment]
Hey @liferay-echo, I send you this pull request because I updated the code from `layout-content-page-editor-web` module (although is the experiences part). Can you review it, please? Thanks! :)

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Hey @liferay-echo, I just rebased the pull request and added a new commit https://github.com/liferay-echo/liferay-portal/pull/1480/commits/398c02f56b55dfb3db6858cc209230147bf86110. Thanks.

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
Thanks @dgarciasarai 🙂

**Comment by p2kmgcl** [comment]
@dgarciasarai I love this PR :heart:

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
