### PR TITLE
LPS-205240 Don't do anything if the ff is enabled since this will be handled from other place

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:test:relevant

**Review by p2kmgcl — APPROVED** [review]

**Comment by p2kmgcl** [comment]
@victorg1991 nice! But SF failed :scream:

**Comment by BarbaraCabrera** [comment]
ci:test:stable

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/146178

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
