### PR TITLE
[Urgent] LPD-24264 ResultSet does not support calling by TableName.columnName in Oracle

### PR DESCRIPTION
**Pull request by javalosjr96**
Issue:
The main issue would be that any type of _get_ on a resultSet using  "tableName.columnName" will result in an invalid column error due to how Oracle handles the columns names when returning the query.

Solution:
In cases like these we can use the column's index in the resultSet so that it'll be compatible with across all databases.

Notes:
This was tested across all databases using a script.
The script used the same select query and would get the same columns.
I think a source formatter rule should be used to prevent cases like this.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
