### PR TITLE
LPD-35535 - First implementation of getting an existing widget page via Headless API

### PR DESCRIPTION
**Pull request by ruben-pulido**
https://liferay.atlassian.net/browse/LPD-35535 - First implementation of getting an existing widget page via Headless API

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
@ruben-pulido you need to run semantic versioning see https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/913503/

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
SF failure related to breaking changes fixed here: https://github.com/liferay-echo/liferay-portal/pull/16253

**Pull request closed without merging**
