### PR TITLE
LPS-130975 Clean page editor CSS

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
LGTM :) I believe we can also take the chance and 🔥 all unused CSS, what do you think? We can split the files to make it more bearable 😇

**Comment by sandrodw3** [comment]
> LGTM :) I believe we can also take the chance and 🔥 all unused CSS, what do you think? We can split the files to make it more bearable 😇

Ok! I think it's a good idea! 🙂
Let's pass this PR and I'll continue working on the same LPS.

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
