### PR TITLE
LPS-204954 - Cannot propagate changes from Site Template to Site when using Master Page

### PR DESCRIPTION
**Pull request by ruben-pulido**
This PR adds an integration test to the original PR: https://github.com/liferay-echo/liferay-portal/pull/14925

Original PR comment by @jonathanmccann:

https://liferay.atlassian.net/browse/LPS-204954

Previously submitted under https://github.com/liferay-echo/liferay-portal/pull/14902 @ruben-pulido. Resending due to a few issues caught by @jorgediaz-lr.

The changes from the previous pull are:

1. Using a parameter to set the boolean for `privateLayout` instead of hard coded `0` and `1` due to differences in databases
2. Updating the layout's `layoutId` to avoid a potential conflict in the case of private pages existing in the site
3. Additionally updating the `LayoutFriendlyURL` table to reflect the change from public to private

If there are any questions or concerns please let me know.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:upgrade

**Comment by Tim-Cao** [comment]
ci:report:2492016766

**Comment by Tim-Cao** [comment]
Hi @ruben-pulido, the issue still happens on this pr.
[data-archive-virtual-instances-postgresql.zip](https://github.com/liferay-echo/liferay-portal/files/13985346/data-archive-virtual-instances-postgresql.zip)
```
     [java] 2024-01-18 11:50:27.049 INFO  [main][UpgradeProcess:137] Failed upgrade process com.liferay.layout.internal.upgrade.v1_4_2.LayoutUpgradeProcess in 2 ms
     [java] 2024-01-18 11:50:27.051 ERROR [main][UpgradeExecutor:333] Failed upgrade process for module com.liferay.layout.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: org.postgresql.util.PSQLException: ERROR: relation "layoutpagetemplateentry" does not exist
     [java]   Position: 90
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:128) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor._executeUpgradeInfos(UpgradeExecutor.java:202) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.executeUpgradeInfos(UpgradeExecutor.java:124) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.execute(UpgradeExecutor.java:85) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeExecutor.java:330) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeExecutor.java:290) ~[?:?]
     [java] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$DefaultEmitter.emit(ServiceTrackerMapImpl.java:200) ~[com.liferay.osgi.service.tracker.collections.jar:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.lambda$activate$0(UpgradeExecutor.java:179) ~[?:?]
     [java] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerMapImpl.java:256) [com.liferay.osgi.service.tracker.collections.jar:?]
     [java] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerMapImpl.java:244) [com.liferay.osgi.service.tracker.collections.jar:?]
     [java] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943) [org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1) [org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) [org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) [org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:893) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:799) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:125) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:224) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:461) [org.eclipse.osgi.jar:?]
     [java] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:906) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:892) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:128) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:962) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:732) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1053) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1007) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1216) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1137) [bundleFile:?]
```

**Comment by ruben-pulido** [comment]
Thanks for the heads up @Tim-Cao!

Now the failure does seem related to the Upgrade process introduced in the PR.

@jonathanmccann Can you take a look?
Thanks!

**Comment by jonathanmccann** [comment]
@ruben-pulido @Tim-Cao I wasn't able to reproduce the failure locally on Postgres 9.5. I'm not sure if the test is performing some different steps though (upgrading from an older version, etc.) Here is the log of the successful upgrade:

```
2024-01-19 18:20:42.226 INFO  [main][DialectDetector:144] Using dialect org.hibernate.dialect.PostgreSQL95Dialect for PostgreSQL 9.5
2024-01-19 18:20:43.992 INFO  [main][ModuleFrameworkImpl:1352] Starting initial bundles
2024-01-19 18:20:44.270 INFO  [SystemExecutorServiceUtil-6][InterpolationConfigurationPlugin:109] Configured directory for secrets: /home/jonathan/deploy/master/osgi/configs
2024-01-19 18:20:44.525 INFO  [main][ModuleFrameworkImpl:1642] Started initial bundles
2024-01-19 18:20:44.525 INFO  [main][ModuleFrameworkImpl:1687] Starting dynamic bundles
2024-01-19 18:20:47.335 WARN  [Start Level: Equinox Container: e030ba5c-bd78-4c2f-aad4-329b965dadce][SidecarManager:72] Liferay automatically starts a child process of Elasticsearch named sidecar for convenient development and demonstration purposes. Do NOT use sidecar in production. Refer to the documentation for details on the limitations of sidecar and instructions on configuring a remote Elasticsearch connection in the Control Panel.
2024-01-19 18:20:49.679 INFO  [main][ModuleFrameworkImpl:1710] Started dynamic bundles
2024-01-19 18:20:49.679 INFO  [main][ModuleFrameworkImpl:1717] Starting web bundles
2024-01-19 18:20:52.922 INFO  [main][ModuleFrameworkImpl:1771] Started web bundles
2024-01-19 18:20:52.922 INFO  [main][ModuleFrameworkImpl:283] Navigate to Control Panel > System > Gogo Shell and enter "lb" to see all bundles
2024-01-19 18:20:58.327 INFO  [main][StartupHelperUtil:96] There are no patches installed
2024-01-19 18:20:58.337 INFO  [main][LoggingTimer:74] Starting com.liferay.portal.verify.VerifyProperties#verifySystemProperties
2024-01-19 18:20:58.338 INFO  [main][LoggingTimer:35] Completed com.liferay.portal.verify.VerifyProperties#verifySystemProperties in 1 ms
2024-01-19 18:20:58.339 INFO  [main][LoggingTimer:74] Starting com.liferay.portal.verify.VerifyProperties#verifyPortalProperties
2024-01-19 18:20:58.357 INFO  [main][LoggingTimer:35] Completed com.liferay.portal.verify.VerifyProperties#verifyPortalProperties in 19 ms
2024-01-19 18:20:59.222 INFO  [main][LoggingTimer:74] Starting com.liferay.portal.events.StartupHelperUtil#initResourceActions
2024-01-19 18:20:59.340 INFO  [main][LoggingTimer:35] Completed com.liferay.portal.events.StartupHelperUtil#initResourceActions in 118 ms
2024-01-19 18:21:04.319 INFO  [SystemExecutorServiceUtil-3][Sidecar:101] Sidecar Elasticsearch liferay started at 127.0.0.1:9201
2024-01-19 18:21:18.756 INFO  [main][UpgradeProcess:119] Upgrading com.liferay.layout.internal.upgrade.v1_4_2.LayoutUpgradeProcess
2024-01-19 18:21:18.757 INFO  [main][LoggingTimer:74] Starting com.liferay.layout.internal.upgrade.v1_4_2.LayoutUpgradeProcess#doUpgrade
2024-01-19 18:21:38.361 INFO  [main][LoggingTimer:35] Completed com.liferay.layout.internal.upgrade.v1_4_2.LayoutUpgradeProcess#doUpgrade in 19604 ms
2024-01-19 18:21:38.362 INFO  [main][UpgradeProcess:137] Completed upgrade process com.liferay.layout.internal.upgrade.v1_4_2.LayoutUpgradeProcess in 19615 ms
2024-01-19 18:21:38.382 INFO  [main][LoggingTimer:74] Starting com.liferay.portal.db.index.IndexUpdaterUtil#updateIndexes#Updating database indexes for com.liferay.layout.service
2024-01-19 18:21:38.404 INFO  [main][LoggingTimer:35] Completed com.liferay.portal.db.index.IndexUpdaterUtil#updateIndexes#Updating database indexes for com.liferay.layout.service in 21 ms
2024-01-19 18:21:39.695 INFO  [main][LoggingTimer:74] Starting com.liferay.portal.db.index.IndexUpdaterUtil#updateAllIndexes#Updating database indexes
2024-01-19 18:21:40.067 INFO  [main][LoggingTimer:35] Completed com.liferay.portal.db.index.IndexUpdaterUtil#updateAllIndexes#Updating database indexes in 372 ms
2024-01-19 18:21:44.265 INFO  [main][UpgradeRecorder:154] Micro upgrade finished with result success

Completed Liferay upgrade process in 60 seconds
```
I'm not sure how to proceed from here but let me know if there are other tests I can perform.

**Comment by Tim-Cao** [comment]
ci:test:bundle

**Comment by Tim-Cao** [comment]
ci:test:upgrade

**Comment by Tim-Cao** [comment]
ci:report:2504054335

**Comment by Tim-Cao** [comment]
ci:test:upgrade

**Comment by Tim-Cao** [comment]
ci:report:2504054335

**Comment by Tim-Cao** [comment]
Hi @ruben-pulido and @jonathanmccann, I cannot reproduce it on my local. It seems like a ci-only issue also happens on other prs. We could ignore it. Sorry for bother you.

**Comment by Tim-Cao** [comment]
ci:report:2491593629

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/146438

**Comment by Tim-Cao** [comment]
ci:close

**Comment by ruben-pulido** [comment]
Thanks a lot for checking @Tim-Cao !

**Pull request closed without merging**
