### PR TITLE
LPS-150023 Group options in journal article history

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
Hey @Tim-Cao Would you mind taking a look at these failures, please? We've changed the component used for the Web Content Structure actions, so the markup may be changed a bit 

Many thanks!!

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7619

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
