### PR TITLE
LPS-131407 Set asset publisher default option to collection | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-131407

This is only for master.

@victorg1991
cc @lfbesada

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Thanks @Tim-Cao 😍

**Comment by Tim-Cao** [comment]
Hi @victorg1991, the testray is down. I cannot analyze the results at the moment.

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
Hi @victorg1991, there are regression issues.
The Most Viewed Assets, Highest Rated Assets and Related Assets don't have asset selection section, shouldn't they keep the old behavior? Could you have a look at? Thanks

**Comment by victorg1991** [comment]
Hey @Tim-Cao 

> The Most Viewed Assets, Highest Rated Assets and Related Assets don't have asset selection section, shouldn't they keep the old behavior?

I think so yea, let me take a look at those

> The asset selection of Asset Publisher will be changed to Collection automatically after upgrade. Shouldn't keep dynamic until user change it?

I don't think this is a problem. It only happens when you have asset publishers without changing any of the configuration, right? Having an asset publisher with 0 configuration isn't a very common use case.

**Comment by Tim-Cao** [comment]
Hi @victorg1991, 

> I don't think this is a problem. It only happens when you have asset publishers without changing any of the configuration, right? Having an asset publisher with 0 configuration isn't a very common use case.

I checked the failing cases, those Asset Publisher didn't change any configuration before upgrade.
Is that possible don't change to Collection after upgrade?

**Comment by victorg1991** [comment]
> I checked the failing cases, those Asset Publisher didn't change any configuration before upgrade.
Is that possible don't change to Collection after upgrade?

I don't think so, we can do an upgrade proccess to make sure that the default dynamic is added, but as I mention this isn't a common use case, an asset publisher without configuration isn't very useful...

**Comment by victorg1991** [comment]
Do we have a test that cover that upgrade? We may need to update it then, and set the configuration to dynamic

**Comment by victorg1991** [comment]
Btw updated the preferences of the portlets that you mentioned. I've resent it here: https://github.com/liferay-echo/liferay-portal/pull/7367

**Pull request closed without merging**
