### PR TITLE
LPS-114729 Remaining renames (2nd try after rebasing)

### PR DESCRIPTION
**Pull request by JorgeFerrer**
@ealonso @4lejandrito @adolfopa

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:forward

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
@adolfopa, @ealonso, @JorgeFerrer, I'll take care of this.

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/1172.

**Comment by 4lejandrito** [comment]
ci:close

**Comment by JorgeFerrer** [comment]
Resent as https://github.com/liferay-echo/liferay-portal/pull/1172

**Pull request closed without merging**
