### PR TITLE
LPS-196125 Standardize the text to Make a Copy through the product

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-196125)

## Notes

This pr should be merge after https://github.com/liferay-echo/liferay-portal/pull/13676 due to changes related to Display Page Templates

### Display Page Templates
Pasted Graphic

### Master Pages
Pasted Graphic 1

### Information Templates
Pasted Graphic 2

### Widget Templates
Pasted Graphic 3

### Fragment 
Pasted Graphic 4

### Style Book
Pasted Graphic 5

### Page
image

### Utility Pages
image

### Forms
Pasted Graphic 8

### Web Content
Pasted Graphic 9
Pasted Graphic 10
Pasted Graphic 11

### Wiki
Pasted Graphic 12

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/13688

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
