### PR TITLE
LPS-131993 Skip verticalAlignment if it is null

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl and @ealonso, cannot set up Vertical Alignment of Grid.
The Default is always selected whatever you select.

**Comment by p2kmgcl** [comment]
Checking :sweat_smile:

**Comment by Tim-Cao** [comment]
Hi @ealonso and @p2kmgcl, the second issue is fragment composition is invisible when add it to page.
Step to reproduce
Add a content page
Add a Container
Add a Heading into Container
Save as Fragment
Add the fragment composition to page

Expected Results:
The new fragment composition should be shown on page.

Actual Results:
The new fragment composition is not shown on page.

**Comment by Tim-Cao** [comment]
Hi @ealonso and @p2kmgcl, the third issue is cannot import master page with Container.
Step to reproduce
Add a master page
Add a Container to master page
Publish Master
Export the master page
Delete the master page
Import the exported zip file

Expected Results:
The master should be imported successfully.

Actual Results:
The import failed. Even though the common success message shown, but the specific error message shown in modal
```
No page template could be imported.
master-pages/master/master-page.json could not be imported because its page definition is invalid.
```

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/4928

**Pull request closed without merging**
