### PR TITLE
LPS-138565 Widget pages doesn't have structure so do nothing here

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @victorg1991,

Why we are calling LayoutCopyHelperImpl.java for portlet pages?

**Comment by victorg1991** [comment]
HEy @ealonso 

We are doing a bunch of other stuff in this class that applies also to widget pages:

Screenshot 2021-09-03 at 09 09 41

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @victorg1991, LayoutCopyHelperTest.testCopyContentLayoutStructure is failure could you review it?

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
@Tim-Cao reviewed and fixed! Thanks!!

**Comment by ealonso** [comment]
ci:reevaluate:1317401_212

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The failure are unrelated to this PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/106685

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
