### PR TITLE
LPS-165392 | [HR_131,150] Make the pages have only one and descriptive h1 tag

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
ci:test:sf

**Comment by ozysouza** [comment]
ci:test:relevant

**Comment by rebsilva** [comment]
Hi @ozysouza and @veroglez! Just for some context, some tests have been failing on relevant that aren't related to this PR; it seems like they are unstable and are already failing on master too. I've discussed this on a thread on slack with the brazilian QA team and we think that the kaleo forms tests were some of the few related. If you need further help to investigate this please let me know, I'll be happy to help you! Thanks!

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/124863

**Comment by ozysouza** [comment]
ci:close

**Pull request closed without merging**
