### PR TITLE
LRQA-73533 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRQA-73533

This is only for master.

@david-gutierrez-mesa
cc @sandrodw3

Would you mind review the [javascript codes](https://github.com/liferay-echo/liferay-portal/commit/248e96bb082c940f7d8201f36a06b50a7519a540) and [groovy script](https://github.com/liferay-echo/liferay-portal/commit/dd0b06bffe096b7810e5cb894dff14431a12e191)?

Additionally, Here is the logic of WaitForPageLoad function
Original
```
		var javaScript = '''
			return document.readyState === "complete";
		''';

		Condition javaScriptCondition = getJavaScriptCondition(
			javaScript, message, argument);

		javaScriptCondition.waitFor("false");
```

Modified
```
	function waitForPageLoad {
		if (!(isSet(locator1))) {
			var locator1 = "0";
		}

		var javascript = '''
window.onload = function() {
	setTimeout(() => {
		console.log("Page is fully loaded");
	}, "${locator1}");
};
		''';

		selenium.runScript("${javascript}");
	}
```

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
Hi @Tim-Cao 🥰
Code looks good to me. I only would change `var` variables to `const`, as they are not being changed.
I also would align the code the way below, so it's more readable.

image

**Comment by sandrodw3** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7398

**Pull request closed without merging**
