### PR TITLE
LPS-186991 Fix incorrect behaviors of Structures filter

### PR DESCRIPTION
**Pull request by mbowerman**
Motivation
=======
The expected behavior of the Structures filter is that it would return all articles matching the structure in both the current folder _and all its descendants_. The reasoning behind this was to make it consistent with the other filters in the "FILTER BY NAVIGATION" menu, which function the same way (returning matching articles in both the current folder and its descendants). This behavior has been clearly defined on both [LPS-141474](https://issues.liferay.com/browse/LPS-141474) and [PTR-2706](https://issues.liferay.com/browse/PTR-2706).

However, currently, this expected behavior is not being met. Currently, only the articles within the current folder are being returned. Articles in the current folder's descendants are NOT being returned. This pull request aims to resolve that.

While I was testing this, I discovered a related bug, which is that when you click the "x" on the "Structures: [Structure Name]" level, the page does not change at all. The expected behavior is that it would restore the original folder view. This does not happen; nothing changes. So I fixed that as well (see ba92b6c5ecc65184a4943e65c7c0a349b86614e9)

See more details on [LPS-186991](https://issues.liferay.com/browse/LPS-186991)

Proposed Solution
========
To fix the first problem, I passed in the folderIds of both the current folder and all its descendants into the `filterFindByG_F_C_S_L` method, as opposed to only passing in the folderId of the current folder. Except in the case that the folder is the root folder, then I made us pass in an empty list, since that removes the folderId check entirely (since all folders are descendants of the root, so we want to return all matching web contents in the group regardless of folder).

To fix the second problem, I removed the "ddmStructureId" parameter of the "removeLabelURL", since its existence in the URL was causing the "Filter by Structures" screen to still be displayed.

Steps to Verify
========
1. Go to Content & Data -> Web Content -> Structure (tab).
2. Create a new structure "ST-Test" with any field.
3. Go to Content & Data -> Web Content -> Web Content (tab).
4. Create a new Web Content "ST-Parent" based on "ST-Test" .
5. Create a new folder "F-Child".
6. Inside "F-Child", new Web Content "ST-Child" based on "ST-Test" and create a new folder "F-GrandChild".
7. Inside "F-GrandChild", create a new Web Content "ST-GrandChild" based on "ST-Test".
8. Move to "F-Child", filter by structure and select "ST-Test".

 Expected Result: Works as the other filters by navigation, showing results in cascade (ST-Child, ST-GrandChild)
 Actual Result: Shows only ST-Child

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
I have added the On-Hold label because of: https://liferay.slack.com/archives/G03LYN0J8/p1686200197746739

**Comment by mbowerman** [comment]
Hello @lfbesada, I cannot seem to visit your Slack link. Is it in a private channel?

**Comment by lfbesada** [comment]
Hi @mbowerman 

This is our team's private channel 😅 Please, contact Mateo Hermosin to talk about it, I am following its indications.

Regards

**Comment by ealonso** [comment]
Hey @mbowerman,

It is the expected behavior. So, closing it for the moment. I added a comment in jira ticket.

**Pull request closed without merging**
