### PR TITLE
LPS-176671 Replace alert divs with clay:alert taglib in layout-admin-web

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-176671)

For the _9a0b6f127809590d0336c1abe9159a32e1b001de_ this is the result:
 
image

I've changed the appearance of the button for a better fit with the clay style.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by claraizquierdo — APPROVED** [review]
LGTM 🎉

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/12765

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
