### PR TITLE
LPS-206080 The predefined content is not shown in web content

### PR DESCRIPTION
**Pull request by jkappler**
https://liferay.atlassian.net/browse/LPS-206080

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
@ealonso

**Comment by ealonso** [comment]
@JavierMoral I think we also need this one

**Comment by JavierMoral** [comment]
:+1:  @ealonso thank you for the heads up

**Review by lfbesada — APPROVED** [review]
It works like a charm, thanks :kissing_heart:

**Comment by jkappler** [comment]
@Tim-Cao, I think we need to change some poshi tests right?

**Comment by Tim-Cao** [comment]
Those failures are related to changes. @jkappler

**Comment by Tim-Cao** [comment]
ci:forward:force

**Comment by jkappler** [comment]
Thanks a lot as always @Tim-Cao!!!!

**Pull request closed without merging**
