### PR TITLE
LPS-146807 Change scheduled filter's label

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-146807

cc: @mbowerman @javalosjr96

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:test:relavant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @Tim-Cao @david-gutierrez-mesa , 
I have added a commit to update the "Scheduled" status filter label that this PR changes to "With Scheduled Versions". Please, could you check if my change is correct?
Thanks a lot! :heart:

**Comment by Tim-Cao** [comment]
Well done! @lfbesada. LGTM!

**Comment by ealonso** [comment]
ci:reevaluate:1367401_501

**Comment by ealonso** [comment]
ci:reevaluate:1267401_1797

**Comment by ealonso** [comment]
ci:reevaluate:1267401_1797

**Comment by ealonso** [comment]
ci:reevaluate:1267401_1797

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113539

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
