### PR TITLE
LPS-164924 baseline

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
@ealonso there are some regression issues, coudl you please have a look at?

The failures on these integration tests seems to be related.
com.liferay.layout.taglib.test.RenderLayoutStructureTagTest
com.liferay.layout.search.test.LayoutPublishedSearchTest
com.liferay.layout.crawler.test.LayoutCrawlerTest
com.liferay.layout.content.page.editor.web.internal.portlet.action.test.PublishLayoutMVCActionCommandTest
com.liferay.layout.type.controller.content.internal.layout.type.controller.test.ContentLayoutTypeControllerTest

**First regression** 

1. Navigate to Liferay DXP Site and Enable staging

There is an error on console and UI.

`2022-10-06 16:49:43.745 ERROR [liferay/background_task-4][BatchingBatch:134] HHH000315: Exception executing batch [java.sql.BatchUpdateException: integrity constraint violation: unique constraint or index violation: IX_9336DDD], SQL: insert into LayoutLocalization (mvccVersion, ctCollectionId, uuid_, groupId, companyId, createDate, modifiedDate, content, languageId, plid, lastPublishDate, layoutLocalizationId) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
2022-10-06 16:49:43.746 ERROR [liferay/background_task-4][SqlExceptionHelper:142] integrity constraint violation: unique constraint or index violation: IX_9336DDD
2022-10-06 16:49:43.756 ERROR [liferay/background_task-4][LoggerExportImportLifecycleListener:399] Staged model {class: com.liferay.layout.model.LayoutLocalization, uuid: f4cc787b-315d-c1ae-598c-a04eeda90850} import failed
javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute batch
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:154) ~[hibernate-core.jar:5.6.7.Final]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:181) ~[hibernate-core.jar:5.6.7.Final]
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:188) ~[hibernate-core.jar:5.6.7.Final]
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1411) ~[hibernate-core.jar:5.6.7.Final]
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1394) ~[hibernate-core.jar:5.6.7.Final]
	at com.liferay.portal.spring.hibernate.PortletTransactionManager$TransactionStatusWrapper.reset(PortletTransactionManager.java:283) ~[portal-impl.jar:?]`
	
	
**Second regression**

1. Add a site template
2. Add a widget page to site template
3. Add a new site based on site template

The pages from site template are not shown

**Third regression**

1. Add a new site template and disable Ready for Propagation
2. Add a new site based on site template and view Home page
3. Navigate to site template
4. Add an Asset Publisher to Home page and selecy Dynamic Collection
5. Publish Home page
6. Navigate to Product Menu -> Configuration -> Site Template Settings and enable Ready for Propagation
7. Navigate to newly created site
8. View Home page

The AP should be propagated to page

https://user-images.githubusercontent.com/72820234/194400426-a679207f-2524-42f1-a020-17e9beceb424.mp4


**Fourth regression**

1. Add a web content
10. Add a Collection Display to content page
11. Select Most Viewed Assets in Collection Providers
12. Add a Heading fragment to collection display and map it to Title
13. Add an Asset Publisher to page
14. Select Dynamic Collection and enable View Count Increment on AP
15. Add a Paragraph fragment to collection display and map it to View Count
16. Publish the page
17. Navigate to page at view mode
18. Click on the Web Content Title on AP and click on back icon
19. View the count number

The count number jumped to 14

https://user-images.githubusercontent.com/72820234/194397944-6119f915-b3f5-4c0d-8af2-0aac6b639b0a.mp4

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
@ealonso there is just the issue related to the count number jumped to 14 instead of 1.

**Comment by ealonso** [comment]
@ozysouza it is because we are rendering the content 14 times each one per each language that we support, 🤦🏾

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, there is a regression issue found by automation case.
The view count is wrong.
**Steps to reproduce** 
1. Add three web contents
2. Add a Collection Display to a cosntent page
3. Select the Most Viewed Assets in Collection Display
4. Add two Heading fragments into Collection Display
5. One is mapping to Title field, another one is mapping to View Count field
6. Add an Asset Publisher below the Collection Display
7. Change the asset selection to dynamic 
8. Publsih the content page
9. Navigate to the content page at view mode
10. Navigate to the any web content detail pages via Asset Publisher
11. Back to list page

**Expected Results:**
The view count should be 1.

**Actual Results:**
The view count is 14.

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
@ealonso, seems like the count isse was resolved :tada: :tada:
I will analyze the report and whether this last attempt doesn't work I'll manually send it.

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/124627

**Pull request closed without merging**
