### PR TITLE
LPS-130145 Take into account the ddm structure key, since it is the subtype for some entities

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @jkappler,

Could you please take a look at it 30492f2? I don't like it so much, but I don't know how to filter the values by item sub type without this logic.

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/4234

**Pull request closed without merging**
