### PR TITLE
LPS-125615 Remove background color from inner container

### PR DESCRIPTION
**Pull request by achaparro**
Notes from @kevhlee

> Ticket:
> https://issues.liferay.com/browse/LPS-125615
> 
> Notes:
> The goal of this fix is to preserve the full-width container styling from previous DXP versions during upgrades. The fix is based on the workaround discussed in the following Slack thread: https://liferay.slack.com/archives/CL9RTSZ52/p1610074901031100. The fix works by surrounding the container encompassing the content with a new, fluid-width container, which will be used to hold the background color and image.
> 
> So, we have the following in 7.2:
> 
> Section (fixed-width, background color)
> └── Content
> Then the upgrade needs to change the structure to the following to preserve full-width:
> 
> Container (background color, fluid)
> └── Container (fixed-width)
>     └── Content
> Let me know if you have any questions/concerns.

@kevhlee @samziemer

### CODE REVIEW

**Comment by achaparro** [comment]
ci:test:sf

**Comment by achaparro** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Thanks for the fix @kevhlee and @achaparro!

Sent to Brian [here](https://github.com/liferay-echo/liferay-portal/pull/3618)

**Pull request closed without merging**
