### PR TITLE
LPS-190962 Web content admin search Filter by Status doesn't work properly when Index all Versions is disabled

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-190962

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @lfbesada, could you check this failed integration tests?
[PortalLogAssertorTest-modules-integration-mysql57-jdk8/0/2](https://testray.liferay.com/home/-/testray/case_results/2388496019)

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
Hi @Tim-Cao 

Thanks for reviewing it! ❤️ 

I have launched the ci:forward again because I think it is not related to this PR since I have been able to reproduce the failure of that test in the current master.

Thank you so much!

**Comment by Tim-Cao** [comment]
Thanks for your checking @lfbesada

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/138123

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
