### PR TITLE
LPS-189601 Adapt front-end to use ClayPanel and clean css

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
The motivation behind this ticket is to clean some css code related to the segments editor since now the ClayPanel component is being used.
https://liferay.atlassian.net/browse/LPS-189601

Proposed Solution
========
The proposed solution consists in removing some of the css code that can be replaced with clay utilities.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:forward

**Comment by Stephy6** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward:force

**Pull request closed without merging**
