### PR TITLE
[TS] LPS-133146

### PR DESCRIPTION
**Pull request by jonathanmccann**
Sending this through the Echo team due to discussion on https://issues.liferay.com/browse/PTR-2459

From @noornajj

> https://issues.liferay.com/browse/LPS-133146
> 
> The issue here was that after removing a language from site settings, an article's content translation was retained when the web content is updated. 
> To fix the issue, I had the ddmFormValues return only the locales that are currently available in the site.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@jonathanmccann, could you please sent this to the DDM Team?

Thanks!

**Comment by jonathanmccann** [comment]
https://github.com/liferay-data-engine/liferay-portal/pull/484

**Pull request closed without merging**
