### PR TITLE
LPS-129536 We can check with this method and cover display pages and collection pages too

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
@linolaoj

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
resend: https://github.com/liferay-echo/liferay-portal/pull/4147

**Pull request closed without merging**
