### PR TITLE
LPS-134065

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1890#issuecomment-858530311

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by marianoalvarosaiz** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Thanks for the fix @marianoalvarosaiz 
Forwarding to Brian

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
