### PR TITLE
LPS-205100 Hide Permissions option in sidebar for Web Content

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-205100)

### Changes

Hide the "Permissions" option from the sidebar for Web Content when the FF is active.

>[!NOTE]
>You should activate the FF: LPS-198959

## Test scenario 1

1. Go to Content & Data > Web Content.
2. Check if the Permission options appears in the sidebar.

## Results

image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by BarbaraCabrera** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward:force

**Pull request closed without merging**
