### PR TITLE
LPS-179488 Create tabs for Javascript and CSS sections

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://issues.liferay.com/browse/LPS-179488)

## Steps
**Layout**

1. Go to Site Builder > Pages
2. Enter Home page
3. In the left side of the editor panel > Page Design Options 
4. Click configure icon
Screenshot 2023-03-30 at 15 47 22
Screenshot 2023-03-30 at 15 47 35

**Layout set**
1. Go to Site Builder > Pages
2. On the right upper site, click on he three dots kebab > configuration
Screenshot 2023-03-30 at 15 48 50

Screenshot 2023-03-30 at 15 49 05

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:forward

**Comment by DiegoHu97** [comment]
This PR is on hold as it is based on  https://github.com/liferay-echo/liferay-portal/pull/11616, and it has regression issue, so  we will wait until this one is solved.

**Comment by DiegoHu97** [comment]
ci:test:sf

**Pull request closed without merging**
