### PR TITLE
LPS-112247 Rename ExportHelper to LayoutPageTemplatesExporter, and move to corresponding package

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@ruben-pulido

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by jpince** [comment]
@vicnate5 can you ask the team if they can work on this type of error? Or at least have CII track data for this kind of error so the team has data on the frequency of occurrence.
`Duplicate entry 'com.liferay.portal.repository.portletrepository.PortletRepositor' for key 'IX_B27A301F'`

**Comment by vicnate5** [comment]
@jpince I have been watching this and we know the reason for the issue, the team is working on a fix this week.

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jpince** [comment]
@vicnate5 failure in `ViewPortalSmokeArchiveAutoUpgrade7210`, see results from the [GitHub comment at April 27 6:54 PM](https://github.com/liferay-echo/liferay-portal/pull/426#issuecomment-620329992). Couldn't find an open ticket for this.
```
LIFERAY_ERROR: Data truncation: Data too long for column 'key_' at row 1
LIFERAY_ERROR: Unable to execute background task
```
Same error here: https://github.com/hhuijser/liferay-portal/pull/4173#issuecomment-620407161

**Comment by jpince** [comment]
ci:forward

**Comment by jkappler** [comment]
Thanks @jpince!

**Comment by jpince** [comment]
@kenjiheigel @david-gutierrez-mesa failed to initiate a new portal instance on retry
```
     [exec]     Retrying test attempt 1 of 1
     [exec] 
     [exec]     ###
     [exec]     ### LocalFile.CPSitetemplates#OnlySiteAdminCanModifyPageAssociatedWithSiteTemplate
...
     [exec] com.liferay.poshi.runner.PoshiRunner > test[LocalFile.CPSitetemplates#OnlySiteAdminCanModifyPageAssociatedWithSiteTemplate] STANDARD_OUT
     [exec]     LIFERAY_ERROR: com.liferay.portal.kernel.events.ActionException: java.lang.NullPointerException
     [exec]     LIFERAY_ERROR: User ID null
     [exec]     LIFERAY_ERROR: Current URL /web/guest
     [exec]     LIFERAY_ERROR: com.liferay.portal.kernel.events.ActionException: java.lang.NullPointerException
     [exec]     LIFERAY_ERROR: Unable to register portal instance {mvccVersion=1, companyId=44034, accountId=44038, webId=cloud-10-0-13-145.lax.liferay.com, mx=liferay.com, homeURL=, logoId=0, system=false, maxUsers=0, active=true}
```

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:reopen

**Pull request closed without merging**
