### PR TITLE
LPS-137856

### PR DESCRIPTION
**Pull request by mbowerman**
Hi Echo Team,

We are resubmitting this fix because we could not get the regression bugs to occur.

Notes from @javalosjr96:

> Previous fix was rebased to a more recent version of master to try to get the regression bugs to occur.
> Both LPS-138269 and LPS-138244 failed to occur.
> Resubmitting original fix.

/cc @javalosjr96

https://issues.liferay.com/browse/LPS-137856

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:echo

**Comment by ealonso** [comment]
ci:test:echo

**Comment by javalosjr96** [comment]
Hi @ealonso,
Can I get an update on this?

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
@javalosjr96 please see https://github.com/liferay-echo/liferay-portal/pull/5944

**Pull request closed without merging**
