### PR TITLE
LPS-142664 Auto

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:test:relevant

**Comment by guilhermedcamacho** [comment]
ci:forward

**Comment by guilhermedcamacho** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/6691

**Pull request closed without merging**
