### PR TITLE
LPS-194610 and LPS-194406

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-194610
https://liferay.atlassian.net/browse/LPS-194406

Dear reviewer 
This PR adds a scheduled task to unlock layouts. That task should work with an instance-scoped configurable interval, but in this PR that configuration doesn't work, the interval used is always the default (15 minutes).
Apparently, it's an infrastructure limitation, the cron interval seems to only be configurable at the system level. I have asked the component owner team to clarify this: https://liferay.slack.com/archives/C01FP01V5L0/p1693398158005989

cc: @jkappler Thanks! :heart:

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
