### PR TITLE
 LPS-190735 Exclude props with default value from export

### PR DESCRIPTION
**Pull request by jkappler**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-190735)

Motivation
=======
When exporting pages, there are some default or empty props that are stored the json created when exporting the page. We want to avoid those default props to be exported.

**NOTE: I will include two screenshots, at left the screenshot without the default props and at right the screenshot with the props configured and exported well.**

## Steps
- Go to Design > Page Templates > Page Templates > Create a Content Page Template 

**Case 1: Container**
  - Add a Container to a content page template
  - Select the Container and see Container configurations at right side 
  - In general tab > Container Width > Fixed
  - In Styles tab configure the opacity to 99 and the following properties to 1px:
  - "borderWidth",
     "marginBottom",
     "marginLeft",
     "marginRight",
     "marginTop",
     "paddingBottom",
     "paddingLeft",
     "paddingRight",
     "paddingTop",
containerWithoutDefaultProps1
containerWithPropsConfigured1

**Case 3: Form**
  - Go to Control Menu > Control Panel > Objects
  - Create a new Object 
  - View the new Object 
  - Go to fields > add a new field
  - Publish the Object
  - Add a Form Container to a content page template 
  - Map the container to the form created
  - Go to Form Container configuration 
  - In general tab > Container Width > Fixed
  
formWithoutDefault
formConfigured

@DiegoHu97

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Hey @jkappler, we had some integration tests that failed and I'm not entirely sure it was as expected. Would you mind looking at this?

[com.liferay.layout.page.template.admin.web.internal.portlet.action.test.ImportExportLayoutPageTemplateEntriesTest](https://testray.liferay.com/home/-/testray/case_results/2398140313)
```
[exec] com.liferay.layout.page.template.admin.web.internal.portlet.action.test.ImportExportLayoutPageTemplateEntriesTest > testImportExportLayoutPageTemplateEntryContainerBackgroundFragmentImage FAILED
     [exec]     java.lang.AssertionError: expected:<{"pageElement":{"pageElements":[{"definition":{"fragmentStyle":{"backgroundColor":"","borderRadius":"rounded-0","borderWidth":"0","fontFamily":"sans-serif","fontSize":"medium","fontWeight":"font-weight-normal","height":"h-auto","maxHeight":"none","maxWidth":"none","minHeight":"auto","minWidth":"auto","overflow":"visible","shadow":"shadow-none","textAlign":"none","width":"w-auto"},"indexed":true,"layout":{"borderWidth":0,"marginBottom":0,"marginLeft":0,"marginRight":0,"marginTop":0,"opacity":100,"paddingBottom":0,"paddingLeft":0,"paddingRight":0,"paddingTop":0,"shadow":"None","widthType":"Fluid"}},"pageElements":[{"definition":{"fragmentStyle":{"backgroundColor":"","backgroundFragmentImage":{"url":{"value":"https://upload.wikimedia.org/wikipedia/commons/b/b2/Liferay-logo-full-color-2x.png"}},"borderRadius":"rounded-0","borderWidth":"0","fontFamily":"sans-serif","fontSize":"medium","fontWeight":"font-weight-normal","height":"h-auto","maxHeight":"none","maxWidth":"none","minHeight":"auto","minWidth":"auto","overflow":"visible","shadow":"shadow-none","textAlign":"none","width":"w-auto"},"indexed":true,"layout":{"borderWidth":0,"marginBottom":0,"marginLeft":0,"marginRight":0,"marginTop":0,"opacity":100,"paddingBottom":0,"paddingLeft":0,"paddingRight":0,"paddingTop":0,"shadow":"None","widthType":"Fluid"}},"type":"Section"},{"definition":{"fragmentStyle":{"backgroundColor":"","backgroundFragmentImage":{"url":{"mapping":{"fieldKey":"smallImage","itemReference":{"className":"com.liferay.journal.model.JournalArticle","classPK":34607}}}},"borderRadius":"rounded-0","borderWidth":"0","fontFamily":"sans-serif","fontSize":"medium","fontWeight":"font-weight-normal","height":"h-auto","maxHeight":"none","maxWidth":"none","minHeight":"auto","minWidth":"auto","overflow":"visible","shadow":"shadow-none","textAlign":"none","width":"w-auto"},"indexed":true,"layout":{"borderWidth":0,"marginBottom":0,"marginLeft":0,"marginRight":0,"marginTop":0,"opacity":100,"paddingBottom":0,"paddingLeft":0,"paddingRight":0,"paddingTop":0,"shadow":"None","widthType":"Fluid"}},"type":"Section"}],"type":"Section"}],"type":"Root"},"settings":{"colorSchemeName":"01","themeName":"Classic"},"version":1.1}> but was:<{"pageElement":{"pageElements":[{"definition":{"fragmentStyle":{"backgroundColor":"","borderRadius":"rounded-0","borderWidth":"0","fontFamily":"sans-serif","fontSize":"medium","fontWeight":"font-weight-normal","height":"h-auto","maxHeight":"none","maxWidth":"none","minHeight":"auto","minWidth":"auto","overflow":"visible","shadow":"shadow-none","textAlign":"none","width":"w-auto"},"indexed":true,"layout":{"shadow":"None"}},"pageElements":[{"definition":{"fragmentStyle":{"backgroundColor":"","backgroundFragmentImage":{"url":{"value":"https://upload.wikimedia.org/wikipedia/commons/b/b2/Liferay-logo-full-color-2x.png"}},"borderRadius":"rounded-0","borderWidth":"0","fontFamily":"sans-serif","fontSize":"medium","fontWeight":"font-weight-normal","height":"h-auto","maxHeight":"none","maxWidth":"none","minHeight":"auto","minWidth":"auto","overflow":"visible","shadow":"shadow-none","textAlign":"none","width":"w-auto"},"indexed":true,"layout":{"shadow":"None"}},"type":"Section"},{"definition":{"fragmentStyle":{"backgroundColor":"","backgroundFragmentImage":{"url":{"mapping":{"fieldKey":"smallImage","itemReference":{"className":"com.liferay.journal.model.JournalArticle","classPK":34607}}}},"borderRadius":"rounded-0","borderWidth":"0","fontFamily":"sans-serif","fontSize":"medium","fontWeight":"font-weight-normal","height":"h-auto","maxHeight":"none","maxWidth":"none","minHeight":"auto","minWidth":"auto","overflow":"visible","shadow":"shadow-none","textAlign":"none","width":"w-auto"},"indexed":true,"layout":{"shadow":"None"}},"type":"Section"}],"type":"Section"}],"type":"Root"},"settings":{"colorSchemeName":"01","themeName":"Classic"},"version":1.1}>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:120)
```


[com.liferay.layout.headless.delivery.dto.v1_0.test.PageDefinitionDTOConverterTest](https://testray.liferay.com/home/-/testray/case_results/2398140385)

```
[exec] com.liferay.layout.headless.delivery.dto.v1_0.test.PageDefinitionDTOConverterTest > testToPageDefinitionSection FAILED
     [exec]     java.lang.AssertionError: expected:<Fluid> but was:<null>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:120)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:146)
     [exec]     	at com.liferay.layout.headless.delivery.dto.v1_0.test.PageDefinitionDTOConverterTest.testToPageDefinitionSection(PageDefinitionDTOConverterTest.java:541)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]     	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```


[PortalLogAssertorTest-modules-integration-mysql57-jdk8/0/4](https://testray.liferay.com/home/-/testray/case_results/2398140257)
```
 [exec] com.liferay.headless.delivery.resource.v1_0.test.MessageBoardThreadResourceTest > testGetMessageBoardThreadsRankedPageWithSortString STARTED
     [exec] 2023-08-01 16:56:44.197 ERROR [http-nio-8080-exec-5][WebApplicationExceptionMapper:29] null
     [exec] com.liferay.portal.odata.sort.InvalidSortException: Unable to sort by property: ratingValue
     [exec] 	at com.liferay.portal.odata.internal.sort.SortParserImpl.getSortField(SortParserImpl.java:138) ~[?:?]
     [exec] 	at com.liferay.portal.odata.internal.sort.SortParserImpl.parse(SortParserImpl.java:71) ~[?:?]
     [exec] 	at com.liferay.portal.vulcan.internal.jaxrs.context.provider.SortContextProvider.createContext(SortContextProvider.java:76) ~[?:?]
     [exec] 	at com.liferay.portal.vulcan.internal.jaxrs.context.provider.SortContextProvider.createContext(SortContextProvider.java:104) ~[?:?]
     [exec] 	at com.liferay.portal.vulcan.internal.jaxrs.context.provider.SortContextProvider.createContext(SortContextProvider.java:36) ~[?:?]
     [exec] 	at org.apache.cxf.jaxrs.utils.JAXRSUtils.createContextValue(JAXRSUtils.java:1364) ~[bundleFile:3.4.10]
     [exec] 	at org.apache.cxf.jaxrs.utils.JAXRSUtils.processParameter(JAXRSUtils.java:1079) ~[bundleFile:3.4.10]
     [exec] 	at org.apache.cxf.jaxrs.utils.JAXRSUtils.processParameters(JAXRSUtils.java:999) [bundleFile:3.4.10]
```


```

```

**Comment by jkappler** [comment]
@DiegoHu97, can you please take a look?

Thanks @alessandromalves!

**Comment by DiegoHu97** [comment]
@jkappler Resent here: https://github.com/liferay-echo/liferay-portal/pull/13131

**Pull request closed without merging**
