### PR TITLE
LPS-137577 Select multiple Categories when creating a navigation menus

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-137577

cc: @sandrodw3 

I have changed a POSHI test because the text of the button of the layout selection popup in the site navigation menu item creation, has changed from "Add" to "Select". @david-gutierrez-mesa Please, could you review that commit: https://github.com/liferay-echo/liferay-portal/commit/e7ae53657efa977f913383ec5d557ad0fd0ce6d7 

Thanks!

### CODE REVIEW

**Comment by sandrodw3** [comment]
🥳

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:bundle

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/6573

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
