### PR TITLE
LPS-132872 Embed react component in a div since <react:component> taglib uses it direct parent to render the app

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The failure task is a semantic versioning in portal-impl unrelated to the changes in PR. Due to saving CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/102409

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
