### PR TITLE
LPS-124483 Name should be Liferay or Liferay DXP depending on the deployment

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:echo

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Tim-Cao** [comment]
Hi @jkappler, it seems like the DXP bundle still shows **Welcome to Liferay Portal**
The company.default.name=Liferay doesn't changes when change to dxp script.

**Comment by jkappler** [comment]
ci:test:relevant

**Pull request closed without merging**
