### PR TITLE
LPS-198057

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
cc: @henriquelimadotcom @lfbesada

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/144174

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by Tim-Cao** [comment]
Hi @ealonso, would you mind double checking the [js-unit-jdk8/0/0](https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/674721//consoleText)?

**Comment by ealonso** [comment]
@Tim-Cao failures are not related with my changes, I'm going to reopen Brian's pr and close this one.

**Pull request closed without merging**
