### PR TITLE
[TS] LPS-146458

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team, 

This PR, which is a folloup of #7103, tries to fix the conditions checked at the time of showing the workflow status filters and the workflow-related emails in Web Content Administration.

Currently the check only looks for Workflows activated at Web Content Folder level, but should also check for Web Contents at site level (companyId > 0, groupId > 0) and at company level (companyId > 0, groupId == 0).

Could you please review it?

Thanks in advance!

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1317401_1949

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Hi @dacousalr 
First of all, please, sorry for the delay in the review.
Thanks a lot for the fix, it works great!
Regards

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
