### PR TITLE
LPS-194273 Add validation and add import strategies for import page template  process

### PR DESCRIPTION
**Pull request by Mikellorza**
Story: https://liferay.atlassian.net/browse/LPS-175120
Subtask: https://liferay.atlassian.net/browse/LPS-194273

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by ealonso** [comment]
@Mikellorza Could you please add a message on source format channel about the SF error? It seems to be not related with your changes.

**Comment by jkappler** [comment]
yes, it's an issue that is present in many PR

**Comment by jkappler** [comment]
Fix for SF was sent, so we have to wait for it to be merged

**Comment by Mikellorza** [comment]
The fix of the SF is : https://github.com/ling-alan-huang/liferay-portal/pull/2100

**Comment by Mikellorza** [comment]
@ealonso I checked the failing test and is not related with the PR changes. So I proceed to create a [bug](https://liferay.atlassian.net/browse/LPS-195446) to fix it .


Thanks

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @Mikellorza,
Semantic versioning seems to be related with your changes

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
@ealonso , thanks for the reminder, I have just push the fix for the semantic versioning.

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
