### PR TITLE
[TS] LPS-157939 Import layout friendly URLs before layout portlets

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team, 

Can you help review this PR?

**Notes from @noornajj:**

> https://issues.liferay.com/browse/LPS-157939
> 
> The issue here was that a lar file couldn't be imported when it had two pages with the same name and created off of a page template. 
> 
> I found the issue was occurring when _importLayoutPortlets was being called and the friendlyURLMap is being retrieved. Since the friendly URLs are not imported yet, an empty friendlyURLMap was being passed and a default URL was generated based off of the page's name. 
> 
> This was causing a duplicate error to occur since the two pages being imported had the same name as well as an OptimisticLockException.
> 
> To fix the issue I reordered the imports so that _importLayoutFriendlyURLs called before _importLayoutPortlets

Please let us know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Thanks @ericyanLr and @noornajj!

**Pull request closed without merging**
