### PR TITLE
LPS-138591 Isolate Page Editor Edit Image and Edit HTML modals

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-138591

This pr isolates the Page Editor Image Edit and HTML Content Edit modals. Image Edit modal is fully isolated. HTML Content Edit modal is only partially isolated, only `modal-header`, `modal-footer`, and source editor toolbar contents have the cadmin class. 

/cc @victorg1991 

Screenshots:
html-edit-content
page-editor-edit-image

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
This works flawlessly 😻 Many thanks!!

I pinged @boton since it is touching image editor css and it belongs to lima. I'm not sure in which places it is being used, so it's better that they review it 😇 

Marking the pr as on hold until the review is done!

**Comment by boton** [comment]
Tested and working great ✅ 

Thanks, guys!

**Comment by victorg1991** [comment]
Thanks for reviewing this! 👏🏻

**Comment by victorg1991** [comment]
ci:forward

**Comment by pat270** [comment]
Thanks!

**Pull request closed without merging**
