### PR TITLE
LPS-193898 Site builder search field is having problems with searches ending in vowel+y

### PR DESCRIPTION
**Pull request by jkappler**
https://liferay.atlassian.net/browse/LPS-193898

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139714

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
