### PR TITLE
LPS-125886 Move inputValue into a function

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
ci:test:relevant

**Comment by boton** [comment]
ci:test:sf

**Comment by ealonso** [comment]
cc: @jeyvison

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
See changes here https://github.com/liferay-echo/liferay-portal/pull/3445

**Pull request closed without merging**
