### PR TITLE
LPS-195345 ordering categories based on hierarchy

### PR DESCRIPTION
**Pull request by ZakiMiklos**
### Motivation
A solution to [this ticket](https://liferay.atlassian.net/browse/LPS-195345) where category display is not displayed in order 

### Proposed Solution
Adding a new comperator to sort the categories based on hierarchy 

### Steps to Verify

1. Go to Categorization > Categories > “+“
2. Add a new vocabulary
3. Add a category hiearchy  (A > B > C > D > E > F)
4. Create a new web content
5. Open CATEGORIZATION on the right menu, and select all categories 
6. Check the order in which they line up from the top. (A > B > C > D > E > F)
7. Publish it
8. Open it again and check the categories

### screenshot of the initial order
image

### Screenshot of the wrong order
image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ZakiMiklos** [comment]
ci:test

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
@ZakiMiklos Could you please fix the source formatter errors?

**Comment by ZakiMiklos** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Hey @ZakiMiklos, it is still failing also could you please merge both commits, to have more clear the commits history

**Comment by ZakiMiklos** [comment]
Hell @ealonso Yes of course.

**Comment by ZakiMiklos** [comment]
ci:test:sf

**Comment by ZakiMiklos** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:sf

**Comment by jkappler** [comment]
Hi @ZakiMiklos, can you please check the SF, it's still failing.

Thanks

**Comment by ZakiMiklos** [comment]
ci:test:sf

**Comment by ZakiMiklos** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Hey @ZakiMiklos,

I'm not completely sure about what should be the correct order in the input field, so Could you please open a PTR and we can decide about it?, since it is going to affect all clients.

Regards,
Eudaldo.

**Comment by ZakiMiklos** [comment]
Hi @ealonso 

I opened a new [PTR](https://liferay.atlassian.net/browse/PTR-4305) as you asked 

Best Regards,
Miklós

**Comment by ZakiMiklos** [comment]
Hi @ealonso The PTR was answered and they same to be suggesting the same solution.

**Comment by ealonso** [comment]
please see: https://github.com/liferay-echo/liferay-portal/pull/13685

**Pull request closed without merging**
