### PR TITLE
LPS-128642 The search bar is disabled when searching

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
This fixes https://issues.liferay.com/browse/LPS-128642

**Step to reproduce:**
1. Product Menu > People > Teams
2. Add a new team named New Team
3. Access to new team > Users tab
4. Assign the Test Test to new team
5. Search user in seach bar

**Expected Results:**
The 0 Results for user should be shown and the search bar should be still enabled.

After this fix, the search bar is not disabled when there are no results: 
Screenshot 2021-03-05 at 12 05 26

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
