### PR TITLE
LPS-174425 Adapt the Content Display Fragment rendering to the requirements

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-174425

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:reevaluate:1377401_8612

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1337401_2788

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1377401_8638

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by jkappler — APPROVED** [review]
❤️

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
