### PR TITLE
LPS-130706 Migrate asset categories selection modals (part 2)

### PR DESCRIPTION
**Pull request by markocikos**
Hey @liferay-echo ,

JIRA ticket: https://issues.liferay.com/browse/LPS-130706

In https://github.com/liferay-echo/liferay-portal/pull/4436 I missed one usage to migrate. Fixing it with this PR!

Test case:
1. Open Categorization > Categories.
1. Create two vocabularies and a category
1. Category > (⋮) > Move

Before:
before

After:
after

/cc @kresimir-coko @jonmak08

### CODE REVIEW

**Review by kresimir-coko — APPROVED** [review]
LGTM! 👍

**Comment by victorg1991** [comment]
I've fixed a bug (not caused by this pr) and resent here: https://github.com/liferay-echo/liferay-portal/pull/4525 

@markocikos i'm wondering in which cases the openSelectionModal function needs the eventName to be passed. I've seen several places where it was removed  🤔

**Comment by markocikos** [comment]
> i'm wondering in which cases the openSelectionModal function needs the eventName to be passed. I've seen several places where it was removed

@victorg1991  In the `openSelectionModal` utility, we are introducing standard multiple selection behavior, integrated with search container. If you are using this type of selection, you don't need `selectEventName`.

In all other cases, you need to pass in `selectEventName`, along with code in modal that will fire a custom event with that name.

**Comment by victorg1991** [comment]
@markocikos Got it! Thanks for the explanation 👏

**Pull request closed without merging**
