### PR TITLE
LPS-117091 Enable color selector. It seems that without passing a function to the onColorsChange callback the color selector is not show

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
image

**Comment by p2kmgcl** [comment]
image
!!!

**Comment by sandrodw3** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:close

**Comment by victorg1991** [comment]
sent here: https://github.com/liferay-echo/liferay-portal/pull/1551

**Pull request closed without merging**
