### PR TITLE
LPS-184185 | Collapse can not closed after searching in Fragments and Widgets

### PR DESCRIPTION
**Pull request by jaimelr10**
[Link to the Ticket 
](https://issues.liferay.com/browse/LPS-184185)

## Test Scenario

- Add a content page
- Search anything like "a" in the Fragments and Widgets panel
- After search, click any of the Collapse icon

https://github.com/liferay-echo/liferay-portal/assets/40394495/1581ed1c-1db0-4b99-ab89-0d1b3477c375

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by claraizquierdo — COMMENTED** [review]
Hi @jaimelr10 ! Thank you for submitting your PR. The solution works but mantaining two elements in the state with the logic of opening or closing the collapsibles seems a little bit weird to me. Why don't you try changing the open state initialization to something like this:

```
const [open, setOpen] = useSessionState(
		`${config.portletNamespace}_fragment-collection_${collection.collectionId}_open`,
		initialOpen || isSearchResult
	);
```

I think it might work 🤔  What do you think?

**Comment by claraizquierdo** [comment]
> Hi @jaimelr10 ! Thank you for submitting your PR. The solution works but mantaining two elements in the state with the logic of opening or closing the collapsibles seems a little bit weird to me. Why don't you try changing the open state initialization to something like this:
> 
> ```
> const [open, setOpen] = useSessionState(
> 		`${config.portletNamespace}_fragment-collection_${collection.collectionId}_open`,
> 		initialOpen || isSearchResult
> 	);
> ```
> 
> I think it might work 🤔 What do you think?

The solution I told does not work correctly. Your solution works perfect, sorry for the misunderstanding 😞

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Failures are not related, pushed to BChan directly at https://github.com/brianchandotcom/liferay-portal/pull/135512

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
