### PR TITLE
LPS-146271 Split common styles between General and Styles tabs

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by veroglez** [comment]
Looks really nice! 🎉

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7170

**Pull request closed without merging**
