### PR TITLE
LPS-114454 and LPS-114455: Implement FormProvider for JournalArticle and BlogsEntry (Rebased)

### PR DESCRIPTION
**Pull request by JorgeFerrer**

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:forward

**Comment by JorgeFerrer** [comment]
ci:forward

**Comment by JorgeFerrer** [comment]
ci:forward

**Comment by JorgeFerrer** [comment]
Re-running tests based on an analysis of the failed tests, since they all seem to be flaky and unrelated to this pull

**Comment by manoelcyreno** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
The first error `/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:11825: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common-portal-acceptance-batch.xml:237: The following error occurred while executing this line:
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:8911: Sourced file: inline evaluation of: `` 								 									import com.liferay.jenkins.results.parser.GitHubDevSyncUtil;  . . . '' : TargetError : at Line: 91 : in file: inline evaluation of: `` 								 									import com.liferay.jenkins.results.parser.GitHubDevSyncUtil;  . . . '' : throw e ; ` is a jenkins issue, should be flaky.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/889

cc: @JorgeFerrer

**Pull request closed without merging**
