### PR TITLE
LPS-152865 baseline

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:stop

**Comment by ozysouza** [comment]
ci:close

**Comment by ozysouza** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/117072

**Pull request closed without merging**
