### PR TITLE
[TS] LPS-135814

### PR DESCRIPTION
**Pull request by wanderlast**
https://issues.liferay.com/browse/LPP-41992
https://issues.liferay.com/browse/LPS-135814

Hi @liferay-echo team!

Currently we have a CSS selector for the tabs fragment that forces all img tags within it to match the width of the container. Due to how indiscriminately this selects, this affects all images within the tabs which includes things like document previews, causing problems for DM and Asset Publisher portlets placed in the tabs fragment. This CSS being removed was added in 2b03892bb62c1f5ce9942f0801cc4242ff7a7d90 when we were still using an editable image with the message "Use editable image until we have dropzones". We have already removed this editable image and substituted a dropzone in its place so I believe it should be safe to remove. Please let me know if you have any questions or concerns. Thanks!

### CODE REVIEW

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
LGTM! 🎉

**Comment by veroglez** [comment]
ci:forward

**Pull request closed without merging**
