### PR TITLE
LPS-190367

### PR DESCRIPTION
**Pull request by Mikellorza**

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
hey @ealonso ,

I have fix some test that were failing. Please take a look and if it fine for you we go forward.

Thanks.

**Comment by alessandromalves** [comment]
ci:forward:force

**Comment by alessandromalves** [comment]
The failures are not related to this PR [(see comparison with acceptance routine)](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1691175828402&testrayRunIdA=2399969137&testrayRunIdB=2400151520). See https://github.com/brianchandotcom/liferay-portal/pull/138853

**Pull request closed without merging**
