### PR TITLE
LPS-191691 Do not allow the user to edit the article if they cannot view the article's structure

### PR DESCRIPTION
**Pull request by jonathanmccann**
Motivation
=======
https://liferay.atlassian.net/browse/LPS-191691

The issue is that when a user has permission to edit an article but does not have permission to view the underlying structure the article does not display properly.

Proposed Solution
========
To solve this problem I introduced a new permission check to ensure the user has permission to view the structure. If they do not then the do not have the option to edit the article.

Steps to Verify
========
1. Go to the Global site
2. Go to Content & Data - Web Content - Structures
3. Add a new Structure
4. Go to Control Panel - Users and Organizations
5. Add a new user
6. Add the user as a member of the Liferay DXP site
7. Add the Site Administrator role to the user
8. On the default site add a new Web Content Article utilizing the new structure
9. Sign in as the new user
10. Go to Content & Data - Web Content
11. Edit the newly created article

Alternative Solutions that were discarded (if applies)
========
I wasn't 100% certain what the behavior should be in this situation. If you would rather allow the user to be able to edit the article please let me know.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by jonathanmccann** [comment]
@lfbesada Thanks for the quick response. I've opened PTR-4147 to discuss the issue further.

**Pull request closed without merging**
