### PR TITLE
LPS-168056 HR_190 SR is not announcing "Add page" Dialog box

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
[Link to ticket](https://issues.liferay.com/browse/LPS-168056)

## Test Scenario
* Use JAWS/VoiceOver
* Navigate to Site Builder > Pages > New > Global Templates
* Add a new Page

image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:forward

**Review by sandrodw3 — APPROVED** [review]

**Pull request closed without merging**
