### PR TITLE
LPS-158932 Allow for userID to be passed correctly when using Experiences with Workflow

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-158932

Previous PR: https://github.com/liferay-echo/liferay-portal/pull/9269

@noornajj
@jakesliwka
@ericyanLr

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Forwarded manually since ci:forward is not working. See https://github.com/brianchandotcom/liferay-portal/pull/121876

**Comment by david-gutierrez-mesa** [comment]
ci:close

**Pull request closed without merging**
