### PR TITLE
LPS-185245 Move configurations to same page

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @sandrodw3, would you mind having a look at this failed integration test?
[com.liferay.layout.service.test.LayoutLocalServiceTest](https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/524805/testReport/com.liferay.layout.service.test/LayoutLocalServiceTest) - [Failed 0 of last 25](https://testray.liferay.com/home/-/testray/case_results/2314160195/history)

**Comment by Tim-Cao** [comment]
ci:forward:force

**Pull request closed without merging**
