### PR TITLE
LPS-161051 - Web content preview is not displayed.

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @tototrinh

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ruben-pulido，the Web Content admin is broken.
image
Would you mind having a look at?

**Comment by ruben-pulido** [comment]
Thanks for the heads up @Tim-Cao 
@tototrinh, can you look into making sure that the fix does not cause the regression TIm mentions? Thanks!

**Pull request closed without merging**
