### PR TITLE
LPS-110755 - Add mapped value support for export/import functionality

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @pavel-savinov

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
https://github.com/liferay-echo/liferay-portal/pull/80#issuecomment-608554178

**Pull request closed without merging**
