### PR TITLE
LPS-157069 Limit the itemSelector to the current scope

### PR DESCRIPTION
**Pull request by bakayattila**
hi Team,
Could you review this?

https://issues.liferay.com/browse/LPS-157069

Best,
Attila

----

**Steps to reproduce:**
Navigate to Control Panel > Sites and create a new site
Navigate to Site menu > Site Builder > Pages and add a new page
Navigate to Site menu > Site Builder > Navigation menu and add a new navigation menu
Add the page from step 3. to the navigation menu
Click on the added navigation menu element, then on the right side, click on the Choose button
**Expected result:** The generated page selector should have the same limitation on the scope as the one on the add new navigation menu items 
**Actual result:** Users can navigate to other sites in the item selector.

Related slack thread to the topic:
https://liferay.slack.com/archives/CL9RTSZ52/p1656412961775489

This is the slector when we add a new element to the navigation menu:
image (4)

And this is the item selector when I edit an already added element:
image (3)

And this is the same item selector after the modifcaion:
image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
Ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
