### PR TITLE
LPS-192600

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by alessandromalves** [comment]
Hey @ealonso I've seen that this test is failing on CI but it hasn't failed locally, but an error appears on the log just like the one reported on CI. I'm not completely sure that this is related, would you mind taking a look? This was the only failure found. Thanks in advance!


[PortalLogAssertorTest-modules-integration-mysql57-jdk8/0/6](https://testray.liferay.com/home/-/testray/case_results/2410282316)

**Comment by alessandromalves** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139562

**Pull request closed without merging**
