### PR TITLE
[TS] LPS-123387

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-123387

Forwarded from https://github.com/ChrisKian/liferay-portal/pull/270 with changes applied as requested: https://github.com/brianchandotcom/liferay-portal/pull/96337#issuecomment-735551171

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
