### PR TITLE
LPS-150957, LPS-150958, LPS-146824 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-150957
https://issues.liferay.com/browse/LPS-150958
https://issues.liferay.com/browse/LPS-146824

This is only for master.

@p2kmgcl
cc @ozysouza

There is a regression issue. Would you mind having a look at before forward?
The Margin Left and Margin Right should be disabled when Container has Fixed Width. The new spacing styles don't have this status, even though the defined Margin Left and Margin Right won't be applied to Container.

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/7712

**Comment by Tim-Cao** [comment]
ci:reopen

**Comment by p2kmgcl** [comment]
Cherry picked done :)
I am closing this again

**Pull request closed without merging**
