### PR TITLE
LPS-165399 Add aria-label to clay:dropdown-actions

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @sandrodw3 @p2kmgcl,
What do you think about adding it automatically to the taglib? instead of adding in whole portal

**Comment by ealonso** [comment]
@p2kmgcl or they are not going to put never the label, like we are doing until today

**Comment by p2kmgcl** [comment]
:(

**Comment by liulukiwi** [comment]
ci:test:bundle

**Comment by liulukiwi** [comment]
Hi @p2kmgcl , I find an issue when analyzing the test results, blank page when clicking view usage in web content, could you take a look? here are the steps:
1.  Add a web content
2. Go to ellipse menu and click view usages

image

**Comment by p2kmgcl** [comment]
@liulukiwi sure, having a look :smile:

**Comment by p2kmgcl** [comment]
ci:test:bundle

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ozysouza** [comment]
The failures are unrealted to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/125296

**Comment by ozysouza** [comment]
ci:close

**Pull request closed without merging**
