### PR TITLE
[TS] LPS-136518

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

Can you please review the integration test for https://issues.liferay.com/browse/LPS-136518

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Review by lfbesada — CHANGES_REQUESTED** [review]
Hi @balazssk 

Thanks for the PR!

Please, could you do the same verification but in another test dedicated to expressly testing this case.

It would also be great if you could add another test checking that if the site is not the default one, then the group friendly url is added.

Thanks!

Regards

**Comment by lfbesada** [comment]
ci:reevaluate:1267401_846

**Comment by balazssk** [comment]
Thanks for the feedback @lfbesada , I'm on it.

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
O wow,
The test already proved useful by failing

**Comment by balazssk** [comment]
Can't reproduce this locally though. Maybe `PropsValues.VIRTUAL_HOSTS_DEFAULT_SITE_NAME != "Guest"` on the CI server

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by balazssk** [comment]
ci:test:sf

**Review by lfbesada — APPROVED** [review]
Thanks!

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
