### PR TITLE
LPS-147515 Adapt modal sizes

### PR DESCRIPTION
**Pull request by victorg1991**
The idea is to some exploratory testing of this PR

More info in the associated subtask: https://issues.liferay.com/browse/LPS-153479

modules to deploy: 

`asset-categories-admin-web`
`asset-categories-admin-web`
`asset-categories-selector-web`
`asset-categories-selector-web`
`asset-categories-selector-web`
`asset-taglib`

@david-gutierrez-mesa @liulukiwi @Tim-Cao @ozysouza

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/8215

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
