### PR TITLE
LPS-169795 Create tags filter

### PR DESCRIPTION
**Pull request by p2kmgcl**
(The only FrontEnd change is here: https://github.com/liferay-echo/liferay-portal/pull/10528/commits/6c4cab5f1835512710d0ecc268c9b9ae6209962d#diff-ed5536ea32fef4b0a98d6063740534f9b43562486c53b3692fa3c32530ce4498)

This is an initial development for the story, adding a new "Tags" filter fragment. In order to test this:

1. Enable FragmentCollectionFilters component.
2. Deploy all modules.
3. Add some tags (in Product Menu > Categorization > Tags).
4. Upload some images to the document library and tag them.
5. Create a manual collection of Basic Documents (it can be empty).
6. Add a content page with:
   - A collection display fragment targeting the created collection.
   - A collection filter fragment targeting the created collection display and using _tags_ as filter type.

Things to check:
- [ ] The page can be published.
- [ ] If something is typed into the fragment and enter is pressed, the page reloads and a new URL parameter appears.
- [ ] The fragment preserves typed tags into the URL.
- [ ] When typing a tag, it suggest existing tags.
- [ ] Content is filtered depending on selected tags.

**Warning**: currently the page is reloaded whenever a tag is added/removed. This is intended as we need to reload the page to update results, but we should investigate if this behavior can be improved.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
Pal brian (cc @lfbesada)

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
Hey @p2kmgcl, regression found ([See how the acceptance routine compares](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2128641555&testrayRunIdA=2127498119&statusB=3)). Only one regression was found that was related to the `com.liferay.layout.content.page.editor.web.internal.portlet.action.test.GetCollectionSupportedFiltersMVCResourceCommandTest` test. Could you take a look at it?

**Comment by alessandromalves** [comment]
Hey @p2kmgcl, only one regression was found ([See how the acceptance routine compares](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2128641555&testrayRunIdA=2127498119&statusB=3)) that was related to the `com.liferay.layout.content.page.editor.web.internal.portlet.action.test.GetCollectionSupportedFiltersMVCResourceCommandTest` test:

```[exec] com.liferay.layout.content.page.editor.web.internal.portlet.action.test.GetCollectionSupportedFiltersMVCResourceCommandTest > testAssetListSupportedFilters FAILED
     [exec]     java.lang.AssertionError: expected:<2> but was:<3>
     [exec]     	at org.junit.Assert.fail(Assert.java:89)
     [exec]     	at org.junit.Assert.failNotEquals(Assert.java:835)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:647)
     [exec]     	at org.junit.Assert.assertEquals(Assert.java:633)
```
Could you take a look at it?

**Comment by p2kmgcl** [comment]
Hey @alessandromalves! Thanks for having a look. I am updating the PR :smile:

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:reevaluate:1377401_7207

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:test:help

**Comment by liulukiwi** [comment]
ci:help

**Comment by liulukiwi** [comment]
Hi @p2kmgcl , modules-semantic-versioning-jdk8/0/0 only fails on this pull, could you take a look?

```
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/layout/layout-api] STARTED
     [exec] 
     [exec] com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/layout/layout-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.layout.util                            MINOR      4.1.0      4.1.0      4.2.0      VERSION INCREASE REQUIRED
     [exec]     	+   interface  com.liferay.layout.util.LayoutsTree
     [exec]     		+   access     abstract
     [exec]     		+   method     getLayoutsJSON(javax.servlet.http.HttpServletRequest,long,boolean,long,boolean,java.lang.String)
     [exec]     			+   access     abstract
     [exec]     			+   return     java.lang.String
     [exec]     		+   method     getLayoutsJSON(javax.servlet.http.HttpServletRequest,long,boolean,long,boolean,java.lang.String,com.liferay.portal.kernel.model.LayoutSetBranch)
     [exec]     			+   access     abstract
     [exec]     			+   return     java.lang.String
     [exec]     		+   method     getLayoutsJSON(javax.servlet.http.HttpServletRequest,long,boolean,long,int)
     [exec]     			+   access     abstract
     [exec]     			+   return     java.lang.String
     [exec]     		+   method     getLayoutsJSON(javax.servlet.http.HttpServletRequest,long,boolean,long,int,com.liferay.portal.kernel.model.LayoutSetBranch)
     [exec]     			+   access     abstract
     [exec]     			+   return     java.lang.String
     [exec]     		+   method     getLayoutsJSON(javax.servlet.http.HttpServletRequest,long,boolean,long,long[],boolean,java.lang.String)
     [exec]     			+   access     abstract
     [exec]     			+   return     java.lang.String
     [exec]     		+   method     getLayoutsJSON(javax.servlet.http.HttpServletRequest,long,boolean,long,long[],boolean,java.lang.String,com.liferay.portal.kernel.model.LayoutSetBranch)
     [exec]     			+   access     abstract
     [exec]     			+   return     java.lang.String
     [exec]     		+   method     getLayoutsJSON(javax.servlet.http.HttpServletRequest,long,java.lang.String)
     [exec]     			+   access     abstract
     [exec]     			+   return     java.lang.String
     [exec]     		+   method     getLayoutsJSON(javax.servlet.http.HttpServletRequest,long,java.lang.String,com.liferay.portal.kernel.model.LayoutSetBranch)
     [exec]     			+   access     abstract
     [exec]     			+   return     java.lang.String
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 25.3.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertFalse(Assert.java:64)
     [exec]         at com.liferay.semantic.versioning.SemanticVersioningTest.testSemanticVersioning(SemanticVersioningTest.java:82)
     [exec]         at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
     [exec]         at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
     [exec]         at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
     [exec]         at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
     [exec]         at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
     [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
     [exec]         at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
     [exec]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
     [exec]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
     [exec]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
     [exec]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
     [exec]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
     [exec]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
     [exec]         at org.junit.runners.Suite.runChild(Suite.java:128)
     [exec]         at org.junit.runners.Suite.runChild(Suite.java:27)
     [exec]         at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
     [exec]         at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
     [exec]         at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
     [exec]         at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
     [exec]         at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
     [exec]         at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
     [exec]         at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
     [exec]         at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]         at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
     [exec]         at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
     [exec]         at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
     [exec]         at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [exec]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
     [exec]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]         at java.lang.reflect.Method.invoke(Method.java:498)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
     [exec]         at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
     [exec]         at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
     [exec]         at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
     [exec]         at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
     [exec]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
     [exec]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
     [exec]         at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
     [exec]         at java.lang.Thread.run(Thread.java:745)```

https://testray.liferay.com/home/-/testray/case_results/2134435151
[Jenkins log](https://testray.liferay.com/reports/production/logs/2022-12/test-1-38/test-portal-acceptance-pullrequest(master)/5307/modules-semantic-versioning-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by lfbesada** [comment]
Hi @liulukiwi Thanks for the review. IMHO that is not related to this PR since this PR does not change anything in the layout-api, but I have added a commit fixing it and I have resent it here: https://github.com/liferay-echo/liferay-portal/pull/10665

**Pull request closed without merging**
