### PR TITLE
LPS-143841 Give feedback when item does not have display page

### PR DESCRIPTION
**Pull request by sandrodw3**
/cc @ealonso @lfbesada 🦄

### CODE REVIEW

**Comment by sandrodw3** [comment]
@ealonso backend changes are applied in this one 🥰

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
@sandrodw3 SF error

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/7081

**Pull request closed without merging**
