### PR TITLE
LPS-168837 Replace liferay-ui:icon in journal-content-web

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
[Link to ticket](https://issues.liferay.com/browse/LPS-168837)

* Delete the unused edit_template.jsp instead of modify it.
* No changes needed in portlet_header.jsp.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
Weeeee 🎉

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
