### PR TITLE
LPS-132000 Apply body color to resize viewport

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:reevaluate:1027401_661

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
packageRunTest app-builder-web :raised_eyebrow:

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
D: what a horrible PR

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/4770

**Pull request closed without merging**
