### PR TITLE
LPS-168166 Move test to the corresponding test folder

### PR DESCRIPTION
**Pull request by YurenaC**
After refactor needed in LPS-166857 some review about the available test need to be performed to ensure that they are in the right folder.

ticket -> https://issues.liferay.com/browse/LPS-168166

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by ealonso** [comment]
@YurenaC

**Comment by ealonso** [comment]
@YurenaC SF is going to fail

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/11835 and https://github.com/liferay-echo/liferay-portal/pull/11838

**Pull request closed without merging**
