### PR TITLE
LPS-114252 - Support having draft and published Fragment simultaneously in back end

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @jkappler @sandrodw3

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:stable

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
sent directly to Brian: https://github.com/brianchandotcom/liferay-portal/pull/90234

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
