### PR TITLE
LPS-129701 Migrate open selection modals in site modules

### PR DESCRIPTION
**Pull request by kresimir-coko**
Hi @liferay-echo, here's a new PR migrating open selection modals, the first PR (https://github.com/liferay-echo/liferay-portal/pull/4185) wasn't a great success - it got reverted. So here's a new one, encompassing all of the usages (except 2 - explained later) which should eliminate all of the usages of the old modal implementation and use the new `openSelectionModal`.

# 👀  The missing usages

There are 2 leftover usages, one of them is being migrated as part of the `users-admin` migration, the other one is bugged. 

1. `site-browser-web/view.jsp` - Handled as part of `users-admin` migration in [https://github.com/pei-jung/liferay-portal/pull/830](https://github.com/pei-jung/liferay-portal/pull/830)
2.  `site-memberships-web/site_roles.jsp` - Bugged - [https://issues.liferay.com/browse/LPS-130400](https://issues.liferay.com/browse/LPS-130400)

# 🧪 Testing

I've documented the test scenarios for these modals below:

## `user_groups_roles.jsp`

- People > Memberships > User Groups
- User Group options > Assign Roles/Unassign Roles

## `select_user_groups.jsp`

- People > Memberships > User Groups
- Assign a User Group

## `users_roles.jsp`

- People > Memberships > Users
- User options > Assign Roles

## `select_organizations.jsp`

- People > Memberships > Organizations
- Select an organization

## `select_users.jsp`

- People > Memberships > Users
- Assign a new user to site

## `select_site_role.jsp`

- People > Memberships > Filter by Roles

## `site-item-selector-web/view_sites.jsp`

- User Profile Icon -> My Sites
- `site_administration_header_icon_sites.jspf` same but button on left sidebar

## `site-taglib/site_browser/page.jsp`

- Add a new user -> Memberships section -> Click the Select button of Sites section

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
LGTM :) Thanks a lot @kresimir-coko The detailed description was very useful 👏

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
