### PR TITLE
LPS-139573 Remove feature flag and adapt code

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/5942

**Pull request closed without merging**
