### PR TITLE
LPS-157995 Adds page actions when editing a page

### PR DESCRIPTION
**Pull request by jkappler**
This PR changes the actions that a user is able to perform when editing a page. Before, we only showed a cog icon, now we show a list of actions that the user can perform: configure, permissions and delete. All the actions are already present in miller columns

page actions

A showcase can be seen in the gif

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
@david-gutierrez-mesa, @Tim-Cao, @liulukiwi, @ozysouza, this will most likely break poshi tests, so I'm flagging as QA review needed. Thanks!

**Comment by david-gutierrez-mesa** [comment]
ci:test:echo

**Comment by jkappler** [comment]
no, thanks @ozysouza!

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ozysouza** [comment]
@jkappler, the last relevant failed becuase the cog icon is also missing on content page at view mode. On the video you showed that it was replaced by the ellipisis icon at edit mode, which should be the behavior at view? Keep the cog icon or indeed remove it?

**Comment by jkappler** [comment]
only change it in edit mode @ozysouza, will re-check everything. Thanks!

**Pull request closed without merging**
