### PR TITLE
LPS-124967 In case field name is "name", getName can return TemplateNode object.

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
Not reproducible with data engine, but needed to clean code and fix breaking change in 7.X

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Since the failure case is common failure not related to change in PR and in order to not clog up ci resources I pushed directly to BChan.
See https://github.com/brianchandotcom/liferay-portal/pull/97069

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
