### PR TITLE
LPS-178949 Create ManagementToolbarDisplayContext used in view.jsp

### PR DESCRIPTION
**Pull request by YurenaC**
Motivation
=======
Currently we are going through different technical tasks oriented to improve the quality of the code within the segment-web module.

Commits
========
- LPS-178949 Create segmentsManagementToolbarDisplayContext class
- LPS-178949 Calling segmentsManagementToolbarDisplayContext from view
- LPS-178949 Reorganizing methods from SegmentsDisplayContext to SegmentsManagementToolbarDisplayContext class
- LPS-178949 Adapting some data to segmentsManagementToolbarDisplayContext

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:stop

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/12050

**Pull request closed without merging**
