### PR TITLE
LPS-194571 Page Templates admin becomes blank after rename page template set

### PR DESCRIPTION
**Pull request by YurenaC**
Motivation
=======
Page Templates admin becomes blank after rename page template set

Proposed Solution
========
The problemas was that it was redirecting to the wrong tab after renaming, this PR fixes that.

Steps to Verify
========

1. Add a new site
2. Navigate to the Page Templates admin
3. Add a page template set
4. Edit the page template set
5. Rename it then save

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward:force

**Comment by liulukiwi** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139807

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
