### PR TITLE
LPS-142508 - Handle multiple item creation with hierarchy

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @lfbesada

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @lfbesada, could you have a look at the integration test failure? Thanks

**Comment by lfbesada** [comment]
Hi @Tim-Cao, the failed test is not related to the changes of this PR. Thanks. Regards

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
