### PR TITLE
LPS-121887 Migrate v2 usages in layout/layout-taglib

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

Viewing related assets should work as expected.

**Test plan**:
- Navigate to **Content & Data** > **Blogs**
- Create a new Blog Entry and publish it
- Navigate to **Content & Data** > **Web Content**
- Create a new Basic Web Content
- In the sidebar on the right, search for **Related Assets**
- Click on the **Select** button and choose **Blog Entry**
- Select the Blog Entry you published and click on **Done**
- Navigate to **Site Builder** > **Pages**
- Create a new **Public Page** based on the **Blank** template
- Enter an name for your page and click on **Add**
- Drag and drop a **Web Content Display** and configure it to show the
Web Content you previously created
- Publish the page
- Navigate to **Content & Data** > **Web Content**
- Click on the kebab menu to the right of the Web Content you previously
created and select **View Usages**

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
cc @ambrinchaudhary @markocikos @jonmak08

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
I've created a related (tiny) bug that was already happening on master :D
https://issues.liferay.com/browse/LPS-128646

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by julien** [comment]
Thanks @p2kmgcl

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
this-is-fine

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
