### PR TITLE
LPS-168157 Make other actions more accessible

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, would you mind checking the failed integration test?
[com.liferay.asset.service.test.AssetEntryServiceTest.testGetTopViewedEntries](https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/328277//testReport/com.liferay.asset.service.test/AssetEntryServiceTest/testGetTopViewedEntries)

**Comment by ealonso** [comment]
Hey @Tim-Cao,
It should not be related, in this pr we are changing the visual aspect of print icon, nothing related with backend.

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
