### PR TITLE
LPS-188018 Create a Client Mock to be able to manually and POSHI testing simulating the real API interaction

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-188018

In this PR we are adding a simulation of the OpenAI client so that it allows us to test the full functionality without interacting with the OpenAI API. This will allow us to do manual tests, POSHI tests, or even Integration tests that test all the functionality.

To enable the mock, go to the Gogo Shell and enable the mock component:

`scr:enable com.liferay.ai.creator.openai.web.internal.client.MockAICreatorOpenAIClient`

How the mock works when editing the configuration depends on the API Key that is entered. 

Using VALID_API_KEY will be considered as a valid API Key and will allow us to access the AI Creator button in the Web Content CKEditor when this functionality is enabled.

Using USER_CONTENT as the user prompt will produce an OK response simulation returning as completion the text "OPENAI_API_COMPLETION_RESPONSE_CONTENT"

To simulate a controlled error we have disposed of some keys that could be used as API Key and/or as the user prompt.

These are the Keys and their expected behavior:

OPENAI_API_INVALID_API_KEY --> The response will be the same as when the real API returns an invalid API key's response.
OPENAI_API_IOEXCEPTION --> The response will be the same as when the real API throws an exception.
OPENAI_API_{0}_RESPONSE_CODE --> The response will be the same as when the real API response code is {0}.

The mock has a text completion fast response, so the user can't see the loading view. In order to be able to see the loading view you can use the user prompt USER_CONTENT_SLEEP_MILLIS_XXX where XXX is the number of milliseconds of delay to apply and must be a number greater than 0 and lower than 10000.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Hi @lfbesada!

I like the general approach of having the Mock client for performing the tests as it allows you to test cases that are not easily reproduced using the real client.

I think it makes sense to control the response of the `validateAPIKey` method by using different values of `apiKey`.

However, I think it will be more convenient for manual testing if the response of the `getCompletion` method is controlled not only by `apiKey` but by a combination of `apiKey` and `content`.

That way the different cases can be tested by modifying the `content` parameter instead of having to change the key within the portal instance configuration.

What do you think?

**Comment by lfbesada** [comment]
Hi @ruben-pulido 
Thanks a lot for the review and, especially, for that great idea 😍 
It has sense, it will be easiest to use that way and I think the code will look better!!!
So I am going to add these changes as soon as possible.
Thanks again! 
Regards

**Comment by lfbesada** [comment]
Hi @ruben-pulido 
Thank you very much for your feedback! I have incorporated it into the PR. I've also adapted the description to reflect the new behavior, could you please take a look at it?
Regards

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:stable

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1377401_12811

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
