### PR TITLE
LPS-164248 It should be default

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
Hi @ealonso! There is a regression issue. Could you please have a look at?

1. Add a new site
2. Add a widget page
3. Add a master page template
4. Add a Menu Display to master page template

Expected result: The widget page should be shown
Actual Result: There is a message "There are no menu items to display."

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
