### PR TITLE
[TS] LPS-128817

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-128817

Please let me know if you have any questions, thanks!

CC @lipusz, these changes allow for possibly more groups to be included in the groupSearch.  I don't believe this will concern you, but I thought I'dd CC you just in case.

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
Manually testing the failed tests shows no problems.  Private sites are still hidden from regular users, restricted site membership requests work, and a regular user is able to leave a given site.

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by Tim-Cao** [comment]
Hi @ChrisKian and @ruben-pulido, there is a regression issue caused by your changes.
My Sites widget doesn't work as expected
*Step to reproduce:*
1. Add a new user
2. Sign In as new user
3. Click the personal menu > My Dashboard > My Sites

*Expected Results:*
No sites were found. should be shown in My Sites widget.

*Actual Results:*
The existing sites are listed in My Sites widget.

**Comment by ChrisKian** [comment]
Resent here: https://github.com/liferay-echo/liferay-portal/pull/3985

**Pull request closed without merging**
