### PR TITLE
LPS-171076 The preview of the Utility pages in Staging cannot be accessed due to lack of permissions.

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-171076

cc: @BarbaraCabrera 

https://user-images.githubusercontent.com/84471361/207643791-3e19f164-d601-4384-9b9e-1d4010575433.mov

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1297401_5774

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1277401_6228

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/127710

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
