### PR TITLE
LPS-118272 buildLang

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @sandrodw3 and @pavel-savinov , there is another regression issue. The Content Display can not render the collection item in Collection Display.
Actual

**Comment by pavel-savinov** [comment]
ci:close

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/1859

**Pull request closed without merging**
