### PR TITLE
LPS-145046 - Add fragment collection option to item selector

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @p2kmgcl @victorg1991

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @ruben-pulido, there is a regression issue. Could you have a look at?
**Steps to reproduce**

1. Add a new site based on Blank

**Expected Results:**
There shouldn't be error thrown.

**Actual Results:**
The following error thrown:
```
2022-01-24 09:12:30.430 ERROR [http-nio-8080-exec-5][PortletServlet:119] javax.portlet.PortletException: java.lang.UnsupportedOperationException: Requires 3.0 opt-in
javax.portlet.PortletException: java.lang.UnsupportedOperationException: Requires 3.0 opt-in
        at com.liferay.portal.kernel.portlet.bridges.mvc.BaseMVCResourceCommand.serveResource(BaseMVCResourceCommand.java:49) ~[portal-kernel.jar:?]
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.callResourceMethod(MVCPortlet.java:462) ~[portal-kernel.jar:?]
        at com.liferay.portal.kernel.portlet.LiferayPortlet.serveResource(LiferayPortlet.java:143) ~[portal-kernel.jar:?]
        at com.liferay.portal.kernel.portlet.bridges.mvc.MVCPortlet.serveResource(MVCPortlet.java:366) ~[portal-kernel.jar:?]
        at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:146) ~[portal-impl.jar:?]
        at com.liferay.portlet.ScriptDataPortletFilter.doFilter(ScriptDataPortletFilter.java:88) ~[portal-impl.jar:?]
        at com.liferay.portlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:140) ~[portal-impl.jar:?]
        at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:78) ~[portal-kernel.jar:?]
        at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:115) ~[portal-kernel.jar:?]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) ~[servlet-api.jar:4.0.FR]
```
Additionally, the Applications Menu is broken.
image

**Comment by ruben-pulido** [comment]
https://github.com/liferay-echo/liferay-portal/pull/7036

**Pull request closed without merging**
