### PR TITLE
LPS-183066 Final adjustments

### PR DESCRIPTION
**Pull request by sandrodw3**
On Hold: waiting for https://github.com/liferay-echo/liferay-portal/pull/11932

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:forward

**Comment by lfbesada** [comment]
I think the changes to the page configuration view that this PR makes cause some of the tests to fail. Maybe some selectors should be updated, QA, could you please review it?
Thanks in advance!

**Comment by sandrodw3** [comment]
> I think the changes to the page configuration view that this PR makes cause some of the tests to fail. Maybe some selectors should be updated, QA, could you please review it? Thanks in advance!

Thanks a lot @lfbesada ❤️ just for more context for QA: Changes in this PR are visual:
- Changed some toggles to checkbox, and therefore some CSS classes were not needed and I removed them. Fields `name` and `id` are still the same.
- Modified titles of SEO, Open Graph and Custom Meta Tags to lowercase
- Added subtitles to Favicon and Logo sections for layout sets

**Pull request closed without merging**
