### PR TITLE
LPS-157688 Sets label field name and value field name on Object info framework implementation

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ozysouza** [comment]
Just start reviewing :)

**Comment by ozysouza** [comment]
Hi @ealonso, the failures are unrelated to your changes. We can go ahead with this PR.

**Comment by ozysouza** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/119973

**Comment by ozysouza** [comment]
ci:close

**Pull request closed without merging**
