### PR TITLE
LPS-152091 Render dynamic AssetVocabularySiteNavigationMenuItem

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-152091

Notes for reviewers ❤️ 

To implement a dynamic menu item based on a vocabulary we have thought of two possibilities:

- Implement the necessary model listeners to replicate in the items menu table the changes that have occurred to the vocabulary and its categories.
- Generate the hierarchy of menu items corresponding to the vocabulary dynamically and on-demand.

The two possible approaches have been analyzed in terms of simplicity and performance.
Regarding simplicity, the second approach has seemed much clearly simpler than the first.
To analyze a performance comparison between one approach and the other, we have thought that the steps to generate the menu would be the following depending on the approach:

1. Generate the hierarchy previously with the model listeners:
- We should get the tiered menu hierarchy from the SiteNavigationMenuItem table.
- For each of the items we would need at least its title localized with the appropriate language. In order to get that, the title should be maintained updated for all the available locales in the typeSettings of all the menu items in which an element could be. The alternative is to also obtain the AssetCategory of the corresponding table. Both solutions seem to be expensive.

2. Generate the hierarchy on-demand:
- Only the item corresponding to the vocabulary would be obtained from the SiteNavigationMenuItem table, while the hierarchy would be obtained directly from the AsseyCategory table, directly having everything necessary to render the menu item.

We believe that the performance difference between getting the hierarchy of the SiteNavigationMenuItem table or the AssetCategory table will depend mainly on the number of records. And in the second step, getting the needed item properties, the second approach is better.
It seems reasonable to us to assume that in a real installation there tend to be more SiteNavigationMenuItem records than AssetCategory if we take the first approach. This is because, in addition to the other existing menu item types, a category could be repeated N times in the SiteNavigationMenuItem table.

For these reasons, in this implementation, the second approach has been chosen, dynamically generating the menu hierarchy corresponding to a vocabulary.

Attached to the related task there is a big vocabulary (Fruits.lar) that could be useful for testing purposes.

Thanks a lot! ❤️

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Two minor things which can be changed in a follow up PR:
- Should we reanme categorySiteNavigationMenuItem to assetCategorySiteNavigationMenuItem?
- In AssetVocabularySiteNavigationMenuItemType:
Should we declare a variable for `typeSettingsUnicodeProperties.get("regularURL")` to avoid getting the value from the map twice?

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
