### PR TITLE
LPS-204954 - Cannot propagate changes from Site Template to Site when using Master Page

### PR DESCRIPTION
**Pull request by ruben-pulido**
This PR adds an integration test to the original PR: https://github.com/liferay-echo/liferay-portal/pull/14925

Original PR comment:

https://liferay.atlassian.net/browse/LPS-204954

Previously submitted under https://github.com/liferay-echo/liferay-portal/pull/14902 @ruben-pulido. Resending due to a few issues caught by @jorgediaz-lr.

The changes from the previous pull are:

1. Using a parameter to set the boolean for `privateLayout` instead of hard coded `0` and `1` due to differences in databases
2. Updating the layout's `layoutId` to avoid a potential conflict in the case of private pages existing in the site
3. Additionally updating the `LayoutFriendlyURL` table to reflect the change from public to private

If there are any questions or concerns please let me know.

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:upgrade

**Comment by ruben-pulido** [comment]
Job to analyze test results started here: https://test-1-1.liferay.com/job/generate-testray-csv/7812/

**Comment by jkappler** [comment]
Failure in test results is not related to the changes

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:report:2488097077

**Comment by Tim-Cao** [comment]
ci:report:2486845386

**Comment by Tim-Cao** [comment]
Hi @ruben-pulido, Failed upgrade process for module com.liferay.layout.service from 6.2 at postgresql
[data-archive-afs-store-postgresql.zip](https://github.com/liferay-echo/liferay-portal/files/13945072/data-archive-afs-store-postgresql.zip)
```
     [java] 2024-01-11 11:06:49.026 INFO  [main][UpgradeProcess:137] Failed upgrade process com.liferay.layout.internal.upgrade.v1_4_1.LayoutClassedModelUsageUpgradeProcess in 2 ms
     [java] 2024-01-11 11:06:49.028 ERROR [main][UpgradeExecutor:333] Failed upgrade process for module com.liferay.layout.service
     [java] com.liferay.portal.kernel.upgrade.UpgradeException: org.postgresql.util.PSQLException: ERROR: relation "fragmententrylink" does not exist
     [java]   Position: 174
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:128) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor._executeUpgradeInfos(UpgradeExecutor.java:202) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.executeUpgradeInfos(UpgradeExecutor.java:124) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.execute(UpgradeExecutor.java:85) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeExecutor.java:330) ~[?:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeExecutor.java:290) ~[?:?]
     [java] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$DefaultEmitter.emit(ServiceTrackerMapImpl.java:200) ~[com.liferay.osgi.service.tracker.collections.jar:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.lambda$activate$0(UpgradeExecutor.java:179) ~[?:?]
     [java] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerMapImpl.java:256) ~[com.liferay.osgi.service.tracker.collections.jar:?]
     [java] 	at com.liferay.osgi.service.tracker.collections.internal.map.ServiceTrackerMapImpl$ServiceReferenceServiceTrackerCustomizer.addingService(ServiceTrackerMapImpl.java:244) ~[com.liferay.osgi.service.tracker.collections.jar:?]
     [java] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:229) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:903) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:893) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:799) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:125) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:224) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:461) ~[org.eclipse.osgi.jar:?]
     [java] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:906) ~[?:?]
     [java] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:892) ~[?:?]
     [java] 	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:128) ~[?:?]
     [java] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:962) ~[?:?]
     [java] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:732) ~[?:?]
     [java] 	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1053) ~[?:?]
     [java] 	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1007) ~[?:?]
```

**Comment by Tim-Cao** [comment]
ci:test:upgrade

**Comment by Tim-Cao** [comment]
ci:report:2488519850

**Comment by Tim-Cao** [comment]
Hi @ruben-pulido, this issue only happens on your PR. Would you mind investigating?
https://github.com/liferay-echo/liferay-portal/pull/14964#issuecomment-1893023674

**Comment by jonathanmccann** [comment]
@ruben-pulido I'm wondering if rebasing this branch would fix the issue as it might not include the changes made in https://liferay.atlassian.net/browse/LPS-205274.

**Comment by ruben-pulido** [comment]
Hi @jonathanmccann 
Good point! I think what you are suggesting has a very good chance of fixing the issue. 
I have rebased and resolved the conflicts here: https://github.com/liferay-echo/liferay-portal/pull/15016

**Pull request closed without merging**
