### PR TITLE
LPS-185796 Improve accessibility in structure tree 

### PR DESCRIPTION
**Pull request by veroglez**
https://issues.liferay.com/browse/LPS-185796

The improvements made are the following:
- Improvements in the tree navigation doing in more consistent.
- SR feedback for item actions: Rename, delete, duplicate and hide.
- When the element is hidden, feedback is given when the sr reaches the element.
- There is no loss focus.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by claraizquierdo — COMMENTED** [review]
Hello @veroglez,

everything seem to be working fine. Just 3 issues/questions:
- Why adding a tabindex to the actions buttons? 
- I'm still getting a random error after performing a few actions when navigating with the keyboard :(
- In the description of the bug they say that: "_Navigation by arrows is not consistent, after tabbing in an item you cannot use the arrows up/down, you only can make it work again by using left/right_" But I don't see that fixed here. Maybe you plan to do it in another PR or maybe I didn't check it correctly.

**Comment by veroglez** [comment]
Hi @claraizquierdo!

I answer your questions below :)

> Why adding a tabindex to the actions buttons?

The tabindex in the actions buttons is related with Roving tabindex, https://www.w3.org/WAI/ARIA/apg/practices/keyboard-interface/#kbd_roving_tabindex. Roving tabindex is used to manage the focus in a component, in this way we can determine the elements that we want to be focusable.

> I'm still getting a random error after performing a few actions when navigating with the keyboard :(

This error is only reproduced for me when I have the Chrome Devtools open. It also happens to me in master :(. It's something we have to investigate.

> In the description of the bug they say that: "Navigation by arrows is not consistent, after tabbing in an item you cannot use the arrows up/down, you only can make it work again by using left/right" But I don't see that fixed here. Maybe you plan to do it in another PR or maybe I didn't check it correctly.

Yes, this is something that should be fixed in the Clay component. I already spoke with @marcoscv-work about this.

**Comment by claraizquierdo** [comment]
> Hi @claraizquierdo!
> 
> thanks for the review! I answer your questions below :)
> 
> > Why adding a tabindex to the actions buttons?
> 
> The tabindex in the actions buttons is related with Roving tabindex, https://www.w3.org/WAI/ARIA/apg/practices/keyboard-interface/#kbd_roving_tabindex. Roving tabindex is used to manage the focus in a component, in this way we can determine the elements that we want to be focusable.
> 
> > I'm still getting a random error after performing a few actions when navigating with the keyboard :(
> 
> This error is only reproduced for me when I have the Chrome Devtools open. It also happens to me in master :(. It's something we have to investigate.
> 
> > In the description of the bug they say that: "Navigation by arrows is not consistent, after tabbing in an item you cannot use the arrows up/down, you only can make it work again by using left/right" But I don't see that fixed here. Maybe you plan to do it in another PR or maybe I didn't check it correctly.
> 
> Yes, this is something that should be fixed in the Clay component. I already spoke with @marcoscv-work about this.

Thank you very much for your answers @veroglez . Then, this is ready to be merged :)

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Hi @veroglez ,  the ellipsis button has to be clicked twice to go to the drop  down menu,can you take a look? thanks!

here are the steps:

1. Add a content page
2. Add a asset publisher to the content page
3. Mouse overt to AP and click ellipsis icon

Actual result:
Only the AP's topper displays, you have to click ellipsis icon again to go to the drop dowqn menu.

https://github.com/liferay-echo/liferay-portal/assets/4900382/607aee59-f48c-4443-8da5-4e37c06aa57c


Expected result:
The drop dowqn menu is opened.

**Comment by veroglez** [comment]
Hi @liulukiwi, I have already fixed that you comment, could you check it? Thanks a lot!

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
sf failed for `Unable to execute Gradle task: :portalYarnCheckFormat`, will try again later...

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
Hi @veroglez , there's a  js unit failure found, can you take a look? thanks!

```
     [exec] > Task :apps:layout:layout-content-page-editor-web:packageRunTest FAILED
     [exec] PASS test/page_editor/app/components/fragment_configuration_fields/CSSClassSelectorField.test.js (13.095s)
     [exec] 
     [exec] Summary of all failing tests
     [exec] FAIL test/page_editor/app/thunks/deleteItem.test.js
     [exec]   ��� deleteItem ��� dispatches the delete item action with the portletIds of the removed portlets, if any
     [exec] 
     [exec]     TypeError: Cannot read properties of undefined (reading 'items')
     [exec] 
     [exec]       48 | 		}).then(
     [exec]       49 | 			({pageContents, portletIds = [], layoutData: nextLayoutData}) => {
     [exec]     > 50 | 				const [firstChild] = nextLayoutData.items[
     [exec]          | 				                                    ^
     [exec]       51 | 					nextLayoutData.rootItems.main
     [exec]       52 | 				].children;
     [exec]       53 | 
     [exec] 
     [exec]       at src/main/resources/META-INF/resources/page_editor/app/thunks/deleteItem.js:50:41
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec]       at Object.<anonymous> (test/page_editor/app/thunks/deleteItem.test.js:113:3)
     [exec] 
     [exec] 
```

**Comment by liulukiwi** [comment]
And not sure there's actually a sf issue here, can you also take a look?

**Comment by veroglez** [comment]
@liulukiwi Fixed!

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136583

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
