### PR TITLE
[TS] LPS-132521 Change AssetEntry.title to CLOB

### PR DESCRIPTION
**Pull request by vendeltoreki**
Dear @liferay-echo team,

[LPS-132521](https://issues.liferay.com/browse/LPS-132521) is a fix only for 7.4. The long-term solution will be [LPS-131417](https://issues.liferay.com/browse/LPS-131417).

I've created an upgrade step to change the `AssetEntry.title` column type to CLOB, based on the discussions on [PTR-2392](https://issues.liferay.com/browse/PTR-2392).

cc: @achaparro

Please review my changes.

Thanks,
Vendel

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @vendeltoreki,

We can't reuse the current UpgradeAssetEntry class because some CE users are already in 7.4 so they will miss this upgrade step. We need to create a new upgrade process.

Thanks

cc/ @ealonso

**Comment by vendeltoreki** [comment]
Thanks for the review @achaparro . I'm resending one with a new upgrade step. I will add it as a micro version change on top of the [latest one](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/upgrade/v7_4_x/PortalUpgradeProcessRegistryImpl.java#L63), i.e.: `new Version(12, 2, 1)`.

**Comment by achaparro** [comment]
yeah @vendeltoreki, that makes sense

Thanks!

**Pull request closed without merging**
