### PR TITLE
[TS] LPS-134443

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

could you please check my fix.

After the js logic is moved into a separate module (js/Source.js) we dont need to use the escapeJS, just the escape. 

**Steps to reproduce:**

1. Start a bundle
2. Create a structure, put some Date fields in it
3. Put special characters in the fields, like !^^Date, %Date, $\Date
4. Create a Dynamic Collection
5. Select the Web Content Article -> custom structure
6. Check the fields in the 'Order by' list

**Expected behavior:** FIelds are shown with decoded special characters, like '%Date'
**Current behavior:** Fields are shown with escaped special characters, like '\x25Date'

https://issues.liferay.com/browse/LPS-134443

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
Hey @rolandpakai,
We have the same behavior for AssetPublisher, Could you please take a look if we have the same problem there and fix it?

We have the same code in configuration/source.jsp line 248 of asset-publisher-web

```java
classTypeFieldsList.add(
	HashMapBuilder.<String, Object>put(
		"label", HtmlUtil.escapeJS(classTypeField.getLabel())
	).put(
		"selectedOrderByColumn1", selectedOrderByColumn1
	).put(
		"selectedOrderByColumn2", selectedOrderByColumn2
	).put(
		"value", value
	).build());

```

Thanks!!

**Comment by rolandpakai** [comment]
Hi @ealonso 

yes, sure, i will check it.

Roland

**Comment by rolandpakai** [comment]
Hi @ealonso 

yes, we can remove there too.
I force pushed this PR with this change,

Thanks, Roland

**Comment by ealonso** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reevaluate:1257401_1676

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
