### PR TITLE
LPS-102959 Apply responsive styles to widget pages with master pages

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by jpince** [comment]
Just started reviewing :)

**Comment by jpince** [comment]
Pushed to BChan's origin
https://github.com/brianchandotcom/liferay-portal/commit/db6c72986369c63e5dc73fc2c19f1cc95a7cebee
Added https://github.com/brianchandotcom/liferay-portal/commit/9c7d3d74594d2dc8e440d83a8a8fc382bdfd293e

**Comment by pavel-savinov** [comment]
ci:forward

**Pull request closed without merging**
