### PR TITLE
LPD-1668 Overwrite look and feel for class portlet-borderless

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Previous  #15018

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:stable

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
@georgel-pop-lr [modules-integration-mysql57-jdk8/0/6](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/885493//consoleText)
[com.liferay.layout.taglib.servlet.test.LayoutStructureCommonStylesCSSServletTest](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/885493/testReport/com.liferay.layout.taglib.servlet.test/LayoutStructureCommonStylesCSSServletTest) - [Failed 0 of last 23](https://testray.liferay.com/home/-/testray/case_results/2530490446/history) seems to be related with your changes

**Comment by georgel-pop-lr** [comment]
> ci:forward

Hi  @ealonso,

Thanks for checking this, I commit the fix for the test, not sure if you want to run again the test or we do a ci:forward

Regards.

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:report:2531389798

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
