### PR TITLE
LPS-147828 UpgradeAssetDisplayPageEntryTest fails on Oracle Database 19.3

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-147828 Set value to externalReferenceCode, since if it's null it causes issues with some DBs
- LPS-147828 Transform query, since condition is different depending on the DBs (Oracle treats != '' as unknown for example)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Pull request closed without merging**
