### PR TITLE
LPS-161373 New services to get articles by ID and status

### PR DESCRIPTION
**Pull request by jkappler**
[Jira task ticket](https://issues.liferay.com/browse/LPS-161373)

## Motivation

In Tango Team we are working on improving the information panel of content dashboard. One of this improvements is to show the [history of versions for a specific element](https://issues.liferay.com/browse/LPS-161013). So we are trying to implement this for web contents too. 

There are cases, depending on the user, were want to filter the web content articles that they can see by status. In the case of services of web contents, there's no service to achieve this, only one to retrieve all versions without filtering.

## Proposed solution

Since service.xml already has a finder for articleId and status, our proposed solution is to add this service to JournalArticleService. As usual, if no status is specified (ANY), we will retrieve based on current implementation.

## How to test it

Since this is not yet implemented in content dashboard, there's no way to test it in the UI. Still, we added integration tests for this. We also added a test for the existing service since there wasn't one for it.

Thanks Team!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
cc:// @cgoncas

**Comment by ozysouza** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/122187

**Comment by ozysouza** [comment]
ci:close

**Pull request closed without merging**
