### PR TITLE
LPD-1719 - When importing fragments sets is not overriding the title

### PR DESCRIPTION
**Pull request by ruben-pulido**
https://liferay.atlassian.net/browse/LPD-1719 - When importing fragments sets is not overriding the title

@georgel-pop-lr

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:reevaluate:1397401_9158

**Comment by ruben-pulido** [comment]
ci:report:2527827581

**Comment by ruben-pulido** [comment]
Rerunning the tests since the [Test Results Analysis CSV](https://test-1-19.liferay.com/userContent/jobs/generate-testray-csv/builds/4/testray-results.csv ) continues to be empty

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:report:2530456563

**Comment by ruben-pulido** [comment]
ci:reevaluate:1277401_11209

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
