### PR TITLE
LPS-150463 We can't remove filter styles that have default value in responsive viewports

### PR DESCRIPTION
**Pull request by victorg1991**
### References

- Story: https://issues.liferay.com/browse/LPS-147783
- Epic: https://issues.liferay.com/browse/LPS-132571

### What is the goal of this PR?
This PR moves the common styles css styles to a `<style>` tag 

### What does it look like?
- It creates a new `DynamicInclude` that is injected in the `<head>` of the page.
- Modifies the common-styles.json to add CSS styles templates for abstracting that part
- Now each layout structure item has a unique className where the styles will be applied: `lfr-layout-structure-item-<item-id>`
- When rendering each layout structure item, the css class and the styles of the common styles are not rendered, with a few exceptions:
    - Background image uses an adaptive media processor  that relies in the element having a `--background-image-file-entry-id` css variable
    - Also, the url of the background image is also added to a CSS variable `--lfr-<item-id>-background-image`, so that when the adaptive media doesn't apply (for example if the image comes from an url instead of the D&M). This is not mandatory but calculating it here is cheaper than having to move the calculation to the `DynamicInclude`.

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by victorg1991** [comment]
@ruben-pulido I have applied the changes we've talked :)

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Conflicts solved [here](https://github.com/liferay-echo/liferay-portal/pull/7642)

**Pull request closed without merging**
