### PR TITLE
LPS-137566 Update and standardize templates help text

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-137566

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Review by ealonso — APPROVED** [review]

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:forward

**Pull request closed without merging**
