### PR TITLE
LPS-119565 Add adapter classes where we have to make sure that our styles are not altered by the theme

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by victorg1991** [comment]
@Tim-Cao Checking out the ci errors I think we have to update some poshi tests, maybe we can check it together tomorrow? :)

**Comment by jpince** [comment]
@p2kmgcl @victorg1991 @martaeli https://issues.liferay.com/browse/LPS-119565 was transitioned to Closed and as a result marked as fixed in CE GA6/DXP GA1. Why are we continuing to add commits? Was it not fully fixed? This is potentially confusing to customers.

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/2601

**Comment by Tim-Cao** [comment]
ci:close

**Comment by victorg1991** [comment]
Hey @jpince,  I used the wrong Jira issue number, LPS-119565 was solved, I've updated the jira tickets accordingly, changed the commit messages, and sent it here with the correct ones: https://github.com/liferay-echo/liferay-portal/pull/2607  sorry for the confusion!

**Pull request closed without merging**
