### PR TITLE
LPS-131992 Check for valid values instead of not null

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
There are more use cases for this

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
LGTM!

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
> LGTM!

Los Gatos Toman Malta, correct, that's true

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
I think we may need to update some poshi test for this PR, can you take a look at it @Tim-Cao ?? Thanks :D

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/4550

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
