### PR TITLE
LPS-197422 Add cadmin class to the Picker in Simulation panel and Experience Selector component

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by veroglez** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward:force

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/141440

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
