### PR TITLE
LPS-181172 Create configuration to control which users can see the control menu

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-181172

cc: @Mikellorza

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1377401_11098

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by alessandromalves** [comment]
resent here https://github.com/liferay-echo/liferay-portal/pull/11949

**Pull request closed without merging**
