### PR TITLE
LPS-131407 Change default preferences for Asset publisher like portlets

### PR DESCRIPTION
**Pull request by victorg1991**
Setting this as on hold until https://issues.liferay.com/browse/LPS-148093 is resolved

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
Hi @victorg1991, I've resent here with upgrade Poshi cases updates.
https://github.com/liferay-echo/liferay-portal/pull/7369

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
