### PR TITLE
LPD-15572 - Failed upgrade process for module com.liferay.layout.service from 7.0.10.6 to master

### PR DESCRIPTION
**Pull request by ruben-pulido**
https://liferay.atlassian.net/browse/LPD-15572 - Failed upgrade process for module com.liferay.layout.service from 7.0.10.6 to master

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:report:2531457421

**Comment by achaparro** [comment]
@ruben-pulido it seems there are no unique failures in the ci:test:upgrade suite

**Comment by ealonso** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
Thanks a lot for checking @achaparro!

**Comment by ruben-pulido** [comment]
ci:report:2531534028

**Comment by ruben-pulido** [comment]
ci:forward:force

**Pull request closed without merging**
