### PR TITLE
LPS-134332 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-134332

This is only for master.

@jkappler

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The failure tasks are unrelated to changes in PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/103488

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
