### PR TITLE
LPS-110324 Change Smoke to be more stable

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
https://issues.liferay.com/browse/LPS-109350

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
ci:test

**Comment by david-gutierrez-mesa** [comment]
ci:test

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/274

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
