### PR TITLE
LPS-115439 Adds PermissionCheckerMethodTestRule to integration test class

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@ruben-pulido, same failures as draft of fragments, seems we have some real poshi failures in upstream

**Comment by victorg1991** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by victorg1991** [comment]
@ealonso resent here https://github.com/liferay-echo/liferay-portal/pull/1084 I forgot to close this one

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci

**Pull request closed without merging**
