### PR TITLE
LPS-200157 Make sure we always render fragments in render phase

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @victorg1991, the Applied Filters and Collection Filter fragments are rendered wrong.
image
image

**Comment by victorg1991** [comment]
Thanks @Tim-Cao 

This was caused by https://liferay.atlassian.net/browse/LPS-191314 I'm contacting the people involved

**Pull request closed without merging**
