### PR TITLE
LPS-179280 Integrate Tango test suites inside Echo team ones

### PR DESCRIPTION
**Pull request by david-gutierrez-mesa**
https://issues.liferay.com/browse/LPS-179280

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by david-gutierrez-mesa** [comment]
ci:test:echo-analytics-cloud

**Comment by david-gutierrez-mesa** [comment]
ci:test:echo-analytics-cloud

**Comment by david-gutierrez-mesa** [comment]
ci:test:echo

**Comment by david-gutierrez-mesa** [comment]
ci:test:echo-acceptance

**Comment by david-gutierrez-mesa** [comment]
ci:test:echo-analytics-cloud

**Comment by david-gutierrez-mesa** [comment]
ci:test:sf

**Comment by david-gutierrez-mesa** [comment]
Rebase fix here: https://github.com/liferay-echo/liferay-portal/pull/11531

**Pull request closed without merging**
