### PR TITLE
LPS-135943

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Related ticket: https://issues.liferay.com/browse/LPS-135943

### CODE REVIEW

**Comment by rodrigopaulino** [comment]
⚠️  Only the last two commits need to be reviewed here. The other ones are necessary since LPS-135943 depends on LPS-135942 for testing purposes. The beginning of this pull is identical to https://github.com/liferay-echo/liferay-portal/pull/5510 as I'm writing this comment.

**Comment by rodrigopaulino** [comment]
ci:test:sf

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by rodrigopaulino** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
See: https://github.com/liferay-echo/liferay-portal/pull/5555

**Pull request closed without merging**
