### PR TITLE
LPS-177285 Split Site Initializers and Site Templates into two sections

### PR DESCRIPTION
**Pull request by alessandromalves**
Split Site Initializers and Site Templates into two sections
image

This is only for master
https://issues.liferay.com/browse/LPS-177285
https://issues.liferay.com/browse/LPS-177348
cc.: @ealonso @david-gutierrez-mesa

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by alessandromalves** [comment]
ci:test:sf

**Comment by alessandromalves** [comment]
Resent based on https://github.com/liferay-echo/liferay-portal/pull/11314

**Comment by alessandromalves** [comment]
ci:test:relevant

**Comment by alessandromalves** [comment]
ci:forward

**Comment by ealonso** [comment]
Manual forward: https://github.com/brianchandotcom/liferay-portal/pull/131197

**Pull request closed without merging**
