### PR TITLE
LPS-112643 Fixing size of Miller Columns to maximize their space in the screen but considering Control Menu, Navigation Bar, Management Bar, breadcrumbs and bottom space according to Lexicon pattern

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
