### PR TITLE
LPS-138079 As of LPS-112527 we don't allow certain characters in the name of the LayoutPageTemplateEntry, so it's safe to remove the escape from the name

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
