### PR TITLE
[TS] LPS-172057

### PR DESCRIPTION
**Pull request by crodriguezy**
Motivation
=======
This fix solves case described in https://issues.liferay.com/browse/LPS-172057

Proposed Solution
========
Apply the same formatting logic of NumericDDMFormFieldUtil in TemplateNode.

Steps to Verify
========
Steps to reproduce:

1. Create a new structure and add a Numeric (integer) field.
2. Add a template for 'test' displaying the field.
3. Create a new 'test' content, and fill the value: 8
4. Save as draft.
5. Add the 'ar' locale to the URL, so the edition page is displayed in arabic.
6. Visualize the arabic content through the template (through the "eye" icon)

### CODE REVIEW

**Comment by crodriguezy** [comment]
Hello team @liferay-echo , does this PR look ok to you?
Thanks! :)

**Comment by jkappler** [comment]
Hi @crodriguezy, can you please help us by filling the Pull Request Template -> https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md?

Thanks!

**Comment by crodriguezy** [comment]
Hey @jkappler I've updated the description, please let me know if you need anything else :)

**Review by lfbesada — APPROVED** [review]
Hi @crodriguezy 
Thanks for the fix! 
LGTM 🎉 
Regards

**Comment by lfbesada** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128643

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
