### PR TITLE
LPS-206124 Allow fragments update their name when importing with over…

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
…write option

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@ruben-pulido you are most likely going to ask this :D

@georgel-pop-lr, could you please add a tests for this? Thanks!

**Comment by ruben-pulido** [comment]
We need to handle the case where there are both a published fragment and a draft. I have tried to cover that case here:
https://github.com/georgel-pop-lr/liferay-portal/pull/39

**Comment by ruben-pulido** [comment]
https://github.com/liferay-echo/liferay-portal/pull/15057

**Pull request closed without merging**
