### PR TITLE
[7.4 Only] LPS-122894 Replace menu editor with new React implementation

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
@Tim-Cao could you have a look at this? We've migrated the editor to React and we might need to update some poshi tests

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, Could you check your codes again? The plus icon button is frozen and the following error is thrown in browser console. Due to most navigation menus created by json web service, this issue is unintuitive in testray report.
BrowserConsole

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/2822

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
