### PR TITLE
[TS] LPS-171968 No need to set before clearing

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

As per Brian's [comment](https://github.com/brianchandotcom/liferay-portal/pull/128857#issuecomment-1385922395), I have removed the logic that saves the output before clearing.

Best regards,
István

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1297401_6198

**Comment by jkappler** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Hi @IstvanD 
Thanks for the fix!
LGTM 🎉 
Regards

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
