### PR TITLE
LPS-167491 Use simple repository browser tag for fragment resources

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to task](https://issues.liferay.com/browse/LPS-167491)

Lima Team introduced in LPS-165648 a new taglib that offers a limited interface to browse and operate on repository documents and folders. 

## Proposed solution

Use the new taglib in fragment set resources view instead of the custom view, since we will benefit of all the new features and standardize views across components 

## Change summary:

* If feature flag is activated, then we will show the view with the taglib, otherwise we will show the old view

## Test Scenario

* Start portal with FF LPS-158675 activated
* Go to Design > Fragments and create a new fragment set
* Go to Resources tab
* Here we will be able to interact with resources for the fragment set

browser

## Notes

* Resources are maintained if switching FF on/off
* Resources are unique per collection

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:reevaluate:1257401_5256

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/125798

**Pull request closed without merging**
