### PR TITLE
LPS-144559 Hide site selection (breadcrumb), since we only allow to select pages from the current site, not from other sites.

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @jkappler, the failure is unrelated to changes. If this PR is ready for merge, feel free to let me know.

**Comment by jkappler** [comment]
Hi @Tim-Cao, yes, lets proceed. Thanks!

**Comment by Tim-Cao** [comment]
The failure test is unrelated to this PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/111945

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
