### PR TITLE
[TS] LPP-48522>LPS-182407 Prevent xss in liferay-asset:select-asset-display-page

### PR DESCRIPTION
**Pull request by ces-quanhuynh**
Hi team,
## Motivation
This PR is for fixing [LPS-182407](https://issues.liferay.com/browse/LPS-182407)

## Proposed solution

As Minhchau recommend
>It is able to reproduce the issue in master using blogs by setting a breakpoint here:
>
>https://github.com/liferay/liferay-portal/blob/7.4.3.75-ga75/modules/apps/asset/asset->taglib/src/main/java/com/liferay/asset/taglib/internal/display/context/SelectAssetDisplayPageDisplayContext.java#L276
>
>And setting the viewInContextURL to themeDisplay.getURLCurrent() the way that https://github.com/liferay/liferay->portal/blob/7.4.3.75-ga75/modules/apps/journal/journal->web/src/main/java/com/liferay/journal/web/internal/asset/model/JournalArticleAssetRenderer.java#L418 does.

That why we should fix on master as well.
This is the previous discussion with Minhchau about this issue https://github.com/holatuwol/liferay-portal-ee/pull/156
So we decide to add HtmlUtil.escapeJS to solve this problem

The https://github.com/ces-quanhuynh/liferay-portal/pull/27 was passed my review
Please review and leave your comment.
Thanks,
Quan
cc @locpham97 @holatuwol

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
Hi @ces-quanhuynh 

Thanks for the pull request!

I am afraid I can't review it because of the following:

1. The reported bug has never been verified by QA
2. This PR has source formatting issues

In addition, when a pull request is sent, the related ticket status should be set as In Review and assigned to the product team.

Please, if QA verifies the bug, resend the pull request after fixing the source formatting issue and setting the proper status in the ticket.

Regards

**Pull request closed without merging**
