### PR TITLE
[TS] LPS-124229 Move the input check inside the addEventListener

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

could you please check my fix?

The LPS-90336 changes caused a regression with this commit: https://github.com/liferay/liferay-portal/commit/d3eff975ca03#
The toggleSubclasses function is not added to the eventlistener, becuase the ddmStructureFieldNameInput and ddmStructureFieldValueInput are null objects
https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-publisher-web/src/main/resources/META-INF/resources/configuration/source.jsp#L482-L486

Moving the if check inside the addEventListener the event is working again.

See details on https://issues.liferay.com/browse/PTR-2197

Thanks, Roland

https://issues.liferay.com/browse/LPS-124229

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
Hi @veroglez 

could you please push this forward?

Thanks, Roland

**Comment by ealonso** [comment]
Hey @rolandpakai,
We are trying to do that, but as you can see the pull is not in green.

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
