### PR TITLE
LPS-120702 Move DropZone component to same file as it's not being used elsewhere

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Rebase then resend. See https://github.com/liferay-echo/liferay-portal/pull/2369

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
