### PR TITLE
LPS-202697 BuildLang

### PR DESCRIPTION
**Pull request by veroglez**
This PR adds a new parameter to the `aui:input` and `ui:input-localized` taglibs, so it will be also reviewed FI team

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
looks good @veroglez ❤️

**Comment by p2kmgcl** [comment]
Awesome :smile:

**Comment by veroglez** [comment]
Waiting for the review of https://github.com/liferay-frontend/liferay-portal/pull/3876

**Comment by veroglez** [comment]
ci:forward

**Comment by liulukiwi** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/145234

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
