### PR TITLE
LPS-196830 Copy naming for Stylebook should follow the pattern

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-196830)

### Changes

Add a method to get a unique name when copying StykeBooks

## Test scenario 1

1. Go to Stylebooks
2. Create a stylebook
3. Copy the stylebook
4. Copy the same stylebook a few times and check the names

## Results

https://github.com/liferay-echo/liferay-portal/assets/93203423/f6924838-856b-4a68-bd7b-09f61068ec6b

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward:force

**Pull request closed without merging**
