### PR TITLE
LPS-147972 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-147972

This is only for master.

@victorg1991

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:help

**Comment by Tim-Cao** [comment]
Hi @victorg1991
Cannot select associate page in web content editor.
**Steps to reproduce**

1. Add an Asset Publisher to a widget page
2. Set as the Default Asset Publisher for This Page
3. Add a web content
4. Associate the page as specific display page template
5. Select the page

**Expected Results:**
The page could be selected.

**Actual Results:**
Nothing happens. The following error is thrown
image

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/8168

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
