### PR TITLE
LPS-176836 | Test Fix | Master

### PR DESCRIPTION
**Pull request by rafaellajordao**
# Element is not present at ContentPerformance#NoNavigationWithoutIncomingTraffic

Hi! :)
This pr is corresponding to this ticket: [LPS-176836](https://issues.liferay.com/browse/LPS-176836)

**Problem:**
Data does not arrive in time for checking on the Content Performance page.

**Fix:**
Substitution of values for "-" because we understand that If the value is -, it also means no incoming traffic. The - and 0 are the same for our case

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
LGTM!

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
