### PR TITLE
[7.4-only] LPS-121961 - Migrate v2 usages of clay:vertical-card in fragment/fragment-web

### PR DESCRIPTION
**Pull request by julien**

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Review by carloslancha — APPROVED** [review]

**Comment by victorg1991** [comment]
Hey @julien 
If you deploy this pr and navigate to the fragment UI a null pointer exception is thrown

It seems that a nullity check is missing [here](https://github.com/liferay/liferay-portal/blob/86da0d6891c600ea2d3c8eca5da03274d06feb57/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/BaseCardTag.java#L35-L43)

Could you update the pr?

Something like this should be enough:

```java
Map<String, String> dynamicAttributes = Optional.ofNullable(
     _cardModel.getDynamicAttributes()
).orElse(
     Collections.emptyMap()
);
```

**Comment by victorg1991** [comment]
It may probably affect others pr too

**Comment by julien** [comment]
Hey @victorg1991 thanks for the tip, let me try that.

**Comment by julien** [comment]
@ealonso so you want me to resent a PR or did you accidentally close?

**Comment by ealonso** [comment]
Yes, fix an resend

**Pull request closed without merging**
