### PR TITLE
LPS-192060 Rename layoutReportsTabsURL and segmentExperienceSelectorData

### PR DESCRIPTION
**Pull request by veroglez**
Just review the last commit 2666c5a471775b104bac7cc11fb3f681068deff1. This PR is part of https://github.com/liferay-echo/liferay-portal/pull/13114

**How to test?**
- The Page Speed Insight tab in Page Audit panel has to work perfectly.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139322

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
