### PR TITLE
LPS-196191 Add context title to back button in Journal module

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-196191)

## Test scenario 1 
1. Create a Web content and/or edit one.
2. Check the back button tooltip. Should follow the “Go to x” pattern.
3. Also go the kebab menu of actions for the web content and choose “Move”
4. Check again the back button tooltip. Should follow the “Go to x” pattern.

Pasted Graphic 12

## Test scenario 2 
1. Create a Web content and create some versions doing changes and saving it
2. Go the kebab menu of actions for the web content and choose “View history”.
3. Open the kebab menu and select “Compare to…” and select one version.
4. Check again the back button tooltip. Should follow the “Go to x” pattern.

Pasted Graphic 3

## Test scenario 3 
1. Create a Web content and create some versions doing changes and saving it
2. Go the kebab menu of actions for the web content and choose “View history”.
3. Check again the back button tooltip. Should follow the “Go to x” pattern.

Pasted Graphic 14

6.  Now try to copy it from the kebab menu for actions and check again the back button tooltip. Should follow the “Go to x” pattern.

Pasted Graphic 4

## Test scenario 4 
1. Create a new structure.
2. Check the back button tooltip. Should follow the “Go to x” pattern.

Pasted Graphic 9

4.  Now try to copy it from the kebab menu for actions and check again the back button tooltip. Should follow the “Go to x” pattern.

Pasted Graphic 5

## Test scenario 5 
1. Create a new template.
2. Check the back button tooltip. Should follow the “Go to x” pattern.

Pasted Graphic 8

4.  Now try to copy it from the kebab menu for actions and check again the back button tooltip. Should follow the “Go to x” pattern.

Pasted Graphic 10

## Test scenario 6 
1. Activate “Show Feeds” for Web Content in System Settings.
2. Check the back button tooltip. Should follow the “Go to x” pattern.

Pasted Graphic 15

4. Create a new feed.
7. Check again the back button tooltip. Should follow the “Go to x” pattern.

Pasted Graphic 11

## Test scenario 7 
1. Create a Web content folder and/or edit one.
2. Check the back button tooltip. Should follow the “Go to x” pattern.

Pasted Graphic 2

## Test scenario 8 
1. Create a Web content and choose the “View usages” in the dropdown for actions.
2. Check the back button tooltip. Should follow the “Go to x” pattern.

Pasted Graphic 13

4. Open the kebab menu and select “View in page” for one usage.
6. Check again the back button tooltip. Should follow the “Go to x” pattern with the web content name.

Pasted Graphic 16

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
