### PR TITLE
LPS-202724 Wrap form sections in a group

### PR DESCRIPTION
**Pull request by p2kmgcl**
Just needs review for the last three commits, the rest have been reviewed in this other PR: https://github.com/liferay-echo/liferay-portal/pull/14569

cc @veroglez

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
Backend review done in the previous PR: https://github.com/liferay-echo/liferay-portal/pull/14569

**Comment by veroglez** [comment]
Marvelous :heart_eyes:

**Review by lfbesada — APPROVED** [review]
LGTM :tada:

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward:force

**Pull request closed without merging**
