### PR TITLE
Lps 99336

### PR DESCRIPTION
**Pull request by JavierMoral**
Hi team, this pull fixes [LPS-99336](https://issues.liferay.com/browse/LPS-99336)
Could you take a look at it? Thanks

I did not dare to deprecate the entire JournalCreationStrategy class because I'm not 100% sure if the remaining methods of this class have some kind of use or not but it would probably make sense.
I deprecated the "add*Permissions" methods because they were interfering with the calculation of these permission related properties made in the portlet data context [made here](https://github.com/liferay/liferay-portal/blob/4ec72ac348bb90ebc4514a3e096528a2077fc5a9/modules/apps/export-import/export-import-service/src/main/java/com/liferay/exportimport/internal/lar/PortletDataContextImpl.java#L1887)

### CODE REVIEW

**Comment by JavierMoral** [comment]
ci:test

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
