### PR TITLE
LPS-129064 Change page definition for home page

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
ci:test

**Comment by david-gutierrez-mesa** [comment]
ci:test:stable

**Comment by david-gutierrez-mesa** [comment]
ci:test:stable

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/4045

**Pull request closed without merging**
