### PR TITLE
LPS-179281 Web Content article do not expire correctly when database partitioning is enabled

### PR DESCRIPTION
**Pull request by jkappler**
https://issues.liferay.com/browse/LPS-179281

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Review by lfbesada — APPROVED** [review]
Amazing 😍

**Comment by lfbesada** [comment]
ci:reevaluate:1407401_1215

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:echo

**Comment by jkappler** [comment]
just launching tests again even though they don't seem related.....

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
