### PR TITLE
LPS-118321 Simplify FragmentContentProcessor

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by jpince** [comment]
ci:forward @p2kmgcl forwarding this critical issue since I saw your `ci:forward` comment above

**Comment by Tim-Cao** [comment]
@jpince, thanks

**Pull request closed without merging**
