### PR TITLE
LPS-test Add macros to add segment entry via JSONWS

### PR DESCRIPTION
**Pull request by Tim-Cao**
I only implemented macros to add segment entry with single field. There is a simple test to validate.
See https://github.com/liferay-echo/liferay-portal/pull/4292/commits/b24dcf62953f0d3cad61c3dd0ec81f76c5714531

@CarlosBrichete

### CODE REVIEW

**Comment by CarlosBrichete** [comment]
Just started reviewing :)

**Comment by Tim-Cao** [comment]
ci:test:nocompile

**Comment by Tim-Cao** [comment]
ci:test:nocompile

**Comment by Tim-Cao** [comment]
ci:test:nocompile

**Comment by Tim-Cao** [comment]
Hi @CarlosBrichete, All issues are resolved. LGTM!

**Comment by CarlosBrichete** [comment]
Just started reviewing :)

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
