### PR TITLE
LPS-129443 Publish page once all changes are saved

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @sandrodw3, Cannot click the Publish button in page editor via Poshi and Javascript with your changes. Could you have a look at?
Try use the following codes in browser console.
```
var element = document.evaluate("//*[contains(@class,'btn')][normalize-space(text())='Publish']", document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
var event = document.createEvent('MouseEvent');
event.initEvent('click', true, false);
element.dispatchEvent(event);
```

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
@Tim-Cao I fixed that issue, let's see how relevant goes this time 🤞

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
@Tim-Cao could you take a look at the test that are still failing? 🙏

**Comment by Tim-Cao** [comment]
Hi @sandrodw3, Still nothing happens when click the Publish button in page editor via Poshi with your changes. Could you have a look at? The js click already works but Poshi invokes selenium function.
Try to run the following case in source directory
`ant -f build-test.xml run-selenium-test -Dtest.class=ContentPages#EditContentPage`

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
Thanks @Tim-Cao 🙂 let's put our biggest 🕯 for this time 😂

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:stable

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
