### PR TITLE
LPS-112527 Ensure generated keys and names are unique.

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@ealonso

**Comment by marianoalvarosaiz** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/560

**Pull request closed without merging**
