### PR TITLE
LPS-121878 This is also needed since we don't have sorting

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @victorg1991 and @julien, there is a regression issue caused by this PR.
The Select All button cannot be checked when there is only react fragment in collection.
Actual
It should be like the following screenshot
Expected
Even though the react fragment cannot be exported, it doesn't make sense the Select All button is enabled but cannot be checked.

**Comment by julien** [comment]
Hi @Tim-Cao thanks for reporting the error.

I didn't actually test that part when doing the changes, because I completely forgot that in order to import "React" fragments, we need to install and use [generator-liferay-fragments](https://github.com/liferay/generator-liferay-fragments).

I installed the fragment generator and imported a fragment collection; both in `master` and in this branch.

This is how it looks in `master` (using `<clay:management-toolbar-v2>`) 



As you can see, the management toolbar let's us select all items, but since the "react" fragment is not selectable (you'll notice it doesn't have a checkbox) it doesn't let us delete it.

This is how it looks in this branch (using `<clay:management-toolbar>`)

recording (2)

In this case, the management toolbar selects only items that are selectable, and once those are deleted, it doesn't let you select the remaining fragment because it isn't.

Another thing to take in account, is that in `master` although the management toolbar let's you "select" the React fragment, it actually doesn't do anything once it's selected. 

Since a gif is worth 1000 words, this is what I mean:



You'll see that when using the management toolbar's "select all" feature, in this case it doesn't really change anything, you can do anything with the selection.

When discussing this with @victorg1991 we actually think that the behavior in this branch makes more sense than in `master`

**Comment by Tim-Cao** [comment]
Hi @julien, Why don't disable select all checkbox when there is only react fragment? It could make more sense to user.
Expected

**Comment by julien** [comment]
Hi @Tim-Cao,
I didn't do it for two reasons: 
- It doesn't seem to be the goal of this task
- I'd rather have the approval from the team before doing this kind of change.

**Comment by Tim-Cao** [comment]
Hi @victorg1991, could you cherry-pick my commits then rerun forward?
https://github.com/liferay-echo/liferay-portal/pull/3902

**Comment by victorg1991** [comment]
Let's just ci:forward the other one :)

**Comment by victorg1991** [comment]
forwanding this here: https://github.com/liferay-echo/liferay-portal/pull/3902

**Pull request closed without merging**
