### PR TITLE
[TS] LPS-119215

### PR DESCRIPTION
**Pull request by wanderlast**
From @kevhlee:

> LPS Ticket: <https://issues.liferay.com/browse/LPS-119215>
> 
> The issue is that when the key combination `Shift + Enter` is entered, the key code is `2228237` rather than `13`. This is expected as CKEditor creates a specific key code for `Shift + Enter` by adding the key codes of `Shift` (`2228224`) and `Enter` (`13`). Thus, we must explicitly check for this key combination and cancel the event when the combination occurs.
> 
> Let me know if you have any questions.

### CODE REVIEW

**Comment by p2kmgcl** [comment]
Thanks @wanderlast, I'll have a look :smile:

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
I'm going to check this locally

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/2205

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/2205

**Comment by p2kmgcl** [comment]
ci:close

**Pull request closed without merging**
