### PR TITLE
LPS-186873 Empty state title is not translated

### PR DESCRIPTION
**Pull request by veroglez**
https://issues.liferay.com/browse/LPS-186873

Currently if an ClayEmptyState has no title, by default a title is added which is always in English. To avoid this, we need to add a translated title. The same goes for the description.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:stable

**Comment by liulukiwi** [comment]
ci:forward

**Comment by liulukiwi** [comment]
resend with test-fix here: https://github.com/liferay-echo/liferay-portal/pull/12431

**Pull request closed without merging**
