### PR TITLE
LPS-127769 & LPS-127771 fileEntryId everywhere

### PR DESCRIPTION
**Pull request by p2kmgcl**
/cc @sandrodw3 
/cc @ruben-pulido 

__FrontEnd__: we are basically enabling all "in progress" cells in this [document](https://docs.google.com/spreadsheets/d/1IQgYKwjXGZ8_nGsssnSz4o4A6ZDIHR5Vpb6dVAj1Nb4/edit#gid=0) (needs to set `adaptiveMediaEnabled` feature flag to `true`).

__BackEnd__: I've injected `fileEntryId` both for `InfoItemService` and `CollectionService`, but this looks like a lot of duplication, I am not sure if we can prevent that.

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Thanks @p2kmgcl!

I am OK with that duplicating that piece of code in two places.
When we tackle editable background images, if we see we need the same code on a third place I am in favour of extracting it

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
