### PR TITLE
[TS] LPS-170849

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-170849

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @ChrisKian 
Thanks for the fix!
This PR needs to be reviewed by core-infra, could you please send them the PR?
Thank you!

**Comment by ChrisKian** [comment]
Thanks @lfbesada, I've submitted the PR to core: https://github.com/liferay-core-infra/liferay-portal/pull/2713

**Pull request closed without merging**
