### PR TITLE
[TS] LPS-124315

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

After the introduction of the possibility of configuring virtualhost per language in LPS-44217, it is not possible to change the language via Language Selector widget since it is not longer possible to rely on i18nFilter to prepend the language prefix and make the language change effective.

This solution tries to detect that a virtualhost per language is active and prepares the redirect to prepend or remove the proper language prefix.

Could you please review it? If you think that this PR should be send to someone else, please, let me know who.

Please, also let me know if further clarifications are needed.

Thanks in advance

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @dacousalr,
Those kind of changes in portal-impl are being reviewed by the Core Infra Team.
Could you please sent it to them?
Regards,
Eudaldo.

**Pull request closed without merging**
