### PR TITLE
[7.4-only] LPS-121958 Migrate v2 usages of clay:vertical-card in asset-display-page-item-selector-web

### PR DESCRIPTION
**Pull request by julien**
**Original PR and review**: https://github.com/liferay-frontend/liferay-portal/pull/502

In this change, we replace <clay:vertical-card-v2 />(clay 2.x:
Metal+soy) with
<clay:vertical-card /> (clay 3.x: React)

Test plan

- Fetch this branch
- Deploy the `asset-display-page-item-selector-web` module
- Navigate to **Design** > **Pages Templates**
- Select the **Display Page Templates** tab
- Click on the **+** button to create a new Display Page Template
- Click on the **Blank** Card
- In the modal window that appears, type in a name for your new Display Page
Template
- In the **Content Type** field, select **Web Content Article**
- In the **Subtype** field, select **Basic Web Content** and click on
the **Save Button**
- Click on the **Publish Button** to publish this new Display Page
Template
- Navigate to **Content & Data** > **Web Content**
- Click on the **+** button to create a new **Web Content**
- Enter a title and some content for this **Web Content**
- In the sidebar on the right, toggle the **Display Page Template**
field
- Select **Specific Display Page Template**
- Click on the **Select** button
- In the modal window, click on the **Display Page Template** you
created previously
- Click on the **Publish** button

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
@p2kmgcl, @liferay-echo just so you know, we've replaced `<vertical-card-v2 />` with `<vertical:card />`, but it seems that this could be a `<clay:navigation-card />` which will be done in https://github.com/liferay-frontend/liferay-portal/pull/503, , so we recommend you to migrate this vertical card to a navigation card once is merged.

/cc @ealonso @atjuan

**Comment by p2kmgcl** [comment]
LGTG! :partying_face:

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
