### PR TITLE
LPS-186285 Export / Import single page with a single fragment without references

### PR DESCRIPTION
**Pull request by jkappler**
https://issues.liferay.com/browse/LPS-186285

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:echo

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by jkappler** [comment]
@ruben-pulido, as expected, we need to update a test: LocalFile.FragmentsExportImport#ExportImportCollectionViewFragment

Will take a look on Monday

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by alessandromalves** [comment]
The failures are not related to this PR ([see comparison with acceptance routine results](https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=2340235014&testrayRunIdA=2327898350&statusB=3)). See https://github.com/brianchandotcom/liferay-portal/pull/135844

**Pull request closed without merging**
