### PR TITLE
LPS-173123 Add support for title and name description

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-173123 Reintroduce code that was removed by mistake and is necessary for the pages tree in staging. This partially reverts 5cac84b7d42a5ce9e583890fb6db48774f262fb7
- LPS-173123 Remove those that are no longer needed
- LPS-173123 Add support for item title and name description and also change name color when page is incomplete
- LPS-173123 buildLang
- LPS-173123 There could be 3 columns
- LPS-173123 Improve file structure

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@sandrodw3 , @ealonso

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
