### PR TITLE
LPS-127106 Reuse resolveEditableValue

### PR DESCRIPTION
**Pull request by p2kmgcl**
_The only Java commit_: https://github.com/liferay-echo/liferay-portal/pull/3621/commits/59c0933b3298a3287971a972207d69cc66106b8b

FronEnd secrets: I've make a bit of refactor in order to prepare for "layout" mapping, something that needs to be added on the next task. There is also a bit of random fixing all the things :woman_shrugging:

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
> > This must be false
> 
> or just remove the line :D

I'll create a DEFAULT_HIDDEN_PAGES value constant in frontend, that is sent to backend and then the displaycontext recalculated. This is much more efficient

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
https://github.com/p2kmgcl/liferay-portal/pull/727

**Pull request closed without merging**
