### PR TITLE
LPS-143666 Check for duplicated virtual hosts

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-143666 New finder to retrieve all virtual host by name that don't belong to a specific layout set
- LPS-143666 Build service
- LPS-143666 New method based on the finder that we created
- LPS-143666 Build service
- LPS-143666 Use new method. Basically we check for the constraint that exists, that is, that there cannot be duplicated virtual hostnames, so fail gracefully
- LPS-143666 Baseline

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:forward

**Comment by liulukiwi** [comment]
No unique failures after checking, will send to BChan directly.

**Comment by liulukiwi** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/120929

**Pull request closed without merging**
