### PR TITLE
LPS-145232 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-145232

This is only for master.

@victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
FYI, @victorg1991, failure cases are unrelated to your changes. I've made some changes to make poshi robust.

**Comment by victorg1991** [comment]
Sure @Tim-Cao I'll do

**Comment by victorg1991** [comment]
Thanks for your help!!

**Comment by victorg1991** [comment]
resent here: https://github.com/liferay-echo/liferay-portal/pull/7187

**Pull request closed without merging**
