### PR TITLE
LPS-167619 Text and modal size of fragment cards

### PR DESCRIPTION
**Pull request by BarbaraCabrera**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
Hey @BarbaraCabrera, nice work 🥰 just some tiny things:
- I think we don't need to specify 600px `max-width` as it's the default value for the modal, just removing the 700px line should work
- As you are applying the font size to `modal-dialog` class, it's affecting the whole modal. Could we apply it only to `card-text` class? So it only affects the subtitle. By the way, 16px is the value that Lexicon/Clay has set for Card subtitles, if we want to change it, maybe we should report it to them instead of manually changing it, what do you think? Maybe we could ask Mery about it

**Review by sandrodw3 — CHANGES_REQUESTED** [review]
Hey @BarbaraCabrera, nice work 🥰 just some tiny things:

- I think we don't need to specify 600px `max-width` as it's the default value for the modal, just removing the 700px line should work
- As you are applying the font size to `modal-dialog` class, it's affecting the whole modal. Could we apply it only to card-text class? So it only affects the subtitle. By the way, 16px is the value that Lexicon/Clay has set for Card subtitles, if we want to change it, maybe we should report it to them instead of manually changing it, what do you think? Maybe we could ask Mery about it

**Review by sandrodw3 — APPROVED** [review]

**Comment by sandrodw3** [comment]
🧁

**Comment by ozysouza** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Pushed to BChan directly: https://github.com/brianchandotcom/liferay-portal/pull/125963

**Pull request closed without merging**
