### PR TITLE
LPS-122798 - Remove Adaptive Media feature flag

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @p2kmgcl

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
@p2kmgcl @ruben-pulido the test failure is the same for many other pulls

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
