### PR TITLE
LPS-175670 Add shortcut to select or deselect multiple items

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Divino 👏

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Hi @sandrodw3 , Pages tab in Select Display Page is gone after clicking it, can you take a look? thanks!

Steps to reproduce:
1. Add a page
2. Add a Asset publish to page and set it as Default Asset Publisher
3. Add a web content, go to display page section
4. Select specific and click add to select display page
5. Click Pages tab

Actual result:
Pages tab in Select Display Page is gone after clicking it.

reproduce

**Comment by victorg1991** [comment]
resent here https://github.com/liferay-echo/liferay-portal/pull/11197

**Pull request closed without merging**
