### PR TITLE
LPD-30896 Fragment does not keep selected when it is dragged to a page

### PR DESCRIPTION
**Pull request by veroglez**
Story link https://liferay.atlassian.net/browse/LPD-30467

## How to check?

- When a fragment/widget is added to the page with mouse or keyboard interaction, it must be selected
- When the fragment is selected, the Browser panel is kept

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
@veroglez LGTM 🥰 as we discussed, I just was thinking is the `itemIsBeingAdded` state is needed, as it's working fine for me without it, could you please check? If some specific case is failing, we can take a look

**Comment by sandrodw3** [comment]
ci:test:echo

**Comment by veroglez** [comment]
ci:test:echo

**Comment by ealonso** [comment]
ci:test:echo

**Comment by veroglez** [comment]
ci:test:echo

**Comment by veroglez** [comment]
ci:test:echo

**Comment by veroglez** [comment]
ci:test:echo

**Comment by veroglez** [comment]
ci:test:echo

**Comment by sandrodw3** [comment]
ci:test:echo

**Comment by veroglez** [comment]
ci:test:echo

**Comment by veroglez** [comment]
ci:test:echo

**Comment by veroglez** [comment]
ci:test:echo

**Comment by veroglez** [comment]
ci:test:stop

**Comment by veroglez** [comment]
ci:stop

**Comment by veroglez** [comment]
ci:stop

**Comment by veroglez** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/15980

**Pull request closed without merging**
