### PR TITLE
LPS-160998 Creates new info-button taglib

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-160998

cc: @ealonso @jkappler

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @lfbesada, no info panel shown when click the info button. Would you mind having a look at?
image

**Comment by lfbesada** [comment]
Hi @Tim-Cao,
Thanks for looking at it in depth!
I have solved that issue and the code conflicts.
Enjoy your vacation! 🌴 
Regards

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
I have been checking the test failures and I think that some of them have failed because of the selector used to get the "Info button". This PR changes the generated "Info button" HTML so I guess the selector should be adapted.
Thanks in advance! ❤️

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/9445

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
