### PR TITLE
LPS-131180 Use site group ID when resolving display pages

### PR DESCRIPTION
**Pull request by adolfopa**
Currently, when looking for a display page, the element group ID is used. This makes it not possible to use the site default display page with content from Global or any Asset Library.

See video attached to the Jira ticket to see this behaviour.

Thanks!

### CODE REVIEW

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
Some errors seem to be relevant. I'll take a look and resend.

**Comment by adolfopa** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/5207

**Pull request closed without merging**
