### PR TITLE
LPS-158393 [App Pages] If the user hasn't set a specific label then the input fragment label should be updated when the info field label changes

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-158393

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
https://github.com/liferay-echo/liferay-portal/pull/8979

**Pull request closed without merging**
