### PR TITLE
LPS-141924 fix LayoutPageTemplateEntryUpgradeProcess

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-141924

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1317401_1035

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1317401_1035

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
