### PR TITLE
LPS-190225

### PR DESCRIPTION
**Pull request by ealonso**
from: https://github.com/liferay-echo/liferay-portal/pull/12962

Motivation
=======
As part of [story](https://liferay.atlassian.net/browse/LPS-190225) related with undo/redo we mark fragments as deleted, to make it easier the redo. Since, when we reload the page the undo/redo is lost, we are loading deleted FragmentEntryLinks and it is not necessary.

Proposed Solution
========
The idea of this task is doesn’t load deleted fragments in `_getFragmentEntryLinks().`

Steps to Verify
========
- Add a breakpoint in ContentPageEditorDisplayContext.java line 722 and connect the debugger.

```
).put(
	"fragmentEntryLinks", _getFragmentEntryLinks().  <--- Here
).put(

```

- Go to the portal and create a new content page.
- Add 3 buttons and remove 2 of them using the **UNDO** arrows on the top right part of the page.
- Without saving or publishing the changes, reload the page using the **reload button in your browser**.
- Then you debugger should stop at the break point and when evaluating result of the` _getFragmentEntryLinks()` method, only one _FragmentEntryLink_ should be showed. (if you repeat this code in master, without this changes, you'll be able to see multiple _FragmentEntryLinks_ in te response as the deleted ones are included as well).

** please let me know if you need any help to verify it

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @YurenaC, the conversion draft page is broken.
**Steps to reproduce**

1. Add a new site
2. Add an Asset Publisher to a widget page
3. Convert to the content page
4. Edit the conversion draft
5. Remove the Asset Publisher and Add a Web Content Display below the Container
6. Navigate to the Pages admin
7. Edit the conversion draft once again

**Expected Results**
The Web Content Display and Container should be shown.

**Actual Results**
The page editor is broken. The following error is thrown in browser console
```
VM685:11 TypeError: Cannot read properties of undefined (reading 'com.liferay.fragment.entry.processor.styles.StylesFragmentEntryProcessor')
    at hasInnerCommonStyles (?browserId=chrome&minifierType=js&languageId=en_US&t=1690324199693&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/getTargetData.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/getTargetPositions.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/itemIsAncestor.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/defaultComputeHover.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/getDropData.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/useDragAndDrop.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/config/constants/containerWidthTypes.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/config/constants/fragmentClassPlaceholder.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/getFrontendTokenValue.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/getLayoutDataItemTopperUniqueClassName.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/generateStyleSheet.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/hasInnerCustomStyles.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/components/CommonStylesManager.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/common/openItemSelector.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/item_selector_value/itemSelectorValueToInfoItem.js:23:306)
    at ?browserId=chrome&minifierType=js&languageId=en_US&t=1690324199693&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/getTargetData.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/getTargetPositions.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/itemIsAncestor.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/defaultComputeHover.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/getDropData.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/useDragAndDrop.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/config/constants/containerWidthTypes.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/config/constants/fragmentClassPlaceholder.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/getFrontendTokenValue.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/getLayoutDataItemTopperUniqueClassName.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/generateStyleSheet.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/hasInnerCustomStyles.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/components/CommonStylesManager.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/common/openItemSelector.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/item_selector_value/itemSelectorValueToInfoItem.js:25:3631
    at Array.forEach (<anonymous>)
    at calculateStyles (?browserId=chrome&minifierType=js&languageId=en_US&t=1690324199693&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/getTargetData.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/getTargetPositions.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/itemIsAncestor.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/defaultComputeHover.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/getDropData.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/useDragAndDrop.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/config/constants/containerWidthTypes.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/config/constants/fragmentClassPlaceholder.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/getFrontendTokenValue.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/getLayoutDataItemTopperUniqueClassName.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/generateStyleSheet.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/hasInnerCustomStyles.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/components/CommonStylesManager.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/common/openItemSelector.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/item_selector_value/itemSelectorValueToInfoItem.js:25:2829)
    at ?browserId=chrome&minifierType=js&languageId=en_US&t=1690324199693&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/getTargetData.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/getTargetPositions.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/itemIsAncestor.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/defaultComputeHover.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/getDropData.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/drag_and_drop/useDragAndDrop.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/config/constants/containerWidthTypes.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/config/constants/fragmentClassPlaceholder.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/getFrontendTokenValue.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/getLayoutDataItemTopperUniqueClassName.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/generateStyleSheet.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/hasInnerCustomStyles.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/components/CommonStylesManager.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/common/openItemSelector.js&/o/js/resolved-module/@liferay/layout-content-page-editor-web@3.0.173/page_editor/app/utils/item_selector_value/itemSelectorValueToInfoItem.js:25:1028
    at Ui (0:2:79067)
    at lk (0:2:103491)
    at U.unstable_runWithPriority (0:2:121544)
    at fg (0:2:46759)
    at Sj (0:2:103254)
```

**Comment by sandrodw3** [comment]
https://github.com/liferay-echo/liferay-portal/pull/13031

**Pull request closed without merging**
