### PR TITLE
LPD-27946 & LPD-27948 Exporting and Importing Layouts should also include their StyleBookEntry and LayoutPageTemplateEntry

### PR DESCRIPTION
**Pull request by balazssk**
https://liferay.atlassian.net/browse/LPD-27946
https://liferay.atlassian.net/browse/LPD-27948

ps.: Sorry for bundling the 2 tickets into 1 PR

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
Hey @balazssk,

I saw that you removed `if (MergeLayoutPrototypesThreadLocal.isInProgress()) {` from the logic , It was added as part of LPS-134955, is it not necessary anymore?

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/15776

**Comment by balazssk** [comment]
hey @ealonso ,
It was necessary to remove as it was preventing layoutPageTemaplateEntry export-import for Staging and LAR export.

**Pull request closed without merging**
