### PR TITLE
LPS-204013 Rename

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @victorg1991, could you check the failed test
[com.liferay.asset.util.test.AssetVocabularySettingsHelperTest](https://testray.liferay.com/home/-/testray/case_results/2476884557)

**Comment by victorg1991** [comment]
Updated!

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
dish

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward:force

**Pull request closed without merging**
