### PR TITLE
LPS-199208 Uses correct taglib reference

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-199208)

## Steps 

1. Go to Content & Data > Documents and media
2. Click add button > File Upload
3. Select a file and give it a name > Save 

**Note: I have used in chrome devtools the custom throttling tool to delay the request and appears the progress-bar if not, you have to upload a large video to delay the request** 
ezgif com-video-to-gif

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
@DiegoHu97 Could you please fix semantic versioning?

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
@ealonso Fixed 😄

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
