### PR TITLE
LPS-119542 Only show article visible-interaction menu when controls-h…

### PR DESCRIPTION
**Pull request by hongvo2308**
…idden not set

### CODE REVIEW

**Comment by holatuwol** [comment]
Some additional context:

https://issues.liferay.com/browse/PTR-1885

**Comment by hongvo2308** [comment]
Thank you.

**Comment by p2kmgcl** [comment]
@holatuwol thanks for the PR! Looks good to go :D

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
