### PR TITLE
LPS-167054 Allow scope to be configurable for the Related Assets portlet

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Team,

Can you help review this PR?

Ticket: [LPS-167054](https://issues.liferay.com/browse/LPS-167054)

For additional context, see: 
[PTR-3483](https://issues.liferay.com/browse/PTR-3483)

Please let me know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1357401_3376

**Review by lfbesada — APPROVED** [review]
Hi @ericyanLr 
Thanks for the fix!
LGTM!
Regards

**Comment by lfbesada** [comment]
ci:forward

**Comment by jkappler** [comment]
Thanks @ericyanLr!

**Comment by lfbesada** [comment]
ci:forward

**Comment by alessandromalves** [comment]
ci:forward

**Pull request closed without merging**
