### PR TITLE
LPS-129394 Use util class

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Thanks @bakayattila!

**Comment by jkappler** [comment]
@ealonso

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
> ci:stop

@ealonso is this ready to merge?

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
