### PR TITLE
LPS-119450 - Allow setting the visibility of a vocabulary only when it is first created

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
Since the failure case caused by anthor regression issue not related to the changes in PR and in order to not clog up ci resources I pushed directly to BChan.
See https://github.com/brianchandotcom/liferay-portal/pull/93017

**Pull request closed without merging**
