### PR TITLE
LPS-150957, LPS-150958, LPS-146824, LPS-151000

### PR DESCRIPTION
**Pull request by p2kmgcl**
cc @Tim-Cao 
cc @ozysouza

### CODE REVIEW

**Comment by p2kmgcl** [comment]
I think it is ready, but needs review.

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7714

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
