### PR TITLE
LPS-135665 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-135665

This is only for master.

@victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @victorg1991, the alert message is different with previous. Could you have a look at?
image
It should be **This category might be being used in some contents. If you delete it, this category and all of its subcategories will also be deleted and removed from those contents. Do you want to continue deleting this category?**

**Comment by Tim-Cao** [comment]
Some language key might be missing in Asset Publisher configuration
image
Select Collection Provider
Select Collection
Set and Enable
Ordering

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Thanks @Tim-Cao going to fix that :)

**Comment by victorg1991** [comment]
fixed here: https://github.com/liferay-echo/liferay-portal/pull/5291

**Pull request closed without merging**
