### PR TITLE
LPS-129860 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-129860

This is only for master.

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ealonso, How about the navbars? Partial new navbar and old navbar co-exist.
See https://github.com/liferay-echo/liferay-portal/pull/4340#issuecomment-826343695

**Comment by Tim-Cao** [comment]
According to the last running, Poshi side is ready. Wait for this, https://github.com/liferay-echo/liferay-portal/pull/4355#issuecomment-827225666

**Comment by ealonso** [comment]
Hey @Tim-Cao,

For this story the idea is to have both navbars, since we only enable the new portlet. Also, we have planned another story https://issues.liferay.com/browse/LPS-102711 to move the configuration to other categories. I already implemented it but I'm waiting to merge this one, since the pull is too big.

Regards,
Eudaldo.

**Comment by ealonso** [comment]
ci:reevaluate:1037401_9544

**Comment by Tim-Cao** [comment]
That's a bad news. I have to fix poshi since both navbar exists.

**Comment by ealonso** [comment]
@Tim-Cao, Can I do something to make it easier for you?

**Comment by Tim-Cao** [comment]
If could hide any of navbar, Poshi won't need to be updated.

**Comment by ealonso** [comment]
We cannot do that at this moment, since the navbars are necessary those allow us to navigate to different places

**Comment by Tim-Cao** [comment]
Ok. Let me update them.

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
