### PR TITLE
[TS] LPS-191622 - LinkToLayout.getData() return is diferent after upgrade to 7.4 when no layout is selected

### PR DESCRIPTION
**Pull request by joseluisbango**
Motivation
=======
If no layout is selected, `LinkToLayout.getData()` return values:
- <7.4: "" (blank, empty string)
- 7.4: "`{}`" (empty JSON, not empty string)

This behavior doesn't seem consistent. 
In addition, if you upgrade, you still get an empty string, which is ok. But if you edit the journal article (keeping clear the Link To Page field), then the value is overwritten and you will get `{}` from there on.

See [LPS-191622](https://liferay.atlassian.net/browse/LPS-191622) for details.

Proposed Solution
========
Use `null` instead of `{}`. This way, we store `null` in database, which is the value you get for an empty LinkToLayout field right after an upgrade from <7.4.

Note that there might be customers in 7.4 that already deal with/expect an empty JSON, and they would be affected by this solution. Although it is likely that they already control when the return value is an empty string and/or a valid JSON.

Steps to Verify
========
See [LPS-191622](https://liferay.atlassian.net/browse/LPS-191622).

References to existing code (if applies)
========
Not found

Alternative Solutions that were discarded (if applies)
========
Check for `{}` in [TemplateNode.getData()](https://github.com/liferay/liferay-portal/blob/379d5d45bc941efe624948991865b40fe63e5c14/portal-kernel/src/com/liferay/portal/kernel/templateparser/TemplateNode.java#L162) and return an empty string if so.

---

What are your views on this @liferay-echo ? Thanks!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by joseluisbango** [comment]
ci:test:sf

**Comment by joseluisbango** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @joseluisbango code looks good :) Can you elaborate a bit more in which causes this may be a problem for customers? since you are probably never uses the getData method without parsing it first to json, right?

**Comment by joseluisbango** [comment]
Sure thing @victorg1991!

The customer's use case is this:

```
<#if myLinkToPage?? && myLinkToPage.getData() != "" > 
     <#-- DO SOMETHING -->
<#elseif ...
```
Basically, the did that to check whether `myLinkToPage` has content or not. And it was working in 7.2 and, apparently, in 7.4 too. But after updating the journal article, it doesn't work anymore because `myLinkToPage.getData()` return `{}` if no page is selected.

Hope this helps to understand their case. Let me know if you have more questions.

Thanks!

**Comment by victorg1991** [comment]
hey @joseluisbango I'm a bit reluctant to change this now since it is like this since 3 years, and changing that will cause a breaking change. Fixing the templates to take into account this change seems straightforward, isn't it?

**Comment by joseluisbango** [comment]
Hi @victorg1991.

I can see your point. I do have the same concerns. 

At the beginning, the customer told me that they had multiple templates and it was not possible to update them all manually, they wanted us to provide a solution. 
We were able to provide them some SQL `select`s and they realized that they don't have so many affected templates, just a few, so they decided to update them manually. They have even closed the ticket.

Having all of that into account, do you prefer closing the ticket as Won't fix?

**Comment by victorg1991** [comment]
Hey @joseluisbango YEs I think so, and more so if they won't be using this change at all. If other customers bring the same issue we can always revisit this solution :) 

Sorry for the inconvenciences and thanks for the work!

**Pull request closed without merging**
