### PR TITLE
LPS-165828 Fix Poshi Automation | master

### PR DESCRIPTION
**Pull request by ozysouza**
https://issues.liferay.com/browse/LPS-165828

cc @david-gutierrez-mesa 
cc @Tim-Cao

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by Tim-Cao — COMMENTED** [review]
Hi @ozysouza, shouldn't move up twice?

**Comment by ozysouza** [comment]
> Hi @ozysouza, shouldn't move up twice? https://github.com/liferay-echo/liferay-portal/pull/9944/files#diff-6390915ebd52ac5770065b2b4fc370f7bd55c4055977c8bb6e3ccec9b258ba2aR324-R327

Hi @Tim-Cao! I don't think so, just once is enough. Have you had a change to try it locally?

**Comment by ozysouza** [comment]
> Hi @ozysouza, shouldn't move up twice? https://github.com/liferay-echo/liferay-portal/pull/9944/files#diff-6390915ebd52ac5770065b2b4fc370f7bd55c4055977c8bb6e3ccec9b258ba2aR324-R327

Hi @Tim-Cao, yes you're right. I must have mistaken some order while testing it. Thanks for the heads up! PR updated.

**Pull request closed without merging**
