### PR TITLE
LPS-178986 - Test Scenarios Coverage | Backend

### PR DESCRIPTION
**Pull request by ruben-pulido**
[Commits](https://github.com/brianchandotcom/liferay-portal/compare/ca30016e0d...324142d081) for LPS-178896 are already in Brian's master but not yet synchronized in Liferay's master.

Motivation
=======
https://issues.liferay.com/browse/LPS-178627

Steps to Verify
========
1. Create a vocabulary with several categories and child categories
1. Request categories with `flatten=true`
```
curl -s -X GET 'http://localhost:8080/o/headless-admin-taxonomy/v1.0/taxonomy-vocabularies/44166/taxonomy-categories?flatten=true&sort=dateCreated&restrictFields=actions,availableLanguages,creator,dateModified,description,externalRefereceCode,numberOfTaxonomyCategories,id,parentTaxonomyVocabulary,siteId,taxonomyCategoryProperties,taxonomyCategorUsageCount,taxonomyVocabularyId' -H 'Accept-Language: en-US' -u test@liferay.com:test
```

```
{
  "actions": {},
  "facets": [],
  "items": [
    {
      "dateCreated": "2023-03-22T10:27:07Z",
      "name": "c1"
    },
    {
      "dateCreated": "2023-03-22T10:27:11Z",
      "name": "c2"
    },
    {
      "dateCreated": "2023-03-22T10:27:19Z",
      "name": "c3"
    },
    {
      "dateCreated": "2023-03-22T10:27:37Z",
      "name": "c1_1",
      "parentTaxonomyCategory": {
        "id": 44326,
        "name": "c1"
      }
    },
    {
      "dateCreated": "2023-03-22T10:27:51Z",
      "name": "c2_1",
      "parentTaxonomyCategory": {
        "id": 44329,
        "name": "c2"
      }
    },
    {
      "dateCreated": "2023-03-22T10:28:00Z",
      "name": "c2_2",
      "parentTaxonomyCategory": {
        "id": 44329,
        "name": "c2"
      }
    },
    {
      "dateCreated": "2023-03-22T10:28:12Z",
      "name": "c1_2",
      "parentTaxonomyCategory": {
        "id": 44326,
        "name": "c1"
      }
    },
    {
      "dateCreated": "2023-03-22T10:28:28Z",
      "name": "c4"
    },
    {
      "dateCreated": "2023-03-22T10:28:37Z",
      "name": "c3_1",
      "parentTaxonomyCategory": {
        "id": 44332,
        "name": "c3"
      }
    }
  ],
  "lastPage": 1,
  "page": 1,
  "pageSize": 20,
  "totalCount": 9
}
```

//cc @ealonso @jkappler

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1387401_7031

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
