### PR TITLE
LPS-166427 | LPS-166622 New related assets collection provider - assets with categories in the same vocabularies

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

Related tickets
[Link to task](https://issues.liferay.com/browse/LPS-166427)
[Link to bug](https://issues.liferay.com/browse/LPS-166622)

Echo Team is trying to add features based on clients needs. One of them is improving the related collections that are shown in collection fragments for display pages.

One feature that is heavily demanded is to show all related items that share vocabularies, which is what this PR tries to solve.

When working on the task, a bug was found were unavailable collections could be selected. This PR contains the fix, to ensure that the corresponding collections works correctly

## Change summary for LPS-166622 Inactive related collection providers are shown in the UI:

* Filter out collections that are not available
* Add integration tests for available and unavailable collections

## How to test the changes

* Start the portal with FF LPS-166036 disabled
* Create a new Display Page Template for Web Content
* Add a collection fragment to the page
* Click on the collection fragment to configure it
* Go to the related collection tabs
* Assets with categories in the same vocabularies collection provider should not be shown

## Change summary for LPS-166427 New related assets collection provider - assets with categories in the same vocabularies:

* Add new related collection provider to show items that share the same vocabularies as the one that is shown in the display page
* Add integration tests

## How to test the changes

* Start the portal with FF LPS-166036 enabled
* Create a new Display Page Template for Web Content
* Add a collection fragment to the page
* Click on the collection fragment to configure it
* Go to the related collection tabs
* Select Assets with categories in the same vocabularies collection provider
* Add a heading to the collection fragment and map the title of the web content to it
* Publish the display page template and mark it as default
* Add a new vocabulary
* Add 2 categories to the vocabulary
* Create a new web content and assign the first category to it
* Create a second web content and assign the second category to it
* Click on the kebab of the first web content and select "View Content"
* You will see the title of the second web in the list

related

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
@ealonso, just noticed that the test package is wrong (with the other PR too, will update it)

**Comment by jkappler** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @jkappler, I canno reproduce the failure case on my local. Would you mind rebasing on master then retest?

**Comment by jkappler** [comment]
@Tim-Cao, I'm sorry Bro. I think you are referring to https://github.com/liferay-echo/liferay-portal/pull/10041. That one depends on the for: LPS-166427. I updated the description in the other PR

I'm attaching the video for this, but activating the feature flag from the console, you will see that the other collection provider is shown, because the active method is not set to false (It's set in the other LPS, but I thought that sending 4 stories in the PR was too much)

Sorry that it was so confusing

Tim

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:reevaluate:1287401_4926

**Comment by ozysouza** [comment]
Just started reviewing :)

**Pull request closed without merging**
