### PR TITLE
LPS-159631 better link to url naming

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-159631 Better namings
- LPS-159631 Update language keys
- LPS-159631 Build lang

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1257401_4152

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1317401_4644

**Comment by ealonso** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Fixed rebase issues

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/9365

**Pull request closed without merging**
