### PR TITLE
[TS] | LPS-125614 Fix Web Content update with Featured Image

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @liferay-echo 

could you please check my fix and push it forward?

Thanks, Roland

https://issues.liferay.com/browse/LPS-125614

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:related

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
