### PR TITLE
LPS-143919 Simulation iframe allows the user to interact with the control menu

### PR DESCRIPTION
**Pull request by beltranrengifo**
See [Jira issue](https://issues.liferay.com/browse/LPS-143919)

### Motivation
Get rid of a weird app-in-app situation on the simulator device panel, due to the presence of the control menu after the first navigation.
The param `p_l_mode=preview` used for hiding this menu only works for the first load of the iframe.

### Solution proposed
Now, the JS verifies if the param is present after a navigation, adding it if needed.
In case portal navigation occurs, a listener will handle the DOM to create a smooth transition between pages vía CSS.

### Steps
- Create a page
- Navigate to home
- Open the simulator
- Click on the new page menu item, in order to navigate

**Actual**: The new loaded page shows the control menu
**Expected**: The new loaded page does not display the control menu

Note: after navigation, a visible delay before hiding the control menu is expected

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Hi @beltranrengifo, May I have question? How to interact with product menu or applications menu in simulation mode if hide the control menu?

**Comment by beltranrengifo** [comment]
> Hi @beltranrengifo, May I have a doubt? How to interact with Product Menu or Applications Menu in simulation mode if hide the control menu?

Hi @Tim-Cao !
I believe the purpose of the the simulator is to render the site like a non-logged user could see it, that's why in the first load the preview param is added. To interact with those menus is better to exit the simulator. However, this is a question I'll formulate to Julia on Friday, tomorrow is national holiday in Sp
What do you think?

**Comment by sandrodw3** [comment]
> > Hi @beltranrengifo, May I have a doubt? How to interact with Product Menu or Applications Menu in simulation mode if hide the control menu?
> 
> Hi @Tim-Cao ! I believe the purpose of the the simulator is to render the site like a non-logged user could see it, that's why in the first load the preview param is added. To interact with those menus is better to exit the simulator. However, this is a question I'll formulate to Julia on Friday, tomorrow is national holiday in Sp.
> 
> Another thought is that is not relevant for a regular editor of the site to see/check the responsive version of this administrative parts, as they can not be easily changed with the page edit. Isn't it?
> 
> What do you think?

In case it helps, I agree with @beltranrengifo 🥰
I also think the purpose of the simulator is to render the site without any administration options.

**Comment by Tim-Cao** [comment]
I see. Thanks @beltranrengifo  and @sandrodw3, did you meet control menu appears suddenly when navigate to page?
Actual

**Comment by beltranrengifo** [comment]
> I see. Thanks @beltranrengifo and @sandrodw3, did you meet control menu flash when navigate to page? Actual

Yeah, I've noticed 😢 
I'm trying to improve the navigation experience right now, but the JS load delays a bit

I set the PR status to Draft, so It does not disturb the team. I'll post a comment when ready.
Thank you both for your help! 🙌

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:stop

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:stop

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:close

**Pull request closed without merging**
