### PR TITLE
LPS-139353 baseline

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
cc: @victorg1991

**Comment by Tim-Cao** [comment]
Hi @ealonso, Removes VM support for Journal Templates, The language field is not shown. Is that expected?
image

**Comment by ealonso** [comment]
Hey @Tim-Cao, 
Yes, it is expected.

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
The Poshi cases are need to update @ealonso  and @victorg1991

**Comment by victorg1991** [comment]
I think so

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/5885

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
