### PR TITLE
LPS-173651 | Test Automation Creation | Master

### PR DESCRIPTION
**Pull request by rafaellajordao**
# LPS-169877 - Product QA | Test Automation Creation

Hi! :)
This pr is corresponding to this ticket: [LPS-173651](https://issues.liferay.com/browse/LPS-173651) → [LPS-172639](https://issues.liferay.com/browse/LPS-172639)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by liulukiwi** [comment]
LGTM!

**Comment by liulukiwi** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Just start reviewing :)

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
Just start reviewing :)

**Comment by liulukiwi** [comment]
Hi @rafaellajordao, I resend with some changes at: https://github.com/liferay-echo/liferay-portal/pull/11888. One is to assert the step "The field is marked as non required", And I file [LPS-182835](https://issues.liferay.com/browse/LPS-182835) for the case CanAdd10TagsFragmentsToPage, last, I move the cases to form components and modify the descriprions and some texts in tasks, please take a look, thanks!

**Comment by rafaellajordao** [comment]
Thanks a lot! I'll take a look! :) @liulukiwi

**Pull request closed without merging**
