### PR TITLE
LPS-127200 Avoiding undefined reference

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @liferay-echo! 

Please read [my commit message](https://github.com/liferay-echo/liferay-portal/pull/3606/commits/20406337a7cf421245500b89a959cf8b82391ff1). I don't know what the actual root cause is but it seems to fix the issue.

Thanks!

**Comment by ealonso** [comment]
Hey @4lejandrito,
Could you please send this one to @liferay-frontend?
Thanks!!

**Comment by victorg1991** [comment]
@4lejandrito it seems that is not reproducible today

**Comment by victorg1991** [comment]
Closing as this is not reproducible anymore

**Comment by victorg1991** [comment]
Thanks!

**Comment by 4lejandrito** [comment]
Thanks @victorg1991!

**Pull request closed without merging**
