### PR TITLE
[TS] LPS-122451

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team, could you review this, please?

Display Pages URLs for Web Contents should not add their ID if the status is approved.

Thanks in advance

\cc @antonio-ortega

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
@david-gutierrez-mesa seems that we miss a test here because it passed all the tests when we merged the original PR (see reverted commits).

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by pavel-savinov** [comment]
ci:forward

**Pull request closed without merging**
