### PR TITLE
LPS-196125 Standardize the text to Make a Copy through the product

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://liferay.atlassian.net/browse/LPS-196125

@BarbaraCabrera

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:help

**Comment by Tim-Cao** [comment]
ci:test:forms-functional

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional

**Comment by Tim-Cao** [comment]
Hi @BarbaraCabrera, should this copy be Make a Copy or not?
Step to reproduce
Add a web content structure
Make a copy of structure
image

**Comment by Tim-Cao** [comment]
ci:test:forms

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:forms

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:forms

**Comment by BarbaraCabrera** [comment]
see https://github.com/liferay-echo/liferay-portal/pull/13699

**Pull request closed without merging**
