### PR TITLE
LPS-203883 Form container in Display page template not loading relationship field

### PR DESCRIPTION
**Pull request by Mikellorza**
bug: https://liferay.atlassian.net/browse/LPS-203883
bug: https://liferay.atlassian.net/browse/LPS-204676

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Mikellorza** [comment]
ci:test:sf

**Review by p2kmgcl — APPROVED** [review]
Nice :smile:

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Hi @Mikellorza , apps:fragment:fragment-impl:compileJava FAILED, can you take a look? thanks!
```
main/java/com/liferay/fragment/internal/renderer/FragmentEntryFragmentRenderer.java:179: error: unreported exception com.liferay.portal.kernel.json.JSONException; must be caught or declared to be thrown
     [exec]       fragmentEntryInputTemplateNodeContextHelper.toInputTemplateNode(
```

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward:force

**Pull request closed without merging**
