### PR TITLE
LPS-195058

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by alessandromalves** [comment]
The failures are not related to this PR [(comparison with acceptance routine here)](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1693596636965&testrayRunIdA=2416364971&testrayRunIdB=2416988239). See https://github.com/brianchandotcom/liferay-portal/pull/140132

**Comment by alessandromalves** [comment]
ci:close

**Pull request closed without merging**
