### PR TITLE
LPS-168579 Add new SourceFormat Rule

### PR DESCRIPTION
**Pull request by p2kmgcl**
Motivation
=======
Currently `clay:dropdown-actions` taglib can be used without any label, breaking accessibility: https://issues.liferay.com/browse/LPS-168579

Proposed Solution
========
We have added a new SF rule that checks if any of "aria-label", "label" or "title" attributes are present, and giving an error if this is not the case.

Steps to Verify
========
1. Use clay:dropdown-actions somewhere in portal without any label
1. Try running SF

Alternative Solutions that were discarded (if applies)
========
We considered checking this in the taglib itself, but currently there is no easy way to check if "some of a list of attributes is present". That's why we have added the SF rule.

cc @ling-alan-huang

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:stable

**Comment by p2kmgcl** [comment]
:thinking: this looks unrelated

**Comment by ling-alan-huang** [comment]
SF failures are not related to this PR.
I sent the fixes here: https://github.com/brianchandotcom/liferay-portal/pull/126778

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by ling-alan-huang** [comment]
ci:forward

**Pull request closed without merging**
