### PR TITLE
[TS] LPS-178852 Comparing web content versions of the same structure does not work

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

**Note:** I am not sure if your Team is responsible for that part of the code. If you're not, please feel free to let me know the appropriate Team and I'll send the pull to them. Thank you.

Motivation
=======
In a structure, a custom field named "type" might be used as a field reference. During the parsing of the structure, when a default template is created (in the absence of an already existing template), a [TemplateNode](https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/templateparser/TemplateNode.java) like this will be generated, with a `type` field whose value is not a string but an object:

`[null, null, optionsMap={}, null, data=, null, null, null, name=FieldsGroup77008454, null, attributes={}, label={attributes={language-id=en_US}, name=label, data=, type=text, options=[], optionsMap={}}, type={attributes={language-id=en_US}, name=type, data=, type=select, options=[], optionsMap={video=video, player=player, button=button}}, null, null, target={attributes={language-id=en_US}, name=target, data=, type=select, options=[], optionsMap={_self=_self, _blank=_blank}}]`

The [getType()](https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/templateparser/TemplateNode.java#L227-L229) method will fail to cast the Object to a String.

Proposed Solution
========
Changing `getType()` so that it handles this case properly. I'm using the pattern of [getName()](https://github.com/liferay/liferay-portal/blob/master/portal-kernel/src/com/liferay/portal/kernel/templateparser/TemplateNode.java#L205-L213).

Steps to Verify
========
Please see the linked LPS for the reproduction steps, including a sample structure.
https://issues.liferay.com/browse/LPS-178852

Thank you and best regards,
István

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by IstvanD** [comment]
Dear Team,

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:reevaluate:1357401_3923

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
