### PR TITLE
LPS-131992 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-131992

This is only for master.

@p2kmgcl
@victorg1991

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, there is an issue, the vertial padding (pb-0, pt-0) are missing in default Fluid Container. Only horizontal padding (pr-0,pl-0) are shown. I guess it is related to https://github.com/liferay-echo/liferay-portal/pull/4550/commits/26b6ffa2111a4447af8b55eb34755836a55be36d
Could you have a look at?

**Comment by p2kmgcl** [comment]
@Tim-Cao this is intended. The idea is to remove all classes by default, but we need pr-0 and pl-0 to make it work properly.

**Comment by Tim-Cao** [comment]
@p2kmgcl Not only the mb- or ml- invalid value?

**Comment by p2kmgcl** [comment]
@Tim-Cao nope, remove everything that users haven't configured manually. I will improve this behavior in this other ticket https://issues.liferay.com/browse/LPS-131993 but the main idea is try removing everything by default.

**Comment by Tim-Cao** [comment]
@p2kmgcl  Last question, Will those class be still shown or not on Container after upgrade from legacy?

**Comment by p2kmgcl** [comment]
@Tim-Cao they should not, but this is actually fine because having pt-0 (or the wrong pt-) is basically the same than having nothing

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
@p2kmgcl LGTM!

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
