### PR TITLE
[7.4.x only] LPS-120694 Change Target Link labels to make it understandable to non-technical users

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
@Tim-Cao can you have a look at that test? I think we might need to update it (cc @veroglez)

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/2663

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
