### PR TITLE
LPS-192155 Remove the use of global functions in edit_feed.jsp

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-192155)

After completing this issue (https://github.com/liferay-echo/liferay-portal/pull/12900) I created a task to improve the quality of the existing code and move all global functions to JS.

## Proposed solution

The solution was to move the code to `propsTransformers` to remove unnecessary global functions.

## Test Scenario 1
* Go to system settings > search journal > web content
* Go to system scope > Administration and click on show feed and save
* Create a content page
* Create a vocabulary with a category on it
* Go to Content and Data > Feed and create a new one
* Complete the Friendly URL with “/web/guest/[name of your content page]
* Click on web content constraints and check the behaviour of the buttons for Select structures and categories:

Pasted Graphic 4

* Also check the behaviour of the presentation settings and save+cancel buttons:

image

### Note: 
We won't change the Remove cases until find a solution related with the `disabled` attribute and the behaviour when using a `propsTransformer` on clay buttons.

### CODE REVIEW

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Review by sandrodw3 — COMMENTED** [review]
Hey @BarbaraCabrera good job!! Almost everything is ok, I just left some comments with some improvements we could do 😄

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:stable

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
