### PR TITLE
LPS-142517 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-142517

This is only for master.

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:test:lima

**Comment by Tim-Cao** [comment]
ci:help

**Comment by Tim-Cao** [comment]
ci:test:site-template

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:acceptance-functional

**Comment by Tim-Cao** [comment]
Wait for ci:test:acceptance-functional results, Could we forward if there is no regression found and no acceptance cases failure? @ealonso

**Comment by ealonso** [comment]
@Tim-Cao yes, we can forward it if everything is working fine

**Comment by Tim-Cao** [comment]
Need to find a solution to switch RFF to ON or OFF for each case.

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7784

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
