### PR TITLE
LPS-165969 baseline

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Hi @ealonso , there's no new commit added, the same issue happens again when running relevant:

Here are the steps to reproduce:
1. Add a display page template for Category
2. Add a Heading fragment to display page template and map Name field to Heading
3. Mark the display page template as default
4. Add a vocabulary and add a category in it
5. Go to category, click eclipse menu and choose view display page
Actual result: An unexpected error occurred after clicking view display page in category. And there's 2022-10-20 08:24:05.952 ERROR [http-nio-8080-exec-2][FragmentRendererControllerImpl:122] Unable to render content of fragment entry 0:null in server console.

**Comment by ealonso** [comment]
Hey @liulukiwi,
I cannot reproduce it locally, 😞, Do you have a video with the steps?

**Comment by ozysouza** [comment]
@ealonso, there is a video with the steps.

https://user-images.githubusercontent.com/72820234/197182511-9595930d-4951-442c-8619-03933143a56d.mp4

**Comment by jkappler** [comment]
@ozysouza, @liulukiwi, already reproduced this, it only happens in DXP builds because of AnalyticsReportsLayoutDisplayPageInfoDisplayRequestAttributesContributor

**Comment by ealonso** [comment]
ci:forward

**Comment by jkappler** [comment]
@ealonso, seems analytics reports module is failing because of the changes 😢

**Comment by ealonso** [comment]
@jkappler it is because they are not using constants and using literals, I've already fixed it

**Comment by ealonso** [comment]
@jkappler see [c77a978](https://github.com/liferay-echo/liferay-portal/pull/9968/commits/c77a978c60eadbcd825235b8315f7027c117307a)

**Comment by ealonso** [comment]
ci:forward

**Comment by jkappler** [comment]
awesome @ealonso 😍

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
