### PR TITLE
[TS] LPS-129073 Prevent from rendering empty markup for title and actions

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This fix tries to prevent from rendering empty markup when possible since it makes the margins between elements be bigger than they should.

Could you please review it?

Thanks in advance

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
@dacousalr, please see https://github.com/liferay-echo/liferay-portal/pull/4044

**Pull request closed without merging**
