### PR TITLE
LPS-173665 New configuration for managing asset.categories.search.hierarchical property at instance level and using the UI

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-173665

Previous PR: https://github.com/brianchandotcom/liferay-portal/pull/129444

I am just changing the language key to follow [this comment](https://github.com/brianchandotcom/liferay-portal/pull/129444#issuecomment-1410825759)

Reviewed by the Echo Team [here](https://github.com/liferay-echo/liferay-portal/pull/10934)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Failures are not related, pushed to BChan directly at https://github.com/brianchandotcom/liferay-portal/pull/129657

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
