### PR TITLE
LPS-132737 product-navigation-control-menu-theme-contributor adds imp…

### PR DESCRIPTION
**Pull request by pat270**
…ersonate-user-icon styles. They are being overwritten by cadmin.

@victorg1991 This fixes the `impersonate-user-icon` being wrong size and color. The other issues in the Product Menu and Control Menu are due to `product-navigation-product-menu-web` and `product-navigation-control-menu-web` css not being included.

Screenshot:
impersonate-user1

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
thanks @pat270

**Pull request closed without merging**
