### PR TITLE
LPS-146650 Do not load variations until they reach the viewport

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
LGTM! 🥰
Just the thing we discussed in slack, it should be cool to add loading animation when variations hasn't loaded yet.

**Comment by p2kmgcl** [comment]
> LGTM! smiling_face_with_three_hearts Just the thing we discussed in slack, it would be cool to add loading animation when variations hasn't loaded yet.

Done!

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
