### PR TITLE
LPS-112981 The p_auth token is exposed in query string when adding new page

### PR DESCRIPTION
**Pull request by IstvanD**
Hi @liferay-echo 

Could you please review this pull request?
Please see the explanation in the [LPS](https://issues.liferay.com/browse/LPS-112981).

Forwarded from https://github.com/IstvanD/liferay-portal/pull/111

@rgusztus

Thank you and best regards,
István

### CODE REVIEW

**Comment by victorg1991** [comment]
Hey @IstvanD 
I cannot reproduce this issue in master, the url doesn't contain the p_auth, is there anything else that needs to be done for this to happen?

**Comment by rgusztus** [comment]
Hey @victorg1991,

You need to inspect network activity by opening up the browser's dev tools/network tab.
Once the form is submitted to create a new page, in the very first URL under the network activity you'll see the p_auth parameter.

Please let me know in case you need more information.

Regards,
Robert

**Comment by victorg1991** [comment]
Hey @rgusztus 
I've some portal-ext property that disables this 🤦 sorry about that

Speaking of the fix, is there any particular reason this has to be addressed in the layout module only? I've seen that this is reproducible is other parts of the portal. 

I am not sure if this a bug either but I think this should be corrected in a higher layer, otherwise you are going to have to keep doing this fix all over the portal code

**Comment by rgusztus** [comment]
Hi @victorg1991,

I've seen a couple of places where this issue was addressed, for ex. this [lps](https://github.com/liferay/liferay-portal-ee/pull/14408/commits/4e665a56358f96007ddfe5b7eed2c1bed02ad3d2).

I also was looking at different places on the portal looking after this issue but couldn't find any, so hence I've tried to fix it in this module, plus, in addition to the above I've found a couple of LPSs in JIRA where these issues were handled separately. But indeed you're right, I had this in mind as well, can you tell me a few examples where you were able to reproduce maybe?

Thanks!
Robert

**Comment by victorg1991** [comment]
Hey @rgusztus 

I was wrong, I checked the html and the p_auth was there, but it was removed when the form was submitted.
After some investigation i've seen that we have something commont to deal for most of these cases which is the [submitForm](https://github.com/liferay/liferay-portal/blob/884cd741c11f60df048c695bd2567d3c69bd411e/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/events.js#L154-L158) function

I think in this case we cannot rely on using that function, because additional logic, so this is good to go :)

Sorry for the delay, and thank you for the fix

🚀

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
