### PR TITLE
LPS-172006 Replace liferay-ui:icon in asset_selection_action.jsp

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Test Scenario

1. Navigate to Content & Data > Web Content.
2. Create some Web contents (almost 1).
3. Navigate to Site Builder > Collection.
4. Create a manual collection.
5. Add the Web contents to the collection.
6. Check that the symbol on the right to delete the Web Content  in the collection appears and works.

image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
Niiiiiiiiice 👏

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
