### PR TITLE
LPS-137856

### PR DESCRIPTION
**Pull request by mbowerman**
Follow-up pull for https://issues.liferay.com/browse/LPS-137856

/cc @javalosjr96

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Hi @mbowerman @javalosjr96 
Thanks for the pull request! ❤️ 
LGTM!
Regards

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
