### PR TITLE
LPD-34550 Destructure

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:page-management-playwright

**Comment by ealonso** [comment]
ci:test:page-management-playwright

**Comment by sandrodw3** [comment]
ci:stop

**Comment by sandrodw3** [comment]
ci:test:page-management

**Comment by sandrodw3** [comment]
ci:stop

**Comment by sandrodw3** [comment]
ci:test:page-management-playwright

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
