### PR TITLE
LPS-183077 Remove default properties from page definition

### PR DESCRIPTION
**Pull request by jkappler**
https://liferay.atlassian.net/browse/LPS-183077

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @jkappler, could you check this failed integration test?
[com.liferay.change.tracking.rest.resource.v1_0.test.CTEntryResourceTest](https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/239903/testReport/com.liferay.change.tracking.rest.resource.v1_0.test/CTEntryResourceTest)

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
