### PR TITLE
[TS] LPS-114885

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/891

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
