### PR TITLE
[TS] LPS-121562 Default web content view does not show related assets

### PR DESCRIPTION
**Pull request by vendeltoreki**
Dear @liferay-echo team,

The commit [LPS-92040 Don't show related assets by default](https://github.com/liferay/liferay-portal/commit/65bc491ea241) changed the default behavior between 7.1 and 7.2. However, some users still expect it to work the same way as before. To fix that, I've added a new configuration value "relatedAssetsEnabled", so this setting can be changed.

[LPS-121562](https://issues.liferay.com/browse/LPS-121562)

Please review my changes.

Thanks,
Vendel

### CODE REVIEW

**Comment by vendeltoreki** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/2541

**Pull request closed without merging**
