### PR TITLE
LPS-199463 Use Site language when adding the suffix to make copies

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPS-199463)

### Changes

Change the getMostRelevantLocale() to the getDefault() to use the site language instead of the user one.

## Test scenario

Change the user language to Spanish.

## Test scenario 1

1. Create a Web Content.
2. Make a copy.
3. Check that the suffix it’s in English instead of Spanish.
image

## Test scenario 2

1. Create a Fragment.
2. Make a copy.
3. Check that the suffix it’s in English instead of Spanish.
image

## Test scenario 3

1. Create a StyleBook.
2. Make a copy.
3. Check that the suffix it’s in English instead of Spanish.
image

## Test scenario 4

1. Create a Master page.
2. Make a copy.
3. Check that the suffix it’s in English instead of Spanish.
image

## Test scenario 5

1. Create a Display Page Template.
2. Make a copy.
3. Check that the suffix it’s in English instead of Spanish.
image

## Test scenario 6

1. Create a Utility Page.
2. Make a copy.
3. Check that the suffix it’s in English instead of Spanish.
image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:relevant

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@BarbaraCabrera, looks good. I launched relevant just in case. One thing, I noticed we don't have tests for copying fragments.  What do you say if we take the oportunity to add one or some?

**Comment by jkappler** [comment]
ci:stop

**Comment by BarbaraCabrera** [comment]
For sure! I will add an integration test for copying fragments 😄 thanks!

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/14380

**Pull request closed without merging**
