### PR TITLE
LPS-202182 Use type=module in fragments scripts

### PR DESCRIPTION
**Pull request by p2kmgcl**
This should have no effect on existing fragments, but enable developers to use top-level imports (`import Taca from 'toco'`) in fragment scripts.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
reject modernity embrace tradition

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, the carousel navigation doesn't work with your changes.

1. Add a Banner Slider fragment to a content page
2. Cannot navigate to the second slide

**Comment by p2kmgcl** [comment]
Yep, I was having a look at it. @victorg1991 I needed to update the JS :disappointed:

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, the same issue still happens. Would you mind double check?

**Comment by p2kmgcl** [comment]
Fixed. There were more than one slider fragment in portal.

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
Hey @Tim-Cao, I tested this manually and the JS is working, but the tests failing look a bit flacky. I tried the Slider#DecreaseNumberOfSlides test and it looks that at some point it doesn't know how to switch slides to continue with the process.

I uploaded a video to youtube (the video is too big for github), could you have a look at it?

https://www.youtube.com/watch?v=mTqSz9XxUEE

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, the issue is the slide will always go back to the slide 1 after mapping field.

Steps to reproduce

1. Add a web content
2. Add a Banner Slider to a content page
3. Navigate to the slide 2
4. Map the Title field of web content to the Slider 2 Title

It should stay at slide 2

It goes back to the slide 1

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
