### PR TITLE
[TS] LPS-122070 Exclude embedded and customizable portlets to preserve previous behavior

### PR DESCRIPTION
**Pull request by peterpetrekanics**
Dear @liferay-echo Team,

Please review @dacousalr 's  fix, and if you approve this change, please forward it to the next approver,
please read the related tickets in case you have questions or need more context.

Thank you,
Peter

### CODE REVIEW

**Comment by peterpetrekanics** [comment]
ci:test:sf

**Comment by peterpetrekanics** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
See changes https://github.com/liferay-echo/liferay-portal/pull/2739

**Pull request closed without merging**
