### PR TITLE
LPS-111480 | Page structure does not follow fragment configuration

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi, 
This solution has two parts: 
- The backend part that merges correctly editables and default editables and stores them correctly in the database, and
 - The front end part that keeps both editableValues and editables in sync (thanks to @p2kmgcl for providing the fix!).

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/260

**Comment by p2kmgcl** [comment]
ci:close

**Pull request closed without merging**
