### PR TITLE
LPS-130853 Try to look only using the classNameId when the page content is not present.

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
