### PR TITLE
LPD-15493

### PR DESCRIPTION
**Pull request by JavierMoral**
Motivation
=======
Fixing https://liferay.atlassian.net/browse/LPD-15493
Reproduction steps cause a NPE in com.liferay.portal.configuration.module.configuration.internal.model.listener.PortletPreferencesModelListener where it tries to obtain a [serviceContent from ServicecontextThreadLocal](https://github.com/liferay-echo/liferay-portal/blob/master/modules/apps/portal-configuration/portal-configuration-module-configuration/src/main/java/com/liferay/portal/configuration/module/configuration/internal/model/listener/PortletPreferencesModelListener.java#L199-L204) but it gets a null value.
I changed v3_3_0.LayoutPageTemplateStructureRelUpgradeProcess to add a serviceContext to this threadlocal before updating Portlet Preferences.

Steps to Verify
========
**Reproduction steps:**
1. Start an instance using version 7.2 sp8
2. In default site, create segment “seg1”, role equals administrator
1. Create content page “myContentPage“
1. Add any fragment to “myContentPage“, for example a banner and publish
1. Edit “myContentPage”
1. Create new experience, select segment “seg1” and save
1. Add widget "Search Bar" to top of the page, do not publish as the page needs to remain in draft status
1. Stop server and run upgrade tool

**Expected behavior:**

Upgrade finishes without errors

**Actual behavior:**

The following error is seen in upgrade log:
```
2024-01-25 13:28:16.276 INFO  [main][UpgradeProcess:119] Upgrading com.liferay.layout.page.template.internal.upgrade.v3_3_0.LayoutPageTemplateStructureRelUpgradeProcess
2024-01-25 13:28:16.362 ERROR [main][PortletPreferencesModelListener:216] Unable to update the layout's modified date
java.lang.NullPointerException: null
	at com.liferay.portal.configuration.module.configuration.internal.model.listener.PortletPreferencesModelListener._updateLayout(PortletPreferencesModelListener.java:203) ~[?:?]
	at com.liferay.portal.configuration.module.configuration.internal.model.listener.PortletPreferencesModelListener.onAfterUpdate(PortletPreferencesModelListener.java:69) ~[?:?]
	at com.liferay.portal.configuration.module.configuration.internal.model.listener.PortletPreferencesModelListener.onAfterUpdate(PortletPreferencesModelListener.java:41) ~[?:?]
	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.update(BasePersistenceImpl.java:792) ~[portal-kernel.jar:?]
	at com.liferay.portal.service.base.PortletPreferencesLocalServiceBaseImpl.updatePortletPreferences(PortletPreferencesLocalServiceBaseImpl.java:394) ~[portal-impl.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_311]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_311]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_311]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_311]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:41) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:60) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48) ~[portal-impl.jar:?]
	at com.liferay.portal.kernel.aop.ChainableMethodAdvice.invoke(ChainableMethodAdvice.java:55) ~[portal-kernel.jar:?]
	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:48) ~[portal-impl.jar:?]
	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:40) ~[portal-impl.jar:?]
	at com.sun.proxy.$Proxy111.updatePortletPreferences(Unknown Source) ~[?:?]
	at com.liferay.layout.page.template.internal.upgrade.v3_3_0.LayoutPageTemplateStructureRelUpgradeProcess._updatePortletPreferences(LayoutPageTemplateStructureRelUpgradeProcess.java:112) ~[?:?]
	at com.liferay.layout.page.template.internal.upgrade.v3_3_0.LayoutPageTemplateStructureRelUpgradeProcess._upgradeLayoutData(LayoutPageTemplateStructureRelUpgradeProcess.java:179) ~[?:?]
	at com.liferay.layout.page.template.internal.upgrade.v3_3_0.LayoutPageTemplateStructureRelUpgradeProcess._upgradeLayoutPageTemplateStructureRel(LayoutPageTemplateStructureRelUpgradeProcess.java:236) ~[?:?]
	at com.liferay.layout.page.template.internal.upgrade.v3_3_0.LayoutPageTemplateStructureRelUpgradeProcess.doUpgrade(LayoutPageTemplateStructureRelUpgradeProcess.java:53) ~[?:?]
	...
```

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ruben-pulido** [comment]
ci:forward:force

**Pull request closed without merging**
