### PR TITLE
[Technical Support] LPS-136009

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-136009

/cc @huynguyen-codeengine @thuycao-gs

Imitating the changes from from LPS-117229.

https://github.com/liferay/liferay-portal/blob/7.4.0-ga1/modules/apps/portal-vulcan/portal-vulcan-api/src/main/java/com/liferay/portal/vulcan/util/UriInfoUtil.java#L58-L67

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reevaluate:1267401_96

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/5462

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/5463

**Pull request closed without merging**
