### PR TITLE
LPS-164464 buildLang

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, would you mind checking the sf issue?

**Comment by ealonso** [comment]
Hey @Tim-Cao,
The SF error is not related with this pr, it is related with ObjectField/useObjectFieldForm.d.ts, 😞

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/124527

**Comment by ozysouza** [comment]
ci:close

**Pull request closed without merging**
