### PR TITLE
LPD-20876 Error during publishing a page from staging after the upgrade

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-20876

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
@jkappler Would you please be so kind as to review this PR?
Thank you very much in advance! :heart:

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by jkappler** [comment]
@lfbesada, looks good ❤️

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:report:2552600204

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1337401_5385

**Comment by lfbesada** [comment]
ci:reevaluate:1377401_16392

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
