### PR TITLE
LPS-134609 buildLang

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
(Just rebased onto master and separated this commit: https://github.com/shuyangzhou/liferay-portal/pull/10127)

**Comment by p2kmgcl** [comment]
I have reviewed these two results:
- CollectionCategoryFilter#FilterResultsOfCollectionPageBasedOnManualCollectionByContainsAnyCategories
- CollectionCategoryFilter#FilterResultsOfCollectionPageBasedOnManualCollectionBySingleCategory

And it looks like we need to update some Poshi locators, as we have replaced "Multiple Selection" option with "Single Selection":

```
 BUILD FAILED: Element is not present at "//label[contains(.,'Multiple Selection')]/input[@type=
'checkbox']"
```

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl  Missing language key for include-search-field

**Comment by Tim-Cao** [comment]
For poshi codes, see https://github.com/liferay-echo/liferay-portal/pull/5037

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/5037

**Pull request closed without merging**
