### PR TITLE
[TS] LPS-129422

### PR DESCRIPTION
**Pull request by jonathanmccann**

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
It looks like CI got stuck testing. I am going to rebase and resend this PR.

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:close

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/4091

**Pull request closed without merging**
