### PR TITLE
LPS-175831 Change focused styles logic

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
It seems that everything is working fine but one thing. If you place the focus on the favourit button and then press tab and shift tab, the favourite button get back the focus but the list item is not activated, I believe it doesn't have to be like this right?

**Comment by sandrodw3** [comment]
> It seems that everything is working fine but one thing. If you place the focus on the favourit button and then press tab and shift tab, the favourite button get back the focus but the list item is not activated, I believe it doesn't have to be like this right?

Yeah that's right, I didn't contemplate that case, I will add a focus listener to that button as well, thanks! 😄

**Comment by sandrodw3** [comment]
@victorg1991 it should be fixed now! Could you take a look?

**Comment by victorg1991** [comment]
Divino!

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
