### PR TITLE
[TS] LPS-134061 The available locales for a site must be retrieved using LanguageUtil.getAvailableLocales

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-134061

When we retrieve the available locales for a site, we must use **LanguageUtil.getAvailableLocales** instead of group.getAvailableLanguageIds().
The group.getAvailableLanguageIds()  method it seems it is intended for retrieving the locales used in the name and description of the group object for Staging purposes.

I have also applied the same change to the headless API in the SiteResourceImpl class as it is getting the wrong locales, after double checking it in slack: https://liferay.slack.com/archives/C5E1CRLJY/p1623393578079400 

/cc @liferay-usm @drewbrokke @pei-jung

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:echo

**Comment by jorgediaz-lr** [comment]
ci:test:headless

**Comment by jorgediaz-lr** [comment]
ci:test:echo

**Comment by jkappler** [comment]
ci:test:echo

**Comment by ruben-pulido** [comment]
Thanks for the fixes @jorgediaz-lr

I have tested both commits (the headless related one using http://localhost:8080/o/headless-admin-user/v1.0/sites/by-friendly-url-path/s1) and both look good to me.

Forwarding to Brian.

/cc @liferay-usm @drewbrokke @pei-jung

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
