### PR TITLE
LPS-199322 Clean metal dependencies

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, the Forms admin is unavailable.
image
```
2023-10-18 06:42:33.101 ERROR [http-nio-8080-exec-7][render_portlet_jsp:122] null
java.lang.IllegalStateException: Unable to find META-INF/resources/package.json in com.liferay.dynamic.data.mapping.form.builder
	at com.liferay.frontend.js.loader.modules.extender.internal.npm.InvalidNPMResolverImpl._throwIllegalStateException(InvalidNPMResolverImpl.java:46) ~[?:?]
	at com.liferay.frontend.js.loader.modules.extender.internal.npm.InvalidNPMResolverImpl.resolveModuleName(InvalidNPMResolverImpl.java:38) ~[?:?]
	at com.liferay.dynamic.data.mapping.form.builder.internal.context.helper.DDMFormBuilderContextFactoryHelper._getSidebarPanels(DDMFormBuilderContextFactoryHelper.java:412) ~[?:?]
	at com.liferay.dynamic.data.mapping.form.builder.internal.context.helper.DDMFormBuilderContextFactoryHelper._createEmptyStateContext(DDMFormBuilderContextFactoryHelper.java:274) ~[?:?]
	at com.liferay.dynamic.data.mapping.form.builder.internal.context.helper.DDMFormBuilderContextFactoryHelper.create(DDMFormBuilderContextFactoryHelper.java:100) ~[?:?]
	at com.liferay.dynamic.data.mapping.form.builder.internal.context.DDMFormBuilderContextFactoryImpl.create(DDMFormBuilderContextFactoryImpl.java:48) ~[?:?]
	at com.liferay.dynamic.data.mapping.form.web.internal.display.context.DDMFormAdminDisplayContext.getFormBuilderContextJSONObject(DDMFormAdminDisplayContext.java:712) ~[?:?]
	at org.apache.jsp.admin.view_jsp._jspService(view_jsp.java:236) ~[?:?]
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111) ~[jasper.jar:9.0.80]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[servlet-api.jar:4.0.FR]
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411) ~[jasper.jar:9.0.80]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473) ~[jasper.jar:9.0.80]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377) ~[jasper.jar:9.0.80]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[servlet-api.jar:4.0.FR]
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:319) ~[?:?]

```

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142425

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
