### PR TITLE
LPS-120702 Clean Page Editor warnings

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by veroglez** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Since the failure tasks caused by bundle version and startTestableTomcat and in order to not clog up ci resources I pushed directly to BChan.
See https://github.com/brianchandotcom/liferay-portal/pull/94355

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
