### PR TITLE
LPS-116838 Rename containerItemEnabled to containerItemFlexEnabled

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @p2kmgcl

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
Poshi reports give a 404, I'm running tests again

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
