### PR TITLE
LPS-197807 Applying the Workflow permission logic in the Journal Article permisson to fix the view permission bug by the copied URL

### PR DESCRIPTION
**Pull request by vngoliveira**
Related issue: [LPS-197807](https://liferay.atlassian.net/browse/LPS-197807)
LPP ticket: [LPP-50732](https://liferay.atlassian.net/browse/LPP-50732)
Previous PR: https://github.com/liferay-echo/liferay-portal/pull/13880
**Context about the issue and the proposed solution**:
Hi team,
this issue was marked as a Workflow bug, but by our investigation, we see that it was not, since the user without site roles doesn't receive a notification about the web content and is out of the workflow notifications.
We believe that this fix is a good way to solve the issue because the workflow logic will guarantee that only the assigned users can see the content.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by vngoliveira** [comment]
ci:test:stable

**Comment by vngoliveira** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @vngoliveira 
Thank you for coming to us with this.
I have analyzed the problem you raise in more depth and I think it is a Workflow problem, not a Journal problem.
I preferred to explain it in the ticket for a better follow-up, please see [this comment](https://liferay.atlassian.net/browse/LPS-197807?focusedCommentId=2486141). 
I am afraid I can be useful with this, surely the workflow component's team will be able to help more with the solution.
Regards

**Pull request closed without merging**
