### PR TITLE
LPS-170962 Auto

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, there is a regression issue. Would you mind having a look at?
Cannot select web content in manual colllection
**Step to reproduce**

1. Add a new site
2. Add a web content
3. Add a manual collection for All Types
4. Select the new web content as collection item

**Actual Results**
No collection items are selected.

**Pull request closed without merging**
