### PR TITLE
LPS-129307 Adds uuid to the JSON object

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Review by ealonso — APPROVED** [review]

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@ealonso, @p2kmgcl, will check what's wrong

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:stop

**Pull request closed without merging**
