### PR TITLE
[TS] LPS-197580 Only delete group scoped permission when an organization or its site is removed

### PR DESCRIPTION
**Pull request by evibudai**
Hi Team,
https://liferay.atlassian.net/browse/LPS-197580

Issue:
After deleting a Site, their resourcePermission entries stayed in DB instead of being deleted together with the Site.
These entries were for example, com.liferay.journal, com.liferay.blogs, com.liferay.knowledge.base.admin, com.liferay.message.boards, com.liferay.wiki, com.liferay.asset.categories.

Solution:
To prevent regression of [LPSA-36943](https://liferay.atlassian.net/browse/LPSA-36943), the solution proposed was to only delete the resource permissions with SCOPE_GROUP when an organization’s site or an organization is removed, and delete all other resource permissions of any other scope for the rest of the cases.
I also removed the now unnecessary group resource permissions deletion, since they were deleted under the "any" scope.

I tested this solution in my local environment on master and it worked as expected, the group's resource permissions were deleted.

Please review my PR!

Best regards,
Évi

CC/ @dacousalr

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
Hi @evibudai, thanks for this. Can you provide an integration test? It's mostly so that we don't break anything in the future.

Thanks in advance!

**Comment by jkappler** [comment]
thanks @evibudai ❤️!

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Thanks @evibudai and @dacousalr!

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142139

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
