### PR TITLE
LPS-148040 Misalignment in miller column.

### PR DESCRIPTION
**Pull request by BarbaraCabrera**

### CODE REVIEW

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:relevant

**Comment by BarbaraCabrera** [comment]
ci:test:relevant

**Comment by BarbaraCabrera** [comment]
ci:test:relevant

**Comment by BarbaraCabrera** [comment]
ci:test:relevant

**Comment by BarbaraCabrera** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:forward

**Review by veroglez — APPROVED** [review]

**Comment by veroglez** [comment]
ci:forward

**Pull request closed without merging**
