### PR TITLE
LPS-140261

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

First I thought that the use-case was about the left side menu being reachable, so I've implemented the isShow method for ApplicationsPanelCategory.java. I've followed the pattern of ControlPanelCategory and CommercePanelCategory.

Secondly, I've noticed that since https://issues.liferay.com/browse/LPS-124107 LayoutHeaderProductNavigationControlMenuEntry doesn't have a specific false condition to hide it for a Guest user. I think we should hide it, but the best condition I could come up with is Control Panel View permission.

Can you please review?
https://issues.liferay.com/browse/LPS-140261

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1267401_405

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
Hi Balazs

Thanks for the PR!

I've been trying to reproduce the second issue that you mention in the description about the LayoutHeaderProductNavigationControlMenuEntry being hidden from the Guest user.

The Guest user is any user who is not logged in and I cannot reproduce that a user not logged in sees the top header, it only appears when he is logged in.

On the other hand, the condition that you add in the second commit removes the title of the page for all users who do not have permission to view the control panel, even if they have permission to edit that page or on other sections. If the intention is to hide something when accessing the Guest user, it would be enough to check if is logged in or not.

Since the first commit perfectly solves the bug to which the PR refers, I have chosen to make a new PR with that commit. For the second bug that you mention, please open a new issue describing the steps to follow to reproduce it.

Please look at: https://github.com/liferay-echo/liferay-portal/pull/6054

Thank you!

Regards

**Pull request closed without merging**
