### PR TITLE
LPS-166850 Permission error when editing web content in an asset library

### PR DESCRIPTION
**Pull request by adolfopa**
# Motivation

https://issues.liferay.com/browse/LPS-166850

Users with roles that don't have the global group VIEW permission explicitly assigned won't be able to edit web content in an asset library (this may happen too in sites, but we haven't checked it).

The fix is to explicitly check for that permission before invoking the services.

# Change summary

- Make explicit permission check.
- Make sure the display context doesn't return a negative value.
- Minor SF changes.

# How to test the changes

1. Add a new asset library.
2. Add a new regular role and define the permissions below:
  - Asset Libraries: Access in Control Panel.
    - Asset Libraries: View.
    - Asset Library Settings > Asset Library Entry: View Site and Asset Library Administration Menu.
4. Create a new user.
5. Edit the new user > Memberships to select the added asset library and save it.
6. Edit the new user > Roles to select the regular role(under REGULAR ROLES) and Asset Library Owner(under ASSET LIBRARY ROLES).
7. Login in with the new user.
8. Go to the added asset library > Web Content.
9. Try to add a new web content.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
@victorg1991, it is related with the story about preview Display Page Templates

**Comment by victorg1991** [comment]
LGMT Thanks @adolfopa

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
Manual forward https://github.com/brianchandotcom/liferay-portal/pull/125353

**Pull request closed without merging**
