### PR TITLE
LPS-177945 Date Fragment custom format not working on Display Page Template Preview

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://issues.liferay.com/browse/LPS-177945)

## Steps 

1. Go to Content & Data > Web Content
2. Create a Basic Web Content: title w1
3. Go to Design > Page Templates > Display Page Templates
4. Create a new Display Page Template for Basic Web Contents
5. Add a Date fragment to the page
6. Map the Publish Date field to the Date fragment
7. Set The custom format of the Date fragment to "YYYY"
8. Publish the Display Page Template
9. Edit the Display Page Template again
10. From the top menu, Preview with, select the Basic Web 
Screenshot 2023-03-15 at 14 08 02
Content w1

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test.relevant

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
