### PR TITLE
LPS-121062 Button to edit the page should not post any form

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi guys,

Can you review this pull request, please?

You can find more information in [LPS-121062](https://issues.liferay.com/browse/LPS-121062), and the solution is based in [this comment](https://github.com/liferay-frontend/liferay-portal/pull/398#issuecomment-696581735) in previous pull request.

Thanks.

Regards.

/cc @haubuicodeengine, @holatuwol

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by john-co** [comment]
FYI, the unique classic theme errors should be no longer reproducible now. https://issues.liferay.com/browse/LPS-121303. It seems to have been caused by https://issues.liferay.com/browse/LPS-119582 which has been reverted.

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
