### PR TITLE
LPS-84862 use the service object to call copyStructure instead of calling the post

### PR DESCRIPTION
**Pull request by lucasmiranda0**
[LPS-84862](https://issues.liferay.com/browse/LPS-84862) The copying of the structure in the CopyDataDefinitionMVCActionCommand class was being done through the ‘post’ method of the dataDefinitionResource without copying the permissions. The solution was to, instead of this, use the “copyStructure” method of the “ddmStructureService”, which adequately copies the permissions.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lucasmiranda0** [comment]
ci:test:sf

**Comment by lucasmiranda0** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
Hey @lucasmiranda0,

Your changes are causing a regression, the code that you remove was added to fix https://issues.liferay.com/browse/LPS-127986, Could you please take a look at it? It seems that we should update the logic of copy method to have unique reference ids.

Regards,
Eudaldo

**Comment by lucasmiranda0** [comment]
Working on it :)

**Comment by lucasmiranda0** [comment]
.

**Comment by lucasmiranda0** [comment]
ci:test:sf

**Comment by lucasmiranda0** [comment]
ci:test:relevant

**Comment by lucasmiranda0** [comment]
I tried to replicate the copying logic that is currently present in the CopyDataDefinitionMVCActionCommand file in order to make the field names and references unique.

**Comment by lucasmiranda0** [comment]
I just realized that a bug is happening. Working on it tomorrow, but can you tell if I'm in the right path?

**Comment by lucasmiranda0** [comment]
ci:test:relevant

**Comment by lucasmiranda0** [comment]
Hi, @ealonso! I noticed that the relevant is breaking on the unit test, because the test compares the two structures but they won't have the same name, because the copy of X will be called CopyOfX

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
Hey @lucasmiranda0,

The changes that you are doing are under dynamic data mapping, so you should talk with the bpm team in Brasil, since this code is under their responsibilities.

So, I'm going to make some changes in the pr and send to them, so you can start a conversation with them.

Please see: https://github.com/liferay-objects/liferay-portal/pull/1346

Regards,
Eudaldo.

**Pull request closed without merging**
