### PR TITLE
LPD-32950 - Technical Task | Add a GET endpoint for Collection Providers so users can access its list of items for items of type AssetEntry

### PR DESCRIPTION
**Pull request by ruben-pulido**
https://liferay.atlassian.net/browse/LPD-32950 - Technical Task | Add a GET endpoint for Collection Providers so users can access its list of items for items of type AssetEntry

This PR build on https://github.com/liferay-headless/liferay-portal/pull/2151, which is required for the Test to work.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
Setting the PR on hold since it depends on https://github.com/liferay-headless/liferay-portal/pull/2151

**Comment by ruben-pulido** [comment]
Removing "On hold" since https://github.com/brianchandotcom/liferay-portal/pull/153541 was merged

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/16171

**Pull request closed without merging**
