### PR TITLE
LPS-142917 We should postpone the deletion of the relations after checking the viewable categoryIds.

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-128928

cc: @NemethNorbert @sandrodw3

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
