### PR TITLE
LPS-121068 Check if fragments have dropzones to disallow duplicating

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
Rebase then resend. See https://github.com/liferay-echo/liferay-portal/pull/2420

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
