### PR TITLE
LPS-138911 Fix test

### PR DESCRIPTION
**Pull request by lfbesada**
JournalArticleServiceTest.testCheckArticleWithInvalidStructure.

The fix for LPS-133617 avoids caching journal content, which causes the default values to be sets in document if content doesn't have some structure field.

We change put the desired document to test the specific case.

https://issues.liferay.com/browse/LPS-138911

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
