### PR TITLE
LPS-190802 Turn off the asset view counters for LXC

### PR DESCRIPTION
**Pull request by jkappler**
https://liferay.atlassian.net/browse/LPS-190802

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@ealonso

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:forward:force

**Comment by jkappler** [comment]
@Tim-Cao, I don't like these failures:

com.liferay.view.count.service.persistence.test.ViewCountEntryFinderTest.testIncrementViewCount - UNTESTED
com.liferay.view.count.service.impl.test.ViewCountEntryLocalServiceTest.testLazyCreationWithRaceCondition - UNTESTED
com.liferay.view.count.service.persistence.test.ViewCountEntryPersistenceTest.testCreate - UNTESTED

I will retest, just to be sure

**Comment by jkappler** [comment]
all good @Tim-Cao

**Pull request closed without merging**
