### PR TITLE
[TS] LPP-46181 > LPS 160071 HTML injection in Liferay URL parameter p_p_id vulnerable to content spoofing

### PR DESCRIPTION
**Pull request by chileces**
Dear Team,

Our customer finds out an issue that HTML injection in Liferay URL parameter p_p_id vulnerable to content spoofing.
This PR is to fix it. Please help to review this solution and give me feedback.
Ticket https://issues.liferay.com/browse/LPP-46181 > https://issues.liferay.com/browse/LPS-160071

Thank you very much,
@chileces

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by chileces** [comment]
ci:test:bundle

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @chileces 
Thanks for the fix!
Please resend us the PR when you have fixed the source formatting errors
Thanks in advance!
Regards

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:stop

**Pull request closed without merging**
