### PR TITLE
LPS-154690 Modified sidebar body position.

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
FWD: https://github.com/fortunatomaldonado/liferay-portal/pull/19
https://issues.liferay.com/browse/LPS-154690

`LPS-154690 Modified sidebar body position to unblock sidebar header from view.`

Before:
before

After:
after

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
thanks @fortunatomaldonado @SelenaAungst 👏

**Pull request closed without merging**
