### PR TITLE
[TS] LPS-147300 Hidden pages are not displayed in the item selector

### PR DESCRIPTION
**Pull request by jcampoy**
https://issues.liferay.com/browse/LPS-147300

### CODE REVIEW

**Comment by jcampoy** [comment]
ci:help

**Comment by jcampoy** [comment]
ci:test:echo

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
