### PR TITLE
LPS-129860 Uses the correct parameters to redirect when there is an error

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
Hey @Tim-Cao,

Could you please take a look to poshi failures and rebase error?

Thanks!!

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/4355

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
