### PR TITLE
LPS-139064 - As a Page Creator I would like to preview a draft page so that I could approve it

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
@ealonso

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
https://github.com/liferay-echo/liferay-portal/pull/5893

**Pull request closed without merging**
