### PR TITLE
Revert "LPD-17866 NewSegmentCanBeAssignedToARegularRole"

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
Hey @smottal

I'm reverting your change "LPD-17866 NewSegmentCanBeAssignedToARegularRole" since it is breaking 72 poshi tests of Segmentation, please see the following common error:

```
com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: 
Element is not present at "//a[@data-qa-id='creationMenuNewButton']"
```
You can find those errors in https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=2540957582

Regards,
Eudaldo

**Comment by smottal** [comment]
hey @ealonso I was checking the errors right now and I was preparing the revert PR me too. Sorry for the inconvenience.

**Pull request closed without merging**
