### PR TITLE
LPS-148090 show correct highlight for layout summaries

### PR DESCRIPTION
**Pull request by jgarcialr**

### CODE REVIEW

**Comment by jgarcialr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by jgarcialr** [comment]
Hi  @ealonso 

Sorry I just rebased and forcepush to test on my user the PR and see if the semantic versioning failing test was my fail or not related.

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
