### PR TITLE
LPS-117884 Introduce the concept of InfoCapability to allow declaring that a certain custom entity supports a specific feature/capability

### PR DESCRIPTION
**Pull request by JorgeFerrer**
cc @jkappler

### CODE REVIEW

**Comment by JorgeFerrer** [comment]
ci:forward

**Comment by JorgeFerrer** [comment]
ci:forward

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by JorgeFerrer** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
Since the failure is unrelated to changes in PR and in order to not clog up ci resources I pushed directly to BChan.
See https://github.com/brianchandotcom/liferay-portal/pull/91990

**Pull request closed without merging**
