### PR TITLE
[TS] LPS-164130 | Canonical URLs contain duplicate locales on Display page when using locale.prepend.friendly.url.style=2

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-164130
Thank you!

------
**Steps to reproduce:**

1. Put locale.prepend.friendly.url.style=2 in the portal-ext
2. Create a Display page template for basic web content, mark it as default
3. Create a basic web content, publish it
4. Open the web content in incognito mode, check the page source

**Current behavior:** Locales are duplicated in the canonical URLs
**Expected behavior:** Locales shouldn't be duplicated 

Based on my tests the root cause of the issue is that the alternateURL generator adds the language path without checking if it's there. At that point, the display page already added the language path to the web content friendlyURL path.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1387401_3982

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1257401_4787

**Comment by lfbesada** [comment]
Hi @bakayattila 
Thanks for the fix! ❤️ 
I have been testing it and it worked great.
I have only detected a bug when the friendlyURL contains the i18Npath of the default locale of the site.
For example, when we are in a site with EN as the default locale and we have as web content's friendlyURL something like my-url-prefix/en/my-url-suffix.
In that case, the site's default locale alternate loses the i18Npath.
I have pushed a pull request that avoids this error, please see: https://github.com/liferay-echo/liferay-portal/pull/9796
Regards

**Pull request closed without merging**
