### PR TITLE
LPS-147251, LPS-147252, LPS-147253, LPS-146986, LPS-148717, LPS-146976

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-147251
https://issues.liferay.com/browse/LPS-147252
https://issues.liferay.com/browse/LPS-147253
https://issues.liferay.com/browse/LPS-146986
https://issues.liferay.com/browse/LPS-148717
https://issues.liferay.com/browse/LPS-146976

@Tim-Cao 
@ruben-pulido
@sandrodw3

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7553

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
