### PR TITLE
LPS-134363 &   LPS-134673 Support pagination for Collection Display Fragment on backend for view mode

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @jkappler @veroglez

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:reevaluate:1257401_1946

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:reevaluate:1257401_1969

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The failure case is unrelated to changes in PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/103638

**Comment by Tim-Cao** [comment]
ci:close

**Comment by ruben-pulido** [comment]
ci:reevaluate:1257401_1969

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
@ruben-pulido, already merged

**Pull request closed without merging**
