### PR TITLE
LPS-134544 Make sure that we always set a valid context to avoid crashes

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
The failure cases are unrelated to changes in PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/103489

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
