### PR TITLE
LPS-190948 - The Specific Content is missing on Action panel after import the display page template

### PR DESCRIPTION
**Pull request by ruben-pulido**
https://liferay.atlassian.net/browse/LPS-190948

Once it has been reviewed by Echo, this PR probably needs to be reviewed by the Objects team since objects ItemSelector 
is being modified.

//cc @ealonso @jkappler

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Hi @ruben-pulido 
LGTM 😍 Thanks!
I am assigning this PR to resent this to the Objects repo or to ask for their review here. Up to you!
Regards

**Comment by ruben-pulido** [comment]
Forwarded to objects team here: https://github.com/liferay-objects/liferay-portal/pull/2390

**Pull request closed without merging**
