### PR TITLE
[TS] LPS-123387

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-123387

Unfortunately, it seems the problem described in LPS-123387 cannot be resolved easily with a query.  This is because the query would need to return results within the given date ranges OR null values for displayDate/expirationDate.  Currently, it's only possible to retrieve a valid value or null, but not in the same query.

This specific query was achieved with a dynamic query as seen in https://github.com/liferay-echo/liferay-portal/pull/2873, however the dynamic query locked up the portal, killing performance when fetching multiple display articles at once.

So, in order to resolve any performance hits due to large amounts of journal article versions, I've added a configuration which allows for a max version cap.  Currently, this value is 0, meaning there is no upper-limit of versions.  However, changing this value to a valid int will put a cap on how many versions can exist for a given journal article.  This is done by expiring all article versions past this limit, starting with the lowest version numbers.

Also, I wasn't having any luck generating the language files; there were far too many translations trying to go through at once.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/3042

**Pull request closed without merging**
