### PR TITLE
[7.4-only] LPS-121969 Migrate v2 usages of clay:vertical-card in site-browser-web

### PR DESCRIPTION
**Pull request by julien**
cc @carloslancha @markocikos

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Review by carloslancha — COMMENTED** [review]
@julien don't we need to migrate `getData`?

**Comment by julien** [comment]
@carloslancha yes I forgot that

**Comment by julien** [comment]
ci:test:relevant

**Review by carloslancha — APPROVED** [review]

**Comment by veroglez** [comment]
Nice! 🥳

**Comment by veroglez** [comment]
ci:forward

**Pull request closed without merging**
