### PR TITLE
LPS-120601 Not needed

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Please don’t run ci:forward until poshi update

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
Hi @sandrodw3  and @victorg1991, your changes cause the following regression issue
Add a page based on Blank
Add a Container to page
Click the body of Container
Select Fixed Width as Container Width

Expected:
The Margin Left and Margin Right fields should be disabled.

Actual:
The Margin Left and Margin Right fields are still enabled.
Actual

**Comment by sandrodw3** [comment]
Thanks @Tim-Cao, I'm taking a look!

**Comment by sandrodw3** [comment]
Fixed the issue and sent another PR here https://github.com/liferay-echo/liferay-portal/pull/2291

**Comment by sandrodw3** [comment]
ci:close

**Pull request closed without merging**
