### PR TITLE
LPS-188301 and LPS-188303 Add friendly URL warnings when there is a conflict between a site template and some connected site

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:test:stable

**Comment by lfbesada** [comment]
ci:forward

**Comment by rafaellajordao** [comment]
> **Jenkins Build:**[test-portal-acceptance-pullrequest(master)#3780](https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/3780/)
> **Jenkins Report:**[jenkins-report.html](https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3780/jenkins-report.html)
> **Jenkins Suite:**relevant
> **Pull Request:**[liferay-echo#12615](https://github.com/liferay-echo/liferay-portal/pull/12615)
> **Testray Routine:**[EE Pull Request](https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894)
> **Testray Build:**[[master] ci:test:relevant - p2kmgcl > liferay-echo - PR#12615 - 2023-06-28[23:48:46]](https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2364662405)
> **Testray Importer:**[publish-testray-report#6949](https://test-1-40.liferay.com/job/publish-testray-report/6949/)

Apparently the failures are not related because they fail in other suites!

**Comment by rafaellajordao** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
