### PR TITLE
LPS-143680 Move widget usage calculation to front

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
Hey @victorg1991, as we have been already talking about this, could you please take a look? 🥰

One thing I wanted to discuss is that I found that currently (in master), a non instanciable widget can't be added to different experiences, and the logic tells me that it should. With my changes, the front is ready for it, but when trying to add the widget to another experience it's throwing an exception in the server. What do you think about this?

Thanks in advance ❤️

**Comment by victorg1991** [comment]
@ealonso We have moved the calculations about used widget to the frontend: https://github.com/liferay-echo/liferay-portal/pull/7572/commits/11110405a5e15773c5852601a024879af6ceafe9 Did you see any downside to this? For doing that in the backend we'd need to get the list of all fragmentEntryLinks everytime the user adds a non-instanceable portlet

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
@sandrodw3 @victorg1991 



cc: @BarbaraCabrera

**Comment by ealonso** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
