### PR TITLE
LPS-178946 AUI module liferay-portlet-segments-simulation into a js component

### PR DESCRIPTION
**Pull request by p2kmgcl**
Follow up of https://github.com/liferay-echo/liferay-portal/pull/11885

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
Hey @Stephy6! I have added some small commits with the issues I found in the PR.

The reason it was failing is that `HashMapBuilder` ~is dumb~ needs to receive only Strings, so we need to convert all URLs to strings manually: https://github.com/liferay-echo/liferay-portal/pull/11901/commits/b87b01d0e9f8766fcb0dd94963a9b94b8be85ee5

I also added [this last commit](https://github.com/liferay-echo/liferay-portal/pull/11901/commits/e1727d91332635161208eca780aa0b0cf8bd1f7f) because the page wasn't being reloaded when selecting some segments, but I am not sure if that is ok, so please have a look at it :smile: 

If everything is ok, please forward the PR :rainbow:

**Comment by Stephy6** [comment]
Hi @p2kmgcl, works perfectly, thank you!

**Comment by Stephy6** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
