### PR TITLE
[TS] LPS-128652 Only change 1 fragmentEntryLink in the scope of this method

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

This method is overiterating through fragmentEntryLinks. All calls for this method already handle supplying the correct fragmentEntryLinkIds so we don't need to update every fragmentEntryLink belonging the oldFragmentEntryLink's fragmentEntry.

Apart from performance improvement, defaultEditableValues was never updated to match it to the current fragmentEntryLink of the loop, so the editableValues of 2 different fragmentEntryLinks were merged, causing LPS-128652.

Can you please review?
https://issues.liferay.com/browse/LPS-128652

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by balazssk** [comment]
Hi @ruben-pulido ,
To me, it looks like the only failing test is related to Data Engine, rather than Fragments:

>  [parallel] 2021-03-05 17:16:52.439 ERROR [Portal Dependency Manager Component Executor--1][DataEngineNativeObjectPortalExecutor:161] java.lang.NullPointerException
>  [parallel] java.lang.NullPointerException
>  [parallel] 	at com.liferay.data.engine.rest.resource.v2_0.DataListViewResource.builder(DataListViewResource.java:50)
>  [parallel] 	at com.liferay.data.engine.rest.internal.resource.v2_0.DataDefinitionResourceImpl._removeFieldsFromDataListViews(DataDefinitionResourceImpl.java:1208)
>  [parallel] 	at com.liferay.data.engine.rest.internal.resource.v2_0.DataDefinitionResourceImpl._removeFieldsFromDataLayoutsAndDataListViews(DataDefinitionResourceImpl.java:1200)
>  [parallel] 	at com.liferay.data.engine.rest.internal.resource.v2_0.DataDefinitionResourceImpl.putDataDefinition(DataDefinitionResourceImpl.java:634)

Can you please check if the code changes are ok?
Thanks

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Pull request closed without merging**
