### PR TITLE
LPS-134431 No items shown when apply Contains Any public and internal categories filter

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-134431

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @lfbesada,
Could you please add some tests for it? Also, we can not break the compatibility, we should deprecated the methods and create new ones.
Regards,
Eudaldo

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @ealonso ,
I've renamed the modified methods and done junit tests. Could you please take another look at it?
Thank you!
Regards

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/5145

**Pull request closed without merging**
