### PR TITLE
LPS-117324 validate the value of uuid and groupId

### PR DESCRIPTION
**Pull request by AliciaGarciaGarcia**

### CODE REVIEW

**Comment by AliciaGarciaGarcia** [comment]
Hi @liferay-echo 

I was looking for this bug that was assigned to @adolfopa but is on PTO.

I detected that with the old system and the image empty, on https://github.com/liferay/liferay-portal/blob/3065ef268a0e532d585f9e8ca8fe82940f53ba37/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/service/impl/JournalArticleLocalServiceImpl.java#L6777 the value, the content of the dynamicContentElement when the type is an image, is `""`.
Now with DE activated, the empty value is `{"description":"","title":"","url":""},` so the `Validator.isNull` is not triggered and it will try to find the fileEntry on `FileEntry fileEntry = dlAppLocalService.getFileEntryByUuidAndGroupId(uuid, groupId);` with `""` and `0` and the system throws an error.

On the other hand if you create an WC with an image, save and after that you clear the image, the value will be `{}`. So it is inconsistent with the first time you create the WC.

This is a workaround that bypass both conditions by validating the value of uuid and groupId, but I think that DE team must made consistent the content of the dynamicContentElement when is an image.
If this is enough to solve this lvl 5 issue, review and forward 

Thanks!

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/1684

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
