### PR TITLE
LPS-114403 Enable fragments and widgets sidebar panel

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @liulukiwi @Tim-Cao,

Could you please update the broken tests?

We are mixing the sidebar panel categories, fragments and widgets into a new one. The new user interface looks like this:

LPS_-_113243_-_Fragments_Panel_Redesign_–_Figma

See: https://issues.liferay.com/browse/LPS-113243

Regards,
Eudaldo.

**Comment by ealonso** [comment]
@liulukiwi @Tim-Cao, also if you find any issue, please let us know.

cc: @veroglez @p2kmgcl

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
Hey @liulukiwi @Tim-Cao,

Apart from the linked story, we introduced a new change in the sidebar collapse buttons (see screenshot), which is this: 
https://github.com/liferay-echo/liferay-portal/pull/794/commits/77f4cc192f35984e9691fed06094fa42fc3d0cdd#diff-4d0c40e224c3f016cc1e9fb313a4ee02R48-R50

We surrounded the button label with a span tag that prevents browsers from showing a border around (black in the screenshot, but its color/shape may vary between browsers and/or os) when the button is clicked. We needed to fix some unit tests because of this, and I think it was causing some issues with poshi tests too, so I removed it from this PR https://github.com/liferay-echo/liferay-portal/pull/790

Can you have a look at that PR if tests fail on that PR please? That one has the old sidebar panels, with the feature flag disabled.

Thanks!

image

**Comment by Tim-Cao** [comment]
ci:test:bundle

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Pull request closed without merging**
