### PR TITLE
LPS-201588 Accessing nonexistent URL throws NPE and displays a malformed page

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-201588

cc: @jonathanmccann

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1287401_8285

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @lfbesada, there is a regression issue found.
When search non-existent option in Select from List fragment, no results found should be shown
image
But the actual results is dropdown menu closed.
image

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143902

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
