### PR TITLE
LPS-118704 Include the company as parameter to calculate the terms of an user

### PR DESCRIPTION
**Pull request by darquesdev**
Hi @liferay-echo, I'm sending this PR since the asset-list-api has been modified, It can be reviewed after GA5 is released. Thanks!

**Motivation**
Currently, the content recommendation feature only works using the default company (virtual instance), this story was created to support different companies to the default company in Content Recommendation. 

**Approach**
I've exposed the companyId parameter as part of the AssetListAssetEntryQueryProcessor API, then I've updated the implementation to calculate the terms of an user depending on the current company.

**How to test it** 
I've added unit tests. Integration tests will be added [here](https://issues.liferay.com/browse/LPS-118836). Functionally it is laborious to test it, I've added detailed steps as part of the [description of the story](https://issues.liferay.com/browse/LPS-111468).

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
