### PR TITLE
Don't forward until GA5 is ready - LPS-115224

### PR DESCRIPTION
**Pull request by sandrodw3**
We are still not forwarding this one, as we decided to send it after the GA5. I'm leaving the PR here only to see if all tests are ok.

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by manoelcyreno** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
Hi @sandrodw3 and @pavel-savinov , this PR has the following issue:
1. Button, Card and Image miss custom style.
2. Update poshi since always show style panel for fragments.
3. Update semantic version for headless-delivery-api and layout-api modules.
4. Update other poshi issues to adapt the expected behavior.

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/1862

**Pull request closed without merging**
