### PR TITLE
LPS-203646 Fix back button title when configuring Widget Page Templates in Global SIte

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-203646)

## Steps 

**Case 1: edit_asset_list_entry.jsp : Configuring Widget Page Templates**

**- 2 ways:**
**Case 1.1: LayoutPageTemplateEntryActionDropdownItemsProvider.java**

- Go to Design > Page Templates > Create a Widget Page Template
- Click on the Page Template ellipsis > Configuration > See back button title 

Screenshot 2023-12-11 at 16 11 49

**Case 1.2: LayoutPageTemplateEntryActionDropdownItemsProvider.java**

- Go to Control Menu > Sites > Global Site 
- Go to Design > Widget Page Templates > Create one 
- In the Page created > click on ellipsis > Configure

Screenshot 2023-12-11 at 16 12 48

**Case 2: LayoutPrototypeVerticalCard.java: Editing WPT by clicking on the name**

- Go to Control Menu > Sites > Global Site 
- Go to Design > Widget Page Templates > Create one 
- In the Page created > click on the name > see back button title

**Case 3: ContentManager.java: Creating Web Content from Collection Display fragment**

- Go to Content & Data > Web Content > Create one
- Go to Site Builder > Collections > Create a Manual Collection with Web Content Article > Basic Web Content
- Add the Web Content created
- Go to Site Builder > Pages > Create a Collection Page > select the Collection created
- Edit the Collection Page
- Click on the Collection Display 
- Go to Collection Display Options in the right navbar
- Click on ellipsis > Edit Collection

Screenshot 2023-12-11 at 16 14 37

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
Hey @DiegoHu97 ! Just a little comment. I was testing your pr and for the _Case 1.2_ I've just seen that it only work if we click on the ellipsis menu and select "edit" but i doesn't when clicking on the title.

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
@BarbaraCabrera Updated! Thx for the review ❤️

**Comment by BarbaraCabrera** [comment]
Nice!! 🎉

**Comment by BarbaraCabrera** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward:force

**Pull request closed without merging**
