### PR TITLE
LPS-195349 Fix url calculation since the friendly url can have slashes too

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
hey @Tim-Cao Can you review if we need to update the FF for some poshi tests? this story: https://liferay.atlassian.net/browse/LPS-184193 has been moved to another epic, so the FF has changed to `LPS-195205`

**Comment by Tim-Cao** [comment]
Hi @victorg1991, NPE happens on go to blog details page via associated display page
**Steps to reproduce**

1. Add a web content
2. Add a blogs entry
3. Add a display page template for Web Content Article and Basic Web Content
4. Add a Blogs widget and Asset Publisher widget to display page template then publish
5. Mark the display page as default
6. Navigate to the Web Content admin
7. Navigate to the associated display page via View Content action
8. Click the blog entry title link on Asset Publisher

Expected Results
It should go to the blogs entry details page

Actual Results:
The following NPE is thrown:
```
2023-09-06 17:56:46.086 WARN  [http-nio-8080-exec-8][PortalImpl:6446] null
org.apache.jasper.JasperException: java.lang.NullPointerException
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:440) ~[jasper.jar:9.0.75]
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473) ~[jasper.jar:9.0.75]
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377) ~[jasper.jar:9.0.75]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) ~[servlet-api.jar:4.0.FR]
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:319) ~[?:?]
	at com.liferay.portal.osgi.web.servlet.jsp.compiler.internal.JspServlet.service(JspServlet.java:331) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.servlet.ResponseStateHandler.processRequest(ResponseStateHandler.java:63) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.context.DispatchTargets.doDispatch(DispatchTargets.java:120) ~[?:?]
	at org.eclipse.equinox.http.servlet.internal.servlet.RequestDispatcherAdaptor.include(RequestDispatcherAdaptor.java:48) ~[?:?]
	at com.liferay.portal.servlet.TransferHeadersHelperImpl$TransferHeadersRequestDispatcher.include(TransferHeadersHelperImpl.java:155) ~[portal-impl.jar:?]
	at com.liferay.layout.type.controller.display.page.internal.layout.type.controller.DisplayPageLayoutTypeController.includeLayoutContent(DisplayPageLayoutTypeController.java:212) ~[?:?]
	at com.liferay.portal.model.impl.LayoutImpl.includeLayoutContent(LayoutImpl.java:1021) ~[portal-impl.jar:?]
	at com.liferay.portal.action.LayoutAction.processLayout(LayoutAction.java:425) [portal-impl.jar:?]
	at com.liferay.portal.action.LayoutAction.execute(LayoutAction.java:165) [portal-impl.jar:?]
	at com.liferay.portal.struts.PortalRequestProcessor._process(PortalRequestProcessor.java:386) [portal-impl.jar:?]
	at com.liferay.portal.struts.PortalRequestProcessor.process(PortalRequestProcessor.java:142) [portal-impl.jar:?]
	at com.liferay.portal.internal.servlet.MainServlet.doGet(MainServlet.java:189) [portal-impl.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:529) [servlet-api.jar:4.0.FR]
	at com.liferay.portal.internal.servlet.MainServlet.service(MainServlet.java:589) [portal-impl.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:623) [servlet-api.jar:4.0.FR]
	at com.liferay.shielded.container.internal.proxy.ServletWrapper.service(ServletWrapper.java:103) [com.liferay.shielded.container.impl.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209) [catalina.jar:9.0.75]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153) [catalina.jar:9.0.75]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) [tomcat-websocket.jar:9.0.75]
```

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140425

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
