### PR TITLE
LPS-186892 Inline since there is no more usages

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by lfbesada — APPROVED** [review]
@victorg1991 LGTM 🎉 
But previous to ci:forward palante I think you should add a layout-api baseline commit.
Could you please add it and then type "ci:forward palante"? don't forget the "palante" that is the token word! Otherwise, it won't work.
Regards

**Comment by victorg1991** [comment]
ci:forward palante

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
