### PR TITLE
LPS-140136 Preview draft action needs update permission

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-140136 Don't show preview and discard draft actions when the user doesn't have update permissions for the page
- LPS-140136 Remove unused configurationPid

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:reevaluate:1257401_477

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/6046

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
