### PR TITLE
LPS-155230 Fail to add a fragment within Publications

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-155230 Adds dependencies
- LPS-155230 Enable change tracking for client extensions
- LPS-155230 Build service

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@ealonso, built service agan resolving conflicts

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/8329

**Pull request closed without merging**
