### PR TITLE
[TS] LPS-142251 Remove portletResource, because it causes not persisting portlet settings when saving a content in addcontent panel and returning to the widget page. Regression caused by LPS-116913.

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hi Team,

LPS: https://issues.liferay.com/browse/LPS-142251
Regression issue caused by https://issues.liferay.com/browse/LPS-116913 that effects the configured portlets on widget page. After creating a content and returning to the page, the portlets look like non-configured. This seems a critical issue that was reported by one of our customer. 

We had similar issue in the past with portletResource when we removed it after experiencing regressions.

@jkappler @victorg1991 

Could you please review it?
Thank you!

### CODE REVIEW

**Comment by orsolyaDekany** [comment]
ci:test:sf

**Comment by orsolyaDekany** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@Tim-Cao, we are going to remove the success message when adding content directly from pages until we find a better way to do it, it creates too many problems (just like this issue)

**Pull request closed without merging**
