### PR TITLE
LPS-134656 Inline text is not shown in the content list when there are only images in a rich text editable

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
