### PR TITLE
LPS-173176 Take into account prefix in edit mode

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
Hey @victorg1991, regression found. **Steps to reproduce**: 

[Task :apps:layout:layout-content-page-editor-web:packageRunTest](https://testray.liferay.com/home/-/testray/case_results/2166595975)

1. cd ~/dev/projects/liferay-portal/modules
2. gw :apps:layout:layout-content-page-editor-web:packageRunTest

```[exec] > Task :apps:layout:layout-content-page-editor-web:packageRunTest FAILED
     [exec] PASS test/page_editor/app/components/ImageSelectorSize.test.js
     [exec] PASS test/page_editor/app/components/fragment-configuration-fields/HideFromSearchField.test.js
     [exec] PASS test/page_editor/app/components/layout-data-items/ColumnWithControls.test.js
     [exec] PASS test/page_editor/app/components/app-hooks/usePreviewURL.test.js
     [exec] FAIL test/page_editor/app/processors/ImageProcessor.test.js
     [exec]   ??? ImageProcessor ??? render ??? wraps everything with an anchor if the editable element is not a link
     [exec] 
     [exec]     expect(received).toBe(expected) // Object.is equality
     [exec] 
     [exec]     Expected: "http://localpie"
     [exec]     Received: "undefinedhttp://localpie"
     [exec] 
     [exec]       139 | 
     [exec]       140 | 			expect(image.parentElement instanceof HTMLAnchorElement).toBe(true);
     [exec]     > 141 | 			expect(image.parentElement.getAttribute('href')).toBe(
     [exec]           | 			                                                 ^
     [exec]       142 | 				'http://localpie'
     [exec]       143 | 			);
     [exec]       144 | 			expect(image.parentElement.getAttribute('target')).toBe('_blank');
     [exec] 
     [exec]       at Object.<anonymous> (test/page_editor/app/processors/ImageProcessor.test.js:141:53)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
     [exec] PASS test/page_editor/app/utils/getUntiqueName.test.js

**Comment by victorg1991** [comment]
Should be fixed now @alessandromalves :)

**Comment by victorg1991** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
The failures are not related to this PR. See https://github.com/brianchandotcom/liferay-portal/pull/129048

**Comment by alessandromalves** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Recalling CI once the results were not imported correctly

**Comment by alessandromalves** [comment]
ci:forward

**Pull request closed without merging**
