### PR TITLE
LPS-120819 Change key shortcut label depending on the OS

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by victorg1991** [comment]
https://github.com/liferay-echo/liferay-portal/pull/2349

**Comment by victorg1991** [comment]
ci:close

**Pull request closed without merging**
