### PR TITLE
LPD-30389 Add portlet preferences to store the asset list entry ERC and the scope ERC if apply

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-30389

This PR introduces a preference to persist template group, displayStyleGroupExternalReferenceCode, even when displayStyleGroupKey exists, due to these reasons:

- The group persistence must be avoided when it matches the portlet's group and displayStyleGroupKey is always provided.
- Persisting the group's ERC instead of the group's key is more aligned with our existing preferences and entity finders, which primarily use ERC.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by JavierMoral** [comment]
Finished testing it and LGTM!

**Comment by JavierMoral** [comment]
ci:forward

**Pull request closed without merging**
