### PR TITLE
LPS-116338, LPS-116339, LPS-116340 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-116338
https://issues.liferay.com/browse/LPS-116339
https://issues.liferay.com/browse/LPS-116340

This is only for master.

@manoelcyreno
@sandrodw3

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by sandrodw3** [comment]
♥️

**Comment by sandrodw3** [comment]
ci:close

**Comment by sandrodw3** [comment]
ci:stop

**Comment by sandrodw3** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/1389

**Comment by sandrodw3** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/1393

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/1393

**Pull request closed without merging**
