### PR TITLE
[TS] LPS-130746

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-130746

Issue is only reproducible in 72x and below, however the code changes still apply to 73x and above, thus I'm sending a master PR through.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @ChrisKian,

Could you please send this one to Core Infra Team? Since it is a general solution for PortletPreferences.

Regards,
Eudaldo.

**Comment by ChrisKian** [comment]
ci:stop

**Comment by ChrisKian** [comment]
Sent to https://github.com/shuyangzhou/liferay-portal/pull/9955

**Pull request closed without merging**
