### PR TITLE
LPS-205274 v1_4_1.LayoutClassedModelUsageUpgradeProcess fails on Oracle and DB2

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-205274

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:test:upgrade-performance

**Comment by lfbesada** [comment]
ci:test:upgrade

**Comment by achaparro** [comment]
ci:test:upgrade-performance

**Comment by achaparro** [comment]
This can be a problem from the performance perspective. I don't the database we have for the performance have fragments, but let's check it.

**Comment by achaparro** [comment]
Also, please check my comment in:
https://liferay.atlassian.net/browse/LPS-205274?focusedCommentId=2551155

I don't think like comparisons are invalid so I guess it should be something else

**Comment by lfbesada** [comment]
> Also, please check my comment in: https://liferay.atlassian.net/browse/LPS-205274?focusedCommentId=2551155
> 
> I don't think like comparisons are invalid so I guess it should be something else
> 
> @lfbesada @ealonso

Thanks a lot @achaparro your tip [here](https://liferay.atlassian.net/browse/LPS-205274?focusedCommentId=2551155) pointing BasePortletIdUpgradeProcess has helped me to realize that there is no problem because of the like in the where clause. All the issues are due to the distinct in the select clause, so the fix is to remove the distinct and it is not going to cause any performance issue.

Thank you!

Regards

**Comment by lfbesada** [comment]
ci:test:upgrade

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:upgrade-performance

**Comment by lfbesada** [comment]
ci:test:upgrade

**Comment by lfbesada** [comment]
ci:test:upgrade-performance

**Comment by lfbesada** [comment]
I have rebased with the current master and added https://github.com/brianchandotcom/liferay-portal/pull/146045 to pass CI. So I am relaunching the tests.

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:upgrade

**Comment by lfbesada** [comment]
ci:test:upgrade-performance

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by achaparro** [comment]
Hi @lfbesada,

The results look good to me since the upgrade process is running properly in Oracle and DB2 now. The performance issue is not caused by your changes, it is caused by a previous pull and we need to change the tests to address it.

What I would ask you to change is this:
https://github.com/liferay-echo/liferay-portal/pull/14941/files#diff-deca0937a8b6276841603d75995dafbb5ece141490fd5ccc33be76684e2c8e77R136

With that you are saying that the version should be greater or equal to 2.5.0 but less than 3.0.0. We just need the first condition since we want to wait until the plid column exists, it is not needed in other cases.

Can you change that?

Thanks.

**Comment by lfbesada** [comment]
@achaparro Thanks a lot for your feedback, I have added it and rebased it.
Thanks!

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:test:upgrade

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
