### PR TITLE
LPS-121860 Migrate v2 usages in asset/asset-display-page-item-selector-web

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

Selecting a new display page template for a Web Content article should
work as expected

**Test plan**:
- Navigate to **Design** > **Page Templates**
- Select the **Display Page Templates** tab
- Click on the **+** button to create a new **Display Page Template**
- Enter a name
- Select **Web Content Article** under the **Content Type** drop down
menu
- Select **Basic Web Content** under the **Subtype** drop down menu
- Click on **Save**
- Publish your Display Page Template
- Navigate to **Content & Data** > **Web Content**
- Create a new **Basic Web Content**
- In the sidebar on the right, search for **Display Page Template**
- In the drop down menu, select **Specific Display Page Template**
- Click on the **Select** button
- Make sure you can filter the available Display Page Templates
- Select the **Display Page Template** you created

### CODE REVIEW

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by julien** [comment]
cc @ambrinchaudhary @markocikos @jonmak08

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
