### PR TITLE
LPS-147829 Add Empty state to the tree

### PR DESCRIPTION
**Pull request by victorg1991**
The idea is to some exploratory testing of this PR

More info in the associated subtask: https://issues.liferay.com/browse/LPS-147829

Deploy: site-navigation-item-selector-web

- Navigate to Site Builder > Navigation Menus
- Create a new Navigation Menu
- Navigate to Site Builder > Pages
- Create a new (Blank) Page
- Drag and Drop the "Menu Display Widget" on the page
- Click on the elipsis menu on the right and choose "Configuration"
- Under the "Menu Items to Show" section, select the first drop down
- menu, and choose "Select Parent"
- Click on the "Menu Item" button

@david-gutierrez-mesa @liulukiwi @Tim-Cao @ozysouza

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:stop

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @victorg1991, No regression issues found during my exploratory testing. However, there is an issue. Could you fix it?
The search icon is unused since the search results is shown along with typing. Could we remove it?
For example, The search field doesn't that icon in Configure Allowed Fragments modal.
image)

**Comment by Tim-Cao** [comment]
Waiting for testing on Safari.
cc @david-gutierrez-mesa

**Comment by victorg1991** [comment]
Hey @Tim-Cao same as in the other PR, I will update the allowed fragments to include the icon and to be consistent with other search bars :)

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Tested on Safari and works as expected!

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
