### PR TITLE
LPS-135170 - API implementation for layoutTypePortlet that considers Content Pages

### PR DESCRIPTION
**Pull request by ethib137**
cc: @jkappler @lfbesada @david-truong @shuyangzhou @ivicac

Please let me know if it would be helpful to have a call to discuss this PR.

One additional note:
- It may make sense to update LayoutTypePortletImpl.getExplicitlyAddedPortlets() and LayoutTypePortletImpl.getPortlets() to include portlets added to content pages, but this is not necessary to fix getPlidByPortletId since LayoutTypePortletImpl.getEmbeddedPortlets() already gets all portlets on a content page using portlet preferences.

### CODE REVIEW

**Comment by ethib137** [comment]
NOTE: As of [this ticket](https://issues.liferay.com/browse/LPS-108378) being merged portlet preferences on content pages have not been removed when the portlets are removed. To fix this should we include an upgrade step to clean up portlet preferences that exist for portlets that are no longer on the page?

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @ethib137,

I was reviewing your pr and I found that you are not only fixing [**API implementation for layoutTypePortlet that considers Content Pages**](https://issues.liferay.com/browse/LPS-135170), you are also fixing other issues with the same LPS ticket, so for the moment I've only reviewed  the part related with it. 

My idea is send it first to master and then we should send the other parts in different LPS, since those should send to different teams.

I already send the code related with LPS-135170 here https://github.com/liferay-echo/liferay-portal/pull/7582.

Please let me know if you have any question.

**Comment by ealonso** [comment]
Hey @ethib137,

Since the first part is already merge on master, and we need to send different pr, one of them to Commerce team and the other one to Echo, What do you thing about closing it and open a new one with the corresponding code?

Thanks!!
Eudaldo

**Comment by ethib137** [comment]
Hey @ealonso yeah I'm happy to send additional PRs for those. The commerce one is pretty straightforward but it will need the pull to echo to be merged to be of any use. For the one to echo, I've discovered some more complexity around how ownerType for portlet preferences is managed. This PR, was simply updating content pages to follow what widget pages was doing in setting the portletPreferences ownerType to be PortletKeys.PREFS_OWNER_TYPE_LAYOUT even when the portlet has set `com.liferay.portlet.preferences-unique-per-layout=false`.

This is a much easier fix to make, but it doesn't seem to follow our definition of [preferences-unique-per-layout](https://docs.liferay.com/portal/7.4-latest/7.4-ga8/definitions/liferay-portlet-app_7_4_0.dtd.html#preferences-unique-per-layout). But... switching things the other way to set the ownerType to PortletKeys.PREFS_OWNER_TYPE_GROUP when `com.liferay.portlet.preferences-unique-per-layout=false` requires many more changes throughout Liferay and is a bit more complex.

For instance, Content pages calls [this method](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/PortletPreferencesFactoryImpl.java#L969) resulting in the owner type being set to PortletKeys.PREFS_OWNER_TYPE_GROUP , but if that is set then content pages won’t be able to delete portletPrefernces using this method [here](https://github.com/liferay/liferay-portal/blob/master/modules/apps/layout/layout-impl/src/main/java/com/liferay/layout/internal/util/LayoutCopyHelperImpl.java#L613), and getPlidFromPortletId won’t be able to find those portlets since it uses this call [here](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portal/model/impl/LayoutImpl.java#L1418).
Additionally any place that calls [PortletPreferencesFactoryImpl.getLayoutPortletSetup](https://github.com/liferay/liferay-portal/blob/master/portal-impl/src/com/liferay/portlet/PortletPreferencesFactoryImpl.java#L286) such as widget pages or content pages for embedded widgets would also need to be changed.

It would be helpful to have a conversation about it first to make sure that I'm taking the correct approach.

**Pull request closed without merging**
