### PR TITLE
LPS-165966 HR_73

### PR DESCRIPTION
**Pull request by SelenaAungst**
### [LPS-165966](https://issues.liferay.com/browse/LPS-165966) HR_73 
**Solution**
Added clay alert to utilize autoClose feature. This solves the issue of not having enough time to navigate to this alert while using a screen reader. 

**Description**
Screen Reader (SR) user is not getting enough time to move to the links "The recycle Bin" and "Undo" on the success message alert

**Steps to reproduce**

1. From the menu, Navigate to Content and Data > Web content
2. Navigate to More options (three dots) menu and expand it
3. Press enter on move to recycle bin option
4. Press enter on ok button. Alert message opens

**Results of Testing**
_Expected Result:_
Message stays open until the user uses any of the links/buttons to navigate to the recycle bin, undo the deletion, or close the alert.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:sf

**Comment by SelenaAungst** [comment]
ci:test:relevant

**Pull request closed without merging**
