### PR TITLE
LPS-128016 - Extract logic to compute fileEntryId to a common class

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @p2kmgcl

[LPS-128016](https://issues.liferay.com/browse/LPS-128016) changes on top of changes for [LPS-127937](https://issues.liferay.com/browse/LPS-127937) which were already sent [here](https://github.com/brianchandotcom/liferay-portal/pull/98833)

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:reevaluate:1117401_8403

**Comment by ruben-pulido** [comment]
ci:reevaluate:1117401_8403

**Comment by ruben-pulido** [comment]
ci:reevaluate:1117401_8403

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
