### PR TITLE
LPS-159106 If layoutStructureItem is null this assetListEntryUsage is not present in the current layoutStructure

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
Collection selector fragments are generating NPE in the Page Editor

Proposed Solution
========
The issue relates LPS-149434, which change 0 being the default experienceId. The editor in this case is not using the correct experience and returns a layoutStructure that is wrong. So firstly, I'm fixing layoutStructure generation based on logics from LPS-149434. Secondly, the assetListEntryUsages were not limited to the current experience either, so if there are multiple experiences, an NPE could be avoided by checking the layoutStructureItem.

Steps to Verify
========
1. Go to Design > Fragments
2. Click on the kebab menu of "FRAGMENT SETS" and import the attached file: collections-20220720135554025.zip
3. Go to Site Builder > Collections and add a dynamic collection:
4. Web Content Article as the "Item Type"
5. And "Basic web Content" as the Item Subtype
6. Go to Site Builder > Pages and add a blank (content) page
7. Add the fragment "Example" > "CollectionSelector" to the page
8. Click on the fragment and select the created collection
9. Publish the page
10. Go to Site Builder > Pages and click on the 3 dot menu beside the page and select "Edit"

Expected behaviour: Page editor appears with no errors
Actual behaviour: An error appears in the UI: "Content Page Editor Temporarily Unavailable"

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @balazssk This is working fine!

i think we can simplify it a bit more. I believe it should be better justo add a segmentsExperienceId parameter to this method: https://github.com/liferay/liferay-portal/blob/0b8860591f0d743c1a51dd7bcd3534481527dfc4/modules/apps/layout/layout-content-page-editor-web/src/main/java/com/liferay/layout/content/page/editor/web/internal/util/AssetListEntryUsagesUtil.java#L85

and you can use this segmentsExperienceId to calculate the layoutStructure. There is no need to do an extra calculation in this class :) Also the null check is not mandatory since if we are in the correct segment the layoutStructureItem should exist

What do you think?

**Comment by balazssk** [comment]
Hi @victorg1991 ,
Thanks for the hint! Indeed segmentsExperienceId would be better retrieved from a method parameter. I'll change this is the next PR.
As for the null check of the layoutStructureItem, it is not immediately visible with the base scenario, but once there are at least  2 Experiences, `assetListEntryUsages` will have 2 usages that are distinct and 1 will always trigger an NPE (`layoutStructureItem` will be `null`) here when checked against the other experience's `layoutStructure`. What do you think?

Also, I should send a new PR, right?

**Comment by victorg1991** [comment]
> As for the null check of the layoutStructureItem, it is not immediately visible with the base scenario, but once there are at least 2 Experiences, assetListEntryUsages will have 2 usages that are distinct and 1 will always trigger an NPE (layoutStructureItem will be null) here when checked against the other experience's layoutStructure. What do you think?

True, we can leave the null check then :)

> Also, I should send a new PR, right?

Whatever you prefer, you can push force the new changes here, or you can close this one and open a new one, as you wish :)

**Comment by balazssk** [comment]
Cheers @victorg1991 ,
I've pushed the updates here

**Comment by victorg1991** [comment]
Thanks!! LGTM

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
