### PR TITLE
[TS] LPS-140318 | Changes in the master page won't propagate to the content page

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-140318
Thank you!

------

We discussed the [regression](https://issues.liferay.com/browse/LPS-140737) issue on [PTR-2713](https://issues.liferay.com/browse/PTR-2713) with @dacousalr. According to my findings, the HSQL database regression was caused by the difference in the preferences map order. The validation was based on the string comparison of two XMLs, because of this, the comparison becomes order sensitive to the order of the preferences. To remove this limitation, I compare the two preferences map directly without creating XMLs from them.

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Thanks @bakayattila!

Great finding! The changes look good. Forwarding them to Brian

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
