### PR TITLE
LPS-190096 Make sure to return classPK as a string

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @victorg1991, the update title of selected item is not shown in item selector.
**Steps to reproduce**

1. Add a new site
2. Add a web content
3. Add a Heading fragment to a content page
4. Map the Title field of web content to Heading fragment
5. Navigate to the Mapping panel of Heading
6. Click the ellipsis button of item selector
7. Edit the web content
8. Update the title then publish
9. The mapped title is updated

**Actual Results**
The title of selected item is not updated.

**Expected Results**
The title of selected item should be also updated.

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/138379

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
