### PR TITLE
LPS-115840 Fix error in master caused because two pulls were merged in the same moment, https://github.com/brianchandotcom/liferay-portal/pull/90530 and https://github.com/brianchandotcom/liferay-portal/pull/90538

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
cc: @jpince

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:forward

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @jpince, 

The last commit fix the compile error on master, should we send it directly to Brian?

Regards,
Eudaldo

**Comment by JorgeFerrer** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
@JorgeFerrer @ealonso I manually merged this.

**Pull request closed without merging**
