### PR TITLE
LPS-116693 Auto

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @ealonso, Can not add widget element to page editor.

**Comment by Tim-Cao** [comment]
ci:test:bundle

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
ci:forward

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
