### PR TITLE
[TS] LPS-163085 adding assetcategories from page template

### PR DESCRIPTION
**Pull request by GaborKomaromi**
Hi Team,
Could you review this PR?
https://issues.liferay.com/browse/LPS-163085

Thank you and best regards,
Gábor

------------------------------------

**Reproduction Steps:**

1. Go to Categorization --> Categories --> create a vocabulary and add a category to it.
2. Go to Design --> Page Templates and add a template collection, then add a content page Template and publish it.
3. Go back to the page Templates and on the created Template click on configure and add the Category to it, then save it.
4. Go to Site Builder --> Pages and create a content Page based on the template and publish it.
5. Go to Site Builder --> Pages and click on the 3 dot menu beside the Page and select Configure, then check the category.

**Actual Result:** The category is not set on the Page.
**Expected Result:** The category is set on the page.

The category from the page template was not in the servicecontext when the page was created from a page template. I got the categoryId from the page template and passed it through the servicecontext. [AddContentLayoutMVCActionCommand](https://github.com/liferay/liferay-portal/blob/f2471ae7850b6937f6e662b274f0901413151dc8/modules/apps/layout/layout-admin-web/src/main/java/com/liferay/layout/admin/web/internal/portlet/action/AddContentLayoutMVCActionCommand.java)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by GaborKomaromi** [comment]
ci:test:sf

**Comment by GaborKomaromi** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by bakayattila** [comment]
Hi Team,
The ci is not yet configured for Gabor so I triggered the tests for him.
Best,
Attila

**Comment by ealonso** [comment]
Please see: https://github.com/liferay-echo/liferay-portal/pull/9673

**Pull request closed without merging**
