### PR TITLE
[TS] LPS-168328 | Creating a Structure with Boolean-fieldset results in a blank page

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-168328
Thank you!

----

**Steps to reproduce:**

When a fieldset is created for structures with a boolean field it results in an NPE as it tries to cast the options of the boolean to LocalizedValue. I added a check to only do this if the given options exist.

1. Go to Menu -> Content & Data -> Web Content -> Structures
2. Click on Add
3. Click on Fieldsets -> Create New Fieldset
4. Drag Boolean field on to the page -> Name it -> Save it
5. Drag the newly created fieldset onto Structure's page

 **Actual behavior:** Page goes blank and errors shown in browser console
 **Expected behavior:** Structure with Boolean-fieldset is created and can be saved

Addition question: Is there a reason why the modification only deployed locally after I bumped the version number?

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@bakayattila, wrong team, please send this to the Data Engine Team. Thanks!

**Pull request closed without merging**
