### PR TITLE
LPS-166116 Allow to preview expired articles

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Relates https://github.com/liferay-echo/liferay-portal/pull/3994

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
https://github.com/liferay-echo/liferay-portal/pull/10080

**Pull request closed without merging**
