### PR TITLE
[TS] LPS-175664

### PR DESCRIPTION
**Pull request by crodriguezy**
Motivation
This fix aims to solve case described in https://issues.liferay.com/browse/LPS-175664, that was found while investigating https://issues.liferay.com/browse/PTR-3646, where structures where not being correctly upgraded (https://issues.liferay.com/browse/LPS-173034) and once fixed manually we need to update the related contents. Those are simpler steps identified that represents our case here:

Steps to reproduce:

1. Add a new structure 'enlaces' with the following structure (child is repetible):
- Parent
  - Child
  - Child
2. Create a content based on 'enlaces' structure:
- parent
  - Child 1
  - Child 2
  - Child 3
  - Child 4
3. Update 'test' structure through 'Import and Override' option. Use the structure attached (Structure_7.4_migrada_ok.json):
- parent
  - child
   - grandchild
4. Open the content.

**Expected result:** content is updated accordingly.
**Current result:** content is not updated correctly. See Contenido Web - Liferat DXP.webm attached

(Attachments available in https://issues.liferay.com/browse/LPS-175664)

**Proposed Solution**
@carolmariaabb proposed this solution to fully fix customer's scenario, where they could not perform the upgrade again with the fix proposed in https://issues.liferay.com/browse/LPS-173034. A correct migrated structure has to be imported and replaced by the incorrect one, and related contents (also incorrect) need to be updated according to the new structure.

I tested it and it works, but it needs to be reviewed by this team.

**Screenshots (if applies)**
There is a recording attached to https://issues.liferay.com/browse/LPS-175664

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
Hey @crodriguezy,

In the video and steps, you are changing the structure using the user interface, but your logic change the import action, that it is not related with the steps and the video.

So, Could you please let us know why the changes are necessary in that file?

**Comment by crodriguezy** [comment]
Sorry @ealonso , the steps are not correct. I'll update them accordingly, since as you pointed this fix tries to solve the case where you import and replace a new json definition for a specific structure.

**Comment by ealonso** [comment]
Hey @crodriguezy,

As I can see we have the same problem if we update the structure via UI, so, Is there any reason to fixing it only for export/import action?

**Comment by crodriguezy** [comment]
Hi @ealonso ,
this was the specific case the customer reported, and it was critical for them so we only focused on it (and we don't have much time currently). I can create a new LPS with the UI case later, or do you prefer to send both fixes together?
Thanks

**Comment by crodriguezy** [comment]
Hello @ealonso , were you able to read my previous comment? 
Thanks

**Comment by ealonso** [comment]
Yes @crodriguezy, but I need more time to find another solution. I need to test the issue and try to find the best way of fixing it, since it is affecting other places like UI update.

**Pull request closed without merging**
