### PR TITLE
LPS-160998 baseline

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by jkappler** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @ealonso, the info button is missing on details page after enable Show Actions.
**Step to reproduce**

1. Add a Documents and Medias to a widget page
2. Enable the Show Actions on configuration modal of DM
3. Upload a file via DM portlet
4. Navigate to the details page of uploaded file

**Expected Results:**
The info button should be shown on details page.
image

**Actual Results:**
The info button is missing.
image

**Comment by lfbesada** [comment]
@Tim-Cao thanks for catching it! 

See: https://github.com/liferay-echo/liferay-portal/pull/9395

**Pull request closed without merging**
