### PR TITLE
LPS-170906 Check specific editable element instead of looking for any submit element within the fragment

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
Fail to map card fragment, talk to sandro on slack.

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
SF is failing here because of a source formatter bug. Fix is already merged by Brian (https://github.com/brianchandotcom/liferay-portal/pull/127568) but master is not synced, so waiting for it.

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Failure is not related.

**Comment by liulukiwi** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/127646

**Pull request closed without merging**
