### PR TITLE
LPS-186000

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso and @YurenaC, cannot add fragment entry
**Step to reproduce**

1. Add a new site
2. Add a fragment set
3. Add a basic fragment then publish

**Expected Results**
The new fragment is shown under fragment set

**Actual Results**
The fragment set is empty.
The following error is thrown in browser console
```
liferay-amd-loader | 
 A require() call has failed but no failure handler was provided.
 Note that even if the call stack of this error trace looks like coming from the Liferay AMD Loader, it is not an error in the Loader what has caused it, but an error caused by the require() call.
 The reason why the Loader is in the stack trace is because it is printing the error so that it doesn't get lost.
 However, we recommend providing a failure handler in all require() calls to be able to recover from errors better and to avoid the appearance of this message.
 
 Some information about the require() call follows:
   · Require call id: 1 
   · Required modules: frontend-js-spa-web@5.0.38/init 
   · Missing modules: frontend-js-web@5.0.88/index,frontend-js-spa-web@5.0.38/surface/Surface,frontend-js-spa-web@5.0.38/util/utils,frontend-js-spa-web@5.0.38/util/pathParser,frontend-js-spa-web@5.0.38/route/Route,frontend-js-spa-web@5.0.38/cacheable/Cacheable,frontend-js-spa-web@5.0.38/screen/Screen,frontend-js-spa-web@5.0.38/app/App,frontend-js-spa-web@5.0.38/app/LiferayApp,frontend-js-spa-web@5.0.38/screen/RequestScreen,frontend-js-spa-web@5.0.38/screen/HtmlScreen,frontend-js-spa-web@5.0.38/screen/EventScreen,frontend-js-spa-web@5.0.38/screen/ActionURLScreen,frontend-js-spa-web@5.0.38/screen/RenderURLScreen,frontend-js-spa-web@5.0.38/init 
   · Stack trace of the require() call: 
        Error
            at e.value (http://localhost:8080/o/frontend-js-loader-modules-extender/loader.js?&mac=kuyYLzgmJRuntKLenfFpZdHstco=&browserId=chrome&languageId=en_US&minifierType=js:2:17083)
            at <anonymous>:2:16
            at runJSFromText (http://localhost:8080/o/frontend-js-web/__liferay__/index.js:1:64537)
            at runScriptsInOrder (http://localhost:8080/o/frontend-js-web/__liferay__/index.js:1:64570)
            at runNextScript (http://localhost:8080/o/frontend-js-web/__liferay__/index.js:1:63913)
            at runJSFromText (http://localhost:8080/o/frontend-js-web/__liferay__/index.js:1:64565)
            at runScriptsInOrder (http://localhost:8080/o/frontend-js-web/__liferay__/index.js:1:64570)
            at runNextScript (http://localhost:8080/o/frontend-js-web/__liferay__/index.js:1:63913)
            at runJSFromText (http://localhost:8080/o/frontend-js-web/__liferay__/index.js:1:64565)
            at runScriptsInOrder (http://localhost:8080/o/frontend-js-web/__liferay__/index.js:1:64570) 
 Error: Load timeout for modules: frontend-js-spa-web@5.0.38/init
value @ loader.js:2
```

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137716

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
