### PR TITLE
LPS-194153 Inconsistency in the focus of the Control Menu buttons

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Comment by victorg1991** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Comment by alessandromalves** [comment]
The failures are not related to this PR [(comparison with acceptance routine here)](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1692809723354&testrayRunIdA=2410970934&testrayRunIdB=2410635801). See https://github.com/brianchandotcom/liferay-portal/pull/139622

**Comment by alessandromalves** [comment]
ci:close

**Pull request closed without merging**
