### PR TITLE
LPS-121778 Web content template loses its Featured Image after re-saving

### PR DESCRIPTION
**Pull request by MarcellGyopos**
Hi !

I have made some manual tests.

If I change to URL image, no issue is coming.
If I change it to no image, same.
If I upload a new image, still no issue.

Could you please review this pull request?
Thank you and best regards,
Marci

### CODE REVIEW

**Comment by MarcellGyopos** [comment]
ci:test:sf

**Comment by MarcellGyopos** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by MarcellGyopos** [comment]
Hi,
I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.
Thank you and best regards,
Marci

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
@MarcellGyopos forwarded here https://github.com/liferay-echo/liferay-portal/pull/2658 Thanks!

**Comment by pavel-savinov** [comment]
ci:stop

**Comment by pavel-savinov** [comment]
ci:close

**Pull request closed without merging**
