### PR TITLE
[TS] LPS-124521

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @brianikim

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @jonathanmccann,

Could you please send this one to @liferay-frontend user?

Thanks!!

**Comment by ealonso** [comment]
ci:stop

**Comment by jonathanmccann** [comment]
Of course, thanks for catching it.

https://github.com/liferay-frontend/liferay-portal/pull/601

**Pull request closed without merging**
