### PR TITLE
LPS 178961 Replaces com.liferay.taglib.aui.IconTag with ClayIcon

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
The motivation behind this ticket is to avoid uses of IconTags and printing mark up code from the backend in the analytics-reports-web module which corresponds to the Content Performance panel.

Proposed Solution
========
What we did to solve this problem is to change the base class from which AnalyticsReportsProductNavigationControlMenuEntry.java extends to another one which includes the usage of jsp. This allow us to separate the logic from the mark-up code.

Steps to Verify
========
1. Ching connect to Analytics Cloud.
2. Open the Content Performance panel and check that everything looks good.
3. Refresh the page with the panel opened and check that stills working fine.
4. Open anothers panel (simulation panel, A/B Test panel) and check that the panel doesn't break.

Screenshots
========
Screenshot 2023-04-12 at 17 00 18

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
Hey @Stephy6,

You are reverting the changes introduced in https://issues.liferay.com/browse/LPS-148315, those are related to performance. 

The idea of the task is replace only this logic in the java class:
```
IconTag iconTag = new IconTag();

iconTag.setCssClass(
	"btn btn-monospaced btn-unstyled component-action " +
		"sidenav-close text-secondary");
iconTag.setImage("times");
iconTag.setUrl("javascript:void(0);");
```

With the clay icon in clay taglib.

**Comment by ealonso** [comment]
@Stephy6 in SimulationProductNavigationControlMenuEntry, we are using a button instead of an icon to fix an accessibility issue https://issues.liferay.com/browse/LPS-167238

```
ButtonTag buttonTag = new ButtonTag();

buttonTag.setCssClass("close sidenav-close");
buttonTag.setDisplayType("unstyled");
buttonTag.setDynamicAttribute(
	StringPool.BLANK, "aria-label",
	_language.get(
		(HttpServletRequest)pageContext.getRequest(), "close"));
buttonTag.setIcon("times");
```
You should apply this fix to:

* LayoutReportsProductNavigationControlMenuEntry
* AnalyticsReportsProductNavigationControlMenuEntry
* SegmentsExperimentProductNavigationControlMenuEntry

**Comment by Stephy6** [comment]
> Hey @Stephy6,
> 
> You are reverting the changes introduced in https://issues.liferay.com/browse/LPS-148315, those are related to performance.
> 
> The idea of the task is replace only this logic in the java class:
> 
> ```
> IconTag iconTag = new IconTag();
> 
> iconTag.setCssClass(
> 	"btn btn-monospaced btn-unstyled component-action " +
> 		"sidenav-close text-secondary");
> iconTag.setImage("times");
> iconTag.setUrl("javascript:void(0);");
> ```
> 
> With the clay icon in clay taglib.

Understood, thank you!

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
