### PR TITLE
LPS-193226 Add filtering options to render times list

### PR DESCRIPTION
**Pull request by veroglez**
This PR depends on https://github.com/liferay-echo/liferay-portal/pull/13252

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
Can you update the pr to fix the conflict @veroglez? :)

**Comment by victorg1991** [comment]
LGTM :clap: :D

**Comment by victorg1991** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:forward:force

**Comment by liulukiwi** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/139517

**Pull request closed without merging**
