### PR TITLE
[TS] LPS-131795 Add #banner and #footer to the DEFAULT_WHITELIST to allow configure a portlet if added to the theme's  header or footer section

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

could you please review my fix?

**Reproduction steps:**
0) Create a theme which includes an embedded WCD within the footer 
(https://issues.liferay.com/secure/attachment/404607/testtheme-theme-master.war)
1) Start the server and log in as admin
2) Deploy the testtheme-theme,
3) Create a Content Page in Liferay
4) On the Content page, at the right-side toolbar, go to "Look and Feel" > Define a specific look and feel for this page > Change Current Theme > testtheme > Save
5) You will see a Web Content Display on the footer of the page. Hover the mouse over it to attempt editing it (e.g. selecting a web content to be displayed) - see the attached screenshot

**Expected:**
The portlet to be editable.

**Actual behavior:**
A message on the interface will pop-up and the portlet is not editable

image

https://issues.liferay.com/browse/LPS-131795

Thanks, Roland

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
Hey @rolandpakai, did you check this with some product manager/designer?

When we decided to disable banner and footer by default, it was to prevent accidental navigation when the page editor is open (ex. an user clicks a link that appears on the footer).

It think if would be better keep them disabled by default, and make this list configurable somehow, so a client can enable them on purpose (maybe temporarily).

**Comment by rolandpakai** [comment]
Hi @p2kmgcl 

no, i didnt opened a PTR about my solution.
I tryed to look after why can not be configured the portlets in the header and footer section but i didnt find any relevant information about it. 

We have a customer ticket about this issue on 7.2: https://issues.liferay.com/browse/LPP-41285

Do you think we can provide any workaround for them, or this is the expected behavior that we might improve on a Feature Request?

Thanks, Roland

**Comment by ealonso** [comment]
Hey @rolandpakai,

Could you please open a new PTR?, so we can continue talking about it there. For the moment I'm going to close the pr since as Pablo mentions this is the expected behaviour

Thanks,
Eudaldo

**Comment by rolandpakai** [comment]
Hi @ealonso @p2kmgcl 

i opened a PTR here: https://issues.liferay.com/browse/PTR-2424

Thanks, Roland

**Pull request closed without merging**
