### PR TITLE
LPS-193228 Do not make HTML title for draft layoutPage

### PR DESCRIPTION
**Pull request by ZakiMiklos**
https://liferay.atlassian.net/browse/LPS-193228

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ZakiMiklos** [comment]
ci:test

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
Hi @ZakiMiklos 
Thank you very much for your fix ❤️ 
After analyzing it, I have chosen a different approach that allows fixing the bug in already existing layouts. It is also more conservative since in the case of display pages the editing of the HTML is saved in the draft.
Please see: https://github.com/liferay-echo/liferay-portal/pull/13245
Regards

**Pull request closed without merging**
