### PR TITLE
LPS-143652 fetching group in case the site is not fully created yet

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by linolaoj** [comment]
Hi, please let me know if this pull should be sent to another team.

**Comment by linolaoj** [comment]
ci:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @linolaoj 

Thanks for the pull request!

I have been testing this pull request, following the steps detailed in the related ticket, and I get the same result with this PR as without it.

Maybe it is not that the solution does not work but that the steps described to reproduce it are not the proper ones. IMHO what is informed as a bug in this ticket is the normal behavior. If the server is stopped it will not respond, neither to the login page nor to any other request.

Please, could you reformulate the steps to follow to reproduce the bug so that it can be verified that this fix solves it?

Thanks

Regards

**Comment by lfbesada** [comment]
Hi @linolaoj 
As far as I know, with the default tomcat configuration, if you establish an HTTP connection to the server and stop that thread with a breakpoint, regardless of where placed the breakpoint, the server will queue all other HTTP requests and it will not process any until this thread is released.
Please resend this pull request once the bug description is reformulated so that it is reproducible and its fix can be confirmed.
Thank you very much!
Regards

**Pull request closed without merging**
