### PR TITLE
[TS] LPS-189199 BreadcrumbEntry titles are escaped in view layer

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
[LPS-189199](https://liferay.atlassian.net/browse/LPS-189199)
The content of Breadcrumb widgets on Content Display Pages appear escaped

Proposed Solution
========
The Breadcrumb widget handles escaping the BreadcrumbEntry's titles in the view layer (ftl, jsp). So there is no need to escape the infoItemName in BreadcrumbUtil.java

Steps to Verify
========
1. Go to Design > Page Templates > Display Page Templates
2. Create a new Display Page Template for Basic Web content
3. Add a Breadcrumb widget to the Display Page Template
4. Publish the Display Page Template
5. Using the Display Page Template’s kebab menu, set it as default
6. Go to Content & Data > Web Content
7. Create a Basic Web Content
8. Set the title to “bed & breakfast”
9. Publish the web content
10. Once back on the Web Content Admin view, use “bed & breakfast”'s kebab menu to preview it

**Expected behaviour:** The “bed & breakfast” is displayed
**Actual behaviour:** “bed &amp;&amp; breakfast” is displayed

Cheers,
Balázs

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by alessandromalves** [comment]
The failures are not related to this PR. See https://github.com/brianchandotcom/liferay-portal/pull/137105

**Comment by alessandromalves** [comment]
ci:close

**Pull request closed without merging**
