### PR TITLE
LPS-134846 Make RSS URL behavior consistent

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi guys,

As I explained in [LPS-134846](https://issues.liferay.com/browse/LPS-134846) this is a common case in environments upgraded from 6.2 or before since we used to add `p_p_cacheability=cacheLevelFull` to the RSS URL. All those end users who stored that URL in their RSS managers (like feedly) are now getting an error when trying to reach the URL... unless the Asset Publisher is set to "show full context" in display settings what should not affect this case at all.

I've followed [Dani's advice in PTR-2520](https://issues.liferay.com/browse/PTR-2520?focusedCommentId=2476327&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2476327) and send a redirect without the parameter in case it is part of the URL, so the behavior is consistent and users are not getting an error in any case.

Thanks.

Regards.

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reevaluate:1197401_8565

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by antonio-ortega** [comment]
Hey guys,

Can you move forward this pull request, please?

Thanks.

Regards.

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
