### PR TITLE
[TS] LPS-165413 File structure naming persists though the Master Template is renamed

### PR DESCRIPTION
**Pull request by tototrinh**
Hi guys,
Please help review this PR and leave your comments. Thanks.
Ticket: https://issues.liferay.com/browse/LPS-165413
Chi's Solution:
Exported file structure uses the template entry key as the subfolder name, however, when changing the name for an existing template, it is not updated accordingly, we should update the template entry key when changing the name as it is in the add new template function. Therefore the exported structure file will base on the latest name.
cc @chileces

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by tototrinh** [comment]
ci:test:sf

**Comment by tototrinh** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @tototrinh @chileces,

We are discussing about if it is a bug or not, since, we are using the key to generate the folder name and not the name of page template entry.

The idea of using the key, is because the key should be unique in the group, and changing it can cause problems. It can be used as reference in other places, and changing it means that we should replace the references.

So, we are going to evaluate it carefully and let you know our decision.

Regards,
Eudaldo.

**Comment by chileces** [comment]
Dear @ealonso,
Thank you for your feedback, this LPS will help us resolve an LPP ticket for the customer, any update on how the review process is going?
Best regards,
Chi

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
