### PR TITLE
LPS-121626 Add priority to the slider fragment

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
Looks like a random error (checked sf locally)

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
:shrug:

**Comment by jpince** [comment]
ci:forward

**Pull request closed without merging**
