### PR TITLE
LPS-142280 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-142280

This is only for master.

@david-gutierrez-mesa
@ozysouza

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test

**Comment by Tim-Cao** [comment]
ci:test

**Comment by Tim-Cao** [comment]
ci:test

**Comment by Tim-Cao** [comment]
ci:test

**Comment by jkappler** [comment]
Note: for now it cannot be reproduce locally, only CI

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
