### PR TITLE
LPS-136506 SF - Reorder

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl and @ealonso, there is a regression issue, The selected category is not shown in field after select a category in Collection Filter. Additionally, the Collection Filter doesn't work.
image

**Comment by p2kmgcl** [comment]
https://github.com/ealonso/liferay-portal/pull/3108

**Pull request closed without merging**
