### PR TITLE
LPD-37803 Add test to check that only the parent item is selected when pasting

### PR DESCRIPTION
**Pull request by veroglez**
### What to check?
- Close the topper actions dropdown when an action is selected-
- Show the breadcrumb when a grid with content inside is copied and then, an item from the previously copied grid is selected.
- When a grid with elements inside is pasted only the parent (grid) is selected when pasting.
- Prevent when a fragment is selected and press shift the configuration panel is reloaded.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
