### PR TITLE
LPS-125197 Use the name of the group of the company instead of the language key

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
@adolfopa I think the failures on the tests are related with your changes, Could you please take a look?

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
@ealonso Finally, all tests passed in our repo: https://github.com/liferay-lima/liferay-portal/pull/1779

Other than some semver issues, all other failures were flaky; The only change I made there relative to this PR was a refresh of the "Basline" commit. Are you guys ok if I forward that PR instead of retrying the tests here? That way we can save another 5 days of CI pain :-D

Thanks!

**Comment by ealonso** [comment]
https://github.com/liferay-lima/liferay-portal/pull/1779

**Pull request closed without merging**
