### PR TITLE
LPS-161955 Rename

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:reevaluate:1277401_5409

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
Hi @ealonso, I don't think this PR is going to be forward by CI. There are a lot of tests failing due LPS-166067 that are going to blocker it. I'll cancel the forward and manually send it.

**Comment by ozysouza** [comment]
ci:stop

**Comment by ozysouza** [comment]
Please see https://github.com/brianchandotcom/liferay-portal/pull/124881

**Pull request closed without merging**
