### PR TITLE
LPS-154307 - Add faviconFileEntryId to Layout and LayoutSet service.xml

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @lfbesada

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Hi @ruben-pulido , could you take a look at StagingLocalServiceTest.java:99, this reletes to your change in _layoutLocalService.updateLayout.
```    [exec] > Task :apps:staging:staging-test:compileTestIntegrationJava FAILED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/staging/staging-test/src/testIntegration/java/com/liferay/staging/service/test/StagingLocalServiceTest.java:99: error: no suitable method found for updateLayout(long,boolean,long,long,Map<Locale,String>,Map<Locale,String>,Map<Locale,String>,Map<Locale,String>,Map<Locale,String>,String,boolean,Map<Locale,String>,boolean,<null>,long,long,ServiceContext)
     [exec] 			stagingLayout = _layoutLocalService.updateLayout(
     [exec] 			                                   ^
     [exec]     method LayoutLocalService.updateLayout(Layout) is not applicable
     [exec]       (actual and formal argument lists differ in length)
     [exec]     method LayoutLocalService.updateLayout(long,boolean,long,Date) is not applicable
     [exec]       (actual and formal argument lists differ in length)
     [exec]     method LayoutLocalService.updateLayout(long,boolean,long,long,long) is not applicable
     [exec]       (actual and formal argument lists differ in length)
     [exec]     method LayoutLocalService.updateLayout(long,boolean,long,long,Map<Locale,String>,Map<Locale,String>,Map<Locale,String>,Map<Locale,String>,Map<Locale,String>,String,boolean,Map<Locale,String>,boolean,byte[],long,long,long,ServiceContext) is not applicable
     [exec]       (actual and formal argument lists differ in length)
     [exec]     method LayoutLocalService.updateLayout(long,boolean,long,String) is not applicable
     [exec]       (actual and formal argument lists differ in length)
     [exec]     method LayoutLocalService.updateLayout(long,boolean,long,String,byte[],String,String,long,String,long,long) is not applicable
     [exec]       (actual and formal argument lists differ in length)
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/staging/staging-test/src/testIntegration/java/com/liferay/staging/service/test/StagingLocalServiceTest.java:110: error: no suitable method found for updateLayout(long,boolean,long,long,Map<Locale,String>,HashMap<Locale,String>,Map<Locale,String>,Map<Locale,String>,Map<Locale,String>,String,boolean,Map<Locale,String>,boolean,<null>,long,long,ServiceContext)
     [exec] 			stagingLayout = _layoutLocalService.updateLayout(
     [exec] 			                                   ^
     [exec]     method LayoutLocalService.updateLayout(Layout) is not applicable
     [exec]       (actual and formal argument lists differ in length)
     [exec]     method LayoutLocalService.updateLayout(long,boolean,long,Date) is not applicable
     [exec]       (actual and formal argument lists differ in length)
     [exec]     method LayoutLocalService.updateLayout(long,boolean,long,long,long) is not applicable
     [exec]       (actual and formal argument lists differ in length)
     [exec]     method LayoutLocalService.updateLayout(long,boolean,long,long,Map<Locale,String>,Map<Locale,String>,Map<Locale,String>,Map<Locale,String>,Map<Locale,String>,String,boolean,Map<Locale,String>,boolean,byte[],long,long,long,ServiceContext) is not applicable
     [exec]       (actual and formal argument lists differ in length)
     [exec]     method LayoutLocalService.updateLayout(long,boolean,long,String) is not applicable
     [exec]       (actual and formal argument lists differ in length)
     [exec]     method LayoutLocalService.updateLayout(long,boolean,long,String,byte[],String,String,long,String,long,long) is not applicable
     [exec]       (actual and formal argument lists differ in length)
     [exec] Note: /opt/dev/projects/github/liferay-portal/modules/apps/staging/staging-test/src/testIntegration/java/com/liferay/staging/test/StagingImplTest.java uses or overrides a deprecated API.
     [exec] Note: Recompile with -Xlint:deprecation for details.
     [exec] 2 errors 
```

And there's startup issue when starting the bundle upgraded from 6.2,7.0,7.1,7.2,7.3,7.4:
```   [java] 2022-05-23 22:50:13.757 INFO  [main][UpgradeProcess:97] Upgrading com.liferay.layout.internal.upgrade.v1_2_1.LayoutAssetUpgradeProcess
     [java] 2022-05-23 22:50:13.791 ERROR [main][SqlExceptionHelper:142] Unknown column 'this_.faviconFileEntryId' in 'field list'
     [java] 2022-05-23 22:50:13.792 ERROR [main][BasePersistenceImpl:633] Caught unexpected exception
     [java] org.hibernate.exception.SQLGrammarException: could not extract ResultSet
     [java] 	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:63) ~[hibernate-core.jar:5.6.7.Final]
     [java] 	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37) ~[hibernate-core.jar:5.6.7.Final]
     [java] 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113) ~[hibernate-core.jar:5.6.7.Final]
     [java] 	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99) ~[hibernate-core.jar:5.6.7.Final]
     [java] 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:67) ~[hibernate-core.jar:5.6.7.Final]
     [java] 	at org.hibernate.loader.Loader.getResultSet(Loader.java:2322) ~[hibernate-core.jar:5.6.7.Final]
     [java] 	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2075) ~[hibernate-core.jar:5.6.7.Final]
     [java] 	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037) ~[hibernate-core.jar:5.6.7.Final]
     [java] 	at org.hibernate.loader.Loader.doQuery(Loader.java:956) ~[hibernate-core.jar:5.6.7.Final]
     [java] 	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:357) ~[hibernate-core.jar:5.6.7.Final]
     [java] 	at org.hibernate.loader.Loader.doList(Loader.java:2868) ~[hibernate-core.jar:5.6.7.Final]
     [java] 	at org.hibernate.loader.Loader.doList(Loader.java:2850) ~[hibernate-core.jar:5.6.7.Final]
     [java] 	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2682) ~[hibernate-core.jar:5.6.7.Final]
     [java] 	at org.hibernate.loader.Loader.list(Loader.java:2677) ~[hibernate-core.jar:5.6.7.Final]
     [java] 	at org.hibernate.loader.criteria.CriteriaLoader.list(CriteriaLoader.java:109) ~[hibernate-core.jar:5.6.7.Final]
     [java] 	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1922) ~[hibernate-core.jar:5.6.7.Final]
     [java] 	at org.hibernate.internal.CriteriaImpl.list(CriteriaImpl.java:370) ~[hibernate-core.jar:5.6.7.Final]
     [java] 	at com.liferay.portal.dao.orm.hibernate.DynamicQueryImpl.list(DynamicQueryImpl.java:140) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.dao.orm.hibernate.DynamicQueryImpl.list(DynamicQueryImpl.java:126) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.findWithDynamicQuery(BasePersistenceImpl.java:520) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.service.base.LayoutLocalServiceBaseImpl.dynamicQuery(LayoutLocalServiceBaseImpl.java:185) ~[portal-impl.jar:?]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
     [java] 	at com.liferay.portal.service.impl.LayoutLocalServiceStagingAdvice$LayoutLocalServiceStagingInvocationHandler._invoke(LayoutLocalServiceStagingAdvice.java:834) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.service.impl.LayoutLocalServiceStagingAdvice$LayoutLocalServiceStagingInvocationHandler.invoke(LayoutLocalServiceStagingAdvice.java:673) ~[portal-impl.jar:?]
     [java] 	at com.sun.proxy.$Proxy292.dynamicQuery(Unknown Source) ~[?:?]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
     [java] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57) ~[portal-impl.jar:?]
     [java] 	at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49) ~[portal-impl.jar:?]
     [java] 	at com.sun.proxy.$Proxy292.dynamicQuery(Unknown Source) ~[?:?]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
     [java] 	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.executeDynamicQuery(DefaultActionableDynamicQuery.java:349) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery$1.call(DefaultActionableDynamicQuery.java:272) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery$1.call(DefaultActionableDynamicQuery.java:268) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.doPerformActions(DefaultActionableDynamicQuery.java:326) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery.performActions(DefaultActionableDynamicQuery.java:86) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.layout.internal.upgrade.v1_2_1.LayoutAssetUpgradeProcess.doUpgrade(LayoutAssetUpgradeProcess.java:69) ~[?:?]
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.lambda$upgrade$0(UpgradeProcess.java:100) ~[portal-kernel.jar:?]
     [java] 	at com.liferay.portal.db.partition.DBPartitionUtil.forEachCompanyId(DBPartitionUtil.java:118) [portal-impl.jar:?]
     [java] 	at com.liferay.portal.dao.db.BaseDB.process(BaseDB.java:356) [portal-impl.jar:?]
     [java] 	at com.liferay.portal.kernel.dao.db.BaseDBProcess.process(BaseDBProcess.java:327) [portal-kernel.jar:?]
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:87) [portal-kernel.jar:?]
     [java] 	at com.liferay.portal.kernel.upgrade.UpgradeProcess.upgrade(UpgradeProcess.java:124) [portal-kernel.jar:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor$UpgradeInfosRunnable.run(UpgradeExecutor.java:230) [bundleFile:?]
     [java] 	at com.liferay.portal.output.stream.container.internal.OutputStreamContainerFactoryTrackerImpl.runWithSwappedLog(OutputStreamContainerFactoryTrackerImpl.java:134) [bundleFile:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.SwappedLogExecutor.execute(SwappedLogExecutor.java:51) [bundleFile:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.executeUpgradeInfos(UpgradeExecutor.java:158) [bundleFile:?]
     [java] 	at com.liferay.portal.upgrade.internal.executor.UpgradeExecutor.execute(UpgradeExecutor.java:118) [bundleFile:?]
     [java] 	at com.liferay.portal.upgrade.internal.registry.UpgradeStepRegistratorTracker$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeStepRegistratorTracker.java:214) [bundleFile:?]
     [java] 	at com.liferay.portal.upgrade.internal.registry.UpgradeStepRegistratorTracker$UpgradeStepRegistratorServiceTrackerCustomizer.addingService(UpgradeStepRegistratorTracker.java:147) [bundleFile:?]
     [java] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:943) [org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:1) [org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) [org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183) [org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:321) [org.eclipse.osgi.jar:?]
     [java] 	at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:264) [org.eclipse.osgi.jar:?]
     [java] 	at com.liferay.osgi.util.ServiceTrackerFactory.open(ServiceTrackerFactory.java:104) [bundleFile:?]
     [java] 	at com.liferay.portal.upgrade.internal.registry.UpgradeStepRegistratorTracker.activate(UpgradeStepRegistratorTracker.java:69) [bundleFile:?]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
     [java] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:310) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:300) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:341) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:983) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:956) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:765) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1053) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1007) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1216) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1137) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:944) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:880) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1168) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:125) [bundleFile:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:891) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469) [org.eclipse.osgi.jar:?]
     [java] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:906) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:892) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:128) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:959) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:732) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1053) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1007) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1216) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1137) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:944) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:880) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1168) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:125) [bundleFile:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:891) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469) [org.eclipse.osgi.jar:?]
     [java] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:906) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager$3.register(AbstractComponentManager.java:892) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.RegistrationManager.changeRegistration(RegistrationManager.java:128) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.registerService(AbstractComponentManager.java:959) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:732) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1053) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.DependencyManager$SingleStaticCustomizer.addedService(DependencyManager.java:1007) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1216) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.customizerAdded(ServiceTracker.java:1137) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.trackAdding(ServiceTracker.java:944) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$AbstractTracked.track(ServiceTracker.java:880) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.manager.ServiceTracker$Tracked.serviceChanged(ServiceTracker.java:1168) [bundleFile:?]
     [java] 	at org.apache.felix.scr.impl.BundleComponentActivator$ListenerInfo.serviceChanged(BundleComponentActivator.java:125) [bundleFile:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:109) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:891) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:804) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:127) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:228) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:469) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:487) [org.eclipse.osgi.jar:?]
     [java] 	at org.eclipse.osgi.internal.framework.BundleContextImpl.registerService(BundleContextImpl.java:1004) [org.eclipse.osgi.jar:?]
     [java] 	at com.liferay.portal.tools.DBUpgrader._registerModuleServiceLifecycle(DBUpgrader.java:256) [portal-impl.jar:?]
     [java] 	at com.liferay.portal.tools.DBUpgrader._upgradeModules(DBUpgrader.java:346) [portal-impl.jar:?]
     [java] 	at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:166) [portal-impl.jar:?]
     [java] 	at com.liferay.portal.tools.DBUpgrader.upgrade(DBUpgrader.java:154) [portal-impl.jar:?]
     [java] 	at com.liferay.portal.tools.DBUpgrader.main(DBUpgrader.java:130) [portal-impl.jar:?]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
     [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_121]
     [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
     [java] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
     [java] 	at com.liferay.portal.tools.db.upgrade.client.DBUpgraderLauncher.main(DBUpgraderLauncher.java:54) [com.liferay.portal.tools.db.upgrade.client.jar:?]
     [java] Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'this_.faviconFileEntryId' in 'field list'
     [java] 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql.jar:8.0.21]
     [java] 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql.jar:8.0.21]
     [java] 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql.jar:8.0.21]
     [java] 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql.jar:8.0.21]
     [java] 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003) ~[mysql.jar:8.0.21]
     [java] 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52) ~[hikaricp.jar:?]
     [java] 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java) ~[hikaricp.jar:?]
     [java] 	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57) ~[hibernate-core.jar:5.6.7.Final]
     [java] 	... 142 more
```

**Comment by ruben-pulido** [comment]
Thank you @liulukiwi!
I'll fix the test and resend it

**Comment by ruben-pulido** [comment]
https://github.com/liferay-echo/liferay-portal/pull/8192

**Pull request closed without merging**
