### PR TITLE
LPD-7205 Adjust journal styles

### PR DESCRIPTION
**Pull request by p2kmgcl**
> Needs `feature.flag.LPS-114700=true`

New web content editor:
image

To be reviewed by Platform Experience:
- [x] https://github.com/liferay-echo/liferay-portal/commit/4738119d177b72bc36827b26bf47e12c6847926c
- [x] https://github.com/liferay-echo/liferay-portal/commit/0d4067a195ba6813791935a452f1ea7076c953c2

To be reviewed by BPM:
- [ ] https://github.com/liferay-echo/liferay-portal/commit/0276d3aa83706c9c59f72160a7f5bfd2e87e5079

To be reviewed by echo:
- [x] https://github.com/liferay-echo/liferay-portal/commit/54ee33d953243af1dbe928e26923538735230410
- [x] https://github.com/liferay-echo/liferay-portal/commit/e4572c2092ab0ddb84968eb067257d0db288e9eb

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
Marvelous :heart_eyes:

**Review by matuzalemsteles — APPROVED** [review]
LGTM

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:report:2534412597

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
