### PR TITLE
LPS-124319 Truncates text for very long titles and shows tooltip to avoid missing information

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi guys,

Can you check this pull request, please?

You can find more information about how to reproduce the issue in [LPS-124319](https://issues.liferay.com/browse/LPS-124319).

Before submit it I checked the solution with @marcoscv-work and @eduardoallegrini

Thanks.

Regards.

/cc @dacousalr

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Thanks a lot for fixing this! Works nice 👏

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
