### PR TITLE
LPD-24944 Add External Reference Code to Navigation Menus

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Motivation

[Link to ticket](https://liferay.atlassian.net/browse/LPD-24944)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by ealonso** [comment]
@BarbaraCabrera We are not adding update methods, and fetch methods in local service are already autogenerated, so it is not necessary to add it.

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/15647

**Pull request closed without merging**
