### PR TITLE
LPS-188294 Fix duplicated web contents when filtering with Recent and Status

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Previous pull: https://github.com/liferay-core-infra/liferay-portal/pull/4851

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Hi @georgel-pop-lr 
Thanks for the fix ❤️ 
LGTM 🎉 
Regards

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137551

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
