### PR TITLE
LPS-132737 Isolate Product Menu, Control Menu, Add Panel, Simulation Menu, Page Audit, Page Editor Toolbar CSS

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-132737

@victorg1991 Resending https://github.com/liferay-echo/liferay-portal/pull/5156 with rtl fix (Thanks @izaera) and visual fixes for user icon and page tree icons.

RTL Screenshot
rtl-working

User Icon & Page Tree Screenshot
fixed

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:stop

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:bundle

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
Hi @victorg1991, no regression issue found according to ci:test:echo results
https://testray.liferay.com/home/-/testray/runs/compare?formDate=1626861328347&testrayRunIdA=1548579940&testrayRunIdB=1548605363

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/5275

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
