### PR TITLE
LPS-132172 Implement card item

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
LGTM 😄 Cards look very beautiful!

**Comment by victorg1991** [comment]
fixing those

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Pull request closed without merging**
