### PR TITLE
[TS] LPS-202412 Content Dashboard displays the first web content author and not the last editor

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you review this fix?
https://liferay.atlassian.net/browse/LPS-202412
best,
Attila

------

Reproduction Steps:

1. Open the main menu on the top right --> Control Panel --> Users --> Users and Organizations --> add a user and assignn administrator role to it.
2. Go to the Users page, click on the kebab menu beside new user, and select “Impersonate User”.
3. Go to DXP Site --> Content & Data --> Web Content and add basic web content.
4. Click on the user profile icon on the upper right and select "Be yourself again".
5. Go to DXP Site --> Content & Data --> Web Content, edit the previously created web content, and publish it.
6. Open the main menu on the top right --> Applications --> CONTENT --> and select Content Dashboard.
7. Check the Content list, check under the Author the user icon, and click on the info icon "i" to open the info pane and check the author details.

**Actual Result**: On the content list the author displays the new user and on the info panel it also displays the new user and for the edited content it also displays new user as the author.
**Expected Result**: The author icon under the Content list should display "Test Test" and on the info panel "Test Test" should be displayed as the author of the content latest version.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/144247

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
