### PR TITLE
LPS-168864 Add new template for Disclosure Navigation Menu

### PR DESCRIPTION
**Pull request by veroglez**
https://issues.liferay.com/browse/LPS-168850
It fixes https://issues.liferay.com/browse/LPS-167245

**How to test:**
1. Create several content pages (some nested)
2. Go to Home page
3. Add a Menu Display widget
4. Go to its configuration (elipsis button)
5. Go to Setup tab
6. Select Bar with Links in Display Template field
7. Save it
8. Publish the page
9. Test with JAWS

**Expected result:**
All menu items have to be read as links

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Hey @veroglez,

What about the old template? Why we don't just update it? 

The default template of navigation portlet, is going to be the older one, right?

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
Awesome! :D

**Comment by veroglez** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1307401_5552

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
