### PR TITLE
LPS-197358 Navigation Menu Configuration Description is Inaccurate

### PR DESCRIPTION
**Pull request by jkappler**
https://liferay.atlassian.net/browse/LPS-197358

Proposed new message from the Design Team: When creating a new page, display an option to allow adding it to this navigation menu.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by alessandromalves** [comment]
The related failures ([comparison with acceptance routine here](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1696431300259&testrayRunIdA=2435187856&testrayRunIdB=2436245782)) only needed a test fix. See https://github.com/liferay-echo/liferay-portal/pull/13916

**Comment by alessandromalves** [comment]
ci:close

**Pull request closed without merging**
