### PR TITLE
[TS] LPS-127728

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This PR restores the link to edit scheduled Web Contents from Web Content Display widgets unintendedly removed in LPS-58011. Please, see [PTR-2239](https://issues.liferay.com/browse/PTR-2239) for more details.

Could you please review it?

Please, let me know if any clarification is needed.

Thanks in advance

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
LGTM :)

**Comment by victorg1991** [comment]
Thanks!

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
