### PR TITLE
LPS-149594 Add icons to Page's drop-down

### PR DESCRIPTION
**Pull request by DiegoHu97**

### CODE REVIEW

**Comment by victorg1991** [comment]
Hey @DiegoHu97 

I believe there is another place we need to update:
Screenshot 2022-03-28 at 09 49 36

In order to show this view, you need to add some widgets to the page and the option "Orphan Portlets" will appear.

Checking that view we probably need to change the icon for each row to match the one from the managment toolbar

Everything else is fine :D

**Comment by victorg1991** [comment]
LGTM :)

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7633

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
