### PR TITLE
LPS-127513 Synchronize site's available locales with the instance's available locales.

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

@MarcellGyopos
https://github.com/IstvanD/liferay-portal/pull/139

Thank you and best regards,
István

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
