### PR TITLE
LPS-125510 Adapt tests

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
Brian has asked for a naming change, this was reviewed here: https://github.com/liferay-echo/liferay-portal/pull/3570

**Comment by victorg1991** [comment]
ci:foward

**Comment by victorg1991** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:reevaluate:1222004_7743

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:reevaluate:1242004_594

**Comment by victorg1991** [comment]
rebasing..

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
