### PR TITLE
LPS-129552 Can not link to a public page when adding a link in Rich Text

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
This is a fix for https://issues.liferay.com/browse/LPS-129552. 

**Steps to reproduce:** 
1. Go to Product Menu > Web Content > Create a new Web Content
2. On the editor, try to add a link(Click Browse Server > Go to Public Pages tab > Select one page)

Screenshot 2021-03-25 at 13 52 06

**Expected result:**
Can select a page to link.
**Actual Result**
Can not select a page to link: Clicking the page can not select it and no save button shows on the Select Item page

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
Sorry for the SF error, just fixed!

**Comment by victorg1991** [comment]
Thanks!!

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
