### PR TITLE
LPS-136421 Redirect non-authenticated users to login page

### PR DESCRIPTION
**Pull request by epgarcia**

### CODE REVIEW

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by epgarcia** [comment]
ci:test:relevant

**Comment by epgarcia** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
Hey @epgarcia this is working fine. The behaviour is a bit weird since it tries to load the page but suddenly redirect to the login. Can we add this logic to the typeController so that it just simply redirects? Maybe somewhere around [here](https://github.com/liferay/liferay-portal/blob/dafb8a444fce6c0230ae60bb910edba12d5[…]nal/layout/type/controller/DisplayPageLayoutTypeController.java) :)

**Comment by epgarcia** [comment]
Hey @victorg1991 thanks for your feedback. It sounds like a better option, I'll send you a new PR.

**Pull request closed without merging**
