### PR TITLE
LPS-177952 Fix POSHI automation

### PR DESCRIPTION
**Pull request by alessandromalves**
This is only for master
https://issues.liferay.com/browse/LPS-177952
cc.: @david-gutierrez-mesa @Tim-Cao

### CODE REVIEW

**Comment by alessandromalves** [comment]
ci:help

**Comment by alessandromalves** [comment]
ci:test:sf

**Comment by alessandromalves** [comment]
ci:test:echo-acceptance

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
