### PR TITLE
LPS-170432 Create unique react component for product menu pages tree

### PR DESCRIPTION
**Pull request by DiegoHu97**
Motivation
=======
Actually, the product menu tree is separated in four react components, we want to unify these component in one to simplify the code.

Steps to Verify
========
1. Go to Product Menu > Page tree

Screenshots 
========
https://user-images.githubusercontent.com/91208451/207571480-e7184f87-5308-4ac2-99f9-b9634c287130.mov

Code
========
- In the first commit, I have unified the React components in one called ProductMenuTree.
- In the second commit, I have unified the part when retrieving the tree's data in only one method called "getProductMenuTreeData()" in order to simplify the code.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
Hey @DiegoHu97, super nice work here 😄 I'm leaving some comments with some things I think we can improve:
- I see that now we render a unique react component in `pages_tree.jsp`, that's awesome 🎉. Anyway, I think we could leave the different react components separated, and render all of them in `ProductMenuTree` component, so it works like a wrapper. I mean something like:

```
function ProductMenuTree(...) {
  return <>
     <LayoutFinder />
     <PageTypeSelector />
     {isNavigationMenu ? <NavigationMenuTree /> : <PagesTree />
     </>;
}
```
This way we only render one react component in the `jsp` but we have the components well separated, so it's more readable.
- I think we don't need the divs with the id like `<div id="layoutsTree" />` anymore. Could you remove them and check if everything works well?
- I think we have lost the Pages Administration link in the process (the one that is in the bottom of the pages tree). I think we should add another component for it.

What do you think? 🙂 just tell me if you need any help or if you want to pair program it!

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/10649

**Pull request closed without merging**
