### PR TITLE
LPS-173995 Styles are lost in utility pages

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-173995)

The goal of these changes is to prevent the loss of styles in utility pages view mode

## Change summary:

* Add a new dynamic include to include the styles of the utility page

## Test Scenario

* Enable FF feature.flag.LPS-162765=true
* Create a new site based on welcome site initializer
* Go to Site Builder > Pages
* Go to Utility Pages tab
* Mark existing 404 utility page as default
* Navigate to a non existing page in the site

utility pages

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
@victorg1991, applied the changes that you mentioned, it works fetén

**Comment by jkappler** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
This is working super perfecto señor J 👏

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
