### PR TITLE
[TS] LPS-121441

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team, could you please review this PR? Thanks in advance \cc @holatuwol @tototrinh

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Taking a look :)

**Comment by victorg1991** [comment]
Sent here: https://github.com/liferay-echo/liferay-portal/pull/2583 thanks!! :)

**Pull request closed without merging**
