### PR TITLE
LPS-175262 Update UI for Theme section

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://issues.liferay.com/browse/LPS-175262)

## Steps

1. Go to Product Menu > Pages
2. Create a Widget Page > Go to Widget Page configuration 
3. Go to look and feel section > Themes
Screenshot 2023-03-14 at 12 06 05
Screenshot 2023-03-14 at 12 06 20

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:forward

**Comment by DiegoHu97** [comment]
Just started reviewing :)

**Pull request closed without merging**
