### PR TITLE
LPS-145232 Add namespace and apply to translations

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by adolfopa** [comment]
ci:stop

**Comment by adolfopa** [comment]
ci:test:sf

**Comment by adolfopa** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by adolfopa** [comment]
ci:test:translation

**Comment by adolfopa** [comment]
ci:test:translation

**Comment by adolfopa** [comment]
ci:test:translation

**Comment by victorg1991** [comment]
I have resent it here @adolfopa https://github.com/liferay-echo/liferay-portal/pull/7723

**Comment by victorg1991** [comment]
will trigger a translation test suite there :)

**Pull request closed without merging**
