### PR TITLE
LPS-134288-2 Bulk action "Assign display page template" should not …

### PR DESCRIPTION
**Pull request by lfbesada**
…be available on global or depot sites.

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1117401_9107

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
The failure case is unrelated to changes in PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/103611

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
