### PR TITLE
LPD-19076 Hide label with CSS

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:reevaluate:1377401_16320

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
see: https://github.com/brianchandotcom/liferay-portal/pull/148207

**Pull request closed without merging**
