### PR TITLE
LPS-173926 Improve message for Content Page error

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-173926

This PR also should be reviewed by the Core Infra Team.

This development allows a portlet to customize its unhandled error message. It is based on taking advantage of the LanguageImpl fallback implemented [here]( https://github.com/liferay/liferay-portal/blob/d076f63b4ae36b8cce79f0d4abcaddd46071d00b/portal-impl/src/com/liferay/portal/language/LanguageImpl.java#L959-L977
).

This fallback allows a key to be introduced indicating a context between brackets, if the key is found it will be used, otherwise the same key will be used but eliminating the part between brackets. This allows us to search for the specific key for that portlet and, if it is not there, the default one will be used as before.

This language key pattern is already used in some points, for example, [here](https://github.com/liferay/liferay-portal/blob/903f53b2a67034f71071d8876503c27cf7abf19f/modules/apps/archived/portal-security-sso-google-api/src/main/java/com/liferay/portal/security/sso/google/configuration/GoogleAuthorizationConfiguration.java#L30-L50).

cc: @sandrodw3

 
Captura de Pantalla 2023-01-27 a las 16 45 04

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1387401_6016

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@lfbesada, we can send this to CI to see what they think about it 😍

**Comment by lfbesada** [comment]
Sent to core-infra for review here: https://github.com/liferay-core-infra/liferay-portal/pull/3206

**Pull request closed without merging**
