### PR TITLE
LPS-116693 baseline

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @ealonso, your changes cause the following regression issue
Add a widget page
Add an Asset Publisher to page
Click the ellipsis button on the topper of Asset Publisher
Configuration > Setup > Asset Selection
Expand Scope
Click Select
Other Site or Asset Library...

Expected Results:
Expected

Actual Results:
Actual

**Comment by ealonso** [comment]
Hey @Tim-Cao 

The second screenshot is the expected behaviour, since for some reason the Lima Team change the behaviour in our component. I made some changes to keep the behaviour that we have in 7.2, and it is the second screenshot.

Could you please take a look and fix the poshi tests?

Regards,
Eudaldo.

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/2289

**Pull request closed without merging**
