### PR TITLE
LPS-154309 Fix Page Editor's comment input styles

### PR DESCRIPTION
**Pull request by DiegoHu97**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
Hey @DiegoHu97 It seems that a bunch of css properties can be removed from `page-editor__editor-placeholder`

I believe we only need the color one. Would you mind updating it and remove the ones that are not needed?

```css
color: #6b6c7e; ✅
font-size: 0.875rem; ❌
padding-left: 16px; ❌
top: 0.35rem; ❌
```

**Comment by DiegoHu97** [comment]
updated @victorg1991, thanks!

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
