### PR TITLE
LPS-151347

### PR DESCRIPTION
**Pull request by mbowerman**
Please see [PTR-2970](https://issues.liferay.com/browse/PTR-2970) for discussion about the intended behavior and solution. Please let me know if you have any questions about this. Thanks!

LPS Link: https://issues.liferay.com/browse/LPS-151347

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Please see: https://github.com/liferay-echo/liferay-portal/pull/7769

**Pull request closed without merging**
