### PR TITLE
LPS-146669 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
cc: @crodriguezy

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/113834

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
