### PR TITLE
LPS-152915 master

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi @liferay-echo 

could you please review my fix?

The cause of the regression is the following change: 
https://github.com/brianchandotcom/liferay-portal/pull/107500/commits/95fefe8d32ddeb89a904d1219671d405faff465f

Because we lost the logic to get the content through the JournalArticleDisplay we get back the json structure from the search engine.

I reverted the LPS-147918 changes to create JournalArticleModelSummaryContributor.
After that i only reverted the changes of  [LPS-138944 journal-service: use content …](https://github.com/liferay-echo/liferay-portal/commit/cecb5d3a58ad8f2b8b798a094fad23843633e63a) 
And lastly i fixed the build issues.

…returned directly from search engine

**Reproduction steps**

1. Create a structure with a Link to Page field
2. Create a template for the structure and the Link to Page field to the template and rename the link to Home
3. Create a Web Content based on this new structure: Select the Home page for the Link to Page field
4. Go to the the start page of the portal and search for: Home

 **Actual Result:** The Web Contentt is displayed. The description of the Web Content contains the JSON structure of the Link to Page field

 **Expected Result:** The Web Contentt is displayed. The description of the Web Content is Home and it is highlighted.

### CODE REVIEW

**Comment by rolandpakai** [comment]
ci:test:sf

**Review by lfbesada — CHANGES_REQUESTED** [review]
Hi @rolandpakai 
IMHO is better to replicate the changes that would cause reverting [this commit](https://github.com/liferay-echo/liferay-portal/commit/cecb5d3a58ad8f2b8b798a094fad23843633e63a) in the JournalArticleModelSummaryContributor instead of reverting all the changes done by [LPS-147918](https://issues.liferay.com/browse/LPS-147918) 
What do you think about it?
Thanks!
Regards

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
Hi @lfbesada 

the logic from the JournalArticleIndexer was moved to the JournalArticleModelSummaryContributor on [LPS-147918](https://issues.liferay.com/browse/LPS-147918) without the JournalArticleDisplay. The JournalArticleDisplay uses the portletRequest, portletResponse which is not exists in the ModelSummaryContributor::getSummary method. 
In case we want to use the JournalArticleDisplay in the contributor we need to change the interface by adding the portletRequest, portletResponse parameters and  in the other 26 implementations too.  

Thanks, Roland

**Comment by joshuacords** [comment]
Hey guys, I'm part of the Search Team and made the change that's being reverted here. When I made the commit change I didn't understand how WC Structures where indexed. This shows that we're indexing everything returned from [getDDMFieldValueString](https://github.com/liferay/liferay-portal-ee/blob/c6768deff7f788b7c3430013114a7c4d6d892cdb/modules/apps/dynamic-data-mapping/dynamic-data-mapping-service/src/main/java/com/liferay/dynamic/data/mapping/internal/util/FieldsToDDMFormValuesConverterImpl.java#L214). For example, I see this being indexed: `{"groupId":20121,"label":"Home","layoutId":"1","path":[{"groupId":"20121","label":"All","layoutId":0,"privateLayout":false}],"privateLayout":false}`

We should not being doing this, this mean searches for "groupId", "false", "path", "all", etc, etc, will all return this Web Content - all this change does is hide the problem content that is indexed. 

What needs to be fixed is what is indexed, not what is shown on the screen. Perhaps in this specific case only the label should indexed. Please reconsider how to fix this in this direction.

**Comment by rolandpakai** [comment]
ci:test:relevant

**Comment by rolandpakai** [comment]
ci:test:stable

**Comment by lfbesada** [comment]
Hi @rolandpakai 
Thanks a lot for the details, I was testing this PR and analyzing the solution and I think that it cause at least two problems:
1. The highlights are lost when we are using a locale different from the default.
2. It is introducing a dependency of PortletRequest and PortletResponse in the indexer that will impossibility the migration to the contributor's framework that we are working on.
IMHO the solution to this bug should be analyzed having into account both LPSs and looking to not introduce another bug in the process. So I think the proper way to handle it is to discuss the different approaches in a PTR involucrin SME and Search Team.
Could you please open the ticket referring to this pull request?
Please referring the ticket here and we are going to continue discussing the fix there.
Thanks!
Regards

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
Hi @joshuacords,
Thanks a lot for your proactivity. I was analyzing the implementation and I totally agree. The better approach seems to be to change the way these fields are indexed not the way we show the results.
Could we continue discussing this in a PTR? 
I am sure we will be able to find a better approach to solve it by working together.
Thanks!!!
Regards

**Comment by rolandpakai** [comment]
Hi @lfbesada 

i opened the PTR here: [PTR-3057](https://issues.liferay.com/browse/PTR-3057)
Currently the assigne is the SME Web Experience.

Thanks, Roland

**Pull request closed without merging**
