### PR TITLE
[TS] LPS-152888 - change redirect in the specific case where we are viewing an asset in context and use a related assets portlet

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @liferay-echo,

Resend of https://github.com/liferay-echo/liferay-portal/pull/8640

This PR addresses a very specific case where we have a related assets portlet and an asset publisher portlet we're using to view assets in context. In the client's case, they're using the related assets portlet as a navigational tool. If you use simple navigation on the related assets portlet and click 'next' to scroll to the next asset in the related assets portlet, the redirect for the asset publisher where you are viewing the content changes to the related asset portlet itself. I've changed it so that the URL is now the referring URL rather than the current URL in this specific case so the back icon on the asset publisher works properly.

Please let me know if you have any questions about this. Thanks!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1387401_1798

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1267401_3712

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @wanderlast 
Thanks for the fix!
I have been testing it in my local and it does not always work correctly, sometimes the back takes the URL http://localhost:8080/-/client that responds with a 404.
IMHO isn't a good idea to use the referer header since it's not always present. In addition, adjusting the behavior when it's a concrete portlet, the Related Assets portlet, in this case, is not a good practice.
I think other possible solutions should be explored.
Please, if you need help in the implementation you can create a PTR ticket asking for support.
Thanks,
Regards

**Comment by lfbesada** [comment]
ci:stop

**Pull request closed without merging**
