### PR TITLE
LPS-183830 Cannot view child sites in Sites admin

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://issues.liferay.com/browse/LPS-183830)

### CODE REVIEW

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @DiegoHu97 the fix was to add a missing </div> right? could you split that change from the first commit? I had a hard time realising what was the fix x) so it is better to extract it so it is simpler

The rest looks good :D 

Thanks!!

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
@victorg1991 Updated!

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
Nice Diego!! :D

**Pull request closed without merging**
