### PR TITLE
LPS-130736 Generate the template with the correct values for longitude and latitude

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Pull request closed without merging**
