### PR TITLE
LPS-139117 Make sure that plids and revisionIds will not conflict

### PR DESCRIPTION
**Pull request by moltam89**
Hey guys,

For plid generation, a specific Layout counter is used, which can result in conflicting plids and revisionIds.
This ticket is about an upgrade issue, but I can imagine other use case as well.

This can be problematic, because in the PortletPreferences table the revisionIds are used as plids. In case if conflicting ids, irrelevant Preferences can be returned.

This fix is a bit of a hack, but I couldn't come up with a better solution, if we want to keep the unique counter for layouts.
An alternative solution could be to use the general counter. I tried to track down the reason why we have a layout counter, but the [commit message ](https://github.com/brianchandotcom/liferay-portal/pull/75860/commits/a7b6d1c5c4f72be5c60ed24f951295e8d5d16698) doesn't really explains it.

Best,
Tamas

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test:sf

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
ci:test:stable

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
