### PR TITLE
[TS] LPS-161738 Have the Private Page tab always be visible whether private pages exists or not

### PR DESCRIPTION
**Pull request by ericyanLr**
Hi Echo Team,

Can you help review this PR?

**Notes from @noornajj**

> https://issues.liferay.com/browse/LPS-161738
> 
> The issue here is that the Private Pages tab was being set to visible based on whether the SCOPED group had private pages created. However, the Portlet URL for the tab was being generated off of the REFERRER group. This caused a null pointer error to occur and the portlet to become unavailable when the Private Pages tab is clicked. This is because the URL is trying to navigate to the private pages of a group that does have any private pages.
> 
> To fix the issue, I had the Private Pages tab work similar to the Public Pages so that it will always be visible but will show "No pages available" if the group doesn't have any pages.
> Based on how the [PortletURL](https://github.com/noornajj/liferay-portal/blob/2173b7690c4205ef30cabbadc4c7fecdd599f193/modules/apps/item-selector/item-selector-web/src/main/java/com/liferay/item/selector/web/internal/ItemSelectorImpl.java#L335) gets generated, it intentionally sets the group of all tabs, other than the selected tab, to the referrer group. Therefore, it would make sense that the visibility of the Private Pages tab should not be dependent on the SCOPED group.

Please let us know if you have any questions.
Thanks!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ericyanLr** [comment]
ci:test:sf

**Comment by ericyanLr** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
