### PR TITLE
[TS] LPS-134264

### PR DESCRIPTION
**Pull request by jonathanmccann**
Prior to https://issues.liferay.com/browse/LPS-128817 groups were filtered using the following logic:

https://github.com/liferay/liferay-portal-ee/blob/fix-pack-dxp-12-7210/modules/apps/site/site-browser-web/src/main/java/com/liferay/site/browser/web/internal/display/context/SiteBrowserDisplayContext.java#L398-L404

After LPS-128817 filtering only took place if:

1. `filterManageableGroups` is true
2. A value for `usersGroups` is supplied to the group search

This change in behavior allowed all sites to be returned when a user was adding another user to a site (https://issues.liferay.com/browse/LPS-134264).

The changes in this pull attempt to bring back the previous behavior by checking for the "Assign Members" permission.

Please let me know if there are any questions or if there are any flaws in the logic. Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Thanks for the PR @jonathanmccann
It looks like the changes break the following 3 tests:
- LocalFile.MySites#JoinSitePrivateNo
- LocalFile.MySites#JoinSiteRestricted
- LocalFile.MySites#LeaveSite
Can you take a look at them and let us know if you need additional help. Thanks!

**Comment by jonathanmccann** [comment]
@ruben-pulido Thank you for letting me know. I've pushed up some changes to resolve that issue. I'll keep an eye on the test results to see if anything still doesn't pass.

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ruben-pulido** [comment]
Thanks for the updated changes @jonathanmccann. 
The issue is with your changes no longer reproducible and no tests are failing :)

For subsequent pulls I have two suggestions that would help us during the review:

- I find it helpful to have a separate commit for changes that are only refactoring existing code. We usually prefix the commit message with "Refactor". In this Pull, a first commit could be just extracting the already existing code to the new method `_filterGroups` and calling the new method from where the existing code was removed. A second commit would then move the assignment of `actionId`, add the conditional call to `_filterGroups` and possibly the change in SiteBrowserDisplayContext (that could be also part of a third commit).

- I personally favour closing an existing PR and opening a new one whenever there are changes (rather than updating it). That makes it easier to compare the changes across PRs.

Thanks!! :)

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
