### PR TITLE
LPS-202279 It should be 3, I don't know why sf is not complaining about it

### PR DESCRIPTION
**Pull request by p2kmgcl**
Follow up from https://github.com/brianchandotcom/liferay-portal/pull/144553

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
cc @ealonso

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:stop

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, would you mind checking failed integration tests?
[com.liferay.journal.internal.upgrade.v5_2_1.test.JournalArticleLayoutClassedModelUsageUpgradeProcessTest](https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/780452/testReport/com.liferay.journal.internal.upgrade.v5_2_1.test/JournalArticleLayoutClassedModelUsageUpgradeProcessTest)

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/144623

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
