### PR TITLE
LPS-192065 Ensure only needed values are stored in data_ column of LayoutPageTemplateStructureRel

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-192065)

Motivation
=======
When creating pages, there are some empty props that are stored in the database. The goal of this task is to avoid those props to be added to the database.

## Steps
- Go to Design > Page Templates > Page Templates > Create a Content Page Template > Publish
- Go to the database > In LayoutPageTemplateStructure Schema you can find the Page Template stored
**- To test this, we will have to compare the values stores before the changes and after the changes**

**## NOTE: As we can see in the screenshots after, "config" and "children" fields cannot be removed because it breaks a lot of archives.**

**Case 1: Container styled**
  - Add a Container to a content page template
container
containerBefore

**Case 2: Collection styled**
  - Click the Collection Display and see configurations at right side 
  - Select a Collection, for example a collection provider
collectionBefore
collectionAfter

**Case 3: Fragment styled**
  - Add a  Button to a content page template
fragmentBefore
fragmentAfter

**Case 4: Row styled and Column styled**
  - Add a  Grid to a content page template
  - Column and row will be stored in the database
rowBefore
rowAfter
columnBefore
columnAter

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @DiegoHu97 There are other places in the JS where we are using the display property directly, don't those cases need update too?

image

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by DiegoHu97** [comment]
ci:stop

**Comment by DiegoHu97** [comment]
ci:test:echo

**Comment by DiegoHu97** [comment]
ON HOLD: WAITING FOR THE TEST TO BE DONE

**Pull request closed without merging**
