### PR TITLE
LPS-134858 Better naming

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The failure cases are unrelated to changes in PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/103747

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
