### PR TITLE
LPS-118212 Undo is already implemented for CHANGE_MASTER_LAYOUT

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by veroglez** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @veroglez , could you have a look at? The add interacton should be called Add ${fragmentName}
See 
[before2.jpg.gz](https://github.com/liferay-echo/liferay-portal/files/5018826/before2.jpg.gz)

**Comment by veroglez** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:test:stable

**Pull request closed without merging**
