### PR TITLE
LPS-131487 Normalized Asset Tag names

### PR DESCRIPTION
**Pull request by manuelRives**

### CODE REVIEW

**Comment by manuelRives** [comment]
ci:test:sf

**Comment by manuelRives** [comment]
ci:test:relevant

**Comment by manuelRives** [comment]
ci:test:stable

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/4424

**Pull request closed without merging**
