### PR TITLE
LPS-182598 | Update template messages to make them more consistent

### PR DESCRIPTION
**Pull request by jaimelr10**
**Description:** Follow up to [pull/12112](https://github.com/liferay-echo/liferay-portal/pull/12112) in order to change some messages that could be missleading

**Jira Ticket:** https://issues.liferay.com/browse/LPS-186152

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
Nice @jaimelr10 👏

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
