### PR TITLE
LPS-134343 - Test Scenarios Coverage | Backend

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @jkappler

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:reevaluate:1047401_8428

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The failure cases are unrelated to changes in PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/103790

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
