### PR TITLE
LPS-129822

### PR DESCRIPTION
**Pull request by BryanEngler**

### CODE REVIEW

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@ealonso

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by BryanEngler** [comment]
hey guys, looks like this pr breaks the LocalFile.InfoListProviders#DisplayRelatedAssetsInAssetPublisher functional test. would you like me to look into it or will your team handle it?

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/4144

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
