### PR TITLE
LPS-177299 Replace liferay-ui:tabs with clay:tabs in site-admin-web

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://issues.liferay.com/browse/LPS-177299)

## Steps 
**Case 1**

1. Go to Control panel > Sites
2. Upper right click on the info icon 
Screenshot 2023-05-05 at 13 47 51

**Case 2**

1. Go to Control panel > Sites
2. Create a new blank site 
3. Upper right click on the info icon 
Screenshot 2023-05-05 at 13 49 02

**Case 3**

1. Go to Control panel > Sites
2. Create two new blank sites
3. Upper right click on the info icon
Screenshot 2023-05-05 at 13 49 45

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
