### PR TITLE
LPS-151076 Make sure that stylesheet is only generated when styles change, otherwise use the cached stylesheet

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
Very nice :rainbow:

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
