### PR TITLE
LPS-202718 Use index keys since current sub implementation does not support named keys

### PR DESCRIPTION
**Pull request by p2kmgcl**
With the latest sub update we have (accidentally) remove support for named keys in translations. It is very difficult to add this functionality since we need to deal with mixed arrays + objects + react nodes, and it did not add much value, so for now we can just rely on indices.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by ambrinchaudhary — APPROVED** [review]
I accept this change, but I think there may be other cases where this will fail...

**Comment by ambrinchaudhary** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
