### PR TITLE
LPS-195643 Fix JournalFeedTypeUpgradeProcess: `DuplicateVocabularyExc…

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Sending again based on my comment: https://github.com/brianchandotcom/liferay-portal/pull/140712#issuecomment-1719731583

This makes it clear that assetVocabularyName is being retrieved from assetVocabularyTitleMap when adding vocabulary on `titleMap.get(LocaleUtil.getSiteDefault())` in https://github.com/liferay/liferay-portal/blob/1a561075882158d5f2d316d3b9581eb332cf45f9/portal-impl/src/com/liferay/portlet/asset/service/impl/AssetVocabularyLocalServiceImpl.java#L119

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@georgel-pop-lr, will talk to BChan about this if he wants more changes. Thanks for all the hard work ❤️

**Comment by georgel-pop-lr** [comment]
> @georgel-pop-lr, will talk to BChan about this if he wants more changes. Thanks for all the hard work ❤️

Thanks! :)

**Pull request closed without merging**
