### PR TITLE
LPS-191942 Adapt tests and add new test

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward-force

**Comment by Tim-Cao** [comment]
Hi @sandrodw3,
Could you check this failed integration test?
[com.liferay.layout.content.page.editor.web.internal.portlet.action.test.GetCollectionFieldMVCResourceCommandTest](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/505697/testReport/com.liferay.layout.content.page.editor.web.internal.portlet.action.test/GetCollectionFieldMVCResourceCommandTest)

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by sandrodw3** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward:force

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/138541

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
