### PR TITLE
LPS-190367

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @Mikellorza, could you check this failed integration test?
[com.liferay.layout.reports.web.internal.product.navigation.control.menu.test.LayoutReportsProductNavigationControlMenuEntryTest](https://testray.liferay.com/home/-/testray/case_results/2399784029)

**Comment by Mikellorza** [comment]
@ealonso  see : https://github.com/liferay-echo/liferay-portal/pull/13146

**Pull request closed without merging**
