### PR TITLE
LPS-169503 - Add new dropdown options

### PR DESCRIPTION
**Pull request by ruben-pulido**
This PR contains the implementation for "Delete", "Copy" and "Permissions" actions

//cc @ealonso @veroglez @victorg1991 @lfbesada @sandrodw3

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
Failures are not related, pushed to BChan directly at https://github.com/brianchandotcom/liferay-portal/pull/128219

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
