### PR TITLE
LPS-128744 Fix broken DOM structure caused by LPS-120600

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
LPS-128744 Fix broken DOM structure caused by LPS-120600, DOM contains an empty element p and asset-actions.jsp content places outside his parent element span. Change asset_actions.jsp parent element span with div for markup validity as actions contain a div and span can't be parent of a div.

Resend from frontend review to echo team as per request liferay-frontend#870 (comment)

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Comment by sandrodw3** [comment]
@georgel-pop-lr same poshi tests has failed in both relevant runs, so it seems related. Could you take a look? 🙂

**Comment by georgel-pop-lr** [comment]
> @georgel-pop-lr same poshi test has failed in both relevant runs, so it seems related. Could you take a look?

Hi @sandrodw3,

Me and @dacousalr had a look over it and seems to be related to our changes because the xpath was changed, and also we have changed span to div so probably there is the trick.
`Element is not present at "//a[contains(@class,'asset-title')][normalize-space(text())='WC WebContent Title 3']/following-sibling::span//*[*[name()='svg'][contains(@class,'lexicon-icon-pencil')]]"`

I'm not experienced with changing this tests, could we get some help from someone in QA? 

Regards.

**Comment by sandrodw3** [comment]
> > @georgel-pop-lr same poshi test has failed in both relevant runs, so it seems related. Could you take a look?
> 
> Hi @sandrodw3,
> 
> Me and @dacousalr had a look over it and seems to be related to our changes to xpath, also we have changed span to div so probably there is the trick.
> `Element is not present at "//a[contains(@class,'asset-title')][normalize-space(text())='WC WebContent Title 3']/following-sibling::span//*[*[name()='svg'][contains(@class,'lexicon-icon-pencil')]]"`
> 
> I'm not experienced with changing this tests, could we get some help from someone in QA?
> 
> Regards.

Hey @georgel-pop-lr 🙂 Sure, we can ask @Tim-Cao por help, let's see what he thinks about it (cc @david-gutierrez-mesa)

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/3976

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
