### PR TITLE
LPS-174806 Replace liferay-ui:icon in layout-seo-web

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://issues.liferay.com/browse/LPS-174749)

## Test Steps

1. Go to Product Menu -> Configuration -> Site Settings
2. In Content & Data section -> Pages
3.  Choose Open Graph section
Screenshot 2023-02-07 at 19 22 17

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
@DiegoHu97 I added https://github.com/liferay-echo/liferay-portal/pull/11056/commits/428eace7f427081da23da42d5f821accadbf945f 😄

**Comment by ealonso** [comment]
Hey @DiegoHu97,

There is a SF error, Could you please fix it?

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
