### PR TITLE
[TS] LPS-152888 - change redirect in the specific case where we are viewing an asset in context and use a related assets portlet

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @liferay-echo,

This PR addresses a very specific case where we have a related assets portlet and an asset publisher portlet we're using to view assets in context. In the client's case, they're using the related assets portlet as a navigational tool. If you use simple navigation on the related assets portlet and click 'next' to scroll to the next asset in the related assets portlet, the redirect for the asset publisher where you are viewing the content changes to the related asset portlet itself. I've changed it so that the URL is now the referring URL rather than the current URL in this specific case so the back icon on the asset publisher works properly.

Please let me know if you have any questions about this. Thanks!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Hi @wanderlast 
There is a SF failure. Can you fix it? Thanks!

**Pull request closed without merging**
