### PR TITLE
LPS-189834 Expire info is missing in Content Display

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-189834)

## Test Scenario

1. Add a web content
2. Add a Content Display to a content page
3. Display the web content in Content Display
4. Expire the web content
5. Back to page editor

image

### CODE REVIEW

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/137533

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
