### PR TITLE
[TS] [Urgent] LPS-187703 Improve performance of SegmentsEntryRel reindexing process

### PR DESCRIPTION
**Pull request by mbowerman**
Motivation
=======
Currently the SegmentsEntryRel reindexing process is extremely inefficient in regards to keeping the `SegmentsEntryRel` table in the database up to date. It removes every related entry to the segment, and then adds them back in. It would be much more efficient to only remove the entries that have actually been removed from the segment, and to only add the entries that have actually been added to the segment.

This inefficiency is causing a very large number of cache-clearing operations for the SegmentsEntryRel cache, proportional to the number of users in the segment. We have a customer who is also using clustering with cache replication, and their segments are big enough that so many cache-clearing messages are getting generated that it chokes up their entire cluster because of the excessive number of cache clearing messages that are being queued up to be sent to the other node. This is a blocker for them

Proposed Solution
========
To solve this issue, I implemented the proposed solution originally approved by the product team on [PTR-4003](https://issues.liferay.com/browse/PTR-4003). This solution is to only remove the entries from the SegmentsEntryRel table that have actually been removed from the segment, and to only add the entries that have actually been added to the segment (rather than remove and then re-add a bunch of entries redundantly).

Note that this implementation _assumes_ that all SegmentsEntryRel objects will have their classNameId set to the classNameId corresponding to the `type` of the SegmentsEntry. As far as I could tell, it did not seem to be possible (at least not without using the API) to change the `type` of a SegmentsEntry. Please let me know if this is not a valid assumption.

Steps to Verify
========
1. Start up Liferay and log in as the admin user.
2. Create two new users: "test1@liferay.com" and "test2@liferay.com".
3. From the Global Menu, navigate to Control Panel > Roles, and add a new Regular Role named "Test Role".
4. Assign the "Test Role" to "test1@liferay.com" and "test2@liferay.com".
5. From the Site Administration menu of the default Liferay DXP Site, navigate to People > Segments.
6. Create a new Segment named "Test Segment" with the following condition: Regular Role equals Test Role.
7. From the Global Menu, navigate to Control Panel > Server Administration > Script.
8. Execute the [CallSegmentsEntryRelReindex.groovy](https://issues.liferay.com/secure/attachment/504551/504551_CallSegmentsEntryRelReindex.groovy) script.

**Checkpoint:** Check the SegmentsEntryRel table in your database. You should see two rows, corresponding to the memberships of "test1@liferay.com" and "test2@liferay.com" in the "Test Segment".

9. Unassign the "Test Role" from the "test2@liferay.com" user.
10. Connect the debugger to Liferay and put breakpoints at the beginning of [SegmentsEntryRelPersistenceImpl.updateImpl](https://github.com/liferay/liferay-portal/blob/dcf1fd98e86a327e8bfc999363224e6d9ab03b60/modules/apps/segments/segments-service/src/main/java/com/liferay/segments/service/persistence/impl/SegmentsEntryRelPersistenceImpl.java#L2271) and [SegmentsEntryRelPersistenceImpl.removeImpl](https://github.com/liferay/liferay-portal/blob/dcf1fd98e86a327e8bfc999363224e6d9ab03b60/modules/apps/segments/segments-service/src/main/java/com/liferay/segments/service/persistence/impl/SegmentsEntryRelPersistenceImpl.java#L2238).
11. Navigate back to Control Panel > Server Administration > Script, and execute the [CallSegmentsEntryRelReindex.groovy](https://issues.liferay.com/secure/attachment/504551/CallSegmentsEntryRelReindex.groovy) script. Note whenever a breakpoint is reached and then resume the debugger.

**Expected Result:** The breakpoint for removeImpl would only be reached one time, to remove "test2@liferay.com" from the segment. The breakpoint for updateImpl would never be reached.
**Actual Result:** The breakpoint for removeImpl is reached twice, once to remove "test1@liferay.com" from the segment and a second time to remove "test2@liferay.com" from the segment. Then the breakpoint for updateImpl is reached to add "test1@liferay.com" back into the segment.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
Hey @mbowerman,
Could you please create a test for it?
I was doing a first review and everything looks good to me.

**Comment by mbowerman** [comment]
Hello @ealonso,

I have pushed a new commit which adds an integration test class to do as you described. Could you please check it and see if it is acceptable?

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @mbowerman,
The failures on tests are related with your changes, Could you please take a look?

**Comment by mbowerman** [comment]
Ah!! My bad @ealonso, I messed up in the new logic that I added.

I've pushed a new commit that should fix the issue. Could you please take a look when you get a chance?

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
