### PR TITLE
LPS-180317 & LPS-180293 - Site REST API should return appropriate error messages when site cannot be created & Test Scenarios Coverage | Backend

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @jkappler

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@ruben-pulido, tests don't seem related at all, we'll see and if not force fw

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
