### PR TITLE
LPS-156365 buildLang

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
@p2kmgcl we should review it tomorrow

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
