### PR TITLE
LPS-135963 build.gradle

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
cc: @rodrigopaulino

**Comment by rodrigopaulino** [comment]
Hi, @ealonso. Thanks for reviewing this. 

I would really appreciate a bit more context on your changes. 😀 
I'm confused why you chose to not test the entire class for the sake of simplifying the test. Don't you think it's valid to test how the exception and success are being handled as well as the way the class retrieves the parameters from the request?

Thanks in advance.

**Comment by ealonso** [comment]
Hey @rodrigopaulino,

Sorry about not explaining the changes.

IMHO, the code in Test class was too complex to check if a data definition is imported successfully or not, so for that reason I prefer to only check the new method. I'm referring this code:

```java
private MockMultipartHttpServletRequest
			_createMockMultipartHttpServletRequest(String fileName)
		throws Exception {

		MockMultipartHttpServletRequest mockMultipartHttpServletRequest =
			new MockMultipartHttpServletRequest();

		Class<?> clazz = getClass();

		byte[] bytes = _file.getBytes(
			clazz.getResourceAsStream("dependencies/" + fileName));

		mockMultipartHttpServletRequest.addFile(
			new MockMultipartFile(fileName, bytes));

		mockMultipartHttpServletRequest.setCharacterEncoding(StringPool.UTF8);

		String boundary = "WebKitFormBoundary" + StringUtil.randomString();

		mockMultipartHttpServletRequest.setContent(
			_getContent(boundary, bytes, fileName));
		mockMultipartHttpServletRequest.setContentType(
			MediaType.MULTIPART_FORM_DATA_VALUE + "; boundary=" + boundary);

		return mockMultipartHttpServletRequest;
	}

	private byte[] _getContent(String boundary, byte[] bytes, String fileName) {
		String start = StringBundler.concat(
			StringPool.DOUBLE_DASH, boundary,
			"\r\nContent-Disposition:form-data;name=\"jsonFile\";filename=\"",
			fileName, "\";\r\nContent-type:application/json\r\n\r\n");

		String end = StringBundler.concat(
			"\r\n--", boundary, StringPool.DOUBLE_DASH);

		return ArrayUtil.append(start.getBytes(), bytes, end.getBytes());
	}

```

By the way, if you prefer the other code, please close this one and send your pr to Brian, it is fine for me.  I was trying to simplify the code, but maybe I didn't do it in the correct way.

Regards,
Eudaldo.

**Comment by rodrigopaulino** [comment]
I understand, @ealonso. Thanks for explaining.

Although I understand your intentions here, the other implementation is not just testing if the data definition was successfully imported. It's also testing the session errors and messages as well, which I think is valid to guarantee that the app is working as intended without creating a functional test for it.
But if you think it's too complex, we can work together to find a solution that works for the two cases. Do you think extracting that request mocking and putting it in a utility class would help the test's readability?

Looking forward to hearing from you?

**Comment by ealonso** [comment]
Hey @rodrigopaulino,

What do you think to create a unit test for it instead of integration test?. IMHO, I think it is better if we create a unit test for it, since we don't want to test that the data definition was successfully imported.

Regards,
Eudaldo.

**Comment by rodrigopaulino** [comment]
Hey, @ealonso.

Thanks for suggesting this, but my intentions before with the integration test was to test the whole functionality. So, I was wondering if we could do both: test the class' entire logic (not just the import part) and its integration with the platform.

Here... I gave a shot to your suggestion and this is what I have so far: https://github.com/rodrigopaulino/liferay-portal/commit/318a26ce0eca2c5172269cfa70fe7272a745ebd6. Please, bear with me as it is just a draft, is currently failing and for sure needs refactoring, but as you can see I had to mock practically every line of that MVCActionCommand to start testing and it turned out to be not very practical and quite cumbersome.

What do you think?

**Comment by rodrigopaulino** [comment]
Hey, @ealonso. Did you have time to see my previous comment?

Thx

**Comment by ealonso** [comment]
Yes, I took a look to your pr, and you are right maybe it is not a good idea to have a unit test for it.  So, taking a look again to your first pr, I don't like the idea of adding those changes d251bd6 because of the tests. Is there any way of removing it?

**Comment by rodrigopaulino** [comment]
@ealonso, I tried that a lot actually, but wasn't successful, because the method `getUploadPortletRequest` throws an exception if the request passed as parameter is not wrapping a `PortletRequestImpl`, which is internal to `portal-impl` and we can't import to the test module.

**Pull request closed without merging**
