### PR TITLE
LPS-120808 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-120808

This is only for master.

@victorg1991
@p2kmgcl

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Since the failure tasks caused by bundle version and startTestableTomcat and in order to not clog up ci resources I pushed directly to BChan.
See https://github.com/brianchandotcom/liferay-portal/pull/94316

**Comment by Tim-Cao** [comment]
ci:close

**Comment by victorg1991** [comment]
Many thanks @Tim-Cao :)

**Pull request closed without merging**
