### PR TITLE
LPS-117828 Include fieldSet label in loop key

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
ci:reopen

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Conflicts for LPS-117828 resolved [here](https://github.com/liferay-echo/liferay-portal/pull/1784)

**Comment by ealonso** [comment]
@p2kmgcl @jkappler @ruben-pulido @victorg1991 

11 días abierto? 🤦

**Comment by jkappler** [comment]
@ealonso, LPS-117994 está mergeado desde hace 10 días: https://github.com/brianchandotcom/liferay-portal/pull/92050

**Comment by ealonso** [comment]
@jkappler y la tenemos de recuerdo?

**Comment by jkappler** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/92470

**Comment by jkappler** [comment]
This was never closed but was passed around in several other PR

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
