### PR TITLE
LPS-165113 - When using the App Pages, the Picklist field does not display it's default value

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1387401_4616

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @ruben-pulido,
What about frontend logic to take into account the default value?

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
Hey @ruben-pulido,

What do you think an approach like this?

```java
dropdownItem -> {
	dropdownItem.setActive(
		_assetBrowserDisplayContext.getGroupId() ==
			groupId);
	dropdownItem.setHref(
		getPortletURL(), "groupId", groupId, "scope",
		"current");
	dropdownItem.setLabel(
		HtmlUtil.escape(
			group.getDescriptiveName(
				_themeDisplay.getLocale())));
})
```
where we set the default to the option instead of creating a new field, so it could be something like:

```java
public static class Option {

...

        private final boolean _default = false;
        private final InfoLocalizedValue<String> _label;
	private final String _value;
}
```

**Comment by ruben-pulido** [comment]
@ealonso I considered the approach of adding a default attribute of type boolean to option, but favoured the approach of setting the default value as a separate attribute of the field with the default option since the the former would allow setting default to true for multiple options, when we may want to have a single default value.

Giving it a second thought, I do see some advantages of modelling the default value as a boolean attribute of the option, since this would allow setting a default value that may be comprised of several options (which can be useful for the case that the Selector allows multiple selection). 

I'll send a new PR following this approach.

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Pull request closed without merging**
