### PR TITLE
LPS-125654 Move fragmentConfig to fragmentStyles

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Did you find any hint on why this stopped working? Although this change is necessary to update the config to the new styles, I think it should work right away without needing to update it. I think we should try to find the root cause

**Comment by pavel-savinov** [comment]
ci:forward

**Pull request closed without merging**
