### PR TITLE
LPS-138540 Preview Item doesn't work with Display Page Content fragment

### PR DESCRIPTION
**Pull request by veroglez**

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @veroglez, the displayed content doesn't change when change the template in Content Display. Could you have a look at?
image

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by p2kmgcl** [comment]
https://github.com/liferay-echo/liferay-portal/pull/5757

**Pull request closed without merging**
