### PR TITLE
LPS-168803 Cannot export Fragments if Thumbnail is missing

### PR DESCRIPTION
**Pull request by moltam89**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
Hi @moltam89, thanks for the PR. Could you please explain how we arrived to this? I understand the change, but it's weird that the user deletes the file entry by hand

**Comment by moltam89** [comment]
Hi @jkappler ,

We discovered this issue in the customer's UAT, unfortunately I don't know how this happened.
It can be quite painful though, when an hours long export process fails because of missing file entry.

Best,
Tamas

**Comment by jkappler** [comment]
Thanks @moltam89, I understand. Would really like to find the scenario that causes this, since it can cause more issues

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1257401_5431

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
