### PR TITLE
LRAC-14599 | master

### PR DESCRIPTION
**Pull request by marcosapmf**
Jira ticket: https://issues.liferay.com/browse/LRAC-14599

This pull allows to publish a variant experience when current experiment experience is the same as current page experience.
The scenario we found this bug was when we have a terminated experiment and try to publish its variant. So, after publishing the variant, it was not published indeed.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
Hey @marcosapmf,

I think it is related with your changes:

[modules-integration-mysql57-jdk8/0/4](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/731700//consoleText)
[com.liferay.segments.service.test.SegmentsExperimentLocalServiceTest](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/731700/testReport/com.liferay.segments.service.test/SegmentsExperimentLocalServiceTest) - [Failed 0 of last 23](https://testray.liferay.com/home/-/testray/case_results/2427764653/history)
[testUpdateSegmentsExperimentStatusToCompletedWithWinnerSegmentsExperienceAndDefaultControlSegmentsExperience](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/731700//testReport/com.liferay.segments.service.test/SegmentsExperimentLocalServiceTest/testUpdateSegmentsExperimentStatusToCompletedWithWinnerSegmentsExperienceAndDefaultControlSegmentsExperience)

**Comment by marcosapmf** [comment]
ci:test:sf

**Comment by marcosapmf** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
