### PR TITLE
LPS-142557 - Collection Display for Objects does not display all instances, even when "Display All Collection Items" is checked

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc //cc @ealonso @sandrodw3 @p2kmgcl

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ruben-pulido, would you mind have a look at integration test failure?

**Comment by ruben-pulido** [comment]
@Tim-Cao The integration failure is unrelated

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Thank you @Tim-Cao!

**Comment by Tim-Cao** [comment]
The failure task is unrelated to this PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/111299

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
