### PR TITLE
LPS-202551 Only call changeCallback if the user has pressed some key while editing the text

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
hey  @georgel-pop-lr could you help me validate this fix? It seems that it is working fine now, but wanted to have a second opinion :)

**Comment by georgel-pop-lr** [comment]
> hey @georgel-pop-lr could you help me validate this fix? It seems that it is working fine now, but wanted to have a second opinion :)

Hi @victorg1991,

I just checked and is fixed.

Thanks for your help!

Regards.

**Comment by victorg1991** [comment]
Nice :D

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
Thanks!!

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
