### PR TITLE
LPD-26865 Adds performance tests to evaluate the LPD-20883 fix against the previous solution

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-26865

The reason for this PR is that we feared that we were worsening performance for all DB types when we incorporated the LPD-20883 fix for DBs that do not support the distinct clause on CLOB columns.

These have led us to modify this test so that, in addition to asserting the functionality, it allows us to use it to test performance.

With the changes incorporated here I have tested the performance on MySQL and I have verified that:

- The performance of the previous implementation is similar to the current one if there are few sites linked to the site template
- Increasing the number of linked sites, a certain worsening of performance is already beginning to be noticed, although it does not seem notable. For example, those are the execution times with 100 sites linked to the site template.

***Before LPD-20883***
image

***After LPD-20883***
image

It is pending to decide whether this justifies maintaining the old implementation for the DBs that support it.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
