### PR TITLE
[TS] [Urgent] LPS-200518 When upgrading from before U84 to U84+, existing Object Collection Provider configurations become invalid

### PR DESCRIPTION
**Pull request by mbowerman**
Motivation
=======
In [LPS-189110](https://liferay.atlassian.net/browse/LPS-189110), we moved the `ObjectEntrySingleFormVariationInfoCollectionProvider` class into a different package. This is problematic because Collection Providers for the Objects portlet reference the fully qualified class names of this class. Unfortunately, there was no upgrade process created to update any references to this class, so any portlet that has been configured to display an Objects Collection Provider became broken after the upgrade.

Ticket: [LPS-200518](https://liferay.atlassian.net/browse/LPS-200518)

Proposed Solution
========
Add an upgrade process to upgrade the references to the fully-qualified class name of the `ObjectEntrySingleFormVariationInfoCollectionProvider` class inside the `LayoutPageTemplateStructureRel` table.

Steps to Verify
========
1. Startup a clean instance of 7.4 U73.
2. Navigate to Control Panel > Objects, and create a new Object definition as follows:
* Name it “Test Object”
* Set its Panel Category Key to Control Panel > Object
* In the Fields tab, create a new field with any name and type.
* Publish the object.
3. Navigate to Control Panel > Objects > Test Objects.
4. Add 2 entries.
5. On the Home page, add a Collection Display fragment.
6. Map the Collection Display to the “Test Object” Collection Provider
7. Verify the table shows the expected entries from the previous steps
8. Shut down the server.
9. Upgrade your bundle to master.
10. Perform a full reindex from Control Panel > Search > Index Actions.
11. Navigate to the home page where the Collection Display was added.

**Expected Result:** The object collection display appears (or at least correctly shows 2 entries).
**Actual Result:** The object collection display does not appear and there is a UI message in its place that just says: ‘No Results Found’.

Note that there is another Objects regression caused by [LPS-195264](https://liferay.atlassian.net/browse/LPS-195264) that also causes the items not to render properly (although the count should at least be correct), at least for certain Display Styles. This bug is not intended to address that regression. It is only intended to ensure that the Collection Display is fetching the correct data, even if it does not actually render it on the page.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
Hey @mbowerman,

This looks good to me, I'm going to ask uniform team about REPLACE, to make sure it is going to work with all databases.

Thanks you very much!!

**Comment by ealonso** [comment]
Hey @mbowerman,

I saw we already are using it in LayoutTemplateIdUpgradeProcess, so 🚀

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:stable

**Comment by liulukiwi** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143126

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
