### PR TITLE
[TS] LPS-116019 Check if the pages are hidden

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team, could you review this adaptation to make the multi column template be aware of the showHiddenPages option, please?

Thanks in advance

\cc @ealonso

### CODE REVIEW

**Comment by dacousalr** [comment]
ci:test:sf

**Comment by dacousalr** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
thanks @dacousalr

**Pull request closed without merging**
