### PR TITLE
LPS-172013 Fix articleId validation

### PR DESCRIPTION
**Pull request by rolandpakai**
Hi Team,

could you please check my fix?

**Reproduction steps**

1. Create a Web Content Structure with a Web Content field
2. Create a Web Content from this Structure and save it
3. Edit this Web Content and press Select for the Web Content field

**Expected behaviour:** The current Web Content should not be selectable to eliminate the change of infinite loops
**Actual behaviour:** The current Web Content is selectable

The issue was fixed on [LPS-168190](https://issues.liferay.com/browse/LPS-168190)
but the [LPS-171587](https://issues.liferay.com/browse/LPS-171587) is causing a regression.

Thanks, Roland
https://issues.liferay.com/browse/LPS-172013

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by rolandpakai** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Hey @rolandpakai, please see https://github.com/liferay-echo/liferay-portal/pull/10781 and sorry for the regression, my bad.

**Comment by rolandpakai** [comment]
Thanky @ealonso 

No problem

**Pull request closed without merging**
