### PR TITLE
LPS-147251, LPS-147252, LPS-147253, LPS-146986, LPS-148717, LPS-146976

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-147251
https://issues.liferay.com/browse/LPS-147252
https://issues.liferay.com/browse/LPS-147253
https://issues.liferay.com/browse/LPS-146986
https://issues.liferay.com/browse/LPS-148717
https://issues.liferay.com/browse/LPS-146976

This is only for master.

@lfbesada
@ruben-pulido
@sandrodw3

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @lfbesada, there is a difference between collection and collection provider
Would you mind double checking if it is expected?
It still keeps None pagination upgrade or import when Collection Display using collection provider.

**Comment by Tim-Cao** [comment]
Also @lfbesada and @sandrodw3  would you mind resolving the rebase conflict?

**Comment by lfbesada** [comment]
> Hi @lfbesada, there is a difference between collection and collection provider Would you mind double checking if it is expected? It still keeps None pagination after upgrade or import when Collection Display using collection provider.

Hi @Tim-Cao,

After resolving the rebase conflicts, I am not able to reproduce it in my local. 

Could you please check these gifs of my testing? Maybe I am doing something wrong... 🤔 

Thanks!

Creating target page and exporting from 7.4.3 ga9
UpgradingImportingAPage


Upgrading/Importing in the feature branch
UpgradingImportingAPageFeatureBranch

**Comment by lfbesada** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7551

**Pull request closed without merging**
