### PR TITLE
LPS-179512 Create new taglib for logo selector

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:test:sf 🤷‍♂️

**Comment by ealonso** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
The failures are not related to this PR. See https://github.com/brianchandotcom/liferay-portal/pull/132414

**Pull request closed without merging**
