### PR TITLE
LPS-134062 Asset Publisher should use site default locale when is filtering by structure field

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-134062

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/4878

**Pull request closed without merging**
