### PR TITLE
LPS-127318 Optimize SQL search queries

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @liferay-echo team,

I've made an optimization similar to [LPS-109979](https://issues.liferay.com/browse/LPS-109979). When the `title` and `description` fields are not used, `(1 = 0)` is added to the conditions and the DBMS will ignore the JournalArticleLocalization joins. 

Please review my changes.

Thanks,
Vendel

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Thanks for your changes @vendeltoreki!

Sent to Brian [here](https://github.com/liferay-echo/liferay-portal/pull/3736)

**Pull request closed without merging**
