### PR TITLE
LPS-152849 Add support for redirections to display pages

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-152849

Previous PR: https://github.com/liferay-echo/liferay-portal/pull/8053

cc: @adolfopa

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1307401_3308

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
