### PR TITLE
LPS-120494 Returning true by default as below

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@jkappler

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:stable

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
thanks @4lejandrito!

**Pull request closed without merging**
