### PR TITLE
LPS-200776 Actions & Conditions Backend

### PR DESCRIPTION
**Pull request by victorg1991**
Link to the story: https://liferay.atlassian.net/browse/LPS-196463

This need this FF to be enabled: `feature.flag.LPS-169837=true`

This PR includes:
 - Modify current action commands to take into account actions and conditions
 - Add import/export for actions
 - Add id to the page element schema. This is needed because we use the id in the action definition and the id was generated when creating the layoutStructure. This way we can have stable ids

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward:force

**Pull request closed without merging**
