### PR TITLE
LPS-152843 Typo

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ozysouza** [comment]
ci:reevaluate:1367401_1155

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, the same issue with https://github.com/liferay-echo/liferay-portal/pull/8085

**Comment by ozysouza** [comment]
Note: I could noticed two things about the above failures.

1. The macro PageEditorMapping.mapEditableTextToField(); is constantly failing when trying to map the Button fragment, it seems to be just reproducible with Button. May @Tim-Cao have same ideia?
2. There is a tiny change of behavior on page editor, when selecting some tab like Styles or Advanced and then navigating to Page Content, when coming back to Page Elements the user is redirected to general tab. Currently on master it saves the last tab that we werer on. Video below

https://user-images.githubusercontent.com/72820234/169179486-11b26d06-1863-4e28-b698-2f68f181e4e9.mp4

**Comment by p2kmgcl** [comment]
Thanks @Tim-Cao and @ozysouza, I am going to fix the selected tab in the sidebar. Speaking about the button mapping, I still have no idea how to do with that, because I haven't been able to reproduce it manually :disappointed:

**Comment by ozysouza** [comment]
> Thanks @Tim-Cao and @ozysouza, I am going to fix the selected tab in the sidebar. Speaking about the button mapping, I still have no idea how to do with that, because I haven't been able to reproduce it manually disappointed

I also couldn't reproduce the issue manually. I'm trying to find some explanation for it :cry:

**Comment by p2kmgcl** [comment]
(I know this won't work, but I need the test results to check some things :sweat_smile:)

**Comment by p2kmgcl** [comment]
I have waited too long for this. I am closing this task and will check if I can cherry-pick some commits that work and send them separately. Sorry for the mess :candle:

**Pull request closed without merging**
