### PR TITLE
LPS-97596 Global Site is not ordered correctly when displayed in Japanese

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-97596)

The goal of these changes is to order correctly the sites in admin view. This error doesn't happen if the user has selected order by from the menu, which saves the value correctly in the preferences.

## Change summary:

* Separate GroupProvider in 2 methods, so that we can change at will the attributes before searching
* Change display context tied to the view

## Test Scenario

* Follow the steps in the ticket

japanese

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/130043

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
