### PR TITLE
LPS-176119 Consolidate MultipleSelection and MultiSelection into MultiSelect

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
Hey @ealonso, I found some unique failures, could you take a look at it?

[modules-semantic-versioning-jdk8/0/0](https://testray.liferay.com/home/-/testray/case_results/2208979651)

```com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/asset/asset-vocabulary-item-selector-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.asset.vocabulary.item.selector.criterion MAJOR      1.0.0      1.0.0      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.asset.vocabulary.item.selector.criterion.AssetVocabularyItemSelectorCriterion
     [exec]     		+   method     isMultiSelect()
     [exec]     			+   return     boolean
     [exec]     		-   method     isMultiSelection()
     [exec]     			-   return     boolean
     [exec]     		+   method     setMultiSelect(boolean)
     [exec]     			+   return     void
     [exec]     		-   method     setMultiSelection(boolean)
     [exec]     			-   return     void
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 2.0.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     
     
     
     com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/client-extension/client-extension-type-item-selector-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.client.extension.type.item.selector.criterion MAJOR      1.1.0      1.1.0      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.client.extension.type.item.selector.criterion.CETItemSelectorCriterion
     [exec]     		+   method     isMultiSelect()
     [exec]     			+   return     boolean
     [exec]     		-   method     isMultipleSelection()
     [exec]     			-   return     boolean
     [exec]     		+   method     setMultiSelect(boolean)
     [exec]     			+   return     void
     [exec]     		-   method     setMultipleSelection(boolean)
     [exec]     			-   return     void
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 2.0.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     
     
     
     com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/item-selector/item-selector-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.item.selector                          MAJOR      4.10.0     4.10.0     5.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   interface  com.liferay.item.selector.ItemSelectorViewDescriptor
     [exec]     		+   method     isMultiSelect()
     [exec]     			+   return     boolean
     [exec]     		-   method     isMultipleSelection()
     [exec]     			-   return     boolean
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 7.0.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertFalse(Assert.java:64)
     
     
     
     com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/item-selector/item-selector-criteria-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.item.selector.criteria.info.item.criterion MAJOR      2.1.0      2.1.0      3.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.item.selector.criteria.info.item.criterion.InfoItemItemSelectorCriterion
     [exec]     		+   method     isMultiSelect()
     [exec]     			+   return     boolean
     [exec]     		-   method     isMultiSelection()
     [exec]     			-   return     boolean
     [exec]     		+   method     setMultiSelect(boolean)
     [exec]     			+   return     void
     [exec]     		-   method     setMultiSelection(boolean)
     [exec]     			-   return     void
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 11.0.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertFalse(Assert.java:64)

**Comment by alessandromalves** [comment]
```
com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/layout/layout-display-page-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.layout.display.page                    MAJOR      3.1.0      3.1.0      4.0.0      VERSION INCREASE REQUIRED
     [exec]     	+   interface  com.liferay.layout.display.page.LayoutDisplayPageMultiSelectProvider
     [exec]     		+   access     abstract
     [exec]     		+   method     getClassName()
     [exec]     			+   access     abstract
     [exec]     			+   return     java.lang.String
     [exec]     		+   method     getPluralLabel(java.util.Locale)
     [exec]     			+   access     abstract
     [exec]     			+   return     java.lang.String
     [exec]     		+   method     process(java.util.List)
     [exec]     			+   return     java.util.List
     [exec]     	+   interface  com.liferay.layout.display.page.LayoutDisplayPageMultiSelectProviderRegistry
     [exec]     		+   access     abstract
     [exec]     		+   method     getLayoutDisplayPageMultiSelectProvider(java.lang.String)
     [exec]     			+   access     abstract
     [exec]     			+   return     com.liferay.layout.display.page.LayoutDisplayPageMultiSelectProvider
     [exec]     		+   method     getLayoutDisplayPageMultiSelectProviders()
     [exec]     			+   access     abstract
     [exec]     			+   return     java.util.List
     [exec]     	-   interface  com.liferay.layout.display.page.LayoutDisplayPageMultiSelectionProvider
     [exec]     		-   access     abstract
     [exec]     		-   method     getClassName()
     [exec]     			-   access     abstract
     [exec]     			-   return     java.lang.String
     [exec]     		-   method     getPluralLabel(java.util.Locale)
     [exec]     			-   access     abstract
     [exec]     			-   return     java.lang.String
     [exec]     		-   method     process(java.util.List)
     [exec]     			-   return     java.util.List
     [exec]     	-   interface  com.liferay.layout.display.page.LayoutDisplayPageMultiSelectionProviderRegistry
     [exec]     		-   access     abstract
     [exec]     		-   method     getLayoutDisplayPageMultiSelectionProvider(java.lang.String)
     [exec]     			-   access     abstract
     [exec]     			-   return     com.liferay.layout.display.page.LayoutDisplayPageMultiSelectionProvider
     [exec]     		-   method     getLayoutDisplayPageMultiSelectionProviders()
     [exec]     			-   access     abstract
     [exec]     			-   return     java.util.List
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 5.0.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)
     [exec]         at org.junit.Assert.assertFalse(Assert.java:64)
     
     
     
     com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/layout/layout-item-selector-api] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.layout.item.selector.criterion         MAJOR      1.4.0      1.4.0      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.layout.item.selector.criterion.LayoutItemSelectorCriterion
     [exec]     		+   method     isMultiSelect()
     [exec]     			+   return     boolean
     [exec]     		-   method     isMultiSelection()
     [exec]     			-   return     boolean
     [exec]     		+   method     setMultiSelect(boolean)
     [exec]     			+   return     void
     [exec]     		-   method     setMultiSelection(boolean)
     [exec]     			-   return     void
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 6.0.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     
     
     
     com.liferay.semantic.versioning.SemanticVersioningTest > testSemanticVersioning[/apps/layout/layout-taglib] FAILED
     [exec]     java.lang.AssertionError:   PACKAGE_NAME                                       DELTA      CUR_VER    BASE_VER   REC_VER    WARNINGS  
     [exec]     = ================================================== ========== ========== ========== ========== ==========
     [exec]     * com.liferay.layout.taglib.servlet.taglib.react     MAJOR      1.1.0      1.1.0      2.0.0      VERSION INCREASE REQUIRED
     [exec]     	>   class      com.liferay.layout.taglib.servlet.taglib.react.SelectLayoutTag
     [exec]     		+   method     isMultiSelect()
     [exec]     			+   return     boolean
     [exec]     		-   method     isMultiSelection()
     [exec]     			-   return     boolean
     [exec]     		+   method     setMultiSelect(boolean)
     [exec]     			+   return     void
     [exec]     		-   method     setMultiSelection(boolean)
     [exec]     			-   return     void
     [exec]     [Baseline Warning] Bundle Version Change Recommended: 14.0.0
     [exec]         at org.junit.Assert.fail(Assert.java:88)
     [exec]         at org.junit.Assert.assertTrue(Assert.java:41)

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, only the Delete action is shown on the dropdown menu. Would you mind checking? Thanks
image
**Expected Results**
image

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, would you mind rebasing this PR?

**Comment by Tim-Cao** [comment]
Hi @ealonso, would you mind rebasing then rerun ci:test:relevant? Even though I cannot reproduce failure cases yet, I'm not sure if anything is missing.

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ealonso, multiSelection is not defined happens on Select Categories selector, would you mind having a look at?
**Step to reproduce**

1. Add a new site
2. Add a category under a vocabulary
3. Add a navigation menu
4. Add a Category type item
5. Select the new category

**Expected Results**
The category is selected.

**Actual Results**
The modal is empty. The following error is thrown in browser console.
image

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Hi @ealonso, would you mind checking the sf issue? Thanks

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Hey @Tim-Cao,
The SF error is not related with the commits in this pr, it is related with Objects.

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/131559

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
