### PR TITLE
LPS-200496 Replace AUI() usages in change-tracking-web

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
The motivation behind this ticket is removal of AUI code and use native functions instead.
https://liferay.atlassian.net/browse/LPS-200496

Steps to Verify
========
1. Enable LPS-171364 feature flag.
2. Enable Publications by going to Applications Menu -> Publications
3. Create two different publications and go to one of them by clicking on the button on the top of the portal view -> then select a publication
4. In one of the publications make some changes, like adding a paragraph to the Home page view
5. Go to publications like in step 2
6. Click on the publication you made changes on -> Click on the change you've made -> in the change view click on the dropdown button on the right -> Move Changes
7. In the Move Changes view go to the bottom -> in the Publications section select the other publication and see that the Move Changes button is disabled and enabled.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by p2kmgcl** [comment]
ci:forward :love_you_gesture:

**Comment by liulukiwi** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143175

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
