### PR TITLE
LPS-204954 - Cannot propagate changes from Site Template to Site when using Master Page

### PR DESCRIPTION
**Pull request by ruben-pulido**
This PR adds an integration test to the original PR: https://github.com/liferay-echo/liferay-portal/pull/14925

Original PR comment:

https://liferay.atlassian.net/browse/LPS-204954

Previously submitted under https://github.com/liferay-echo/liferay-portal/pull/14902 @ruben-pulido. Resending due to a few issues caught by @jorgediaz-lr.

The changes from the previous pull are:

1. Using a parameter to set the boolean for `privateLayout` instead of hard coded `0` and `1` due to differences in databases
2. Updating the layout's `layoutId` to avoid a potential conflict in the case of private pages existing in the site
3. Additionally updating the `LayoutFriendlyURL` table to reflect the change from public to private

If there are any questions or concerns please let me know.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
@ruben-pulido That's what I was seeing as well. I modeled this new upgrade process heavily based on https://github.com/jonathanmccann/liferay-portal/blob/6ce0b9eb049e99a50285a324a3bd4afd76d340ab/modules/apps/asset/asset-display-page-service/src/main/java/com/liferay/asset/display/page/internal/upgrade/v2_1_1/AssetDisplayPrivateLayoutUpgradeProcess.java#L79

There it simply updates the `layoutId` without changing any other tables so I assume we are safe here as well.

**Comment by jonathanmccann** [comment]
ci:test:upgrade

**Comment by ruben-pulido** [comment]
Feedback from @jkappler incorporated here: https://github.com/liferay-echo/liferay-portal/pull/14950
- Simplified integration test removing publication step since it is not required
- Use classPK instead of classPk in query

**Pull request closed without merging**
