### PR TITLE
LPS-174431 Site template friendly URL collision - edit site template page

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @liferay-echo ,

Please review my changes for [LPS-174431](https://issues.liferay.com/browse/LPS-174431) story, as this modifies code in the `layout/layout-admin-web` project.

Use `feature.flag.LPS-174431=true` for testing.

Thanks,
Vendel

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
Hi @vendeltoreki, we'll try to take a look at it tomorrow. In the meantime, can you help us with the conflicts?

Thanks as always!

**Comment by vendeltoreki** [comment]
Thanks, @jkappler . Meanwhile, I'm working on a similar story too: [LPS-174434](https://issues.liferay.com/browse/LPS-174434). This is basically modifying the same code.
Is it ok if I send these together?

**Comment by jkappler** [comment]
sure, please to @vendeltoreki!

**Comment by vendeltoreki** [comment]
Hi @jkappler ,

I've force-pushed the merged conflicts and the changes related to the other [LPS-174434](https://issues.liferay.com/browse/LPS-174434) story.

We have 2 feature flags now:
```
feature.flag.LPS-174431=true
feature.flag.LPS-174434=true
```

Thanks,
Vendel

**Comment by jkappler** [comment]
Hi @vendeltoreki, from code perspective it looks good (made the basic tests). I passed this to our design team and they mention that we are working on displaying the alerts in a different way in another similar story (https://issues.liferay.com/browse/LPS-172561), like this:
 
Screenshot 2023-03-30 at 10 02 13

The figma has more info, so it would be food to standardize this.

What do you think?

Thanks!

**Comment by vendeltoreki** [comment]
Hi @jkappler ,

Yes, the case seems similar. However, this check is specifically for site templates. If there are multiple similar page friendly URLs across unrelated sites, then it's usually not a problem (e.g.: '/about' or '/news' etc.). These warnings are to prevent the site template admins from creating pages, that some sites already have on their own. Also, preventing site admins to create a page that the template already has, just not propagated yet.
We already had this conflict detection after the propagation, it just wasn't visible for most of the users.

My guess is that the design will also be different, as in the warning text we explain site template specific problems. However, the idea of limiting the number of conflicts we display is something we can incorporate here, as we don't want to list ~3000 entries in one warning when so many sites were created from a template.

So yes, if the component will be configurable, then we can replace this with it. But I don't really see too many common logic that would be worth to be extracted into one component.

cc: @zsigmondrab

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
Hi @vendeltoreki, seems another baseline issue: 

[beanshell] [Baseline Warning] Bundle Version Change Recommended: 102.1.0

**Comment by vendeltoreki** [comment]
Thanks, @jkappler . If that's OK, I'm forwarding this to Staging QA, so they can also check this change: https://github.com/liferay-staging/liferay-portal/pull/265 .

**Comment by jkappler** [comment]
ok, perfect, thanks @vendeltoreki

**Comment by jkappler** [comment]
I will close this one, we can send from the other PR

**Pull request closed without merging**
