### PR TITLE
LPS-190225 Remove default value

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Only one unique failure was found by the CI ([comparison with acceptance routine here](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1690474957166&testrayRunIdA=2395783501&testrayRunIdB=2395839245)) and were not reproducible locally. The others are not related to this PR. See https://github.com/brianchandotcom/liferay-portal/pull/138499

**Comment by alessandromalves** [comment]
ci:close

**Pull request closed without merging**
