### PR TITLE
LPS-195024 Convert old AUI to new js in product_navigation_control_menu.js

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-195024)

## Steps
- Go to Design > Pages 
- Create a Widget Page and edit it
- See buttons in the control Menu
ezgif com-video-to-gif (2)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
Hey @liulukiwi ! The SF is failing on Poshi, I think is related with your changes, could take a look? Thanks!

**Comment by Tim-Cao** [comment]
Hi @DiegoHu97, Could you help us to find which js file could indicate the buttons are loaded completely?
Before this change, /o/frontend-js-aui-web/liferay/menu_toggle.js could indicate. The current poshi changes will make poshi tests unstable.

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/13600

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
