### PR TITLE
LPS-171486 "Preview in a new tab" option for pages does not load Client Extensions

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-171486

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1377401_7794

**Comment by Tim-Cao** [comment]
Hi @lfbesada, the failure cases are unrelated to your changes.

**Comment by jkappler** [comment]
❤️

**Comment by jkappler** [comment]
ci:forward

**Review by jkappler — APPROVED** [review]

**Comment by lfbesada** [comment]
ci:reevaluate:1267401_6852

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128486

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
