### PR TITLE
LPS-119211 Adds ApplicationsMenu Application Selector to Portlet Header

### PR DESCRIPTION
**Pull request by jbalsas**
This is a slight revamp of https://github.com/liferay-echo/liferay-portal/pull/1959 and the second part of the split of https://github.com/liferay-frontend/liferay-portal/pull/289 which covers the first [UX Refinement for Applications Menu](https://issues.liferay.com/browse/LPS-117782)
- [Show Application Section in Control Menu](https://issues.liferay.com/browse/LPS-119209)
- [Show Related Applications Dropdown in Control Menu](https://issues.liferay.com/browse/LPS-119211)

I tried to reduce the amount of checks we do from the previous version and testing it again I don't perceive a noticeable regression. Since the `portlet_header` is only included in admin apps, there should be no impact on performance tests either.

If we want to further improve server-side performance, we can do something similar to the `ProductsMenu` component that rather than the list of Apps gets an endpoint to retrieve it asynchronously. I didn't do it this way because we need to know in advance if we have 1 or more apps in a section in order to show a dropdown, so there's no easy way to avoid the calculation.

90763509-1f611400-e2e7-11ea-939d-8b314868759a

90763494-14a67f00-e2e7-11ea-9a99-6512ab53c240

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
@marcoscv-work, [based on the design](https://www.figma.com/file/IWV8DgAZdoyzfHAGLGY5JN/Applications-Menu-Visual-changes-7.3-release?node-id=215%3A128), the dropdown, when it exists, should have a **fixed width of 292px**. Right now the implementation is still fluid, which also causes the caret to slightly reposition based on the difference between the jsp and js rendering (spaces). Please work on that adjustment and other additional visuals that might be needed.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @jbalsas,

A normal use case that we have in portal is allow developers change the the portlet title, for example when we are editing or adding a new entity we change the portlet title, please see the following screenshots:

Test_Test_-_Edit_User_Test_Test_-_Control_Panel_-_Liferay

Add_User_-_Control_Panel_-_Liferay


Is it the expected behaviour? Could you please take a look at it?

Regards,
Eudaldo.

**Comment by ealonso** [comment]
@jbalsas I've just send a pr with some changes to you, please see: https://github.com/jbalsas/liferay-portal/pull/2232, I've made some source format and implement the active item on drop down

**Comment by ealonso** [comment]
ci:close

**Comment by jbalsas** [comment]
Hey @ealonso, I think this is more for @victorvalle and @ryconn888 to determine. Will ping them on Slack as well so they can take this into consideration.

**Pull request closed without merging**
