### PR TITLE
LPS-134433 BuildLang

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reevaluate:1257401_2165

**Comment by ealonso** [comment]
ci:reevaluate:1257401_2165

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1257401_2196

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @Tim-Cao,

I've already fix it.

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
@ealonso, thanks

**Comment by Tim-Cao** [comment]
The failure cases are unrelated to changes in PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/103827

**Pull request closed without merging**
