### PR TITLE
LPS-202551 Revert change as this should affect only paragraph fragment

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
If you click on the paragraph is still adding an update in the history, as is adding a paragraph element in the default text.

Not sure if we can add this paragraph element in the default text for paragraph fragment.

image

image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by georgel-pop-lr** [comment]
Hi @veroglez,

I tried to change the default value of https://github.com/liferay/liferay-portal/blob/13b99c305ec72a38a2f28a1be08ab7f202e2c7f5/modules/apps/fragment/fragment-collection-contributor/fragment-collection-contributor-basic-component/src/main/resources/com/liferay/fragment/collection/contributor/basic/component/dependencies/paragraph/index.html  to include the p element but is still adding a change in the paragraph fragment when clicked. I checked this and before changing this config this did not happen for paragraphs.

The value, after clicking on it, is this:
<div class="clearfix component-paragraph text-break page-editor__editable page-editor__editable--active" data-lfr-editable-id="element-text" data-lfr-editable-type="rich-text" data-tooltip-floating="true" title="Edit Text"><p>A paragraph is a self-contained unit of a discourse in writing dealing with a particular point or idea. Paragraphs are usually an expected part of formal writing, used to organize longer prose.</p>
</div>

Not sure what else could I try, so any ideas would be great.

Regards.

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
resent here https://github.com/liferay-echo/liferay-portal/pull/14827

**Pull request closed without merging**
