### PR TITLE
LPS-164942 User without permission should not see form container

### PR DESCRIPTION
**Pull request by thienquach87**
@ealonso  
Here is the PR for fixing https://issues.liferay.com/browse/LPS-164942. The original PR was passed my review. Please help to review and leave your comments.

The solution is as below:
The LayoutData contains the items to be displayed on the Content Page Editor. So I filter the data layout to make sure the Form Containers that the user doesn't have permission to view and its children wouldn't be included.
I also have a change on getFragmentEntryLinkJSONObject to not show submit button in [ContentsSidebar](https://github.com/liferay/liferay-portal-ee/blob/master/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/plugins/page-content/components/ContentsSidebar.js)

cc: @tototrinh

Thanks

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by tototrinh** [comment]
ci:test:sf

**Comment by tototrinh** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
I'm marking the PR as on hold, since we first need to clarify with Product Management and Design what the expected behaviour should be in this case.

**Comment by ruben-pulido** [comment]
@thienquach87 

The expected behaviour in this case still needs to be defined.
An "unexpected error" should not be displayed, but it is not clear yet what should be displayed instead.

Hiding the container could lead to undesired results, since the page editor would be seeing a different output while editing the page from what will be later displayed in view mode. Therefore we are discarding this PR and will revisit the bug once the expected behaviour has been defined.

**Pull request closed without merging**
