### PR TITLE
LPS-171971 Replace liferay-ui:icon-help in edit_asset_vocabulary.jsp

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Test Scenario

1. Navigate to Categorization > Categories.
2. Click on the Add button (+) to create a new vocabulary.
3. Hover the info icon next to the Visibility label and see the message: _When visibility is set to internal, the vocabulary will not be displayed in pages, either through widgets, fragments, or content mapping, and can be used for internal searches and categorization only. Visibility configuration cannot be reverted._
image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by veroglez** [comment]
see https://github.com/liferay-echo/liferay-portal/pull/10794

**Pull request closed without merging**
