### PR TITLE
LPS-189886 Apply to asset-list-web

### PR DESCRIPTION
**Pull request by sandrodw3**
Motivation
=======
The motivation behind this PR is to fix some style issues in Asset Publisher and Collections for the Edit View.

Proposed Solution
========
What I did to solve this problem is to add the necessary spacing between elements and also remove some unnecessary styling code from it.

Steps to Verify
========
### Asset Publisher
1. Go to Edit view for a page
2. Add an Asset Publisher from the left sidebar Widget Section
3. Click on the Options ellipsis button -> Configuration
4. Select Dynamic for Asset Selection and then go to the Filter section

### Collections
1. Go to Site Builder > Collections
2. Create a dynamic collection
3. Open Filter section

Screenshots
========
BEFORE
Screenshot 2023-07-17 at 11 06 01

AFTER
Screenshot 2023-07-17 at 11 07 51

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
cc @Stephy6

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/12926

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
