### PR TITLE
LPD-28845 - Create site-admin Open API Specification for export/import of Pages

### PR DESCRIPTION
**Pull request by ruben-pulido**
https://liferay.atlassian.net/browse/LPD-28845 - Create site-admin Open API Specification for export/import of Pages

This PR contains the Open API specification for pages (including content and widget pages), page specifications (i.e: draft and published), experiences, page elements, page rules, rule conditions and actions, fragment compositions, widget instances, master pages, display page templates, page templates (including content page template and widget page templates), display page template folders, page template sets and utility pages.  

A commit containing the generated buildREST code is not yet included since buildREST is failing for this open API specification. (A separate issue has been opened to investigate: https://liferay.atlassian.net/browse/LPD-28872)

The goal of the site-admin REST APIs is twofold:
- Allow promoting pages, along with all their referenced entities, across environments.
- Provide a REST API to manage pages, which could be used both by external clients and by internal clients, as our page administration and page editor UIs.

The components share part of the structure with the ones already defined in the headless-delivery module. 
However, we have taken the opportunity of starting with a new version of the API to simplify them (for example, removing unneeded fields like internal IDs or renaming entities by replacing legacy names by the current names used in the UI, thus making the API easier to understand, as well as moving shared properties to Base entities and extending from them).

We have also agreed to simplify some patterns that made the endpoints convoluted, for example, including external reference codes as part of the path without specifying "by-external-reference-code", with the aim of making the endpoints more concise and easier to read.

Endpoints and entities use External Reference Codes to ensure relationships between entities are maintained and can be resolved in a lazy fashion.

Although multiple conversations between members of Page Management team, Headless team and Marco (thank you all!), have already taken place to arrive at the current status, any additional feedback is more than welcome.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by lfbesada — APPROVED** [review]
@ruben-pulido Great work :clap:

**Comment by victorg1991** [comment]
Looks great @ruben-pulido :clap: 

Just a couple of questions/comments :) 


What is the purpose of this?  https://github.com/liferay-echo/liferay-portal/blob/87adcb2d068822ed3654ff1c2330f04ae38ae904/modules/apps/headless/headless-admin-site/headless-admin-site-impl/rest-openapi.yaml#L2107

and also this:  https://github.com/liferay-echo/liferay-portal/blob/87adcb2d068822ed3654ff1c2330f04ae38ae904/modules/apps/headless/headless-admin-site/headless-admin-site-impl/rest-openapi.yaml#L574C1-L578C107

I believe it should be "form" in this comment? https://github.com/liferay-echo/liferay-portal/blob/87adcb2d068822ed3654ff1c2330f04ae38ae904/modules/apps/headless/headless-admin-site/headless-admin-site-impl/rest-openapi.yaml#L2020C1-L2023C51


Regarding [rules](https://github.com/liferay-echo/liferay-portal/blob/87adcb2d068822ed3654ff1c2330f04ae38ae904/modules/apps/headless/headless-admin-site/headless-admin-site-impl/rest-openapi.yaml#L2258) I'm not so sure if we should include it in the first version. Since we are adding more thing to rules maybe it is worth waiting for them to evolve a bit before adding it to the yaml

**Comment by ruben-pulido** [comment]
Thank you for the review @victorg1991 and sorry for the mega late response! Better late than never 

> What is the purpose of this?
> 
> https://github.com/liferay-echo/liferay-portal/blob/87adcb2d068822ed3654ff1c2330f04ae38ae904/modules/apps/headless/headless-admin-site/headless-admin-site-impl/rest-openapi.yaml#L2107

"draftFragmentExternalReferenceCode" corresponds to the internal value "originalFragmentEntryLinkId".
When publishing a page, this allows updating the fragments in the published page, (instead of deleting them and recreating them).
Having this, prevents publications from detecting those "changes", which were confusing for the user (see https://liferay.atlassian.net/browse/LPD-5088)

Thanks @lfbesada for the explanation!

**Comment by ruben-pulido** [comment]
> and also this: https://github.com/liferay-echo/liferay-portal/blob/87adcb2d068822ed3654ff1c2330f04ae38ae904/modules/apps/headless/headless-admin-site/headless-admin-site-impl/rest-openapi.yaml#L574C1-L578C107

pageSpecifications correspond to the draft and published "versions" of the page.
pageVersion was not deemed as an appropriate term, which led to using pageSpecification (which seems not so easy to understand :( )

**Comment by ruben-pulido** [comment]
> I believe it should be "form" in this comment? https://github.com/liferay-echo/liferay-portal/blob/87adcb2d068822ed3654ff1c2330f04ae38ae904/modules/apps/headless/headless-admin-site/headless-admin-site-impl/rest-openapi.yaml#L2020C1-L2023C51

Thanks!

**Comment by ruben-pulido** [comment]
> Regarding [rules](https://github.com/liferay-echo/liferay-portal/blob/87adcb2d068822ed3654ff1c2330f04ae38ae904/modules/apps/headless/headless-admin-site/headless-admin-site-impl/rest-openapi.yaml#L2258) I'm not so sure if we should include it in the first version. Since we are adding more thing to rules maybe it is worth waiting for them to evolve a bit before adding it to the yaml

I talked about this to Javi, and we agreed to keep them for now on the definition and move the stories related to rules to a separate epic.

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/16035

**Pull request closed without merging**
