### PR TITLE
LPS-118321 Avoid destroying editor twice

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl , there is a regression issue that the popup doesn't close after edit inline content of HTML fragment.
Video

**Comment by veroglez** [comment]
ci:close

**Comment by Tim-Cao** [comment]
See https://github.com/Tim-Cao/liferay-portal/pull/344

**Pull request closed without merging**
