### PR TITLE
LPD-15726 - Blank page is displayed after filtering for category in collection page

### PR DESCRIPTION
**Pull request by ruben-pulido**
https://liferay.atlassian.net/browse/LPD-15726 - Blank page is displayed after filtering for category in collection page

//cc @balazssk

Original PR comment:

Motivation
=======
Blank page is displayed after filtering for category in collection page because in some cases a categorised User can make its way to the search results. Which can't be converted to the AssetList's type.
https://liferay.atlassian.net/browse/LPD-15726

Proposed Solution
========
By adding a classTypeId filter to the searchContext of the dynamicSearch triggered, we can rule out User typed results.

Cheers,
Balázs

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:report:2536761162

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
