### PR TITLE
LPS-196807 Older versions of Web Content are indexed with the newest version's values 

### PR DESCRIPTION
**Pull request by lfbesada**
This PR fixes two bugs:
https://liferay.atlassian.net/browse/LPS-196807
https://liferay.atlassian.net/browse/LPS-198486
On already existing content, a reindex is needed to fix these issues.

cc: @joshuacords @ruben-pulido

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:stop

**Pull request closed without merging**
