### PR TITLE
LPS-123148 Add page comment fails after upgrade

### PR DESCRIPTION
**Pull request by IstvanD**
Dear Team,

Could you please review this pull request?

On DXP, all Pages (`Layouts`) have a corresponding `AssetEntry` that is fetched and used during the submission of a Page Comment
https://github.com/liferay/liferay-portal/blob/master/modules/apps/comment/comment-taglib/src/main/java/com/liferay/comment/taglib/internal/struts/EditDiscussionStrutsAction.java#L211

On 6.2, Pages don't have an `AssetEntry`, therefore, when upgrading 6.2 => DXP adding a Page Comment will fail due to the missing `AssetEntry`.

Therefore, I introduced a new upgrade process that calls `layoutLocalService.updateAsset()` for all `Layouts`, creating their `AssetEntries`.
 
Thank you and best regards,
István

### CODE REVIEW

**Comment by IstvanD** [comment]
ci:test:sf

**Comment by IstvanD** [comment]
ci:test:relevant

**Comment by IstvanD** [comment]
Dear Team,

I was wondering if you could find the time to review the pull request.
Please let me know if you need any help or explanation.

Thank you and best regards,
István

**Comment by jkappler** [comment]
Hey @IstvanD, it was holiday in Spain yesterday, we'll take a look at it today

**Comment by IstvanD** [comment]
Hi @jkappler no problem. I hope you enjoyed the holiday. :)
Thank you for looking at the pull.

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/2850

**Pull request closed without merging**
