### PR TITLE
LPS-183305 Moves onClick for configure-chart to js

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
The motivation behind this ticket is to remove the usage of a openModal component directly rendered from the backend and use a js component instead for the charts modal configuration in the Content Dashboard.

Proposed Solution
========
What I did to solve the problem is to create a js component that is called when the configure button is pressed and receives the necessary url and other props to render the modal.

Steps to Verify
========
1. Go to the Content Dashboard
2. Click on Configure Chart button
3. Check that the modal works correctly by interchanging audiences and saving them.

### CODE REVIEW

**Comment by Stephy6** [comment]
ci:test:sf

**Comment by Stephy6** [comment]
ci:test:relevant

**Review by sandrodw3 — COMMENTED** [review]
Hey @Stephy6, good job! This looks good and works, but I was thinking that instead of using a `liferay-frontend:component`, you could just add a `propsTransformer` to the `clay:button`. Do you know how it works? Tell me if you need any help 😄

**Comment by Stephy6** [comment]
ci:test:sf

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by Stephy6** [comment]
ci:stop

**Comment by Stephy6** [comment]
ci:forward

**Comment by ealonso** [comment]
Hey @Stephy6,
The test failure is related with your changes

**Comment by Stephy6** [comment]
ci:forward

**Comment by Stephy6** [comment]
ci:stop

**Comment by Stephy6** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:test:stable

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
