### PR TITLE
LPS-150307

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-150307

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @mbowerman Thanks for the fix!

After reviewing it I think it may be better to escape it when adding the param to the url, I've resent it here: https://github.com/liferay-echo/liferay-portal/pull/7631

Also, the filter by structure option was failing too, so I fixed that too :)

Let me know what do you think!

**Pull request closed without merging**
