### PR TITLE
LPS-129677, LPS-132403, LPS-132684, LPS-134207, LPS-134897 | master

### PR DESCRIPTION
**Pull request by veroglez**
https://issues.liferay.com/browse/LPS-129677
https://issues.liferay.com/browse/LPS-132403
https://issues.liferay.com/browse/LPS-132684
https://issues.liferay.com/browse/LPS-134207
https://issues.liferay.com/browse/LPS-134897

This is only for master.

@Tim-Cao

### CODE REVIEW

**Comment by veroglez** [comment]
ci:test:echo

**Comment by veroglez** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
Hi @veroglez, good news, ci:test:echo and ci:test:relevant catch two issues here
https://issues.liferay.com/browse/LPS-135294
https://issues.liferay.com/browse/LPS-135295

**Comment by Tim-Cao** [comment]
Fixed some missing poshi issue, then resend here
https://github.com/liferay-echo/liferay-portal/pull/5104

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
