### PR TITLE
LPS-197426 Improve unlock locked pages using Actionable query

### PR DESCRIPTION
**Pull request by Mikellorza**
Changes requested from Brian here: https://github.com/brianchandotcom/liferay-portal/pull/143253#issuecomment-1793387212

**Solution**: Pass the map and the date as parameters.

technical task : https://liferay.atlassian.net/browse/LPS-197426

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by liulukiwi** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/143773

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
