### PR TITLE
LPS-195369 Migrate the Page Edition Mode Single Select to the Clay Picker

### PR DESCRIPTION
**Pull request by liulukiwi**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-195369)

## Steps
- Go to Design > Pages 
- Create a Widget Content Page and edit it

Screenshot 2023-09-07 at 10 48 20

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by liulukiwi** [comment]
ci:forward

**Comment by rafaellajordao** [comment]
The failures are not related to this PR [(comparison with acceptance routine here)](https://testray.liferay.com/home/-/testray/runs/compare?testrayRunIdB=2420185341&testrayRunIdA=2420925767&view=teams). See https://github.com/brianchandotcom/liferay-portal/pull/140480

**Comment by rafaellajordao** [comment]
ci:close

**Pull request closed without merging**
