### PR TITLE
[TS] LPS-186036

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team,

This is a PR that aims to fix the duplication of links in the portlet configuration tab Communication in other supported languages than English.

Could you please review it? Please, let me know if further clarifications are needed for this review.

Thanks!

Motivation
=======
Fix the duplication of links in the portlet configuration tab Communication in other supported languages than English.

Proposed Solution
========
Remove the links from the translations to add them in the JSON file used by Liferay Learn Taglib.

Steps to Verify
========

1. Add an Asset Publisher widget to Home page
2. Navigate in the page with different language (in my case localhost:8080/es)
3. Go to Asset Publisher > Configuration > Communication

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
Hi @dacousalr @henriquelimadotcom 
Thanks for the PR.
I think the changes you are doing in this PR are not related to Asset Publisher specifically but to any portlet. That's why it seems to me that we are not the right team to review this PR, I think it should be sent to Core Infra.
Regards

**Comment by dacousalr** [comment]
Hi @lfbesada,

LPS-186036 was created due to the changes introduced in LPS-175972 by a member of the Echo team.

Looking at the [app.bnd](https://github.com/liferay/liferay-portal/blob/018c0afef9bb74c509d7f0629f53ce91fee4ab23/modules/apps/portlet-configuration/app.bnd#L13) of this set of modules, this seems to belong to the former Web Experience Management team, former name of the current Echo team.

Best

**Comment by lfbesada** [comment]
Hi @dacousalr 
You're right, sorry for my confusion! 
Regards

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
