### PR TITLE
LPS-147252, LPS-147253, LPS-146976 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-147252
https://issues.liferay.com/browse/LPS-147253
https://issues.liferay.com/browse/LPS-146976

This is only for master.

@sandrodw3
@lfbesada

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
Sorry @Tim-Cao, I'm sending another one modifying some frontend things and rebasing on Victor's PR that was in conflict with this one.

See https://github.com/liferay-echo/liferay-portal/pull/7415

**Comment by Tim-Cao** [comment]
@sandrodw3 nvm

**Pull request closed without merging**
