### PR TITLE
LPS-151001

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-151001

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @holatuwol,
Thanks for the fix!
In order to easy testing, could you please attach to the ticket the 7.2.sp6 SQL dump used to assert it? Thank you very much! ❤️
Regards

**Comment by tototrinh** [comment]
Hi @lfbesada , I have attached the SQL file used for testing in the LPS ticket. Hope this helps. Thanks.

**Review by lfbesada — COMMENTED** [review]
Hi @holatuwol @tototrinh 
Thanks for the fix! It works great!
I have added a commit in order to better performance, please see: https://github.com/liferay-echo/liferay-portal/pull/7887
Thanks!

**Pull request closed without merging**
