### PR TITLE
LPS-162527 Set to false since we are unmrking the item

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
@ealonso

**Comment by ozysouza** [comment]
Hi @victorg1991 @ealonso, could you please have a look on the integration test [PublishLayoutMVCActionCommandTest > testDeletedItemPortletPreferencesAreRemovedWhenLayoutIsPublished](https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/245118/testReport/com.liferay.layout.content.page.editor.web.internal.portlet.action.test/PublishLayoutMVCActionCommandTest/testDeletedItemPortletPreferencesAreRemovedWhenLayoutIsPublished/)? The failure is related to the changes.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
