### PR TITLE
LPS-147972 Adapt modal size

### PR DESCRIPTION
**Pull request by victorg1991**
The idea is to some exploratory testing of this PR

More info in the associated subtask: https://issues.liferay.com/browse/LPS-153440

@david-gutierrez-mesa @liulukiwi @Tim-Cao @ozysouza

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by ozysouza** [comment]
Just started reviewing :)

**Comment by ozysouza** [comment]
Hi @victorg1991, I've found a bug and some questions. Would you have a look at?

 * There is a bug when selecting the page via keyboard.

1.   Add a site
2.   Add a page
3.   Add a navigation menu
4.   Go to Select pages
5.   Search for the page name
6.   Press TAB
7.   Press space to select the page
8.   Click on the Select button

 * Should we be able to select the page just clicking on the name? Currently it's not working.
 * Are we going to add the same tree Layout to Categories?
 * I could add the page to navigation menu without select it, searching and pressing enter, the page was automatically added to navigation menu, but I could just reporduce it twice of 50 times, I didn't find a consistent way to reproduce so I don't think we just be worried about this one.

https://user-images.githubusercontent.com/72820234/168886278-ef9f4c4e-2f51-481f-8ef6-054aafd19d6a.mp4

**Comment by ozysouza** [comment]
@david-gutierrez-mesa, would you please test it on Safari? Thanks!

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
should be fixed now @ozysouza would you mind checking again, please? :D

**Comment by victorg1991** [comment]
nevermind @ozysouza give me some minutes

**Comment by victorg1991** [comment]
now @ozysouza 😇

**Comment by ozysouza** [comment]
> now @ozysouza innocent

Hey @victorg1991, the issues are gone! :tada:

**Comment by victorg1991** [comment]
Thanks for the review!!

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ozysouza** [comment]
ci:reevaluate:1327401_3991

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/8159

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
