### PR TITLE
LPS-124407 Set appropriate language cookie

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @victorg1991, there is a NoSuchResourceActionException thrown in server console.
**Step to reproduce:**
1. Add a page based on Blank
2. Add an Asset Publisher to page
3. Publish the page

**Expected Results:**
There shouldn't be error thrown in console.

**Actual Results:**
The following error thrown in console.
```
2020-12-15 08:45:51.610 ERROR [http-nio-8080-exec-8][SearchPermissionCheckerImpl:159] com.liferay.portal.kernel.exception.NoSuchResourceActionException: com.liferay.translation.model.TranslationEntry#VIEW
com.liferay.portal.kernel.exception.NoSuchResourceActionException: com.liferay.translation.model.TranslationEntry#VIEW
        at com.liferay.portal.service.impl.ResourceActionLocalServiceImpl.getResourceAction(ResourceActionLocalServiceImpl.java:323)
        at sun.reflect.GeneratedMethodAccessor170.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
        at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
        at com.sun.proxy.$Proxy32.getResourceAction(Unknown Source)
        at com.liferay.portal.service.impl.ResourcePermissionLocalServiceImpl.hasResourcePermission(ResourcePermissionLocalServiceImpl.java:1171)
        at sun.reflect.GeneratedMethodAccessor921.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:50)
        at com.liferay.portal.spring.transaction.TransactionInterceptor.invoke(TransactionInterceptor.java:69)
        at com.liferay.portal.spring.aop.AopMethodInvocationImpl.proceed(AopMethodInvocationImpl.java:57)
        at com.liferay.portal.spring.aop.AopInvocationHandler.invoke(AopInvocationHandler.java:49)
        at com.sun.proxy.$Proxy31.hasResourcePermission(Unknown Source)
        at com.liferay.portal.search.internal.SearchPermissionCheckerImpl._getPermissionFilter(SearchPermissionCheckerImpl.java:535)
```
I doubt your changes make this issue happens on content page.
https://issues.liferay.com/browse/LPS-123324

**Comment by victorg1991** [comment]
waiting for the fix of https://issues.liferay.com/browse/LPS-123324 in order to merge this pr, otherwise test are going to fail again

**Comment by victorg1991** [comment]
Fix is on its way to master, cherrypicking it here to see if tests pass now

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
