### PR TITLE
[TS] LPS-137014 Copy the old LayoutPrototype permissions for the new LayoutPageTemplateEntries

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

Can you please review?
https://issues.liferay.com/browse/LPS-137014

Thanks,
Balázs

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Known issues: [LPS-134190](https://issues.liferay.com/browse/LPS-106184), [LPS-136747](https://issues.liferay.com/browse/LPS-136747), failures are not related to this pr, will send this pr manually.

**Comment by liulukiwi** [comment]
ci:stop

**Comment by liulukiwi** [comment]
Pushed to BChan directly:
brianchandotcom#105658

**Pull request closed without merging**
