### PR TITLE
LPS-124706 Preserve existing fragment configurations

### PR DESCRIPTION
**Pull request by allen-ziegenfus**
We've been seeing a number of fragment styling configs getting lost after upgrading to 7.3, for example cases like the following:
```
  {
    "com.liferay.fragment.entry.processor.background.image.BackgroundImageFragmentEntryProcessor": {},
    "com.liferay.fragment.entry.processor.editable.EditableFragmentEntryProcessor": {
      "link": { "defaultValue": "Go Somewhere", "config": {} }
    },
    "com.liferay.fragment.entry.processor.freemarker.FreeMarkerFragmentEntryProcessor": {
      "buttonType": "secondary"
    }
  }
```
will get changed to

```
 {
    "com.liferay.fragment.entry.processor.background.image.BackgroundImageFragmentEntryProcessor": {},
    "com.liferay.fragment.entry.processor.editable.EditableFragmentEntryProcessor": {
      "link": { "defaultValue": "Go Somewhere", "config": {} }
    },
    "com.liferay.fragment.entry.processor.freemarker.FreeMarkerFragmentEntryProcessor": {}
  }
```
This is because the upgrade step only includes settings from com.liferay.fragment.entry.processor.freemarker.FreeMarkerFragmentEntryProcessor that have an experience. But there are cases (e.g. display page templates) where we have configurations without experiences and the upgrade step is just removing these.

I made this fix which solves a lot of styling issues for us. Can you please take a look?

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by allen-ziegenfus** [comment]
Hmm I believe the test case would have to be updated, sorry I overlooked that

**Comment by pavel-savinov** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by allen-ziegenfus** [comment]
@ealonso  I fixed the test failures - can we try this again or do I need to open a new PR? 

Thanks

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
Looks like random failure, I am running tests again

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
@pavel-savinov @allen-ziegenfus is this ready to be sent to Brian?

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
