### PR TITLE
LPS-134885 Create Templates entry in Product Menu -> Design

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-134885

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/5083

**Pull request closed without merging**
