### PR TITLE
LPS-133322 Check if the field exists before printing it. This is useful when we create web contents based on a structure, and then add fields to it.

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reevaluate:1257401_462

**Comment by ealonso** [comment]
ci:forward

**Review by ealonso — APPROVED** [review]

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1257401_525

**Comment by Tim-Cao** [comment]
The failure cases will be fixed in https://github.com/brianchandotcom/liferay-portal/pull/102597. Due to saving CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/102631

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
