### PR TITLE
LPD-25467 Adds ERC to layout page template entry

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-25467

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:upgrade

**Comment by lfbesada** [comment]
ci:report:2568117285

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:upgrade

**Comment by lfbesada** [comment]
ci:report:2568128719

**Comment by lfbesada** [comment]
ci:report:2568125481

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:report:2568298610

**Comment by lfbesada** [comment]
ci:report:2568295672

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:report:2568371879

**Comment by lfbesada** [comment]
ci:reevaluate:1407401_9598

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:reevaluate:1397401_10078

**Comment by lfbesada** [comment]
ci:reevaluate:1397401_10079

**Comment by pyoo47** [comment]
ci:report:2568371879

**Comment by ealonso** [comment]
ci:test:stable

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
