### PR TITLE
LPS-143251 | Correct LayoutClassedModelUsage entry for published content pages

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-143251 New method to obtain a fragmentEntryLink based on the original fragmentEntryLink
- LPS-143251 Build Service
- LPS-143251 Set original fragmentEntryLink when creating the object
- LPS-143251 Use correct value
- LPS-143251 Don't set in activate, otherwise we won't notice invalidate of cache in other places

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@ealonso, changes made

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@ealonso, applied changes. Only fragmentEntryLink containers will be taken into account

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
