### PR TITLE
LPD-31041 Replace by integration tests InformationTemplates#MapToEditableFieldInCollectionDisplay

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-31041

**What these tests do:**

- Create a site with a content layout and different types of content: Category, Blog entry, Document, and Web Content.
- Create an InformationTemplate for that content where they map a content field.
- Edit the page to map the InformationTemplate of the content using the different possibilities: collection-display, content-display, and editable-field.
- Publish the page and render it in view mode.
- Check that the InformationTemplate is rendered correctly on the page showing the expected content.

**Why they cannot be named after a specific class:**

- These integration tests are end-to-end since they involve everything from creating the template to rendering it.
- The execution of these tests involves several classes from both the different modules of the Template app and other apps such as Layout and Fragment. 

Therefore, I think that these tests cannot be identified with any specific class, but rather with a functionality: mapping InformationTemplate fields in content pages, based on which I have named it MapToFieldInformationTemplateTest.

[LPD-31320]: https://liferay.atlassian.net/browse/LPD-31320?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
I have only rebase with master

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
