### PR TITLE
LPS-138659 Fix test by capturing the log. It's okay to do it since we are forcing a failure in freemarker and we check for FragmentEntryContentException. AssertionErrors comes from the log

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@ealonso

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The failure is unrelated to this PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/106679

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
