### PR TITLE
LPS-190735 Exclude props with default value from export

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-190735)

Motivation
=======
When exporting pages, there are some default or empty props that are stored the json created when exporting the page. We want to avoid those default props to be exported.

**NOTE: I will include two screenshots, at left the screenshot without the default props and at right the screenshot with the props configured and exported well.**

## Steps
- Go to Design > Page Templates > Page Templates > Create a Content Page Template 

**Case 1: Container**
  - Add a Container to a content page template
  - Select the Container and see Container configurations at right side 
  - In general tab > Container Width > Fixed
  - In Styles tab configure the opacity to 99 and the following properties to 1px:
  - "borderWidth",
     "marginBottom",
     "marginLeft",
     "marginRight",
     "marginTop",
     "paddingBottom",
     "paddingLeft",
     "paddingRight",
     "paddingTop",
containerWithoutDefaultProps1
containerWithPropsConfigured1

**Case 3: Form**
  - Go to Control Menu > Control Panel > Objects
  - Create a new Object 
  - View the new Object 
  - Go to fields > add a new field
  - Publish the Object
  - Add a Form Container to a content page template 
  - Map the container to the form created
  - Go to Form Container configuration 
  - In general tab > Container Width > Fixed
  
formWithoutDefault
formConfigured

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by DiegoHu97** [comment]
Hi @ruben-pulido, the pr is updated, thank you 😄

**Comment by ruben-pulido** [comment]
Hi @DiegoHu97

We are still hardcoding the default values within the mappers (for example here: https://github.com/liferay-echo/liferay-portal/blob/e4a32ea38d11610aea91315234caacdcf47e9def/modules/apps/headless/headless-delivery/headless-delivery-impl/src/main/java/com/liferay/headless/delivery/internal/dto/v1_0/mapper/FormLayoutStructureItemMapper.java#L251)
We should also replace those with references to the constants.

It's useful to define the constants as:
`	
public static final String VERTICAL_ALIGNMENT_START = "start";
public static final String VERTICAL_ALIGNMENT_TOP = "top";
`

but we should store the default values in a single place, for example:
`
public static final String DEFAULT_COLLECTION_VERTICAL_ALIGNMENT = VERTICAL_ALIGNMENT_START;
public static final String DEFAULT_ROW_VERTICAL_ALIGNMENT = VERTICAL_ALIGNMENT_TOP;
`

which we can reference from both the Mappers and the LayoutStructureItems.

I noticed there is a semantic versioning test failing. You'll need to run `gw baseline` to fix it.

Since I'll be on PTO during the next weeks you can assign additional review to @jkappler

**Comment by jkappler** [comment]
ci:forward

**Comment by DiegoHu97** [comment]
ci:forward

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/13107

**Pull request closed without merging**
