### PR TITLE
LPS-139962 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-139962

This is only for master.

@sandrodw3

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:stop

**Comment by sandrodw3** [comment]
ci:close

**Pull request closed without merging**
