### PR TITLE
LPS-195022 Migrate some page editor reducers to typescript

### PR DESCRIPTION
**Pull request by p2kmgcl**
I general these are only type migrations, but I needed to apply some logic changes too to facilitate typings :sweat_smile: 

The most annoying case is `fragmentEntryLinksReducer > UPDATE_PREVIEW_IMAGE` case, which contains a recursive iteration through all editable fields looking for a "fileEntryId" property with the corresponding value. Apart from that, those are just small changes :smile:

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by liulukiwi** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/140202

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
