### PR TITLE
LPS-118214 Move collections to the site builder section instead of content & data

### PR DESCRIPTION
**Pull request by pavel-savinov**
To be forwarded after the GA5 release.

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
