### PR TITLE
[TS] LPS-195074 | Site templates should not indicate propagation for master pages page templates or display pages

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?
https://liferay.atlassian.net/browse/LPS-195074
Thank you!

--------------------------------

This pull request is the result of https://liferay.atlassian.net/browse/PTR-4173. Based on the PTR I removed the propagation indication in site templates for master pages, page templates, and display pages. I also removed the information marker in the child site about resetting changes related to propagation for these page types.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @bakayattila 
Thanks for the fix! :heart: 
According to my tests, the "Actual behavior" described in the bug ticket description is not correct. Following the steps, the current behavior at the master branch is that the propagation icon appears in the site template but the reset-changes icon does not appear in the site.
Based on this I see that it works correctly only with the first commit and that the second is not necessary.
What do you think?
Regards

**Comment by lfbesada** [comment]
Hi @bakayattila 
I have observed exactly the same behavior in Utility Pages. I don't know if we should add the exclusion of Utility Pages here or if its propagation should work and it doesn't. This should be decided by the PM. Please, could you inquire about it in the related PTR?
Thank you so much!

**Comment by lfbesada** [comment]
Hi @bakayattila 
This PR should be adapted because of https://github.com/liferay/liferay-portal/commit/fe890a0f 
I have done it yet in my local and added a minor SF change. I will resend this when resolve my previous comments.
I guess we should add the Utility Page exclusion too, but it should be confirmed by the PM.
If they are OK with this I can add the Utility Page exclusion.
Regards

**Comment by bakayattila** [comment]
Hi @lfbesada,
I also found that the I icon (information disappeared for display pages on master, but I could not locate the reason behind it. My guess is that it was not removed but it was a side effect of another modification. So just in case, I removed it properly so it could not appear again if someone changes something around this side effect. It's a good idea to do the same with the utility pages.

**Comment by lfbesada** [comment]
@bakayattila 
Thanks! Could you please inquire about the Utility Page in the PTR? In that way, the decision will be explicit and will be documented so it will help us in the future.
Thanks!

**Comment by lfbesada** [comment]
@bakayattila 
About the "I Icon", it never appears in the templates because they have a different LayoutSet that is never linked to the prototype so [this condition](ayoutSetPrototypeLinkActive) always is evaluated as true. So I think the second commit is not necessary.
Regards

**Comment by lfbesada** [comment]
@bakayattila 
I have identified one scenario when your second commit is needed: using RFF "Disabled private pages" and checking "Create default pages as private (available only to members). If unchecked, they will be public (available to anyone)." when creating the site. In this case, the I Icon appears on templates and UPs.

Screenshot from 2023-10-10 11-20-50


So I will add it too, thanks!

**Comment by lfbesada** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/13962

**Pull request closed without merging**
