### PR TITLE
LPS-125886 Use new function to get initial value

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
@boton @victorg1991 Could you please take a look? Thanks!

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
This is good to go, thank you both @boton @pavel-savinov :D

**Comment by victorg1991** [comment]
doing the ci:forward after test:relevant has finished

**Comment by boton** [comment]
LGTM :)

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
