### PR TITLE
LPS-155873 Export/Import of cssClasses in fragments added to a page

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-155873 Adds new property that contains a list of CSS Classes that will be applied on top ot the element when being rendered in a page. For now, don't create a new external property since it's only a list of string
- LPS-155873 buildR
- LPS-155873 Take into account CSS Classes when exporting page definitions
- LPS-155873 Take into account CSS Classes when importing page definitions
- LPS-155873 CollectionStructureItem doesn't contain styles, so clean it up
- LPS-155873 Hide under FF
- LPS-155873 Early return, just like with the other importers

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
