### PR TITLE
LPS-171060 A draft version of a page is publicated when saving an AB Test variant

### PR DESCRIPTION
**Pull request by Mikellorza**
Coming from https://github.com/liferay-echo/liferay-portal/pull/10891

Motivation
=======
There is a bug that causes that a draft version of a page is publicated when saving an AB Test variant

Link to the story: [LPS-171060](https://issues.liferay.com/browse/LPS-171060)

Proposed Solution
========
The draft version to be the same as before the AB Test. 

For that we are going to : 

> Create a new action command to save the variant.
> Add a new success message when that variant is saved:   "The variant was saved successfully."

Steps to Verify:
----------------
1. Create a draft version of a page
2. Create an AB Test for that page
3. Create a variant > Edit the variant (notice that you'll see the draft version already)
4. Click 'Save Variant'

Screenshots:
----------------------

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Mikellorza** [comment]
Hey @liferay-echo ,

The rebase  [error](https://github.com/brianchandotcom/liferay-portal/pull/129011#issuecomment-1399763789) has been fixed.

**Comment by Mikellorza** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @Mikellorza 
The Echo Team has already approved this PR. 
Could you please do a manual forward to Brian's repo?
Thank you!

**Comment by Mikellorza** [comment]
Hi @lfbesada ,

Ok, I will send this PR to Brian manually.

Thanks a lot!!

**Comment by Mikellorza** [comment]
Hi @lfbesada ,

Ok, I will send this PR to Brian manually.

Thanks a lot!!

**Comment by Mikellorza** [comment]
Sent manually to brian : https://github.com/brianchandotcom/liferay-portal/pull/129158

**Comment by Mikellorza** [comment]
ci:close

**Pull request closed without merging**
