### PR TITLE
[TS] LPS-136518

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,
This is the followup of https://github.com/liferay-echo/liferay-portal/pull/5407
I've tried running relevant test locally, but most of the time the outcome was a general failure.
I did find that https://github.com/liferay-echo/liferay-portal/pull/5417/commits/642717142758d09bc20f1a1441b5e788b721c72e should have fixed some of the failures from my previous PR.

Can you please review?
https://issues.liferay.com/browse/LPS-136518

Thanks,
Balázs

### CODE REVIEW

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @balazssk 

Thanks for the PR, it looks great!

Only that, if the request is mandatory in the themeDisplay, you should ensure that it is present in all those who currently use the provider. That seems to be the cause of the failed integration tests, could you please check it?

It would also be great if you create an integration test to ensure the desired behavior remains.

Thanks a lot!

Regards

**Comment by balazssk** [comment]
Cheers @lfbesada , I'm looking into the test

**Pull request closed without merging**
