### PR TITLE
LPS-177303 Replace clay:navigation-bar with clay:tabs in site-memberships-web

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://issues.liferay.com/browse/LPS-177303)

## Steps 

1. Go to Control Menu > Control Panel > Users and organisations
2. Create 2 users and 2 organisations
3. Go to Product Menu > People > memberships 
4. Click on the info icon in both users and organisations sections
Screenshot 2023-05-12 at 11 45 24
Screenshot 2023-05-12 at 11 45 34
Screenshot 2023-05-12 at 11 45 53

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
