### PR TITLE
LPD-24489 Change expected behavior for LPS-165678

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-24489

LPS-165678 introduced the expected behavior that the URL of a site with no published pages but with a draft page would lead to this page even though it was not published. This task changes that behavior to lead to the first product menu entry for which it has permissions in that case.

In addition to the test modified in this PR, these changes are covered by the POSHI test PagesTree#PreviewDraftWhenContentPageAtDraftStatus test.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:report:37711479

**Comment by lfbesada** [comment]
ci:report:37711479

**Comment by lfbesada** [comment]
At least one test failure is related because, the test must be adapted

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:report:38333144

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
