### PR TITLE
LPS-193763 Add actions to created folders

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
=======
The new feature to display and edit object entries is producing that users have several display pages for the same object. This said, it will be very useful to provide a way to our users so they can organize them.

Proposed Solution
========
Allow users to create folders to organize them

Steps to Verify
========
1. Go to Design > Page Templates > Display Page templates
2. Create a folder
3. Verify that the actions are show when displaying the dropdown menu (rename, delete, permissions) and that work as expected

COMMITS:

- LPS-193763 Add return tab as a variable when retrieving dropdown item actions
- LPS-193763 Create method to retrieve dropdown item actions for DisplayPageTemplateCollectionHorizontalCards
- LPS-193763 Show dropdown item actions for DisplayPageTemplateCollectionHorizontalCards
- LPS-193763 Redirecting to the right tab after rename collection
- LPS-193763 Adding PropsTransformer
- LPS-193763 Modifying propsTransformer to work also with actions
- LPS-193763 Refactor modifying propsTransformer to work also with actions

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/139665

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
