### PR TITLE
LPS-168190 Disable refering articles selection for DDM Field

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

Motivation
=======
[LPS-168190](https://issues.liferay.com/browse/LPS-168190)
Having a Web Content refer itself could cause infinite recursion in ddm templates.

Proposed Solution
========
By forwarding the referring article's resourcePrimKey to the Item Selector, we can disable selectablility for the referer article
I'm unsure if any extra CSS to differentiate this referer article would be needed or what would be suitable for it.

Steps to Verify
========
1. Create a Web Content Structure with a Web Content field
2. Create a Web Content from this Structure and save it
3. Edit this Web Content and press Select for the Web Content field

**Expected behaviour:** The current Web Content should not be selectable to eliminate the change of infinite loops
**Actual behaviour:** The current Web Content is selectable

References to existing code (if applies)
========
A similar solution was used for Related Assets in https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-browser-web/src/main/java/com/liferay/asset/browser/web/internal/display/context/AssetBrowserDisplayContext.java#L327

Alternative Solutions that were discarded
========
I've discarded filtering the results in the 
- business logic layer: because of performance reasons and manipulating the results would make the result list less maintainable.
- service layer: While Search could be filtered with the correct search context having an exclusion term added, The DisplayContext uses multiple Service calls, that would need an extra parameter to work. I've opted to avoid creating new service methods.

Cheers,
Balázs

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :)

**Comment by ealonso** [comment]
Please see: https://github.com/liferay-echo/liferay-portal/pull/10317

**Comment by ealonso** [comment]
ci:stop

**Pull request closed without merging**
