### PR TITLE
[TS] LPS-186686

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-186686

Rebased from https://github.com/liferay-echo/liferay-portal/pull/12307 with new solution.

@ealonso, thank you for your comment on the last PR regarding difficult reproduction steps.  It made me re-evaluate how to reproduce, which led to shorted steps to reproduce as well as a fix in the correct location.  Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/136079

**Pull request closed without merging**
