### PR TITLE
LPS-186562 Delete content recommendation from portal

### PR DESCRIPTION
**Pull request by YurenaC**
Motivation
=======
Content recommendations were broken and unused so we proceed to delete them

Commits:
=======
- LPS-186862 Delete interestTerms in order to remove contentRecommendation
- LPS-186862 Delete processor in order to remove ContentRecommendation
- LPS-186862 Delete processor tests
- LPS-186862 Remove contentRecommendation related labels
- LPS-186562 buildLang
- LPS-186862 Remove assetListAssetEntryQueryProcessor usages

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:stable

**Comment by liulukiwi** [comment]
Failures are not related, pushed to BChan directly at https://github.com/brianchandotcom/liferay-portal/pull/136224

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
