### PR TITLE
[TS] LPS-149324 - Improve accessibility, remove headings and empty elements 

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
LPS-149324 Improve accessibility, remove headings and empty elements inside my sties portlet

For more details, please check https://issues.liferay.com/browse/LPS-149324

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
Hi @georgel-pop-lr! This looks good to me 🥰
Just a little thing, I've been taking a look and I think the `h5` and `h6` classes are not necessary. I guess you are adding them to adapt the style of the text but they are actually don't affecting it. What do you think?

**Comment by georgel-pop-lr** [comment]
> Hi @georgel-pop-lr! This looks good to me smiling_face_with_three_hearts Just a little thing, I've been taking a look and I think the `h5` and `h6` classes are not necessary. I guess you are adding them to adapt the style of the text but they are actually don't affecting it. What do you think?

Hi @sandrodw3,

You are right, I will remove them.

Regards.

**Comment by georgel-pop-lr** [comment]
> > Hi @georgel-pop-lr! This looks good to me smiling_face_with_three_hearts Just a little thing, I've been taking a look and I think the `h5` and `h6` classes are not necessary. I guess you are adding them to adapt the style of the text but they are actually don't affecting it. What do you think?
> 
> Hi @sandrodw3,
> 
> You are right, I will remove them.
> 
> Regards.

Hi @sandrodw3,

Changes done, please review.

**Comment by sandrodw3** [comment]
Thanks @georgel-pop-lr! I think it's good to go 🙂

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7529

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
