### PR TITLE
LPS-190007 Replace aui:button with clay:button in journal-content-web

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-190007)

## Steps

1. Go to Content & Data > Web Content > Create a Web Content and save 
2. Go to Site Builder > Pages > Create a Content Page
3. Add a Web Content Display widget 
4. Go to the widget configuration 
5. See select button
6. Select the WB created
7. See the change and remove button
8. Below, in template section > select Use a specific template
9. See Select and Clear button
Screenshot 2023-07-27 at 17 06 43

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by veroglez** [comment]
ci:forward

**Pull request closed without merging**
