### PR TITLE
LPS-131407 Add step to define the asset selection of Asset Publisher as dynamic

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7378

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
