### PR TITLE
LPS-204596 check latest non-expired article, to make assetentry visible

### PR DESCRIPTION
**Pull request by 4lejandrito**
Hi Team,

Could you please review this pull request?
https://liferay.atlassian.net/browse/LPS-204596
Thank you!

------

**Reproduction Steps:**

1. Add an Asset Publish to the Home page and configure Asset Selection to Dynamic
2. Create a Web Content: MyWC
3. Enable Local Staging
4. Assert that MyWC is visible in both Staging and Live
5. Edit MyWC again in order to to create a newer version of it
6. Go to Version history and expire version 1.0. Version 1.1 is still approved.
7. Go to Publishing > Staging and perform a new Publish Process

**Expected**
MyWC is still visible in the Home page in both Staging and Live

**Actual**
MyWC is not visible anymore in Live site

**Solution:**
As AssetEntry was updated on every version's iteration, I checked if there is any non-expired version, and updated the visible status.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
@GaborKomaromi, @4lejandrito, taking a look, but the issue should be somewhere else. I'm putting this on hold while I try to dig deeper

**Comment by vendeltoreki** [comment]
Hi @jkappler ,

We discussed this fix with @GaborKomaromi . The problem seems to be that the asset was always updated with each imported version, and if the last one updates the asset with the wrong isVisible value, it will not be shown.
With this fix, the order does not matter, the asset will always have the correct value. However, this also introduces an extra query, that can affect the performance.

Another solution I can think of is to sort the versions during the export phase. Although, I'm not sure whether that always will be correct.

**Comment by jkappler** [comment]
Hi @vendeltoreki, I understand, but assigning expirationDate for example might lead to inconsistencies in other scenarios.

**Comment by vendeltoreki** [comment]
@jkappler I agree, there are a lot of other scenarios we might not now about

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
@vendeltoreki @jkappler When I was reviewing this PR I detected errors when making many different versions changing the expiration date in each one or setting/unsetting never never-expire check.
The deletion or expiration of some versions caused changes to the expiration date of others.
I can't remember exactly the steps but I did find that error.
Therefore, from my point of view, this approach is not appropriate to solve this problem.
I hope this helps, regards

**Comment by vendeltoreki** [comment]
Thanks @lfbesada for checking, @jkappler has already started working on a different approach. I'm looking into that as well.

**Comment by jkappler** [comment]
This would be the other approach that @vendeltoreki mentioned. https://github.com/jkappler/liferay-portal/pull/1150. From what I see no direct errors are thrown, but it will do a complete test, just in case

**Comment by jkappler** [comment]
Thanks @lfbesada for also checking it out ❤️

**Comment by jkappler** [comment]
Talking to @4lejandrito, the change in the ChangeSetDataHandler wouldn't be the correct one, so that option is out of the table

**Pull request closed without merging**
