### PR TITLE
LPS-125160 - The styles of fragments are missing in edit mode after upgrade

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @pavel-savinov @victorg1991 @Tim-Cao

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
Hi @Tim-Cao.

In the context of fixing this bug we have tried doing some simplifications on the code, by moving them to the upgrade process.

¿Would you mind doing some sanity testing around styles with this PR before we submit it to Brian?

We are not sure whether these [changes](https://github.com/liferay-echo/liferay-portal/pull/3359/commits/ef75650f8ecb6ff6caecccf97639a0ece4289842) may have unwanted effects that we are not able to think of at the moment.

¡Thanks!

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ruben-pulido, the textAlign are missing on both edit mode and view mode with your fix. Could you have a look at?

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by ruben-pulido** [comment]
Thanks a lot for reviewing the test results @Tim-Cao! I'll look into the issue with textAlign

**Comment by ruben-pulido** [comment]
https://github.com/liferay-echo/liferay-portal/pull/3372

**Pull request closed without merging**
