### PR TITLE
LPD-17762 Allow freemarker variables to use - symbol for layoutpagetemplateentrykey

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
Same as https://github.com/liferay/liferay-portal/commit/4140e7c386f40547f0d0ef9e3c97f4f58811849d

The unique key is being created here: https://github.com/liferay/liferay-portal/blob/5af8b3db3d61285e86371cdd942fcbbfc3b9d105/modules/apps/layout/layout-page-template-service/src/main/java/com/liferay/layout/page/template/internal/info/item/provider/DisplayPageInfoItemFieldSetProviderImpl.java#L128

When a client is using space in Display page template name, this is being replaced with - symbol, this creates problems as is being used as operator minus.

I added others symbols to be blacklisted as they could create the same issues.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:report:2538449000

**Comment by ealonso** [comment]
Hey @georgel-pop-lr,

There are some failures that seems to be related with your changes. Could you please take a look?

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by georgel-pop-lr** [comment]
> Hey @georgel-pop-lr,
> 
> There are some failures that seems to be related with your changes. Could you please take a look?

The problem is that I blacklisted parenthesis, and we add them in the name when we create a copy, we added them in this commit https://github.com/liferay/liferay-portal/commit/0422e0d4837d157f479fba2b53a12a573c773591

In the end I needed to use the ID instead of key as this contains only numbers and is never changing, this will fix both cases, this one and LPD-17765

The only issue is that the client would need to redo his mappings and the templates, but if they changed names this will happen anyway.

Let me know your thoughts on this.

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
