### PR TITLE
[TS] LPS-152888 - Incorrect redirect on asset publisher in specific scenarios

### PR DESCRIPTION
**Pull request by wanderlast**
Hi @liferay-echo!

Previous pull: https://github.com/liferay-echo/liferay-portal/pull/8640

I'm forwarding this pull from @dacousalr to address [LPS-152888](https://issues.liferay.com/browse/LPS-152888). It addresses a specific case where the redirect on an asset publisher can become incorrect/unusable due to using a secondary asset publisher on the same page as a navigational method.

See [PTR-3197](https://issues.liferay.com/browse/PTR-3197) for further context.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by wanderlast** [comment]
ci:test:sf

**Comment by wanderlast** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1307401_3863

**Comment by lfbesada** [comment]
Hi @wanderlast 
Thanks for the fix!
The AssetListAssetEntryProviderTest.testCombineSegmentsOfDynamicCollection test failure seems to be related to this pull request changes.
Could you please review it?
Thanks!
Regards

**Comment by dacousalr** [comment]
Hi @lfbesada,

I have taken a quick look at the code of the test failure, but I cannot establish any link between the changes of this PR located at the Asset Publisher's view/controller level and the classes operated by the integration test located at the Asset/AssetList service level where no Asset Publisher widget is involved.

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
LGTM! @wanderlast @dacousalr Thanks for the fix! Regards

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
