### PR TITLE
LPS-192983 Make sure that we override the previousConfig, since when we select block option it removes the key from the config

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Hi @victorg1991 , one[ js unit test failed](https://testray.liferay.com/home/-/testray/case_results/2403478624), can you take a look? thanks!

```
     [exec] FAIL test/page_editor/app/thunks/updateItemConfig.test.js
     [exec]   ??? updateItemConfig ??? dispatches updateItemConfig and updatePageContents actions
     [exec] 
     [exec]     expect(jest.fn()).toHaveBeenCalledWith(...expected)
     [exec] 
     [exec]     - Expected
     [exec]     + Received
     [exec] 
     [exec]     @@ -2,10 +2,11 @@
     [exec]         "itemId": "0",
     [exec]         "layoutData": Object {
     [exec]           "items": Object {},
     [exec]           "version": 1,
     [exec]         },
     [exec]     +   "overridePreviousConfig": false,
     [exec]         "pageContents": Array [
     [exec]           Object {
     [exec]             "classPK": "pk",
     [exec]             "name": "contents",
     [exec]             "title": "title",,
     [exec] 
     [exec]     Number of calls: 1
     [exec] 
     [exec]       63 | 		await runThunk();
     [exec]       64 | 
     [exec]     > 65 | 		expect(updateItemConfigAction).toHaveBeenCalledWith({
     [exec]          | 		                               ^
     [exec]       66 | 			itemId: '0',
     [exec]       67 | 			layoutData: {
     [exec]       68 | 				items: {},
     [exec] 
     [exec]       at Object.<anonymous> (test/page_editor/app/thunks/updateItemConfig.test.js:65:34)
     [exec]       at processTicksAndRejections (node:internal/process/task_queues:96:5)
     [exec] 
```

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
