### PR TITLE
LRQA-66445 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRQA-66445

This is only for master.

@david-gutierrez-mesa
@kenjiheigel

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
Hi @kenjiheigel
The failure cases are not related to changes in PR.
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1523925181
It seems like the document.readyState solution works.

**Comment by Tim-Cao** [comment]
ci:test:echo:nocompile

**Comment by Tim-Cao** [comment]
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1523953662
The same as previous results

**Comment by kenjiheigel** [comment]
ci:test:echo:nocompile

**Comment by Tim-Cao** [comment]
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1523953662
No new issues found.

**Comment by Tim-Cao** [comment]
Resent and retest without the last commit and add an additional commit
See https://github.com/liferay-echo/liferay-portal/pull/4187

**Comment by kenjiheigel** [comment]
@Tim-Cao, could you make these changes: 
* Rename to `waitForPageLoad` 

Additionally, could you change this from a macro to a function? Try to follow something similar to this: 
https://github.com/liferay/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/functions/WaitForLiferayEvent.function#L83-L100. 

Your javascript snippet will need to resolve to a boolean. I think you should use the `waitForJavaScriptNoError` + the `verifyJavaScript` methods, because it shouldn't necessarily fail out if the javascript snippet isn't valid.

Here's some additional documentation: 
https://qa-compendium.readthedocs.io/en/latest/poshi/javascript-functions.html#wait-for-a-javascript-condition-to-be-met-no-exceptions-will-be-thrown

This is advantageous because: 
* It will let javascript handle the condition, let the Poshi method handle the waiting
* The log will reflect when the condition is not true (highlighted yellow as a verification warning)

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/4189

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
