### PR TITLE
LPS-163433 Unnecessary calls to JournalArticle.getContent, when we really need DDMFormValues objects

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-163433

In [LPS-129058](https://issues.liferay.com/browse/LPS-129058) the JournalArticle xml was extracted to the DDM* database tables.

After that LPS changes, the JournalArticle.getContent now calls the DDM API to get the DDMFormValues object and generate the XML, see:
https://github.com/liferay/liferay-portal/blob/master/modules/apps/journal/journal-service/src/main/java/com/liferay/journal/model/impl/JournalArticleImpl.java#L226-L254

But we have several calls to JournalArticle.getContent that parses the content XML to generate the DDMFormValues so in the end we are doing unnecessary transformations:

- getContent: gets the DDMFormValues => Fields => and generates the XML calling journalConverter.getContent
- the method that calls getContent, needs the DDMFormValues or the Fields, so it parses the XML to generate them

A direct call to DDMFieldLocalServiceUtil.getDDMFormValues(ddmStructure.getDDMForm(), getId()); will avoid the unnecessary transformations to XML and back to DDMFormValues

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
@jorgediaz-lr this is awesome!!!

**Comment by jorgediaz-lr** [comment]
image

**Comment by jorgediaz-lr** [comment]
borat

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @jorgediaz-lr,

I think the test failures are related with your changes, Could you please take a look?

Thanks

**Comment by jorgediaz-lr** [comment]
Hi @ealonso 

I have solved a problem related to [LocalFile.TranslationsApplication#CanTranslateWCAfterEditingStructure](https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/208985//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_TranslationsApplication_CanTranslateWCAfterEditingStructure_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-09/test-1-26/test-portal-acceptance-pullrequest(master)/5062/functional-tomcat90-mysql57-jdk8/1/13/LocalFile.TranslationsApplication_CanTranslateWCAfterEditingStructure/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-09/test-1-26/test-portal-acceptance-pullrequest(master)/5062/functional-tomcat90-mysql57-jdk8/1/13/LocalFile.TranslationsApplication_CanTranslateWCAfterEditingStructure/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-09/test-1-26/test-portal-acceptance-pullrequest(master)/5062/functional-tomcat90-mysql57-jdk8/1/13/jenkins-console.txt.gz) test error.

About LocalFile.TranslationsWCExportImport errors, I am trying to reproduce them in local but I am not able to do it, I will try executing the poshi test locally.

I will send a new PR.

**Comment by jorgediaz-lr** [comment]
Hi @ealonso 

I have sent a new PR, see https://github.com/liferay-echo/liferay-portal/pull/9725

**Pull request closed without merging**
