### PR TITLE
LPS-147083 Migrate Feeds Type To Asset Categories

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-147083

Previous PR: https://github.com/liferay-echo/liferay-portal/pull/11095

cc: @georgel-pop-lr @achaparro

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
@achaparro as you mentioned [here](https://github.com/liferay-echo/liferay-portal/pull/11095#issuecomment-1434635727) this PR should be reviewed by the @liferay-uniform Team. Do you prefer to review it in this repo or I should resend this pull request to your repo after our review?
Thanks
Regards

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by achaparro** [comment]
Hi @lfbesada, @georgel-pop-lr,

I took a look at the upgrade changes (database and schema version changes, not the logic itself since that's more up to you) and we need to make a change.

Drop a column is a major schema change (see [this](https://liferay.atlassian.net/wiki/spaces/ENGCOREUPGRADE/pages/1654719711/Upgrade+Development+Training#Major-changes)). For that reason, we should create an additional major upgrade process just for dropping the column (use the inline method from _UpgradeProcessFactory_). We don't need to backport this major upgrade process so it will be present in master only. This is safer because, in case there is a bug in the migration upgrade process, we will still have the column type as data backup.

Let me know what you think.

Thank you.

cc/ I will review why the SF rule that detects major changes did not work in this case.

**Comment by lfbesada** [comment]
Hi @achaparro 
Thank you very much for the review and the tip! ❤️ 
I've added the last commit to implement that change.
Thank you!

cc: @georgel-pop-lr

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
😍

**Pull request closed without merging**
