### PR TITLE
LPS-122862 Read config from the theme not using the hard-code

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-122862

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
Hey @holatuwol,

Could you please send this one to Staging Team?, since they are the owners of site templates.

Thanks!
Eudaldo

**Comment by holatuwol** [comment]
https://github.com/vendeltoreki/liferay-portal/pull/139

**Pull request closed without merging**
