### PR TITLE
LPS-190735 Exclude props with default value from export

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-190735)

Motivation
=======
When exporting pages, there are some default or empty props that are stored the json created when exporting the page. We want to avoid those default props to be exported.

**NOTE: I will include two screenshots, at left the screenshot without the default props and at right the screenshot with the props configured and exported well.**

## Steps
- Go to Design > Page Templates > Page Templates > Create a Content Page Template 

**Case 1: Container**
  - Add a Container to a content page template
  - Select the Container and see Container configurations at right side 
  - In general tab > Container Width > Fixed
  - In Styles tab configure the opacity to 99 and the following properties to 1px:
  - "borderWidth",
     "marginBottom",
     "marginLeft",
     "marginRight",
     "marginTop",
     "paddingBottom",
     "paddingLeft",
     "paddingRight",
     "paddingTop",
containerWithoutDefaultProps1
containerWithPropsConfigured1

**Case 3: Form**
  - Go to Control Menu > Control Panel > Objects
  - Create a new Object 
  - View the new Object 
  - Go to fields > add a new field
  - Publish the Object
  - Add a Form Container to a content page template 
  - Map the container to the form created
  - Go to Form Container configuration 
  - In general tab > Container Width > Fixed
  
formWithoutDefault
formConfigured

@DiegoHu97

### CODE REVIEW

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
thanks @DiegoHu97!

**Comment by Tim-Cao** [comment]
Hi @DiegoHu97, could you have a look at the failed integration test?
[com.liferay.layout.page.template.admin.web.internal.portlet.action.test.ImportExportLayoutPageTemplateEntriesTest](https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/518419/testReport/com.liferay.layout.page.template.admin.web.internal.portlet.action.test/ImportExportLayoutPageTemplateEntriesTest)

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
@jkappler Sorry 😢 , hope this time is everything ok.

**Comment by jkappler** [comment]
It's okay @DiegoHu97, thanks for your hard work ❤️!

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@DiegoHu97, seems com.liferay.layout.page.template.admin.web.internal.portlet.action.test.ImportExportLayoutPageTemplateEntriesTest is failing, unsure if it's from your changes

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by DiegoHu97** [comment]
@jkappler Updated! 😄

**Comment by jkappler** [comment]
Awesome @DiegoHu97, lets see if this is the final one! 🤞

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/138972

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
