### PR TITLE
LPS-127205 [Experiences] Scroll to the new experience is not happening

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

When opening the experiences dropdown, if the user has more that 4 experiences created, and it has selected one of the end of the list, the list does not scroll to the active one.

**Solution**

- Scroll without animation to the active one on dropdown open
- Don't scroll if the user change selects another experience from the list
- Scroll with animation if the user duplicates an experience (`useEffect` listening to `experiences.length`)

Also, I remove the unnecessary duplicate action and split the `action.payload` data in the reducers call to add the specific parameters.

**Screenshot**

https://user-images.githubusercontent.com/15845466/108515274-2e8c4300-72c5-11eb-9e9a-871f9e841f6b.mov

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Hey @liferay-echo, can you give me feedback? @p2kmgcl was helping my with these changes :) Thanks!

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
I'm going to rebase with latest master changes and run the CI again 😄

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:forward

**Pull request closed without merging**
