### PR TITLE
LPS-143762 Wrap custom collection renderer inside a container

### PR DESCRIPTION
**Pull request by p2kmgcl**
As a solution, I have wrapped all collections with a container with overflow-hidden and no padding

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl , No regression issues found according to [ci:test:echo](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1594490200&testrayRunId=1594494373)

**Review by lfbesada — APPROVED** [review]

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
