### PR TITLE
LPS-152572 Checks if the user exist or not, to avoid NoSuchUserException if the user that creates the LayoutPageTemplateStructure doesn't exist

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
@ealonso merged to temp branch too, see 0bf07e15320b124590d9097d0da99e4b12444fb0

**Pull request closed without merging**
