### PR TITLE
LPS-127327 Include ancestor templates

### PR DESCRIPTION
**Pull request by ealonso**
forward

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:reevaluate:1107401_4514

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
