### PR TITLE
 [TS] LPS-149390 - Shared url on social bookmarks has long params

### PR DESCRIPTION
**Pull request by georgel-pop-lr**
LPS-149390 Shared url on social bookmarks on an asset with no display page has long params, caused by LPS-145876

When using _urlImpl we cut the params using this method https://github.com/liferay/liferay-portal/blob/592af9d2d922f428016b391a35ff5adfa7fc2a02/modules/apps/social/social-bookmarks-taglib/src/main/java/com/liferay/social/bookmarks/taglib/servlet/taglib/SocialBookmarksTag.java#L204 with includeQueryString = false

### CODE REVIEW

**Comment by georgel-pop-lr** [comment]
ci:test:sf

**Comment by georgel-pop-lr** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @georgel-pop-lr,

Could be possible to use the same method that we where using in SocialBookmarksTag in the generation of social URL?

Regards,
Eudaldo

**Comment by ealonso** [comment]
Hey @georgel-pop-lr,

Could be possible to use the same method that we where using in SocialBookmarksTag in the generation of social URL?

Regards,
Eudaldo

**Comment by georgel-pop-lr** [comment]
> Hey @georgel-pop-lr,
> 
> Could be possible to use the same method that we are using in SocialBookmarksTag in the generation of social URL?
> 
> Regards, Eudaldo

Hi @ealonso,

I checked, but we can't apply the same method to all the URL, for example when there is a friendly URL the method `PortalUtil.getCanonicalURL` adds the layout page in the URL and that breaks it:

Friendly URL: http://localhost:8080/w/web-content-1-es-

Gets transformed to: http://localhost:8080/es/7/w/web-content-1-es- 

And doesn't work:

image

This works only with internal URL like http://localhost:8080/es/7/-/asset_publisher/EHzmpENo98X8/content/web-content-1-es-

But then we need to check if it is a friendly URL or not, and I don't know if that is something we want, as it will increase code complexity and decrease performance.

Let me know your toughts.

Regards.

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/7560

**Comment by ealonso** [comment]
Please see my latest changes in https://github.com/liferay-echo/liferay-portal/pull/7560

**Pull request closed without merging**
