### PR TITLE
LPS-135165 Add redirect to make sure that we always redirect to the same url

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @victorg1991, Perfect fix. Thanks

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
