### PR TITLE
LPS-197423 Migrate more reducers to TypeScript

### PR DESCRIPTION
**Pull request by p2kmgcl**
I have migrated some reducers to TypeScript and finally reached the LayoutData structure, so I added some configuration types. It is not complete but at least give us some structure definition we can continue working on.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
❤️

**Comment by p2kmgcl** [comment]
Thanks :D

conflicts solved!

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
It looks like everything is working... just rebased onto master

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Hey @p2kmgcl, a regression found ([comparison with acceptance routine here](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1696427042784&testrayRunIdA=2435187856&testrayRunIdB=2436136319)). Steps to repdroduce:

1. Add a Content Page
2. Go to Fragments and Widgets panel
3. Try searching for a widget (e.g. Asset Publisher)

Expected result:
Widget is found and can be used
image


Actual result:
The widget is not found and the widget list is not loaded completely
image

**Comment by p2kmgcl** [comment]
:thinking: thanks @alessandromalves! I'll have a look

**Comment by p2kmgcl** [comment]
Alright this looks better. @alessandromalves do you think it might be related too?

**Comment by alessandromalves** [comment]
@p2kmgcl, the failures are related to this PR. Here are the steps for reproduction: 

1. Add a company Object with any field
2. Add a Content Page
3. Add a Form Container framgment to content page
4. Map the Form Container to new Object

Expected result:
The field related to the created object will appear instantly

https://github.com/liferay-echo/liferay-portal/assets/69062082/fd48c2c7-a7d2-4910-9c3a-23d8e4486623


Actual result:
the field related to the created object will not appear instantly, and will only appear after the page is reloaded.

https://github.com/liferay-echo/liferay-portal/assets/69062082/fcde16b4-9a14-4837-a504-46756ad5d5fd

**Comment by p2kmgcl** [comment]
Thanks so much :smile: 
Fixed!

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by alessandromalves** [comment]
The failures are not related to this PR [(comparison with acceptance routine here)](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1696609144779&testrayRunIdA=2436651261&testrayRunIdB=2437612556). See https://github.com/brianchandotcom/liferay-portal/pull/141895

**Comment by alessandromalves** [comment]
ci:close

**Pull request closed without merging**
