### PR TITLE
LPS-128329 Apply in journal

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Review by ealonso — APPROVED** [review]

**Comment by balazssk** [comment]
Hi @jkappler and Echo Team,
Thank you very much for this solution!
I'd like to add https://github.com/jkappler/liferay-portal/pull/961 to this fix if possible.

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
@balazssk, will add your commit and update this pull, thanks for the heads up

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
Resent here: https://github.com/liferay-echo/liferay-portal/pull/4066

**Pull request closed without merging**
