### PR TITLE
LPS-122451 Apply the same approach

### PR DESCRIPTION
**Pull request by pavel-savinov**

### CODE REVIEW

**Comment by pavel-savinov** [comment]
ci:test:sf

**Comment by pavel-savinov** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
@antonio-ortega please check if https://github.com/liferay-echo/liferay-portal/pull/2702/commits/690c695e5042eb07c7903365483d6998817acac4 makes sense. And if it does, feel free to forward.

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
