### PR TITLE
Icons update inside "Properties" menu in segment creation

### PR DESCRIPTION
**Pull request by YurenaC**
[Story](https://liferay.atlassian.net/browse/LPS-188046)

[Here](https://clayui.com/docs/components/icon.html) you can find all the clay icons 

*COMMITS*
----------------
- LPS-188046 Remove enabled=false in order to be able to show custom fields
- LPS-188046 Add new icon field to Field
- LPS-188046 Using customizers to define custom icons as requested
- LPS-188046 Display icon when it's available
- LPS-188046 Modifiying Field's creation with customized icon when necesary

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/12768

**Pull request closed without merging**
