### PR TITLE
LPS-131264 Prefix not exported .scss files with _ in layout-admin-web

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reevaluate:1187401_5750

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/4382

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
