### PR TITLE
LPS-113869 Site Pages Variation doesn't change when navigating to staging page

### PR DESCRIPTION
**Pull request by moltam89**
Hi guys,

This is a small fix to store the selected site pages variation when we're navigating on the Site Builder section.

Best,
Tamas

### CODE REVIEW

**Comment by moltam89** [comment]
ci:test:sf

**Comment by moltam89** [comment]
ci:test:relevant

**Comment by moltam89** [comment]
ci:test:stable

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
