### PR TITLE
LPS-125615 - The background color of Content Page section builder layouts does not remain the full width of the screen after upgrading

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @achaparro @kevhlee @SamZiemer

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:reevaluate:1152004_3838

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:forward

**Pull request closed without merging**
