### PR TITLE
LPS-151464 Check if the page exists with the urlWithoutLocale in more cases (not only if the URL only has 1 slash)

### PR DESCRIPTION
**Pull request by vendeltoreki**
Hi @liferay-echo ,

I'm forwarding the https://github.com/liferay-staging/liferay-portal/pull/51 pull request to you. I've added some integration test cases to verify the scenario.

Please review the changes.

cc: @robertoDiaz

Thanks,
Vendel

### CODE REVIEW

**Comment by robertoDiaz** [comment]
@vendeltoreki  Thank you so much for your help (and fix the typo in the if clause)

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:reevaluate:1367401_975

**Comment by lfbesada** [comment]
ci:test:relevant

**Review by lfbesada — APPROVED** [review]
Hi @vendeltoreki @robertoDiaz 
Thanks for the fix! It works great! 😍 
Regards

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
