### PR TITLE
LPS-160268 Change wording and error message in Master pages

### PR DESCRIPTION
**Pull request by jkappler**
This PR removes the heading "Drop Zone" from the drop zone of a master page, and also gives a friendly error to the user when trying to add fragments or widgets to it, instead of the "An unexpected error has occurred" error

error-dropzone

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@Tim-Cao, unsure if we would need poshi changes here... so I'mm cc'ing you in advance :D

**Comment by Tim-Cao** [comment]
Hi @jkappler, I don't think this change affect our existing cases. Thanks for your reminding.

**Comment by sandrodw3** [comment]
Hey @jkappler 🥰 this looks super good to me, I'm forwarding it. Only wanted to remind that in the topper and the sidebar we are still calling this item "Drop Zone" and showing it in the master page. Maybe we should let our designers know it just in case they want to change that name also.

**Comment by sandrodw3** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/121781

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
