### PR TITLE
LPS-195029

### PR DESCRIPTION
**Pull request by ealonso**
On hold until we finish both epics.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, the failures are need to review by BPM team QA. I've asked here
https://liferay.slack.com/archives/C026NQPV6TV/p1694737384920939

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ealonso, would you mind resending this pr to object team? The failed tests belongs to object.

**Comment by ealonso** [comment]
see: https://github.com/liferay-objects/liferay-portal/pull/2579

**Pull request closed without merging**
