### PR TITLE
LPS-204257 Removes view count reference for asset service

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, could you check this failed test?
[com.liferay.document.library.webdav.test.WebDAVOSXTest](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/994084/testReport/com.liferay.document.library.webdav.test/WebDAVOSXTest) - [Failed 0 of last 25](https://testray.liferay.com/home/-/testray/case_results/2485886626/history)
[testMSOffice3Modify](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/994084//testReport/com.liferay.document.library.webdav.test/WebDAVOSXTest/testMSOffice3Modify)

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/146173

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
