### PR TITLE
LPS-191367 Integration tests for LPS-182022

### PR DESCRIPTION
**Pull request by jkappler**
https://liferay.atlassian.net/browse/LPS-191367

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by rafaellajordao** [comment]
The failures are not related to this PR [(comparison with acceptance routine here)](https://testray.liferay.com/home/-/testray/runs/compare?testrayRunIdB=2420185341&testrayRunIdA=2420994318&view=teams). See https://github.com/brianchandotcom/liferay-portal/pull/140481

**Comment by rafaellajordao** [comment]
ci:close

**Comment by rafaellajordao** [comment]
ci:reopen

**Comment by rafaellajordao** [comment]
Hi @jkappler! Can you check this comment from Brian?

https://github.com/brianchandotcom/liferay-portal/pull/140481#issuecomment-1711905473

**Pull request closed without merging**
