### PR TITLE
LPS-152257 Adapt import so it does not fail when a widget is not available

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to ticket](https://issues.liferay.com/browse/LPS-152257)

When a page definition contains a widget that does not exist, the import fails, not as with fragments where they are ignored. So this PR deals with it, standardizing the cases

## Change summary:

- Instead of throwing an exception, ignore widgets that don't exist
- Adds test

## Test Scenario (ideal case)

- Deploy a widget to a portal instance
- Create a new page template and add the widget to the page
- Export the page template
- Delete the page template
- Undleploy the widget
- Import the page page
- It should succeed

## Test Scenario (medium case)

- Create a new page template and add any widget to the page
- Export the page template
- Delete the page template
- Blacklist the widget
- Import the page page
- It should succeed

## Test Scenario (non optimal case)

- Just run the integration test

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Review by lfbesada — APPROVED** [review]
Awesome 😍 as always ❤️

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
