### PR TITLE
[TS] LPS-117050

### PR DESCRIPTION
**Pull request by ChrisKian**
[**LPS-117050**](https://issues.liferay.com/browse/LPS-117050)

From @jesseyeh-liferay 

> This solution accounts for an edge case in which a trailing slash in a URL to a `JournalArticle` results in a `NoSuchLayoutException`, which in turn yields a "requested resource could not be found error."

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Hi @ChrisKian, @jesseyeh-liferay, could you please send this to the core infr Team? Since it's related to FriendlyURLServlet it would be better if they review it.

Thanks!

**Comment by jkappler** [comment]
ci:close

**Comment by ChrisKian** [comment]
forwarded to https://github.com/shuyangzhou/liferay-portal/pull/9263

**Pull request closed without merging**
