### PR TITLE
LPS-147833 Add Integration Test

### PR DESCRIPTION
**Pull request by holatuwol**
https://issues.liferay.com/browse/LPS-147833

Requested here https://github.com/brianchandotcom/liferay-portal/pull/114523#issuecomment-1065084995

Previous pull request failed due to updating source formatting failures without checking to see if the changes recompiled.

### CODE REVIEW

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
please see: https://github.com/liferay-echo/liferay-portal/pull/7612

**Pull request closed without merging**
