### PR TITLE
LPS-171455 Display Page Preview does not display changes

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
Draft versions of Web Contents can't accurately be displayed in Display Page Template Previews if an approved version exists.
[LPS-171455](https://issues.liferay.com/browse/LPS-171455)

Proposed Solution
========
Adding NOT to the isNull check will make sure the version is forwarded if it exists.

Steps to Verify
========
1. Create a Display Page Template for Web Content > Basic Web Content
2. Add a Display Page Content fragment to it and Publish
3. Create an Asset Library
4. Add a Web Content to the Asset Library and Publish it
5. Edit the Web Content; add "draft version" to its content field, but **do not** Publish
6. Select the Display Page Template under Display Page Preview
7. Press Preview

**Expected behaviour:** "draft version" **is** displayed in the Display Page Content fragment
**Actual behaviour:** "draft version" **is not** displayed in the Display Page Content fragment

Thanks,
Balázs

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reevaluate:1327401_7502

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Failures are not related, pushed to BChan directly at https://github.com/brianchandotcom/liferay-portal/pull/127967

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
