### PR TITLE
Accessibility: LPS-183087 Allow user to remove toast when ready

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-183087

The toast should remain open until a user decides to close it, interact with it, or go to a different page. 
This is for accessibility purposes for users that use Screen Readers or have disabilities that makes it difficult to react to the toast.
https://www.w3.org/TR/UNDERSTANDING-WCAG20/time-limits-no-exceptions.html

If there are any questions or comments please let me know.
Thank you!

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
Hey @fortunatomaldonado 

I believe this is not the correct solution since it changes the behaviour and it is very annoying to have to close the alert manually every time. Every other alert in the portal is automatically closed.

I think the correct approach would be to control manually if the focus is within the alert, and doesn't hide it in that case

Could you give it a try?

Thanks!

**Comment by fortunatomaldonado** [comment]
Hello @victorg1991,

Thank you for taking a look at this and the clarification.
Unfortunately, I cannot take a look at this further at this time and will be closing this pull.

Thank you again!

**Pull request closed without merging**
