### PR TITLE
LPS-129860 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-129860

This is only for master.

@ealonso

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, It shouldn't redirect to Site Settings admin after save Site Configuration.
Step to reproduce:
1. Add a new site
2. Click the Site Configuration
3. Click the Save

Expected Results:
It should stay in Site Configuration

Actual Results:
It redirects to Site Settings.

1. Add a new site
2. Click the Site Configuration
3. Expand the Site URL section
4. Type /alpha/alpha/alpha in Friendly URL field
5. Click the Save

Expected Results:
It should stay in Site Configuration. The following message should shown below Friendly URL field.  **The friendly URL has too many slashes.**

Actual Results:
It redirects to Site Settings.

**Comment by Tim-Cao** [comment]
The nav items are not migrated completely to vertical navbar yet. Both horizontal and vertical navbar co-exist.
NavBar

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
https://github.com/liferay-echo/liferay-portal/pull/4352

**Pull request closed without merging**
