### PR TITLE
LPS-154527 Apply changes

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:test:bundle

**Comment by liulukiwi** [comment]
Hi @ealonso , 4 issues found in automation tests, I put them [here ](https://issues.liferay.com/browse/LPS-154527?focusedCommentId=2690398&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2690398) in the JIRA, could you take a look? Thanks!

**Comment by ealonso** [comment]
Thanks you very much @liulukiwi it's helps my a lot.

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
