### PR TITLE
LPS-178527

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
Hey @ealonso, I found a single failure related to [com.liferay.fragment.contributor.test.FragmentCollectionContributorTest](https://testray.liferay.com/home/-/testray/case_results/2234788404), could you take a look at it?

[Full log here](https://testray.liferay.com/reports/production/logs/2023-03/test-1-34/test-portal-acceptance-pullrequest(master)/3745/modules-integration-mysql57-jdk8/0/1/jenkins-console.txt.gz?authuser=0)
```com.liferay.fragment.contributor.test.FragmentCollectionContributorTest > testRegisterFragmentCollectionContributor FAILED
     [exec]     java.lang.AssertionError: Thread Thread[Framework Event Dispatcher: Equinox Container: 846e5214-5613-44fc-b90f-dc8bd3f9918e,5,main] caught concurrent failure: java.lang.AssertionError: {level=ERROR, loggerName=osgi.logging.Events.Framework, message=FrameworkEvent ERROR
     [exec]     java.lang.AssertionError: {level=ERROR, loggerName=osgi.logging.Events.Framework, message=FrameworkEvent ERROR
     [exec]     	at com.liferay.portal.test.rule.LogAssertionTestRule$LogAppender.append(LogAssertionTestRule.java:330)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:161)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
     [exec]     	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
     [exec]     	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:542)
     [exec]     	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:500)
     [exec]     	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:483)

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/11450

**Pull request closed without merging**
