### PR TITLE
LPS-129403 Replace also new placeholder

### PR DESCRIPTION
**Pull request by p2kmgcl**
https://github.com/liferay/generator-liferay-fragments/commit/737e32d075e19ca5f2b1be0e9e0028106f077428

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by p2kmgcl** [comment]
I believe in you, CI. You can do it :muscle:

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
