### PR TITLE
LPS-201522 Prevent from changing the content type when the user hasn't permission to VIEW the current content type

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-201522

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
cc: @sandrodw3 :heart:

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
@jkappler Thanks for the review :heart: I have added changes according to your feedback. Thanks a lot!

**Comment by lfbesada** [comment]
ci:forward

**Pull request closed without merging**
