### PR TITLE
LPS-132890 Not needed

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:stop

**Comment by Tim-Cao** [comment]
The failure task is a semantic versioning in portal-impl unrelated to the changes in PR. Due to saving CI resource, I've sent this PR to BChan directly.
 See https://github.com/brianchandotcom/liferay-portal/pull/102408

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
