### PR TITLE
LPS-202358 Replace AUI() usages in iframe-web

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-202358)

## Steps

- Add an Iframe widget to a Content Page
- Go to the Page in view mode 
- Go to the widget configuration and add a source url (it might be a local source)
- Notice the view of the iframe changes

https://github.com/liferay-echo/liferay-portal/assets/91208451/b2631263-c5c2-437f-b459-85e6b7c254ab

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
Cool! @DiegoHu97 just a question, could we replace `<script:aui>` with `<script>`?

**Comment by DiegoHu97** [comment]
@veroglez Updated! Thanks 😄

**Comment by veroglez** [comment]
ci:forward

**Comment by DiegoHu97** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
