### PR TITLE
LPD-16349 - After re-publishing the Site Template Page with search option portlet the propagation breaks the search option portlet on the Site

### PR DESCRIPTION
**Pull request by ruben-pulido**
https://liferay.atlassian.net/browse/LPD-16349 - After re-publishing the Site Template Page with search option portlet the propagation breaks the search option portlet on the Site

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:test:echo

**Comment by ruben-pulido** [comment]
ci:report:2535574643

**Comment by ruben-pulido** [comment]
[Testray CSV](https://test-1-5.liferay.com/userContent/jobs/generate-testray-csv/builds/7/testray-results.csv) file shows no unique failures

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
