### PR TITLE
LPS-184710 | Set new message board email template as default

### PR DESCRIPTION
**Pull request by jaimelr10**
**Description**: We want to provide the user the capability to make the template created on [LPS-183496](https://issues.liferay.com/browse/LPS-183496) the default one.

For this, the following propertie should be added to the `portal-ext.properties` file:
`message.boards.email.message.added.body=${resource:com/liferay/portlet/messageboards/dependencies/email_message_added_body_LPS-182020.tmpl}
`

**Jira Ticket**: https://issues.liferay.com/browse/LPS-184710

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by victorg1991** [comment]
Niiice job @jaimelr10 👏

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward:force

**Pull request closed without merging**
