### PR TITLE
LPD-4585 Allow configuring only the HTML Title and the HTML Description in case Utility Page

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPD-4585

cc: @sandrodw3 Thanks :heart:

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by p2kmgcl — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:reevaluate:1327401_3483

**Comment by lfbesada** [comment]
ci:report:2529730071

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
