### PR TITLE
LPS-168149 Add groupTitleTag param

### PR DESCRIPTION
**Pull request by sandrodw3**
Copying @ambrinchaudhary as https://github.com/liferay-echo/liferay-portal/pull/10941/commits/364dc2d94d40c73f8ea889d83eed612c23f4a351 needs to be reviewed by Lima team 😄

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by ealonso** [comment]
Hey @sandrodw3,
Could you please explain me the problem in this case a little bit more? Why we need to set different tags (span, h4, h2) in different places? Is the usage different? if the answer is yes Why?

**Comment by sandrodw3** [comment]
> Hey @sandrodw3, Could you please explain me the problem in this case a little bit more? Why we need to set different tags (span, h4, h2) in different places? Is the usage different? if the answer is yes Why?



> Hey @sandrodw3, Could you please explain me the problem in this case a little bit more? Why we need to set different tags (span, h4, h2) in different places? Is the usage different? if the answer is yes Why?

@ealonso I thought about this solution because I found we have 21 different usages of `liferay-asset:asset-categories-selector` and each one can have different heading hierarchy. For example in users edition we have this levels, and that's why I put and `h4`.
image

But then for example in web content edition, we render the taglib inside the right sidebar, and the headings hierarchy is different, there we don't any `h2` or `h3`. 

image


That's why I thought it would make sense to decide the tag in each usage, and I put `span` as the default value for the cases in which we don't pass any tag.

If you prefer I can confirm with Marcos or Evan about this solution to see what they think, please let me know 😄

**Comment by jkappler** [comment]
@sandrodw3, looks great from backend point of view ❤️.

**Pull request closed without merging**
