### PR TITLE
LPS-133858 Fix nested lists width

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
The failure task is com.liferay.commerce.pricing.web version issue unrelated to changes in this PR. In order to save CI resource, I've sent this PR to BChan directly.
See https://github.com/brianchandotcom/liferay-portal/pull/104715

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
