### PR TITLE
LPS-200442 Categories are not displayed in alphabetical order in secondary languages

### PR DESCRIPTION
**Pull request by jkappler**
https://liferay.atlassian.net/browse/LPS-200442

Note: We cannot use an orderByComparator since we are sorting by xml field. So use a normal comparator and sort before returning the results

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Review by lfbesada — APPROVED** [review]
It works like a charm, thanks! :kissing_heart:

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
