### PR TITLE
LPS-143882 Navigation Menu is broken when an item type doesn't exists

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-143882

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
https://github.com/liferay-echo/liferay-portal/pull/6757

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Comment by ruben-pulido** [comment]
Just started reviewing :)

**Pull request closed without merging**
