### PR TITLE
[TS] LPS-169845 | Asset Publisher is not visible in Page Preview

### PR DESCRIPTION
**Pull request by bakayattila**
Hi Team,
Could you please review this pull request?
https://issues.liferay.com/browse/LPS-169845
Thank you!

-------

**Steps to reproduce:**

1. Create a Web Content
2. Create a Page
3. Place an Asset Publisher on the page
4. Configure the Asset Publisher to Dynamic Asset Selection
5. Open "Preview in a New Tab" from the top left kebab menu

**Expected behaviour:** The Asset Publisher is visible on the Preview with the web content
**Actual behaviour:** The Asset Publisher is not visible

The root cause of the issue is that the renderRequest gets the portletPrefrences for the control panel in preview mode, which does not exist. So the configured dynamic selection is not followed. I found that the themeDisplay is properly configured so I try to get the preferences from the themeDisplay -> portletDisplay connection.

### CODE REVIEW

**Comment by bakayattila** [comment]
ci:test:sf

**Comment by bakayattila** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:reevaluate:1387401_5330

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128017

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
