### PR TITLE
LPS-192878 The Home folder should be visible on selection modal

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-192878)

## Test Scenario 1
1. Add a new site
2. Navigate to the Web Content admin
3. Add some new folders
4. Add a web content inside one folder
5. Move this folder with the web content to Recycle Bin
6. Navigate to the Recycle Bin
7. Go into the folder
8. Restore the web content and check the modal
 
### This is the PR result:
 
Pasted Graphic

### This is the Figma design:

image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:stable

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
