### PR TITLE
LPS-169365 Don't persist fallback to default layout if redeployment might be in progress

### PR DESCRIPTION
**Pull request by matthiasblaesing**
With LPS-66138 a mechanism was introduced, that switches the layout for a page to the default layout if the selected layout does not exist and persists that change.

Before the change associated with that issue the switch was only transient.

This causes a regression if the following sequence happens:

1. layout template plugin is being redeployed - as one of the first steps the layout is made unavailable
2. user accesses a page configured with one of the layouts in the plugin
3. LPS-66138 change _permanently_ switches layout to default layout
4. Redeployment completes

The fix is to only apply the fix from step three if no redeployment is in flight.

The obvious way would be to listen for BundleEvents and block the fix when a STOPPING event is seen and reenable it once STARTED (redeployment) or UNINSTALLED (undeployment) is observed.

For layouts this does not work because the themes are (un-)installed by deploylisteners, that are invoked before the OSGI integration. So there is a gap between the layout template not being available and the STOPPING BundleEvent.

The fix idea is to use a ScheduledExecutor, that delays application of the layout reset (fix in step 3) for a grace period of one minute. In case a BundleEvent is received in between, all pending layout resets are rescheduled. It is assumed, that one minute is enough time, that a redeployment will run completely through.

In the referenced issue steps to reproduce are provided. This change can be tested by enabling logging on level `TRACE` for  `com.liferay.layout.taglib.internal.servlet.taglib.GuardedLayoutResetter`.

**Redeployment**

1.  Run the setup from the issue description is done (steps 1-6)
2. Remove the layout plugin by deleting it from the `osgi/war` folder and wait until it is fully undeployed (you'll find `STOPPED testlayout-layouttpl_1.0.0 [????]`  in the log
3. Open the test page in browser again (layout from plugin is not visible anymore)
4. Reinstall the layout plugin again by copying it to the `deploy` folder and wait until it is deployed again (you'll find `STARTED testlayout-layouttpl_1.0.0 [????]` in the log) (this must have happened in less than 60 seconds after step 3!)
5. Open the test page in browser again (layout is now visible again)
6. Wait for one minute - you'll find `Resetting layout to default (plid: ??, groupId: ???, privateLayout: false, layoutId: ??)` in the log. Indicating, that the layout template was found and thus no reset happened.
7. Open the test page again and you'll find, that the layout from the plugin is still configured

**Uninstalling**

1.  Run the setup from the issue description is done (steps 1-6)
2. Remove the layout plugin by deleting it from the `osgi/war` folder and wait until it is fully undeployed (you'll find `STOPPED testlayout-layouttpl_1.0.0 [????]`  in the log
3. Open the test page in browser again (layout from plugin is not visible anymore, in the page settings no layout is selected)
4. Wait for one minute - you'll find `Resetting layout to default (plid: ??, groupId: ???, privateLayout: false, layoutId: ??)` in the log. Indicating, that the layout template was found and thus no reset happened.
5. Open the test page again - layout is still the default layout, but in the page settings the default layout is now selected

So both cases work now.

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
Hi @matthiasblaesing 
Thanks for the fix!
Could you please fix the source formatting issues?
Thanks

**Comment by matthiasblaesing** [comment]
@lfbesada sorry, I did multiple rounds and cleaned up after each step and I would have sworn I ran the code formatter after the last one, but indeed, there were left over logger imports. Should be good now, update was pushed. Thank you!

**Comment by lfbesada** [comment]
Hi @matthiasblaesing 
Thanks again for the fix ❤️ 
I have changed the fix approach because it seemed to me easier to use the default layoutTemplateId in rendering but not to persist the change. In this way, I think we are handling also other cases in which there is temporary unavailability, in addition, to redeploying cases.
Please see: https://github.com/liferay-echo/liferay-portal/pull/10505
Regards

**Pull request closed without merging**
