### PR TITLE
[7.4-only] LPS-121951 Migrate v2 usages of clay:horizontal-card in layout-admin-web

### PR DESCRIPTION
**Pull request by markocikos**
Fixes https://issues.liferay.com/browse/LPS-121951

In this PR we are updating Soy-based horizontal card with Clay-based navigation card in layout-admin-web

To reproduce feature with the updated element, create a page (see gif on the bottom)

Notes:
- There is a bug with the appearance of the vertical card on top, with extra icon and extra padding on bottom. Those are bugs unrelated to this PR, [first](https://github.com/liferay/clay/pull/3816) and [second](https://github.com/liferay/clay/issues/3813).

/cc @carloslancha @julien

after

### CODE REVIEW

**Comment by markocikos** [comment]
ci:test:sf

**Comment by markocikos** [comment]
ci:test:relevant

**Review by carloslancha — APPROVED** [review]
>There is a bug with the appearance of the vertical card on top, with extra icon and extra padding on bottom.

That vertical card is a clear example of a navigation card, so we highly recommend @liferay-echo to replace it with a `<clay:navigation-card>`, that will solve the icon issue.

PR LGTM

**Comment by victorg1991** [comment]
LGTM :)

@carloslancha I've tried changing the vertical card in the screenshot to navigation card and found some issues:

- The card rendered before the react component is created is not loading the icon correctly. I think this is because getImageSrc() doesn't return null on the card model, but empty string. I guess we should change [this check](https://github.com/liferay/liferay-portal/blob/e37c8d7abb721ddd7639d183c291c3ee4dc66d75/modules/apps/frontend-taglib/frontend-taglib-clay/src/main/java/com/liferay/frontend/taglib/clay/servlet/taglib/NavigationCardTag.java#L219) to using `Validator.isNotNull()` to take into consideration those cases

- When trying to use an image instead of a icon, the image is displaying only a part of the image not rescaling it:
Screenshot 2020-11-30 at 10 58 41

Are you aware of those?

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorvalle** [comment]
Hi @victorg1991 !
Having an image there was never a requirement that is why it probably doesn't work. If you have this requirement please open a Lexi ticket so we cover that.

**Comment by victorg1991** [comment]
Thanks @victorvalle I'll talk with Juan to see if we want to go further :)

**Pull request closed without merging**
