### PR TITLE
LPS-164281 Add the InfoPermissionProvider implementation for Objects

### PR DESCRIPTION
**Pull request by lfbesada**
https://issues.liferay.com/browse/LPS-164281

Dear reviewers ❤️

This PR needs the LPS-164280 commits, those commits are waiting for Brian's review in this PR: https://github.com/brianchandotcom/liferay-portal/pull/123910.
That is the reason those commits are included here but **just the three last commits, with LPS-164281, should be reviewed here**.

@gabrielwas could you please review the first two LPS-164281 commits that are Object's related?

Thanks in advance!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
ci:stop

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by gabrielwas** [comment]
Hey @lfbesada! First, thanks for incrementing InfoFramework implementations for Objects! 
About the commits related to it, they LGTM :)

I have thus just a couple of topics here:

1 - In [this line here](https://github.com/liferay-echo/liferay-portal/pull/9794/commits/10ba94c06723c769dacbbfe642a0bc29a3105d46#diff-6267e21a2e6c38117149d6918ee68125c9df5cfa81f4bebfe221b9df0e65f150R33), is it supposed to be FileEntry or ObjectEntry?

2 - Is it ok to use *Util classes [in this case](https://github.com/liferay-echo/liferay-portal/pull/9794/commits/10ba94c06723c769dacbbfe642a0bc29a3105d46#diff-6267e21a2e6c38117149d6918ee68125c9df5cfa81f4bebfe221b9df0e65f150R45-R55)? Maybe passing the references as parameters? Just a consideration.

Thanks again!

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:reopen

**Comment by ozysouza** [comment]
The failures are unrelated to this PR. Please see https://github.com/brianchandotcom/liferay-portal/pull/124039

**Comment by ozysouza** [comment]
ci:close

**Pull request closed without merging**
