### PR TITLE
LPS-126656 | master-only

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LPS-126656

cc @david-gutierrez-mesa

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:forward

**Comment by liulukiwi** [comment]
ci:stop

**Comment by liulukiwi** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:stop

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:forward

**Comment by liulukiwi** [comment]
The failure above is not related to the changes here, so I push directly to BChan: https://github.com/brianchandotcom/liferay-portal/pull/98235

**Pull request closed without merging**
