### PR TITLE
LPS-175473 add integration test

### PR DESCRIPTION
**Pull request by Vy-CES**
Hi team, this is a follow-up according to Brian's comment here: https://github.com/brianchandotcom/liferay-portal/pull/130461#issuecomment-1435663681.

I introduce an integration test for ClientExtensionEntryRel which extends the abstract class BaseStagedModelDataHandlerTestCase.

See ticket LPS-175473 for more information.

Please review it and give me your feedback.
Thanks!

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Vy-CES** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @Vy-CES,

Could you please the source format error?

**Comment by Vy-CES** [comment]
ci:test:sf

**Comment by Vy-CES** [comment]
ci:test:relevant

**Comment by Vy-CES** [comment]
Hey @ealonso, thank you for the feedback!

I've formatted the source code and re-run the test, all seems to be good from my point of view now.

**Comment by ealonso** [comment]
Please see: https://github.com/liferay-echo/liferay-portal/pull/11285

**Pull request closed without merging**
