### PR TITLE
LPS-190122 Fix design options url to go to the published layout configurations

### PR DESCRIPTION
**Pull request by Mikellorza**
Fix impedibug : https://liferay.atlassian.net/browse/LPS-190122

cc: @sandrodw3

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @Mikellorza, the configuration page is empty when access via Page Design Options
**Step to reproduce**

1. Add a new site
2. Add a content page
3. Navigate to the Page Design Options panel
4. Click the cog icon

**Expected Results:**
The user could access to the configuration page

**Actual Results:**
The configuration page is empty.

**Comment by Mikellorza** [comment]
> Hi @Mikellorza, the configuration page is empty when access via Page Design Options **Step to reproduce**
> 
> 1. Add a new site
> 2. Add a content page
> 3. Navigate to the Page Design Options panel
> 4. Click the cog icon
> 
> **Expected Results:** The user could access to the configuration page
> 
> **Actual Results:** The configuration page is empty.

Hi @Tim-Cao ,

I reproduce the problem and now It is fixed.  I forgot to add the FF. 

Thanks !

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by alessandromalves** [comment]
ci:forward:force

**Comment by alessandromalves** [comment]
The failures are not related to this PR [(see comparison with acceptance routine)](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1689078182339&testrayRunIdA=2372452216&testrayRunIdB=2377871499). See https://github.com/brianchandotcom/liferay-portal/pull/137670

**Pull request closed without merging**
