### PR TITLE
LPS-135009 - Remove pagination parameters from URL when entering edit mode since they may be outdated after publishing

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso @jkappler

### CODE REVIEW

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:test:sf

**Comment by ruben-pulido** [comment]
ci:test:relevant

**Comment by ruben-pulido** [comment]
ci:stop

**Comment by ruben-pulido** [comment]
@ealonso's feedback incorporated [here](https://github.com/liferay-echo/liferay-portal/pull/5064)

**Pull request closed without merging**
