### PR TITLE
LPS-158430 Use InetAddressUtil#getInetAddressByName to make use of dn…

### PR DESCRIPTION
**Pull request by vendeltoreki**
Dear @liferay-echo Team,

I'm forwarding pull request https://github.com/liferay-staging/liferay-portal/pull/88 to you.

Please review the changes.

Thanks,
Vendel

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
