### PR TITLE
LPS-178747 Adapt Master Page and Style Book selectors

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://issues.liferay.com/browse/LPS-178747)

## Steps 

1. Go to Product Menu > Pages
2. Select kebab of Search Page or any Widget Page > Configure
3. Go to look and feel > Master Page and Style Book sectio
Screenshot 2023-03-17 at 12 27 10
n

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by DiegoHu97** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by alessandromalves** [comment]
Just started reviewing :)

**Comment by alessandromalves** [comment]
The reported failures will only require a fix at the tests

**Pull request closed without merging**
