### PR TITLE
LPS-201623 Revert "LPS-200805 Removes LPS-180328 Feature Flag" since we want to keep it at least one more version

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
Hi @ealonso, Could you fix this test? Thanks
[com.liferay.exportimport.test.LayoutSetPrototypePropagationTest](https://testray.liferay.com/home/-/testray/case_results/2462282449)

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Hey @Tim-Cao,

It is working locally, so I'm going to run tests again

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
