### PR TITLE
LPS-122611 Use map to store the TempFiles with their corresponding FileEntries. In this sense we also avoid duplications and improve performance

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@Tim-Cao, this is the PR for the "blocker"

**Comment by brianchandotcom** [comment]
@jkappler I merged this and backported this to 7.3.x.

See af9dd5996e4b37dec71ed33b942bb647b031603a

**Comment by jpince** [comment]
ci:close, fix was merged to master and backported to 7.3.x (see LPS ticket). @Tim-Cao please let us know if you see any regressions caused by this bug fix in the automation test results.

**Comment by Tim-Cao** [comment]
@jpince Sure!

**Pull request closed without merging**
