### PR TITLE
LPS-147396 Enable hiding fragments from search

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
@sandrodw3 @ealonso frontend looks good :) One thing to mention is that it also hides the content from the page administration, apart from the site search that the story mentions. I assume that is intended right?

**Comment by victorg1991** [comment]
Also, since the API doesn't tell anything this will only work with our implementation of the LayoutCrawler, we have to make sure to mention this in the documentation :)

**Comment by sandrodw3** [comment]
> Also, since the API doesn't tell anything this will only work with our implementation of the LayoutCrawler, we have to make sure to mention this in the documentation :)

Ok! I'll mention it, thanks 🥰

**Comment by sandrodw3** [comment]
> @sandrodw3 @ealonso frontend looks good :) One thing to mention is that it also hides the content from the page administration, apart from the site search that the story mentions. I assume that is intended right?

Um, I guess we can ask our PMs about this tomorrow

**Comment by sandrodw3** [comment]
@ealonso I have renamed `nonindexable` to `nonindexed` as I assumed it was not intended, but could you please take a look? I also fixed all tests locally, I hope they pass this time

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/7620

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
