### PR TITLE
LPS-142093

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-142093

/cc @javalosjr96

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/6364

**Pull request closed without merging**
