### PR TITLE
LPS-171977 - Pages Tree loses selected page after navigating to it

### PR DESCRIPTION
**Pull request by ruben-pulido**
//cc @ealonso

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ruben-pulido** [comment]
ci:forward

**Comment by ruben-pulido** [comment]
Solving conflicts in https://github.com/brianchandotcom/liferay-portal/pull/128316

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Hi @ruben-pulido, would you mind checking the compile issue? apps:layout:layout-impl:compileJava FAILED

**Comment by ruben-pulido** [comment]
Thanks for the heads up @Tim-Cao 
Fixed here: https://github.com/liferay-echo/liferay-portal/pull/10833

**Pull request closed without merging**
