### PR TITLE
LPS-120733 Reset orderByCol to null when Web Content Display is accessed

### PR DESCRIPTION
**Pull request by SamZiemer**
Notes from @noornajj
> https://issues.liferay.com/browse/LPS-120733
> 
> The issue here was that the value of the orderByCol preference was retaining the last selection the user made. Therefore, the default value is not always set correctly.
> To fix the issue, first I had to delete the line in getSearchActionURL() that sets the orderByCol parameter because it was preventing the preference from being assigned a default value. Next, I had to reset the orderByCol preference to null after the user is finished with search because, even after the default value is assigned, this line 
> `_orderByCol = _portalPreferences.getValue(
> 				JournalPortletKeys.JOURNAL, "order-by-col", defaultOrderByCol);`
> will override the default value with the previous value that was selected by the user.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/2430

**Pull request closed without merging**
