### PR TITLE
LPS-190005 Replace aui:button with clay:button in asset-taglib module

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
The motivation behind this PR stadirize the usages of buttons in the portal by using for clay:button or clay:icon.
https://liferay.atlassian.net/browse/LPS-190005

Proposed Solution
========
The proposed solution consist in substitute the usages of aui:button for clay:button o clay:icon.

Steps to Verify
========
First create a DPT for Blogs: 
Design -> Page Templates -> Display Page Templates -> create one for blogs

Second create a blog and add it to the DPT:
Product Menu -> Content & Data -> Blogs -> create a new blog -> Display Page Template section -> choose specific and a select button appears -> check that the button is working correctly

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Stephy6** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
