### PR TITLE
LPS-195216 Not-needed H1 in home fragment page

### PR DESCRIPTION
**Pull request by veroglez**
https://liferay.atlassian.net/browse/LPS-195216

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
poshi tests should be updated

**Comment by david-gutierrez-mesa** [comment]
Test fix here https://github.com/liferay-echo/liferay-portal/pull/13926

**Comment by david-gutierrez-mesa** [comment]
ci:close

**Pull request closed without merging**
