### PR TITLE
LPS-185241 No experience selected in experience selector when the experience does not exist

### PR DESCRIPTION
**Pull request by Mikellorza**
Bug: https://issues.liferay.com/browse/LPS-185241

Description
----
Fix the bug showing as selected the default segments experience when the selected segments experience does not belong to the page or it does not exist

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
