### PR TITLE
LPS-112196

### PR DESCRIPTION
**Pull request by dacousalr**
Hi team, this PR reduces the amount of duplicate CSS and JS resources of the widgets included in fragment-based pages in edit mode. This does not fulfill all the LPS-106098 requirements although it represents a step forward. \cc @dsanz @ealonso

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
see https://github.com/liferay-echo/liferay-portal/pull/411

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
https://github.com/liferay-echo/liferay-portal/pull/412

**Pull request closed without merging**
