### PR TITLE
LRQA-64008 | master

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LRQA-64008

This is only for master, thanks!

 cc @david-gutierrez-mesa

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
ci:forward

**Comment by liulukiwi** [comment]
Will rerun after maintenance :(

**Comment by liulukiwi** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
