### PR TITLE
LPS-116769 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-116769

This is only for master.

@victorg1991
@sandrodw3
@manoelcyreno

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:close

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/91191

**Pull request closed without merging**
