### PR TITLE
LPS-123126 Remove mapping information when selecting an image

### PR DESCRIPTION
**Pull request by p2kmgcl**

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
Hi @p2kmgcl, two suggestion. One is the source selection field doesn't have field label.
ImageSource
Could you have a look at Container's? Make them consistent, For example, label named Image Source, the option is Manual Selection and Content Mapping not Direct and Mapping.
The second one is the Mapping of Banner Center fragments left.
BannerCenter

**Comment by p2kmgcl** [comment]
@Tim-Cao I'm going to check this with Juan :sweat_smile:

**Comment by p2kmgcl** [comment]
I still need to update the corresponding labels according to the ticket description

**Comment by p2kmgcl** [comment]
@Tim-Cao it should be ready to test

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
Peek 2020-11-17 13-10

**Comment by Tim-Cao** [comment]
Just start reviewing

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/2928

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
