### PR TITLE
LPS-122451 We also need to add article's id to the URL in case some version was already published

### PR DESCRIPTION
**Pull request by antonio-ortega**
Hi guys,

Can you review this pull request, please?

This is coming from [this change](https://github.com/liferay-echo/liferay-portal/pull/971/commits/abea9d01b693c101e59c82308bd0f1fc484baee9) in [LPS-114648](https://issues.liferay.com/browse/LPS-114648) and it is causing the issue described in [LPS-122451](https://issues.liferay.com/browse/LPS-122451).

Thanks.

Regards.

/cc @dacousalr

### CODE REVIEW

**Comment by antonio-ortega** [comment]
ci:test:sf

**Comment by antonio-ortega** [comment]
ci:test:relevant

**Comment by pavel-savinov** [comment]
Just started reviewing :)

**Comment by pavel-savinov** [comment]
ci:close

**Comment by pavel-savinov** [comment]
@antonio-ortega Resent here https://github.com/liferay-echo/liferay-portal/pull/2702

**Pull request closed without merging**
