### PR TITLE
LPS-197353 Multiple AssertionErrors in TaxonomyVocabularyResourceTest

### PR DESCRIPTION
**Pull request by Mikellorza**
This is a temporal solution until headless team take into account the global resources in the test generation using buildRest gradle task. 
 
bug: https://liferay.atlassian.net/browse/LPS-197353

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by jkappler** [comment]
@Mikellorza, better not delete. There might be other tests that use them, such as poshi tests

**Comment by Mikellorza** [comment]
ok @jkappler , no problem. I will override each failing test

**Comment by Mikellorza** [comment]
Hi @jkappler ,

I made some changes. I have overwritten each failing test.

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
hey @jkappler ,

Take a look when you have time to this temporal solution until the headless team fix the issue in a correct way.

**Comment by jkappler** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/142812

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
