### PR TITLE
LPS-121859 Migrate v2 usages in asset/asset-browser-web

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

**Test plan**:
- Navigate to **Content & Data** > **Blogs**
- Create a new Blog Entry and publish it
- Navigate to **Content & Data** > **Web Content**
- Create a new Web Content
- In the sidebar on the right, scroll down and click on the **Related
Assets** button, and select **Blog Entry**
- In the modal window, select the Blog Entry you created previously
- Assert that the Blog Entry you selected is visible in the **Related
Assets** section

### CODE REVIEW

**Comment by julien** [comment]
cc @ambrinchaudhary @markocikos @jonmak08

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by p2kmgcl** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
