### PR TITLE
LPS-160041 Add scroll to FragmentsSidebar 

### PR DESCRIPTION
**Pull request by veroglez**
cc @p2kmgcl

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by veroglez** [comment]
ci:test:sf

**Comment by veroglez** [comment]
Hi @p2kmgcl! I added several commits related to the styles of the tabs when scrolling. Also, I made a change to your pull by removing [this `d-flex`](https://github.com/liferay-echo/liferay-portal/pull/9339/commits/e4225d82ece5a4ba50e39152e484f8b4a2a4b0bd) . A priori I didn't see that it was necessary, in fact it was causing the structure tree to not have the full width of the sidebar. If this `d-flex` is necessary, please let me know.

**Comment by veroglez** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1277401_4533

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:reevaluate:1377401_4294

**Comment by ealonso** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:forward

**Comment by david-gutierrez-mesa** [comment]
ci:stop

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by david-gutierrez-mesa** [comment]
Sending manually since failures are not related to changes in this PR. See https://github.com/brianchandotcom/liferay-portal/pull/121878

**Comment by david-gutierrez-mesa** [comment]
ci:close

**Pull request closed without merging**
