### PR TITLE
LPS-140026 Remove class

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by ealonso** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by veroglez** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/6043

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
