### PR TITLE
LPS-121901 Migrate v2 usages in portlet-configuration/portlet-configuration-web

### PR DESCRIPTION
**Pull request by julien**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

**Test plan (1)**:

- From the global menu, select the **Control Panel** tab
- Navigate to **Users and Organizations**
- Click on the dropdown menu to the right of a user name and select
**Permissions**
- In the modal window, make sure you can change and filter Permissions

**Test plan (2)**:

- On the **Home** page, click on the **Navigation Menu** and select
**Configuration Templates**
- In the modal window, click on **Save Current Configuration as
Template**
- From the management toolbar select one or more template configuration
and asset you can delete them

### CODE REVIEW

**Comment by julien** [comment]
cc @ambrinchaudhary @markocikos @jonmak08

**Comment by julien** [comment]
ci:test:sf

**Comment by julien** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:forward

**Comment by julien** [comment]
@victorg1991 looks like "ci:forward" didn't actually work - please let me know if you need help - thanks!

**Comment by victorg1991** [comment]
ci:forward

**Pull request closed without merging**
