### PR TITLE
LPS-132152 Look for collection ancestor only if the editable is mapped to a collection and use masterLayoutData or layoutData depending if the fragment belongs to the master page

### PR DESCRIPTION
**Pull request by victorg1991**

### CODE REVIEW

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
Sandro asked me to foward this. He is happily walking with this dog ATM 🐶

**Comment by victorg1991** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
