### PR TITLE
LPS-191350 Lock the Draft by the user at the first autosave

### PR DESCRIPTION
**Pull request by lfbesada**
https://liferay.atlassian.net/browse/LPS-191350

Dear reviewer 👋

Thanks in advance for your review ❤️

This PR implements:

- When a user tries to perform an action over a draft layout, we will check if the layout is locked by this user.
- In case the user hasn't already the lock, then we will check if the draft isn't locked by another user, in wich case we will try to get the lock for this user.
- If the user already has the draft lock or gets the draft lock successfully then the action is performed.
- If the user can't get the lock for any reason (commonly is already locked by another user) or lose the lock during the action perform, then the user is redirected to the blocked page view.

The lock acquire process is implemented here but we still need to use scripts to unlock the draft. In addition, to be able to test it, the feature flag must be enabled:
feature.flag.LPS-180328=true

These scripts are useful to test this PR:

Script to lock a draft by a user
[LockLayout.txt](https://github.com/liferay-echo/liferay-portal/files/12208679/LockLayout.txt)

Script to see the status of a draft (locked/unlocked) with respect to all the users of the company
[isUnlockedLayout.txt](https://github.com/liferay-echo/liferay-portal/files/12208680/isUnlockedLayout.txt)

Script to unlock a draft
[UnlockLayout.txt](https://github.com/liferay-echo/liferay-portal/files/12208681/UnlockLayout.txt)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by lfbesada** [comment]
cc: @p2kmgcl @sandrodw3 Thanks a lot for your help 🌟 ❤️

**Comment by Tim-Cao** [comment]
Failure are unrelated to changes.

**Comment by lfbesada** [comment]
Hi @jkappler 
Thank you very much for your feedback ❤️ 
I have added it, could you please take a look?
Thanks!

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@lfbesada

**Comment by lfbesada** [comment]
ci:forward

**Comment by lfbesada** [comment]
ci:forward:force

**Pull request closed without merging**
