### PR TITLE
LPS-171953 Replace liferay-ui:icon in view_container_model.jsp

### PR DESCRIPTION
**Pull request by BarbaraCabrera**
## Test Scenario

1. Navigate to Content and Data > Web Content.
2. Create a folder with a Web content into it.
3. Delete the folder.
4. Go to Recycle Bin > Recycle Bin.
5. Look for the Web content that you added in the folder on the Search Bar.
6. You should see the result as: _"Web Content Name"_ + Found in deleted folder + _"Folder Name"_ (as a link) 
image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by BarbaraCabrera** [comment]
ci:test:sf

**Comment by veroglez** [comment]
Works perfectly!! just one thing, is it possible to replace the message `(Found in deleted folder x .)` by `(Found in deleted folder x).`?

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
