### PR TITLE
LPS-195749 Fix "Cannot delete the new pages variation and site pages variation"

### PR DESCRIPTION
**Pull request by DiegoHu97**
[Link to ticket](https://liferay.atlassian.net/browse/LPS-195749)

ezgif com-video-to-gif

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:test:stable

**Comment by gaborlovasdotcom** [comment]
ci:test:staging

**Comment by rafaellajordao** [comment]
Hi @DiegoHu97,
Analyzing the failures of the relevant I found two tests failing and are suspicious, can you take a look?

modules-compile-jdk8/0/7 - [Jenkins Console](https://testray.liferay.com/reports/production/logs/2023-09/test-1-32/test-portal-acceptance-pullrequest(master)/1978/modules-compile-jdk8/0/7/jenkins-console.txt.gz?authuser=0)

js-unit-jdk8/0/0 - [Jenkins Console](https://testray.liferay.com/reports/production/logs/2023-09/test-1-32/test-portal-acceptance-pullrequest(master)/1978/js-unit-jdk8/0/0/jenkins-console.txt.gz?authuser=0)

**Comment by ealonso** [comment]
Hey @rafaellajordao,

Those failures should not be related, we only changed two jsps files on staging-bar-web module.

**Comment by rafaellajordao** [comment]
Perfect @ealonso, I'll pass it on manueally! Thank you!

**Comment by rafaellajordao** [comment]
The failures are not related to this PR [(comparison with acceptance routine here)](https://testray.liferay.com/home/-/testray/runs/compare?formDate=1694460709642&testrayRunIdA=2422051148&testrayRunIdB=2420185341). See https://github.com/brianchandotcom/liferay-portal/pull/140563

**Comment by rafaellajordao** [comment]
ci:close

**Pull request closed without merging**
