### PR TITLE
LPS-172282 Change the Field Name and Option Value based on the Field and Option Reference in Web Content Structures

### PR DESCRIPTION
**Pull request by carolmariaabb**
**Context:**
https://issues.liferay.com/browse/LPS-172237

Allow users to easily update the `DDMFormField -> name` by copying the same value from the `DDMFormField -> fieldReference`. This behavior should also be applied to `options`.

**Previous PR**: https://github.com/liferay-forms/liferay-portal/pull/2101

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by Tim-Cao** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/128956

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
