### PR TITLE
LPS-164257, LPS-165673 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LPS-164257
https://issues.liferay.com/browse/LPS-165673

@veroglez
cc @ozysouza

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:echo

**Comment by Tim-Cao** [comment]
Hi @ozysouza, would you mind keeping working on this one? Thanks!

**Comment by veroglez** [comment]
Hi @Tim-Cao, I have resolved the impedibug related to this https://issues.liferay.com/browse/LPS-164257. Could you check it and verify if everything is ok?

See https://github.com/liferay-echo/liferay-portal/pull/9990

**Pull request closed without merging**
