### PR TITLE
LPS-162764 Use the desired languageId to calculate friendlyURL template contextObject

### PR DESCRIPTION
**Pull request by balazssk**
Motivation
=======
[LPS-162764](https://issues.liferay.com/browse/LPS-162764)
ThemeDisplay might not be correctly set up in remote calls of getContent. Using the parameter `languageId` would 100% match the content's languageId.

Proposed Solution
========
Use the input parameter `languageId` to identify the current translation's friendlyURL.

Steps to Verify
========
1. Create a new Web Content Structure with a Text field
2. Create a Template for this structure: add the Text field and ${friendlyURL} to it
3. Create a Display Page Template for this Web Content Structure and set it as default
4. Create a Web Content from the Structure
5. English translation: title: en, content: en, friendlyURL: en
6. French translation: title: fr, content fr, friendlyURL: fr
7. Publish
8. Edit the Web Content again and check the right side menu > Basic Information > ID. Save this value, it will be used in the script as articleId
9. Go Configuration > Site Settings and select Site Configuration
10. Save the value of Site Id, it will be used in the script as groupId
11. Go to Control Panel > Server Administration, Script
12. Set the copied articleId and groupId in the following script and run it:

```
import com.liferay.journal.service.JournalArticleLocalServiceUtil;
import com.liferay.portal.kernel.service.ServiceContextThreadLocal;
import com.liferay.portal.kernel.theme.ThemeDisplay;

long groupId = 20121;
String articleId = "";

article = JournalArticleLocalServiceUtil.fetchArticle(groupId, articleId);
serviceContext = ServiceContextThreadLocal.getServiceContext();
			
ThemeDisplay themeDisplay = serviceContext.getThemeDisplay();

themeDisplay.setLanguageId("en_US");
themeDisplay.setScopeGroupId(groupId);

try {
	out.println(JournalArticleLocalServiceUtil.getArticleContent(
		article, null, null, "fr_FR", null, themeDisplay));
}
catch (Exception e) {
	e.printStackTrace(out);
}
```
**Expected behaviour:** French content is displayed with French friendlyURL (http://localhost:8080/w/fr)
**Actual behaviour:** French content is displayed with English friendlyURL (http://localhost:8080/w/en)

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
