### PR TITLE
LPS-199891 Hide folder selection when setting structure default values

### PR DESCRIPTION
**Pull request by JavierMoral**
Previously sent #14093 

Motivation
=======
Fix for [LPS-199891](https://liferay.atlassian.net/browse/LPS-199891)

[LPS-133629](https://liferay.atlassian.net/browse/LPS-133629) added the capacity to select a folder when adding a new web content from the asset publisher widget. This folder selector is being shown (I think unintentionally) when editing the default values of a structure.

The aim of this pr is to hide this selector in the mentioned use case.

Proposed Solution
========
As suggested in #14093 I'm changing the logic of isShowSelectFolder() to check the classNameId and identify the case in which default structure values are being created

Steps to Verify
========
1. From Web Content Administration, go to structures and create simple structure (in my case with text field)
1. In the structure go to the three dots and select Edit Default Values

- **Expected behavior**
In web content edit page, the folder selector is not shown

- **Actual behavior**
In web content edit page, the folder selection is shown

image

### CODE REVIEW

**Comment by liferay-echo** [comment]
Thank you for submitting this PR. 👏

Make sure it follows the [Echo Pull Request Template](https://gist.github.com/liferay-echo/5a4455285ff1800f9da146816d85e67d#file-pull-request-template-md) if you haven't already done so. 

Learn more about it [here](https://liferay.atlassian.net/wiki/spaces/ENGECHO/pages/2027455014/Echo+Pull+Request+Etiquette).

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
